### ISSUE TITLE
GC3 r200 and earlier: Evolved Skeletons are using the old GC1 ranged attack system

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#1047]
In GC1, Evolved Skeletons used to shoot 2 arrows per second, those arrows were slower and "heavier" with short range. In GC2, Evolved Skeletons were like those on the Overworld, just their arrows weren't less effected by the gravity (= lesser descent curve), sort of.

In GC3, the GC1 ranged attack is back. *(Personally I prefer the GC2 system :x)*

**Comment by EzerArch** [comment]
I think this could be closed if intended.

**Comment by micdoodle8** [comment]
I implemented a new method in the latest build. Feedback welcomed.
