### ISSUE TITLE
Gravity bug can jump on a non-solid block

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#1073]
Gravity Bug Step to reproduce
Please test on Moon, Mars or Asteroids
1. Place non-solid block ex. Button, Tallgrass
2. Jump on it
3. You can jump on the Button or Tallgrass

**Comment by radfast** [comment]
As @BlesseNtumble has shown on #2114, you can also jump on the surface of liquids in low gravity dimensions.
