### ISSUE TITLE
Sealable Oxygen pipes often fail to pass oxygen

### ISSUE THREAD

**Issue by SquareWheel** [micdoodle8/Galacticraft#1085]
I've noticed that when using Oxygen Sealers, they don't connect reliably to sealable oxygen pipes.  Swapping them out for regular oxygen pipes fixes this.  I also tested swapping them out for another sealable oxygen pipe (to "renew" the connection), but that didn't work either.  Once I replace it with a regular oxygen pipe the machine fills instantly, like it had been building up a buffer.

To clarify, when I say "connect" I mean they don't pass oxygen as expected.  They visibly connect just fine.  I've not had any issues with power cables, sealable or otherwise.

Latest stable Galacticraft in custom pack (about 50 mods).  Would be happy to list them if relevant.  Unfortunately there's no crash log to provide in this instance.

**Comment by EzerArch** [comment]
http://youtu.be/usfiAsWR4qU?t=16s

**Comment by radfast** [comment]
lolz
