### ISSUE TITLE
GC3 r210: [Aesthetics] Limbs spazzing out in space station dimension

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#1102]
Low priority. Totally Aesthetics.

Limbs, specially the legs, shake a bit if you are moving "mid-air". The intensity depends on the speed when you walk off a platform or move around.

* **Video:** http://www.twitch.tv/ezerarch/b/575590820?t=18s

**Comment by radfast** [comment]
This should be fixed in next build.
