### ISSUE TITLE
[3.0.4] Water and sludge render odd together

### ISSUE THREAD

**Issue by EoD** [micdoodle8/Galacticraft#1111]
If you drop a bucket of water close to sludge, the water seems to be attracted by the sludge and flows "towards" it. It also stays if you have removed the water sourceblock.
It's pretty hard to describe.

![Large](https://cloud.githubusercontent.com/assets/293499/4569020/174ce9da-4f43-11e4-8433-a9079d659653.png)

![Small](https://cloud.githubusercontent.com/assets/293499/4569021/18190cfe-4f43-11e4-8ff6-b05d7c20df34.png)

In both screenshots, the water source block has been removed.

**Comment by radfast** [comment]
Fixed in next build, thank you for raising.
