### ISSUE TITLE
GC3 r213: Mars Dungeons generation without boss room and other minor problems

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#1126]
1. Still some dungeons are generated without boss room (see minimap at the bottom, 1st pic);
2. Sometimes hallways are blocked, you have to open a hole to proceed;
3. Feature? The dungeon entrance is generated without the "disc" of exposed rock for better visibility (compare 2nd pic with [this](http://wiki.micdoodle8.com/wiki/File:Mars_dungeon_entrance.png)).

![2014-10-10_04 28 47](https://cloud.githubusercontent.com/assets/6743303/4605918/4523ee12-5204-11e4-9332-51c24cdb4bbc.png)
![2014-10-10_04 35 27](https://cloud.githubusercontent.com/assets/6743303/4605917/4522f656-5204-11e4-847c-29dfd1726a77.png)

**Comment by micdoodle8** [comment]
So, this issue is very old, but do you remember if there was any pattern to the dungeon issues? I'm not seeing any myself, but I could be missing something that you noticed.

**Comment by EzerArch** [comment]
I've created 2 worlds and explored 6 dungeons :
* 4 were 100% okay
* 1 haven't found any problem, except a hallway with stone wall at chunk border, probably it's a feature since it's pretty common to find hallways with exposed rock and sometimes connected with caves:
![2015-04-04_11 24 05](https://cloud.githubusercontent.com/assets/6743303/6993128/b49750d2-dac0-11e4-952c-dd3591e02f46.png)
* 1 without boss room:
![2015-04-04_12 50 00](https://cloud.githubusercontent.com/assets/6743303/6993444/8f305018-dacb-11e4-8ffd-58a49eabce93.png)


> So, this issue is very old, but do you remember if there was any pattern to the dungeon issues? I'm not seeing any myself, but I could be missing something that you noticed.

I can't tell if there's a pattern. You can explore the dungeon ```/seed 6570215269621266590``` ```/tp @p -1150 30 -776```. It seems the 3rd room before the treasure room is a "failed" boss room (see next pic), which is **too** close this room (I opened a hole in the wall to show it).

![2015-04-04_13 22 56](https://cloud.githubusercontent.com/assets/6743303/6993537/dafd3eaa-dacd-11e4-894e-757bd5511650.png)

**Comment by micdoodle8** [comment]
Fixed in the latest build for 1.8.9
