### ISSUE TITLE
Tooltips in energy storage overlap when charging an item

### ISSUE THREAD

**Issue by EoD** [micdoodle8/Galacticraft#1130]
You should probably disable the tooltip overlay when an item is in the slot. 
I would also disable it for the case in #840 .

![2014-10-12_20 05 03](https://cloud.githubusercontent.com/assets/293499/4607086/15535376-5240-11e4-9b17-5c79cdee6ec9.png)

**Comment by help132** [comment]
You creators of galacticraft ... this mod is very good but even on that I wanted to talk more about the mod ... good will it would be good to add , the climates of other planets , would also be good to add , very resistant minerals such as titanium to make a tough maroon to go in mercury or other planets that have a very strong climate as Jupiter a gaseous planet, venus a hot planet and great pressure, neptune with strong, icy winds , and also the Saturn 's moons and others ... I know that talk is easy but could do it please, I admire your efforts.

**Comment by radfast** [comment]
https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md
