### ISSUE TITLE
[3.0.5] Telemetry Unit + Display screen rendering issue

### ISSUE THREAD

**Issue by EoD** [micdoodle8/Galacticraft#1140]
1. Skin is not rendered.
2. Thermal padding should be rendered 0.01f above the screen, such that it doesn't overlap (Imho it should not be rendered at all). The thermal padding is not seen by other players on a SMP server.
3. Text is overlapping the picture (should be much more to the right/centered imho)

The idea is great, I love it so much! ;-)

![2014-10-13_18 23 34](https://cloud.githubusercontent.com/assets/293499/4616632/c161b1c0-52f5-11e4-963f-c84cee290f1b.png)

**Comment by alexjamespeter** [comment]
i cant seem to link myself to the Telemetry Unit

**Comment by dj3520** [comment]
Can you describe the problem in more detail?

**Comment by EzerArch** [comment]
> Can you describe the problem in more detail?

Let me try:

1. Place a Telemetry Unit
2. Place a Display Screen
3. Right-click the Frequency Module on the Telemetry Unit
4. The game says "First I'll need to track an entity with that Frequency Module! (Or try wearing it!)"
5. Put the Frequency Module on.
6. Right click the Display Screen to show the Link mode
7. Display Screen says "No link".
8. *sigh*

**Comment by dj3520** [comment]
Ok just making sure it was done the same way I successfully did it with 350
on my server. For me the link resets after a chunk load.
