### ISSUE TITLE
Block screen display translation and some GUI translation doesn't work properly

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#1167]
![2557-10-15_23 13 29](https://cloud.githubusercontent.com/assets/6128413/4688980/042b2aa2-569f-11e4-89b3-6a8b0c10b305.png)
![2557-10-15_23 04 42](https://cloud.githubusercontent.com/assets/6128413/4688981/04595850-569f-11e4-8654-10326f153948.png)
![2557-10-15_23 05 08](https://cloud.githubusercontent.com/assets/6128413/4688982/04627390-569f-11e4-9439-3fcbf2bb88ae.png)
![2557-10-15_23 09 20](https://cloud.githubusercontent.com/assets/6128413/4688983/0484e2f4-569f-11e4-96af-ed50dd031f7c.png)
![2557-10-15_23 10 16](https://cloud.githubusercontent.com/assets/6128413/4688984/048b3500-569f-11e4-8990-c00805a92b9f.png)
![2557-10-15_23 10 54](https://cloud.githubusercontent.com/assets/6128413/4688986/04933b4c-569f-11e4-90a1-d57ff9ef7c69.png)
![2557-10-15_23 12 38](https://cloud.githubusercontent.com/assets/6128413/4688985/049099be-569f-11e4-9fe2-7b2764e746d7.png)

And this space race GUI and slimeling name translations doesn't work.
![2557-10-15_23 37 47](https://cloud.githubusercontent.com/assets/6128413/4688987/22303d80-569f-11e4-9010-ac8ea1cf774c.png)
![2557-10-15_23 40 05](https://cloud.githubusercontent.com/assets/6128413/4688988/223723ca-569f-11e4-9b5d-0291e48dc920.png)

**Comment by radfast** [comment]
Space Race and Slimeling are fixed thanks to @ErrorCraftLP.

See also https://github.com/micdoodle8/Galacticraft/commit/a8387b5816b80577c46a2594ad5337d0f05365e4

**Comment by SteveKunG** [comment]
![2559-02-13_12 59 56](https://cloud.githubusercontent.com/assets/6128413/13026213/5faf94b4-d252-11e5-8983-008cf2674a03.png)
![2559-02-13_13 00 00](https://cloud.githubusercontent.com/assets/6128413/13026214/600f75d2-d252-11e5-9170-38b0771847cd.png)
![2559-02-13_13 00 40](https://cloud.githubusercontent.com/assets/6128413/13026215/6015e0f2-d252-11e5-8a0b-299c6d567e64.png)
![2559-02-13_13 02 05](https://cloud.githubusercontent.com/assets/6128413/13026216/601a308a-d252-11e5-8405-4e54f6d67404.png)
![2559-02-13_13 04 33](https://cloud.githubusercontent.com/assets/6128413/13026217/601f838c-d252-11e5-8ccc-3f132abc5721.png)

Fixed at all except "No link" translation.

![2559-02-13_13 05 11](https://cloud.githubusercontent.com/assets/6128413/13026223/7c7ad388-d252-11e5-95a9-9275c63bd88a.png)

**Comment by radfast** [comment]
ok thank you.  We can fix 'No link'.  :)
