### ISSUE TITLE
GC3 r228: Space Race Manager opens without user request

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#1180]
The Space Race Manager keeps opening without user request (via Game Menu) after the player death and after world reload.

**Video:** http://www.youtube.com/watch?v=fpnIJY8SkOM&t=19m15s (oh, that was anti-climatic)

**Comment by micdoodle8** [comment]
Fixed the "on-respawn" space race manager opening.

In the future, I will add a per-world option to "not open again".
