### ISSUE TITLE
Biome Moon on overworld?

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#1190]
![2557-10-30_21 31 49](https://cloud.githubusercontent.com/assets/6128413/4857638/fd2cdbea-60d2-11e4-989b-f47eb714aad2.png)

I installed with Mods.
BiomesOPlenty-1.7.10-2.1.0.1004-universal
GalacticraftCore-BETA-1.7-3.0.5.229
Galacticraft-Planets-BETA-1.7-3.0.5.229
More-Planet's-BETA-1.7.10-1.0.4.Dev

Coordinate X Y Z : Please follow in the picture.
Seeds : 1989408553

**Comment by SteveKunG** [comment]
http://pastebin.com/4tj0Lrya

![2558-01-01_15 32 09](https://cloud.githubusercontent.com/assets/6128413/5592080/628d6d28-91e4-11e4-9ee0-827b0618816b.png)

That not work. T_T

**Comment by radfast** [comment]
I think this is likely a biome ID conflict.

Biome IDs are configurable in Galacticraft, so you just need to find one which is not taken.  Biomes o' Plenty takes a lot.  __It's best to configure this before you create a world__.  There's nothing more we can do about this.  See also:
https://github.com/MinecraftForge/MinecraftForge/issues/1704
