### ISSUE TITLE
Arrow "destroy" rockets.

### ISSUE THREAD

**Issue by BlesseNtumble** [micdoodle8/Galacticraft#1213]
If you shoot a bow in a rocket standing on the platform, the rocket breaks and drop out.

http://2.firepic.org/2/images/2014-11/06/o8z3drey8i0r.png
http://2.firepic.org/2/images/2014-11/06/kaypr0lbntzs.png
http://2.firepic.org/2/images/2014-11/06/thxlubjk4m38.png
http://2.firepic.org/2/images/2014-11/06/bz6jzmuzb0ha.png
http://2.firepic.org/2/images/2014-11/06/kjox4egm4y86.png
http://2.firepic.org/2/images/2014-11/06/8hzk0wlzsvp5.png

**Comment by radfast** [comment]
See also:
http://forum.micdoodle8.com/index.php?threads/moon-landers-despawn.5085/#post-36937

Looks like arrows destroy moon landers too.  I think there is probably a fairly easy solution to this.

(By the way, the way vanilla minecarts work is if you hit them 3 or 4 times quickly, they break, but if you hit them once then leave it for a bit, you can keep doing that indefinitely - the game code has them "heal"!)

**Comment by radfast** [comment]
Should be fixed in .299.  Players can still destroy rockets of course.
