### ISSUE TITLE
Space Station Bug

### ISSUE THREAD

**Issue by Larrer45** [micdoodle8/Galacticraft#1218]
In my modded lets play I have made a space station. The space station was fine until the other day. When I used a Mekanism Teleporter to go back there every block was just black. The glass was still see-through, but every other block was dark except for inverted lamps from Project-Red

**Comment by goldomenso** [comment]
For all the other players that have this problem I think its because you have night vision on. After I took off my nightvis goggles it fixed itself. also I know this is a necropost.

**Comment by radfast** [comment]
Necro is fine on Github issues, plenty of people still come to these old issues from Google
Thank you for the info!
