### ISSUE TITLE
GC3 r232: Cryogenic chamber requires a space brigger that its own size, and may destroy blocks

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#1228]
The Cryogenic chamber is 3 blocks tall and 1 block wide, but it requires 4 x 3 to be placed, but still allows you to place blocks right next to it.

Once you have placed the Cryogenic chamber, you can place blocks above and around it. Now say, you want to move the Cryogenic chamber elsewhere; you break it and the ceiling and all nearby blocks are also destroyed along with.

![2014-11-11_11 36 12](https://cloud.githubusercontent.com/assets/6743303/4993549/03851da0-6997-11e4-862f-aaaee93d1865.png)
![2014-11-11_11 36 23](https://cloud.githubusercontent.com/assets/6743303/4993550/03877bc2-6997-11e4-932a-252737da933d.png)

(moved part 2 to https://github.com/micdoodle8/Galacticraft/issues/1159#issuecomment-67794676)

Similar report: #374

(EDIT: I loved the new size of the Cryogenic chamber, it looked like a giant bathtub before.)

**Comment by radfast** [comment]
Fixed by #1641, thanks to @SteveKunG.
