### ISSUE TITLE
Sun Disappears In Asteroid Belt

### ISSUE THREAD

**Issue by JakXLT** [micdoodle8/Galacticraft#1234]
I think I've mentioned this before but never actually raised an issue about it. When using lower view distances the sun disappears. I was hoping this was fixed in the new stable release but I guess not :(

I'm using optifine btw.

At 'Normal' View distance(setting 8), the sun cannot be seen.
![](http://puu.sh/cL7kr/cd711e3282.png)

At Normal+ at, setting 9-11, the sun can be seen but it's kind of dim.
![](http://puu.sh/cL7zg/5739314906.png)

Beyond that everything appears to be fine, though the sun does noticeably get brighter as you turn the view distance even higher.

**Comment by radfast** [comment]
The issue where the sun (sometimes) disappears completely is now fixed.

I'm still having problems finding the reason for the issue where it dims when it's near the center of the screen...
