### ISSUE TITLE
Space race console spam

### ISSUE THREAD

**Issue by mattymaats** [micdoodle8/Galacticraft#1235]
Hi guys,

I'm sorry if this is a duplicate but I looked through open issues and few pages of the closed issues and I couldn't find this report anywhere. Basically I'm getting the below message spam the console constantly. I noticed we're not using the latest build but as I haven't seen this issue posted I just wanted to see if you're aware of it and if it's fixed in the latest version.

10.11 19:09:55 [Server] INFO [19:09:55 INFO]: LifeCrafterHD
10.11 19:09:55 [Server] INFO [19:09:55 INFO]: Vector3 [1.0,1.0,1.0]
10.11 19:09:55 [Server] INFO [19:09:55 INFO]: micdoodle8.mods.galacticraft.core.wrappers.FlagData@1d170dde

Using following versions. GalacticraftCore-BETA-1.7-3.0.5.225.jar
Galacticraft-Planets-BETA-1.7-3.0.5.225.jar

**Comment by radfast** [comment]
I forgot about this one, sorry.  This logging is now made Debug mode only, in next GC build (3.0.8.257).

The Space Race Data should be saved in the ```.minecraft/world/data``` folder, file name ```GCSpaceRaceData.dat```
