### ISSUE TITLE
Aluminum Wires Do Not Connect To Big Reactors Power Ports.

### ISSUE THREAD

**Issue by JakXLT** [micdoodle8/Galacticraft#1245]
Title ^

**Comment by TeufelPenguin** [comment]
I have the following and have the same issue as above:

Mekanism - 1.7.10-7.1.1.127
Buildcraft - 6.2.6
Big Reactors - 0.4.0rc11
Galacticraft - 1.7-3.0.6.233

**Comment by dj3520** [comment]
![image](https://cloud.githubusercontent.com/assets/8284194/6540087/1aa6c034-c459-11e4-859d-e25bfd8aed28.png)
Try with BigReactors 0.4.1A2, Buildcraft 6.4.2, and Galaticraft 1.7-3.0.8.271 (I don't have Mekanism)
Also this was fixed by radfast in this post.
>Please try latest version 3.0.6.240 which has RF support.

**Comment by radfast** [comment]
@TeufelPenguin   update Galacticraft to the Latest and let us know how you get on.
