### ISSUE TITLE
API requets

### ISSUE THREAD

**Issue by NightKosh** [micdoodle8/Galacticraft#1259]
I need a way to get access to items from additional slots.

**Comment by radfast** [comment]
I added an API, you should be able to get at the Galacticraft inventory (which is a simple extension of IInventory) using
> ```micdoodle8.mods.galacticraft.api.inventory.AccessInventoryGC.getGCInventoryForPlayer(player)```

Please see commit 361e009 for details

**Comment by NightKosh** [comment]
Thank you very much!

**Comment by radfast** [comment]
A pleasure, if it isn't 100% for your needs then please say and I will tweak it.
(By the way ignore commit 6a06465, I made a mistake in that and overwrote it with force-pushed 361e009)

**Comment by Mochnant** [comment]
@radfast I don't mean to hijack this issue, but it seems related to a request I have with the OpenBlocks devs regarding graves and Galacticraft items disappearing, and their suggestion for a code tweak you could possibly make to fix it on your end.  Could you take a peek and see if it is reasonable and/or possible?  Thanks.

https://github.com/OpenMods/OpenBlocks/issues/585
