### ISSUE TITLE
GC3 r232: Summon command issues

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#1266]
Not game-breaking at all, low priority.

I'm generating 3D preview pics for the Galacticraft Wiki ([example](http://wiki.micdoodle8.com/wiki/File:Advanced_Solar_Panel.png)) including entities and vehicles, to do so I use /summon command. The issues:

`/summon Lander` or `/summon EntityLander` no longer works.

`/summon LandingBalloons` and `/summon EntryPodAsteroids` work, but the game crashes if you right-click on them.

**Comment by SteveKunG** [comment]
![2558-01-13_15 43 00](https://cloud.githubusercontent.com/assets/6128413/5720616/27efeb5e-9b59-11e4-91b8-2fe91e5af087.png)

Here when I summoned with slimeling they is no color and name.

And this is list of non-mob entity to use in summon command.
GalacticraftCore.Meteor
GalacticraftCore.GCFlag
GalacticraftCore.MeteorChunk
GalacticraftCore.Buggy
GalacticraftCore.MeteorChunk
GalacticraftMars.GrappleHookGC
GalacticraftMars.CargoRocket
GalacticraftMars.SpaceshipT2
GalacticraftCore.Spaceship
GalacticraftMars.Tier3RocketGC
GalacticraftCore.Lander
GalacticraftMars.LandingBalloons
GalacticraftCore.OxygenBubble
GalacticraftMars.ProjectileTNT
GalacticraftCore.CelestialScreen
GalacticraftCore.ParaChest
GalacticraftMars.SmallAsteroidGC

**Comment by radfast** [comment]
I've fixed the crashes.

The name change from:
```/summon Lander```
to
```/summon GalacticraftCore.Lander```
is because more than a year ago, we switched all non-mob entities from being Global entities to being mod specific.  A few months ago we also switched mobs from Global to mod specific, so the mobs will now also be ```GalacticraftCore.EvolvedSpider``` instead of ```EvolvedSpider```.

I guess NEI can dump a list of all entity names?

**Comment by EzerArch** [comment]
> I guess NEI can dump a list of all entity names?

No.

![2016-03-27_00 42 43](https://cloud.githubusercontent.com/assets/6743303/14063737/e7054d40-f3b4-11e5-8aaa-439d78193744.png)

Now the lander and other vehicles no longer crash I can test them (ref: #1710).
