### ISSUE TITLE
Lag-Festival on Moon

### ISSUE THREAD

**Issue by NitroxydeX** [micdoodle8/Galacticraft#1267]
I was really excited about the moon but after my friend and me finished the Moon-Base we experience some really-really ping-problems. You join and you can watch your ping going to more than 800!

Java is using 100% of the Internet-Connection. Ping turns sometimes normal but not for a long time. It's just on the moon. Don't know if its on Mars & Asteroids too.

**Comment by radfast** [comment]
The 'earth disappearing issue' is fixed in latest GC 3.0.9.
