### ISSUE TITLE
Nether Portals can be generated in Galacticraft dimensions

### ISSUE THREAD

**Issue by Dream-Master** [micdoodle8/Galacticraft#1283]
![image](https://cloud.githubusercontent.com/assets/2970688/5221938/254f651e-7688-11e4-9836-884aa0f2cc24.png)

![image](https://cloud.githubusercontent.com/assets/2970688/5221943/30f004be-7688-11e4-9ca5-d503581b8e13.png)

**Comment by radfast** [comment]
Fire charge use is now disabled if there is no oxygen.

Nether Portals can exist on space worlds - even in airless locations.  Here are some ways:
* they were created using fire in some way
* they were created using a Fire Charge in pre-411 versions of Galacticraft
* they were created inside oxygen (e.g. Oxygen Bubble) and then the oxygen was removed but the Nether Portal was left intact.

As of Galacticraft 411, Nether Portals which have been built in space dimensions will have no function - the player can stand inside the portal but will not be teleported to the Nether.  (And Nether mobs will never come out of the portal.)

**Comment by radfast** [comment]
Fire-starting tools from other mods - for example the 'Lighter' - will still function in oxygenless environments.  The only way to stop that is to code specifically to blacklist each one.  I can do that slowly, if people inform me of the common tools.
