### ISSUE TITLE
GC3 r240: Moon Buggy hit box is so big that vehicle breaks if you punch the air while sitting on it

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#1297]
Moon Buggy hit box is so big that vehicle breaks if you punch the air or anywhere while sitting on it

Sit on a Moon Buggy, look up, punch, the Moon Buggy breaks with just one hit.

This is a problem, if you are driving a buggy and a hostile mob appears, you can't use a bow or a sword without break the vehicle you are driving.

Also, shift-click still works as "Dismount" key, a thing that is deprecated in vanilla.

Pic:
![2014-12-04_18 36 02](https://cloud.githubusercontent.com/assets/6743303/5305625/6a28932a-7be4-11e4-84f2-4c50f462ffe2.png)

**Comment by radfast** [comment]
Fixed, thanks to @Gebatzens.
