### ISSUE TITLE
[GC1.7-3.0.6.240] Space Station movement is very heavy-like

### ISSUE THREAD

**Issue by davidpox** [micdoodle8/Galacticraft#1298]
Moving around in a space station is quite "buggy" and it's quite hard to fluidly move around. I dont know if this is intentional to represent the actual movement you'd have in space, but I'm just checking to see if its still being worked on, and I wonder if its able to be changed client-side to how the user would like it.

I have made a video demonstrating the movement right here:
https://www.youtube.com/watch?v=XCqWqkCSV5E

If it is intentional, I'll create a Mystcraft void dimension instead. it's not too much of a big deal (although then I wont get to fly the rockets and stuff, and have the awesome skybox)

**Comment by morlanius** [comment]
If anything there is too much gravity for being in orbit, unless overworld has more mass  than we are used to. To fall at that are in orbit overworld would need to be several earth masses. Would it be better to set it much much lower. If you became detached it would take you days to fall enough that the outer atmosphere would start to slow you making you fall faster.

So basically I'm saying the opposite to this guy, make it harder. Perhaps add a suicide pill in case you get detached, or I guess you just just pull your helmet off, perhaps that's more acceptable albeit less realistic.

**Comment by radfast** [comment]
I'm thinking about 2 modes, see my comment in #1383
