### ISSUE TITLE
Fire arrows still burn in space.

### ISSUE THREAD

**Issue by XxGenorator** [micdoodle8/Galacticraft#1310]
When you shoot a flame arrow the arrow burns in the ground. Sorry if you already know of this issue. I was goofing around and decided to report it.

**Comment by radfast** [comment]
Fixed, thanks for raising this.

**Comment by EzerArch** [comment]
Wow, I was fine with this one. I used to think "it's just magic" or "mobs burn because they use oxygen gears", my "Suspension of disbelief" bag is getting emptier and emptier. :-)
