### ISSUE TITLE
[GC 1.7-3.0.6.246] Display Screen displays same, incorrect image across all worlds

### ISSUE THREAD

**Issue by Arkandy** [micdoodle8/Galacticraft#1319]
I thought it was strange that our overworld looked incorrect when flying out of it with a rocket, so I built a display screen and saw the same image: http://i.imgur.com/ehzwihN.png
I made two new SSP and CSP worlds, both of which show this image.

Is there any more info that I should include to help out with this?

**Comment by radfast** [comment]
Fixed in new build 442.  The map on the Overworld is correct.  Currently on other worlds no map will be shown.  See #1752 for a description of the new system.
