### ISSUE TITLE
Galacticraft 1.7.10 potion effect on BoP phantom mob in Nether crashes to launcher

### ISSUE THREAD

**Issue by adamvan2000** [micdoodle8/Galacticraft#1323]
I was derping around in the Nether on my favourite server and saw an Infernal BoP phantom. As soon as it aggro'd on me and I got the potion effect, I crashed to the launcher. This was repeatable, as every time I went back to get my stuff as soon as the phantom aggro'd me I'd crash.

Modpack: Resonant Rise (Mainline) 3.1.0.1
Forge: 10.13.2.1231
Galacticraft: 3.0.6.239
Infernal Mobs: 1.7.10

http://pastebin.com/WQxEs7Za

**Comment by radfast** [comment]
On #1365 it's been suggested that __Blood Magic__ may be the cause.
