### ISSUE TITLE
GC3 r245: Moon Buggy uses Overworld's gravity value regardless the dimension

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#1324]
The Moon Buggy, while being used, will disregard the custom gravity and will use Overworld's gravity value no matter the dimension.

For example, go to the space station dimension, drive a buggy and run off the floor, you will plunge into the Overwolrd at 1G.

**Comment by radfast** [comment]
Fixed, thanks to @Gebatzens.
