### ISSUE TITLE
[INFO] Energy network: acceptor took too much energy. Console Spam.

### ISSUE THREAD

**Issue by PunOfUs** [micdoodle8/Galacticraft#1328]
This just started showing up this morning in console for a bukkit server we are running with a new custom modpack. The only thing I know to have changed in this space station is one of our users made a quite large sized BigReactor. Please let me know what other information you need to resolve this issue. We are running 2.0.14.1084

06:41:02 [INFO] Energy network: acceptor took too much energy, offered 0.005139754, took 3.2123463. TileMultipart_cmp$$29@105dfc36
06:41:12 [INFO] Energy network: acceptor took too much energy, offered 0.0067397584, took 4.212349. TileMultipart_cmp$$29@105dfc36
06:41:22 [INFO] Energy network: acceptor took too much energy, offered 0.005139754, took 3.2123463. TileMultipart_cmp$$29@105dfc36
06:41:32 [INFO] Energy network: acceptor took too much energy, offered 0.0067397584, took 4.212349. TileMultipart_cmp$$29@105dfc36
06:41:42 [INFO] Energy network: acceptor took too much energy, offered 0.0067397584, took 4.212349. TileMultipart_cmp$$29@105dfc36
06:41:52 [INFO] Energy network: acceptor took too much energy, offered 0.005139754, took 3.2123463. TileMultipart_cmp$$29@105dfc36
06:42:02 [INFO] Energy network: acceptor took too much energy, offered 0.004969892, took 3.1061826. TileMultipart_cmp$$29@105dfc36
06:42:12 [INFO] Energy network: acceptor took too much energy, offered 0.0067397584, took 4.212349. TileMultipart_cmp$$29@105dfc36
06:42:22 [INFO] Energy network: acceptor took too much energy, offered 0.005139754, took 3.2123463. TileMultipart_cmp$$29@105dfc36
06:42:34 [INFO] Energy network: acceptor took too much energy, offered 0.0048849587, took 3.0530992. TileMultipart_cmp$$29@105dfc36
06:42:44 [INFO] Energy network: acceptor took too much energy, offered 0.005139754, took 3.2123463. TileMultipart_cmp$$29@105dfc36
06:42:54 [INFO] Energy network: acceptor took too much energy, offered 0.004969892, took 3.1061826. TileMultipart_cmp$$29@105dfc36
06:43:04 [INFO] Energy network: acceptor took too much energy, offered 0.005139754, took 3.2123463. TileMultipart_cmp$$29@105dfc36
06:43:17 [INFO] Energy network: acceptor took too much energy, offered 0.0067397584, took 4.212349. TileMultipart_cmp$$29@105dfc36
06:43:27 [INFO] Energy network: acceptor took too much energy, offered 0.0048849587, took 3.0530992. TileMultipart_cmp$$29@105dfc36
06:43:37 [INFO] Energy network: acceptor took too much energy, offered 0.005139754, took 3.2123463. TileMultipart_cmp$$29@105dfc36
06:43:47 [INFO] Energy network: acceptor took too much energy, offered 0.0067397584, took 4.212349. TileMultipart_cmp$$29@105dfc36
06:43:57 [INFO] Energy network: acceptor took too much energy, offered 0.005139754, took 3.2123463. TileMultipart_cmp$$29@105dfc36
06:44:07 [INFO] Energy network: acceptor took too much energy, offered 0.005139754, took 3.2123463. TileMultipart_cmp$$29@105dfc36
06:44:17 [INFO] Energy network: acceptor took too much energy, offered 0.0067397584, took 4.212349. TileMultipart_cmp$$29@105dfc36
06:44:27 [INFO] Energy network: acceptor took too much energy, offered 0.0067397584, took 4.212349. TileMultipart_cmp$$29@105dfc36
06:44:37 [INFO] Energy network: acceptor took too much energy, offered 0.005139754, took 3.2123463. TileMultipart_cmp$$29@105dfc36
06:44:47 [INFO] Energy network: acceptor took too much energy, offered 0.0067397584, took 4.212349. TileMultipart_cmp$$29@105dfc36
06:44:57 [INFO] Energy network: acceptor took too much energy, offered 0.0067397584, took 4.212349. TileMultipart_cmp$$29@105dfc36
06:45:07 [INFO] Energy network: acceptor took too much energy, offered 0.0049698898, took 3.1061811. TileMultipart_cmp$$29@105dfc36
06:45:17 [INFO] Energy network: acceptor took too much energy, offered 0.0067397584, took 4.212349. TileMultipart_cmp$$29@105dfc36
06:45:27 [INFO] Energy network: acceptor took too much energy, offered 0.004969892, took 3.1061826. TileMultipart_cmp$$29@105dfc36
06:45:37 [INFO] Energy network: acceptor took too much energy, offered 0.004969892, took 3.1061826. TileMultipart_cmp$$29@105dfc36
06:45:49 [INFO] Energy network: acceptor took too much energy, offered 0.004969892, took 3.1061826. TileMultipart_cmp$$29@105dfc36
06:45:59 [INFO] Energy network: acceptor took too much energy, offered 0.0067397584, took 4.212349. TileMultipart_cmp$$29@105dfc36

**Comment by Linrox** [comment]
I am using 1.6.4-2.0.14.1098 and still get the same issue as above. i could not find the 1096 build. 

11:33:10 [INFO] Energy network: acceptor took too much energy, offered 0.029227734, took 0.029296875. micdoodle8.mods.galacticraft.core.tile.GCCoreTileEntityEnergyStorageModule@2e2ed3d9
11:33:18 [INFO] Energy network: acceptor took too much energy, offered 0.029177666, took 0.029296875. micdoodle8.mods.galacticraft.core.tile.GCCoreTileEntityEnergyStorageModule@2e2ed3d9
11:33:22 [INFO] Energy network: acceptor took too much energy, offered 0.029192924, took 0.029296875. micdoodle8.mods.galacticraft.core.tile.GCCoreTileEntityEnergyStorageModule@2e2ed3d9
11:33:36 [INFO] Energy network: acceptor took too much energy, offered 0.029237747, took 0.029296875. micdoodle8.mods.galacticraft.core.tile.GCCoreTileEntityEnergyStorageModule@2e2ed3d9
11:34:01 [INFO] Energy network: acceptor took too much energy, offered 0.029196978, took 0.029296875. micdoodle8.mods.galacticraft.core.tile.GCCoreTileEntityEnergyStorageModule@2e2ed3d9
11:34:23 [INFO] Energy network: acceptor took too much energy, offered 0.029175282, took 0.029296875. micdoodle8.mods.galacticraft.core.tile.GCCoreTileEntityEnergyStorageModule@2e2ed3d9
11:34:32 [INFO] Energy network: acceptor took too much energy, offered 0.029176235, took 0.029296875. micdoodle8.mods.galacticraft.core.tile.GCCoreTileEntityEnergyStorageModule@2e2ed3d9
11:34:45 [INFO] Energy network: acceptor took too much energy, offered 0.029186487, took 0.029296875. micdoodle8.mods.galacticraft.core.tile.GCCoreTileEntityEnergyStorageModule@2e2ed3d9
11:34:49 [INFO] Energy network: acceptor took too much energy, offered 0.02919674, took 0.029296875. micdoodle8.mods.galacticraft.core.tile.GCCoreTileEntityEnergyStorageModule@2e2ed3d9
11:34:57 [INFO] Energy network: acceptor took too much energy, offered 0.029195786, took 0.029296875. micdoodle8.mods.galacticraft.core.tile.GCCoreTileEntityEnergyStorageModule@2e2ed3d9
11:35:05 [INFO] Energy network: acceptor took too much energy, offered 0.02919674, took 0.029296875. micdoodle8.mods.galacticraft.core.tile.GCCoreTileEntityEnergyStorageModule@2e2ed3d9
11:35:19 [INFO] Energy network: acceptor took too much energy, offered 0.029214144, took 0.029296875. micdoodle8.mods.galacticraft.core.tile.GCCoreTileEntityEnergyStorageModule@2e2ed3d9
11:35:47 [INFO] Energy network: acceptor took too much energy, offered 0.029232979, took 0.029296875. micdoodle8.mods.galacticraft.core.tile.GCCoreTileEntityEnergyStorageModule@2e2ed3d9
11:38:10 [INFO] Energy network: acceptor took too much energy, offered 0.029424667, took 0.029541016. micdoodle8.mods.galacticraft.core.tile.GCCoreTileEntityEnergyStorageModule@2e2ed3d9
11:38:21 [INFO] Energy network: acceptor took too much energy, offered 0.029451134, took 0.029541016. micdoodle8.mods.galacticraft.core.tile.GCCoreTileEntityEnergyStorageModule@2e2ed3d9
11:38:36 [INFO] Energy network: acceptor took too much energy, offered 0.029453516, took 0.029541016. micdoodle8.mods.galacticraft.core.tile.GCCoreTileEntityEnergyStorageModule@2e2ed3d9
11:38:53 [INFO] Energy network: acceptor took too much energy, offered 0.02946043, took 0.029541016. micdoodle8.mods.galacticraft.core.tile.GCCoreTileEntityEnergyStorageModule@2e2ed3d9
11:39:09 [INFO] Energy network: acceptor took too much energy, offered 0.029459951, took 0.029541016. micdoodle8.mods.galacticraft.core.tile.GCCoreTileEntityEnergyStorageModule@2e2ed3d9
11:40:07 [INFO] Energy network: acceptor took too much energy, offered 0.029432535, took 0.029541016. micdoodle8.mods.galacticraft.core.tile.GCCoreTileEntityEnergyStorageModule@2e2ed3d9
11:40:14 [INFO] Energy network: acceptor took too much energy, offered 0.029460905, took 0.029541016. micdoodle8.mods.galacticraft.core.tile.GCCoreTileEntityEnergyStorageModule@2e2ed3d9

I know it is not that latest MC version but it has less issues than 1.7.10 and 1.8
Is there a version of GC that does not have this issue thanks
Thanks

**Comment by radfast** [comment]
@Linrox  there is currently no version of GC for Minecraft 1.6.4 which does not have this logging issue, unless you want to go back more than 1 year to something like GC 2.0.4, which will have a ton of other issues.

>  it has less issues than 1.7.10 and 1.8
This I don't agree with.  All major mods including Galacticraft have been stable on 1.7.10 for some time, it's better in most ways than 1.6.4 - unless there is some specific mod you want which has not been updated to 1.7.10?

The actual issue you are seeing looks like a rounding error in the internal game calculations, because you are putting a very small amount of energy into an Energy Storage Module - probably because it's almost full and it's powering only one small thing.  If the log message is annoying you that much, you could try a different build in game - maybe add a few more machines to drain that Energy Storage Module a bit harder.  Alternatively disconnect the power input from the Energy Storage Module and use an infinite battery instead.  It's not cheating if you already have plenty of power to keep that Energy Storage Module full all the time.
