### ISSUE TITLE
Display Screen doesn't show the horse type

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#1334]
![2557-12-21_19 24 56](https://cloud.githubusercontent.com/assets/6128413/5525291/584e9e5c-8a16-11e4-8911-ee6eb9f74a80.png)

When I tracking my donkey and using the display screen to show my donkey in a screen. But it's doesn't show the horse type.

**Comment by radfast** [comment]
I like horses, I have been meaning to solve this for a long time :)
