### ISSUE TITLE
Thermal Armor

### ISSUE THREAD

**Issue by BlesseNtumble** [micdoodle8/Galacticraft#1343]
Good afternoon. 
Creating Venus, I thought about creating a new Thermal Armor.
 But then came the problem. Current thermal armor has no restrictions on   

@Override     
public float getThermalLevelModifier ()
 {         
return +10;     
} 

You can make thermal armor on levels?
For Example, level 1 = -2 to +2
level 2 = -4 to +4

**Comment by radfast** [comment]
This is a suggestion, please take it to the forum not the Github - I'm 100% happy if you want to add this to one of your existing Venus threads on the forum, we will see it.

It's not totally clear what you are suggesting here - I think you are saying you want different planets to have different temperatures and therefore need different tiers of thermal armor?  That's a good idea for the future of Galacticraft but will need a bit of re-coding.

**Comment by radfast** [comment]
If it's helpful, you might want to use new method GCPlayerHandler.normaliseThermalLevels()
https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/entities/player/GCPlayerHandler.java#L511

Normal thermal armor will "normalise" the thermal level (push it towards the central position) by +/-1 per tick if a full set is worn.  With better thermal protection systems, you could have your systems call that with a larger increment than 1.
