### ISSUE TITLE
Galacticraft Inventory not saving with Openblocks Graves

### ISSUE THREAD

**Issue by cproo12** [micdoodle8/Galacticraft#1351]
@Openmods
On death, a players galacticraft items simply drop, rather than saving with the rest of the stuff in the openblocks grave.

**Comment by radfast** [comment]
That will need to be implemented by the OpenBlocks dev team, not us.  We have provided a command which another mod can 'simulate' in-game to do this (/gcinv) - see http://wiki.micdoodle8.com/wiki/Command_gcinv - or the other mod could copy the /gcinv code.

I'm also looking at how else we can help, see also ongoing discussions with the GraveStone mod team at #1259 and #1288

**Comment by radfast** [comment]
Anyone who is interested in this, please point the OpenBlocks dev team at the new API just added to Galacticraft to facilitate this, see 361e009.

Further info at #1259 and #1288.

That's all we can do in Galacticraft, it's up to the OpenBlocks team now.

**Comment by radfast** [comment]
OK, big thanks to the OpenBlocks team for showing me that Galacticraft could in fact do things better: https://github.com/OpenMods/OpenBlocks/issues/585

GC should be compatible with OpenBlocks as from next build 3.0.7.256.  Here's hoping anyhow!
