### ISSUE TITLE
Galacticraft overrides GT Helium gas texture by no texture

### ISSUE THREAD

**Issue by hanakocz** [micdoodle8/Galacticraft#1353]
According to Greg, missing texture of helium gas is connected with Galacticraft:
http://forum.industrial-craft.net/index.php?page=Thread&postID=177720#post177720

Is there any way how to make that not conflicting? Now GT helium gas loses its texture and has typical "no texture" purple/black thing.

**Comment by radfast** [comment]
I can add a config to Galacticraft not to register Helium gas at all (so it will let GT do it).
Please let me know of any other similar issues, as I'd like to do all together.
The Galacticraft gases are:
* Oxygen + Liquid Oxygen
* Nitrogen + Liquid Nitrogen
* Argon + Liquid Argon
* Methane + Liquid Methane
* Hydrogen
* Helium
* Carbon Dioxide
* Atmospheric Gases (it's a mixture of gases whose components depends on the planet)

We do not yet have Liquid Hydrogen or Liquid Helium though those are likely in GC4.

**Comment by hanakocz** [comment]
Well, it does only for Helium, all other gases have (or seems to) textures when placed to some tank (I failed to put argon in tank, so dont know there) 
But it is pity these gases are not the "same" - as same as GC uses same oil with BC oil :)

**Comment by radfast** [comment]
Helium should be the same.  I think the issue is GC registers it first, which means GT does not register its version.  GC currently has no texture for it because it isn't in the game (no machine uses or makes it), it's only present so that it can be available as an atmosphere component.

**Comment by radfast** [comment]
Config option is added in the next build (look in asteroids.conf).
