### ISSUE TITLE
Cryo Chamber cannot be left by button with Morpheus installed

### ISSUE THREAD

**Issue by hanakocz** [micdoodle8/Galacticraft#1357]
Hi again,
We found strange thing on our server. We have Morpheus mod for better sleeping, however we are unable to get off from cryo chamber when sleeping in it. Morpheus sees the chambes usage same as bed, but it does not "wake up" players from it when the day starts. However it is absolutely impossible to get from that cryo chamber, the button does not work. Only way was to kick the player from server...

Morpheus does that it counts players in beds and when there are sleeping set %, it will force the day ....so the only change is that not everyone on server needs to sleep to skip the night...

**Comment by EzerArch** [comment]
*Probably* related to #1159.

**Comment by radfast** [comment]
Should be fixed in latest build 492 for Minecraft 1.7.10, and also fixed in Galacticraft 4.

Sorry that it took 2 years ... our focus was elsewhere!
