### ISSUE TITLE
Moon - map discontinuity at chunk edge

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#1358]
![2558-01-01_21 06 13](https://cloud.githubusercontent.com/assets/6128413/5602345/9c14c2bc-9379-11e4-8088-6d71ea707b62.png)
![2558-01-01_21 06 54](https://cloud.githubusercontent.com/assets/6128413/5602348/b586a436-9379-11e4-988c-b03e53275e2c.png)

With chunk coordinate.
![2558-01-01_21 06 28](https://cloud.githubusercontent.com/assets/6128413/5602346/b00e7826-9379-11e4-960a-8ae1e35c1e92.png)
![2558-01-01_21 06 34](https://cloud.githubusercontent.com/assets/6128413/5602347/b013db04-9379-11e4-971d-d931a10857c6.png)

**Comment by radfast** [comment]
Thank you for reporting.

This is probably connected with some change (maybe a code change between Galacticraft versions, maybe a change of your modpack or a config connected with biomes) which as a consequence changed the order random numbers were provided, for the same map position, even though the World Seed remained unchanged.  So the RNG was different by the time the worldgen reached ```chunkProviderMoon.createCraters()```.

That means if you had 2 chunks A and B, chunk A generated before the change, chunk B generated after, there can be map discontinuities like this.

I cannot think of any other reason, but if you notice this again __in a newly generated world__ (all Moon chunks generated with same Galacticraft version and same modpack) please re-open!

**Comment by SteveKunG** [comment]
I'm testing on development and using the same seed and create new world.

![2558-03-24_16 03 20](https://cloud.githubusercontent.com/assets/6128413/6821033/e284d422-d306-11e4-920b-2609a311d781.png)
