### ISSUE TITLE
Rendering sleeping player wrong

### ISSUE THREAD

**Issue by TheJulianJES** [micdoodle8/Galacticraft#1361]
http://imgur.com/a/Go6NW (sorry for the wrong album title...)
First Image with Galacticcraft
Second without (also Coremods)
Versions:
Minecraft: 1.7.10
Forge: 10.13.2.1277
MicdoodleCore: 3.0.6.250
GalacticraftCore: 3.0.6.250
Galacticraft-Planets: 3.0.6.250

**Comment by radfast** [comment]
Thanks for reporting.  It's a duplicate of open issue #897 so I will close this now.

**Comment by TheJulianJES** [comment]
@radfast Sorry, I searched but didn't found anything.

**Comment by radfast** [comment]
It's no problem, I definitely prefer to have the bugs reported twice than not at all!
