### ISSUE TITLE
[Feature Request] Sealable Hydrogen Pipe

### ISSUE THREAD

**Issue by Kodos-Atoz** [micdoodle8/Galacticraft#1362]
We have Oxygen, but no Hydrogen sealable pipe blocks.

Also, if possible or even necessary, an infinite hydrogen creative-only item as well.

**Comment by radfast** [comment]
Suggestions on the forum please, the issue list should be a bug-tracker only.

I have noted the suggestion and it will probably come about some time, but currently the 16 possible types of sealable pipes are all used - I plan to add another 16 at some point including some requested on the forum, but no ETA for that yet.
