### ISSUE TITLE
model update event

### ISSUE THREAD

**Issue by morlanius** [micdoodle8/Galacticraft#1370]
When placing a rocket on a pad most time you dont see the rocket there but if you go out the area and back in (loading the chunk) the rocket is displayed on the pad. using GC 248

**Comment by morlanius** [comment]
Struggling to reproduce this now.

**Comment by radfast** [comment]
I've never seen this.  If you find a way to reproduce it, please let us know and I'll reopen - gonna close this meanwhile.
