### ISSUE TITLE
Crash on orbit

### ISSUE THREAD

**Issue by morlanius** [micdoodle8/Galacticraft#1371]
I've been getting a strange crash related to biome providers, it mentioned the asteroid dimension but sometimes it'll mention another one, its probably just the position in iterator it happened to be in.

http://91.121.75.102/pages/gc_error.log  <-- log file.

**Comment by radfast** [comment]
This
>java.lang.ClassCastException: micdoodle8.mods.galacticraft.planets.asteroids.world.gen.BiomeGenBaseAsteroids cannot be cast to erebus.world.biomes.BiomeBaseErebus

is the Erebus biome ID conflict bug reported at #1342, also mentioned on the Wiki under http://wiki.micdoodle8.com/wiki/Compatibility#Erebus
I thought at first it was an iterator error but no, it's a straight up ID conflict.  The only solution for now is to edit the Erebus config to change Erebus biome IDs from 102-105 to some other numbers like 112-115 (should be easy enough to find some unused ones as you do not have Biomes o' Plenty installed).  This does unfortunately then require a regen of the Erebus dimensions to eliminate all the conflicting biomes.

In the next Galacticraft build we are introducing similar configs so the Galacticraft biome IDs can be changed.  You might want to use that instead if you don't want to regenerate dimensions.  Although best policy would say that the Galacticraft dimensions ought to be regenerated if the GC biome IDs change, in practice nothing bad will happen (I think) if you do not regenerate them after changing the GC configs, except that the biome ID info shown on the F3 debug screen will be incorrect.



I'm also seeing a Mekanism error which has nothing to do with Galacticraft:
> [18:19:26] [Server thread/WARN]: java.util.ConcurrentModificationException
[18:19:26] [Server thread/WARN]: 	at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:394)
[18:19:26] [Server thread/WARN]: 	at java.util.LinkedHashMap$KeyIterator.next(LinkedHashMap.java:405)
[18:19:26] [Server thread/WARN]: 	at mekanism.api.transmitters.DynamicNetwork.fullRefresh(DynamicNetwork.java:95)

**Comment by morlanius** [comment]
Ahh, i see. Thanks.
