### ISSUE TITLE
Crash when fighting skeleton boss

### ISSUE THREAD

**Issue by Rainboww** [micdoodle8/Galacticraft#1375]
https://gist.github.com/Rainboww/ce3679bd9b7c3ce8e489
This happens every time I fight the skeleton boss on the moon, I believe when it grabs me to throw me away. It doesn't (didn't) happen for someone else on the same server, who fought another skeleton boss just fine.

**Comment by radfast** [comment]
Please test new build (latest) 3.0.7.253 - you only need to update that on your client, not on the server.

If that doesn't fix it then read on... ... ...

----

I found this on Forge which looks to be a similar crash from 8 months ago, unfortunately not resolved:
https://github.com/MinecraftForge/MinecraftForge/issues/1082

What version of Galacticraft + Forge is the other player running?  Also what versions are on the server?  I'm guessing server and all players are on Galacticraft 3.0.7.252.  It's strange - but probably very helpful in finding a possible cause for this - that the other player has no crash.  As between you and the other player, please think of any possible differences - Forge version, Java version, any client-side only mods (e.g. Optifine).  Also, is the play setup exactly the same, like did both you and the other player fight the Skeleton Boss alone or were other players nearby (within 40 blocks distance)?

**Comment by Barhandar** [comment]
We fought alone, I'm indeed on Galacticraft 3.0.7.252 with Forge 10.13.2.1286 and Java 8.25. Rainboww is playing from client running on same machine as server, I'm playing from a different one.

I'll try fighting on client and server without my clientside mods to see if they do miraculously fix the issue. I don't have Optifine, but I do have Numina installed, which could, through greatly convoluted path, affect the issue as it unlinks player speed and FOV, as well as a few others.

**Comment by Rainboww** [comment]
I'm on galacticraft 3.0.7.252 as well, with same forge version and java 7. I'll get the new version of galacticraft when it's available, if that doesn't help we'll see.

**Comment by Barhandar** [comment]
Re-adding all of my clientside mods did nothing. Crash definitely happens if client is capable of hearing the sound boss makes (using frequency module or came not via a rocket, resulting in sound-dampening code not executing. Is it possible to hook into overall dimension change instead of rocket transfer?), and it happens at the exact same moment as boss laughs a second time in a row.

**Comment by radfast** [comment]
3.0.7.254 now available, I'd be very grateful if you would test and see if this fixes the issue.

**Comment by radfast** [comment]
By the way if you have OP privileges on the server you can use the command ```/dimensiontp``` to travel to the Moon without a rocket.

Thanks for flagging the "sound dampening code not executing if player teleports to the dimension", that's a separate issue (OK, I can see how it could be related here) which I will need to look into.

**Comment by Barhandar** [comment]
>3.0.7.254 now available, I'd be very grateful if you would test and see if this fixes the issue.

Seems to have fixed the issue. Thanks!
>Thanks for flagging the "sound dampening code not executing if player teleports to the dimension", that's a separate issue (OK, I can see how it could be related here) which I will need to look into.

The thing is, *only* the boss's sounds (laughter and shout when he throws you) are heard. Everything else is correctly muted.

**Comment by Rainboww** [comment]
as Barhandar said, thanks a bunch, that seemed to have fixed it!
