### ISSUE TITLE
Energy Storage Cluster output GUI issue

### ISSUE THREAD

**Issue by dj3520** [micdoodle8/Galacticraft#1385]
![image](https://cloud.githubusercontent.com/assets/8284194/5771980/39ea3354-9d17-11e4-9df1-c166eb25aa6b.png)
"/t" off screen floating onto background. Present in gJ and RF unit settings.

**Comment by radfast** [comment]
Thanks for spotting this.  That GUI could do with a total redesign.  See also http://forum.micdoodle8.com/index.php?threads/about-properties-and-values-of-wires-and-electrical-machineries.3432/#post-30603

**Comment by dj3520** [comment]
That looks really interesting. My only nickpick would be to put horizontal lines in the charge bar to emphasize it's a cluster.
For now you can move the text a bit to the left. If we're talking pixels my guess would be about 6 (judging by the pixel size and width of the M in Max.)

**Comment by radfast** [comment]
@SteveKunG has made that temporary fix, thank you, so I will close this now.
The updated GUI will come some time in the future, but I have a few other things on my 'to do' list first.

**Comment by dj3520** [comment]
Hate to bug you about that 'to do' list of yours, but I'm itching for [my idea](http://forum.micdoodle8.com/index.php?threads/redstone-controlled-spin-thrusters-control-the-spin.4510/) to become true...
