### ISSUE TITLE
java.lang.IllegalArgumentException: ID is already registered: 31

### ISSUE THREAD

**Issue by C0rish** [micdoodle8/Galacticraft#1387]
First of all: 3.0.6.232 runs fine and smooth till now with a lot other mods...

Yesterday I tried to update to the most recommended version 3.0.7.252 and the following error appeared (also with the newest version 3.0.7.254):

>java.lang.IllegalArgumentException: ID is already registered: 31
>	at net.minecraft.entity.EntityList.func_75618_a(EntityList.java:93)
>	at net.minecraft.entity.EntityList.func_75614_a(EntityList.java:107)
>	at cpw.mods.fml.common.registry.EntityRegistry.registerGlobalEntityID(EntityRegistry.java:251)
>	at micdoodle8.mods.galacticraft.planets.mars.MarsModule.registerGalacticraftCreature(MarsModule.java:164)
>	at micdoodle8.mods.galacticraft.planets.mars.MarsModule.registerCreatures(MarsModule.java:148)
>	at micdoodle8.mods.galacticraft.planets.mars.MarsModule.init(MarsModule.java:96)
>	at micdoodle8.mods.galacticraft.planets.PlanetsProxy.init(PlanetsProxy.java:26)
>	at micdoodle8.mods.galacticraft.planets.PlanetsProxyClient.init(PlanetsProxyClient.java:29)
>	at micdoodle8.mods.galacticraft.planets.GalacticraftPlanets.init(GalacticraftPlanets.java:57)
>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>	at java.lang.reflect.Method.invoke(Unknown Source)
>	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
>	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>	at java.lang.reflect.Method.invoke(Unknown Source)
>	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
>	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
>	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
>	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
>	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
>	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
>	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>	at java.lang.reflect.Method.invoke(Unknown Source)
>	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
>	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
>	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
>	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
>	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
>	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
>	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:691)
>	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
>	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)
>	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
>	at net.minecraft.client.main.Main.main(SourceFile:148)
>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>	at java.lang.reflect.Method.invoke(Unknown Source)
>	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
>	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

I checked all config files from all mods but there is no "ID 31" in any of them... maybesomeone can help me?

**Comment by radfast** [comment]
See here:
http://forum.micdoodle8.com/index.php?threads/galacticraft-planets-id-error-mc-1-7-10.4838/

It's not a Galacticraft error, it's one of your other mods which is registering its entities improperly.  Unless seanster789 there tells us which mod it is, I guess you will have to figure that out yourself...

A "binary search" is efficient: remove half the mods out of your /mods folder, start the game, see if it starts OK, if so then you know the problem is in the half you removed, so put half of those (1/4) back and try again.  Make sure you know which half is which!  Make sure to do this tests in a new world, because you will corrupt any existing world by changing the mods around.

**Comment by C0rish** [comment]
Ah okay thanks
