### ISSUE TITLE
Configurable Power/Energy Side on Machines

### ISSUE THREAD

**Issue by Mochnant** [micdoodle8/Galacticraft#1389]
It would be very helpful organizationally if power would be accepted from whatever side sends it, rather than the left side only.  Baring that, accepting it from the back would allow a much tidier/denser workshop layout.

It's not as noticeable when using the mod's generators, but once external power is used the routing of power lines is difficult.

Thank you.

**Comment by radfast** [comment]
Suggestions go on the forum, not here please.
http://forum.micdoodle8.com/index.php?forums/suggestions.7/

**Comment by Mochnant** [comment]
That's unusual, every other mod I have ever found on github tracked suggestions and enhancements in the tracker here.  You mod, though, so your rules.  That said, I'm sure I am too lazy to go register at a forum to suggest this, so I'll have to let this closed issue stand in place of any forum post.  Regards.
