### ISSUE TITLE
[Implements Request] Fix parachest texture

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#1391]
![parachest](https://cloud.githubusercontent.com/assets/6128413/5800277/140b38c2-a00f-11e4-86a0-b8f6215e616f.png)

@radfast  Please replace this texture. I try to fix #1384 and now that work!

**Comment by EzerArch** [comment]
Good, it's a quick-fix. It looks better now, but the model still has bad UV wrap.

![2015-01-19_11 27 20](https://cloud.githubusercontent.com/assets/6743303/5801135/c69c8a4a-9fce-11e4-98cd-1528ee4a77e3.png)

**Comment by micdoodle8** [comment]
Fixed via 985077dbc18da2355f15572df830b11c9dbf50d4
