### ISSUE TITLE
[3.0.7.252+ only]  Loss of regular player inventory items on death

### ISSUE THREAD

**Issue by radfast** [micdoodle8/Galacticraft#1395]
I've seen one report of a loss of player items on death, if the player is also equipped with Galacticraft items (e.g. Oxygen gear).  Seems it's only in the latest builds, 3.0.7.252 or later.

Please can anyone else who experiences this issue post up here, as I need to understand whether it's affecting all players or just a few.

If posting, please mention:
* whether single player or on a server
* which Forge version
* which Galacticraft version
* anything else which may be relevant to inventory, for example the "keep player inventory on death" Minecraft options setting on a server

**Comment by Cracks777** [comment]
Ive also had this ill get more info on it.

**Comment by radfast** [comment]
Fixed in new build 3.0.7.256
