### ISSUE TITLE
GC3 r256: Ghost rockets on world reload

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#1399]
This is a major and gamebreaking bug.

The game is spawning ghost rockets if you reload your world just after you have landed with a real rocket (by Launch Controller) or with parachute. This ghost rocket spawns at the same coord from the previous dimension you came from and descends with no player inside.

Even if you go from dim A to dim B by Launch Controller and land safely with your rocket on dim B, if you reload the game a ghost rocket is spawned in the sky and slams itself onto the ground.

Details in the video:

**Video:** http://www.twitch.tv/ezerarch/c/5941349

EDIT:

Re-tested with no other mods, except JorneyMap and NEI. The same problem happens.

**Comment by Cracks777** [comment]
list of mods are you using?

**Comment by EzerArch** [comment]
JourneyMap5.0.1_Unlimited_MC1.7.10.jar
CodeChickenCore-1.7.10-1.0.4.29-universal.jar
NotEnoughItems-1.7.10-1.0.3.74-universal.jar
Galacticraft-Planets-1.7-3.0.7.256.jar
GalacticraftCore-1.7-3.0.7.256.jar
MicdoodleCore-1.7-3.0.7.256.jar

**Comment by radfast** [comment]
I haven't reproduced your rocket re-landing / explosion issue in 10 tests, though one time the rocket which had just landed on the pad, was missing after relog.

(I am of course sometimes seeing the issue where the rocket "lands" 2 or 3 blocks higher than the pad level, it's intermittent.   Though I'm well aware of this issue, I have not been able to figure out the cause in the code ... yet.)

Please list steps to reproduce, with exact timing of the logout.  Do you press SHIFT to exit the rocket first?  What percentage of the time do you see the issue?  Are you playing on a server or SSP?  (I'm testing on a locally set up Cauldron server which is my usual testbed.)

(I know you made a vid but I still have issues playing your twitch.tv, it spends most of the time buffering.)

**Comment by EzerArch** [comment]
Reproduced with a brand new world, single-player world:
- launch pad
- placed a Tier 3 rocket (Pre-fueled)
- lift off
- map select: Mars
- landed on Mars with Landing balloons
- new launch pad exactly at the landing point
- placed a Tier 3 rocket
- lift off
- map select: Overworld
- landed on Overworld with parachute and parachest (containing the rocket)
- then, after about 30 seconds, saved and quit to Title
- then, after about 30 seconds, reopened the same world
- looked up. Nothing happened.

Continuing, now with launch controller:
- launch pad + launch controller (freq: 1, dest: 2, keep the pad)
- placed a Tier 3 rocket (Pre-fueled)
- lift off
- map select: Mars
- landed on Mars with Landing balloons
- new launch pad exactly at the landing point + launch controller (freq: 2, dest: 1, keep the pad)
- placed a Tier 3 rocket
- lift off
- map select: Overworld
- rocket descend.
- landed on Overworld 3 meters above the pad
- dismounted, didn't break the rocket
- then, after about 30 seconds, saved and quit to Title
- then, after about 30 seconds, reopened the same world
- looked up. Nothing happened.

Continuing with launch pad on both dims:
- launched from overworld
- landed on Mars, 3 meter above the pad
- broke the rocket
- placed it on the pad
- lift off
- descent
- landed on overworld, 3 meter above the pad
- dismounted, didn't break the rocket
- then, after about 30 seconds, saved and quit to Title
- then, after about 30 seconds, reopened the same world
- looked up. I see 4 smoke trails from the sky down
- after 30 seconds, another rocket slams on the ground next to me. The other rocket is still on the pad, floating 3 meters.

**Comment by EzerArch** [comment]
With both Launch Controllers enabled, I tried to:
- dismount the rocked with right-click or LSHIFT, followed with world reload: ghost rocket, 100%
- dismount the rocked with right-click or LSHIFT, and break the rocket, world reload: ghost rocket, 100%

Then I launched from OW to Mars, disabled the Mars Launch Controller, lift-off, landed with parachute on OW, reloaded the world, the smoke trails appeared for 10 seconds and then disappeared. It tells something.

**Comment by radfast** [comment]
hmm that's very strange.  Thanks for the steps to reproduce, I will test more and see if I can get this to happen.

**Comment by EzerArch** [comment]
My guess: the bug may have something to do with Launch Controllers' chunk loaders. The old entity (the ghost rocket) doesn't get properly removed from a chunk which is still loaded. Reloading the world "revives" the old entity as a full working rocket.

**Comment by radfast** [comment]
oho, nice thinking it could very well be that.  Once I manage to reproduce the issue (I'm not currently on my test PC) that will be the first thing I test.

**Comment by radfast** [comment]
@EzerArch there's a good chance this has have been fixed now, either by the recent changes in GC 420, or by https://github.com/micdoodle8/Galacticraft/commit/2675afc95dcc02847f87d968c97bec29c46fca26

When you have time would you mind testing this again?  I'm not seeing it happening in my tests.

**Comment by EzerArch** [comment]
> When you have time would you mind testing this again?

Sure!

(Replying to remind later)

**Comment by EzerArch** [comment]
![2016-02-05_00 06 14](https://cloud.githubusercontent.com/assets/6743303/12836032/509af1f6-cb9c-11e5-9262-5e5e308da347.png)
Today the sky is clear, on the Overworld and on Mars. No forecast of falling rockets. :+1: 

Confirmed, tested in 440.

**Comment by radfast** [comment]
Great news.  I think the recent stability improvements for Launch Controlled rockets fixed this too :)

**Comment by EzerArch** [comment]
I think I'm gonna close it, since I can. ^^'
