### ISSUE TITLE
Planet Map: Gas Giants (Saturn, Uran, Neptune) No rings!

### ISSUE THREAD

**Issue by BlesseNtumble** [micdoodle8/Galacticraft#1400]
Gas giants are no rings, although they are in the files.

![Image](https://pp.vk.me/c619726/v619726755/1886b/nrERJXaD6p8.jpg)

In the center - Saturn
As you can see - no rings

**Comment by micdoodle8** [comment]
This is the Saturn "Celestial Object" from the core mod, or a new Saturn you've added?

**Comment by radfast** [comment]
I think @BlesseNtumble means this: https://github.com/micdoodle8/Galacticraft/blob/master/src/main/resources/assets/galacticraftcore/textures/gui/celestialbodies/saturnRings.png is unused

(see also Galacticraft T-shirts! http://i.imgur.com/KQ6t662.jpg )

**Comment by micdoodle8** [comment]
Oh I see, I didn't even notice they weren't there in the main mod...

Thanks
