### ISSUE TITLE
Mekanism universal cable conne. to heavy al. cable

### ISSUE THREAD

**Issue by Huplok** [micdoodle8/Galacticraft#1403]
Hi guys,
I have a problem with connecting GC heavy al. cable together with mekanism universal cable.
First time it happens in normal mc world, so mcedit save it.
Now i was on moon dim. and after crash, mc does not seems to load the map in list on start menu (and mcedit too).
log (from the second): http://pastebin.com/P9w0e7f1

(Sorry for my english, i'm the worst ever :D)
Have a good day and thx for replays

**Comment by radfast** [comment]
It is not intended for GC Heavy Aluminium Wire to connect directly to Mekanism cable or other mods' cables.  Please use a block - for example, Energy Storage Module - to make the connection.

I think you must use MCEdit to break the connection before you can load the world.
