### ISSUE TITLE
Can't automate heavy-duty plates with Elec. Compressor and vanilla hopper.

### ISSUE THREAD

**Issue by TheJulianJES** [micdoodle8/Galacticraft#1404]
Minecraft: 1.7.10
Forge: 10.13.2.1277
MicdoodleCore: 3.0.6.250
GalacticraftCore: 3.0.6.250
Galacticraft-Planets: 3.0.6.250

**Comment by radfast** [comment]
Did you do this:
http://wiki.micdoodle8.com/wiki/Electric_Compressor#Automation

You need to lay out the ingredients on the grid correctly to start with.
Automation will stop working if the grid is empty.
