### ISSUE TITLE
Spaceship name localization missing

### ISSUE THREAD

**Issue by Cobra1117** [micdoodle8/Galacticraft#1405]
The cargo rocket and tier 2 ship seem to be missing localization--on the display screen they show up as "entity.GalacticraftMars.CargoRocket.name" and "entity.GalacticraftMars.SpaceshipT2.name".

Tested with:
Forge: 10.13.2.1277
Galacticraft: 1.7-3.0.8.257

**Comment by radfast** [comment]
Thanks for reporting, and thank you @Adaptivity for spotting this and responding so quickly, wow!

The update will be included in next build .258  (probably we won't make that build today though, there are a couple of other things)
