### ISSUE TITLE
Feature request: Make oxygen gear activate when swimming

### ISSUE THREAD

**Issue by Cobra1117** [micdoodle8/Galacticraft#1413]
It would be nice if oxygen gear activated when swimming so that it could be used as scuba gear.

**Comment by radfast** [comment]
Just to be clear about this, "Feature request" = suggestion, and suggestions belong on the Suggestions area of the forum.  This is a suggestion that has already been proposed and discussed there.

**Comment by Cobra1117** [comment]
Ack. My apologies for posting it in the wrong location!

You may want to mention that in the original post in the MinecraftForum thread so that people don't post in the wrong location. (Various mod authors have widely differing preferences for suggestions, so folks don't always know where to post them!)
