### ISSUE TITLE
All Moon blocks have the same blast resistance

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#1417]
All Moon blocks ``tile.moonBlock`` have the same blast resistance, very low. None of them can stand the impact of a meteor or the explosion of a TNT.

It hasn't been like this before: #981

It doesn't matter if you use Moon Turf or Moon Dungeon Brick as building block in your base, a meteor can open a 3x3 hole in your base with impact.

EDIT:

Let me be nosy:

* I found where the problem is: [BlockBasicMoon.java#L123](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/blocks/BlockBasicMoon.java#L123)
* Now compare with [BlockBasicMars.java#L94](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/planets/mars/blocks/BlockBasicMars.java#L94).
* BlockBasicMars.java sets a special blast resistance for both Mars Dungeon Brick (metadata 7) and for the dungeon spawner (10), but BlockBasicMoon.java sets a blast resistance only for the dungeon spawner (15).

Hope I did it right: https://github.com/micdoodle8/Galacticraft/pull/1418

**Comment by EzerArch** [comment]
Just a small comment: How is this possible? [BlockBasicMoon.java#L161](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/blocks/BlockBasicMoon.java#L161)

````
if (meta == 14)
{
return 4.0F;
}
if (meta > 13)
{
return -1F;
}
````
14 is greater than 13 too. I think ````if (meta > 13)```` should be replaced with ````if (meta == 15)````.

**Comment by radfast** [comment]
Either one works, but ```if (meta > 13) ``` is one less character for the coder to type.  :)
