### ISSUE TITLE
Exception GT and GC ? 

### ISSUE THREAD

**Issue by hanakocz** [micdoodle8/Galacticraft#1419]
GT version 5.07.07
GC version3.0.7.256

https://www.dropbox.com/s/rvqjhxeokro0f21/exception.txt?dl=0

Just need to know what is this about...

**Comment by radfast** [comment]
Are you getting that on a __server__?

If so, it's either a bug in another mod (ComputerCraft suspected) or maybe a Forge bug.  See #1377 which is the same issue.  I think this is not an issue in either GC or GT.

**Comment by hanakocz** [comment]
Yes server. And we have no ComputerCraft. I can give you whole list, but still thanks for response. 
If it is okay on GC side, then good :) Better false flag than letting some bug escape :P

**Comment by radfast** [comment]
Something (not Galacticraft) is telling the server to run client-side code.  You did not say, but is this only happening in a shutdown phase when there are 0 players online?

One idea could be to try to figure out which mods you have which are the same as in #1377.  But it could be a Forge / Cauldron bug like I mentioned.

**Comment by hanakocz** [comment]
Well, the server had a lot of players, maybe nearly full at that time. 
As #1377 , We run Java 8, Cauldron based on 1231 Forge, I seen it first time ever and it did not had any impact on performance or so ...
I will try to get some answer from Greg also, maybe he will see something in it.

**Comment by radfast** [comment]
If you want to explain the issue to Greg, the problem here is that FMLCommonHandler.instance().getEffectiveSide() is returning Side.CLIENT on a server.  That should be impossible.

https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/entities/player/GCPlayerHandler.java#L102

**Comment by radfast** [comment]
hmmm, this guy (who I rate) says that FMLcommonHandler.instance().getEffectiveSide() is "not robust in all situations".  http://greyminecraftcoder.blogspot.co.uk/2015/01/the-client-server-division.html
I'm not sure what that means, but I guess he knows.

I'm looking at whether we can change this.

**Comment by radfast** [comment]
This issue should be fixed in the next version.  I don't think you need to trouble Greg with this now.

**Comment by hanakocz** [comment]
Well, I just posted it in GT forums, if anybody sees in it something, just IMPROVE can be made :) 
But it is funny how "looks like nothing wrong" can turn into "fixed in new verison" :) 
I just need to learn write my own code so I can help more than just posting logs, but.....so low time for that :/

**Comment by radfast** [comment]
I guess you can ask GT if they use multi-threaded code (which can cause this type of issue, though really it's a Forge issue) but really you don't need to raise it at GT now, I coded GC in a different way so that the issue now cannot arise.

**Comment by hanakocz** [comment]
I don´t think GT uses multi threading, that I think is jsut a big dream of everyone ...

However, I mabye got an idea how it could happen....we have some stuff from GC minetweaked so it is made inside GT machinery, so probably there? No other idea..
