### ISSUE TITLE
OFFICIAL: Known Issues - and general guide to posting issues on the Github  <---- ** READ FIRST **

### ISSUE THREAD

**Issue by radfast** [micdoodle8/Galacticraft#1420]
This is a list of known issues in the latest build of Galacticraft 3, in addition to the other currently open issues in this Issues list.  Get the latest build here: http://micdoodle8.com/mods/galacticraft/downloads (the 'Latest' build in red).

_Posting new issues - guidelines:_  [Please read in full](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md)

Suggestions and Feature Requests belong on the [official forum](http://forum.micdoodle8.com/index.php?forums/suggestions.7/) - not on the Github.
## I see a lot of open issues - does anyone read the issues list?

For sure.  Issues are being fixed all the time, and the goal is to fix all issues eventually.  Any issue which is causing crashes, item loss, or serious incompatibility with another mod (loss of playability) is prioritised.

Sometimes an issue is flagged 'missing info' - that means we cannot fix it without more information being provided.
## Compatibility

We think it is very important that Galacticraft is stable, compatible and works well in modpacks, especially when combined with technical mods or other popular mods.  Because Galacticraft is a large, powerful and complex mod and makes quite a few 'under the hood' changes to how Minecraft works and how things look, and because the aim is to be 100% compatible with everything, this can be quite a challenge.  More compatibility notes can be found here: http://wiki.micdoodle8.com/wiki/Compatibility 
## Compatibility issues
-  Sealed Applied Energistics cables are not working properly
## Space Stations
-  You cannot walk "up" stairs on a space station, you become stuck
-  You cannot go "down" ladders on a space station
-  Rotating Space Stations - blocks not connected to the space station will rotate as well
-  Mekanism Jetpack and MMMPS (Machine Muse's Modular Power Suits) do not currently work in space

(Link to old thread: #791)

You can post comments and replies here but be warned they may become irrelevant as the known issues get fixed.  Irrelevant and off-topic comments _will be deleted_.

**Comment by dj3520** [comment]
Quick question. Methane synthesizers don't work inside sealed areas. This could be intentional due to the inability to collect Co2 in an o2 environment, but could also be accidental because an 'air' block is blocking the valve. If this is intentional, the oxygen bubble distributor does not have this same effect. If non-intentional, I've brought it to light then.

**Comment by EzerArch** [comment]
> Methane synthesizers don't work inside sealed areas.

I think this is intentional, Methane synthesizer must be exposed to CO₂-rich atmospheres to directly collect CO₂ from air. Otherwise, use Fragmented Coal. I'll add this in the wiki if confirmed.

**Comment by radfast** [comment]
100% intentional.  Inside a sealed space, the atmosphere is not "rich" in CO2.  (And yeah, I don't know the markup language to get that nice subscript...)

Thanks for bringing up that the Methane Synthesizer is still sucking in CO2 inside an Oxygen Distributor bubble, I'll fix that.

**Comment by EzerArch** [comment]
>  (And yeah, I don't know the markup language to get that nice subscript...)

Just copy and paste: http://en.wikipedia.org/wiki/Unicode_subscripts_and_superscripts

**Comment by dj3520** [comment]
Another question. How do you obtain liquid methane? Normally converting gas to liquid would involve the Liquifier. But this makes fuel...

**Comment by radfast** [comment]
http://wiki.micdoodle8.com/wiki/Gases#Methane

**Comment by dj3520** [comment]
Ah, apologies. I'm working on new gas textures and couldn't find the method of obtaining liquid methane to test it's texture in a pipe.

**Comment by radfast** [comment]
Methane Synthesizer with Oxygen Distributor bubble is fixed in the latest build

**Comment by BBoldt** [comment]
Hey, can you add this as a 'known issue'?
https://github.com/micdoodle8/Galacticraft/issues/1180

People playing my modpack keep complaining about it because it's been causing deaths due to the screen popping up and taking over controls. I just want to be able to point people here to show that you guys know about it and haven't forgotten.

**Comment by radfast** [comment]
All issues listed in the Github list are "known issues".  We have not forgotten about this one.  But sure, if it helps you we can list it here too.

**Comment by skwerlman** [comment]
Not sure if you know this already, but if you have a file called ```CONTRIBUTING.md```, a link to it shows up as an alert when submitting an issue. You can put all the known issues and submission instructions in there for a bit more visibility.

**Comment by radfast** [comment]
I didn't know - that's great, thank you, will give it a try.

**Comment by radfast** [comment]
Closing this because it's no longer needed.   And because I'm close to getting sealed ME cables working.
