### ISSUE TITLE
Disabling spacestation creation not only on servers

### ISSUE THREAD

**Issue by Robijnvogel** [micdoodle8/Galacticraft#1424]
In the config files there is an option to turn off the ability for players to create a space station when they are on servers.

I am here to report that turning on this option makes creating space stations on single player worlds on single player worlds impossible as well. (I am using Forge 1.7.10 [...] 1240, with only Galacticraft, MicdoodleCore and GC Planets installed.)

1. Maybe this was the intention all along, but someone forgot to change the config text. 
2. If not, this probably has something to do with the mod being compatible with both Forge for 1.7.2 and 1.7.10. In between these two Forge versions, as you may know, Forge changed the way it determines is a server is really a standalone server or just a client "gone rogue :P ." In 1.7.2 it used "if World.islocal() == false" and in 1.7.10 it uses "if World.isremote() == true" or something like it. I have taken a glimpse at the classes in this repository and saw that you have probably written a workaround to bridge this gap. Now my guess is that either this workaround is not correctly functional, or it is in this case wrongly implemented. 

In any case, I suggest someone takes a look at it, because this might solve future problems before they arise.

**Comment by radfast** [comment]
Thank you.  This is intended behaviour.  In single player if you want to make a Space Station then obviously don't set the config option to disable it.

The "on servers" message means that in a multiplayer game disabling / enabling this on a client will have no effect.

**Comment by Robijnvogel** [comment]
Dear radfast, as I tried to explain, this config option DOES have effect on a client if you change it.
