### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by vavraCZe** [micdoodle8/Galacticraft#1426]
Permissions for /ssinvite and /ssuninvite doesn´t work correctly.

From wiki:
micdoodle8.mods.galacticraft.core.command.GCCoreCommandSpaceStationAddOwner
micdoodle8.mods.galacticraft.core.command.GCCoreCommandSpaceStationRemoveOwner

When is micdoodle8.mods.galacticraft.core.command.* in PEX, then these command work correctly. I try use micdoodle8.mods.galacticraft.core.command.CommandSpaceStationRemoveOwner like https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/command/CommandSpaceStationRemoveOwner.java but nothing... 

Build 257
Latest Cauldron 1.7.10

**Comment by radfast** [comment]
Sounds like it's just a naming issue.

Please search your ```fml-server-latest.log``` for the correct permission nodes for these commands.  (I guess search for "RemoveOwner" first?)   A server in startup will __always__ post the permission nodes in the server log, so you can see exactly what it should correctly be.

Do you have Wiki editing access (needs a registered email)?  If so then please edit the wiki to fix this.  If not tell us here the correct nodes and I will edit the wiki.

**Comment by vavraCZe** [comment]
You're right. From log:

http://hastebin.com/usuviqizek.avrasm

Please edit this in wiki. Registration doesn't work on the wiki :/

micdoodle8.mods.galacticraft.core.command.CommandSpaceStationAddOwner
micdoodle8.mods.galacticraft.core.command.CommandSpaceStationRemoveOwner

**Comment by radfast** [comment]
Thanks for the log.  Wiki now updated.
