### ISSUE TITLE
Server hang up when opening the Galactic Map

### ISSUE THREAD

**Issue by darkman1984** [micdoodle8/Galacticraft#1427]
If someone on the Server opens the Galacticmap the Server CPU Load is going to 100% and the RAM is starting to get full. Don't know exactly why this happens.

**Comment by radfast** [comment]
Please post the server log from the time when this happened

You said there was a crash?  Please post the crash report.

**Comment by darkman1984** [comment]
Thats the Problem. There is nothing in the log. It seems that the server hangs up

**Comment by radfast** [comment]
> Please post the server log from the time when this happened

The log helps me to understand and reproduce your setup.  I will need to see it please, to take this issue any further.

**Comment by radfast** [comment]
Any update, @darkman1984 ?   You didn't even say which version of Minecraft + Galacticraft this is, or what other mods you have installed.

**Comment by radfast** [comment]
Closing due to lack of response in 1 month.  We can re-open if a log is provided.
