### ISSUE TITLE
evoled creeper bug

### ISSUE THREAD

**Issue by bdudek** [micdoodle8/Galacticraft#1428]
the evolved creeper boss is overriding the texture of the blizz from thermal expansion/foundation. it still acts like a blizz though.

**Comment by radfast** [comment]
Is this on a server or single player?

I think most likely it's not a Galacticraft bug, it sounds like Thermal Expansion is not registering the EntityID for the Blizz correctly.   Does Thermal Expansion allow you to set Entity ID numbers in the config?

**Comment by radfast** [comment]
Also which version of Galacticraft?  And which version of Thermal Expansion.

**Comment by bdudek** [comment]
sorry to bother you but after a few more tests that came to me over coffee i found out it was an id missmatch between the server and client i replaced both the server galacticcraft and te files with the client ones and it fixed the problem. sorry for bothering you.

**Comment by radfast** [comment]
No problem.   Out of interest, which GC versions was it, in case anyone else has the same issue?

**Comment by bdudek** [comment]
version 3.0.8.257
