### ISSUE TITLE
Invisibility Potion effects not handled properly in Thermal Padding

### ISSUE THREAD

**Issue by Korynkai** [micdoodle8/Galacticraft#1429]
It seems Galacticraft Thermal Padding does not handle vanilla Invisibility Potion effects properly. 

This was originally reported erroneously as a bug in the PowerSuits Active Camoflage module, however this module is based on the Invisibility Potion effect and I can only surmise this scenario simply wasn't caught within Galacticraft.

![2015-01-06_00 12 54](https://cloud.githubusercontent.com/assets/6743303/5623310/d65525dc-9538-11e4-8fc0-d66e6dcc5848.png)

Please refer to https://github.com/QMXTech/MachineMusePowersuits/issues/15 and https://github.com/MachineMuse/MachineMusePowersuits/issues/520 for more details.

**Comment by Korynkai** [comment]
Excuse the deleted reference, the issue is semi-related but I had noticed belatedly that was "GC3 200 and earlier" and we're at GC3 257

**Comment by radfast** [comment]
Deleted reference is fine, issue #1048 is not fixed yet so it's still open.

Please can you explain in words or pictures what you think should be happening, but is not happening - if possible without referencing MMMPS as I don't have that installed just now.

I mean: are you saying that with an invisibility potion the Thermal Padding remains visible, and you think it should become invisible?   Even though vanilla armor remains visible?  I actually don't have an opinion just now on which way the Thermal Padding should go on this, I will think about it...

**Comment by Korynkai** [comment]
Hmm, I see, well, that's the problem summed up right there, guess I should've checked the vanilla armor behavior first...

I suppose I must look a little deeper into MMMPS, it must look for whether or not the player has the invisibility potion effect and causes the entire suit to become invisible in such a case.

The issue was, when wearing Thermal Padding under the Powersuit with the Active Camoflage module installed and active, the Thermal Padding would still be visible... I then took a look at how the Thermal Padding itself behaves when using an invisibility potion without the Powersuit, and figured this was an error with the way Thermal Padding was handling the invisibility potion effect without realizing the vanilla armor does the exact same thing. Makes me feel kind of silly having posted this issue here in the first place... 

This means it is in fact more of a Powersuits issue and it would in fact be preferred to implement the Thermal Padding as a module to Powersuits, otherwise unnecessary hooks or functionality would be required for the Thermal Padding.

Thanks for your insight into this.

**Comment by radfast** [comment]
@Korynkai I did not pick up that you were maintaining the mod (guess I could have clicked on your Github profile, but I didn't :p ).  I'm happy to make contact with you.  I like playing the MMMPS mod myself those times I do get to play Minecraft.

I am more than happy to include code in Galacticraft specifically to improve compatibility with MMMPS.

I've thought about it and I'm happy to make the Thermal Padding invisible with an invisibility potion.  To my way of thinking the Thermal Padding is more like clothing than armour.  And a Minecraft skin's clothes go invisible with the potion, so Thermal Padding should do the same.

Galacticraft Oxygen helmet, gear and tanks will not go invisible, but I guess MMMPS has an alternative way of providing Oxygen anyhow?

So I think you will not need to code a Thermal Insulation module (and I'm not totally sure that we made thermal properties accessible through Galacticraft's API yet anyhow).

See also #1383 which is an open issue connected with MMMPS though I think it's one for me to solve.

**Comment by Korynkai** [comment]
@radfast I'm glad you're on-board and I'm definitely glad to have made contact with you, too! I'm glad you like the mod and I'm definitely hoping to hear from @MachineMuse again, I suspect she's probably busy and has problems getting to maintaining MPS, however... How should I put this... First we made one change to allow a tiny inter-mod fix for MPSA... then another change for something else... Then that change leads to another and before you know it a tiny change leads to an avalanche of changes.... And all the while our group is working on another rather large project that doesn't even involve Minecraft we end up taking maintenance duty on, not one, but three mods (Numina, MPS and MPSA) :lol: We are definitely hoping the Forge modding community and other developers will benefit greatly from our projects though and I am very happy to maintain these great mods out of respect for the community, even when MachineMuse returns.

Regarding this issue and its initial context, some thoughts regarding it are located at https://github.com/QMXTech/MachineMusePowersuits/issues/15#issuecomment-73345180

Regarding https://github.com/micdoodle8/Galacticraft/issues/1383, if I can help in any way, please let me know.

Reopening this to indicate this hasn't been resolved (as you indicated?)
