### ISSUE TITLE
Fire not appear on mob in a planet with Oxygen gas

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#1432]
![2558-02-07_16 02 48](https://cloud.githubusercontent.com/assets/6128413/6092030/f5e5438c-aefb-11e4-9d52-8bb5291bd04a.png)

**Comment by radfast** [comment]
Fixed in latest commit, thanks for spotting this.

I made it so the mob can burn if there is either BreathableAtmosphere or IAtmosphericGas.Oxygen present.  In this case, that is correct - things can burn in the presence of oxygen, even if the atmosphere is poisonous to living creatures.
