### ISSUE TITLE
[Add-on] No raining particles and Enderman not affected the rain

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#1435]
![2558-02-07_10 12 38](https://cloud.githubusercontent.com/assets/6128413/6096522/5c758126-afc8-11e4-988a-4105538e7e4f.png)
![2558-02-07_10 20 38](https://cloud.githubusercontent.com/assets/6128413/6096523/5ca58632-afc8-11e4-8374-be650336c73c.png)

**Comment by Alex-the-666** [comment]
could this possibly be a vanilla bug?

**Comment by EzerArch** [comment]
My guess: because rain particles themselves don't hurt Enderman, but if both of the following conditions are met: there is no block above its head and the world variable that tells if it is raining is true.

**Comment by micdoodle8** [comment]
I can't see this being a Galacticraft issue, but please re-open if there's any more info that leads you to believe it could be.
