### ISSUE TITLE
Sludgeling AI bug

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#1436]
Here : https://www.youtube.com/watch?v=Cp_Jw-lzyRs

**Comment by EzerArch** [comment]
You want to mean, switching to peaceful mode will not remove existing Sludgelings if Optifine is installed.

Please confirm my statement above.

**Comment by micdoodle8** [comment]
Please test in the same environment with silverfish. Most of the code is derived from the silverfish code, so it's likely that the bug will also exist with them.

**Comment by EzerArch** [comment]
I think this issue can be closed.

Sludgelings work with OptiFine (D3 and D4) and without OptiFine installed.
