### ISSUE TITLE
Added FastCraft on server, not loaded -> GC has also some problems in log

### ISSUE THREAD

**Issue by hanakocz** [micdoodle8/Galacticraft#1440]
Hi,
can you look at this? Dunno if it is error here or on Player' s side, but posting...you have quite big part of log with GC :)
https://www.dropbox.com/s/vk5k0cvvyzztm37/latest.log?dl=0

**Comment by radfast** [comment]
It's a FastCraft issue, not a Galacticraft issue.  See this line in the log:
> at fastcraft.asm.FastCraftTransformer.transform(F:229)

The prior line:
> [20:42:11] [main/INFO]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1764]: Galacticraft successfully injected bytecode into: sv (1 / 1)

is not the cause of the error - when that line is printed, it shows Galacticraft has already finished its bytecode injection error-free (if it says 1 / 1 that means there was no error).

To give more detail, at this part of your log, Galacticraft and Fastcraft here are both, one after the other, making bytecode injections in class "sv" which is EntityLivingBase.  Galacticraft is doing it first.  But I don't see that the Galacticraft changes can possibly be the cause of Fastcraft not working.  (If that is the reason, then Fastcraft should be able to fix it by making their bytecode transformation a little more flexible.)

Our bytecode injection in EntityLivingBase is making just one small change, it's in the moveEntity() method, replacing Minecraft's standard gravity value of 0.08D with a call to a Galacticraft method which gives a different gravity value on different planets.

If you are reporting this to the Fastcraft devs, please give them this link them to our code here:
https://github.com/micdoodle8/MicdoodleCore/blob/master/src/main/java/micdoodle8/mods/miccore/MicdoodleTransformer.java#L686-709

**Comment by hanakocz** [comment]
Well, Player (author ) had just : "Cauldron is not supported" :D So the problem is incompability Cauldron -> Fastcraft, yes...jsut put it here if you can get something from it, you know, other mods did not wrote it :)
