### ISSUE TITLE
parachute rendering with SmartMoving

### ISSUE THREAD

**Issue by N247S** [micdoodle8/Galacticraft#1441]
Hey, I'm curently busy building a modpack. I added galacticraft and more planets to it along with smartmoving (wich might cause this bug). and I noticed that when you parachute down, the parachute isnt showing.
I dont take falldamage and I dont get the fall animation from smartmoving, but it isnt 'sitting' either. right clicking the parachute or remove it while falling isnt affecting anything.
I'm using MC 1.7.10 with galacticraft version 3.0.8.261

**Comment by radfast** [comment]
Which version of SmartMoving?  And I guess you do you have RenderPlayerAPI and SmartRender installed on the client?

**Comment by N247S** [comment]
The system of smartmoving has been changed slightly. The RenderPlayerAPI isnt required anymore and the smartmoving mod is splited up into three separete mods. So here is the list of all of them:

PlayerAPI 1.7.10-1.1

Smart Moving 1.7.10-15.2
SmartCore 1.7.10-1.0
SmartRender 1.7.10-2.0

**Comment by radfast** [comment]
do you know if it worked OK with the previous version of SmartMoving?

**Comment by N247S** [comment]
I've never used it with previous versions so I honestly dont know. But I could test it, do you mean previous versions for MC 1.7.10, or previous MC versions?

**Comment by radfast** [comment]
If you have time, would be great if you can test SmartMoving 15.1 and 15.2 both __with RenderPlayerAPI__.   (SmartMoving says RenderPlayerAPI is "optional", but I think it will help with this issue.)

**Comment by N247S** [comment]
I've tested both versione with RenderPlayerAPI, and it doesnt make a difference unfortunatly. also a small suggestion for improve the survival change. when you parachute you're not able to move, so when youre unlucky to spawn above a lava pool, youre screwed. maybe you could add this feature

**Comment by radfast** [comment]
OK thanks for testing, I'll look for a fix - will take some time, like 1 - 2 weeks, so please be patient.

**Comment by N247S** [comment]
Oke, no problem. thanks for the reply.

**Comment by babybasher** [comment]
I see this is an old post, and the OP probably fixed their issue.  However I had the same problem too.  Oxygen gear wasnt rendering on players, and couldn't see the parachute.  What fixed the issue for me was installing RenderPlayerAPI and RenderPlayerAPIEnhancer.  

Below are the versions i'm currently using.

PlayerAPI-1.7.10-1.2
SmartMoving-1.7.10-15.3
SmartCore-1.7.10-1.0
SmartRender-1.7.10-2.1

RenderPlayerAPI-1.7.10-1.3
RenderPlayerAPIEnhancer-1.7.10-1.3

**Comment by radfast** [comment]
@babybasher thank you, I think that means we can close this.

I've added the information to the wiki:
http://wiki.micdoodle8.com/wiki/Compatibility#Smart_Moving

**Comment by radfast** [comment]
@N247S  if you are making a modpack, make sure to update Galacticraft from time to time.  Currently version 3.0.11.306 fixes a __lot__ of minor stability issues, it's strongly recommended for modpacks.

**Comment by N247S** [comment]
oke, sure I will. I have my modpack ready except for one mod. when thats finnished I'm updating all mods at once, and publish it!

**Comment by radfast** [comment]
Great stuff, but I mean you will need to update your modpack sometimes _after_ you publish it!  Anyhow, better let you publish it first.
