### ISSUE TITLE
[Minor] Gas Liquefier shows liquid connection on front

### ISSUE THREAD

**Issue by dj3520** [micdoodle8/Galacticraft#1443]
The Gas Liquefier shows a liquid connection on the front of the machine although pumping in/out does nothing. The picture shows the connection done via iron pipe (gray.)

![image](https://cloud.githubusercontent.com/assets/8284194/6141772/46b38da4-b178-11e4-863b-4dcbb5969ab2.png)

GC3.0.8.261 w/ planets.

**Comment by radfast** [comment]
thanks, I'll take a look

**Comment by dj3520** [comment]
Just did this test on top and bottom and included Water Electrolyser and Methane Synthesizer.
*All sides posses pipe connectivity.*
Fixing this means disabling top, front & bottom for all, as well as the rear of the Methane Synthesizer.
Also, the Gas Liquefier does not have it's output sides marked via red dot.

**Comment by radfast** [comment]
This does not occur in my testing.  Using an older version of Buildcraft, fluid pipes do not connect to those sides.

This therefore __appears__ to be a bug in the version of Buildcraft you are using.  Please can you test this more widely: test Buildcraft pipes with fluid-handling machines from other mods, and test fluid pipes from some other mod (for example, Thermal Expansion or Mekanism) with the Galacticraft machines.

Closing for now as this seems not to be a Galacticraft issue, but I will keep an open mind and re-open this if it starts to look like it is a Galacticraft issue.

**Comment by radfast** [comment]
It's intended that the Gas Liquefier does not have its fluid output sides marked, as you cannot connect to those sides using "vanilla" Galacticraft, only if you have some other mod installed.

**Comment by dj3520** [comment]
>you cannot connect to those sides using "vanilla" Galacticraft, only if you have some other mod installed.

I hate to point this out, but the fuel loader, refinery, and cargo loader/unloader don't follow this idea. The marked side serves to aid the player.

**Comment by radfast** [comment]
You're right on those markings, but still I don't like it, it's potentially confusing for players who do not have access to fluid pipes, and I don't like it on those older machines either.  Maybe we should be looking at a more discreet graphic which is similar across all those types of machines to show where pipe connections _can_ be made.

**Comment by dj3520** [comment]
Perhaps we detect piping mods and display the graphics if detected? Though this might become complicated.

I see your point but for those who are just starting off it's a bit confusing that the output isn't marked.

**Comment by radfast** [comment]
I will look at that, @dj3520, added to my list.  Detecting piping mods is not the easiest as it would have to be done by name and we would miss any new ones.  I'm likely to go for a more discreet marking.  This might be GC4 only.

Any feedback on the original bug reported here?

**Comment by dj3520** [comment]
Confirmed GC not at fault via Mekanism.
Problem in Buildcraft 6.4.0
Thank you and apologies for the finger pointing.
