### ISSUE TITLE
DragonAPI wiki entry out of date and misleading; wiki does not allow creation of new account

### ISSUE THREAD

**Issue by ReikaKalseki** [micdoodle8/Galacticraft#1445]
The ["Compatibility"](http://wiki.micdoodle8.com/wiki/Compatibility) page on the wiki says "DragonAPI is, once again, causing issues with Galacticraft 3. It's because DragonAPI includes an out-of-date version of the Galacticraft API (and loads it first - it really should not be doing that). "

This is no longer true, and has not been for months, as it was fixed in the v3 release that saw my API shipping needs almost entirely eliminated, but I still get many people coming to me and asking (or complaining or deriding) to me based on the information on the wiki.

I would fix it myself, but the wiki will not let me create a new account, instead taking me to a white page when I click "create account".

**Comment by radfast** [comment]
@ReikaKalseki thanks for looking in and thanks for the update

I did not know this was fixed, that's good news for players and I'm sure someone will update the GC Wiki now appropriately, if not then I'll fix it next time I'm on the wiki.

I'm not sure why Wiki account creation is not working, we'll have to look into that.

**Comment by EzerArch** [comment]
> I'm not sure why Wiki account creation is not working, we'll have to look into that.

My guess, the CAPTCHA is not working. Hence why I have to ask you to fix external links for me.

**Comment by radfast** [comment]
Could be, I'll mention it to Tyrantelf

**Comment by radfast** [comment]
Wiki now edited.
