### ISSUE TITLE
When Will I be Getting My Galacticraft Cape I donated $5 Last Thursday its now a week from then.

### ISSUE THREAD

**Issue by Krazymonkey151** [micdoodle8/Galacticraft#1447]
I am Krazymonkey151 and i asked for cape 14 please reply and get it to me asap.

**Comment by micdoodle8** [comment]
Apologies for the delay, I was on vacation. You should have your cape now, thanks for the donation!

**Comment by Krazymonkey151** [comment]
No problem I got the cape thanks alot mic :D
