### ISSUE TITLE
[Add-on] Why oil is generated in my planet?

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#1449]
![2558-02-13_15 56 24](https://cloud.githubusercontent.com/assets/6128413/6187321/ab60cf8c-b3b7-11e4-8ed5-dce52fb95d4a.png)
![2558-02-13_15 56 04](https://cloud.githubusercontent.com/assets/6128413/6187322/ab98f59c-b3b7-11e4-8769-91e518be0742.png)

I don't config the oil gen in external dimension.

**Comment by radfast** [comment]
I'll take a look.  One quick question: does your planet worldgen use any of the vanilla worldgen code for the Overworld?

Nice Xray screenshot, I <3 the new shape of the oil reservoirs.

**Comment by radfast** [comment]
I think commit b2559df will fix this.

If you want oil generation on any of your planets in future, just add them in the config for this list:
>    I:"Oil gen in external dimensions"
