### ISSUE TITLE
Slimeling unwilling to sit, cannot shorten name, and not showing post-feeding GUI

### ISSUE THREAD

**Issue by perkinslr** [micdoodle8/Galacticraft#1450]
I'm running galacticraft built from git revision ec97b242e5312fada12cfc0a30858de4ad172095.  

The sit/stay button in the slimeling GUI is disabled, and when I feed them I don't see any extra popup to let me pick healing et cetera.  Also, while I can type into the rename box to lengthen the name, backspace makes the name flash red, but not shorten, so I can't actually rename them...  The git version I'm using is from the 9th of Feb, so 4 days ago, the last time the slimeling file changed was 14 days ago, so I doubt this issue's been changed since I updated galacticraft.  If I get a bit of free time, I'll maybe poke at it and see if I can patch it, but I thought I'd let you guys know what I found.

**Comment by radfast** [comment]
I just now tested Galacticraft built from the current git master and I am not seeing the issues you describe.
* I can rename my slimeling, even to a short name like 'o'
* Backspace key works fine
* Sit/Follow button in the slimeling GUI works fine.

Are you running this in a de-obfuscated environment (e.g. from inside Eclipse?)  That could explain a difference in behaviour.  Please do also try out a download of a regular obfuscated version of the mod (grab 3.0.8.264 from the Jenkins here: http://ci.micdoodle8.com/job/Galacticraft-1.7/264/) and see if the same issue occurs.

If it is that, and if you do have time to track this down and figure out what it is (for a start, I would like at our VersionUtil code for a de-obfuscated environment) then of course that would be greatly appreciated.  But I would suggest this is not a game-breaking issue if it is only occurring in a de-obfuscated environment.

**Comment by EzerArch** [comment]
> Sit/Follow button in the slimeling GUI works fine.

It does, but in some cases it doesn't. For example, slimeling won't sit if its owner has been attacked by a mob, it won't sit while the offender is still alive. The same goes for tamed wolves: they won't sit for a period of time if their owners were recently attacked, or because the offending mob is still alive. I had to reload the world several times because I couldn't make those *idiots* sit.

Isn't it because slimelings share the vanilla wolf code?

**Comment by radfast** [comment]
Yes, slimelings are like wolves - seems reasonable that they won't sit if the owner is being attacked.  Are you saying they should be more obedient?

**Comment by EzerArch** [comment]
> you saying they should be more obedient?

No, just saying that slimelings refuse to sit as wolves will not either. Perhaps @perkinslr was facing the same situation and a world reload could help.

(Also, it would feel *so* wrong that a custom mob works better than a vanilla counterpart... j/k)

**Comment by perkinslr** [comment]
Okay, so I just now had time to poke at what exactly is going on, and I think it's not an issue.  No, it wasn't because I'd recently been attacked or from running in a deobfuscated environment.  I believe the issue came from it not thinking I was its owner, so I added a bunch of System.out.println calls to figure out exactly why that was the case, and restarted.  I discovered that my login access token had expired, which I think may be what caused the issue, because when I logged in again it went to working without issues.  The only remaining oddity is that, while it didn't think I was the owner, it didn't display the gui.slimeling.chat.wrongPlayer message to let me know I wasn't the owner.  

As far as acting like wolves, it would be kinda nice to be able to make them behave more like the iron golems to defend a base.  I like having the help keeping the local skeleton and zombie population under control, but having them follow me is bloody annoying. 

Oh, one other thing I can't really test myself, even when it thought I wasn't the owner, I could add on to the name, just not shorten it.  I don't know if that was because I really was the owner and it was just glitching, or if it will let you extend the names of slimes you don't own...  Someone may want to check that, but since I don't have other players around, I can't myself...

**Comment by radfast** [comment]
Thanks for confirming this is not an issue.

**Comment by dj3520** [comment]
I seem to be having this issue with GC v269
![image](https://cloud.githubusercontent.com/assets/8284194/6475713/6741a538-c1db-11e4-9bdd-cf8f6ceb9764.png)
Exactly what I did.
* Switched to survival quickly to punch the egg I spawned. I was getting hurt by lack of oxygen.
* Switched back to creative.
* This guy spawned.
* Clicked and opened GUI. Cannot shorten name but added 3 Es.

**Comment by radfast** [comment]
ok we should look at how you can add the 3 Es but nothing else, when in Creative.

**Comment by dj3520** [comment]
Backspace does make it blink red. But I am having the same problems as OP. No sitting, feeding, etc

**Comment by gotex007** [comment]
Having this issue with 1.7-3.0.12.357 (only version I've ever tried), but only on the server. The name cannot be backspaced (flashes red) but can be extended to the character limit, the following mode button is disabled and unchangeable (permanently stuck on follow), and feeding it its favorite food does not bring up the GUI even though it consumes the item. The eggs were found naturally on Mars, brought back to earth, and hatched there properly in survival. The single player eggs and slimes work perfectly fine.

Using forge 1.7.10-10.13.4.1492 if that's any help.

**Comment by perkinslr** [comment]
I checked the ownership by compiling a custom version that wrote the ownership information to the console.  Then I solved it by making the ownership check always return true.  It's not difficult to do, but it does take a bit of time to set up the development environment.

**Comment by gotex007** [comment]
Doing something like that is beyond my expertise. I just wanted to report it and hopefully have it be fixed so the slimelings aren't worthless.

**Comment by perkinslr** [comment]
Fair enough.  How did you acquire your slimelings?  If you use creative to summon them in, they don't reliably end up with the right ownership information.  

As for the bug, it may be worth adding a config option for SMP that makes them listen to everyone.  It would sidestep the bug, and on a non-competitive server, it's nice to be able to share ownership of the pets.

**Comment by gotex007** [comment]
As I said, they were found naturally on Mars (I didn't even know they existed until I got there) and brought to Earth to be hatched. However in single player I spawned the egg in creative, but hatched it normally in survival and it functioned properly.

Is the second part to me or a statement towards the developer? Because I wouldn't know how to do that since I wasn't able to find anything about slimelings in the config.

**Comment by perkinslr** [comment]
Hm, how did you bring them back to earth?  I never tried silk touch on them.  And yeah, the second part is a recommendation for how to reduce the impact of the bug.  Currently there isn't anything in the config for it.  

If I get some time this weekend I'll see about building the latest version with that as a config option.

**Comment by gotex007** [comment]
When you break it with a pickaxe the egg drops. Then I brought it back to Earth, sat it down, broke it with a barehand, and they hatched.
