### ISSUE TITLE
[Feature Request]: Minetweaker Support For Machines

### ISSUE THREAD

**Issue by Lanse505** [micdoodle8/Galacticraft#1457]
Hey o/

I can't seem to find if you already have minetweaker support for your machines or not, as a PackMaker I feel this would a really neat feature to play with ^^. Hopefully MT-Support can be added somehow if it already isnt in ^^

//Best Regards
Lanse

**Comment by radfast** [comment]
Any suggestion in this area belongs on the Suggestions area of the forum where it can be discussed by other forum members, and if there is a strong reason for it then we can look at it further.  If making a suggestion there, please explain why this support is necessary, i.e. what you want to change about the behaviour of our machines.

Closing.
