### ISSUE TITLE
"Flying" Cargo Rocket

### ISSUE THREAD

**Issue by BlesseNtumble** [micdoodle8/Galacticraft#1458]
![Image](http://firepic.org/images/2015-02/18/nouilfo6ywo6.png)

Build 262.

**Comment by EzerArch** [comment]
Sigh #563 and #1252.

**Comment by BlesseNtumble** [comment]
Other Rockets (Tier 1,2,3 ,etc) are normal.
![Image](http://firepic.org/images/2015-02/18/nk4cuicgx2bi.png)

**Comment by EzerArch** [comment]
Hmm?! Could you confirm this bug happens only with Cargo Rockets?

**Comment by radfast** [comment]
I will look at this.  Getting the rocket landing correct has been __surprisingly__ difficult, see other issues.  Part of the problem is that the exact positioning of the rocket "entity" can be a little different on the client and on the server, it's due to different tick rates etc.
