### ISSUE TITLE
Galacticraft UBC Ore Registration

### ISSUE THREAD

**Issue by Grim-Ascensions** [micdoodle8/Galacticraft#1463]
Not really an issue, more of a compatibilty question/request... Wasn't sure where to put it...

Was wondering if Galacticraft would be getting UBC Ore Registration sometime in the future. This would allow your aluminum, copper, and tin ores support other block types than stone.

More information on this can be found here:
http://minecraft.curseforge.com/mc-mods/227992-ubc-ore-registrar

Keep up the good work guys! We love it!

**Comment by radfast** [comment]
This seems more like a suggestion to me, so please make it here:
http://forum.micdoodle8.com/index.php?forums/suggestions.7/

I have not personally heard of UBC so I will need to understand whether this a widely used mod and which modpacks it's in.
