### ISSUE TITLE
Possible Oil Dupe bug with TE3 Liquid Transposer

### ISSUE THREAD

**Issue by sww1235** [micdoodle8/Galacticraft#1464]
I am running build #257 latest stable build, and I was attempting to use the liquid transposer from thermal expansion to extract oil out of filled canisters. When I placed the canister in the transposer and had the outputs closed on the transposer, the transposer would fill its internal tank, and then deposit an empty canister in the output. However it would leave the original filled canister in the input slot. When taken back out and then placed back in, the same cycle would happen, with a new empty canister being spawned each time. 

In addition, If I turned the output of the fluid transposer on when it was extracting the oil, it would continuously output to an attached tank without showing any signs of depleting.

I do not have images currently, but I can get them it it would help.

Thank you

**Comment by radfast** [comment]
Thanks for reporting, we would certainly want to eliminate any dupe.
I'm reasonably sure canisters are working OK though, as I've tested them on a variety of other mod's similar blocks like Railcraft tanks and IC2 bottling plant.
It's possible this is a bug in Thermal Expansion.
Please can you list which other fluid items you have tested in the Fluid Transposer?  Especially test custom fluid containers from other mods which can be part-filled - so not just buckets.

**Comment by sww1235** [comment]
After further testing, I believe it was a bug with thermal expansion so I am closing this for now. The only fluid handler that actually worked correctly with the fluid transposer was thermal expansion's own.

**Comment by radfast** [comment]
ok thanks for coming back
