### ISSUE TITLE
Oxygen apparatus doesn't work underwater

### ISSUE THREAD

**Issue by IdleMuse** [micdoodle8/Galacticraft#1465]
Is this possible to implement? I see an old issue regarding this, but it was closed without explanation about a year ago.

**Comment by radfast** [comment]
Since that's intended, it's not a bug.
If you want to discuss, please visit the suggestions area of the forum where you can find existing discussions about this  http://forum.micdoodle8.com/index.php?forums/suggestions.7/

**Comment by IdleMuse** [comment]
Cheers, read the recent discussion where you went over your reasoning. Still hoping it'll be added as a new feature at some point!
