### ISSUE TITLE
Crash due to another mod using out-dated BuildCraft API

### ISSUE THREAD

**Issue by TubesCraft** [micdoodle8/Galacticraft#1470]
Tried to upload crash report but failed. Seems to be a conflict with buildcraft? or maybe API? Is this a known issue?

**Comment by radfast** [comment]
Upload the crash report and we can take a look.  How about using a Gist on Github for the upload (see menu on top of your screen)?

Also check you are using the genuine latest version of Galacticraft, that's 3.0.8.269.

If it's the Buildcraft API issue, this might help you: http://wiki.micdoodle8.com/wiki/Compatibility#Buildcraft_API

**Comment by TubesCraft** [comment]
Thanks for the super fast reply and the guidance.

**Comment by radfast** [comment]
Closing now, on the assumption that that has fixed it.   If there is still a problem, please post and we can re-open this.
