### ISSUE TITLE
Crash with Version 3.0.8 .269 and Fastcraft 1.19

### ISSUE THREAD

**Issue by Dream-Master** [micdoodle8/Galacticraft#1471]
I get this Crash:

https://gist.github.com/Dream-Master/21648407a2aa647ebe34#file-gistfile1-txt

I guess it have something to do with the Oil can catch fire and how fastcraft render things.

**Comment by radfast** [comment]
Thanks for spotting, fixed in next build.  (Unfortunately, we have to disable oil catching fire and fuel explosions if you are playing with Fast Craft.)

And btw that was probably the fastest fix ever - please don't expect such service in future. :)

**Comment by Dream-Master** [comment]
nice thanks!

**Comment by sfPlayer1** [comment]
This is not FastCraft specific, you'll get a ChunkCache instance with Vanilla MC as well.

**Comment by radfast** [comment]
thanks @sfPlayer1, good point - this is a pain though, because ChunkCache unhelpfully hides the world provider from us (even though it knows it itself).  I'll fix this at some point.
