### ISSUE TITLE
[Minor] Display screen Cargo Rocket GUI issue.

### ISSUE THREAD

**Issue by dj3520** [micdoodle8/Galacticraft#1473]
![image](https://cloud.githubusercontent.com/assets/8284194/6448585/0ca4e60a-c0e9-11e4-9977-94350cf37926.png)

**Comment by radfast** [comment]
Which exact version @dj3520 ?  There have been recent changes on that.

**Comment by dj3520** [comment]
269. However it should be noted I'm running the mod unzipped (testing new
fluid textures)

**Comment by radfast** [comment]
OK tested and confirmed this is a problem, thanks for raising it.

**Comment by radfast** [comment]
Fixed in next build.

**Comment by dj3520** [comment]
Text hangs off for speed after launch.
![image](https://cloud.githubusercontent.com/assets/8284194/6450639/33099bac-c0f7-11e4-86fe-68c568cb14fc.png)
