### ISSUE TITLE
Server moon crash with .270 build - fixed in .271

### ISSUE THREAD

**Issue by babybasher** [micdoodle8/Galacticraft#1477]
Hi again! I recently updated my server from the .266 to the .270 build. 

I went to the moon as usual, walked a bit then the server crashed.  I'll reboot the server and it kept crashing whenever I tried logging in.  My daughter was able to login fine without crashing the server, she's on earth.

I downgraded the GC version back to .266 and logged in fine without crashing. 

I have attached the crashlog file, not sure if that's what you want here.

http://www.filedropper.com/crash-2015-03-03183858-server

Thank you!

**Comment by radfast** [comment]
Please update to version .271.  There was a small, stupid bug in .270, hopefully not too many people will be affected by it as version .270 was only available for around 12 hours.

**Comment by radfast** [comment]
Although this is fixed, I will leave the issue open for today in case anybody else is affected by it.

**Comment by babybasher** [comment]
Love the speed of bug fixes in this mod, thanks!

**Comment by msajharder** [comment]
I am sort of having the same problem. My apologies for posting to the wrong thread. my OP was on crossbows.

I am running 1.7.10 and GC 3.0.8-257. I did try with the latest build (271) and the same thing happens. The worldgen stalls at "downloading terrain" while FML just loops the same message until i force close. This time I got an actual crash when attempting to go to the moon.

http://pastebin.com/z37i47sE
The actual crash

http://pastebin.com/93rA2kUZ
What FML's console is just spewing. I have a 7MB log file with tons of this just going on and on.

I've removed two mods potentially stalling worldgen when joining other dimensions such as the nether. I received the crash fairly quickly this time.

If you need a list of anything associated with my loadout of mods, please let me know.

**Comment by radfast** [comment]
Does this help you @msajharder:
http://wiki.micdoodle8.com/wiki/Compatibility#Crashes_on_the_Moon_and_how_to_fix_.28CofHCore_.27Flat_Bedrock.27_feature.29

**Comment by msajharder** [comment]
Ah, yes, thank you. Clearly I see several points I need to look at.
I will tweak the CoFH Core config so it spawns normal bedrock behavior
Due to running Reika's RotaryCraft, DragonAPI v4 is required. Should I notify the author of this?
Seems I may have to can MPM.

Much appreciated for pointing me in the right direction!

**Comment by radfast** [comment]
DragonAPI v4 is fine.  Like it says on the Wiki, it's only DragonAPI v2 that had the problem.

**Comment by radfast** [comment]
You should test MPM before canning it, if it works for you then we can update the info on the wiki - it may depend on versions and also whether you have PlayerAPI.

**Comment by msajharder** [comment]
Thankfully this fixed the crash, but I'm going to have to say that its not entirely fixed. Removing JourneyMap and MPM allows proper menu behavior when reaching Y:1200 . With it installed, it blocked the menu.
I'm just going to have to go mod by mod and rip each one out until it starts working.
Right now my culprits are:
MPM
JourneyMap
RopesPlus
Ruins
ChocolateQuest

**Comment by radfast** [comment]
I don't 100% understand what you wrote.  Which mod is blocking the planet selection screen from opening at Y:1200?

**Comment by msajharder** [comment]
JourneyMap is preventing your Solar map from opening. My apologizes.

I've had a major storage server fail out here at work, and I dont have time to debug the problems. I will open a fresh bug report when everything is back up to normal.

**Comment by radfast** [comment]
Thanks for that on JourneyMap, heading now added to the Wiki.  Sorry to hear about the server fail.

Take your time, any specific information you can give us now or in future about mod incompatibilities will be appreciated, the aim is to fix all of these or as many of them as possible.

**Comment by radfast** [comment]
Closing this issue as the .270 problem is fixed in .271 and hopefully everyone affected by it now knows that.
