### ISSUE TITLE
Bad packet ID 64 when players join

### ISSUE THREAD

**Issue by DigitalSniperz** [micdoodle8/Galacticraft#1480]
Hi,

When players join the server, the server crashes and no one can join because it says "Bad Packet ID 64". I have tested with the latest 1.7.10 GC version (271). I remove galacticraft and the server dosnt crash or give bad packet also I have tried creating a new world but still it occurs.

Server crash report:
http://pastebin.com/8B7znPnk

**Comment by radfast** [comment]
Can you post up more of that crash report please - a lot more lines, before and after that place.

Also which Forge version are you using?  I've heard of an issue like this if server and client had different Forge versions, but that was 2 or 3 months back so you should be OK if everyone is using the latest Forge.

**Comment by DigitalSniperz** [comment]
Server is running 1307 forge and client is using 1291 forge. That is literally the error lines in console when someone joins the server. No crash reports in the crash report folder.

**Comment by radfast** [comment]
Please try this:
* synchronise Forge between server and client, so exact same version of Forge on both
* synchronise Galacticraft, so again exact same version on client and server
* copy exact Galacticraft config folder from server to client

Let us know if you still have the same issue after you did all that.

(Also I should ask, are you using Spigot / Cauldron / Bukkit / BungeeCord or anything like that?)

If it's a vanilla Forge server and there is still an issue after you did the syncing, please can you test whether you have the issue if you take away all mods _except_ Galacticraft, and create a new world with only Galacticraft installed.  If the problem goes away when you do that, then that will point to it being a mod conflict in which case I'll need your exact modlist, or better still if you could zip up your full mods and config folders and upload to Mediafire or some place like it.

**Comment by radfast** [comment]
Also upload a full ```fml-server-latest.log``` somewhere for me to look at please.

**Comment by radfast** [comment]
Closing due to lack of response.
