### ISSUE TITLE
Map key

### ISSUE THREAD

**Issue by xJon** [micdoodle8/Galacticraft#1481]
Basically, Galacticraft's map overrides every singel minimap-mod with it taking the 'M' key by default. Galacticraft's map is useful and very cool, but it should'nt take the place of the normal minimap.

I'd want to ask you guys to move the keys options of Galacticraft to the config folder so I, as a modpack developer would be able to fix it myself (:

**Comment by radfast** [comment]
Personally I think this is a good idea: see #298 which was before I joined this project.

I'll probably add the M key only.  I agree it conflicts with a number of things (including the electric bow as well).

**Comment by xJon** [comment]
Great! Should I expect this change to be out in a new version soon (AKA Today), or not?
Thanks :)

**Comment by radfast** [comment]
Not.

**Comment by xJon** [comment]
No problem :)

**Comment by xJon** [comment]
Is there any possibility that this configuration option will have it's own .cfg file? With it being a part of the core .cfg file I got to reset the whole file, and it is a big problem for me as a modpack maker.

If this feature will have it's own .cfg file I'll have no problem using it, because currently, I just can't!

**Comment by micdoodle8** [comment]
If an option doesn't exist in the cfg file, it will be added to the end. There's no reason to reset the whole file.

**Comment by xJon** [comment]
@micdoodle8 Gotcha. Thanks!
