### ISSUE TITLE
Aluminum  Wire Microblocks not breaking

### ISSUE THREAD

**Issue by ecapp** [micdoodle8/Galacticraft#1482]
I am running a Tekkit server which runs Minecraft 1.6.4.  After abt 10 hours of use, aluminum  wire microblocks stopped working properly.  They can be set down and connected together but will not break when trying tyo reposition them or remove them.  This behaviour is the same whenther in creative or survival modes.  I tryied reinstallling the mods but to no avail.  That being said, it is only an issue on the server.  When the single player client is loaded through the Technic launcher, the alumiunum wire microblocks work fine.

Thx

**Comment by radfast** [comment]
Which version of Galacticraft is Tekkit using?  One problem can be it is often very far from being the latest version.

If you're playing single player, you can try updating to the latest 1.6.4 version of Galacticraft and see if that fixes it.  If you're on a server, the server owner and all the players would need to do that.  (And Tekkit then probably bugs you to "update" Tekkit meaning actually roll back to its version, so you might have to answer "no" every time you launch the game.)

We cannot offer you any support with this unless it's a confirmed bug you are seeing in the Latest 1.6.4 version of Galacticraft.  To confirm, you'd need to test it with the latest and tell us exact steps to reproduce.

Closing, for now.  I will re-open if it's shown to be an issue in the latest - you're welcome to post here any more info you find.
