### ISSUE TITLE
Cryochamber Bug

### ISSUE THREAD

**Issue by SportsFan10** [micdoodle8/Galacticraft#1483]
I can't get out of a cryogenic chamber when two people are in the same dimension.  Meaning if two people are on Mars for example, and one is not sleeping, and the other has to leave their chamber they can't.  This video will show a better example of this:
https://www.youtube.com/watch?v=EhS0nwLUTyA&feature=youtu.be
Minecraft 1.7.10
Forge: 7.10.85.1291
Galacticraft: 1.7-3.0.8.265

This probably will be impossible to test in single player as you need at least two players to cause the issue.  If two people are sleeping then it's fine, but you can't leave the chamber.

I'm open to further testing since I have a server that uses the mod.
Thanks,
-Nick

**Comment by radfast** [comment]
Is this the same issue as #1159?

**Comment by SportsFan10** [comment]
My apologies i didn't look further into other issues.

**Comment by radfast** [comment]
no need at all to apologise, you have given us very helpful extra info i.e. that it only happens with 2 players online, which is why we have not been seeing it in testing.

Thank you very much for that, hopefully this will lead to a fix of this issue soon - it's definitely a shame if the chambers are not working for people.

**Comment by SportsFan10** [comment]
Alright, well that's good news.  Yes it is indeed similar to issues #1159.  If one player is online, or no other players in the same dimension all is fine you sleep through and then pop out.  If two players are in and both sleep all is fine.  Only happens if something prevents you from sleeping through the night.  Or if two people both sleep, then you try to get out then it won't  let you.

Once again if you'd like me to try and builds when you get around to it, I'd be fine with that.
Glad I can help(a little)
-Nick
