### ISSUE TITLE
[Addon] Solar systems stacked apon eachother

### ISSUE THREAD

**Issue by Alex-the-666** [micdoodle8/Galacticraft#1487]
I created a custom solar system. however, it appears right above the default Solar System, as seen Below:
![kepleroverlay](https://cloud.githubusercontent.com/assets/8662109/6546622/12e17518-c578-11e4-960b-da5151e330a7.png)

code:
Main Class:
package beyondsol;

import beyondsol.core.ModCelestials;
import net.minecraft.util.ResourceLocation;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;

@Mod(modid = BeyondSol.MODID, version = BeyondSol.VERSION, dependencies = "required-after:GalacticraftCore",
        name = BeyondSol.NAME)
public class BeyondSol
{
    public static final String MODID = "beyondsol";
    public static final String VERSION = "1.0";
    public static final String NAME = "Beyond Sol";
   
	
	
    @Instance(value = MODID)
    public static BeyondSol instance;
   
    @SidedProxy(clientSide="beyondsol.ClientProxy", serverSide="beyondsol.CommonProxy")
    public static CommonProxy proxy;
   
    @EventHandler
    public void preInit(FMLPreInitializationEvent event) {
    }
   
    @EventHandler
    public void init(FMLInitializationEvent event)
    {       
    	ModCelestials.init();
    	proxy.render();
       
    }
   
    @EventHandler
    public void postInit(FMLPostInitializationEvent event) {
    }
   
}

ModCelestials:

package beyondsol.core;

import beyondsol.BeyondSol;
import micdoodle8.mods.galacticraft.api.galaxies.*;
import net.minecraft.util.ResourceLocation;
import net.minecraft.world.WorldProvider;
import micdoodle8.mods.galacticraft.api.galaxies.GalaxyRegistry;
import micdoodle8.mods.galacticraft.api.vector.Vector3;
import micdoodle8.mods.galacticraft.api.world.IAtmosphericGas;

public class ModCelestials {

	public static Planet kepler_22b;
	public static Star kepler_22;
	public static SolarSystem system_kepler22;
	
	public static void init(){
		kepler22();
		register();
	}
	public static void kepler22(){
		system_kepler22 = new SolarSystem("kepler_22", "milkyWay");
		system_kepler22.setMapPosition(new Vector3(-32.0F, -32.0F));
		kepler_22 = (Star) new Star("kepler_22").setParentSolarSystem(system_kepler22);
		kepler_22.setTierRequired(-1);
		kepler_22.setBodyIcon(new ResourceLocation("beyondsol:textures/planets/star_kepler_22.png"));
		system_kepler22.setMainStar(kepler_22);
		kepler_22b = (Planet) new Planet("kepler_22b").setParentSolarSystem(system_kepler22);
		kepler_22b.setRingColorRGB(0.53F, 2.02F, 1.42F);
		kepler_22b.setPhaseShift(0.1176471F);
		kepler_22b.setRelativeDistanceFromCenter(new CelestialBody.ScalableDistance(0.88F, 0.88F));
		kepler_22b.setRelativeOrbitTime(1.5F);
		kepler_22b.setTierRequired(1);
		kepler_22b.setRelativeSize(17F);
		kepler_22b.setBodyIcon(new ResourceLocation("beyondsol:textures/planets/kepler_22b.png"));
		kepler_22b.setDimensionInfo(0, WorldProvider.class, false).setTierRequired(1);
		kepler_22b.atmosphereComponent(IAtmosphericGas.NITROGEN).atmosphereComponent(IAtmosphericGas.OXYGEN).atmosphereComponent(IAtmosphericGas.ARGON).atmosphereComponent(IAtmosphericGas.WATER);

	}

	public static void register(){
		GalaxyRegistry.registerSolarSystem(system_kepler22);
		GalaxyRegistry.registerPlanet(kepler_22b);
	}
}

Thanks in advance for help :)

**Comment by radfast** [comment]
See that textbox at the top of the page named "Search"?  It can help you.
https://github.com/micdoodle8/Galacticraft/issues/1306

**Comment by Alex-the-666** [comment]
still does not work; Ive put in multiple values that are not zero and there is no change.
