### ISSUE TITLE
oil becomes oilgc and is useless

### ISSUE THREAD

**Issue by leftyde** [micdoodle8/Galacticraft#1490]
Hello there,

I got a issue? with GC oil. I created a world a few weeks ago with GC and without Buildcraft. Now I wanted to add BC, tested it a little in SP and I realized all oil from GC is now called oilgc and can't be used anymore?

I took 3 screen to show you that: http://imgur.com/X6V2qMt,o23PB0A,1XjVqYA#0

**Comment by radfast** [comment]
You're not really supposed to add mods after you already created a world.  But people often do, so in a recent update we have tried to make Galacticraft work as well as reasonably possible in this situation.  (Before, all the Galacticraft oil would simply have been deleted from the world when you added Buildcraft.)

Please can you test a few things and let me know what the exact situation is.

It should be this:
1.  existing reservoirs of Galacticraft oil are still present in the world, and can still be 'mined' using the Galacticraft Oil Extractor
2.  existing Oil Canisters work normally (can be used in Galacticraft Refinery or in Buildcraft tanks etc)
3.  if you obtained Galacticraft oil (now become __oilgc__) from a reservoir using another mod's pipes, it can only be used in a Galacticraft Refinery - not a Buildcraft Refinery
4.  Galacticraft Refinery can also process Buildcraft oil
5.  if you had a half-full Galacticraft Refinery at the point when you added Buildcraft, it is still half-full of oil, and it will still process that into fuel
6.  if you delete Buildcraft from your mods (make a backup of your world first!) and load the same world, Galacticraft oil should go back to normal

Please can you let me know if any of these 6 things is not working.  In your screenshots, I'm only seeing that oilgc will not feed a Buildcraft Refinery, which is intended.

**Comment by leftyde** [comment]
I know what I'm doing as long as mods play nice with it (that is at least in 99% the fall in the last 2-3 years where I do mc servers :D) So I event find that system before 1.7 better because you could easily change a stupid ID to fix an issue like that to delete the whole oil and for use we would have a mining world. But yeah now to your points:

1. Yes they're there and it does work. I can even use the oil canister on tanks who is oilgc in there.
2. yep
3. Nope, no refinery does work (as you can see on the third screen).
4. yep
5. can't test that
6. Yep

**Comment by radfast** [comment]
Right, so basically everything is working?  I don't see the issue here.

If you have Buildcraft installed, the fluid named "oil" means Buildcraft oil, and "oilgc" means Galacticraft oil.  They can't be named the same, because otherwise the Galacticraft oil would change into Buildcraft oil and then would all be lost from the world if you decide to take Buildcraft out of your modpack again.  Galacticraft without oil would basically be unplayable, because you need fuel for your rockets.

**Comment by leftyde** [comment]
Öhm no like I said 2 times, you can't use oilgc in the galacticraft refinery..... Look at the screenshot, the oil won't go inside of the refinery or I have to use the canisters everytime I want to refine that oil and that's just stupid, than pls add a config option to delete GC oil....

**Comment by radfast** [comment]
No.

**Comment by radfast** [comment]
If you try the latest version, you should find the Refinery can now process the oilgc as intended.
