### ISSUE TITLE
MFR sludge lakes generating on moon

### ISSUE THREAD

**Issue by themechman** [micdoodle8/Galacticraft#1491]
Just want to drop this out there. The reason for the difficulty in worldgen was CoFH moved the location of their configs. The original CoFHcore.cfg is now under the same CoFH folder, but in a sub-folder called "core" with the file name of "Common.cfg".

Also MFR's liquid lakes are spawning on the moon. Although not a serious problem, it's still awkward.

**Comment by radfast** [comment]
Which Galacticraft version?

**Comment by msajharder** [comment]
3.0.8.271 for 1.7.10

**Comment by radfast** [comment]
For the MFR liquid lakes, check your Galacticraft core.conf config for this:
>     B:"Generate other mods features on planets"=false

For the CoFH config, I don't understand your point - that's not a Galacticraft issue.

**Comment by msajharder** [comment]
I understand that is not a GC issue, but might want to put that along with your "flat bedrock" section of your FAQ for the cofh config. I am letting you know that the current version, the config name and location changed, should anyone have the same difficulty I was.

Also along those lines is an admin plugin I use which also causes flat bedrock.

For MFR, the config is as you have it listed. I did not change that as it said "Not recommended".

**Comment by radfast** [comment]
Wiki updated, thank you.  Your admin plugin is OK, the issue is a bug in CoFHCore so unless your plugin has the same bug, it should be fine.

**Comment by radfast** [comment]
@themechman a question for you: __how__ are you generating the MFR sludge lakes, I mean is it being generated by CoFHCore custom worldgen or is it 'regular' MFR?

**Comment by themechman** [comment]
They were just showing up I'm afraid. All I did was drop in your mod. Now, this was a bit back and a lot has changed with the CoFH core and the mods I was using. I havent traveled to the moon since. I will check it out again and let you know. Unfortunately I'm traveling and may not be able to check things over the weekend as my laptop refuses to play even vanilla 1.7.10. Will be in touch.

**Comment by radfast** [comment]
no worries.  It sounds like you are not using CoFHCore custom worldgen then, just MFR and CoFHCore on default settings.

**Comment by radfast** [comment]
I think this will be fixed in next build (as long as in GC ```core.conf``` config you leave the CoFHCore whitelist setting as false).  Obviously, you will have to re-generate your moon terrain to see the effects of this.  Delete DIM-28 to have it automatically re-generate - doing that will of course destroy anything built on the Moon.
