### ISSUE TITLE
*Urgent* Liquid Region Crash

### ISSUE THREAD

**Issue by Omuck3** [micdoodle8/Galacticraft#1493]
I need to fix this! Please help!
micdoodle8.mods.galacticraft.core.blocks.BlockFluidGC.isFlammable(BlockFluidGC.java:122)

**Comment by radfast** [comment]
Do you think, just maybe, you should give more information like your full crash report, if you want help?

My guess is it's a duplicate of this:
https://github.com/micdoodle8/Galacticraft/issues/1471

**Comment by Omuck3** [comment]
So it's fixed?  I just have to download the new build?
