### ISSUE TITLE
Spawning in thin air

### ISSUE THREAD

**Issue by sfxworks** [micdoodle8/Galacticraft#1500]
I just finished building my space station. When I trigger /spawn while in creative, no problems. I spawn inside my oxygen sealed space station.

However...when I /gamemode 0 and /spawn I spawn above the space station...in thin air.

According to 2pk189, an Admin from Lapito's Galacticraft, this issue is due to Oxygen Sealer creating an invisible block while essentials is deliberately moving the spawn due to that invisible block being "in the way"... I don't believe this. Surely someone has tried to build a space station as their spawn before so I would usually see issues similar to mine.

Still running cauldron-1.7.10-1.1307.06.218 as well as GalacticraftCore{3.0.8} and GalacticraftMars{3.0.8}

Edit: He then suggested to place a door down and set spawn there...
And that worked........
So I do think this might be an issue. Do you need my essentials version?

Edit 2:
Video of how to reproduce the issue
http://youtu.be/WRUB4USz9D0

**Comment by sfxworks** [comment]
He then suggested to place a door down and set spawn there...
And that worked........
So I do think this might be an issue. Do you need my essentials version?

**Comment by radfast** [comment]
It's a bug in Essentials.  Go tell them to test for Block.isAir() correctly.
See also http://wiki.micdoodle8.com/wiki/Compatibility#Code_in_other_mods_which_looks_for_.27air.27_blocks

Galacticraft players have known for a long time that if you want to set an Essentials home or teleport location on a Space Base, you need to do it in a vacuum area.  Maybe use an airlock?  Or you can use an Oxygen Distributor, Essentials doesn't have an issue teleporting you into an oxygen bubble.
