### ISSUE TITLE
[Add-on] Fake celestial ring

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#1502]
I tried to create the mars moon. I found the fake celestial ring when zoom into mars.
Here is my info : https://www.youtube.com/watch?v=GrJy7V5yNJg

**Comment by BlesseNtumble** [comment]
![1](http://firepic.org/images/2015-03/19/412b6zq6ixmx.png)
![2](http://firepic.org/images/2015-03/19/0wsjrwupu2k0.png)
![3](http://firepic.org/images/2015-03/19/y93581b1d1qz.png)

**Comment by micdoodle8** [comment]
Hey I can take a look at this, but I need a way to recreate it in my environment. Is it possible to get a copy of your mod's source for testing purposes? Thanks.

**Comment by BlesseNtumble** [comment]
package blessentumble;
 

import java.io.File;

import micdoodle8.mods.galacticraft.api.GalacticraftRegistry;
import micdoodle8.mods.galacticraft.api.galaxies.CelestialBody;
import micdoodle8.mods.galacticraft.api.galaxies.GalaxyRegistry;
import micdoodle8.mods.galacticraft.api.galaxies.Moon;
import micdoodle8.mods.galacticraft.api.galaxies.Planet;
import micdoodle8.mods.galacticraft.api.recipe.SchematicRegistry;
import micdoodle8.mods.galacticraft.api.world.IAtmosphericGas;
import micdoodle8.mods.galacticraft.core.GalacticraftCore;
import micdoodle8.mods.galacticraft.core.tick.TickHandlerServer;
import micdoodle8.mods.galacticraft.core.util.CreativeTabGC;
import micdoodle8.mods.galacticraft.core.util.GCCoreUtil;
import micdoodle8.mods.galacticraft.planets.mars.MarsModule;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.common.MinecraftForge;
import blessentumble.core.blocks.BlocksAddon;
import blessentumble.core.configs.OreGenOtherModsGS;
import blessentumble.core.configs.PlanetsConfig;
import blessentumble.core.fluids.FluidsAddon;
import blessentumble.core.handler.SkyProviderHandlerBA;
import blessentumble.core.items.ItemsAddon;
import blessentumble.core.proxy.CommonProxy;
import blessentumble.moons.callisto.dimension.WorldProviderCallisto;
import blessentumble.moons.deimos.dimension.WorldProviderDeimos;
import blessentumble.moons.enceladus.dimension.WorldProviderEnceladus;
import blessentumble.moons.enceladus.entity.EntityBossCrystallBrain;
import blessentumble.moons.enceladus.entity.EntityEvolvedGiantSnail;
import blessentumble.moons.enceladus.tile.TileEntityBlockCrystallTE;
import blessentumble.moons.enceladus.tile.TileEntityEnceladusTreasureChest;
import blessentumble.moons.europa.dimension.WorldProviderEuropa;
import blessentumble.moons.europa.entities.EntityBossBlaze;
import blessentumble.moons.europa.entities.EntityEvolvedColdBlaze;
import blessentumble.moons.europa.recipe.CraftingRecipesEuropa;
import blessentumble.moons.europa.tile.TileEntityDungeonSpawnerEuropa;
import blessentumble.moons.europa.tile.TileEntityEuropaTreasureChest;
import blessentumble.moons.ganymede.dimension.WorldProviderGanymede;
import blessentumble.moons.io.dimension.WorldProviderIo;
import blessentumble.moons.io.entities.EntityEvolvedFireCreeper;
import blessentumble.moons.io.entities.EntityTier4Rocket;
import blessentumble.moons.io.recipe.CraftingRecipesIO;
import blessentumble.moons.io.recipe.Tier4RocketRecipe;
import blessentumble.moons.io.schematic.SchematicTier4Rocket;
import blessentumble.moons.phobos.dimension.WorldProviderPhobos;
import blessentumble.moons.phobos.recipe.CraftingRecipesPhobos;
import blessentumble.planets.ceres.dimension.WorldProviderCeres;
import blessentumble.planets.mercury.dimension.WorldProviderMercury;
import blessentumble.planets.mercury.recipe.CraftingRecipesMercury;
import blessentumble.planets.venus.dimension.WorldProviderVenus;
import blessentumble.planets.venus.entity.EntityBossGhast;
import blessentumble.planets.venus.entity.EntityEvolvedFireSkeleton;
import blessentumble.planets.venus.entity.EntityEvolvedFireSpider;
import blessentumble.planets.venus.entity.EntityTier5Rocket;
import blessentumble.planets.venus.recipe.CraftingRecipesVenus;
import blessentumble.planets.venus.recipe.Tier5RocketRecipe;
import blessentumble.planets.venus.schematic.SchematicTier5Rocket;
import blessentumble.planets.venus.tile.TileEntityVenusTreasureChest;
import cpw.mods.fml.common.FMLCommonHandler;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.registry.GameRegistry;

 

@Mod(
		   modid = "blesseaddon",
		   version = "1.7",
		   dependencies = "required-after:GalacticraftCore",
		   name = "GalaxySpace"
		)

public class BlesseAddon

{

    public static final String MODID = "blesseaddon";
    public static final String VERSION = "1.7";
    public static final String NAME = "GalaxySpace";
    public static final String ASSET_PREFIX = "blesseaddon";
    
    public static Planet planetVenus;
    public static Planet planetMercury;
    public static Moon phobosMars;
    public static Moon deimosMars;
    public static Planet planetCeres;
    public static Planet planetJupiter;
    public static Moon ioJupiter;
    public static Moon europaJupiter;
    public static Moon ganymedJupiter;
    public static Moon callistoJupiter;
    public static Planet planetSaturn;
    public static Moon enceladus;
    public static Moon titan;
	//public static Moon diona;
	
    
    
    //public static SolarSystem newsystem;
    
 

       
    //___________________
    
    @Instance(value = MODID)

    public static BlesseAddon instance;

   

    @SidedProxy(clientSide="blessentumble.core.proxy.ClientProxy", serverSide="blessentumble.core.proxy.CommonProxy")

    public static CommonProxy proxy;

   

    @EventHandler

    public void preInit(FMLPreInitializationEvent event) {

    	new PlanetsConfig(new File(event.getModConfigurationDirectory(), "Galacticraft/GSplanets.conf"));
		FMLCommonHandler.instance().bus().register(new SkyProviderHandlerBA());
		ItemsAddon.initItems();
		BlocksAddon.initialize();
		FluidsAddon.initialize();
		proxy.preload();
    	
    }

   

    @EventHandler

    public void init(FMLInitializationEvent event)

    {  
    	proxy.load();
    	this.registerEntities();
    	TickHandlerServer eventHandler = new TickHandlerServer();
    	FMLCommonHandler.instance().bus().register(eventHandler);
    	MinecraftForge.EVENT_BUS.register(new OreGenOtherModsGS());
        MinecraftForge.EVENT_BUS.register(eventHandler);
        // Mercury ------------------------------------
        	planetMercury = (Planet) new Planet("mercury").setParentSolarSystem(GalacticraftCore.solarSystemSol);
        	planetMercury.setRingColorRGB(0.1F, 0.9F, 0.6F);
        	planetMercury.setPhaseShift(1.45F);
        	planetMercury.setTierRequired(5);
        	planetMercury.setRelativeDistanceFromCenter(new CelestialBody.ScalableDistance(0.5F, 0.5F));
        	planetMercury.setRelativeOrbitTime(0.24096385542168674698795180722892F);
        	planetMercury.setBodyIcon(new ResourceLocation(GalacticraftCore.ASSET_PREFIX, "textures/gui/celestialbodies/mercury.png"));
        	planetMercury.setDimensionInfo(PlanetsConfig.dimensionIDMercury, WorldProviderMercury.class);
        // --------------------------------------------
        // Venus --------------------------------------
    		planetVenus = (Planet) new Planet("venus").setParentSolarSystem(GalacticraftCore.solarSystemSol);
    		planetVenus.setRingColorRGB(0.1F, 0.9F, 0.6F);
    		planetVenus.setPhaseShift(2.0F);
    		planetVenus.setTierRequired(4);
    		planetVenus.setRelativeDistanceFromCenter(new CelestialBody.ScalableDistance(0.75F, 0.75F));
    		planetVenus.setRelativeOrbitTime(0.61527929901423877327491785323111F);
    		planetVenus.setBodyIcon(new ResourceLocation(GalacticraftCore.ASSET_PREFIX, "textures/gui/celestialbodies/venus.png"));
    		planetVenus.setDimensionInfo(PlanetsConfig.dimensionIDVenus, WorldProviderVenus.class);
    		planetVenus.atmosphereComponent(IAtmosphericGas.CO2).atmosphereComponent(IAtmosphericGas.HELIUM).atmosphereComponent(IAtmosphericGas.ARGON);
    	// --------------------------------------------
    	// Earth --------------------------------------

    	// --------------------------------------------
    	
    	// MARS ---------------------------------------
    		phobosMars = (Moon) new Moon("Phobos").setParentPlanet(MarsModule.planetMars);
    		phobosMars.setRelativeSize(0.0017F);
    		phobosMars.setRelativeDistanceFromCenter(new CelestialBody.ScalableDistance(8F, 8F));
    		phobosMars.setRelativeOrbitTime(100F);
    		phobosMars.setTierRequired(2);
    		phobosMars.setBodyIcon(new ResourceLocation("blesseaddon", "textures/gui/celestialbodies/phobos.png"));
    		phobosMars.setDimensionInfo(PlanetsConfig.dimensionIDPhobos, WorldProviderPhobos.class);
    	
    		deimosMars = (Moon) new Moon("Deimos").setParentPlanet(MarsModule.planetMars);
    		deimosMars.setRelativeSize(0.0017F);
    		deimosMars.setRelativeDistanceFromCenter(new CelestialBody.ScalableDistance(16F, 16F));
    		deimosMars.setRelativeOrbitTime(300F);
    		deimosMars.setTierRequired(2);
    		deimosMars.setBodyIcon(new ResourceLocation("blesseaddon", "textures/gui/celestialbodies/deimos.png"));
    		deimosMars.setDimensionInfo(PlanetsConfig.dimensionIDDeimos, WorldProviderDeimos.class);
        	
    	// ---------------------------------------------
    		
    	// Asteroides ----------------------------------
    		planetCeres = (Planet) new Planet("Ceres").setParentSolarSystem(GalacticraftCore.solarSystemSol);
    		planetCeres.setPhaseShift(2.0F);
    		planetCeres.setTierRequired(3);
    		planetCeres.setRelativeDistanceFromCenter(new CelestialBody.ScalableDistance(1.31F, 1.31F));
    		planetCeres.setRelativeOrbitTime(15.0F);
    		planetCeres.setBodyIcon(new ResourceLocation(BlesseAddon.ASSET_PREFIX, "textures/gui/celestialbodies/ceres.png"));
    		planetCeres.setDimensionInfo(PlanetsConfig.dimensionIDCeres, WorldProviderCeres.class);
    		
    	// --------------------------------------------- 
    		
    	// Jupiter -------------------------------------
    		
            BlesseAddon.planetJupiter = (Planet) new Planet("jupiter").setParentSolarSystem(GalacticraftCore.solarSystemSol);
            BlesseAddon.planetJupiter.setRingColorRGB(0.1F, 0.9F, 0.6F);
            BlesseAddon.planetJupiter.setPhaseShift((float) Math.PI);
            BlesseAddon.planetJupiter.setBodyIcon(new ResourceLocation(GalacticraftCore.ASSET_PREFIX, "textures/gui/celestialbodies/jupiter.png"));
            BlesseAddon.planetJupiter.setRelativeDistanceFromCenter(new CelestialBody.ScalableDistance(1.5F, 1.5F));
            BlesseAddon.planetJupiter.setRelativeOrbitTime(11.861993428258488499452354874042F);
            
          	ioJupiter = (Moon) new Moon("ioJupiter").setParentPlanet(BlesseAddon.planetJupiter);
    		ioJupiter.setRelativeSize(0.0017F);
    		ioJupiter.setRelativeDistanceFromCenter(new CelestialBody.ScalableDistance(10F, 10F));
    		ioJupiter.setRelativeOrbitTime(50F);
    		ioJupiter.setTierRequired(3);
    		ioJupiter.setBodyIcon(new ResourceLocation("blesseaddon", "textures/gui/celestialbodies/io.png"));
    		ioJupiter.setDimensionInfo(PlanetsConfig.dimensionIDIo, WorldProviderIo.class);
    		
    		europaJupiter = (Moon) new Moon("Europa").setParentPlanet(BlesseAddon.planetJupiter);
    		europaJupiter.setRelativeSize(1.1F);
    		europaJupiter.setRelativeDistanceFromCenter(new CelestialBody.ScalableDistance(15F, 15F));
    		europaJupiter.setRelativeOrbitTime(200F);
    		europaJupiter.setTierRequired(3);
    		europaJupiter.setBodyIcon(new ResourceLocation("blesseaddon", "textures/gui/celestialbodies/europa.png"));
    		europaJupiter.setDimensionInfo(PlanetsConfig.dimensionIDEuropa, WorldProviderEuropa.class);
    		
    		ganymedJupiter = (Moon) new Moon("Ganymed").setParentPlanet(BlesseAddon.planetJupiter);
    		ganymedJupiter.setRelativeSize(3.0517F);
    		ganymedJupiter.setRelativeDistanceFromCenter(new CelestialBody.ScalableDistance(20F, 20F));
    		ganymedJupiter.setRelativeOrbitTime(350F);
    		ganymedJupiter.setTierRequired(3);
    		ganymedJupiter.setBodyIcon(new ResourceLocation("blesseaddon", "textures/gui/celestialbodies/ganymede.png"));
    		ganymedJupiter.setDimensionInfo(PlanetsConfig.dimensionIDGanymede, WorldProviderGanymede.class);
    		
    		callistoJupiter = (Moon) new Moon("Callisto").setParentPlanet(BlesseAddon.planetJupiter);
    		callistoJupiter.setRelativeSize(1.5017F);
    		callistoJupiter.setRelativeDistanceFromCenter(new CelestialBody.ScalableDistance(30F, 30F));
    		callistoJupiter.setRelativeOrbitTime(500F);
			callistoJupiter.setTierRequired(3);
    		callistoJupiter.setBodyIcon(new ResourceLocation("blesseaddon", "textures/gui/celestialbodies/callisto.png"));
		    callistoJupiter.setDimensionInfo(PlanetsConfig.dimensionIDCallisto, WorldProviderCallisto.class);
			// ---------------------------------------------
    		// Saturn --------------------------------------
    		BlesseAddon.planetSaturn = (Planet) new Planet("saturn").setParentSolarSystem(GalacticraftCore.solarSystemSol);
    		BlesseAddon.planetSaturn.setRingColorRGB(1.1F, 0.9F, 0.6F);
    		BlesseAddon.planetSaturn.setPhaseShift(5.45F);
    		BlesseAddon.planetSaturn.setRelativeDistanceFromCenter(new CelestialBody.ScalableDistance(1.75F, 1.75F));
    		BlesseAddon.planetSaturn.setRelativeOrbitTime(29.463307776560788608981380065717F);
    		BlesseAddon.planetSaturn.setBodyIcon(new ResourceLocation("blesseaddon", "textures/gui/celestialbodies/saturn.png"));
    	    
    		
    		enceladus = (Moon) new Moon("Enceladus").setParentPlanet(BlesseAddon.planetSaturn);
    		enceladus.setRelativeSize(0.0017F);
    		enceladus.setRelativeDistanceFromCenter(new CelestialBody.ScalableDistance(15F, 15F));
    		enceladus.setRelativeOrbitTime(50F);
    		enceladus.setTierRequired(5);
    		enceladus.setBodyIcon(new ResourceLocation("blesseaddon", "textures/gui/celestialbodies/enceladus.png"));
    		enceladus.setDimensionInfo(PlanetsConfig.dimensionIDEnceladus, WorldProviderEnceladus.class);
    		
    		titan = (Moon) new Moon("Titan").setParentPlanet(BlesseAddon.planetSaturn);
    		titan.setRelativeSize(0.0017F);
    		titan.setRelativeDistanceFromCenter(new CelestialBody.ScalableDistance(18F, 18F));
    		titan.setRelativeOrbitTime(50F);
    		titan.setTierRequired(5);
    		titan.setBodyIcon(new ResourceLocation("blesseaddon", "textures/gui/celestialbodies/titan.png"));
    		//titan.setDimensionInfo(PlanetsConfig.dimensionIDTitan, WorldProviderTitan.class);
    		// ---------------------------------------------
    	/*	
    		// Test ----------------------------------------
    		newsystem = new SolarSystem("new", "milkyWay").setMapPosition(new Vector3(1.0F, 0.0F));
            Star starNew = (Star) new Star("test").setParentSolarSystem(BlesseAddon.newsystem).setTierRequired(-1);
            starNew.setBodyIcon(new ResourceLocation(GalacticraftCore.ASSET_PREFIX, "textures/gui/celestialbodies/sun.png"));
            newsystem.setMainStar(starNew);
   	    
            // ---------------------------------------------
    	 */
    		GalaxyRegistry.registerPlanet(planetVenus);
    		GalaxyRegistry.registerPlanet(planetMercury);
    		GalaxyRegistry.registerMoon(phobosMars);
    		GalaxyRegistry.registerMoon(deimosMars);
    		GalaxyRegistry.registerPlanet(planetCeres);
    		GalaxyRegistry.registerPlanet(BlesseAddon.planetJupiter);
    		GalaxyRegistry.registerMoon(ioJupiter);
    		GalaxyRegistry.registerMoon(europaJupiter);
    		GalaxyRegistry.registerMoon(ganymedJupiter);
    		GalaxyRegistry.registerMoon(callistoJupiter);
    		GalaxyRegistry.registerPlanet(BlesseAddon.planetSaturn);
    		GalaxyRegistry.registerMoon(enceladus);
			GalaxyRegistry.registerMoon(titan);
    		
    		//GalaxyRegistry.registerSolarSystem(newsystem);
    		

    		
    	    	
    	
    	
        GalacticraftRegistry.registerTeleportType(WorldProviderPhobos.class, new WorldProviderPhobos());
        GalacticraftRegistry.registerTeleportType(WorldProviderEuropa.class, new WorldProviderEuropa());
        GalacticraftRegistry.registerTeleportType(WorldProviderIo.class, new WorldProviderIo());
        GalacticraftRegistry.registerTeleportType(WorldProviderVenus.class, new WorldProviderVenus());
        GalacticraftRegistry.registerTeleportType(WorldProviderMercury.class, new WorldProviderMercury());
        GalacticraftRegistry.registerTeleportType(WorldProviderEnceladus.class, new WorldProviderEnceladus());
        GalacticraftRegistry.registerTeleportType(WorldProviderDeimos.class, new WorldProviderDeimos());
        GalacticraftRegistry.registerTeleportType(WorldProviderCeres.class, new WorldProviderCeres());
        GalacticraftRegistry.registerTeleportType(WorldProviderGanymede.class, new WorldProviderGanymede());
        GalacticraftRegistry.registerTeleportType(WorldProviderCallisto.class, new WorldProviderCallisto());
        
        GalacticraftRegistry.addDungeonLoot(4, new ItemStack(ItemsAddon.Tier4Schematic, 1, 0));
        GalacticraftRegistry.addDungeonLoot(5, new ItemStack(ItemsAddon.Tier5Schematic, 1, 0));
        GalacticraftRegistry.addDungeonLoot(6, new ItemStack(ItemsAddon.Tier6Schematic, 1, 0));
        
        CreativeTabsBlesse.BlesseBlocksTab = new CreativeTabGC(CreativeTabs.getNextID(), "AddonsBlocks", Item.getItemFromBlock(BlocksAddon.EuropaGlowStone), 0);
        CreativeTabsBlesse.BlesseItemsTab = new CreativeTabGC(CreativeTabs.getNextID(), "AddonsItems", ItemsAddon.Tier4Rocket, 0);
        CreativeTabsBlesse.BlesseArmorTab = new CreativeTabGC(CreativeTabs.getNextID(), "AddonsArmor", ItemsAddon.QuantHelmet, 0);
        
        

        
    }

    

    @EventHandler

    public void postInit(FMLPostInitializationEvent event) {

    	CraftingRecipesPhobos.loadRecipes();
    	CraftingRecipesEuropa.loadRecipes();
    	CraftingRecipesIO.loadRecipes();
    	CraftingRecipesVenus.loadRecipes();
    	CraftingRecipesMercury.loadRecipes();
    	proxy.postload();
    	
    }
    
  	
    
    private void registerEntities()
    {
        this.registerCreatures();
        this.registerNonMobEntities();
        this.registerTileEntities();
        this.registerRecipesWorkBench();
    }
    
    public void registerCreatures()
	{
		GCCoreUtil.registerGalacticraftCreature(EntityEvolvedColdBlaze.class, "EvolvedColdBlaze", -771829, -870131);
		GCCoreUtil.registerGalacticraftCreature(EntityBossBlaze.class, "EvolvedBossBlaze", -771829, -870131);
		GCCoreUtil.registerGalacticraftCreature(EntityEvolvedFireCreeper.class, "EvolvedFireCreeper", -771829, -870131);
		
		GCCoreUtil.registerGalacticraftCreature(EntityBossGhast.class, "EvolvedBossGhast", -771829, -870131);
		GCCoreUtil.registerGalacticraftCreature(EntityEvolvedFireSpider.class, "EvolvedFireSpider", -771829, -870131);
		GCCoreUtil.registerGalacticraftCreature(EntityEvolvedFireSkeleton.class, "EvolvedFireSkeleton", -771829, -870131);
	
		GCCoreUtil.registerGalacticraftCreature(EntityEvolvedGiantSnail.class, "EvolvedGiantSnail", -771829, -870131);
		GCCoreUtil.registerGalacticraftCreature(EntityBossCrystallBrain.class, "EvolvedBossCrystallBrain", -771829, -870131);
		
		
	}

    private void registerNonMobEntities()
    {
    	GCCoreUtil.registerGalacticraftNonMobEntity(EntityTier4Rocket.class, "SpaceshipT4", 150, 1, false);
    	GCCoreUtil.registerGalacticraftNonMobEntity(EntityTier5Rocket.class, "SpaceshipT5", 150, 1, false);
    }

    private void registerTileEntities()
    {
        GameRegistry.registerTileEntity(TileEntityBlockCrystallTE.class, "Crystall");
        
    	GameRegistry.registerTileEntity(TileEntityEuropaTreasureChest.class, "Tier 4 Treasure Chest");
    	GameRegistry.registerTileEntity(TileEntityVenusTreasureChest.class, "Tier 5 Treasure Chest");
    	GameRegistry.registerTileEntity(TileEntityEnceladusTreasureChest.class, "Tier 6 Treasure Chest");
    	
    	SchematicRegistry.registerSchematicRecipe(new SchematicTier4Rocket());
    	SchematicRegistry.registerSchematicRecipe(new SchematicTier5Rocket());
    	
    }
    
    private void registerRecipesWorkBench()
    {
    	Tier4RocketRecipe.registerRecipeWorkBench();
    	Tier5RocketRecipe.registerRecipeWorkBench();
    }
    
    
    

   

}

**Comment by micdoodle8** [comment]
Sorry, I meant a zip file of the source of your project. If you don't want to share it publicly you can send it to micdoodle8@gmail.com

**Comment by SteveKunG** [comment]
OK. I send my source code into your gmail.

**Comment by micdoodle8** [comment]
Okay, fixed some issues. Not the "ghost rings" yet, but some other pretty major stuff.

Replace your initSolarSystems code with this:
https://gist.github.com/micdoodle8/8e47fae8ace6da6a260c

Combine that with the commit I've pushed to this  repo, and a lot of map bugs will be fixed.

**Comment by micdoodle8** [comment]
Okay, all map bugs should now be fixed. If you have any other troubles with your addon please let us know.

**Comment by SteveKunG** [comment]
Thank you very much for fix fake ring :). But I'm found some minor bug when I tried to change my custom solar system position.
![2558-04-06_13 33 20](https://cloud.githubusercontent.com/assets/6128413/7002693/f9ff2744-dc78-11e4-85f6-c2dd361502b9.png)
![2558-04-06_13 34 10](https://cloud.githubusercontent.com/assets/6128413/7002694/fa023d6c-dc78-11e4-964f-a1c27a9d737c.png)
![2558-04-06_13 34 33](https://cloud.githubusercontent.com/assets/6128413/7002695/fa0269c2-dc78-11e4-92b8-f79ce6abe353.png)
