### ISSUE TITLE
Suggestion for Jupiter

### ISSUE THREAD

**Issue by sfxworks** [micdoodle8/Galacticraft#1503]
When you include Jupiter....Can you add it's moon too?
http://insightticker.com/2015/03/16/347/nasa-confirms-jupiters-moon-ganymede-contain-massive-subsurface-oceans/

**Comment by radfast** [comment]
Suggestions belong on the forum, not here.  There are existing substantial discussions on Jupiter's moons.
http://forum.micdoodle8.com/index.php?forums/suggestions.7/
