### ISSUE TITLE
Oxygen bubble remains

### ISSUE THREAD

**Issue by lukepollard** [micdoodle8/Galacticraft#1504]
If you destroy a oxygen bubble distributer with the bubble showing it will continue to show that bubble after you delete it and you cannot get rid of it.

**Comment by micdoodle8** [comment]
I was unable to recreate this after multiple attempts. I need some more information on how to recreate this, for example:

- Happened on a multiplayer server / single player
- Happened right after placing the oxygen bubble distributor
- Happened after unloading the chunk and going back

.. etc

Thanks.

**Comment by lukepollard** [comment]
Hi, I appreciate your reply. To see a developer so proactive on mod issues is amazing.

As for the issue it was on a multiplayer, on the space station dimension. I placed the item with creative power and oxygen and then removed the distributer and the bubble remained. But I am opped so the chunk was loaded.

However I restarted the server and all appears fine now. The bubble os no longer there. It may have been the server trying to catch up on itself.

Thanks for your reply thou!

Luke
________________________________

**Comment by radfast** [comment]
__How__ did you remove the distributor?  Did you do it in Creative mode?  Also which exact Galacticraft version number please.

**Comment by SonarBeserk** [comment]
Encountered the same issue in build 305. The bubble is still counted as there even if not able to be seen until the server is restarted. You are fully safe in the area where it was.

**Comment by radfast** [comment]
Thanks for raising, this should be fixed in next build 3.0.12.336.
See [d05d1e3](https://github.com/micdoodle8/Galacticraft/blob/d05d1e3c33cf2e7f38dd7b37ed107563e42567a9/src/main/java/micdoodle8/mods/galacticraft/core/tile/TileEntityOxygenDistributor.java#L96)
