### ISSUE TITLE
Moon lander fuel

### ISSUE THREAD

**Issue by babybasher** [micdoodle8/Galacticraft#1507]
You can't seem to use a partially filled fuel cannister to retrieve the fuel from your moon lander.

I always have to empty whats in my cannister (into my fuel loader of course), before I can retrieve the fuel from the moon lander.

I have no issues getting the fuel from my para chest in the overworld.  That always works with a partially filled cannister.

**Comment by radfast** [comment]
Thank you for reporting, that's probably a 1 line fix.  We'll look into this.
