### ISSUE TITLE
3.0.10.298 only - Refineries converting oil straight into fuel without needing to work.

### ISSUE THREAD

**Issue by babybasher** [micdoodle8/Galacticraft#1514]
Running the latest build .298 in a survival world.

When I add filled oil cannisters to my refinery, no oil appears in it.  The refinery says "No Oil", tried putting in 6 filled cannisters. The cannisters empty, but no oil appears in refinery.

I made a creative world to test.  Putting oil in a refinery (unpowered and powered) in creative automatically refined the oil into fuel instantly. Don't know if thats normal for creative, i'm only concerned about the first issue in survival :P

Thanks

**Comment by radfast** [comment]
oops, that looks like a new bug which was added in .298.  https://github.com/micdoodle8/Galacticraft/commit/f847eb316fe8c5918ef4e57cae5cf60e357ec797

The oil is going into the Refinery but actually it's going into the wrong tank - it's going directly into the Fuel tank so it gets refined without doing any work.  (Same thing in either Creative or Survival modes.)

Please either live with this until we get it fixed, or roll back to .297, it's up to you.

You are not losing your oil.

**Comment by radfast** [comment]
Fixed in latest 3.0.10.300 - please update to that.
