### ISSUE TITLE
Crash on launch with latest version (#299)

### ISSUE THREAD

**Issue by xJon** [micdoodle8/Galacticraft#1519]
http://pastebin.com/0ZgN1YCd

**Comment by radfast** [comment]
new build 300 fixes.   Thank you very much for raising so promptly, lets us fix it before too many people are affected.   299 was a late night build I made with a stupid error.

**Comment by xJon** [comment]
I can confirm it launches with build 300, and no problem - this is the least I can do as a user, thanks for the support! [:

**Comment by radfast** [comment]
:)

Keep them coming!  We are very grateful for all issue reports  (at least all the ones which are genuine Galacticraft issues).  Our goal is to have a super-stable Galacticraft.
