### ISSUE TITLE
Startup crash with .299 - fixed in .300

### ISSUE THREAD

**Issue by babybasher** [micdoodle8/Galacticraft#1521]
I swear I posted this already... must have forgotten to 'submit' :P

I get a server startup crash when using the .299 build

Downgrading to .298 and my server started fine.  Here is the crash log:

http://s000.tinyupload.com/index.php?file_id=01153874717738371310

Also, minecraft crashes when I launch the game (opening the game, not joining a world) with .299.  Here is the crash log for that :/

http://s000.tinyupload.com/index.php?file_id=74267924512921945079

**Comment by radfast** [comment]
ahem: https://github.com/micdoodle8/Galacticraft/issues/1520

**Comment by radfast** [comment]
Seems it may be best if I leave this open for today, so that anyone else affected sees this and knows to update to .300.

**Comment by babybasher** [comment]
Woops, I only had open topics viewable.  Sorry, will search in future.  Thanks!
