### ISSUE TITLE
Infinite Oxygen Supply (canister thing) doesn't work in decompressor like it says in its description

### ISSUE THREAD

**Issue by draksterau** [micdoodle8/Galacticraft#1523]
However it does work when put in a storage module!?

**Comment by Suikju** [comment]
you can put only the red, orange, and green tank into the decompressor. The infinite supply is similar too the  liquid one, thats why it doesnt work.

**Comment by draksterau** [comment]
My point is the description is wrong mainly. It says to place it in the decompressor for unlimited out.

I wasted 10 minutes thinking I did it wrong.

**Comment by Suikju** [comment]
hmm ok, i cant prove it. In the german description it just says that its an inifnite oxygen supply without any details.

**Comment by Suikju** [comment]
Sorry then ^^

**Comment by radfast** [comment]
There is no issue or bug here.  Everything is working as intended.
http://wiki.micdoodle8.com/wiki/Oxygen_Decompressor
http://wiki.micdoodle8.com/wiki/Infinite_Oxygen_Supply
