### ISSUE TITLE
java.lang.NullPointerException: Ticking entity

### ISSUE THREAD

**Issue by Alaberti** [micdoodle8/Galacticraft#1527]
http://pastebin.com/CTvseUu6 The full log. Galacticraft 3.0.10.301, Forge 1307.

-- Entity being ticked --
Details:
        Entity Type: null (micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP)

I'm not sure if this is a codechicken issue or Galacticraft. The player in question is constantly out exploring new chunks when this happens

**Comment by radfast** [comment]
99% sure this is not a Galacticraft issue.  The Minecraft vanilla EntityPlayerMP is always renamed to micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP whenever Galacticraft is installed, so any player-related crash from any mod will have a GCEntityPlayerMP showing in it somewhere.

The stacktrace shows this as connected with CodeChickenCore's "watchChunk" function, I'm not too sure what that is, but I think you'll have to raise it with CodeChicken.  If he says it is a Galacticraft issue, please link him to what I said here.

Closing for now, but you're welcome to post any further findings.

**Comment by EzerArch** [comment]
@Alaberti you should try to use the recommended versions of NEI and CodeChickenCore for 1.7.10, those are what I use with GC: http://chickenbones.net/Pages/links.html.
