### ISSUE TITLE
Oxygen warning message rendering

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#1528]
![2558-03-29_04 14 01](https://cloud.githubusercontent.com/assets/6128413/6884949/31a06d52-d634-11e4-83ef-4f50196f098b.png)
![2558-03-29_00 40 49](https://cloud.githubusercontent.com/assets/6128413/6884950/31d7e84a-d634-11e4-9e6b-c91480a9c72a.png)

**Comment by EzerArch** [comment]
Related to https://github.com/micdoodle8/Galacticraft/issues/1048#issuecomment-87306138, item 2.
