### ISSUE TITLE
Selecting moon zooms very far out.

### ISSUE THREAD

**Issue by dj3520** [micdoodle8/Galacticraft#1533]
Selecting the moon causes the map to zoom out very far.
![image](https://cloud.githubusercontent.com/assets/8284194/6911157/c4731534-d72a-11e4-858e-6ebd2ae60c5e.png)

**Comment by radfast** [comment]
Thank you for reporting.  The same issue is covered here: http://forum.micdoodle8.com/index.php?threads/solar-system-map-moon-space-station.5115/
and a fix is already committed: this will be fixed in the next build.

**Comment by dj3520** [comment]
Alright, thanks.

**Comment by radfast** [comment]
new build is out.
