### ISSUE TITLE
Evolved creepers not honoring mobGriefing gamerule

### ISSUE THREAD

**Issue by SonarBeserk** [micdoodle8/Galacticraft#1536]
Evolved Creepers as of at least builds 300-305 still cause destruction of the environment.

**Comment by micdoodle8** [comment]
Just tested, this evolved creepers do honor the rule. I'm not sure... either another mod is overriding the game rule, or you didn't set the rule correctly. This is also confirmed due to the fact that the actual "exploding code" is done in EntityCreeper.java, I'm not overriding it.
