### ISSUE TITLE
Freefalling Config?

### ISSUE THREAD

**Issue by azzanoodles** [micdoodle8/Galacticraft#1538]
Hey, I was just wondering if there was a way to disable free falling? Because it makes space stations unplayable in survival.

**Comment by radfast** [comment]
No.  No it doesn't make them unplayable.  What is it you are finding hard?

**Comment by azzanoodles** [comment]
Specifically building, I cannot use my jetpack from other mods (I assume because of free falling), making careful building a much more difficult task. That is probably more accurate but I want to play minecraft, not an ultra-realistic simulator, therefore I was wondering if there was a way to turn it off only for my session.

**Comment by azzanoodles** [comment]
Specifically building, I cannot use my jetpack from other mods (I assume because of free falling), making careful building a much more difficult task. That is probably more accurate but I want to play minecraft, not an ultra-realistic simulator, therefore I was wondering if there was a way to turn it off only for my session.

**Comment by radfast** [comment]
OK, so the real issue here is that the jetpack from other mods doesn't work in space.  That's in the Known Issues list but it's been there quite a while, we need to do something about this.  If we can't figure out a solution which seems OK to us, then maybe in that situation we will switch off the freefall mechanics when jetpacks are worn.

Which jetpack is it?

**Comment by azzanoodles** [comment]
Mekanism.

**Comment by radfast** [comment]
OK.  Give us a few days, we can do something about that.  I'm going to leave this issue closed as there are other open issues #1298 and #1420.

**Comment by azzanoodles** [comment]
Okay, thank you!

**Comment by EzerArch** [comment]
> then maybe in that situation we will switch off the freefall mechanics when jetpacks are worn.

Is it possible for MPS too? I use MPS jetpacks but they are useless in Space Station except in sealed spaces (https://github.com/micdoodle8/Galacticraft/issues/1383#issuecomment-72021090).
