### ISSUE TITLE
Oredictionary Desh and Meteoric Iron

### ISSUE THREAD

**Issue by JasonMcRay** [micdoodle8/Galacticraft#1539]
Would it be possible to remove Compressed Desh and Compressed Meteoric Iron from plateDesh and plateMeteoricIron oredictionary entries and put them into compressedDeshPlate and compressedMeteoricIronPlate?

Same as its done with Compressed Bronze, Tin etc... it will help with integrating into GregTech.

**Comment by radfast** [comment]
As GregTech is probably the only mod which picks these up from the OreDict, I'm happy to change it as needed.  But what about the names "compressedDesh" and "compressedMeteoricIron"?  Seems more logical.

**Comment by JasonMcRay** [comment]
Yea. That sounds fine. No idea why I put Plate in the end of each.
Thank you.
