### ISSUE TITLE
White strip on the left oxygen meter

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#1541]
A white strip appears on the left oxygen meter if the left tank is 100% full. It seems the left bar "overflows" the field it was supposed to be within.

![2015-04-04_05 32 49](https://cloud.githubusercontent.com/assets/6743303/6992025/43132c26-da8c-11e4-8412-765d9a4fa4de.png)

**Comment by dj3520** [comment]
Noticed this too but thought it was intentional.

**Comment by EzerArch** [comment]
> Noticed this too but thought it was intentional.

There's no practical use for that. I also have a slight impression the left meter lags behind the right one just a bit. That must be the cause.

**Comment by dj3520** [comment]
Sure there is. "Hey buddy, this one's 100% full."

**Comment by micdoodle8** [comment]
This wasn't intentional. Although it might be useful to someone wondering if their tank is at 100%, you can just look in your inventory to see if the tank has damage.
