### ISSUE TITLE
Armors don't hook to Evolved Zombie animation

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#1542]
Minor. Something has changed that Evolved Zombie animation is not in sync with armor.

![2015-04-04_12 05 36](https://cloud.githubusercontent.com/assets/6743303/6993185/f61546fc-dac2-11e4-9f79-df179fbf98c8.png)

![evolvzombie - wait to load](https://cloud.githubusercontent.com/assets/6743303/6993162/40a43eae-dac2-11e4-9c33-a3adf426cf7d.gif)

... I blame Radfast, he said something about adjusting mob movement according to the gravity or something. ;-)

**Comment by micdoodle8** [comment]
Any chance you know when the last time you saw them working fine was? 

Also, I can't seem to get zombies to wear armor... I'm failing hard at recreating this bug :P Any tips?

**Comment by Cracks777** [comment]
i know if you use mekanism theres a setting you can adjust to make mobs spawn with armor?

**Comment by EzerArch** [comment]
> i know if you use mekanism theres a setting you can adjust to make mobs spawn with armor?

Mekanism has this option but it's for Mekanism armor.

> Also, I can't seem to get zombies to wear armor... I'm failing hard at recreating this bug :P Any tips?

It's a rare occurrence. Set the game to Hard to increase the chances (0%-15%) and spawn dozens of Ev. Zombies during the daytime so those with no armor will burn away.

I've just tested with r308 with no other mod, the bug is there. I'll test with earlier versions.

**Comment by radfast** [comment]
It will most likely be this: https://github.com/micdoodle8/Galacticraft/commit/41cbf10080a9c7753d984fb8d46a89f467887fff
(@EzerArch does the glitch happen __only__ if you have Hard Mode enabled in configs?)

It can also be this, this was the gravity thing I changed (affects Hard Mode __and__ normal mode):
https://github.com/micdoodle8/Galacticraft/commit/41cbf10080a9c7753d984fb8d46a89f467887fff

**Comment by EzerArch** [comment]
> does the glitch happen only if you have Hard Mode enabled in configs?

No. My core.conf says:

```
    # Set this to true for increased difficulty in modpacks (see forum for more info).
    B:"Harder Difficulty"=false

    # Set this to true for less metal use in Galacticraft recipes (makes the game easier).
    B:"Quick Game Mode"=false
```

... and I get that glitch. I change that to "true", then I get this: http://youtu.be/BXWB6nCUZgc

**Comment by radfast** [comment]
> I'd put my bet on r279, which changes the way how Ev. Zombie biped model walks.

Thinking about it, I'm sure you are right, it must be this: https://github.com/micdoodle8/Galacticraft/commit/b017c036b856d95fba9e9be2bc6ea0ae7f15fb86  (I meant to post this above but posted the same twice, derp derp)

**Comment by micdoodle8** [comment]
That commit brought out the issue, but it was actually caused by the evolved zombie "armor model" still using the vanilla model class. Fixes in the commit mentioned above.

**Comment by EzerArch** [comment]
> That commit brought out the issue, but it was actually caused by the evolved zombie "armor model" still using the vanilla model class.

I was thinking something around these lines (so that I had changed the issue title). I feel a bit bad for having said it was a bug, but instead it was just an unfinished feature.

Just out of curiosity: Will Evolved Zombies move fast but their legs just a little, or the animation will adjust according to the local gravity?

**Comment by radfast** [comment]
From memory I think the animation adjusts according to the gravity.

**Comment by EzerArch** [comment]
Not fixed with Mekanism armor: 

![2015-04-14_05 12 43](https://cloud.githubusercontent.com/assets/6743303/7133024/3065fb5e-e265-11e4-89a4-a32b58a24d62.png)

**Comment by radfast** [comment]
aaargghh.  This needs @micdoodle8's special skills, I think.

(Or, worst case, we can make the zombies have vanilla movement if they are wearing non vanilla armor)

How did you spawn a zombie with Mekanism armor anyhow - I mean is there a trick to do that on demand (for testing) or was it just random luck?

**Comment by Cracks777** [comment]
i change this,  general {
        D:MobArmorSpawnRate=0.03
in the mek config so that all my mobs spawn with mek armor.

**Comment by radfast** [comment]
Thank you @Cracks777 - that could be very useful, I didn't know about that config

**Comment by Cracks777** [comment]
not a problem.
