### ISSUE TITLE
Hitbox of heavy aluminium wire to small

### ISSUE THREAD

**Issue by fayer3** [micdoodle8/Galacticraft#1543]
It seems that the hitbox of the heavy aluminium wire is to small.
![2015-04-04_19 41 19](https://cloud.githubusercontent.com/assets/8282299/6993854/f5961f9a-db02-11e4-8792-013514e0d85c.png)

using Galacticraft 1.7-3.0.11.310

**Comment by radfast** [comment]
Thank you.  By coincidence the excellent @SteveKunG spotted this and fixed it in #1516, the fix will be in the next build (.313).
