### ISSUE TITLE
Frequency Module Server Crash

### ISSUE THREAD

**Issue by rygold** [micdoodle8/Galacticraft#1551]
If one player gives another player a linked Frequency Module, the game crashes if the 2nd player equips it. Edit: Seems to be its when the host equips it, regardless of origin. Edit2: Seems to be because of a fake player-esque mod, but I dont have one.

For info:
LAN server.
Minecraft version 1.7.10
Latest Galacticraft version, downloaded this morning.

**Comment by radfast** [comment]
Please post the crash report.

**Comment by kpoe** [comment]
I have experienced similar problems with multiplayer and the use of frequency modules. With my experience, however, when a player has a frequency module equipped, and they open their single player game to LAN, and another player joins, it crashes. Additionally, if the LAN is already open and another player is in ther game, when the host equips their frequency module, the game crashes. Players who have joined and are not the host don't seem to trigger this by equipping a frequency module. Hope this helps. I have several examples in crash reports but here is just one:


---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 5/16/15 5:39 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at micdoodle8.mods.galacticraft.core.tick.TickHandlerServer.onServerTick(TickHandlerServer.java:217)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_68_TickHandlerServer_onServerTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:260)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:536)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.6.8
	Java Version: 1.6.0_65, Apple Inc.
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
	Memory: 251412592 bytes (239 MB) / 504160256 bytes (480 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 102
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 6 mods loaded, 6 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GalacticraftCore{3.0.11} [Galacticraft Core] (GalacticraftCore-1.7-3.0.11.306.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GalacticraftMars{3.0.11} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.11.306.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [GCEntityPlayerMP['k_poe'/167, l='C&C Space', x=-624.98, y=69.00, z=-4141.71]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by radfast** [comment]
Thanks kpoe, that's exactly what I needed.  We can probably get this fixed today now.

**Comment by radfast** [comment]
Please test new version [3.0.12.342](http://ci.micdoodle8.com/job/Galacticraft-1.7/342/).  I hope this should fix all issues of this kind.  Sorry it has taken a while to fix.
