### ISSUE TITLE
Color-coded sides incorrect on refinery

### ISSUE THREAD

**Issue by Brycey92** [micdoodle8/Galacticraft#1553]
The oil and fuel color-coded sides on a GC refinery are switched. Oil must be input through the side with the yellow ring, and fuel is output through the side with the black ring. I am running GC build 312.

**Comment by radfast** [comment]
Thank you, we'll have to fix that.  Which type of fluid pipes are you using, so that we can test?

**Comment by Brycey92** [comment]
I use Extra Utilities to extract fuel, but BuildCraft to insert oil, as ExU seems to be unable to insert oil for some reason.

**Comment by radfast** [comment]
thanks for reporting, this is fixed next build
