### ISSUE TITLE
Gravity on space station is messed up.

### ISSUE THREAD

**Issue by halvors** [micdoodle8/Galacticraft#1555]
Gravity on space station is messed up. Seems that i'm in fly mode or something... But i'm not.

You're not falling to the ground, you have to SHIFT to go down. It's weird.

**Comment by dj3520** [comment]
Intentional behavior I believe.

**Comment by halvors** [comment]
@dj3520 You sure? Because it seems like fly mode. And i'm getting kicked out with the message "Fly mode not enabled on this server". So anyway that should be fixed for the space station dimension.

**Comment by iPencil** [comment]
What makes you think you can/will "float" downwards in a no gravity environment (physics class anyone??)? I agree it feels weird to play like that but from logic/realistic view it's fine.

**Comment by halvors** [comment]
I know that it's realistic, but it annoys me that you can shift click when building blocks to prevent falling down. And being able to shift click etc is not realistic either unless you have a jetpack or some kind of thrust.

Slowly falling down would then be more practical.

And also dropped items is falling down, i suppose that is not very realistic then? If this is intentional items should float as well.

I know. But say i don't want to allow fly mode cheat on the rest of the server?

**Comment by iPencil** [comment]
As I said I know it's weird to build there, but if you take away the "almost-zero-G" gravity in space stations then whats so special about it? Considering this is still MineCraft, I think it's as close to real zero-G we can get :D.

Also, disallow flight in the properties fixes maybe 0.1% of the flyhacks :D

**Comment by radfast** [comment]
@halvors you should not be being kicked for flying.  Please provide server logs covering the time period when you were kicked.  Also details of the server, like version, is it Cauldron, any plugins etc.

The rest is intentional.  I express my continual amazement that players of a space mod raise comments when space turns out to be ... like space.   The reason there is some acceleration / deceleration allowed using keyboard controls even when you are in freefall is because otherwise it would be completely unplayable - it is a game not a simulator.

Further reading: http://wiki.micdoodle8.com/wiki/Overworld_Space_Station

**Comment by halvors** [comment]
Yeah i understand that this is intentional, just think that dropped items should in that case have zero-G too and that "fly-mode" should be allowed in space station dimensions. And that it should somehow be possible to SHIFT click when walking on a floor edge to avoid going outside it and fall down.

**Comment by halvors** [comment]
@radfast Also the reason why i was asking this is because before it was some gravity on the space station.

Also is it an idea that you need to have some sort of thrust/jet pack in order to move on the space station? So if you forget that you're basically lost in space, i think that would be cool. It would be a watch out like forgetting oxygen setup before going to space.

**Comment by halvors** [comment]
I do realize that this is not the place to come up with suggestions, except from my point of sight this is more a solution to already a "buggy" experience. So anyway, i've added this to the suggestion section of the forum: http://forum.micdoodle8.com/index.php?threads/reqiure-thrust-jetpacks-in-order-to-move-on-a-space-station.5156/

**Comment by radfast** [comment]
I understood what you are saying now: the vanilla SNEAK motion, where you walk to the edge of a block without falling off it, is not working on Space Stations.  That needs to be fixed.

**Comment by halvors** [comment]
@radfast Ah ok. I assumed that this was a bug. Is there another issue open for this?
