### ISSUE TITLE
When i try to go to the moon it gets stuck on downloading terrain

### ISSUE THREAD

**Issue by Dextroyer12** [micdoodle8/Galacticraft#1556]
Please Help Don't know what to do like i said when i try to go to the moon i click on moon and it gets stuck on downloading terrain.

**Comment by radfast** [comment]
Which version of Galacticraft?  The first thing to try is update to the latest version.
http://micdoodle8.com/mods/galacticraft/downloads

**Comment by radfast** [comment]
Closing due to lack of any response in 2 weeks.

If there is a response (or if anyone else is affected by this issue) I will re-open this.
