### ISSUE TITLE
crash after attacking a mob

### ISSUE THREAD

**Issue by leftyde** [micdoodle8/Galacticraft#1561]
http://pastebin.com/cX1NcZCY

crashed after I attacked a mob from GrimoireOfGaia3, so I don't know if it is GC or GoG so I postet it on both mods.

**Comment by radfast** [comment]
This has no connection at all with Galacticraft.

The error is connected with this ```com.flashoverride.heartdrop``` and some interaction between that and GrimoireOfGaia.
