### ISSUE TITLE
[Add-on] Solar system disappear when zooming

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#1563]
I'm found some minor bug when I tried to change my custom solar system position.

Here is my code.

    MorePlanetsCore.siriusSolarSystem = new SolarSystem("sirius", "milkyWay").setMapPosition(new Vector3(1.1F, 1.2F, 0.4F));
    MorePlanetsCore.sirius = new Star("sirius").setParentSolarSystem(MorePlanetsCore.siriusSolarSystem);
    MorePlanetsCore.sirius.setTierRequired(-1);
    MorePlanetsCore.sirius.setBodyIcon(new ResourceLocation("mpcore:textures/gui/celestialbodies/sirius_celestial.png"));
    MorePlanetsCore.siriusSolarSystem.setMainStar(MorePlanetsCore.sirius);

    MorePlanetsCore.kapteynBSolarSystem = new SolarSystem("kapteyn", "milkyWay").setMapPosition(new Vector3(-1.2F, 0.6F, -0.9F));
    MorePlanetsCore.kapteyn = new Star("kapteyn").setParentSolarSystem(MorePlanetsCore.kapteynBSolarSystem);
    MorePlanetsCore.kapteyn.setTierRequired(-1);
    MorePlanetsCore.kapteyn.setBodyIcon(new ResourceLocation("kapteynb:textures/gui/celestialbodies/kapteyn_star_celestial.png"));
    MorePlanetsCore.kapteynBSolarSystem.setMainStar(MorePlanetsCore.kapteyn);

![fa0269c2-dc78-11e4-92b8-f79ce6abe353](https://cloud.githubusercontent.com/assets/6128413/7084052/17f4d4b6-df93-11e4-8c51-0db0352af906.png)
![f9ff2744-dc78-11e4-85f6-c2dd361502b9](https://cloud.githubusercontent.com/assets/6128413/7084051/17f32c92-df93-11e4-8ca5-315c737aaeaa.png)
![fa023d6c-dc78-11e4-964f-a1c27a9d737c](https://cloud.githubusercontent.com/assets/6128413/7084053/17fcef3e-df93-11e4-9b63-3f771b243d64.png)

**Comment by radfast** [comment]
If possible please help me by finding a fix for this in GC code and post a Pull Request, then I will merge it.

**Comment by SteveKunG** [comment]
Sorry for missing information. 
Here is my full info : https://www.youtube.com/watch?v=YbGBmh1wGOU

**Comment by drunksob** [comment]
@SteveKunG This has been bugging me for a while also. Hey Steve if you do atempt to fix this, just an idea.. you should look into if its possible to do simple left right up down arrows or grab and drag on the gc map.
