### ISSUE TITLE
Are you working on a new galacticraft version?

### ISSUE THREAD

**Issue by Miguel1042** [micdoodle8/Galacticraft#1567]
Hello, I have a question for you. Are you working in galacticraft 4? I love that mod and I will be very thankful if you tell me when is ti going to be finnished.
And what is the next planet, is it venus? A Júpiter´s moon? 
Thanks!
![interrogacion](https://cloud.githubusercontent.com/assets/11526915/7103273/c9061064-e09f-11e4-99fb-7e077a703d0d.png)

**Comment by EzerArch** [comment]
This topic was specially made for people like you: http://forum.micdoodle8.com/index.php?threads/3753 :)

**Comment by Miguel1042** [comment]
thenks
