### ISSUE TITLE
Telepad appear direction

### ISSUE THREAD

**Issue by aschmois** [micdoodle8/Galacticraft#1568]
When teleporting your direction is not saved and are always teleported facing one direction. Is this fixable?

**Comment by EzerArch** [comment]
I can't reproduce it in 3.0.11.315. The "f" value (in the debug screen) was saved.

![2015-04-11_20 57 26](https://cloud.githubusercontent.com/assets/6743303/7103744/6664cc00-e08d-11e4-8988-3e0f596417b5.png)
![2015-04-11_20 57 30](https://cloud.githubusercontent.com/assets/6743303/7103745/666f641c-e08d-11e4-8964-dcb41e4056f4.png)

**Comment by radfast** [comment]
Closing for now.

If there is more information to show a reproduceable issue, I will re-open.

@aschmois?
