### ISSUE TITLE
A mod is causing another regular inventory tab to show up, any ideas? (ill put mod list in here just in case)

### ISSUE THREAD

**Issue by Nick-77ab2** [micdoodle8/Galacticraft#1570]
no picture yet, ill have a picture quickly just need to load stuff up and take one

**Comment by Nick-77ab2** [comment]
might take a bit longer i derped on something

**Comment by Nick-77ab2** [comment]
![2015-04-11_22 55 25](https://cloud.githubusercontent.com/assets/8357073/7104333/e9d52c14-e09d-11e4-8d50-e03610ea5ced.png)

**Comment by Nick-77ab2** [comment]
its really annoying as it ironically pushes the galacticraft tab off of the tabs list, and shows both are clicked at the same time

**Comment by Nick-77ab2** [comment]
actually there are a ton of mods but ill list as much as i can

**Comment by Nick-77ab2** [comment]
here are ones that add tabs:
galacticraft
ancient warfare
Mine and blade Battlegear 2(not the cause as added after the problem)
Custom NPC's
Baubles(not the problem as added after, I believe)

**Comment by dj3520** [comment]
Could you please use the post edit button instead? PLEASE?

**Comment by Nick-77ab2** [comment]
?

**Comment by Nick-77ab2** [comment]
i....did

**Comment by Nick-77ab2** [comment]
im just totally confused about what mod is causing this and am asking if you guys no if not then i can just close it

**Comment by dj3520** [comment]
For your posts, please use the edit button. This isn't a chat room and everyone gets an email for every post you make.

**Comment by Nick-77ab2** [comment]
ah xD sorry *rubs back of head* i didnt know that :(

**Comment by dj3520** [comment]
Also, don't post "oops I don't have a picture yet" just wait until you have a picture and then create the issue.

**Comment by EzerArch** [comment]
@Nick-77ab2, please I ask you to avoid spamming the git.

For your information: Every time someone posts, an email is sent to everyone else following this git, you are spamming our mailboxes with your one-liners, and I doubt you will draw developers' attention this way.

This is not a chat, please prefer to edit your post to add *relevant* info.

**Comment by radfast** [comment]
Updating Galacticraft to latest should fix the "extra vanilla tab" issue.  If not you can let us know.  With one post only, please.

**Comment by Nick-77ab2** [comment]
I already had latest, and yes it's still there, i can test it in a world with just those mods and slowly take then out to see which mod adds it.
