### ISSUE TITLE
ASM Conflict with ChromatiCraft v6d

### ISSUE THREAD

**Issue by grimallq** [micdoodle8/Galacticraft#1571]
This happens when running GalactiCraft (any recent version) with ChromatiCraft v6d:

Report:
https://paste.ee/p/KJ8r7

Log:
http://paste.ee/p/V2543

This is probably on Reika's side since it started with the v6d update. Just FYI.

**Comment by radfast** [comment]
I'm seeing this in the log:
``` [12:35:13] [main/ERROR] [LaunchWrapper]: A critical problem occurred registering the ASM transformer class
java.lang.ClassNotFoundException:
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]```

This appears to me to be a MultiMC issue.

I can't tell whether its Galacticraft (MicdoodleCore) or DragonAPI or another mod causing the issue, but my guess is Galacticraft is OK here, see this line:
```[12:35:13] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodlePlugin:getASMTransformerClass:102]: Successfully Registered Transformer```

**Comment by grimallq** [comment]
Figured as much. Just for the sake of argument logs from Mojang Launcher:

https://paste.ee/p/k62z4
https://paste.ee/p/cwpgz
https://paste.ee/p/RW3HQ

**Comment by radfast** [comment]
I'm not sure about all those logs, there seem to be other errors in some of them but in the last one (XZ5wq) I'm seeing logging about ```ChromaASMHandler```, my guess is the MultiMC issue is connected with that.

**Comment by grimallq** [comment]
OK, thanks.

**Comment by radfast** [comment]
Reika and I have worked together to fix this - it should be fixed in the next ChromatiCraft release v6e later today.
