### ISSUE TITLE
Key bug when in Gui Chat or Gui Manu in game

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#1579]
Here : https://www.youtube.com/watch?v=CtN_hKQeAes

**Comment by EzerArch** [comment]
Hmm, let me describe the bug: the W/A/S/D/F keybinds were not supposed to affect/steer the moon buggy if the chat is open. Confirm?

**Comment by radfast** [comment]
@EzerArch   that's certainly a bug I'm seeing from @SteveKunG's video.  Happening if either chat is open or any GUI.  It should be easy enough to fix.
