### ISSUE TITLE
Oxygen Indicator rendering problem by using old GC 2 texture

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#1582]
![2558-04-12_02 06 44](https://cloud.githubusercontent.com/assets/6128413/7179223/cee9392a-e45f-11e4-9964-62dadccd4cc0.png)

And I see a small green line on the left of Oxygen Indicator.

**Comment by radfast** [comment]
See also: https://github.com/micdoodle8/Galacticraft/issues/1541

**Comment by EzerArch** [comment]
Oh, this is still haunting GC. Looks like GC is mapping gui.png wrong.

I opened gui.png (of my resouce pack) in the editor and drew a purple line in the meter just to see where it would end up:

![untitled](https://cloud.githubusercontent.com/assets/6743303/7228239/82e6893a-e72d-11e4-9ec9-9966e332236e.png)

and...

![2015-04-20_07 13 07](https://cloud.githubusercontent.com/assets/6743303/7228253/9db2ca12-e72d-11e4-99fe-103a1647e051.png)

It seems GC samples and stretches wrong the png file on the UI.

**Comment by SteveKunG** [comment]
![2559-02-21_13 00 02](https://cloud.githubusercontent.com/assets/6128413/13201249/0aa3b0c8-d89b-11e5-9e47-5cefe57c2cb6.png)

OK. I think its should fix by this texture.
![gui](https://cloud.githubusercontent.com/assets/6128413/13201252/2c5a4344-d89b-11e5-8c33-3a24206b36f2.png)

And I think its no longer used.

**Comment by radfast** [comment]
Thank you very much.  It's a good texture :)
