### ISSUE TITLE
Third person view bug when kill yourself while Rocket is flying

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#1590]
Step to reproduce
1. Riding a rocket and flying to the sky
2. Using /kill command while rocket is flying
3. You get this view like this pictures

![2558-04-18_02 13 23](https://cloud.githubusercontent.com/assets/6128413/7214867/88a16be2-e5e8-11e4-8aa2-84d7c8c88d4c.png)
![2558-04-18_02 13 28](https://cloud.githubusercontent.com/assets/6128413/7214866/88a048e8-e5e8-11e4-8432-26aa21424055.png)

**Comment by radfast** [comment]
You can fix this by pressing F5 and F5 again, the same way as with any other third person view issues.

I don't think this is a "bug".  Who types the /kill command while flying in a rocket?
