### ISSUE TITLE
Grapple doesn't reel back if player is not on solid block

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#1593]
Grapple doesn't reel back nor does it push the player along with if he or she is not touching a solid block or floating away, exact when the player most needs it.

And it leads to some situations like this:

![2015-04-18_23 08 45](https://cloud.githubusercontent.com/assets/6743303/7217873/1a741218-e620-11e4-8b52-3d015200c065.png)

**Comment by radfast** [comment]
Thank you, good spot.  Fixed in build 323.

I think the fix for this __may__ have also improved the position for jetpacks from other mods, including MMMPS - feedback welcome :)

**Comment by EzerArch** [comment]
Oh thank you! :+1:
