### ISSUE TITLE
installing

### ISSUE THREAD

**Issue by LoOnyBin25** [micdoodle8/Galacticraft#1596]
https://dl.dropboxusercontent.com/u/20748481/MC/bspkrsCore/[1.7.10]bspkrsCore-universal-6.12.jar

This link no workie workie lol

**Comment by EzerArch** [comment]
What does that have to do with Galacticraft?

**Comment by LoOnyBin25** [comment]
well download the mods place in mods folder the run game the it should be downloading something for galacticraft in the install phase but it cant because the link is broken

**Comment by LoOnyBin25** [comment]
![error](https://cloud.githubusercontent.com/assets/10241185/7219302/33b9564c-e699-11e4-812c-47f11646dc72.jpg)

**Comment by LoOnyBin25** [comment]
they say a picture is a 1000 words

**Comment by EzerArch** [comment]
> they say a picture is a 1000 words

Your picture doesn't say anything about Galacitcraft attempting to download bspkrsCore.

Galacitcraft *does not* download bspkrsCore, neither does Galacitcraft need it. You probably might have any of bspkrs' mods installed (e.g. ArmorStatusHUD, DirectionHUD, StatusEffectHUD).

What you need is here: http://www.curse.com/mc-mods/minecraft/bspkrscore#t1:other-downloads, and save [1.7.10]bspkrsCore-universal-6.12.jar in mods/1.7.10.

Oh, please, use the EDIT button. Git is not a chat. Git sends an email to everyone every time someone replies here.

**Comment by radfast** [comment]
Thank you @EzerArch, you said it all :)
