### ISSUE TITLE
Crashes when loading new world

### ISSUE THREAD

**Issue by l3CY** [micdoodle8/Galacticraft#1597]
This crash occurs with both the Stable and Latest versions.
http://pastebin.com/Zf2ab4pP

I'm able to load to the minecraft title menu just fine.  However, an attempts to load a world result in a crash.

**Comment by radfast** [comment]
Don't use MultiMC.

MultiMC is not explicitly supported by Galacticraft.  Some people have figured out how to make it work OK, but if there is even the smallest thing wrong with your MultiMC setup then it will not work.
(Probably, it's because you have the mods and libraries in the wrong folders.)

**Comment by radfast** [comment]
http://wiki.micdoodle8.com/wiki/Tutorials/Galacticraft_Installation_Guide#MultiMC_problems

**Comment by radfast** [comment]
It could also be connected with the security changes Mojang just made in 1.8.4, which have - apparently - affected all the non-vanilla launchers.

You did not say whether your setup was working before?

Either way, it's not a Galacticraft issue.

**Comment by radfast** [comment]
Other players here are saying it's an issue caused by using Optifine with MultiMC, maybe fixed by updating Optifine: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287888-galacticraft-3-4-100-000-downloads?page=126

**Comment by radfast** [comment]
http://www.optifine.net/changelog?f=OptiFine_1.7.10_HD_B6.jar

**Comment by l3CY** [comment]
Thank you.  I've updated Optifine and it works again.
