### ISSUE TITLE
Texture Error

### ISSUE THREAD

**Issue by Bravemark1** [micdoodle8/Galacticraft#1600]
---- Minecraft Crash Report ----
// Sorry :(

Time: 20.4.2015 16:44
Description: Registering texture

net.minecraft.client.renderer.StitcherException: Unable to fit: galacticraftmars:pipe_hydrogen - size: 16x16 - Maybe try a lowerresolution resourcepack?
	at net.minecraft.client.renderer.texture.Stitcher.func_94305_f(SourceFile:56)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:242)
	at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:90)
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(SourceFile:72)
	at net.minecraft.client.renderer.texture.TextureManager.func_110580_a(SourceFile:61)
	at net.minecraft.client.renderer.texture.TextureManager.func_130088_a(SourceFile:52)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:537)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.texture.Stitcher.func_94305_f(SourceFile:56)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:242)
	at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:90)

-- Resource location being registered --
Details:
	Resource location: minecraft:textures/atlas/blocks.png
	Texture object class: net.minecraft.client.renderer.texture.TextureMap
Stacktrace:
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(SourceFile:72)
	at net.minecraft.client.renderer.texture.TextureManager.func_110580_a(SourceFile:61)
	at net.minecraft.client.renderer.texture.TextureManager.func_130088_a(SourceFile:52)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:537)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows XP (x86) version 5.1
	Java Version: 1.8.0_40, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 195530304 bytes (186 MB) / 406224896 bytes (387 MB) up to 510918656 bytes (487 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx500M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 75 mods loaded, 75 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	NotEnoughItems{1.0.3.74} [Not Enough Items] (NotEnoughItems (1.0.3.74).jar) Unloaded->Constructed->Pre-initialized
	lucky{5.0.0} [Lucky Block] ([1-7-2]_Lucky_Block_v5-0-0.jar) Unloaded->Constructed->Pre-initialized
	MoreWolvesMod{1.6.2} [MoreWolvesMod] ([1.7.10-1.7.2]MoreWolvesMod.jar) Unloaded->Constructed->Pre-initialized
	lasermod{v1.1.0a} [Laser Mod] ([1.7.10] Laser Mod - v1.1.0a.jar) Unloaded->Constructed->Pre-initialized
	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized
	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) Unloaded->Constructed->Pre-initialized
	More Crafting Recipes Mod{Minecraft 1.7.2} [More Crafting Recipes Mod] ([2.1.1] More Crafting Recipes Mod.jar) Unloaded->Constructed->Pre-initialized
	advancedgenetics{1.5.7} [Advanced Genetics] (advancedgenetics-1.7.10-1.5.7.jar) Unloaded->Constructed->Pre-initialized
	Aquaculture{1.2.3} [Aquaculture] (Aquaculture (1.2.5.8).jar) Unloaded->Constructed->Pre-initialized
	iChunUtil{4.1.2} [iChunUtil] (iChunUtil (4.1.2).jar) Unloaded->Constructed->Pre-initialized
	Grinder{4.0.0} [Grinder] (AttachableGrinder (4.0.0).jar) Unloaded->Constructed->Pre-initialized
	Backpack{2.0.0} [Backpack] (Backpack (2.0.0).jar) Unloaded->Constructed->Pre-initialized
	battlegear2{1.0.7.0} [Mine & Blade Battlegear 2 - Bullseye] (Battlegear 2 (1.0.7.0).jar) Unloaded->Constructed->Pre-initialized
	FLabsBF{4.3} [Better Furnaces] (Better Furnaces (4.3).jar) Unloaded->Constructed->Pre-initialized
	CoFHCore{1.7.10R3.0.0B8} [CoFH Core] (CoFHCore (3.0.0B8-36).jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Core{6.4.3} [BuildCraft] (buildcraft-6.4.3.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Transport{6.4.3} [BC Transport] (buildcraft-6.4.3.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Silicon{6.4.3} [BC Silicon] (buildcraft-6.4.3.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Builders{6.4.3} [BC Builders] (buildcraft-6.4.3.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Energy{6.4.3} [BC Energy] (buildcraft-6.4.3.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Factory{6.4.3} [BC Factory] (buildcraft-6.4.3.jar) Unloaded->Constructed->Pre-initialized
	chisel{1.5.7} [Chisel] (Chisel (1.5.7).jar) Unloaded->Constructed->Pre-initialized
	customrecipes{4.72} [Custom Recipes] (Custom Recipes (4.7).jar) Unloaded->Constructed->Pre-initialized
	EasyCrafting{1.7.10-2.0.1.16} [Easy Crafting] (Easy Crafting (2.0.1.16).jar) Unloaded->Constructed->Pre-initialized
	emeraldmod{3.1.3} [EmeraldMod] (EmeraldMod 1.7.2 Forge V3.2.jar) Unloaded->Constructed->Pre-initialized
	EnderIO{1.7.10-2.2.8.367} [Ender IO] (EnderIO-1.7.10-2.2.8.367.jar) Unloaded->Constructed->Pre-initialized
	enhancedbiomes{2.1 for MC 1.7.2} [Enhanced Biomes] (Enhanced Biomes 2.1 for MC 1.7.2.jar) Unloaded->Constructed->Pre-initialized
	enviromine{1.3.101} [EnviroMine] (EnviroMine (1.3.101).jar) Unloaded->Constructed->Pre-initialized
	exnihilo{1.37} [Ex Nihilo] (Ex Nihilo (1.37).jar) Unloaded->Constructed->Pre-initialized
	MetallurgyCore{4.0.4} [Metallurgy Core] (Metallurgy Core (4.0.4.180).jar) Unloaded->Constructed->Pre-initialized
	Mantle{1.7.10-0.3.1.jenkins180} [Mantle] (Mantle (0.3.1).jar) Unloaded->Constructed->Pre-initialized
	Waila{1.5.5} [Waila] (Waila (1.5.5).jar) Unloaded->Constructed->Pre-initialized
	TConstruct{1.7.10-1.6.0.build611} [Tinkers' Construct] (Tinkers Construct (1.6.0d40.1).jar) Unloaded->Constructed->Pre-initialized
	Metallurgy{4.0.6} [Metallurgy 4] (Metallurgy (4.0.6.80).jar) Unloaded->Constructed->Pre-initialized
	ExtraTiC{0.8.4} [ExtraTiC] (ExtraTiC (1.0.3).jar) Unloaded->Constructed->Pre-initialized
	fc{0.3.3} [FloorBallCraft] (fc-1.7.10-2.0.1.jar) Unloaded->Constructed->Pre-initialized
	FoodPlus{3.2rS} [§bFood Plus] (FoodPlus-(3.2rS).jar) Unloaded->Constructed->Pre-initialized
	GalacticraftCore{3.0.6} [Galacticraft Core] (GalacticraftCore-1.7-3.0.6.232.jar) Unloaded->Constructed->Pre-initialized
	GalacticraftMars{3.0.11} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.11.320.jar) Unloaded->Constructed->Pre-initialized
	Hats{4.0.1} [Hats] (Hats (4.0.1).jar) Unloaded->Constructed->Pre-initialized
	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (Inventory Tweaks (1.58-147).jar) Unloaded->Constructed->Pre-initialized
	IronChest{6.0.41.729} [Iron Chest] (Iron Chest (6.0.41.729).jar) Unloaded->Constructed->Pre-initialized
	journeymap{5.0.0RC2} [JourneyMap] (Journey Map (5.0.0RC2).jar) Unloaded->Constructed->Pre-initialized
	lom{1.7.10-3.0.3} [LotsOMobs] (lom-1.7.10-3.0.3.jar) Unloaded->Constructed->Pre-initialized
	more{1.0} [more] (M-Ore 1.7.2.jar) Unloaded->Constructed->Pre-initialized
	mopickaxes{630} [Mo' Pickaxes] (Mo' Pickaxes (630).jar) Unloaded->Constructed->Pre-initialized
	MoarFood{V5.8.0} [MoarFood] (MoarFood-5.8.0.jar) Unloaded->Constructed->Pre-initialized
	ModOfMoni{1.1.0} [ModOfMoni] (Mod of Moni (1.1.0).zip) Unloaded->Constructed->Pre-initialized
	Morph{0.9.1} [Morph] (Morph (0.9.1).jar) Unloaded->Constructed->Pre-initialized
	cfm{3.3.5} [§6MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.3.5(1.7.10).jar) Unloaded->Constructed->Pre-initialized
	NEIAddons{1.12.3.11} [NEI Addons] (NEI - Addon (1.12.3.11).jar) Unloaded->Constructed->Pre-initialized
	NEIAddons|Botany{1.12.3.11} [NEI Addons: Botany] (NEI - Addon (1.12.3.11).jar) Unloaded->Constructed->Pre-initialized
	NEIAddons|Forestry{1.12.3.11} [NEI Addons: Forestry] (NEI - Addon (1.12.3.11).jar) Unloaded->Constructed->Pre-initialized
	NEIAddons|CraftingTables{1.12.3.11} [NEI Addons: Crafting Tables] (NEI - Addon (1.12.3.11).jar) Unloaded->Constructed->Pre-initialized
	NEIAddons|ExNihilo{1.12.3.11} [NEI Addons: Ex Nihilo] (NEI - Addon (1.12.3.11).jar) Unloaded->Constructed->Pre-initialized
	NEIPlugins{1.1.0.8-unofficial} [NEI Plugins Unofficial] (NEI - Plugin (1.1.0.8).jar) Unloaded->Constructed->Pre-initialized
	NetherOres{1.7.10R2.3.0RC3} [Nether Ores] (Nether Ores (2.3.0RC3-84).jar) Unloaded->Constructed->Pre-initialized
	YogpstopLib{2.0.1} [Yogpstop Library] (Quarry Plus (2.0.1).jar) Unloaded->Constructed->Pre-initialized
	QuarryPlus{2.0.1} [QuarryPlus] (Quarry Plus (2.0.1).jar) Unloaded->Constructed->Pre-initialized
	securitycraft{v1.6.1} [SecurityCraft] (SecurityCraft v1.6.1 for 1.7.10.jar) Unloaded->Constructed->Pre-initialized
	SGCraft{1.9.0} [Greg's SG Craft] (SGCraft (1.9.0).jar) Unloaded->Constructed->Pre-initialized
	SSR{Alpha 0.9a} [Soul Shards: Reborn] (SSR (Alpha 0.9c).jar) Unloaded->Constructed->Pre-initialized
	StartingInventory{1.7.10.r03} [StartingInventory] (Starting Inventory (r03).jar) Unloaded->Constructed->Pre-initialized
	stillhungry{1.7.2-2.1.0} [Still Hungry!] (stillhungry-1.7.2-2.1.1.jar) Unloaded->Constructed->Pre-initialized
	TiCTooltips{1.1.11b} [TiC Tooltips] (Tinkers Tooltips (1.1.11b).jar) Unloaded->Constructed->Pre-initialized
	Translocator{1.1.1.14} [Translocator] (Translocator (1.1.1.14).jar) Unloaded->Constructed->Pre-initialized
	vending{1.2.0b} [Vending Block] (Vending (1.2.0b).jar) Unloaded->Constructed->Pre-initialized
	WailaHarvestability{1.1.2} [Waila Harvestability] (Waila Harvest (1.1.2).jar) Unloaded->Constructed->Pre-initialized
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	Launched Version: 1.7.10-Forge10.13.2.1291
	LWJGL: 2.9.1
	OpenGL: Intel 855GM GL version 1.3.0 - Build 4.14.10.4396, Intel
	GL Caps: Using GL 1.3 multitexturing.
Not using framebuffer objects because OpenGL 1.4 is not supported, EXT_blend_func_separate is supported, OpenGL 3.0 is not supported, ARB_framebuffer_object is not supported, and EXT_framebuffer_object is not supported.
Anisotropic filtering is supported and maximum anisotropy is 2.
Shaders are not available because OpenGL 2.1 is not supported, ARB_shader_objects is not supported, ARB_vertex_shader is not supported, and ARB_fragment_shader is not supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by Bravemark1** [comment]
Im using:
GalacticraftCore-1.7-3.0.6.232
Galacticraft-Planets-1.7-3.0.11.320
MicdoodleCore-1.7-3.0.11.320

**Comment by radfast** [comment]
It's not specifically Galacticraft causing that, it's just a coincidence that a Galacticraft texture is the one the game had reached when it ran out of resources.  There's nothing special about the Hydrogen Pipe texture, it's a pretty small 16x16 texture.

You might be able to fix this by changing graphics card OpenGL settings, expecially anything connected with texture memory.

If that doesn't work for you, then you may have to try playing with a smaller mods list, or a lower-res texture pack like the crash report advises you.

**Comment by radfast** [comment]
hmm, Intel 855GM is a graphics chipset dating from 2003.  You must be using a very old laptop, even older than mine (mine is a Dell Latitude from 2007).  No shame in that, but you shouldn't expect it to run a huge modpack.

**Comment by Bravemark1** [comment]
yea around 12 years old

**Comment by Bravemark1** [comment]
and like you see at the end im not using texture packs

**Comment by Bravemark1** [comment]
and how to change openGL settings?

**Comment by radfast** [comment]
Every time you post it emails the 100 or so people who are monitoring this Issues list for issues relevant to the Galacticraft mod.  You need to ask your support questions on a general Minecraft forum, not here.  As already stated, this is not an issue caused by the Galacticraft mod.
