### ISSUE TITLE
Ticking Entity. Exception In Server Tick Loop errors.

### ISSUE THREAD

**Issue by MtnDrew** [micdoodle8/Galacticraft#1610]
This started when I died in the nether, respawned, immediately ran back to the portal, and teleported back to the nether. As soon as it started loading in the nether, the game crashed and I got this report:

http://pastebin.com/tVwKNjzD

I started Minecraft up again, tried to load my world, but it crashed again and I got this different error:

http://pastebin.com/rwL1F1cB

I can't read these very well, but the first one seemed to be saying something about Galacticraft, I think. 

Opened it up a third time and got a different crash report. This one is a ticking entity crash now. I keep seeing that Galacticraft.core.entities.player error. Here's the report on that one: 

http://pastebin.com/VXkMHWst

**Comment by radfast** [comment]
These crashes have __no connection at all with Galacticraft__.

Did you read this?  [Guidelines for contributing](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md)   It was given to you at the top of the page _when you opened this issue_.  It explains somewhere in the middle of it that crash reports with lines like this:
>      at micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP.func_70097_a(GCEntityPlayerMP.java:73)

are not bugs or issues in Galacticraft, it's just a name change from the regular Minecraft name EntityPlayerMP to GCEntityPlayerMP.

This is not a "general Minecraft support area" but to try to help you a little:
* your first two crash reports look similar, I've not seen anything like it before but it could be connected with the way the world saved - you might need to delete a part of the world map (and have it automatically regenerated), but no promise that that will fix it
*  your third crash report looks to be connected with a CoFH mod, see this line:
>         at cofh.mod.updater.UpdateManager.tickStart(UpdateManager.java:82)

It's the lines at the __top__ of the crash report which tell you what went wrong, not the lines in the middle of it.

**Comment by MtnDrew** [comment]
I'm sorry about that. I sincerely thought it was galacticraft because at the time, even besides having that coreentitiesplayer message, I thought that the entity ticking might have been the Galacticraft machines I was running inside my base as I was doing all this stuff.
