### ISSUE TITLE
Galacticraft mobs spawning on the Overworld

### ISSUE THREAD

**Issue by PlanetBeast** [micdoodle8/Galacticraft#1620]
Hello! I'm currently having an issue with the most recent stable version of Galacticraft where some of the mobs you'd find on planets, mainly bosses, are spawning in the overworld randomly. The server is running Cauldron on forge 1291. I'd appreciate any guidance on how to get this fixed thanks!

**Comment by dj3520** [comment]
I'd imagine this is not Galacticraft's fault and you run more than just one mod on your server. If so, you mind posting a list of the mods you run on your server?

**Comment by PlanetBeast** [comment]
Applied Energistics 2
Bdlib
Bilbiocraft
Bilbliowoods BoP
Bibliowoods Forestry
Big Reactors
Binnie's Mods
Biomes O' Plenty
Blue Power
Botania
Buildcraft
Buildcraft Compat
Carpenter's Blocks
Chisel 2
CodeChickenCore
CoFHCore
ComputerCraft
DenseOres
EiraIRC
EnderIO
Ender Storage
Extra Utilities
Forestry
Galacticraft
Gendustry
iChunUtil
InventoryTweaks
Iron Chest
Jabba
Journey Map
Magic Bees
Mantle
Mekanism
Micdoodle Core
Minechem
Minefactory Reloaded
MineTweaker 3
Morph
MrCrayFish Furniture
NEI Addons
NEI Intergration
Not Enough Items
Morpheus
Open Blocks
OpenModsLib
Pam's Harvestcraft
QumunityLib
Railcraft
Redstone Arsenal
Simply Jetpacks
Tinker's Construct
Thaumcraft
Thaumic Energistics
Thaumic Exploration
Thaumic Tinkerer
Thermal Dyanmics 
Thermal Expansion
Thermal Foundation
Twilight Forest
WAILA
WAWLA

**Comment by PlanetBeast** [comment]
Sorry for the wall

**Comment by radfast** [comment]
Assuming you are playing on a server, this is not Galacticraft causing this, it's another mod which is set up differently between your client and your server.  Basically ... it's your fault.

To fix it:

1.  Check you have __exactly__ the same mod list on your client and your server (no extra mods on the client, except for clientside mods like Optifine or mapping mods)

2.  Check you have __exactly__ the same version of every mod on your client and your server.

3.  If that still doesn't fix it, check the __configs__ for all mods all exactly match between your client and your server

4.  Steps 1-3 will fix it in 99% of cases.  If not, then maybe it's a bug in another mod, but that's pretty unlikely.

The easiest way to do steps 1-3 could be to Zip up your ```/mods``` and ```/configs``` folder from the server, and on the client, delete the ```/mods``` and ```/configs``` folder and replace with what came from the server.

**Comment by radfast** [comment]
Duplicate of #1428 and probably others before that.
