### ISSUE TITLE
Exception in server tick loop on world reload

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#1624]
I was on Mars and closed the game. Now I'm getting "Exception in server tick loop" on attempting to load the world.

Crash log: https://gist.github.com/EzerArch/79081875cc5b6a415bc7
Forge log: https://gist.github.com/EzerArch/4c93209755a21bfef0df

EDIT: I managed to load my world. First I created a new world on creative, walked around, and then I opened actual world.

**Comment by radfast** [comment]
Thanks, I'm looking at this.  Did you by any chance update a mod between closing the game and attempting to reload?
