### ISSUE TITLE
When I join a server whilst playing with 1.7.10 Optifine, My Minecraft crashes. Why!?

### ISSUE THREAD

**Issue by JoeStoke03** [micdoodle8/Galacticraft#1625]

**Comment by radfast** [comment]
Seriously?

1.  Go report at Optifine, not here at Galacticraft.

2.  Try a search for your crash report.  I think 99% probability it's this: 
http://wiki.micdoodle8.com/index.php?title=Common_Problems#NoSuchMethodError_on_world_load
