### ISSUE TITLE
Chat message on death leads to the wiki

### ISSUE THREAD

**Issue by mDiyo** [micdoodle8/Galacticraft#1628]
I am currently using build 333 of MicdoodleCore, GalacticraftCore, and Galacticraft-Planets. Every death sends a message to the chat that points to the wiki and cannot be disabled. The message should not appear at any time.

**Comment by radfast** [comment]
That's strange, one of the recent updates should have prevented that chat being seen where it's not intended.  Is this on a server or single player?

**Comment by radfast** [comment]
Thanks, I think I fixed it now, this will be in 334 when it comes.
