### ISSUE TITLE
Aluminum Wire still connecting with 4 input

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#1629]
![2558-05-04_16 39 38](https://cloud.githubusercontent.com/assets/6128413/7490634/4d4bc6d2-f40c-11e4-8dac-708c0e05c5ca.png)

**Comment by radfast** [comment]
It's OK, that's intended (even though the connection is not drawn like that, some players may need to connect it that way if they have itemduct systems or something.

We should document that on the Wiki.   Please can we use your image?

**Comment by SteveKunG** [comment]
OK. Thanks.
