### ISSUE TITLE
Very minor model issue on Short Range Telepad

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#1635]
![2558-05-10_22 07 43](https://cloud.githubusercontent.com/assets/6128413/7561351/8177a038-f7f5-11e4-958c-e080d20f49b9.png)
![2558-05-10_22 08 01](https://cloud.githubusercontent.com/assets/6128413/7561352/81795c0c-f7f5-11e4-9c9c-c058430b2c24.png)

**Comment by radfast** [comment]
Please circle the issue in that screenshot, because right now I'm not seeing it ...

**Comment by Kodos-Atoz** [comment]
The very small gap between the center piece and the outer ring of the dark grey.
