### ISSUE TITLE
Oxygen Bubble Distributors dissapear 

### ISSUE THREAD

**Issue by DavidEdwin** [micdoodle8/Galacticraft#1636]
I am using Minecraft 1.7.2 with 
GalacticraftCore-1.7-3.0.11.334
Galacticraft-Planets-1.7-3.0.11.334
MicdoodleCore-1.7-3.0.11.334

And after Oxygen Bubble Distributors are placed they randomly disappear until there is only one or two them left. Oxygen Sealers work but my bases are too large to use oxygen sealers. other than this I see no other errors. This is causing me to wonder if this is an incompatibility with this new update and my other mods or if this is a common bug with this incremental build. Thank You for looking at my problem.

Here is a few Screenshots showing missing collectors on earth(Testing to see if it was a one time thing) and mars

http://1drv.ms/1PBWhQa

P.S. http://1drv.ms/1PBWhQa now contains a mods list and a crash log with an error with Oxygen Bubble Distributors (Even though it never stopped the game)

**Comment by DavidEdwin** [comment]
P.S. http://1drv.ms/1PBWhQa now contains a mods list

**Comment by radfast** [comment]
Thank you for reporting.  The crash will be fixed next build .335 available later today.   The cause seemed to be having multiple Oxygen Bubble Distributors nearby.

I hope fixing the crash will also fix the other issues with these blocks "disappearing", but will have to try and see.

**Comment by DavidEdwin** [comment]
Thank You
