### ISSUE TITLE
NEI weirdness with the Galacticraft tab, yet again

### ISSUE THREAD

**Issue by xJon** [micdoodle8/Galacticraft#1639]
I'm aware that you guys tried to fix it many times but today I tested Galacticraft v3.0.11.334 with Forge v10.13.3.1403 and the issue still happens.
![image](https://cloud.githubusercontent.com/assets/8945347/7610814/8a860d56-f988-11e4-8805-892ce21c0ebe.png)

**Comment by radfast** [comment]
I'm not seeing any weirdness in that screenshot.  Please explain what you mean, maybe post more screenshots...

**Comment by xJon** [comment]
@radfast Sorry for not been clear enough. Some of the items on NEI are darker, just like in https://github.com/micdoodle8/Galacticraft/issues/1532

**Comment by radfast** [comment]
It would have been better to post a comment on the old issue.  I am re-opening that.

**Comment by xJon** [comment]
@radfast No problem, will do next time.
