### ISSUE TITLE
Since Galacticraft 3.0.12.335 I cant use Modtweaker scripts for Tinkers Constuct any more.

### ISSUE THREAD

**Issue by Dream-Master** [micdoodle8/Galacticraft#1643]
What you changing between Version 3.0.11.334 and 3.0.12.335 related to Tinkers Construct  because now my Tinkers Construct Modtweaker Recipes dont work any more. (only when i reload the scripts the first load not have any error) I check the updated code a bit but i cant find anything. In my case the Basin and Casting recipes (remove) get out an error.

(minetweaker log)
https://gist.github.com/Dream-Master/50470b02f3667228a70a#file-gistfile1-txt

Maybe it is not a Galacticraft Bug and Modtweaker have to update but i hope you can say me what you change and I can post it on the Modtweaker 2 Git.

Thanks

**Comment by radfast** [comment]
It's not a Galacticraft bug.

The only possible change we made which can be related to this is that Galacticraft Tin, Copper and Aluminium Blocks are now included in the OreDictionary so are oredict-compatible with Tinker's Construct - I guess these blocks can probably be made in the Casting Basin now when they could not before.

Maybe that affects your scripts, or maybe there's a bug in MineTweaker, I really don't know but it's not a Galacticraft bug.

**Comment by Dream-Master** [comment]
Ok thanks for this Info.
