### ISSUE TITLE
CargoRocket Crash

### ISSUE THREAD

**Issue by yeyaowei** [micdoodle8/Galacticraft#1644]
Minecraft Version = 1.7.10
Forge Version = 10.13.3.1403 and 10.13.2.1291
Galacticraft Version = 3.0.11.333

When I open the GUI of CargoRocket, it will crash. And my language settings is zh-cn. But when I change to the en-uk. the crash won't happen.
I'm not good at English.
so... If I make some mistakes in my English, please pardon me :)

Full Forge Log = http://pastebin.com/LQmaJZB9

**Comment by radfast** [comment]
Thank you for reporting.  I will fix this now.

**Comment by radfast** [comment]
This will be fixed in new build 3.0.12.337 ready in ~30 minutes from now.  Both __server__ and __client__ will need to update to the new build.

**Comment by radfast** [comment]
If you participate in Chinese Minecraft forums, please can you help us - please notify Chinese players and servers they should update to 3.0.12.337.   For example:  http://www.mcbbs.net/thread-435616-1-1.html

**Comment by yeyaowei** [comment]
Okay, I will.
