### ISSUE TITLE
[Rendering Glitch] Oxygen Gear fails to render

### ISSUE THREAD

**Issue by Alaberti** [micdoodle8/Galacticraft#1656]
I couldn't find any reference in the console or in logs, however I do have some screencaps of the issue. From time-to-time the oxygen gear will either fail to render, leaving only a little brown box on the player's back. Most peculiar. If affects all players on our server when it happens; I can't find anything in specific that causes it to happen. I have been seeing the issue on and off since around 311 or so. Galacticraft 338, Forge 1403, Fastcraft 1.21, Optifine HD U B7.

![2015-05-18_16 21 36](https://cloud.githubusercontent.com/assets/10929796/7682741/6708d57a-fd7a-11e4-924e-874ac23c8aab.png)
![2015-05-18_16 21 14](https://cloud.githubusercontent.com/assets/10929796/7682742/6eb89152-fd7a-11e4-88a0-28f53c99ecb5.png)
![2015-04-18_21 23 39](https://cloud.githubusercontent.com/assets/10929796/7682803/f80b192a-fd7a-11e4-8efa-c3d06f41df3f.png)
![2015-05-16_16 47 01](https://cloud.githubusercontent.com/assets/10929796/7682847/3ad27f3c-fd7b-11e4-8b01-8298311e4bfd.png)

**Comment by radfast** [comment]
Does the issue still happen if you disable / uninstall Optifine?

**Comment by Alaberti** [comment]
Just removed backtools / ichunutils and that made the black block go. I'll check optifine next, I'm aware that historically it's usually the culprit.

**Comment by radfast** [comment]
Sounds like backtools / ichunutils is the cause, surely?   Especially if it is server wide?

**Comment by Alaberti** [comment]
Oddly the gear still isn't rendering without it. Curiously, the game won't launch without Optifine...weird.

**Comment by Alaberti** [comment]
Okay, so it looks like it is an Optifine issue - on standard (tested on B6), it'll render the gear about 50/50, while on ultra (tested on B7 HD U) it seems it won't render at all. Settings haven't seemed to affect it, still trying to crack this one but since everyone's breathing I'd say low-priority.

**Comment by radfast** [comment]
Optifine causes a lot of problems for Galacticraft's rendering, and each time we fix it they update Optifine.

Some players have found success by installing Player API, RenderPlayerAPI and SmartRender pulled from SmartMoving mod.  [More information](http://wiki.micdoodle8.com/wiki/Compatibility#Optifine)  Maybe one of your players can test this and see how it works out?  You do not need these installed on your server.

**Comment by Alaberti** [comment]
I will try this now, I haven't used those since the last time I tried to get Mo Bends to work wow lol. Update forthcoming.

**Comment by Alaberti** [comment]
Removing Optifine did fix this, I thought I had updated this and I uh....hadn't.

**Comment by radfast** [comment]
Hey Alaberti.  This issue is still being worked on, see #1809 and #1819.  We will get there eventually!

**Comment by radfast** [comment]
@Alaberti  Good news: the Optifine issue is fixed in latest GC version 421.

**Comment by Alaberti** [comment]
Awesome! Thanks for all the hard work and time you put into this mod!
