### ISSUE TITLE
Evolved Spider eyes rendering issue

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#1658]
Here : https://www.youtube.com/watch?v=hicahPUADDI

Please see this force crash report if this issue is problem in my graphic card.

---- Minecraft Crash Report ----
// There are four lights!

Time: 18/5/2558, 1:26 น.
Description: Manually triggered debug crash

java.lang.Throwable
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1851)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1040)
	at net.minecraft.client.Minecraft.run(Minecraft.java:962)
	at net.minecraft.client.main.Main.main(Main.java:164)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
	at GradleStart.main(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:415)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['Player882'/5, l='MpServer', x=-521.61, y=98.62, z=843.74]]
	Chunk stats: MultiplayerChunkCache: 217, 217
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-524,4,837), Chunk: (at 4,0,5 in -33,52; contains blocks -528,0,832 to -513,255,847), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
	Level time: 5642280 game time, 6000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 18 total; [EntityEvolvedCreeper['คริปเปอร์อวกาศ'/195, l='MpServer', x=-520.50, y=12.00, z=811.50], EntityEvolvedCreeper['คริปเปอร์อวกาศ'/196, l='MpServer', x=-524.50, y=12.00, z=810.50], EntityEvolvedCreeper['คริปเปอร์อวกาศ'/197, l='MpServer', x=-527.50, y=12.00, z=812.50], EntityEvolvedCreeper['คริปเปอร์อวกาศ'/7, l='MpServer', x=-517.75, y=97.00, z=839.56], EntityEvolvedSpider['แมงมุมอวกาศ'/8, l='MpServer', x=-522.57, y=97.00, z=833.34], EntityEvolvedCreeper['คริปเปอร์อวกาศ'/9, l='MpServer', x=-514.50, y=98.00, z=826.03], EntityEvolvedSpider['แมงมุมอวกาศ'/10, l='MpServer', x=-512.91, y=99.00, z=833.88], EntityEvolvedCreeper['คริปเปอร์อวกาศ'/11, l='MpServer', x=-525.06, y=96.00, z=844.75], EntityItem['item.tile.unlitTorchLit'/12, l='MpServer', x=-488.88, y=30.13, z=857.38], GCEntityClientPlayerMP['Player882'/5, l='MpServer', x=-521.61, y=98.62, z=843.74], EntityEvolvedZombie['ผีดิบอวกาศ'/15, l='MpServer', x=-578.44, y=15.00, z=803.47], EntityItem['item.tile.unlitTorchLit'/16, l='MpServer', x=-459.13, y=30.13, z=851.16], EntityEvolvedCreeper['คริปเปอร์อวกาศ'/17, l='MpServer', x=-563.50, y=86.00, z=785.50], EntityEvolvedCreeper['คริปเปอร์อวกาศ'/18, l='MpServer', x=-562.50, y=91.00, z=772.50], EntityEvolvedSkeleton['โครงกระดูกอวกาศ'/242, l='MpServer', x=-477.50, y=79.00, z=795.50], EntityEvolvedZombie['ผีดิบอวกาศ'/19, l='MpServer', x=-513.50, y=41.00, z=916.50], EntityEvolvedSkeleton['โครงกระดูกอวกาศ'/243, l='MpServer', x=-473.50, y=79.00, z=796.50], EntityEvolvedZombie['ผีดิบอวกาศ'/244, l='MpServer', x=-478.88, y=24.00, z=917.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:415)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2567)
	at net.minecraft.client.Minecraft.run(Minecraft.java:983)
	at net.minecraft.client.main.Main.main(Main.java:164)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
	at GradleStart.main(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 857766944 bytes (818 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 3 total; -Xincgc -Xmx1024M -Xms1024M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.140.1401 Minecraft Forge 10.13.3.1401 9 mods loaded, 9 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.140.1401} [Forge Mod Loader] (forgeSrc-1.7.10-10.13.3.1401-1710ls.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.3.1401} [Minecraft Forge] (forgeSrc-1.7.10-10.13.3.1401-1710ls.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.0.4.90} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.90-dev.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GalacticraftCore{3.0.12} [Galacticraft Core] (bin) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NBTEdit{1.7.10} [In-game NBTEdit] (bin) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GalacticraftMars{3.0.12} [Galacticraft Planets] (bin) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '3.3.0' Renderer: 'GeForce 9500 GT/PCIe/SSE2'
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce 9500 GT/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: ภาษาไทย (ประเทศไทย)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by radfast** [comment]
In my testing, it's caused by the Evolved Spider.  Take the Evolved Spider off the screen, and the rendering problem on the Evolved Creeper is fixed.
