### ISSUE TITLE
Automation problem

### ISSUE THREAD

**Issue by hehe3301** [micdoodle8/Galacticraft#1660]
when AE2 interfaces are trying to put plates into the compressor they are all going into the top row and not the top two rows as specified in the recipe.

**Comment by radfast** [comment]
Did you read [this](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md)?

Did you also read [the Wiki on this](http://wiki.micdoodle8.com/wiki/Electric_Compressor#Automation)?

If it's behaving as described on the Wiki, that is __intended behaviour__.
If not, then please start by specifying which version of both mods you are using, and maybe also test the same setup with a hopper.
