### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by denwd** [micdoodle8/Galacticraft#1662]
****************************
 Powered By MCP:
 http://mcp.ocean-labs.de/
 Searge, ProfMobius, Fesh0r,
 R4wk, ZeuX, IngisKahn, bspkrs
 MCP Data version : snapshot_20141130
****************************
:compileApiJava UP-TO-DATE
:processApiResources UP-TO-DATE
:apiClasses UP-TO-DATE
:sourceMainJava UP-TO-DATE
:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6
D:\galacticraft\forge-1.8-11.14.1.1410-src\build\sources\java\micdoodle8\mods\ga
lacticraft\planets\asteroids\client\render\item\ItemRendererTier3Rocket.java:46:
 error: ';' expected
        this.modelSpaceship.bake()
                                  ^
1 error
1 warning
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 8.896 secs

**Comment by radfast** [comment]
Right.

**Comment by denwd** [comment]
D:\galacticraft\forge-1.7.10-10.13.3.1408-1.7.10-src\build\sources\java\micdoodl
e8\mods\galacticraft\core\energy\EnergyUtil.java:11: error: package mekanism.api
.energy does not exist
import mekanism.api.energy.ICableOutputter;
                          ^
D:\galacticraft\forge-1.7.10-10.13.3.1408-1.7.10-src\build\sources\java\micdoodl
e8\mods\galacticraft\core\energy\EnergyUtil.java:12: error: package mekanism.api
.energy does not exist
import mekanism.api.energy.IStrictEnergyAcceptor;
                          ^
D:\galacticraft\forge-1.7.10-10.13.3.1408-1.7.10-src\build\sources\java\micdoodl
e8\mods\galacticraft\core\energy\grid\EnergyNetwork.java:3: error: package build
craft.api.mj does not exist
import buildcraft.api.mj.MjAPI;
                        ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
100 errors
1 warning
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 19.525 secs
