### ISSUE TITLE
Custom oregen config not working with the block name "ProjRed|Exploration"

### ISSUE THREAD

**Issue by denwd** [micdoodle8/Galacticraft#1670]
The config does not understand this regular season:

ProjRed|Exploration:projectred.exploration.ore

**Comment by radfast** [comment]
I don't understand your comment.  Maybe post a log?

**Comment by denwd** [comment]
# Enter IDs of other mods' ores here for Galacticraft to generate them on the Moon and other planets. Format is BlockName or BlockName:metadata. Use optio
nal parameters at end of each line: /RARE /UNCOMMON or /COMMON for rarity in a chunk; /DEEP /SHALLOW or /BOTH for height; /SINGLE /STANDARD or /LARGE for clum
p size; /XTRARANDOM for ores sometimes there sometimes not at all.  /ONLYMOON or /ONLYMARS if wanted on one planet only.  If nothing specified, defaults are /
COMMON, /BOTH and /STANDARD.  Repeat lines to generate a huge quantity of ores.
    S:"Other mods ores for GC to generate on the Moon and planets" <
  ProjRed|Exploration:projectred.exploration.ore:0 /SHALLOW /BOTH /COMMON /LAGRE /ONLYMARS


No work ((
only this regular season doesn't work

**Comment by radfast** [comment]
> /LAGRE 

This is not spelled correctly.  It's /LARGE.

**Comment by radfast** [comment]
Now understood.  I have updated the issue title.

Re-opening, until this is fixed.
