### ISSUE TITLE
Cannot call galacticraft class in Modtweaker.

### ISSUE THREAD

**Issue by numbernegative** [micdoodle8/Galacticraft#1672]
I'm trying to call the `micdoodle8.mods.galacticraft.api.recipe.CircuitFabricatorRecipes` class into Modtweaker to write a new recipe for the Circuit Fabricator but `import mods.micdoodle8.mods.galacticraft.api.recipe.CircuitFabricatorRecipes;` causes the script to throw error `> No such member: micdoodle8`

Have also tried `mods.galacticraft.api.recipe.CircuitFabricatorRecipes` to be met with `> No such member: galacticraft`

Am I just trying to call the class incorrectly or is there an issue with the way MT is communicating with GC?

I'm using GalacticraftCore-1.7-3.0.8.257

**Comment by Dream-Master** [comment]
I think Galacticraft is not supported at the moment.

**Comment by radfast** [comment]
This does not seem to be a Galacticraft issue.  Maybe ask Modtweaker to support Galacticraft.  Though to be frank we don't really want people changing the recipes unless there's an exceptional reason like a Gregtech tech tree, so it's not something I'd usually encourage.

You do know you can configure alternative items for Galacticraft to accept as "silicon" in the Circuit Fabricator, right?

**Comment by numbernegative** [comment]
Radfast, getting the fabricator to accept a different silicon is exactly what I'm trying to do. How is that configured? I've searched for a solution but I guess overlooked it.

**Comment by radfast** [comment]
>  I've searched for a solution

I think you need to improve your search technique!  A search of our wiki for "Silicon" gives this:

http://wiki.micdoodle8.com/wiki/Raw_Silicon

http://wiki.micdoodle8.com/wiki/Config#Silicon_compatibility_with_other_mods
