### ISSUE TITLE
Placing Arc Lamp on overhead becomes invisable when it's 5 blocks up.

### ISSUE THREAD

**Issue by TheQuadShot** [micdoodle8/Galacticraft#1686]
When I place the arc lamp on my overhead (ceiling) that is 5 blocks high it's visible for a brief second then it's invisible, it doesn't show in my inventory (like a block that isn't placed). and I have to right click the same spot to get it back.  I can place them on the overhead that is 3 blocks up and it works fine (although it is pointed at an angle). I hope that all makes sense.

**Comment by radfast** [comment]
1.  Are you playing single player or on a server?

2.  Which dimension?

3.  Do you get the same effect trying to place any other block on your ceiling that is 5 blocks high, standing in the same spot?

It sounds like maybe the server and client have you (your player feet) in fractionally different places - so your client thinks you are close enough to the ceiling to place a block, the server thinks you are further away so not close enough to place the block.  I never heard of that before, but I guess it can happen.  In that case, it's not connected with the arc lamp _per se_.  But I'm not ruling that out for now, just asking the questions.

**Comment by TheQuadShot** [comment]
I figured it out after lots of testing. I think it has something to do with morph. It only happens after I have morphed from a 1 block tall critter (bat). Then it happens to any block I try to place. Sorry

**Comment by radfast** [comment]
No problem at all, I'm glad you have figured it out.  If reporting to iChun, it's definitely worth mentioning that the block item in your inventory "disappears, and reappears when you next use the inventory slot" - that means something different is happening on the client and on the server.
