### ISSUE TITLE
Items lost when leaving Nasa workbench

### ISSUE THREAD

**Issue by TheQuadShot** [micdoodle8/Galacticraft#1687]
I was making the moon buggy with 54 storage, I put everything into the bench, but I was one heavy duty plate short, so I escaped out of the workbench, and of course all of the items "dropped" to the floor. I got all of the items except for 2 of the storage units(I have the Botania magnetic ring, so I picked everything up). I then went back into the work bench and clicked on the storage boxes (to see if they were there but just not visible) I noticed that there were "glowing sparkles" showing in the background however not storage compartments. I tried destroying the bench and re-placing it, and still no storage compartments. I also tried to close and re-launch incase of client/server de-sync. I also checked all surrounding block inventories to ensure that something else didn't grab them.

**Comment by radfast** [comment]
The NASA workbench works like a regular Crafting Table in vanilla Minecraft - if you escape out of it, all the items in it will drop, nothing can be stored in it.

Could be a bug in the Botania magnetic ring, I'm really not too sure.

Anyhow I'll take a look, but it doesn't sound like this is going to be a repeatable bug.  You have our permission to spawn in for yourself 2 storage units, if it helps :)

**Comment by TheQuadShot** [comment]
I just finished creating another instance with only GC, NEI, and Waila installed and it did repro, I then created another 2 storage box's and backed out of the workbench again, this time I lost 2 of the storage boxes and all of the wheels, I'm afraid to try it again, I might go poof too :)

**Comment by radfast** [comment]
ok thanks that's helpful, we'll check it out.  Could be a day or two before I get back to you.

**Comment by radfast** [comment]
Thanks for reporting, and testing the repro.  Seems like this bug has probably been in Galacticraft for 2 years - it only affected the 2nd and 3rd storage boxes in the Moon Buggy workbench.

Fixed in 3.0.12.341.
