### ISSUE TITLE
Nasa Workbench doesn't show components

### ISSUE THREAD

**Issue by TheQuadShot** [micdoodle8/Galacticraft#1688]
This is in my "test instance" that only has GC, NEI and Waila installed.
![2015-06-02_06 12 04](https://cloud.githubusercontent.com/assets/11265900/7936515/85b9ed54-08ee-11e5-8c0f-6744e2436c28.png)
![2015-06-02_06 12 08](https://cloud.githubusercontent.com/assets/11265900/7936521/8c46dbe6-08ee-11e5-998e-47f6e381aa7b.png)

**Comment by radfast** [comment]
http://forum.micdoodle8.com/index.php?threads/is-this-a-bug-or-is-it-something-im-doing-wrong.5470/

Let me get this straight: the issue you are reporting is that the __ingredients__ are not shown in the NASA workbench?  For example, the Tier 1 rocket ingredients are not shown?

I'm 99% sure that Galacticraft has never shown the ingredients on the NASA workbench crafting screens.  You are supposed to use NEI, or if you do not have NEI, use the Wiki to find the recipe.

Closing.  If someone wants to show me Galacticraft showing the ingredients in some earlier version (note: not in NEI!!!) then please post a screenshot and we can maybe re-open this.  But like I say, it's not something I remember seeing.
