### ISSUE TITLE
Galacticraft does not check for BCCompat's TileGenericPipe override

### ISSUE THREAD

**Issue by asiekierka** [micdoodle8/Galacticraft#1692]
https://github.com/BuildCraft/BuildCraft/issues/2744

**Comment by asiekierka** [comment]
A future-proof solution would be to find the matching BlockGenericPipe and then call its createNewTileEntity.

**Comment by radfast** [comment]
Thanks, much appreciated - we'll take a look.

**Comment by radfast** [comment]
Fixed, thank you.  I apologise for the long delay in fixing this, I was away from the mod from July through December for personal reasons.
