### ISSUE TITLE
Tier 3 rocket is uncraftable in .12.340

### ISSUE THREAD

**Issue by iTpyn** [micdoodle8/Galacticraft#1694]
After placing all the resources for Tier 3 rocket in NASA workbench, rocket doesnt appear in the output slot. Had no problem crafting the other rockets.

Rolling back to 3.0.11.333 fixed the issue.

**Comment by radfast** [comment]
Thanks for notifying, we'll test and fix this asap.

**Comment by radfast** [comment]
Bug fixed in version 3.0.12.341, thanks for the report.

Actually in 3.0.12.340 you can craft a Tier 3 Rocket OK __if you add wooden chests__ - it's only the 0 storage rocket which has the crafting bug.
