### ISSUE TITLE
Galacticraft oregeneration config

### ISSUE THREAD

**Issue by JasonMcRay** [micdoodle8/Galacticraft#1696]
All I can see in the config is disabling oregen for Overworld and Moon. Is the oregenration config for Mars and Asteroids missing due to bug, has it been forgotten, or am I blind.

Mainly I am talking about: GC Iron Ore, Aluminum Ore, and probably others on Mars and Asteroid dimensions.

I would really like to disable some oregen, because in my modpack I have other ways (harder) on obtaining for example Aluminum ore.

Thanks

**Comment by radfast** [comment]
There is no bug, simply nobody previously has required to disable ores on Mars or Asteroids.

You have ways to generate Aluminum ore which are harder than making a Tier 3 Rocket?!  I can't really imagine what those ways are.

**Comment by Dream-Master** [comment]
I would really appreciate it to have a config file to make the ores on Mars and Asteroids configurable like the config for moon. I using Galactic Greg (GT origen on all Planets/moons) and for better mod pack tiering it would be very helpful to enable or disable ores individual.

**Comment by JasonMcRay** [comment]
Disregard the harder ways on getting Aluminum. :)

But as @Dream-Master said it would be nice to have a config to enable/disable certain ores for Asteroids and Mars because of GalacticGreg mod, which adds GT ores to GC dimensions. Also I am trying to get rid of most ores from other mods if they have equivalent one in GT.

**Comment by Dream-Master** [comment]
So any updates. We gat a config option ?

**Comment by Dream-Master** [comment]
@micdoodle8 
It is possible to get a config option to disabled all mars ores like on the Moon.

**Comment by Dream-Master** [comment]
Nice thanks.
