### ISSUE TITLE
Player falling when arrives at Moon/Mars/Asteroids/Space Stations - Server not sending world chunk info

### ISSUE THREAD

**Issue by Ahyl** [micdoodle8/Galacticraft#1697]
First, sorry for my bad English
When I (or one of my friends) try to go on The moon, mars, asteroids or any spaces station in my server,  I just fall, and the dimension not appear.
Forge 1.7.10 10.3.1408, version 3.0.12.339
Mods list:
![image](https://cloud.githubusercontent.com/assets/12777915/8020943/e189457a-0c8c-11e5-9928-f35001d1b7e4.png)

It works on singleplayer!

**Comment by radfast** [comment]
Are you using a Cauldron server?  This is most likely connected with your ```bukkit.fml``` or other Bukkit settings, or a Bukkit plugin.

Please post ```fml-server-latest.log```

Some things you can try temporarily:

(1)   __backup your world__ and then test your server after removing DragonMounts, LittleBlocks, MCA, MrCrayfish, RadixCore and SlimevoidLibrary.

(2)  run a vanilla Minecraft + Forge server, not using Cauldron

**Comment by Ahyl** [comment]
I'm using a normal forge server. I will try to find if there are a conflict with one of the mods currently installed. I updated to latest version too, and nothing change.

**Comment by Ahyl** [comment]
fml-server-latest.org :

http://www.filedropper.com/fml-server-latest

**Comment by Ahyl** [comment]
Removing DragonMounts, LittleBlocks, MCA, MrCrayfish, RadixCore and SlimevoidLibrary.

**Comment by ArgonBird18** [comment]
I am having the same problem. But when I use a map I can see the mars terrain on the map. It looks like a problem sending the chunks to the client. Another note, I used F3 and I was falling slower than normal.
Forge Client and Server Version:  10.13.4.1448-1.7.10

**Comment by radfast** [comment]
@ArgonBird18  I really need to see logs.  Please post a log, or a log extract covering the time period around 1 minute each side of when a player goes to Mars.

I also need a list of all other mods installed, or a link to the modpack being used.

**Comment by radfast** [comment]
@Ahyl did you ever succeed in getting this working?  I am sorry for the long delay, I have been absent from Galacticraft for some months due to real-world issues. :(

**Comment by Ahyl** [comment]
Haven't try again, but I will as soon as possible

2016-01-08 14:53 GMT+01:00 Galacticraft developer <notifications@github.com>
:

**Comment by Ahyl** [comment]
Tryed with recommended 1.7.10 forge version (1.7.10 - 10.13.4.1558) and latests Galacticraft mods (1.7-3.0.12.410 is crashing, so 1.7-3.0.12.375), and connect with localhost (and not my ip)

It seems working now, but maybe it was because I login in with localhost and not my ip?

**Comment by radfast** [comment]
@Ahyl  that's great news, thanks for coming back.  Presumably using your IP caused delays or packet loss in server/client data?  I am looking at ways to improve initial planet loading on laggy server/client connections, Galacticraft already has a lot of built in robustness for overcoming lag or packet loss but more can always be good.

But umm ... why is 410 crashing?  It shouldn't be.  Please can I see the crash report?

**Comment by Ahyl** [comment]
[crash-2016-01-09_00.35.53-server.txt](https://github.com/micdoodle8/Galacticraft/files/83646/crash-2016-01-09_00.35.53-server.txt)

**Comment by radfast** [comment]
Thank you so much, that is an important crash report - it's a problem in recent Forge versions (more recent that the one on my test platform).

This will be fixed in GC version 411.
