### ISSUE TITLE
Incorrect texture

### ISSUE THREAD

**Issue by Hubba-boy** [micdoodle8/Galacticraft#1700]
i have a problem, whenever i play galaticcraft on forge 10.3.2.291 the texture don't load correctly.

**Comment by radfast** [comment]
That's not enough information to explain the issue.

Do you mean Forge 10.3.2.1291?
Which exact Galacticraft version?
Which other mods do you have?  (Especially things like Optifine and Shaders mod)
Do you see the issue if only Galacticraft is installed, no other mods?
Please post full ```fml-client-latest.log```
Please post a screenshot.

**Comment by dj3520** [comment]
Also disable any texture packs. Please specify what is missing a texture
and confirm it's not a client issue by pressing F3 + B to force reload
textures.

**Comment by Hubba-boy** [comment]
Yes it's Forge 10.3.2.1291
Galacticraft version 3.0.11.333
I have many mods so it's hard to list them but i do have Optifine but no Shaders mod
No I don't see the issue if only Galacticraft is installed

![2015-06-07_23 03 16](https://cloud.githubusercontent.com/assets/12790684/8037795/83b58bc2-0dc5-11e5-81e6-10b972a2da28.png)
![2015-06-07_23 03 56](https://cloud.githubusercontent.com/assets/12790684/8037796/83bcbdb6-0dc5-11e5-8f51-351d0f010a8a.png)

**Comment by dj3520** [comment]
Use pastebin or gist to post your mods list. 
Update [Optifine](http://optifine.net/downloads) to B7, [Forge](http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.7.10.html) to 1307, and [Galacticraft](http://ci.micdoodle8.com/job/Galacticraft-1.7/) to it's latest version.
I'd also recommend more than 512MB of heap size if you have a lot of mods installed. Preferably 1GB or more depending on how many mods and how demanding they are.
Does this only happen with Galacticraft items? It looks like some planks and grass blocks are missing sides.

>No I don't see the issue if only Galacticraft is installed

Start with only Galacticraft installed and one by one enable your mods. Once this reappears try with only GC and the last mod you installed.

**Comment by radfast** [comment]
It's Optifine.  You are using Optifine 1.7.10_HD_A4 which has known issues with the newer Forge versions, was fixed in Optifine B1 and later.

**Comment by Hubba-boy** [comment]
oh thank you
