### ISSUE TITLE
Idea: Gravity Field/sealer & Configs for how good the Oxygen Sealer is and how big a room 1 sealer can do

### ISSUE THREAD

**Issue by mariodk** [micdoodle8/Galacticraft#1709]
like the Oxygen bubble/Sealer

can we get something like this but for gravity so inside this area will be Overworld gravity:
Will cost power(without change the configs: will be alot of power so needing atleast 1 standard sized big reactor just made for a gravity field for a pretty  mid/big sized space station (around 3x3 chunks+afew layers)

and for make it abit compact we can have it so Oxygen+Gravity Bubble & Sealer can be inside 1 machine

also Config for Oxygen Sealer for how many Air Blocks it can Cover
since in a modpack im making i will really like to buff it

**Comment by EzerArch** [comment]
Please, use the forum to post ideas and suggestions:
* [Galacticraft forum](http://forum.micdoodle8.com/index.php)
* Recommended: [The most reposted ideas](http://forum.micdoodle8.com/index.php?threads/the-most-reposted-ideas-read-this-before-posting-an-idea.3677/)
