### ISSUE TITLE
java.lang.NoClassDefFoundError: buildcraft/api/recipes/BuildcraftRecipes

### ISSUE THREAD

**Issue by Tsyklop** [micdoodle8/Galacticraft#1711]
http://pastebin.com/XkZ6iKgQ 
Buildcraft 7.0.9
GC 342

**Comment by radfast** [comment]
Sorry 'bout that.  Please try Galacticraft version [343](http://ci.micdoodle8.com/job/Galacticraft-1.7/343/).
