### ISSUE TITLE
Memory use on client increases when Buildcraft Quarry hits a crude oil reservour

### ISSUE THREAD

**Issue by kremsy** [micdoodle8/Galacticraft#1712]
https://github.com/BuildCraft/BuildCraft/issues/2780

As soon the Quarry hits a oil reservour the oil is distributed around and it causes massive laggs (guess the rendering of the oil).

**Comment by radfast** [comment]
Server lag or client lag?
Evidence?
Which exact versions of each mod?

**Comment by radfast** [comment]
Also what usually happens when a Buildcraft quarry hits water or lava?

**Comment by kremsy** [comment]
Found out that it only happens on crude oil bec it get distributed over the whole quarry hole and lots of oil get rendered and this rendering seems to causing the laggs. Basically clientlaggs for everyone, ram cpu of server is fine but if you come closer to the hole it starts lagging way more. 

Versions I can provide a screenshot later.

**Comment by radfast** [comment]
So you're playing on a server.  Please list server plugins especially GriefPrevention, WorldGuard, Factions type stuff.

Please provide two or three screenshots from the client with F3 debug information shown on each one.  Does the lag stop if the quarry stops working - I mean take the power away from the quarry, what happens?

It would also help if you can explain better what you mean by "lagging" - do you mean:
* block lag (so delays if you mine blocks before they drop as items, or delays if you place blocks)
* low tps on the server (so machines with progress bars or animations - like a furnace or anything else which takes time - run "slow" and the progress bar keeps jumping backwards on the client)
* low tps on the client (so your whole Minecraft runs slow, it takes seconds before anything happens, when the player moves you move in massive jumps from place to place and can't really control it)
* network lag (slow or patchy chunk loading when you move around the map so 16x16 'holes' at the edges of the map and you can fall down into them)
* low fps (so the machines in the game all run OK and the map is OK, but your frame rate is lower than normal so movement is not smooth)

If it's low fps, does it revert to normal when you no longer have any of the oil blocks in your frustum?

Are you running Optifine, Shaders or any other visual mod on the client?

Full logs from both server and client to cover the time period when this is happening will be helpful.

**Comment by kremsy** [comment]
We dont use any plugins, only simple mods(about 10) woll provide you a list as soon as I am at home.

Taking power away or stopping quarry doesnt change a lot, I think its just the oil itself causing the laggs when it gets distributed around, will send a sceenshot soon. Cant really test a lot anymore as we removed the oil from out environemnt, since then we dont have problems anymore.

About the kind of laggs I will provide some information, all I can say atm is that the ram of the client went up dramatically and if you fly into the quarry come closer to the oil it felt like 2-3 fps. Really hard lagg, impossible to move.

More information soon.

**Comment by kremsy** [comment]
Installed Mods (+Bc Compat):
![mods](https://cloud.githubusercontent.com/assets/2006941/8159456/2c1f987e-1367-11e5-92f2-2e9c80a7b785.png)

The only picture of the problem I still have is this one:

![d357c08c-10ef-11e5-88cd-d59057ffd6e8](https://cloud.githubusercontent.com/assets/2006941/8159500/939a5c0a-1367-11e5-82fd-e5a5273aa8fa.png)

You cant see the whole quarry but you can see how the oil is distributed around down there, this causes the extreme laggs.

Of you laglist I would count it as a mixture between low tps and low fps. It also used 100% of my 500mb client ram when the lagg happened, I increased it to 1GB, it went up sometimes to 700-800mb when I came close the quarry but still lagged (not as much as before).

Flying in creative mode into the quarry to the badrock was almost impossible due the laggs.

**Comment by radfast** [comment]
This is important:
> It also used 100% of my 500mb client ram when the lagg happened

**Comment by kremsy** [comment]
I got the next oil field again (so obviously world edit didnt remove all):

![lagfps1](https://cloud.githubusercontent.com/assets/2006941/8236868/8fac09a0-15eb-11e5-8b53-cb3e910cb96f.png)
![lagfps2](https://cloud.githubusercontent.com/assets/2006941/8236867/8faacb8a-15eb-11e5-8d5a-96ab6b9ef6f8.png)

After removing the oil in there with worldedit its running smooth again.

**Comment by SteveKunG** [comment]
Can confirm this issue still exist in 1.7.

1.7 : https://github.com/micdoodle8/Galacticraft/blob/MC1.7/src/main/java/micdoodle8/mods/galacticraft/core/blocks/MaterialOleaginous.java

1.8 : https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/blocks/MaterialOleaginous.java

**Comment by radfast** [comment]
Thanks @SteveKunG 

I think you're right, that 1.8 performance improvement will probably also fix this.  Fixed in next 1.7 build, that's build 500.
