### ISSUE TITLE
problem with galacticraft-planets-mod-1.7-3.0.11.333

### ISSUE THREAD

**Issue by Vladutky** [micdoodle8/Galacticraft#1717]
please solve this problem!
when i start minecraft forge it says:
"Mod file _Galacticraft-Planets-Mod-1.7.10.jar is an incomplete download and will likely cause errors, please re-download it!"
i re-download the mod and this message appears again and again and again... 
can you solve this problem please?

**Comment by radfast** [comment]
Some things for you to try:
* Delete all three Galacticraft files from your ```/mods``` folder.
* Make sure you don't have any other old Galacticraft .jar files hanging around in your ```\mods``` folder or in the ```1.7.2``` or ```1.7.10``` subfolders - if you do, delete them all.
* Go to your browser's downloaded files folder and make sure no old Galacticraft versions are hiding there
* Re-download all three files from the [official site](http://micdoodle8.com/mods/galacticraft/downloads)
* You should be using the latest version 3.0.12.344, not 3.0.11.333.  I keep on telling people this, it is well covered [on](http://wiki.micdoodle8.com/wiki/Whats_New#Latest_versions) [the](http://wiki.micdoodle8.com/wiki/Tutorials/Galacticraft_Installation_Guide) [wiki](http://wiki.micdoodle8.com/wiki/Compatibility).
* If you are using MultiMC or something like that, don't.  Just use the regular Minecraft launcher, with Forge of course.
