### ISSUE TITLE
Galacticcraft sealers not sealing properly?

### ISSUE THREAD

**Issue by Valleriani** [micdoodle8/Galacticraft#1723]
Here is an easy video on what is going on.:

https://www.youtube.com/watch?v=4eAeM5jkJ8s   .   Using 1.7-3.0.12.339

When I am in the chunk with the sealers, it works fine. When I am in a chunk over, I take random damage 'sometimes'. The rooms are sealed.

The damage occurs when the sealers are 'checking'. I don't show it in the video but with tests with a buddy when it said the sealers were checking, he sometimes took damage. The sealers have plenty of oxygen and energy. 

I'm not really sure what I can do to solve it. I took the map and tested it in single player, and it's fine there.

**Comment by radfast** [comment]
On the server, you can switch on debug logging: in ```core.conf``` set this setting:
>    B:"Enable Debug Messages"=true

This will put some information in the server log (you might also see it on the server console) which may give some more insight into what is going on, if you can post up log segments for us - you will see which ones, it will be information about sealer checks.

**Comment by Valleriani** [comment]
After a second reboot the issue stopped coming up. I don't know what exactly it was, but I am going to close this for now since the issue seems to be resolved.
