### ISSUE TITLE
Galacticraft in-game config stretching off-screen

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#1725]
Just discovered (thanks to @SteveKunG) the in-game config. I tried it and liked it, but something seems a bit wrong:

![2015-06-19_22 33 52](https://cloud.githubusercontent.com/assets/6743303/8265548/aece4ab2-16d3-11e5-8ed8-a6e7151849ff.png)
![2015-06-19_22 34 07](https://cloud.githubusercontent.com/assets/6743303/8265549/aef60cb4-16d3-11e5-8516-b234e5dffc5f.png)

Those screenshots were taken full-screen, no MCPatcher, on US English.

Tested with Japanese too (not that I know Japanese, I wanted to see how it would look like with "shorter" translation strings):
![2015-06-19_22 34 45](https://cloud.githubusercontent.com/assets/6743303/8265550/aefa5396-16d3-11e5-89d8-026cac2b2436.png)

**Comment by radfast** [comment]
hmm, looks like we need shorter strings - there's probably just one or two long ones.

**Comment by radfast** [comment]
When next build is ready please see if that fixes it - I have added some more strings as well thanks to @SteveKunG.
