### ISSUE TITLE
soloar icons not showing properly

### ISSUE THREAD

**Issue by Hubba-boy** [micdoodle8/Galacticraft#1726]
the icons in the solar system does not show correctly.

 
![2015-06-20_07 42 44](https://cloud.githubusercontent.com/assets/12790684/8267308/c7d200b0-1720-11e5-827c-3a635094721b.png)
![2015-06-20_07 41 59](https://cloud.githubusercontent.com/assets/12790684/8267309/c8cf34f6-1720-11e5-97da-4c803c83a401.png)
![2015-06-20_07 42 14](https://cloud.githubusercontent.com/assets/12790684/8267310/c8e6e128-1720-11e5-84a3-ea49ab3f597c.png)
![2015-06-20_07 42 36](https://cloud.githubusercontent.com/assets/12790684/8267311/c96be1c0-1720-11e5-8e04-33d55cc421b9.png)

**Comment by radfast** [comment]
Seems like you are using an Add-On - I'm not sure which one.

Does the icons work if you don't have the Add-On?

**Comment by EzerArch** [comment]
>  I'm not sure which one.

It looks like EnviroMine: https://github.com/Funwayguy/EnviroMine/wiki

**Comment by radfast** [comment]
I'm closing this.  I'm 99% sure the issue is caused by whichever Galacticraft Add-On is adding "Ceres", "Pluto", "Eris" and the "Kuiper Belt".

Anyhow, there has been no response from the OP in 6 months ...
