### ISSUE TITLE
Conflict with Tinkersconstruct steelworks

### ISSUE THREAD

**Issue by wmgarden76** [micdoodle8/Galacticraft#1727]
I have tried loading tinkers construct steelworks with galacticraft and mincraft crashes. Is there something i can do to make them work together?

**Comment by dj3520** [comment]
You could start with posting a crash log to gist or pastebin so we can start to see why you are crashing.

**Comment by TheQuadShot** [comment]
I'm not exactly sure if this helps, I added Tinkers Steelworks and it does crash to launcher, but the problem is in the Steelworks code. If your interested here's the crash log:
http://pastebin.com/k5EzHhmb

**Comment by radfast** [comment]
Thanks @TheQuadShot 

This problem does not seem to have any connection with Galacticraft.  Presumably, Tinkers Steelworks will crash in the exact same way without Galacticraft installed?  (Even if not, the problem looks to be in their code.)

**Comment by TheQuadShot** [comment]
No Problem! glad to help, btw I filed this bug with the Steelworks team.

**Comment by radfast** [comment]
Thank you, let's hope that leads to a fix.  If the Steelworks guys come back and say Galacticraft is causing this somehow then I will take another look - but I think that is extremely unlikely.

**Comment by wmgarden76** [comment]
Thank you for looking into that for me. i enjoy playing galacticraft.
