### ISSUE TITLE
Crude Oil spawning flying blocks

### ISSUE THREAD

**Issue by SirWilli** [micdoodle8/Galacticraft#1729]
GalacticraftCore-1.7-3.0.11.333

If you get near the galacticraft generated crude oil it will spawn flying crude oil blocks and dropped items. This creates massive performance issues on client and server.

Screenshots:
http://imgur.com/a/6wU0D
http://imgur.com/a/U0lUQ

**Comment by radfast** [comment]
This may explain this: #1712.  Investigating.

**Comment by radfast** [comment]
I can't reproduce this in testing.

Can you give more details, like:
* what else is nearby (e.g. lava?)
* other mods installed
* server or SSP?

**Comment by SirWilli** [comment]
- Thanks to a not loading chunk I could find the source block of the oil. http://i.imgur.com/qvTPbSv.png
- Mods list: http://www.feed-the-beast.com/modpacks/FTBHorizonsII
- It's on a server, exporting the world to singleplayer allows to reproduce the issue too

**Comment by SirWilli** [comment]
Ok, I found the source now... http://i.imgur.com/cTGXuKV.png
But it seems to only happen with the crude oil as nothing happens if I place water or lava near it.

**Comment by radfast** [comment]
I don't see this as a Galacticraft issue.  It's the Gravitational Anomaly from Matter Overdrive.  Maybe ask the author of that mod not to do this with Forge Fluid blocks.
