### ISSUE TITLE
Crude Oil blocks are rendering their overlapping sides 

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#1737]
The game is no longer culling the overlapping side faces.

This is me standing in an oil pocket, looking down, right at where two block columns meet face-to-face:

![2015-06-21_16 42 27](https://cloud.githubusercontent.com/assets/6743303/8273084/826adb22-1834-11e5-9dee-3782788f27e4.png)

**Comment by radfast** [comment]
I think this should be fixed already in next build, see: https://github.com/micdoodle8/Galacticraft/commit/134415f74771e6ea3142a1da746b82c900781d65

Any problem in the next build 345, please say and this can be re-opened.

(In fact aesthetically it's not yet quite how I want it - rendering the oil correctly is proving to be a complex problem.)
