### ISSUE TITLE
Render Rings on Galactic Map.

### ISSUE THREAD

**Issue by BlesseNtumble** [micdoodle8/Galacticraft#1738]
![1](http://6.firepic.org/6/images/2015-06/22/zo8druj8i95q.png)
![2](http://6.firepic.org/6/images/2015-06/22/j2gw6enqutfc.png)

Can not specify a planet from another system.
Rather, the specify is possible, but the circles are drawn in our system.

**Comment by micdoodle8** [comment]
So only some of the rings are working properly? I see two rings there in the new system, is it consistently those two working and the other one not?

**Comment by BlesseNtumble** [comment]
I took your code to render the rings, and tried to ring the other planets of the solar system. But they have created in our solar system in the coordinates of the sun, which is the planet in another system.

**Comment by BlesseNtumble** [comment]
In this case, the ring appeared on Jupiter's orbit, and had to "X" a different planet system.

**Comment by micdoodle8** [comment]
Is it possible to get a copy of the source code? It's pretty hard for me to reproduce this problem. I can provide my email if you would prefer.

**Comment by BlesseNtumble** [comment]
public class GSEventHandlerClient
{
	// TODO RED
    @SideOnly(Side.CLIENT)
    @SubscribeEvent
    public void onRingRender(CelestialBodyRenderEvent.CelestialRingRenderEvent.Pre renderEvent)
    {
        if ((renderEvent.celestialBody.equals(BlesseAddon.planetKuiperBelt)))
        {
        	if (FMLClientHandler.instance().getClient().currentScreen instanceof GuiCelestialSelection)
        		GL11.glColor4f(0.7F, 0.0F, 0.0F, 0.5F);
        	else
        		GL11.glColor4f(0.3F, 0.1F, 0.1F, 1.0F);
            renderEvent.setCanceled(true);
            GL11.glBegin(GL11.GL_LINE_LOOP);

            final float theta = (float) (2 * Math.PI / 90);
            final float cos = (float) Math.cos(theta);
            final float sin = (float) Math.sin(theta);

            float min = 72.0F;
            float max = 78.0F;

            float x = max * renderEvent.celestialBody.getRelativeDistanceFromCenter().unScaledDistance;
            float y = 0;

            float temp;
            for (int i = 0; i < 90; i++)
            {
                GL11.glVertex2f(x, y);

                temp = x;
                x = cos * x - sin * y;
                y = sin * temp + cos * y;
            }

            GL11.glEnd();
            GL11.glBegin(GL11.GL_LINE_LOOP);

            x = min * renderEvent.celestialBody.getRelativeDistanceFromCenter().unScaledDistance;
            y = 0;

            for (int i = 0; i < 90; i++)
            {
                GL11.glVertex2f(x, y);

                temp = x;
                x = cos * x - sin * y;
                y = sin * temp + cos * y;
            }

            GL11.glEnd();
            GL11.glColor4f(0.7F, 0.0F, 0.0F, 0.1F);
            GL11.glBegin(GL11.GL_QUADS);

            x = min * renderEvent.celestialBody.getRelativeDistanceFromCenter().unScaledDistance;
            y = 0;
            float x2 = max * renderEvent.celestialBody.getRelativeDistanceFromCenter().unScaledDistance;
            float y2 = 0;

            for (int i = 0; i < 90; i++)
            {
                GL11.glVertex2f(x2, y2);
                GL11.glVertex2f(x, y);

                temp = x;
                x = cos * x - sin * y;
                y = sin * temp + cos * y;
                temp = x2;
                x2 = cos * x2 - sin * y2;
                y2 = sin * temp + cos * y2;

                GL11.glVertex2f(x, y);
                GL11.glVertex2f(x2, y2);
            }

            GL11.glEnd();
        }
		
		//TODO GREEN RING
		if (renderEvent.celestialBody.equals(GalacticraftCore.planetOverworld))
         {
         	if (FMLClientHandler.instance().getClient().currentScreen instanceof GuiCelestialSelection)
         		GL11.glColor4f(0.0F, 0.7F, 0.0F, 0.5F);
         	else
         		GL11.glColor4f(0.3F, 0.1F, 0.1F, 1.0F);
             renderEvent.setCanceled(true);
             GL11.glBegin(GL11.GL_LINE_LOOP);

             final float theta = (float) (2 * Math.PI / 90);
             final float cos = (float) Math.cos(theta);
             final float sin = (float) Math.sin(theta);

             float min = 72.0F;
             float max = 78.0F;

             float x = max * renderEvent.celestialBody.getRelativeDistanceFromCenter().unScaledDistance;
             float y = 0;

             float temp;
             for (int i = 0; i < 90; i++)
             {
                 GL11.glVertex2f(x, y);

                 temp = x;
                 x = cos * x - sin * y;
                 y = sin * temp + cos * y;
             }

             GL11.glEnd();
             GL11.glBegin(GL11.GL_LINE_LOOP);

             x = min * renderEvent.celestialBody.getRelativeDistanceFromCenter().unScaledDistance;
             y = 0;

             for (int i = 0; i < 90; i++)
             {
                 GL11.glVertex2f(x, y);

                 temp = x;
                 x = cos * x - sin * y;
                 y = sin * temp + cos * y;
             }

             GL11.glEnd();
             GL11.glColor4f(0.0F, 0.7F, 0.0F, 0.1F);
             GL11.glBegin(GL11.GL_QUADS);

             x = min * renderEvent.celestialBody.getRelativeDistanceFromCenter().unScaledDistance;
             y = 0;
             float x2 = max * renderEvent.celestialBody.getRelativeDistanceFromCenter().unScaledDistance;
             float y2 = 0;

             for (int i = 0; i < 90; i++)
             {
                 GL11.glVertex2f(x2, y2);
                 GL11.glVertex2f(x, y);

                 temp = x;
                 x = cos * x - sin * y;
                 y = sin * temp + cos * y;
                 temp = x2;
                 x2 = cos * x2 - sin * y2;
                 y2 = sin * temp + cos * y2;

                 GL11.glVertex2f(x, y);
                 GL11.glVertex2f(x2, y2);
             }

             GL11.glEnd();
         }
      
    }

**Comment by micdoodle8** [comment]
Also the planet/star registration code please. Note: Please use pastebin.com or gist, it's quite hard to read here.

**Comment by BlesseNtumble** [comment]
http://pastebin.com/9TdPZF71

**Comment by micdoodle8** [comment]
Okay, so in the latest API version you can access the Vector3f value for the parent offset, inside the CelestialRingRenderEvent.Pre event.

All you have to do in your event handler is add an opengl push/pop and translate by renderEvent.parentOffset

Example:
https://gist.github.com/micdoodle8/00eed72237ec5a131df2
