### ISSUE TITLE
[enhancement] It would be nice to be able to rotate Display Screen

### ISSUE THREAD

**Issue by TheQuadShot** [micdoodle8/Galacticraft#1740]
I have a "launch center", with display units in the overhead (ceiling) and they are "upside down" for the direction I have it built. 
![2015-06-21_20 24 54](https://cloud.githubusercontent.com/assets/11265900/8275128/55530aa4-1854-11e5-86fc-97a863fb7393.png)

**Comment by radfast** [comment]
Suggestions on the forum please.  Having said that, this is an issue I am aware of - it will probably get fixed some time.

**Comment by TheQuadShot** [comment]
Sorry, I couldn't decide of it was a bug or an enhancement, so I went with lowest denominator ;-)
