### ISSUE TITLE
Meteors Destroying Moon Surface - Feature Request?

### ISSUE THREAD

**Issue by mrgrey1** [micdoodle8/Galacticraft#1750]
Love the mod but after sometime playing on the Moon the surface is getting heavily damaged and covered in meteors. They're everywhere. I initially tried to keep up with mining them and repairing the damage they did but it started taking way too much of my time. I have protected my base with shields but that is not stopping the surface and landscape getting decimated. It looks terrible and is not very realistic. Is there any way to stop the meteors spawning? If not can we please get it as a config option in a future release?

**Comment by SportsFan10** [comment]
I seem to get this issue quite a bit as well.  It always seems like when you first get to the moon, it's the most tedious task to get enough meteor to build the next tier of rocket.  If you stay long enough and want to establish a base, then you get destroyed by meteors.  I agree, there should be a config option in someway.

**Comment by dj3520** [comment]
You do realize there's a place for requests that isn't here?

**Comment by mrgrey1** [comment]
This is not just a request. It's a game play bug report with an attached recommendation/request. IMO this is a legitimate bug and therefor this is the appropriate forum.
The bug report is :  Given time an over abundance of meteors destroys the planetary surfaces making the dimensions practically unusable.
The request/recommendation is : A config option to turn meteors off or adjust their spawn rate.

Take it or leave it for what it is but I've abandoned my plans for a permanent base on Mars or The Moon as a consequence of this issue. This has relegated Galacticraft, (a mod I love,) to a secondary novelty mod rather then a primary mod that my gameplay focuses on and revolves around. If I were developing Galacticraft I'd definitely want to know about a bug driving players away from using it as a primary gameplay mechanic.

**Comment by micdoodle8** [comment]
I'll look into adding a better solution, such as an anti-meteor laser or anti-meteor satellite or something, but for now I've added a config option to reduce them.

**Comment by mrgrey1** [comment]
Excellent. Thankyou. I was thinking an in game anti meteor counter measure would be a much better solution then the config option as well. I'd been thinking a 'magnetic repulser field' idea would be good but an anti meteor satellite also sounds pretty cool... Anyway, thanks again for your prompt response, think I'll go regen the moon and get back to 'walking on it'. :)

**Comment by Moobien** [comment]
Cool would be if Open Modular Turrets could target the meteors and destroy them

_Sent from my Samsung SM-G955F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by dj3520** [comment]
@Moobien Suggestions on the forum please
