### ISSUE TITLE
The Astro Miner's route is blocked by: unknown

### ISSUE THREAD

**Issue by ErrorCraftLP** [micdoodle8/Galacticraft#1753]
I created an Astro Miner Base with an Infinite Battery and started an Astro Miner. Then I started a rocket  and flew to Mars. As soon as I landed, a message appeared in the chat: ``The Astro Miner's route is blocked by: unknown``.
**Note:** The message is called [here](https://github.com/micdoodle8/Galacticraft/blob/53a03c4114e1694bd8d1b198a6d365c6fdbc0cdd/src/main/java/micdoodle8/mods/galacticraft/planets/asteroids/entities/EntityAstroMiner.java#L1042).

**Comment by radfast** [comment]
This has no connection with your rocket.  It's a block of some kind directly in the path of the Astro Miner.

Can you go find the Astro Miner and see what it is?

One thought: do you have Railcraft installed?  Railcraft puts some weird invisible blocks in the world, I have not tested the Astro Miner with those.

**Comment by ErrorCraftLP** [comment]
Strange. I started the world again (I was still on the Mars) and this time there were two messages: ```The Astro Miner's route is blocked by: unknown``` and ```The Astro Miner's route into its base seems to be blocked!```.  I flew back to the overworld and my three Astro Miners came back normal.
EDIT: I do not have Railcraft installed.

**Comment by ErrorCraftLP** [comment]
Closing this because I think it's solved
