### ISSUE TITLE
Tier3 Rocket impossible to fuel with gasoline (Aka Refined Oil)

### ISSUE THREAD

**Issue by ALivingBeing** [micdoodle8/Galacticraft#1771]
This problem happen on the Infitech2 server (version 3.1.3)
Version of Galacticraft : 3.0.12.350

This happen both in single player and multiplayer.
Tier1 and Tier2 Rocket have no problem at all getting fuel.
It does not seem to be a modpack related problem, at least according to the modpack author of Infitech2.

**Comment by dj3520** [comment]
Issue confirmed. GC v 349
