### ISSUE TITLE
Orbital planet is not being rendered properly on rocket ascending or descending phase

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#1775]
The orbital planet sprite is rendered for a very short period of time and vanishes during the ascending or descending phase.

I'm using:
* journeymap-1.7.10-5.1.0-unlimited.jar
* CodeChickenCore-1.7.10-1.0.4.29-universal.jar
* NotEnoughItems-1.7.10-1.0.3.74-universal.jar
* Galacticraft-Planets-1.7-3.0.12.350.jar
* GalacticraftCore-1.7-3.0.12.350.jar
* MicdoodleCore-1.7-3.0.12.350.jar

Before:
![2015-05-03_17 56 55](https://cloud.githubusercontent.com/assets/6743303/8632217/1ff5b348-2768-11e5-9d89-ca2d40f9f0e2.png)

Now:
![2015-07-11_00 37 58](https://cloud.githubusercontent.com/assets/6743303/8632162/155dcf3a-2766-11e5-9398-f01c8fb15618.png)

**Comment by EzerArch** [comment]
Fixed the title.

**Comment by coolmodi** [comment]
Can confirm, this is the case for version 345+, it had the "Improved switch to blocky planet as rocket leaves Overworld. (commit: f158169cc178b1e7d09e842e724b3dfd236268e7)".

This was no improvement :)
