### ISSUE TITLE
Possible item bug in Galacticraft dimensions.

### ISSUE THREAD

**Issue by nullg** [micdoodle8/Galacticraft#1779]
I'm recently getting a problem similar to http://forum.micdoodle8.com/index.php?threads/item-bug.872/

It happens when after the server restarted. Items have shuffled occasionally. I don't know what's causing this, and I can't even reproduce the issue intentionally. While this has been occurring, there were no mods added or deleted. It shuffles items but only in dimension -30, -29 and -28. Nothing wrong with the same items in the other dimensions (not sure of space stations since we can't create ones by the rules) so IDs are definitely not changed in a game for sure.
We have those three dimensions set to keep loaded statically in a config file.
Updating Galacticraft to newer versions and still occurring.

http://imgur.com/VnfIKAb
This sometimes generates such funny items like Chestplate with -31946 durability left.

Could it be doing something wrong to files that keep inventory info of the dimensions?

**Comment by micdoodle8** [comment]
Sorry, I have no idea what would cause this, but it's out of the scope of this mod. We're currently not doing anything funky that would cause item IDs or metadata (the durability, for example) to change. Mods related to world saves, or the server frameworks like Mantle would be more likely to cause these issues, though I'm not completely sure.
