### ISSUE TITLE
Cargo Rocket don't show up in a destanation I wanted to be.

### ISSUE THREAD

**Issue by Pawtpoow** [micdoodle8/Galacticraft#1780]
Minecraft Version: 1.7.10
When I launch a cargo rocket to My station and then Get my tier 1 rocket to get there it is not there..
So is my cargo.
And My cargo's launch controllers frequency was 4 and my space station's one of launch controllers is 3
Can you fix this?

**Comment by Pawtpoow** [comment]
Also another bug...When my non-cargo lands on a destination...It's flying over the pad..

**Comment by EzerArch** [comment]
>  When I launch a cargo rocket to My station and then Get my tier 1 rocket to get there it is not there.

Same as #1981, still open with more posts and details.

> When my non-cargo lands on a destination...It's flying over the pad..

Same as #1807, solved.

Therefore I recommend closing this issue.

**Comment by radfast** [comment]
Thank you @EzerArch, good spot.

"Normally" I would say that #1981 should be closed as it duplicates this which reported the issue first.  But like you say, #1981 is much more likely to lead to a fix :)

(And these are not normal times because "someone" has been away from the mod...)
