### ISSUE TITLE
Galaxy map key resetting

### ISSUE THREAD

**Issue by xJon** [micdoodle8/Galacticraft#1782]
Changing the key to anything else than 'M' resets after every config change of the mod, when there are new updates. Other configs don't change, so I'd guess this is a bug.
It's a big problematic to change it again every time the mod updates.

Thanks!

**Comment by micdoodle8** [comment]
Are you changing the key in the config file or in the in-game controls menu?

**Comment by xJon** [comment]
In the config file.
Thanks for the reply :)

**Comment by xJon** [comment]
Didn't happen while updating from v3.0.12.350 to v3.0.12.357.
Closing.
