### ISSUE TITLE
API has links back to the main code

### ISSUE THREAD

**Issue by twothe** [micdoodle8/Galacticraft#1785]
The API has many links back to the main code, which in the end makes it necessary to use the entire code-base (including all APIs used by Galacticraft as well) to use the API of Galacticraft. This is highly undesirable, as it either blows up the mod-code-base or makes testing extremely difficult.

The API should be stand-alone, that is: a modder can copy _only_ the api folder and work with that.

**Comment by MJRLegends** [comment]
i know right but atm you got to have the api and the source

**Comment by twothe** [comment]
Currently that is for me a sadly reason to not support Galacticraft at all. 

It not only would totally mess up my Git history, in addition I have to update with every of your releases, as otherwise I can no longer guarantee that it works, with all those dependencies.

**Comment by MJRLegends** [comment]
You dont have to update your addon for every version of galacticraft just remove the source of galacticraft when compiling

**Comment by micdoodle8** [comment]
As of the latest commit the API no longer has references back to the main project. One exception is the 'prefab' class, which you can use an IDE to exclude from your project's source.
