### ISSUE TITLE
Oxygen Collector runs forever, even if full

### ISSUE THREAD

**Issue by ExDomino** [micdoodle8/Galacticraft#1789]
The Oxygen Collecter runs forever, even if full of oxygen, wasting a lot of energy. I didn't find any way to turn it off, except if I remove its power alimentation, but it has a very big internal buffer.

**Comment by TheQuadShot** [comment]
Not my project or db, however I have requested a way to "turn the thing off" with a redstone signal, which is an added feature/enhancement and they don't go here, they go on the website here
http://micdoodle8.com/

**Comment by ExDomino** [comment]
I don't understand, your message makes no sense. What do you mean exactly?

**Comment by dj3520** [comment]
@ExDomino As far as I know that is the only way to turn them off, as well as any GC machine, except for the Disable button. It's how I've gotten familiar with IC2's splitter cable.

**Comment by hunator** [comment]
@TheQuadShot This is more a bug than feature request, I think that this should be here because it should be fixed.

I agree, it shouldn't drain energy when it does have full storage of oxygen.

**Comment by ExDomino** [comment]
The machine is placed on the overworld.

**Comment by DarknessShadow** [comment]
I think the Fuel Loader should also not drain energy when the rocket is already full.

**Comment by dj3520** [comment]
I suppose no work no drain for everything then?

**Comment by ExDomino** [comment]
They should not waste energy.
