### ISSUE TITLE
Localization: Font size is too small for Unicode font

### ISSUE THREAD

**Issue by oldjunyi** [micdoodle8/Galacticraft#1790]
Many languages, such as Chinese or Japanese, only have Unicode font in Minecraft.

If I play the game in the Unicode font mode, there will be some text impossible to read:
![a](https://cloud.githubusercontent.com/assets/641817/8831854/c1d0d616-30d7-11e5-9eb4-284934c461ea.png)
Unfortunately, setting the GUI Scale to "Large" won't help (I'm using a laptop with 1600 x 900 resolution, the resolution is not large enough to apply Large GUI Scale in Unicode font mode).

By the way, because the lack of anti-aliasing text rendering method, using any OpenGL scale ratio that smaller than 1.0 will make the text lose most pixels, making it hard to read.

So, could you please fix this problem? Maybe by adding a config option to use larger scale ratio or by some other method.

**Comment by micdoodle8** [comment]
Hey, thanks for the report, I would never have thought to check this. 

I am possibly doing a full-screen version of the space race manager in the next major Galacticraft version. I'll do my best to redesign the GUI so 100% font size will fit properly. As you can see here, having that font at 100% will make it too large for the slider it is describing.

**Comment by radfast** [comment]
Changed this to a 1.8 issue as this is the next major Galacticraft version :)

**Comment by darthvader45** [comment]
@micdoodle8 Same here, it's still too small even in the 1.10.2 version.  Full-screen is the only way to view it currently.

**Comment by darthvader45** [comment]
Thanks for referencing my issues.  This really needed a fix as it was getting quite annoying.
