### ISSUE TITLE
Lag Spikes

### ISSUE THREAD

**Issue by Glitchyminecraft** [micdoodle8/Galacticraft#1791]
After a few minutes on a moon or planet thats not earth, every 3-5 seconds it freezes a split second, increasing when jumping,walking or mining. its very annoying. i hope that the next update fixes it

**Comment by micdoodle8** [comment]
It's possible that your client is running out of memory, google the solution for designating more RAM for Minecraft. If that doesn't fix it, then I'll need your client log(s) please.
