### ISSUE TITLE
Server Crash after placing Arc Lamp on a place over 238

### ISSUE THREAD

**Issue by Arytas** [micdoodle8/Galacticraft#1792]
MC Version: 1.7.10
Server: Cauldron 1388
Forge: 1388
Galacticraft Version: latest (3.0.12.350)
Forge error Log: https://copy.com/lz7tqqjf8TlrNjY4

I updated my Server to newer Cauldron Version and also clientside the Forge version
i use the Technic Launcher an created own Modpack with Galacticraft included
(Modpackname: Imba Wimba)

I also updated the Galacticraft Mod to the latest version. after i try to start my server i got the error 

 Ticking block entity Acr Lamp

I fixed it by using MCEdit and deleted the ID from the Error Tile from the Map.
after that server started correctly.
But then i tried to place a new Arc Lamp and same crash comes

now i know that the Problem isnt the Arc Lamp itself (cause the Lamps are in the world)
the Problem is the Light of the Lamps

I also updated other Mods, but they are working correctly.

**Comment by TheQuantumGeneral** [comment]
What version? I'm on the latest and using them without issue.

**Comment by Arytas** [comment]
yeah sorry hitting return to early ^^

**Comment by dj3520** [comment]
Please provide a crash log via gist or pastebin or else no one will know
why you are crashing.

**Comment by Arytas** [comment]
i ve postet the crash log via link 
here is the crash log via gist. Hope this is working
https://gist.github.com/143ba441d5d04ef8f35f#file-gistfile1-txt

and i also find some a load problem. maybe this is the problem? 

[17:07:23] [main/INFO]: [micdoodle8.mods.miccore.MicdoodleTransformer:printResultsAndReset:1777]: Potential problem: Galacticraft did not complete injection of bytecode into: oi (4 / 6)
[17:07:24] [main/INFO]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1848]: Galacticraft successfully injected bytecode into: sv (1 / 1)
[17:07:24] [main/INFO]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
[17:07:24] [main/INFO]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1848]: Galacticraft successfully injected bytecode into: xk (1 / 1)
[17:07:26] [main/INFO]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1848]: Galacticraft successfully injected bytecode into: zc (1 / 1)

**Comment by Arytas** [comment]
ok update 
the crash wouldnt come every time
but if i place the arc lamp on a high place (so the light comes over 256) 
the crash comes

**Comment by Arytas** [comment]
so i tried it out some times, and find out it comes on placing at a high of 238 or higher

**Comment by Arytas** [comment]
so the problem must be in your code i guess
cause there is a NullPointerException in line 240 from the TileEntityArclamp.java file
where the light area will be generate (if i understand the code correct)

Line:
239 |||                           Block b = sideVec.getBlockIDsafe_noChunkLoad(world);
240 |||                           if (b.isAir(world, sideVec.x, sideVec.y, sideVec.z))

**Comment by Arytas** [comment]
but i dont understand why it comes also at a high from 238
so the for loop of the light is iterrating 14 times
and if we go from an interval of 0 till 255
the loop stops at 252

**Comment by Arytas** [comment]
ah ok there is also a while loop with 6 iiterratings in the foor loop 
than its clear for that hight  ;)

**Comment by Arytas** [comment]
an btw the light from the arclamps is also going throught blocks
maybe should be fixed to
