### ISSUE TITLE
No config option for space race screen upon player login

### ISSUE THREAD

**Issue by anteNox** [micdoodle8/Galacticraft#1793]
Minor minor minor issue.

I'm creating a storyline-based map with galacticraft but I'd rather minimise things that would break the immersion for the introductory scene. Would be great if there was a config option to *not* have the space race screen open as soon as a player loads the world.

**Comment by dj3520** [comment]
Technically a feature request, not a bug report.

**Comment by EzerArch** [comment]
This Git for the development and bug reports for Galacticraft only. Please, address suggestions and ideas to our forum: http://forum.micdoodle8.com/index.php?forums/suggestions.7/.
