### ISSUE TITLE
[Minor] Energy transfer not as stated when no wires involved.

### ISSUE THREAD

**Issue by dj3520** [micdoodle8/Galacticraft#1794]
So I've made a setup with two energy clusters in parallel. That means the max I should be able to move is 548EU/t with a 1.6 ratio as shown below.
![image](https://cloud.githubusercontent.com/assets/8284194/8879820/1a06239c-3202-11e5-9896-34ec6cb6b33f.png)

However, after having the outputs directly touching an MFSU, I thought something was a bit off and discovered this:
![image](https://cloud.githubusercontent.com/assets/8284194/8879908/c5bc1782-3202-11e5-90ce-fdfafab8598c.png)
That's a bit more than advertised. A bit as in twice.

As the picture somewhat shows, Buildcraft meets Galaticraft then converts directly into IC2 without a wire in the middle. Goes out the back via Glass Fibre Cable, through the gray box (an Average EU/t Counter from Nuclear Control) and up to the MFSU on top. RF -> gJ -> EU Using a Glass Fibre Cable drops this back to what it should be. This also occurs once the clusters are just converting energy and not supplying it via their buffers. That gives me what I generate, which is still about 800EU/t.

**Comment by Youjust** [comment]
This appears to be a compatability problem, and not necessarily a Galacticraft problem.

**Comment by dj3520** [comment]
It isn't exactly a problem per say, but unintended behavior

**Comment by dj3520** [comment]
Retested with 400. Persists.
![image](https://cloud.githubusercontent.com/assets/8284194/11003199/0f15c562-847f-11e5-8fa6-e88d077f9cc5.png)
No wire between GC and IC2 yields 512Eu/t out of a single ESC when 287 advertized. However...
![image](https://cloud.githubusercontent.com/assets/8284194/11003258/611e8bc8-847f-11e5-891a-ee782673d019.png)
256EU/t (configured 95% loss, but this isn't about energy conversion.)

**Comment by radfast** [comment]
Thanks for reporting and thank you for the November update, that was very helpful.

@dj3520 you have done a fine job keeping the issues list in check while I have been away from the mod.

This issue should be fixed next build.  It was not a programming error per se.  Simply that IC2 machines (unlike any of the other energy mods) "actively" suck energy out of any energy store they are connected to.  So every tick, the MFSU is pulling energy out of the Energy Storage Module the IC2 way, and the Energy Storage Module is also pushing energy out the GC way.  Result: a double transfer every tick.

**Comment by dj3520** [comment]
np @radfast I subscribed to the repo to track issues in case something game
breaking pops up. I also feel like if I see someone with a problem I might
know the solution to I should at least say something.
