### ISSUE TITLE
Launch Controllers

### ISSUE THREAD

**Issue by JDuskey** [micdoodle8/Galacticraft#1802]
Launch controllers do not seem to be working properly. When i launch from them, and i have them set to go to a target destination, and I get in the rocket and launch from the launch controller, it still takes me to the Choose a Planet screen. And cargo rockets that I send don't make it to the destination launch pad.

**Comment by micdoodle8** [comment]
Is this just in single player?
The target destinations are in other dimensions, right?
Can I see a list of other mods you have installed?
