### ISSUE TITLE
crash to launcher when placing Arclamp and world corrupt with ticking block entity

### ISSUE THREAD

**Issue by TheQuadShot** [micdoodle8/Galacticraft#1806]
I had a player in a Runic Dungeon (dimID-34, I think) and when he placed an Arclamp he crashed to launcher and all players got kicked from the server(IntegratedServer). The world is corrupted and I have to set removeErroringEntities=true in the forge.cfg file to get it back.
here's the server log files
server log when it happened: http://pastebin.com/zEi2T8dk
server start up after crash: http://pastebin.com/rah6BpH6

**Comment by Arytas** [comment]
same on my issue #1792

**Comment by micdoodle8** [comment]
Fixed with e323435e93da016358a0b5855196ef84baba4d90
