### ISSUE TITLE
Oxygen Bubble Distributer has oxygen but still drains oxygen/hurts the player without tanks

### ISSUE THREAD

**Issue by HyperionNexus** [micdoodle8/Galacticraft#1808]
So this has happened twice so far where the OBD has oxygen from ultimate pressurized tubes from Mekanism that has oxygen from the electrolytic separator. I usually have to replace them and it's a pain to do so if you have lots of them around.

Even when the bubble is "active" it still drains the oxygen from my tanks and if they run out or I take them off I get damage. 

This has happened in two different builds one of them was somewhat old but still had the astro miner and such but we are currently using the most current build in the download section of the site.

**Comment by HyperionNexus** [comment]
Note this is on a server and only happens when I lag out so it's like my client doesn't register the bubble unless I replace the block again.

**Comment by DarknessShadow** [comment]
https://github.com/micdoodle8/Galacticraft/issues/1718
