### ISSUE TITLE
Galacticraft oxygen equip/frequency module not rendering

### ISSUE THREAD

**Issue by HyperionNexus** [micdoodle8/Galacticraft#1809]
Overall exactly what the title says, I cannot see the oxygen equip on my back or the frequency module.

I also have had another bug that is related to this rendering and that is when you move on any planet with light gravity or none the thermal padding moves very oddly and the players legs don't really move either.

**Comment by EzerArch** [comment]
Let me guess, are you using More Player Models or More Player Movements?

http://wiki.micdoodle8.com/wiki/Compatibility

**Comment by HyperionNexus** [comment]
Nope. They're not in the custom modpack but it looks like it's optifine that is causing the tanks and such to be invis, going to try the fix and will give an update soon.

**Comment by HyperionNexus** [comment]
Okay so I got smart render and renderAPI so I see the oxygen stuff now but now anything the is on the "chestplate" slot is bugging out and stuck facing south. This is only for regular armor, jetpacks, backpacks and botania's wings.

**Comment by dj3520** [comment]
Probably the same as #1819

**Comment by radfast** [comment]
Good news, the Optifine issue is fixed in GC 421.

For the RenderPlayerAPI armor issue, thank you @HyperionNexus for the info about the "chestplate" slot, that helps me track down the source of the problem.  This is now duplicated in #1819, and as I have commented on #1819 I will close this.
