### ISSUE TITLE
Move API to separate project

### ISSUE THREAD

**Issue by NightKosh** [micdoodle8/Galacticraft#1813]
Hello. Can you move your API to separate project? It will allow to use it as a git submodule without exporting all your mod's sources. At the same time submodules give a more flexible way to configure and deploy project and all its dependencies(one of them is your API)

You can read more about submodules here https://git-scm.com/book/en/v2/Git-Tools-Submodules
For gradle configuration examples you can look at Forestry(https://github.com/ForestryMC/ForestryMC/blob/dev/build.gradle#L47),  Railcraft(https://github.com/CovertJaguar/Railcraft/blob/master/build.gradle#L26) or Gravestone(https://github.com/NightKosh/GraveStone-mod/blob/master/build.gradle#L36) repositories.

**Comment by micdoodle8** [comment]
Good point, done.
