### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Bormandesign** [micdoodle8/Galacticraft#1815]
Server random crash. Here is crash-report. Plz help.
http://pastebin.com/77Q2YQa5

**Comment by Arytas** [comment]
did you read the error message?

Forestry : [Forestry] Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client:
Bukkit, MCPC+, or other Bukkit replacement
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.

have you updated something? 
ore used new mods with an old world?

**Comment by micdoodle8** [comment]
Sorry, there's nothing I can do about 1.6.4 errors, we don't support Galacticraft 2 at this point.
