### ISSUE TITLE
Telemetry Frequency Module Crash

### ISSUE THREAD

**Issue by a92b** [micdoodle8/Galacticraft#1816]
My brother and I were playing together on a LAN world where he died and his game crashed. Now, whenever we open the world, the game crashes.

Crash Report:

![screen shot 2015-08-11 at 5 16 12 pm](https://cloud.githubusercontent.com/assets/13755093/9210894/b8c6b46c-404c-11e5-9493-fbb2e7dc654b.png)

**Comment by Arytas** [comment]
cant read the error
can u plz use pastebin ore something else

**Comment by dj3520** [comment]
I would try moving where he spawns via MCEdit

**Comment by a92b** [comment]
I have tried moving him via MCEdit and it hasn't fixed anything.

**Comment by HyperionNexus** [comment]
It would be easier to read and then help if you put the crash on paste bin.
