### ISSUE TITLE
Equipment worn doesn't show up using Optifine

### ISSUE THREAD

**Issue by Glitchyminecraft** [micdoodle8/Galacticraft#1819]
I used OptiFine_1.7.10_HD_U_C1 and Galacticraft Core. -Planets and Micdoodle8Core build 351, everything except thermal padding is invisible. And thermal padding acts strange when in space or on any planet/moon Except earth.

SCREENSHOTS:
![2015-08-16_11 22 05](https://cloud.githubusercontent.com/assets/13451091/9292734/2889c03a-440a-11e5-8813-3d07c4451c00.png)

![2015-08-16_11 22 40](https://cloud.githubusercontent.com/assets/13451091/9292735/3577fa0a-440a-11e5-88de-b0081da1c03c.png)

**Comment by dj3520** [comment]
There's a wiki page that fixes your problem.

**Comment by EzerArch** [comment]
http://wiki.micdoodle8.com/wiki/Compatibility

**Comment by HyperionNexus** [comment]
That solution doesn't really work for me, it made the armor face south but everything else was fine.

**Comment by dj3520** [comment]
Does it happen to look a bit like this?
![image](https://cloud.githubusercontent.com/assets/8284194/11005238/b4180e5c-848a-11e5-81a9-fef6c90ce99e.png)

**Comment by radfast** [comment]
Good news: the "equipment not rendering with Optifine" issue is now fixed in GC version 421.

**Note it is fixed without using RenderPlayerAPI.** 

The "armor facing south with RenderPlayerAPI" issue is not fixed by this, I think.  Please can @dj3520 and anyone else affected by that:
* test with GC 421
* if it is still happening, give details of what other mods have to be installed to cause it - e.g. Optifine alone, Optifine + RenderPlayerAPI, RenderPlayerAPI alone

**Comment by dj3520** [comment]
@radfast Unable to test until #2029 is fixed. Looking forward to having this fixed though.
![image](https://cloud.githubusercontent.com/assets/8284194/12373655/478d634e-bc4e-11e5-9f8c-7f0fe155f58c.png)

**Comment by radfast** [comment]
OK that crash is fixed now, please try 422.

When testing this armor issue:
* please specify which out of (O) Optifine  (R) RenderPlayerAPI  and (S) SmartRenderAPI are installed on the client (I'm going to assume latest versions unless you tell me different)
* please tell me the visibility of (1) GC thermal armor  (2) GC equipment   (3) regular armor e.g. Titanium Chestplate

In *my* testing with O+R, I'm seeing thermal armor OK, regular armor OK (no issues) but no GC equipment.

**Comment by radfast** [comment]
In my tests, the armor is now working correctly with RenderPlayerAPI.*

RenderPlayerAPI is only necessary if you are using another mod which requires it to assist compatibility, like **Smart Moving**, **Animated Player** or **VoxelPlayer**.  RenderPlayerAPI is not necessary if you just want to play with Optifine.

* (Minor issue: if a chestplate is worn, your arms seem to become thicker.  I'm not sure if that is a Galacticraft issue)

Closing this now.

If there are rendering compatibility issues in GC version 423 or above, please start a new issue report, with screenshots.  State the relevant mods (discussed here) and versions, and how the problem happened.
