### ISSUE TITLE
GC Tin/Copper takes over Metallurgy Copper/Tin

### ISSUE THREAD

**Issue by Glitchyminecraft** [micdoodle8/Galacticraft#1820]
All metallurgy recipes requiring copper use GC copper instead of its own copper. Also, railcraft copper takes over GC copper recipes. so is Metallurgy Copper as useless as dirt

**Comment by dj3520** [comment]
Sounds like an ore dict problem with Metallurgy. My experience with
Railcraft is that the copper works fine with other "coppers."

**Comment by micdoodle8** [comment]
This is just how the ore dictionary works. Mods that register their ores and ingots in the dictionary will share the recipe ingredients using those items. If other mods have significant ingot creation methods, making their ingots more valuable, the mod author should add an option to disable their ore dictionary integration.

**Comment by dj3520** [comment]
All coppers are the same, however you can turn off Galaticraft copper ore
gen. I also suggest using Railcraft's metals chest as it will make all
copper Railcraft copper.
