### ISSUE TITLE
Server deadlock - AoA mobs spawning on a space station.

### ISSUE THREAD

**Issue by ProsperCraft** [micdoodle8/Galacticraft#1822]
https://github.com/Funwayguy/Epic-Siege-Mod/issues/23

If we could get the biome id for space station we could add it to just another spawner spawning blacklist, which might help this issue.

**Comment by Funwayguy** [comment]
Sorry to jump in on this issue (I'm working on the other one) but I believe the ID you're looking for is 105 (by default) according to this:

https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/util/ConfigManagerCore.java#L160
and this:

https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/world/gen/BiomeGenBaseOrbit.java#L10

However the biome base number is a config so changing it will offset the space biome ID too.

**Comment by ProsperCraft** [comment]
Thank you, what would it look liked spelled out? this is what they look like in the Just another spawner blacklist.  For some reason the Galacticraft biomes/dims don't show up in that file, I don't know if its generated from the mod information or already there in a static config.  Full config here - http://pastebin.com/q8zSDEbc

    chylex.hee.world.biome.BiomeGenHardcoreEnd.Sky
    com.arisux.avp.dimension.acheron.BiomeAcheron.LV-426 (Acheron)

**Comment by radfast** [comment]
Try
    micdoodle8.mods.galacticraft.core.world.gen.BiomeGenBaseOrbit.space

Any further issues please re-open.
