### ISSUE TITLE
EndOI crash

### ISSUE THREAD

**Issue by 23Link89** [micdoodle8/Galacticraft#1824]
When I go on the moon I crash only when I have a conduit hooked up to a sealer on the moon. Crash: http://pastebin.com/8YvxDYPh I think it may have something to do with JRE 8 and the being on the moon with no sound accept I have a frequency module which allows me to hear on the moon when I have it on. Thank you for your time.

**Comment by radfast** [comment]
This crash is connected with **Weather Mod**.  Not Galacticraft.

Google search shows [this which explains in the final post it is Weather](http://www.minecraftforum.net/forums/support/modded-client-support/2304484-crashing-consistently)
also [this](http://www.minecraftforum.net/forums/support/unmodified-minecraft-client/2489186-minecraft-crashes-in-the-middle-of-a-modded-world) - note that the poster there has Weather installed but not Galacticraft.

There are also many other reports of this type of crash, which have no connection with Galacticraft.
