### ISSUE TITLE
Oxygen sealers

### ISSUE THREAD

**Issue by 23Link89** [micdoodle8/Galacticraft#1825]
When I take off my oxygen tanks and wait in a sealed room sometimes it will flash "Oxygen setup invalid" and do damage then disappear.

**Comment by micdoodle8** [comment]
Sorry for the delay. I believe if you 'enable debug' in the core config, you should get more info on what the oxygen sealers are doing, if you watch the console. If there's anything fishy going on in there, please re-open this issue with the extra information. Thanks.
