### ISSUE TITLE
GC Torches in Ex Nihilo crucible

### ISSUE THREAD

**Issue by thomk114** [micdoodle8/Galacticraft#1826]
I wanted to use a Galacticraft space station for a skyblock modpack. Unfortunately, the torch is seen as GalacticraftCore:tile.unlitTorch or GalacticraftCore:tile.unlitTorchLit. I can't use the GalacticraftCore:tile.unlitTorchLit as a heat source for the crucible from Ex Nihilo and modtweaker doesn't change it.

I would like to use it, but the only torch that does work is the Tinkers' Construct stone torch because it doesn't get affected by oxygen.

**Comment by micdoodle8** [comment]
So as an example, you're using 
mods.exnihilo.Crucible.addHeatSource(GalacticraftCore:tile.unlitTorchLit, 0.1);
?

**Comment by radfast** [comment]
That's strange, because in all recent versions of Galacticraft, the Tinker's Construct stone torch does get affected by oxygen.  Which version of GC are you testing?

**Comment by radfast** [comment]
> Yes, I was using mods.exnihilo.Crucible.addHeatSource(GalacticraftCore:tile.unlitTorchLit, 0.1);

micdoodle8 typed it differently, see the ```<``` and the ```>```
```mods.exnihilo.Crucible.addHeatSource(<GalacticraftCore:tile.unlitTorchLit>, 0.1);```

I see no reason why that wouldn't work.  But this can also help other people using Ex Nihilo who don't have ModTweaker, so I will add this tweak to Galacticraft.
