### ISSUE TITLE
Oxygen sealers do not provide hearing

### ISSUE THREAD

**Issue by katzenpapst** [micdoodle8/Galacticraft#1827]
Just went to my oxygen-sealed space station without a frequency module and noticed that I can't hear there. It even shows me the "I need the Frequency Module to hear here" message.

**Comment by EzerArch** [comment]
This was suggested: http://forum.micdoodle8.com/index.php?threads/sound-should-be-audible-in-air-filled-ambients.2478/

**Comment by micdoodle8** [comment]
Hmm, doing this correctly would be quite complicated actually. Since sound requires a sealed area throughout it's travel time, for each sound I would need to do a pathfinding check to see if all the area between the sound and the player is sealed. I might end up adding a more simple solution, for performance reasons, where both the sound source and the player are checked for an oxygenated environment before playing the sound.

**Comment by katzenpapst** [comment]
I'd say the simple solution would be enough.

**Comment by EzerArch** [comment]
>  I might end up adding a more simple solution, for performance reasons, where both the sound source and the player are checked for an oxygenated environment before playing the sound.

I'd go for a even simpler solution: check if *only* the player is in a normal-pressurized environment, as you said, "oxygenated environment". For player perspective, he may think "**I** am in a sealed room, therefore **I** am supposed to be able to hear the sound regardless the position of its source". Of course, this is quite far from realism or scientific accuracy, but it fits in the suspension of disbelief the game provides and it works.

**Comment by dj3520** [comment]
In a game where a tree can grow on a single floating block of dirt, I have to agree with @EzerArch, though the more complicated version would be interesting too, so long as it's not too intensive. Maybe a simple check to see if the source and player are in the same sealed space.

**Comment by micdoodle8** [comment]
So I ended up going with the slightly more complicated solution. I thought about doing just checking if the player was in an oxygenated environment, but really it's a small client-side check to see if the sound source is in oxygen as well, so I ended up doing both checks. Although it might be confusing to some people at first, that might teach them a little bit about how sound works in space :)
