### ISSUE TITLE
Galacticraft 3 Head sticks to ceiling in space station

### ISSUE THREAD

**Issue by lellis2k** [micdoodle8/Galacticraft#1828]
Version: GalacticraftCore-1.7-3.0.11.333

When I created a space station I spawned with my head attached to the ceiling, I can move around horizontally using WASD but no combination of sneak/jump can make me move DOWN.

The only way I was able to move down was to either change to creative mode (not possible for the other players as they're not OPs) or to remove the ceiling, at which point I could now use shift (sneak) to move down.

Once I had moved off the ceiling by destroying it, all movement worked fine, until I came into contact with another peice of ceiling (i.e. seemingly any block touching my head) at which point I was stuck again until I repeated the above steps.

I want to build an enclosed space station but this currently seems impossible.

Thanks in advance, Leigh

**Comment by dj3520** [comment]
Have you tried with a newer version?

**Comment by lellis2k** [comment]
New version worked fine, tried the old version again and that worked fine.
May have been a one-off glitch.
