### ISSUE TITLE
Galacticraft developer download site doesn't update new versions

### ISSUE THREAD

**Issue by Xen1290** [micdoodle8/Galacticraft#1829]
@radfast @micdoodle8 
http://www.micdoodle8.com/mods/galacticraft/downloads/dev In this page, the dev jar And the api are for version BETA 3.0.1(correnti version 3.0.12), But in jenkins are updated.
http://ci.micdoodle8.com/job/Galacticraft3-dev/

**Comment by micdoodle8** [comment]
Thanks for the report, fixed.

**Comment by Xen1290** [comment]
Thanks!
