### ISSUE TITLE
Crash on rocket launch

### ISSUE THREAD

**Issue by PootisDispenser** [micdoodle8/Galacticraft#1832]
--- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 8/30/15 2:42 PM
Description: Exception ticking world

java.lang.IllegalArgumentException: Could not get provider type for dimension -29, does not exist
at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:148)
at net.minecraftforge.common.DimensionManager.shouldLoadSpawn(DimensionManager.java:268)
at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:347)
at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:165)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:148)
at net.minecraftforge.common.DimensionManager.shouldLoadSpawn(DimensionManager.java:268)
at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:347)
at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:165)

-- Affected level --
Details:
Level name: New World
All players: 0 total; []
Chunk stats: ServerChunkCache: 1 Drop: 1
Level seed: 29073684723001238
Level generator: ID 00 - default, ver 1. Features enabled: false
Level generator options: 
Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Level time: 0 game time, 0 day time
Level dimension: 0
Level storage version: 0x00000 - Unknown?
Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
Level game mode: ERROR NullPointerException: null
Stacktrace:
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
Minecraft Version: 1.7.10
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_25, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 217580160 bytes (207 MB) / 501587968 bytes (478 MB) up to 1060372480 bytes (1011 MB)
JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 24 mods loaded, 24 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
UCHIJAAAA mcp{9.05} Minecraft Coder Pack 
UCHIJAAAA FML{7.10.99.99} Forge Mod Loader 
UCHIJAAAA Forge{10.13.4.1448} Minecraft Forge 
UCHIJAAAA Micdoodlecore{} Micdoodle8 Core 
UCHIJAAAA alluwant{2.1} All U Want 
UCHIJAAAA animalsPlus{1.2} Animals+ 
UCHIJAAAA AnimationAPI{1.2.4} AnimationAPI 
UCHIJAAAA CustomSpawner{3.3.0} DrZhark's CustomSpawner 
UCHIJAAAA MoCreatures{6.3.1} DrZhark's Mo'Creatures Mod 
UCHIJAAAA meteors{2.13} Falling Meteors 
UCHIJAAAA GalacticraftCore{3.0.12} Galacticraft Core 
UCHIJAAAA GalacticraftMars{3.0.12} Galacticraft Planets 
UCHIJAAAA iChunUtil{4.2.2} iChunUtil 
UCHIJAAAA GraviGun{4.0.0-beta} GraviGun 
UCHIJAAAA RadixCore{2.0.2} RadixCore 
UCHIJAAAA MCA{1.7.10-5.0.7.2} Minecraft Comes Alive 
UCHIJAAAA MobAmputation{4.0.0} MobAmputation 
UCHIJAAAA MobDismemberment{4.0.0} MobDismemberment 
UCHIJAAAA Morph{0.9.2} Morph 
UCHIJAAAA cfm{3.4.8} §9MrCrayfish's Furniture Mod 
UCHIJAAAA hbm{0.0.1} HbMs Mod 
UCHIJAAAA shadowworld{1.2.1} Shadow World 
UCHIJAAAA StructureSpawner{0.1} StructureSpawner 
UCHIJAAAA zeldaswordskills{1.7.10-2.2.6} Zelda Sword Skills 
GL info: ERROR RuntimeException: No OpenGL context found in the current thread.
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Player Count: 1 / 8; [GCEntityPlayerMP['I_Love_Ducks'/2069, l='New World', x=-227.50, y=11.40, z=211.50]]
Type: Integrated Server (map_client.txt)
Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by dj3520** [comment]
Next time just open the issue again

**Comment by HadesDurin** [comment]
you should update your java version to update 60 and you also give detailed informations about the versions of the mods you use, because GalacticraftMars{3.0.12} Galacticraft Planets is not sufficient, we need also the correct build number (like: Galacticraft-Planets-1.7-3.0.12.357).

**Comment by SteveKunG** [comment]
@PootisDispenser This is dimension id conflict with other mod. You should changing galacticraft dimension id.

**Comment by PootisDispenser** [comment]
thx but im not good with editing ids so how do i do it lol

**Comment by micdoodle8** [comment]
Open your Galacticraft Mars config file (.minecraft/config/Galacticraft/mars.cfg) with notepad. Change the line that says:
    I:dimensionIDMars=-29
to something with a different (negative) number other than 29.
