### ISSUE TITLE
GT input hatches can't accept fluids with GC installed

### ISSUE THREAD

**Issue by Zer0id** [micdoodle8/Galacticraft#1836]
I have a problem with GregTech input hatches stop accepting fluids (not only oxygen as mentioned in thread below) when GC is installed

Found an answer by GregoriusT:
Maybe GC does something to the Fluid Registry that breaks Forge Fluids as a whole and that is the actual Problem.
http://forum.industrial-craft.net/index.php?page=Thread&postID=189147#post189147

so, I decided to open issue here. 

versions of mods i used:
Galacticraft 1.7-3.0.12.357
Gregtech 5U 1.7.10-5.08.29

**Comment by micdoodle8** [comment]
I'm using Mekanism's gas registry, which registers gases in the fluid registry.

I'm curious if Mekanism (which also adds oxygen as a fluid) has a similar problem with GT. Do you have Mekanism installed?

**Comment by Zer0id** [comment]
No, the only mods, which adds fluids, I'm playing with is Industrial Craft Experimental and GregTech

**Comment by Dream-Master** [comment]
Fluid not have textures when using Gregtech.
Helium, CO2 and Argon.
https://github.com/micdoodle8/Galacticraft/issues/1664

**Comment by Krysinski** [comment]
If you fill certus tank from ExtraCells mod with untextured gases (https://github.com/micdoodle8/Galacticraft/issues/1664) you get "already tesselating" error and crash client.
You cant connect to server more, you will getting crash. World will be broken for you then.

**Comment by micdoodle8** [comment]
@Zer0id This should be fixed in the latest build, please let me know (if you are still able to test this).

**Comment by Zer0id** [comment]
It seems in a new created world it works fine now.
but in existing world nothing changed - after installing GC all GT multiblocks, which interact with liquid materials, can't accept fluids. and continue their work only after removing GC.
