### ISSUE TITLE
Thermal underwaer 

### ISSUE THREAD

**Issue by HadesDurin** [micdoodle8/Galacticraft#1838]
i lately start galacticraft and craft those underwear, which indicates, when worn under your armor it is unseen, but this is what i got
i use 1.7-3.0.12.350 build of galacticraft

![2015-09-09_12 05 28](https://cloud.githubusercontent.com/assets/5231067/9759180/99a21fc6-56eb-11e5-9fb4-80d5db86f5d2.png)

in the picture, the underwear is overlaying my helmet texture...

**Comment by micdoodle8** [comment]
If you're using a mod which makes your helmet smaller than the default game, there's nothing I can do about the size of the Galacticraft helmet being bigger.

Google translated:
Wenn Sie eine mod, die Ihren Helm kleiner als die Standard-Spiel macht sind, gibt es nichts, was ich über die Größe des Galacticraft Helm wobei größere tun.
