### ISSUE TITLE
BC Oil compatibility

### ISSUE THREAD

**Issue by Galvanize** [micdoodle8/Galacticraft#1839]
I had some problems with compatibility between GC Oil and BC. I won't get into details because I think I found the cause.
After some digging I found this:
https://github.com/micdoodle8/Galacticraft/commit/77589e0a5531533e8bbba6ea7014bc5f66518211

I don't want to sound obnoxious but that looks like a lazy fix to me.

Also I would like to know if there is any reason to use different oil types? I noticed that GC Oil should not be allowed to be picked up in bucket, but doing so get me BC oil on the bucket, and thats the only way I found to convert them so far.

As far as I know fluids are supposed to be shared between all mods that need it now (i.e. Steam is steam, not RC steam, MFR steam, Big Reactors steam, etc.)

**Comment by asiekierka** [comment]
Overwriting BC's own recipe names is not supported. Neither is reflecting to support multiple APIs, but I'll let that pass if done right.

**Comment by micdoodle8** [comment]
Fluid compatibility should be vastly improved in the latest dev build. I've dropped the whole oil extraction process... although it was unique to Galacticraft, it is a nightmare to keep compatible with other mods.

If there are any remaining compatibility issues, please let me know.

**Comment by asiekierka** [comment]
It is a shame, though we are experimenting with new oil processing ourselves nowadays.
