### ISSUE TITLE
Other players not rendering in Space Station

### ISSUE THREAD

**Issue by PsychoLynx** [micdoodle8/Galacticraft#1840]
Using KCauldron 1.7.10-1492.152 as server and Forge 10.13.4.1492 as a clients. Galacticraft version 357. 

It seems players are unable to see each other in the spacestation dimensions. We've tried accessing the dimension via rocket, /dimensiontp and essentials warp-command, but it didn't help. Logging out and in while in the station makes you visible to other players, but the player who logged in cannot see them.

To a lesser extent this is also true with the Moon dimension, but it is possible to log-in and out and have all players see each other in Moon.

**Comment by micdoodle8** [comment]
Are you getting any errors on the client or server? Either way, can I get a client log after this has happened? Thanks

**Comment by PsychoLynx** [comment]
Hey! There are some server errors, but I doubt they're relevant. Here's some logs for you:

Server (from when I join the game in the space station dimension):
http://pastebin.com/3mjtVMT9

Client log: 
http://pastebin.com/PAzJb3Kq

**Comment by micdoodle8** [comment]
Sorry for the delay, I'm not sure if you still have the same environment...

Those server errors don't appear to be relevant, but can I have a look at the logs/fml-client-latest.log file - after the issue has been re-created in-game?

Thanks.

**Comment by dj3520** [comment]
Quick question. Does this happen for a short while on the Overworld if a
player teleports to an area with another player already there? If so, I
have the same issue and it happens because of Essentials, not Galaticraft.

**Comment by PsychoLynx** [comment]
Hi! it is possible that this is a KCauldron issue, as highlighted in this thread:
tcpr.ca/forums/discussion/138/cant-be-seen-if-other-people-teleport-to-me 
I have been unable to test the potential bugfix as I'm not skillful enough to build the fixed server from source yet. I shall report my results back once I get my hands on the new server version.

**Comment by PsychoLynx** [comment]
Can now confirm to be due to KCauldron bug, fixed in the newest version of KCauldron. Sorry for the confusion!

**Comment by micdoodle8** [comment]
Okay, glad it's fixed :)

**Comment by chezpaul** [comment]
When is the latest KCauldron coming out? ;-)

**Comment by dj3520** [comment]
That's a conversation for somewhere else.
