### ISSUE TITLE
Player gets stuck in the ceiling in airless rooms in the space station

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#1841]
(ref.: http://forum.micdoodle8.com/index.php?threads/cant-move-on-space-station.5828/)

This issue is hard to reproduce and happens in several ways:

1. The player spawns in the space station and moves slowly upwards to the ceiling, and then he gets stuck. The sneak key doesn't work, unless he breaks the block above the head or walks away from the ceiling.

2. If there's no air blocks (I couldn't reproduce the bug in pressurized rooms) and the player moves up (jump key) and touches the ceiling, he can no longer move down. Same workaround above applies.

3. I couldn't reproduce this bug in a newly generated world, only on old ones, but still I noticed the player head gets "sticky" if the touches the ceiling in airless rooms in the new worlds.

Probably related to the bug:

* The player will always move upwards after dismounting a rocket or world reload, and in this case 1 block up.

* Sometimes the player spawns at the Arrival Block 1 block up, at y=66, instead of y=65. Rarely at y=67, getting suffocation.

**Comment by spacebuilder2020** [comment]
Yea

**Comment by dj3520** [comment]
Seems to be a duplicate of #1833 which has a bit more info on the matter.

**Comment by EzerArch** [comment]
I'm closing it to avoid duplication. @dj3520 thank you.
