### ISSUE TITLE
Infinite Energy

### ISSUE THREAD

**Issue by ArgonBird18** [micdoodle8/Galacticraft#1842]
![infinate](https://cloud.githubusercontent.com/assets/7106615/9833211/f88e13be-595c-11e5-92cf-99f576fc44cd.png)

That setup gives me infinite energy. As long as the energy storage module has power to start with, the stored energy should start to increase.

**Comment by ArgonBird18** [comment]
I did a little bit of testing and I figured out this:
1. This issue only happens with BuildCraft installed

2. With BuildCraft installed, the Energy Beam Receiver can be placed on wires as shown in the picture in my previous post

3. If BuildCraft is removed and the generator is still in the world, it will not work.

4. This only works with energy storage clusters.

**Comment by radfast** [comment]
Thank you, this is very helpful information, this should be fixed soon.
