### ISSUE TITLE
ExtraUtilities Conflict

### ISSUE THREAD

**Issue by RebaLynn1960** [micdoodle8/Galacticraft#1843]
With GalactiCraft Installed the ExtraUtilities portals for the deep dark and the last millennium no longer work. If I remove GC, they work just fine. I have to conclude that something in GC is blocking them.

**Comment by UnbelievableOne** [comment]
I have the same problem. I tried a lot of version but always the same problem. If I try to craft unstable ingots or the portal to deep dark it doesn`t work correct. Without GC everything is fine.

**Comment by UnbelievableOne** [comment]
Ok just 5 min later and I found a solution ;D . Just add PlayerAPI and everything will work correct. I read that in the GC wiki.

**Comment by radfast** [comment]
Thank you @UnbelievableOne  - nice one!   I have updated the [Wiki](http://wiki.micdoodle8.com/wiki/Compatibility) to include extra references to this so that more people will find it.
