### ISSUE TITLE
[Crash]

### ISSUE THREAD

**Issue by Dream-Master** [micdoodle8/Galacticraft#1848]
I get this crash.
Open Eyes said it have something to do with Galacticraft.

https://gist.github.com/Dream-Master/098065ea378662dfcc35#file-gc

**Comment by micdoodle8** [comment]
The line
    at gregtech.common.GT_Client.onPlayerTickEventClient(GT_Client.java:241)
makes me think that it's a GregTech issue, the stack trace does involve Galacticraft, but it's simply passing through a custom player update method.

**Comment by Dream-Master** [comment]
Ok will ask on GT side.
Thanks
