### ISSUE TITLE
24 fire block in sealed room causes cpu hang.

### ISSUE THREAD

**Issue by NolanSyKinsley** [micdoodle8/Galacticraft#1849]
I was making a room to make Super Massive Tech stars in, which needs 1000  fire blocks, so I made a large room to do it in, 7000 blocks including the walls. It was sealed with 7 o2 sealers with an airlock. I can put down 20 fire blocks just fine, but if I place down 4 more java's cpu usage maxes out and the game hangs. I can't even kill it normally, have to issue kill -9 to get java to stop.

Tested outside in an 02 bubble and it works just fine, I can place as many fire blocks as I like.

I am running the galactic science modpack. Log from start until hang: http://paste.feed-the-beast.com/view/c9937bef

**Comment by dj3520** [comment]
This isn't the best thing to do since even if you did place all of those
fire sources down, unsealing the area they're in gets rid of a all of them
instantly.

**Comment by NolanSyKinsley** [comment]
>.> giving birth to the star needs the fire, and gets rid of them, fire needs oxygen so a sealed room for such a large amount is easier then confining 1000 blocks of fire to an 02 bubble.

**Comment by dj3520** [comment]
Yes but why on a Galacticraft planet where oxygen is needed? Why not
somewhere else?

**Comment by NolanSyKinsley** [comment]
Because I am playing the Galactic Science modpack , there is no overworld dimension as the earth was "destroyed". There are only planets, moons, asteroids and space stations so I have to provide oxygen to start fires.

**Comment by micdoodle8** [comment]
Hey, can you try setting "Enable Debug Messages" to true in the core config, and providing the new log after this is enabled (and the problem is recreated)? That should give me more information on why the sealer thread(s) are hanging. Thanks

**Comment by NolanSyKinsley** [comment]
Well this is most certainly odd. I enabled debug mode, started a new world, created a sealed room and tried to recreate the issue and was unable to do so in debug mode, I placed 30 fire down and nothing happened. 

I was going to say the issue was resolved as I am running the latest build, but I decided to disable debug mode just to make sure and I logged back into the world and immediately froze up. I saw the HUD with my health bar, but everything else remained black. I re-enabled debug mode and tried to log back into the world an the log just stops at "downloading terrain", it won't go any further, never even loads the HUD.

Don't know how much it will help, but here is the log from the second lock up while logging in with debug mode: http://paste.feed-the-beast.com/view/5bb1c613

**Comment by micdoodle8** [comment]
Hmm, strange. The last message before the ~40 second hang is ```[NEIAddons]: World changed, resetting``` I'm not familiar with this mod, is it possible to remove it and test the results?

**Comment by NolanSyKinsley** [comment]
NEI addons is just there as a handler to allow other mods to add non-standard recipes to NEI. I disabled it and the issue still persisted

http://paste.feed-the-beast.com/view/9f0d3780

(note it didn't save this time, I was alt+tabbed away when it loaded)

**Comment by NolanSyKinsley** [comment]
Okay, more oddening... I tried starting a new world with debug enabled, created sealed room, set 30 fire down without incident, then I logged out and logged back in without shutting down the client. It lagged out again, only this time it made me start falling through the world even though all the chunks were loaded.

http://paste.feed-the-beast.com/view/4d640dc0 (nei addons was still removed for this test)

**Comment by micdoodle8** [comment]
This is on a single-player world, correct?

**Comment by micdoodle8** [comment]
Good news, it was a small mistake made earlier and it explains all the weirdness above. Thanks for the help with finding the source of the issue.
