### ISSUE TITLE
Cant run a Lapitos Galacticraft Server

### ISSUE THREAD

**Issue by Antkin** [micdoodle8/Galacticraft#1850]
Hello,
Hope this is the right place to post. My friend and I have been trying to run a minecraft forge server to be able to use the Lapitos Galacticraft mod together, however we have not had any success. The forge server works without mods, however as soon as we copy the mod folder from technics app data folder into forges mod folder the server doesnt start and crashes. I'm not sure whats going wrong, has anyone had a similiar experience?

**Comment by domkalan** [comment]
You probly need to take out the client mods such as minimaps and resource loaders. A great place to ask this would be on the Minecraft Forums as this site is mostly intended for developers.

**Comment by Antkin** [comment]
All right thank  you. I've posted to the minecraft forums, and I'm going to try removing client mods.
