### ISSUE TITLE
Galacticraft breaks PneumaticCraft (and possibly others) oil and fuel

### ISSUE THREAD

**Issue by lundal** [micdoodle8/Galacticraft#1853]
After newer versions of PneumaticCraft startet to properly use the fluid registry, its oil and fuel has become completely broken by GalactiCraft. Buckets can no longer be used to pick up the fluids from tanks, and tanks and machinery will not accept them.

I believe the cause to be the conditional fluid renaming on lines 234-235 in GalacticraftCore.java, as simply prepending X to GalactiCraft's jar file name to make it load after PneumaticCraft fixes the problem:

```
if (FluidRegistry.getFluid(nameOil) != null) nameOil = "oilgc";
if (FluidRegistry.getFluid(nameFuel) != null) nameFuel = "fuelgc"; 
```

In that case, it might break the oil and fuel of all other mods with names later in the alphabet, unless a mod with an earlier name has already registered them.

**Comment by micdoodle8** [comment]
Thanks, that commit should fix it. There's the disadvantage that mods known to add oil and fuel now need to be checked manually. So far I have BuildCraft and PneumaticCraft for oil, and just BuildCraft for fuel. If there are others that cause issues let me know.

**Comment by XFactHD** [comment]
@micdoodle8 pneumaticcraft also adds fuel, although the localized name is gasoline.

**Comment by micdoodle8** [comment]
It shouldn't conflict unless the registry name is exactly "fuel", so gasoline should be fine.

**Comment by lundal** [comment]
PneumaticCraft registers its gasoline as "fuel" to be compatible with other mods, so that will still be an issue. Is there a reason why GalactiCraft can't always use "oilgc" and "fuelgc" to be on the safe side?

**Comment by XFactHD** [comment]
If GC would do that, everybody would complain "your mod is incompatible, fix your mod!".

**Comment by micdoodle8** [comment]
Okay, I've committed the quick fix for the possible "fuel" conflict. I'll investigate better solutions when I get a chance, possibly even changing the oil extraction process for compatibility's sake.

**Comment by 1skandar** [comment]
Actually, you shouldn't have to do that. In fact you SHOULDN'T do that. Yes, technically in new worlds PneumaticCraft oil and fuel is broken if GC loads first, it actually isn't a problem. Mods look to the illiquid registry for whatever fluid they need and use what they fund regardless of what mod it comes from.

This means that if GC loads first, it registers its oil as "oil" and all other mods that try to register "oil" don't. Then all oil in that world that generates or uses oil from whatever source comes from GC. If PneumaticCraft gens oil, it gens GC oil, if it needs oil it uses GC oil.

Existing worlds remember their settings so new mods can't override them, so if a pre GC world was using PneumaticCraft oil it will keep on using PneumaticCraft oil even if GC loads first.

It is true that if you have a world that is using GC as its oil that any PneumaticCraft oil will be unusable, but you also cannot get PneumaticCraft oil in survival, you'd have to spawn it in.

By making GC register its own oil as "oilgc" you can potentially mousetrap someone who isn't careful. Your oil then becomes useless in any machines except your own and if they disable world gen for all other oils they are stuck.

**Comment by 1skandar** [comment]
Note: if you want to test this, a Minecraft instance with COFH, NEI, NEI Integration, PneumatiCraft and Galacticraft is an easy way to see it in action. Go into a creative world and dump the fluid registry (NEI options, Tools, Dumps). It will show what mod is responsible for what fluid. 

Now, if you haven't touched the configs for GC or PC they should both be generating oil. Use NEI to look up the numerical IDs of both PC and GC oil. Then use the cofh clearblocks command to remove each of those IDs in about a 64 block radius. You'll see that only 1 of them will have any blocks to clear despite both mods generating oil in the mod.

Now, if you go abd place some GC oil in creative, you should be able to pick it up in a bucket and place it in a PC refinery. Likewise, the refinery should spit out GC fuel in place of its gasoline.
