### ISSUE TITLE
The fuel Loader causes minecraft to crash when buildcraft is installed.

### ISSUE THREAD

**Issue by LucidityZero** [micdoodle8/Galacticraft#1854]
When I place the fuel loader down when buildcraft is installed. as soon as I click to place, minecraft crashes

**Comment by LucidityZero** [comment]
Strangly enough when buildcraft core and transport is installed the game works fine. but once any other of the modules are added the fuel loader crash happens besides this buildcraft causes no conflicts

**Comment by Alaberti** [comment]
What version of each mod do you have? Do you have a copy of the crash log? Is this in forge or cauldron?

**Comment by micdoodle8** [comment]
I'm going to have to close this, please re-open it if you have the information Alaberti asked for above. (Most importantly the crash report)

**Comment by LucidityZero** [comment]
buildcraft version 7.0.23 with galacticraft core 1.7-3.0.6.232 and planets same numbers

**Comment by LucidityZero** [comment]
srry for such a long wait my internet access is really patchy where I am
