### ISSUE TITLE
Galacticraft/Mekanism wire connections do not work

### ISSUE THREAD

**Issue by Hexicube** [micdoodle8/Galacticraft#1860]
Here's the tested scenarios:

- Connect a MK energy cube directly to a GC machine = works
- Same thing but with MK cables = works
- Same thing but with GC wires = works
- Same thing but with MK cables attaching to GC wires or vice versa = not working

Issue is easily noticed as I want to use the sealed wire for a single block in my cable network, due to the pain of collecting large quantities of wool. The MK cables visibly connect to the GC wires but not the other way around, suggesting that the GC wires aren't properly detecting the cables.

This occurs on MK 8.1.7.252 and GC 3.0.2.357, have yet to test another version of MK.

**Comment by dj3520** [comment]
Galacticraft connecting to wires from other mods via wire-to-wire connections causes lag and is therefore undesirable. As for GC wires connecting to machines this is intended.

**Comment by Hexicube** [comment]
That's besides the point, the only two ways to have sealed wiring is to either only use GC wiring (which is lossy and costs a huge amount of wool) or to have machines always be against the wall that the wire is inside (which isn't always feasible).

There either needs to be support for sealing other cables, or the ability to mix cable types.

**Comment by dj3520** [comment]
Galacticraft can be configured to be lossless for conversions. I'm not
familiar with mekanism much, but if there's a battery block (Like the
energy storage ones for GC) placing that in the wall allows one way
transfers that could be sealed.

**Comment by Hexicube** [comment]
Battery blocks are a fair suggestion, but GC ones only allow horizontal connections and the mekanism ones really shouldn't count as sealed. I mean come on, they're basically a frame with a floating cube of energy...

**Comment by dj3520** [comment]
Either way any wire-to-wire connections are unintentional and should be reported. Your report describes expected behavior.

**Comment by BionicFelps** [comment]
I believe Mekanism wires attempt to connect to multiple other mod wires, this might be something to report to them  and they can either code in an exception for galacticraft wires so the connection isn't made graphically, or find a way to make it work...  I know the wires used to be able to connect to and use IC2, BC, and RF back when all three were different anyway...

**Comment by radfast** [comment]
Galacticraft is behaving correctly.  Wire-to-wire connections between mods are bad, unnecessary and unsightly, and can cause lag.  Galacticraft therefore, by design, does not allow wire-to-wire connections.

If the Mekanism wires are still "looking as though" they connect to Galacticraft cables that is an issue you should ask the Mekanism developers to consider.
