### ISSUE TITLE
Request: Support for Extra Utilities pipe jackets for seal checking

### ISSUE THREAD

**Issue by Hexicube** [micdoodle8/Galacticraft#1861]
Considering the visual appearance of the combination of a pipe jacket and hollow cover (it looks like a solid surface), any block with a hollow cover that also has a pipe jacket should be considered sealable on the surfaces that have the hollow cover (basically treat a hollow cover as a regular cover if there's a pipe jacket).

This would allow for better mod compatibility, as any mod that allows for micro-block covers should also allow the EU jackets (usage info in NEI states it's compatible with any forge multi-part integrated block), and therefore would be sealable.

As an alternative, you could check for the occupation of the central slot of the micro-block structure, since that would be occupied by a pipe or other covered tube of sorts.

**Comment by radfast** [comment]
As covered in the guidance notes for contributors (shown when you created this issue), please make requests on the forum, not here.  Making requests on the forum allows a larger number of other GC players to comment on whether they think it is a good idea or not.

My initial take on this is that this will require too much time to code, for a niche situation.  But I will keep this under advisement.
