### ISSUE TITLE
Fuel Loader Doesnt accept Buildcraft Fluid pipes (SAME AS #1409)

### ISSUE THREAD

**Issue by chezpaul** [micdoodle8/Galacticraft#1863]
I have the same problem that ticket #1409 had.

I'm using gold fluid pipes from Buildcraft into a GC Fuel loader. The fuel stacks up to the loader but doesn't go in. I'm running on the latest GC 357 and Buildcraft 7.1.9 on a KCauldron 1.7.10 1492.155
(Forge 1492). 

I had the same problem with a  GC Refinery in which Oil (using the same gold pipes) would go in the machine fine and Fuel was created but the fuel wouldn't go out of the refinery into the gold pipes.

Seems like this might be part of the same problem maybe?

Pipes do attach but fuel doesn't go in. And yes, the Loader is powered.

**Comment by EzerArch** [comment]
While we are at this. I noticed something changed between GC 351 and 357:

1. If Forge 1291 installed: Refinery doesn't accept Oil. It disappears. 
2. If Forge 1492 installed: Refinery accepts Oil. Okay.
3  If Forge 1492 installed: Fuel Loader's reservoir doesn't accept fuel from Mekanism pipes. The Fuel goes straight from the pipe to the rocket.

**Comment by micdoodle8** [comment]
This is likely fixed in the latest build, I worked on fluid compatibility quite a bit.

Please re-open if the issue persists.

**Comment by chezpaul** [comment]
Well, I can't even login anymore now... Only changed to 360 and I get on server side an error missing some fuel and oil blocks. Okay, I go pass that but after that I can't login the server, I get
[07:54:02 INFO]: chezboutin[/104.xxx.xxx.xxx:52622] logged in with entity id xxxx at ([world] xxxx.9297694270404, 87.0, xxxx.2459958502986)
[07:54:02 INFO]: Sent config to 'chezboutin.'
[07:54:02 WARN]: EnergyNet.addTileEntity: ic2.core.block.wiring.TileEntityCable@c68a32f (ic2.core.block.wiring.TileEntityCable@c68a32f) is still conflicting with ic2.core.block.wiring.TileEntityCable@4a0acf16 using the same position (overlapping), aborting

**Comment by chezpaul** [comment]
Updating to IC2 782 fixes the problem and the pipes now work!
YEAH... thanks a ton.  ;-)

**Comment by chezpaul** [comment]
One more thing.... since I updated to 360 and IC2 782, it literally takes 4 minutes to join my server. As to before  it would take 30 seconds to login. Now I can't say if it's GC or IC2 that changed that. But hey.. just saying... thanks for working on this mod. Great mod. So cool to see your fuel going into your Loader.  ;-)

**Comment by micdoodle8** [comment]
Okay glad to hear you got it working. If you set your client to keep the minecraft console open while the game is running, can you see what's going on in the background when you're connecting for 4 minutes? Usually either a message will be spammed, or it will just stop outputting anything, in which case the message(s) before and after the hang will be useful. Take a look, and if you suspect it's Galacticraft let me know.
