### ISSUE TITLE
Crash (during firework)

### ISSUE THREAD

**Issue by Dream-Master** [micdoodle8/Galacticraft#1864]
I get this crash if i unlock the first vanilla arcivement (during the firework) and the race menu is open.
Galacticraft 3.0.12.359

Is this a Galacticraft issue?

Crash Log:
https://gist.github.com/Dream-Master/d4aeeee0c18c1264f1e1#file-gt

https://github.com/Blood-Asp/GT5-Unofficial/issues/221#issuecomment-146944679

**Comment by micdoodle8** [comment]
I'll attempt a fix, but I'm not sure if it is the source of the issue. Please test out the dev build when it appears, since I don't have an easy way of recreating this.

**Comment by Dream-Master** [comment]
Thanks.  Will test it.

**Comment by Dream-Master** [comment]
I test it and it not crashed. So fixed i think.
Thanks. (used Version 362)

**Comment by Dream-Master** [comment]
@micdoodle8 
Get the same Error i guess with version 365

https://gist.github.com/Dream-Master/4927f90641dda85a7d50#file-gc

**Comment by micdoodle8** [comment]
Does the issue go away without Galacticraft? (not removing other mods such as player api)

**Comment by Dream-Master** [comment]
Will test it and let you know.

**Comment by Dream-Master** [comment]
Tested it several time no crash atm.

**Comment by micdoodle8** [comment]
Okay, so with a bit more research it looks like the problem might be another mod using Player API calling the update method, then Galacticraft calls it normally after. I also backed this up to some degree since I wasn't able to get any crash with just GC, GT5, IC2 and Player API. With your environment, could you remove groups of mods until the problem disappears, that will help to narrow down the possible problematic mod(s).

**Comment by Dream-Master** [comment]
This evening i not get any crash with many different setups of Mods.

**Comment by micdoodle8** [comment]
You're not getting a crash when you unlock the first vanilla achievement on a new world? Could you recreate this crash every time before?

**Comment by Dream-Master** [comment]
no that is is the problem. Some times it crash some times not. 
Yesterday it not crashing with or without galacticraft.
Will test it today again.

**Comment by micdoodle8** [comment]
Any further issues?

**Comment by Dream-Master** [comment]
No crash any more.
