### ISSUE TITLE
New update wipes out Galacticraft oil

### ISSUE THREAD

**Issue by 1skandar** [micdoodle8/Galacticraft#1865]
Updated from 357 to 260 and Forge warned me GC oil was missing. Saved, came in, and, indeed, all GC oil was gone. Because of the fluid conflicts in previous versions this could potentially wipe out all the oil in existing worlds until you explore new chunks.

**Comment by micdoodle8** [comment]
I've added a config option to use the old registration IDs. This should prevent old worlds from losing their oil. Sorry about the wipe, I wasn't aware this would happen. I hope you had a backup :/

**Comment by 1skandar** [comment]
No worries, when Forge warned me that the fluids from Galacticraft were missing I quickly made a back up.

**Comment by katzenpapst** [comment]
Doesn't seem to have worked. At least for me these two options don't do anything. And I'm pretty sure I see the error, too:

B:"Use legacy "oilgc" fluid registration"=true
B:"Use legacy "fuelgc" fluid registration"=true

Too many double quotes. That can't possibly parse.

**Comment by 1skandar** [comment]
Ok, not necessary.GC has retrogen. Set it to true and the old oil does vanish, but the new oil generates in its place. The locations change slightly, but that is acceptable.

**Comment by micdoodle8** [comment]
@katzenpapst I'm not exactly sure how it parses, it's possible that it checks for nested quotes. I've changed it to remove those double quotes anyhow. Also localized the oil and fuel blocks.

**Comment by katzenpapst** [comment]
ok thx, I'll check if it works when I'm home
