### ISSUE TITLE
Gas Liquefier only craftable with filled oxygen tanks

### ISSUE THREAD

**Issue by dj3520** [micdoodle8/Galacticraft#1866]
Not exactly sure if this is intended, but in order to craft the gas Liquefier, the oxygen tanks in the recipe are required to be filled.

**Comment by micdoodle8** [comment]
I didn't create the recipe, but I assume not... since the tanks are empty when you place the block.

**Comment by dj3520** [comment]
Not sure if the commit fixes water electrolysers as well. Or methane
synthesizers.
