### ISSUE TITLE
Nightvision in certain areas cause screen to go black

### ISSUE THREAD

**Issue by artubi** [micdoodle8/Galacticraft#1870]
Tested with:
GalacticraftCore-1.7-3.0.12.358 / 363
Galacticraft-Planets-1.7-3.0.12.358 / 363
MicdoodleCore-1.7-3.0.12.358 / 363

Affected areas:
Overworld - only above y=220
Space station - entire area
Moon - entire area
Asteroids - entire area

The issue:
Using nightvision potion in above mentioned areas causes screen to go black. Except sky, hud and item in hand everything become completely dark.
In overworld, nightvision woks normally in y=200 to 219 even thought sky / fog is getting darker, 220 and above causes same effect as mentioned above.
http://imgur.com/a/8k728
Both pictures were taken with nightvision on.

In overworld, wouldn't be better if sky would get darker above y=256 instead of 200?

**Comment by micdoodle8** [comment]
Does the screen not go black on Mars?

**Comment by artubi** [comment]
No, screen does not get black on Mars while using nightvision.

**Comment by micdoodle8** [comment]
I'm unable to recreate the issue, so it must be a driver difference. Please check with the latest build (394), I've attempted a fix in there.

**Comment by artubi** [comment]
Well... it didn't help. Updated graphic driver didn't help either.

I've had graphical glitches before (even before adding Galacticraft), but they occurred randomly and I didn't know how to trigger them. Ranging from out of place "ghost" bocks/parts of chunks to... well... artifacts...

I mean, if you're telling me that's driver issue and cannot reproduce it alongside with no other reports,
I don't think there is that much can be done. Especially if it is one of those very specific issues. I wanted to use nightvision purely from convenience but.. I guess I could carry more glowstone blocks/torches.

Anyway, I would like to thank you for your effort trying to help me.

**Comment by dj3520** [comment]
Are you using Optifine? If not and you see  textures that are wrong, hold
F3 + T to relax textures manually.

**Comment by artubi** [comment]
Optifine: no
Fastcraft: yes (1.21, only in pack I play)
However, all these reports were done without any of them. Only mods I had was:
CodeChickenCore
NEI
CodeChickenLib
Baubles
FMP
+Galacticraft
Hell, I've even tried Forge+GC only. Same result.

I had graphical issues, but they looked like this:
(note: 35 near 4K pictures)
http://imgur.com/a/rKxmk

**Comment by dj3520** [comment]
I've had this before and forget how I got rid of them. Though I'm sure that
reinstalling Forge will fix this. Just delete everything except mods,
config, saves, and anything else you'd like to keep. Install again and you
should be OK.

**Comment by artubi** [comment]
Disabling fog (via optifine) solves this issue.

**Comment by radfast** [comment]
See also #752.

**Comment by radfast** [comment]
Please check with latest Galacticraft build, I think this should be OK now even if fog is enabled.

**Comment by artubi** [comment]
I confirm that in latest build (433) I can use nightvision in any of the mentioned areas and the screen does not go black.

However:
Screen will go black in overworld above y=220 while using nightvision and the rockets.
proof: (note: very large pictures)
http://imgur.com/a/Asw6u
It happens only when player is flying in rocket with nightvision. I can go above y=220 (as player, not in a rocket) in overworld with nightvision without any issue.
Personally, I won't mind this since it happens only in this scenario.

**Comment by radfast** [comment]
Thank you for spotting that.
Yes, the code I put in to overcome the Night Vision / fog problem is only operating on other dimensions.
I can easily add "in rocket on Overworld above y=220" as well.

**Comment by radfast** [comment]
Your first screenshot is showing another issue - the player's head is outside the rocket, he is not drawn correctly inside the rocket.

Is that first screenshot with PlayerAPI + RenderPlayerAPI?

**Comment by artubi** [comment]
> Your first screenshot is showing another issue - the player's head is outside the rocket, he is not drawn correctly inside the rocket.

(large photos)
http://imgur.com/a/vqUFf
Orange armor - without PlayerAPI, RenderPlayerAPI
Blue armor - with PlayerAPI, RenderPlayerAPI
Using:
latest Galacticraft build 433
PlayerAPI 1.4
RenderPlayerAPI 1.4

I've been flying in circles and it seem that players head is sticking out only in certain direction. It doesn't stick out all the time.
However, RenderPlayerAPI causes entire player to stay in vertical position. So if I tilt the rocket about 90 degrees, player rotation won't change. Removing it fixes the issue.
Player is still visible in that moon landing device (in older versions wasn't).

Also:
http://imgur.com/a/8rmHA
My character turns black after landing in overworld. Unless I move, it'll stay black. Moving forward (or any direction) fixes it.

**Comment by radfast** [comment]
Thank you, very helpful.

**Comment by EzerArch** [comment]
> My character turns black after landing in overworld. Unless I move, it'll stay black. Moving forward (or any direction) fixes it. 

This glitch was worse and perhaps related to this: #784 (notice item 4 under "How to reproduce")

> Your first screenshot is showing another issue - the player's head is outside the rocket, he is not drawn correctly inside the rocket.

Related? https://github.com/micdoodle8/Galacticraft/issues/1963#issuecomment-174344829

----

Sometimes bugs like this come in handy.

![pic](https://pbs.twimg.com/media/CPo8iJoWEAA7Upw.png:large)
([tweet](https://twitter.com/EzerArch/status/646896054856773632))
