### ISSUE TITLE
Galacticraft crashes before the game even launches!!

### ISSUE THREAD

**Issue by stmacl** [micdoodle8/Galacticraft#1873]
I wanted to test Galacticraft out before I added any more mods and it crashed out before I could do so. Won't even go to the main menu.

http://pastebin.com/KtQ7kQ5K

**Comment by micdoodle8** [comment]
```FileNotFoundException: C:\Users\Stephen\Documents\Curse\Minecraft\Instances\TO SPACE!!```
This is probably the issue, since I've never used curse client before, is "TO SPACE!!" a profile name?

**Comment by dj3520** [comment]
To add to micdoodle, I'd also take out the exclamation points.
