### ISSUE TITLE
Machines cannot store energy and liquids

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#1879]
Most of machines can't store energy and liquids in their internal tanks/batteries, unless if you manually place them with canisters and batteries.

Energy setup:
![2015-10-13_03 16 12](https://cloud.githubusercontent.com/assets/6743303/10447197/f27d8bbc-7158-11e5-9cfd-088ed97c1dc7.png)
![2015-10-13_03 16 20](https://cloud.githubusercontent.com/assets/6743303/10447199/f2857ca0-7158-11e5-8b26-6bea38f0c5a2.png)
![2015-10-13_03 16 36](https://cloud.githubusercontent.com/assets/6743303/10447198/f27e1816-7158-11e5-9cc2-3ca3900edad6.png)

Fuel setup (with Mekanism pipes):
![2015-10-13_03 36 36](https://cloud.githubusercontent.com/assets/6743303/10447543/b1f4364c-715b-11e5-9876-dc931c1e7a9a.png)
![2015-10-13_03 36 49](https://cloud.githubusercontent.com/assets/6743303/10447545/b1f8d8d2-715b-11e5-94da-67b1de2398c4.png)
![2015-10-13_03 36 54](https://cloud.githubusercontent.com/assets/6743303/10447544/b1f6eb30-715b-11e5-9e0d-23d902c507ce.png)

Mod used:
Forge 1448
[1.7.10]bspkrsCore-universal-6.16.jar
[1.7.10]ArmorStatusHUD-client-1.28.jar
[1.7.10]DirectionHUD-client-1.24.jar
[1.7.10]StatusEffectHUD-client-1.27.jar
[1.7.10]DamageIndicatorsMod-3.2.0.jar
journeymap-1.7.10-5.1.0-unlimited.jar
CodeChickenCore-1.7.10-1.0.4.29-universal.jar
NotEnoughItems-1.7.10-1.0.3.74-universal.jar
Galacticraft-Planets-1.7-3.0.12.365.jar
GalacticraftCore-1.7-3.0.12.365.jar
MicdoodleCore-1.7-3.0.12.365.jar
Mekanism-1.7.10-8.1.7.252.jar
MekanismGenerators-1.7.10-8.1.7.252.jar
MekanismTools-1.7.10-8.1.7.252.jar

**Comment by micdoodle8** [comment]
Hmm, did this break in the last couple builds?

**Comment by EzerArch** [comment]
351 was okay. Probably it's something ranging from 357 and 365, as I said here: https://github.com/micdoodle8/Galacticraft/issues/1863#issuecomment-146752646.
