### ISSUE TITLE
[Bug] New System Space Station [Build 367]

### ISSUE THREAD

**Issue by BlesseNtumble** [micdoodle8/Galacticraft#1880]
Create stations works perfectly, but here is a map of the bug:
On the planet that can not fly - a window appears creation of space station.
![1](http://6.firepic.org/6/images/2015-10/13/4zydguv5rmgh.png)
![2](http://6.firepic.org/6/images/2015-10/13/lei9gwj1r1b8.png)
![3](http://6.firepic.org/6/images/2015-10/13/7cmb305sy8yi.png)

I disabled addon GalaxySpace that there was no suspicion of crooked code addon.

On this.mapMode and on !this.mapMode works equally bug.

**Comment by Dream-Master** [comment]
@BlesseNtumble 
With your Mod installed (version 2.5fix and newst Galacticraft Version 368) this crash i get. I think @micdoodle8 change a lot.
https://gist.github.com/Dream-Master/ac4176436a3265c9dbb4#file-gs

**Comment by BlesseNtumble** [comment]
Because it was 2.5 for the preform station of the old system.
Therefore, the crash.

**Comment by Dream-Master** [comment]
Yes i know. I only whant to say it to you. It is not a complain.
