### ISSUE TITLE
Server crashing with MicdoodleCore

### ISSUE THREAD

**Issue by tyman09** [micdoodle8/Galacticraft#1881]
when i launch my server with all of the galacticraft files it crashes almost instantly. For some reason i couldn't attach the log file.

**Comment by halvors** [comment]
What version? You have to use pastebin.com or something and post the link here.

**Comment by tyman09** [comment]
1.7.10 latest 
http://pastebin.com/EXtdnrFm

**Comment by dj3520** [comment]
Have you tried redownloading?

**Comment by tyman09** [comment]
yes

**Comment by micdoodle8** [comment]
Try the latest build. It will not fix the issue, but the log will show a bit more information as to what's going on. If you could paste the new log after trying the new build that would be great. The likely issue is that the Dependency Loader in MicdoodleCore tries to create a subdirectory in the minecraft mods folder (.minecraft/mods/1.7.10 for example), but without read/write access this will fail.

**Comment by tyman09** [comment]
here is the new log
 http://pastebin.com/tLDj8bC8

**Comment by micdoodle8** [comment]
Okay so yeah, the client couldn't create "/home/minecraft/multicraft/servers/Default Server/./mods/1.7.10" 

I'm no Linux expert, but the client needs run with sudo as far as I know, you shouldn't get this error with admin privileges on the multicraft client.

**Comment by tyman09** [comment]
do you know of a way to run the server on sudo through something like putty?

**Comment by micdoodle8** [comment]
How are you running the server right now? Via command line?

**Comment by tyman09** [comment]
im using a simplexservers vpn and im running the server through multicraft but i have access to the command line.

**Comment by micdoodle8** [comment]
Try ```sudo java -Xmx1024M -Xms1024M -jar minecraft_server.jar nogui``` replacing minecraft server.jar with the jar you're using.

**Comment by tyman09** [comment]
it seems to have worked thanks so much, but how do i stop it?

**Comment by tyman09** [comment]
never mind, Thanks for all of the help and quick responses!

**Comment by micdoodle8** [comment]
No problem, glad you got it working.
