### ISSUE TITLE
Request: Reduced oxygen usage for sealers

### ISSUE THREAD

**Issue by Hexicube** [micdoodle8/Galacticraft#1882]
As it stands, the bubble generator is massively better in terms of oxygen consumption (160/s for a large bubble, would take 4 sealers at 320/s each to match, so 8x better) and also lacks the issue of needing air-locks. There's currently no reason to use a sealer over a bubble generator, and it's absurd that a vacuum-exposed bubble of air dissipates more slowly than a sealed room containing air, especially since the blocks sealing it are more-or-less air-tight.

Considering the need for an air-tight room is a down-side to using a sealer, could the oxygen requirement be dropped so that it's more efficient than a bubble generator for the same volume? Maybe something in the region of 30/s, which would make it a little better than a bubble generator (120/s vs 160/s for same volume) in exchange for needing an air-tight room.

**Comment by micdoodle8** [comment]
Okay, I see your point. I've decided to reduce the oxygen required by sealers, but not as low as 30/s. I chose 120/s, because although the sealer requires the room to be sealed, there is still a huge advantage in that the oxygen fills all blocks in the room, whereas the bubble distributor is a static shape. This is still a very large reduction, over 2.5x lower than before.

**Comment by Hexicube** [comment]
Would it be possible to have this tweakable via config, since it's only a single value in the code?

**Comment by dj3520** [comment]
I see two possibilities here for interesting additions. One is that the oxygen requirement changes depending on the space that is sealed (I've seen that a count for blocks sealed is done via debug mode.) Other is only using oxygen if there's a living entity in the space (with possible "always drain" value.) The latter would be a big advantage over the oxygen bubble, where it makes sense the oxygen goes away even if not breathed in (dissipation.)
