### ISSUE TITLE
getStackTrace() in MaterialOleaginous can stall the game

### ISSUE THREAD

**Issue by sk89q** [micdoodle8/Galacticraft#1885]
We've had problems with `Thread.currentThread().getStackTrace()` in [MaterialOleaginous](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/blocks/MaterialOleaginous.java#L25) stalling our server, sometimes up to 30 seconds, presumably during large flows.

Now I understand the reason for the code, but both `Thread.currentThread()` and `getStackTrace()` are pretty slow. You can cut down the time a bit with `new Exception().getStackTrace()`, but it's still slow.

**Comment by micdoodle8** [comment]
If you're still getting issues after the latest change, let me know and I'll add a config option to disable the flow blocking.

**Comment by Builderb0y** [comment]
Not sure about sk89q, but I definitely am still having issues with it, as my (duplicate) issue states.

**Comment by sk89q** [comment]
I disabled the flow blocking in our version when I reported this issue and admittedly never looked back. All our GC oil also disappeared with a GC update anyway, so we only had PC oil gen (and then we disabled GC oil gen), which was less confusing for players too because you can't pick up GC oil with bucket or something if I remember correctly.
