### ISSUE TITLE
Pressing shift dismounts you from rocket during flight, resulting in great losses

### ISSUE THREAD

**Issue by BBoldt** [micdoodle8/Galacticraft#1888]
http://forum.micdoodle8.com/index.php?threads/shift-should-not-automatically-dismount-when-you-are-in-a-rocket-launching-to-space.5359/

I initially posted this in the suggestions section of the forum, but to me it feels more like a proposed solution to a problem than a suggestion. So I am posting the problem here as an issue due to the thread getting buried.

**Comment by dj3520** [comment]
Pretty sure this is already implemented

**Comment by BBoldt** [comment]
As in there is something now preventing you from accidentally pressing shift in a rocket and losing everything?

**Comment by EzerArch** [comment]
> As in there is something now preventing you from accidentally pressing shift in a rocket and losing everything?

I tested it wih GC 375, neither Shift or right-click should dismount you from a rocket. But right-clicking still dismounts you from Landing Balloons and Landers, **this should also be disabled**. As to Landers, if you dismount them while descent procedure, they stop "midair".

![2015-10-17_19 31 08](https://cloud.githubusercontent.com/assets/6743303/10561583/f3a7f18e-7505-11e5-8b3a-48379fda6799.png)

**Comment by BBoldt** [comment]
Well, I'm glad the rocket dismount thing is fixed, but yeah that lander thing looks like a problem too.

You really shouldn't be able to dismount anything that isn't safely landed.

**Comment by micdoodle8** [comment]
The lander issue is fixed with 2447e08783cde0b9f7e57a05731b20e7a0748307

**Comment by BBoldt** [comment]
@micdoodle8 

Galacticraft 402:
https://dl.dropboxusercontent.com/u/134976541/ShareX/2015-11/2015-11-02_23-47-46.mp4

I launched the rocket, and pressed the shift key mid flight, resulting in me plummeting to the ground and the rocket flying away. This is what I'm talking about. There should be at least a warning, in the same way you need to "confirm the launch" in the beginning.

```
Abort? This will likely result in loss of rocket. If I press dismount again, there is no going back!
```

**Comment by EzerArch** [comment]
O_O'...

Just tested GC 402 with Tier 1, 2 and 3 rockets, on the overworld dim: Dismounting by shift key is disabled.

Must be something else affecting.
