### ISSUE TITLE
Incorrect display on the planets.

### ISSUE THREAD

**Issue by Tsyklop** [micdoodle8/Galacticraft#1891]
Installed(Only Mods that add something to the display) :
IC2 Backpack HUD
InGameInfoXML
EnviroMine
Galacticraft-1.7-3.0.12.375
200+ mods.

And when I go to Mars, then I go out like this here:
If you look up in the air:
![2015-10-18_00 56 16](https://cloud.githubusercontent.com/assets/6783568/10561540/6109bdd2-7535-11e5-8595-7b393df0aaba.png)

If you look at the blocks.
![2015-10-18_00 56 12](https://cloud.githubusercontent.com/assets/6783568/10561542/6b7779bc-7535-11e5-8bc7-43b10ee2234c.png)

**Comment by EzerArch** [comment]
Possibly related to #1524 and #1532.

**Comment by Tsyklop** [comment]
@EzerArch and? I looked through everything. But there is nothing like that.

**Comment by EzerArch** [comment]
> and?

Just showing similar bugs, it *may* help devs in the debug process. We had some lighting bugs that caused texts to lose color just by hovering the mouse pointer on some entities/blocks on screen.

**Comment by Tsyklop** [comment]
@EzerArch Okey

**Comment by micdoodle8** [comment]
Sorry for the spam. I'm not exactly sure what's going on here any more. I debugged the OpenGL state and after the last commit there is no change between when the sky renderer is started to when the sky renderer method exits.
