### ISSUE TITLE
Incorrect mcmod.info

### ISSUE THREAD

**Issue by DarkLeach7** [micdoodle8/Galacticraft#1893]
While not affecting the actual mod gameplay, this did confuse me when I was updating this mod for a modpack. The mcmod.info in version 3.0.12.375 of Galacticraft Core (the recommended download) is for the Crossbow Mod 2 version 0.2.13..

**Comment by MJRLegends** [comment]
Yep i have noticed this too

**Comment by dj3520** [comment]
Is micdoodle core like this too? Think I saw it there.
