### ISSUE TITLE
Unwanted energy conversions

### ISSUE THREAD

**Issue by leagris** [micdoodle8/Galacticraft#1894]
Sometimes it is undesirable to have GC convert energy upstream like see:
[Beyond Reality mod-pack issue #290 "Other think for convert rf to eu"](Beyond-Reality/BeyondRealityModPack#290)

I tried to fiddle with conversion ratios and loss% but it look like `power-GC3.conf` content is ignored:
```YAML
# Configuration file

compatibility {
    D:"BuildCraft Conversion Ratio"=16.0
    B:"Disable old Buildcraft API (MJ) interfacing completely?"=true
    D:"IndustrialCraft Conversion Ratio"=6.557376861572266
    I:"Loss factor when converting energy as a percentage (100 = no loss, 90 = 10% loss ...)"=0
    D:"Mekanism Conversion Ratio"=0.6557376980781555
    D:"RF Conversion Ratio"=0
}
```

Part of the issue could be with GC forcing maximal conversion loss at 95% with min value 5 at:
https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/energy/EnergyConfigHandler.java#L128

What we would need please:
- A mean to disable specific energy type on input (example disabling RF altogether)
- A mean to disable specific energy type output.
- Or implement disabling energy conversions

**Comment by micdoodle8** [comment]
That should hopefully be the change you're looking for. This is not very easy for me to test at the moment, so let me know if there are further issues. Thanks.
