### ISSUE TITLE
Problem creating a space station on my addon!!!

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft#1895]
I trying to make a space station for a planet,

I am able to make the recipe and the creation of the space station work
![](https://i.gyazo.com/a4484d794965ed69e9500ec0359e9785.png)

But when i try and launch to this space station i get 
"java.lang.IllegalArgumentException: Could not get provider type for dimension -256, does not exist" 

Here is the main code
http://pastebin.com/6UNG8TYS

Let me know if you need to see any of the classes code.....

I would be really grateful if someone could help me out here :D

**Comment by micdoodle8** [comment]
What's the full stack trace?

**Comment by MJRLegends** [comment]
http://pastebin.com/vzEcD4pQ

**Comment by micdoodle8** [comment]
Why does that one say ```dimension 65376```? Did you change it since the original post?

**Comment by MJRLegends** [comment]
Yeah i was messing around changing it to see if it made a difference but still no the paste-bin link has been updated with the correct id now

**Comment by micdoodle8** [comment]
I'm building a 'debug' version. Run the game with this and then paste the full log for me please (using pastebin).

**Comment by MJRLegends** [comment]
ok where will i download this version?

**Comment by MJRLegends** [comment]
http://pastebin.com/8zq6WK3J

**Comment by micdoodle8** [comment]
Can I have a paste of your main mod class? I need to see where each call made in http://pastebin.com/6UNG8TYS is made.

**Comment by MJRLegends** [comment]
here is it 
http://pastebin.com/PrgaLvJ7
the function in this class called init() is being called in the FMLInitializationEvent in the main mod class

**Comment by micdoodle8** [comment]
Ah, I think the issue is in WorldProviderJupiterOrbit. This should be the last thing I need to see :)

**Comment by MJRLegends** [comment]
Ok http://pastebin.com/7V632Ppv

**Comment by micdoodle8** [comment]
Yeah, you're setting the dimension IDs to -256 there. -256 is the provider ID, the dimension ID needs to be automatically set by the ```setDimension(int id)``` method. Does it work if you just copy the WorldProviderOrbit class into there and don't change anything.

**Comment by MJRLegends** [comment]
let me give this a try

**Comment by MJRLegends** [comment]
if i use WorldProviderOrbit class i get
this http://pastebin.com/j9pXqRey
and if i let the setDimension(int id) method set the id i get this
http://pastebin.com/S07L4G18

**Comment by micdoodle8** [comment]
The error when you let the setDimension(int id) method set the id is caused by getCelestialBody being null.

**Comment by MJRLegends** [comment]
But its not null?

**Comment by micdoodle8** [comment]
You need to debug in your IDE to figure out why it's null.

**Comment by MJRLegends** [comment]
Sorted it

**Comment by MJRLegends** [comment]
But now my console is being spammed with http://pastebin.com/RdtQdnya when ever i go to a custom space station or the overworld space station in galacticraft core. Also i have found another bug in which when you travel to a space station sometimes you cant use shift to go down or space to go up but i can use WSAD keys to move.

**Comment by micdoodle8** [comment]
I fixed the console spamming, but the other issue needs to go in a separate report.

**Comment by BlesseNtumble** [comment]
![1][https://pp.vk.me/c624318/v624318755/4333a/bhMQ6v8xRqc.jpg]
All works.
