### ISSUE TITLE
Tin Ingot not registered as ingotTin in the oreDictionary.

### ISSUE THREAD

**Issue by WolfAmaril** [micdoodle8/Galacticraft#1897]
(not registered as anything in the oreDictionary)

Makes building space stations impossible unless you have something else that adds tin.

**Comment by micdoodle8** [comment]
What are you seeing that makes you think it's GC? I am 99% sure the tin ore dictionary registration is working fine.

**Comment by WolfAmaril** [comment]
it is possible that my oreDictionary borked up somewhere, but I've got two mods active that show the oreDictionary names in the item's description in NEI, and of the 5+ types of Tin I have yours is the only one that doesn't say "ingotTin" on it.

That and when I tried to use it to make a space-station I was told "you don't have any tin."

**Comment by micdoodle8** [comment]
It's kind of a pain, but could you remove all the mods except GC and the mods that show the oreDictionary names, and see if it's registered properly? Another mod might be doing something funky with the ore dictionary.

**Comment by WolfAmaril** [comment]
Having Disabled all mods except for Galacticraft, my suite of NEI addons (needed to show oreDictionary names), and the required coremods:

Galacticraft (as of version 1.7-3.0.12.375) does not register a Tin Ingot as ingotTin.

**Comment by micdoodle8** [comment]
Okay, I've added some debug output for this issue in build 385. Try that one, and then paste the whole client log in pastebin. Should help me find out what's going on, thanks.

**Comment by WolfAmaril** [comment]
So I installed 385 in a completely fresh instance with nothing but MicdoodleCore, Galacticraft Core|Planets, NEI, CCC, and NEI Intigration (the one with the oreDictionary option).

Not only is Tin not registered with the oreDictionary, but neither are Copper, Aluminum, or Metioric Iron. Desh and Titanium are registered as ingotDesh and ingotTitanium respectively.

[Complete log can be found here] (http://pastebin.com/4NbaKf0D)

**Comment by micdoodle8** [comment]
Look at line 521 in that pastebin link, you can see it was registered successfully. I checked with those mods and it's working for me, so try a different forge version (I'm using 1448).

**Comment by WolfAmaril** [comment]
Huh, strange.

Well, given that there's not bug in your code, and I've got like 7 different versions of ingotEverything runnign around, I'm a call this one closed.
