### ISSUE TITLE
Issue https://github.com/micdoodle8/Galacticraft/issues/1664 has not been fixed about 6 months

### ISSUE THREAD

**Issue by Krysinski** [micdoodle8/Galacticraft#1901]
Issue https://github.com/micdoodle8/Galacticraft/issues/1664 has not been fixed about 6 months.
Its a dangerous bug:
If you fill certus tank from ExtraCells mod with untextured gases (https://github.com/micdoodle8/Galacticraft/issues/1664) you get "already tesselating" error and crash client.
You cant connect to server more, you will getting crash. World will be broken for you then.

**Comment by XFactHD** [comment]
Did you try to reproduce it with other tanks? If other tanks do not have this problem with untexured fluids, then this is a bug in ExtraCells. Also, are you using Optifine?

**Comment by Krysinski** [comment]
There is still no textures( 
But now there is more missing textures on items (cells, universal fluid cells)
Please reopen this issue

**Comment by micdoodle8** [comment]
#1664 has been re-opened, we don't need more than one issue for the same bug. I'll be looking at this later, I can re-create the issue so it shouldn't be too difficult.
