### ISSUE TITLE
No Spawn Egg for Galacticraft mobs

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#1903]
![2558-10-21_17 09 03](https://cloud.githubusercontent.com/assets/6128413/10635673/bda90786-7824-11e5-8758-f7ec21d29aeb.png)

I think this is a problem. (Maybe)
https://github.com/micdoodle8/Galacticraft/commit/a74341455dc06373bc80266ff475d6ba152c58e1

**Comment by Adaptivity** [comment]
Yeah, probably. @micdoodle8 you should add spawn eggs manually. An example how to do this: https://github.com/GirafiStudios/Atum/commit/a325f7f7e485d43553d041f693b524c84e5419f8
