### ISSUE TITLE
Snow in Space?

### ISSUE THREAD

**Issue by Niels2012** [micdoodle8/Galacticraft#1904]
okay, so I found this bug in Galacticraft 3.0.11.333 where if it rains in the overworld and you leave with a rocket, it snows at the moment where you can look down on the earth, now I don't know if this problem is fixable or not, but it is a problem, here are some screenshots:
![2015-10-21_14 24 05](https://cloud.githubusercontent.com/assets/14995338/10636395/dc2ca502-77ff-11e5-8960-b3de6283a386.png)
![2015-10-21_14 24 07](https://cloud.githubusercontent.com/assets/14995338/10636396/dc309d9c-77ff-11e5-90a5-87a8c0a2f59f.png)

**Comment by SteveKunG** [comment]
@micdoodle8 Already fix it.
Please using build 378 : http://ci.micdoodle8.com/job/Galacticraft-1.7/378/

**Comment by Niels2012** [comment]
thanks, and if I made a mistake or something like that, sorry for that

**Comment by EzerArch** [comment]
@Niels2012 , no problem, just be sure you're using the latest version to confirm if the bug is still present before reporting. :)
