### ISSUE TITLE
Fuel loader does not accept fuel from pipes

### ISSUE THREAD

**Issue by dragon-dreamer** [micdoodle8/Galacticraft#1906]
Probably the same as #1863 and #1409.

Fuel loader does not accept fuel from any pipes (tried Thermal Dynamics fluiducts, golden pipes and wooden pipes with engine from buildcraft). However, it accepts energy from Thermal Expansion fluxducts. Refinery works with all kinds of pipes (fluid end energy) well.

Tried both 375 and 392 Galacticraft builds.

As you can see, the pipe is full, but the fuel loader is empty:
![bug1](https://cloud.githubusercontent.com/assets/11682915/10701449/3c923862-79cc-11e5-91b2-ca7c21dfa7a2.png)
![bug2](https://cloud.githubusercontent.com/assets/11682915/10701461/46be9e84-79cc-11e5-8585-47a0718dffad.png)

Running on forge-1.7.10-10.13.4.1448. Buildcraft is 7.1.11, Thermal Dynamics is 1.1.0-161.

**Comment by dragon-dreamer** [comment]
Probably this is essential: I have these options set to true:

`    # Set to true to make Galacticraft oil register as oilgc, for backwards compatibility with previously generated worlds.`
`    B:"Use legacy oilgc fluid registration"=true`

`    # Set to true to make Galacticraft fuel register as fuelgc, for backwards compatibility with previously generated worlds.`
`     B:"Use legacy fuelgc fluid registration"=true`

I had to turn them on as I've recently upgraded Galacticraft from 357 build, and forge asked me to remove all oil and fuel from the world, which I wanted to keep.

**Comment by dragon-dreamer** [comment]
Well, setting `B:"Use legacy fuelgc fluid registration"` to `false` fixed the issue. But probably the fuel loader should work with both option values.

**Comment by micdoodle8** [comment]
Thanks for the detailed report, made for a really quick fix.

**Comment by andrewminer** [comment]
For future Googlers who may land here... I thought I had this problem too until I realized that I had faced the fuel port (the yellow circle) toward my launch pad.  That, of course, meant it was impossible to also place a fuel pipe facing that direction!

**Comment by radfast** [comment]
good call, @andrewminer  - see #2435
