### ISSUE TITLE
World Crashes, cant find reason

### ISSUE THREAD

**Issue by ZachariaLeAngel** [micdoodle8/Galacticraft#1907]
Hi, my name is Kenneth, and I've recently downloaded Galacticraft. I love playing it but I've run into issues with the newest release of it. For some reason, the world I play on will log me out as soon as it's loaded. I'll see maybe a second of the game, 5 or more seconds if I'm lucky, but the end result is the same: it logs me out saying the a fatal error has occurred, and then instead of kicking me to the title screen or the singleplayer world screen, it kicks me to the multiplayer screen and starts searching for servers. I dont know why this is, but after downloading the new update and replacing the old mod files with the new ones, its been giving me this problem. The problem didnt actually occur until my astrominers powered up, and during one of the periods where it didnt log me out immediately, one of the miners was stuck sideways in its base, and the game did not register any of the three miners as being there. I assume this may have something to do with this but I dont know what exactly, so I'm hoping somebody here can figure this out.
Enclosed is the link to the pastebin site where the latest logs for this crash can be found. If any additional information is needed, please contact me though my email, whic im hoping is posted with my profile. Thanks!
~Kenny
http://pastebin.com/VspkENmu

**Comment by ZachariaLeAngel** [comment]
There was something i forgot to mention. If i create another world, load it, then quit that world and delete it, then load up my world, it works fine for a while but after some time passes, usually about 5 or so minutes, it will do the same thing again. Dont know if this helps any

**Comment by micdoodle8** [comment]
Hey, I believe this is fixed in the latest build (392). Let me know if that fixes it.
