### ISSUE TITLE
Ticking entity

### ISSUE THREAD

**Issue by mightydanp** [micdoodle8/Galacticraft#1911]
im on the latest version of Galacticraft and the bug is related to Galacticraft is ther e any chance of fexing it ?

net.minecraft.util.ReportedException: Ticking entity
[B#333]  	at net.minecraft.world.World.func_72939_s(World.java:1902) ~[ahb.class:?]
[B#333]  	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006) ~[bao.class:?]
[B#333]  	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) ~[bao.class:?]
[B#333]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
[B#333]  	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
[B#333]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
[B#333]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
[B#333]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
[B#333]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
[B#333]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
[B#333]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[B#333]  Caused by: java.lang.ArrayIndexOutOfBoundsException: -103
[B#333]  	at net.minecraft.potion.PotionEffect.func_76455_a(PotionEffect.java:105) ~[rw.class:?]
[B#333]  	at net.minecraft.entity.EntityLivingBase.func_70679_bo(EntityLivingBase.java:524) ~[sv.class:?]
[B#333]  	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:293) ~[sv.class:?]
[B#333]  	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:318) ~[sa.class:?]
[B#333]  	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1561) ~[sv.class:?]
[B#333]  	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288) ~[yz.class:?]
[B#333]  	at net.minecraft.client.entity.EntityPlayerSP.localOnUpdate(EntityPlayerSP.java) ~[blk.class:?]
[B#333]  	at api.player.client.ClientPlayerBase.onUpdate(Unknown Source) ~[ClientPlayerBase.class:?]
[B#333]  	at micdoodle8.mods.galacticraft.core.entities.player.GCPlayerBaseSP.onUpdate(GCPlayerBaseSP.java:68) ~[GCPlayerBaseSP.class:?]
[B#333]  	at api.player.client.ClientPlayerAPI.onUpdate(Unknown Source) ~[ClientPlayerAPI.class:?]
[B#333]  	at api.player.client.ClientPlayerAPI.onUpdate(Unknown Source) ~[ClientPlayerAPI.class:?]
[B#333]  	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java) ~[blk.class:?]
[B#333]  	at net.minecraft.client.entity.EntityClientPlayerMP.func_70071_h_(SourceFile:63) ~[bjk.class:?]
[B#333]  	at net.minecraft.world.World.func_72866_a(World.java:2070) ~[ahb.class:?]
[B#333]  	at net.minecraft.world.World.func_72870_g(World.java:2034) ~[ahb.class:?]
[B#333]  	at net.minecraft.world.World.func_72939_s(World.java:1887) ~[ahb.class:?]
[B#333]  	... 10 more

**Comment by micdoodle8** [comment]
The bug doesn't appear to be related to GC. Although it passes through the GC player's update method, the crash is caused by potion effects, which this mod does not change at all.

More information at the end of the following report: https://github.com/MinecraftForge/MinecraftForge/issues/1695
