### ISSUE TITLE
[Feature Request] Register oxygen gas with forge

### ISSUE THREAD

**Issue by Silly511** [micdoodle8/Galacticraft#1913]
Then other mods like extra cells could interact with oxygen.

**Comment by XFactHD** [comment]
The oxygen gas is not a fluid, therefore it can only be handled by the oxygen pipes, but GC has a machine called a gas liquefier which can turn oxygen into liquid oxygen and the other way around. Liquid oxygen is a forge fluid and can be stored with ExtraCells or any other liquid storage.

**Comment by dj3520** [comment]
Technically the gas is also registered as a fluid. Buildcraft fluid pipes
can move it around. Same with hydrogen gas.

**Comment by micdoodle8** [comment]
Since the definition of a fluid is ```a substance that has no fixed shape and yields easily to external pressure; a gas or (especially) a liquid.``` all gases in the mod are registered in the forge Fluid Dictionary. If there is a specific incompatibility somewhere, let me know.

**Comment by dj3520** [comment]
I hate to point this out, but water in it's liquid state takes up a defined
volume of space.  This is what defines it as a liquid. A gas, while sharing
the "shapeless" attribute, doesn't take up a certain space since it's
easily compressed.

**Comment by XFactHD** [comment]
@dj3520 ok, didn't know BC number pipes could handle oxygen.

**Comment by Silly511** [comment]
If BC pipes can handle oxygen then why can't extra cells interact with it?
