### ISSUE TITLE
Slimeling ownership issues

### ISSUE THREAD

**Issue by dragon-dreamer** [micdoodle8/Galacticraft#1914]
I have the same problem as #1450: The sit/stay button in the slimeling GUI is disabled, I can't rename it (I can only add letters to name, but not remove).

Galacticraft: 392 build.
Running on forge-1.7.10-10.13.4.1448.

![bug3](https://cloud.githubusercontent.com/assets/11682915/10729226/16c19cc0-7bf9-11e5-8f8d-6610ff5f5645.png)

I'm playing on my local server with `online-mode=false` option in my server.properties file, my minecraft client don't check my credentials online, too. This is probably the reason of this ownership problem.

**Comment by micdoodle8** [comment]
Do you have the exact username that the "Owner" indicator shows? In the case of this screenshot, are you having issues while using the username "Hardcore"?

**Comment by dragon-dreamer** [comment]
Yes, this is my exact username, I'm the only player on my own local server (which is running on my computer).

**Comment by micdoodle8** [comment]
Can you re-create the issue on a single-player world?

**Comment by dragon-dreamer** [comment]
On single-player everything is fine.

**Comment by dragon-dreamer** [comment]
Here is the log: https://www.sendspace.com/file/mo9a70
21:06 - I log in, put yellow slimeling egg on the ground, destroy it with pickaxe, then the issue is reproduced. Unfortunately, nothing special at this time in the log (Galacticraft debug mode is on).

**Comment by dragon-dreamer** [comment]
Seems that other mods don't have any issues with ownership (for example, chunk loader from ChickenChunks works fine).

**Comment by micdoodle8** [comment]
Hmm, well ChickenChunks uses player username for ownership. I forgot that I was using UUIDs for ownership, so players that change their username through Mojang and still have their slimeling ownership. 

Vanilla wolves are using a very similar method. Are you able to tame and control them correctly on the server?

**Comment by micdoodle8** [comment]
So I've attempted a fix, if build 400 doesn't work, please re-open the issue.

**Comment by dragon-dreamer** [comment]
The fix worked, thank you!

And yes, vanilla wolves are working fine (I mean taming and controlling them).
