### ISSUE TITLE
Moon buggy model is duplicated on removal

### ISSUE THREAD

**Issue by dragon-dreamer** [micdoodle8/Galacticraft#1916]
1. Place the moon buggy on the ground:
![bug4](https://cloud.githubusercontent.com/assets/11682915/10768112/8e02a4e4-7cf0-11e5-8c4d-e4f13d83c68a.png)

2. Push it with hand. Two items will appear, but you can pick up only one, the second one is actually ghost model.
![bug5](https://cloud.githubusercontent.com/assets/11682915/10768117/93637012-7cf0-11e5-8922-e795737dd816.png)
![bug6](https://cloud.githubusercontent.com/assets/11682915/10768137/a30969d6-7cf0-11e5-80a3-416a780d72db.png)
![bug7](https://cloud.githubusercontent.com/assets/11682915/10768139/a6152a98-7cf0-11e5-95ef-0f1224ba947f.png)

This ghost item spawns both on single and multiplayer and disappears after re-login to the server (multiplayer) or reloading the world (single-player).

Galacticraft: build 392;
Forge: 1.7.10-10.13.4.1448.

**Comment by dj3520** [comment]
Having the same issue on my server.
