### ISSUE TITLE
Suggestion for API

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft#1917]
Please can we have hooks in the API to make our own thermal padding and oxygen equipment like oxygen tanks/mask, as i have a cool idea for my addon but its not possible because the thermal padding and oxygen equipment are all hard-coded within galacticraft.

**Comment by BlesseNtumble** [comment]
For thermal armor to do protection levels.
For example: a standard armor gives protection only between -2 and +2 temperature level.
And already from the add-on will give a +3 and -3.
This will fly to distant planets with great realism.
So how to make more sustainable suit.

**Comment by micdoodle8** [comment]
Changing the solar system registration hierarchy is too large of a change right now. I'll look into changing this for the next major GC version.

**Comment by MJRLegends** [comment]
I would like it if we was able to make custom oxygen masks and tanks :P
