### ISSUE TITLE
Registering Biomes with Forge

### ISSUE THREAD

**Issue by jimcarreer** [micdoodle8/Galacticraft#1919]
Currently I work on a [Mod adding ambient sounds](https://github.com/Ambiotic/Ambiotic)  to different Minecraft environments.  You add new Biomes like "moon" and "mars" , however I don't believe that you  register these with the [BiomeDictionary](https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/common/BiomeDictionary.java) in forge.  Specifically I key off of "BiomeType" values to estimate the type of ambient sounds appropriate to the user's environment.

Some suggestions for the BiomeTypes to register:
* Moon
 * COLD
 * DRY
 * DEAD
 * SPOOKY (maybe?)
* Mars
 * COLD
 * DRY
 * DEAD
 * SANDY
 * SPOOKY (maybe?)
* Venus
 * HOT
 * DRY
 * DEAD
 * SANDY
 * SPOOKY (maybe?)

In particular the DEAD tag will let my Mod know it's not appropriate to play "animal" sounds on Mars/Venus/Moon

**Comment by dj3520** [comment]
"dead?" It's space. The only ambient sounds are your own breaths inside
your spacesuit. And there's no ambient animals. Just space zombies,
skeletons and spiders.

Also there's no Venus without an add-on. Moon, Mars, and Asteroids so far.

Cold and dry additives to an area don't seem effective. There's no forests
or oceans. Just a lot of storage dirt.

**Comment by jimcarreer** [comment]
@dj3520 I think you're completely missing the point, this is about making Galacticraft support other mods better.

"COLD" and "DRY" have nothing to do with there being "forests" or "oceans" their just tags that help describe the biome environment.  Last time I checked both Mars and the Moon were cold and dry.  Also "DEAD" in the fact that *they have no life* like you said.

Finally, you don't appear to be a developer, or even someone who knows how to write code, so I'm not really interested in your opinion.

**Comment by dj3520** [comment]
Well I'm not about to lie and say I am a developer. I've only put in two
pull requests to this repository despite not knowing any Java. I do a lot
of scripting though, so writing code isn't hard.

I wasn't saying that it was a bad idea in general, but instead for
Galacticraft. The terrain doesn't vary much.

I also wasn't shooting your mod compatibility down either.

**Comment by jimcarreer** [comment]
Forgive me for being blunt, but you don't actually seem to be able to comprehend what BiomeType and the BiomeDictionary are for. Galacticraft definitely adds new biomes to Minecraft for these worlds and if they ARENT registered in the BiomeDictionary, Forge will perform a "best guess" as to what type it is.  Currently that guess is __terribly inaccurate__ for the "Moon" and "Mars" biomes.  The BiomeDictionary in Forge is meant to support incompatibility between Mods that do things based on biomes and Mods that add Biomes. Galacticraft adds biomes, ergo it should register them with Forge and classify them with BiomeTypes.

**Comment by chezpaul** [comment]
Yes, please Galacticraft devs, please add them. Shouldn't they already be added?
I would think this would be basic coding no?
It would be so great. I use Jim's mod and it's really nice. The only problem is that I hear birds on MArs and the moon.  ;-)

If this is easy, I would really appreciate this.  ;-)
Thanks.

I will add your post Jim to a thread about Galaxy Space which is the Galacticraft add on which adds a lot more planets one of them being Venus.
Or maybe you could tell them better.  ;-)

http://forum.micdoodle8.com/index.php?threads/1-7-2-1-7-10-galaxy-space-beta.5298/

Thanks everyone... 

On another note, hearing only someone breathing hard in a helmet would be pretty cool for those planets.  ;-)

**Comment by dj3520** [comment]
I saw on the display screen there's a "heart rate." Would be cool if that
triggers faster/slower breathing. Maybe some grunts for jumping, landing,
or even swinging swords.

**Comment by micdoodle8** [comment]
Okay, so I've registered the biomes, and the registrations can be disabled in the config files for those that don't want them.
Mars:
*cold
*dry
*dead
Moon:
*cold
*dry
*dead
Asteroids:
*cold
*dry
*dead
*spooky

**Comment by chezpaul** [comment]
You literally ROCK!  ;-)

**Comment by jimcarreer** [comment]
@micdoodle8 Thanks for adding this!

**Comment by EzerArch** [comment]
@micdoodle8, thank you.

Sorry for asking, but what about the space station dims? They still have the Overworld biomes.

> I saw on the display screen there's a "heart rate." Would be cool if that triggers faster/slower breathing. Maybe some grunts for jumping, landing, or even swinging swords.

I think this suits better as a separate mod.

**Comment by micdoodle8** [comment]
Oh, is that the old issue that would also happen on the moon/Mars where F3 mode would show the overworld biome names? I guess I didn't fix it for the space station.

**Comment by EzerArch** [comment]
> Oh, is that the old issue that would also happen on the moon/Mars where F3 mode would show the overworld biome names?

Probably. I still have this problem with Mars. The biome name goes back and forth from ```marsFlat``` to a random OW biome as I walk. Is there a way to convert chunks with wrong biome name when I load the world/dim? I tried to convert them manually with MCEdit and WEdit, but it may be problematic.

**Comment by EzerArch** [comment]
There! http://wiki.micdoodle8.com/wiki/Biomes

**Comment by chezpaul** [comment]
Nice.


Paul Boutin
310 498 4593
paulboutinonline.com

**Comment by EzerArch** [comment]
I don't know if it's worth reporting.

I was trying to convert the biomes in my SS dim to "space". WorldEdit can recognize "marsFlat" and "moon" as valid biome types (```//setbiome <biome type>```), but not "space".

![2015-11-09_00 56 57](https://cloud.githubusercontent.com/assets/6743303/11025003/308575f8-867d-11e5-8fa3-ab162bf5aac9.png)

**Comment by dj3520** [comment]
Is the WorldEdit you use Bukkit or Forge?

**Comment by EzerArch** [comment]
@dj3520, it's Forge.

**Comment by EzerArch** [comment]
Space Stations keep reseting the "space" biome back to OW biomes. The only way to make the mod remember it is "space" is by drifting away to create new chunks then the game remembers "oops, it's space".

And "space" is not registered with BiomeDictionary.

**Comment by SteveKunG** [comment]
![2558-12-18_11 35 50](https://cloud.githubusercontent.com/assets/6128413/11889388/632db7b4-a57b-11e5-9e35-91c06d0746b1.png)

OK. I fixed Biome Gen in the space station.
https://github.com/SteveKunG/Galacticraft/commit/faab9856963abfb192d5e50f96f9b71a4b9c146e

**Comment by EzerArch** [comment]
@SteveKunG, thank you! :)
