### ISSUE TITLE
Portable Oil Extractor missing

### ISSUE THREAD

**Issue by Zebbieman** [micdoodle8/Galacticraft#1920]
![2015-10-28_11 52 27](https://cloud.githubusercontent.com/assets/15366363/10797942/a607b9c4-7d6a-11e5-92e9-67558108004b.png)
Not much of a story here.I am using the latest galacticraft build. I made the attempt to craft the Portable oil extractor and I got nothing on the crafting table! I looked in the creative inventory and I was unable to find the item. So what's going on here?

**Comment by dragon-dreamer** [comment]
As I remember, portable oil extractor has been marked deprecated in recent versions. You should use usual buckets instead.

**Comment by Zebbieman** [comment]
Ok Thank you!
