### ISSUE TITLE
soul bound items?

### ISSUE THREAD

**Issue by JewNoodles** [micdoodle8/Galacticraft#1922]
so soul bound my thermal padding and oxygen gear so when i die i dont struggle to get my grave...

seem like the soul bound property doesnt work on these items. i can add the property but it the mechanic of soul bound doesnt work.  so when i die... i loose all of my Galacticraft gear :(

**Comment by micdoodle8** [comment]
Ars Magica doesn't support having soul bound items in the Galacticraft extended inventory. You can ask their developer(s) to add support, because the inventory is accessible from the player's getExtendedProperties method.
