### ISSUE TITLE
UI Issues with Fuel Loader/Water Electrolyzer

### ISSUE THREAD

**Issue by Youjust** [micdoodle8/Galacticraft#1924]
I've been getting an odd bug with the UI's of the Fuel Loader and Water Electrolyzer- I pump in fuel to the tanks (yes, it is the GC fuel- the item ID matches) and the liquid doesn't show up in the tanks. However it still fills my rocket, which is odd. In addition, I tried a brand-new Water Electrolyzer out, and after pumping in water and giving it power, it wouldn't electrolyze. There was enough water in the pipe I had connected to it, and I tried everything- I made sure the connections were right, I put in a GC battery into the little energy slot, and a bucket of water into the input slot- but nothing happened. It wouldn't even accept my water bucket. I'm not sure if this is related to the fuel loader issue- or maybe it's just a settings thing- I don't know. I'm using GC build 3.0.12.375.

**Comment by dj3520** [comment]
Can you try again with build 400?

**Comment by Youjust** [comment]
OK. Gonna make a backup first though XD

**Comment by Youjust** [comment]
Both work great, and my framerate seems to have doubled as well! Thanks!
