### ISSUE TITLE
Recommendation: Tiered Oxygen Pipes / Faster Oxygen Transfer

### ISSUE THREAD

**Issue by Yanniclord** [micdoodle8/Galacticraft#1927]
Heyo, i only wanted to plop by and for the next update maybe recommend so you can either change the Oxygen Transfer speed in the config (for both pipes and those super slow Oxygen Storage Modules). If that wont be added, maybe instead add Tiered Oxygen Pipes that have fast transfer rates, same goes for the Oxygen Storage Modules. This recommendation is because i found out that if the Space Station starts getting all to big, you need a room that generates oxygen every 2nd room, wich just does not cut it. That is because the transfer rates of the Storage Modules and the Pipes are to slow, ending up with being unable to fill the whole system with Oxygen, even if you are doing fine with generating oxygen, you just end up having one end not being filled up, wich is kind of sad considering some wanting to make huge Space Stations.

Here is a picture of the current situation (sorry for my Paint skills :D ): 
![2015-11-04_16 09 52](https://cloud.githubusercontent.com/assets/5807595/10942332/f90bfd9c-830f-11e5-9e4d-007522031a9f.png)

So, as you see, the problem is the transfer rate. I have more than enough Oxygen, but in the end there is no way to fill all of the Sealers and Storage Modules fast enough, even if the beginning of the line is completely filled up (lets say the first 10 Storage Modules). Thats why i would recommend faster transfer rates for the Oxygen Pipes and Storage Modules, because for large Space Stations they are more than necessary (they might work just fine on the Moon or wherever you make a base on a Planet, but because of on Space Stations you just want to do things compact and completely Sealed, it would be better that way.)

Thanks for reading :)

**Comment by Yanniclord** [comment]
Also, i know Mekanism has fast transfer rates for its Tiered Gas Pipes, but i prefer the look of Galacticraft, and also there are no whole blocks in both Mekanism and Galacticraft that can transfer Oxygen fast enough and being sealed at the same time.

**Comment by Yanniclord** [comment]
Hmm, seems that the Mekanism Gas Pipes are so fast that they act like tanks (since they can hold so much). Also, it seems the Storage Modules dont have a Transfer Limit, but the Oxygen Pipes do :)

**Comment by Yanniclord** [comment]
Hello?

**Comment by XFactHD** [comment]
Please give the devs some time, they also have their own life.

**Comment by Yanniclord** [comment]
Im actually just asking for any reply here, thats all i want.

**Comment by dj3520** [comment]
They're likely going to point out that suggestions are not for the issue
tracker. The guidelines you were supposed to read state that clearly.

**Comment by Yanniclord** [comment]
Actually i did, but i know for sure that many other mod makers use the Issue tracker also for recommendations, and i dont know where else that should go.

**Comment by dj3520** [comment]
True, other mods might, but it says here that you should not. Unfortunately
making a forum post is as far as you should go.

**Comment by radfast** [comment]
Thanks guys.  As @dj3520 said, suggestions are not wanted on this Issue Tracker, it is only for current issues with the mod.  You are welcome to make the suggestion on the forum - that is better, because more players will comment on it there.  We do read all the suggestions on the forum.

**Comment by radfast** [comment]
@Yanniclord can you try to build multiple Oxygen Storage Modules with outputs connected together to the same oxygen pipe?  I think that will maybe solve your space station problem.  Let us know...

**Comment by Yanniclord** [comment]
Ye actually i tried that, having three lines doesnt even help. But, again, as i said using EnderIO Gas Conduits works fine. I went into the EnderIO config and made it transfer 3500 per second, wich is more than what the Oxygen Storages can hold. By that, they will always be full and able to output alot to. However, i would still suggest to add an option to the Galacticraft config to be able to modify the Oxygen I/O rate of both the Oxygen Pipes and the Oxygen Storage Modules, as the normal options wont cut it on a large Space Station with a main Oxygen generator room, and not even three lines of seperate Oxygen supply. Only using EnderIO Conduits did the trick.
