### ISSUE TITLE
EventHandlerGC.onSoundPlayed consumes PlaySoundEvent17 events

### ISSUE THREAD

**Issue by TruePikachu** [micdoodle8/Galacticraft#1933]
Working in [this issue at Railcraft](https://github.com/CovertJaguar/Railcraft/issues/655), [I determined](https://github.com/CovertJaguar/Railcraft/issues/655#issuecomment-155139840) that Galacticraft prevents Railcraft's block sounds from working.
What happens is that, in [onSoundPlayed](https://github.com/micdoodle8/Galacticraft/blob/677c6b270426377d693b61c7512c4dae8bf0d6f2/src/main/java/micdoodle8/mods/galacticraft/core/event/EventHandlerGC.java#L728), if the player has a frequency module or is in a sound-conductive environment, `event.result` gets set to `event.sound`.

However, Railcraft's (as an example; other mods probably have similar issues) blocks issue stuff like `minecraft:step.railcraft` as their `event.sound`. This normally isn't a problem, since Railcraft's [`onPlaySound`](https://github.com/CovertJaguar/Railcraft/blob/master/src/main/java/mods/railcraft/client/sounds/RCSoundHandler.java#L37) catches `minecraft:step.railcraft` and sets `event.result` to an actual sound. But if Galacticraft's handler takes the event, it will (in most circumstances) set `event.result` to `minecraft:step.railcraft`
```
[Client thread/WARN]: Unable to play unknown soundEvent: minecraft:step.railcraft
```

A fix would be a `return null` if [this `if` statement](https://github.com/micdoodle8/Galacticraft/blob/677c6b270426377d693b61c7512c4dae8bf0d6f2/src/main/java/micdoodle8/mods/galacticraft/core/event/EventHandlerGC.java#L748) fails; currently it executes [this statement](https://github.com/micdoodle8/Galacticraft/blob/677c6b270426377d693b61c7512c4dae8bf0d6f2/src/main/java/micdoodle8/mods/galacticraft/core/event/EventHandlerGC.java#L774) if it fails.

**Comment by TruePikachu** [comment]
I might mention this isn't a 100% of environments thing; the bug only clearly appeared after adding Chisel2 to the environment, which made Railcraft load _before_ Galacticraft (instead of after).

**Comment by radfast** [comment]
Thank you very much, this will be fixed from next GC build.

Thank you for the explanation.  The GC event handler will now not alter the ```event.result```, except possibly to attenuate its volume in space environments.

I guess a lot of mods are probably coded based on ```event.sound``` where it should be on ```event.result```.  But yes, we definitely should not have been automatically setting ```event.result``` to ```event.sound```.
