### ISSUE TITLE
Planets with Multiverse

### ISSUE THREAD

**Issue by rpgexperience** [micdoodle8/Galacticraft#1939]
I want to use the Multiverse-Core plugin to have a complete world and dimension management: custom chat, portals... I tried to import the different dimensions and it seemed to work but I couldn't go to another planet/dimension when I arrived to the galaxy map.
When I restarted the server, this kind of line appeared for all the dimensions registered in Multiverse:

[19:31:39] [Server thread/ERROR]: Dimension already registered to another mod: unable to register planet dimension -28

I tried to change the environment type and the generator but I couldn't find how to resolve the problem.
How can I resolve that ?

**Comment by dj3520** [comment]
Have you tried changing the Galacticraft config for the dimension IDs?

**Comment by rpgexperience** [comment]
Yep, same error...

The line for the moon:
[20:59:42] [Server thread/ERROR]: Dimension already registered to another mod: unable to register planet dimension -28

If I change the dimension IDs the line is:
[21:02:23] [Server thread/ERROR]: Dimension already registered to another mod: unable to register planet dimension 3

**Comment by rpgexperience** [comment]
I've just resolved the problem: the dimensions weren't loaded at server start so multiverse didn't know how to send me to the dimensions.
You have to go in the core.conf file and add the dimensions in the "I:"Static Loaded Dimensions"" line: the dimensions will be loaded now and erverything will be fine.

**Comment by radfast** [comment]
Great, thank you for coming back with the solution.   I will update the Galacticraft Wiki to cover this, it should help some other players.

**Comment by radfast** [comment]
Hmm, already covered on the Wiki but it was hard to find!  Hopefully clearer now, and it references Multiverse.  http://wiki.micdoodle8.com/wiki/Tutorials/Space_Station_for_Server_Admins#Making_dimensions_available_to_other_mods_using_core.conf

**Comment by Cronosus** [comment]
hello
if someore read this, i tried that, but GC register dimensions after multiverse, then i ave still problem with that. :(
