### ISSUE TITLE
Server crashing when reaching atmosphere.

### ISSUE THREAD

**Issue by Technoblazed** [micdoodle8/Galacticraft#1940]
Whenever we reach the atmosphere of the overworld, the server just crashes, I've looked far and wide and can't seem to find any one else having the issue.

Forge-logs: http://pastebin.com/s8WG6YRG
Crash report: http://pastebin.com/9nqL9dXD

**Comment by radfast** [comment]
Is this issue still a problem for you?
Please can you re-upload the crash report to pastebin because the link expired.
Please also test this *without any Galacticraft addons*.

**Comment by radfast** [comment]
@Technoblazed please re-upload the crash report in your first post.

**Comment by radfast** [comment]
Please also try out build 314a - download links are [here](https://github.com/micdoodle8/Galacticraft/issues/2001#issuecomment-171146658).  It's possible this has fixed the problem.  Hard to say, because without seeing your crash report I don't know what the problem is....

**Comment by dj3520** [comment]
you mean 413a?

**Comment by radfast** [comment]
Sorry for any confusion caused.

I meant to say **414a**.  It's the latest version.  The post above links to the download links.

**Comment by radfast** [comment]
Please now use version 415 from the official micdoodle8.com website.

**Comment by radfast** [comment]
No response from @Technoblazed.  Anyhow, I think this is likely fixed in recent builds, we have fixed a lot of problems of this type.  I will close this now.

If you are still having crashes in GC version 420 or later, please post the crash report and we can re-open this.
