### ISSUE TITLE
Moon buggy sinks and disappears on clunk reload

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#1941]
This is a very annoying and frustrating bug. Always happens on the overworld, never happened on the other dimenions. I've lost dozens of moon buggies on my overworld base, and I have a handful of them stuck 3-10 blocks underground to be unearthed.

1st, place the moon buggy.
![2015-11-15_18 48 56](https://cloud.githubusercontent.com/assets/6743303/11170927/dc7bcd52-8bc9-11e5-8f23-091df9942edd.png)

Have a walk a few chunks away.
![2015-11-15_18 49 11](https://cloud.githubusercontent.com/assets/6743303/11170928/dc7bfe94-8bc9-11e5-9439-b2fd2a5ee02d.png)

Oh noes, my moon buggy disappeared.
![2015-11-15_18 30 23](https://cloud.githubusercontent.com/assets/6743303/11170929/dc7cb12c-8bc9-11e5-9a6b-eae50c50a51b.png)

![2015-11-15_18 49 28](https://cloud.githubusercontent.com/assets/6743303/11170930/dc7cdcb0-8bc9-11e5-9d48-47f7811523eb.png)

Sometimes it just sinks 3 blocks 
![2015-11-15_18 29 11](https://cloud.githubusercontent.com/assets/6743303/11170926/dc7ae4c8-8bc9-11e5-884a-72eba580d7ae.png)

Using:
Galacticraft-Planets-1.7-3.0.12.402.jar
GalacticraftCore-1.7-3.0.12.402.jar
MicdoodleCore-1.7-3.0.12.402.jar
Forge 1558.

Similar to #1710.

**Comment by radfast** [comment]
This should be fixed in GC 1.7.10 build 487.  Please re-open if it's still an issue..

**Comment by radfast** [comment]
not so fixed as I thought, very sorry.

we'll get there ... I definitely fixed the moon Lander so this shouldn't be too much harder

**Comment by EzerArch** [comment]
Yep, my buggy sunk but I've found it underground. I used a small tool called [In-game NBTEditor](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286750-in-game-nbtedit-edit-mob-spawners-attributes-in) on it:

![2017-04-22_09 23 54](https://cloud.githubusercontent.com/assets/6743303/25304440/a5dd4eb8-273d-11e7-8fb9-ac67347ec581.png)
