### ISSUE TITLE
Entities Not Configurable=Crash

### ISSUE THREAD

**Issue by jredfox** [micdoodle8/Galacticraft#1942]
Version: Latest
Crash Report: http://pastebin.com/acAg94xj

**Comment by SteveKunG** [comment]
com.Mod_Ores.ClientProxy.registerRenderers(ClientProxy.java:21)
I think it's not Galacticraft issue. -.-

**Comment by SteveKunG** [comment]
Galacticraft should be use EntityRegistry.registerModEntity method.
See also : https://github.com/SteveKunG/More-Planets/blob/master/src/main/java/stevekung/mods/moreplanets/core/init/MPEntities.java#L205-L210

**Comment by jredfox** [comment]
well then there is a critical error with the latest version and you need to report that crash to them.

**Comment by micdoodle8** [comment]
Galacticraft registers it's entity IDs dynamically, so this is definitely not an issue on our side. Unless you have another crash report pointing the issue this way, the crash it caused by Mod_Ores...
