### ISSUE TITLE
Oil blocks update recursively during terrain gen causing lag spikes

### ISSUE THREAD

**Issue by Builderb0y** [micdoodle8/Galacticraft#1943]
Sampling the server thread with visualVM during terrain generation revealed a VERY long stack trace with "micdoodle8.mods.galacticraft.core.blocks.MaterialOleaginous.func_76230_c" (and other liquid-block-related methods) mentioned many times. I took screenshots of the top and bottom of it, but I can also upload the .nps file for it if necessary.

Top: http://i.imgur.com/tZVnd5I.png
Bottom: http://i.imgur.com/R1Wmp4I.png

Lastly: The issue gets worse when pneumaticcraft is configured to also generate oil. Disabling oil generation in both mods' config files does resolve it, though I do not see this as a satisfactory solution, as oil is still required by both mods.

**Comment by Builderb0y** [comment]
Whoops, duplicate of #1885, didn't see that one when searching for "oil". Sorry.

**Comment by radfast** [comment]
Closing as duplicate, and the issue has been addressed in latest GC versions as discussed on #1885.
