### ISSUE TITLE
Oxygen bubbles not providing oxygen at random.

### ISSUE THREAD

**Issue by PsionicArchon** [micdoodle8/Galacticraft#1953]
Using version .404 of Galacticraft (latest available) on version .1448 of forge.

My oxygen bubble distributors will fail to provide me oxygen, commonly on loosing and regaining power. The bubble renders and the machine claims to be using oxygen when this happens. If I pick up the machine and place it down again, allowing the bubble to reform, I no longer get oxygen warnings.

I've seen this bug mentioned before several months ago and it was listed as fixed. I have not tested the oxygen sealer yet.

**Comment by micdoodle8** [comment]
Do you notice any links between logging out/in, or moving far away from the machine and coming back having an impact on the incorrect warnings? Or is it just losing and re-gaining power that causes the issue. I would recommend the sealer for now if this is a common enough issue to be game-breaking.

**Comment by PsionicArchon** [comment]
It only seems to happen if the oxygen bubble looses its oxygen source or if it looses power. Unloading the chunk didn't have an effect, though I keep them chunkloaded now just to be safe. 

I like to use oxygen bubbles while I'm constructing space stations, gives me room to build without constantly having to refill tanks. 

If you want to reproduce the issue just provide oxygen to an oxygen bubble, cut the power, then restore power and let the bubble reform. You'll usually start suffocating even when within the bubble.

**Comment by dj3520** [comment]
> If you want to reproduce the issue just provide oxygen to an oxygen bubble, cut the power, then restore power and let the bubble reform. You'll usually start suffocating even when within the bubble.

Just tried this and wasn't able to reproduce the issue.

**Comment by radfast** [comment]
I tried it also, and cannot reproduce the issue.

Do you have any Galacticraft add-ons or submods installed?
Which dimension is this on?
Are you playing on a server or single player?

**Comment by radfast** [comment]
@PsionicArchon quick question - are you using clones from **Sync** mod, or any other mod which offers anything like teleporting or re-spawning?  If so, did the oxygen issue only happen after cloning / teleporting?

**Comment by radfast** [comment]
I'm closing this, because nobody else has been able to reproduce the issue, and no response from @PsionicArchon 

We can re-open this if it is still happening in the latest Galacticraft.  I'd like to see a full mods list please.
