### ISSUE TITLE
Crafting a Thaumcraft Iron Caped one (the first one) Crash the Game

### ISSUE THREAD

**Issue by Dream-Master** [micdoodle8/Galacticraft#1955]
When i try to lay a Thaumcraft Iron Capped Wand in the Inventory the Game crash.

Tested with Galacticraft 404

Client Crash:
https://gist.github.com/Dream-Master/8a8b011a46f6ed1ec843#file-tainted-magic

Sever Error:

https://gist.github.com/Dream-Master/5a2bec01e41a161e2b16#file-ultrapeeks

Post the issue here too:

https://github.com/yorkeJohn/TaintedMagic/issues/12

**Comment by dj3520** [comment]
Does not seem to be an issue caused by Galacticraft.

**Comment by Dream-Master** [comment]
Maybe not but i let this here so far i not here anything from Tainted magic Dev.

**Comment by Alaberti** [comment]
This is not a Galacticraft issue, it is a tainted magic issue. Also related to https://github.com/yorkeJohn/TaintedMagic/issues/8.

**Comment by Dream-Master** [comment]
It happend when the Wand not have any NBT data Tag. So i close this here.
