### ISSUE TITLE
Rockets unfuelable

### ISSUE THREAD

**Issue by katzenpapst** [micdoodle8/Galacticraft#1960]
Title says it all, the fuel loader has energy and fuel and is active, is next to a launch pad with any rocket on it, but the rocket doesn't get fueled. I suspect it has to do something with the legacy oilgc and/or fuelgc config options, which I have both set to true

**Comment by dj3520** [comment]
What version of Galacticraft are you using?
Are all rockets not fuelable?

**Comment by Dream-Master** [comment]
Disable old fuel support in the config and it will work. I have the same issue before. (both values set to false)

    B:"Use legacy oilgc fluid registration"=false
    B:"Use legacy fuelgc fluid registration"=false

**Comment by katzenpapst** [comment]
1.7-3.0.12.402.

And meh, I guess I have to disable the legacy stuff and cheat me my oil back. It never really worked

**Comment by Dream-Master** [comment]
Use Buildcraft Oil

**Comment by BlesseNtumble** [comment]
Custom rockets?
