### ISSUE TITLE
Random rocket launch pad randomly generating in the overworld with MicdoodleCore-1.7-3.0.12.357

### ISSUE THREAD

**Issue by lightning02** [micdoodle8/Galacticraft#1968]
With Micdoodle Core 1.7-3.0.12.357 this rocket launch pad randomly generating in the world.
Why this object happens? How to solve? There is a way to change the ID of this block? How can i understand which is the ID to change? 

![b127682ee5c614d943d0d71ce50625fbf05ea4a2297edcdc74 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/11884147/11823173/ebafea0e-a372-11e5-987e-856b39770ac9.jpg)
![655643c20c522cf382ff98b528e983e1b9f49364d06d984740 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/11884147/11823174/ecc2b4a8-a372-11e5-9b86-46a7fcf23608.jpg)

**Comment by radfast** [comment]
Please post a full startup log (latest.log from your .minecraft logs folder)
If it's too long to post, put it on Pastebin or similar, and give us the link please.

**Comment by lightning02** [comment]
Here it is the latest log. http://pastebin.com/iY72a94B
Let me know if you need the fml latest log.

**Comment by lightning02** [comment]
Here it is the latest log. http://pastebin.com/iY72a94B
Let me know if you need the fml latest log.

**Comment by radfast** [comment]
Yes please, provide the fml latest log.

It looks like one of your other mods is causing this.  For a start, can you please try uninstalling 4space and any other addons.  **Create a new world for testing: uninstalling mods will cause damage to your existing worlds if you try to load them.**

**Comment by lightning02** [comment]
I will do as you suggested :) thanks for the attention and the patience

**Comment by radfast** [comment]
I don't see any relevant errors in that log.

You are saying something is creating this in worldgen?

I think the most likely is that the config of one of your other mods has been set with a Block ID number which is the landing pad.  For example, if a mod can generate extra ores in the world, in a config you might have set the Block ID # for ores which you wanted.  (Or the modpack creator did that.)  Then if newer mods were added to the pack, or even an existing mod was updated, all the Block ID numbers can change, so suddenly the config is wrong.

I would start by looking at CoFHCore config for worldgen, and any other mods which have configurable worldgen settings.  (A lot of mods have worldgen: not just the obvious ones, think about any mod which adds new ores to the world.)

One other possibility to check for conflicts: **TardisMod** also has a block named "LandingPad".

---

I do not think there is any bug in Galacticraft *per se* here.  I'm going to close the issue, as I do not think there is anything for us to fix in Galacticraft's code.

But we can continue the discussion in this thread, and if you can maybe identify which specific mod is conflicting and causing this, we might be able to find a fix.

It looks like you are using a modpack named "Wonderful Bounty Ultra Pack".  Did you make changes to the pack, and did you raise this issue with the pack creator?

**Comment by radfast** [comment]
Note that the log is telling you you have a bad download of one of the mods: Hamsterrific-0.2.0.jar.zip

**Comment by lightning02** [comment]
Yes I'm in contact with the modpack author, he already said that he will look into it but it will take him some time. anyway, I never found someone that has your same patience to explain and wish to help other people, you are a really good person!!
