### ISSUE TITLE
Equipment survival tab issue .

### ISSUE THREAD

**Issue by crunkazcanbe** [micdoodle8/Galacticraft#1970]
Hey there is there anyway you could make this compatible with this mod here https://github.com/shift02/SextiarySector2/issues/11 ? Please if you can . The mods tabs in the servival inventory are overlapping each other . If you could not make the mods compatible could you just make a quick change by adding a option in the config file of your mod to disable the tab ,and instead of there being a tab have the option of a key bind bringing up the Equipment survival tab ?  I would really appreciate it if you could make these mods work together. BTW TConstruct mod has compatibility built in for this mod . Thank you .

To use this mod you need two jar files get this one here http://forum.minecraftuser.jp/viewtopic.php?t=22369 and this one here http://forum.minecraftuser.jp/viewtopic.php?f=13&t=17110&p=145963#p145962 . Again Thank you very much !!

**Comment by EzerArch** [comment]
This is similar to #831, CustomNPCs tabs overlapping Galacticraft's.

Relevant quote from @radfast, from https://github.com/micdoodle8/Galacticraft/issues/831#issuecomment-51713285:

> It's up to the CustomNPCs mod author to make their tab system compatible with Tinker's Construct's "TabRegistry". If that mod is not currently supported then maybe some player who knows Java can produce a patch for it.

**Comment by crunkazcanbe** [comment]
Could you please make a patch for me man ? Pretty please ? I would really really appreciate it me and my wife will . We are trying to play with these mods but can not click on some tabs . Its really really annoying . If you could man I wouldn't be able to think you enough .

**Comment by dj3520** [comment]
Not GC's fault so nothing to fix

**Comment by radfast** [comment]
Please show a screenshot of the TConstruct compatibility.
