### ISSUE TITLE
MISSING OCEANS!!

### ISSUE THREAD

**Issue by shuja555** [micdoodle8/Galacticraft#1971]
my oceans DISAPPEAR entirely
there is no more water even though the biome is ocean
there is even trees!

**Comment by EzerArch** [comment]
Create a new world to confirm.

**Comment by shuja555** [comment]
Confirmed :)
![2015-12-17_15 51 31](https://cloud.githubusercontent.com/assets/16040078/11881677/23362d76-a4d6-11e5-9d11-447bb00ef770.png)

**Comment by dj3520** [comment]
Mod list?

**Comment by shuja555** [comment]
mc heli
carpenter blocks
zans minimap
better furnaces
damage indicators
status effect hud
ars magica 2
mystcraft
item physics
animation API
applied energistics
archimedes ships
avatar the last blockbender
backpacks
bacteria
battletowers
better hud
buildcraft
chisel 2
clay soldiers
crossbow
decocraft
deconstruction table
dont pick up
dragon mounts
ench plus
ender IO
ender storage
extra util
galacticraft+planets
grav gun
hats
in game wiki
insta house
inv tweaks
iron chest
jabba
malis' doors
voxelmap(zans)
morph
crayfish furniture
mutant creatures
NEI
openblocks
optifine
orespawn
pandoras box
pneumaticcraft
rival rebels
sapman pack
soul shards reborn
steves carts
super heroes unlimited
Tconstruct
thaumcraft
erebus
thermal expansion+foundation
transformers
twilight forest
veinminer
WAILA
p.s. prerequisites not noted ex. Mantle

**Comment by EzerArch** [comment]
I don't think there are missing oceans. The terrain doesn't resemble an ocean floor in any bit. Probably it's just the minimap acting up. Press F3 and tell us the biome from the debug screen.

**Comment by radfast** [comment]
Why is this a Galacticraft bug?

Closing, we can re-open if there is evidence Galacticraft is causing this.

Note: this sounds like a biome ID conflict in one of your other mods.  There is more info about this on the Galacticraft wiki: http://wiki.micdoodle8.com/wiki/Config#Biome_ID_Base
