### ISSUE TITLE
Player respawn and dimension change don't honor "Show Cape: OFF"

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#1972]
Every time I respawn or change the dimension, the cape keeps reappearing, then I go to Game Options, Multiplayer Settings, the "Show Cape" parameter is OFF.

Also in the options.txt, ```showCape:false```.

**Comment by radfast** [comment]
Seems to be a bug in vanilla Minecraft - or anyhow, it used to be: https://bugs.mojang.com/browse/MC-44039

I have no way to confirm whether it is still a bug in vanilla Minecraft - only a person with a vanilla cape can do that.

Anyhow, we can fix this in Galacticraft, and we should support our supporters :)
