### ISSUE TITLE
Cant do anything in the asteroid dimension in Galacticraft

### ISSUE THREAD

**Issue by Spikeal** [micdoodle8/Galacticraft#1977]
I have tried restarting my game multiple times, but i can not do anything in the s=asteroid dimension, i am on survival mode and i cant even get out of the landing pod, this is the log that minecraft has of the run:
[Game Output.txt](https://github.com/micdoodle8/Galacticraft/files/71425/Game.Output.txt)

**Comment by EzerArch** [comment]
Unfortunately the log says nearly nothing.

I tested the asteroid dim, I could leave the pod with right-click and with shift-key. Must be some another mod affecting it.

Check the your keybinds for conflicts.

Are you using a mod that changes the player model/animation?

**Comment by radfast** [comment]
Galacticraft alone does not have this problem.

It looks like it could be a JourneyMap issue, or one of your other mods conflicting.

Please uninstall JourneyMap then test again.  If you still have problems after that, uninstall a bunch of others until you find the conflicting mod, and then let us know which one it is.

**Comment by radfast** [comment]
Is this the same issue as #1697?   So the space station or planet map shows on the minimap, but the player cannot move, like when the player is falling out of the world?

**Comment by radfast** [comment]
Just checking to make sure the original poster tried using LEFT SHIFT (the SNEAK key) and also Right-Click to exit the landing pod?

**Comment by radfast** [comment]
Hope to hear something from you @Spikeal
