### ISSUE TITLE
OxygenHooks crash on dedicated server

### ISSUE THREAD

**Issue by spamenigma** [micdoodle8/Galacticraft#1979]
Since updating RotaryCraft I'm getting 'server only' crashing issues which I'm being told most likely is a galacticraft issue. 

https://github.com/micdoodle8/Galacticraft-API/issues/4

If this could be looked into that would be great as I'm stuck! Thanks

**Comment by xKillerbees** [comment]
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/501

**Comment by Patman0021** [comment]
and 502... and the original.. 484

**Comment by radfast** [comment]
This is a duplicate of issue #1990 - or more accurately, #1990 is a duplicate of this!

Thank you for reporting.

This is fixed in the latest Galacticraft build number 407  (or any later build)  - you only need to update to build 407 on servers, clients do not need to update.
