### ISSUE TITLE
CraftGuide & GC

### ISSUE THREAD

**Issue by wujekbrezniew** [micdoodle8/Galacticraft#1980]
When I open Craft Guide book in my modpack the game is crashing.
It may be an GalactiCraft issue.
Log :
http://pastebin.com/XTsSPLBU

**Comment by radfast** [comment]
It's not a Galacticraft issue.  Read https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md  guidelines no 1.
