### ISSUE TITLE
Flag model lighting issue with NEI HUD

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#1983]
![2558-12-22_00 34 02](https://cloud.githubusercontent.com/assets/6128413/12018793/531df9e8-ad9a-11e5-947a-148a2a4d0695.png)
![2558-12-22_00 34 04](https://cloud.githubusercontent.com/assets/6128413/12018794/5322985e-ad9a-11e5-8a39-48c1db66fa68.png)

**Comment by dj3520** [comment]
Also appears not to wave.

**Comment by EzerArch** [comment]
@dj3520, the wave speed depends on the [```windLevel```](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/client/model/ModelFlag.java#L70) of the dimension you are in. The moon's is 0.0; Mars' is 0.3; Asteroids' is 0.05.

**Comment by dj3520** [comment]
Sorry I didn't look hard enough at the pictures.

**Comment by radfast** [comment]
I can't reproduce this issue in my testing.

Which versions of NEI and CodeChickenCore are you using?   Any other mods (Optifine?)

**Comment by SteveKunG** [comment]
I testing in the eclipse. Using latest source of CCC and NEI. (No optifine installed)
![2559-01-12_13 36 42](https://cloud.githubusercontent.com/assets/6128413/12256650/8e39096c-b931-11e5-8e11-9481a8627185.png)
![2559-01-12_13 36 43](https://cloud.githubusercontent.com/assets/6128413/12256651/8e3ac978-b931-11e5-96c7-04cea5d4d146.png)

**Comment by SteveKunG** [comment]
I think I can't reproduce this issue. That's weird.
