### ISSUE TITLE
Server crashes on start due to GuiScreen not found

### ISSUE THREAD

**Issue by notchriss** [micdoodle8/Galacticraft#1990]
I was told it's Galacticraft issue using Gui on server side. Could you please look into it?

http://paste.ubuntu.com/14367693/

**Comment by VX7NORBA** [comment]
Same problem with rotarycraft engines on my server. But I use recommended galacticraft version. On singleplayer it works.

**Comment by aetherpirate** [comment]
Same here

https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/501

**Comment by radfast** [comment]
Thank you for reporting.  This should be fixed in next build.

**Comment by radfast** [comment]
Please try GC build number 407 on your server.  Shortcut for you: http://ci.micdoodle8.com/job/Galacticraft-1.7/407/
