### ISSUE TITLE
Energy dupe with IC and Beam Receiver

### ISSUE THREAD

**Issue by Zer0id** [micdoodle8/Galacticraft#1991]
![2016-01-04_16 14 44](https://cloud.githubusercontent.com/assets/14043791/12091620/3d97e5ce-b309-11e5-943a-44cc3ae1a59a.jpg)

starting with both storages empty and single filled battery (GC or IC) the whole system fills up less in a minute

tried recommended .375 and last .407 builds

**Comment by aidancbrady** [comment]
That is an incredibly old version of Mekanism- please update!

**Comment by Zer0id** [comment]
There's no Mekanism mod. Only GC and IC exp

**Comment by radfast** [comment]
Thanks for reporting, I'll look into this.

**Comment by dj3520** [comment]
Comfirmed in 406
![image](https://cloud.githubusercontent.com/assets/8284194/12156991/6b0cbf2c-b49c-11e5-892e-40df55bec556.png)

Top is 2048 EU/t constant (MFSU output rate.) ESC accepts 1024EU/t until full, then 307 EU/t
![image](https://cloud.githubusercontent.com/assets/8284194/12157054/f41eb9dc-b49c-11e5-862b-7e2c86a624b0.png)

An MFSU fills in the time it takes to read this. And this all started with one GC battery...

**Comment by radfast** [comment]
This seems to be issue #1113 in reverse.  I am looking at both of these issues urgently - we do not want duping.

**Comment by radfast** [comment]
This will be fixed in release 410.  The tested setup (screenshot in OP) now works perfectly.  Several bugs were found, so the Beam Receiver behaviour should be perfect, or at least improved, in other situations as well.
