### ISSUE TITLE
Empty Canister + Ex Nihilo Crucible doesn't fill canister

### ISSUE THREAD

**Issue by SirWilli** [micdoodle8/Galacticraft#1993]
hey,

after updating from build 345 to 399 it is no longer possible to fill the canister with oil via the crucible.
Same issue with latest version (408).

Probably related to this issue: https://github.com/micdoodle8/Galacticraft/issues/1952

**Comment by radfast** [comment]
Thank you for reporting, I will look at both issues.

**Comment by dj3520** [comment]
Do buckets work?

**Comment by SirWilli** [comment]
I haven't tried it yet but I can fill the crucible with a bucket, so I assume the other way around works too but I will test that later.

**Comment by SirWilli** [comment]
Yep, works fine with bucket

**Comment by SirWilli** [comment]
Works, thanks :)
