### ISSUE TITLE
Gracefully all GC slabs are now Mars Dungeon Brick Slabs

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#1994]
All ```GalacticraftCore:slabGCHalf``` block with any metadata (0..5) will "gracefully" turn into Mars Dungeon Brick Slab. The slab with metadata 1 will render with the correct texture but still the game thinks it is Mars Dungeon Brick Slab. :wink: 

![2016-01-07_21 37 20](https://cloud.githubusercontent.com/assets/6743303/12186115/dbf79af0-b586-11e5-918b-71b8671dff8f.png)

![2016-01-07_21 22 33](https://cloud.githubusercontent.com/assets/6743303/12185859/f996bd72-b584-11e5-8a2b-c01f141eb0d4.png)

Mods used in the test:
[1.7.10]bspkrsCore-universal-6.16.jar
[1.7.10]ArmorStatusHUD-client-1.28.jar
[1.7.10]DirectionHUD-client-1.24.jar
[1.7.10]StatusEffectHUD-client-1.27.jar
[1.7.10]DamageIndicatorsMod-3.2.0.jar
OptiFine_1.7.10_HD_U_C1.jar
journeymap-1.7.10-5.1.1-unlimited.jar
CodeChickenCore-1.7.10-1.0.7.47-universal.jar
NotEnoughItems-1.7.10-1.0.5.118-universal.jar
EasyConfigButton-1.0.jar
Galacticraft-Planets-1.7-3.0.12.408.jar
GalacticraftCore-1.7-3.0.12.408.jar
MicdoodleCore-1.7-3.0.12.408.jar

**Comment by radfast** [comment]
uh oh

I hate these slabs.  :/
