### ISSUE TITLE
Aluminium wire does not connect to 2 new IC2 machines

### ISSUE THREAD

**Issue by dj3520** [micdoodle8/Galacticraft#1995]
The electric kinetic generator and the electric heat generator. I've tested a few others but it seems like it's only these two. GC 406 and IC2 807
![image](https://cloud.githubusercontent.com/assets/8284194/12199952/e69e4dba-b5e9-11e5-9ad2-d775663385f2.png)
A bit sorry to report this after 410 came out. I had seen this in survival but didn't know if more machines were affected or not.

**Comment by radfast** [comment]
Please test what happens if you add components inside those IC2 machines so that they actually consume electricity.

e.g.  Electric Kinetic Generator needs Electric Motors added inside before it will do anything.

**Comment by dj3520** [comment]
I've done this in survival. No dice. IC2's wires connect immediately
without power draining components.

**Comment by radfast** [comment]
That world with the ore blocks is survival??

**Comment by dj3520** [comment]
No, but I have done this in survival a while ago. Result is the same.

**Comment by radfast** [comment]
This is a coding error (or deliberate design decision?) in IC2.

These two new machines - unlike all other IC2 machines - do not implement the IC2 API.
Specifically, they do not implement IEnergySink.
Therefore, they are not compatible, for now, with any other non-IC2 mods.  You can only use IC2 energy to power them.

Please report this to the IC2 developers, it needs them to implement IEnergySink on these two new electric machines.

**Comment by dj3520** [comment]
I've never actually sent them an issue before...

**Comment by dj3520** [comment]
http://bt.industrial-craft.net/view.php?id=1797
Mantis gives me a headache.

**Comment by radfast** [comment]
Good job.  I like the precision which Mantis forces :)

**Comment by radfast** [comment]
Except you made it sound like a Galacticraft issue.  I told you, **all** non-IC2 mods which offer IC2 energy compatibility will have the same issue.

**Comment by dj3520** [comment]
Dah,  all right.
I don't see any edit buttons. I'll add it as a note instead. Thanks for
catching that. Illustrates the problem is much bigger.

**Comment by dj3520** [comment]
> I like the precision which Mantis forces :)

Even to a person like me (who doesn't write fancy looking websites) it looks a bit like the internet did when it got popular. :floppy_disk: Lots of boxes, small box-sided fonts, poor color choices etc. Working and likely great in practice, but imho needs a facelift. HTML5 and CSS animations are a thing now.

**Comment by Aroma1997** [comment]
The IC2 energy net is made in a modular way, so you can separate the energy part from your TileEntity by registering another TileEntity with the same position to the energy net. This is a feature, not a bug. This also allows you to add EnergyNet delegates to Blocks / TileEntities that normally don't interact with the Energy Net. See player's E-Net-Bridge addon for an example.
If you want to support this, you can listen to the EnergyTile events and create a BlockPos -> TileEntity mapping yourself (or you could use IC2 core classes to use IC2's mapping).
So yeah, it's not a bug. It's a feature.

**Comment by radfast** [comment]
@Aroma1997 thank you for your input.

Are the methods needed to do this all exposed in IC2's API?  If not, then I do not fancy the work required from me to do this.  In case it's not obvious, Galacticraft is not an IC2 submod.  While I'm happy to implement inter-mod compatibility, if another mod is intentionally making it hard for me to do that then I'm not very motivated to do it.

**Comment by Aroma1997** [comment]
I need to correct myself. There is a simple way of getting the energy tile for a given TileEntity/position.
ic2.api.energy.EnergyNet.instance.getTile(World, BlockPos) will do that. 
( ic2.api.energy.EnergyNet.instance.getTileEntity(World, int, int, int) for Minecraft 1.7.10)
