### ISSUE TITLE
draining only one tank at the time

### ISSUE THREAD

**Issue by DarknessShadow** [micdoodle8/Galacticraft#1996]
I think it would be cool as an config option or as an upgraded oxygen gear that only one of the two tanks gets drained and not both simultaniously. It should switch to the tank after the first one is empty.

Its a bit annoying that you either get damage or the tanks arent fully drained yet when its time to switch them for new tanks.
<sub>In addition I'm one of those people that want to always have 100% filled tanks when I'm inside an oxygen room and it gets annoying to always recharge two tanks from 95% to 100% instead of one tank from 90% to 100%.</sub>

**Comment by dj3520** [comment]
Issue tracker is for issues. Forum is for suggestions. Allows more people
to see your suggestions and add their options.

**Comment by radfast** [comment]
It's something I've been meaning to implement for a long time.  Now done, thank you for raising.
