### ISSUE TITLE
Incorrect rocket inventory size prevents proper shift-click.

### ISSUE THREAD

**Issue by ProgrammerHero** [micdoodle8/Galacticraft#1997]
Using build 408, shift-clicking items directly into or out of rocket inventories treats the inventory as 27 slots regardless (the [transferStackInSlot](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/inventory/ContainerRocketInventory.java#L95) function). This means rockets with <27 inventory slots confuse their own inventory and the player's inventory (for shift-click actions), and rockets with >27 inventory slots will not allow players to shift click into or out of slots >27.

Manually picking up items and placing them in the slots still work, only shift-click is misbehaving.

**Comment by radfast** [comment]
Thank you for reporting, I'll take a look.

**Comment by radfast** [comment]
Thanks.  This was a long-standing bug from GC2 days, I fixed the rest in GC2 ... something like 18 months ago ... I don't know why I missed these three. :/

**Comment by ProgrammerHero** [comment]
That's a strange and annoying function - prone to little bugs like that :)

**Comment by radfast** [comment]
If you spot anything else in GC, your contributions will be most welcome - all help gratefully received :)
