### ISSUE TITLE
Unable to craft electric storage module with partially filled batteries.

### ISSUE THREAD

**Issue by dj3520** [micdoodle8/Galacticraft#1998]
My charging energy crystal gave them a bit of juice in my inventory before I noticed it. Figured I was fine.
![image](https://cloud.githubusercontent.com/assets/8284194/12213626/ce5345ca-b649-11e5-96d3-c5093765ed49.png)
nope

**Comment by radfast** [comment]
Intended behaviour.  Empty those batteries, then craft.

**Comment by dj3520** [comment]
Gah, fine. Makes sense anyway
