### ISSUE TITLE
Website micdoodle8.com is down

### ISSUE THREAD

**Issue by Dream-Master** [micdoodle8/Galacticraft#1999]
Webside http://micdoodle8.com/ is down.

**Comment by dj3520** [comment]
Jenkins is too I believe

**Comment by Dream-Master** [comment]
yes

**Comment by radfast** [comment]
Only @micdoodle8 can fix this.  I have messaged him.  Given that it's Saturday and currently 05:00am in the US/Canada, it may be a while before this gets fixed.

**Comment by EzerArch** [comment]
The techguys who are taking care of the server are awere of the problem already, and working on it, just it'll take a while to fix.

**Comment by radfast** [comment]
Something is happening, it now brings up a HostGator page.

**Comment by jeffluo35** [comment]
They're probably gradually re-building the site, now it just displays lots of example text.

**Comment by radfast** [comment]
There will be a temporary site for the next 1 day or so, while the main server is repaired.
The temporary site will have the latest GC version for download (411).
More updates on Twitter: @micdoodle8 and @radfast

**Comment by radfast** [comment]
The temporary site is now up

**Comment by Dream-Master** [comment]
@radfast 
can you give us the link please.

**Comment by EzerArch** [comment]
> can you give us the link please.

It's the same. But the design is quite different.

**Comment by katzenpapst** [comment]
What about the forum?

**Comment by EzerArch** [comment]
> What about the forum?

It will take a while. Probably 1 or 2 days. The download site is the priority.

**Comment by radfast** [comment]
The current temporary [www.micdoodle8.com](www.micdoodle8.com) site has download links for version 3.0.12.411 of Galacticraft.

Build 411 is stable - the only bug I know about is that in that build, a vanilla Bed placed in a space world cannot be destroyed (I went a bit too far when stopping beds exploding in space, lol).

For anyone who wants the **latest** build - which is 414a - download links are in [this post] (https://github.com/micdoodle8/Galacticraft/issues/2001#issuecomment-171146658)

**Comment by radfast** [comment]
The server is now up again.  Yay!  Thanks to the behind-the-scenes guys who fixed this.

**Comment by Wolfofthenyght** [comment]
Uhm, the site appears to be offline again :( Is this a regular thing? Should I just simply check back later? Thank you! Looking forward to playing with the newest version of GC3 :3

**Comment by EzerArch** [comment]
@Wolfofthenyght, we are aware of the problem, so are micdoodle. Follow up: #2151
