### ISSUE TITLE
Removing Arc Lamp sometimes leaves lighted areas behind (relog fixes)

### ISSUE THREAD

**Issue by radfast** [micdoodle8/Galacticraft#2000]
As in the header.  Place Arc Lamp -> it lights up the area.  Destroy Arc Lamp -> sometimes not all the light in the area is removed.

Seems to be a client-side issue only: the server has correctly removed all the lighting blocks.  (As confirmed by re-logging.)

Looking at the code, the lighting is only changed on the server, and a simple world.setBlock() command is used.  Therefore this appears to be a network issue.  I'm playing on a same-PC server using localhost.  

I am interested to see if other people also have this issue.

It suggests there may be packet loss or something weirder happening.

**Comment by Solarstrike** [comment]
Congrats on 2k issues!

**Comment by radfast** [comment]
Oh!  Thank you :)  I'm not sure that's anything to be proud of ... maybe congratulate when there are 2k *closed* issues.

---

More on the issue.  Definitely a BlockBrightAir is remaining on the client when it should not ... re-logging fixes it.  I can find the location of the bright block on the client, block it in and the light disappears, reveal it again and the light re-appears.

No other mods installed apart from NEI.

**Comment by radfast** [comment]
It's very strange, this one.  Maybe a bug in vanilla?
I'm looking at net.minecraft.server.management.PlayerManager.markBlockForUpdate()

**Comment by Zer0id** [comment]
I had a similar bug few times, but server-sided. and w/o GC installed.
When i dig room for a mob farm in Nether and removing single lava blocks in netherrack sometimes light still remains and prevent mobs from spawning from placed spawner.
Each time I relog I can see a bright area for a few seconds, then room becomes dark, but only client-sided, mobs still not spawning.

I can find the location of the bright block on the client, block it in and the light disappears  
--same. and mobs start spawning
reveal it again and the light re-appears
--and mobs stop spawning again

**Comment by radfast** [comment]
Thank you, that's very helpful to know.  Seems like it could be a bug in the vanilla lighting engine then.

**Comment by L-Clouds** [comment]
FloodLights also has off-and-on had a problem exactly like this https://github.com/Keridos/FloodLights/issues/51 so if you do figure out a fix, I'd encourage you to share it with that author. :)

**Comment by Keridos** [comment]
This seems to be a vanilla forge/Minecraft bug. No idea on how to fix that. Block Updates apparently do not fix it.

**Comment by Cracks777** [comment]
Can BlockBrightAir cause lag of FPS Drop, if i remove several arc lights in the area and save the world, the area remains lighted. if i close the server and open the world in mc edit it shows lots of BlockBrightAir blocks.

**Comment by Keridos** [comment]
I cannot speak for the GC Mod, but in my floodlights mod the lights that are left behind disappear on relog in SMP / Save+Quit and rejoin in SP. ANd my debug item that shows any of my light blocks shows none even with the phantom lights. It seems for some reason the light level is never correctly changed.

**Comment by radfast** [comment]
Thank you @Keridos, I am seeing the same.  (Hence "relog fixes" in the thread title ...)

My memory says this did not used to be an issue 1 year ago when I first made this block, that would have been with older Forge versions (before 1291) - I'll do some more testing some time.

-----

@Cracks777 the block BlockBrightAir does not create lag or any problems except unwanted lighting.  It should automatically be removed if you remove all Arc Lamps.  (But if you WorldEdit or MCEdit away the Arc Lamps, I guess strange things might happen.)

**Comment by Keridos** [comment]
I can confirm that the it does not seem to be a misplaced block (i use airlike light blocks aswell). IN a later version of Floodlights I added a debug tool that renders all blocks that have the corresponding TE for the block. When turning off/destroying the actual machine that places them the TileEntities and I am fairly sure, the corresponding block is removed. But for some of them the lighting does not seem to update. Another weird thing I noticed that it seems to affect at least mostly the same block every time. Have not yet found out any pattern.

**Comment by radfast** [comment]
Yes, I agree, see above - I think it is a bug in the vanilla lighting engine: the old block light value remains even though the block which 'generates' that light value has been removed.  It seems likely the bug is in ```net.minecraft.server.management.PlayerManager.markBlockForUpdate()```.  Maybe I'll find time at some point to find the bug ...  Though should I be debugging Mojang's code for free? I'm not sure how I feel about that...

**Comment by Keridos** [comment]
This seems to be happening on 1.8.9 and 1.9.4 as well. I tried a bunch of things over block updates and notifyLightSet(pos), still no success. Though it seems this happens in the mode of my lights that should place by far the most blocks. When not using much blocks it seems to work fine.

**Comment by radfast** [comment]
This issue is now fixed in 1.8.9+.  Basically, by having the Arc Lamp generate its brightly lit blocks client-side as well as server side.

In 1.8.9+, there seems to be a bug in vanilla Minecraft where if:
* several blocks which change lighting levels are changed on the server inside the same tick
* some of those blocks affect light levels in chunks outside their own (this is fairly normal, for any bright block)
* then a small percentage, < 10%, of the server -> client block updating fails to properly update the light levels client-side in the nearby chunks - usually only one or two block positions out of hundreds are wrong, but it's enough to see it

I guess this can be reproduced in vanilla by building a few Glowstone blocks near each other, then exploding them all together with TNT.


------


Closing this, because it's fixed in 1.8.9+, and I can't spend time fixing bugs in vanilla Minecraft.
