### ISSUE TITLE
Fuel lines / Reservoirs from RotaryCraft are not working with Fuel Loader from Galacticraft.

### ISSUE THREAD

**Issue by C1ffisme** [micdoodle8/Galacticraft#2005]
The game does not crash, but connecting a fuel line from a reservoir to a fuel loader with fuel lines currently does not work. The Fuel Loader will not fill with fuel.

I have the latest version of Galacticraft (3.0.12.411), and RotaryCraft (v10d).

I am not sure if this is a RotaryCraft issue, but if it is, then I cannot post it there, because it seems the [RotaryCraft github page](https://github.com/ReikaKalseki/RotaryCraft) does not support issues.

**Comment by radfast** [comment]
Please try out Galacticraft build 427, it should become available to download later today.

**Comment by C1ffisme** [comment]
Nice, not exactly what I was going for with using jet fuel instead of GC fuel, but this might prove interesting.

Actually, the problem I had was with transporting GC fuel.

**Comment by radfast** [comment]
Please check your Galacticraft config ```.minecraft/config/Galacticraft/core.conf```.  You are looking for this config entry:
>     ```B:"Use legacy fuelgc fluid registration"=false```

If that says ```true``` in your config, change it to ```false```.

Apart from that there's nothing we can do from our side to help this: the GC fuel should be transported, the Fuel Line transports anything named "fuel" and that is the name of GC fuel.

(If you have a tank of GC fuel created in an older version of GC, before build 358, that could be a specific problem, in that case ask for further advice.)

**Comment by C1ffisme** [comment]
Nope, the configuration is false. The Fuel actually goes through the pipes, it just doesn't enter the fuel loader, though. (Sorry for the confusion, I should have worded it differently.) And the only version of Galacticraft I've had is build 411.

**Comment by radfast** [comment]
OK, thanks for the further info.  I'll take another look at this later today, this definitely ought to work.

**Comment by radfast** [comment]
Please try build 427, now available.  In my testing, a Fuel Lines is filling a Fuel Loader's tanks correctly.

The only minor issue I am noticing is that if you use Galacticraft fuel canisters to fill the Reservoir, right-clicking the canister on the Reservoir, it does not return the empty canister to you as it should.  I think this is likely a bug in RotaryCraft.  EnderIO tanks have, or used to have, a similar bug.

**Comment by C1ffisme** [comment]
I'll give it a go. :)
