### ISSUE TITLE
Water electrolyzer

### ISSUE THREAD

**Issue by ivanich-fmf** [micdoodle8/Galacticraft#2016]
Water electrolyzer continuing produce oxygen when hydrogen tank is full (Forge 10.13.4.1558 for Minecraft 1.7.10 GalacticCraft mod 3.0.12.411).

**Comment by dj3520** [comment]
Right now the behavior is if either tank has space the machine with run.
Not 100% sure but this might be intended.

**Comment by radfast** [comment]
This is intended.  :)  Thank you @dj3520

**Comment by Solarstrike** [comment]
2016 issues!

**Comment by radfast** [comment]
Lol.  I'd be happier with 2016 issues fixed.
