### ISSUE TITLE
Global entities, conflicts, and different code in GC Core and GC Mars

### ISSUE THREAD

**Issue by L-Clouds** [micdoodle8/Galacticraft#2030]
#1896 seems relevant.

I was getting a tough-to-pin-down error with Reika's VoidMonster in my local modpack.  When I Googled the exact error, another user's post pointed to a conflict with Galacticraft.

> ---- Minecraft Crash Report ----
> // Oops.
> 
> Time: 1/15/16 12:36 AM
> Description: Initializing game
> 
> java.lang.IllegalArgumentException: ID is already registered: 127
> 	at net.minecraft.entity.EntityList.func_75618_a(EntityList.java:93)
> 	at cpw.mods.fml.common.registry.EntityRegistry.registerGlobalEntityID(EntityRegistry.java:199)
> 	at Reika.VoidMonster.VoidMonster.load(VoidMonster.java:94)

Entity 127 was a Sludgeling...or Slimeling...one of those.

I have a few mods which register global entities, VoidMonster included.  Although this practice is discouraged, they all seem to do it the prescribed way, with findGlobalUniqueEntityId and registerGlobalEntityID.  An entity ID dump shows that I have plenty of entity IDs still available and I must conclude that Galacticraft, or at least Galacticraft Mars, is interfering with the discouraged but properly implemented way of registering global entities.

It appears commit a692d6f made a change in GCCoreUtil.java that isn't identically reflected in MarsModule.java although frankly I'm not sure if that's at the root of the problem or not.  My best guess is that whatever Galacticraft is doing, it interferes with findGlobalUniqueEntityId() which may then return Galacticraft-occupied IDs.

In my specific case, by making an illicit bytecode edit to MarsModule.java to test, changing line 234 to be int eggID = 127; leads to MarsModule starting its entities at ID 128 and alleviating the error.

**Comment by radfast** [comment]
Thank you for spotting this, and thank you x10 for spotting the cause.

The cause is actually the reverse.  a692d6f fixes this type of issue in GCCoreUtil.  I wasn't aware (had forgotten) that MarsModule had similar code, fixing that now.

I agree with you that we should provide compatibility with mods which register global entities, because they are *out there*.  A lot of devs would just tell you to go tell the other mods not to use global entities...
