### ISSUE TITLE
vanishing chunks in asteroid dimension

### ISSUE THREAD

**Issue by Zer0id** [micdoodle8/Galacticraft#2033]
all chunks, that contains no asteroid, vanishing after relog or going far from them and back

already few missing chunks are seen on map:
![2016-01-17_20 28 50](https://cloud.githubusercontent.com/assets/14043791/12379125/806c305c-bd64-11e5-872a-1efa60da5fe0.jpg)

and this is what happens after relog:
![2016-01-17_20 29 09](https://cloud.githubusercontent.com/assets/14043791/12379123/8069fa8a-bd64-11e5-895d-151a8812bb4f.jpg)

my 'house' built on chunk border before:
![2016-01-17_20 28 31](https://cloud.githubusercontent.com/assets/14043791/12379124/8069e8ba-bd64-11e5-9b77-a6af50c7ce21.jpg)
and afer relog:
![2016-01-17_20 29 33](https://cloud.githubusercontent.com/assets/14043791/12379126/806ca320-bd64-11e5-92a0-71d182516a5d.jpg)

**Comment by radfast** [comment]
Nice house :)  Thank you, that helps me understand the issue.

Can this be connected with saving?  Please test a forced save before you logout, using ```/save-all```

**Comment by Zer0id** [comment]
same thing even after saving chunks

It seems chunks disappear only once. after that I can build something in that 'clear' chunk and it doesnt vanish even after few relogs

**Comment by radfast** [comment]
* Which Galacticraft version?
* Which Forge version?
* SSP or playing on a server?  If it's a server, is it regular / Cauldron / other?
* Please list other mods installed

**Comment by Zer0id** [comment]
GC  .424 and .375 builds
Forge 10.13.4.1614
both SSP and Cauldron server
tried with only GC installed. on screens above GC+NEI+Rei's minimap

**Comment by radfast** [comment]
Perfect info, thanks for that.

**Comment by radfast** [comment]
Thanks for raising this issue.

Turns out the "empty" map chunks were being incorrectly saved in a freshly generated Asteroids dimension.  This bug has been in Galacticraft for around 1 year but nobody noticed before.  So kudos to you :)

**Comment by radfast** [comment]
Fixed in build 427, now available.
