### ISSUE TITLE
Galaxy Map; zoom in issue on other star systems.

### ISSUE THREAD

**Issue by KingOfMiners** [micdoodle8/Galacticraft#2034]
There is an issue when zooming in to other planets and star systems where it zooms into empty space, but when I try to zoom in on the normal solar system it works fine. This prevents add on developers and I from adding accessible moons for other planets.

![galacticraft error](https://cloud.githubusercontent.com/assets/13870019/12381968/6efff46a-bd51-11e5-8213-e48cf933d4f8.gif)

**Comment by radfast** [comment]
Thank you, I see the problem in your animated GIF.  (Nice job!)

Please give an example of a current AddOn where I can reproduce this problem, for testing...

Will I see this problem in Galaxy Space or More Planets?  @BlesseNtumble  @SteveKunG

**Comment by BlesseNtumble** [comment]
This is because the coordinates of Z, if I'm not mistaken.
.setMapPosition(new Vector3(1.0F, -2.0F, 0.0F));

**Comment by radfast** [comment]
Thank you @BlesseNtumble 

Seems like a coding issue in the Add On then.  Not a Galacticraft issue.
