### ISSUE TITLE
Crash when Dynamic Lights is installed

### ISSUE THREAD

**Issue by Nosiphus** [micdoodle8/Galacticraft#2036]
http://pastebin.com/SKA7fEKv

Whenever I load Galacticraft-1.7 builds 407 and above, Dynamic Lights crashes. This doesn't occur on Galacticraft-1.7 Build 406 and below.

**Comment by radfast** [comment]
Thank you for reporting, we need to fix this asap.

Small detail, but I think the change https://github.com/micdoodle8/Galacticraft/commit/cb11134a11ff5317b4453e41f405ac24e234edc7 which seems to be causing this crash was first in GC build 411.

I can see it is connected with a fake player (dummy entity) created in Dynamic Light.

I am looking at how we can stop this crash happening - really I'm surprised that fake player doesn't have a lot of other issues even apart from this, if it is triggering Galacticraft player code.

**Comment by radfast** [comment]
Please try build 426 - [quick link to download all three files](http://ci.micdoodle8.com/job/Galacticraft-1.7/426/).  I hope that fixes this, please re-open if not.

Any players who currently have GC versions 411-425 and Dynamic Lights will need to update to this version 426.

**Comment by Nosiphus** [comment]
Thanks for the rather quick response time!

**Comment by radfast** [comment]
Np :)  Did this fix it?

**Comment by Nosiphus** [comment]
Yes. This did indeed fix it.
