### ISSUE TITLE
Energy Beam transmission does not resume once destination is no longer full. (To GC only)

### ISSUE THREAD

**Issue by dj3520** [micdoodle8/Galacticraft#2040]
How to reproduce:
- Connect two clusters via a beam
- Use beam to fill the receiving cluster. This will stop the energy transfer as there isn't anywhere for it to go.
- Fill the transmitting cluster slightly to show the transfer has stopped
- Drain energy from the receiving cluster. This should start the transfer again.
- Observe no energy drain on transmitting cluster and that the receiving cluster does not fill. This shows evidence of no energy transfer.

As far as I can tell you have to have the transfer stop via the receiving end being full. An important thing to note is this will **not** happen when transferring power to a beam receiver that is not GC. IC2 transmit starts and stops normally. Tested with GC423 and will update and retest soon.

**Comment by radfast** [comment]
Thank you for reporting.  If it is happening in 423, it will also happen in 428, nothing has changed for Beam Receivers recently.

**Comment by dj3520** [comment]
Updated. Persists with 428

**Comment by dj3520** [comment]
Just tested this with GC4 v69 and it doesn't appear to be there. However with GC3 481 the issue persists.
