### ISSUE TITLE
Problems with rocket landing in a different world (Multiverse)

### ISSUE THREAD

**Issue by finnbo11** [micdoodle8/Galacticraft#2041]
I launch off with a rocket in let's call this world 2 (not main world(multiverse world)) this world is a game playing world and then when I decide to come down from space the world I land in is world 1 (server spawn) which is the main base world. Is there anyway I can change it so I launch off in world 2 then I land back in world 2 or is this impossible. I'm using KCauldron-1.7.10-1566, Galacticraftcore, micdoodlecore and planets 1.7-3.0.12.375 and multiverse 2.5-b699 (beta). Any help would be much appreciated!

**Comment by radfast** [comment]
Make sure World 2 has dimension ID 0.  Set your server spawn world to a different dimension ID, not 0.

Also read this: http://wiki.micdoodle8.com/wiki/Compatibility
and this: http://wiki.micdoodle8.com/wiki/Tutorials/Space_Station_for_Server_Admins (some now out of date, but a lot of useful info)
