### ISSUE TITLE
ClassCastException placing conduit near GC arc lamp

### ISSUE THREAD

**Issue by plaguewolf** [micdoodle8/Galacticraft#2042]
relevant logs: http://pastebin.com/qSGah5N6

enderIO 2.3.0.421 beta
galacticraft 3.0.12.375

game locked up then crashed, when placing a teir 1 conduit, on the ceiling, near a GC arc lamp.

also posted on https://github.com/SleepyTrousers/EnderIO/issues/3157

**Comment by radfast** [comment]
It's an EnderIO issue.  The same thing would happen if the GC Arc Lamp was a vanilla furnace or chest.

Not relevant to this, but you really should be using GC 3.0.12.429.

**Comment by plaguewolf** [comment]
k, good to know, i had assumed it was enderio thing, because ive had that issue before with enderio, but thought id link/post here, just in case it was relevant.

and thanks, i hadnt realised there was a new GC out.

**Comment by HenryLoenwind** [comment]
Can you elaborate on what we are doing wrong here?

**Comment by radfast** [comment]
> ```crazypants.enderio.conduit.render.ConduitBundleRenderer.renderWorldBlock(ConduitBundleRenderer.java:127) ```

I assume you are not doing an ```instanceof IConduitBundle``` check, but TBH I have not read your code to see.

**Comment by HenryLoenwind** [comment]
No we are not. It is not something you normally have to do in the block renderer. It is not as if Minecraft was using a dice to decide which renderer to call. So how does your TileEntity end up in our block?

**Comment by radfast** [comment]
I'm sorry I have no idea how this happened.  The TileEntityArcLamp is a straightforward TileEntity - unlike some in Galacticraft, it has no interfaces with other mods, no runtime patching, and it does not instantiate anything except the vanilla TileEntity class.  Its renderer is registered here: https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/proxy/ClientProxyCore.java#L343

It sounds like some block coordinates may have changed, but I don't really see how that can happen.  The TileEntityArcLamp does not move.  Maybe the player has some other system in his base which is moving blocks?  MFFS force fields or something like that, I really don't know.

@plaguewolf can you post screenshots of the base, and a save file of that region?

**Comment by plaguewolf** [comment]
will upload the save in a bit, but do you need screens for the whole area?

heres the bit that was affected:
![2016-01-25_14 49 15](https://cloud.githubusercontent.com/assets/7838485/12564220/bb2ce00a-c373-11e5-82ee-b0f08fb3131b.png)

the conduit was placed where the arc lamp used to be, so im suspecting the tile entity was somehow derped, and placing the conduit there tried to overwrite the TE, or something, dunno. never messed with TE before, more than just basic stuff.

**Comment by radfast** [comment]
Thank you for the additional explanation.  I can see what is going on.

@HenryLoenwind I'm very sorry, this was a bug in GC code.  We failed to invalidate the tile properly.  There is no issue in EnderIO.   Looks like we've had this bug hidden in the code for 15+ months and it has never crashed before.

**Comment by HenryLoenwind** [comment]
thx radfast, that went better than I hoped. Sorry for pushing that hard, but I have been looking at those kinds of crashes for months now I could never find a reason.
