### ISSUE TITLE
[Minor + Rendering] Full oxygen canisters show as empty in HUD

### ISSUE THREAD

**Issue by dj3520** [micdoodle8/Galacticraft#2043]
So I was admiring the new textures in GC428 next to my flying chickens when I noticed something:
![image](https://cloud.githubusercontent.com/assets/8284194/12532754/8bcdce4a-c1e9-11e5-9bad-c21f357e89af.png)

WAT. Oh well it's fine I'll just fill it.

![image](https://cloud.githubusercontent.com/assets/8284194/12532755/b236e2b0-c1e9-11e5-91b5-29920e0d2840.png)

It's full? Welp bug report time. Just to check, I filled my other one:
![image](https://cloud.githubusercontent.com/assets/8284194/12532759/d4aa924c-c1e9-11e5-81c4-fe3082dcc060.png)

And with it on:
![image](https://cloud.githubusercontent.com/assets/8284194/12532761/e07f7b46-c1e9-11e5-84bf-93b752ac892f.png)

![image](https://cloud.githubusercontent.com/assets/8284194/12532763/eb44a09c-c1e9-11e5-9e42-f23cf8f7dd11.png)

Welp huh.

**Comment by dj3520** [comment]
Forgot to mention this happens with and without Optifine

**Comment by C1ffisme** [comment]
I can confirm this, occasionally the oxygen bars do not update when you place new tanks in their slots.

**Comment by radfast** [comment]
I need step-by-step instructions on how to reproduce this.
Not screenshots.
Please.

**Comment by dj3520** [comment]
Refill a canister from your own back. Worked 100% for me. Helps to do it in
a sealed space, since I think an update tick fixes it.

**Comment by Cracks777** [comment]
something just to figure out if its supposed to happen or not, relating to this issue sort of, when im on the moon, only one of the tanks are drawn from at a time? is this normal?

**Comment by dj3520** [comment]
Yes this was changed recently to what you're seeing.

**Comment by dj3520** [comment]
Made a not so short video to show what I'm seeing.
Also shows #1963 in action.
https://www.youtube.com/watch?v=mIER5yCZkIE

**Comment by EzerArch** [comment]
> Also shows #1963 in action.

My reply here: https://github.com/micdoodle8/Galacticraft/issues/1963#issuecomment-174826153

**Comment by C1ffisme** [comment]
I think the problem is that the HUD doesn't re-draw until you breathe from the oxygen tanks. But that's just a guess, since they don't update in oxygen filled enviroments.

**Comment by dj3520** [comment]
Heads up this also happens when switching sync clones.

>I think the problem is that the HUD doesn't re-draw until you breathe from the oxygen tanks.

I'm actually pretty sure this is what is happening. After introduction of a tank, GC either doesn't update the HUD properly or doesn't get the right numerical value for updating said GUI.

**Comment by C1ffisme** [comment]
Just to test... Maybe someone should try putting a half-full tank on in a breathable area, if it's not the problem @dj3520 mentioned, it may be that the HUD loops over, so that 2700 oxygen = 0 oxygen in the HUD.

**Comment by radfast** [comment]
This issue is fixed in build 441 now available.

**Comment by dj3520** [comment]
Apparently persists in 442 as of #2096
