### ISSUE TITLE
Space Station Impossible to create

### ISSUE THREAD

**Issue by appollon41** [micdoodle8/Galacticraft#2048]
Hello, 
I wanted to create a space station in a server, but I could not.
I tried in SinglePlayer, and there is not ANY Create button in the galaxy tab. I did all fine, took all materials needed, but could not at least see the create button.
I'm here If you need any file from me.

appollon41

**Comment by radfast** [comment]
You have to ride a rocket to create a space station.

If you only use the 'M' key to see the Galaxy map, you cannot create a space station.

**Comment by appollon41** [comment]
No of course I did it! I laugncher a Tier 2 rocket and went on the Galaxy thing!

**Comment by appollon41** [comment]
launched

**Comment by radfast** [comment]
I added this:
Now move your mouse to the Overworld, and click on the Overworld. Then you can see the CREATE button.
http://wiki.micdoodle8.com/wiki/Planet_Selection_Screen

If this isn't working, please provide screenshots.

**Comment by appollon41** [comment]
and there is not the create button as I see in every tutorial, let's play etc

**Comment by appollon41** [comment]
Tried it, doesn't work. I'll take a ss now

**Comment by appollon41** [comment]
![buggc1](https://cloud.githubusercontent.com/assets/16938618/12646132/83c28f90-c5ce-11e5-978a-6213171e4fd1.png)
here it is. And it's in singleplayer mode, so it's not the server blocking it. (I'm playing on a server, so I tried it in single player, and both of them don't work.)

**Comment by appollon41** [comment]
And the space-station is enabled in the config file, although it's for servers

**Comment by radfast** [comment]
A config setting has set the Overworld to be unreachable in rockets.  Take a look in ```.minecraft/config/Galacticraft/core.conf```, I think you will see this:

    B:"Disable rockets from returning to Overworld"=true


If you can't reach the planet (its tier of rocket is shown in red) then you can't create a space station.

(Otherwise you would have a way to reach the planet ... just fall out of the space station.)

This looks like a custom modpack, any further issues like this please resolve them with the modpack maker.

**Comment by appollon41** [comment]
Imma see that. Because I'm the only one to have this problem in the server, and everyone uses the same pack (Galactic Science) and lots did create a personnal Space Station :/

**Comment by appollon41** [comment]
It works now! Thanks a lot you're amazing :D

**Comment by radfast** [comment]
@Slind14 I think you need to cover this in Galactic Science documentation :)

I'm not sure why some players have the 'disable rockets to overworld' config setting true and others do not?

**Comment by XeMo97** [comment]
@radfast So I've to set it to **false**?

**Comment by XeMo97** [comment]
Worked!

**Comment by XeMo97** [comment]
@radfast Next problem: I can not reach the overworld by falling off the space station and I can't reach it with flying directly to it. What now?

**Comment by radfast** [comment]
I don't understand.  Are you reporting a bug or asking for help?

If reporting a bug, please precisely specify the bug and exact conditions to reproduce it (including config settings).

If asking for help, I hope that Galactic Science modpack players can help you - or try the official Galacticraft forum at http://forum.micdoodle8.com/index.php

**Comment by Slind14** [comment]
The overworld is destroyed, you should be not be able to get there. If you try to, you go into a death loop, depending on the modpack version.

**Comment by Slind14** [comment]
@radfast do you recall if something regarding this matter changed recently. We have a few players with space stations on the server but the earth is disabled. Those space stations could be half a year old though.
