### ISSUE TITLE
Space Station Spin results in centrifugal force player motion even when feet are on a solid block.

### ISSUE THREAD

**Issue by BumblebeeCannon** [micdoodle8/Galacticraft#2049]
Hello, recently, I've been constructing a Space Station for my friends and I to live on on my server. After making it large enough and adding spin thrusters, the outward push from the center of gravity comes into affect (as expected), however, it continues to move us around slightly, even when our feet on planted on the ground. I read up that this should only be happening while floating, not while standing. If you need any more information, let me know, thank you.

By the way, I think an option for this in the config could be nice, to reduce it if people don't like it, thanks!

**Comment by radfast** [comment]
Thanks, I'll take a look.

You must have a large space station to see this.  I like large space stations, any chance of a screenshot please?  :)

I don't see why a config is needed, if players don't want this type of effect on a space station then don't use Spin Thrusters...

**Comment by BumblebeeCannon** [comment]
I'll send you a screenshot soon, my developers are currently working on the server (preparing it for a larger release). As for not using the spin thrusters, there also seems to be a bug where players get stuck on ceilings and can't go downwards unless a spin thruster is active. It really gets annoying, if you can take a look at that to, that'd be great! Thanks.

**Comment by EzerArch** [comment]
> there also seems to be a bug where players get stuck on ceilings and can't go downwards

@BumblebeeCannon, it's a known issue:  #1833

**Comment by BumblebeeCannon** [comment]
@EzerArch Yeah, I figured. I was just letting him know why I was using the Spin Thrusters. But thanks anyway,

**Comment by BumblebeeCannon** [comment]
http://imgur.com/a/nGR52

Here's the station, we just started on it today, so it's not too large, we are focusing on making it habitable and the interior before expansion and making the exterior look great, but I think we've made good progress for one day.

**Comment by radfast** [comment]
This issue is maybe fixed in latest build [438](http://ci.micdoodle8.com/job/Galacticraft-1.7/438/) - I'd be grateful if you or your players would try it out.

**Comment by BumblebeeCannon** [comment]
No problem, I'll update the server tonight and let you know if we find any bugs with it within the next day or so, thanks!

**Comment by BumblebeeCannon** [comment]
Yep, everything seems to be working, thanks!

**Comment by radfast** [comment]
Great stuff.  Thanks for confirming.
