### ISSUE TITLE
Crashing when creating steel compressed plates (dev build)

### ISSUE THREAD

**Issue by b0bst3r** [micdoodle8/Galacticraft#2050]
http://pastebin.com/q2QXcHKk
In ingot compressor or electric compressor.

Using MicdoodleCore-1.7-3.0.12.434.jar
GalacticraftCore-1.7-3.0.12.434.jar
Galacticraft-Planets-1.7-3.0.12.434.jar

Using dev versions as I also have GalaxySpace-1.0.5+STABLE.jar which requires 426 onwards and 434 is all I can find.

Source- http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2412548-1-7-10-galaxy-space-addon-for-galacticraft-3?comment=130

**Comment by simonappleton** [comment]
Same here, have loaded just Galacticraft 434 and forge 1230 and insta-crash when creating steel plates.

**Comment by b0bst3r** [comment]
I lied I had Galaxy space 1.0.4 but having issues getting 1.0.5 running, not that this is the issue.

**Comment by radfast** [comment]
Fixed in 435.  Get it directly from [here](http://ci.micdoodle8.com/job/Galacticraft-1.7/435/)

Thanks for bringing this to our attention quickly, I hope not too many people will be affected.  434 is only around 12 hours old.

**Comment by b0bst3r** [comment]
Thanks Radfast
