### ISSUE TITLE
Sealed Pipes for other mods

### ISSUE THREAD

**Issue by themechman** [micdoodle8/Galacticraft#2052]
If memory serves me correctly, you guys used to have sealed cables for other mods like Mekanism, Applied Energistics, and EnderIO.

Did these get removed? Do I need to do something to make these available? I only have IC2exp cables available (aside from GC's).

**Comment by radfast** [comment]
Read the guidelines before creating issues.  They were shown to you at the top of the page when you pressed that 'New Issue' button.

[This](http://forum.micdoodle8.com/index.php?threads/suggestion-request-sealed-pipe-cable-support-for-ae2-td-eio-etc.6260/) may help you.

**Comment by themechman** [comment]
Thank you radfast. I've posted suggestions and bugs here before and was not aware things have changed. I will post add'l info on that thread.

**Comment by radfast** [comment]
We've always had the same policy about suggestions.  They've been written down in the [Notes for contributors](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) for at least the last ~18 months.

**Comment by themechman** [comment]
I am not getting the confirmation email's for your forum. The email is quite valid.

**Comment by radfast** [comment]
Hmm, sorry I don't know why that would be - I can pass a message to the site tech guy but it might be a few days before anything happens.

If you can post the additional info here, I would appreciate it.  I can copy it over to the forum.  I am interested in all reasoned arguments for blocks which need sealing.  Each one is a huge amount of coding work.  I see ME cable as the top priority.

Several reasons for keeping suggestions on the forum.  The main ones:
1. It gives other players a chance to comment and discuss, which usually makes for better suggestions in the end
2. The issues list is only for current issues, it would get out of hand if it had all the suggestions as well

**Comment by themechman** [comment]
Thank you. I have not used GC since a year ago, but now that my server is devoid of players I can finally get back to resetting the world and finally build that space station!

AE is my primary concern as the P2P tunnels can assist other mods in transferring using a single cable system.

TD/TE now has their own paneling system for hiding only their ducts so forge microblocks cannot be used to cover them. I am guessing it is because of the new cryo-stablized flux-ducts. While the tesseracts are impressive devices, they are far too expensive for a 3-10 block distance.

Mekanism has pipes, ducts and good cables now as well. These accept forge microblocks and can be placed in hollow panels.

Since you're using universal power api, the psudo-unlimited heavy aluminum cable is okay, but my setups generally push 18M+ RF/t at their peak. Not even mekanism's own cables can handle this kind of torture (The ultimate caps at 1.58M RF/t).

**Comment by EzerArch** [comment]
> Hmm, sorry I don't know why that would be - I can pass a message to the site tech guy but it might be a few days before anything happens.

My email box keeps flagging as suspicious the messages from micdoodle8.com, so that I had to create an email redirect to force those emails to my inbox, otherwise they would be sent them to the SPAM folder, still warns me about fishing attempt.

**Comment by radfast** [comment]
> Since you're using universal power api

You seem slightly confused.  We **wrote** what you're calling universal power api.

**Comment by themechman** [comment]
> You seem slightly confused. We wrote what you're calling universal power api.

I learn something new every day radfast.
