### ISSUE TITLE
Tile Ingot Compressor broken in dev builds beyond v430?

### ISSUE THREAD

**Issue by Robijnvogel** [micdoodle8/Galacticraft#2053]
It is said that using the Ingot Compressor in GC versions past v430 crashes the game.
The More Planets mod requires v433.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287888?page=138#c2776

**Comment by BlesseNtumble** [comment]
http://ci.micdoodle8.com/job/Galacticraft-1.7/435/

**Comment by Robijnvogel** [comment]
Wow, you guys are fast!
Keeping good tabs on the Minecraft Forums as well. Chapeau!

**Comment by radfast** [comment]
If there's incorrect info on the Minecraft Forums please can someone put them straight.
I don't have time to do everything.

**Comment by Robijnvogel** [comment]
That was an actual compliment.
No sarcasm :)
