### ISSUE TITLE
Crash when starting Challenge mode

### ISSUE THREAD

**Issue by fayer3** [micdoodle8/Galacticraft#2058]
just wanted to try the new challenge mode, but when starting the game the game crashed.
after restarting I could play normally.

<del>this crash can be reproduced by starting a new world with that seed: -2647088854889722269</del>
happens now on every new world :(

crash report: http://pastebin.com/C7CZPUsJ
fml-client-latest.log: http://pastebin.com/CzR7S93i

Galacticraft version: 3.0.12.437
forge version: 13.4.1566

**Comment by radfast** [comment]
Thanks, seems to be a Forge issue - I don't think this would happen in Forge 13.4.1448.

Anyhow, we'll fix it in next build 438.

**Comment by radfast** [comment]
Build [438](http://ci.micdoodle8.com/job/Galacticraft-1.7/438/) is now available with this fix.
