### ISSUE TITLE
Fatal error with placement of sealable stone fluid pipe [v3.0.12.440-1.7.10]

### ISSUE THREAD

**Issue by Demonoid321** [micdoodle8/Galacticraft#2064]
Decided to finally build this block and try it out with buildcraft pipes, but the game disconnects me saying a fatal error has occurred. It doesn't crash the game or anything just that the connection is lost. Happens on servers and in singleplayer from my testing. I'm not sure if this is galacticraft coding issue,  but it does show up as a galacticraft item so I'm posting it here.
[fml-client-latest.txt](https://github.com/micdoodle8/Galacticraft/files/118636/fml-client-latest.txt)

**Comment by radfast** [comment]
Thanks for reporting, I'll take a look.
It's Buildcraft code erroring, but maybe it needs us to do something with that fluid pipe.

**Comment by radfast** [comment]
It's not a Galacticraft issue.
Buildcraft Fluid Pipes will error with the exact same issue.
Seems like Buildcraft 6.2.6 is not compatible with Forge version 1448.  Either update Buildcraft, or roll back to Forge version 1291.

Thanks for wasting my time.

**Comment by Demonoid321** [comment]
Rude...
