### ISSUE TITLE
Non-cargo rockets disappearing when launched unmanned with Launch Controller

### ISSUE THREAD

**Issue by SolraBizna** [micdoodle8/Galacticraft#2065]
I poked around in the source code and I think I found the problem: https://github.com/micdoodle8/Galacticraft-API/blob/master/src/main/java/micdoodle8/mods/galacticraft/api/prefab/entity/EntityTieredRocket.java#L368-L375

If there's no one in the rocket, there is nothing that creates a rocket at the destination. (If there _is_, that job is done by transferEntityToDimension.) The cargo rocket has special code to handle this. I wanted to adapt that code to EntityTieredRocket but was unable to get it compiling at all, even after an hour or so of work. Gradle and I are _not_ friends.

This bug does _not_ occur if the destination controller is in the same dimension.

**Comment by radfast** [comment]
This is intended behaviour.

You are suggesting the rocket should land, empty?  I guess that would be reasonable...

**Comment by EzerArch** [comment]
> You are suggesting the rocket should land, empty?

That would be useful in a SMP server where a player is stuck in a moon base and asks someone to send a rocket.

**Comment by SolraBizna** [comment]
If it is intended behavior, then there are _two_ bugs here: one that an empty non-cargo rocket can be launched with a launch controller at all, and one where an empty non-cargo rocket _can_ do an entire takeoff/landing sequence with complete success as long as it is within the same dimension.

> You are suggesting the rocket should land, empty?

This is my expectation, and again, this is what happens if the destination is in the same dimension.

> That would be useful in a SMP server where a player is stuck in a moon base and asks someone to send a rocket.

The reason it has come up for me is because I'm running a somewhat-hardcore multiplayer cooperation-based server where resources are limited, life is hard, and the stakes for failure are high. Being able to use a launch controller to send rockets back empty means we can use a single rocket to transport an entire team, with enough fuel and care. The only other available alternative is to build one rocket per person, which would be prohibitively expensive.

I never did get it compiling, but I've decompiled and modified a version that gives me the behavior I want. I'm about to make a pull request containing an equivalent change. I'm not sure whether the fact that this was _easier_ says something about gradle's obtuseness, my insanity, or both.

**Comment by radfast** [comment]
Gradle is a pain to set up, but a joy once it is working as you never have to think about it again.  (Which makes it even more of a pain to set up, because if you ever need to it again, it's probably 12 months after you last did it and you forgot how.)

Nice job on the PR.  I like people who raise issues, then fix them themselves, a lot :)

**Comment by radfast** [comment]
This is fixed in build [441](http://ci.micdoodle8.com/job/Galacticraft-1.7/441/) now available.
