### ISSUE TITLE
AE2 Meteorite World Generation Not Whitelisting

### ISSUE THREAD

**Issue by LukeSkywaIker** [micdoodle8/Galacticraft#2068]
seem the same issue like issue #1547. Galacticraft 3.0.12.437 and Applied Energistics 2 RV3 Beta 4

i added the specific dimension ids to the ae dimension whitelist, but meteorites dont show up on moon or asteroid dim. 

EDIT: just found a server log info with: 

[micdoodle8.mods.galacticraft.core.util.WorldUtil:otherModPreventGenerate:1605]: Whitelisting AE2 meteorites worldgen on planets.

but which one?

hope u can help

greets luke

**Comment by radfast** [comment]
If you're seeing this, Galacticraft's side of things is working correctly:
> [micdoodle8.mods.galacticraft.core.util.WorldUtil:otherModPreventGenerate:1605]: Whitelisting AE2 meteorites worldgen on planets.

Please post up your ae dimension whitelist.

**Comment by LukeSkywaIker** [comment]
thx for quick reply
here:

I:meteoriteDimensionWhitelist <
        -28
        -29
        -30
        -2546
        -2551
     >

**Comment by radfast** [comment]
-2546 and -2551 are dimensions?  I've never heard of those.  If they're not valid dimensions, maybe it is causing AE2 to error - can you try it with only -28 -29 and -30 listed?

**Comment by LukeSkywaIker** [comment]
these are from more planets addon

**Comment by radfast** [comment]
ok, even so please try like I said with only -28 -29 -30.  Maybe AE2 wants them in the range -128 to 128 (I don't know, I didn't look)

**Comment by LukeSkywaIker** [comment]
same message, same result

**Comment by LukeSkywaIker** [comment]
same message, same result with just ae and gc installed.

**Comment by radfast** [comment]
This is an AE2 issue, not a Galacticraft issue.  You might find it works in other AE2 versions, I don't know.

We are from our side correctly calling this AE2 code on the Moon (dimension -28) and other GC dimensions:
> ```appeng.worldgen.MeteoriteWorldGen.generate(fmlRandom, chunkX, chunkZ, world, chunkGenerator, chunkProvider);```

I have tested it in earlier AE2 versions and it worked fine.

**Comment by LukeSkywaIker** [comment]
Thanks!

**Comment by Natesky9** [comment]
I've been struggling with this too, I think it was because of a change that AE did with the meteor generation, making meteors spawn more frequently, if not always on the surface. I don't think they like to spawn in anything other than vanilla terrain either, which means that there is no spot that has line of sight to the sky, and has dirt/stone

**Comment by radfast** [comment]
If AE2 now has terrain requirements for spawning their meteors like vanilla dirt or stone (or grass?), then there's nothing we can do to help here.  Obviously there is no dirt or stone on planets (unless maybe you use a Terraformer to make grass?)  You'd need to request AE2 to include a config option to add additional block types for their meteors to spawn on, it's up to them exactly how that would work.

All we can do is allow the AE2 code to run on planets, and let it do whatever it wants to do.

If there's a specific block type from inside the AE2 meteors which you need, possibly another option is for you to add that block to Galacticraft config as an ore which can be generated underground.  It's a bit lame, but maybe the best you can do.
