### ISSUE TITLE
Localization causes Space station "Create" button to be drawn in incorrect position

### ISSUE THREAD

**Issue by vadimyer** [micdoodle8/Galacticraft#2070]
Hey, as I've wrote before, this is the button glitch - https://youtu.be/ZcS2ZDcnOiY
Creation only works by clicking on some of the resources icon.
I don't think this is because of custom fonts, because it happens on a standard MC client as well (with thin font).

**Comment by EzerArch** [comment]
This is what I see:
- click on "Overworld".
- on SS creation menu, click on "Create", it doesn't work, instead it closes the menu.
- you had then to click on the SS recipe to create the SS.

Does this bug happen on full screen mode?

**Comment by radfast** [comment]
This appears to be server lag.

Please test what happens if you click the button **once** and then **wait**.

**Comment by vadimyer** [comment]
@EzerArch Yes I thought that's clear. The bug happens in full screen as well...

@radfast No my server doesn't lag that much ._.

I've waited tested this, no reaction after around 2-3 minutes. And after that, solar system dialog disappeared and I've died in the sky because I've suffocated ._.

Debug mode doesn't show anything in my console.

**Comment by vadimyer** [comment]
BTW, if you've noticed I can't see other player's space stations anymore, after upgrade to the latest GC. I'm OP ._.

**Comment by radfast** [comment]
This is a **localization issue**.  The Russian text is drawn larger than the English text, and so the button is drawn on-screen lower than the GUI region where the mouse expects to find the button.

**Comment by radfast** [comment]
This is closely related to #1790, I think...  We need to try to fix this either in 1.7 or 1.8 now.

**Comment by radfast** [comment]
We will try changing the text to this:    Здесь можно построить станцию!
