### ISSUE TITLE
Broken Dungeon spawners!! Fixed found just needs applying!!

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft#2076]
Right the spawner's in dungeon are not being created with entities applied to them this is because they cant be found. 

When adding "GalacticraftCore." before them it fixed it. 
The fix needs to be applied to the RoomSpawner Classes within the dungeon world gen files.

See https://github.com/MJRLegends/ExtraPlanets/commit/4e52b9f88bbe8bb3a28dfb43b4051057327c50f0 for an example of the fix because i fixed them for my addon

Proof of the fix 
![](https://i.gyazo.com/4911bd436115e5137dbeb1f72923ce38.png)

I would submit a pull request but dont have the time atm

**Comment by radfast** [comment]
Thanks I'll take a look.

**Comment by MJRLegends** [comment]
No problem :)

**Comment by radfast** [comment]
Fixed, see 923e88e.  Thank you :)

**Comment by MJRLegends** [comment]
Yeah just saw :P Thanks
