### ISSUE TITLE
Feature/addon suggestion: Register all loaded Dimensions as planets

### ISSUE THREAD

**Issue by DraksterAU** [micdoodle8/Galacticraft#2077]
It would be really cool if all loaded dimensions could somehow be rendered in the default galacticraft galaxy view somehow (maybe grouped based on mod for each solar system?) , to be visited by rockets (as long as they are not in the blacklisted dimensions list!)

This has like 0% chance of being picked up, I just thought I'd suggest it

**Comment by XFactHD** [comment]
Please only post suggestions on the forum.

**Comment by radfast** [comment]
There is an [existing forum thread](forum.micdoodle8.com/index.php?threads/using-other-mod-dimentions-as-planets.6308/).

**Comment by EzerArch** [comment]
> There is an existing forum thread.

There! I fixed the link: forum.micdoodle8.com/index.php?threads/using-other-mod-dimentions-as-planets.6308/
