### ISSUE TITLE
Gas Liquifier is producing Nitrogen and Argon on mars

### ISSUE THREAD

**Issue by DavidEdwin** [micdoodle8/Galacticraft#2081]
When I tried to get Carbon dioxide so I could make fuel I spawned an atmospheric valve put it into the Liquifier and got Nitrogen instead.

Here are some screenshots and my mod List:

[Modlist.txt](https://github.com/micdoodle8/Galacticraft/files/129442/Modlist.txt)

![2016-02-13_14 38 32](https://cloud.githubusercontent.com/assets/6610457/13030030/5f264078-d262-11e5-99dd-4441765b12a3.png)
![2016-02-13_14 38 35](https://cloud.githubusercontent.com/assets/6610457/13030031/5f28b43e-d262-11e5-909c-077542e0bfb5.png)

**Comment by DavidEdwin** [comment]
Here is my Mod list.

[1.7.10]ArmorStatusHUD-client-1.28
[1.7.10]CrystalWing-universal-1.7.10.r02
[1.7.10]Treecapitator-universal-2.0.4
advancedgenetics-1.7.10-1.5.9
aether-1.7.10-1.6
AncientTrees-1.7.10-1.6.4
appliedenergistics2-rv2-stable-10
archimedesshipsplus-1.7.10-1.8
Aroma1997Core-1.7.10-1.0.2.16
AromaBackup-1.7.10-0.0.0.6
ATG-1.7.10-0.12.0
backpack-2.0.1-1.7.x
BackTools-4.0.0
BattleTowers-1.7.10
BiblioCraft[v1.11.4][MC1.7.10]
BiomesOPlenty-1.7.10-2.1.0.1548-universal
boilerplate-1.7.10-6.2.1.68-universal
buildcraft-7.1.14
BuildcraftAdditions-1.7.10-2.2.5
Carpenter's Blocks v3.3.7 - MC 1.7.10
CodeChickenCore-1.7.10-1.0.7.47-universal
CoFHCore-[1.7.10]3.1.1-324
commonfun-1.7.10-1.0.0
CraftingPillars-1.7.x-1.6.1
CustomMobSpawner 3.3.0
CustomNPCs_1.7.10d
DimensionalPockets-1.7.10-0.11.4.1-universal
DrZharks MoCreatures Mod v6.3.1
DynamicSurroundings-1.7.10-1.0.4.6BETA
EquivalentExchange3-1.7.10-0.3.507
Eureka-1.7.10-3.0.2
Excore-1.3.4-1.7.10
Farseek-1.0.10
forestry_1.7.10-4.2.7.55
GalacticraftCore-1.7-3.0.12.441
Galacticraft-Planets-1.7-3.0.12.441
gilded-games-util-1.7.10-1.9
GravityGun-4.0.0-beta
iChunUtil-4.2.2
industrialcraft-2-2.2.811-experimental
journeymap-1.7.10-5.1.3-unlimited
KoreSample-1.7.10-1.3.2
LanteaCraft-1.7.10-70
legacyjavafixer-1.0
MicdoodleCore-1.7-3.0.12.441
MineFactoryReloaded-[1.7.10]2.8.1-174
MorePlayerModels_1.7.10b
movingworld-1.7.10-1.8
MrCrayfishFurnitureModv3.4.7(1.7.10)
mystcraft-1.7.10-0.12.3.01
NotEnoughItems-1.7.10-1.0.5.118-universal
OmnisCore-1.7.10 - 0.0.6-universal
OpenComputers-MC1.7.10-1.5.22.46-universal
PortalGun-4.0.0-beta-6
Railcraft_1.7.10-9.8.0.0
RedstoneArsenal-[1.7.10]1.1.2-92
SimplyJetpacks-MC1.7.10-1.5.3
Sophisticated Wolves 3.2.0
steamcraft2-1.7.10-B5.0.1
Streams-0.1.6
Teleplates-1.1-1.7.10
Thaumcraft-1.7.10-4.2.3.5
TheElysium-1.7.x-1.0.3
ThermalDynamics-[1.7.10]1.1.0-161
ThermalExpansion-[1.7.10]4.1.1-237
ThermalFoundation-[1.7.10]1.2.2-111
tropicraftv6_0_5 for MC v1_7_10
twilightforest-1.7.10-2.3.7
VersionChecker-1.1.9
Waila-1.5.10_1.7.10
WailaHarvestability-mc1.7.10-1.1.6
WallTeleporters-1.7.10-1.0.5
WR-CBE-1.7.10-1.4.1.9-universal

**Comment by radfast** [comment]
http://wiki.micdoodle8.com/wiki/Gases#Carbon_Dioxide
