### ISSUE TITLE
Problem with downloading

### ISSUE THREAD

**Issue by xXMintBunnehXx** [micdoodle8/Galacticraft#2086]
I've tried to download both 1.7.10 versions of the mod, but it gives me a 503 error. I need to download it today because from tomorrow for a long lime I'll be away, in a place with no internet so I can't download it. I've been downloading it from the mod's official site but I still can't download it. It says:

> Service Temporarily Unavailable

> The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Any reason why this is happening?

**Comment by radfast** [comment]
Thanks for the heads up.  I've informed people and it's now just a question of waiting for the server to come back up.

If the download server is still not working tonight (that's 5 hours from the time of this post) then I'll post latest vesions on the [alternative download site](http://wiki.micdoodle8.com/wiki/DownloadTemp) but please don't use that currently, it is 1 year out of date!

Another idea: the latest versions are in [SpaceAstronomy modpack](http://www.curse.com/modpacks/minecraft/233384-space-astronomy) on Curse / FTB - you could download the modpack and then just take out the three Galacticraft and MicdoodleCore files from it?

**Comment by DraksterAU** [comment]
Thx @Radfast :)

**Comment by radfast** [comment]
The [alternative download site](http://wiki.micdoodle8.com/wiki/DownloadTemp) now has the latest GC build, 3.0.12.442.

**Comment by Fabboz** [comment]
tha main site is back

**Comment by dj3520** [comment]
So is jenkins. Please close.
