### ISSUE TITLE
Matter Overdrive ores do not spawn on GalactiCraft planets.

### ISSUE THREAD

**Issue by Haggle1996** [micdoodle8/Galacticraft#2089]
The Matter Overdrive ores (by @simeonradivoev) do not spawn on either the moon or mars (or the GalaxySpace planets either) using the following config. The ReactorCraft ores spawn correctly.

```
    S:"Other mods ores for GC to generate on the Moon and planets" <
        mo:dilithium_ore /UNCOMMON /DEEP /STANDARD
        mo:tritanium_ore /COMMON /SHALLOW /STANDARD
        ReactorCraft:reactorcraft_block_ore:1 /UNCOMMON /DEEP /STANDARD
        ReactorCraft:reactorcraft_block_ore:2 /UNCOMMON /DEEP /STANDARD
        ReactorCraft:reactorcraft_block_ore:3 /UNCOMMON /DEEP /STANDARD
```

The log has these entries:
```
[15:43:17] [Client thread/ERROR] [Galacticraft/GalaxySpace]: [config] Other mod ore generate IDs: unrecognised block name 'mo:dilithium_ore'.
[15:43:17] [Client thread/ERROR] [Galacticraft/GalaxySpace]: [config] Other mod ore generate IDs: unrecognised block name 'mo:tritanium_ore'.
```

I get two sets of them, I assume one for GalaxySpace and one for Galacticraft.

I'm certain the names are correct. `/give <playername> mo:dilithium_ore` works correctly, for example. I've also tried other variations, such as mo:dilithium_ore:0, etc.

Any ideas what I'm doing wrong?

**Comment by radfast** [comment]
This is likely the same issue as #1670
It seems our code does not like the "_" or other non letters.  Possibly.

Please can you test it using the block ID number and see if that works.

**Comment by radfast** [comment]
Also: using the block ID number should give you a log message from Galacticraft, telling you the block name to use...

**Comment by radfast** [comment]
OK I think the reason could be that the MO ore - for example ```mo:dilithium_ore``` - is the name of an item not a block.  Like... they could have the block named differently.

We can probably add to Galacticraft so that it can understand item names as well, if the item corresponds to a block.

**Comment by Haggle1996** [comment]
When using the block ID's, this error prints in the log:
```
[16:57:33] [Client thread/INFO] [Galacticraft/GalaxySpace]: [config] Other mod ore generate IDs: the use of numeric IDs is discouraged, please use minecraft:air instead of 3595
[16:57:33] [Client thread/INFO] [Galacticraft/GalaxySpace]: [config] Other mod ore generate IDs: not a good idea to specify air, skipping that!
```

**Comment by radfast** [comment]
I've made a custom build of 442 for you to try, with the new item code patched in.

Please go to http://wiki.micdoodle8.com/wiki/DownloadTemp and grab Galacticraft-Planets 442 and MicdoodleCore 442 if you don't have them already.

Then download [this custom GalacticraftCore 442](http://s000.tinyupload.com/index.php?file_id=81123254482206862494)

Please let me know if this fixes it.

**Comment by Haggle1996** [comment]
Testing now.

**Comment by Haggle1996** [comment]
No, the special download does not fix it. Still reports the same error in the log (for both the named resource and the ID), and no ore is generated.

**Comment by radfast** [comment]
OK looking at Matter Overdrive source code, I think I see the problem.  They do not register their blocks until ```init``` phase, when most mods do it in ```preinit```.

If you can (temporarily) change the loading order of your mods - simply by renaming the Matter Overdrive .jar file to something beginning with A,B,C,D,E or F - then I think you will see this fixed.

For a more permanent solution, we can put back the oregen to ```postinit``` in Galacticraft.  That will be in next build 443.
