### ISSUE TITLE
[question]1.8 update

### ISSUE THREAD

**Issue by jochuan** [micdoodle8/Galacticraft#2090]
galacticraft will be updated to 1.8 or to 1.8.9 ?

**Comment by BlesseNtumble** [comment]
Nope.

**Comment by radfast** [comment]
Ban.

**Comment by EzerArch** [comment]
http://forum.micdoodle8.com/index.php?threads/when-will-the-next-update-when-will-new-planets-rockets-mobs-or-whatever-be-added.3753

*Le sigh*
