### ISSUE TITLE
Astro Miner Issue with Chromaticraft ore

### ISSUE THREAD

**Issue by Keyarose** [micdoodle8/Galacticraft#2093]
I was trying out the astro miner in the End and noticed that it was not properly collecting Chromaticraft ore.  The ore in Chromaticraft is all the same block with different metadata for each type.  The ore found in the End being chromaticraft_block_teiredore with a metadata of 11 or 12.  The ore that the miner returns to its base is chromaticraft_block_teiredore with metatdata 0, a different ore which only spawns in the Overworld.

Shown in the first slot of the base inventory:
![2016-02-18_18 48 59](https://cloud.githubusercontent.com/assets/1906772/13164455/c0f7ecde-d68b-11e5-83f8-7b01e879863c.png)

Chromaticraft V10d
Galacticraft 3.0.12.442

**Comment by radfast** [comment]
Thanks for reporting.  It must be something strange about the Chromaticraft ores.

Please can you confirm:
1.  NEI HUD shows the correct Chromaticraft ore when you look at it.
2.  A silk touch pick mines the correct ore.
3.  The 'Pick Block' button in creative mode gives you the correct ore when used on the block.

**Comment by Keyarose** [comment]
1. Confirmed
2. Drops the item for the ore instead of picking up the block(the powder or crystal it is suppose to drop with a normal pickaxe)
3. Confirmed

**Comment by radfast** [comment]
This will be fixed in new build 444, which should be available Sunday night.
