### ISSUE TITLE
refinery output needs BC wooden pipe to extract fuel

### ISSUE THREAD

**Issue by mathers992** [micdoodle8/Galacticraft#2094]
I am coming across a problem with the refinery output working. I can get the input to work fine with buildcracft pipe (using golden fluid pipe) and its accepting and filling the refinery with oil then on the output i have gold fluid pipe running to my fuel loader but its not pushing out the fuel at all. I have tried this also with thermal Dynamics pipe and its still not working.

I currently am running Galacticraft version 3.0.12.442
minecraft version 1.7.10

Please help me with this, i found a previous ticket you had from October with the same issue and tried the steps in there but they didnt work. I also noticed they were on older versions and saw that i was on the latest available so not sure what could be wrong.

**Comment by radfast** [comment]
Thanks for reporting, we'll take a look.  Might be a day or so before anything further happens.

**Comment by mathers992** [comment]
Ok, thank you for looking into this.

**Comment by radfast** [comment]
Refinery is working correctly.  Tested GC build 3.0.12.442 using Buildcraft pipes and EnderIO fluid conduits.

Like all Galacticraft machines (and a lot of machines in other mods) the Refinery never "pushes" out fluids, you need to extract them.  So:
* with Buildcraft, use a Wooden Fluid Pipe at the Refinery output, then Gold Fluid Pipes after that
* with EnderIO, right click the extraction end of the conduit and set it to extract automatically without a redstone signal
