### ISSUE TITLE
Energy Storage Cluster storage resets to 500,000 upon earth re-entry

### ISSUE THREAD

**Issue by Creeperman8362** [micdoodle8/Galacticraft#2095]
Ever since I first got an energy storage cluster (the blue one that holds 2.5 million), it has been resetting to 500,000 when I re-enter the earth.

**Comment by radfast** [comment]
I guess you mean the Energy Storage Cluster is in your Overworld base, and if you go away (for example to a Space Station) and come back, it has reset to 500,000?

**Comment by Creeperman8362** [comment]
Yes. I think its because both energy storage units use a damage system similar to vanilla tools (0 is full durability, 251 is 0 durabily on iron tools, etc), and it is at 0 when it has 2.5 million gJ. When I come back, the game reads the data and thinks "The energy storage cluster is at full capacity, load 500 gJ into it), like it would for the energy storage module.

This is pure guesswork, and I have not done any other testing other than survival observations.

**Comment by radfast** [comment]
Thank you, good spot.  Problem found and fixed.
