### ISSUE TITLE
Query: Preventing takeoff from non-overworld dimensions?

### ISSUE THREAD

**Issue by DraksterAU** [micdoodle8/Galacticraft#2098]
Hi There,
I saw that we have a way  to blacklist certain worlds from launching from.. is there any way to whitelist?
I'd like to only be able to launch from worlds that are viewable in the Galaxy menu.... and the number of worlds on my server goes up with the number of players without admin intervention.. (theyre size limited and population is capped under server's max).

There used to be a setting to enable/disable takeoff from non-overworlds.... I asked @radfast about that a long time ago... does that still exist at all?

**Comment by radfast** [comment]
There is no configurable whitelist - but the Overworld and all worlds reachable in the Galaxy menu are automatically whitelisted.

So you could manually blacklist all dimensions, and that should achieve what you want.  Do the worlds on your server have predictable dimension IDs (even if there are many?)  You could just list all possible dimension IDs - e.g. 2 to 200 - in the blacklist.  That won't prevent GC Space Stations from working because, like I said, Galacticraft-created worlds are automatically whitelisted.

Listing dimension IDs 2 to 200 in your config file will make an ugly config file, but you don't need to read that file normally, and it will not create lag or memory issues.  The game just stores all that as a list of numbers, and checks it when a player attempts to launch a rocket.

**Comment by DraksterAU** [comment]
No worries @radfast Thanks :)

Ive already had to do that for AE2 etc.. i'll copy the list of Dim IDs and see how we go :)

thanks for the response!

**Comment by DraksterAU** [comment]
PS: The Dim IDs are assigned between 1 and 2500 I have not much control over that.

**Comment by radfast** [comment]
> The Dim IDs are assigned between 1 and 2500

!  Which mod does that?  Maybe you can ask it to config that to a more sensible range.

Tell you what.  I hate adding config clutter, but we can add a "*" option which means blacklist all non-GC dimensions.  So you just put a "*" in the list of dimension IDs.

**Comment by DraksterAU** [comment]
Perfect!!! Thanks @radfast  :)

Its a bukkit plugin, Multiworld on a KCauldron server... I have NPC interaction to trigger creation of a 128x128 block world (and configured with WG etc)  for players to call their own after they complete a questline.... and a cleanup script that kills off inactive users and their worlds.

Basically it just uses the next available Dim ID that is positive and will go all the way to 2500.

**Comment by radfast** [comment]
Done, this will be in next build 443 tonight.

**Comment by DraksterAU** [comment]
Thanks Rad... Really appreciate you taking the time to consider this one!

**Comment by radfast** [comment]
My pleasure.  You have contributed plenty to Galacticraft over the years and we appreciate that on our side :)

I also think it's important to support large server owners, I know what I pain it is to keep a stable server running with mods.  #2054, #2066 and #2070 are current concerns, though maybe only occurring on vadimyer's server?

**Comment by DraksterAU** [comment]
#1 looks like an issue with a Bukkit spawn handler being used and overriding your spawn handler for that dimension..

#2 is simply an incompatibility with More planets and KCauldron.... The KC guys keep messing with stuff that is breaking previously working mods / plugins in order to get new ones working.
#3 I'm not as sure of... Only time I've seen something similar to that is when configs are set to disallow space station creation.

**Comment by DraksterAU** [comment]
@radfast it's 4 am so if I've misinterpreted anything let me know lol

**Comment by radfast** [comment]
> it's 4 am so if I've misinterpreted anything let me know lol

I forgot you are in Australia, though I see there is a clue ...
I meant "tonight" in Europe / east coast US.  Probably around 2 hours from now...

**Comment by DraksterAU** [comment]
@radfast Lol I was referring to my comments on the issues, you take as much time as you need for the build :)

**Comment by radfast** [comment]
oh lol.  Your comments are much appreciated.

**Comment by DraksterAU** [comment]
Hi @radfast Sorry to be a pain.. is the "*" needing to be quoted?
https://github.com/StargateMC/Server/blob/master/base/config/Galacticraft/core.conf#L11

**Comment by DraksterAU** [comment]
@radfast I've tried both "*" and * without quotes using B444 and this doesn't seem to be working to blacklist rocket takeoffs on any dimensions at all.

**Comment by DraksterAU** [comment]
Idiot. You are using B442 on the client side because Solder failed to get  the changes.... (Sorry @radfast )

**Comment by DraksterAU** [comment]
Ok @radfast I've tried my darndest to get this to work using * and "*" and made sure I'm using the appropriate builds (Looks like I'm an idiot sometimes too) ..... Can you double check this one please?

Space station gui is gone this time ;)

**Comment by radfast** [comment]
???

In the server config, you have lines like this:
```           <
              1
              -1
               >```

Just add one more line in there - it can be anywhere, before or after the 1 and -1, like this
```             *```

See also: https://github.com/micdoodle8/Galacticraft-API/blob/239c974cc0e858d89119076e6ec50565a88688c1/src/main/java/micdoodle8/mods/galacticraft/api/prefab/entity/EntityAutoRocket.java#L818-L822

**Comment by DraksterAU** [comment]
@radfast I had an extra space. really wasn't myself at stupid o'clock sorry man.
Won't waste your time again.

**Comment by DraksterAU** [comment]
@radfast Can you see what I am doing wrong? 

https://github.com/StargateMC/Server/blob/master/base/config/Galacticraft/core.conf

I have tried everything...

**Comment by DraksterAU** [comment]
@radfast this is not working... Check my
Comment above and if I've made a mistake I apologise profusely.... But I don't think I have.
