### ISSUE TITLE
Fallen Meteor cools down in a second

### ISSUE THREAD

**Issue by paduser** [micdoodle8/Galacticraft#2105]
If I walk closer to an Fallen Meteor it first looks red but as soon I'm getting closer it looks gray.

You can see it in the video. After 5 seconds it switches colors.
https://www.dropbox.com/s/72d1jbacrgk6hxw/2016-02-21-2101-05-2.mp4?dl=0

**Comment by EzerArch** [comment]
Yes, I noticed that. Now a question: how old is that meteor?

If the meteor has recently fallen: it will cool down gradually as expected.

If it is very old, the game will render them hot and it cools down in a second if you approach. This happens with my old worlds from MC 1.6.4.

**Comment by paduser** [comment]
The world was generated under 1.6.4 but after upgrading on 1.7.2 I lost my old moon.

**Comment by radfast** [comment]
Thank you both.

In a new 1.7.10 world, I've noticed that a Fallen Meteor which has been in the map for some minutes already is rendered red when you are far away (>32 blocks or so) but then gray when you are close.

**Comment by radfast** [comment]
Hmm, it's connected with vanilla Minecraft, it's basically the same issue that causes machines to stop working when you are more than 2-3 chunks away from them.

**Comment by paduser** [comment]
Does that mean it isn't fixable or you just need to find a way?

**Comment by radfast** [comment]
Fixable but it's not an easy fix, so may take a while.

**Comment by radfast** [comment]
The issue is likely improved in 1.10.2 and later versions due to the different way vanilla handles chunk updating.  I don't have the energy to continue searching for a fix for 1.7.10, it's a fairly minor problem and caused by vanilla.
