### ISSUE TITLE
[Cauldron] All Bukkit plugins not picking up registered world names

### ISSUE THREAD

**Issue by DraksterAU** [micdoodle8/Galacticraft#2106]
Hi all,

Not sure if your even going to look at this but...
Bukkit based plugins use the name of a world to reference it, rather than the dimension Id.

As such all of them come up with "dim-30" for asteroids etc.

Is there any way you can register the name in the Lang file to the dimensions in the game? That way they support it...

If it's not possible all good, but if it is possible and your not willing any chance you could share some info on how?

**Comment by radfast** [comment]
Dimension names are already registered as  "moon.moon", "planet.mars", "planet.asteroids".

You should see this - for example - if you run the **dump** command from in-game.

It's only the space stations which have numbers.

Localising the names in the lang files won't help any plugins, because the plugins - presumably - need to use the same configs and code in all languages.  Almost everything coded uses unlocalised names.

Seems like this could be a Bukkit / Cauldron issue.  If you can be more specific about which piece of KCauldron code is getting the wrong name then I can maybe look at this some more, but your description is too general.

**Comment by DraksterAU** [comment]
Hi @radfast 

I'm talking about when calling the equivalent of player.worldObj.getWorldInfo().getWorldName() it renders "dim-30" rather than the alternative "Mars".

Sorry for not being so clear.... is this something that can be remedied?

**Comment by radfast** [comment]
oh ok.  We are giving a name for worldObj.provider.getDimensionName().  Maybe not the WorldInfo, I'll look now.

**Comment by DraksterAU** [comment]
@radfast Sorry man... part of Bloods awesome work with cauldron was sometimes only translating one path between Forge and bukkit for something, not both.

**Comment by radfast** [comment]
As far as I can see, ```player.worldObj.getWorldInfo().getWorldName()``` gives the same name for all dimensions (vanilla or modded) and it's a name based on the name you gave to the world when you created it.

So it's not that.  Any other ideas for what it could be?

**Comment by DraksterAU** [comment]
@radfast Ill have a play around now, I have a test cauldron server and a mod I know the code of... :) Stay tuned! haha

**Comment by DraksterAU** [comment]
Hi @radfast I've checked and you are right, WorldServer.provider.getDimensionName() is registering "planet.asteroids" (which I assume can be changed in lang?).

Bukkit plugins however always use the WorldServer.getWorldInfo().getWorldName() - this couldn't be modified without asking  the KCauldron developers.... and they are changing a lot right now that makes me uncomfortable updating after asking, even if they were willing to.

Up to you if you'd be willing to register both.... but it would be really appreciated :)

**Comment by DraksterAU** [comment]
Side note: The World Name would rename folders correct? Is it possible you can set this as an optional for "bukkit/cauldron" support, or even show me where to splice in the code to run a fork of GC.......

**Comment by radfast** [comment]
OK here's what's going on.

* On a standard Minecraft server, not Cauldron, the ```WorldInfo.getWorldName()``` is always, for all dimensions, the name of the main world folder.  Like when you create a new world in SSP, you give that world a name.  On a server it is probably always just "world".

[This line](https://github.com/MinecraftForge/MinecraftForge/blob/1.7.10/src/main/java/net/minecraftforge/common/DimensionManager.java) in Forge has that effect.

* It looks like KCauldron has patched that - the first thing I found is someone else's [fork](https://github.com/TCPR/Thermos/blob/master/patches/net/minecraftforge/common/DimensionManager.java.patch#L159-L165) - and gives the dimensions a name.  **But KCauldron there is automatically giving every modded dimension, outside the range -1,0,1, the name DIMnn**.

So ... this is definitely a KCauldron issue, not a Galacticraft issue.

**Comment by Cracks777** [comment]
@Robotia

**Comment by DraksterAU** [comment]
If only I could be using Thermos... :(

**Comment by radfast** [comment]
See my updated comment above.

I'm no expert on different Cauldron versions, but I would guess this is the same or similar across all.  Key point is, Cauldron uses the save folder name as the dimension name.  I still haven't understood why that causes you an insurmountable problem ...

**Comment by DraksterAU** [comment]
@radfast , It doesn't...

The main problem is that It causes all plugins (such as factions, worldguard, multiworld, multiverse, worldborder etc) to register every dimension as DIMXX. Its incredibly hard to tell which is which in the configs and not very helpful when it displays Event X has occurred on DIMXX in-game... its confusing for players.

With Galacticraft + GalaxySpace/MorePlanets we're talking like 25+ Dimensions.... players and admins cant memorise the dimension ids... not to mention other mods...

Same reason DNS was invented... us humans cant remember numbers in bulk... :P

I'll report this on the appropriate spot now. Thanks.

**Comment by DraksterAU** [comment]
https://gitlab.prok.pw/KCauldron/KCauldron/issues/387

**Comment by Robotia** [comment]
Hi, I am one of the maintainers of Thermos. I will be fixing this issue, since it is clearly on our end

**Comment by radfast** [comment]
Final comment from me: world.provider.getDimensionName() gives an unlocalised name.  That can obviously be localised if required for client chat purposes, I'm not sure whether this localisation already happens automatically in Bukkit or whether you would always want it localised?

**Comment by dj3520** [comment]
From what I've seen Bukkit only references the name a server assigns to the
Overworld. The nether and The End are referenced by dimension numbers.

**Comment by Robotia** [comment]
Wait...this is kinda expected behavior. It's been this way since 1.5.2 and I don't think it would be a good idea to change it now

**Comment by radfast** [comment]
@DraksterAU maybe you can implement a chat translator which translates "DIM-28" into "Moon"?  If you are already using a chatfilter plugin, this should take you about 1 minute.

**Comment by DraksterAU** [comment]
I've already got that for the forge mods I use - took a little longer than 1 minute though haha. 
How can I intercept messages that were initiated by the bukkit side ?

Shame @robotia... But I see your point as to how long the bug has been there and what the ramifications for fixing it are.

**Comment by radfast** [comment]
I see, you would need to filter the output of other Bukkit plugins.  Maybe there is a mod or Bukkit plugin which can do this filtering at the point that chat actually hits the screen?  I've certainly seen plugins which are able to suppress log spam from other plugins and mods.  I'm no expect on current Bukkit plugins, any info I have is at least 2 years out of date.

**Comment by DraksterAU** [comment]
@radfast I agree also... It's just a shame this bug wasn't caught years ago :/ haha!

I'll look into some existing Bukkit chat filter plugins and see if any so a regex find and replace. Probably my best bet.

Thanks for your time @radfast @robotia

**Comment by Robotia** [comment]
@radfast I have an idea...maybe a config setting that is false by default? This way @DraksterAU can use the feature without disturbing the configuration of other Thermos users.

**Comment by radfast** [comment]
I think @DraksterAU said he is not using Thermos!  I think he said "if only he could"!!

I am also thinking about a config in Galacticraft, we could fairly easily call a WorldInfo.setName() to update the name every time after loading GC dimensions.  I kind of like the idea of Galacticraft dimensions being properly named on all managed servers, instead of DIM-28 or whatever.

**Comment by DraksterAU** [comment]
@robotia I would love that!!

I can almost guarantee that new thermos users will want to use that too if they use Bukkit plugins that reference forge worlds... Just saying.

Best of both worlds :)

**Comment by DraksterAU** [comment]
May even have some older servers manually adjust their configs to suite.

**Comment by radfast** [comment]
> If only I could be using Thermos... :(

That's what DraksterAU said before.  I'm so confused :/

**Comment by DraksterAU** [comment]
@radfast I am slowly working through issues I have with thermos. @robotia has been great - I just can't switch just yet.

**Comment by radfast** [comment]
I think the reason why both me and @Robotia probably like helping you specifically, you ask nicely, your requests make a lot of sense, you have made some sound suggestions in the past, and you give good feedback after we attempt fixes.  Really it's quite refreshing :)  Just saying!

**Comment by DraksterAU** [comment]
Much appreciated @radfast :)

I try to remember you guys do this for free for the most part and to make sure I've done my homework haha... So if the idea isn't solid (or at least I think it is) don't waste your time.
Sorry if this one makes a little less sense.... It was rather late when I submitted :)

**Comment by Robotia** [comment]
@radfast @DraksterAU https://github.com/TCPR/Thermos/commit/8942590fde73f4749adda73a801ac34f76f1613a

**Comment by Robotia** [comment]
Worlds will still be saved in DIM## but renamed in Bukkit.

**Comment by DraksterAU** [comment]
Thank you guys!!! :)


I'll do some more testing of the latest build for thermos tonight... Fingers crossed that player interact issue is fixed and I can ditch KCauldron!

**Comment by radfast** [comment]
@Robotia are you sure about [line 193](https://github.com/TCPR/Thermos/blob/8942590fde73f4749adda73a801ac34f76f1613a/patches/net/minecraftforge/common/DimensionManager.java.patch)?  Isn't ```world``` unassigned there?  And don't you want ```provider.getDimensionName()``` there?  The WorldInfo isn't even created until the constructor for WorldServerMulti() ...

**Comment by Robotia** [comment]
@radfast Ye I just realized, I'm not even using an IDE for this, fixing it right now xD

**Comment by Robotia** [comment]
@radfast https://github.com/TCPR/Thermos/commit/144b355e9667d2d5c4d92128efb03d7a80dc27b6 should fix it

**Comment by radfast** [comment]
? I don't think that will work either :(

The ```world``` has no provider and no worldInfo until it has been constructed!!!!  And this code in DimensionManager is the actual constructor for the world.  So the worldInfo doesn't even have a name until you give it a name using ```realName``` - you will see, if you follow how that String parameter ```realName``` gets passed around in the vanilla MC constructors, ater eventually vanilla MC will call worldInfo.setName(realName)

But the WorldProvider for the dimension already exists and has a name.  There is 1 WorldProvider for each dimension and it exists from the init() phase of the server.

I suggest go back to https://github.com/TCPR/Thermos/commit/8942590fde73f4749adda73a801ac34f76f1613a but replace line 193 with:

```realName = WorldProvider.getProviderForDimension(dim).getDimensionName();```

Or if you want to get fancy you could re-use your ```provider``` local variable from higher up, if you move it outside the ```if { }``` statements.

**Comment by DraksterAU** [comment]
@radfast @Robotia Done some testing... B31 completely breaks Bukkit plugins when the real names setting is enabled :/

https://github.com/TCPR/Thermos/issues/148

Sidenote, Forge side now registers names properly, so perhaps something is just missing?

@radfast Can I rename "planet.mars"? I cant seem to find it in the langs.

**Comment by EzerArch** [comment]
@DraksterAU:
> Can I rename "planet.mars"? I cant seem to find it in the langs.

This? https://github.com/micdoodle8/Galacticraft/tree/master/src/main/resources/assets/galacticraftmars/lang

**Comment by DraksterAU** [comment]
@EzerArch thanks man, but the planet.mars= doesn't change the name of the dimension itself.... :(

**Comment by EzerArch** [comment]
And ```dimension.Mars.name=Mars```? [L141](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/resources/assets/galacticraftmars/lang/en_US.lang#L141)

**Comment by DraksterAU** [comment]
@EzerArch I have them both set. It does nothing. @radfast may be able to assist.... I'm not sure.

**Comment by DraksterAU** [comment]
See here:

dimension.Mars.name=P2Y-394
planet.mars=P2Y-394

**Comment by radfast** [comment]
Galacticraft currently gives the unlocalised name for the dimensions (this is also vanilla Minecraft behaviour).  I will localise it next build, I don't think that should break anything.  "Localise" means run it through the ```.lang``` files.

**Comment by DraksterAU** [comment]
@radfast You rock dude. 
Im replacing it on both Lang files ;) being Aussie we tend to try to keep the poms and Yankees happy!

**Comment by DraksterAU** [comment]
@radfast is there any way for me to configure what planets use what tier rocket, without hacking things to pieces?

Could this be done in an add on (which I write), or would I need to edit GC code to edit the existing planet tiers? (Just a question, not a feature request!)

Reason I ask is to try to mimic galaxies by grouping worlds within GC - something I've written for sgcraft... Which works beautifully. I've increased power costs to go between galaxies via Stargate.
I was hoping to do tier based restrictions in Galacticraft.

For "intergalactic travel" I was hoping to limit this to tier 8 rockets.... While changing langs to make it so more planets worlds appear as if they are in different galaxies.

Not sure if this makes sense... Sorry to hound you man!

PS if I learned how to code a GC add on properly, do you natively support galaxies? I noticed it does have Milky Way in the interface.

**Comment by radfast** [comment]
https://github.com/SteveKunG/More-Planets  contains good examples on how to code galaxies.

Galacticraft and add-ons set the rocket tiers at startup.  It's not configurable.  But you could code a small mod which loads after Galacticraft (and add-ons), accesses each registered CelestialBody and changes the required rocket tier to something different.

GC built-in behaviour where a space station is always reachable from the world it orbits - with all rocket tiers - cannot easily be changed.

**Comment by DraksterAU** [comment]
Appreciate your answer @radfast !

I'll investigate MorePlanets code tonight. 

space stations are fine.. I don't mind if they're always accessible from their planet.

**Comment by DraksterAU** [comment]
Hey, thought Id add this comment to somewhere relevant.
@radfast Were you still able to lang the world names? You mentioned it might be possible above.
I can create a new issue if you like?

**Comment by DraksterAU** [comment]
Also... robotia isn't able to do the bukkit name translation as bukkit is having a hissy fit when it is turned on (he said he'd get to it .. but it might be a while as there are more important things to deal with ... like crash bugs)... so if you could do the registration of the WorldInfo.getWorldName() ... or show me how in a custom jar ... I'd really appreciate it.. If not, all good I can be patient :D
