### ISSUE TITLE
[Huge modpack] Biomes issue causing GC background MapGen to Crash

### ISSUE THREAD

**Issue by xJon** [micdoodle8/Galacticraft#2107]
http://pastebin.com/vbfKgVu3
Any idea what caused the issue?
I crashed after entering a singel-player world which the player spawned in a Mystcraft age.
Worth noting that this happened after updating Galacticraft to `.444` and re-profiling Mystcraft.
Thanks!

**Comment by radfast** [comment]
Thanks for reporting.  It's not connected with where the player is or Mystcraft.

This crash is in code which runs in the background for the first few minutes after you start a server with Galacticraft (or the first few minutes after you updated Galacticraft in an existing world).

The background code is building a biome map of the Overworld.  It uses vanilla Minecraft's worldgen code, the part which builds biomes, which is how it makes an accurate map.

Vanilla Minecraft would probably crash in a similar way if a player had gone to the part of the world map which Galacticraft was mapping just then.

The only possible cause for the crash that I can think of is you have a biome conflict.  If possible, it would be great if you can use NEI's "Dump" feature to list out all your biomes and see if they look OK - maybe post the list here.  You have so many mods there could be a conflict, I guess.  **Biomes o' Plenty** is where I would start to look...

I'd like to solve this issue if possible.

You have not said if your game keeps crashing or this was a one-time problem?

If it keeps on crashing, I think for now you will have to roll back Galacticraft to [build 441](http://ci.micdoodle8.com/job/Galacticraft-1.7/441/).  There is currently no way to switch off the background mapping in build 444.

**Comment by xJon** [comment]
It indeed kept crashing *on this particular world*, other old worlds I tried to load up had no problem.
Trying to enter the world with `.441` worked okay.
About the list, [here](https://docs.google.com/spreadsheets/d/1C2SlLIhJvhzweHookVqdXy9A4Blwvm4mIWcgGh1ZsVc/edit?usp=sharing) it is.

**Comment by radfast** [comment]
Any chance you can give me the world seed for that particular world?

**Comment by xJon** [comment]
It's a Mystcraft age, does it have a seed?
Anyway I'm currently not next to the PC, but I'll try to in about 24 hours from now.

**Comment by radfast** [comment]
The world seed for the whole world.

The Galacticraft crash occurred on the Overworld (even though you weren't there!)  I want to try to create exactly the same world as you and see if I can make the same crash on my PC ... it's the best route to finding a fix...

**Comment by xJon** [comment]
I see. I'll try to give you it as soon as I'd be able to.

**Comment by xJon** [comment]
`-7`
![image](https://cloud.githubusercontent.com/assets/8945347/13298901/6222fef0-db41-11e5-9f96-45397eefdf53.png)

**Comment by radfast** [comment]
Thank you.

The crash is fixed in [new build 145](http://ci.micdoodle8.com/job/Galacticraft-1.7/445/).  In the situation which would have crashed, Galacticraft will now color the map region in black.

I still don't actually know the exact reason for the crash, but it seems like one of your other mods is not properly registering all of its biomes - one of the biomes (probably a rare one) is coming up as ```null```.  If that's not causing you any other problems, there's nothing to worry about here.

**Comment by xJon** [comment]
@radfast Well you can see in the [list](https://docs.google.com/spreadsheets/d/1C2SlLIhJvhzweHookVqdXy9A4Blwvm4mIWcgGh1ZsVc/edit?usp=sharing) I gave you, the class of biomes 155-157 appears as null.

**Comment by radfast** [comment]
Yes, I see that, although those are vanilla Minecraft biomes - they are the 'M' versions of biomes 27,28,29 which include Birch Forest Hills.

As I say, I'm not too sure what's going on with your biomes, but it's definitely not a Galacticraft issue.  Unless it's causing other issues, I wouldn't worry about it.  When you have so many mods there are always going to be small issues and imperfections.

**Comment by xJon** [comment]
@radfast No they don't cause other issues, but do you think I should link this issue to Biomes O' Plenty?

**Comment by radfast** [comment]
No.  I can't be sure it's a Biomes O'Plenty issue.  You have 5 other mods which also create biomes.

**Comment by xJon** [comment]
@radfast Okay. Thanks for the quick replies
