### ISSUE TITLE
Space Station/Space Race/Slimeling/Some machines textbox doesn't support with keyboard typing function

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#2110]
![2559-02-25_04 26 12](https://cloud.githubusercontent.com/assets/6128413/13301937/e13a6592-db79-11e5-8913-8dfdfccb47f1.png)
![2559-02-25_04 26 33](https://cloud.githubusercontent.com/assets/6128413/13301938/e140996c-db79-11e5-9ef1-ec32b079d1e4.png)
![2559-02-25_04 39 25](https://cloud.githubusercontent.com/assets/6128413/13301939/e1442942-db79-11e5-956c-b15f962fd22f.png)
![2559-02-25_04 39 36](https://cloud.githubusercontent.com/assets/6128413/13301941/e152f1ca-db79-11e5-924e-eb66dd2efbdf.png)
![2559-02-25_04 39 54](https://cloud.githubusercontent.com/assets/6128413/13301940/e14f4a0c-db79-11e5-8acd-38d5627fb126.png)

Keyboard function I mean Ctrl + C, Ctrl + V, Ctrl + A etc. I don't know how to explain it. -_-

**Comment by dj3520** [comment]
It isn't treated like a selectable text box, which would allow cut, copy,
and paste.

**Comment by radfast** [comment]
This is a feature request.

If you want to code this + make a Pull Request, that will be awesome.

But I don't see this as a current issue with the mod.  Ctrl+C , Ctrl+V is not really necessary for a frequency number or a team name or space station name.
