### ISSUE TITLE
textures.gui.celestialbodies are 12x12 size not 16x16, affects rendering on very old graphics hardware

### ISSUE THREAD

**Issue by linkerblox** [micdoodle8/Galacticraft#2111]
hi when i get on galaxy map the planets dont have texture they are all white!!! can some1 help me?
![2016-02-24_21 38 40](https://cloud.githubusercontent.com/assets/17463648/13306199/6ca2ff8e-db40-11e5-8e35-d59ba2638d80.png)

also when im on my sateliete and the earth is all white and no texture D:

**Comment by EzerArch** [comment]
What do you have installed along with? Including MCPatcher, Optifine, shaders pack etc.

**Comment by radfast** [comment]
I cannot reproduce this, everything looks fine here.  I need more details of your setup to try to understand this:

It would be helpful to know:
* which exact Galacticraft version and which Forge version?
* any other mods installed (see EzerArch list for the most important to mention)?
* do you see the same problem with only Galacticraft (latest version 445) installed, no other mods?
* is this a problem which started only recently, like everything was OK in some older Galacticraft a month back?
* PC or Mac? Java version? Do you have any other issues in Minecraft except this? 

It would also help if you can please build a Display Screen, switch it to the solar system view (that should be the second screen in), and post a screenshot of what you see.

**Comment by linkerblox** [comment]
galacticraft 3.0.12.444
PC windows 7 64 bit
this happened on the first time i played galaticraft on minecraft 1.7.10
(on 1.6.4 was ok)
forge10.13.4.1614-1.710
minecraft 1.7.10
mods installed
industrialcraft
buildcraft
railcraft
plasmacraft
optifine D1
NEI
codechickencore
mapwriter 2
damage indicators
mo villages
somnia
kradxn xray
infinite lava
keeping inventory

**Comment by linkerblox** [comment]
i updated to last version
and i still need help

**Comment by radfast** [comment]
Can you try without Damage Indicators?  (If it's not that, also look at removing MapWriter2 and the xray.)

If removing one of those "fixes" it then please let me know, then we can maybe find a proper solution.

I can't test Damage Indicators, it's a discontinued mod and I don't have a 1.7.10 version to test. :(

**Comment by EzerArch** [comment]
> I can't test Damage Indicators, it's a discontinued mod and I don't have a 1.7.10 version to test. :(

I got you fam! [DamageIndicatorsMod.zip](https://github.com/micdoodle8/Galacticraft/files/147506/DamageIndicatorsMod.zip)

**Comment by linkerblox** [comment]
nope still no texture
but thats not a big deal i will try to find a solution myself

**Comment by radfast** [comment]
> It would also help if you can please build a Display Screen, switch it to the solar system view (that should be the second screen in), and post a screenshot of what you see.

**Comment by jochuan** [comment]
i think that your graphics card doesn't support textures that have dimensions that aren't a power of two

**Comment by radfast** [comment]
@linkerblox  (and anyone else with this issue):  do you have the issue with **only Galacticraft** installed?

**Comment by jochuan** [comment]
to see if your graphics cards dont support textures that aren't a power of two try using pixelmon or jurassicraft if any mobs of these mods are blank your graphics card dont support textures that aren't a power of two

**Comment by C1ffisme** [comment]
@Jochuan couldn't he just use a texture pack to reset one of his textures to 15x15? That seems a lot simpler than downloading a whole mod to test for this problem.

**Comment by linkerblox** [comment]
other addon's planets have texutre like more planets the new planets that are added have texture

**Comment by linkerblox** [comment]
also after i unistalled mapwriters i installed reis minimap

**Comment by EzerArch** [comment]
> OptiFine scales the offending textures to power-of-2 dimensions in order to keep the mipmaps.
You can disable the mipmaps to stop the rescaling.

> When most of the textures are higher resolution (lets say 64x), OptiFine may upscale smaller textures to 64x in order to enable all 6 levels of mipmaps (64 = 2 ^ 6). It checks what percentage of the textures are to be upscaled and does it only if the atlas texture increase is going to be minimal. (by sp614x from: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1272953-optifine-hd-h3-fps-boost-hd-textures-shaders-and?page=2365#c49048)

Does this help?

**Comment by linkerblox** [comment]
my mipmap levels are already off

**Comment by linkerblox** [comment]
i also dont have graphic cards

**Comment by dj3520** [comment]
Please provide a screenshot with the F3 debug text.

**Comment by radfast** [comment]
> @linkerblox (and anyone else with this issue): do you have the issue with only Galacticraft installed?

Thanks though for the info about More Planets - that's a useful clue.

**Comment by linkerblox** [comment]
this is my f3 screenshot
![2016-03-06_10 55 19](https://cloud.githubusercontent.com/assets/17463648/13555058/dccde7da-e395-11e5-9ebc-98b50e431c73.png)

**Comment by radfast** [comment]
> @linkerblox (and anyone else with this issue): do you have the issue with only Galacticraft installed?

**Comment by linkerblox** [comment]
still happening with only galaticraft installed
yeah its graphic card problems and i think i should install a better one

**Comment by dj3520** [comment]
I doubt this is a graphics card problem.

As requested, please test this with _only_ Galacticraft installed in your environment. If the issue persists try with a fresh minecraft install. If the issue goes away, add in the mods you normally use one-by-one and checking the issue again each time a mod is added.

**Comment by SteveKunG** [comment]
I think should buy a new graphic card or upgrading your computer.

Here is system requirement for Minecraft : https://help.mojang.com/customer/en/portal/articles/325948-minecraft-system-requirements

Also I can't find anything about minimum system requirement for Minecraft Forge.

**Comment by TheQuadShot** [comment]
I would use the Performance Monitor (Control Panel -> Administrative Tools) and/or the Resource Monitor (Launch the Task Manager(crtl-shift-esc), goto the Performance Tab, button at the bottom of page) and start profiling my machine/environment. I use that data to determine my system requirements for how I use my machine (which is nothing like anyone else would(in most cases)). You can "drill down" to monitor individual threads/processes if you really wanted to. Anyway that's how I make a determination of that kind.

**Comment by radfast** [comment]
Lol at those system requirements, they are an invention.  It's a Java game so it's system independent, and the graphics settings can be turned down so that it can run on a very basic system.  And lots of young kids are running Minecraft on an old or second-hand laptop PC which can be 5 years old.

The only hard requirement is OpenGL2.0 on your GPU, which was a requirement introduced between versions 1.7.2 and 1.7.4.  This is one reason why we chose to release Galacticraft 3 with dual support for 1.7.2 **and** 1.7.10, so that the kids with old laptops can still enjoy it.

This issue is easily fixable, just needs the same textures to be 16x16 pixel files, but uv chosen so that the texture on screen is identical to how it is now.

**Comment by radfast** [comment]
Fixed for next 1.7 build.  This does matter, because people are still playing 1.7.
