### ISSUE TITLE
Cryogenic Chamber not working

### ISSUE THREAD

**Issue by Cjoe30** [micdoodle8/Galacticraft#2112]
The Cryogenic Chamber on the moon seems to be acting like a normal bed, the player animation plays like a normal bed and the game does not jump to the next sunrise. Any help would be appreciated.

SMP Galacticraft version 1.7-3.0.12.445 installed over a Feed the Beast; Horizons: Daybreaker modpack with a few additions:
-Bibliocraft
-CustomNPCs
-EnchantingPlus
-Endercore
-EnderIO
-InvisibLights
-Magicalcrops
-MCA
-PowerTools

**Comment by radfast** [comment]
Thank you for reporting this.

Yes, looks like the Cryogenic Chamber needs some attention, see also #1159 and #1357.  The player positioning inside it is also wrong ...

I hope to have this fixed in the next few days.
