### ISSUE TITLE
Oxygen Pipe network - Huge performance hit on server

### ISSUE THREAD

**Issue by UbiPangolin** [micdoodle8/Galacticraft#2117]
Hello,
I updated galacticraft from version 406 to 434 a while ago and the performance on my server plummeted.
I went back to version 406 and since then, I tried updating every time I saw a new version of Galaticraft. Unfortunately, the issue was still there for each version. I tried updating again today to version 445 and that didn't fix anything :(.

Context:
I have a large Mars base shaped like a torus (diameter is 96 blocs) with half a sphere (16 blocs high) in the middle that has probably 110 sealers all equipped with thermal controllers in order to breathe normally :). Performance is perfectly fine on version 406 as the server update time is around 12 ms and the tick is stable at 20.
As soon as I run the server with any version of Galacticraft higher or equal to 334, I get constant "Can't keep up" message on the server and TickProfiler reports an average of 6-7 TPS. It may be caused by a change prior to version 334 but I didn't test this (Sorry)

It seems that the air network feeding the sealers could be the culprit as the profiler I use (TickProfiler) points to TileEntityOxygenPipe and TileEntityOxygenStorageModule. 
I have attached various logs to this issue:

[Server-latest.txt](https://github.com/micdoodle8/Galacticraft/files/149376/Server-latest.txt)
[fml-server-latest.txt](https://github.com/micdoodle8/Galacticraft/files/149375/fml-server-latest.txt)
[profile.txt](https://github.com/micdoodle8/Galacticraft/files/149377/profile.txt)

I ran the server only a few minutes to generate the logs but the issue is the same if I let it run for hours.
Please note that I only update Galacticraft and nothing else to isolate the issue.

Thanks!

**Comment by radfast** [comment]
Thank you for reporting.  This is extremely helpful.  There have been other reports of performance hits linked to the Oxygen Storage Module (@EzerArch...)

Just to be clear: you don't have any information on which version **between** 406 and 434 resulted in the change?  You can get old versions from the changelog, look on the left side: http://ci.micdoodle8.com/job/Galacticraft-1.7/changes

It would help me so much if you have time to identify the version which caused this, by a binary search technique - so test version 420 with your world: lag or no lag?  If no lag, then test version 427.  etc  etc

Alternatively you could upload your Mars world folder with that build for me to test (though I would need all the same mods as you to load it, and that could start to be difficult if you have a big modpack...)

**Comment by radfast** [comment]
hmm ... I'm gonna make a guess that **version 411** is what caused this change

So if you can test version 410 against version 411 for your world that would be really great.

**Comment by UbiPangolin** [comment]
Sure. I started testing the versions you pointed out and will report back. I may take a bit of time though :)

**Comment by UbiPangolin** [comment]
Also, on a side note, I noticed a while ago that if an oxygen network is partially loaded, let's say because there is a missing chunk loader for an oxygen sealer but the oxygen extractor is always loaded, the performance degrades over time (cpu & memory wise). 
A fix I found was to add chunk loaders everywhere so that the entire network is always loaded (currently the one I use). Another fix is that you can use a drawbridge (TMechworks) or a turtle (computercraft) to break an oxygen pipe on the network and put it back in place so that the oxygen network gets recreated by the code. This certainly allows the garbage collector to free resources and the oxygen network code to start fresh again.
I traced the code a while ago (xmas holiday) and had a hint that the oxygen network has a bug when determining where to send oxygen if there is no machine connected (because it is not loaded yet). I unfortunately didn't have more time to investigate further. Plus, I don't have JDK installed (too lazy to install it :p).

**Comment by radfast** [comment]
thanks, could be ... The oxygen network code is (unfortunately) still based on electricity network code originally coming out of the Universal Electricity project in MC 1.4.7, which was low performance.  (Galacticraft's _electricity_ network uses high performance code updated by me, but I haven't paid so much attention to the oxygen network.)

**Comment by UbiPangolin** [comment]
Well, as long as the network is always loaded, it is fine, I wouldn't worry much about it :). I mean it has worked until now, so it is quite reliable. I consider this as by design, as I guess it is not that easy to track if a chunk is loaded or not.

**Comment by radfast** [comment]
I think we have to deal robustly with bases with unloaded chunks.  Minecraft loads and unloads chunks all the time, it's the nature of the game.

One thing to look out for here is simply whether your Oxygen Sealers have a constant supply of oxygen - if they are running out of oxygen intermittently this could be a major source of lag, as it means the space becomes unsealed for 1 tick (or the sealers have to re-arrange themselves so that another sealer takes up the task of being the "head" sealer, which also places a heavy load).

We could do semi-forced chunkloading on oxygen pipe networks.  By "semi-forced" I mean that if one pipe in the network is chunkloaded, then it chunkloads the whole network.  It wouldn't act as a chunkloader otherwise.  But this is open to abuse - for example if a server allows players a 1-chunk chunkloader, they could place an oxygen network on that chunk and so spread the goodness over as many chunks as they want.

**Comment by UbiPangolin** [comment]
I understand that it might not be the best solution. I actually saw that the code in the oxygen extractor is extracting a fair chunk oxygen every x ticks and uses the internal storage to feed the network until the next update. This made some extractors starve and others being full, which was costly. I saved around 2ms by increasing the number of extractors (x 1.5) and use oxygen storage as buffers to stabilise the oxygen extraction system. So to answer your question, I have more extractors than necessary, in a 15x15x11 box full of leaves :).
Anyway, I am not here to criticize, I wouldn't have the patience and the ideas you and other collaborators have to create and maintain such a mod.

**Comment by radfast** [comment]
One problem people are not realising - I think - is that the Oxygen Storage Module currently cannot pump out much oxygen per tick, so unless you have many Oxygen Storage Modules in parallel, you can have an oxygen-starved network even when you have enough Oxygen Collectors.

I am significantly increasing that output rate, next GC build.

Any more info on which in the range 406-434 caused the lag problem to start?  I understand that testing this takes a lot of time, to download the mod + restart the game.

**Comment by UbiPangolin** [comment]
410 is fine but I get a crash at 411 related to more planets. So I removed that mod and I started again. Hence the time it takes for me to report back :).

For the oxygen storage, I indeed have them in parallel to ensure that the output is more than enough. The sealers never starve of oxygen (internal storage are always full). I always have systems that generate excess energy or oxygen just in case ;)

**Comment by UbiPangolin** [comment]
And I have a crash with 411 and 413 without more planets: 

at micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.check(ThreadFindSeal.java:359)
	at micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.<init>(ThreadFindSeal.java:92)
	at micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.<init>(ThreadFindSeal.java:47)
	at micdoodle8.mods.galacticraft.core.oxygen.OxygenPressureProtocol.updateSealerStatus(OxygenPressureProtocol.java:64)

Trying later versions to see if that fixes the issue

**Comment by UbiPangolin** [comment]
Yes, 419 fixes it :)

**Comment by radfast** [comment]
yes, sorry, some of those intermediate versions might have crashes - sorry about that, the ChangeLog may be a guide if one or two versions later it says "fixed crash with X".  You are best testing this without addons as they may be locked to a specific GC version.

**Comment by UbiPangolin** [comment]
Oh man, I want to apologize as it turns out More Planets was the culprit after all. Even though I don't use anything yet from this mod and the fact that I updated both your mod and theirs, if I remove it, my server runs smoothly again, maybe 1 or 2 ms slower, but I can certainly live with that!
So here goes More Planet and sorry if I wasted your time :(

**Comment by UbiPangolin** [comment]
I will run a last test to make sure More Planets is the one to cause havok on my server.

**Comment by radfast** [comment]
Yes please.  It's very strange, as nothing in More Planets makes use of oxygen pipes.

**Comment by UbiPangolin** [comment]
Sorry it takes a bit of time, I try to have a 100% repro.

**Comment by UbiPangolin** [comment]
Back to square one :(. More planets has nothing to do with it after all. It seems it was a fluke

**Comment by UbiPangolin** [comment]
I am sorry it takes so long to give you some proper feedback

**Comment by UbiPangolin** [comment]
I am confused now. If I update GC version by version, it all works fine, with or without More Planets.

**Comment by radfast** [comment]
Sounds like it's not based on the GC version but instead on something in your setup.  Like an intermittent problem which depends on some condition - I hope something simple like whether there is enough oxygen, but worst case could be something like which order the chunks loaded in.

**Comment by UbiPangolin** [comment]
And no, it happens again, I left the server running a bit longer this time.

**Comment by EzerArch** [comment]
> I am sorry it takes so long to give you some proper feedback

I know the struggles. :<

**Comment by radfast** [comment]
@UbiPangolin  I should have said this earlier.  Please can you switch on 'Enable debug logging' in your ```.minecraft/configs/Galacticraft/core.conf```  This should give you in your log - every few seconds - some timing and other information about how the sealers are working.

**Comment by UbiPangolin** [comment]
Ok, I turned that on. In the meantime, it seems something happens between vers 419 and 421. If I let 419 run for 10 minutes, I don't see any cpu spike or "can't keep up" message. But with 421, after 10 minutes, I had a few spikes and about 6 or 7 "can't keep up" messages.
I will run again both versions with the debug on.

**Comment by radfast** [comment]
There is no change between 421 and 419 that can affect oxygen performance.

I'm afraid I think again this difference is likely based on some different condition in your test run for 421 - not the actual GC version number.

**Comment by UbiPangolin** [comment]
Ok, let me run the server longer on v419. It's the only version I can run after 410. The others in between crash unfortunately.

**Comment by UbiPangolin** [comment]
Oh I forgot to let you know earlier, but I left the server running 20 minutes on v410 when I started testing and no issue there.

**Comment by radfast** [comment]
interesting, so definitely somewhere between 410 and 421?

/me goes to read changelog again

**Comment by UbiPangolin** [comment]
v411 definitely brings a lot of optimizations, so that might be there, as it was your first guess earlier today. Sorry, the longer I test this, the worse my help is.

**Comment by radfast** [comment]
The optimisations were minor, really - just clearing some references so that the JVM garbage collector can recover the memory sooner.

Actually the sealer check is _horrible_ in terms of memory use, in a large volume it creates thousands of Java objects for very temporary use.  I'm looking if I can do that more efficiently but this is super hard, getting into quite a specialist area.

**Comment by UbiPangolin** [comment]
Maybe you could preallocate memory per sealer and reuse it, using your worst case x 1.25. That's a trade off between memory usage and performance, but quite efficient in games like open world ones (paging system with preallocated memory is mandatory in those). If you have sealers sharing space, you could use memory from a shared pool. Well, these are ideas but I haven't seen this code and it is probably hard to do and/or long. Plus, I am pretty sure you thought about this already. 

Oh and I confirm letting the server run for 20 minutes with v419 doesn't solve the issue. I was mistaken earlier - and not patient enough - and I am sorry if it misled you.

**Comment by UbiPangolin** [comment]
Sorry, I forgot to attach the log with the debug on. Running it all again on version 419. Do I need to let it run for a while or a minute or two is enough? The log might get huge if I let it run for too long

**Comment by UbiPangolin** [comment]
Here's the log for a 5 minute run:
[fml-server-latest.txt](https://github.com/micdoodle8/Galacticraft/files/149588/fml-server-latest.txt)

I don't know what I can do else to help you guys, so here's a link to the mars folder from my world and also to the mods I use: http://1drv.ms/1RaWxpC

I hope that will help you.

**Comment by radfast** [comment]
thanks for all your help today, I hope you've found time to do other things as well.

Just to be absolutely sure:
* you are seeing the lag issue in 419
* you are not seeing the lag issue in 406

**Comment by UbiPangolin** [comment]
Don't worry, I had some catch up to do on some tv shows :). 
And yes, to confirm, I don't have the lag issue in 406, or even 410 for that matter but do have in 419.

**Comment by radfast** [comment]
OK according to that log the oxygen sealer for the big room (24259 blocks) is taking around 8ms of tick time (16%), approximately once every 9 seconds.  That's 0.089% of server time.

I'd like to get that 16% lower - imagine if fifty players on a multiplayer server all had this - but this alone cannot be the source of lag in your game, it shouldn't even have that much of an impact on the tick when it happens.

(Roughly how the sealer checks work is this: multiple sealers in a room are 'aware' of each other and only one, the 'head' sealer, will run the sealer check.  With a large collection of sealers, the sealer check is deliberately delayed - you'll see in the logs the smaller sealed rooms are checking more often.)

Everything is pointing to my attempt to help the garbage collector, added in build 411.  I'm going to switch that off now, make a new build 446, and when you're ready it would be great to know if that fixes the issue.

**Comment by UbiPangolin** [comment]
I would be glad to help. Unfortunately, I think that won't be before tomorrow as I have plans for tonight :). But yes, let me know when the build is ready and I will try it as soon as I can, if that's ok with you!

**Comment by UbiPangolin** [comment]
The garbage collection optimization could explain it as at the end of my test run, the "can't keep up" message came 2 or 3 times every 4 or 5 minutes, but hammered the server for a good minute. CPU was all over the place while the memory was stable.

**Comment by UbiPangolin** [comment]
Sorry, I hope that I won't sound too rude or condescending as it is not my goal. I checked the code regarding the Garbage Collection optimization in ThreadFindSeal.java and it is not necessary to call the Clear method on all the lists as you recreate them every time you check if it is sealed. In fact it may hurt it more than it help on large collections.
Not clearing the lists will make them go to an older generation in the garbage collection, which will run less frequently. It will actually be easier on the Garbage collector as you don't overcrowd the young generation. Plus, as soon as you reallocate the lists, this will flag the old ones and their content as "cleanable" by the Garbage Collector. It will then decide when the moment is best for it to run. 
I know this was an attempt to save memory, but it will be cleared anyway as soon as you run the check method again :). 
Anyway, I also guess you ran profiling tools and what I say might be wrong. I just have a guess that this might be the cause of the lag. Not the oxygen network in itself but the gargage collector taking too long to clean the younger generations.

**Comment by UbiPangolin** [comment]
Actually, that happened to me a while ago while programming with large datasets (databases with millions of rows in the table I seeked) that I was clearing too often. The GC doesn't run as often as we'd think and the young generation stacks up pretty quickly. At the end, any time the GC would run, the CPU would spike and application I was programming would freeze.
I hope this will help as well.

**Comment by radfast** [comment]
This ^^ type of help is _extremely_ welcome.

A reference to the ThreadFindSeal instance is retained by all the sealers which 'see' each other and have been linked through a seal check.  (Perhaps not the best way of doing it, but anyhow.)  Therefore references to the lists are retained until list re-creation next check on that same ThreadFindSeal - which is probably 5-10 seconds later.  My thinking was this was unnecessary memory retention.

But the proof is in the pudding, it looks like clearing these is a disaster performance-wise - presumably for the reason you give, overcrowding the young generation.

I'm currently looking at whether I can create a type of HashSet using primitives, in which case I can switch these to longs.  The main reason for using 25000 ```BlockVec3``` objects is for the good performance of ```checkedLocal.contains(vec)``` where ```checkedLocal``` is a HashSet.

**Comment by UbiPangolin** [comment]
I could still be very wrong about the garbage collection. If there's only one reference to the shared entity - the "head - 25000 elements isn't that much. In the example I used, I was manipulating a lot of data in a very short span of time, so it was more understandable to get some bottleneck.

Anyway, looking at the BlockVec3 object, you have overriden the Hashcode and equals methods. You know it is dangerous to recompute the hashcode on class members that change. When you actually add an element to a hashset or dictionary, it computes its hashcode for further lookups at that moment. If you update the element itself (let's say change one of its members), the hashset won't be able to rely on the hashcode method and will have to fallback on the equals method. As it has no idea it has to fall back to the equals method, it will of course loop through all the elements calling the hashcode method first and then call the equals method, which is a hit, especially on large collections. Why don't you compute an ID when you create the object, yes a bit more memory again, but then, just store this ID in the hashset for faster retrieval later on, as you don't really care about positioning in this case? Well you do care about positioning, but the positions might not change while you run the update. Am I correct on this? Anyway, you may waste memory somewhere, but you may win it back somewhere else ;)

That's an idea I would try, maybe it won't help at all :).
Also, sorry, I have to head out now. Just post updates on when I can test the next build I will be glad to test that tomorrow morning (North American east coast time ;))

**Comment by radfast** [comment]
> You know it is dangerous to recompute the hashcode on class members that change. When you actually add an element to a hashset or dictionary, it computes its hashcode for further lookups at that moment.

Yes, I know :)

> If you update the element itself (let's say change one of its members), the hashset won't be able to rely on the hashcode method and will have to fallback on the equals method. As it has no idea it has to fall back to the equals method, it will of course loop through all the elements calling the hashcode method first and then call the equals method, which is a hit, especially on large collections.

In all the uses where BlockVec3 is stored in a HashSet or HashMap, its fields x, y, z will not in practice change.  They are not immutable as in MC 1.8's block references but in ThreadFindSeal they are not changed.  Only the sideDoneBits are changed, and those are not used in the .equals() and .hashcode() methods - totally deliberately, I designed BlockVec3 primarily for use in this code.

I am looking at using an integer ID for the block position instead, as soon as I find a fast way to check whether a collection of (say) 25000 unsorted integers contains a specific integer.  The integer ID will be based on relative x, z position from the sealer, 9 bits per coordinate (8 bits for the y coordinate) allowing a range of  +/- 255 blocks which I think is enough.

**Comment by UbiPangolin** [comment]
I was sure that you knew about the hashcode, but it's a habit of mine to try to challenge the obvious. We do this all time at work and it sticks with you after that! :)

Another approach, if we ignore the memory side of it, is that you could simply generate a UUID from the coordinates, where x represents the first 32bits of the UUID, y the next 32 bits and z the next again. The last bits could be used for additional identification or could be set to 0. 

It worked rather well in the code I've implemented not so long ago where we had to draw about 100 000 elements on a 2D map based on 3D coordinates, where we had to order the elements by the Y coordinates. At the end, the generation of the UUID looked like this (it was in C# but the principle is the same):

// In C#, BitConverter.GetBytes => converts any type to a raw representation in bytes
// In C#, Concat just concatanes multiple arrays, in this example below, we will end up with an array
// of 16 bytes (4 for each coordinates + an empty array for the last bits)
byteArray[] coordinatesArray = BitConverter.GetBytes(x).Concat(BitConverter.GetBytes(z)).Concat(BitConverter.GetBytes(y)).Concat(new byte[4]);
Guid myId = new Guid(coordinatesArray);

You can then use that in a Dictionary for fast retrieval or just this as your key. It's just an idea and might not be what you are looking for, but maybe it is overkill to do compress data in an int. 

Anyway, on the bright side, v446 has been running for the last 30 minutes on my server and it's look good so far :)

**Comment by UbiPangolin** [comment]
Nearly an hour now and so good so far. No lag when in game, not cpu spike anymore and no more "can't keep up" messages. Yay! Good work!

**Comment by radfast** [comment]
Great, thanks for the feedback.  I think this issue can now be closed.

It's ridiculous that clearing those arrays should have such a serious performance hit on your server, but I completely understand the reasons.

You're welcome to continue to chat here, it's useful + fun to have someone who actually understands coding looking at the tougher parts of the mod!  If you have any better ideas or solutions definitely let me know (or make a PR...).

See also: https://github.com/micdoodle8/Galacticraft/issues/1468 which has not been progressed as it proved to be lower performance in my testing, though I might pick up some of the ideas from that again in future.  Meanwhile I have now found a way to trace leaks, using route data which was 'hidden' within the existing algorithm, so the next feature in Galacticraft will be leak detection.

Thank you very much for the suggestion but I don't see a ```UUID``` as helpful.  That is another new object, so it doesn't have any performance advantage over a ```BlockVec3```.  And a ```BlockVec3``` is tailor-made for the current purpose.  Generally speaking, I'm looking for a solution with **more** bitwise operations and **fewer** objects and memory accesses.  My rule of thumb is that bitwise operations are very high performance, simple in terms of both Java bytecode and translation to native code.  Memory accesses are lower performance, especially random accesses.  Object creation is the lowest performance, once you also take into account of the cost of the garbage collection later.

I am looking very seriously at whether it can all be done using ```int``` (or possibly a different primitive, i.e. ```long```).   I have looked at various **IntHashSet** implementations.  There are several of those - including one written by Goldman Sachs, lol - but they are all general purpose with too much overhead for my liking.

My current inclination is to code something custom, somewhere between an array and HashSet with a fixed number of buckets.

**Comment by UbiPangolin** [comment]
That makes sense for the UUID if you want to go to a lower level of implementation, because you run this in one go every update.

I don't know how much work would be required for that but I would spread the computation across multiple updates and partition the data for faster retrieval. The worst case would remain identical, or a bit slower because there's always an overhead with this kind of method, but it would occur less frequently.

A friend of mine used to work on the bullet physics aspect of a military shooter, and the computation was so heavy that they had to spread the computation over multiple frames, by splitting the data in two and process each half every other frame. That of course lowered the refresh rate but was a lot less heavy on the game itself, and was still working well for their need.

What I mean by this is that instead of running the update every 9 seconds or so, just store the data you need at that moment and do the computation over multiple updates. I saw that you had some sort of layers, maybe process only a few layers at a time. Maybe that won't help as the thread itself is on its own, but I still believe it could certainly be a relief for the server when the time comes to compute all this.

All I mean with this, is that sometimes, instead of trying to optimize a single complex piece of code by making it faster (like optimising the way to store in a hashset), just think how it could run on multiple threads in parallel if possible, and if only one thread can be run at a time, just run the sequence over multiple updates. It's not something that is unheard of, at least not from my experience :).

**Comment by radfast** [comment]
Thank you :)

On a multiplayer server, there could be several bases like yours all loaded together, let's say 50 in a worst case scenario.  Therefore we do not have the luxury of running code over several ticks.  Currently the TileEntityOxygenSealers are managed so there should not be two sealers being checked in the same tick on a server.

More generally, a problem when coding for multiblock structures for modded Minecraft - you can say a sealed base is an extreme example of a multiblock structure - is that **blocks can change** every tick.  Therefore it is necessary to check all the contiguous blocks in the same tick.  Same for energy or fluid networks.  Otherwise you will get invalid results if something changes.

You can see the same issue in vanilla Minecraft with lighting.  When there is a lighting update, all connected blocks are checked in the same tick to determine how the light propagates - this causes a massive performance hit on servers, up to 40% of tick time can be spent on lighting updates. 

As you probably spotted, the oxygen sealer check code **is** capable of running asynchronously in a separate thread, but that feature is currently disabled.  The multi-threaded code could be re-enabled again, but there are potential issues when accessing the map.  Again this is because if two map accesses fall in different ticks then the blocks could have been changed.  That doesn't matter too much, with lighting - it could in theory result in small lighting glitches, but Spigot has moved the vanilla lighting update to a separate thread without any reported issues.  For an oxygen sealer it's more important not to have glitches, because players and farm animals take damage if a base goes unsealed.

If I eventually decide to switch this over to the system in the ```oxygen-alt``` branch, that may be more suitable for running asynchronously, it does not need so many map accesses.

**Comment by UbiPangolin** [comment]
I had a hint that you already thought about this, multi threaded and across multiple ticks that is :).

I understand why you did it this way, knowing MC constraints. And the fact you already run each master sealer on different ticks so it isn't as much as a burden than having all of them together is nicely thought.
I also guess you already thought about doing incremental checks, only flagging the blocks that have changed and work from there. It could be done by having some code that acts as watcher that keeps track of changes between two updates, so you can use that information when a real update is needed.
I haven't checked your code any further, so I have no idea if it's there or not. I guess the whole point of having an ID into a int with the fastest lookup you can get is for this purpose.

I know that MC is a wonderful game but also a pain as you have to constantly consider that blocks have changed :(. Performance wise, it is unfortunately far from ideal. But as I said earlier, you have made a really nice mod and I am quite impressed with the work you put into it. I wouldn't worry as much about people having 50 huge bases altogether. Every time I play with friends of mine on the server, we're all well aware that we shouldn't push things too much, like chunk loaders, space bases, factories... And I am pretty sure that every server is a bit like this. It is part of the game's limitations. If not, you can't really blame yourself for having people using 100 sealers a 50 different locations with chunk loaders everywhere :)

Keep up the good work, you have made my favourite mod for this game!
