### ISSUE TITLE
You can see your own player sleep in a bed

### ISSUE THREAD

**Issue by chaNcharge** [micdoodle8/Galacticraft#2121]
What I mean is that when you go to sleep, you can see your player actually in the bed, mostly just the inside of your head. This bug usually reproduces when you have Thermal Padding gear and/or armor equipped. This bug also reproduces with and without OptiFine. I noticed that this bug is similar to issue #2073, I'm not sure if this is the same issue however, but they both involve rendering the player incorrectly when using beds. I'm using Galacticraft build number 446.

To Reproduce:
1. Set time to night in Overworld
2. Go to sleep (if nothing occurs, continue on to step 3)
3. Leave the bed and equip some thermal padding gear and armor (I used diamond armor for testing)
4. Go back to sleep. Notice how you can see the inside of your head.

![bed bug](https://cloud.githubusercontent.com/assets/11594018/13387305/1f8ca998-de6a-11e5-95a5-b16c5b8a04e6.png)

**Comment by EzerArch** [comment]
Are you using other mods besides OptiFine and Galacticraft?

I'll try to reproduce it.

**Comment by radfast** [comment]
hmm, looks like we could have positioned the sleeping player a bit **too** accurately ... !

Please list any of the following which you have installed:
* PlayerAPI
* RenderPlayerAPI
* SmartMoving + SmartRender

**Comment by chaNcharge** [comment]
I have none of those mods installed, just Galacticraft, and yes it happens with all 4 bed angles. In the screenshot, there was others installed, but this still reproduced with only Galacticraft installed

**Comment by Fabboz** [comment]
Actually i'm using renderplayerapi and the bed work fine. (I have updated my pack to forestry 4 and at the creation of a new world i got that issue to. The api is used by zoom mod)

**Comment by radfast** [comment]
This is a strange one.

In my testing, sleeping the first time does not cause it. But sleep again, and the problem starts.

**Comment by EzerArch** [comment]
Does forge version affect the testing as in [here](https://github.com/micdoodle8/Galacticraft/issues/2073#issuecomment-187702850)?

**Comment by dj3520** [comment]
I cannot reproduce with my setup (up to _PlayerAPI_) Forge 1492 multiplayer.

**Comment by chaNcharge** [comment]
I am using forge 1614, not 1492. I haven't tested the latest version of Galacticraft yet, I was going to test it at the time I post this, but the website is down. So until further notice, I'm not sure if this is still present in the later versions.

**Comment by dj3520** [comment]
>the website is down

Downloads available for now at #2151

**Comment by dj3520** [comment]
Website has returned, [here's a free link to the jenkins](http://ci.micdoodle8.com/job/Galacticraft-1.7/)

**Comment by chaNcharge** [comment]
Ok, the bug is still present in 454, no changes about the bug since this was first reported.

**Comment by chaNcharge** [comment]
I just found a temporary fix for this issue, install PlayerAPI and PlayerRenderAPI, and player renders correctly on the bed (like vanilla sleeping). A more permanent solution could be nice though.

**Comment by chaNcharge** [comment]
Now a part of vanilla minecraft, and appears to be fixed in GC4. Closing for now.
