### ISSUE TITLE
Redstone with the creeper?

### ISSUE THREAD

**Issue by Shurik1236** [micdoodle8/Galacticraft#2123]
Почему с криперов падает редстоун? Это дисбаланс, верните как было!
<a target="_blank" href="http://radikal.ru/fp/e3b46815bf0b43cdb3883d454f97f73e"><img src="http://s020.radikal.ru/i707/1603/9b/24ba27149b0ft.jpg" ></a>

**Comment by dj3520** [comment]
Raw Google translate: Why a creeper falls Redstone? This imbalance of return as it was!
My interpretation: Why does a creeper drop Redstone? This causes more imbalance! (Second part I'm not very sure about.)

Google translate input: I don't know russian but have tried to translate using Google Translate. Are you saying that dropping Redstone messes with the game balance?
Google translate output: Я не знаю русский, но пытались перевести с помощью Google Translate. Вы говорите, что падение Редстоун напутает с игрового баланса?

**Comment by Shurik1236** [comment]
Да, я считаю это минус к балансу. Редстоун с криперов + MineFactoryReloaded (Или алмазная тележка из JABBA) = бесконечный редстоун. А в ThermalExpansion это главный компонент.
Или его добыть в шахте, или сделать ферму на спавнере из сокровищницы с луны.
Пусть лучше с криперов падает то, что должно падать. Порох.

**Comment by dj3520** [comment]
Google Translate:
Yes, I believe it is a minus to the balance. Redstone with creeper + MineFactoryReloaded (or diamond trolley from JABBA) = infinite Redstone. And ThermalExpansion is the main component.
Or is it to get in the mine, or to make a farm on spavner from the treasury to the moon.
Better with creeper falls that should fall. Powder.

Effectively, @Shurik1236 is complaining that having creepers drop redstone upsets the balance of the game. In some instances and with help from a few mods this could be seen as infinite redstone, which even with a vanilla mob farm tactic this is possible.

**Comment by Creeperman8362** [comment]
It would be difficult to make a creeper farm, since you'd need to drop moreblocks to fall in less gravity

**Comment by EzerArch** [comment]
It is an **intended feature** that Evolved Creepers drop redstone instead of gunpower and other rare drops, likewise [the other space mobs](http://wiki.micdoodle8.com/wiki/Category:Mobs). See: http://wiki.micdoodle8.com/wiki/Evolved_Creeper#Data

The standard language of this Git is English. If you don't feel confident to write in English only, you may write in any other language as long as you provide an English translation.

By the way @Shurik1236, +1 for the avatar. :)

**Comment by Shurik1236** [comment]
По английски я не умею, так что простите.
Автоматическая ферма огненных стержней.
Просто как две копейки.
Вообще другие модификации не использованы.
(Google Translate)
In English, I do not know, so I'm sorry.
Automatic farm fiery rods.
Just as two pennies.
Other modifications not generally used.
<a target="_blank" href="http://radikal.ru/fp/4ec08d99433a4f4c94e3a5b1ad46bdf8"><img src="http://s019.radikal.ru/i633/1603/35/6718caad497ct.jpg" ></a>

Ну, тут мне помог Tinkers' Construct, но можно и деревянные шипы из extra utilities использовать.
Ферма редстоуна:
(Google Translate)
Well, then I helped Tinkers' Construct, but can and wooden spikes of extra utilities to use.
Farm redstone:
<a target="_blank" href="http://radikal.ru/fp/3e3777b05ecd4cda9e92f7bb6d66d588"><img src="http://s019.radikal.ru/i607/1603/2d/278b13e649a3t.jpg" ></a>

Ради простого пороха так заморачиваться смысла нет.
А вот ради редстоуна и стержней вполне можно.
(Google Translate)
For the sake of a simple powder so few will bother.
But for the sake of Redstone and bars is quite possible.

**Comment by radfast** [comment]
Thanks guys for the translation help :)

@Shurik1236  this is intended behaviour

> риперов + MineFactoryReloaded (Или алмазная тележка из JABBA) = бесконечный редстоун.

Seriously?  You're complaining about balance and you have Minefactory Reloaded?  If you want a balanced game, don't use Minefactory Reloaded.  **MFR = infinite everything.**

Also: Vanilla [Witches](http://minecraft.gamepedia.com/Tutorials/Witch_farming) drop redstone, so this is hardly a new problem.  MFR + Witch = Infinite redstone

**Comment by Shurik1236** [comment]
Разница в том, что ведьмы редкие, и у них нет спавнеров. А у криперов есть.
The difference is that witches are rare, and they have no spawners. And the creeper is.

**Comment by XFactHD** [comment]
The witches can also be spawned with MFR.

**Comment by radfast** [comment]
Like I said before.  MFR is your problem, it is overpowered.   MFR = infinite: blaze rod, ghast tear, Nether Star, gold, ender pearl.

And frankly, if a player has the resources to go to **the Moon or Mars** to find an Evolved Creeper spawner, then I think he deserves some redstone dust!

Remember there is no redstone ore on Moon, Mars, Asteroids.  This is why the Evolved Creeper drops redstone dust.  It is absolutely balanced.

And if a player with a Fortune III pick goes mining on the Overworld for 1 minute, he can easily mine 1 stack of redstone dust.  Redstone dust is **not** a rare resource.

I do not see any reason to change this.  MFR is not a reason.  Like I said already, that mod is **grossly OP** so you can't complain about game balance if you are using it.

**Comment by radfast** [comment]
If you don't like this behaviour, I guess you could roll back to Galacticraft 429, or better:
* Download GalacticraftCore 3.0.12.429.jar
* Pull the ```EntityEvolvedCreeper.class``` out of the .jar file
* Patch that old ```EntityEvolvedCreeper.class``` into the latest Galacticraft .jar

**Comment by BlesseNtumble** [comment]
Add config and no problem...

**Comment by dj3520** [comment]
More config = more clutter in the file

**Comment by dj3520** [comment]
More config = more clutter in the file.
I haven't messed with mod tweaker but I figure this is something you could change via that as well.
Or of course follow radfast's instructions
