### ISSUE TITLE
Pumping LOX into Oxygen Storage Module does not give right amount of oxygen

### ISSUE THREAD

**Issue by dj3520** [micdoodle8/Galacticraft#2127]
Pumped a canister of Liquid Oxygen (1000mB) into an oxygen storage module via buildcraft. Yields 93 oxygen.
Placed a canister of Liquid Oxygen (1000mB) into an oxygen storage module's oxygen slot. Yields 10800 oxygen.

**Comment by radfast** [comment]
oops... 10800 is the correct amount

**Comment by dj3520** [comment]
Yes I figured that and was like "Woah this needs reported." Since I was using an IC2 bottling plant to fill, pull and place a canister in the OSM. Hooked it up to liquid and within moments all my space chickens die.
