### ISSUE TITLE
Dimensional unloading problem.

### ISSUE THREAD

**Issue by border999** [micdoodle8/Galacticraft#2128]
Whenever I go to log off my single-player world, I'm faced by a serious slow down. For whatever reason, whatever method you've used to implement your dimensions takes quite a bit of time to unload. I was curious if you could look in on this issue. It's be nice to shut off my world in under 10 minutes. By the way, your three dimensions take up 95% of that time.

**Comment by XFactHD** [comment]
How much RAM did you allocate to MC and how many mods do you have?

**Comment by border999** [comment]
3gbs of ram and 268 mods, only 263 are active

**Comment by XFactHD** [comment]
Can you allocate more RAM (about 5-7 GB)?

**Comment by dj3520** [comment]
Does it still take as long with only Galacticraft installed?

**Comment by radfast** [comment]
> your three dimensions take up 95% of that time.

I'm going to need to see some evidence for this, quite simply I don't believe it.  Are you talking about freshly generated dimensions or generations where you have build blocks from some of your 263 other mods?
