### ISSUE TITLE
[Crash] Galacticraft 446 - java.lang.NullPointerException: Exception in server tick loop

### ISSUE THREAD

**Issue by Yanniclord** [micdoodle8/Galacticraft#2130]
I have no idea what this is, can anyone explain?

http://pastebin.com/J0NmKp7Z

**Comment by Yanniclord** [comment]
It happens when a Space Station is being loaded. It does not always happen, just randomly. It might even happen while we are on that Space Station.

**Comment by Yanniclord** [comment]
Looking at the code, where the error refers to, it seems it has something to do with the dimension ID. Here:

final Integer dim = WorldUtil.getProviderForNameServer(dimension.getPlanetToOrbit()).dimensionId;

I changed the dimension IDs in the GalaxySpace file, could it have something to do with that? Though, i did not change the Mars dimension ID, and neither did i change the dynamic and static dimension ID the planet orbits, so what could the actual problem be? I only changed dimension IDs related to other planets.

**Comment by DraksterAU** [comment]
@Yanniclord Your running a really old version of KCauldron with known issues with Galacticraft.

I recommend updating to Build 185 (but not further) of KCauldron... or switching to Thermos b28 (and again, not later...) 

https://repo.prok.pw/pw/prok/KCauldron/1.7.10-1614.185/KCauldron-1.7.10-1614.185-bundle.zip
https://github.com/TCPR/Thermos/releases/28

Reason for not using the later builds is both versions contain mod breaking code... some of the mods I use do not work after these builds. That is not saying that it would be the same for you, though.

**Comment by Yanniclord** [comment]
Thank you for the hints, most people would ignore KCauldron or say "We do not support KCauldron" and such. I appreciate the hint.

**Comment by Yanniclord** [comment]
So what is better, Thermos or KCauldron? What do you recommend? What is the big difference?

**Comment by DraksterAU** [comment]
@Yanniclord @radfast Supports Kcauldron users (us!) - Just not old versions of the software :)

**Comment by Yanniclord** [comment]
Btw @DraksterAU , i see that i wont be able to use Thermos, as it requires me to modify the java arguments, as seen here: https://tcpr.github.io/Thermos/install

**Comment by Yanniclord** [comment]
@DraksterAU Any way to possibly circumvent this, or do i not necessarily need to use the Java arguments? I did write a Support Request to my Server Host, but i am not expecting them to reply that early.

**Comment by DraksterAU** [comment]
@Yanniclord I don't run any java arguments on my KC server..... or my thermos server..... Give it a go... 

I only have ~30 players online at a time on each... might be more important at higher numbers.

**Comment by Yanniclord** [comment]
Ok thank you, will do :)

**Comment by Yanniclord** [comment]
@DraksterAU Uhm, little problem when starting the server, no idea what causes it. I did delete the bin folder, downloaded the latest libraries folder from the install page of Thermos, then this happens: http://pastebin.com/9YruGrbP

**Comment by Yanniclord** [comment]
@DraksterAU Would it be possible for you to hand me your libraries folder? Since the latest libraries folder crashes the server on startup, and getting the old libraries is not possible.

**Comment by Yanniclord** [comment]
This crash does still exist, even with one of the newest stable KCauldron builds. It has to be Galacticraft, as it did not happen with build 444. First since Galacticraft updated to 446, and GalaxySpace updated to 1.0.8 has this been happening. Log: http://pastebin.com/sUWTXU9Q

**Comment by DraksterAU** [comment]
Use thermos for Galacticraft with Addons.
And GC don't fully support GalaxySpace if I remember. Not their problem if an addon isn't working.

This is not a problem for GC Devs.

**Comment by Yanniclord** [comment]
Again, Thermos is a no go, get tons of crashes with it. The issue has only happened since build 446, so its a new problem that has been occurring only since the latest build. And GalaxySpace works as it should, or i have at least not seen any problems with it so far besides this.

**Comment by dj3520** [comment]
Build 446 and up of Galacticraft should work without GalaxySpace, meaning you can't blame Galacticraft for what you're seeing.

>GalaxySpace works as it should, or i have at least not seen any problems with it so far besides this.

May I emphasize _besides this_ for you. GalaxySpace works in top of Galacticraft, which is why it might look as though Galacticraft is to blame.

@DraksterAU I cannot recommend Thermos. The devs there have acknowledged that they've messed with things a bit too much in attempts to improve performance and are working from scratch again. I tried it once and saw lots of strange behavior, even in vanilla mechanics.

**Comment by Yanniclord** [comment]
@dj3520 I opened a ticket for GalaxySpace to, lets see what he has to say about it.

**Comment by DraksterAU** [comment]
@dj3520 Both Thermos and KCauldron developers have broken things since bloodmc. It's a real shame.

That's why I have provided the recommended versions to @yannicord that have the least bugs I have seen. (thermos 28 an KC 185)

**Comment by DraksterAU** [comment]
@yannicord if you run into issues feel free to run them by me and I can share fixes if I've had a similar problem. Posting issues in the wrong place will generally be frowned upon by the developers of the mod your spamming the issue tracker for ;)

**Comment by radfast** [comment]
This one is a GalaxySpace addon issue - not specifically the addon's "fault", just something changed which they didn't yet update - now fixed by @BlesseNtumble, see #2137.

This has no connection at all with KCauldron or Thermos versions.
