### ISSUE TITLE
[Crash] Galacticraft 446 - java.lang.NullPointerException: Ticking block entity

### ISSUE THREAD

**Issue by Yanniclord** [micdoodle8/Galacticraft#2131]
So, my server crashed due to something with Applied Energistics 2 (rv3-beta5) and Galacticraft. I am using a ME Interface on a Circuit Fabricator, and it used to work well, but not it just randomly crashed.

Log: http://pastebin.com/x6bjREeU

**Comment by DraksterAU** [comment]
Use Rev 2 build 28.

Rev 3 breaks in Cauldron servers from what I have seen..... with out without GC.

**Comment by Yanniclord** [comment]
Yes but in rev 2 there is the problem, that if the AE system is to big, it won't work properly. Some bus stop working, cables run out of channels and so on. Rev 3 is more stable than Rev 2, and so far this has been the only problem with AE, so it probably is GC in this case.

**Comment by dj3520** [comment]
> if the AE system is to big, it won't work properly. Some bus stop working, cables run out of channels and so on

I thought this was a feature in AE2.

**Comment by Yanniclord** [comment]
Yes the channel system is a thing, but if the AE system in general is too large, some stuff just stops working. To fix that, you need to replace some of the Controller blocks, aka break them down and place them back. Due to that, i am quite sure it is not intended that the whole system starts skipping some export/import bus or ME interface. The problem is, they SEEM like they work, due to their channel ends being lit blue, which means they are connected, but they don't import or export anything. Once you "reload" the AE system, they work properly again.

**Comment by DraksterAU** [comment]
@Yannicord Regardless, if you want to report ae2-cauldron bugs the Galacticraft forum is not the place to post it.

I can speak from experience, your better off using rev 2.

Getting a perfect pack with Cauldron is basically impossible... Performance hits do exist.

**Comment by radfast** [comment]
This is not a Galacticraft issue.


AE2 is crashing when vanilla Minecraft methods are used to detect whether the AE2 block is emitting a redstone signal.

Any redstone-dependent vanilla block - e.g. door, piston - would provoke a similar crash if placed next to an AE2 block.

This issue should be reported to the AE2 dev team if it's not already fixed in AE2, so test latest before reporting.
