### ISSUE TITLE
[Opis] Large number of TileEntities created by Enclosed wire and pipe

### ISSUE THREAD

**Issue by kernelstubbs** [micdoodle8/Galacticraft#2134]
I was getting severe tick lag - 4500ms+ so I installed opis to track the issue which was occurring in the Asteroid Dimension.  However, Opis is showing the lag originating from items in the Mars Dimension and also revealing that chunks are loaded there.

If I return to the overworld, the lag continues and always from -30

I've included screen shots where Tick lag will spike.  The first is from last night and the following two are from this morning when I logged in.

I'm running FTB DW20 1.10.0 with Galacticraft added...so fastcraft and I added optifine as well but chunk loading is set to normal.

I've seen a number of other threads with Oxygen issues but this seems new.  The problem didn't start until I sealed an asteroid that was large enough to require 6 sealers...however...since the lag is NOT occuring in the Asteroid dimension...it's as though Asteroid DIM is trying to pull oxygen from Mars DIM.  If I visit MARS, which I can't right now...the lag stops...but only while I'm there.  I can't get there right now, but after a server reboot, I'm going to try to chunk load MARS and see if that helps.  Should be about 8-9 hours from now...

<img width="918" alt="screen shot 2016-03-08 at 7 12 49 pm" src="https://cloud.githubusercontent.com/assets/17745384/13637831/6c23e6a8-e5d7-11e5-8640-54e325487300.png">
![screen shot 2016-03-09 at 9 04 28 am](https://cloud.githubusercontent.com/assets/17745384/13637832/6c2f6438-e5d7-11e5-8b5a-0ce256bd0a4a.png)
![screen shot 2016-03-09 at 9 07 06 am](https://cloud.githubusercontent.com/assets/17745384/13637833/6c2f9336-e5d7-11e5-9fb9-1d1ee20c90fa.png)

**Comment by kernelstubbs** [comment]
I would also like to add...that I love this mod!!!

**Comment by Yanniclord** [comment]
What Galacticraft version do you use?

**Comment by kernelstubbs** [comment]
Sorry - I'm on the latest version .446

**Comment by Yanniclord** [comment]
That is odd, did you try going there once? It fixed it for me. The lag persisted UNTIL i went to where it did lag, then it stopped lagging, even if i was absent. I had the same problem as you, but with Space Stations, see here #2129

**Comment by kernelstubbs** [comment]
I did, Lag stops instantly after landing at MARS base but the issue recurs if I return to the Asteroid dimension after a few minutes of being there.

Last night, I rebooted the server and it was running OK - but this morning, I logged in and the tick rate was 4k+.

I did read #2129 and at a second glance seems related - but my MARS base is extremely small, I'm not using GalaxySpace and my server isn't crashing.  I can try -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy on my server tonight and get back to you.

I'll also do some prodding around to figure things out...but even after a reboot, without going to the MARS base, the lag occurs as soon as I load the Asteroid dimension.

**Comment by kernelstubbs** [comment]
...seems similar to #2117 as well...but as I said, my MARS base is small.  It's a 9x9 with two 1x2 tunnels that are maybe 12 blocks long apiece?  2-3 collectors, one sealer and a bubble generator.

**Comment by kernelstubbs** [comment]
Can confirm:

1. Those Java args do nothing.
2. Chunk Loading the dimensions fixes the issue
     a. This leads me to believe it's a problem unloading the dimension...
     b. Upon rebooting my server (trying to) the /stop process halts indefinitely
         while unloading dimensions...had to force close.
3. The issue seems to replicate entities ad-nauseum (I saw this in another thread)
     a. Noticed that after leaving a dimension, I had close to 37k entities...number grows constantly
         explaining lag over time.
<img width="810" alt="screen shot 2016-03-09 at 1 19 18 pm" src="https://cloud.githubusercontent.com/assets/17745384/13645591/adff135a-e5f9-11e5-9f48-ba97ef582fbc.png">

**Comment by kernelstubbs** [comment]
<img width="821" alt="screen shot 2016-03-09 at 1 27 49 pm" src="https://cloud.githubusercontent.com/assets/17745384/13645926/2f268f84-e5fb-11e5-8680-bd82d5e57f96.png">

**Comment by kernelstubbs** [comment]
Eureka.  This issue appears to be caused by Launch Controllers...once I remove them from a dimension...no problems with leaving.

They're forcing chunks to remain loaded...but screwing up oxygen systems while doing so...

**Comment by radfast** [comment]
> Chunk Loading the dimensions fixes/avoids the issue a. This leads me to believe it's a problem unloading the dimension... b. Upon rebooting my server (trying to) the /stop process halts indefinitely while unloading dimensions...had to force close.

> The issue seems to replicate entities ad-nauseum (I saw this in another thread) a. Noticed that after leaving a dimension, I had close to 37k entities...number grows constantly explaining lag over time. 

> Eureka. This issue appears to be caused by Launch Controllers...once I remove them from a dimension...no problems with leaving. In the meantime, as a fix to get by - using Chicken Chunk Loader + Magnum Torch to keep my bases loaded while I'm away.

These comments are helpful.

My best guess is the issue is caused by chunks loading and unloading over and over, probably because (with the Launch Controller) you have 1 chunk which is being chunkloaded, which has an electricity or oxygen source, and it therefore sometimes loads the neighbouring chunk when it is pumping electricity or oxygen to it.

Can you provide a screenshot (showing chunk boundaries) or a schematic of your Mars setup which was causing the lag.  Or a world file for DIM-29.

Please specify which exact server you are using (vanilla / Spigot / KCauldron / Thermos etc).

**Comment by radfast** [comment]
I'd be grateful if you can also please try out 447 and see if it's made any improvement.  (Remove the Chicken Chunk Loader and go back to the Launch Controller!)

**Comment by dj3520** [comment]
@radfast I don't think you meant 'vanilla' in the way most people would
interpret it, but I know what you mean :)

**Comment by radfast** [comment]
**Update: the issue is caused by the change we made to Galacticraft to add redstone control.  The issue has been present in all versions since 3.0.12.432.

It's not specific to Oxygen Sealers or any other machine.

_Every_ Galacticraft machine checks (through vanilla Minecraft methods) to see whether it is receiving a redstone signal.  The vanilla Minecraft redstone check is causing the unwanted chunk loading, which results in lag.  Currently working on a fix...**

**Comment by radfast** [comment]
[Build 449](http://ci.micdoodle8.com/job/Galacticraft-1.7/449/) fixes the lag, or at least makes a huge improvement from our side.  Other blocks (including vanilla pistons etc) can still cause similar lag.

There is a separate issue here, thanks for highlighting, it looks like **Sealable** blocks are not destroying their tile entities properly.  Therefore leaving this open, for now.

**Comment by kernelstubbs** [comment]
I just installed the latest version [450] and the lag problem is gone.

I configured the Chicken Chunk loaders to fully encompass all cabling, machines and contents (sealed areas) of my bases - but I've removed them and as I mentioned above, the issue is gone.

Here is my base:  (It does keep 1-2 chunks forced at any given time, but the lag is gone)

<img width="1073" alt="screen shot 2016-03-12 at 9 50 37 pm" src="https://cloud.githubusercontent.com/assets/17745384/13726590/2cbc126a-e89d-11e5-998a-aeb5ba3e90f5.png">


As for the sealable blocks - the issue in question was causing a lot of entities to replicate - not just sealable blocks...residual heat was another.

**Comment by kernelstubbs** [comment]
...as for server version, it's Feed the Beast Direwolf20 1.10.0 server files - not something I set up myself...sorry that I can't elaborate more.

**Comment by radfast** [comment]
> I just installed the latest version [450] and the lag problem is gone.

Great news!

>  the issue in question was causing a lot of entities to replicate - not just sealable blocks...residual heat was another.

OK thank you, in that case I will not investigate this further, it seems like it was all linked with the chunkloading / unloading issue.

**Comment by ensirius** [comment]
Today i had same issue on my server with build 1.7.10.502. 

```
[07:47:36 INFO]: Dimension: -29 Loaded Chunks: 21 Active Chunks: 0 Entities: 475483 Tile Entities: 4910790
[07:47:36 INFO]:  Entities Last Tick: 0 Tiles Last Tick: 0 Removed Entities: 475480 Removed Tile Entities: 4910768
```

```[08:05:23 INFO]: Dimension: -29 Loaded Chunks: 8 Active Chunks: 0 Entities: 482386 Tile Entities: 4982130
[08:05:23 INFO]:  Entities Last Tick: 0 Tiles Last Tick: 0 Removed Entities: 482386 Removed Tile Entities: 4982121```

After landing on mars lags gone

**Comment by radfast** [comment]
1. Any clue **which** TileEntities those are?

2. Can you set up conditions to reproduce the problem, or it's a one-time only thing?

3. If you can reproduce it, please if possible test with a much smaller modlist - maybe only Galacticraft and NEI - to see if the issue still occurs.  If you have a large modlist it could be any mod causing this.

4.  If it happens at one specific base / chunk position only, please provide screenshots of what's there.  

Please especially think about:
a.  chunk loaders from Galacticraft (Launch Controllers) and from other mods
b.  wire or pipe connections running across chunk boundaries - especially wires/pipes/conduits from other pipes
c. any thing else which is complex / inter-dimensional (for example, teleporters)
