### ISSUE TITLE
[Recommendation] Reversed Rocket Tier Usage

### ISSUE THREAD

**Issue by Yanniclord** [micdoodle8/Galacticraft#2135]
The "issue" is quite simple and straight forward. It would be nice that in the next version, some kind of indicator would be added to planets (like NBT or such) that let a Rocket indicate if it can go there or not. The reason for why i am asking, is it seems that you need a T3 rocket to fly to a T3 planet, but you can use ANY kind of rocket (T1) to fly across the whole solar system, which if you ask me is plain stupid.

I tried this from Vega B (GalaxySpace planet), which requires a T8 rocket to get to, but i could "travel" the exact same distance back with a T1 rocket, which either does not make sense, or that was a VERY powerful T1 rocket :P. Anyways, some kind of indicator for dimensions/planets would be nice, so that you need the same rocket tier to travel back or to another planet. For the other planets, it would be somewhat better if it worked like this: lets say i'm on a T3 planet, and want to travel to a T5 planet. Now, i would only need a T3 rocket for that, instead of a T5 rocket, as the distance (even if different) is the same for any T* rocket, for example if you can travel to Mars with a T2 rocket and then travel with a T1 rocket to the Asteroids, it would be the same as if you traveled to the Asteroids directly with a T3 rocket.

**Comment by dj3520** [comment]
Suggestions are to be posted on the forums.

**Comment by Yanniclord** [comment]
Sorry, will do.

**Comment by Creeperman8362** [comment]
but then someone could use a T1 rocket to hop from planet to planet, eventually to T8 planets

**Comment by C1ffisme** [comment]
While this is here, it does sound like a good idea to make Tier 1 Rockets only be able to jump one planet backwards, while it still takes a Tier 3 Rocket to get to the Asteroids/Wherever.

(In other words, a Tier 1 rocket can get you from the Asteroids to Mars, but you still need a Tier 3 rocket to get to the Asteroids at all in the first place.)

**Comment by EzerArch** [comment]
Just posted my idea: http://forum.micdoodle8.com/index.php?threads/reversed-rocket-tier-usage.6425/#post-41021

Please use the forum.
