### ISSUE TITLE
Add MicDoodleCore as git submodule

### ISSUE THREAD

**Issue by Teteros** [micdoodle8/Galacticraft#2136]
To successfully compile GC I had to include both the [API](https://github.com/micdoodle8/Galacticraft-API) and [MicDoodleCore](https://github.com/micdoodle8/MicdoodleCore) as per [wiki guidelines](http://wiki.micdoodle8.com/wiki/GC3_API#Full_Galacticraft_Sources) like so:
https://github.com/GTNewHorizons/Galacticraft/commit/1897b977beff960101348307ec7cef5c524a348f#diff-c197962302397baf3a4cc36463dce5eaR28.

May I suggest adding MicdoodleCore to the repository (if not already added) as a git submodule just like the API is? I think it would serve as a good reminder for that coremod since it's a dependency after all.

**Comment by radfast** [comment]
It's not necessary.  Not too many people want to compile GC, and anyone who does should be able to figure it out.  As per wiki guidelines.  It's also extra work for us to re-arrange it.  And the API submodule is already a pita.
