### ISSUE TITLE
A fatal error has occurred

### ISSUE THREAD

**Issue by valentinp72** [micdoodle8/Galacticraft#2138]
Hello,
Maybe related to [this one](https://github.com/micdoodle8/Galacticraft/issues/2125) (because I use bubble distributor, and I don't have yet modified the mod to apply the correction said in this post), I explain here in details what happen with my singleplayer space station.

Sometimes, the client crashes and I get this message in the logs : http://pastebin.com/xmL9qATv (the location of the block always change when crashing).

Sometimes, I get kicked from the world, the message is "_A fatal error has occurred, this connection is terminated_", and when I click on the button "_Back to title screen_", I'm on the multiplayer screen (I play in single player). The message in the log is : http://pastebin.com/t3dpERuF

Edit : When that happen, I'm often in the circle of my space station, with many oxygen bubble distributors. I also observed that before I'm kicked of the world, the oxygen bubble doesn't work (detectors no longer detect oxygen, and I take damage because it says that my oxygen setup is invalid). http://vlntn.pw/f/u/Hqlyx.png

Edit(2) : My world seems to by very buggy ... Every time I quit the space station on a spaceship to earth, my client crashes, because of a null pointer ... http://pastebin.com/92cRxvX8

I just wanted to say that I love this mod, and all the people working on it, this mod is incredible ! :+1: 

Thanks in advance,
Valentin

**Comment by Yanniclord** [comment]
Most of the issues i am having, and you to apparently have been occurring since build 446. However, the lag in builds previous to 446 was unbearable, but i really can't say whats worse. Constantly crashing, or being unable to play due to the lag caused from the Oxygen System previous to 446.

**Comment by radfast** [comment]
>  the mod itself should fix it

@Yanniclord If you're having an issue in some Forge versions and not others, that is likely a Forge bug not a mod bug.  In any case, your post is not about Valentin's issue so it does not belong on this thread.  Your theory that many GC issues have been occurring since build 446 is unlikely to be correct, the changes in build 446 are incremental and minor.  I will happily look at any specific issues where you can either post a crash report or give me steps to reproduce it, but general "it's got worse" statements are not helpful.

**Comment by radfast** [comment]
This should be fixed in build 447.  Please re-open if there are any more issues.

> Edit(2) : My world seems to by very buggy ... Every time I quit the space station on a spaceship to earth, my client crashes, because of a null pointer ... http://pastebin.com/92cRxvX8

I have not investigated this yet.  This may be fixed as a result of fixing the Oxygen Distributor issue.  If not, then please comment and we can re-open this thread.

**Comment by valentinp72** [comment]
Hello,

Thanks for the help!
I installed the build 447, and now, every time I load my world, the client crashes : http://pastebin.com/QaZTehma

**Comment by radfast** [comment]
Please try out [build 448](http://ci.micdoodle8.com/job/Galacticraft-1.7/448/)

**Comment by valentinp72** [comment]
With this build, I also crash : http://pastebin.com/jLgJKXhZ

**Comment by radfast** [comment]
Sorry about this!  I think you have more Oxygen Distributors than everyone else ...   Looking for a fix now.

**Comment by valentinp72** [comment]
Ok, thanks!
I'm using bubble distributors because oxygen distributors make my world "slow" when updating blocks (breaking a block, or opening an air lock).

**Comment by radfast** [comment]
Please try [build 450](http://ci.micdoodle8.com/job/Galacticraft-1.7/450/)

**Comment by valentinp72** [comment]
This is ... perfect! My world doesn't crash anymore! 
Thanks a lot! 😀

Valentin

**Comment by radfast** [comment]
Thanks for the confirmation.
We really appreciate you reporting the issues.
You probably have 10+ Oxygen Bubble Distributors, when in my test worlds I only make 1 or 2.

I will be working on reducing Oxygen Sealer lag some more in future versions, so keep an eye on the changelog and maybe one day you can use those.  They work best in smaller rooms (low ceiling height).  If you have big rooms 20 x 20 x 10 then Oxygen Sealers are always going to be a bit laggy.
