### ISSUE TITLE
Disabling Race Manager Window

### ISSUE THREAD

**Issue by ExDomino** [micdoodle8/Galacticraft#2139]
On our server we need to disable the race manager window from poping up when a new players join the server. We're searched in the config and we have not found any option to disable it. How to disable this window please? It's urgent!

**Comment by EzerArch** [comment]
According to @radfast:

> There is no way to hide it.
(from: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287888-galacticraft-3-0-12-6-400-000-downloads?comment=2812)

And:
> I agree it's somewhat annoying for the GUI to come up at first logon
(from: 
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287888-galacticraft-3-0-12-6-400-000-downloads?comment=2815)

My guess it is planned to be changed.

**Comment by dj3520** [comment]
I feel like purpose built adventure maps would also loose a bit of the
immersion. Realistically the menu only serves as a flag design and team
management interface. Also having it pop up once placed into a new world
isn't always the best for multiplayer servers, when your first visit could
be at night. Perhaps a chat message when making the flag pointing out it
will be blank until customized. Maybe even clicking on the flag opens it.

Wait, this is a suggestion. Doh! Anyway, suggestions belong on the forum,
not here.

**Comment by DraksterAU** [comment]
I'd consider something spamming users a bug... not a suggestion, but hey.

**Comment by dj3520** [comment]
It's behavior is as intended if it only shows up by itself the first time
you enter a world. I don't consider once "spam."

**Comment by DraksterAU** [comment]
@dj3520 Cauldron servers sometimes have 50+ worlds...?

**Comment by dj3520** [comment]
Wait, does this come up every time with Multiworld/Multiverse as well?

**Comment by DraksterAU** [comment]
Nope just on login. I'm really not supposed to be behind a keyboard today.... Sorry mate.

**Comment by dj3520** [comment]
I'm having a bit of trouble understanding what you're seeing. For each Multiverse world does this show up again?

**Comment by micdoodle8** [comment]
I've had a bit of a change of heart here. I don't know why I thought it necessary to force the Space Race Manager upon people right when they start a world, and upon each subsequent login until they use it, but I've changed it. The popup feature is now disabled by default.

**Comment by dj3520** [comment]
Perhaps to make a team and a flag design, which is still important. Might I bring up a suggestion I made earlier:
>Perhaps a chat message when making the flag pointing out it
will be blank until customized. Maybe even clicking on the flag opens it.
