### ISSUE TITLE
Do not teleport to the planet if a non-English language

### ISSUE THREAD

**Issue by vSkyD1** [micdoodle8/Galacticraft#2141]
If the client's language is not English, it says when you try to teleport to the planet:
http://pastebin.com/nmWEzZLn

Version: 446
Core: Thermos-1.7.10-1614-46

**Comment by radfast** [comment]
Thank you for reporting.  We will fix this as a priority.  There will then be a version update to 4.0.13 which players and servers must both update to.

**Comment by radfast** [comment]
This will be fixed in next build.  For now you can maybe ask the **client** to roll back to Galacticraft [build 445](http://ci.micdoodle8.com/job/Galacticraft-1.7/445/), that should work OK even if the server is on 446-450.

**Comment by vSkyD1** [comment]
@radfast 

On the planet is now teleport. But when creating a station, it writes:
http://pastebin.com/LrefEJ3Q

Build 451

**Comment by radfast** [comment]
Thank you, fixed in build 452.
