### ISSUE TITLE
[Server Startup Crash] Galacticraft 450 - java.lang.NullPointerException: Exception in server tick loop

### ISSUE THREAD

**Issue by Yanniclord** [micdoodle8/Galacticraft#2142]
Ok, so now the server crashes instantly once someone joins the server, who is on a Space Station or alike (actually, dimension does not seem to matter, i had people from different worlds log in, the server crashed anyway). http://pastebin.com/rviVSkP6

Galacticraft build 450.

**Comment by Yanniclord** [comment]
Second log, not that it should be any different: http://pastebin.com/iq1UYPrq

**Comment by radfast** [comment]
This is the same as #2130.

Now you must roll back to the **previous** version of GalaxySpace, the one which caused the crash in #2130.

**Comment by Yanniclord** [comment]
Wait so this will probably be fixed by BlesseNTumble then soon i guess?

**Comment by Yanniclord** [comment]
@radfast You fixed it! The latest Galacticraft 451 fixed the crash issue! Thank you :)

**Comment by Yanniclord** [comment]
Ok so you fixed the crash, but this is a real problem right there. What the heck causes this?:
Check the TPS of Space Station 3, look at it real close.
![2016-03-13_18 10 55](https://cloud.githubusercontent.com/assets/5807595/13730127/2b2a51c8-e947-11e5-9f81-9c98f4310bfa.png)

**Comment by dj3520** [comment]
What does that almost GB represent? World size? Memory use? Not all of 
us are familiar with what plugins/mods you're using.

**Comment by Yanniclord** [comment]
I did actually mention them in many earlier posts, and you can also check out the crashlog, everything is defined there. Also the lag went the second i nuked all entities, and the entities were from some Galacticraft, most likely all blocks it checked. The only problem now, is that i can not teleport to the other Space Station.

**Comment by dj3520** [comment]
If you're using anything bukkit to teleport (such as Essentials) then it 
cannot be into a sealed room. bukkit reports "sealed air blocks" as 
solid to plugins, making them think you want to teleport into a wall.

**Comment by Yanniclord** [comment]
I know that, i set my home outside on a platform.

**Comment by dj3520** [comment]
Is the destination chunk loaded?

**Comment by Yanniclord** [comment]
Yes, but that fixed it at first. It seems the lag came because of that, something that was changed in 450 or 451. Anyways, it does currently not matter, only problem i have is with an existing Mars Space Station.

**Comment by radfast** [comment]
> bukkit reports "sealed air blocks" as solid to plugins

**Comment by dj3520** [comment]
Well this is why you make mods and I just report bugs :smile: Wasn't even aware that bukkit essentials could do a isAir test. From my understanding bukkit wouldn't need a isAir ability since it doesn't have the ability to add blocks.
