### ISSUE TITLE
Spin thruster not responding to redstone

### ISSUE THREAD

**Issue by dj3520** [micdoodle8/Galacticraft#2143]
![image](https://cloud.githubusercontent.com/assets/8284194/13726811/1046c856-e8a6-11e5-894d-bf22ae8aee0d.png)
My world still goes 'round. GC 450 with [all of this too](http://net.dj3520.net:8000/minecraft/modlist.btm)

I believe my friend got this to work momentarily by forcing a block update, but I've yet to make the spinning stop.

Huh minecraft screenshot somehow captured my MSI Afterburner overlay as well...

**Comment by Yanniclord** [comment]
I might be wrong, but you might remember this: http://ci.micdoodle8.com/job/Galacticraft-1.7/449/

**Comment by dj3520** [comment]
Not seeing it being disabled in the commit.

**Comment by EzerArch** [comment]
I can't get it working either. But was redstone signal ever enabled for them?

**Comment by dj3520** [comment]
According to f756eb9d821edc9d26eae718f4c43234e2aef38a yes, which was very exciting for me. I enjoy control and Galacticraft really didn't have that option.

**Comment by EzerArch** [comment]
Just checked the commit, [```BlockSpinThruster.java```](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/blocks/BlockSpinThruster.java) is not listed in Changed files. Guessing wrong?

**Comment by dj3520** [comment]
* Not guessing (look at the commit's name)
* Found BlockSpinThruster mentioned in WorldProviderOrbit.java line1205

**Comment by EzerArch** [comment]
> Not guessing (look at the commit's name)

That's why I should use subject/pronouns more, I wanted to mean "Am I guessing wrong?". >_<

**Comment by radfast** [comment]
The redstone check for Spin Thrusters was included in commit  f756eb9.

The problem here was that a BUD was not causing a re-evaluation of the space station spin.

**Comment by dj3520** [comment]
>That's why I should use subject/pronouns more

Funny enough I also interpreted it like that as well but due to the wording I figured "Are you" was more likely of the two.
