### ISSUE TITLE
Issues with SmartMoving and Tails

### ISSUE THREAD

**Issue by ExDomino** [micdoodle8/Galacticraft#2144]
Hello, your mod has problems with two others mods: SmartMoving and Tails. Can you make your mod compatible with them please? I contact you because you're still in 1.7.10, these other mods are updated in 1.8.x and refuses to make changes for 1.7.10. For now I'm using RenderAPI that solves the problem with Tails but there is still a problem with SmartMoving. Thank you in advance, because you're my last hope.

**Comment by C1ffisme** [comment]
Some links might be helpful...

It would also be helpful if you posted more information (Crash Logs, What you were doing, System Specs, etc.).

**Comment by dj3520** [comment]
I'm guessing there is some graphical issues with the player model with
Tails. If so please post screenshots. We should already be compatible with
SmartMoving.

**Comment by radfast** [comment]
Our mod is 100%, totally, compatible with SmartMoving.
Make sure you are using latest version of Galacticraft.

(If this is a disguised attempt to ask about 1.8 version of Galacticraft then you are asking for a ban.)

**Comment by dj3520** [comment]
Think it's not due to how things are worded.
> ... _these other mods_ are updated in 1.8.x and refuses to make changes for 1.7.10.

**Comment by ExDomino** [comment]
Ok, so the problem with SmartMoving is when I add RenderAPI, to allow Tails to work. The problem with Tails it that models (a tail, ears, etc) are not shown.

(PS: We're playing 1.7.10 and I will not ask you to upgrade your mod to 1.8 when I ask to modders to backport their new versions of their mod for the 1.7.10, for now I'm playing the 1.7.10 version of minecraft, not the 1.8, for exemple OpenComputers and SGCraft. Personaly I hate people who ask for an upgrade to a new version of minecraft, leaving the previous version without support.)

**Comment by dj3520** [comment]
Does Tails work with SmartMoving without Galacticraft? Are you using any
other mods that might effect rendering, such as Optifine?

**Comment by ExDomino** [comment]
Yes it worked perfectly well before I installed Galacticraft. Also, I noticed that when I installed Galacticraft, I ceassed to see myself to crawl or to swim, I mean the animation. And yes we're using Optifine because without it's unplayable, too many lags despite we have good computers.

**Comment by radfast** [comment]
> Make sure you are using latest version of Galacticraft.

Please provide a copy of your ```fml-client-latest.log```

**Comment by radfast** [comment]
@ExDomino  please provide the log as requested, there's nothing I can do to help you without it

**Comment by EzerArch** [comment]
I will install Tails with SM. BRB.

**Comment by EzerArch** [comment]
I don't like double-posts but it's an important update.

![tails](https://cloud.githubusercontent.com/assets/6743303/13902112/2bfe9a64-ee1a-11e5-9714-50026da2c48d.gif)

**Relevant mods:**
1.7.10/FoxLib-1.7.10-0.7.0.jar
Tails-1.7.10-1.4.1a.jar
PlayerAPI-1.7.10-1.4.jar
RenderPlayerAPI-1.7.10-1.4.jar
SmartMoving-1.7.10-15.6.jar
SmartRender-1.7.10-2.1.jar
OptiFine_1.7.10_HD_U_D1.jar
Galacticraft, full install, 454

Tails mod is not strange for me. I've played with it around lots of times with Galacticraft and MorePlayerModels , except MorePlayerModels does not support Smart Moving and does not render GC oxygen gears.

![2015-08-26_01 03 25](https://cloud.githubusercontent.com/assets/6743303/13902138/62d5d83a-ee1b-11e5-918c-e04580c3d972.png)

**Comment by radfast** [comment]
I think the OP is probably not using the latest Galacticraft.  Which is why I have asked him, twice, to post his log.
