### ISSUE TITLE
Arc lamps cause dark spots

### ISSUE THREAD

**Issue by GameOverGaming** [micdoodle8/Galacticraft#2149]
when i place an Arc Lamp, rather than creating light around it, it rather darkens the area around it, and this area is surrounded by light. (I think its the  way the False-air-Light Blocks that normally make this are bugged.)
![2016-03-16_15 14 17](https://cloud.githubusercontent.com/assets/12983326/13825755/7be1595a-eb8a-11e5-8a36-3fca1bb529cb.png)
EDIT1: This also happens without other mods installed,

**Comment by dj3520** [comment]
Define "other mods installed." Also include any client-side mods installed, such as OptiFine.

**Comment by radfast** [comment]
Where is the Arc Lamp in that image?  I don't see it.

**Comment by GameOverGaming** [comment]
There are 2 behind where that wall sticks out. as for the mods,
![modlist](https://cloud.githubusercontent.com/assets/12983326/13896736/cbe66424-ed6d-11e5-8d34-26ad04f976f8.png)

ThermalFoundation is in that list also.

**Comment by radfast** [comment]
A few more questions please:

1.  Is this a time of day issue - like it only looks like that in the evening?

2.  What do you see if you place a Glowstone block behind that wall where the Arc Lamp is currently?

3.  In recent Galacticraft versions, you should be able to switch an Arc Lamp on and off using a redstone signal, does that make any difference?

I don't really see how this is happening.  The Arc Lamp works approximately as if the air blocks near it are filled with invisible Glowstone blocks.

**In any event** you really should update to the latest Galacticraft, see #2151 for some links which people have kindly given.

**Comment by radfast** [comment]
Any response to my questions posted on 19 March?

**Comment by radfast** [comment]
Closing due to no response in ~ 1 year

It's unlikely this is an Arc Lamp bug, the Arc Lamp can only add light, not remove it.

Possibly there's a weird interaction with the other mods.  I think it was more likely some bug in the vanilla lighting engine, there are a few bugs in the way it updates.

If this is a **reproducable problem** in the latest Galacticraft 1.7.10 version (or in Galacticraft 4 beta), please comment or re-open.
