### ISSUE TITLE
Galacticraft site not working

### ISSUE THREAD

**Issue by jeg623** [micdoodle8/Galacticraft#2151]
I went to download galacticraft and it said above that the website was not working and only got a snapshot. On top of that I couldn't download any of the mods.

**Comment by dj3520** [comment]
Yup whole domain is down (Jenkins/Forums/Main site)

If needed I can host revision 450 until the site comes back up, though @radfast might post a link himself, which of course would be the newest version (I can't host anything newer because I haven't upgraded yet lol)

**Comment by MJRLegends** [comment]
Good job i downloaded the newest version yesterday for my mod pack update :P

**Comment by jeg623** [comment]
Maybe for now you could jut put them in Dropbox or Google Drive folders or something?

**Comment by dj3520** [comment]
http://net.dj3520.net:8000/servitup/GC-tmp/ has 450 for now (I'll probably bring this down once the site works again or radfast puts a link.) If I could get a hold of a newer version I can update the files.

**Comment by MJRLegends** [comment]
Here is build v454 which i believe is the latest version: https://drive.google.com/folderview?id=0B0DAun6LjFwTOUxsRUpDdjFIZTQ&usp=sharing

I will also remove when the site works again or radfast puts a link

**Comment by dj3520** [comment]
@MJRLegends I have updated my site with your files.

**Comment by MJRLegends** [comment]
Your welcome i downloaded them last night so they must be the latest version

**Comment by dj3520** [comment]
I'm writing a nicer index page for my site right now.

**Comment by jeg623** [comment]
thx. I'm sure the work for a new site will pay off. :)

**Comment by dj3520** [comment]
Eh it's just something temporary and already done. Just have to wait for
the real site to come back up.

**Comment by EzerArch** [comment]
My Galacticraft backup page is up with the version 454: http://www.ezerarch.com/downloads *(use this if http://micdoodle8.com download page isn't working)*

**Comment by dj3520** [comment]
_Nicer download page and approved by dev. RIP my temp page._ I'll keep it up anyway for now.

**Comment by Dream-Master** [comment]
When the site will be online again ?

**Comment by dj3520** [comment]
Depends on what's wrong really. Most of the time it's pretty impossible to predict time with these kinds of things since it's quite complex.

**Comment by katzenpapst** [comment]
So... any updates?

**Comment by Creeperman8362** [comment]
Yeah, I want to know the status of the website.

**Comment by viktor40** [comment]
no still offline ... If you want to know if the server is offline or it is just you, use this link http://www.isitdownrightnow.com/micdoodle8.com.html

**Comment by EzerArch** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287888-galacticraft-3-0-12-6-400-000-downloads?page=142

**Comment by Creeperman8362** [comment]
From mcdoodle8 himself:  Mitch Petrie ‏@micdoodle8 Apr 1

Apologies for the website downtime, should hopefully be resolved within a few days. Backup downloads can be found at http://goo.gl/Fq7gox 
1 retweet 3 likes


PROGRESS AT LAST

**Comment by dj3520** [comment]
Website just came back up.

**Comment by BlesseNtumble** [comment]
Forum not worked)

**Comment by katzenpapst** [comment]
Yeah, the forum returns HTTP/1.0 500 Internal Server Error with an empty page.

**Comment by dj3520** [comment]
500 would mean the forums are broken on the server. Basically "I tried to
make a page and then things went wrong."

**Comment by RonFall** [comment]
Please correct the error while registering. I can not register.
![dfg45](https://cloud.githubusercontent.com/assets/18558783/14697735/72e878d0-078f-11e6-85a7-c7de1e31ee66.png)
