### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by Andrey228322** [micdoodle8/Galacticraft#2155]
1)Head to the left - when the rocket is taken from MineCraft skins system, how to change on your own?
2)When you make a realistic earth? - Round (When the moon).
3)Plugin to save items - Scavenger, does not save things (Oxygen equipment)

**Comment by radfast** [comment]
> 1)Head to the left - when the rocket is taken from MineCraft skins system, how to change on your own?

I do not understand your question, at all.  Please provide a screenshot.

> 2)When you make a realistic earth? - Round (When the moon).

This is not a valid issue report.  You can make suggestions on the forum only.

> 3)Plugin to save items - Scavenger, does not save things (Oxygen equipment)

Please raise this issue with the author of **Scavenger** plugin.  Please give him [this link](https://github.com/micdoodle8/Galacticraft-API/blob/master/src/main/java/micdoodle8/mods/galacticraft/api/inventory/IInventoryGC.java).

**Comment by Andrey228322** [comment]
1)http://i.imgur.com/uXz22sp.png

**Comment by radfast** [comment]
I understand, thank you.

The player head shown in the rocket HUD cannot be changed.

**Comment by Andrey228322** [comment]
You can add settings to change?

**Comment by radfast** [comment]
No.  We will not add settings to change something which 1 person does not like.

If you have ideas for improving the mod, you can make suggestions on the suggestions forum.  (Not today, the forum is offline.)  There we can see if it is an idea supported by many players.

**Comment by Andrey228322** [comment]
This feature, for projects that use personal skins system!
Very useful!

**Comment by Andrey228322** [comment]
Forum not working!

**Comment by radfast** [comment]
See what I wrote:

>  (Not today, the forum is offline.)
