### ISSUE TITLE
[GC & Smart Moving] Can't fit in 1x1 spaces after a while of playing

### ISSUE THREAD

**Issue by Fernando540** [micdoodle8/Galacticraft#2158]
I can crawl into 1x1 spaces for a little while, but then something happens and I cannot do it anymore. When I exit and reconnect I can do it again for a moment but the the error still coming after a while.

Mods I have installed:
-GC (Core, Planets & MicdoodleCore) 1.7-3.0.12.454
-PowerSuits 0.11.0.300 & Numina 0.4.0.131
-OF HD UD1
-Player API 1.7.10-1.4
-Render Player API 1.7.10-1.4
-SmartMoving 15.6 & SmartRender 2.1

**Comment by EzerArch** [comment]
Geez, I had plans to open an issue listing the remaining incompatibilities between GC and SM. This is one of them.

This bug breaks one of the SM's main features: crawling through 1-block tall passages.

But I had made some tests already, version by version, from 411 to 440, **the bug appears in 439**.

**Reproducing:**
*Glitch 1 - 1-block tall hole:*
1. Build a wall and open a 1-block tall passage.
2. Shift+Control to crawl, and try to crawl through the hole.
3. You can't. The game thinks the player still has a 2-block tall hitbox while crawling. It was expected to be able to crawl through the hole but you'll stop at the opening.

![2016-03-21_00 37 05](https://cloud.githubusercontent.com/assets/6743303/13910212/2dead886-eefd-11e5-81f8-0e475f5588d0.png)

*Glitch 2 - 2-block tall room:*
1. Build a 2-block tall room.
2. Go beneath the ceiling.
3. Press Shift+Control to crawl.
4. Release Shift+Control.
5. You are stuck in the crawling position even if there is enough room to stand up. The game thinks the player's head is already touching the ceiling.

![2016-03-21_00 49 16](https://cloud.githubusercontent.com/assets/6743303/13910324/1ad71faa-eeff-11e5-8751-1de629e901b6.png)

*Glitch 3 - 2-block tall room:*

**Comment by dj3520** [comment]
What does F3 + B look like when crawling?

**Comment by Fernando540** [comment]
With GC installed:
![2016-03-20_23 52 23](https://cloud.githubusercontent.com/assets/15991514/13911477/d1650d08-eef6-11e5-89c0-3bd956a16bca.png)

Without GC:
![2016-03-20_23 57 47](https://cloud.githubusercontent.com/assets/15991514/13911558/b7bbfb72-eef7-11e5-98ba-4d43c4994049.png)

**Comment by EzerArch** [comment]
> What does F3 + B look like when crawling?

I don't trust the hitbox highlighter much, but it would be cool a comparison between SM + GC  438 and SM + GC  454 for a definitive test.

(Thanks @Fernando540 :+1: )

**Comment by dj3520** [comment]
Is the Jenkins back up? I haven't checked today.

**Comment by EzerArch** [comment]
> Is the Jenkins back up?

Nope. But I have the files: http://ezerarch.com/downloads

**Comment by Creeperman8362** [comment]
Not a galacticraft issue

**Comment by dj3520** [comment]
@Creeperman8362 um yes I think it is
>But I had made some tests already, version by version, from 411 to 440, the bug appears in 439.

**Comment by radfast** [comment]
Thank you @EzerArch  for this thorough testing.

I will look at this, but can't do much at the moment while the Jenkins is down.  I don't have any magic way of accessing the Jenkins that you guys don't, it's in the cloud for me too.  :)  The server guys are working on it.

**Comment by dj3520** [comment]
@EzerArch Do you need access to some older builds for testing? My backup system recently got a fix as to not keep old files inside of new backups, but I forgot they were all dumped somewhere else for long term storage. TD;DR is 
![image](https://cloud.githubusercontent.com/assets/8284194/13974431/035e819a-f082-11e5-9634-cf2692d9e8a8.png)
And yes, only those versions listed, but with a matching MicDoodleCore as well.

**Comment by radfast** [comment]
I need the changelog from the Jenkins to see what commits belong with version 439.  If anyone has a saved copy of the changelog text ...

(Note to self: make local copies of that kind of stuff, in case the Jenkins goes offline again...)

**Comment by dj3520** [comment]
>I need the changelog from the Jenkins
Figured it would of been that. Darn it.

**Comment by Creeperman8362** [comment]
http://ci.micdoodle8.com/job/Galacticraft-1.7/changes

changelog

**Comment by dj3520** [comment]
@Creeperman8362 No offence but did you even check that link before posting? Specifically for #2151

**Comment by Zemor** [comment]
Any news on this issue?

**Comment by dj3520** [comment]
GC460 no SM
![image](https://cloud.githubusercontent.com/assets/8284194/16206776/e6718e30-36f7-11e6-994d-5e4d2a86839e.png)

Witchery has lycanthropy, and when in dog form walking through 1 high spaces should be a thing, but it's not so.
![image](https://cloud.githubusercontent.com/assets/8284194/16206832/3cbec87a-36f8-11e6-919a-e65359b571b0.png)

_I should make a new skin_

**Comment by Zethalion** [comment]
I can confirm this is still an issue. Using:
- GalacticraftCore-1.7-3.0.12.463
- MicdoodleCore-1.7-3.0.12.463
- SmartMoving-1.7.10-15.6
- PlayerAPI-1.7.10-1.4
- SmartRender-1.7.10-2.1

Took me 2 whole days to find this weird behavior is due this incompatibility. 

I only can ask help me out. I'd like to have GC inlcuded on my server. SM is just more important,

**Comment by dj3520** [comment]
Seeing as how this happens without SmartMoving at all (my testing with Witchery above) then I'm led to believe it's a Galacticraft problem.

**Comment by EzerArch** [comment]
> But I had made some tests already, version by version, from 411 to 440, **the bug appears in 439**. https://github.com/micdoodle8/Galacticraft/issues/2158#issuecomment-199101413

**Comment by dj3520** [comment]
@EzerArch does this mean that it isn't present in 438?

**Comment by EzerArch** [comment]
@dj3520 Nope. As I said, I tested version by version, from 411 to 440.

**Comment by dj3520** [comment]
@EzerArch ah, then perhaps it's 2eb466e7d7b7379f91190fef2adb45efd78527b1 Line 37 looks suspicious, but I have no experience in Java.

**Comment by masterfulmadman** [comment]
I understand that there is no easy solution, but is there a solution? I also encountered this issue and would like to know if it is possible to keep both galacticraft and smartmoving without losing functionality in a future update.

**Comment by EzerArch** [comment]
> but is there a solution?

Besides someone who knows Java picking up the offending build (i.e. 439) and fixing the bug, no. And micdoodle can't afford fixing non-critical bugs as he's focused on porting the mod in his limited spare time.

> @EzerArch ah, then perhaps it's 2eb466e Line 37 looks suspicious, but I have no experience in Java.

You mean [this line](https://github.com/micdoodle8/Galacticraft/blob/2eb466e7d7b7379f91190fef2adb45efd78527b1/src/main/java/micdoodle8/mods/galacticraft/core/entities/player/FreefallHandler.java#L37)? Yeah, pretty likely, but I have little modding literacy to be certain. If I had the environment on the go, I could try reverting the lines 34-39 just for a _Deus Ex Machina_ moment.

**Comment by dj3520** [comment]
Skimming through #1833 made me realize 375616a also changes binding boxes and is included in versions +441

Something interesting to note as well is [the amount of downward force when sneaking is greater with hard mode on](https://github.com/micdoodle8/Galacticraft/blob/375616aa8ef6bc314ce69e605b7319bf0c632bc1/src/main/java/micdoodle8/mods/galacticraft/core/entities/player/FreefallHandler.java#L121)

If I had to guess it might have to do something with this:
>The player appears to have a quick involuntary "bounce" down and up when starting downward movement in freefall, this is the result of the 'Sneak' mechanics in the vanilla game and is something we are working very hard to eliminate

This tells me that something was done to the sneak at the start of it. What confuses me completely though is that in my testing, restarting the server means every block I tested was fixed, even if I removed and replaced it. I'm guessing something at the start makes everything in the world correct when first loaded, but then as things change this check or whatever isn't triggered again, meaning ceilings that are newly added since the server started have issues, but ones that are old are fine, even if the blocks are changed.

**Comment by BionicFelps** [comment]
This is currently driving me crazy in a pack I'm playing (and made), bat form loses the ability to hit mobs, and has shorter reach for the payoff of being 1x1 block, is there any temporary workaround besides disabling galacticraft or ignoring it? lol

**Comment by dj3520** [comment]
At the moment, sadly, no.

**Comment by Kerai** [comment]
It took me about 10 seconds to find the source of this problem...

[PlayerClient.java#L176,L182](https://github.com/micdoodle8/Galacticraft/blob/MC1.7/src/main/java/micdoodle8/mods/galacticraft/core/entities/player/PlayerClient.java#L176,L182)

Seems Galacticraft is changing height of a player and moving the top of boundingbox accordingly. Obviously this will cause compatibility problems with any mod that also changes player height.

Sure, commenting out these lines obviously fixes the issue. I don't think they are that necessary anyway as they are just for looks.

[Here's a compiled jar with these lines commented out](https://cdn.keray.eu/mc/1.7.10/mods/GalacticraftCore-1.7-3.0.12.0.jar) - for those who don't want to build the whole project just for this small change.

**Comment by EzerArch** [comment]
> Here's a compiled jar with these lines commented out - for those who don't want to build the whole project just for this small change.

Thank you @Kerai. Is this change against GC464?

Seriously this will not break anything else in GC? If will not, could you PR the change? I'll contact mic to see it; this is pretty much requested.

**Comment by Kerai** [comment]
I changed against latest code from 1.7 branch. So, newer than 464. This shouldn't break anything else in GC.

As for PR - yeah, I might make a proper change later. (check if mods like SmartMoving are installed, and if not, only then change player height) Right now it's just a quick and dirty fix.

**Comment by dj3520** [comment]
Ah, the player is made slightly taller if wearing an oxygen mask.

**Comment by EzerArch** [comment]
Glitch 1 - 1-block tall hole: fixed.
Glitch 2 - 2-block tall room: fixed
Glitch 3 - Flying and space station: fixed
Extra - Player doesn't drown while swimming: fixed
Thank you sir. :)

**Comment by EzerArch** [comment]
**Update**

**_Bonus fix:_** Cryogenic Chamber is back working again!

(I don't like double-posting, but this is really a new/significant info.)

**Comment by dj3520** [comment]
Gotta love it when a pull request fixes things. The players care!

**Comment by micdoodle8** [comment]
Thanks for the fix @Kerai, don't have a 1.7.10 workspace at the moment so it's much appreciated. Please re-open if there are remaining issues.

**Comment by EzerArch** [comment]
@Kerai, just a question: did you create a 1.7.10 workspace with no problems? Did it compile normally?

I'm just wondering if some other people might have had problems with compiling for 1.7.10 (e.g. #2390).

**Comment by Brayan2005** [comment]
There is so much to read that i didn't understood. So my problem is glitch 1 so what schould i do. (Is galacticraft the problem?)

**Comment by Brayan2005** [comment]
Is there realy no other solution as removing Galacticraft?

**Comment by dj3520** [comment]
@Brayan2005 If you're using the newest versions of both mods and the issue exists, it would probably be best to make a new issue report. With that being said I'm pretty sure development has moved on to newer versions.
