### ISSUE TITLE
Alien Villagers replacing overworld villagers.

### ISSUE THREAD

**Issue by TripOptic** [micdoodle8/Galacticraft#2160]
Every default minecraft villager is an alien villager. Spawning a default villager soon turns into an alien counterpart. Modded villagers are affected except for Agricraft villagers(in my modpack)

**Comment by dj3520** [comment]
Could you post a list of mods in your modpack?

**Comment by C1ffisme** [comment]
You also might want to see [this](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md). If you report any other bugs, this is the place to go to before posting. Otherwise, **We cannot help you.**

**Comment by TripOptic** [comment]
@C1ffisme I read through the closed issues and saw nothing of simmilarity. Also C1iffiisme the Micdoodle8 website has been down for a few days and I would go and ask questions there instead of coming to github. @dj3520 Here is the Imgur album of my mods. http://imgur.com/a/Vclcr

**Comment by C1ffisme** [comment]
@TripOptic Okay, but just make sure that any future issues comply.

(Sorry if I was rude, the post was a bit vague.)

**Comment by TripOptic** [comment]
@C1ffisme  It was my bad, I really didnt know how to explain the issue.

**Comment by radfast** [comment]
Please do not reply to questions which do not come from me.

@TripOptic:

1.  Are you playing on a server or SSP?

2.  What does PeacefulSurface do?  I don't know that mod.

3.  Do you have any other mods which affect mob spawning?

4.  Please post your complete ```fml-client-latest.log``` somewhere for me to look at.

**Comment by TripOptic** [comment]
@radfast 

1. Personal Server
2. Peaceful Surface changes mob spawning to require light level 0 before a mob can spawn.
3. No, Peaceful Surface is the only one.
4. Link to google doc( file too large for any free text hosting site) https://drive.google.com/file/d/0B6yDn0hEziJiY2oyVUJxRGZYRTQ/view?usp=sharing

**Comment by TripOptic** [comment]
My bad...

**Comment by radfast** [comment]
I don't see anything wrong in the logs, AlienVillagers are being registered correctly, as are all the mobs from other mods.

1.  Please carefully check that your client mods and configs **exactly** match the server mods and configs.  Best would be to delete the clientside ```/mods``` and ```/config``` folders and copy them from the server folder to your client ```.minecraft``` folder.  Obviously save any client-only mods first, I'm not sure what is client only.  And delete server-only mods from the client copy of the mods folder!

2.  If that doesn't yield results, please try your whole setup without the non-essential mods like FastCraft, MemoryCleaner, and PeacefulSurface - anything which does not actually place blocks / items / mobs in your world.  You have a lot of things there which change how vanilla code works, maybe something is messing with the villager spawning without realising it.

3.  If you still have the issue, my only suggestion is to try a reduced set of mods until the issue goes away, then we can figure out that the mod causing the conflict is in the ones you removed ... you can use a binary search method for efficiency.

If you can identify for me the one other mod which is causing this, we can look for a more specific cause.  So "installing XXX mod + Galacticraft on a clean server, causes the issue", that I might be able to fix.

**Comment by TripOptic** [comment]
@radfast 
Could the issue be arising from Extra planets or Project Nova?

**Comment by radfast** [comment]
I don't know what Project Nova is, so definitely maybe that.

Extra Planets is unlikely as somebody else would probably have reported the issue before, a lot of people use that add on in the Space Astronomy modpack.  But I do not test the add-ons myself, too busy with Galacticraft itself.  So could be a version compatibility issue, I guess.  Each version of the add-on is made for a specific Galacticraft version.  You'd have to ask the add-on authors for details.

**Comment by TripOptic** [comment]
I checked what the accual name of the add-on was and does Nova Galactic sound like an add-on you have heard of? Project link http://minecraft.curseforge.com/projects/nova-galactic?gameCategorySlug=mc-mods&projectID=241940

**Comment by radfast** [comment]
Thanks for the link, I didn't know about that one before.  Guess I do now!

**Comment by TripOptic** [comment]
I wiped my config files and cleared my mods folder to have server mods(same set of mods) loaded a new world and alien villagers are present. Removed peaceful surface and on a new world the still presist. Trying now just removing nova galactic but still having peacefulsurface. In my findings Nova Galactic is the problem.

**Comment by radfast** [comment]
> In my findings Nova Galactic is the problem.

Thank you, we can close this here then.  Please report the issue to the Nova Galactic developer.  I think you suspected this mod already in your earlier post ... ?
