### ISSUE TITLE
Rare 'Already Decorating!' Crash on Mars caused by WorldGenEggs

### ISSUE THREAD

**Issue by emptyknight** [micdoodle8/Galacticraft#2161]
Got to the Moon just fine, but when I launch in a Tier 2 rocket and the game tries to transition me to Mars I get the server crash below. Unabridged modpack, replicated in 407 and 446. Also have Galaxy Space 1.0.8, which according to their website is the right version for 446.

I checked the config file and "Generate all other mods features on planets" is set to false.

New to Github, couldn't find this problem in a search, apologies if already addressed somewhere else.

> ---- Minecraft Crash Report ----
> // Who set us up the TNT?
> 
> Time: 3/23/16 6:24 AM
> Description: Exception getting block type in world
> 
> java.lang.RuntimeException: Already decorating!!
>   at micdoodle8.mods.galacticraft.api.prefab.world.gen.BiomeDecoratorSpace.decorate(BiomeDecoratorSpace.java:24)
>   at micdoodle8.mods.galacticraft.api.prefab.world.gen.ChunkProviderSpace.decoratePlanet(ChunkProviderSpace.java:341)
>   at micdoodle8.mods.galacticraft.api.prefab.world.gen.ChunkProviderSpace.func_73153_a(ChunkProviderSpace.java:355)
>   at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
>   at fastcraft.a.d.a(F:84)
>   at fastcraft.Hooks.r(F:137)
>   at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040)
>   at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:52)
>   at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
>   at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189)
>   at net.minecraftforge.common.util.AsynchronousExecutor$Task.get(AsynchronousExecutor.java:165)
>   at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:341)
>   at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
>   at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
>   at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
>   at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
>   at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
>   at net.minecraft.world.World.func_72964_e(World.java:419)
>   at net.minecraft.world.World.func_147439_a(World.java:345)
>   at net.minecraft.world.World.func_147453_f(World.java:3881)
>   at net.minecraft.world.World.func_147455_a(World.java:2603)
>   at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:851)
>   at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:660)
>   at net.minecraft.world.World.func_147465_d(World.java:451)
>   at micdoodle8.mods.galacticraft.planets.mars.world.gen.WorldGenEggs.func_76484_a(WorldGenEggs.java:27)
>   at micdoodle8.mods.galacticraft.planets.mars.EventHandlerMars.onPlanetDecorated(EventHandlerMars.java:151)
>   at cpw.mods.fml.common.eventhandler.ASMEventHandler_473_EventHandlerMars_onPlanetDecorated_Post.invoke(.dynamic)
>   at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
>   at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
>   at micdoodle8.mods.galacticraft.api.prefab.world.gen.BiomeDecoratorSpace.decorate(BiomeDecoratorSpace.java:34)
>   at micdoodle8.mods.galacticraft.api.prefab.world.gen.ChunkProviderSpace.decoratePlanet(ChunkProviderSpace.java:341)
>   at micdoodle8.mods.galacticraft.api.prefab.world.gen.ChunkProviderSpace.func_73153_a(ChunkProviderSpace.java:355)
>   at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
>   at fastcraft.a.d.a(F:84)
>   at fastcraft.Hooks.r(F:137)
>   at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040)
>   at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:52)
>   at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
>   at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189)
>   at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354)
>   at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30)
>   at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:596)
>   at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
>   at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
>   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
>   at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
> ## A detailed walkthrough of the error, its code path and all known details is as follows:
> 
> -- Head --
> Stacktrace:
>   at micdoodle8.mods.galacticraft.api.prefab.world.gen.BiomeDecoratorSpace.decorate(BiomeDecoratorSpace.java:24)
>   at micdoodle8.mods.galacticraft.api.prefab.world.gen.ChunkProviderSpace.decoratePlanet(ChunkProviderSpace.java:341)
>   at micdoodle8.mods.galacticraft.api.prefab.world.gen.ChunkProviderSpace.func_73153_a(ChunkProviderSpace.java:355)
>   at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
>   at fastcraft.a.d.a(F:84)
>   at fastcraft.Hooks.r(F:137)
>   at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040)
>   at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:52)
>   at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
>   at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189)
>   at net.minecraftforge.common.util.AsynchronousExecutor$Task.get(AsynchronousExecutor.java:165)
>   at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:341)
>   at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
>   at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
>   at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
>   at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
>   at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
>   at net.minecraft.world.World.func_72964_e(World.java:419)
> 
> -- Requested block coordinates --
> Details:
>   Found chunk: true
>   Location: World: (-146,89,607), Chunk: (at 14,5,15 in -10,37; contains blocks -160,0,592 to -145,255,607), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
> Stacktrace:
>   at net.minecraft.world.World.func_147439_a(World.java:345)
>   at net.minecraft.world.World.func_147453_f(World.java:3881)
>   at net.minecraft.world.World.func_147455_a(World.java:2603)
>   at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:851)
>   at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:660)
>   at net.minecraft.world.World.func_147465_d(World.java:451)
>   at micdoodle8.mods.galacticraft.planets.mars.world.gen.WorldGenEggs.func_76484_a(WorldGenEggs.java:27)
>   at micdoodle8.mods.galacticraft.planets.mars.EventHandlerMars.onPlanetDecorated(EventHandlerMars.java:151)
>   at cpw.mods.fml.common.eventhandler.ASMEventHandler_473_EventHandlerMars_onPlanetDecorated_Post.invoke(.dynamic)
>   at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
>   at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
>   at micdoodle8.mods.galacticraft.api.prefab.world.gen.BiomeDecoratorSpace.decorate(BiomeDecoratorSpace.java:34)
>   at micdoodle8.mods.galacticraft.api.prefab.world.gen.ChunkProviderSpace.decoratePlanet(ChunkProviderSpace.java:341)
>   at micdoodle8.mods.galacticraft.api.prefab.world.gen.ChunkProviderSpace.func_73153_a(ChunkProviderSpace.java:355)
>   at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
>   at fastcraft.a.d.a(F:84)
>   at fastcraft.Hooks.r(F:137)
>   at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040)
>   at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:52)
>   at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
>   at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189)
>   at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354)
>   at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30)
>   at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:596)
>   at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
>   at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
>   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
>   at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by emptyknight** [comment]
Also tested without FastCraft, same problem.

**Comment by radfast** [comment]
Thank you.  I've looked at this, this is a bug in Galacticraft.  We can fix it next build, but there may be a couple of days delay because right now I cannot release a new build while the website is down.

Important message for other people finding this issue in a search for 'Already Decorating!' type crashes: in emptyknight's case this is a genuine Galacticraft bug caused by the WorldGenEgg code.  You can tell this from the stacktrace which has this code twice, once at the top and once half way through:
> micdoodle8.mods.galacticraft.api.prefab.world.gen.BiomeDecoratorSpace.decorate

Most other 'Already Decorating!' type crashes are not bugs in Galacticraft, for example #2066 is not Galacticraft.

**Comment by emptyknight** [comment]
@radfast Thank you for taking a look at it. I managed to finally get it to work by deleting the Mars dimension folder on the server. The first time the crash happened again, when I deleted it a second time and tried again Mars worked just fine.

I appreciate your help!
