### ISSUE TITLE
In game config UI does not save changes

### ISSUE THREAD

**Issue by The-Silver-Kid** [micdoodle8/Galacticraft#2163]
The in-game config UI (in the mods area of the title screen) doesn't save changes upon exit in galacticraft v 1.7-3.0.12.444

**Comment by radfast** [comment]
Thanks for reporting.  We'll take a look.  It could be a few days, as there's not much I can do while the server behind our website is down.

**Comment by EzerArch** [comment]
It's saving for me, with world reload, client reload and between worlds. (GC3 501)

Unless there's a specific config entry that is not saving, I think it's safe to close this.

**Comment by radfast** [comment]
There were a couple of problems with the config GUI which are now fixed in all versions.
