### ISSUE TITLE
Can't add other treasure Items to Tier 2 Treasure Chest

### ISSUE THREAD

**Issue by pfeiferocks** [micdoodle8/Galacticraft#2166]
Can't add Items to Tier 2 Chest because range is only from 1 to 3

Using "GalacticraftRegistry.addDungeonLoot(tier, item);"

EntityCreeperBoss.java
407 - 437
`  
public ItemStack getGuaranteedLoot(Random rand)

```
{
    List<ItemStack> stackList = GalacticraftRegistry.getDungeonLoot(2);
    int range = 2;
    //If player seems to have Tier 3 rocket already then add Astro Miner to the loot
    final EntityPlayer player = this.worldObj.getClosestPlayer(this.posX, this.posY, this.posZ, 20.0);
    if (player != null)
    {
        GCPlayerStats stats = GCPlayerStats.get((EntityPlayerMP) player);
        if (stats != null)
        {
            for (ISchematicPage page : stats.unlockedSchematics)
            {
                if (page.getPageID() == ConfigManagerAsteroids.idSchematicRocketT3)
                {
                    range = 3;
                    break;
                }
            }
            if (stats.rocketItem == AsteroidsItems.tier3Rocket)
                range = 3;
        }
        if (range == 2)
        {
            SpaceRace race = SpaceRaceManager.getSpaceRaceFromPlayer(player.getGameProfile().getName());
            if (race != null && race.getCelestialBodyStatusList().containsKey(AsteroidsModule.planetAsteroids))
                range = 3;          
        }
    }
    return stackList.get(rand.nextInt(range)).copy();
}
```

`

**Comment by MJRLegends** [comment]
All you need to do to add items to the tier 2 chest is do GalacticraftRegistry.addDungeonLoot(2, ITEMHERE);

**Comment by pfeiferocks** [comment]
I used it but the range is always 2  or sometimes 3
int range = 2;

**Comment by MJRLegends** [comment]
What you on about? range? what range?

**Comment by MJRLegends** [comment]
The tier is the tier of chest you want it to be in

**Comment by pfeiferocks** [comment]
It dont read the size of the list 

this is out of the skelletonboss
public ItemStack getGuaranteedLoot(Random rand)
    {
        List<ItemStack> stackList = GalacticraftRegistry.getDungeonLoot(1);
        return stackList.get(rand.nextInt(stackList.size())).copy();
    }

**Comment by SteveKunG** [comment]
Same as @pfeiferocks :(

**Comment by MJRLegends** [comment]
@radfast ok, any chance we can add something for the Mars Dungeon boss to drop other schematics, as i really need a schematic to be in the Mars Dungeon? :P Please :P

**Comment by radfast** [comment]
Does this help?  https://github.com/micdoodle8/Galacticraft/issues/2717#issuecomment-301505877

If not, what do we need to do here?  I don't really want to add new registry options, just something to give add-ons access to the loot table so you can manipulate it yourself.

**Comment by MJRLegends** [comment]
@radfast That issue/comment you linked helped with a more planets issues on my mod pack but not this issue, basically getGuaranteedLoot in the creeper boss is to hard codded in to only giving certain schematics which adding anything to the tier 2 loot will not give it in the dungeon chest as getGuaranteedLoot doesnt search for anything but the Tier 3 and Astro miner schematic it seems

**Comment by MJRLegends** [comment]
@radfast It seems theres a nice ordering system to make sure you get both schematics but its to much of a order and isnt the same to how the Tier 2 Rocket and the moon buggy works in the Boss getGuaranteedLoot

**Comment by radfast** [comment]
Thanks for your patience guys.  This is now implemented, thank you to @MJRLegends for the recent suggestions.
