### ISSUE TITLE
Temperature with certain fluids/gases

### ISSUE THREAD

**Issue by JasonMcRay** [micdoodle8/Galacticraft#2167]
Galacticraft is owerwriting some fluids/gases (or GregTech is grabbing it from other mods if they are present in them). It results on showing the incorect temperature.

Found gases are:
Oxygen
Methan
Hydrogen
Nitrogen

All of these have temperature set at 0K. on its own i dont think it can cause problems, but with GregTech the temperature is somewhat important when using pipes. GregTech pipes can hold only liquids/gases up to certain temperature (for example you can't use Wooden Fluid Pipes to transport Lava, it will result in burned pipe) and also higher temperature in pipes can hurt players iuf they will stand on the pipe.

Would it be possible to fix that and add temperatures?

Or maybe let other mods to load their fluids and do not overwrite them?

**Comment by DarknessShadow** [comment]
Those are gases in gregtech not cooled down to liquids. They should all be at around 300K.
<a href="http://imgur.com/7tAFUO3"><img src="http://i.imgur.com/7tAFUO3.png" title="source: imgur.com" /></a>
