### ISSUE TITLE
Aluminum/Aluminium

### ISSUE THREAD

**Issue by dtriplet** [micdoodle8/Galacticraft#2168]
I guess this is a feature request. Please look at changing GC Aluminium to be oredict compatible with and maybe change it to the US spelling of Aluminum.

In the real world, the word Aluminum is mostly used in the USA and the rest of the world uses Aluminium and they are the same. In modded Minecraft, Aluminum was used by mods like Tinkers Construct (TiCo) and was easy to get by finding Aluminum Ore and Aluminum Gravel Ore and smelting it while Aluminium was GregTech specific and required complex processing of Bauxite Ore. The two were not interchangeable and I think it would be best to stick with one name to avoid GregTech, and possibly IC2, causing problems with Aluminium.

**Comment by C1ffisme** [comment]
> I guess this is a feature request.

Please use the Galacticraft Forum for suggestions or feature requests.

**Comment by dj3520** [comment]
IIRC both aluminum and aluminium are registered. Think I chuckled when I
saw it in NEI.

**Comment by radfast** [comment]
Please provide evidence that this is causing a problem.
Galacticraft aluminium is already oredict compatible with all other forms I am aware of.
