### ISSUE TITLE
Add ComputerCraft and OpenComputers support for Launch Controller and Oxygen Detector

### ISSUE THREAD

**Issue by leoworm** [micdoodle8/Galacticraft#2169]
Because these kind of things would be very useful for a Moon Base.

**Comment by C1ffisme** [comment]
Please use the Galacticraft Forum for suggestions or feature requests.

**Comment by dj3520** [comment]
Oxygen Detector outputs redstone already.

**Comment by Creeperman8362** [comment]
Except the forum is down so he cant

**Comment by NoOneNo** [comment]
the forums have been down for over 2 weeks?

**Comment by dj3520** [comment]
Still, don't post it here.

**Comment by leoworm** [comment]
Where then?

**Comment by MJRLegends** [comment]
@dj3520 how can he post it there the site is down?? lol

**Comment by NoOneNo** [comment]
This is kinda sad, the site has been down for around 2 weeks, and no word from the devs on an eta?

**Comment by Creeperman8362** [comment]
Tweets Tweets & replies Media 

        Pinned Tweet
        Mitch Petrie ‏@micdoodle8 Apr 1

        Apologies for the website downtime, should hopefully be resolved within a few days. Backup downloads can be found at http://goo.gl/Fq7gox

**Comment by dj3520** [comment]
@MJRLegends
>how can he post it there the site is down?? lol

I know the site is down. See #2151. As for posting it on the forum, you'll simply have to wait until it's back up.

**-- REASONING --**

![image](https://cloud.githubusercontent.com/assets/8284194/14369349/50739e44-fcf2-11e5-95f4-9636d16ab549.png)

https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md#what-else-is-not-ok-on-the-issues-list

**Comment by radfast** [comment]
Thanks for the suggestion.  All suggestions must go on the forum, not this issues list, so I will close this.  Apologies for the site downtime a couple of months back, it was frustrating for me as well, and outside my control.

FWIW, this is a frequent suggestion, and is on my to-do list, it will happen some time.  No ETA.
