### ISSUE TITLE
WEBSITE IS BACK ONLINE [NOT A BUG]

### ISSUE THREAD

**Issue by Creeperman8362** [micdoodle8/Galacticraft#2172]
no bugs here just want you guys to know

**Comment by EzerArch** [comment]
We know already: https://github.com/micdoodle8/Galacticraft/issues/2151#issuecomment-207822851

No need to open another issue just of that, specially when you have posted on [the existing one)[https://github.com/micdoodle8/Galacticraft/issues/2151#issuecomment-204879519] already.
