### ISSUE TITLE
Galacticraft won't load

### ISSUE THREAD

**Issue by SimplyJames1** [micdoodle8/Galacticraft#2173]
I have forge, Galacticraft, GC Planets and Micdoodlecore are the only mods in my mod folder at the moment, but no matter what I do, when I try to load the game it always comes up with this:

---- Minecraft Crash Report ---- // There are four lights!

Time: 12/04/16 20:11 Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: micdoodle8/mods/galacticraft/planets/asteroids/tile/TileEntityShortRangeTelepad at cpw.mods.fml.common.LoadController.transition(LoadController.java:163) at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:538) at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243) at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480) at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) at net.minecraft.client.main.Main.main(SourceFile:148) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:483) at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) at net.minecraft.launchwrapper.Launch.main(Launch.java:28) Caused by: java.lang.NoClassDefFoundError: micdoodle8/mods/galacticraft/planets/asteroids/tile/TileEntityShortRangeTelepad at micdoodle8.mods.galacticraft.planets.asteroids.blocks.AsteroidBlocks.initBlocks(AsteroidBlocks.java:38) at micdoodle8.mods.galacticraft.planets.asteroids.AsteroidsModule.preInit(AsteroidsModule.java:99) at micdoodle8.mods.galacticraft.planets.PlanetsProxy.preInit(PlanetsProxy.java:18) at micdoodle8.mods.galacticraft.planets.PlanetsProxyClient.preInit(PlanetsProxyClient.java:18) at micdoodle8.mods.galacticraft.planets.GalacticraftPlanets.preInit(GalacticraftPlanets.java:51) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:483) at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:483) at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) at com.google.common.eventbus.EventBus.post(EventBus.java:275) at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:483) at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) at com.google.common.eventbus.EventBus.post(EventBus.java:275) at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:535) ... 10 more Caused by: java.lang.ClassNotFoundException: micdoodle8.mods.galacticraft.planets.asteroids.tile.TileEntityShortRangeTelepad at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) at java.lang.ClassLoader.loadClass(ClassLoader.java:424) at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ... 42 more Caused by: java.lang.NoClassDefFoundError: micdoodle8/mods/galacticraft/core/tile/TileEntityElectricBlock at java.lang.ClassLoader.defineClass1(Native Method) at java.lang.ClassLoader.defineClass(ClassLoader.java:760) at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ... 44 more Caused by: java.lang.ClassNotFoundException: micdoodle8.mods.galacticraft.core.tile.TileEntityElectricBlock at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) at java.lang.ClassLoader.loadClass(ClassLoader.java:424) at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ... 48 more

A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details -- Details: Minecraft Version: 1.7.10 Operating System: Windows 10 (amd64) version 10.0 Java Version: 1.8.0_25, Oracle Corporation Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation Memory: 149777736 bytes (142 MB) / 264396800 bytes (252 MB) up to 1060372480 bytes (1011 MB) JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0 FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.3.1424 6 mods loaded, 6 mods active mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.3.1424-1.7.10.jar) Unloaded->Constructed->Pre-initialized Forge{10.13.3.1424} [Minecraft Forge](forge-1.7.10-10.13.3.1424-1.7.10.jar) Unloaded->Constructed->Pre-initialized Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized GalacticraftCore{3.0.12} [Galacticraft Core](Galacticraft-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized GalacticraftMars{3.0.0} [Galacticraft Planets](Galacticraft-Planets-Mod-1.7.10.jar) Unloaded->Constructed->Errored GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 364.72' Renderer: 'GeForce GTX 970M/PCIe/SSE2'

So what is the problem and how do I fix it?

**Comment by radfast** [comment]
1.  Please try re-downloading the Galacticraft files, maybe you have a download error.

2.  If that doesn't fix it, please post your full `fml-client-latest.log`

**Comment by radfast** [comment]
Closing as no follow-up.  My guess is the OP fixed it by re-downloading.
