### ISSUE TITLE
PlayerAPI breaks cryogenic chamber

### ISSUE THREAD

**Issue by katzenpapst** [micdoodle8/Galacticraft#2174]
I was trying to figure out why the cryogenic chamber doesn't work for me, and noticed that it's PlayerAPI's fault. As soon as it's installed, the chamber becomes unuseable. You get moved into the chamber, or rather, onto it's position, but you don't actually sleep. It seems to work on the otherworld, though, but there only like a regular bed.

Tested with PlayerAPI 1.3 and 1.4, and GC 454.

**Comment by EzerArch** [comment]
Not the 1st one to spot the issue:
> I'm also investigating other issues when installed with mods other than those listed below. For example: once the player awakens, the cryochamber becomes impassable (solid) and the player has to break free *(Edit: It's smart moving again!)*. https://github.com/micdoodle8/Galacticraft/issues/1159#issuecomment-182098308

Maybe also related to #1357.

**Comment by nidico100** [comment]
I have the problem too :(

**Comment by themechman** [comment]
Confirming this still happens.

**Comment by radfast** [comment]
Fixed from build 492.  Sorry it took us so long to get to this.

You'll need to be using PlayerAPI versions 1.3 or 1.4 for Minecraft 1.7.10 - hard to imagine anyone isn't using this version but Forge should now enforce this.
