### ISSUE TITLE
Possible Blood Magic issue again.

### ISSUE THREAD

**Issue by border999** [micdoodle8/Galacticraft#2176]

**Comment by border999** [comment]
In the latest version of Galacticraft that is out for 1.7.10, has anyone noticed issues with using blood magic rituals or activating the eldritch portal to the Outerlands? Both Thaumcraft and Blood Magic are respectively on their latest 1.7.10 updates.

**Comment by radfast** [comment]
You have not reported any specific issue...

If there is any Blood Magic issue at all, normally you can fix it by installing **PlayerAPI** - further info [here](https://wiki.micdoodle8.com/wiki/Compatibility)

If you don't want to install PlayerAPI, then please ask the Blood Magic developer to update his 'fake player detection' code to accommodate the Galacticraft player entities, as he kindly did once before.  The Galacticraft player entities are [server entity](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/entities/player/GCEntityPlayerMP.java) and [client entity](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/entities/player/GCEntityClientPlayerMP.java)
