### ISSUE TITLE
Dynamic Surroundings and Galacticraft

### ISSUE THREAD

**Issue by Managarmr719** [micdoodle8/Galacticraft#2177]
With Dynamic Surroundings installed, the gravity returns to normal, clouds start appearing, the overworld doesn't show beneath the station, the player stops leaving footprints and the HUD disappears.

Without DS:
![2016-04-15_15 56 41](https://cloud.githubusercontent.com/assets/7836631/14565361/b9b084e0-0322-11e6-8514-e8a41b7481b0.png)
![galacticcraftnods](https://cloud.githubusercontent.com/assets/7836631/14565251/15a36692-0322-11e6-948c-1345dab7f6e7.PNG)
![2016-04-15_15 43 16](https://cloud.githubusercontent.com/assets/7836631/14565008/efefa2f4-0320-11e6-8ce9-6540d947d3e8.png)

With DS:
![2016-04-15_15 15 04](https://cloud.githubusercontent.com/assets/7836631/14564102/eb699838-031c-11e6-8fa7-425812008683.png)
![2016-04-15_15 15 13](https://cloud.githubusercontent.com/assets/7836631/14564113/f3310010-031c-11e6-9647-ad0fa5d5e800.png)
![2016-04-15_15 43 58](https://cloud.githubusercontent.com/assets/7836631/14565016/f941e1dc-0320-11e6-9a1f-5f06da135f8a.png)

**Comment by Managarmr719** [comment]
Disabling Fancy Cloud handling in the dsurround.cfg file fixes it.

**Comment by mcdodge34** [comment]
Good to know... it was driving me insane and found out the most awesome mod I've added to my pack caused this weird issue.

**Comment by EzerArch** [comment]
Not a bug. I'm replying to inform I've released a Dynamic Surroundings config file pack for Galacticraft 1.7.10 (probably will also work with 1.8.9, except on Venus... yet).

I'd like some people to try/test it: https://forum.micdoodle8.com/index.php?threads/dynamic-surroundings-config-files-for-galacticraft.6639/

**Comment by Managarmr719** [comment]
Dynamic Surroundings removed fancy cloud handling in version 1.0.5.7 so it shouldn't be a problem from that version onward.

**Comment by EzerArch** [comment]
@Managarmr719: I know that. What I mean is that I released a cfg file that will mute some sound effects in airless dims (OSS, Moon, Asteroids) and add wind sounds on Mars.

**Comment by Managarmr719** [comment]
@EzerArch I saw that but I though that I should leave that here as a note. About the config pack I'll test it out today or tomorrow.

**Comment by Managarmr719** [comment]
@EzerArch  I was trying out the config pack when I noticed some audio problems. It's specially bad when I move around, you can check the recordings here: https://drive.google.com/drive/folders/0ByBK1E1PKZ5QVHY2VFlxY0pHRnc?usp=sharing. I was using the latest versions of Dynamic surroundings.  I tried earlier versions of DS and 1.0.5.7 fixes part of the problem, Overworld sounds work fine again but when I go back to Mars the wind is still broken although it's still better than with the newer versions. Everything else seems to be working although I just started testing, there are some things that annoy me but I don't know if it's possible to fix without completely disabling them, such as the jump sound (even tough there are no step sounds), mobs making sounds in environments without air, etc...

**Comment by Managarmr719** [comment]
@EzerArch Adding "repeatDelay" ou "repeatDelayRandom" fixes the sound problem that I was having on Mars.

**Comment by radfast** [comment]
> I also though about using DS dust storms on Mars 

Sounds nice, can anyone point me to a video showing what this looks like, maybe in a Desert or Mesa biome on the Overworld?  We can maybe look at Galacticraft implementing its own version of this on Mars.

**Comment by Managarmr719** [comment]
@radfast You can see how it looks here: https://youtu.be/1CDMAlmv1OQ?t=4m9s

**Comment by radfast** [comment]
oooh that's very nice.  We can look at doing that.

**Comment by EzerArch** [comment]
@Managarmr719: I have disabled many sounds just after installing DS for the first time, for personal choice/taste (footsteps, jump, whales, sounds that go too out-of-place etc).

It seems it's possible to set footstep/jump sounds for Galacticraft blocks (I've never tried it). In your video, the footsteps sound like walking on concrete. Even without DS, walking on Mars superficial blocks emit "stained clay block" footsteps; probably DS is getting block hardness to set a "default" sound. I think gravel sounds would fit better.

> I was using the latest versions of Dynamic surroundings. I tried earlier versions of DS and 1.0.5.7 fixes part of the problem (...) mobs making sounds in environments without air

Interesting I'm using 1.0.5.9, I don't get any problems on Mars. I'll use `repeatDelayRandom` as improvement.

As to the mobs: you'll be able to hear them if you're using a Frequency Module. Unless there's something else I'm missing.

----
@radfast:
> We can maybe look at Galacticraft implementing its own version of this on Mars.

Nice. Would the dust storms be like rain on the Overworld but with different textures?

Just some references:
Forum discussion: [post 1](https://forum.micdoodle8.com/index.php?threads/dust-storms.2767/#post-28839) , [post 2](https://forum.micdoodle8.com/index.php?threads/dust-storms.2767/#post-28871).
Videos: [NatGeo](https://www.youtube.com/watch?v=JKBk_Kfucs4)
Article: [Nasa 1](https://www.nasa.gov/mission_pages/mer/images/20070720.html), [Nasa 2](https://www.nasa.gov/feature/goddard/the-fact-and-fiction-of-martian-dust-storms).

**Comment by radfast** [comment]
Nice images!

I have read: [https://en.wikipedia.org/wiki/Mars_trilogy Red Mars trilogy] and [https://en.wikipedia.org/wiki/The_Martian_(Weir_novel) The Martian], and seen the movies [https://en.wikipedia.org/wiki/The_Martian_(film) The Martian], [https://en.wikipedia.org/wiki/Red_Planet_(film) Red Planet] and [https://en.wikipedia.org/wiki/Mission_to_Mars Mission to Mars], so I have some other ideas what Mars should be like ... 

Also seen an **awesome** exhibition of photographs/art from [http://www.nytimes.com/interactive/2011/12/02/science/space/20111202-planetscapes.html?_r=0#3 Michael Benson] - really recommend this if you ever have the chance, internet reproductions do not do these images justice - they are 10kx10k resolution beautiful images that he makes.

My "homework": watch [https://en.wikipedia.org/wiki/The_Last_Days_on_Mars The Last Days on Mars] and [https://en.wikipedia.org/wiki/John_Carter_(film) John Carter] :)

**Comment by radfast** [comment]
Oh: http://graphics8.nytimes.com/images/2011/11/30/science/30Goldilocks-slide-ZLL6/30Goldilocks-slide-ZLL6-jumbo.jpg

Martian sunset: The blue colour around the setting sun is caused by atmospheric scattering

**Comment by Managarmr719** [comment]
@EzerArch I also usually disable the jump sound and things like that, but I was wondering if it was possible to disable them only on certain biomes/dimensions, so that people didn't have to have choose between having them everywhere or not having them at all. I had a quick look around on the DS wiki but didn't find a way. 

> As to the mobs: you'll be able to hear them if you're using a Frequency Module. Unless there's something else I'm missing.

I wasn't having trouble hearing them, it was the opposite I could still hear them without the Frequency Module. I'm using GC 3.0.12.465, I'll try with a newer version to see if that fixes it.

**Comment by EzerArch** [comment]
@Managarmr719:
> but I was wondering if it was possible to disable them only on certain biomes/dimensions.

It seems it's not possible to customize the continuous footsteps, unless those random sound events triggered by walking in certain biomes or on blocks (e.g. squeakywood).

At first assuming DS would read any json file in [{root}/assets/dsurround/data/footsteps](https://github.com/OreCruncher/BetterRain/tree/master/src/main/resources/assets/dsurround/data/footsteps), I tried to create a [Galacticraft_blockmap.json](https://gist.github.com/EzerArch/0826fa20f1d9f213596c4c03202d66c0). DS will not load it; I guess anything in data folder is protected against resource pack modification.

**Comment by Managarmr719** [comment]
Tested with GC 3.0.12.475, still hearing mobs on dimensions without "air" (i.e. moon) while not having the Frequency Module equipped, I'm guessing that's not the intended behaviour, should I open new a issue?

**Comment by radfast** [comment]
I doubt that we can fix this on our side.  Can you give me a link to Dynamic Surroundings source code?

**Comment by Managarmr719** [comment]
@radfast https://github.com/OreCruncher/BetterRain/tree/1.7.10

**Comment by radfast** [comment]
thank you

**Comment by Managarmr719** [comment]
I'm still hearing them even without the Dynamic Surroundings mod.

**Comment by EzerArch** [comment]
> I'm still hearing them even without the Dynamic Surroundings mod.

I was very suspicious there was something wrong: both GC mob sounds and the frequency module worked pretty fine, with or without DS. I guess there must be another mod that is affecting GC.

Mod list?

Old reply:
> Edit: I also thought about using DS dust storms no Mars but _**because it replaces rain and GC doesn't allow rain on Mars it doesn't work. :(**_

Can I take the blame? ;) Long, long, long time ago I complained that mobs weren't burning on the Moon and Mars during daytime because it was raining invisible rain (issue 394). Probably the solution was to kill the precipitation altogether.

**Comment by Managarmr719** [comment]
It's working fine now, deleted configs, I must have forgotten to delete the old config files after updating and they were causing this issue, sorry for the trouble :\.
