### ISSUE TITLE
Thermos 55 + Multiverse 2.5 + Galacticraft 413-454 causes client-side rendering issues on relog, occasionally resulting in client crash

### ISSUE THREAD

**Issue by Brycey92** [micdoodle8/Galacticraft#2182]
Please see [Thermos issue #313](https://github.com/TCPR/Thermos/issues/313) for full details.

**Comment by Brycey92** [comment]
Sorry for all the title changes!

**Comment by Brycey92** [comment]
I have determined a71571d934b9656dc005037bf449c9da1feb45a2 as the deadly commit, since it is the only commit related to worlds between 412 and 413, the last build without the issue and the first build with it.

**Comment by DraksterAU** [comment]
I've been using build 446 of galactic craft with thermos b46 since 446 was released.

No issues.

I think this might be related to new thermos commits, not galacticraft - possibly the same
Stuff that broke maps?

**Comment by DraksterAU** [comment]
@Brycey92 Wanna confirm you're OK once you downgrade thermos?

**Comment by Brycey92** [comment]
@DraksterAU I haven't downgraded Thermos, only GC.

**Comment by DraksterAU** [comment]
And I'm saying try downgrading thermos because I have no issue with b46, latest GC and multiverse :)

**Comment by Nentify** [comment]
What solution has been determined for this?

**Comment by DraksterAU** [comment]
Downgrade thermos. I'm using these plugins and mods without any issue on B46.... Its a thermos problem.

**Comment by radfast** [comment]
Doesn't seem like a Galacticraft issue, judging from DraksterAU's posts.

We are committed to having Galacticraft work in a Thermos environment, so if further info shows that this **is** a Galacticraft issue after all, please re-open this issue.
