### ISSUE TITLE
Integration with "Custom Chest Loot"

### ISSUE THREAD

**Issue by Shurik1236** [micdoodle8/Galacticraft#2185]
RUS:
Решил добавить в сундуки на Марсе (Которые ключом открываются) схемы из AE2...
Поставил "Custom Chest Loot" как единственный известный мне мод изменяющей генерацию предметов в сундуках...
А он просто не видит сундуки сокровищниц! Вообще.
Может добавить поддержку этого мода?
ENG(Yandex Translator):
Decided to add in chests on Mars (Which the key opened) schematic of AE2...
Put "Custom Chest Loot" as the only mod changing the generation of the items in the chests...
And he just doesn't see the treasure chests! At all.
Can add support for this mod?

**Comment by radfast** [comment]
No, sorry, I will not + cannot do this.

If the author of Custom Chest Loot wants to contact us to talk about Galacticraft API hooks to allow this to happen, we will do what we can to help him.  But if he has no interest in doing this, then it's not something we can do from our end.
