### ISSUE TITLE
Galacticraft 3.0.12.375 incompatibility with Animated Player v1.5.1 mc1.7.10

### ISSUE THREAD

**Issue by Somriure** [micdoodle8/Galacticraft#2187]
Hi. When i use Animated player v 1.5.1 mc 1.7.10, AnimationAPI v1.2.4 mc1.7.10 with Galacticraft 3.0.12.375 i dont see animation from Animated player mod. I use Render Player API 1.7.10 v1.4 and Player API 1.7.10 v1.4, but it doesn't work. How to fix this problem?

**Comment by Reshirou** [comment]
same with Mo' bends.
There should just be an option in the config to turn off the custom GC animations

**Comment by Somriure** [comment]
GC 3 don't have this option in config.cfg(

**Comment by Reshirou** [comment]
@Somriure yeah, I know
there should be, I can see that fixing lots of problems with custom rendering mods

**Comment by radfast** [comment]
You're supposed to use Galacticraft 3.0.12.460.
