### ISSUE TITLE
How to create a 2 biome on his planet?

### ISSUE THREAD

**Issue by RonFall** [micdoodle8/Galacticraft#2188]
Good day. I have a planet on which I want to make a few biomes. Tell me please, how to create a biome on his planet? How many times I tried, I failed. Still, the second biome does not appear. If you have any instructions or links will be grateful.

**Comment by C1ffisme** [comment]
I would probably ask support or modding questions on the [forum](https://forum.micdoodle8.com/index.php#galacticraft.3).

**Comment by RonFall** [comment]
The forum can not be registered. After registration, the server error occurs.
![72e878d0-078f-11e6-85a7-c7de1e31ee66](https://cloud.githubusercontent.com/assets/18558783/15013251/2ba93d6a-1207-11e6-9924-454dbc47b928.png)

**Comment by C1ffisme** [comment]
Oh boy, more website problems.

**Comment by RonFall** [comment]
You can advise tutorials on creating biome in its dimension?

**Comment by EzerArch** [comment]
> The forum can not be registered. After registration, the server error occurs.

Contacting the tech support.

**Comment by EzerArch** [comment]
@RonFall, please try again now.

**Comment by RonFall** [comment]
Registration completed successfully! Thank you.

**Comment by EzerArch** [comment]
@RonFall, perhaps you could try to ask here (https://forum.micdoodle8.com/index.php?threads/1-7-10-galaxy-space-stable.5298/). @BlesseNtumble managed to create a planet with more than 1 biome.

**Comment by RonFall** [comment]
Question resolved successfully! The answer is here: https://github.com/Jimmy04Creeper/Minecraft_Tutorial_1.5.2/tree/master/com/MultiBiomeDim

**Comment by EzerArch** [comment]
@RonFall , You received the confirmation email on registering, didn't you?

**Comment by RonFall** [comment]
@EzerArch Yes, I checked.

**Comment by EzerArch** [comment]
@RonFall , did you receive the confirmation email?

**Comment by RonFall** [comment]
@EzerArch Yes

**Comment by EzerArch** [comment]
> Question resolved successfully!

@RonFall, could you close this issue? :)

**Comment by RonFall** [comment]
Yes, thank you.
