### ISSUE TITLE
Possible config bug

### ISSUE THREAD

**Issue by THEVOLCO** [micdoodle8/Galacticraft#2192]
Hi,

I would like to disable the generation of oil in the overworld; for that I deleted the "0" in the config file here:

 I:"Oil gen in external dimensions" <
     >

I thought this would work but it didn't. Am I doing something wrong or is it a bug?

**Comment by dj3520** [comment]
I'd imagine this isn't a bug. Simply a misunderstanding. "External" sticks
out to me, meaning that it's likely the overworld is hard coded myself to
be on.

**Comment by Creeperman8362** [comment]
Try this

    # Increasing this will increase amount of oil that will generate in each chunk.
    D:"Oil Generation Factor"=0

**Comment by THEVOLCO** [comment]
No it doesn't :(

**Comment by THEVOLCO** [comment]
I just found out that it's not a bug. When you right-click at buildcraft oil with a bucket(which I have also installed) i get a bucket of oil from galacticraft.

**Comment by radfast** [comment]
Deleting the "0" in the config file should have prevented generation of Galacticraft oil in any **new** chunks generated in the Overworld after you made that change.  Galacticraft oil is found in pockets deep underground, around y=18 to y=20.

This config will have no effect on **Buildcraft** oil generation, as that oil obviously is made by the other mod.
