### ISSUE TITLE
Error when joining a non forge server from a modded client!!!

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft#2194]
**Right my setup i have here is:**
- A bungeecord server
- A modded thermos/forge server running my mod pack
- A Hub/Lobby Server running Spigot

Client is running my mod pack (Space Astronomy)

**Issue**
Right when i try to join the hub/lobby server through the bungeecord server or directly with build 442 and newer then I get a error on screen saying "No OpenGL context found in the current thread" and i get this error in the console http://pastebin.com/a7HRK10L

After looking in to the issue it seems to be this commit that seems to broke it as if i use a 441 build and later it works all fine - https://github.com/micdoodle8/Galacticraft/commit/e782f73750887f26b6913ebe857015932308234a

And i tracked it down to this function that seems to be the issue -https://github.com/micdoodle8/Galacticraft/blob/e782f73750887f26b6913ebe857015932308234a/src/main/java/micdoodle8/mods/galacticraft/core/util/MapUtil.java#L86

Edit: Also thought i'd just say that joining the server running my mod pack (thermos/forge server) all works great!

**Comment by tyler2k15** [comment]
Also experiencing this issue.

**Comment by radfast** [comment]
Thanks for the nice precise and focused issue report, we should be able to fix this.

**Comment by MJRLegends** [comment]
@radfast No problem, any idea of a ETA as im about to update my mod pack and wonder if i should wait or release it and then include it in the next mod pack update

**Comment by radfast** [comment]
I'll try to fix this later today, no promise, it depends how it goes.

**Comment by MJRLegends** [comment]
@radfast ok need any help with testing let me know

**Comment by radfast** [comment]
@MJRLegends I think this latest commit should have fixed this issue, but I don't have a Bungee server set up to test it on.  Please will you test build 461 and confirm?

**Comment by MJRLegends** [comment]
Yeah will give it a test and get back to you

**Comment by MJRLegends** [comment]
@radfast yeah seems to work great :P

**Comment by radfast** [comment]
Good to know.  Yay, one issue fixed :)
