### ISSUE TITLE
Still spawning on moon

### ISSUE THREAD

**Issue by themechman** [micdoodle8/Galacticraft#2195]
Good evening! Having a bit of a problem. When one of my co-workers dies off world, they keep spawning there until I console them back to earth. I had apparently forgot to set the option on the modpack when I published it. Shouldn't the server config override the client config?

**Comment by EzerArch** [comment]
I pointed out the the death-loop issue long time ago, in #487, this was @radfast's answer:
> If you are playing a SSP world with no cheats, and you get stuck like this, you can change the config option to force respawn on the Overworld - I don't see why that is so hard? On a multiplayer server that is not possible (as the players don't have access to the server's config) but there are usually several ways to move around the server even if the staff won't help you out, for example /spawn, /home, /tp or /f home. -- https://github.com/micdoodle8/Galacticraft/issues/487#issuecomment-48625878

But also, I'm afraid that `Force Overworld Spawn` is not among the options overridden by server cfg_ here: https://wiki.micdoodle8.com/wiki/Game_Balance#Server_controlled_settings

Try to make both server and client to have `B:"Force Overworld Spawn"=false`, and see what happens.

**Comment by themechman** [comment]
Will give it a shot.

**Comment by radfast** [comment]
The Force Overworld Spawn setting on the server is what matters.  The client config _should_ make no difference - the server controls the respawn.

If you're telling me that the client config is making a difference, that's a bug I will want to fix.

**Comment by themechman** [comment]
Sorry, I have not checked this yet. I'll give it a go here later today.

**Comment by themechman** [comment]
Now that I have recuperated I intend to get this checked out. Hopefully give you a result shortly.

**Comment by themechman** [comment]
I'm an idiot. Sorry for not checking into this. Will try it out here hopefully this week.

**Comment by radfast** [comment]
Closing due to no follow-up.  If it still seems to be a problem, please re-open.
