### ISSUE TITLE
Unable to launch to planet

### ISSUE THREAD

**Issue by themechman** [micdoodle8/Galacticraft#2197]
An actual bug this time. My co-wokers and I play on a server I cobbled together at work. Its an i7-4790 with 16GB of ram and a 128GB samsung 520 Pro ssd. The server has been running for two months without issue and restarted every week or two just to purge the memory. It's launcher ram is set to a mere 6GB.

Yesterday we did something glorious. A simultaneous missile launch of five people. Me being the cautious one, I had folks wait to join the world as in the past, initial worldgen was intensely taxing. I land safely on the moon. Then I told them to land one at a time to make sure people got out of the way. Upon clicking "launch" from the planet menu, hercules_maximus (we call him max) says he's stuck in limbo. I was thinking since he's doing the vpn thing it was latency. Errors were spewing across the server console faster than I could read and ram was already starting to thrash the swap file. System ram usage went from a calm 4GB used to 10GB by java.exe in seconds. TPS tanked and eventually I couldnt even issue commands to the server, so I had to go to the box and issue a stop.

I increased the ram allocation to 14GB and this seems to have solved the TPS tanking, but it did not resolve the users changing planets. We all eventually got to the moon. It took the server about three to ten minutes to process each person.

There were some attempts to use the galaxy map to get back to overworld. This worked sorta, but it put one of them right back on the launchpad on overworld with no way to escape. Steve broke his rocket with him in it and it exploded on the launch pad wrecking things.

If you would like this log file, its almost 1GB in size across three log files. I am not sure github would permit such a size.

Edit: Failed to post versions
GalacticraftCore-1.7-3.0.12.454
Galacticraft-Planets-1.7-3.0.12.454
MicdoodleCore-1.7-3.0.12.454

**Comment by radfast** [comment]
If the server has RAM issues or severe lag, then yes obviously you may see unintended behaviour.

Precise steps for how to make a server go from 4GB to 10GB in seconds, please.  That's the worrying part of your issue report.

Maybe cut the log file down to the **relevant part** covering 5-10 seconds either side of when this happened?

I will also need a list of your other mods.  If you feel like testing this some more, please can you try the same steps with a reduced mod list.

For info, I run Galacticraft and about 12 other mods on a server with 1GB of RAM allocated, and it's just fine.

**Comment by themechman** [comment]
So, clarification:
When a rocket launched and went to space, the galaxy map is supposed to open. I've checked this on a remote connection and have some odd results.
With a network latency of 100ms, reaching the point of the galaxy map to open takes  about 20 seconds. Once open, you select the planet and click launch. Great. The screen goes blank and you are falling towards overworld. I am then brought back to galaxy map. This process repeats three times before I am taken to my chosen destination.

What improves this is having a minimum of one chunk loaded on the GC planet. However we have imposed a two minute cool-down on GC dims using galaxy map or use an alternate method to get there (Teleport).

As for the massive ram consumption we're still scratching our heads. First time creation of the GC planets only seems to cause this massive ram consumption.

I've updated several mods since this happened and I also found a ticking entity on overworld. Since these changes we've had far fewer problems.

Mods list (++ add/update since crash)

++\ae2stuff-0.5.0.56-mc1.7.10.jar
\ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar
\AppleCore-mc1.7.10-1.1.0.jar
\appliedenergistics2-rv2-stable-10.jar
++\bdlib-1.9.4.109-mc1.7.10.jar
\BetterRecords-1.7.10-1.2.0.jar
\BiblioCraft[v1.11.4][MC1.7.10].jar
\BigReactors-0.4.3A.jar
\Carpenter's Blocks v3.3.7 - MC 1.7.10.jar
\ChickenChunks-1.7.10-1.3.4.19-universal.jar
\Chisel2-2.5.1.44.jar
\CodeChickenCore-1.7.10-1.0.7.46-universal.jar
\CoFHCore-[1.7.10]3.1.2-325.jar
\ComputerCraft1.73.jar
\CookieCore-1.7.10-1.4.0-11.jar
\DanglingVanillaFixer-1.0.jar
\Decocraft-2.3.2_1.7.10.jar
++\DragonAPI 1.7.10 V14b.jar
\EnderIO-1.7.10-2.2.8.381.jar
++\ExtraCells-1.7.10-2.3.10b190.jar
\ExtraTiC-1.7.10-1.4.5.jar
\extrautilities-1.2.5.jar
\Galacticraft-Planets-1.7-3.0.12.454.jar
\GalacticraftCore-1.7-3.0.12.454.jar
\growthcraft-2.2.2-complete.jar
\IC2NuclearControl-2.1.2a.jar
\iChunUtil-4.2.2.jar
\IguanaTinkerTweaks-1.7.10-2.1.5.jar
\industrialcraft-2-2.2.821-experimental.jar
\Invasion_1.1.2_1.7.10.jar
\InventoryTweaks-1.58-147.jar
\ironchest-1.7.10-6.0.62.742-universal.jar
\legacyjavafixer-1.0.jar
\Lots of Food-1.7.10 v7.jar
\malisiscore-1.7.10-0.14.3.jar
\malisisdoors-1.7.10-1.13.2.jar
\Mantle-1.7.10-0.3.2.jar
++\Mekanism-1.7.10-9.0.2.271.jar
++\MekanismGenerators-1.7.10-9.0.2.271.jar
++\MekanismTools-1.7.10-9.0.2.271.jar
\MicdoodleCore-1.7-3.0.12.454.jar
\MineFactoryReloaded-[1.7.10]2.8.1-174.jar
\MoreChisels-1.7.10-1.0-20.jar
\MrCrayfishFurnitureModv3.4.7(1.7.10).jar
\natura-1.7.10-2.2.0.1.jar
\NetherOres-[1.7.10]2.3.1-22.jar
\NotEnoughItems-1.7.10-1.0.5.110-universal.jar
\OpenBlocks-1.7.10-1.3.jar
\OpenModsLib-1.7.10-0.6.jar
\OpenModularTurrets-1.7.10-2.2.2-217.jar
\Pam's HarvestCraft 1.7.10h.jar
\ProjectRed-1.7.10-4.6.1.80-Base.jar
\ProjectRed-1.7.10-4.6.1.80-Compat.jar
\ProjectRed-1.7.10-4.6.1.80-Integration.jar
\ProjectRed-1.7.10-4.6.1.80-Lighting.jar
\RedstoneArsenal-[1.7.10]1.1.2-92.jar
++\RotaryCraft 1.7.10 V14b.jar
\supercraftingframe-1.7.10.2.jar
\Sync-4.0.0.jar
\TConstruct-1.7.10-1.8.8.jar
\ThermalDynamics-[1.7.10]1.1.0-161.jar
\ThermalExpansion-[1.7.10]4.1.2-240.jar
\ThermalFoundation-[1.7.10]1.2.3-112.jar
\TSteelworks-1.7.10-1.1.1-17.jar
\twilightforest-1.7.10-2.3.7.jar
\Waila-1.5.10_1.7.10.jar
\WailaHarvestability-mc1.7.x-1.1.0.jar
\Xaeros_Minimap_1.8.5.3_Forge_1.7.10.jar
\[1.7.10]Treecapitator-universal-2.0.4.jar
\1.7.10\Baubles-1.7.10-1.0.1.10.jar
\1.7.10\CodeChickenLib-1.7.10-1.1.3.138-universal.jar
\1.7.10\ForgeMultipart-1.7.10-1.1.2.334-universal.jar
\1.7.10\MrTJPCore-1.0.7.14-universal.jar
\1.7.10\[1.7.10]bspkrsCore-universal-6.16.jar
\carpentersblocks\CarpentersBlocksCachedResources.zip
\ic2\EJML-core-0.26.jar

**Comment by radfast** [comment]
It could be any one of these mods causing the issue.

If you can help us to **isolate** the exact problem, then we can look at finding a solution for you.

I will need to see logs covering the period when the RAM consumption increased.  If the logs are so large, it seems like a mod is spamming the log with error messages.

It would also be sensible for you to test a reduced mod list, with Galacticraft, and see if you can figure out which exact minimum combination of mods causes the problem.

To do this, create a test world (don't use your main server world as changing mods will damage it) - so basically rename the `.minecraft/world` folder to `worldsaved` or similar, then start the server and it should give you a new world.

Keep cutting the mod list down, restart the server, take a rocket to a planet, see if the issue still occurs.  Do this over and over, and you can figure out the exact mod / mods causing the problem when combined with Galacticraft.  If you are smart and use a _binary search method_, you should be able to figure it out in 5 or 6 restarts.  (Binary search method means remove exactly half your mods, see if the problem still occurs - if it still occurs, remove another half - if the problem stopped, put back half of the ones you just removed and test again.)

**Comment by themechman** [comment]
Radfast, I will have to low priority this. Ive been in an out of the hospital and ive been told i need "healing time". I will see if i can recreate this, but it may be a while.

**Comment by radfast** [comment]
Sorry to hear that, mate.  Hope you recover well.

Meanwhile, I've identified a possible cause of this - if you have 5 players simultaneously riding in rockets, the Galacticraft server will be running worldgen on their destination (landing site) for all 5 of them.  That could slow things down a little - but not 10GB of RAM worth, it should be not much different from how a multiplayer server behaves when 5 players are exploring unmapped regions of the server.

Still, we can look at improving that in future - Galacticraft can ease off on the world generation rate if there are multiple players in rockets at the same time.

The lag may be caused by some other mod going crazy during worldgen.  With a large modlist, the potential problems due to mod interactions are basically **N squared** where N is the number of mods.

**Comment by themechman** [comment]
@radfast For some odd reason, worldgen speed has always been an issue for my servers. Riding a horse or boat for example usually results in large spikes of cpu usage. I've tried server configurations ranging from dual quad core Xeon's with 48GB and SSD to my old dual core dell laptop. Windows 7 and Server 2012 seemed to run the best.

I've noticed about a 10-20 second lag when changing dims (not just GC ones) regardless of what memory optimization strings I try. Our java expert said move to linux because "eeeew windowz". LOL, but that doesnt really ID the problem.

Tonight's crash seems to indicate another ticking entity problem that is gobbling RAM again. I'm going to remove chunkloaders from dims tonight to see if it continues to chew ram.

**Comment by themechman** [comment]
Ugh, seems I need to have a talk with the AE folks. Now I remember why I needed to chunkload dims.

**Comment by themechman** [comment]
Now that everyone is tired of the world, we are going to try to replicate this problem again by removing all of the GC dims and having the server rebuild them.

**Comment by themechman** [comment]
I'm sorry. I'm going to have to close this issue. I would very much like to get more details, but I cannot get people to commit to do this
