### ISSUE TITLE
Oxygen Collector Using Energy When Full

### ISSUE THREAD

**Issue by Keyarose** [micdoodle8/Galacticraft#2204]
The oxygen collector is once again using energy when it's internal oxygen buffer is full. Looks like the fix for #1789 came undone.

Galacticraft Version 1.7-3.0.12.460

**Comment by Keyarose** [comment]
As well when the oxygen collector receives a redstone signal it's status goes to off but continues to use power and collect oxygen.

**Comment by njord8472** [comment]
Not sure if this helps, but I believe that the change happened between version 3.0.12.430 and 431.
When I use version 430 in Galactic Science modpack, the machines keep the stored energy. 
Using versions 431 and above, the machines gradually lose the stored energy in their buffers.

**Comment by dj3520** [comment]
>oxygen collector receives a redstone signal it's status goes to off but continues to use power and collect oxygen.

Redstone control was disabled in 0cb934b4a97bd1c6550882555284ac0b703dafea to fix #2129 and #2134

**Comment by radfast** [comment]
> Using versions 431 and above, the machines gradually lose the stored energy in their buffers.

This is intended behaviour.

> As well when the oxygen collector receives a redstone signal it's status goes to off but continues to use power and collect oxygen.

Recently fixed the status message, please update to GC version 3.0.12.467 or later.
