### ISSUE TITLE
MoonLander Not spawning

### ISSUE THREAD

**Issue by mangodrew** [micdoodle8/Galacticraft#2205]
Whenever I visit the moon, I am not landing with the lander but with the parachute (like landing on earth). This wouldn't be a problem, but I also am not dropping down with the chest that has my rocket in it. Instead, I keep having to spawn in new rockets to get back to Earth. Wanted to know if anyone else was having this problem and if they fixed it. I am going to try to reinstall the mod to see if it corrects the issue

**Comment by EzerArch** [comment]
Check this in your core.conf:
```
# If this is true, the player will parachute onto the Moon instead - use only in debug situations.
    B:"Disable lander on Moon and other planets"=false
```

**Comment by mangodrew** [comment]
Where do I find that line of code exactly and how would it be best to access/change is? Would notepad be okay?

**Comment by mangodrew** [comment]
Thank you so much! I didn't even think about looking in the .minecraft configs! I had assumed it would have been in the Galacticraft file. Thank you so much!

**Comment by EzerArch** [comment]
:clap: :clap: :clap:

**Comment by dj3520** [comment]
So the actual issue is having this config setting set means no parachest falling. If so I'd suggest editing the title for the sake of clarity.
