### ISSUE TITLE
ResourcePacks for this mod makes problems with liquid's textures in RailCraft tanks

### ISSUE THREAD

**Issue by vadz1999** [micdoodle8/Galacticraft#2206]
I've packed standart mod textures into *.zip and added pack.mcmeta. Here is the problem:
This is BuidCraft oil![2016-06-07_14 11 32](https://cloud.githubusercontent.com/assets/15704718/15855726/cfa4e0fa-2cb9-11e6-9c47-687870c57764.png)
IC2 coolant![2016-06-07_14 11 40](https://cloud.githubusercontent.com/assets/15704718/15855727/cfa9edac-2cb9-11e6-8d1a-9ab9c4fe5d8a.png)
BuildCraft fuel![2016-06-07_14 11 22](https://cloud.githubusercontent.com/assets/15704718/15855728/cfaf7114-2cb9-11e6-87c4-671dbde9fddf.png)
Also same problems with external GalactiCraft resoursepacks i.e. Sphax PureBD addon.

**Comment by EzerArch** [comment]
I believe those are Mekanism dynamic tanks, not Galacticraft, and you are using Sphax resource pack. Probably this is related to this: https://github.com/aidancbrady/Mekanism/issues/3327

**Comment by vadz1999** [comment]
Yeah, i'm using Sphax, tanks are from railcraft, but i'll try this, thx :)

**Comment by radfast** [comment]
This is not a Galacticraft issue - I don't see how Galacticraft is even possibly connected with this **at all**.

The images are showing Railcraft tanks and liquids from various mods, not Galacticraft.

Galacticraft's liquid textures have the exact same layout as water in vanilla Minecraft.

If a resource pack or another mod is not displaying the textures correctly, please raise that as an issue with the author.  Sometimes it's a simple (u, v) issue.
