### ISSUE TITLE
Minecraft crash when dead

### ISSUE THREAD

**Issue by bigrice1018** [micdoodle8/Galacticraft#2209]
minecraft crash when i dead when gc and witchery is install

crash report : http://pastebin.com/9NjCJNpF

**Comment by dj3520** [comment]
You've invoked the [Rite of Prior Incarnation](https://sites.google.com/site/witcherymod/rite-of-prior-incarnation) which is probably failing due to Galacticraft adding oxygen gear. Also you have **way** more mods than just GC and Witchery.

**Comment by bigrice1018** [comment]
yea...
It is fine a the past months, after some mods update and someone report this bug to me......
I test it on a new world and just kill myself to test
So no any ritual is actived

**Comment by radfast** [comment]
This appears to be a bug in Witchery mod.

It has no connection with Galacticraft.  (More explanation)[https://wiki.micdoodle8.com/wiki/Common_Problems#Crash_involving_GCEntityClientPlayerMP]

The post by @dj3520 is incorrect, this has no connection with Galacticraft's oxygen gear.

**Comment by dj3520** [comment]
>I test it on a new world and just kill myself to test
So no any ritual is actived

If this is happening without any ritual, then I can't reproduce this [on my server](http://net.dj3520.net:8000/minecraft/modlist.btm) since I would have noticed the server crashing on any player death.
