### ISSUE TITLE
[Compatibility Bug] Extra Utilities portals not working when Galacticraft installed.

### ISSUE THREAD

**Issue by SnowShock35** [micdoodle8/Galacticraft#2210]
Hello,

I believe I've found a bug with the current release version of Galacticraft and Extra Utilities. 

(Also reported this issue to Extra Utilities, you can see it [here](https://github.com/rwtema/extrautilities/issues/884).)

### Important Information

- Minecraft 1.7.10
- Forge 10.13.4.1614
- MicdoodleCore 3.0.12.375
- Galacticraft Core 3.0.12.375
- Galacticraft Planets 3.0.12.375
- Extra Utilities 1.2.12

### Description

The issue occurs when trying to right click either the Last Millennium or Deep Dark portal from Extra Utilities. I'm unsure why this happens I imagine it probably has something to do with how the right click and teleport to that dimension feature works that's being broken by the two mods. Once galacticraft is removed this issue no longer persists. I tried looking into the config to see if it was perhaps a dimension id conflict but that doesn't appear to be the case.

**Comment by Creeperman8362** [comment]
add playerapi

**Comment by radfast** [comment]
Please RTFM:  https://wiki.micdoodle8.com/wiki/Compatibility#Extra_Utilities

**Comment by SnowShock35** [comment]
Yeah it worked. Although a weird fix for such an issue. Thanks :+1:
