### ISSUE TITLE
insufficient permissions to use /joinrace command

### ISSUE THREAD

**Issue by hobnob11** [micdoodle8/Galacticraft#2214]
Running on 1.7.10 gc version 375, one of the players invited some people to his team and they where unable to use the command to join.

**Comment by dj3520** [comment]
1. Forge only or KCauldron/Thermos server?
2. Suggest updating to [GC v460](https://ci.micdoodle8.com/job/Galacticraft-1.7/) as v375 was made Oct 16, 2015 and there has been a lot of bug fixes since then.

**Comment by hobnob11** [comment]
cannot update to 460 as https://github.com/micdoodle8/Galacticraft/issues/2211 still persists.

**Comment by dj3520** [comment]
>Forge only or KCauldron/Thermos server?

**Comment by xarses** [comment]
Still impacting 1.7-3.0.12.462 on Forge only.

The server admin had to make me an operator before the command would function.

https://wiki.micdoodle8.com/wiki/Commands#Permission_nodes implies that the `permission nodes` only apply to a Bukkit server but they appear to also apply to forge.

**Comment by radfast** [comment]
This is fixed by  2c0249f.
I have also corrected the Wiki.
Thank you very much to @hobnob11 and @xarses for reporting.

**Comment by 1971chevycamaro** [comment]
still not working on 3.0.12.504 need a quick fix

**Comment by Jooosl** [comment]
did anyone fix the issue?
