### ISSUE TITLE
Cant Exit(shift Click) out of the Rocket when landing on my Space Station

### ISSUE THREAD

**Issue by mariodk** [micdoodle8/Galacticraft#2219]
hey i made a little System to go between Space station to many places (with launch controllers): so i dont have to Replace the launch pad each time i go to space
but when i try to exit the rocket after i landed on my space station i cant shift click out of it but i can other dimensions (planets)

im using:
GalacticraftCore-1.7-3.0.12.454 version of galacticraft and i dont see in change log this is fixed for the newer versions

**Comment by dj3520** [comment]
Can confirm with newest GC460. Had to fly to mars to escape (and it was a bit before I was really ready to)

**Comment by mariodk** [comment]
also
if Shift Click + place a Block (on a chest / other machines and stuff like that) it will normaly place the Block and Not open the chest
but on Space Station it will open up that chest/machine/whatever

so i guess Shift click is somehow messed

**Comment by dj3520** [comment]
IIRC radfast is trying to disable all forms of crouching on space stations, though for me it's causing headaches like shift placing blocks (which I do a lot of.) It also messes with anything that requires holding shift, like using the gate duplicator from Buildcraft. The only way around it so far that I've found is that it works when standing on a block, but not in free-fall.

**Comment by radfast** [comment]
You can exit a rocket on a space station (or anywhere else) by using right-click.

It is correct that when in free-fall, sneaking (using LEFT-SHIFT) is currently disabled.  An unwanted side-effect is that when in free-fall you cannot left-shift + right-click to place blocks on blocks which have GUIs.  I am still looking at how best to resolve this.

**Comment by radfast** [comment]
This is fixed from next build (480): you will be able to SHIFT + right-click to place blocks, even when in freefall.  You will also be able to use LEFT-SHIFT to enter and exit rockets, and other vehicles, on Space Stations.

**Comment by dj3520** [comment]
>you will be able to SHIFT + right-click to place blocks

_runs to downloads and ALT+F4 my server for mod update_
