### ISSUE TITLE
1.8 Branch doesn't compile

### ISSUE THREAD

**Issue by pwnage-pineapple** [micdoodle8/Galacticraft#2220]
Error log available here: [http://pastebin.com/yf1RkXRW](http://pastebin.com/yf1RkXRW)

**Comment by 61352151511** [comment]
Why are you trying to manually compile something that obviously isn't done? They don't need to worry about compiling it until they are finished porting it.

**Comment by radfast** [comment]
Thank you for trying it.  It's not intended that non-developers should be compiling the 1.8 branch right now.  We'll announce when it is ready for use.
