### ISSUE TITLE
Items in Galacticraft Inventory not Rendering Correctly

### ISSUE THREAD

**Issue by penelopeyay** [micdoodle8/Galacticraft#2223]
I'm using Galacticraft 3.0.12, although this happened in earlier versions as well. First of all, the oxygen mask, tanks, and gear, along with the frequency module do not show up at all on the player, although they work just fine in gameplay. Also when parachuting back into the overworld, the parachute doesn't appear, although again working just as intended. Lastly, the all pieces of the thermal padding set do appear, but floating a good distance above where they should be.
![2016-06-28_16 00 46](https://cloud.githubusercontent.com/assets/20156256/16432376/e21fa7fe-3d41-11e6-895d-2118759685bf.png)
I should also note that the low-gravity player animations do not work, and the thermal padding moves at a different speed than the rest of the player. And when sleeping in the cryogenic chamber, the player just does the vanilla laying down horizontally animation.

**Comment by EzerArch** [comment]
First, check to see if you have installed mods that change the player model.

Second, search for the solution here: https://wiki.micdoodle8.com/wiki/Compatibility

Third, post the remaining issues you couldn't fix.

**Comment by penelopeyay** [comment]
I only had one mod on that list, More Player Models. I deleted it, but the only problem that was fixed was the floating thermal padding. Everything else still isn't working properly.

**Comment by radfast** [comment]
> I'm using Galacticraft 3.0.12

Which version?  You need to be using the latest version, that's 462 currently.

**Comment by penelopeyay** [comment]
I just updated to 462, and now the low gravity and parachute animations are working, along with the oxygen gear. All that isn't fixed is the cryogenic chamber animation. But now that I updated, many of the Galacticraft textures have changed. This might be because of OptiFine, or just part of the update. Either way, I would like to change them back to how they were before.

**Comment by radfast** [comment]
OK great, so the issues have been fixed

Cryogenic chamber issue seems related to the issue already reported at #2172 and we will work on that, but it's low priority.

I'm not sure what you mean by "many of the Galacticraft textures have changed".  There have been improvements to silicon ore, silicon and some related textures.  If you don't like it, I guess you can edit your copy of the galacticraftcore.jar file, just copy in the old textures which you do like, that should work.  A .jar file can be edited in 7Zip or any other good quality Zip file editor.

**Comment by EzerArch** [comment]
> Cryogenic chamber issue seems related to the issue already reported at #2172.

I think you wanted to mean #2112. :)

**Comment by radfast** [comment]
Actually I meant #2174   :p
