### ISSUE TITLE
Launch controler not working?

### ISSUE THREAD

**Issue by Pizza-man007** [micdoodle8/Galacticraft#2225]
I am not sure I understand the purpose of the launch controller. Is it not to automate the dilivery of resourses to and from the planet's? I set up a two-rocket system where, one rocket brings buckets to mars, the buckets are taken out and filled with fuel that is created there via gas liquifier, then the buckets get loaded into a second rocket that is supposed to take them back to earth and unload them, the buckets are emptied via fluid transposer and then sent to the first rocket again. One the overworld, the first rocket is set to launch when cargo is loaded, and on Mars it is set to launch when cargo is unloaded. The second rocket is opposite, launch when loaded on Mars, and unloaded on earth. I thought this would be all I had to do. The launch controllers would do the launching and the rockets would slowly bring me fuel and look cool in my world. But that doesn't seem to be the case. The first rocket launched from earth okay, but it never came back. I had already been to Mars in that playing session to set all of this up so it's not an issue with the player having to load it before the chunk loader will kick in. What am I doing wrong? Is this not the whole purpose of launch controllers?

**Comment by dj3520** [comment]
>The first rocket launched from earth okay
Meaning that launch controllers are working for you unless you used the launch button on the rocket's GUI.

Instructions on how to use the launch controller can be found on [the wiki page for it](https://wiki.micdoodle8.com/wiki/Launch_Controller).

**Comment by Pizza-man007** [comment]
Yes I read that wiki page when I was trying to trouble shoot. My problem is that it seems to work and as far as I can tell it is set up right. But I left my world running for a few hours and the rocket never came back.

**Comment by radfast** [comment]
Are you using the latest Galacticraft version?

**Comment by Pizza-man007** [comment]
I updated the mod once I started having problems. My pack had an older version. So I have the latest version now. I didn't consider that I might have build it on the borders of chunks....I will go check that. Thanks for that!

**Comment by Pizza-man007** [comment]
okay. that fixed the problem. Its all good. except, it also crashed my game. But, that is probably a modpack issue by the looks of the report. I didn't need the fuel that much anyway. Thanks for your help!

**Comment by radfast** [comment]
Please post the crash report, if it's connected with Galacticraft it may be a bug we should fix.

**Comment by Pizza-man007** [comment]
Crash Report
[crash-2016-07-04_12.47.55-server.txt](https://github.com/micdoodle8/Galacticraft/files/350154/crash-2016-07-04_12.47.55-server.txt)

**Comment by radfast** [comment]
The posted crash report is caused by a RailCraft Anchor.  Not a Galacticraft issue.
