### ISSUE TITLE
Server crash when loading a space station

### ISSUE THREAD

**Issue by mattfreyer** [micdoodle8/Galacticraft#2226]
Server crash when loading a space station with ftb presents the crackpack. http://pastebin.com/gPCJqNBn

**Comment by dj3520** [comment]
GC Version used is 375. Might want to upgrade and try again.

**Comment by mattfreyer** [comment]
Well the problem is this is the new Crackpack pack that FTB just released so i have no way to update it if it is fixed in the new version than I'll report to them instead.

**Comment by radfast** [comment]
When reporting, please tell the Crackpack people that they should **not** be using a 9 month old version of Galacticraft.  They are numpties.  They are also [in breach of the Galacticraft licence](https://wiki.micdoodle8.com/wiki/Modpack_Permission) until they sort this out.
