### ISSUE TITLE
Problem with overworld

### ISSUE THREAD

**Issue by THEJean-Kevin** [micdoodle8/Galacticraft#2229]
Hi,
I would like to begin by apologizing for my english.

So, i create a custom modpack and I set up a server. But sometime, players have the impression of being on a planet in the overworld like a picture 
![2016-07-14_15 28 25](https://cloud.githubusercontent.com/assets/19693105/16841165/3d830b34-49d8-11e6-9148-dc99dc5dea84.png)

normally the overworld is like that.
![2016-07-13_23 27 27](https://cloud.githubusercontent.com/assets/19693105/16841191/5b49d008-49d8-11e6-97b5-947f4d99c937.png)

I use the latest version of galacticraft (GalacticraftCore-1.7-3.0.12.462) and i have multiverse on the server.

if you need more information ask me.

Thank you

**Comment by ktole1999** [comment]
go into your multiverse config and make sure overworld is set for spawn and not moon.

**Comment by radfast** [comment]
Seems like this is a Multiverse / setup issue, not a Galacticraft bug.

Closing now.  Please re-open if it can't be fixed like @ktole1999 explained.
