### ISSUE TITLE
Lang files have a major problem!

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft#2232]
All the entities localised name are not the correct, it seems they are targeting the wrong unlocalised names (Since there is now GalacticraftCore, and GalacticraftMars and that before the name of the entity)
Seems to be a probably on all lang files
![](https://i.gyazo.com/f47a07ee46733ea537a6262a974e8f40.png)

**Comment by EzerArch** [comment]
Outdated version?

![2016-07-17_20 31 43](https://cloud.githubusercontent.com/assets/6743303/16903766/9c2650f6-4c5d-11e6-8681-51283ce8edb7.png)

**Comment by MJRLegends** [comment]
Im using latest build

**Comment by EzerArch** [comment]
> Im using latest build 

Me too. Probably something else is affecting/overriding the entity names. The developer will need a full log of the session when that happened, containing installed mods, environment (SP/MP) and forge version.

**Comment by MJRLegends** [comment]
@EzerArch Dw this isn't a issue it seems my client was messed up as it doesn't do it in my dev version for my mod pack
