### ISSUE TITLE
Freefall on custom spacestations don't work;

### ISSUE THREAD

**Issue by BlesseNtumble** [micdoodle8/Galacticraft#2234]
I think the problem in this check: 

file PlayerClient.java

```
@Override
    public void onLivingUpdatePre(EntityPlayerSP player)
    {
        GCPlayerStatsClient stats = GCPlayerStatsClient.get(player);

        if (player.worldObj.provider instanceof IGalacticraftWorldProvider)
        {
            stats.inFreefallLast = stats.inFreefall;
            stats.inFreefall = FreefallHandler.testFreefall(player);
            if (player.worldObj.provider instanceof WorldProviderOrbit)
            {
                this.downMot2 = stats.downMotionLast;
                stats.downMotionLast = player.motionY;
                ((WorldProviderOrbit) player.worldObj.provider).preVanillaMotion(player);
            }
        }
    }
```

file: GCEntityClientPlayerMP.java and GCPlayerBaseSP.java

```
@Override
    public boolean isSneaking()
    {
        if (this.worldObj.provider instanceof WorldProviderOrbit)
        {
            if (FreefallHandler.testFreefall(this)) return false;
            GCPlayerStatsClient stats = GCPlayerStatsClient.get(this);
            if (stats.inFreefall) return false;
            if (stats.landingTicks > 0) return true;
        }
        return super.isSneaking();
    }
```

```
     if (player.worldObj.provider instanceof WorldProviderOrbit)
```

Most likely because it is impossible to make a free fall at the other stations and all the other planets.

**Comment by radfast** [comment]
This is available in GC4 through extending WorldProviderZeroGravity

Do you still need this in 1.7.10?

**Comment by BlesseNtumble** [comment]
Yes, of course

**Comment by radfast** [comment]
In 1.8.9+ it's now done through implementing `IZeroGDimenion`.

In 1.7.10 it probably already works if you extend WorldProviderOrbit.

I could change that to use IZeroGDimension and FreefallHandler similar to how it is in 1.8.9.

But first I want to check this won't mess anything up for other add-on authors in 1.7.10.

@SteveKunG  @katzenpapst  @MJRLegends your thoughts please?
Maybe @zmaster587 you are interested in this too, I'm not sure how much of Galacticraft's code is relevant to you in 1.7.10 (I know your mod is not dependent at all on Galacticraft from 1.8+)

**Comment by katzenpapst** [comment]
lol, I'm actually waiting for this new zero G dimension stuff to happen in 1.7.10. IMO it will solve more problems than cause.

**Comment by MJRLegends** [comment]
@radfast matching 1.8.9 method of this would be perfect :P

**Comment by radfast** [comment]
ok guys, that makes things fairly clear!

**Comment by MJRLegends** [comment]
In my addon im extending WorldProviderOrbit anyways atm and the WorldProviderOverworldOrbit for 1.8.9 and 1.10.2

**Comment by radfast** [comment]
I've made these changes, see 41d82e3  (ignore the other commit, it is missing two Side.CLIENT annotations).

The ZeroG code is refactored into FreefallHandler.  The freefall motion will be activated (as it is now for Overworld Space Stations) for any WorldProvider implementing ```IZeroGDimension```.  (For some functions it might also need to implement IGalacticraftWorldProvider.)

The Space Station spin code, using Spin Thrusters, is refactored into SpinManager.  This will be activated for any WorldProvider implementing WorldProviderSpaceStation.

WorldProviderSpaceStation also provides a couple of abstract methods for you to implement for easier hooks into SkyProvider creation.  As explained in the Javadoc for WorldProviderSpaceStation, if you **do not** want your space station to spin, then you will need to provide a SpinManager() with methods which do nothing when called.  Or, at minimum, just keep SpinManager.doSpinning = false and SpinManager.skyAngularVelocity = 0.
