### ISSUE TITLE
Server lock up

### ISSUE THREAD

**Issue by Nibbler230** [micdoodle8/Galacticraft#2235]
Hi, I host a small server for just me and my friends. Playing the Space Astronomy pack off the FTB 3rd party launcher.

Well after I placed the galacticraft compressor, the server locked up. By this I mean nothing is happening. it's like an extreme case of lag. I'm looking at the counsel, even typed in a commmand, and no response.
I've restarted the server, and restarted my computer, no simple fix. I have the feeling I'm going to have to world edit that machine out of there unless someone could please give me another solution.

Thank you!

**Comment by radfast** [comment]
Could be an issue with another mod. Please
* raise this with Space Astronomy support
* check Space Astronomy forum
* check that players and server are using the exact same versions of all mods
* use default configs for everything (maybe you changed a config to something which can't work, like a 0 value for something important)

I'm closing this issue for now, as it's a 6 months old issue report, there's not enough info here to find the cause, and I don't think anyone else has this issue: it may not be a Galacticraft issue at all...

Please re-open if it happens again, and provide us with server logs to look at.
