### ISSUE TITLE
 Could not get provider type for dimension -29, does not exist

### ISSUE THREAD

**Issue by Cyb3RGER** [micdoodle8/Galacticraft#2236]
This error happens when i launch a rocket (tier 2 in this case). For some reason it seems to can't get the dimension provider for the mars. But i acctually was on the mars before on this save. Some ideas how to fix? May be an known bug? This may be some incompatibily with some other mods. I saw the same issue  with an GalaxySpace Planet but it was never fixed because it was invalid.

This error first appeared when had ChickenChunks installed. I tried Dimensional Anchors and Railcraft but it still crashed. However I removed these two and mystcraft but the error keeps appearing (but I added some other mods that should not interfere) . I use version 3.0.12.446 for 1.7.10 because i can't download the latest version, so please let me if it got fixed it later versions. There should be no DimID confilcts.

Crash report:
[crash-2016-07-25_14.27.15-server.txt](https://github.com/micdoodle8/Galacticraft/files/381507/crash-2016-07-25_14.27.15-server.txt)

Sorry for my bad english :D

**Comment by Cyb3RGER** [comment]
After some testing i can say its either applied energistics2 or ae2stuff that creates this crash.

If someone want to look into this.
Mc ver:1.7.10
AE ver:2 rv3 beta 6
Ae2stuff ver: rv3 0.5.1.3
MicdoodleCore,GalacticraftCore,GalacticPlanets ver. : 3.0.12.446
GalaxyCraft ver. :1.0.8Stable

By the way this bug effects all dimension from Galacticraft and its addons.

Would be nice if this can get fixed for modpacks.

**Comment by BlesseNtumble** [comment]
Conflict ID dimensions.

**Comment by radfast** [comment]
This is a **GalaxySpace** issue, not Galacticraft.  -29 is not a standard Galacticraft dimension.

Like @BlesseNtumble said, it seems to be a dimension ID conflict, so you need to figure out which mod or mods want to use dimension -29, and set their configs properly.

**Comment by radfast** [comment]
See also #1962 with an example of a dimension ID conflict being reported in the log

**Comment by radfast** [comment]
In some cases these dimension ID conflict issues are caused by AE2's **Spatial Storage Cells**.  AE2 creates a new dimension for _every new storage cell_.  There may be a way to configure it to switch that off or to control which dimensions AE2 is allowed to use, but I am not an AE2 expert.
