### ISSUE TITLE
[WorldEdit] Using WorldEdit to move space station arrival block causes exception ticking world

### ISSUE THREAD

**Issue by MeSoLost** [micdoodle8/Galacticraft#2239]
It refuses to let me upload the ZIP i made with the logs in it.  I've found a fatal crashing glitch that occurs if you move the reception pad even 1 block!  This generates an exception ticking world crash and spams the console with 5+ pages of (see below) when you attempt to start/restart the server.

at micdoodle8.mods.galacticraft.core.blocks.BlockMulti.func_149712_f(BlockMulti.java:185)
at micdoodle8.mods.galacticraft.core.blocks.BlockMulti.func_149712_f(BlockMulti.java:193)
at micdoodle8.mods.galacticraft.core.blocks.BlockMulti.func_149712_f(BlockMulti.java:193)

After doing a detailed thrace through the logs it was found that DIM_SPACESTATION2 had been the initial failure and I had used world edit to move the reception pad (all 3 blocks of it) down 1 block to be even with the prefab floor.  This error is easily repeatable.  The fix for it until a patch can be made is to remove or rename the space station folder.  Upon relaunch all if fine but as soon as you visit the station you will crash again but this appears to be ok because if you simply kick the server back on you will find the reception pad and half of the reception bay are back and you can continue rebuilding.  The back half of the reception bay and the landing/launching pad are not regenerated.

I'm on your forum now as MeSoLost.  You may message me and I'll send all the logs you want.

**Comment by radfast** [comment]
I _think_ this should be fixed from next build 3.0.12.472

If that doesn't fix it then I'm not really willing to do more here.  It is not intended that crucial block positions in Galacticraft are moved around by WorldEdit.
