### ISSUE TITLE
Is this normal behavior? All GC and ExtraPlanets are loaded all the time.

### ISSUE THREAD

**Issue by SteelShot** [micdoodle8/Galacticraft#2240]
So I have installed GC + Extra Planets to my server, and ran the tps command after a good while on a new world, and noticed that all GC and EP dimensions are loaded all the time, is this normal behavior?

I have not used GC in years in my main stream server, so i am not sure of some new features existing, or is this Extra Planets behavior? Sorry if this is a duplicate issue.

GC Version is build #460 which is marked Stable, EP version 1.0-Pre 3.6.4

Screenshot of "/forge tps" command: <a href="http://imgur.com/t3E2Z6X"><img src="http://i.imgur.com/t3E2Z6X.png" title="Uploaded by MyImgur.eden.fm" alt="" /></a>

If you need more information, mods list ect. I'll provide it

**Comment by EzerArch** [comment]
Well, I'm not sure if it's the normal behavior, but I can tell from the screenshot the Nether (DIM -1) is also "loaded".

**Comment by dj3520** [comment]
I don't think it's normal, but I'm not sure if they're loaded just from
seeing them in /forge tps. I know that the bukkit form of Essentials can
show how many chunks are loaded. I don't know a forge only way to show that
info.

**Comment by SteelShot** [comment]
I have looked at "/chunkloaders" command and looking at the moon dimension for example show no chunks being forced or loaded

<a href="http://imgur.com/bjGW61a"><img src="http://i.imgur.com/bjGW61a.png" title="Uploaded by MyImgur.eden.fm" alt="" /></a>

**Comment by SteelShot** [comment]
Even Opis is saying that theres nothing there but they are still loaded... 

<a href="http://imgur.com/huY1v0W"><img src="http://i.imgur.com/huY1v0W.png" title="Uploaded by MyImgur.eden.fm" alt="" /></a>

**Comment by dj3520** [comment]
The fact that they show up means they're registered, but not necessarily loaded (0 chunks loaded.)

Check under `IDs to load at startup, and keep loaded until server stops` in `/config/Galacticraft/core.conf`

**Comment by SteelShot** [comment]
Thats empty, its just normally at least when, i get to a dimension and leave it, its says unloading dimension x. As long as their not causing lag, guess there's nothing bag happening,

`# IDs to load at startup, and keep loaded until server stops. Can be added via /gckeeploaded
    I:"Static Loaded Dimensions" <
     >`

**Comment by radfast** [comment]
[RTFM](https://wiki.micdoodle8.com/wiki/Tutorials/Space_Station_for_Server_Admins#Guide_to_Galacticraft_dimensions_and_commands)
