### ISSUE TITLE
Crash when try going to overworld without any players

### ISSUE THREAD

**Issue by Krysinski** [micdoodle8/Galacticraft#2243]
Client crash when try going to overworld without any players.
Overwold dimension is set to 11 ("idDimensionOverworld"). Also i add 11 to "Static Loaded Dimensions" but this not help.
crash report:
https://drive.google.com/open?id=0B3rROac4Sbv4ZUp1MzhXeUZtUVE

**Comment by Krysinski** [comment]
I downgrade thermos version to 55 and no crashes anymore.

**Comment by Krysinski** [comment]
It crashes when i try to going from moon (or other planets) to overwold (perhabs overworld dim 11 unloaded from memory)
crashreport: http://pastebin.com/byC5rJmq

**Comment by radfast** [comment]
Looks like this is fixed, thank you @tyra314
