### ISSUE TITLE
No bosses in dungeons after world wipe

### ISSUE THREAD

**Issue by vadimyer** [micdoodle8/Galacticraft#2245]
GC version: 3.0.12.460
Server: Thermos B55.

The problem is: after server wipe (full wipe of world folder), but with previous level.dat file (deleted RandomSeed from it, so it became zero), moon/mars dungeons don't have bosses. And thus people can't open chests from there. Is there any way to fix that?

**Comment by radfast** [comment]
Is this still a problem?  I'm guessing not, as this is from August 2016.

I think anyone wiping the world folder but keeping `level.dat` file and manually editing it, can expect strange results.... !
