### ISSUE TITLE
download broken somehow

### ISSUE THREAD

**Issue by plaguewolf** [micdoodle8/Galacticraft#2246]
ive downloaded GalacticraftCore-1.7-3.0.12.463.jar about a dozen times and each time it fails (byte error) at ~7.5 MB
even went so far as to use wget with completion, but then the archive was currupt.

wget complains: Connection closed at byte xxx

**Comment by plaguewolf** [comment]
my latest attempts to download, screen shotted, to illustrate my point.
![fail](https://cloud.githubusercontent.com/assets/7838485/17457170/427ad4ac-5bb5-11e6-8b89-3788fa3990e3.jpg)

**Comment by Krysinski** [comment]
i download it without errors, try this link https://drive.google.com/folderview?id=0B3rROac4Sbv4VkRldjUzeDFsRkE&usp=sharing

**Comment by plaguewolf** [comment]
hey, thanks. for some reason whatever host McDoodle is using is forcibly closing connections on me.
