### ISSUE TITLE
Player dies of suffocation in a wall if he falls from a SS riding non-rocket vehicle

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#2247]
To reproduce it, you can use a boat, a moon buggy or a [MCHeli vehicle](http://ezerarch.com/mcheli.html#MMU).

Daredevil with a boat:
![2016-08-07_19 24 50](https://cloud.githubusercontent.com/assets/6743303/17465667/cf492558-5cd4-11e6-85b6-f966dff54681.png)

Falling:
![2016-08-07_19 24 57](https://cloud.githubusercontent.com/assets/6743303/17465668/cf4bb2aa-5cd4-11e6-8478-eeed17b86b00.png)

 Once I spawn in the OW I start getting hurt:
![2016-08-07_19 25 02](https://cloud.githubusercontent.com/assets/6743303/17465669/cf4c9986-5cd4-11e6-9769-cd0c1632eca7.png)
![2016-08-07_19 25 17](https://cloud.githubusercontent.com/assets/6743303/17465671/cf4fb120-5cd4-11e6-8db3-93c70c8d75e5.png)

Until I die of suffocation in a wall:
![2016-08-07_19 28 46](https://cloud.githubusercontent.com/assets/6743303/17465686/3086e030-5cd5-11e6-83a7-6a02c5a6c078.png)

And when I respawn, I'm stuck in the parachute state. I can't jump and the parachute sound effect keeps playing. **To fix it**, I have to reload the world:
![2016-08-07_19 25 39](https://cloud.githubusercontent.com/assets/6743303/17465670/cf4fa874-5cd4-11e6-85eb-7b54530a5e52.png)

If you fall with a moon buggy, you don't get suffocation but you fall through below the bedrock ad infinitum. Reloading the world made me reappear underground. Lucky me, I respawned in a ravine located at the same x-coord, y=30, z-coord I fell from in SS dim. I could've respawned in a solid landmass.
![2016-08-07_19 35 32](https://cloud.githubusercontent.com/assets/6743303/17465789/f2042b5e-5cd6-11e6-86fc-d9b5d5e75f81.png)

**Comment by radfast** [comment]
Fixed next build 480.

Now:
* the player will not die of suffocation
* the player will dismount from the entity and the player will fall as normal, with a parachute if equipped
* the ridden entity will be spawned high in the sky above the Overworld (10 blocks below the player's position, so if you look down you will see it)
* what happens to the ridden entity then will depend on its own regular physics ... if it's a horse or pig, it will fall and die ~~~ if it's a boat it will fall and smash into wood ~~~ if it's a minecart it will fall intact ~~~ if it's from MCHeli I don't know ? :/

**Comment by EzerArch** [comment]
> if it's from MCHeli I don't know ? :/

They'll explode if they don't fall leveled with the ground.

Out of curiosity: say a vehicle/entity falls off the SS alone with no rider, what will happen? Is it going to re-entry like drops (space debris from [wiki](https://wiki.micdoodle8.com/wiki/Overworld#Galacticraft_Features))?

(Off-topic: The https://wiki.micdoodle8.com/wiki/2 link seems to redirect to the wrong page/section)

**Comment by radfast** [comment]
> Out of curiosity: say a vehicle/entity falls off the SS alone with no rider, what will happen? Is it going to re-entry like drops?

Yes I think so - it wil fall to the Overworld with (I think) the same x, z that it had on the Space Station, so probably close to (0, 64, 0).  Maybe try it with a chicken or something else which does not take fall damage?

----

That wiki link I don't remember now what was planned, I can see that /1 and /2 both redirect to the same location.  I guess maybe it was planned for there to be 2 getting started tutorials in future, a basic one and a more advanced space-focused one, which can be /1 and /2.  If anyone ever writes it, we can change the redirect :)
