### ISSUE TITLE
NEI Mob Overlay Doesn't Work On Moon

### ISSUE THREAD

**Issue by natedogith1** [micdoodle8/Galacticraft#2248]
The NEI mob overlay (F7) doesn't work on the moon (untested on other planets).  I believe this has something to do with mobs being provided by the moon's chunk provider (which the client doesn't have access to), and no mobs being provided by the moon biome (which the client has access to).
TheCBProject/NotEnoughItems#10

**Comment by radfast** [comment]
Fixed from next build 3.0.12.472
