### ISSUE TITLE
GC sun texture.

### ISSUE THREAD

**Issue by Yurigirl** [micdoodle8/Galacticraft#2251]
Attempting to make a resource pack for GC but I can't seem to change the Sun texture for GC dims. I see in SkyProviderMoon.java that the Sun texture called is ResourceLocation("textures/environment/sun.png"); Am I correct that is calling the Vanilla sun texture? because of this, it's not possible to change the sun texture on the moon separately from the overworld.
Could I possibly request support for editing the other dimensions' suns?

**Comment by EzerArch** [comment]
> Am I correct that is calling the Vanilla sun texture?

Yes.

> Could I possibly request support for editing the other dimensions' suns?

No. Just kidding. :p

In fact, I asked something like this: https://forum.micdoodle8.com/index.php?threads/airless-dimensions-should-use-the-space-station-sun-graphic.5523/
