### ISSUE TITLE
Galacticraft core block

### ISSUE THREAD

**Issue by Techtronik** [micdoodle8/Galacticraft#2254]
I'm posting this here after i had posted it in the issue tracker for Aroma1997's Dimensional World as there are some "galacticraft core" blocks generated in the chunk that i didn't see anywhere else in that mining world and seem to be isolated to the world gen bug that affected that chunk. Maybe it involves some sort of interaction with the two mods.

You can find the issue i open for Aroma1997 here: https://bitbucket.org/Aroma1997/miningworld/issues/88/world-gen-bug

**Comment by radfast** [comment]
Looking at the Aroma1997 issue report, it was something connected with the **Chance Cubes** mod, which turns some chunks upside down when generating them.

Not a Galacticraft issue.

(It would have been nice to close this issue at the same time as closing the Aroma1997 issue.)
