### ISSUE TITLE
Moon Buggy moved by Gravity Gun causes ArithmeticException: / by zero

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#2256]
This is a very specific bug.

I normally use [Gravity Gun](http://ichun.me/mods/gravity-gun/) to move blocks, entities and vehicles of any mod. But when it comes to GC Buggy, the Gravity Gun crashes the game with ticking entity for division by zero at on attempting to move the Buggy.

![2016-08-25_22 12 51](https://cloud.githubusercontent.com/assets/6743303/17990997/38a4042e-6b11-11e6-89f8-dfbc976b40c6.png)
Crash:
```
Description: Ticking entity
java.lang.ArithmeticException: / by zero
at micdoodle8.mods.galacticraft.core.entities.EntityBuggy.func_70071_h_(EntityBuggy.java:443)
```
Log: https://gist.github.com/EzerArch/9692378e4fdf44e5fc9ef49442effd20

And now the world crashes every time I try to open it. I had to use MCEdit to remove the Buggy.

Log (non-GC): https://gist.github.com/EzerArch/3e7df8da0b079aac5c62ecf5a065dd4a

**Comment by radfast** [comment]
I don't know about the world crash (looks a non-GC error, but possibly because the world crashed previously, when you were in the middle of using the Gravity Gun)

But I fixed the / by zero error.  This should be fixed in next build 472
