### ISSUE TITLE
Rocket Dupe *Server Breaking*

### ISSUE THREAD

**Issue by SportsFan10** [micdoodle8/Galacticraft#2257]
Forge: 10.13.4.1614
Galacticraft: 1.7-3.0.12.462
Galaxy Space: 1.1.0 Stable

I'm running a fairly heavily modded modpack on my server. (90 mods or so)  
The issue I'm having is that if there is a Galacticraft moon lander on the moon and it is not broke after landing the following occurs:
If everyone on the server disconnects and there are Rockets on the launch pads on the moon, the server will create tons and tons of Rockets of the same type.  
This video should explain things a bit better: https://youtu.be/3Rl6Js55U-4

If you would like me to test anything else let me know,
-Nick

**Comment by SportsFan10** [comment]
After further testing it seems that it actually has something to do with the oxygen sealer.

**Comment by EzerArch** [comment]
Dang! Too bad I barely know Java. I'm forwarding this issue.

**Comment by SportsFan10** [comment]
Actually after further testing I believe it has something to do with the oxygen sealer.  I had a base set up with one while recording this.  Just as a test I delted the lander from the server and let it sit over night.  When I came back on to check, the server was still lagging "X" amount of ms behind.  There was no lander on the server anywhere.  When I removed the oxygen sealer and let it sit for a couple hours there were no messages saying the server was lagging.  Sorry about the poor info before.  

Thanks for the quick reply,
-Nick Killeen

**Comment by EzerArch** [comment]
I suspect this is also related to #2249.

**Comment by SportsFan10** [comment]
It seems like that could be the case, are you using the same version of Galacticraft I was?

**Comment by EzerArch** [comment]
Using Galacticraft 1.7-3.0.12.463.

**Comment by SportsFan10** [comment]
Yeah just to confirm again, the sealer has been removed for a couple days now and have had no issues.  I'll enable the debug log in the config and then place the sealer back down.  I'll post any information I gather.

**Comment by SportsFan10** [comment]
Thanks for the reply; not sure if the sealer needs to be on the space station or anywhere.  In my video it's on the moon and was failing to seal the area.  EzerArch was your sealer in the status "Sealed". Or "Area to big". My area was to big.  Perhaps I should test a sealed environment?

**Comment by Robijnvogel** [comment]
I tried it with both an oxygen sealer at the space station (0, 64, 0).
And with an oxygen sealer on the moon (random coordinates).
In neither case was I able to reproduce your issue.

I was using [this](http://pastebin.com/iQENaUAP) client modpack, in which low or zero gravity doesn't seem to work btw. The server was not running Fastcraft or client sided mods (doh).

**Comment by SportsFan10** [comment]
The problems is, I'm also facing inconsistencies while testing.  As of right now, there is no Sealer on the server and I'm still getting these issues where the server is running 100,000 ms behind.  The rocket dupes aren't happening anymore either.  Initially I though all the individual rocket entities as items on the ground were causing lag.  Now there are not any rockets to even cause lag and I'm still getting the lag messages.

**Comment by SportsFan10** [comment]
Can now confirm it is not the Sealer causing issues.  I'm doing another test over night.  I'm at the pint now where I believe this is not a Galacticraft issue.  On the server I had a quantum link chamber from AE2.  I'm using a really outdated version of AE2 and didn't realize that until now.  I got rid of the link chamber I had on the moon and I'm going to see what happens.  Hopefully the link chamber was the cause as I was reading through some of the AE2 change logs and one of them stated something about fixing a server side memory leak.  Perhaps that's the culprit.

**Comment by SportsFan10** [comment]
Sorry for the false information and assuming this was a Galacticraft issue.  I've updated to the latest stable version of AE2 and have had no issues since.  The server has been running perfect.  Sealer working fine, no rocket dupes.  I was using a very old version of AE2 which had some memory leak problems on servers.  I'm assuming this was the cause as I've had no problems since.
