### ISSUE TITLE
Rocket can't land on or launch from OSS

### ISSUE THREAD

**Issue by UbiPangolin** [micdoodle8/Galacticraft#2259]
Hi there!
I have finally decided to give the Overworld Space Station a go and I was sad to see that I cannot take off from a launch pad with a launch controller. I cannot also land on the pad as the rocket explodes upon touch down. 
Is this a known issue that I missed in here? If so, is there any plan to fix it or I just have to do without it?
Thanks for your time and help!

**Comment by radfast** [comment]
Did you say which version, @UbiPangolin ?

**Comment by UbiPangolin** [comment]
Hello, I tried on both 463 and 465. I am using 463 at the moment but I also did a quick check when 465 was released. To give you a bit more of context, this was on a single player mode and I tried both Survival and Creative.

**Comment by radfast** [comment]
Hello, pleased you are still here :)
I will have to look at this, I've been away from the mod for many months and I can't remember whether this is a known issue or not.

**Comment by EzerArch** [comment]
Just a guess: isn't it because the TPS drops so much that rocket becomes unresponsive? Referent to: https://github.com/micdoodle8/Galacticraft/issues/2249#issuecomment-241280382.

**Comment by UbiPangolin** [comment]
Unfortunately no :). It happens on a fresh savegame with a tick time around 4-5ms.

**Comment by EzerArch** [comment]
Could you post screenshots of Launch Controllers' setup, origin and destination -- I mean, the dialog box.

**Comment by radfast** [comment]
I've tried 10 launches on Space Stations.  All take-offs and landings seemed OK.

I also tried it with a rotating Space Station (using spin thrusters) and the rockets still found their way correctly to the landing pads.

One weird thing I noticed: a Launch Controller is not a sealable block!  I'll be looking into that.

Question: were your launch and destination pads on the same space station?  Or are you trying to fly from the Overworld to space and back?

**Comment by UbiPangolin** [comment]
Hey sorry for the late reply!
I haven't had much chance this week to look at the issue and reproduce it for you. I will try to do it tomorrow.
Sorry again about that...

**Comment by radfast** [comment]
Hey!  Sounds great, any help you can give with reproducing this greatly appreciated.
Screenshots of your pads, your launch controllers, etc could help.
Can you also post a full log from startup to when this issue happens.  `'logs/fml-client-latest.log`
You can upload the log to a Gist (click Gist link at top of screen) or to Pastebin or anywhere else you prefer.

**Comment by UbiPangolin** [comment]
Alright, you can indeed mark it as "can't reproduce". I have tried it today with a fresh savegame, a simple space station with side thrusters and a launch pad and it all worked as expected. I don't know, maybe I got it wrong with the version number :(. Sorry for the time wasted on this one...

**Comment by EzerArch** [comment]
> Sorry for the time wasted on this one...

No need to be sorry. Sometimes 'blems happen. :)

**Comment by radfast** [comment]
No worries at all, UbiPangolin.  While testing all these launches on OSS, I spotted some visual things we can improve in future, so it's all good.
