### ISSUE TITLE
Downloads not downloading

### ISSUE THREAD

**Issue by Chock500** [micdoodle8/Galacticraft#2261]
When I clicked to download the mod/s, it redirected me to a page with ads, which said that the file is being downloaded, and it wasn't. I had to use inspect element to get the link. Please fix so that others who are experiencing this issue can download the mod.

**Comment by EzerArch** [comment]
It's working again, as expected: https://forum.micdoodle8.com/index.php?threads/i-cant-download-galacticraft-what-to-do.3736/
