### ISSUE TITLE
Galacticraft download, forums, and wiki all offline.

### ISSUE THREAD

**Issue by KingOfMiners** [micdoodle8/Galacticraft#2265]

**Comment by dj3520** [comment]
Main site is `OK`

Downloads page reads `SQLSTATE[HY000] [1040] Too many connections`

Forum reads `An unexpected database error occurred. Please try again later.`

Meanwhile [Jenkins is fine, download from there for now.](https://ci.micdoodle8.com/job/Galacticraft-1.7/)

**Comment by EzerArch** [comment]
I've sent @micdoodle8 a message yesterday about the issue, but as usual, he takes about 1 week to ever read and reply.

**Comment by KingOfMiners** [comment]
Ok.

**Comment by EzerArch** [comment]
@KingOfMiners did you get the message I sent you?

**Comment by C1ffisme** [comment]
Everything seems to work now...
