### ISSUE TITLE
new duplication bug

### ISSUE THREAD

**Issue by runescapejon** [micdoodle8/Galacticraft#2267]
Hello, I'm currently having a problem with MineFactory Reload and Galacticraft. The slimling and a slimling bag and but the items in the slimlings inventory. Then get a safari launcher and a safari net (Reusable) and capture it then spawn more with the auto-spawner containing more of the item. Thats how its duped.

will this be fix soon?

**Comment by Gohu29** [comment]
You can blacklist this mob in config Mine Factory reload, for block spawning in auto-spawner.

**Comment by Gohu29** [comment]
`        # A list of entity IDs (e.g.: CaveSpider or VillagerGolem or Forestry.butterflyGE) to blacklist from the AutoSpawner. The Debugger item will display an entity's ID when used.
        S:Blacklist <
            VillagerGolem
         >`

**Comment by runescapejon** [comment]
ohhhh thanks!
