### ISSUE TITLE
Y axis locked in space station

### ISSUE THREAD

**Issue by Hauteknits** [micdoodle8/Galacticraft#2268]
I am unable to move in the overworld spacestation unless I am in creative and flying, i have tried thrusters and nothing works. Walking off the space station and going up or down still leaves you stuck. Crash Report: [http://pastebin.com/4JjX0U2K](url) (Crash was triggered using F3+C)

**Comment by Hauteknits** [comment]
The moon is the only other planet ive traveled to and gravity works fine

**Comment by micdoodle8** [comment]
Can you test in a new world with just Galacticraft installed? You can use /dimensiontp in creative to quickly test it. 

I suspect another mod is interfering with player movement.

**Comment by radfast** [comment]
This is intended behaviour, currently - not a bug.  It is possible to move around, it's just challenging and different from what you are used to.  I think **space** is supposed to be like that.

For the future - as noted on the wiki - we are looking at some small changes to make some things easier, like steps are currently an issue.
