### ISSUE TITLE
Rockets launched via Launch Controller cannot be 100% re-fueled

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#2269]
Once you launched a rocket via Launch Controller with "Launch when: Fully fueled", it can no longer be fully fueled, its fuel tank gets stuck at "99.0% full".

**To reproduce:**
1. Set up a launch base with a Fuel Loader (with fuel) and Launch Controller with "Launch when: Fully fueled" and a target.
   ![2016-09-11_21 39 19](https://cloud.githubusercontent.com/assets/6743303/18421808/b2b2889e-7868-11e6-9a1d-804054039389.png)
   ![2016-09-11_21 39 26](https://cloud.githubusercontent.com/assets/6743303/18421809/b2b2adec-7868-11e6-9aaa-da05ce25f602.png)
2. Place a rocket and let it be fueled. When it gets 100% fueled it will launch.
   ![2016-09-11_21 34 03](https://cloud.githubusercontent.com/assets/6743303/18421823/ef3f2128-7868-11e6-9007-bf06b94ed937.png)
3. The rockets arrives at its target launch base, which is also equipped with a Fuel Loader (with fuel) and Launch Controller with "Launch when: Fully fueled" and a target back home.
   ![2016-09-11_21 41 41](https://cloud.githubusercontent.com/assets/6743303/18421834/308167f4-7869-11e6-97bc-99191e3a5557.png)
   ![2016-09-11_21 48 19](https://cloud.githubusercontent.com/assets/6743303/18421853/814268dc-7869-11e6-8f45-886d5ea00ed2.png)
4. Touch down. The rocket starts being re-fueled.
   ![2016-09-11_21 41 50](https://cloud.githubusercontent.com/assets/6743303/18421836/38bb446c-7869-11e6-91b5-4dfb4c8c94f2.png)
5. Gets stuck at "99.0% full". You can break the rocket and put it back, you can use the rocket in another base the Fuel Loader can't load it up to 100%, you can break the Fuel Loader and the Launch Controller and put them back. It won't help.
   ![2016-09-11_21 49 08](https://cloud.githubusercontent.com/assets/6743303/18421858/972ae75a-7869-11e6-9ad6-2b505f82903c.png)

EDIT: Except the Tier 2 rocket worked, at least once!

EDIT2: Nevermind, the tier 2 rocket worked once and then glitched after the 2nd launch.

**Comment by radfast** [comment]
Thank you.  A fix for this should be included in next 1.7.10 build 472.
