### ISSUE TITLE
Wrong landing coordinates on Asteroids

### ISSUE THREAD

**Issue by SkyFire55** [micdoodle8/Galacticraft#2271]
I have the same problem as here [ #2054 ](https://github.com/micdoodle8/Galacticraft/issues/2054), but my problem is not connected with any plugins or mods.

First 5-6 flights after world generation I don't have any problems, but later landing coordinates on Asteroids become huge.  I removed all mods and plugins from server, and installed latest GC version, and found the same problem. This problem doesn't let me use WorldBorder, coz after landing it teleports players at the 0-coords without their landing pod. Sometimes server extremely lagging after landing.

Server core - Thermos 1.7.10 1614, and any GC version shows me the same bug. Problem connected only with Asteroids.

[logs.txt](https://github.com/micdoodle8/Galacticraft/files/476546/logs.txt)

**Comment by cpypcy** [comment]
Same here also on 1.7.10

**Comment by radfast** [comment]
Thank you for reporting, and sorry for slow response (I have been away for several months)

Please can you:

1.  Try the same setup using a basic Forge server, not Thermos

2.  Do your testing using a fixed world seed, and tell me the world seed so I can test the same one

3.  Provide a copy of this file `GCAsteroidData.dat` - it's in the `data` folder in your world save folder

**Comment by radfast** [comment]
There's a good chance this is fixed by  	a6c19fa  in build 489+ of Galacticraft 3
(and in build 72+ of Galacticraft 4).

If it's still a problem after this, please comment or re-open.  And please provide the requested information ^^^^^^^^^^^^^^^^^^

**Comment by repo-alt** [comment]
The issue definitely still there in version 3.0.12.502 with Thermos. Unfortunately I don't have access to server logs & data. Will open the issue at the modpack github with a reference here.
![aster](https://user-images.githubusercontent.com/23512002/32779235-fd86fa12-c94d-11e7-81e8-ff1cc1a1d498.png)

**Comment by Dream-Master** [comment]
@radfast any idea about the issue we have?
