### ISSUE TITLE
An information about Galacticraft

### ISSUE THREAD

**Issue by Araton10** [micdoodle8/Galacticraft#2273]
Hello guys, this ticket is definitely **not for to rush you**, but only for informational purposes, since I would be thinking of a new Modpack, I would like to know if it is planned to develop GalactiCraft for 1.10.2

Thank You

Sorry for my Bad English

**Comment by EzerArch** [comment]
We have 1.8 and 1.9 ports in progress, but nothing planned for 1.10 yet.

**Comment by gug2** [comment]
@EzerArch    I can help you with 1.10 developing

**Comment by EzerArch** [comment]
GC source code is open. Just fork, start coding, and if you get something done, push request.

**Comment by gug2** [comment]
okay, thanks
