### ISSUE TITLE
Aroma backup crashes client

### ISSUE THREAD

**Issue by NastyCanasta** [micdoodle8/Galacticraft#2275]
On the 1.7.10 pack, the Aroma Backup has a 50/50 chance to crash my client. It's a "clean" crash that puts me back at the launcher. If I crash hosting an LAN, only my client shuts down. Reliable sources told me that this problem involved something with Galacticraft. Here's the crash log! 

http://pastebin.com/wEB4jxJX

**Comment by micdoodle8** [comment]
Thanks. This is fixed in the master branch, which is currently compiling on Minecraft 1.8.9.

I will likely port back to 1.7.10 sometime soon.
