### ISSUE TITLE
compressed metal plates

### ISSUE THREAD

**Issue by themechman** [micdoodle8/Galacticraft#2276]
I know this might seem like a game breaker for some, but I'd like a configurable option to permit compressed steel plates for example to be made in an IC2 exp Compressor or Mekanism Osmium Compressor.

**Comment by dj3520** [comment]
Please read [the contribution guidelines](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md#what-else-is-not-ok-on-the-issues-list) as feature requests are not issues.
