### ISSUE TITLE
Sensor Glasses and GT Compatibility

### ISSUE THREAD

**Issue by JasonMcRay** [micdoodle8/Galacticraft#2279]
Hey. Me again with another GregTech related compatibility issue.
it is probably going to be somewhat similiar to #2215

Sensor glasses - they have config in which I can specify ores that the Glasses will recognize and show them. Problem comes, yes you guessed it, with GregTech ores. If I set gregtech ore in the config, it does nothing, doesnt work. I don't want to make the glasses show all GT ores, since the veins are massive and it would be just useless.

I am looking for being able to specify so called Small Ores, which comes in much smaller ratios (kinda as regular minecraft ore would).

Gregtech ores comes under `gregtech:gt.blockores` and something else as well, but I don't remember the internal name, will check wheni get home and update this, entry and of course they are all Tile Entities.

it is not big issue, but it makes the glasses kinda useless in GregTech modpacks :)

So you know... when you have time or feel little bored :)

**Comment by radfast** [comment]
Hey Jason.  This is too hard for us to do.  From Galacticraft's perspective, all GT ores look similar and we don't have a way to know which is a large ore vein and which is a small ore vein.

Maybe something for an add-on?  Our code is open source, and we have provided an API function to let other mods tell Galacticraft exactly which of their blocks should show up on the Sensor Glasses.  See [here](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/api/block/IDetectableResource.java) - although this may be hard to implement in GT as it probably needs an (x, y, z, dimension) value for the block location as well.

See also [here](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/tick/TickHandlerClient.java#L400-403)

**Comment by radfast** [comment]
I will close this, as I see this as too hard for us to do.  If someone making a GT/GC compatibility module wants to look at this and see what can be done, I'm sure we will accept any reasonable pull request.  Meaning, anything which works, doesn't break other stuff, and has no impact on players not using GT. :)
