### ISSUE TITLE
Help for finding "holes" in room you want to seal

### ISSUE THREAD

**Issue by Johnnybenice** [micdoodle8/Galacticraft#2280]
Hi, i would like to make a suggestion for finding holes when using a Oxygen Sealer in a supposed closed/sealed room. 
Could you add a **whisping sound** and some **particles simulating the air escaping** at the given spot where the air escapes? Not only would it be a cool realistic effect, but also a great help in finding those spots (and also realising which blocktypes are not working for sealing purposes).
I don't know how the algorithm behind the room-size scanning process works, but i'm guessing that implementing those features wouldn't be too complicated.

**Comment by dj3520** [comment]
Please read the guidelines. https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md
