### ISSUE TITLE
OpenComputer integration

### ISSUE THREAD

**Issue by Nex4rius** [micdoodle8/Galacticraft#2283]
Could you add a function of checking wether or not the area is sealed to the oxygen sealer or the oxygen detector so we can access that with a computer?

**Comment by dj3520** [comment]
I believe this is already being worked on. IMO you won't need to have access to the detector since it already outputs redstone.

**Comment by Nex4rius** [comment]
Using the redstone signal just makes everything more complicated.
I think the detector should be directly linked with a computer instead of having to deal with the redstone signals inbetween.

**Comment by dj3520** [comment]
What would you gain from a simple true/false variable in an API? You can already get that from redstone. The detector isn't complicated enough to warrant adding API support.

Also the issue tracker isn't for suggestions. Please read https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md

**Comment by radfast** [comment]
See #2169.
