### ISSUE TITLE
Bugs Galacticraft 4

### ISSUE THREAD

**Issue by gug2** [micdoodle8/Galacticraft#2286]
**Villager trading**
When trading with a Moon Villager,  his suggestions are "copied" 
https://www.youtube.com/watch?v=0TbIqYzoSCc

**Bug with astrominer base**
![2016-10-14_10 52 59](https://cloud.githubusercontent.com/assets/19577359/19379823/aa429aa2-91fc-11e6-9b8b-c9c471271011.png)

**ItemRenderer Astrominer**
![2016-10-14_10 53 05](https://cloud.githubusercontent.com/assets/19577359/19379835/c051f72a-91fc-11e6-8859-d6b5ee129190.png)

**Frequence module not render**
![2016-10-15_11 19 50](https://cloud.githubusercontent.com/assets/19577359/19408569/529d14ee-92c9-11e6-8f1a-7962896c8539.png)
![2016-10-15_11 15 08](https://cloud.githubusercontent.com/assets/19577359/19408572/5a82dbf8-92c9-11e6-81c7-68c1497ca9c7.png)

**Oxygen mask  wrong render, when player is on LSHIFT**
![2016-10-15_11 15 15](https://cloud.githubusercontent.com/assets/19577359/19408578/a1add6a4-92c9-11e6-9ef7-7544308f3c3a.png)

**Comment by Nicrisild22** [comment]
I tested GalactiCraft 4, when I put the rocket on the platform, then the game crashes.

**Comment by micdoodle8** [comment]
@gug2 Thanks, I'll take a look

@Nicrisild22 That's a separate issue, please open a new issue in the tracker. I also need a crash log to solve the problem.

**Comment by gug2** [comment]
Update 1st post

**Comment by BlesseNtumble** [comment]
![1](http://images.vfl.ru/ii/1480571338/64dc5678/15165360.png)
![2](http://images.vfl.ru/ii/1480571341/e4347d5a/15165361.png)

**Comment by micdoodle8** [comment]
Now that the issues in 1.8.9 are slowing down a bit, please create separate issues instead of combining them in one report. Thanks.
