### ISSUE TITLE
[1.8.9] Galacticraft 4 API

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft#2288]
Is the API usable for Galacticraft 4  @micdoodle8 @radfast or is it not ready for developing addons yet? 
As i seem to be getting errors with it in a dev workspace

**Comment by gug2** [comment]
probably API still not ready

**Comment by micdoodle8** [comment]
That API is usable, but will likely be changed to some degree before release. The 1.8.9 API files are in the main repo (this repo), and will be moved back to the separate repo soon.

**Comment by MJRLegends** [comment]
I was getting errors with the api then in that case and they were due to methods/variables changes in 1.8.9
