### ISSUE TITLE
Crash on placing tier 3 rocket [1.8]

### ISSUE THREAD

**Issue by willtree8** [micdoodle8/Galacticraft#2291]
Hi, My game crashes when placing any tier 3 rocket (no other tiers make it crash). I am using the 1.8.9 beta test from the forum. Galacticraft and forge are the only things installed. Crash report: http://pastebin.com/7x6AWZAP. Also the tier 2 rocket seems to be missing a model: http://imgur.com/gallery/9UmDI

Hope you can help and get this fixed! 👍 :)

**Comment by dj3520** [comment]
The tier 2 rocket has a missing model an the tier 3 one crashes when trying to be rendered.
