### ISSUE TITLE
Moon Dungeon generation bug

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#2297]
![2559-10-21_20 15 18](https://cloud.githubusercontent.com/assets/6128413/19599517/4af20e46-97cb-11e6-830e-7269865ead7e.png)

All info in the picture. Testing in Dev environment (Eclipse).

**Comment by KingOfMiners** [comment]
I also noticed this when I was testing out the 1.8 version of Galacticraft, It kept crashing my game until it stopped generating the dungeon and It looked like that.

**Comment by RurouniTim** [comment]
I can also confirm this error. After crashing, I found a similar dungeon, but mine wasn't connected by corridors. Mine had the same dimensions as vanilla dungeons without any hallways. The chests all contained vanilla dungeon loot. When looking at the purple error blocks, f3 told me they were MOON_BOSS_SPAWNERs.

![2016-10-22_08 49 43](https://cloud.githubusercontent.com/assets/23000287/19620540/a14f614e-9834-11e6-8890-79e4aafc8891.png)

**Comment by RurouniTim** [comment]
I just wanted to leave out a similar issue that's also occurred on Mars.

![2016-10-22_09 08 34](https://cloud.githubusercontent.com/assets/23000287/19620689/416d7fa6-9837-11e6-89e1-c50fe22ceadd.png)

**Comment by gug2** [comment]
This bug with dundge on all planets

**Comment by micdoodle8** [comment]
Fixed in the latest build
