### ISSUE TITLE
(1.8.9 Build 30) Rendering issue at certain Y levels

### ISSUE THREAD

**Issue by RurouniTim** [micdoodle8/Galacticraft#2298]
at Y=61, y=47, y=31, and y=15, a rendering glitch occurs if you're surrounded by blocks on the y level above you. I've tried testing this out without galacticraft just to see if maybe it was a forge issue, but that doesn't seem to be the case.

![2016-10-21_23 03 57](https://cloud.githubusercontent.com/assets/23000287/19620409/9e3c1b4e-9831-11e6-9d97-93c7ca265a33.png)
![2016-10-22_08 28 13](https://cloud.githubusercontent.com/assets/23000287/19620410/a2711fb6-9831-11e6-98a9-ff24c0ae3ca4.png)

**Comment by SteveKunG** [comment]
Same here.

**Comment by wlich** [comment]
hi

**Comment by micdoodle8** [comment]
Good catch, thank you. I've found the source, the fix will be included in the next build.
