### ISSUE TITLE
Ambient Thermal Controller not working.

### ISSUE THREAD

**Issue by tethlah** [micdoodle8/Galacticraft#2307]
Every dim with GC that I've gone to, no matter the size of the room, the thermal controller doesn't seem to be working with the oxygen sealers.  Everything else with sealing the room works fine, but players are still getting thermal damage.

**Comment by tethlah** [comment]
This is 1.7.10 most recent stable release fyi

**Comment by dj3520** [comment]
>This is 1.7.10 most recent stable release

To confirm, this is `1.7-3.0.12.463` yes?

**Comment by tethlah** [comment]
No, is't 3.0.12.375, I must have been confused, the website made it sound like the red one's were not stable.

**Comment by tethlah** [comment]
And it looks like the only place it works is the moon, every other GC dim it doesn't work in.

**Comment by dj3520** [comment]
From what I've seen said before, the newest version is considered the most stable due to having the most fixes behind it. I'm not sure why the website has a "recommended stable" link. I'd suggest upgrading and seeing if the problem persists.

>the only place it works is the moon

The moon doesn't require thermal padding.

**Comment by tethlah** [comment]
This is on a production server, not sure if I want to go up to a build that's not proven to be the most stable.

**Comment by dj3520** [comment]
463 was released August 2nd while 375 was released Oct 16th, 2015. I'd imagine there's a lot of improvements since then, including stability and crash fixes. If you're not confident in the reliability I suggest testing it out locally in singleplayer. 

As radfast said in #2221 `The red are the recommended versions.`

**Comment by tethlah** [comment]
Yeah, the official download page is confusing on that one.  Usually the colour red is not associated with being the best option to choose (especially when the page says green is the one to go with).

**Comment by dj3520** [comment]
I agree. At any rate, you should see if this issue persists with the newest build.

**Comment by micdoodle8** [comment]
I'm going to assume this issue did not persist with the newest build based on the last few messages and the lack of response.
