### ISSUE TITLE
Still some problem using Smart Moving with Galacticraft (1.7.10)

### ISSUE THREAD

**Issue by lllMohandarlll** [micdoodle8/Galacticraft#2309]
Hello, I've read some precedent issue with smart moving + galacticraft such as this one; https://github.com/micdoodle8/Galacticraft/issues/441
where micdoodle said it was fixed for the latest developers versions.

Actually with only galacticraft installed (no matter if .375 or .463) I've encountered a weird behavior with smart moving + player api and render api.

When you try to crawl in a hole all it's fine, but when you switch the camera on third person,  then it glitch, and you remain stuck in the hole, cannot move anywhere again, is like your character return to be 2-blocks-tall, and when you break the block underneath you can move again.
From that moment the world you've created remain bugged and you can't even crawl in any hole again :/

**Comment by EzerArch** [comment]
The problem is, since the build 439, the mod always thinks the player head is 1 block up, no matter the situation. I've got stuck in caves and tight passages because of this bug.

Details: https://github.com/micdoodle8/Galacticraft/issues/2158#issuecomment-199101413

**Comment by lllMohandarlll** [comment]
Well, that's what I noticed too :/ is there something that can be done to workaround it?

**Comment by Kerai** [comment]
I added a pull request, but until the official build with the said fix is released, you can use [this unofficial build](https://cdn.keray.eu/mc/1.7.10/mods/GalacticraftCore-1.7-3.0.12.0.jar) that I made for my server

**Comment by EzerArch** [comment]
*applauses* 👏

**Comment by Brycey92** [comment]
@micdoodle8 shouldn't this have the fixed tag?

**Comment by radfast** [comment]
Fixed by #2388 thanks to @Kerai
