### ISSUE TITLE
Can't Sneak In Space Station

### ISSUE THREAD

**Issue by CrazyPyroEagle** [micdoodle8/Galacticraft#2314]
Attempting to sneak when on the ground inside a space station will cause the player to alternate between sneaking and not sneaking.

Expected: The player sneaks when attempting to sneak.

* Minecraft Coder Pack (9.05)
* Minecraft Forge (10.13.4.1614)
* Forge Mod Loader (7.10.99.99)
* Micdoodle8 Core (3.0.12.375)
* Galacticraft Core (3.0.12.375)
* Galacticraft Planets (3.0.12.375)
* Player API (1.4)
* Render Player API (1.4)

Note: SmartRender does not fix this.
Note 2: This does not appear to be a graphical issue, as interactions that require sneaking sometimes fail on the space station.

**Comment by EzerArch** [comment]
> Micdoodle8 Core (3.0.12.375)
Galacticraft Core (3.0.12.375)
Galacticraft Planets (3.0.12.375)

Did you try to update to 463? You are using an over-1-year old release.

**Comment by CrazyPyroEagle** [comment]
That fixed it, but why exactly is the recommended build over a year old?

**Comment by dj3520** [comment]
The "recommended" versions are misleading. As radfast said in #2221 `The red are the recommended versions.`
