### ISSUE TITLE
[1.8.9 - Build 32] Fluid pipe can't connect to hydrogen/methane inputs/outputs

### ISSUE THREAD

**Issue by vistaero** [micdoodle8/Galacticraft#2315]
Hi, sorry bad english. I noticed that the oxygen pipe is now called fluid pipe, so I supposed that it could be used for connecting the water electrolyzer, with the methane synthesizer, and that one with the gas liquefier, instead of using pipes of other mods, but it doesn't.

It's intended or it's a bug? thanks!

**Comment by micdoodle8** [comment]
Thanks, that should be all of them fixed.
