### ISSUE TITLE
[1.8.9 - Build 32] There's no hydrogen canister

### ISSUE THREAD

**Issue by vistaero** [micdoodle8/Galacticraft#2316]
I can't fill empty canisters with hydrogen of the water electrolyzer. I also can't find the item in the creative menu.

**Comment by xarses** [comment]
This issue is also in 1.7-3.0.12.462

**Comment by radfast** [comment]
Canisters are for liquids, not gases.  You would need to use a Gas Liquefier to fill a Canister.  [You are supposed to pipe the hydrogen](https://wiki.micdoodle8.com/wiki/Gases#Hydrogen) out of the Water Electrolyzer, or use it in another mod.

Galacticraft does not currently have Liquid Hydrogen.  That's such a low temperature, and volatile and hard to handle, liquid, that we think it should not be made in the standard Gas Liquefier and it should not be stored in the standard Canister.  This may be changed in future but probably not until Galacticraft has reached the outer planets of the Solar System where Liquid Hydrogen can be found naturally occurring (Galacticraft 5?)
