### ISSUE TITLE
[1.8.9 - Build 32] Black/Violet textures

### ISSUE THREAD

**Issue by vistaero** [micdoodle8/Galacticraft#2317]
Black/violet squares textures:

- Particles of wires and heavy wires.
- The block in the center of space stations.
- Particles of breaking astro miner base.

**Comment by dj3520** [comment]
Like so?
![image](https://cloud.githubusercontent.com/assets/8284194/20027151/3956bc50-a2e2-11e6-85db-a68c16c35a91.png)
This means there's no texture.

**Comment by EzerArch** [comment]
Probably it's a pretty simple bug, just a guess, the texture name in the code doesn't match the actual png file name.
