### ISSUE TITLE
Coal generator with hopper

### ISSUE THREAD

**Issue by AndiLeni** [micdoodle8/Galacticraft#2321]
The coal generator is not taking any items from a connected hopper.

**Comment by dj3520** [comment]
Is this 1.7.10 or 1.8.9?

**Comment by AndiLeni** [comment]
1.7.10
I'm sorry. Forgot to add this piece of information.
By the way, I use Craften Terminal for mods.

**Comment by dj3520** [comment]
>I use Craften Terminal for mods.

Although this may be convenient, you're relying on that service to keep the most recent version of all of the mods available on their servers. I also wouldn't be surprised if they're stepping on User Agreement policies as well.

I've tested with the newest version of Galacticraft (463) and haven't been able to reproduce your issue.

**Comment by AndiLeni** [comment]
You are absolutely right.
I am not playing MC very often. And it is very comfortable to have so many opportunities in one application.
I'll install the newest version of Galacticraft manually later. Just to see if the bug appears only when I use craften terminal.

**Comment by radfast** [comment]
The coal generator only accepts items from a hopper **above** it.

**Comment by dj3520** [comment]
@radfast Don't want to say you're wrong, but in my testing it accepts coal from hoppers on all sides, though I didn't test inserting from the bottom (tested with _only_ Galacticraft.)

**Comment by EzerArch** [comment]
> but in my testing it accepts coal from hoppers on all sides, 

Confirmed.

**Comment by radfast** [comment]
I'm wondering if this is actually a manifestation of #2344, which is now fixed?

Anyhow, seems like nobody has been able to reproduce this problem in testing, so I will close this now.  If it's still an issue, please re-open and please provide screenshots to help to understand your hopper setup.

**Comment by dj3520** [comment]
@radfast more than likely just a bug that was fixed a while ago but @AndiLeni was using a very old version.
