### ISSUE TITLE
galacticraft 1.6.4

### ISSUE THREAD

**Issue by ddoommiinniicc** [micdoodle8/Galacticraft#2322]
i ALWAYS get the error, galacticraft core not found, i will try to re download it

**Comment by ddoommiinniicc** [comment]
and again is the crazy error

**Comment by ddoommiinniicc** [comment]
SSSSSSSSTTTTTTTTIIIIIIILLLLLLLL that STUPID AND UNNECCESARY ERROR

**Comment by ddoommiinniicc** [comment]
WHAT!

**Comment by ddoommiinniicc** [comment]
![screen shot 2016-11-26 at 13 58 38](https://cloud.githubusercontent.com/assets/23610113/20638363/7dc893cc-b3e0-11e6-9529-6ed0df1ed2bc.png)





this is SO WIERD

**Comment by ddoommiinniicc** [comment]
![screen shot 2016-11-26 at 13 59 51](https://cloud.githubusercontent.com/assets/23610113/20638369/9fd3254a-b3e0-11e6-80b8-bd319a027a3e.png) does not HAVE THIS

**Comment by EzerArch** [comment]
Yes, spamming everyone's inboxes will help you out faster.

**FFS, edit your post instead!**

**Comment by dj3520** [comment]
@ddoommiinniicc Not everyone is constantly checking their email/notifications, so instant replies are not a thing. This isn't a chat room and you shouldn't treat it as such. Also, like @EzerArch has said, multiple posts that don't include new information are a waste of time for everyone involved and makes you look bad.

Please make sure you have GalacticraftCore and it's version number matches. If this continues please upload your ForgeModLoader-client-0.log to [Gist](https://gist.github.com/),  [PasteBin](http://pastebin.com/) or [paste.ubuntu.com](http://paste.ubuntu.com/) and post a link to it here. **Do not directly post the contents here.**

Additionally, include what version of forge you're using and a list of all installed mods.

**Comment by ddoommiinniicc** [comment]
ok

**Comment by ddoommiinniicc** [comment]
mabye it is because i have used galacticraftcore for 1.7.10 and my 'puter is used to having it on
