### ISSUE TITLE
Uranus crashing server

### ISSUE THREAD

**Issue by BlackenedHeaven** [micdoodle8/Galacticraft#2324]
hey guys so the issue im having on my Project Ozone 2 server is that when ever someone goes to generate terrain on Uranus it will crash my server. This has happened twice now both when there were two people on Uranus moving in different directions and with only one person flying trying to find the dungeon. Im running the most recent version of both the modpack and the mod it self. 

Here is a link to my crash file: https://www.dropbox.com/s/uyfo9opogmdr9uv/crash-2016-11-29_06.04.37-server.txt?dl=0

**Comment by EzerArch** [comment]
```
at com.mjr.**extraplanets**.worldGen.features.WorldGenIgloo.func_76484_a(WorldGenIgloo.java:91)
at com.mjr.extraplanets.planets.Uranus.worldgen.BiomeDecoratorUranus.decorate (BiomeDecoratorUranus.java:90)
```

Have you tried contacting ExtraPlanets' developer?

**Comment by micdoodle8** [comment]
Nothing I can do about this, sorry. As Ezer said the addon developer might be able to help you out.
