### ISSUE TITLE
[1.8.9 Suggestion] A way to add custom Torch and Chest

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#2325]
Because the new dungeon system I can't find a way to add my custom Torch and Chest into new dungeon system. Could you make it possible?

**Comment by BlesseNtumble** [comment]
To submit an writing of the torches in chunkprovider method specified rooms.

**Comment by micdoodle8** [comment]
You mean overwrite the torches in the moon/mars dungeons, or add your own torch and chest into your own custom dungeons?

**Comment by BlesseNtumble** [comment]
Most likely generate your torches in your dungeon

**Comment by SteveKunG** [comment]
Yes, just like that. In my opinion should be add method to custom things in dungeon.

Example : 
setChestBlock and setChestTile
setGlowstone
setTorch
addRandomMob into spawner

**Comment by BlesseNtumble** [comment]
Now all this can be replaced, but it should be done directly in the rooms generate files.
It would be nice if it was possible to specify all in chunkprovider file your planet/moon.

**Comment by micdoodle8** [comment]
You know you can create your own MapGenDungeon and pieces with as much customization as you'd like, you don't have to call the Galacticraft core ones. Every addon creator would require different changes to the base dungeon, so this isn't something that is easily extensible.
