### ISSUE TITLE
[1.8.9][build 36] Not correct ItemRenderer Cargo rocket, 2 and 3 level rockets

### ISSUE THREAD

**Issue by gug2** [micdoodle8/Galacticraft#2327]
![2016-12-04_13 05 32](https://cloud.githubusercontent.com/assets/19577359/20865117/84fbe9c6-ba22-11e6-8ba3-61b97c6f97a9.png)
![2016-12-04_13 05 34](https://cloud.githubusercontent.com/assets/19577359/20865119/8519d094-ba22-11e6-92f2-9bee273b0512.png)
![2016-12-04_13 05 38](https://cloud.githubusercontent.com/assets/19577359/20865118/8515f42e-ba22-11e6-863a-6be7d05c5d86.png)

**Comment by jlxip** [comment]
Wtf
