### ISSUE TITLE
[1.8.9] Walkway model - UV lock texture

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#2331]
![2559-12-05_00 00 07](https://cloud.githubusercontent.com/assets/6128413/20869324/8f8f01fe-baa2-11e6-8e18-ec30a53a9540.png)
![2559-12-05_00 00 08](https://cloud.githubusercontent.com/assets/6128413/20869325/8f91e838-baa2-11e6-962b-9eb682e39566.png)

Using DEV (Eclipse) environment for testing.

**Comment by micdoodle8** [comment]
What's the issue I'm looking at? Is is it the blue and red circled areas aren't the same?

![walkway](http://i.imgur.com/6nOBk0W.png)

**Comment by SteveKunG** [comment]
Yes, its look similar to vanilla issue. Model needs uv-lock tag.
https://bugs.mojang.com/browse/MC-49656
