### ISSUE TITLE
[1.8.9] Uncraftable Compressed Metals, Skewed Texture

### ISSUE THREAD

**Issue by OfSticks** [micdoodle8/Galacticraft#2334]
Hey, beta testing the 1.8.9 4.0.0.36 can't seem to find any way to compress tin, copper, or aluminum (tried on both compression machines, machines work with other materials, ex; desh) and I discovered that the default texture for the electric compressor is skewed making the power port side appear on the incorrect face. Oh and the coal generator no longer supports charcoal however the compressor still does (if the obj was to remove charcoal compatibility).

**Comment by micdoodle8** [comment]
Thanks, all fixed :)
