### ISSUE TITLE
Disable oxygen collector in the TARDIS

### ISSUE THREAD

**Issue by Shurik1236** [micdoodle8/Galacticraft#2336]
Сборщик кислорода работает в измерениях TARDIS как на Земле. Можно ли его заставить требовать листву? Ладно там можно дышать без маски, но собирать кислород уже слишком.
Я вот про этот мод: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2420176-tardis-mod-updated-to-v0-994-on-25-12-2015
(Google)
Collector oxygen works in dimensions like the TARDIS on Earth. Is it possible to force him to demand the foliage? Okay there it is possible to breathe without a mask, but to collect oxygen too.
I'm here about this mod: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2420176-tardis-mod-updated-to-v0-994-on-25-12-2015

**Comment by micdoodle8** [comment]
Sorry, this should be posted to the Galacticraft forum in the suggestions area.

https://forum.micdoodle8.com/index.php?forums/suggestions.7/
