### ISSUE TITLE
[build 37] Inconsistent Treasure Generation

### ISSUE THREAD

**Issue by gug2** [micdoodle8/Galacticraft#2339]
![2016-12-08_13 37 44](https://cloud.githubusercontent.com/assets/19577359/21004806/a9a6452e-bd4b-11e6-9a65-b714d3328ad4.png)

**Comment by micdoodle8** [comment]
Killing the boss should generate loot in the nearest chest, did you kill the boss?

**Comment by gug2** [comment]
I kill the boss

**Comment by gug2** [comment]
Now loot spawned..
It works through time
![2016-12-09_17 16 13](https://cloud.githubusercontent.com/assets/19577359/21050287/393456c6-be33-11e6-9862-bf2b67ecb231.png)

**Comment by micdoodle8** [comment]
So you didn't kill it again? You just logged out and in at least once, and it appeared?

**Comment by gug2** [comment]
Now, I find new dungeon
