### ISSUE TITLE
[1.8.9] (Build 37) Missing Recipes

### ISSUE THREAD

**Issue by OfSticks** [micdoodle8/Galacticraft#2340]
-Air Lock Controller cannot currently be crafted. (however functions well)
-Sticky Desh Pick cannot be crafted.

-Flag cannot be placed, icon does not update. (I figure it'll be a while until that feature is back up)
-No reason to take off my helmet. (suggestions) :P
🚀

**Comment by micdoodle8** [comment]
Are you holding down right-click to place the flag?

**Comment by OfSticks** [comment]
Oh I see, there just is no flag planting animation any longer, threw me off, one more thing I just noticed is that placed parachests have to texture and render as clear.

**Comment by micdoodle8** [comment]
There should be a flag planting animation as of build 33 I believe, is it not working for you?

**Comment by micdoodle8** [comment]
Air lock controller recipe is fixed now, and will be included in the next build.

The sticky desh pickaxe never had a recipe, see the wiki for more information on that.

Thanks for testing :)
