### ISSUE TITLE
[1.8.9] Missing filled canister item model

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#2342]
![2559-12-08_17 30 01](https://cloud.githubusercontent.com/assets/6128413/21021140/dd55cdd2-bda9-11e6-8932-81216c211692.png)

**Comment by micdoodle8** [comment]
Do you recall the canister item models displaying correctly at any point in 1.8.9?

**Comment by OfSticks** [comment]
I don't.

**Comment by SteveKunG** [comment]
Maybe a problem in my dev workspace.

**Comment by gug2** [comment]
I have this problem too

**Comment by SteveKunG** [comment]
Fixed.
