### ISSUE TITLE
Coal Generators only accepting coal (item) from hoppers

### ISSUE THREAD

**Issue by altrisi** [micdoodle8/Galacticraft#2344]
As I read, Coal Generators can work with Coal or Coal Blocks. It is working fine, but if you try to use a hopper to send the items, the Coal Generator will only accept the coal as an item, the coal blocks will not enter the machine.

## Other mods: _NotEnoughItems-1.7.10-1.0.5.120_ (with _CodeChickenCore-1.7.10-1.0.7.47_)

**Comment by dj3520** [comment]
@altrisi I'd suggest testing with [the newest version, version 464](https://ci.micdoodle8.com/job/Galacticraft-1.7/464/) since version 375 was born on October 16, 2015, meaning it's probably been fixed by now.

Additionally paging @EzerArch [about this.](https://wiki.micdoodle8.com/wiki/Coal_Generator) `(A Block of Coal lasts 9 times longer than regular coal.)` Not sure if Galacticraft respects this but in vanilla it's burn time is 10x not 9. I would check but I'm currently in the middle of a lot of things at once.

**Comment by altrisi** [comment]
Continue only accepting coal as item, tested in [#464](https://ci.micdoodle8.com/job/Galacticraft-1.7/464/) with the same.
PS: I were using .375 because it is what is marked as "stable" in the [web page](https://micdoodle8.com/mods/galacticraft/downloads). I was going to use [#442](https://ci.micdoodle8.com/job/Galacticraft-1.7/464/) because it is marked as "recommended" in the [wiki](https://wiki.micdoodle8.com/wiki/Whats_New).

Thanks.

**Comment by dj3520** [comment]
@altrisi You can't pipe the items in but you can place them in the GUI? Also the download recommended/stable/newest confusion is apparently not rare, so don't feel bad. As I've heard the newest build is always the "recommended" one to download.

**Comment by altrisi** [comment]
I can place it manually (but not using SHIFT-Click).

**Comment by EzerArch** [comment]
@dj3520:
> Additionally paging @EzerArch about this. (A Block of Coal lasts 9 times longer than regular coal.) Not sure if Galacticraft respects this but in vanilla it's burn time is 10x not 9.

1 block of coal or 9 coal lumps = 337,467 gJ. So GC does not respect the vanilla method. It should in my opinion.

**Comment by dj3520** [comment]
@EzerArch Agreed. I'd imagine it's an easy fix, if desired. That "bonus" by compression is intentional to encourage the player to make blocks. Also it's more fuel in less space. If I put a stack of blocks in, not having that bonus would cause a big difference.

**Comment by micdoodle8** [comment]
Quick note: As of the latest 1.8.9 build 1 block of coal lasts 10x, respecting the vanilla method.

**Comment by dj3520** [comment]
>I never knew before that it was 10x in vanilla

Store more coal in less space and get a bonus coal when burning. The only reasons I go through with making them auto-compress in the first place.
