### ISSUE TITLE
[1.8] API Error with EntityTieredRocket

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft#2355]
Fixed thanks for your help

**Comment by micdoodle8** [comment]
Those methods are implemented in EntityAutoRocket.java

EntityTieredRocket extends EntityAutoRocket, so you should not be getting these errors. Check that EntityAutoRocket matches the file in the main repository.

**Comment by MJRLegends** [comment]
Yeah that's what i thought, and yeah i will check and get back to you.

**Comment by MJRLegends** [comment]
But all im doing is adding the beta jar files as external jars for my api adding of galacticcraft and that works for everything but this

**Comment by MJRLegends** [comment]
@micdoodle8 or do i need to do it like the 1.7.10 way with dev jars, if so do you have a download for them or do i need to build them myself

**Comment by MJRLegends** [comment]
@micdoodle8 I know your busy but is there anyway i can fix this as im really eager to get developing stuff for the 1.8.9 version

**Comment by EzerArch** [comment]
> but is there anyway i can fix

If for 1.7.10, can you fork the [1.7 branch](https://github.com/micdoodle8/Galacticraft/tree/MC1.7), code the fix and submit a pull request (PR) against the the said branch? Once PR is submitted, I can nag mic or rad to give it a look.

The dev environment is only necessary to test in game, but the new code needs to be submitted here to be included in the official releases.

**Comment by MJRLegends** [comment]
@micdoodle8, Sorry to keep bothering you but any idea?
