### ISSUE TITLE
[1.8.9] [Suggestion] Village on the Venus

### ISSUE THREAD

**Issue by gug2** [micdoodle8/Galacticraft#2359]
Suggest add village on the Venus! )

**Comment by EzerArch** [comment]
> The issues list is **not** for:
>     suggestions and feature requests - go to [the suggestions forum](https://forum.micdoodle8.com/index.php?forums/suggestions.7/)

https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md#what-else-is-not-ok-on-the-issues-list
