### ISSUE TITLE
RClick during launch exits rocket with no way to get back in

### ISSUE THREAD

**Issue by ghoulsblade** [micdoodle8/Galacticraft#2361]
I lost a tier3 rocket in multiplayer yesterday, i accidentally rclicked during launch (probably while looking at a nearby capacitor bank), and found myself outside the rocket and it launching without me. I tried to get back into the rocket by rclicking it again while it was still on pad and in the air using jetpack, but that didnt work.

Suggestions:
* Block rclick exit during launch
* allow getting back in with rclicking the rocket from outside
* abort launch wasting some/all fuel
* have the rocket fall back as parachute/chest after it went up alone

possibly relevant mods/versions:
GTNewHorizons Modpack 1.2.0.0
GalacticraftCore-1.7-3.0.12.463.jar
GalacticGreg-1.7.10-0.9.5.jar
Galacticraft-Planets-1.7-3.0.12.463.jar
GalaxySpace-1.1.3 STABLE.jar

**Comment by thehumanslayer12** [comment]
I'll take a look at it.

**Comment by thehumanslayer12** [comment]
I'll take a look at this and see what I can do! Everyone is pretty focused on porting to 1.8.9.

**Comment by radfast** [comment]
Thank you, these are good ideas.  I agree it is unfair if a player loses a Tier3 rocket from an accidental right click.

**Comment by radfast** [comment]
> Suggestions:

    Block rclick exit during launch  _No, players need a way to exit from rockets during launch if they want to (for example maybe they forgot oxygen gear or a parachute)_
    allow getting back in with rclicking the rocket from outside  _This already exists - as long as the rocket is not in flight, you can right-click again to climb back inside_
    abort launch wasting some/all fuel  _You can hit the rocket until it breaks, to abort the launch._
    have the rocket fall back as parachute/chest after it went up alone  _It's intended behaviour that a rocket is lost if it goes up alone, and without a launch controller_

I sympathise with your lost rocket item.

But now that I've checked that GC allows players to re-mount rockets which are still on the launchpad (even if counting down), I don't see there is any issue that needs fixing here.

It is **easy** to re-mount a rocket if it is still on the launchpad, you just r-click again to climb back inside.
If you want to abort a launch, you can hit the rocket until you break it.  (You can even hit a flying rocket, if you have a way to move fast enough to keep up with it...)

**Comment by ghoulsblade** [comment]
> allow getting back in with rclicking the rocket from outside This already exists - as long as the rocket is not in flight, you can right-click again to climb back inside

definitely did not work for me. i tried for several seconds while the countdown was still ticking and could not get back in.
