### ISSUE TITLE
Incomplete download

### ISSUE THREAD

**Issue by oxygencraft125** [micdoodle8/Galacticraft#2374]
I downloaded everything required and the downloads are complete, but it shows a download incomplete
![2017-01-18_181817](https://cloud.githubusercontent.com/assets/21054297/22054694/052d6222-ddab-11e6-883b-dd19e7a68d5c.png)

**Comment by radfast** [comment]
Download it again.  Wait for it to finish the download, before you move it to your Minecraft mods folder.
