### ISSUE TITLE
[1.8.9] Slimeling visual bug

### ISSUE THREAD

**Issue by C1ffisme** [micdoodle8/Galacticraft#2376]
Version: 1.8.9-4.0.0.39

When looking certain entities whilst a slimeling is in view, they appear to change color based on the color of the slimeling:

![2017-01-20_12 29 46](https://cloud.githubusercontent.com/assets/9893266/22161635/ef4c38d6-df10-11e6-9e15-7bdfaa240cbe.png)

Doesn't seem to affect armor:

![2017-01-20_12 30 53](https://cloud.githubusercontent.com/assets/9893266/22161647/fd6aca0e-df10-11e6-9247-27d730f3bd5e.png)
![2017-01-20_12 13 03](https://cloud.githubusercontent.com/assets/9893266/22161655/066143c2-df11-11e6-9b90-dbadd7c62478.png)

(Note that sometimes entities further away will be colored, sometimes both, and sometimes only closer ones:)

![2017-01-20_12 13 26](https://cloud.githubusercontent.com/assets/9893266/22161805/8263a212-df11-11e6-9ad9-6809789444ff.png)
![2017-01-20_12 13 29](https://cloud.githubusercontent.com/assets/9893266/22161829/99bf2f44-df11-11e6-9078-4e781e229fcc.png)

**Comment by dj3520** [comment]
It's a virus!

**Comment by SteveKunG** [comment]
![2560-02-24_16 30 57](https://cloud.githubusercontent.com/assets/6128413/23298075/baa36f46-faae-11e6-88a8-82d5b1b51e50.png)

Can't reproduce in development. I think its fixed.

**Comment by radfast** [comment]
Thank you for reporting.
I fixed this in https://github.com/micdoodle8/Galacticraft/commit/671751e00745afd3586633f6598097fb4ddd6ae3
So this shouldn't be a problem in the latest 1.8.9 beta build.
