### ISSUE TITLE
Fuel pipes

### ISSUE THREAD

**Issue by JanSzumotalski** [micdoodle8/Galacticraft#2380]
How to transport fuel between tanks.
How to fix it @micdoodle8 ?

**Comment by EzerArch** [comment]
In 1.7.10 or 1.8.9 beta?

**Comment by JanSzumotalski** [comment]
In 1.7.10.

**Comment by EzerArch** [comment]
> In 1.7.10.

If you can't use GC pipes, you can use if applied: buckets, canister+hoppers, Mekanism pipes, Buildcraft pipes.

**Comment by dj3520** [comment]
>buckets, canister+hoppers, Mekanism pipes, Buildcraft pipes.

Ender IO conduits, Extra Utilities transfer nodes, etc.
