### ISSUE TITLE
server 2008 runing  forge-1.8.9-11.15.1.1902-1.8.9-universal server errors Galacticraft 1.89

### ISSUE THREAD

**Issue by paulspchelp** [micdoodle8/Galacticraft#2381]
4:34:43 am
 CONSOLE:
WARN Disabling terminal, you're running in an unsupported environment.
4:34:43 am
 CONSOLE:
[FML]: Forge Mod Loader version 11.15.1.1722 for Minecraft 1.8.9 loading
4:34:43 am
 CONSOLE:
[FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_111, running on Windows Server 2008:amd64:6.0, installed at C:\Program Files\Java\jre1.8.0_111
4:34:43 am
 CONSOLE:
[FML]: The coremod micdoodle8.mods.miccore.MicdoodlePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
4:34:43 am
 CONSOLE:
[LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
4:34:43 am
 CONSOLE:
[LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
4:34:43 am
 CONSOLE:
[LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
4:34:43 am
 CONSOLE:
[LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
4:34:43 am
 CONSOLE:
[LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
4:34:45 am
 CONSOLE:
[FML]: FML appears to be missing any signature data. This is not a good thing
4:34:45 am
 CONSOLE:
[LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
4:34:45 am
 CONSOLE:
[LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
4:34:45 am
 CONSOLE:
[STDOUT]: [micdoodle8.mods.miccore.MicdoodlePlugin:getASMTransformerClass:101]: Successfully Registered Transformer
4:34:45 am
 CONSOLE:
[STDOUT]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:294]: [Micdoodle8Core]: Patching game...
4:34:45 am
 CONSOLE:
[STDOUT]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:294]: [Micdoodle8Core]: Patching game...
4:34:45 am
 CONSOLE:
[LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
4:34:46 am
 CONSOLE:
[LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
4:34:46 am
 CONSOLE:
[LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
4:34:46 am
 CONSOLE:
[STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1464]: Galacticraft successfully injected bytecode into: adm (1 / 1)
4:34:46 am
 CONSOLE:
[STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1464]: Galacticraft successfully injected bytecode into: lx (4 / 4)
4:34:46 am
 CONSOLE:
[STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1464]: Galacticraft successfully injected bytecode into: pr (1 / 1)
4:34:46 am
 CONSOLE:
[LaunchWrapper]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
4:34:48 am
 CONSOLE:
[STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1464]: Galacticraft successfully injected bytecode into: uz (1 / 1)
4:34:50 am
 CONSOLE:
[STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1464]: Galacticraft successfully injected bytecode into: wq (1 / 1)
4:34:52 am
 CONSOLE:
[INFO] Starting minecraft server version 1.8.9
4:34:52 am
 CONSOLE:
thread/INFO] [FML]: MinecraftForge v11.15.1.1722 Initialized
4:34:52 am
 CONSOLE:
thread/INFO] [FML]: Replaced 204 ore recipies
4:34:52 am
 CONSOLE:
thread/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
4:34:52 am
 CONSOLE:
thread/INFO] [FML]: Searching D:\games\minecraft\Minecraft\mods for mods
4:34:53 am
 CONSOLE:
thread/INFO] [FML]: Forge Mod Loader has identified 6 mods to load
4:34:53 am
 CONSOLE:
thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, Micdoodlecore, GalacticraftPlanets, GalacticraftCore] at CLIENT
4:34:53 am
 CONSOLE:
thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, Micdoodlecore, GalacticraftPlanets, GalacticraftCore] at SERVER
4:34:54 am
 CONSOLE:
thread/INFO] [FML]: Processing ObjectHolder annotations
4:34:54 am
 CONSOLE:
thread/INFO] [FML]: Found 384 ObjectHolder annotations
4:34:54 am
 CONSOLE:
thread/INFO] [FML]: Identifying ItemStackHolder annotations
4:34:54 am
 CONSOLE:
thread/INFO] [FML]: Found 0 ItemStackHolder annotations
4:34:54 am
 CONSOLE:
thread/INFO] [FML]: Configured a dormant chunk cache size of 0
4:34:54 am
 CONSOLE:
Version Check/INFO] [ForgeVersionCheck]: [Forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
4:34:55 am
 CONSOLE:
Version Check/INFO] [ForgeVersionCheck]: [Forge] Found status: UP_TO_DATE Target: null
4:34:56 am
 CONSOLE:
thread/INFO] [FML]: Applying holder lookups
4:34:56 am
 CONSOLE:
thread/INFO] [FML]: Holder lookups applied
4:34:56 am
 CONSOLE:
thread/INFO] [FML]: Injecting itemstacks
4:34:56 am
 CONSOLE:
thread/INFO] [FML]: Itemstack injection complete
4:34:56 am
 CONSOLE:
[INFO] Loading properties
4:34:56 am
 CONSOLE:
[INFO] Default game type: SURVIVAL
4:34:56 am
 CONSOLE:
[INFO] Generating keypair
4:34:56 am
 CONSOLE:
[INFO] Starting Minecraft server on *:25575
4:34:56 am
 CONSOLE:
[INFO] Using default channel type
4:34:57 am
 CONSOLE:
thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
4:34:57 am
 CONSOLE:
thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
4:34:57 am
 CONSOLE:
thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
4:34:57 am
 CONSOLE:
thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
4:34:57 am
 CONSOLE:
thread/ERROR] [GalacticraftPlanets]: Skipping event FMLInitializationEvent and marking errored mod GalacticraftPlanets since required dependency GalacticraftCore has errored
4:34:57 am
 CONSOLE:
thread/ERROR] [FML]: Fatal errors were detected during the transition from INITIALIZATION to POSTINITIALIZATION. Loading cannot continue
4:34:57 am
 CONSOLE:
thread/ERROR] [FML]:
4:34:57 am
 CONSOLE:
= Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
4:34:57 am
 CONSOLE:
Coder Pack] (minecraft.jar)
4:34:57 am
 CONSOLE:
Mod Loader] (ForgeMod.jar)
4:34:57 am
 CONSOLE:
Forge] (ForgeMod.jar)
4:34:57 am
 CONSOLE:
Core] (minecraft.jar)
4:34:57 am
 CONSOLE:
Core] (GalacticraftCore-1.8.9-4.0.0.39.jar)
4:34:57 am
 CONSOLE:
Planets] (Galacticraft-Planets-1.8.9-4.0.0.39.jar)
4:34:57 am
 CONSOLE:
thread/ERROR] [FML]: The following problems were captured during this phase
4:34:57 am
 CONSOLE:
thread/ERROR] [FML]: Caught exception from GalacticraftCore
4:34:57 am
 CONSOLE:
Source) ~[?:1.8.0_111]
4:34:57 am
 CONSOLE:
Method) ~[?:1.8.0_111]
4:34:57 am
 CONSOLE:
Source) ~[?:1.8.0_111]
4:34:57 am
 CONSOLE:
Source) ~[?:1.8.0_111]
4:34:57 am
 CONSOLE:
Source) ~[?:1.8.0_111]
4:34:57 am
 CONSOLE:
Method) ~[?:1.8.0_111]
4:34:57 am
 CONSOLE:
Source) ~[?:1.8.0_111]
4:34:57 am
 CONSOLE:
Source) ~[?:1.8.0_111]
4:34:57 am
 CONSOLE:
Source) ~[?:1.8.0_111]
4:34:57 am
 CONSOLE:
Method) ~[?:1.8.0_111]
4:34:57 am
 CONSOLE:
Source) ~[?:1.8.0_111]
4:34:57 am
 CONSOLE:
Source) ~[?:1.8.0_111]
4:34:57 am
 CONSOLE:
Source) ~[?:1.8.0_111]
4:34:57 am
 CONSOLE:
Source) [?:1.8.0_111]
4:34:57 am
 CONSOLE:
thread/ERROR]: Encountered an unexpected exception
4:34:57 am
 CONSOLE:
Source) ~[?:1.8.0_111]
4:34:57 am
 CONSOLE:
Method) ~[?:1.8.0_111]
4:34:57 am
 CONSOLE:
Source) ~[?:1.8.0_111]
4:34:57 am
 CONSOLE:
Source) ~[?:1.8.0_111]
4:34:57 am
 CONSOLE:
Source) ~[?:1.8.0_111]
4:34:57 am
 CONSOLE:
Method) ~[?:1.8.0_111]
4:34:57 am
 CONSOLE:
Source) ~[?:1.8.0_111]
4:34:57 am
 CONSOLE:
Source) ~[?:1.8.0_111]
4:34:57 am
 CONSOLE:
Source) ~[?:1.8.0_111]
4:34:57 am
 CONSOLE:
Method) ~[?:1.8.0_111]
4:34:57 am
 CONSOLE:
Source) ~[?:1.8.0_111]
4:34:57 am
 CONSOLE:
Source) ~[?:1.8.0_111]
4:34:57 am
 CONSOLE:
Source) ~[?:1.8.0_111]

**Comment by dj3520** [comment]
I'm not sure how you're grabbing this output, but it's hard to read. Please post the contents of the fml-latest.log to pastebin/gist instead of here as outlined [in the contribution guidelines](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md#posting-new-issues---guidelines) under posting new issues point 5.

**Comment by paulspchelp** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.8.9-4.0.0.39.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 25/01/17 4:34 AM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at java.util.ArrayList.addAll(Unknown Source)
	at micdoodle8.mods.galacticraft.core.GCBlocks.finalizeSort(GCBlocks.java:183)
	at micdoodle8.mods.galacticraft.core.GalacticraftCore.init(GalacticraftCore.java:142)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:737)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:325)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:205)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows Server 2008 (amd64) version 6.0
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 521622432 bytes (497 MB) / 840957952 bytes (802 MB) up to 11453595648 bytes (10923 MB)
	JVM Flags: 1 total; -Xmx12288M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.1722 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (ForgeMod.jar) 
	UCHI	Forge{11.15.1.1722} [Minecraft Forge] (ForgeMod.jar) 
	UCHI	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHE	GalacticraftCore{4.0.0} [Galacticraft Core] (GalacticraftCore-1.8.9-4.0.0.39.jar) 
	UCHE	GalacticraftPlanets{4.0.0} [Galacticraft Planets] (Galacticraft-Planets-1.8.9-4.0.0.39.jar) 
	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.8.9-4.0.0.39.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by SteveKunG** [comment]
GCBlocks.finalizeSort() method is fixed.
https://github.com/micdoodle8/Galacticraft/commit/873d5fecf365ade1d365ba7828496a4c41a4bf60

**Comment by paulspchelp** [comment]
ok  then  how do i get  to work  i have  [Build 39]
GC-CORE JAR
PLANETS JAR
MICDOODLECORE JAR
it crashs

**Comment by dj3520** [comment]
You'll have to wait for a new release with the fix included.
