### ISSUE TITLE
Hi, i got a problem with GCcore

### ISSUE THREAD

**Issue by CiberEye** [micdoodle8/Galacticraft#2383]
I downloaded all the required but when i open the minecraft forge 1.7.10 there is a problem with GCcore.     I tried to open the GCcore but seems to be a problem 
![prob](https://cloud.githubusercontent.com/assets/25349182/22299264/7321b18e-e2f1-11e6-9882-d6f5bbbcc9f3.png)
HELP!!! :(

**Comment by dj3520** [comment]
GCcore isn't an executable jar file because it relies on forge and minecraft, so it not opening when running it by itself is normal. Do you have a log when you tried to use GCcore? If so please post it on pastebin/gist instead of here.

**Comment by radfast** [comment]
https://wiki.micdoodle8.com/wiki/Tutorials/Galacticraft_Installation_Guide
