### ISSUE TITLE
 Crashing on  OxygenDistributor  ver 1.8.9

### ISSUE THREAD

**Issue by paulspchelp** [micdoodle8/Galacticraft#2384]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.8.9-4.0.0.39-BETA.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 1/26/17 3:12 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at micdoodle8.mods.galacticraft.core.tile.TileEntityOxygen.func_73660_a(TileEntityOxygen.java:67)
	at micdoodle8.mods.galacticraft.core.tile.TileEntityOxygenDistributor.func_73660_a(TileEntityOxygenDistributor.java:200)
	at net.minecraft.world.World.func_72939_s(World.java:1718)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at micdoodle8.mods.galacticraft.core.tile.TileEntityOxygen.func_73660_a(TileEntityOxygen.java:67)
	at micdoodle8.mods.galacticraft.core.tile.TileEntityOxygenDistributor.func_73660_a(TileEntityOxygenDistributor.java:200)

-- Block entity being ticked --
Details:
	Name: Air Distributor // micdoodle8.mods.galacticraft.core.tile.TileEntityOxygenDistributor
	Block type: ID #207 (tile.distributor // micdoodle8.mods.galacticraft.core.blocks.BlockOxygenDistributor)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (716,67,536), Chunk: (at 12,4,8 in 44,33; contains blocks 704,0,528 to 719,255,543), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,0,512 to 1023,255,1023)
	Actual block type: ID #207 (tile.distributor // micdoodle8.mods.galacticraft.core.blocks.BlockOxygenDistributor)
	Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1718)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [GCEntityPlayerMP['pauls_lap_top'/101, l='New World', x=715.70, y=67.16, z=535.97]]
	Chunk stats: ServerChunkCache: 736 Drop: 0
	Level seed: -986260937038750028
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: 712.00,64.00,551.00 - World: (712,64,551), Chunk: (at 8,4,7 in 44,34; contains blocks 704,0,544 to 719,255,559), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,0,512 to 1023,255,1023)
	Level time: 523 game time, 523 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 136340 (now: false), thunder time: 119839 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 641072968 bytes (611 MB) / 1912078336 bytes (1823 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.19 Powered by Forge 11.15.1.1902 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1902-1.8.9.jar) 
	UCHIJAAAA	Forge{11.15.1.1902} [Minecraft Forge] (forge-1.8.9-11.15.1.1902-1.8.9.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	GalacticraftCore{4.0.0} [Galacticraft Core] (GalacticraftCore-1.8.9-4.0.0.39-BETA.jar) 
	UCHIJAAAA	GalacticraftPlanets{4.0.0} [Galacticraft Planets] (Galacticraft-Planets-1.8.9-4.0.0.39-BETA.jar) 
	UCHIJAAAA	JEI{2.28.18.186} [Just Enough Items] (jei_1.8.9-2.28.18.186.jar) 
	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.8.9-4.0.0.39-BETA.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [GCEntityPlayerMP['pauls_lap_top'/101, l='New World', x=715.70, y=67.16, z=535.97]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by dj3520** [comment]
@paulspchelp Next time post a full log and **to pastebin/gist instead of here.** Instead include this information here (I took it out of your crash log but it's easier to include it yourself.)

- GalacticraftCore-1.8.9-4.0.0.39-BETA
- forge-1.8.9-11.15.1.1902-1.8.9
- jei_1.8.9-2.28.18.186
- Non-dedicated server

Also I see you're using a very old version of Java (Java Version: 1.8.0_25)
