### ISSUE TITLE
[1.8.9] Oxygen Sealer Ambient Thermal Controller not working

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft#2387]
**Issue mainly for @micdoodle8:**
The Oxygen Sealer Thermal Controller is not working, by this i mean it shows N/A when adding the Ambient Thermal Controller, it should be showing "ON" yet i still dont take thermal damage though. Which makes the use of the thermal thing for Oxygen Sealers not working for 1.8.9. I tested with 1.7.10 and it was working there.....

I found this out when using the function below that is in the OxygenUtil within my addon, and its returning false when i should be getting a true when using the setup that is explained above :P
```
public static boolean isAABBInBreathableAirBlock(World world, AxisAlignedBB bb, boolean testThermal)
    {
        final double avgX = (bb.minX + bb.maxX) / 2.0D;
        final double avgY = (bb.minY + bb.maxY) / 2.0D;
        final double avgZ = (bb.minZ + bb.maxZ) / 2.0D;

        if (testThermal)
        {
            return OxygenUtil.isInOxygenAndThermalBlock(world, bb.contract(0.001D, 0.001D, 0.001D));
        }

        if (OxygenUtil.inOxygenBubble(world, avgX, avgY, avgZ))
        {
            return true;
        }

        return OxygenUtil.isInOxygenBlock(world, bb.contract(0.001D, 0.001D, 0.001D));
    }
```

**Comment by MJRLegends** [comment]
Any idea what is causing this issue @radfast / @micdoodle8

**Comment by radfast** [comment]
I'll look at this the next time I have this code loaded, might be 1-2 days

**Comment by MJRLegends** [comment]
Ok thank you :P

**Comment by MJRLegends** [comment]
Wouldnt commit #b370506 fix this issue?

**Comment by radfast** [comment]
Do you mean b370506?

 :)

**Comment by MJRLegends** [comment]
Yeah haha

**Comment by MJRLegends** [comment]
@radfast / @micdoodle8 Any idea when a new beta build will be released?

**Comment by EzerArch** [comment]
> Any idea when a new beta build will be released?

Buddy, you seem a bit too hasty. How about a Potion of Slowness? :o)

**Comment by MJRLegends** [comment]
@EzerArch Was only asking because i wanted to use some of the new features with my addon and wanted other people to be able to use the api changes that my addon uses....

**Comment by radfast** [comment]
> when a new beta build will be released

* I usually make a fresh build on Jenkins when I think a small milestone has been reached, or I think people might be interested to see something, or I have fixed a game-breaking bug in a prior build.

* If you **need** a fresh build on Jenkins, any time, just ask me.

*  More official releases than that - forum and website - are up to micdoodle8.

**Comment by MJRLegends** [comment]
@radfast No problem

**Comment by MJRLegends** [comment]
@radfast No problem, didnt mean to sound rude. Just was looking forward to the features that have been added :D. IE this one

**Comment by MJRLegends** [comment]
@micdoodle8 Please could we have a update to date beta build for 1.8.9 :P as i really want the new features :D

**Comment by radfast** [comment]
@MJRLegends can it wait a few days?  The Painter block is still WIP, it has no GUI right now.
(and for your own testing I guess you are building the mod yourself anyhow?)

**Comment by MJRLegends** [comment]
@radfast Yeah i can wait a few days, and yeah but i want it so i can release my addon update and use the GC new stuff and new/fixed api stuff
