### ISSUE TITLE
[1.8.9] Galacticraft 4.0.0.39 Dedicated Server Crash on Startup

### ISSUE THREAD

**Issue by rdlenk** [micdoodle8/Galacticraft#2389]
Been trying to get a Galacticraft 4.0.0.39 (beta) dedicated server working. With a clean install of everything it just won't start. Running Minecraft 1.8.9 with Forge 11.15.1.1902 (latest) but also tried with build 1722 (recommended). Forge starts on its own without any problems but as soon as I add the Galacticraft jars it fails to start with the following crash:

[crash-2017-02-04_22.03.57-server.txt](https://github.com/micdoodle8/Galacticraft/files/752782/crash-2017-02-04_22.03.57-server.txt)

Client starts fine with the mod but not the server.

**Comment by shing3232** [comment]
[crash-2017-02-10_03.08.56-server.txt](https://github.com/micdoodle8/Galacticraft/files/764780/crash-2017-02-10_03.08.56-server.txt)
I got the same thing here

**Comment by micdoodle8** [comment]
Fixed in the latest build, thanks.
