### ISSUE TITLE
Mod cannot be compiled (at least in 1.7 branch)

### ISSUE THREAD

**Issue by Brycey92** [micdoodle8/Galacticraft#2390]
I wanted to contribute to the mod, but using forge gradle, I couldn't get the 1.7 branch to compile. This is my [gradle.log](https://gist.github.com/Brycey92/1460fa6ae476c9ace478d4c571bd7808).

**Comment by Kerai** [comment]
First you need to download forge source package, and copy both Galacticraft and Micdoodlecore repos into it.

And to build it properly to test you need to run gradle tasks like this

    gradlew build packCoreJar packPlanetsJar packMicCoreJar

**Comment by Brycey92** [comment]
I tried following your instructions, but gradlew build still fails with [this log](https://gist.github.com/Brycey92/65d8fe5e06577b5e5669f667d8062dee). It looks like an access transformer is missing or not being applied or something.

**Comment by Kerai** [comment]
have you done setupDecompWorkspace with these access transformers present?

**Comment by Brycey92** [comment]
Oh, whaddya know, I forgot to re-run setupDecompWorkspace when I added Micdoodlecore! Thanks for the help! I'll update the readme file with instructions so others can benefit from this.

**Comment by radfast** [comment]
@Brycey92 why did you not find this? https://wiki.micdoodle8.com/wiki/GC3_API

If any info there is incorrect, please point it out or edit it yourself :)

**Comment by Brycey92** [comment]
It's not readily apparent that the wiki page for the API would be where to find instructions on making changes to the Galacticraft code itself.

**Comment by radfast** [comment]
I've added a link on the readme.md
There's also a clear pointer here: https://wiki.micdoodle8.com/wiki/Compiling_Workspace
which is the second search result https://www.google.co.uk/search?q=install+galacticraft+source+code
