### ISSUE TITLE
[Feature request] Granular asteroid challenge config settings

### ISSUE THREAD

**Issue by Brycey92** [micdoodle8/Galacticraft#2391]
I propose the addition of several separate, more granular asteroid challenge config settings. For example, separate settings to enable the compressor recipes, mob drops, and spawn handling. I would love for these config settings to at least be added to the 1.7 branch.

I run a modded server, and I want to use my own spawn control system to allow players to go through an introduction and explanation on a specific asteroid. This would let me provide them with oxygen and a safe area from mobs while they got their bearings and put on their gear.

I would write the code changes myself, but as mentioned in #2390, I can't compile the mod from the source.

**Comment by dj3520** [comment]
https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md#what-else-is-not-ok-on-the-issues-list

**Comment by Brycey92** [comment]
Sorry! I didn't see that. I'll move this to a thread now.

**Comment by radfast** [comment]
https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md#pull-requests number 5

**Comment by Brycey92** [comment]
You seem to have some conflicting contribution guidelines there.

**Comment by radfast** [comment]
I don't think so :)   Just different rules for:
- players who want to make suggestions
- developers who want to propose a specific idea which they will implement using a PR.
