### ISSUE TITLE
Incomplete Download?

### ISSUE THREAD

**Issue by SuperHammy3** [micdoodle8/Galacticraft#2393]
Hi. I'm trying to setup Galacticraft on a server but whenever I run the Forge jar file I get this:
![capture](https://cloud.githubusercontent.com/assets/15901871/22768531/a7d74de8-ee37-11e6-879e-3a1d67114c16.PNG)

The GalacticraftCore JAR file download always cancels for me when it's at 7.3/7.4 MB.

**Comment by EzerArch** [comment]
It's recurring: https://forum.micdoodle8.com/index.php?threads/i-cant-download-galacticraft-what-to-do.3736/

**Comment by SuperHammy3** [comment]
Ah. Thanks. Already have it but thanks.

**Comment by EzerArch** [comment]
Please close the issue.
