### ISSUE TITLE
crash with galacticraft

### ISSUE THREAD

**Issue by danilbor11** [micdoodle8/Galacticraft#2401]
http://pastebin.com/KPp116jG

**Comment by SteveKunG** [comment]
at cn.lambdalib.util.datapart.EntityData.getPart(EntityData.java:116)
-.-

**Comment by danilbor11** [comment]
i'm noob.WHAT?

**Comment by EzerArch** [comment]
> i'm noob.WHAT?

Hi noob. I'm what. Did you call me? :>

Just kidding. Well, let's start with this:

```
---- Minecraft Crash Report ----
// I'm sorry, Dave.
 
Time: 2/16/17 8:07 PM
Description: Ticking player
 
java.util.NoSuchElementException: No value present
    at java.util.Optional.get(Unknown Source)
    at cn.lambdalib.util.datapart.EntityData.getPart(EntityData.java:116)
    at cn.academy.ability.api.context.ClientRuntime.instance(ClientRuntime.java:64)
    at ...
```
The 1st five lines are the header: title, unfunny phrase by Mojang, time, and kind of error.

The 6th line: the error itself. Tells what Java method/function broke. Dev stuff.

And then the _aha_ moment: the at-lines. They tell where in each Java module or mod the crash happened. $1-million-question: is there any galacticraft or micdoodle in those at-lines? No. Wait! I know Lambdalib and AcademyCraft, please try reporting here: https://github.com/LambdaInnovation

**Comment by radfast** [comment]
Thank goodness for EzerArch :)
