### ISSUE TITLE
1.7.10 pack adding Galacticraft

### ISSUE THREAD

**Issue by RoyalAmerican** [micdoodle8/Galacticraft#2404]
Hi, I am having an issue with Galacticraft in the means of adding it to a modpack with pre-existing mods. I am using the Technic Launcher's (1.7.10 pack) it looks like gold bars stacked. I had added GalaxySpace which started fine, the AmunRa which started fine, then Archimedes which started fine, then it came to the three Galacticraft mods (all the same version) once I added those mods the Technic Launcher started up the mod pack,, closed technic, then opened up technic and my game will not start with the Galacticraft. Please help, my friends have done the same thing add all the mods and it seems to work for them. 

SCREENSHOTS:
https://gyazo.com/61a928c20742c1f28fe86304e1d10a8a
https://gyazo.com/30f918280a31da0c5d5d62a5b70bb14b

**Comment by dj3520** [comment]
We can't help you much without a client log since without it we can't figure out what's going wrong. [Posting new issues - guidelines](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md#posting-new-issues---guidelines)

**Comment by C1ffisme** [comment]
[Did you seriously just open up a second issue for your current one?](https://github.com/micdoodle8/Galacticraft/issues/2403)

**Comment by radfast** [comment]
Delete AmunRa.

Fixed it for you. :)
