### ISSUE TITLE
switch to third person on rocket launch isn't nice in vivecraft

### ISSUE THREAD

**Issue by doggogoesbork** [micdoodle8/Galacticraft#2405]
Hi.

I am using a minecraft mod known as "vivecraft" which allows minecraft to be played in VR with room tracking.

This mod, over all, works great. However, when getting in and out of rockets/landers/etc, the view may jump from 1st person to third, which is extremely nauseating and is really the only major bug this other wise great mod has with VR.

I think the best possible fix for this issue is to have a config option to disable all 3rd person jumps, and remain in first person at all times.

Thank you!

**Comment by radfast** [comment]
The jump from 1st person to third is intentional.

We can maybe look at a config option here, though I've never heard of anyone else playing GC in VR.  How many downloads does vivecraft have?

**Comment by doggogoesbork** [comment]
http://www.vivecraft.org/

I couldnt find any numbers but it is certainly under development actively with a considerable following.
I would like to note that 1.7.10 is the only current version with forge mod support. I believe later versions of vivecraft will be getting forge support later (it was mentioned a few times on forums)

**Comment by Brycey92** [comment]
My PR #2410 should automatically check if Vivecraft is installed and disable third-person switching if so. If someone could test it, that would be awesome!

**Comment by radfast** [comment]
Thank you to @Brycey92 for finding a solution so fast, great job
We should be able to fix this today or tomorrow.  I've made some comments on #2410

**Comment by Brycey92** [comment]
@doggogoesbork I implemented a config option in #2412 to disable camera changes in vehicles, and radfast merged it. If you can compile and build everything, let us know how it goes in VR. If you can't compile (and radfast doesn't object) I can give you compiled jars from my workspace.

**Comment by radfast** [comment]
I will make a new GC build 466 now with this, and other recent fixes.
@doggogoesbork you can just test 466, please
