### ISSUE TITLE
Galacticraft Site Not Working (Again)

### ISSUE THREAD

**Issue by jeg623** [micdoodle8/Galacticraft#2407]
To be technical, the site itself does work, but when I reached the download page, the countdown wouldn't begin. I fixed this by opening it in Internet Explorer.When I opened it in IE, it said that is was only letting secure content being displayed. When I allowed secure content to be displayed, the countdown was started and the file was available. Currently, I'm using an experimental version of [Chrome](https://www.google.com/chrome/browser/canary.html), but it has been very stable. I also tried it in Edge. I've no experience in coding, but maybe it is seen as insecure content on Chrome and Edge? Possibly because the link opens a new window? It might also that Chrome or Edge simply won't load it for some reason?

**Comment by dj3520** [comment]
Can confirm something isn't right. Meanwhile if you need the files they are available at [The Jenkins](https://ci.micdoodle8.com/job/Galacticraft-1.7/)

Using Chrome Version 56.0.2924.87 on Windows 10 (64-bit) [Version 10.0.14393] there are a few errors in the console. 

`download:1 Mixed Content: The page at 'https://micdoodle8.com/download?TWljZG9vZGxlQ29yZS0xLjctMy4wLjEyLjQ2NS5qYXI…ZhY3QvRm9yZ2UvYnVpbGQvbGlicy9NaWNkb29kbGVDb3JlLTEuNy0zLjAuMTIuNDY1Lmphcg==' was loaded over HTTPS, but requested an insecure script 'http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js'. This request has been blocked; the content must be served over HTTPS.`

`download:1 Mixed Content: The page at 'https://micdoodle8.com/download?TWljZG9vZGxlQ29yZS0xLjctMy4wLjEyLjQ2NS5qYXI…ZhY3QvRm9yZ2UvYnVpbGQvbGlicy9NaWNkb29kbGVDb3JlLTEuNy0zLjAuMTIuNDY1Lmphcg==' was loaded over HTTPS, but requested an insecure script 'http://pagead2.googlesyndication.com/pagead/show_ads.js'. This request has been blocked; the content must be served over HTTPS.`

`download:76 Uncaught ReferenceError: $ is not defined
    at download:76`

`data:application/javascript;base64,dmFyIHVyY2hpblRyYWNrZXI9ZnVuY3Rpb24oKXt9…cmFja2VyQnlOYW1lOiBmdW5jdGlvbigpe190cmFja0V2ZW50OiBmdW5jdGlvbigpe319fTs=:1 Uncaught SyntaxError: Unexpected token var`

**Comment by jeg623** [comment]
Thanks!

**Comment by jeg623** [comment]
I look at the log and it says the use of HTTPS is required. I use an extension that forces webpages to use HTTPS. Maybe this is part of the problem. It is called HTTPS everywhere.

**Comment by jeg623** [comment]
I look at the log and it says the use of HTTPS is required. I use an extension that forces webpages to use HTTPS. Maybe this is part of the problem. It is called HTTPS everywhere.

**Comment by jeg623** [comment]
My mistake.

**Comment by micdoodle8** [comment]
Should be fixed now, just had to switch script source to https. If you notice any other issues around the site feel free to re-open/re-create report. Thanks.
