### ISSUE TITLE
 game crash on space station buld 1.8 

### ISSUE THREAD

**Issue by paulspchelp** [micdoodle8/Galacticraft#2419]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.8.9-2.1.6.jar)
  FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  CoreXU2 (extrautils2-1.8.9-alpha-0.0.2.jar)
  FMLPlugin (InventoryTweaks-1.60-40.jar)
  MicdoodlePlugin (MicdoodleCore-1.8.9-4.0.0.45-BETA.jar)
  IC2core (industrialcraft-2-2.3.262-ex18.jar)
  NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
  EnderCorePlugin (EnderCore-1.8.9-0.3.0.14-beta.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 2/27/17 2:32 AM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at micdoodle8.mods.galacticraft.core.dimension.SpinManager.spin(SpinManager.java:495)
	at micdoodle8.mods.galacticraft.core.dimension.SpinManager.onWorldTick(SpinManager.java:91)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_399_SpinManager_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:274)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:686)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 964001920 bytes (919 MB) / 2302672896 bytes (2196 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.19 Powered by Forge 11.15.1.1902 32 mods loaded, 32 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1902-1.8.9.jar) 
	UCHIJAAAA	Forge{11.15.1.1902} [Minecraft Forge] (forge-1.8.9-11.15.1.1902-1.8.9.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	forgecreeperheal{2.0.1} [Forge Creeper Heal 2.0.1] ([1.8.9] ForgeCreeperHeal-2.0.1.jar) 
	UCHIJAAAA	movillages{1.5.1} [Mo' Villages] ([1.8.x]Mo' Villages-1.5.1.jar) 
	UCHIJAAAA	betterbuilderswands{0.6.1} [Better Builder's Wands] (BetterBuildersWands-0.6.1-1.8.9r105+18eaa0f.jar) 
	UCHIJAAAA	BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8.9-3.0.0.2004-universal.jar) 
	UCHIJAAAA	customnpcs{1.8.9} [CustomNPCs] (CustomNpcs_1.8.9(29oct16).jar) 
	UCHIJAAAA	endercore{1.8.9-0.3.0.14-beta} [EnderCore] (EnderCore-1.8.9-0.3.0.14-beta.jar) 
	UCHIJAAAA	Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
	UCHIJAAAA	EnderIO{1.8.9-3.0.0.26_alpha} [Ender IO] (EnderIO-1.8.9-3.0.0.26_alpha.jar) 
	UCHIJAAAA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.8.9-alpha-0.0.2.jar) 
	UCHIJAAAA	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.8-1.6.jar) 
	UCHIJAAAA	IC2{2.3.262-ex18} [IndustrialCraft 2] (industrialcraft-2-2.3.262-ex18.jar) 
	UCHIJAAAA	GalacticraftCore{4.0.0} [Galacticraft Core] (GalacticraftCore-1.8.9-4.0.0.45-BETA.jar) 
	UCHIJAAAA	GalacticraftPlanets{4.0.0} [Galacticraft Planets] (Galacticraft-Planets-1.8.9-4.0.0.45-BETA.jar) 
	UCHIJAAAA	gravestone{1.1.7} [Gravestone] (GraveStone Mod 1.1.7.jar) 
	UCHIJAAAA	inventorytweaks{1.60-40-e06e29a} [Inventory Tweaks] (InventoryTweaks-1.60-40.jar) 
	UCHIJAAAA	JEI{2.28.18.186} [Just Enough Items] (jei_1.8.9-2.28.18.186.jar) 
	UCHIJAAAA	journeymap{1.8.9-5.2.4} [JourneyMap] (journeymap-1.8.9-5.2.4-unlimited.jar) 
	UCHIJAAAA	malisiscore{1.8.9-2.1.6} [MalisisCore] (malisiscore-1.8.9-2.1.6.jar) 
	UCHIJAAAA	malisisdoors{1.8.9-3.1.4} [MalisisDoors] (malisisdoors-1.8.9-3.1.4.jar) 
	UCHIJAAAA	mantle{1.8.9-0.9.2.jenkins102} [Mantle] (Mantle-1.8.9-0.9.2.jar) 
	UCHIJAAAA	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.8.9-2.1.6.jar) 
	UCHIJAAAA	notenoughwands{1.3.1} [Not Enough Wands] (notenoughwands-1.8.9-1.3.1.jar) 
	UCHIJAAAA	redstonepaste{1.7.2} [Redstone Paste] (redstonepaste-mc1.8.8-1.7.2.jar) 
	UCHIJAAAA	tconstruct{1.8.9-2.2.1.jenkins1005} [Tinkers' Construct] (TConstruct-1.8.9-2.2.1.jar) 
	UCHIJAAAA	TinkersAddons{1.0.2a} [Tinkers' Addons] (Tinkers' Addons-1.8.9-1.0.2a.jar) 
	UCHIJAAAA	villagebox{1.8.9-0.4.0} [Village Box] (villagebox-1.8.9-0.4.0.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.7} [Waila Harvestability] (WailaHarvestability-mc1.8.x-1.1.7.jar) 
	UCHIJAAAA	wawla{1.1.4.168} [What Are We Looking At] (Wawla-1.8.9-1.1.4.171.jar) 
	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.8.9-2.1.6.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
CoreXU2 (extrautils2-1.8.9-alpha-0.0.2.jar)
  com.rwtema.extrautils2.asm.ClassTransformerHandler
FMLPlugin (InventoryTweaks-1.60-40.jar)
  invtweaks.forge.asm.ContainerTransformer
MicdoodlePlugin (MicdoodleCore-1.8.9-4.0.0.45-BETA.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
IC2core (industrialcraft-2-2.3.262-ex18.jar)
  
NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
  net.fybertech.nwr.NowWithRendering
EnderCorePlugin (EnderCore-1.8.9-0.3.0.14-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)

	EnderIO: No known problems detected.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [GCEntityPlayerMP['pauls_lap_top'/352, l='New World', x=0.50, y=65.00, z=0.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by dj3520** [comment]
https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md#posting-new-issues---guidelines see point 5

**Comment by radfast** [comment]
Thanks paulspchelp, I'm looking into this.
Does this happen always for your game, or is it a one-time thing?

**Comment by paulspchelp** [comment]
yes  and  
if go to space station after game  crashes  it  keeps cashing  evey time you try go to space station


 I have  server up at  gameserver.paulspchelp.com.au:25575

**Comment by radfast** [comment]
Thanks, I've noted the server address and edited it to remove it from public view in your comment.

I will look at this next, sorry it's been a bit intense on finishing Space Glass and merging the branches recently.

**Comment by radfast** [comment]
Thank you again for reporting.

This was a problem affecting everyone - so I guess not too many people have tried to go to Space Stations in 1.8.9 yet - maybe everyone is still checking out Venus :)

From next build, space stations should be accessible.

**Comment by radfast** [comment]
Anyone building 1.8.9 from the sources, please note you currently (March 20, 2017) cannot move on Space Stations when the player has feet on solid blocks - place space to jump, then you can move in freefall as in 1.7.10. 

Probably movement on Space Stations is OK with **PlayerAPI** installed, I haven't tested that yet.
