### ISSUE TITLE
Galacticraft Forum currently has intermittent availability ...

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#2433]
![untitled](https://cloud.githubusercontent.com/assets/6128413/23504542/9268dfd4-ff72-11e6-8a62-4034642732a0.png)

I don't know this happen only in Thai or in other country. Its down too often.

But my phone can access the website. That's weird.

![screenshot_20170302-180256](https://cloud.githubusercontent.com/assets/6128413/23504638/01cd38f2-ff73-11e6-8a38-793a3b864432.png)

**Comment by radfast** [comment]
Forum is working for me just now.

If your phone can access the forum, but your PC cannot, sounds like a local connectivity issue.

Your phone has two different 4G networks?

**Comment by SteveKunG** [comment]
My phone use Wi-Fi connection. But now I can access forum again.

**Comment by radfast** [comment]
Good news.  Guess it was some temporary glitch with the service provider or DNS.

**Comment by MJRLegends** [comment]
Yeah i see this problem now and again and have to wait a few mins and then it all works fine

**Comment by radfast** [comment]
Ok, seems like it's an intermittent problem which the webhosts will have to look at.

**Comment by MJRLegends** [comment]
I feel this issue is getting worse, i get it at least 3 times a day atm

**Comment by SteveKunG** [comment]
At today. (23:33 PM in Thai)

![untitled](https://cloud.githubusercontent.com/assets/6128413/24258701/228fad90-1021-11e7-8730-4d24e57bc931.png)

**Comment by micdoodle8** [comment]
Made a change to the server settings on March 23. Has this still been happening? @SteveKunG

**Comment by SteveKunG** [comment]
Since March 23 I don't see any issue with GC Forum.

**Comment by MJRLegends** [comment]
Yeah same seems all good now :D

**Comment by SteveKunG** [comment]
I've got a problem again, NET::ERR_CERT_DATE_INVALID

![1](https://cloud.githubusercontent.com/assets/6128413/26518864/1858e748-42e3-11e7-961a-26750167c1d4.png)

**Comment by dj3520** [comment]
https certificate needs renewed I guess

**Comment by EzerArch** [comment]
@micdoodle8 is aware of it and has told the site maintainers about it.

**Comment by MJRLegends** [comment]
Btw its has now been fixed :D
