### ISSUE TITLE
Fuel loader does NOT accept fuel from pipes.

### ISSUE THREAD

**Issue by JohnnyMolander** [micdoodle8/Galacticraft#2435]
This issue has been up several times but it still ain't working for me.

#1906 #1863 #1409 

I have both lines false in config.

`# Set to true to make Galacticraft oil register as oilgc, for backwards compatibility with previously generated worlds.
    B:"Use legacy oilgc fluid registration"=false

    # Set to true to make Galacticraft fuel register as fuelgc, for backwards compatibility with previously generated worlds.
    B:"Use legacy fuelgc fluid registration"=false`

Still it does not accept fuel from BC Pipes, Ender IO Conduit, TE ducts, Ender IO Fluid Tank or anything else.

I'm running the latest Project Ozone 2 Reloaded Kappa Mode.

Galacticraft Version: 3.0.12.464
Buildcraft Version: 7.1.18
Thermal Dynamics Version: 1.2.0-171
Ender IO Version: 2.3.0.429

**Comment by radfast** [comment]
Those config entries have no effect on what the Fuel Loader does or does not accept.

The Fuel Loader should accept any of the following liquids: Galacticraft's own fuel, BC fuel, any similar "fuel" from other mods, Rocket Fuel from EnderIO, and RotaryCraft Jet Fuel.

The most likely issue here is you are not piping in to the correct side of the Fuel Loader block.  Please provide a screenshot.  If it's not that, then maybe something wrong with your overall setup, please provide a full server log.

> ... the latest Project Ozone 2 Reloaded Kappa Mode.

I don't know what that is.

**Comment by dj3520** [comment]
@radfast https://minecraft.curseforge.com/projects/project-ozone-2-reloaded

@JohnnyMolander What specific fuel are you using (buildcraft, enderio rocket fuel, etc) ?

**Comment by JohnnyMolander** [comment]
My appologies, I thought the yellow was output to the launch pad.

**Comment by radfast** [comment]
> The most likely issue here is you are not piping in to the correct side of the Fuel Loader. 

:D

**Comment by EzerArch** [comment]
Wololo: https://wiki.micdoodle8.com/wiki/Fuel_Loader#Faces

**Comment by darthvader45** [comment]
Have the same problem, I'm using Galacticraft's own fluid pipes and have them going to the right side of the fuel loader, it's got power on the left, and right next to a launchpad with a rocket on it.  Does it not get fuel if the refinery isn't at a certain amount of fuel?
![2020-02-17_17 23 55](https://user-images.githubusercontent.com/2816420/74689749-56c0fd80-51aa-11ea-89a9-ba1a6dd10161.png)

**Comment by dj3520** [comment]
@darthvader45 There's currently no fuel going through that pipe. Use a wrench on the other side to extract fuel into the pipe.

**Comment by darthvader45** [comment]
I'll try that, thanks.
