### ISSUE TITLE
[1.7.10] Cant get out / close slimeling interaction GUI

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft#2437]
See https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/677

**Comment by SteveKunG** [comment]
Caused by this : https://github.com/micdoodle8/Galacticraft/commit/4bd9bcbac7ff8db3fd303aa4369ec864e069835a

It prevent accidentally press ESC key while you feed the Slimeling.

**Comment by MJRLegends** [comment]
@SteveKunG so can it be fixed?

**Comment by radfast** [comment]
A quick fix, nice.  I will make a new build with this later tonight.

**Comment by MJRLegends** [comment]
Sweet thanks :D wasn't expecting it to be fixed so fast

**Comment by MJRLegends** [comment]
@radfast Dont mean to sound pushy but is there a eta on the build containing this fix, i only ask as im trying to get a bug fix update out for my mod pack ASAP

**Comment by MJRLegends** [comment]
@radfast I see you tried to build a version on Jenkins, but i see it says the build failed, im guessing its not safe to use it?

**Comment by radfast** [comment]
You Jenkins stalker, you!

Failed builds (marked in red on Jenkins) will not have any downloadable files, so there is no risk there - if Jenkins is offering you files to download, they should be safe to use, and they are the same as the ones offered on the main micdoodle8.com download page.

In this case I managed to find and fix, quite quickly, the reason why build 469 failed.  (It was an obscure reason connected with Forge including, in the .gitignore file provided when Forge installs itself for mod development, some ignores for Python code - and those ignores happened to match the name of some needed files in the AppliedEnergistics2 API.)

The main thing to take away from this is that Sealable ME Cables are now available in Galacticraft.

**Comment by MJRLegends** [comment]
Haha yeah i was waiting on the build so i could submit my mod pack update and Yeah glad you managed to fix it
