### ISSUE TITLE
[1.7.10] Render custom thermal armor after build 468

### ISSUE THREAD

**Issue by BlesseNtumble** [micdoodle8/Galacticraft#2440]
Not work))
![1](https://pp.userapi.com/c837338/v837338755/295df/JLs40VLLw1A.jpg)

**Comment by radfast** [comment]
:(

Did your #2426 fix it in a test build you made? 
See also 0934908

Also is this with RenderPlayerAPI?

**Comment by BlesseNtumble** [comment]
with and without RenderPlayerApi.
maybe my way to work....

**Comment by radfast** [comment]
See discussion on #2427, maybe this needs a more solid solution.

**Comment by katzenpapst** [comment]
I just noticed that, too, looked at the code, and facepalmed.

if (GalacticraftCore.isPlanetsLoaded && par1EntityLivingBase instanceof EntityPlayerMP)
EntityPlayerMP
MP
...

The renderer will only ever run on the client side. There is no way that render skipping will ever happen.
And, does GCPlayerStats even exist on the client side?

**Comment by radfast** [comment]
lol thank you @katzenpapst  I should read pull request code more carefully before merging it - micdoodle8 and me tend to assume that PRs from people we trust have code which has already been built and tested **before** making the PR ;)

**Comment by radfast** [comment]
I have reverted this change in GC 1.7.10.

Galacticraft will only render it's own thermal armor now.  If a sub-mod has different thermal armor, if that is not entered in the GearData as type "0", then GC will not render it.

See:
[RenderPlayerGC](https://github.com/micdoodle8/Galacticraft/blob/MC1.7/src/main/java/micdoodle8/mods/galacticraft/core/client/render/entities/RenderPlayerGC.java#L96)
[PacketSimple](https://github.com/micdoodle8/Galacticraft/blob/MC1.7/src/main/java/micdoodle8/mods/galacticraft/core/network/PacketSimple.java#L464)

**Comment by radfast** [comment]
Any further change will need to come from @micdoodle8 , see #2427 

-----

Note that in GC4 for Minecraft 1.8.9, Galacticraft now has two tiers of thermal armor.  These are now given sub-types from [https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/Constants.java#L39-49](6 through to 13) according to armor piece and tier.  The sub-type is passed into the PlayerGearData wrapper in [PacketSimple](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/network/PacketSimple.java#L455).
