### ISSUE TITLE
[1.7.10] Error while compiling

### ISSUE THREAD

**Issue by xdMatthewbx** [micdoodle8/Galacticraft#2441]
I'm using the 1.7 code, I downloaded the 1.7.10 forge MDK (the src button on the site), micdoodle8 core 1.7.10, and the GC 1.7.10 code. I copied the forge MDK in to a directory (excluding the src folder cause I dont want the example mod), put in micdoodle8 core, then the GC contents, after that I ran gradlew setupDecompWorkspace eclipse, then opened the project in eclipse, hit run, and it keeps showing this: https://mix1337.gyazo.com/cc2e71140a6bb99e57bd30d8b752a07b

Attached is the error log.
[fml-client-latest.txt](https://github.com/micdoodle8/Galacticraft/files/819720/fml-client-latest.txt)

Any ideas?

**Comment by radfast** [comment]
> 'm using the 1.7 code, I downloaded the 1.7.10 forge MDK (the src button on the site), micdoodle8 core 1.7.10, and the GC 1.7.10 code. I copied the forge MDK in to a directory (excluding the src folder cause I dont want the example mod), put in micdoodle8 core, then the GC contents, after that I ran gradlew setupDecompWorkspace eclipse, then opened the project in eclipse, 

Why is this relevant?

-----

> Attached is the error log.

The error log shows that Smart Render has PlayerAPI 1.3 as a dependency.

**Comment by xdMatthewbx** [comment]
I cant find the github for that
