### ISSUE TITLE
[1.8.9] Missing block particle textures

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#2442]
Included :
Treasure Chest 1-3
Spin Thurster
Display Screen
Short Range Teleport
Energy Beam Reflector/Receiver
Arc Lamp
Full Astro Miner Base

![2560-03-06_07 00 03](https://cloud.githubusercontent.com/assets/6128413/23592930/bd5d1ea6-023a-11e7-8efe-472acb379ee5.png)
![2560-03-06_07 00 19](https://cloud.githubusercontent.com/assets/6128413/23592931/bd5d5038-023a-11e7-8b6b-157559767570.png)
![2560-03-06_07 00 53](https://cloud.githubusercontent.com/assets/6128413/23592932/bd8c30ce-023a-11e7-8b92-c27526c59477.png)

Also its happen with Walkway (When running on Normal Walkway)
![2560-03-06_07 14 29](https://cloud.githubusercontent.com/assets/6128413/23593083/d6b1bfae-023c-11e7-9976-c25ac20475f9.png)

**Comment by radfast** [comment]
These missing textures are - probably - connected with reported errors when loading JSON files.  I'm looking to see if there's an automatic way we can find and fix **every** missing texture ...
