### ISSUE TITLE
[1.7.10] Asteroid Adventure Recipes config setting only works when mod is manually compiled

### ISSUE THREAD

**Issue by Brycey92** [micdoodle8/Galacticraft#2446]
Despite having written the config and code for this setting myself, and it having been merged into the 1.7 branch, the config setting does not work for officially compiled versions of Galacticraft. A friend took the sources for GC and MicdoodleCore and compiled them as they are, which should be equivalent to version 474. However, this config setting works fine in their compiled version.

**Comment by radfast** [comment]
That shouldn't be possible.

Please check for other possible sources of this error - in particular, check the client and server both are running the EXACT same .jar.  Copy the Galacticraft .jars from one to the other, to make sure.

**Comment by Brycey92** [comment]
This issue was noted on singleplayer as well, prior to connecting to any servers.

**Comment by radfast** [comment]
Thank you for reporting, you are correct.  This was due to an error in the Jenkins script, meaning that a couple of other small recent (last 6 months) changes in the API were not being seen in the officially compiled versions.

Fixed from build 3.0.12.475

**Comment by Brycey92** [comment]
Thanks for the fast fix!
