### ISSUE TITLE
game Crash when creating a world

### ISSUE THREAD

**Issue by loster31345** [micdoodle8/Galacticraft#2449]
I know this may be kinda outdated, but i hope someone can help me:D

when i create a new world the game crashs, i think it has something to do whit galacticcraft and glenn's gasses.
MC version: 1.6.4
galacticcraft version: Galacticraft-1.6.4-2.0.14.1084
glenn's gasses version: gases-1.4.3-1.6.4

[SPOILER="crash log:"]
[B#349]  2017-03-07 10:08:06 [INFO] [ForgeModLoader] Recipes loaded.
[B#349]  
[B#349]  
[B#349]  2017-03-07 10:08:06 [INFO] [Minecraft-Client] [CHAT] A newer version of Glenn's Gases(1.5.0) is avaliable for download.
[B#349]  2017-03-07 10:08:06 [INFO] [Minecraft-Client] [CHAT] http://www.jamieswhiteshirt.com/minecraft/mods/gases/news/index.php?hl=18
[B#349]  2017-03-07 10:08:06 [INFO] [STDERR] java.lang.ClassCastException: micdoodle8.mods.galacticraft.core.entities.player.GCCorePlayerMP cannot be cast to net.minecraft.client.entity.EntityClientPlayerMP
[B#349]  2017-03-07 10:08:06 [INFO] [STDERR]     at glenn.gases.UpdateChecker.onEntityJoinedWorld(UpdateChecker.java:34)
[B#349]  2017-03-07 10:08:06 [INFO] [STDERR]     at net.minecraftforge.event.ASMEventHandler_120_UpdateChecker_onEntityJoinedWorld_EntityJoinWorldEvent.invoke(.dynamic)
[B#349]  2017-03-07 10:08:06 [INFO] [STDERR]     at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:39)
[B#349]  2017-03-07 10:08:06 [INFO] [STDERR]     at net.minecraftforge.event.EventBus.post(EventBus.java:108)
[B#349]  2017-03-07 10:08:06 [INFO] [STDERR]     at net.minecraft.world.World.func_72838_d(World.java:1573)
[B#349]  2017-03-07 10:08:06 [INFO] [STDERR]     at net.minecraft.server.management.ServerConfigurationManager.func_72377_c(ServerConfigurationManager.java:267)
[B#349]  2017-03-07 10:08:06 [INFO] [STDERR]     at net.minecraft.server.management.ServerConfigurationManager.func_72355_a(ServerConfigurationManager.java:136)
[B#349]  2017-03-07 10:08:06 [INFO] [STDERR]     at net.minecraft.server.integrated.IntegratedServerListenThread.func_71747_b(IntegratedServerListenThread.java:97)
[B#349]  2017-03-07 10:08:06 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:691)
[B#349]  2017-03-07 10:08:06 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
[B#349]  2017-03-07 10:08:06 [INFO] [STDERR]     at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:175)
[B#349]  2017-03-07 10:08:06 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
[B#349]  2017-03-07 10:08:06 [INFO] [STDERR]     at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
[B#349]  2017-03-07 10:08:06 [SEVERE] [Minecraft-Server] Encountered an unexpected exception ClassCastException
[B#349]  java.lang.ClassCastException: micdoodle8.mods.galacticraft.core.entities.player.GCCorePlayerMP cannot be cast to net.minecraft.client.entity.EntityClientPlayerMP
[B#349]     at glenn.gases.UpdateChecker.onEntityJoinedWorld(UpdateChecker.java:34)
[B#349]     at net.minecraftforge.event.ASMEventHandler_120_UpdateChecker_onEntityJoinedWorld_EntityJoinWorldEvent.invoke(.dynamic)
[B#349]     at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:39)
[B#349]     at net.minecraftforge.event.EventBus.post(EventBus.java:108)
[B#349]     at net.minecraft.world.World.func_72838_d(World.java:1573)
[B#349]     at net.minecraft.server.management.ServerConfigurationManager.func_72377_c(ServerConfigurationManager.java:267)
[B#349]     at net.minecraft.server.management.ServerConfigurationManager.func_72355_a(ServerConfigurationManager.java:136)
[B#349]     at net.minecraft.server.integrated.IntegratedServerListenThread.func_71747_b(IntegratedServerListenThread.java:97)
[B#349]     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:691)
[B#349]     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
[B#349]     at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:175)
[B#349]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
[B#349]     at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
[B#349]  2017-03-07 10:08:06 [SEVERE] [Minecraft-Server] This crash report has been saved to: C:\Users\jostein B\AppData\Roaming\.technic\modpacks\mytechnologypack\crash-reports\crash-2017-03-07_10.08.06-server.txt
[B#349]  2017-03-07 10:08:06 [INFO] [Minecraft-Server] Stopping server
[B#349]  2017-03-07 10:08:06 [INFO] [Minecraft-Server] Saving players
[B#349]  2017-03-07 10:08:06 [INFO] [Minecraft-Server] loster31345 left the game
[B#349]  2017-03-07 10:08:06 [INFO] [STDOUT] Unloading Player: loster31345
[B#349]  2017-03-07 10:08:06 [INFO] [Minecraft-Server] Saving worlds
[B#349]  2017-03-07 10:08:06 [INFO] [Minecraft-Server] Saving chunks for level 'World'/Overworld
[B#349]  2017-03-07 10:08:07 [INFO] [Minecraft-Client] [CHAT] Custom Recipes v4.5 is out of date! Update at http://www.minecraftforum.net/topic/1504359-
[B#349]  2017-03-07 10:08:07 [INFO] [Minecraft-Server] Saving chunks for level 'World'/Nether
[B#349]  2017-03-07 10:08:07 [INFO] [Minecraft-Client] [CHAT] CustomNpcs installed. More info at http://tiny.cc/customnpcs
[B#349]  2017-03-07 10:08:11 [INFO] [ForgeModLoader] Unloading dimension 0
[B#349]  2017-03-07 10:08:11 [INFO] [ForgeModLoader] Unloading dimension -1
[B#349]  2017-03-07 10:08:12 [INFO] [Galacticraft] Unregistered Dimension: -28
[B#349]  2017-03-07 10:08:12 [INFO] [Galacticraft] Unregistered Dimension: -29
[B#349]  2017-03-07 10:08:12 [INFO] [ForgeModLoader] The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
[B#349]  2017-03-07 10:08:12 [INFO] [STDOUT] ---- Minecraft Crash Report ----
[B#349]  2017-03-07 10:08:12 [INFO] [STDOUT] // Why is it breaking :(
[B#349]  2017-03-07 10:08:12 [INFO] [STDOUT] 
[B#349]  2017-03-07 10:08:12 [INFO] [STDOUT] Time: 07.03.17 10:08
[B#349]  2017-03-07 10:08:12 [INFO] [STDOUT] Description: Exception in server tick loop
[B#349]  2017-03-07 10:08:12 [INFO] [STDOUT] 
[B#349]  2017-03-07 10:08:12 [INFO] [STDOUT] java.lang.ClassCastException: micdoodle8.mods.galacticraft.core.entities.player.GCCorePlayerMP cannot be cast to net.minecraft.client.entity.EntityClientPlayerMP
[B#349]  2017-03-07 10:08:12 [INFO] [STDOUT]     at glenn.gases.UpdateChecker.onEntityJoinedWorld(UpdateChecker.java:34)
[B#349]  2017-03-07 10:08:12 [INFO] [STDOUT]     at net.minecraftforge.event.ASMEventHandler_120_UpdateChecker_onEntityJoinedWorld_EntityJoinWorldEvent.invoke(.dynamic)
[B#349]  2017-03-07 10:08:12 [INFO] [STDOUT]     at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:39)
[B#349]  2017-03-07 10:08:12 [INFO] [STDOUT]     at net.minecraftforge.event.EventBus.post(EventBus.java:108)
[B#349]  2017-03-07 10:08:12 [INFO] [STDOUT]     at net.minecraft.world.World.func_72838_d(World.java:1573)
[B#349]  2017-03-07 10:08:12 [INFO] [STDOUT]     at net.minecraft.server.management.ServerConfigurationManager.func_72377_c(ServerConfigurationManager.java:267)
[B#349]  2017-03-07 10:08:12 [INFO] [STDOUT]     at net.minecraft.server.management.ServerConfigurationManager.func_72355_a(ServerConfigurationManager.java:136)
[B#349]  2017-03-07 10:08:12 [INFO] [STDOUT]     at net.minecraft.server.integrated.IntegratedServerListenThread.func_71747_b(IntegratedServerListenThread.java:97)
[B#349]  2017-03-07 10:08:12 [INFO] [STDOUT]     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:691)
[B#349]  2017-03-07 10:08:12 [INFO] [STDOUT]     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
[B#349]  2017-03-07 10:08:12 [INFO] [STDOUT]     at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:175)
[B#349]  2017-03-07 10:08:12 [INFO] [STDOUT]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
[B#349]  2017-03-07 10:08:12 [INFO] [STDOUT]     at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
[B#349]  2017-03-07 10:08:12 [INFO] [STDOUT] 
[B#349]  2017-03-07 10:08:12 [INFO] [STDOUT] 
[B#349]  2017-03-07 10:08:12 [INFO] [STDOUT] A detailed walkthrough of the error, its code path and all known details is as follows:
[B#349]  2017-03-07 10:08:12 [INFO] [STDOUT] ---------------------------------------------------------------------------------------
[B#349]  2017-03-07 10:08:12 [INFO] [STDOUT] 
[B#349]  2017-03-07 10:08:12 [INFO] [STDOUT] -- System Details --
[B#349]  2017-03-07 10:08:12 [INFO] [STDOUT] Details:
[B#349]  2017-03-07 10:08:12 [INFO] [STDOUT]     Minecraft Version: 1.6.4
[B#349]  2017-03-07 10:08:12 [INFO] [STDOUT]     Operating System: Windows 8.1 (amd64) version 6.3
[B#349]  2017-03-07 10:08:12 [INFO] [STDOUT]     Java Version: 1.8.0_121, Oracle Corporation
[B#349]  2017-03-07 10:08:12 [INFO] [STDOUT]     Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
[B#349]  2017-03-07 10:08:12 [INFO] [STDOUT]     Memory: 1000354304 bytes (954 MB) / 1894776832 bytes (1807 MB) up to 1908932608 bytes (1820 MB)
[B#349]  2017-03-07 10:08:12 [INFO] [STDOUT]     JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx2048m
[B#349]  2017-03-07 10:08:12 [INFO] [STDOUT]     AABB Pool Size: 2 (112 bytes; 0 MB) allocated, 2 (112 bytes; 0 MB) used
[B#349]  2017-03-07 10:08:12 [INFO] [STDOUT]     Suspicious classes: FML and Forge are installed
[B#349]  2017-03-07 10:08:12 [INFO] [STDOUT]     IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
[B#349]  2017-03-07 10:08:12 [INFO] [STDOUT]     FML: MCP v8.11 FML v6.4.50.1,345 Minecraft Forge 9.11.1.1345 Optifine OptiFine_1.6.4_HD_U_D1 125 mods loaded, 125 mods active
[B#349]  2017-03-07 10:08:12 [INFO] [STDOUT]     mcp{8.09} [Minecraft Coder Pack] (minecraft.jar)
[/SPOILER]

Regards
loster31345

**Comment by radfast** [comment]
It's very definitely a bug in Glenn Gases.

`glenn.gases.UpdateChecker.onEntityJoinedWorld(UpdateChecker.java:34)`

Glenn's code needs to use `(EntityPlayerMP)` not `(EntityClientPlayerMP)` there.
Glenn should not be using client-side code on a server.

I hope this helps you.  I suggest look for a bugfix update for Glenn Gases, or remove that mod.

**Comment by loster31345** [comment]
Yeees! I manage to fix it:DWhitout removing any modThanks any way for your help



Sendt fra min Samsung Galaxy-smarttelefon.
-------- Opprinnelig melding -------- Fra: Galacticraft developer <notifications@github.com> Dato: 07.03.2017  15:08  (GMT+01:00) Til: micdoodle8/Galacticraft <Galacticraft@noreply.github.com> Ko: loster31345 <jostein.baustad@haugnett.no>, Author <author@noreply.github.com> Emne: Re: [micdoodle8/Galacticraft] game Crash when creating a world (#2449) 
It's very definitely a bug in Glenn Gases.
glenn.gases.UpdateChecker.onEntityJoinedWorld(UpdateChecker.java:34)
Glenn's code needs to use (EntityPlayerMP) not (EntityClientPlayerMP) there.

Glenn should not be using client-side code on a server.
I hope this helps you.  I suggest look for a bugfix update for Glenn Gases, or remove that mod.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/micdoodle8/Galacticraft","title":"micdoodle8/Galacticraft","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/micdoodle8/Galacticraft"}},"updates":{"snippets":[{"icon":"PERSON","message":"@radfast in #2449: It's very definitely a bug in Glenn Gases.\r\n\r\n`glenn.gases.UpdateChecker.onEntityJoinedWorld(UpdateChecker.java:34)`\r\n\r\nGlenn's code needs to use `(EntityPlayerMP)` not `(EntityClientPlayerMP)` there.\r\nGlenn should not be using client-side code on a server.\r\n\r\nI hope this helps you.  I suggest look for a bugfix update for Glenn Gases, or remove that mod."}],"action":{"name":"View Issue","url":"https://github.com/micdoodle8/Galacticraft/issues/2449#issuecomment-284730683"}}}
