### ISSUE TITLE
[1.8.9] Air blocks showing in JEI

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft#2451]
The following blocks are showing in JEI, this isn't a 100% major issue at all just thought i'd let you know

- tile.breatheable_air (Also isn't it meant to be breathable_air)

- tile.bright_air

- tile.bright_breathable_air

Theres no rush to fix this just a polish fix

Screenshot: 
![](https://i.gyazo.com/fb388162b18c8662857300cd06a40a34.png)

**Comment by MJRLegends** [comment]
(Issue for @micdoodle8 or @radfast)

**Comment by radfast** [comment]
Thank you, it will be easy enough to fix, simply needs something like this.  But we have not yet brought in the JEI API...  That could be quite a big job as it will want JEI recipes for all our machines, maybe?

`        for (Block block : GCBlocks.hiddenBlocks)
        {
            API.hideItem(new ItemStack(block, 1, 0));
        }`

I'm not too familiar with JEI, I use NEI.

Can you not use NEI in 1.8.9?  I have it working fine, the 1.8 version seems to work in 1.8.9 as well.

**Comment by MJRLegends** [comment]
@radfast yeah theres no rush but it might be something to look at ahead of time as JEI is the main one above 1.8.. But its not a easy job your right :D 

and i tried to use NEI but i get errors when using the dev versions in my dev environment... lol

**Comment by MJRLegends** [comment]
Edit: Update on my NEI issues, i have took another look at it and got it working

**Comment by radfast** [comment]
I think people are still using NEI in 1.8+, and certainly in 1.10+.

I have added code to hide the items in JEI.

Providing any more compatibility with JEI - like showing all the Galacticraft machine recipes - will be extremely challenging, as JEI does not provide API functions to allow us to do that.  JEI seems to want people to write a fresh JEI submod for each mod that wants to make extended use of it.  I am not going to spend my time doing that.  If someone else wants to give it a go, be my guest ... Galacticraft is open source and it's easy enough to see how we interface with NEI.
