### ISSUE TITLE
[1.8.9 & 1.7.10] [API/Prefab Bug] Custom Rocket Bug with EntityTieredRocket

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft#2453]
I found this bug ages ago, and i feel like this is the right time to say about it.

Version Bug is in: 1.7.10 & 1.8.9

The problem is when you create a rocket between the tiers 7 - 9 you get very bad shaking effect. See examples below,

Tier 4 Rocket (Looks Normal):
https://i.gyazo.com/a5bdd564bd1773969b646c9b02d2276c.mp4

Tier 7 Rocket (Looks Very shaky)
https://i.gyazo.com/c887d212fbeaaff533385825c53a5e8a.mp4

Tier 10 Rocket (Looks Normal):
https://i.gyazo.com/12ec53dcfe9b539b4287384d7ad43bc9.mp4

I have found the section of code that is causing this
https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/api/prefab/entity/EntityTieredRocket.java#L220
and
https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/api/prefab/entity/EntityTieredRocket.java#L221

If i change the this.getRocketTier() to a number that isnt 7 or 8 or 9 its normal shaking

**Comment by MJRLegends** [comment]
My code for them rockets

1.7.10 version:
https://github.com/MJRLegends/ExtraPlanets/tree/master/src/main/java/com/mjr/extraplanets/entities/rockets

1.8.9 version:
https://github.com/MJRLegends/ExtraPlanets/tree/dev_1.8.9/src/main/java/com/mjr/extraplanets/entities/rockets

**Comment by radfast** [comment]
Thank you this can easily be fixed, I should be able to do that later today.

**Comment by MJRLegends** [comment]
Sounds good thanks

**Comment by radfast** [comment]
Will be in next build 480.
