### ISSUE TITLE
[1.7.10] Machines consume power when not running

### ISSUE THREAD

**Issue by Brycey92** [micdoodle8/Galacticraft#2458]
As it says in the title, when a machine is not processing, whether due to lack of inputs or a setting in the GUI, the power still steadily decreases.

**Comment by radfast** [comment]
The decrease is by 1 Galacticraft Joule per second, something like that?  That's intended behaviour.

It's for two reasons:  1) realism  2) server performance on large servers.  If a player leaves a base unattended, machines with power will still consume server tick time even if there is no job for the machine to do.  If the machine gets down to 0 energy, it will consume less server tick time.  (Of course if the player's base has a zero maintenance power generation system, maybe solar panels or something, then his power will stay topped up and so the machine will never reach 0 energy.)

**Comment by Brycey92** [comment]
Ah, got it. Thanks for the explanation!
