### ISSUE TITLE
new version dev

### ISSUE THREAD

**Issue by croziors** [micdoodle8/Galacticraft#2461]
why i have 
Missing Blocks/Items:
GalaxySpace:deimostinore
GalaxySpace:mercurysubgrunt
GalaxySpace:iogrunt
GalaxySpace:enceladusice
GalaxySpace:mercurynickelore
GalaxySpace:mercurycore
GalaxySpace:plutobricks
GalaxySpace:ganymedemagnesiumore
GalaxySpace:makemakesubgrunt
GalaxySpace:venusgrunt
GalaxySpace:deimosoriharukonore
GalaxySpace:iocopperore
GalaxySpace:ganymedesubgrunt
GalaxySpace:tritonmithrilore
GalaxySpace:titanstone
GalaxySpace:ioash
GalaxySpace:ceresmachine
GalaxySpace:callistosubgrunt
GalaxySpace:proteusgrunt
GalaxySpace:plutogrunt2
GalaxySpace:plutogrunt3
GalaxySpace:plutogrunt4
GalaxySpace:europaice
GalaxySpace:proteuswolframiumore
GalaxySpace:phoboscobaltumore
GalaxySpace:ceresmeteoricironore
GalaxySpace:ganymedegrunt
GalaxySpace:enceladusgrunt
GalaxySpace:venussulfurore
GalaxySpace:proteusstone
GalaxySpace:tritonstone
GalaxySpace:phobossubgrunt
GalaxySpace:proteusplatinumore
GalaxySpace:plutostone
GalaxySpace:ceresbricks
GalaxySpace:proteusbricks
GalaxySpace:barnardaCdandelion1
GalaxySpace:barnardaCdandelion2
GalaxySpace:mercuryironore
GalaxySpace:iobricks
GalaxySpace:oberonsubgrunt
GalaxySpace:venusdiamondore
GalaxySpace:proteussubgrunt
GalaxySpace:oberonstone
GalaxySpace:titansubgrunt
GalaxySpace:decoratecopperblock
GalaxySpace:mercurygrunt
GalaxySpace:tritonsubgrunt
GalaxySpace:ceresgrunt
GalaxySpace:oberonadamantiteore
GalaxySpace:phobosstone
GalaxySpace:deimosgrunt
GalaxySpace:ganymedetitanuimore
GalaxySpace:iostone
GalaxySpace:plutosubgrunt
GalaxySpace:callistogrunt
GalaxySpace:decolead
GalaxySpace:venussubgrunt
GalaxySpace:haumeagrunt
GalaxySpace:phobosgrunt
GalaxySpace:enceladusbricks
GalaxySpace:mercuryleadore
GalaxySpace:ceressubgrunt
GalaxySpace:plutogrunt
GalaxySpace:tritongrunt
GalaxySpace:iowolframiumore
GalaxySpace:deimossubgrunt
GalaxySpace:oberongrunt
GalaxySpace:phobosdeshore
GalaxySpace:titangrunt
GalaxySpace:deimossubgrunt
GalaxySpace:tritonsubgrunt
GalaxySpace:enceladusgrunt
GalaxySpace:venussubgrunt
GalaxySpace:proteusbricks
GalaxySpace:barnardaCdandelion2
GalaxySpace:barnardaCdandelion1
GalaxySpace:europaice
GalaxySpace:plutostone
GalaxySpace:phobosdeshore
GalaxySpace:oberongrunt
GalaxySpace:makemakesubgrunt
GalaxySpace:oberonsubgrunt
GalaxySpace:enceladusice
GalaxySpace:ceresgrunt
GalaxySpace:deimosgrunt
GalaxySpace:ganymedegrunt
GalaxySpace:mercuryleadore
GalaxySpace:decolead
GalaxySpace:phobosgrunt
GalaxySpace:deimosoriharukonore
GalaxySpace:proteusstone
GalaxySpace:tritonstone
GalaxySpace:oberonadamantiteore
GalaxySpace:plutobricks
GalaxySpace:ceresmeteoricironore
GalaxySpace:mercurygrunt
GalaxySpace:mercuryironore
GalaxySpace:venusgrunt
GalaxySpace:phobossubgrunt
GalaxySpace:decoratecopperblock
GalaxySpace:tritonmithrilore
GalaxySpace:venusdiamondore
GalaxySpace:ganymedesubgrunt
GalaxySpace:deimostinore
GalaxySpace:mercurysubgrunt
GalaxySpace:titangrunt
GalaxySpace:iocopperore
GalaxySpace:proteussubgrunt
GalaxySpace:iobricks
GalaxySpace:ganymedemagnesiumore
GalaxySpace:proteuswolframiumore
GalaxySpace:ceresbricks
GalaxySpace:tritongrunt
GalaxySpace:venussulfurore
GalaxySpace:plutogrunt4
GalaxySpace:plutogrunt2
GalaxySpace:plutogrunt3
GalaxySpace:ceressubgrunt
GalaxySpace:iowolframiumore
GalaxySpace:ganymedetitanuimore
GalaxySpace:plutogrunt
GalaxySpace:haumeagrunt
GalaxySpace:plutosubgrunt
GalaxySpace:iostone
GalaxySpace:enceladusbricks
GalaxySpace:mercurycore
GalaxySpace:ioash
GalaxySpace:titanstone
GalaxySpace:titansubgrunt
GalaxySpace:ceresmachine
GalaxySpace:callistogrunt
GalaxySpace:mercurynickelore
GalaxySpace:phoboscobaltumore
GalaxySpace:oberonstone
GalaxySpace:phobosstone
GalaxySpace:proteusgrunt
GalaxySpace:proteusplatinumore
GalaxySpace:iogrunt
GalaxySpace:callistosubgrunt

**Comment by radfast** [comment]
[Guideline 6](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md)

**Comment by croziors** [comment]
http://paste.feed-the-beast.com/view/ef502aab

**Comment by radfast** [comment]
Go ask for help at FTB forums.
You have missing mods on the client ("Attempting connection with missing mods")
You have Minecraft 1.8 mods mixed in with 1.7.10.
