### ISSUE TITLE
[FaQ] How to compile Galacticraft

### ISSUE THREAD

**Issue by Dokman** [micdoodle8/Galacticraft#2465]
How i can compile Galacticraft? sorry i am noob setting up the Galacticraft :(

**Comment by SteveKunG** [comment]
https://wiki.micdoodle8.com/wiki/GC3_API

**Comment by Dokman** [comment]
okay thanks ^^

**Comment by Dokman** [comment]
![image](https://cloud.githubusercontent.com/assets/2290904/24041490/08073bfe-0b0e-11e7-901b-51aa2f711d4b.png)

**Comment by radfast** [comment]
[Notes for Contributors](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md)

> The Github issues list is not the best place for 'how to' questions from intending add-on authors - especially noobish type questions. The best place for those is the add-ons area of the forum. We understand that for some people writing a Galacticraft Add-On could seem like an easy first project, and obviously we encourage anyone who wants to learn to code well. But we do not have time to hold your hand: we need to spend our coding time working on Galacticraft itself.

> You should be able to figure things out for yourself if you know Java and you understand Minecraft modding.

----

You can give the JVM more memory for the decompile by creating a `gradle.properties` file.  Any other Forge / Gradle setup questions you have, this really is not the place for them, that belongs in the modding area of MinecraftForum or other places where Forge modders hang out.
