### ISSUE TITLE
[1.7.10]No Oxygen Detected

### ISSUE THREAD

**Issue by zengsb** [micdoodle8/Galacticraft#2467]
So my story is, I launched my t1 rocket to the moon with full set of Oxygen tank(Filled with oxygen), gear, mask. Arrived to the moon, a big title appeared instantly says "No Oxygen Detected" and I start to lose health irrelularly. 

http://prntscr.com/elqarb
http://prntscr.com/elqbe8
what may cause this problem?

**Comment by radfast** [comment]
These words in your screenshots: "No Oxygen detected!" and "You have been depressurized" are **not** part of Galacticraft.

Another mod is causing this.  Please provide your mod list.  (Probably, it's a Galacticraft add-on or else Advanced Rocketry.)

**Comment by zengsb** [comment]
Yes, I installed both Advanced Rocketry and ExtraPlanet.

**Comment by radfast** [comment]
Likely Advanced Rocketry is causing this.  Figure out what it needs, probably it has it's own oxygen system.  (I don't know, I never tried to play that mod.)
