### ISSUE TITLE
[1.10.2] Crash during loading

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft#2470]
Issue for @micdoodle8 

Crash log: http://pastebin.com/1v95XZJk

Disabling all entities being registered with this method registerGalacticraftCreature it works

.... Not sure why though haha

**Comment by MJRLegends** [comment]
Yayyy im the first 1.10 labled issue and the first issue for that version @radfast haha

**Comment by MJRLegends** [comment]
This is probably fixed with commit ceaf047b i will retest using that commit

**Comment by micdoodle8** [comment]
The CLASS_TO_ID static field should be public in EntityList. What's the value of 'mappings' in your build.gradle?

**Comment by MJRLegends** [comment]
Im using your build.gradle in the 1.10 repo now and still same issue

**Comment by micdoodle8** [comment]
How are you running Galacticraft? Why are you getting an access error at runtime instead of compile time?

**Comment by MJRLegends** [comment]
im running it in a dev environment, but just tried compiling the dev jars and linking that to my addon project and not  dev environment of GC and still errors, it only seems to be when i link it to my addon, but it only stops crashing, if i stop GC registering anything using the registerGalacticraftCreature methods

**Comment by micdoodle8** [comment]
I just committed a change to MicdoodleCore which might fix this. If this doesn't work, try to investigate why the access transformer wasn't applied to whatever workspace you're running the game. You might have to re-run setupDecompWorkspace. Also try running the game with -Dfml.debugAccessTransformer=true and post the log.

**Comment by MJRLegends** [comment]
@micdoodle8 ok i will test in a few hours when i get back at my computer

**Comment by MJRLegends** [comment]
@micdoodle8 I just managed to test before i went out and seems to be fixed thanks :D
