### ISSUE TITLE
Tinkers Tools, changing every version

### ISSUE THREAD

**Issue by AntonioNoack** [micdoodle8/Galacticraft#2472]
I know there is such a thing already in planning, still a lot of my (Miner952x) tools on the EU-Server and some of Fifa12343 are broken, e.g. Rubracium and Awakened Draconium instead of Obsidian and Draconium. It would be nice if you could fix those tools...
and maybe prevent future changes

**Comment by radfast** [comment]
?

**Comment by radfast** [comment]
Did you mean to write this on Galacticraft?

**Comment by AntonioNoack** [comment]
Oh sorry xD
I wanted to write it to the modpack GTNH

**Comment by Dream-Master** [comment]
:)
