### ISSUE TITLE
Can't create a space station in survival

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#2478]
(ref.: https://forum.micdoodle8.com/index.php?threads/space-station-in-release-1-7-3-0-12-4xx.6638/ for 1.7.10)

Not much to say. In 1.8.9 (GalacticraftCore-1.8.9-4.0.0.45-BETA), I couldn't create a space station in survival mode, even with the right materials in inventory. You can hover your mouse over "Create" button (en_US), it highlights, but it's unresponsive.

I managed to create the SS in creative. But attempting to access it crashed the game with `NullPointerException: Exception in server tick loop`:

```
[Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$WorldTickEvent@7ee4a02b:
java.lang.NullPointerException
```
https://gist.github.com/EzerArch/bb1b649d62a635c7380a70a19e3b31df

I need to test it in 1.7.10.

![2017-03-25_22 40 43](https://cloud.githubusercontent.com/assets/6743303/24327633/6df3d054-11ac-11e7-8346-f5393ac53db1.png)

**Comment by radfast** [comment]
Are you able to try build 51 beta?  This is fixed in 51 I think

**Comment by radfast** [comment]
Please give these a try :)  We're getting closer to a working release!  There are still many small visual bugs (things rendered too dark, etc) but anything at all you see not working, please do report it.

[GalacticraftCore - Build 51 BETA](http://s000.tinyupload.com/?file_id=11230490492988636701)
[Galacticraft-Planets - Build 51 BETA](http://s000.tinyupload.com/?file_id=22351709708209343342)
[MicdoodleCore - Build 51 BETA](http://s000.tinyupload.com/?file_id=00817994346948491205)

**Comment by radfast** [comment]
In the hope that that fixes it, I'm closing this - please reopen if any part of this issue is still present in build 51

**Comment by radfast** [comment]
[GalacticraftCore 1.8.9 BETA build 53](http://s000.tinyupload.com/index.php?file_id=11944996634729860845)
[Galacticraft-Planets 1.8.9 BETA build 53](http://s000.tinyupload.com/index.php?file_id=06371174299311120850)
[MicdoodleCore 1.8.9 BETA build 53](http://s000.tinyupload.com/index.php?file_id=57240117319544987561)
