### ISSUE TITLE
Crash when loading world

### ISSUE THREAD

**Issue by Mielsen7** [micdoodle8/Galacticraft#2479]
[Crash log](http://pastebin.com/ewLKCBWS)

**Comment by radfast** [comment]
This is a Bibliocraft crash, please report it to them.

It's just a coincidence that Bibliocraft crashed with this Galacticraft tile, I expect you would see the same crash with a tile from any mod in the same location, maybe even with a vanilla furnace there...

**Comment by radfast** [comment]
Respect for your mod list, it's more exciting than the normal!
