### ISSUE TITLE
[1.8.9+] Biome Tweaker crash with Galacticraft

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#2481]
Not sure about compatible with Biome Tweaker, RTG and BOP.

Crash Log : https://pastebin.com/hV3Rq9tv

Mod List
![untitled](https://cloud.githubusercontent.com/assets/6128413/24365189/48a9e272-133f-11e7-8117-1261df969819.png)

**Comment by radfast** [comment]
> Biome Tweaker, RTG and BOP.

Yes these are likely to be a problem with the mapping, I didn't test them fully yet!

Worst case, we can disable the mapping or switch it back to non-multithreaded like it is in 1.7.10.

**Comment by radfast** [comment]
This should be fixed in next build 64.  (Or else, where it would crash, the error is now trapped.  Let's see if we have compatibility with everything yet...)

**Comment by VOiDProXy** [comment]
Bumped into this error today running GalacticraftCore-1.10.2-4.0.0.69-BETA.jar

The cut error is [located here](https://hastebin.com/wiwezoneho.md).
The [full log is here, it's a ~4mb file.](https://www.dropbox.com/s/7zm9pr4jqs6eibw/fml-server-latest.log?dl=0)

**Comment by radfast** [comment]
thanks for reporting.  if you have a chance @VOiDProXy please test it on a copy of the same server **without RTG**.

**Comment by VOiDProXy** [comment]
Same error with RTG disabled.
[Error log here](https://hastebin.com/fupuwotiju.md)

**Comment by radfast** [comment]
ok, thanks very much for testing

I'll see what can be done about this.

For now, don't worry about it too much - it shouldn't really affect gameplay, it only means that the Display Screen map will not be shown.  (This will become more relevant for future planned features.)

**Comment by VOiDProXy** [comment]
Glad to help radfast, I appreciate your reply!

**Comment by VOiDProXy** [comment]
I turned off _both_ RTG and BiomeTweaker today (using GC 1.10.2-4.0.0.76-BETA) and was able to generate a "Overworld192.bin" under my world directory and not get this error.

I thought that now that MicDoodleCore has generated a snapshot-map of the overworld, it'll look past it's differences with RTG and BiomeTweaker. Unfortunately when I started the server with RTG and BiomeTweaker re-enabled, the error came back.
I suppose the mapgen wants to maintain a fresh image of the overworld for accuracy :) I figured I'd share my discoveries - This error doesn't affect launching into space and the mod still works perfectly despite this bug.

**Comment by radfast** [comment]
The mapgen will also be trying to generate a smaller local map whenever you place a new Display Screen (or whenever there's a Display Screen in a loaded chunk which doesn't yet have a local map)

So yes it will often be generating a map.  (Should be no noticeable impact on server performance, as long as you have a spare core on your CPU - but you might see the game using 75% CPU instead of 50%, basically our mapgen redlines 1 core.)

Also... Overworld192.bin is the small map which generates in 10-15 seconds.  That's not the Overworld map, which can take an hour or longer to generate in the background from server start.

**Comment by radfast** [comment]
![large](https://cloud.githubusercontent.com/assets/6842258/25551070/782e5bc6-2c77-11e7-9c75-a743eab39c69.jpg)


That's an example of the Overworld map generated once a server has been running for 1 hour+

**Comment by radfast** [comment]
I plan for that eventually to become something like this ingame - need to mute down the colours a bit, they are too garish currently

![after](https://cloud.githubusercontent.com/assets/6842258/25551126/44f1a320-2c78-11e7-891b-9696ace93632.jpg)

**Comment by dj3520** [comment]
this makes me excited

**Comment by VOiDProXy** [comment]
Really cool @radfast
