### ISSUE TITLE
[Question] About 1.8.9 & 1.10.2 (& Kinda 1.11.2)

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft#2483]
@micdoodle8 

Whats your thoughts on having the 1.8.9 and 1.10.2 versions setup on Jenkins (And maybe the 1.11.2 version two when that one becomes ready for a beta or even alpha release), i say this because i think it will benefit everyone because more up to date versions can be tested and bugs can be found out as development goes on where as regular release would bring all possible bugs to be reported at once. Having them on Jenkins will be there not official releases as such as their not on micdoodle8.com they would be beta versions, so it wouldn't be all the public using them only a certain amount. In till they are fully ready for full public release.

Also it would benefit addon developers to use new features and would allow 1.10.2 addon makers to release a test/beta version for their own development testing via the public.

You dont have to put them on Jenkins by all means just wanted to express my thoughts :P 

I would be very grateful if we could come to some agreement :D

cc @radfast

**Comment by radfast** [comment]
Closing this.   You have "Star Modpack maker" status (and Star Addon maker status) and your long-standing support for Galacticraft is awesome - but even so I think this is not a suitable issue for the Github issues list!  I'll still try to answer you, and happy to have your comments in reply.

I can't speak for micdoodle8 but for me the position is like this.  Galacticraft is a great project which I love, but I also have a full time job and other real life stuff which requires my time.  This means I have limited time each day for Galacticraft, an hour or two each day on average, maybe more at weekends.  (To do even this much, I give up personal time for Galacticraft which other people maybe spend gaming, or watching TV or movies.  For example, although I love scifi movies, I have not yet seen _Arrival_, or _Passengers_, or _Star Trek Beyond_, or even _Rogue One: A Star Wars Story_ - I literally have not had the spare 3 hours to go out to a movie theater or to acquire and watch a DVD.)

Answering questions and issue reports from players, and trying to figure out and resolve issues, takes up a good fraction of that 1-2 hours which I have for Galacticraft each day.  I think it's important to investigate and resolve issues, someone has to do it, and it's part of producing a high quality mod - and I reckon for every person reporting an issue there must be at least 100 people suffering the issue but not reporting it.

But at this stage, 1.8.9 is in Beta, and 1.10.2 and 1.11.2 are I guess in early Alpha, and there are many fairly obvious issues in them which we are aware of and will be fixing.  It's great that some experienced long-standing members of the Galacticraft community are now trying these versions out and reporting issues.  But at this stage, I would not want to open these up as "open Betas" and receive maybe 10x as many issue reports, crash reports, and other mod compatibility issues etc.  We will be ready to do that fairly soon, I think, with 1.8.9 - but not right now.

If we make these versions openly available to anyone who knows the URL for our Jenkins, then basically that's an open Beta.  There are also several "Modded Minecraft" type websites which regularly steal downloads from our Jenkins, rename them to something like "Galacticraft-latest", and then make them available for anyone to download who knows how to type "Galacticraft" into Google.

For myself, I'm happy with the position right now where:
* addon developers can test the code by building Galacticraft for themselves from the sources
* some people have access to the betas (actually anyone who reads all the issue reports here can find links to them, I posted some links earlier this week)
* everyone else will have to wait a bit longer.

If you need a copy of the latest 1.8.9 build for testing, you're welcome to ask, you have my email.  For now you will need to build 1.10.2 and 1.11.2 for yourself, I think, or maybe micdoodle8 can help you with these.

**Comment by MJRLegends** [comment]
@radfast No problem, i just wanted to get your thoughts on the question/idea. It would be very helpful if possible please a new 1.8.9 beta release for the public as i cant release my update for 1.8.9 due to the amazing advancements of the 1.8.9 GC versions.

**Comment by radfast** [comment]
I think it will be _at least_ a week or two before we can do a public beta release, maybe longer

But for coding purposes, I think the core codebase and API for 1.8.9 will not change much now.

**Comment by MJRLegends** [comment]
@radfast Ok no problem
