### ISSUE TITLE
[1.8.9] Missing block/item recipes

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#2484]
Including :
~Painter (Still WIP, I know.)~
~Space Glass (Vanilla, Clear and Strong) Metadata 1 (WIP?)~
~Fluid Tank~
~Fluid Pipe~
~Pre-launch Checklist~ (Will be given to players automatically)
Geothermal Generator
~Shield Controller~ (Treasure Item)
~Tier 2 Thermal Armor~
Communication Dish (WIP)

**Comment by radfast** [comment]
> Space Glass (Vanilla, Clear and Strong) Metadata 1 (WIP?)
This is intended to have no recipe.  The blocks can be found, in-game, in the new Abandoned Base in the Asteroids dimension.

**Comment by radfast** [comment]
All intended recipes are now in the game.

Micdoodle8 is still working on the Pre-launch Checklist, but this will be a book item given to players by certain triggers (similar to the Tinker's Construct books)
