### ISSUE TITLE
[1.8] Crashing when placed in server

### ISSUE THREAD

**Issue by leveljaap** [micdoodle8/Galacticraft#2485]
Hello,

As Galacticraft is one of my favorite mods I decided to test it in a server. This resulted in a crash. Everything is working fine on singleplayer but the server won't start. Here is the crash log:
[https://pastebin.com/QGib7KCy](url)
Could you please fix this, I would love to have this mod on my server. 

Thank you very much,
Leveljaap

**Comment by radfast** [comment]
Please provide log, the pastebin link gives a 404 error.

**Comment by micdoodle8** [comment]
This should be fixed using the latest build (45) available here:

https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-beta-testers.6555/
