### ISSUE TITLE
[1.8] Mod not working, not sure why

### ISSUE THREAD

**Issue by leveljaap** [micdoodle8/Galacticraft#2486]
Hello,

Last time there was an issue with the server not starting with the mod. That is fixed now, but the client doesn't start anymore. This is the mods list:
![2017-04-02 1](https://cloud.githubusercontent.com/assets/19862248/24586947/960b6f9c-17ac-11e7-9284-337a0d630357.png)
I would love to have this mod in my server so could you please take a look at it?

Thank you very much,
Leveljaap

**Comment by leveljaap** [comment]
Nevermind it is working now but I had to download Galacticraft Planets for it. That's kind of disappointing since I did not want the extra planets, just the rockets so that I could travel faster between dimensions. Could you please make a version that works without Galacticraft Planets?

Thank you very much,
Leveljaap

**Comment by radfast** [comment]
Please post fml-client log from the time when it failed to start.

**Comment by radfast** [comment]
If you want Tier 2 and Tier 3 rockets then yes you will have to download Galacticraft Planets, as those rockets are part of Galacticraft Planets.

Please also note that 1.8.9 is currently BETA so some things may not currently be working, and some things will change.  It is not yet ready for play on a public multiplayer server.  If you are running a multiplayer server, it will be sending to wait 3-4 weeks for a later release of Galacticraft.

**Comment by radfast** [comment]
https://wiki.micdoodle8.com/wiki/Compatibility More Player Models is incompatible with Galacticraft and not recommended

https://wiki.micdoodle8.com/wiki/Game_Balance
https://wiki.micdoodle8.com/wiki/Config

**Comment by leveljaap** [comment]
Is there a way to disable the planets but still have the Tier 2 and Tier 3 stuff? That would be really nice...
If it isn't possible, could you make a special version of Galacticraft without any extra dimensions? I don't think I'm the only one who would like a version with just the stuff.

Thank you very much,
Leveljaap

**Comment by radfast** [comment]
I don't think you understand the purpose of this Issues list!

It's not for you to request custom versions of our mod.  It's for you to report issues with the mod to us, which we can then look at fixing.

> Please post fml-client log from the time when it failed to start.

**Comment by leveljaap** [comment]
I'm sorry to comment again on the wrong section, but I want to explain my request.
Crafting is disabled on my server. Everything works with npcs. It's like Minetopia. That's why nobody needs the schematics for the rockets. And because of the dimensions the server is slower. So I'd still like this version to come.

Thank you very much,
Leveljaap

**Comment by radfast** [comment]
> And because of the dimensions the server is slower. 

This is incorrect.  Galacticraft dimensions do not make the server noticeably slower.

The version of Galacticraft you are requesting is not going to come.  Your request is specific to your unusual server setup, and contrary to our intentions for the mod.  Mars, Venus and Asteroids are integral to Galacticraft's gameplay and progression.
