### ISSUE TITLE
[1.8] Extracting and inserting things not possible

### ISSUE THREAD

**Issue by leveljaap** [micdoodle8/Galacticraft#2487]
I don't know if this is a known bug but lately I noticed that I couldn't extract and insert stuff in blocks like cargo (un)loaders and fuel loaders. Automatic systems are very hard/impossible to create like this. Could this please be fixed soon? And compatibility with buildcraft like in 1.7.10 would also be very nice (inserting fuel in fuel loaders using fluid pipes and stuff like that).

Thank you very much,
Leveljaap

**Comment by radfast** [comment]
https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md

Please provide:
* screenshots showing what you are attempting to do
* server log
* versions of all relevant mods

**Comment by leveljaap** [comment]
This is my mod list (client side):
![2017-04-03](https://cloud.githubusercontent.com/assets/19862248/24595679/357c5d70-1839-11e7-80f1-348cfe4acdd4.png)

Server side is without MorePlayerModels.

I was trying to make a system that inserted items in a cargo loader automatically, because my rocket launch platforms are a little high so I wanted to send the items through buildcraft transport pipes. But the pipes did not connect to the cargo loader:
![2017-04-03_07 42 25](https://cloud.githubusercontent.com/assets/19862248/24595758/ac841e94-1839-11e7-9b85-fbb5fdd9ebc1.png)
The pipes I used here were just stone transport pipes, I'm sure they worked before. Also, none of the other transport pipes worked.

I could also place a hopper on the block and connect the pipes to the hopper, I thought. But hoppers can't put anything in the cargo loaders either:
![2017-04-03_07 43 03](https://cloud.githubusercontent.com/assets/19862248/24595797/fbdb6614-1839-11e7-9f81-2b1bc265d896.png)
This dropper didn't insert anything in the cargo loader.

I thought that maybe ComputerCraft's turtles would work. They can put stuff in anything that has an inventory. But they couldn't insert items either:
![2017-04-03_07 43 51](https://cloud.githubusercontent.com/assets/19862248/24595831/3b3ddfd0-183a-11e7-8053-c6caa364042b.png)

I also wanted to let the fuel loader fill automatically by connecting fluid pipes with oil to the fuel loader. The pipes did connect but the fuel loader did not get filled.

I think the problem with the cargo (un)loaders is that nothing recognizes that is has an inventory. The fuel loaders don't recognize that they are being filled by oil pipes but the oil pipes do recognize that they are filling a fuel loader. 

Could these problems please be solved so that me and my friends can build automatic systems?

Thank you very much,
Leveljaap

**Comment by MJRLegends** [comment]
I can confirm I've experienced this issue before on 1.8.9 too just never got around to reporting it

**Comment by radfast** [comment]
These things are fixed now, the fixes will be in next build 52, available soon.

**Comment by radfast** [comment]
Please try these:

[GalacticraftCore 1.8.9 BETA build 53](http://s000.tinyupload.com/index.php?file_id=11944996634729860845)
[Galacticraft-Planets 1.8.9 BETA build 53](http://s000.tinyupload.com/index.php?file_id=06371174299311120850)
[MicdoodleCore 1.8.9 BETA build 53](http://s000.tinyupload.com/index.php?file_id=57240117319544987561)
