### ISSUE TITLE
[1.8] Worldgen hates SuperFlat

### ISSUE THREAD

**Issue by HyperMan19680** [micdoodle8/Galacticraft#2493]
[crash-2017-04-05_16.09.43-server.txt](https://github.com/micdoodle8/Galacticraft/files/900848/crash-2017-04-05_16.09.43-server.txt)

The crash mentions Oil in Desert, and I perfer the normal superflat worlds, so no desert biome means crash at the moment.

**Comment by radfast** [comment]
Thank you, this is basically the same issue as #2481

**Comment by radfast** [comment]
Thank you for testing this!  This should be working OK in next build 64.

Please comment or re-open if something like this happens again.
