### ISSUE TITLE
[1.8] Server crashing when I join

### ISSUE THREAD

**Issue by leveljaap** [micdoodle8/Galacticraft#2496]
Hello,

I have this issue that when I join my server, the server crashes (did not test if it also occured if others joined). Buildcraft seems to play a role too, and I will also report it to them. This happened right after I installed the new update to fix the bug that inserting and extracting items from Galacticraft weren't possible. Could you please take a look at this?
[crash-2017-04-06_22.11.59-server.txt](https://github.com/micdoodle8/Galacticraft/files/903861/crash-2017-04-06_22.11.59-server.txt)

Thank you in advance,
Leveljaap

**Comment by radfast** [comment]
Build 55 contains this fix.  Temporarily you can download this from here: https://wiki.micdoodle8.com/wiki/DownloadTemp

Please bear with us while we work on a number of issues.  We should have smoother access to the new versions by the end of this weekend.
