### ISSUE TITLE
Minecraft Launcher crashes when using Galacticraft

### ISSUE THREAD

**Issue by FearTheswoop** [micdoodle8/Galacticraft#2499]
I have tried all the most recent builds of Galacticraft and all of them cause Minecraft to crash when I try to launch the game.  I am not running any other mods, and even tried deleting everything and reinstalling the game, forge, and mods from scratch.  Launcher starts normally when not using Galacticraft mod.

MC Launcher version: 2.0.832

Forge version: 1.11.2-forge1.11.2-13.20.0.2265

Mod versions:
MicdoodleCore-1.7-3.0.12.465
Galacticraft-Planets-1.7-3.0.12.465
GalacticraftCore-1.7-3.0.12.465

Here is the launcher log from my most recent attempt: https://pastebin.com/5K00fwji

**Comment by SteveKunG** [comment]
> Mod versions:
MicdoodleCore-1.7-3.0.12.465
Galacticraft-Planets-1.7-3.0.12.465
GalacticraftCore-1.7-3.0.12.465

What??

**Comment by FearTheswoop** [comment]
Well that makes plenty of sense then!  I didn't know they had those newer versions in development.  I downloaded the the recommended stable builds from the mod website.  I'll check those out, thanks!

**Comment by dj3520** [comment]
If your issue is resolved please close it.
