### ISSUE TITLE
[1.8.9] Tier 1 dungeon key hasn't texture

### ISSUE THREAD

**Issue by gug2** [micdoodle8/Galacticraft#2503]
![2017-04-07_17 14 56](https://cloud.githubusercontent.com/assets/19577359/24801578/e23c1daa-1bb5-11e7-8f3f-3bda9b87fef2.png)

**Comment by radfast** [comment]
Thank you for beta testing!

Which version of 1.8.9?

I think maybe this has been fixed already in recent versions, please try version 61.  You can get it from [the forum](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555)

(note: if you're updating from an older beta version to this new version 61, you might need to make a new world - more info on that is on the forum thread)

Please **re-open** this if it's still a problem in the latest build 61.

**Comment by gug2** [comment]
build 61: Tier 1 dungeon key
![2017-04-10_09 26 35](https://cloud.githubusercontent.com/assets/19577359/24847105/eb48fbb8-1dcf-11e7-8b52-bae2c70b6afb.png)

**Comment by ThomasAunvik** [comment]
This needs to be reopened

**Comment by radfast** [comment]
ok I understand the issue now:
the key has texture in a chest, and in NEI/JEI, but not when it is **held**

That's a weird one, not seen before

Let's keep this together with the others on #2548 now, it's easier for me that way
