### ISSUE TITLE
[1.11.2] Dark screen while in F5 mode inside Rocket + another bug

### ISSUE THREAD

**Issue by ThomasAunvik** [micdoodle8/Galacticraft#2505]
Currently i used the creative rocket and i went F5 and the screen went a bit dark. Screenshots in minecraft seems to not render the darkness.

So, i will send a gif instead.
http://imgur.com/JqMPXrs

Forge Version: forge-1.11.2-13.20.0.2265
MicDoodleCore: 1.11.2-4.0.0.53-BETA
GalacticraftCore: 1.11.2-4.0.0.53-BETA
GalacticraftPlanets: 1.11.2-4.0.0.53-BETA

[ModList](https://pastebin.com/J7HsMHWQ)

Also the other bug is when you are high up and the rocket stops rendering for some reason

Here is a nice video of what happens w/ the other bugs.
[Video](https://youtu.be/gCYiQmFZr2I)

**Comment by ThomasAunvik** [comment]
A clean minecraft with only galacticraft seems not to make dark screen, but the rendering issue is still there.

**Comment by micdoodle8** [comment]
I think this was fixed somewhere along the way, I can't seem to recreate with build 58. Please re-open if the problem still occurs for you.
