### ISSUE TITLE
[1.11.2] Returning back to Overworld from Overworld crashes client server w/rocket

### ISSUE THREAD

**Issue by ThomasAunvik** [micdoodle8/Galacticraft#2506]
Forge Version: forge-1.11.2-13.20.0.2265
MicDoodleCore: 1.11.2-4.0.0.53-BETA
GalacticraftCore: 1.11.2-4.0.0.53-BETA
GalacticraftPlanets: 1.11.2-4.0.0.53-BETA

[ModList](https://pastebin.com/J7HsMHWQ)

[Crash](https://pastebin.com/zH4m17VX)

Here is a nice video of what happens w/ the other bugs.
[Video](https://youtu.be/gCYiQmFZr2I)

**Comment by MJRLegends** [comment]
Same as #2509

**Comment by micdoodle8** [comment]
Thanks, fixed in the next build.
