### ISSUE TITLE
[1.11.2] Walking on any gc dimension creates a huge error loop

### ISSUE THREAD

**Issue by ThomasAunvik** [micdoodle8/Galacticraft#2508]
When i went to mars it went alright, i landed and then i landed, i bounced and bounced, after i bounced a little more i exited just before it finished bouncing (pressed shift) and just after that i had a massive error loop.

I used a creative tier 3 rocket

Well, the latest.log is too huge, even gist.github.com cant handle it!
There are 1 222 365 lines of log... Ill give you some bits of them.

[Log From where i started going to mars](https://gist.github.com/ThomasAunvik/aa5e8f6da9a3d8401d2d6814ba6d886e)

[Log from line 1 221 888 to end](https://gist.github.com/ThomasAunvik/b9bcd0e7640b5adfca7f3539e677d0b1)

Edit:
After rejoining the world, it seems to do the same error loop after i move one block away from where i started.

Forge Version: forge-1.11.2-13.20.0.2265
MicDoodleCore: 1.11.2-4.0.0.53-BETA
GalacticraftCore: 1.11.2-4.0.0.53-BETA
GalacticraftPlanets: 1.11.2-4.0.0.53-BETA

[ModList](https://pastebin.com/J7HsMHWQ)

**Comment by ThomasAunvik** [comment]
Ok, another bug as the same

**Comment by ThomasAunvik** [comment]
Ok, so i tried this. I teleported to cord 0,0,0 in mars, and it worked. So i could fly around underground until i broke the bedrock. Then i got the error loop again.

**Comment by MJRLegends** [comment]
Seems your getting a issue with the OverlayRocket.renderSpaceshipOverlay(OverlayRocket.java:93) and your getting the other issue you reported (#2510) too in the logs you provided

**Comment by micdoodle8** [comment]
Thanks Thomas and MJR, fixed in the next build.
