### ISSUE TITLE
[1.11.2] Building in the spacestation creates an error loop

### ISSUE THREAD

**Issue by ThomasAunvik** [micdoodle8/Galacticraft#2510]
Another error loop. Still it is a very huge one.
Just this is a bit different than #2508 

This log is cutted alot in the middle, so i just added the first few thousand lines on both of the ends.
[Client Log](https://gist.github.com/ThomasAunvik/21a7edb6ac338647b0940fb33b2ee0b2)

Forge Version: forge-1.11.2-13.20.0.2265
MicDoodleCore: 1.11.2-4.0.0.53-BETA
GalacticraftCore: 1.11.2-4.0.0.53-BETA
GalacticraftPlanets: 1.11.2-4.0.0.53-BETA

[ModList](https://pastebin.com/J7HsMHWQ)

**Comment by MJRLegends** [comment]
I believe this is due to the Galacticraft sounds that are trying to be played, im sure they can fix this :D

**Comment by micdoodle8** [comment]
Thanks, fixed in the next build.
