### ISSUE TITLE
[1.11.2] Going to Venus crashes client server

### ISSUE THREAD

**Issue by ThomasAunvik** [micdoodle8/Galacticraft#2513]
Currently unable to rejoin the world. Beacuse of crash
[Crash Log](https://pastebin.com/954a2H4H)

Forge Version: forge-1.11.2-13.20.0.2265
MicDoodleCore: 1.11.2-4.0.0.53-BETA
GalacticraftCore: 1.11.2-4.0.0.53-BETA
GalacticraftPlanets: 1.11.2-4.0.0.53-BETA

**Comment by radfast** [comment]
@ThomasAunvik  bugtester extraordinaire!

Please can I suggest you take a break and leave this for a day or so now, we will need some time to fix the issues posted. :)

**Comment by dj3520** [comment]
>bugtester extraordinaire!

Makes me want to try GC4 (honestly haven't touched it)

**Comment by micdoodle8** [comment]
Thanks again, fixed in the next build.
