### ISSUE TITLE
[1.11.2] Buggy does not have a texture

### ISSUE THREAD

**Issue by ThomasAunvik** [micdoodle8/Galacticraft#2514]
![Buggy](http://i.imgur.com/MzcEwnb.png)

Unrelated note:
This will be the last one for today, i will do some for tomorrow

**Comment by MJRLegends** [comment]
I believe this has already been reported see issue #2492

**Comment by radfast** [comment]
Yes, thank you this one is fixed, just a bit of lag getting the fix into the 1.11 version.

**Comment by radfast** [comment]
It's really helpful to get a lot of issues on the first day, should help us to get fixes out quickly, so thank you for a great job.
