### ISSUE TITLE
[1.11.2] Energy Beam does not render its "beam"

### ISSUE THREAD

**Issue by ThomasAunvik** [micdoodle8/Galacticraft#2519]
The Energy Beam Receiver works as normal, but it does not render its "beam"
![Energy](http://i.imgur.com/vRC5cTe.png)
![Beam](http://i.imgur.com/0c0bF0A.png)

**Comment by micdoodle8** [comment]
I think this might've been fixed somewhere along the way, as I can't seem to recreate it now.

Please re-open if this bug still exists.
