### ISSUE TITLE
[1.10] World freezing and crashing after a couple of seconds on the moon

### ISSUE THREAD

**Issue by ErnestoPeroPezzi** [micdoodle8/Galacticraft#2522]
[crash-2017-04-08_11.20.35-server.txt](https://github.com/micdoodle8/Galacticraft/files/907554/crash-2017-04-08_11.20.35-server.txt)

Pastebin link: https://pastebin.com/LevGe94r

**Comment by radfast** [comment]
This is a dungeon generation issue affecting all GC4 versions and Moon, Mars and Venus.

Working on a fix...

(In this case, an existing issue has been made perhaps worse by these other mods running their worldgen on the Moon: **ActuallyAdditions** and **Dendrology**, so you could also try testing without those.)

**Comment by radfast** [comment]
This is fixed in next build 58.  Thanks again for reporting.

**Comment by radfast** [comment]
Build 61 now available at the [forum](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/)

**Comment by radfast** [comment]
[build 63](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/) is now available
