### ISSUE TITLE
[1.8.9] When rocket launches, it glitches a huge amount.

### ISSUE THREAD

**Issue by Ironspider0** [micdoodle8/Galacticraft#2523]
When the rocket launches, the rocket goes black, the flames at the bottom partially disappear and the camera goes crazy. I have tried to get a picture, but now my rocket won't launch.

**Comment by radfast** [comment]
Which type of rocket?
Which dimension are you launching from?
Please list other mods installed - or better, provide your fml-client-latest.log so we can see everything about your setup.

**Comment by radfast** [comment]
Please help the beta program by responding!

Please also let us know whether this is still a problem in the latest builds 78 / 79?

**Comment by radfast** [comment]
This issue is likely fixed in the next build 96.

If it's still a problem in build 96, please comment or re-open (and if doing that, please give more info as requested!)
