### ISSUE TITLE
[1.10.2] Crash with IC2 Classic

### ISSUE THREAD

**Issue by NanoHeart** [micdoodle8/Galacticraft#2525]
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from IndustrialCraft 2 Classic (IC2)
Caused by: java.lang.IllegalArgumentException: Duplicate id: Geothermal Generator

There isn't really a good way to test this, as IC2Classic isn't available to the public, and if you aren't on a whitelist the mod will crash your client on launch ^^; 

Changing the mod id should fix the issue

**Comment by radfast** [comment]
Thank you for beta testing!  This is fixed from next build 58, probably available at the forum later today or tomorrow.

**Comment by radfast** [comment]
Build 61 now available at the [forum](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/)

**Comment by radfast** [comment]
[build 63](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/) is now available - fully compatible with IC2 experimental (all power transfers work), but I haven't tested it fully with IC2 classic
