### ISSUE TITLE
[1.8.9] Client gets disconnected when opening/using/placing Inventory, chests, blocks.

### ISSUE THREAD

**Issue by NevCrow** [micdoodle8/Galacticraft#2527]
https://fyfox.xyz/fml-client-latest.log
edit: 
I have got IC2 and other mods, but worked fine before GC

**Comment by micdoodle8** [comment]
Looks like the error occurs on the server side, do you have access to that log?

**Comment by NevCrow** [comment]
https://fyfox.xyz/fml-client-latest.log

**Comment by micdoodle8** [comment]
That's the same client side log, I need the server thread output

**Comment by leveljaap** [comment]
Hi I have the same problem. This is the log:
[latest.txt](https://github.com/micdoodle8/Galacticraft/files/908008/latest.txt)
I had to change the extension to .txt to upload it

**Comment by micdoodle8** [comment]
The file I need is called fml-server-latest in the logs folder

**Comment by NevCrow** [comment]
https://fyfox.xyz/fml-server-3.log sorry I was tired

**Comment by radfast** [comment]
Thanks for the log, we should be able to fix this!

**Comment by NevCrow** [comment]
Alright, can you confirm if that is the correct log?

**Comment by radfast** [comment]
The log shows an important issue with Galacticraft on dedicated servers.  I don't know if this is the **only** issue here, but let's fix this and see if that means players can open chests.

I ishould be able to get a build 59 up in the next 10 minutes, would be great if you can test it and confirm the problem is fixed.

**Comment by NevCrow** [comment]
Alright thank you.

**Comment by radfast** [comment]
I'll give you the links to build 59 shortly, just waiting for the build to finish.

**Comment by NevCrow** [comment]
Alright

**Comment by radfast** [comment]
Build 59 now available to download from [here](https://wiki.micdoodle8.com/wiki/DownloadTemp)

**Comment by NevCrow** [comment]
Is it possible to upload it to google drive or Dropbox due to the hour limit thing.

**Comment by radfast** [comment]
yes, sorry I wasn't aware of this hour limit thing, that's a pain!

**Comment by NevCrow** [comment]
Its fine, I managed to download Gcore, using my vpn to download planets.

**Comment by NevCrow** [comment]
nvm, cant download planets.

**Comment by radfast** [comment]
I'm going to put Planets and MicdoodleCore on Google Drive and change the links.

Seems like FileFactory should be OK if people only download one file from it.

**Comment by radfast** [comment]
OK please refresh that Wiki page, the new links to GoogleDrive are now up.

**Comment by NevCrow** [comment]
Same error: https://fyfox.xyz/fml-server-new.log (server) Do you need the client one as well?

**Comment by radfast** [comment]
no, that's ok thanks - this is an error on the server.  It's only happening on dedicated servers.

That update to 59 has changed things, something different is happening now but I can see that it still isn't fixed.  Sorry about this.  The reasons are a bit obscure but I think we had something similar 2 years ago, I'm looking back to see how we fixed it then.

**Comment by NevCrow** [comment]
Alright, take your time

**Comment by NevCrow** [comment]
Do you need a server to test on?

**Comment by radfast** [comment]
Would be great if you can test build 60.  Get it from the same [wiki download page](https://wiki.micdoodle8.com/wiki/DownloadTemp) - all links now direct downloads from Google Drive.

**Comment by NevCrow** [comment]
Now uploading

**Comment by NevCrow** [comment]
Alright, it lets me place blocks, use inventory. Attempting to go to moon now

**Comment by radfast** [comment]
nice.  1.8.9 should be reasonably stable, I've been testing it myself for 4 weeks, but if you have any more issues please do let us know.

**Comment by NevCrow** [comment]
okay, everything is working perfectly fine, will report back if any issues. Thanks for fixing it.

**Comment by radfast** [comment]
Build 61 now available at the [forum](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/)

**Comment by NevCrow** [comment]
Is there a changelog?

**Comment by radfast** [comment]
not publicly.  But you can review the commits [here](https://github.com/micdoodle8/Galacticraft/commits/master).   What you can't see from that is which is version 58, which is version 61 etc.   Does it matter?  While we are in beta testing there are probably going to be daily changes to Galacticraft, at least through April.
