### ISSUE TITLE
[1.11.2] Arc Lamp bug

### ISSUE THREAD

**Issue by ThomasAunvik** [micdoodle8/Galacticraft#2528]
What happens is a bit hard to explain. Also, i think the rendering of the arc lamp is bugged.
When arc lamp is placed on the ground it rotates the rendering of the block. And the hitbox is wrong.

To recreate the second image you need to right click the hitbox that is in the first image.

Forge Version: 13.20.2279
Galacticraft Core: 4.0.0.58
Galacticraft-Planets: 4.0.0.58
Micdoodlecore: 4.0.0.58

Images:
![1](http://i.imgur.com/GYsRNi8.png)
![2](http://i.imgur.com/Z1nj5Ah.png)
![3](http://i.imgur.com/lDRdsQ5.png)
![4](http://i.imgur.com/Ek8mxVZ.png)

**Comment by radfast** [comment]
thanks for reporting, looks like something broke in conversion from 1.8.9 to 1.10+ ...

**Comment by radfast** [comment]
The baseplate should be in the correct position in version 61 and later.

The actual lamp not rendering is the issue which remains.

**Comment by ThomasAunvik** [comment]
Seems when breaking the lamp creates a lighting issue.
Here are some examples:
![Imgur](http://i.imgur.com/bVqXxd4.png)
![Imgur](http://i.imgur.com/CuuzEb0.png)

**Comment by tabepic** [comment]
I believe that the bug exists in 1.10.2 also.
![2017-04-10_12 25 30](https://cloud.githubusercontent.com/assets/9892196/24876518/3c9d3ef2-1de9-11e7-8a9e-44f07eca26f9.png)

**Comment by radfast** [comment]
that's weird, Arc Lamps are fine for me in 1.10.2

do you guys have Optifine or other mods affecting rendering of everything?

**Comment by ThomasAunvik** [comment]
No, i am only using GC Build 61

**Comment by tabepic** [comment]
Same here

**Comment by tabepic** [comment]
In Build 66, I see it every once in a while, and then I'll move or look around, and it will disappear again
![Screenshot 1](https://cloud.githubusercontent.com/assets/9892196/25074388/e41cd788-22b6-11e7-8d1f-82a511dbb740.png)
![Screenshot 2](https://cloud.githubusercontent.com/assets/9892196/25074389/e41e3b00-22b6-11e7-87fd-f863125db7f0.png)

**Comment by radfast** [comment]
This is very helpful, thank you.

**Comment by radfast** [comment]
Now fixed.

[Build 69 with Sponge compatibility](https://ci.micdoodle8.com/job/Galacticraft-1.10/) is now available.

**Comment by ThomasAunvik** [comment]
Does not support 1.11.2...
