### ISSUE TITLE
[Suggestion] Gravity Controller

### ISSUE THREAD

**Issue by ThomasAunvik** [micdoodle8/Galacticraft#2530]
Gravity Controller, a thing that adds gravity in the spacestation. My idea is that it will work the same as an oxygen sealer, just only with power. If the area is sealed it will add gravity to that area.

Or the gravity controller can work the same as an Oxygen Bubble Distributor

**Comment by radfast** [comment]
Thank you.  There is discussion of similar suggestions on the forum...

We can maybe think about this, but it depends on something else planned for GC4 which is not yet implemented ... I hope you will see what I mean in ~ 1 month from now ... !
