### ISSUE TITLE
[1.11.2] Breaking a part of Air Lock will not remove the Air Lock Seals

### ISSUE THREAD

**Issue by ThomasAunvik** [micdoodle8/Galacticraft#2532]
By breaking one of the Air Lock Frame (Not the Air Lock Controller) will not remove the Air Lock Seals. As Air Lock Seals are unbreakable you cannot pass unless you remove the air lock controller or place the air lock frame back.

Forge Version: 13.20.2279
Galacticraft Core: 4.0.0.58
Galacticraft-Planets: 4.0.0.58
Micdoodlecore: 4.0.0.58

![1](http://i.imgur.com/46yKEnH.png)
![2](http://i.imgur.com/TpSwmMi.png)

**Comment by EzerArch** [comment]
Also happens in 1.7.10 but the seal blocks don't rotate.

**Comment by ThomasAunvik** [comment]
Seems a part of the bug has been fixed. But it still wont remove all the seal blocks.
