### ISSUE TITLE
[1.11.2] Dense Ice texture is broken

### ISSUE THREAD

**Issue by ThomasAunvik** [micdoodle8/Galacticraft#2534]
Forge Version: 13.20.2279
Galacticraft Core: 4.0.0.58
Galacticraft-Planets: 4.0.0.58
Micdoodlecore: 4.0.0.58

Not really much to explain, but here are some images of it.

Here is a gif that show a bit more: [GIF](http://imgur.com/zLFwD9K)

![1](http://i.imgur.com/gny5VGB.png)
![2](http://i.imgur.com/SmWGKxa.png)
![3](http://i.imgur.com/fepGVdR.png)
![4](http://i.imgur.com/r7wnfaH.png)

**Comment by radfast** [comment]
Thank you for reporting and the screenshots :)

Fixed in 1.10, this fix will be picked up in the next build of 1.11.2 as well.

**Comment by radfast** [comment]
Build 61 now available at the [forum](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/)
