### ISSUE TITLE
[1.11.2] Player inventory tab incorrectly rendering parachute on player

### ISSUE THREAD

**Issue by Agentx49** [micdoodle8/Galacticraft#2536]
![errors](https://cloud.githubusercontent.com/assets/26726223/24837666/54a848c6-1d07-11e7-8663-8079304e11a1.PNG)
![errors1](https://cloud.githubusercontent.com/assets/26726223/24837667/54a9405a-1d07-11e7-99c8-046129b819e8.PNG)

**Comment by Agentx49** [comment]
mod list:  galacticraft, extra utilites, custom npcs, optifine

**Comment by ThomasAunvik** [comment]
I have also noticed this too. Just forgot to report it.

**Comment by Agentx49** [comment]
also i cant jump or go into f5 also they dont go away if you take the gear off

**Comment by radfast** [comment]
This is partly #2497  (overlap between Galacticraft and CustomNPCs tabs)

The parachute issue is a separate issue though.

**Comment by Agentx49** [comment]
also i cant jump or go into f5 also they dont go away if you take the gear off

**Comment by ThomasAunvik** [comment]
Rejoining seem to fix the issue. But re-equipping them make it happen again.

**Comment by radfast** [comment]
This is part of a group of errors which show that Galacticraft is not accessing its own extended inventory properly, in 1.11.2.

This definitely needs some attention!

**Comment by micdoodle8** [comment]
Fixed in the next build. Thank you!

**Comment by radfast** [comment]
[build 66 now available](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/#post-43135)
