### ISSUE TITLE
Shift Clicking Items into Rocket (v1.11.2 Build 58)

### ISSUE THREAD

**Issue by SportsFan10** [micdoodle8/Galacticraft#2538]
MC Version: 1.11.2
Galacticraft Version: 1.11.2-4.0.0.58-BETA
Forge Version: 13.20.0.2279
Debug: Enabled

When shift clicking items into a rocket's inventory the game crashes.  This was tested using both a cargo rocket and a tier 3 rocket.  I'd assume the same would happen with Tiers 1 and 2.  

https://pastebin.com/pK0TXpUs

**Comment by radfast** [comment]
Thanks for beta testing :)

This seems to be a different issue from #2515

**Comment by SportsFan10** [comment]
Would you like me to get the crash report for every different type of Rocket like in the other issue or would they all be the same?

**Comment by radfast** [comment]
Likely all the same.  I'm going to leave this one for micdoodle8 to look at - I guess he might ask for some more info but probably that crash report should be enough.

**Comment by SportsFan10** [comment]
Sounds good!  Also not sure if it was meant to be fixed in build 58 but I noticed that shift clicking items into the GC inventory where oxygen and such is held still crashes.  I may have misinterpreted which build that would be fixed in however.  

Thanks for the Quick Replies!

**Comment by micdoodle8** [comment]
Hey, I believe this was fixed somewhere along the way, as I'm not getting any crash in build 64. Thanks for the report, if you're still having this particular crash feel free to re-open.
