### ISSUE TITLE
[1.11.2] Entity name needs to be updated

### ISSUE THREAD

**Issue by ThomasAunvik** [micdoodle8/Galacticraft#2540]
https://github.com/micdoodle8/Galacticraft/blob/MC1.11/src/main/resources/assets/galacticraftplanets/lang/en_US.lang#L14
As we see at this lang file, it is `entity.galacticraftplanets.creeper_boss.name=Evolved Creeper Boss` but what i see in the game is different. It is `entity.creeper_boss.name`

- [Evolved Spider](https://github.com/micdoodle8/Galacticraft/blob/MC1.11/src/main/resources/assets/galacticraftcore/lang/en_US.lang#L43)
- [Evolved Zombie](https://github.com/micdoodle8/Galacticraft/blob/MC1.11/src/main/resources/assets/galacticraftcore/lang/en_US.lang#L44)
- [Evolved Creeper](https://github.com/micdoodle8/Galacticraft/blob/MC1.11/src/main/resources/assets/galacticraftcore/lang/en_US.lang#L40)
- [Evolved Creeper Boss](https://github.com/micdoodle8/Galacticraft/blob/MC1.11/src/main/resources/assets/galacticraftplanets/lang/en_US.lang#L14)
- [Evolved Skeleton](https://github.com/micdoodle8/Galacticraft/blob/MC1.11/src/main/resources/assets/galacticraftcore/lang/en_US.lang#L41)
- [Evolved Skeleton Boss](https://github.com/micdoodle8/Galacticraft/blob/MC1.11/src/main/resources/assets/galacticraftcore/lang/en_US.lang#L42)
- [Alien Villager](https://github.com/micdoodle8/Galacticraft/blob/MC1.11/src/main/resources/assets/galacticraftcore/lang/en_US.lang#L37)
- [Sludgeling](https://github.com/micdoodle8/Galacticraft/blob/MC1.11/src/main/resources/assets/galacticraftplanets/lang/en_US.lang#L25)
- [Slimeling](https://github.com/micdoodle8/Galacticraft/blob/MC1.11/src/main/resources/assets/galacticraftplanets/lang/en_US.lang#L24)

![1](http://i.imgur.com/C2q06AL.png)
![2](http://i.imgur.com/Ki1Vx3v.png)

**Comment by radfast** [comment]
all the entities are in en_US!!  these ones are in galacticraftcore lang file

Evolved Spider (Is not inside en_US.lang)
Evolved Zombie (Is not inside en_US.lang)
Evolved Creeper (Is not inside en_US.lang)
Evolved Skeleton (Is not inside en_US.lang)
Evolved Skeleton Boss (Is not inside en_US.lang)
Alien Villager (Is not inside en_US.lang)

----

The entity name shown in vanilla-generated Spawn Eggs and Mob Spawners has been the unlocalized name from 1.8.9 and later, I haven't yet figured out why...

**Comment by radfast** [comment]
nice screenshots btw, though you really shouldn't have an Evolved Creeper Boss on Venus ;)

**Comment by ThomasAunvik** [comment]
Oh, seems i forgot that there were a core ;)

**Comment by radfast** [comment]
@ThomasAunvik  we found a solution, this should be fixed fully from next build 72

@EzerArch  I'm not sure about resource packs (especially resource packs which add other translations) - as you are the specialist in this area, can you kindly take a look and see if all seems to be working OK for you, next time you are playing 1.11.2  /  build 72?  I think it will be OK, certainly there's no problem about switching languages.  (I also switched to Pirate Speak to try out a language we don't - currently - have in Galacticraft ...)

**Comment by radfast** [comment]
[Build 73](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/) is now available with this fix
