### ISSUE TITLE
[1.8.9] Buildcraft's Fluid Pipes not working on Fuel Loaders

### ISSUE THREAD

**Issue by leveljaap** [micdoodle8/Galacticraft#2542]
Hello,

I was trying to make an automatic rocket charging system. A buildcraft pump would be connected to a Fuel Loader using Fluid Pipes. When I tried to connect the pipes to the loader it did connect. However, when I tried to load fuel into the Fuel Loader, the Fuel Loader did not receive any fuel. Could you please take a look at this?

Thank you very much,
Leveljaap

**Comment by radfast** [comment]
Tested, the Buildcraft Fluid Pipes are working correctly **when connected to the Fuel input side** - that's the side with the black pipe input connection graphic.

Buildcraft Fluid Pipes "look" like they connect to the machine properly even when connected on a side where they can't transfer fluid.   So if you connect to the wrong side, it looks like it should maybe work, but it doesn't.

That's a Buildcraft problem, not Galacticraft problem.  If you use our own Fluid Pipes, or Fluid Pipes from another mod like Thermal Dynamics, you should see that they only correct on the Fuel input side.

I think a lot of people expect the Fuel input side is on the left side of this machine, but actually it's on the right side. See #2435 and older issues referenced there.

**Comment by radfast** [comment]
[Build 73](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/) is now available
