### ISSUE TITLE
[1.10.2] [Server] Empty world

### ISSUE THREAD

**Issue by tabepic** [micdoodle8/Galacticraft#2543]
After the countdown ends and the rocket leaves the ground, but before it escapes the atmosphere, the Minecraft Server crashes.
I tried to reproduce the bug in single player, but I couldn't.

Forge 12.18.3.2272
Mod list [here](https://pastebin.com/PvrVQAVL)
Galacticraft Version 58

**Comment by MJRLegends** [comment]
Crash log??

**Comment by ThomasAunvik** [comment]
Crash Log please

**Comment by tabepic** [comment]
Here it is: [https://pastebin.com/XTACNuzF](https://pastebin.com/XTACNuzF)

**Comment by radfast** [comment]
Thank you for beta testing.  That log really helped, this was a nasty little crash which I would never have found otherwise.

This will be fixed in next build 61.

**Comment by tabepic** [comment]
No problem :)

**Comment by radfast** [comment]
Build 61 now available at the [forum](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/)

**Comment by tabepic** [comment]
I tried it and now get this error: https://github.com/micdoodle8/Galacticraft/issues/2545

**Comment by radfast** [comment]
Like I said on 2545, please can you try without Optifine?

**Comment by tabepic** [comment]
it works fine now, I just forgot to remove the old build of Galanticraft

**Comment by radfast** [comment]
ok cool, thanks for letting me know - maybe this can also help the other guy
