### ISSUE TITLE
[1.10.2] Minecraft won't start

### ISSUE THREAD

**Issue by tabepic** [micdoodle8/Galacticraft#2545]
Minecraft crashes while loading (before window appears)

Crash log: [https://pastebin.com/GMrqrA0Y](https://pastebin.com/GMrqrA0Y)
Forge 12.18.3.2272
Mod list: [https://pastebin.com/XYUhasX8](https://pastebin.com/XYUhasX8)
Galacticraft Build 61

**Comment by radfast** [comment]
hmm, other people have been able to run it OK, so I think it must be an incompatibility with one of your other mods

Please can you retry Galacticraft 1.10.2 without some of these other mods - just take them temporarily out of your ```/mods``` folder and see if Minecraft starts without them.  (Make a new world for testing, your world can be damaged by swapping mods around.)

I would look first at removing:
* **Optifine** - the most likely cause
* **Fybertech / NWR (NowWithRendering?)**  - I don't even know what this is
* **Shadowfacts / Forgelin** - again I don't know what this is

**Comment by tabepic** [comment]
will do, however i don't know what NowWithRendering is either

**Comment by radfast** [comment]
In case @micdoodle8 is looking at this, the key to this crash is here:
>
   at org.objectweb.asm.tree.InsnList.get(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
    at micdoodle8.mods.miccore.MicdoodleTransformer.transformWorld(MicdoodleTransformer.java:1346) ~[MicdoodleCore-1.10.2-4.0.0.58-BETA.jar:?]

**Comment by radfast** [comment]
> however i don't know what NowWithRendering is either

I mean this:  net.fybertech.nwr.NWRTweak
I don't know the .jar file name.  But I think NWR means Now With Rendering...

**Comment by tabepic** [comment]
I feel like an idiot: i forgot to remove the old versions of Galanticraft

**Comment by radfast** [comment]
OK, yes it looks like we're conflicting with ourselves here then :)

Actually this is super helpful, because we can trap this specific error and pop up a box saying "you haven't removed your old Galacticraft".  (I don't know why Forge didn't detect that already, maybe a coremods thing going on here.)
