### ISSUE TITLE
[1.11.2] Buggy Bugs

### ISSUE THREAD

**Issue by ThomasAunvik** [micdoodle8/Galacticraft#2551]
Me just playing.
Best to watch the video to understand everything!
[VIDEO!](https://youtu.be/ge-PCCXROHI)

[Log File w/GC Debug Mode](https://pastebin.com/kaH8PAPG)

Also, when spamming the jump button the screen is zooming in and out just like if you are running and stop running and so on.

**Comment by micdoodle8** [comment]
Fixed the buggy wheel issue. I'm not seeing the problem with the fuel loader though, is the issue that it says "Running" when there's no fueling pad attached?

**Comment by ThomasAunvik** [comment]
No, there is nothing wrong with the fuel loader.

Note: The only issue left seems to be: When spawning the buggy directly ontop of the Buggy Fueling Pad making the player unable to ride it.
