### ISSUE TITLE
[1.11.2] Launch controller Redstone launch not working on all sides

### ISSUE THREAD

**Issue by ThomasAunvik** [micdoodle8/Galacticraft#2552]
When trying to launch with the criteria of having a redstone signal is not working.
![1](http://i.imgur.com/CT7rgTQ.png)
![2](http://i.imgur.com/fI5agCD.png)

Edit:
Seems the only redstone input is the bottom of the block

**Comment by SportsFan10** [comment]
I noticed this as well.  In an earlier build I was able to use a lever leading to a redstone path into the controller and was able to get it to work.

**Comment by radfast** [comment]
Yes, at present the Launch Controller requires to be [strongly powered](http://minecraft.gamepedia.com/Redstone_circuit#Power) - meaning redstone wire pointing into it, or a redstone torch below it, or a lever on the side of the Launch Controller block itself.

I felt that launching a Rocket is such a major event that, to prevent accidents, it should be this way, as some bases do have stray redstone "weak power" in spots where players don't realise.

But in Galacticraft we kind of _like_ for there to be situations where players can have space-related accidents, so I think we should change this.
