### ISSUE TITLE
[1.11.2] Middle mouse click on some GC Machines gives untextured block (Creative)

### ISSUE THREAD

**Issue by ThomasAunvik** [micdoodle8/Galacticraft#2553]
Build 61

When i press middle mouse button, the button to copy the block the block you are looking at is not working correctly.

For example, Middle Mouse click on a Cargo Loader gives me a block without texture and description when pressing shift.

**List of Blocks:**
- Cargo Loader
- Gas Liquifier
- Water Electrolyzer
- Methane Synthesizer

I can place the blocks without texture with no problem.
Example:
![Imgur](http://i.imgur.com/mYoa1gx.png)
![Imgur](http://i.imgur.com/GZWxKSW.png)

**Comment by radfast** [comment]
Thank you, this will be fixed in next build 62.

Your super-precise error reports are **extremely** helpful, thank you for all these!

**Comment by radfast** [comment]
[build 63](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/) is now available
