### ISSUE TITLE
[1.10.2] Client crashes when going to Venus

### ISSUE THREAD

**Issue by tabepic** [micdoodle8/Galacticraft#2556]
Client crashes while Venus is loading
Forge 12.18.3.2272
Galanticraft Build 61
Crash log: https://pastebin.com/xKBhfDEu

Update: When I tried to return to the world, it crashed again.

**Comment by radfast** [comment]
Seems to be a Forge version bug.

Please try running under Forge 12.18.3.2185, see if that fixes it.

**Comment by radfast** [comment]
Could also be Optifine, if you have that?

**Comment by tabepic** [comment]
Nope, wasn't using Optifine, only Galanticraft.

**Comment by tabepic** [comment]
I'll try under 12.18.3.2281 now. (that's the latest I can find on the forge download site)

**Comment by tabepic** [comment]
I'll try with 12.18.3.2185 now

**Comment by tabepic** [comment]
Still crashes with 12.18.3.2185 (no mods except Galanticraft)
And I managed to get a screenshot:
![Screenshot](https://cloud.githubusercontent.com/assets/9892196/24890808/2ded27c8-1e2f-11e7-8370-0a69211e32f5.png)

**Comment by radfast** [comment]
This one is mighty strange.  Maybe @micdoodle8 will have some ideas about the cause?

**Comment by micdoodle8** [comment]
Not sure, I guess this is private in some forge versions (?)

I've changed it to use the other cullFace method, which should hopefully work regardless of which forge version you're on.

**Comment by radfast** [comment]
I've found the problem - it **is** private in Forge 1.10.2 (not sure why?!)
 made public by [CodeChicken](https://github.com/micdoodle8/Galacticraft/blob/MC1.10/dependencies/main/resources/ccl_at.cfg#L48) we need to replicate that in miccore in case CCL not loaded

**Comment by radfast** [comment]
[build 63](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/) is now available and fixes this :)
