### ISSUE TITLE
[1.10.2] Going to Venus crashes Minecraft

### ISSUE THREAD

**Issue by tabepic** [micdoodle8/Galacticraft#2560]
I can see the sun/sky and the brown texture underneath it for a second or two, and then it crashes.

Forge: 12.18.3.2272
Galanticraft Build 61
Crash log: https://ptpb.pw/cWaF

**Comment by radfast** [comment]
This is #2556 !

Please can you  test in Forge **12.18.3.2185** and **without Optifine**.
