### ISSUE TITLE
[1.11.2] Frequency Module does not work with Space Villagers

### ISSUE THREAD

**Issue by ThomasAunvik** [micdoodle8/Galacticraft#2563]
Build 63
![Imgur](http://i.imgur.com/Yc6ZZhB.png)
![Imgur](http://i.imgur.com/ot8Guxu.png)

**Comment by ThomasAunvik** [comment]
Fixed By Re-Logging, as i said in https://github.com/micdoodle8/Galacticraft/issues/2578

**Comment by ThomasAunvik** [comment]
Leaving this issue for 2578

**Comment by radfast** [comment]
Thank you for the precision :)
