### ISSUE TITLE
[1.11.2] Sensor Glasses not working correctly for space villagers

### ISSUE THREAD

**Issue by ThomasAunvik** [micdoodle8/Galacticraft#2565]
[From Wiki](https://wiki.micdoodle8.com/wiki/Sensor_Glasses)

> Sensor Glasses can help you locate nearby ores. To use the glasses, place them in the helmet armor location in the inventory. An interface will then appear with a large blue circle. This works equally well in the Overworld or on the Moon and any ore within 5 spaces should be indicated.

Expected:
![ExpectedGlasses](https://wiki.micdoodle8.com/images/5/58/Sensor_Glasses_View.png)

What i got:
![Imgur](http://i.imgur.com/404CARh.png)
![Imgur](http://i.imgur.com/PVjPara.png)

**Comment by radfast** [comment]
Lol ... this is a suggestion?

It looks great

**Comment by ThomasAunvik** [comment]
No, i found it in the wiki.

**Comment by EzerArch** [comment]
> is it from another mod?

Yeah, it's from an awesome mod, which is called Galacticraft. O wait!

**Comment by radfast** [comment]
I think that image from the wiki was a mock-up!  That effect has never been in Galacticraft.

Until now ...

Take a look in next build 107.  The mobs will now kind of glow when seen through Sensor Glasses, the effect will be stronger in the dark, less strong (hardly noticeable) if the mob is in daylight.

The overall look is not quite as good as the wiki image, maybe @micdoodle8 can improve it in future.

(BTW there is also a Spectral Glow effect you can get on mobs in 1.10.2+ using a Spectral Arrow.)
