### ISSUE TITLE
[1.11.2] Vacuum Glass Bug

### ISSUE THREAD

**Issue by ThomasAunvik** [micdoodle8/Galacticraft#2566]
Located Here: https://github.com/micdoodle8/Galacticraft/issues/2564#issuecomment-293284916

**Comment by ThomasAunvik** [comment]
Even More Images:
![Imgur](http://i.imgur.com/SjRxRCK.png)
![Imgur](http://i.imgur.com/nwrpai1.png)

**Comment by radfast** [comment]
all fixed in next build 77, thank you for the screenshots :)

**Comment by radfast** [comment]
[Build 77 now available](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/)
