### ISSUE TITLE
Suggestion: Mod intergration between PortalGun and Galacticraft for the portal gun.

### ISSUE THREAD

**Issue by border999** [micdoodle8/Galacticraft#2568]
This would be difficult to make a reality I'm certain, but many people would love to see this become a reality. Maybe add the integration as a toggle able config option?

**Comment by micdoodle8** [comment]
If I recall correctly there are a few threads on the forum related to this. Therefore I'm going to close this as the discussion should be continued there.

This is also more of a PortalGun suggestion, as the behavior of what happens when you create/enter portals is completely up to iChun.
