### ISSUE TITLE
[1.11-Build 63] Can't take off parachute 

### ISSUE THREAD

**Issue by DeadPigman17** [micdoodle8/Galacticraft#2573]
Even after dying, it won't take off. The only solution I've found is leaving and joining the world.
![2017-04-13_02 38 01](https://cloud.githubusercontent.com/assets/22800252/24985134/7f409b7c-1ff2-11e7-96a1-1a178a5242b7.png)

**Comment by radfast** [comment]
Thank you for beta testing!

This is the same issue as #2536, I think.  You've added some useful extra info, that it stays even after dying.

**Comment by DeadPigman17** [comment]
I just discovered that it also takes off if you go to another planet.

**Comment by micdoodle8** [comment]
Should be fixed in build 66, thanks for testing!
