### ISSUE TITLE
[1.11.2-Build 63] Opening Fuel Loader, Oxygen Collector, Refinery, etc. Will crash the game.

### ISSUE THREAD

**Issue by DeadPigman17** [micdoodle8/Galacticraft#2576]
I've also tried with the cargo loader, cargo unloader and oxygen bubble distributor, they all crash the game. I guess there are even more GUI's that crash the game. 

Also, it doesn't crash at the exact moment you open the GUI, it takes 2-3 second to crash.

Here's the crash log for the Fuel Loader: https://ptpb.pw/nO8X

**Comment by radfast** [comment]
Thank you for beta testing!

I think @micdoodle8 fixed some errors like this in https://github.com/micdoodle8/Galacticraft/commit/dc59c0f3aaefcacb916287d3a1e277b0eb405724 but I don't know yet if that got them all.  I'll leave this open until we have build 64 out, if it tests OK in that then we're golden.

**Comment by micdoodle8** [comment]
Fixed in the next build, thanks!

**Comment by radfast** [comment]
[build 66 now available](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/#post-43135)
