### ISSUE TITLE
[Suggestion] Compressed Oxygen Cluster

### ISSUE THREAD

**Issue by tabepic** [micdoodle8/Galacticraft#2577]
Something like the Energy Storage Cluster for oxygen, except, because the oxygen has to be compressed into a small space, it requires power to accept oxygen in. (So it would have two inputs and an output)

**Comment by radfast** [comment]
Not necessary.  You can liquefy the oxygen - which compresses it hugely - and then store the Liquid Oxygen in tanks.  Either GC's own tanks, or crazy large tanks from another mod.

**Comment by tabepic** [comment]
Wait a minute; you can liquefy oxygen?

**Comment by radfast** [comment]
https://wiki.micdoodle8.com/wiki/Gases#Oxygen

**Comment by tabepic** [comment]
I haven't been able to pipe liquid oxygen from a liquefier to a tank. It looks like it connects, but it doesn't fill it up/empty the liquefier's internal tanks

**Comment by radfast** [comment]
Did you wrench the output pipe on the liquefier, to put it into 'pull' mode?
