### ISSUE TITLE
[1.11.2] GC Inventory Bugs (Items not rendering/working)

### ISSUE THREAD

**Issue by ThomasAunvik** [micdoodle8/Galacticraft#2578]
Build 63
**Bug 1:**
Oxygen Set, Thermal Padding and so on... does not render until re-logging.
Oxygen Tank seems to only render on all normal oxygen tanks, but not creative oxygen supply.
Before Re-logging:
![Imgur](http://i.imgur.com/4YfoeAs.png)
After Re-logging:
![Imgur](http://i.imgur.com/mlG0UOw.png)

**Bug 2:**
Frequency Module does not work until re-logging.

**Bug 3:**
After dying then crashing then re-log, you will still have the rendering bug.

**Bug 4:** A different kind than Bug 2 and 3
When you die, crash, re-log, you will have the effect as you are wearing the Frequency Module and you are able to talk with the Alien Villagers. Rendering issue is still happening.

_Note 1: When i mean about die, crash, relog, i am talking about (for example) https://github.com/micdoodle8/Galacticraft/issues/2512#issuecomment-294038597 where you die then crash._

_Note 2: Just a quick note about how to fix it: Re-logging normal fixes everything._

**Comment by ThomasAunvik** [comment]
**Bug 5:** 
For the frequency module. When going from overworld to the moon makes it not work again. Relogging fixes that. Not tested for other dimensions, but i am sure that might also happen.

**Comment by micdoodle8** [comment]
Thanks for the detailed report, fixed in the next build.

**Comment by radfast** [comment]
[build 66 now available](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/#post-43135)
