### ISSUE TITLE
[1.11.2] Crash Landing on an moon lander does not kill you

### ISSUE THREAD

**Issue by ThomasAunvik** [micdoodle8/Galacticraft#2579]
Build 63

I was holding shift all the time. There were alerady a moon lander under me. And i crashed into it.
It exploded and somehow this happened:
![Imgur](http://i.imgur.com/vB6hmqk.png)

**Comment by micdoodle8** [comment]
I was able to recreate the issue once but never again. Have you found any consistency to what causes this to happen?

**Comment by radfast** [comment]
I reproduced this one time - hold Shift to get the downwards yMotion as high as possible, like over 70, by the time the lander crashes.  (Might need an existing crater so that it goes a bit deeper than y == 63)

**Comment by radfast** [comment]
Reproducable in 1.10.2 and 1.11.2.  You just have to be going fast enough.  It doesn't matter about a pre-existing lander in the same spot, that is irrevelant - a fresh crash landing will also have this issue.

**Comment by radfast** [comment]
For info for anyone who comes to this via Google:  if the player is wearing high level armor like our **Desh Armor** or **Titanium Armor** or equivalents from other mods, this explosion will not kill the player.
