### ISSUE TITLE
[1.10.2] Placing two Display Screens crashes client

### ISSUE THREAD

**Issue by tabepic** [micdoodle8/Galacticraft#2580]
I placed two Display Screens side-by-side on a single player world and the client immediately crashed
Re-entering the world crashes with the same error

GC Build 63
Mods: Galanticraft and Optifine
Client crash log: https://ptpb.pw/SKMO.txt

**Comment by micdoodle8** [comment]
Thanks for the report, this will be fixed in the next build.
