### ISSUE TITLE
[1.10] Galacticraft Core Download is missing

### ISSUE THREAD

**Issue by vos3464** [micdoodle8/Galacticraft#2588]
![screenshot 48](https://cloud.githubusercontent.com/assets/21976486/25065061/760d2430-21ff-11e7-8ac4-2fe0357ac304.png)

**Comment by xXJamieXx** [comment]
The core and planets text is bound to the same link which is the planets jar.

**Comment by vos3464** [comment]
no because when i placed them in mods it said that core is missing

**Comment by tabepic** [comment]
What do you mean, "no"?
@xXJamieXx is correct

**Comment by tabepic** [comment]
I believe only @micdoodle8 can fix this, as he is the only one able to change the forum post (and therefore the download link)

**Comment by xXJamieXx** [comment]
Is he very active?

**Comment by tabepic** [comment]
I'm not really sure, however he is the mod creator (and presumably he built Build 64)

**Comment by ThomasAunvik** [comment]
radfast can change it too i think.

**Comment by tabepic** [comment]
Maybe. Hey @radfast , can you help us out here?

**Comment by tabepic** [comment]
Never mind, seems to be fixed now.

**Comment by micdoodle8** [comment]
Yes, I've fixed the links, sorry about that.
