### ISSUE TITLE
Oxygen gear bug

### ISSUE THREAD

**Issue by ElSaam** [micdoodle8/Galacticraft#2589]
Hat layer buggy
![2017-04-15_19 21 31](https://cloud.githubusercontent.com/assets/16359905/25065075/c03c35e4-2210-11e7-92e3-5fede2546fa6.png)

**Comment by vos3464** [comment]
I don't see any problems

**Comment by ThomasAunvik** [comment]
As i see in the title i must think you are talking about this bug: https://github.com/micdoodle8/Galacticraft/issues/2578

**Comment by ElSaam** [comment]
Yes

**Comment by radfast** [comment]
This is fixed in build 66, please get it from [here](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/#post-43135)
