### ISSUE TITLE
[1.10.2] Footprints on Moon showing up when walking on non-full block

### ISSUE THREAD

**Issue by tabepic** [micdoodle8/Galacticraft#2592]
When you place a non-full block, for example an oxygen pipe, on top of a moon turf block, walking on the oxygen pipe will create footprints on the moon turf.

This happens with every non-full block I've tested:
- Aluminum wire
- Oxygen pipe
- Stone slab

GC Build 64
Forge 12.18.3.2272

**Comment by micdoodle8** [comment]
Thanks, should be fixed in the next build :)
