### ISSUE TITLE
[1.11.2-Build 64] Two bugs that I've reported from Build 63 are still there (Look in the desc. for links)

### ISSUE THREAD

**Issue by DeadPigman17** [micdoodle8/Galacticraft#2594]
https://github.com/micdoodle8/Galacticraft/issues/2576 In this bug, some GUI's were fixed, but other still crash the game.

https://github.com/micdoodle8/Galacticraft/issues/2573

**Comment by micdoodle8** [comment]
Hey, thanks for bugfixing. Theses issues are still open, which means they're not fixed. You can expect the fixed in the next build after they're closed.
