### ISSUE TITLE
[1.10.2] Connecting Heavy Aluminum Wire to/from IC2 machines causes fps lag

### ISSUE THREAD

**Issue by tabepic** [micdoodle8/Galacticraft#2597]
When connecting certain IC2 machines, it starts to lag really badly (from ~40 fps to 0-1 fps)
![Screenshot](https://cloud.githubusercontent.com/assets/9892196/25067857/64efee36-220d-11e7-8e30-42eb13e81698.png)

Tested so far:
- Solar panel to MFSU (in screenshot)
- Energy Storage Cluster to solar panel
- One block of wire (not connected to anything else) to solar panel

Warning: fml-server-log is over 20MB, mostly repeating lines
fml-server-log: https://ptpb.pw/U--P.log
GC Build 64

**Comment by tabepic** [comment]
Another possibly related issue: When connecting an Energy Storage Cluster to a **full** MFSU, the Energy Storage Cluster still loses power, as if it were charging the MFSU

**Comment by radfast** [comment]
[build 66 now available](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/#post-43135)

Thanks for mentioning the MFSU filling issue, it must probably the same for every IC2 machine which is **full**.  Added to my list of issues to fix, no need to re-report :)
