### ISSUE TITLE
[1.10.2] IC2 higher tier power incompatible with Galanticraft power

### ISSUE THREAD

**Issue by tabepic** [micdoodle8/Galacticraft#2598]
Not exactly sure if this is a bug (or if it's in GC), but...
When connecting, for example, the output of an MFSU to the input of a Energy Storage Cluster, the aluminum wires nearest to the MFSU "explode" and drop as items.
It seems to have something to do with IC2's Voltage, explained [here](http://ic2exp.wikia.com/wiki/IC2_Energy)

GC Build 64
Forge 12.18.3.2272

**Comment by radfast** [comment]
It's intended, and was requested by people who play IC2 a lot.

IC2 has a carefully tiered power system where - in some IC2 versions - lower tier wires and machines cannot be used with higher tier power (at least, not without transformers).

The Galacticraft Heavy Aluminium Wire is easy to make - it's regular Aluminium Wire with extra wool - and it would ruin IC2's tiers if this cheap wire can be used easily in place of their Tier 4 / high voltage wires.

Therefore we limit Galacticraft wires to be approximately equivalent to IC2 tier 3, that's gold cable.  Exact equivalence depends on which IC2 version it is.

You can use our Beam Transmitters and Beam Receivers to connect to MFSUs, those should not explode (or if they do, that's something I would want to fix.)

**Comment by tabepic** [comment]
Ok, thanks for the info

**Comment by tabepic** [comment]
Umm... how exactly do you attach a beam receiver/transmitter to an MFSU?
When I tried, it said "Cannot attach receiver here"

**Comment by radfast** [comment]
uh oh.  I'll take a look at that, thank you.  It's intended that it should attach (it did in 1.7.10).
