### ISSUE TITLE
[1.8.9] Spin Thruster popping out from wall

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#2601]
![2560-04-16_18 21 13](https://cloud.githubusercontent.com/assets/6128413/25070785/b4bbb282-22d1-11e7-9752-c5a269df3181.png)
![2560-04-16_18 21 17](https://cloud.githubusercontent.com/assets/6128413/25070786/b4c02c40-22d1-11e7-99a2-7ec285ab1f8d.png)

**Comment by NevCrow** [comment]
A block cant be touch it, remove the grass block from underneath and try it.
