### ISSUE TITLE
[1.8.9] Arclamp tile render issue with GUI Tooltip

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#2603]
Edit : Tested in Superflat map.

![2560-04-24_00 31 34](https://cloud.githubusercontent.com/assets/6128413/25315810/73a88eb4-2885-11e7-876b-d908500207f0.png)
![2560-04-24_00 31 39](https://cloud.githubusercontent.com/assets/6128413/25315811/73d0ee0e-2885-11e7-94f2-cdd964ed5c2e.png)

Sometime spawning mob make strange rendering.
![2560-04-24_00 31 56](https://cloud.githubusercontent.com/assets/6128413/25315815/81cff5ae-2885-11e7-9f10-97fd9b361619.png)

**Comment by dj3520** [comment]
upside down torch?

**Comment by ThomasAunvik** [comment]
The issue is so minor i cant see what the issue is actually is about.

**Comment by radfast** [comment]
Trust me, if it's from SteveKunG it'll be there!  I'll take a look next time I'm in game.
