### ISSUE TITLE
[1.11.2] Frequency Module position while crouching

### ISSUE THREAD

**Issue by ThomasAunvik** [micdoodle8/Galacticraft#2605]
Build 66
![2017-04-16_15 56 47](https://cloud.githubusercontent.com/assets/9968151/25071657/63405c3c-22bd-11e7-936e-93fc299d7bf4.png)

**Comment by EzerArch** [comment]
Also in 1.10.2.

**Comment by radfast** [comment]
Fixed by @SteveKung

Thanks guys ... the little details all help to give a really polished feel 👍
