### ISSUE TITLE
[1.11.2] Various held item positioning / size errors

### ISSUE THREAD

**Issue by ThomasAunvik** [micdoodle8/Galacticraft#2606]
Build 66
Including Bug #2583
![2017-04-16_16 06 43](https://cloud.githubusercontent.com/assets/9968151/25071710/cfbbbaae-22be-11e7-8c66-802f05dc7237.png)
![2017-04-16_16 06 45](https://cloud.githubusercontent.com/assets/9968151/25071711/d10caa1c-22be-11e7-8a21-f3bde1a16b5a.png)
![2017-04-16_16 06 48](https://cloud.githubusercontent.com/assets/9968151/25071712/d237162a-22be-11e7-9b3f-95795afdf2f2.png)
![2017-04-16_16 06 50](https://cloud.githubusercontent.com/assets/9968151/25071713/d3597ca0-22be-11e7-86c0-3629b5aee450.png)
![2017-04-16_16 06 53](https://cloud.githubusercontent.com/assets/9968151/25071714/d4bc2a5c-22be-11e7-8ea4-62c103e0e5a0.png)
![2017-04-16_16 06 55](https://cloud.githubusercontent.com/assets/9968151/25071715/d6c2fef2-22be-11e7-8e5c-8f5035fed4b9.png)

**Comment by radfast** [comment]
Also reported by @Preminenc3

>  Short Range Telepad ​ (In hand it covers up a lot of the screen)

**Comment by SteveKunG** [comment]
All item model have been fixed except Cryogenic Chamber and Aluminum Wire.

**Comment by radfast** [comment]
Will be fixed in next build 153, thanks for patience.
