### ISSUE TITLE
[Suggestion] [1.8+] JEI Compatibility

### ISSUE THREAD

**Issue by xXJamieXx** [micdoodle8/Galacticraft#2607]
I've been playing with the 1.10.2 version specifically but I believe it is the same for all versions and I have to admit that I don't have the best knowledge of crafting rockets with the NASA workbench and so I had to look it up on the wiki. It would be nice if there was a way of viewing these types of recipes in JEI as otherwise you have to resort to external sources if you don't know how to craft it. You don't have to implement it but it's just my opinion. Thanks!

**Comment by ThomasAunvik** [comment]
It is alerady reported that NEI and JEI is not working correctly. Some crafting recipes already is working.

**Comment by xXJamieXx** [comment]
Yeah, it seems that nearly everything that isn't crafted using a vanilla crafting table won't show its recipe. The new GUI's that galacticraft adds seems not to be registered in JEI yet.

**Comment by radfast** [comment]
JEI does not make it easy to do this, and frankly it seems unfinished.

We are still hoping someone will find a way to have all the aspects of NEI in 1.10+ so that our existing NEI integration code will "just work".  I imagine that's something someone is working on but I haven't checked recently.

Meanwhile if people are using the wiki I think that's a good thing, there's a lot of useful information on the wiki.

Building rockets should be possible with no wiki and no recipe.  It's fairly obvious which components you will need to make a Tier 1 Rocket and shift-click will place the items into the correct spots.

**Comment by radfast** [comment]
Closing this, because discussion of suggestions needs to be on the forum not the issues list.

**Comment by micdoodle8** [comment]
0b7d28925a0da6385297576223f016128fcb375d adds JEI support for tier 1 rocket and buggy recipes. More to come.

**Comment by xXJamieXx** [comment]
@radfast, I realised you edited the message you sent yesterday although I can still see the original message in my email inbox. I just wanted to let you know that covers1264 has already made a [1.10 port of NEI](https://mods.curse.com/mc-mods/minecraft/247694-not-enough-items-1-8) although i'm not sure whether it provided all the support necessary for Galacticraft. (I hope it does seeing as @micdoodle8 has already added some JEI support)

**Comment by radfast** [comment]
Yep.  When I first responded I didn't know that micdoodle8 at the same time had started on JEI support... !

Thanks for the heads up on covers1264 work.  That's very good news, personally I prefer NEI over JEI, and it also means we can keep on using our existing extensive NEI support in Galacticraft.

**Comment by xXJamieXx** [comment]
Yeah! Forgot to mention, NEI, although may seem like a standalone mod, does require JEI to run so personally (as I don't make mods myself) I'm not sure whether that will affect anything to do with the functionality of Galacticraft itself.

**Comment by radfast** [comment]
I think there are two NEIs for 1.10+.  There's an NEI plugin for JEI, which only adds buttons to switch gamemode, rain, stuff like that.  Then there's covers1264 project which looks like an actual port of the original NEI.

**Comment by xXJamieXx** [comment]
I assume the plugin for JEI which you are referring to is [this one](https://mods.curse.com/mc-mods/minecraft/248747-just-enough-buttons)?
I have just tested cover1264's version and can conclude that it does in fact require JEI to work as it does not load without it.

**Comment by radfast** [comment]
Thanks again for the comments.  Yes, it looks like NEI doesn't have all the old features - a shame - anyhow, some people are using only JEI now.

micdoodle8 has given Galacticraft 4 **full support** for JEI, from next build 70 when it's out.  If you spot anything which looks wrong / different from how things were in 1.7.10, please re-open this.
