### ISSUE TITLE
[1.10.2] Terraformer not working on Moon Turf

### ISSUE THREAD

**Issue by tabepic** [micdoodle8/Galacticraft#2608]
I tried to use a terraformer on the Moon, however with everything set up and ready to go, the terraformer complained about having "No Valid Blocks in Bubble", even though there was plenty of moon turf inside the bubble for it to terraform.
I'm not certain, but I believe it doesn't work on the other planets either.

Forge 12.18.3.2272
GC Build 66

**Comment by Mike-T4** [comment]
It doesn't work on Venus either.

**Comment by micdoodle8** [comment]
Thanks, fixed in the next build
