### ISSUE TITLE
[1.10+] [Sponge] Sponge powered servers - workaround for dimension issues

### ISSUE THREAD

**Issue by radfast** [micdoodle8/Galacticraft#2612]
https://github.com/SpongePowered/SpongeForge/issues/1429

SpongeForge currently breaks standard Forge mod usage of ```DimensionType``` and ```DimensionManager```.

This thread is for testing and discussion of workarounds that we can do on Galacticraft's side, until we find a solution for this.

**Comment by radfast** [comment]
hmm, this hasn't worked yet.

**Comment by radfast** [comment]
@silent-mobious  @VOiDProXy  Next Galacticraft 1.10.2 build 69 is Sponge-compatible.  Tested here on a Sponge server and all seems to be working smoothly.  Build 69 should be available later today.

**Comment by gabizou** [comment]
@ZIdane Should be able to make the change in SpongeForge for this to work properly (without the patch).

**Comment by radfast** [comment]
[Build 69 with Sponge compatibility](https://ci.micdoodle8.com/job/Galacticraft-1.10/) is now available.

**KNOWN ISSUE**   When you **first start** the server, the server will slowly create spawn areas for all Galacticraft fixed dimensions (Venus, Asteroids, Mars, Moon) as well as the Overworld.  This will cause a server to timeout while creating spawn.

Current solution:
* Iin ```server.properties``` set ```max-tick-time=500000``` or a similar high number - only needed for this first start, after the first start you can lower it to 60000

----

I'll try to work with the Sponge team to find a more permanent solution (connected with [this](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/core/world/storage/MixinWorldInfo.java#L634-L650) and [this](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/core/world/MixinDimensionType.java#L74-L75) but I haven't figured out the answer yet).

**Comment by VOiDProXy** [comment]
Thank you so much for getting to this so quickly. I'm going to test it out and let you know how it works out :)

**Comment by VOiDProXy** [comment]
I did bump into a BiomeTweaker issue, but that's another error and not related to Sponge.
So far so good on this one.

My server did some long crunching on the new Galacticraft areas at first startup but did not timeout or crash so I did not have to change the tick-times.

**Comment by radfast** [comment]
great news.  please do report any issues, especially while this is still in Beta so we can get them dealt with before full release.

After thinking some more, I actually think it's maybe better to generate some areas of these worlds on first startup.  Better to have it then instead of the first time a player goes to the world, which would produce a lag spike.

I am looking at how we can speed up the gen of the new worlds, especially for Asteroids which is slow (reason for the slowness is mainly vanilla lighting, it thinks that the space 'beneath' an Asteroid is one big cave).
