### ISSUE TITLE
[1.10.2] Leg and Body armor values are swapped

### ISSUE THREAD

**Issue by Mike-T4** [micdoodle8/Galacticraft#2613]
Between 1.7 and 1.10 the Leg and Body armor slot numbers were swapped.

The 1.10 version does of Galacticraft did not update this.
As such, the body armor added by Galacticraft currently has the armor values that leg armor is supposed to have. Eg: Titanium chestplate gives only **+7** armor while Titanium legs give **+10** armor.

**Comment by radfast** [comment]
Thank you for spotting this detail.

Fixed from our build 69, for Steel, Desh and Titanium.

At the same time, I made Titanium Armour a bit more enchantable, consistent with our other armour types: more enchantable than Iron and Diamond Armour, not as good as Gold Armour.
