### ISSUE TITLE
[1.10.2] Build 66, SMP, i cant make a space station

### ISSUE THREAD

**Issue by AnarchySage** [micdoodle8/Galacticraft#2614]
As the title says, i am opped on the server, i am the owner and no config is set to prevent it, i got all the items but i cant make one :/. May say forget gc and go back to advanced Rocketry at this rate :/

**Comment by radfast** [comment]
Fixed in 69.

[Build 69 with Sponge compatibility](https://ci.micdoodle8.com/job/Galacticraft-1.10/) is now available.
