### ISSUE TITLE
[1.10.2] Certain ores registering as "diamond" mining level in overworld

### ISSUE THREAD

**Issue by xXJamieXx** [micdoodle8/Galacticraft#2619]
Tin, Copper and Aluminum ores are being registered as "Diamond" harvest level. 

GC Version: 1.10.2 Beta 69

**Comment by radfast** [comment]
thanks, we'll get onto it right away :)

**Comment by radfast** [comment]
I'm not seeing this in my testing!  Successfully mined these blocks with an Iron Pickaxe.

Are you sure about this?

**Comment by xXJamieXx** [comment]
Will check this as soon as I can get on which will be Sunday.

**Comment by radfast** [comment]
OK, I'm going to close this for now.  Please re-open on Sunday if further tests show it's still a problem...  Also if you're using other mods like Tinker's Construct, Iguana modifications, etc, those can change harvest levels I think...

**Comment by C1ffisme** [comment]
@radfast 

> Iguana modifications

[**Iguana's Tinker Tweaks** hasn't even updated to 1.10.2, or updated at all since March 20, 2016.](https://mods.curse.com/mc-mods/minecraft/223248-iguanas-tinker-tweaks#t1:other-downloads)

**Comment by xXJamieXx** [comment]
@C1ffisme You are correct about that but certain features of the mod have been added to tinkers construct so @radfasts point is still valid.

**Comment by C1ffisme** [comment]
> @C1ffisme You are correct about that but certain features of the mod have been added to tinkers construct so @radfast 's point is still valid.

I don't remember block levels being added, though. (Although, to be fair, I haven't really played Tinker's Construct for 1.10.2 that much in survival.)

**Comment by xXJamieXx** [comment]
Thanks for all the help, turns out there was a mod that was changing the harvest level which I didn't realise was a thing. It must be changing the ore dictionary harvest level.

**Comment by radfast** [comment]
ok, thanks for checking!  I'm pleased it's not a Galacticraft bug.

**Comment by TheQuadShot** [comment]
This should be re-opened. I think there was/is a disconnect on what harvest level is telling you. If a block is at harvest level Iron, it should be harvest-able with a Stone pick-ax. ie. Iron ore is harvest level Iron. I've checked against Forestry, Immersive Engineering, and Embers. This also impacts ExtraPlanets (not sure if fix to core will propagate out).

**Comment by xXJamieXx** [comment]
I have reason to believe that you are correct I have just tested with Galacticraft, Forestry, Immersive Engineering and Embers. All mods except Galacticraft allow you to break copper ore for example with a stone pickaxe. Galacticraft however, requires that you mine the ore with an iron pickaxe.

Interestingly enough, I have WAILA Harvestability installed and it shows that the Galacticraft Copper Ore is harvest level 2, whereas the others are harvest level 1.

![copperores](https://user-images.githubusercontent.com/11248045/29248333-55f84eec-800d-11e7-88e9-5981a9997cac.png)

**Comment by radfast** [comment]
Thanks both :)

I have changed the Overworld, Moon and Mars variants of Tin, Copper, Aluminium Ore (and Mars Iron Ore) to require stone pickaxe.

At the same time, Silicon Ore will now require an Iron Pickaxe, I think this is consistent with other gemstone / redstone type ores.

Asteroids and Venus are unchanged.  I think it's reasonable to expect that players who have reached those dimensions have access to iron or other advanced materials ... (actually this creates an extra challenge in the Asteroids Adventure game mode, but that is perfectly playable, I have played it myself).

**Comment by machetejones** [comment]
@radfast I'm glad I found this before I raised issue.  
"...actually this creates an extra challenge in the Asteroids Adventure game mode..."
Could you possibly have this updated in the adventure mode walkthrough?  I spent a long time trying to figure out why I couldn't follow the walkthrough and get iron from stone picks.  I assume progression requires you to get copper ingots from mob drops?   
While I've got your attention, is it possible to modify the starting inventory of the pod in the adventure mode?  Where would be the best place to ask such questions?

**Comment by TheQuadShot** [comment]
Best place to post! Dev team is pretty active there and lots of helpful people around to help answer questions and/or "chat" about space things. 
https://forum.micdoodle8.com/index.php

**Comment by radfast** [comment]
@machetejones do you mean "is it possible for players / server owners / modpacks to modify the starting inventory" or do you mean you want me to modify it?

It is not currently possible for players to modify it, it is hard coded.

If you want me to modify it, what did you have in mind?  

------

>   I spent a long time trying to figure out why I couldn't follow the walkthrough and get iron from stone picks. I assume progression requires you to get copper ingots from mob drops?

Yes mob drops are the only way to obtain copper.

And tin is very scarce, until you are able to leave the Asteroids dimension, tin canisters dropped from food cans is the only way to acquire tin, and (IIRC) almost all that tin will be required to make a basic Oxygen Collector + Oxygen Compressor.

If you do not have other mods installed then there are at least three ways to obtain iron ingots:

<details>
 <summary>SPOILER - click to read</summary>
1a.  Creeper mining of some Asteroids Iron Ore - not much fun, very dangerous

1b.  or Creeper mining of some Diamond Ore if you find that first - ore can be smelted to make diamonds - diamond pick can mine any ore

1c.  or Creeper mining of some Ilmenite if you find that first - smelt into Titanium Ingot - Titanium pick can mine any ore

2.  Raid an Abandoned Base, that should have at least 2 iron ingots hidden in it, usually 4 for most bases

3.  (_Intended route_)  Use some of your starting Desh Ingots to make a Desh Pickaxe, this can mine any ore
</details>

**Comment by machetejones** [comment]
Thanks for the reply!  I would like for players/pack devs to be able to modify it.  Sorry I didn't clarify.  And if that's not what you would like to do it's cool, just a thought.  Also my comment about copper and progression was a derp on my part, I was thinking about copper pickaxes which isn't your problem.  I'll hop over to the forum in the future if I have other questions as it's more appropriate.

**Comment by radfast** [comment]
You're welcome.  We have updated the walkthrough on the wiki in the light of your comments.  We are thinking about changing the harvest level of Asteroid Iron Ore to stone pickaxe - although that will do nothing for players with older versions of Galacticraft, so the guidance on the wiki will have to stay.

It is a huge amount of work for us to change the Asteroids Adventure starting resources to something configurable, we'd have to design a whole system for this (it's not the same as a loot table, because this is not random loot).  I'm not sure it's worth it for the small number of people who might want to modify it.  There are other ways that a pack developer or server can add more starting items - for example **Custom Starter Gear** mod and **Initial Inventory** mod.

**Comment by TheQuadShot** [comment]
Just a thought, (it's 1st cup of coffee o'clock for me) how difficult to make it configurable via an xml file? I know EIO does this, but I haven't looked at any of the code involved...

**Comment by radfast** [comment]
Very time consuming, we would need whole new code classes to interpret the xml file as we have nothing like this at present.

The closest parallel is the loot table which is in JSON format, but we cannot simply make use of the vanilla code for loot tables because the purpose is different, this is not filling a chest with random objects.

I judge this is not the best use of my time, as only a small minority of players use the Asteroids Adventure mode and, of those, only a small percentage can have a serious interest in changing the starting items.  (And as I've said, it would be easy enough to **add** starting items if a modpack wanted to do that - what is harder is taking away from the items Galacticraft provides as standard.)

If we had 3 or 4 active developers it might be a different story...
