### ISSUE TITLE
[1.10.2]Desh Leggings use incorrect icon

### ISSUE THREAD

**Issue by Mike-T4** [micdoodle8/Galacticraft#2621]
**Desh Leggings** have a notably lighter color than the rest of the Desh set while in the inventory.
It appears that it accidentally uses the same icon as the Heavy-Duty leggings.

The **Desh Sword** and **Desh Axe** seem to have the same issue.

Their model does have the correct color when equipped, it's just the icon that's wrong.

Proper icons is included below. (From Galacticraft 1.7.10)
![deshleggings](https://cloud.githubusercontent.com/assets/12882669/25279861/2be04df8-26a8-11e7-9a9e-d8d42a4fe08b.png)
![deshsword](https://cloud.githubusercontent.com/assets/12882669/25280402/1cc7cb46-26aa-11e7-8894-a03cae9a2c16.png)
![deshaxe](https://cloud.githubusercontent.com/assets/12882669/25280403/1cc84526-26aa-11e7-9327-33662f8c4aab.png)

Edit: Upon closer inspection, it seems like the json files reference the wrong icons.

**Comment by radfast** [comment]
thanks Mike-T4 :)  easy to fix

**Comment by radfast** [comment]
will be in next build 70, thanks again
