### ISSUE TITLE
[1.10.2] Entering Rocket crashes server.

### ISSUE THREAD

**Issue by Axiom1999** [micdoodle8/Galacticraft#2626]
Trying to cast a sheep to a PacketReceiver....

**Comment by Axiom1999** [comment]
On phone, can't edit original post for some reason.
Here is the crash-land.
It also tries to cast ANY entity (items, sheep for example).
https://hastebin.com/avatohekul.scala

**Comment by radfast** [comment]
Hi Axiom1999

Thanks for reporting

Where did you get this Galacticraft from?  Doesn't look like an official download, did you compile it yourself?  I'm trying to figure out which version this is.

**Comment by radfast** [comment]
actually this is really good ... catching a potential error in build 70 before we even make build 70 live.

Thanks :)

**Comment by Axiom1999** [comment]
I'm not Luke. And yes, I compiled this myself. Glad to help!
