### ISSUE TITLE
[1.10.2] Bag of holding inventory dissapearing

### ISSUE THREAD

**Issue by Coaleb2** [micdoodle8/Galacticraft#2627]
When you launch into space the bag loses its inventory. I am using 1.10.2 Version 69.

**Comment by dj3520** [comment]
Bag of holding is from Extra Utilities, yes?

**Comment by Coaleb2** [comment]
Yes

**Comment by radfast** [comment]
I've tested the latest Extra Utilities 2 (1.4.1) and the latest Galacticraft and Bag of Holding keeps its inventory in my tests.  There's really no reason why it should lose its inventory with Galacticraft, we don't touch items in the player inventory unless they are ours.  Maybe it was a bug in an earlier version of Extra Utilities?

If you're still seeing the issue, you can re-open but in this case please:
(A) describe exact steps from game start to reproduce the issue - which type of rocket, which destination, which game mode etc
(B)  test whether the Bag of Holding keeps its inventory when you go through a Nether Portal

![bagholding_crop](https://cloud.githubusercontent.com/assets/6842258/25780485/3ed10356-3320-11e7-8477-3acfaa4ada95.jpg)
