### ISSUE TITLE
1.10.2 Crash on start with T-Construct added

### ISSUE THREAD

**Issue by themechman** [micdoodle8/Galacticraft#2630]
I am currently goofing off with mods and have been individually adding them to my potential [modpack](https://forum.micdoodle8.com/index.php?threads/jailbreak-but-in-spaaaaaaaaaaaaaaaaaaaace.6683/#galacticraft.3).

While I understand that your 1.10.2 mod is in beta, I experienced a crash on starting.

https://pastebin.com/0s4UQbPz
Upon removing Tcon, the game starts.

GC - 4.0.0.66 (Beta)

TConstruct-2.6.3
Advanced Generators-0.9.20.23
bdlib 1.12.4.24 (Required for advanced generators)
JEI 3.14.7.417
MCMultiPart (This is apparently a fork of the forge version and required by Mekanism)
Mekanism, Mek Generators, Mek Tools - 9.2.2.301

**Comment by micdoodle8** [comment]
TConstruct requires Mantle, which isn't in your pack. The crash is occurring when forge can't find Mantle.

**Comment by themechman** [comment]
*facepalm* dangit.... thanks.

**Comment by micdoodle8** [comment]
No worries :)
