### ISSUE TITLE
Oxygen Detector not Detecting Oxygen 1.10.2 Build 71

### ISSUE THREAD

**Issue by jobensingh** [micdoodle8/Galacticraft#2634]
When I place down an oxygen detector in an environment with oxygen it does not emit a red stone signal. I have tried on the moon in a oxygen sealed room, on the moon in an oxygen bubble and on Earth.

**Comment by themechman** [comment]
I can confirm this is happening as well. No redstone output from detector.

**Comment by radfast** [comment]
Thanks for beta testing.  We'll take a look at this, shouldn't be too hard to fix.

**Comment by radfast** [comment]
Thanks again.  This will be fixed from build 72, available in the next day or two.

**Comment by radfast** [comment]
[Build 73](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/) is now available
