### ISSUE TITLE
[1.10.2] Volcanic Pickaxe duplicating Galacticraft machinery

### ISSUE THREAD

**Issue by xXJamieXx** [micdoodle8/Galacticraft#2636]
When using Volcanic Pickaxe and breaking Galacticraft machinery, it duplicates the block. Also it doesn't update the blocks because it I go to stand in the blocks it broke, I glitch out and if I try to place a block in the hole it made, the original block comes back.
Example:
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/11248045/25347130/c5962196-2911-11e7-98ce-61d1742cb4c6.gif)

**Comment by radfast** [comment]
oho!  It's supposed to be a powerful item, but not **that** powerful!

**Comment by radfast** [comment]
Thanks for reporting, this is fixed in next build 79.

**Comment by radfast** [comment]
[Build 79](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/#post-43421) now available
