### ISSUE TITLE
[1.10.2] Immersive Engineering Fluid Pump/Pipes cannot pump into GC blocks

### ISSUE THREAD

**Issue by Mike-T4** [micdoodle8/Galacticraft#2637]
Galacticraft machines cannot seem to receive fluid from Immersive Engineering's fluid pipes.
This is especially unfortunate since Galacticraft seems to have no way on it's own to automatically pump water into devices such as the Fluid Tank and/or Water Electoctrolyzer.

I am not 100% certain that this is on GC's end, but GC for 1.10.2 is in BETA whereas Immersive Engineering is currently stable so I decided to post here first.

**Comment by radfast** [comment]
Please can you test the exact same setup for the same machines + fluids using **Galacticraft's own Fluid Tanks and Fluid Pipes** instead, and let me know what happens.  Some screen shots would also be great.

This will help to show me whether it's a problem with these specific machines accepting piped water (e.g. Water Electrolyzer) or a more general problem.

To use a Galacticraft Fluid Tank + Fluid Pipe:  extremely easy, place the tank, grab a few water buckets and right click the buckets on the tank to fill it.  Place a Fluid pipe (at least 2 tiles length) connecting the Fluid Tank to the Water Electrolyzer.  Now use a Standard Wrench to wrench the fluid pipe touching the tank (that one only) into "pull" mode, it's graphic will change to become a bit more solid.

**Comment by Mike-T4** [comment]
Yeah, Galacricraft pipes work. Here's some pictures.
![worksnotfine](https://cloud.githubusercontent.com/assets/12882669/25378272/3768ce2a-29aa-11e7-97dd-9d33b09ba055.png)
![worksfine](https://cloud.githubusercontent.com/assets/12882669/25378273/376a0754-29aa-11e7-845b-30d53731d601.png)

I tried used IE fluid pipes as well. I also tried putting the pump next to the machines, but it didn't work either.

**Comment by radfast** [comment]
You're welcome!

We really appreciate the help and patience of beta testers.

Thanks to this one post I've fixed around 10 potential issues!  Next build 74 should work with Immersive Engineering and every other pipes/tanks mod in 1.10.2.  I've tested it thoroughly with Mekanism, for example.

**Comment by radfast** [comment]
[Build 75](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/) now available with this fixed.
