### ISSUE TITLE
[1.11] Build 75 Failed

### ISSUE THREAD

**Issue by vos3464** [micdoodle8/Galacticraft#2642]
Build 75 for Minecraft 1.11 failed on Jenkins.

**Comment by kenijey** [comment]
yeah, no download link

**Comment by radfast** [comment]
sorry guys!  wait 30-60 minutes please, I'll get a build 76 made

**Comment by kenijey** [comment]
you're really optimistic :)

**Comment by radfast** [comment]
Build 76 now available.
