### ISSUE TITLE
[1.10.2 outdated build 66] [Modpack] Crash with fluid tanks

### ISSUE THREAD

**Issue by SahkoPete** [micdoodle8/Galacticraft#2649]
I have a server on a modpack where we placed a fluid tank next to a smeltery and it crashed the clients game. The interesting thing is that whenever anyone looks at the tank he gets kicked from the server, so we have now all looked at the tank and are in a situation where we can't join because we get instantly kicked. Then after a while the server crashes. Also I'd like to know if I can disable the tank or something because this is really anoying. Does not seem to affect singlepayer.

Info:
Server: hosted on fluctis
Modpack: ErrorBoysFinlandSpaceRaceLite on TechnicLauncher
MC version: 1.10.2
Galacticraft version: 1.10.2-4.0.0.66-BETA Core and Planets
Forge version: 1.10.2-12.18.3.2254

**Comment by radfast** [comment]
> Also I'd like to know if I can disable the tank or something because this is really anoying.

**Comment by dj3520** [comment]
>The interesting thing is that whenever anyone looks at the tank he gets kicked from the server

Sounds like walia/the one probe

>Then after a while the server crashes

Crash report?

>Modpack: ErrorBoysFinlandSpaceRaceLite on TechnicLauncher

Could we get a list of the mods please?

>Galacticraft version: 1.10.2-4.0.0.66-BETA Core and Planets

Does this still happen with [GC1.10.2-76?](https://ci.micdoodle8.com/job/Galacticraft-1.10/)

**Comment by SahkoPete** [comment]
Well, I'll have to try with the new version. I've got no mod list so I need to make one tomorrow but if you want to check the mods sooner download the pack yourself. The pack has waila and wawla and other addons for it but no oneprobe. I'll also find the crash report tomorrow.

Thanks a lot for answering so soon! ☺
This mod is awesome!

-Pete

**Comment by ThomasAunvik** [comment]
Could it have any connection with #2518 ?

**Comment by radfast** [comment]
@ThomasAunvik  no, the issues you posted at #2518 are specific to Minecraft 1.11.2 

The issue posted in this thread is either due to using an outdated version of galacticraft, or a mod conflict, or something else specific to these guys' server and pack.  Until they post that **crash report** requested, it's pretty difficult to know.

**Comment by SahkoPete** [comment]
Well here is the crash report. I haven't tried updating gc yet but i'll try that soon ...

[crash-2017-04-26_21.32.35-server.txt](https://github.com/micdoodle8/Galacticraft/files/966216/crash-2017-04-26_21.32.35-server.txt)

**Comment by radfast** [comment]
Thank you for the crash report.

This issue was fixed 4 days ago by https://github.com/micdoodle8/Galacticraft/commit/0529fe82170e9eaf3d00c02015820ce7207fadf9

If you update your server + modpack to the latest Galacticraft, you'll find the problem is fixed.

**Comment by SahkoPete** [comment]
Thanks a lot!
