### ISSUE TITLE
[1.10.2] Solar panel behavior on Venus

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#2650]
This is a two fold bug report. One may cancel the other depending on the outcome.

### 1. Solar Panels have too hight environmental boost for Venus

![2017-04-23_20 07 05](https://cloud.githubusercontent.com/assets/6743303/25551130/cfe25366-2c56-11e7-9bc3-99debc422325.png)

Venus has a very thick cloudy atmosphere which would [block almost 100% of the direct sunlight](https://en.wikipedia.org/wiki/Atmosphere_of_Venus#Clouds), however the environmental boost is 137% (3x Moon's).

Since we've got geothermal generators, we could make solar Panels useless with "Sunlight blocked" status, or give them a very low env. boost (-80%).

### 2. Advanced Solar Panels point to the opposite direction

The sun moves in the sky from west to east, but the panels point to the opposite direction -- considering that solar panels are supposed to collect sunlight.

![2017-04-28_21 18 37](https://cloud.githubusercontent.com/assets/6743303/25551239/7826f1ac-2c58-11e7-81d1-2a80b94c1548.png)

**Comment by Agentx49** [comment]
All I can say is lol

**Comment by dj3520** [comment]
>Since we've got geothermal generators, we could make solar Panels useless with "Sunlight blocked" status, or give them a very low env. boost (-80%).

I'd also make the time you can actually make energy pretty low.

**Comment by radfast** [comment]
thanks guys, adjusted in next build 78

**Comment by EzerArch** [comment]
> thanks guys, adjusted in next build 78

Current Environmental Boost in every dim, MC 1.11.2 build 107:
* Overworld: 0%
* O.S.S.: +100%
* Moon: +40%
* Mars: -48.8% (*)
* Asteroids: -23.1% (*)
* **Venus: +137%**

I know the Venus is closer to the Sun, but the solar boost could follow `sunlight = sun_size * (1 - fog_density)` idea, where `fog_density` would be the opacity, ranging from 0.0 (moon, space) to 1.0 (totally opaque).

(* -- the decimals are necessary? I'd round them up/down for sake of simplicity. It's not like we're dealing with engineers. ;-) )

**Comment by radfast** [comment]
We can look forward to Mercury :)

**Comment by EzerArch** [comment]
> We can look forward to Mercury :)

LOL, solar panels would melt on Mercury with so much producing energy.

Still, just to be sure: you got my general idea, didn't you? A solar energy boost that high on Venus not only does not make sense but also makes geothermal generators totally redundant. :<

Since I mentioned "for sake of simplicity", what if we get rid of negative numbers by renaming "Solar Energy Boost" to "Sunlight Intensity"? ([forum post](https://forum.micdoodle8.com/index.php?threads/rename-solar-energy-boost-to-sunlight-intensity.4540/)). Negative boost somewhat sounds like oxymoron to me.

**Comment by C1ffisme** [comment]
@EzerArch
> LOL, solar panels would melt on Mercury with so much producing energy.

 Venus can get hotter than Mercury, though... (Although for the sake of balance, I agree it makes sense to nerf Solar Panels to encourage the player to use Geothermal energy.)

**Comment by radfast** [comment]
On Venus (IRL) it's the clouds which would prevent Solar Panels from being effective.

Fog density (atmospheric scattering) shouldn't have a massive effect as the sunlight is still there, it's just diffuse.

But Venus is a super-cloudy planet, so I agree we should reduce the effectiveness of Solar Panels.

GeoThermal Generators are certainly not totally redundant!  Did you try living on Venus during the Venus night ... ?

**(TODO for the future, we should add a massive amount of clouds on Venus ... and solar panel effectiveness should be reduced if there are clouds in the line of sight (the game is already checking for opaque blocks))**
