### ISSUE TITLE
Text in Space Race GUI is too small to read/Need numbers on color RGB sliders

### ISSUE THREAD

**Issue by darthvader45** [micdoodle8/Galacticraft#2651]
This is a two-parter, so I'll be brief:

1. The text on the brush size slider is a bit too small to read, therefore I cannot tell the size of the brush, and have to estimate using the grid.

2. The RGB sliders have no numbers at all, so I am completely confused as to how to tweak the colors just right to get the correct colors for my flag.  I'd like to see numbers, it'd make it a lot easier to make the flags I want.

Misc: Noticed the grid seems to be 32x48 pixels.

**Comment by radfast** [comment]
Part duplicate of #1790
