### ISSUE TITLE
Just a crash but I may be mistaken

### ISSUE THREAD

**Issue by kenijey** [micdoodle8/Galacticraft#2653]
[crash-2017-04-29_12.10.22-client.txt](https://github.com/micdoodle8/Galacticraft/files/966212/crash-2017-04-29_12.10.22-client.txt)
just i couldn't open the game up, you can close this issue if it's not galacticraft's fault

**Comment by radfast** [comment]
looks like it is our fault, though the underlying cause is strange - is this a fresh game start in single player?

anyhow, this will be fixed from build 78

**Comment by kenijey** [comment]
game just crashed on startup, i couldn't see mainmenu. thanks a lot, i'm glad to i can help you galacticraft developers ^^
