### ISSUE TITLE
A Little Glitch About Arc Lamp

### ISSUE THREAD

**Issue by kenijey** [micdoodle8/Galacticraft#2654]
i'm using sildur's vibrant shaders, and arc lamp works great but it makes very very yellow the ground while using shaders. Is it possible to make it white such as in without shaders? thanks a lot ^^ (using optifine for launch shaders)

**Comment by radfast** [comment]
that's an issue with the shaders, not with Galacticraft - please raise it with them

all we're doing is raising the block lighting levels to 14 or 15, not changing the colors of anything

**Comment by kenijey** [comment]
oh okay, sorry.
