### ISSUE TITLE
[1.11.2] [Sponge server]  Command registration issue

### ISSUE THREAD

**Issue by kenijey** [micdoodle8/Galacticraft#2656]
hello, we're trying to define what causes [THIS](https://github.com/SpongePowered/SpongeForge/issues/1475) problem, and it seems like galacticraft causes this. Can you just look at it? thanks a lot!
and so sorry if it's not galacticraft's fault! thanks..
edit: hey ah, it works without galacticraft. i dunno if this is sponge's problem or GC4.
but it only happens on dedicated server.

**Comment by radfast** [comment]
I don't know if it's Sponge or us.  Because the crash **only** happens with Sponge, it could be a problem their side.  I will look at this later today.

**Comment by kenijey** [comment]
uhm, they said it's %95 not sponge's fault. hope it will be fixed in anyway :( thanks...

**Comment by kenijey** [comment]
i really hope this be fixed :(

**Comment by radfast** [comment]
I've found the problem.

In this case it was a small bug introduced by accident when updating our code from 1.10.2 to 1.11.2.  Easily fixed, this fix will be in next build 79 later today.

I guess this means you are the first person to try Galacticraft with Sponge in 1.11.2, because this issue must affect everyone.

Therefore, please do let us know if you encounter any other issues at all in a Sponge environment.

**Comment by kenijey** [comment]
yeah, i know i am. generally i'm the first person that doing something :D i'm waiting for you relesae the 79, then i will update my modpack to let players join properly :D thanks!

**Comment by kenijey** [comment]
i really need 79 :( could it be available today? thanks

**Comment by kenijey** [comment]
(my players are crying)

**Comment by radfast** [comment]
fixed it for ya :p

**Comment by kenijey** [comment]
but how can i download it :D

**Comment by kenijey** [comment]
in jenkins only b78 is the latest

**Comment by radfast** [comment]
[Build 79](https://ci.micdoodle8.com/job/Galacticraft-1.11/) now available

**Comment by radfast** [comment]
@kenijey   https://wiki.micdoodle8.com/wiki/Galacticraft_4#Servers_and_Sponge   point number (2)

**Comment by kenijey** [comment]
hmmm, @radfast should we report it to the sponge? for fix that smooth landing (hanging in space) ? maybe they can fix it

**Comment by radfast** [comment]
Please report issues with Sponge and Galacticraft to us first.  We will decide whether, and how, to report it to Sponge, or whether to work around it.  In this case we can work around it now that I know about it.

**Comment by kenijey** [comment]
okay ^^ get luck with
