### ISSUE TITLE
[1.10.2][Build 77]Volcanic Pickaxe copy Galacticaft machines

### ISSUE THREAD

**Issue by Pyrom4nia** [micdoodle8/Galacticraft#2657]
Volcanic Pickaxe will copy GC machines after breaking it
But the block didn't actually broke and stuck people which stand on it

**Comment by radfast** [comment]
Thanks for beta testing!  This is a duplicate of #2636 so I will close this as that one is still open.

**Comment by radfast** [comment]
[Build 79](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/#post-43421) now available
