### ISSUE TITLE
Galacticraft frozen fuel problem

### ISSUE THREAD

**Issue by Aragrohl** [micdoodle8/Galacticraft#2660]
This happened when using the 78 Beta galacticraft build and the 7.99.1 alpha buildcraft build, here's the log.
[crash-2017-04-30_19.56.52-client.txt](https://github.com/micdoodle8/Galacticraft/files/966961/crash-2017-04-30_19.56.52-client.txt)

**Comment by dj3520** [comment]
From https://github.com/BuildCraft/BuildCraft/issues/3534
Uses 1.11.2

Seems they're having issues with the fluid texture.

**Comment by radfast** [comment]
Thanks guys.  As confirmed by Alex the developer of Buildcraft, it's a Buildcraft alpha issue.  Closing tihs.
