### ISSUE TITLE
[1.10.2] Item selection darkens player model

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#2661]
Selecting and deselecting a drop in the hotbar darkens the player/armor model.

**To reproduce:**
1. Select a hotbar slot and press E
2. Place and remove a drop (works with any item) in/from the selected slot.

![2017-04-30_23 22 48](https://cloud.githubusercontent.com/assets/6743303/25570671/aee045f8-2dfd-11e7-9916-ad801ce2ebd7.png)

With GC:
![dark](https://cloud.githubusercontent.com/assets/6743303/25570421/851cae02-2dfb-11e7-80ac-314f97250dad.gif)

Without GC:
![dark2](https://cloud.githubusercontent.com/assets/6743303/25570871/6bc2e878-2dff-11e7-8ed0-4627589f6c1f.gif)

**Comment by SteveKunG** [comment]
Not only 1.10.2, happened on 1.8.9 as well.

**Comment by radfast** [comment]
I see it.

It's not the selection of the slot causing the problem.  It's the holding the item in the hand, in the player model.

Empty hand: no problem
Item in hand: problem

Must be a GLState issue, but so hard to track down...

**Comment by radfast** [comment]
fixed, thanks guys
