### ISSUE TITLE
[1.10.2] Slimeling inventory "whitens" game view

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#2662]
Accessing Slimeling inventory will "whiten" hotbar, debug screen, and water blocks will appear the player has somewhat taken a Potion of Night Vision.

![2017-05-01_01 02 10](https://cloud.githubusercontent.com/assets/6743303/25571811/fe61474c-2e09-11e7-904f-d21e7a713fd9.png)

**Video:** https://www.youtube.com/watch?v=Qs-I2nNc5sY (video, since screenshot can't depict it fully)

**Comment by radfast** [comment]
duplicate of #2480 U.

sorry Ez!

**Comment by EzerArch** [comment]
> duplicate of #2480 U.

Too bad. I thought this was similar to an issue with MPS, now I see it's quite different: https://github.com/MachineMuse/MachineMusePowersuits/issues/770

**Comment by radfast** [comment]
Fixed by SteveKung in #2665

**Comment by radfast** [comment]
[Build 79](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/#post-43421) now available

**Comment by EzerArch** [comment]
> Fixed by SteveKunG in #2665

You gotta be kiddin me! I need a video. ;)
