### ISSUE TITLE
1.11 #78 - electric furnace not working anymore

### ISSUE THREAD

**Issue by KingNut** [micdoodle8/Galacticraft#2663]
Hello,

my electronic furnace does not melt ores anymore. Status = Idle.
Full gJ energy and Ore Blocks inside of the furnace.

Version: [1.11 Build #78 (29.04.2017 16:00:23)](https://ci.micdoodle8.com/job/Galacticraft-1.11/lastStableBuild/?auto_refresh=true)
Forge: 1.11.2-13.20.0.2228

Downloadlink for map and screenshots: http://kingnut.de/Download/Daten/gc/GC.rar

![gc1](https://cloud.githubusercontent.com/assets/1338366/25567067/1892e770-2de6-11e7-9321-23d497596069.png)

**Comment by radfast** [comment]
hey @KingNut 

You already reported this on #2659 

Like I said there, this is fixed in next **build 79**.  Please be patient while we get build 79 out, it should be later today - maybe even next hour if all goes well.

**Comment by KingNut** [comment]
oh, sry didnt see your post there. Thanks for the great work. You do a great job!

**Comment by radfast** [comment]
no problem at all, we really appreciate the help from beta testers at this stage

**Comment by radfast** [comment]
[Build 79](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/#post-43421) now available
