### ISSUE TITLE
Server Crash with Sponge (again)

### ISSUE THREAD

**Issue by kenijey** [micdoodle8/Galacticraft#2670]
[crash-2017-05-02_09.58.44-server.txt](https://github.com/micdoodle8/Galacticraft/files/969650/crash-2017-05-02_09.58.44-server.txt)

**Comment by kenijey** [comment]
https://github.com/SpongePowered/SpongeForge/issues/1481

**Comment by kenijey** [comment]
here is the only galacticraft and sponge installed crash. forge 2285.
[crash-2017-05-02_10.48.01-server.txt](https://github.com/micdoodle8/Galacticraft/files/969745/crash-2017-05-02_10.48.01-server.txt)

**Comment by kenijey** [comment]
https://github.com/Ivorforce/RecurrentComplex/issues/189

**Comment by kenijey** [comment]
omg, i'm so sorry :D i just forgot to make the tick time 999999

**Comment by radfast** [comment]
RTFM

**Comment by kenijey** [comment]
sorry :( i did just focus on the second part that u mention.

**Comment by radfast** [comment]
To run a successful multiplayer server with Sponge plugins and Forge mods all working correctly is difficult.  You need to pay careful attention to all the documentation!

I recommend read everything on our wiki about configs, compatibility and server setup.

**Comment by radfast** [comment]
hi @kenijey on your server I found a workaround for point 2 so your players will have smooth transfers.

You need to include one extra thing on your command line when you start the server, that's this:
>
     -Dsponge.causeTracking=false 

Example of a complete server launch command line with this (obviously adapt this to your correct Forge version):
>
    java -Xmx2G -Dsponge.causeTracking=false -jar forge-1.11.2-13.20.0.2282-universal nogui

**Comment by kenijey** [comment]
hey, thank you so much! i just add that command in my server.bat. Thanks !
But, i really need help about protecting my spawn :( I tried FTB Utilities, Block Protector mods. They won't work.
And also these plugins: UniverseGuard, FoxGuard, RedProject. They won't work too. I really need help about protecting my spawn :( all i want is protect my spawn from building and enable the interaction. (right click on any block of mod)

**Comment by dj3520** [comment]
Sorry but this isn't a generic help forum.

**Comment by kenijey** [comment]
... issue is already closed

**Comment by kenijey** [comment]
uhm, hey @radfast , if i add that command, sponge being crazy in console. i took a screenshot:
![123](https://cloud.githubusercontent.com/assets/24831406/25656224/ae274468-3000-11e7-8d12-1ccb9b3ed1c0.png)
it happens like this and it produces it very very fast and forever. should i report it to sponge?

**Comment by radfast** [comment]
ok then maybe don't add that command line flag, seems like it does something weird in your specific version of Sponge

Try updating to Galacticraft version 80, you may be OK with that.

**Comment by kenijey** [comment]
i already did ^^

**Comment by radfast** [comment]
Please be more clear.   Everything is working correctly for your players in version 80 **without** the command line flag, or there is still some issue?

**Comment by kenijey** [comment]
i installed GC b80 yet, now trying it. i will add comment or edit this comment after 5 mins.

**Comment by kenijey** [comment]
oh no ah, it crashed again. here is the crash report
[crash-2017-05-03_16.17.12-server.txt](https://github.com/micdoodle8/Galacticraft/files/973409/crash-2017-05-03_16.17.12-server.txt)

**Comment by kenijey** [comment]
but i think it's about morpheus mod crash, that sponge crashes. 
https://github.com/SpongePowered/SpongeForge/issues/1483
https://github.com/Quetzi/Morpheus/issues/36#event-1065888881

**Comment by kenijey** [comment]
so we should wait sponge to fix that crash fix

**Comment by radfast** [comment]
Yes that's the Morpheus / Sponge issue.  On a Sponge server, you'll need to delete Morpheus from your mods folder, until a solution is found by one of those teams.

**Comment by kenijey** [comment]
hmm, should i try it with deleting morpheus mode?
