### ISSUE TITLE
Mod Compatibility Crash

### ISSUE THREAD

**Issue by kenijey** [micdoodle8/Galacticraft#2671]
morpheus mod is installed, and i just went to mars; server crashed.
here is the crash report, i will report this to morpheus when you say "it's not about galacticraft"
[crash-2017-05-02_18.45.59-server.txt](https://github.com/micdoodle8/Galacticraft/files/971006/crash-2017-05-02_18.45.59-server.txt)

**Comment by micdoodle8** [comment]
As you said, this appears to be unrelated to Galacticraft. I'm looking at the Morpheus code along with the stack trace and nothing leads me to believe this is on our side.

**Comment by kenijey** [comment]
okay ^^

**Comment by radfast** [comment]
I checked this also.  It's not looking like a Galacticraft bug.

Looking at Morpheus sources, I can't see why their code is erroring - possibly the version you have is not their latest build?

 If reporting this as a bug at Morpheus, you can tell them that Galacticraft changed the player dimension, and fired a ```PlayerChangedDimensionEvent``` (this last part is important, it will help them I think).  I can see they have an EventHandler for that.

**Comment by kenijey** [comment]
uhm i reported this to morpheus, they said report it to sponge. then i reported to sponge, they closed it because it's dupe :D

**Comment by dj3520** [comment]
Comment on the dupe saying you're having the same issue.

**Comment by kenijey** [comment]
yeah i didn't see the dupe because it's on the 3. page.
