### ISSUE TITLE
Non-creative players may only interact with 'Infinite Tanks/Batteries'.

### ISSUE THREAD

**Issue by Axiom1999** [micdoodle8/Galacticraft#2673]
This is a request (feature) to have the creative oxygen tanks and batteries to not be interactable, exempt those in creative mode/opped.

This allows for permanent setups of oxygen refill stations without the worry of people stealing the infinite oxygen/battery supply.

**Comment by radfast** [comment]
feature requests on the forum please

This one is very unlikely to be accepted.  If your server has worldguard or other region /  block permissions plugins, you can simply set up an Oxygen Storage Module which the player cannot interact with, and feed the oxygen from that into the machine you want the player to interact with.  Same with the power.

Personally I find it very useful having access to the creative oxygen item through NEI/JEI in survival mode, it means I can test that other parts of the mod are properly functioning in survival mode without worrying about running out of oxygen.
