### ISSUE TITLE
[1.10.2]Mobs disregard Suffocation Cooldown & Damage config settings

### ISSUE THREAD

**Issue by Mike-T4** [micdoodle8/Galacticraft#2676]
The _"Suffocation Cooldown"_ and _"Suffocation Damage"_ config options work fine for players.
Mobs however, will not respect this setting and will always die at the default rate.

**Comment by radfast** [comment]
Lol, this is a suggestion disguised as an issue report.

It's extremely easy to implement though, so I'll put something in later today.

**Comment by Mike-T4** [comment]
> Lol, this is a suggestion disguised as an issue report.

I didn't think this was a bug but it very much seemed like an oversight.
Why would mobs suffocate slower than players do?

**Comment by radfast** [comment]
I've clamped the suffocation cooldown to the range 50-250 for players **and** entities.

**Comment by radfast** [comment]
[Build 81](https://ci.micdoodle8.com/job/Galacticraft-1.11/81/) now available

**Comment by EzerArch** [comment]
> Lol, this is a suggestion disguised as an issue report.

Rather improvement or consistency request? :)
