### ISSUE TITLE
[1.10.2] EnderIO fluid conduits causes NPE.

### ISSUE THREAD

**Issue by Axiom1999** [micdoodle8/Galacticraft#2679]
**Build** compiled manually.

**Crashlog** https://hastebin.com/aloxurutak.scala

**What was I doing?** Tried to connect an EnderIO fluid conduit from an Oxygen Collector to an Oxygen Sealer.

**Comment by radfast** [comment]
Which Galacticraft version is this?  Looks like you self-compiled it from the sources, can you let me know which day you compiled it so I can match it up with our code on that day?

**Comment by Axiom1999** [comment]
Two days ago maybe.

**Comment by radfast** [comment]
Thanks, should be fixed in next build.  I don't really think EnderIO should be trying to fill our machines with null fluids, but anything's possible and therefore we ought to make our machines resilient to that.

**Comment by radfast** [comment]
[Build 83 is now available](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/#post-43464)
