### ISSUE TITLE
[1.10.2] Fluid Pipes refuse to provide to Oxygen Compressor.

### ISSUE THREAD

**Issue by Axiom1999** [micdoodle8/Galacticraft#2680]
**Build** compiled manually.

**Crashlog** there is none.

**Description** Essentially, I've tried to fill fluid tanks and it works, but it seems the other machines refuse to accept oxygen.

**Comment by radfast** [comment]
Thanks for testing this.  Same comment as on your other issue report, can you let me know which day you compiled it so I can match it up with our code on that day?

**Comment by Axiom1999** [comment]
Two days ago perhaps. I'd re-compile the latest right now, but I don't have time at the moment, sorry!

**Comment by radfast** [comment]
ok thanks.  It's working correctly in 1.8.9, but not in 1.10.2 I guess.

**Comment by radfast** [comment]
thanks again, this is now fixed from next build.

**Comment by radfast** [comment]
[Build 83 is now available](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/#post-43464), or the sources are now stable if you want to compile yourself.
