### ISSUE TITLE
[1.11.2] Compatibility issues (I think)

### ISSUE THREAD

**Issue by SpatiumPrinceps** [micdoodle8/Galacticraft#2681]
Hello fellow galacticrafters, 

thank you for updating and maintaining galacticraft. I absolutly love this mod! 
When threw a few mods together, fired up the server, there were a few minor errors:
https://hastebin.com/awocuxiwuz.md
I'm not sure, it looks like a issue with ic2, since the methods from ic2api are not available. Probably you compiled against a different version then the latest ic2 version?
IC2: 2.7.25-ex111 (latest version, just a released a few minutes ago) 
Forge: 2294
GC4: 81
Biomes o plenty: 6.1.0.2210
TContstructs: 2.7.0.9

Thank you for your efforts! 
Kind regards, Spatium

**Comment by radfast** [comment]
Hello Spatium, thanks for testing and thanks for this info.

Yes, we didn't use the latest IC2 because we didn't have it!  Hopefully we can fix this right away, or even make it so that Galacticraft works OK with **either** the latest **or** the non-latest IC2.  That's our usual style...

**Comment by radfast** [comment]
This will be fixed in next build 82, available some time this weekend.

Please let us know of any more compatibility issues you spot!

**Comment by radfast** [comment]
Fixed in [Build 83 is now available](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/#post-43464)
