### ISSUE TITLE
[Actually Additions] oil can be picked up with wooden bowl

### ISSUE THREAD

**Issue by AmazigJj** [micdoodle8/Galacticraft#2682]
the version: MC 1.10.2 GC: 4.0.0.80
I am able to pick up galacticraft oil with a wooden bowl and get a bucket of oil, and when emptied it is a normal iron bucket
I am playing a mudpack, but no other liquids seems to have this happen to them, and the only other liquid to be picked up by a bowl is water which becomes a bowl of water, and stays as a bowl when emptied

**Comment by EzerArch** [comment]
> bowl of water

Is it a modded bowl? If [the vanilla wiki is not wrong](http://minecraft.gamepedia.com/Bowl#Usage), bowls aren't supposed to collect water.

**Comment by AmazigJj** [comment]
It is the vanilla bowl, but actually additions makes it pick up water. This was why i said it was a modpack and said water could be picked up with a bowl.

**Comment by radfast** [comment]
Fixed in [Build 83 now available](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/#post-43464)
