### ISSUE TITLE
[1.11.2] Minecraft Crash

### ISSUE THREAD

**Issue by Yspatil** [micdoodle8/Galacticraft#2683]
Hi,

My Minecraft keeps on crashing whenever I try to load it up and I keep getting this message:

The game crashed whilst initializing game
Error: java.lang.IllegalStateException: Failed to set the frozen variant of galacticraftcore:blocks/fluids/fuel_still!

It started happening when I upgraded to beta 80 and so I decided to go back down to beta 79, but it still continued to happen. I've even tried using different forge versions.

**Comment by radfast** [comment]
It's a bug in **Buildcraft** not in Galacticraft.

I think if you update Buildcraft to the latest version, they fixed it now.
