### ISSUE TITLE
Fuel loader won't load fuel.

### ISSUE THREAD

**Issue by Ulisse54** [micdoodle8/Galacticraft#2684]
I am using galacticraft 1.7-3.0.1.2.490 and the title says pretty much all. Fuel loading doesn't work. Power is there, the pad is there, everything is supposed to be as it should but it doesn't work anyways.
This is the DIR from CMD of my mods folder, so that you can see what mods I am running.
```Markdown
10/02/2017  19:26    <DIR>          1.7.10
06/05/2017  18:00         3.594.028 adventurebackpack-1.7.10-0.8b.jar
12/09/2014  07:17            14.362 BetterTitleScreen-1.7.10-1.1.jar
26/04/2015  19:18         5.253.240 BiblioCraft[v1.10.4][MC1.7.10].jar
10/02/2017  21:31         2.699.045 buildcraft-7.1.20.jar
20/01/2017  00:11           510.164 Carpenter's Blocks v3.3.8.1 - MC 1.7.10.jar
21/01/2017  16:47    <DIR>          carpentersblocks
11/01/2017  20:23         1.729.803 cfm-3.4.8-mc1.7.10.jar
13/02/2015  11:26            39.790 ChestTransporter-2.0.3-MC1.7.10.jar
12/01/2017  16:04         6.378.920 Chisel-2.9.5.11.jar
10/02/2017  19:20         1.230.523 CoFHCore-[1.7.10]3.1.3-327.jar
11/01/2017  20:20         1.397.415 ComputerCraft1.75.jar
10/02/2017  19:17           349.595 CraftGuide-1.6.8.2-forge.jar
20/01/2017  15:42        12.751.950 Decocraft-2.3.6.1_1.7.10.jar
20/01/2017  00:11             7.079 FastLeafDecay-1.7.10-1.4.jar
14/01/2017  03:25         1.392.979 Flans Mod-1.7.10-4.10.0.jar
06/05/2017  17:54            21.071 Flashlight-1.7.10-1.0.jar
25/10/2014  20:44         1.193.160 FoodPlus-1.7.2-3.2rS.jar
06/05/2017  20:51         3.162.309 Galacticraft-Planets-1.7-3.0.12.490.jar
06/05/2017  20:51         9.331.687 GalacticraftCore-1.7-3.0.12.490.jar
06/08/2014  02:27           224.461 InventoryTweaks-1.59-dev-152.jar
22/01/2017  12:44           373.500 IvToolkit-1.2.1.jar
12/01/2017  02:16           648.081 malisiscore-1.7.10-0.14.3.jar
12/01/2017  02:15         1.645.689 malisisdoors-1.7.10-1.13.2.jar
06/05/2017  20:51            64.913 MicdoodleCore-1.7-3.0.12.490.jar
10/02/2017  21:30         1.767.447 MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar
10/02/2017  19:24           753.280 MrTJPCore-1.1.0.33-universal (2).jar
20/01/2017  00:11         3.937.655 NuclearCraft-1.9e--1.7.10.jar
08/04/2015  19:56         2.062.557 Pam's HarvestCraft 1.7.10h.jar
11/02/2017  09:43           265.255 PlayerAPI-1.7.10-1.2.jar
11/01/2017  20:48         1.432.027 ProjectRed-1.7.10-4.7.0pre12.95-Base.jar
11/01/2017  18:47            84.757 ProjectRed-1.7.10-4.7.0pre12.95-Compat.jar
11/01/2017  20:48         1.654.657 ProjectRed-1.7.10-4.7.0pre12.95-Fabrication.jar
11/01/2017  21:13         3.913.048 ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar
11/01/2017  18:47           633.621 ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar
11/01/2017  18:47         2.118.480 ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar
11/01/2017  18:47           478.879 ProjectRed-1.7.10-4.7.0pre12.95-World.jar
21/01/2017  16:48           182.350 Reis-Minimap-Mod-1.7.10.jar
20/01/2017  15:48            92.931 SlimeVoid-Library-1.7.10.jar
10/02/2017  16:28           113.256 TooManyItems-Mod-Forge-1.7.10.jar
13/01/2017  15:05         1.461.467 worldedit-forge-mc1.7.10-6.1.1-dist.jar
22/01/2017  12:12         1.361.162 YeGamolChattels-1.1.2.jar
29/04/2015  17:42           645.760 [1.7.10]DamageIndicatorsMod-3.2.3.jar
```
Note that I was using 1.7-3.0.1.2.465 before and just lately I updated to 1.7-3.0.1.2.490 to see if the issue would be fixed, of course it didn't work.
My forge version is 1.7.10-Forge10.13.4.1614-1.7.10.

**Comment by radfast** [comment]
The usual reason for this is you are trying to load fuel in the wrong side...

Please try the other side.  If it still doesn't work, please provide some screenshots to explain **exactly** what isn't working (you can drag the image file into this thread and it will auto-upload it)

**Comment by Ulisse54** [comment]
@radfast I forgot to mention that: I use buckets & canisters to put fuel into the loader. Apologies.

**Comment by radfast** [comment]
please provide screenshots, because this should definitely be working in 3.0.12.490

Is the fuel tank bar in the machine's GUI filling up with yellow fuel?

**Comment by Ulisse54** [comment]
![2017-05-06_22 09 21](https://cloud.githubusercontent.com/assets/25094434/25772183/d7fc2042-32a8-11e7-953d-1233a6964f77.png)
![2017-05-06_22 09 10](https://cloud.githubusercontent.com/assets/25094434/25772184/d8332a4c-32a8-11e7-8b93-ef659df405b7.png)
![2017-05-06_22 09 14](https://cloud.githubusercontent.com/assets/25094434/25772185/d845576c-32a8-11e7-9e20-61b9ec927300.png)
There you can see how the fuel input isn't plugged in anything, due to the fact that I use the buckets to put fuel into the loader.  You can also see how the loader has a stable energy source and that it touches the pad. You can also see that the loading button is pressed but the fuel stays in the loader. I also tried putting the fuel loader elsewhere around the rocket launch pad but nothing happened.
It doesn't look like I am doing something wrong in these screencaps, o am I?

**Comment by radfast** [comment]
Your screencaps look correct.

This is extremely strange - so you're saying that rocket on the pad is not filling with fuel?  Does the Fuel Loade fuelr tank goes down at all (meaning the Fuel Loader **thinks** it filled the rocket with some fuel)?

Is it only in this location it's not working?  How about on Overworld?

Are you playing on a server or single player?

I need to reproduce this problem to fix it, but I'm struggling - testing the Fuel Loader in my Minecraft 1.7.10 it works fine.

**Comment by Ulisse54** [comment]
I just made a few tests:
I got back to my launchpad in the space station. Fuelin doesn't work.
I created a new world and quickly arranged a launch site in overworld. Fueling works.
I created space station in the test world. Fueling works.
I got back to the main world and quickly arrange a launch site in overworld. Fueling works.
I launched back to my spacestation. Fueling doesn't work.
I rebuild the pad and everything that's around it. Fueling works.
Well, I really don't know what to say man... I think this is one of those bugs you devs don't even have to worry about in all honesty. Thanks for the help you gave to me, have a great time! :D

**Comment by radfast** [comment]
> I rebuild the pad and everything that's around it. Fueling works.

Interesting!  OK, thanks for letting us know.  WIth any luck this was a "one off".  If it happens again, please comment or re-open and we can investigate further.

One thing, please just check that if you quit your world and re-log, the launchpad and fuelling on the SpaceStation still works OK.

**Comment by Ulisse54** [comment]
yes it does work :|
Apparently it was an issue with that specific entity... thanks again for helping me.
