### ISSUE TITLE
[1.10.2] Fuel loader with Forge buckets of fuel

### ISSUE THREAD

**Issue by bortooo** [micdoodle8/Galacticraft#2685]
-  If I put a GC bucket into the fuel loader it normaly works, but if I put a forge bucket, it gives back an empty bucket and doesn't load the fuel

![2017-05-06_17 53 25](https://cloud.githubusercontent.com/assets/28114042/25774033/7be884fa-3288-11e7-9711-4b9909d38ffc.png)

- ~I tried to fill a fuel loader with GC fuel from an enderio tank with fluid pipe but it didn't work, then I tried with enderio fluid conduict and it worked.~

![2017-05-06_18 04 18](https://cloud.githubusercontent.com/assets/28114042/25774102/b824e156-3289-11e7-815d-dfc13be02e6d.png)

I think fuel loader hates me :(

**Comment by radfast** [comment]
Fluid Pipes had a bug in 1.10.2, it should be fixed in build 82.

The bucket issue is also probably now fixed.  Please do try build 82, it will be available ~1 hour from now.  I'll post when it's ready.

**Comment by bortooo** [comment]
Thanks! But I still think fuel loader hates me

**Comment by radfast** [comment]
I'm sure it doesn't :)   (no more than it hates any of us, making it work all day for no pay...)

**Comment by radfast** [comment]
[Build 83 is now available](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/#post-43464)

If Fuel Loader is not working in that, please re-open.

**Comment by bortooo** [comment]
> If I put a GC bucket into the fuel loader it normaly works, but if I put a forge bucket, it gives back an empty bucket and doesn't load the fuel 

I tested in build 84 and it still doesn't work

**Comment by radfast** [comment]
You didn't say about the fluid pipe, so I guess that is now working?

**Comment by bortooo** [comment]
Yes, it works normally

**Comment by radfast** [comment]
Thanks.  Buckets now fixed properly in next build 85.

**Comment by bortooo** [comment]
That's great! I think I will use fluid conduict or pipe, but I wait GC release before creating a survival world.
How long do you think it will take?
