### ISSUE TITLE
Crash on Startup Build: 83 Version: 1.10.2

### ISSUE THREAD

**Issue by jobensingh** [micdoodle8/Galacticraft#2688]
For some reason my server crashes on startup, It only has sponge and galacticraft on it. 
Crash Report:
https://pastebin.com/kcriM9b1

**Comment by radfast** [comment]
hi, looks like same as #2687 

I'm working on a solution, will update you when it's ready.

**Comment by radfast** [comment]
Fixed in build 84 now available.
