### ISSUE TITLE
Sponge Server GC out of memory error

### ISSUE THREAD

**Issue by enterprise12nx** [micdoodle8/Galacticraft#2697]
I am creating a private modpack using Sponge for the server, without Galacticraft once the server is started up, within 30 seconds it gives an out of memory error.
With Galacticraft removed, this error is not present and the game runs smooth.

I am using build 1.10.2-4.0.0.84-BETA

I tested this multiple times, not sure if its how its interacting with sponge or something?
Here are the logs:
[crash-2017-05-08_11.33.25-server.txt](https://github.com/micdoodle8/Galacticraft/files/984029/crash-2017-05-08_11.33.25-server.txt)

[fml-server-latest.txt](https://github.com/micdoodle8/Galacticraft/files/984030/fml-server-latest.txt)
[latest.txt](https://github.com/micdoodle8/Galacticraft/files/984031/latest.txt)

**Comment by enterprise12nx** [comment]
Sorry didnt mean to make two, github kept saying there was an error posting it, when it apparently posted it anyways >.>

**Comment by radfast** [comment]
UPDATE:  this is actually a manifestation of the conflict with **Geographicraft**, fixed in our next build 86.

It's not an EnderIO error, after all.  Just bad luck that EnderIO triggered the out-of-memory error report.

**Comment by radfast** [comment]
[Build 85 now available](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/) - fixes the compatibility with Geographicraft.
