### ISSUE TITLE
Sponge Server [Geographicraft] Build 85 New Error

### ISSUE THREAD

**Issue by enterprise12nx** [micdoodle8/Galacticraft#2700]
The out of memory error is fixed, but i am now getting a new error.
[crash-2017-05-09_23.19.42-server.txt](https://github.com/micdoodle8/Galacticraft/files/988602/crash-2017-05-09_23.19.42-server.txt)
[latest.txt](https://github.com/micdoodle8/Galacticraft/files/988604/latest.txt)
[fml-server-latest.txt](https://github.com/micdoodle8/Galacticraft/files/988605/fml-server-latest.txt)

**Comment by radfast** [comment]
Thanks for testing it so fast.

Please try [build 86](https://ci.micdoodle8.com/job/Galacticraft-1.10/), that should fix this.

**Comment by enterprise12nx** [comment]
laucnhed and currently working.
Np, if anything i thank you, i tried 2 coding classes in college and couldnt wrap my head around anything but the basics.  I know you guys dont make nearly any $$$ from this, but there are a lot of us who really appreciate what you do, bringing fun to minecraft through your mod, its so in depth and has so many features, this is definitly one of my top 5 mods out of the hundreds i use.  Never feel rushed to do things for anyone here, your not paid todo it, this is your own personal/fun project and i hope you can enjoy it in that way.
Thanks again.

**Comment by radfast** [comment]
thanks for these words - top 5 mods, I'll take :)

We appreciate fast, accurate issue reports like yours, helps us deal with an issue before thousands of people download it.

Some ways to help the mod:
* include Galacticraft in your modpacks...
* if you make a modpack: keep Galacticraft **updated**
* help other players who have problems with it - especially on forums other than our own, as we probably don't monitor those
* if your language is not English, help keep the Galacticraft lang files for your language updated and correct - this especially helps **younger players** in your country who maybe don't speak English

**Comment by enterprise12nx** [comment]
well you could say top 4, i dont think there is a such thing as #1, theres always improvement!
ya i have been maintaining my modpack "Industrial Age The Turning" for over 4 years and is usually updated to very recent versions(cant update every little mod fix since theres hundreds of mods xD) I usually can figure out whats causing errors since i understand logs pretty well too, so i dont have to rush over to mod authors all the time, sometimes its just a config file problem or a mod conflict i just correct.

I didnt know curseforge had modpacks until today, and i see they pay well too(if your popular) so i may sign mine onto there, it use to be on page 4 of technic before they completely changed their site, my pack went down in the ranks then haha, but its on FTB too.
Heres the modpack: https://www.technicpack.net/modpack/a-new-age-enterprise.55905

**Comment by radfast** [comment]
Looks like a nice pack.  If you want your pack on CurseForge you'll need to include Galacticraft in your pack's own download page there, as Galacticraft is not on CurseForge.  That's allowed by our modpacks permission (no different from including Galacticraft in the FTB or Dropbox versions of your pack).

**Comment by Timsuper** [comment]
@radfast I don't know how to contact you, besides here. You said you need translators. I have a lot of spare time before my studies begin. My languages are German <-> English

**Comment by radfast** [comment]
hey @Timsuper 

Best way to improve a translation is edit the .lang file **directly** on Github, then make a pull request.  
[Example of a pull request](https://github.com/micdoodle8/Galacticraft/pull/2686)

Some more guidance on the exact steps to do this is [here](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md), under "Translation Fixes".

To update, you would need to compare the ```de_DE``` files with the ```en_US``` files, and spot which lines are missing / untranslated in de_DE.  You can also track the history of the en_US to get recent changes, just go to the en_US file on Github and click 'History'.

**Comment by enterprise12nx** [comment]
New update, server launches but there seems to be a new problem.
The client cannot detect the server, and cannot get into SSP.

No errors when connecting to the server except:
java.lang.noclassdeffounderror:com/mumfrey/liteloader/core/event/eventproxy$2

This did not occur before, also the server had:

Upon launching a ssp world the errors were(attached log files)
[crash-2017-05-10_19.40.02-server.txt](https://github.com/micdoodle8/Galacticraft/files/991477/crash-2017-05-10_19.40.02-server.txt)
[fml-client-latest.txt](https://github.com/micdoodle8/Galacticraft/files/991478/fml-client-latest.txt)
[latest.txt](https://github.com/micdoodle8/Galacticraft/files/991479/latest.txt)

**Comment by enterprise12nx** [comment]
So the server launches, but there is a new problem.
The client cannot detect the server, but when trying to join it creates an error(the server recognized that a client is trying to connect)

When trying to create a world it makes the errors attached to this post.
[latest.txt](https://github.com/micdoodle8/Galacticraft/files/991490/latest.txt)
[fml-client-latest.txt](https://github.com/micdoodle8/Galacticraft/files/991491/fml-client-latest.txt)
[crash-2017-05-10_19.40.02-server.txt](https://github.com/micdoodle8/Galacticraft/files/991493/crash-2017-05-10_19.40.02-server.txt)

Further testing, having galacticraft client side shows that it cannot connect to the server it has a red X next to it, and does not even show its online.
I removed it client side and it connects, its still on server side, i double checked that it has the same versions for all 3 jar files.
the server has no errors in any log files.

**Comment by radfast** [comment]
You didn't update to build 86!!!  (Or did you post the wrong logs?)

From your server log you just posted:
>
     MicdoodlePlugin (MicdoodleCore-1.10.2-4.0.0.85-BETA.jar)

Make sure you have matching mod versions on client and server.

**Comment by enterprise12nx** [comment]
Sorry heres the new info, pretty much still the same problem.
Made sure im using the LATEST geographicraft since it was outdated, and double checked that the client and server are using Galacticraft Core, Plants and MicdoodleCore are the same.

The client cannot detect that the server is online, but it does ping it when i try to connect.

Client Logs:
[latest.txt](https://github.com/micdoodle8/Galacticraft/files/991807/latest.txt)
[fml-client-latest.txt](https://github.com/micdoodle8/Galacticraft/files/991808/fml-client-latest.txt)


Server Logs:
[latest.txt](https://github.com/micdoodle8/Galacticraft/files/991805/latest.txt)
[fml-server-latest.txt](https://github.com/micdoodle8/Galacticraft/files/991806/fml-server-latest.txt)

**Comment by radfast** [comment]
It's hard to see that Galacticraft has any connection with pinging servers or making the server menu.

None of our code will become active until after a player has logged in.

Is it possible that you changed something else in your configuration at the same time as bringing Galacticraft into your mods list?

I have noticed that the Minecraft server menu takes a couple of seconds to "populate" with current server info, and things can be a bit weird if you try to login before it did that - so maybe also this is just a question of timing, you might need to give it a bit longer before you click?

It is possible that timing of things can be different with Galacticraft installed, we are a large mod in terms of lines of code and complexity of our ClassTransformer, so Forge + Java might have to "do more" in the setup stage.

**Comment by enterprise12nx** [comment]
no, i tried many times, once galacticraft ONLY is removed client side does it detect the server.
i then have to remove it server side to be able to connect

**Comment by radfast** [comment]
What happens if you have Galacticraft but **not** Mumfrey/LiteLoader?

**Comment by enterprise12nx** [comment]
It works fine if Liteloader is removed

**Comment by radfast** [comment]
I don't know what that message means.

Sounds like Liteloader was the cause of the problem, then.  I'm glad you've found a fix.

**Comment by enterprise12nx** [comment]
Issue is back...going to do a bunch of testing to see what i can come up with, also a little strange this is the Streams/Farseek mod asks for a /fml confirm on EACH world every time i startup, might report it to the author
