### ISSUE TITLE
Game Crash from Launcher

### ISSUE THREAD

**Issue by MrPoopNose** [micdoodle8/Galacticraft#2704]
Hi,

Sorry if this has been posted before, I've had a look and can't seem to find any other posts with the exact same problem.

After not having played Galacticraft in years I've decided to have another go. I updated my Minecraft, Forge and Galacticraft versions to the latest versions but for some reason I get a Game Crash as soon as I click Play from the Launcher. I have no problems opening the vanilla Minecraft, this problem only occurs when attempting to open the Forge version.

Here's my error log:

https://pastebin.com/Kk4n3ker.

Anyone have any ideas?

Thank you!

**Comment by SpatiumPrinceps** [comment]
I'm not a gc dev, and I really have not that much clue, but is it possible, that your forge installation is corrupted? 
Is it possible to launch just forge with no more mods?

**Comment by MrPoopNose** [comment]
I don't think so, I've since redownloaded Forge and still have the same issue.

Yeah it launches fine without mods, it seems to be the Galacticraft files that are the issue, but I've tried 3 different versions and none of them seem to work.

Oh, and I updated to the latest Flash version as well but that hasn't helped either.

**Comment by radfast** [comment]
You can't use the 1.7.10 versions of Galacticraft with Minecraft 1.11.2!!!

Either:
* get the beta 1.11.2 version of Galacticraft from [here](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/) - it's good and stable now, so you should be fine with it
* or roll back your Minecraft and Forge to versions 1.7.10

**Comment by MrPoopNose** [comment]
Oh whoops I didn't realise that was there, I thought I had the most recent version. That worked, THANK YOU!!!
