### ISSUE TITLE
[1.8.9] Crash when i put a rocket on the launch pad [fixable with CCL]

### ISSUE THREAD

**Issue by BlackOking** [micdoodle8/Galacticraft#2705]
When i put the rocket on the launchpad, Minecraft crash and my save was broken.
The crash report : https://pastebin.com/Zj3nGRvG
I don't know if this crash was caused by an another mod, or just by Galacticraft. Si, this is all of my mods : http://prntscr.com/f6km08

(Sorry for my English, i'm French)

**Comment by radfast** [comment]
Thank you for reporting.  I have not seen this crash before, could be a problem between Galacticraft and the latest Forge version?

Please try with Forge version [1.8.9 - 11.15.1.1722](http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.8.9.html) - that's the Recommended version for 1.8.9.

Tell us if that fixes it?

You can also use Forge version 1.8.9 - 11.15.1.1764 : this is the Forge version we test the mod against.

**Comment by radfast** [comment]
updated my comment with links.

We welcome French players, Galacticraft is of Canadian origin.  If you want to help the project, maybe you can add some translations to the [French lang](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/resources/assets/galacticraftcore/lang/fr_FR.lang) file ....  compare this to [en_US](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/resources/assets/galacticraftcore/lang/en_US.lang) you can see some recent changes are not yet in French!

**Comment by BlackOking** [comment]
The problem was resolved when i use CCL. Thanks !
I would like to help you, but i propose you to use Transifex, because it's more easy to translate your apps or mod on this site for the community
