### ISSUE TITLE
[1.10.2] v87 Purple Striped animation at all times on the character

### ISSUE THREAD

**Issue by JAWSAWN** [micdoodle8/Galacticraft#2708]
![image](https://cloud.githubusercontent.com/assets/8208988/25997283/2fb3817a-3724-11e7-888b-b04626ad6b1e.png)

IT happens at all times and there is no way to stop it.

**Comment by radfast** [comment]
Please show a screenshot of your Galacticraft inventory tab.  Are you wearing a Shield Generator?

**Comment by JAWSAWN** [comment]
I do not. But after testing the same version only ny itself it didnt cause it. I also have Extra Planets addon. So there mighty be a problem with that.

**Comment by radfast** [comment]
Please report to @BlesseNtumble.  If you still have issues with **only** Galacticraft present (no addons) please re-open.

If @BlesseNtumble needs something changing in our render, I'm sure he will tell us or, better, make a PR ... :)

**Comment by JAWSAWN** [comment]
Yeah I wasnt really sure which mod was causing it but i remember everything was normal until i updated galacticraft. And Extra Planets didnt update. I guess updates to gc caused ep to do weird things.

**Comment by MJRLegends** [comment]
@radfast Did you mean to tag me there not @BlesseNtumble ?

**Comment by radfast** [comment]
Sorry guys, yes I meant you.

**Comment by MJRLegends** [comment]
@radfast haha no problem, i can fix this issue :D

**Comment by MJRLegends** [comment]
@JAWSAWN Please can you provide me details on what you was doing and what was around the area you was in. As im unable to reproduce this....

**Comment by Axiom1999** [comment]
I also have this issue on my server, it would only be random sometimes it'd be there, sometimes not. I believe re-logging would reset it. But it was visible on my friends player model, and sometimes just me, other times both of us. None of us had the shield generator on.

We do have Extra Planets. We we're only wearing the necessary oxygen gear, and was on Earth when this happened/ing.

I can't give too much information, haven't really tested into it much as it didn't bother us, was just weird.

**Comment by JAWSAWN** [comment]
@Axiom1999 Yeah I joined to server today and it was gone. Interesting. I remember dying before it happened so something to do with that?

**Comment by radfast** [comment]
@MJRLegends  does Extra Planets add more gear items?   Specifically gear item 10?

**Comment by MJRLegends** [comment]
@radfast nope mine start at 5000 for gear ids

**Comment by MJRLegends** [comment]
@JAWSAWN and @Axiom1999 any more advancements on what is causing this issue or how to reproduce it every time? 

cc @radfast

**Comment by IamaPineapple24** [comment]
just put it on then take it off again- that worked for me.
