### ISSUE TITLE
[Suggestion] Custom Arrow gravity for each planets

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#2711]
Other planets have different gravity. So I think should add method into WorldProvider.

Example code.

>
    public float getArrowGravity()
    {
        return 0.005F;
    }

This is my current code that used in my mod.

> 
    public static float getGravityForCustomArrow(EntityArrow arrow, WorldProvider provider)
    {
        if (provider instanceof IArrowGravity)
        {
            return ((IArrowGravity)provider).getArrowGravity();
        }
        else
        {
            return TransformerHooks.getArrowGravity(arrow);
        }
    }

**Comment by radfast** [comment]
Thank you for the suggestion :)
