### ISSUE TITLE
Mekanism Cables Bug

### ISSUE THREAD

**Issue by enterprise12nx** [micdoodle8/Galacticraft#2713]
Mining a mekanism cable causes an hard crash.
[crash-2017-05-12_21.51.26-client.txt](https://github.com/micdoodle8/Galacticraft/files/998266/crash-2017-05-12_21.51.26-client.txt)
[latest.txt](https://github.com/micdoodle8/Galacticraft/files/998267/latest.txt)
[fml-client-latest.txt](https://github.com/micdoodle8/Galacticraft/files/998268/fml-client-latest.txt)

**Comment by radfast** [comment]
Why are you reporting this to us?

Looks like a bug in either **TreeCapitator** or **Mekanism**.
