### ISSUE TITLE
[1.10.2] Minecraft skin renders arm backwards

### ISSUE THREAD

**Issue by Enemeez** [micdoodle8/Galacticraft#2715]
Original:

![capture](https://cloud.githubusercontent.com/assets/28690420/26036512/aeb4a05e-38a4-11e7-8262-d22ed8bd6782.JPG)

Galacticraft:

![2017-05-14_12 52 36](https://cloud.githubusercontent.com/assets/28690420/26036511/9cfe8244-38a4-11e7-9802-5459c5c92442.png)

**Comment by radfast** [comment]
Two right hands could be good ?  :)

**Comment by dj3520** [comment]
better than two left feet 😆
