### ISSUE TITLE
[1.11.2] Crash using Cargo Loader/Unloader serverside

### ISSUE THREAD

**Issue by Urkaz** [micdoodle8/Galacticraft#2716]
I created a server with Galacticraft for some friends and testing the different features I found that using the Cargo Loader/Unloader makes the server crash, more specifically when the last item is removed from the Loader, probably caused by some Null value.

To solve the problem I had to edit the world using an external editor as each time the server was loaded it crashed instantly again.

Here you have the crash reports with the crashes: [crash-reports.zip](https://github.com/micdoodle8/Galacticraft/files/999687/crash-reports.zip)

This is the only mod I'm using in addition to BiomesOPlenty (but it wasn't used to generate the world).

Version: 4.0.0.87-BETA

**Comment by micdoodle8** [comment]
Thanks for beta testing! This will be fixed in the next build.
