### ISSUE TITLE
[1.7.10] Question/Change request

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft#2717]
Hello

Im a bit confused to why the Astro Miner is because added via getDungeonLoot to Tier 2 and Tier 3 when only Tier 1 and 2 are being used in 1.7.10 Galacticraft. 

I've noticed this is causing issues with More Planets as when i go to a more planets, planet i get the Astro Miner schematic as a 50%, when i should be getting a 100% chance of a Tier 5 Schematic... Seems to a bit weird to me that two dungeons offer the chance of the Astro Miner Schematic haha.
 
cc @SteveKunG

**Comment by BlesseNtumble** [comment]
GalacticraftRegistry.getDungeonLoot(3).clear();

**Comment by MJRLegends** [comment]
@BlesseNtumble that could work yeah but the only issue is I need the change for a mod pack not my addon so have no where to run that code too

**Comment by radfast** [comment]
Fixed in next build 496.
