### ISSUE TITLE
[1.11.2] Treasure chest stays open when unlocked

### ISSUE THREAD

**Issue by martinm236** [micdoodle8/Galacticraft#2720]
When I open Tier 3 treasure chest, chest is open always.

![2017-05-16_18 55 04](https://cloud.githubusercontent.com/assets/15073172/26118201/43f881ba-3a69-11e7-83bb-9479390059b4.png)

**Comment by martinm236** [comment]
Version 4.0.0.90

**Comment by ThomasAunvik** [comment]
Intended Behavior.

**Comment by radfast** [comment]
Thanks guys.

All our Treasure Chests do this, so that you can see from a distance that it's been unlocked.
