### ISSUE TITLE
[1.10.2] Build 90: Extreme FPS lag when breaking blocks near oil underground

### ISSUE THREAD

**Issue by Enemeez** [micdoodle8/Galacticraft#2721]
![2017-05-16_19 54 59](https://cloud.githubusercontent.com/assets/28690420/26136254/7bee5628-3a80-11e7-911d-8b56866863c7.png)

**Comment by SteveKunG** [comment]
It happened in 1.8.9 as well.

**Comment by radfast** [comment]
We will investigate.

[ Note: possible link with #1712 ? ]

**Comment by SteveKunG** [comment]
Looks like custom Material issue, In my development. I've changed `GCFluids.materialOil` to `Material.water`, everything work fine.

**Comment by radfast** [comment]
Thanks for reporting, should be fixed from next build.
