### ISSUE TITLE
[1.7.10]create a another folder dim-29 wich crash my game

### ISSUE THREAD

**Issue by tonimark** [micdoodle8/Galacticraft#2724]
every time I play my world on galacticraft the dimension manager creates another -29 folder wich cause the world to crash every time I join to it I have installed the extra planets mod latest versions and amun-ra (motherships for galacticraft)  but I see this issue of empty folder recreation for galacticraft  wich cause the crashes here is the log:
hi my game crash when I approach the mars also I got a bigger problem now: when I join after game initialized it crashes when I join back to my world here is the crash log: NOTE: I have installed the extra planets mod on latest versions tell me if I need to uninstall this mod, the log:
error:java.lang.IllegalArgumentException: Could not get provider type for dimension -29, does not exist

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 19/5/2017 3:34 μμ
Description: Exception ticking world

java.lang.IllegalArgumentException: Could not get provider type for dimension -29, does not exist
at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:148)
at net.minecraftforge.common.DimensionManager.shouldLoadSpawn(DimensionManager.java:268)
at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:347)
at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:165)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:148)
at net.minecraftforge.common.DimensionManager.shouldLoadSpawn(DimensionManager.java:268)
at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:347)
at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:165)

-- Affected level --
Details:
Level name: test
All players: 0 total; []
Chunk stats: ServerChunkCache: 1 Drop: 1
Level seed: -5525551069869740059
Level generator: ID 00 - default, ver 1. Features enabled: false
Level generator options:
Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Level time: 0 game time, 0 day time
Level dimension: 0
Level storage version: 0x00000 - Unknown?
Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
Level game mode: ERROR NullPointerException: null
Stacktrace:
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
Minecraft Version: 1.7.10
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_51, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 132529248 bytes (126 MB) / 1269825536 bytes (1211 MB) up to 2102919168 bytes (2005 MB)
JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -Xmn128M
AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
IntCache: cache: 11, tcache: 95, allocated: 0, tallocated: 0
FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D7 96 mods loaded, 96 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar)
UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar)
UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar)
UCHIJAAAA	appliedexchange-core{1} [Applied Exchange Core] (minecraft.jar)
UCHIJAAAA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar)
UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar)
UCHIJAAAA	ivtoolkit{1.2.1} [IvToolkit] (minecraft.jar)
UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar)
UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar)
UCHIJAAAA	OpenEye{0.8} [OpenEye] (OpenEye-1.7.10-0.8.jar)
UCHIJAAAA	ThE-core{1.0.0.1} [Thaumic Energistics Core] (minecraft.jar)
UCHIJAAAA	{000} [CoFH ASM] (minecraft.jar)
UCHIJAAAA	{0} [DragonAPI ASM Data Initialization] (minecraft.jar)
UCHIJAAAA	psychedelicraftcore{1.4} [Psychedelicraft Core] (minecraft.jar)
UCHIJAAAA	mcpml{10.1} [Partial Modification Loader [for Minecraft]] (PML_MinecraftApp.jar)
UCHIJAAAA	seasonsmod{pre-3.0beta13d5} [The Seasons Mod] ([1.7.10]TheSeasonsMod-pre-3.0beta13d5.jar)
UCHIJAAAA	seasonsmodac{1.0} [Additional Seasons Content] ([1.7.10]TheSeasonsMod-pre-3.0beta13d5.jar)
UCHIJAAAA	myfit{1.9} [MyFit] (1.7.10-myfit-2.0.jar)
UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar)
UCHIJAAAA	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8c.jar)
UCHIJAAAA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar)
UCHIJAAAA	ae2ee3emcaddon{1.7.10-b8-universal} [AE2 EE3 EMC Addon] (ae2ee3emcaddon-1.7.10-b8-universal (1).jar)
UCHIJAAAA	bdlib{1.9.4.109} [BD Lib] (bdlib-1.9.4.109-mc1.7.10 (1).jar)
UCHIJAAAA	ae2stuff{0.5.0.56} [AE2 Stuff] (ae2stuff-0.5.0.56-mc1.7.10.jar)
UCHIJAAAA	AgriCraft{1.7.10-1.5.0} [AgriCraft] (AgriCraft-1.7.10-1.5.0.jar)
UCHIJAAAA	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar)
UCHIJAAAA	AmnesiaLights{1.1.1} [Amnesia Lights] (AmnesiaLights-1.7.10-1.1.1.jar)
UCHIJAAAA	BuildCraft|Core{7.1.21} [BuildCraft] (buildcraft-7.1.21.jar)
UCHIJAAAA	BuildCraft|Energy{7.1.21} [BC Energy] (buildcraft-7.1.21.jar)
UCHIJAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.495.jar)
UCHIJAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.495.jar)
UCHIJAAAA	GalacticraftAmunRa{0.4.5} [Pra's Galacticraft Mod] (AmunRa-GC-0.4.5.jar)
UCHIJAAAA	antiqueatlas{1.7.10-4.2.10} [Antique Atlas] (antiqueatlas-1.7.10-4.2.10.jar)
UCHIJAAAA	AppleCore{1.3.9} [AppleCore] (AppleCore-mc1.7.10-1.3.9.jar)
UCHIJAAAA	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (ArchimedesShips-1.7.1.jar)
UCHIJAAAA	betterrecords{1.7.10-1.2.1} [Better Records] (betterrecords-1.7.10-1.2.1.jar)
UCHIJAAAA	BiblioCraft{1.11.5} [BiblioCraft] (BiblioCraft[v1.11.5][MC1.7.10].jar)
UCHIJAAAA	BuildCraft|Builders{7.1.21} [BC Builders] (buildcraft-7.1.21.jar)
UCHIJAAAA	BuildCraft|Factory{7.1.21} [BC Factory] (buildcraft-7.1.21.jar)
UCHIJAAAA	BuildCraft|Robotics{7.1.21} [BC Robotics] (buildcraft-7.1.21.jar)
UCHIJAAAA	BuildCraft|Silicon{7.1.21} [BC Silicon] (buildcraft-7.1.21.jar)
UCHIJAAAA	BuildCraft|Transport{7.1.21} [BC Transport] (buildcraft-7.1.21.jar)
UCHIJAAAA	ThermalFoundation{1.7.10R1.2.6} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.6-118.jar)
UCHIJAAAA	ThermalExpansion{1.7.10R4.1.5} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.5-248.jar)
UCHIJAAAA	BuildCraft|Compat{7.1.6} [BuildCraft Compat] (buildcraft-compat-7.1.6.jar)
UCHIJAAAA	CarpentersBlocks{3.3.8.1} [Carpenter's Blocks] (Carpenter's Blocks v3.3.8.1 - MC 1.7.10.jar)
UCHIJAAAA	CrossbowMod2{a0.1.6} [Crossbow Mod 2] (Crossbow-Mod-2-1.7-0.2.14.jar)
UCHIJAAAA	darkcore{0.3} [Dark Core] (darkcore-0.3-86.jar)
UCHIJAAAA	numina{0.4.1.104} [Numina] (Numina-0.4.1.104.jar)
UCHIJAAAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar)
UCHIJAAAA	Railcraft{9.12.2.0} [Railcraft] (Railcraft_1.7.10-9.12.2.0.jar)
UCHIJAAAA	powersuits{1.7.10-0.11.1.114} [MachineMuse's Modular Powersuits] (ModularPowersuits-1.7.10-0.11.1.114.jar)
UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar)
UCHIJAAAA	tc{4.3.2_009} [Traincraft] (Traincraft-4.3.2_009.jar)
UCHIJAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar)
UCHIJAAAA	DragonAPI{1.0} [DragonAPI] (DragonAPI 1.7.10 V16d.jar)
UCHIJAAAA	Eln{@Version@} [Electrical Age] (ElectricalAge-1.14.2.jar)
UCHIJAAAA	RotaryCraft{1.0} [RotaryCraft] (RotaryCraft 1.7.10 V16d.jar)
UCHIJAAAA	ElectriCraft{1.0} [ElectriCraft] (ElectriCraft 1.7.10 V16d.jar)
UCHIJAAAA	enviromine{1.3.124} [EnviroMine] (EnviroMine-1.3.124.jar)
UCHIJAAAA	extracells{2.3.14} [Extra Cells 2] (ExtraCells-1.7.10-2.3.14b197.jar)
UCHIJAAAA	ExtraPlanets{1.7.2} [ExtraPlanets] (ExtraPlanets-1.7.2.jar)
UCHIJAAAA	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10Lb.jar)
UCHIJAAAA	ExtraTiC{1.4.6} [ExtraTiC] (ExtraTiC-1.7.10-1.4.6.jar)
UCHIJAAAA	Steamcraft{0.29.3} [Flaxbeard's Steam Power] (FSP-1.7.10-0.29.3.jar)
UCHIJAAAA	iChunUtil{4.0.0} [iChunUtil] (iChunUtil-4.0.0.jar)
UCHIJAAAA	intellie{2.2.1.610} [IntelliE] (IntelligentEnergistics-1.7.10-2.2.1.610-universal.jar)
UCHIJAAAA	appaero{2.2.1.610} [AppliedAerodynamics] (IntelligentEnergistics-1.7.10-2.2.1.610-universal.jar)
UCHIJAAAA	appaeronei{2.2.1.610} [AppliedAerodynamicsNEI] (IntelligentEnergistics-1.7.10-2.2.1.610-universal.jar)
UCHIJAAAA	appint{${version}} [AppliedIntelligences] (IntelligentEnergistics-1.7.10-2.2.1.610-universal.jar)
UCHIJAAAA	LogisticsPipes{0.9.3.129} [Logistics Pipes] (logisticspipes-0.9.3.129.jar)
UCHIJAAAA	RadixCore{2.1.3} [RadixCore] (RadixCore-1.7.10-2.1.3-universal.jar)
UCHIJAAAA	MCA{1.7.10-5.2.2} [Minecraft Comes Alive] (MCA-1.7.10-5.2.2-universal.jar)
UCHIJAAAA	meteors{2.14.3} [Falling Meteors] (meteors-1.7.10-2.14.3.jar)
UCHIJAAAA	p455w0rdslib{1.0.4} [p455w0rd's Library] (p455w0rdslib-1.7.10-1.0.4 (1).jar)
UCHIJAAAA	psychedelicraft{1.5.2} [Psychedelicraft] (Psychedelicraft-1.5.2 (2).jar)
UCHIJAAAA	RedstoneArsenal{1.7.10R1.1.3} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.3-97 (1).jar)
UCHIJAAAA	corerm{1.0c} [RikMuld's Core] (RikMuldsCore_1.0c.jar)
UCHIJAAAA	rivalrebels{1.7.10W} [Rival Rebels] (rivalrebels-1.7.10W.jar)
UCHIJAAAA	ropebridge{1.3} [Rope Bridge] (RopeBridge-v1.3-mc1.7.10.jar)
UCHIJAAAA	simplyjetpacks{1.5.3} [Simply Jetpacks] (SimplyJetpacks-MC1.7.10-1.5.3.jar)
UCHIJAAAA	SolarFlux{1.7.10-0.8b} [Solar Flux] (SolarFlux-1.7.10-0.8b.jar)
UCHIJAAAA	SpiceOfLife{1.3.8} [The Spice of Life] (SpiceOfLife-mc1.7.10-1.3.8.jar)
UCHIJAAAA	StevesCarts{2.0.0.b18} [Steve's Carts 2] (StevesCarts2.0.0.b18.jar)
UCHIJAAAA	Sync{4.0.1} [Sync] (Sync-4.0.1.jar)
UCHIJAAAA	TardisMod{0.994} [Tardis Mod] (tardismod-1.7.10-0.994-124-DS.jar)
UCHIJAAAA	thaumicenergistics{1.0.0.5-RV2} [Thaumic Energistics] (thaumicenergistics-1.0.0.5-RV2.jar)
UCHIJAAAA	camping{2.1g} [The Camping Mod 2] (TheCampingMod_2.1g.jar)
UCHIJAAAA	ThermalDynamics{1.7.10R1.2.1} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.2.1-172.jar)
UCHIJAAAA	TiCTooltips{1.2.5} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.5.jar)
UCHIJAAAA	TMechworks{0.2.15.106} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.15.106.jar)
UCHIJAAAA	ae2wct{1.7.10-rv2-1.8.7b} [AE2 Wireless Crafting Terminal] (WirelessCraftingTerminal-1.7.10-rv2-1.8.7b.jar)
UCHIJAAAA	aobd{2.9.2} [Another One Bites The Dust] (AOBD-2.9.2.jar)
UCHIJAAAA	HungerOverhaul{1.7.10-1.0.0.jenkins104} [Hunger Overhaul] (HungerOverhaul-1.7.10-1.0.0.jenkins104.jar)
UCHIJAAAA	IguanaTweaksTConstruct{1.7.10-2.1.6.163} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.6.jar)
UCHIJAAAA	UniDict{1.7.10-2.9.2} [UniDict] (UniDict-1.7.10-2.9.2.jar)
GL info: ERROR RuntimeException: No OpenGL context found in the current thread.
AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
CoFHCore: -[1.7.10]3.1.4-329
ThermalFoundation: -[1.7.10]1.2.6-118
ThermalExpansion: -[1.7.10]4.1.5-248
Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
TConstruct Environment: Environment healthy.
RedstoneArsenal: -[1.7.10]1.1.3-97
ThermalDynamics: -[1.7.10]1.2.1-172
List of loaded APIs:
* ae2wct|API (1.7.10-rv3-1.8.6b) from WirelessCraftingTerminal-1.7.10-rv2-1.8.7b.jar
* AgriCraftAPI (1.0) from AgriCraft-1.7.10-1.5.0.jar
* antiqueatlasapi (5.1) from antiqueatlas-1.7.10-4.2.10.jar
* AppleCoreAPI (1.2.0) from AppleCore-mc1.7.10-1.3.9.jar
* appliedenergistics2|API (rv2) from tardismod-1.7.10-0.994-124-DS.jar
* Baubles|API (1.0.1.10) from ThermalFoundation-[1.7.10]1.2.6-118.jar
* BuildCraftAPI|blocks (1.0) from buildcraft-7.1.21.jar
* BuildCraftAPI|blueprints (1.5) from buildcraft-7.1.21.jar
* BuildCraftAPI|boards (2.0) from buildcraft-7.1.21.jar
* BuildCraftAPI|core (2.0) from Railcraft_1.7.10-9.12.2.0.jar
* BuildCraftAPI|crops (1.1) from buildcraft-7.1.21.jar
* BuildCraftAPI|events (2.0) from buildcraft-7.1.21.jar
* BuildCraftAPI|facades (1.1) from buildcraft-7.1.21.jar
* BuildCraftAPI|filler (4.0) from buildcraft-7.1.21.jar
* BuildCraftAPI|fuels (2.0) from buildcraft-7.1.21.jar
* BuildCraftAPI|gates (4.1) from buildcraft-7.1.21.jar
* BuildCraftAPI|items (1.1) from Railcraft_1.7.10-9.12.2.0.jar
* BuildCraftAPI|library (2.0) from buildcraft-7.1.21.jar
* BuildCraftAPI|lists (1.0) from buildcraft-7.1.21.jar
* BuildCraftAPI|power (1.3) from buildcraft-7.1.21.jar
* BuildCraftAPI|recipes (3.0) from buildcraft-7.1.21.jar
* BuildCraftAPI|robotics (3.0) from buildcraft-7.1.21.jar
* BuildCraftAPI|statements (1.1) from Railcraft_1.7.10-9.12.2.0.jar
* BuildCraftAPI|tablet (1.0) from buildcraft-7.1.21.jar
* BuildCraftAPI|tiles (1.2) from Railcraft_1.7.10-9.12.2.0.jar
* BuildCraftAPI|tools (1.0) from buildcraft-7.1.21.jar
* BuildCraftAPI|transport (4.1) from buildcraft-7.1.21.jar
* CarpentersBlocks|API (3.3.7) from Carpenter's Blocks v3.3.8.1 - MC 1.7.10.jar
* CoFHAPI (1.7.10R1.0.2) from DragonAPI 1.7.10 V16d.jar
* CoFHAPI|block (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
* CoFHAPI|core (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
* CoFHAPI|energy (1.7.10R1.0.2) from Railcraft_1.7.10-9.12.2.0.jar
* CoFHAPI|fluid (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
* CoFHAPI|inventory (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
* CoFHAPI|item (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
* CoFHAPI|modhelpers (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
* CoFHAPI|tileentity (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
* CoFHAPI|transport (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
* CoFHAPI|world (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
* CoFHLib (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
* CoFHLib|audio (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
* CoFHLib|gui (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
* CoFHLib|gui|container (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
* CoFHLib|gui|element (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
* CoFHLib|gui|element|listbox (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
* CoFHLib|gui|slot (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
* CoFHLib|inventory (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
* CoFHLib|render (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
* CoFHLib|render|particle (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
* CoFHLib|util (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
* CoFHLib|util|helpers (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
* CoFHLib|util|position (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
* CoFHLib|world (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
* CoFHLib|world|feature (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
* Galacticraft API (1.0) from GalacticraftCore-1.7-3.0.12.495.jar
* IC2API (1.0) from Railcraft_1.7.10-9.12.2.0.jar
* minechemAPI (1.7.10R1) from DragonAPI 1.7.10 V16d.jar
* RailcraftAPI|bore (1.0.0) from Railcraft_1.7.10-9.12.2.0.jar
* RailcraftAPI|carts (1.6.0) from Traincraft-4.3.2_009.jar
* RailcraftAPI|core (1.5.0) from Traincraft-4.3.2_009.jar
* RailcraftAPI|crafting (1.0.0) from Traincraft-4.3.2_009.jar
* RailcraftAPI|electricity (2.0.0) from Traincraft-4.3.2_009.jar
* RailcraftAPI|events (1.0.0) from Railcraft_1.7.10-9.12.2.0.jar
* RailcraftAPI|fuel (1.0.0) from Traincraft-4.3.2_009.jar
* RailcraftAPI|helpers (1.1.0) from Traincraft-4.3.2_009.jar
* RailcraftAPI|items (1.0.0) from Traincraft-4.3.2_009.jar
* RailcraftAPI|locomotive (1.1.0) from Traincraft-4.3.2_009.jar
* RailcraftAPI|signals (2.3.0) from Traincraft-4.3.2_009.jar
* RailcraftAPI|tracks (2.3.0) from Traincraft-4.3.2_009.jar
* Thaumcraft|API (4.2.2.0) from Railcraft_1.7.10-9.12.2.0.jar
* thaumicenergistics|API (1.1) from thaumicenergistics-1.0.0.5-RV2.jar
AE2 Integration: IC2:OFF, RotaryCraft:ON, RC:ON, BC:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
AE2 Integration: RFItem:ON, NEI:ON
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Player Count: 1 / 8; [GCEntityPlayerMP['tonimark'/3549, l='test', x=-0,47, y=65,00, z=-6,80]]
Type: Integrated Server (map_client.txt)
Is Modded: Definitely; Client brand changed to 'fml,forge,pml'
OptiFine Version: OptiFine_1.7.10_HD_U_D7
Render Distance Chunks: 8
Mipmaps: 0
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
Shaders: null
OpenGlVersion: 4.3.0 - Build 20.19.15.4531
OpenGlRenderer: Intel(R) HD Graphics 4400
OpenGlVendor: Intel
CpuCount: 4

**Comment by radfast** [comment]
Usually this type of error is a **config problem**

I don't know if Extra Planets and Amun Ra add ons work together.  Or you maybe need special configs to make them work together?

You can try removing one of those mods.   Please backup your world before removing mods - if you change mods in a currently built world, you can maybe lose some blocks or items.

Apart from this, we'd need to see all your configs for Galacticraft, AmunRa and Extra Planets to help you - maybe put all your ```.minecraft/config``` folder into a Zipfile and upload that to Google drive?  You can ask the authors of those mods for help, or you can ask for help from other players in the Add Ons area of the Galacticraft [forum](https://forum.micdoodle8.com/index.php?forums/addons-and-resource-packs.11/)
