### ISSUE TITLE
[1.10.2] [Metamorph] Build 91: Visual Bug

### ISSUE THREAD

**Issue by RurouniTim** [micdoodle8/Galacticraft#2725]
There's a visual bug that I've noticed with Metamorph that only occurs when Galacticraft is also installed. When morphed as any mob, if you look at yourself in third person, it displays the mob with a bow through the model. It also displays the mob upside down if you look at it from a certain angle. It also has issues rendering the inventory for some reason too. It's been like this since at least build 71, but I haven't tested earlier builds. It seems to also persist in 1.11.2.

![2017-05-19_19 10 11](https://cloud.githubusercontent.com/assets/23000287/26272208/e6680104-3cc7-11e7-9521-638ffe95af43.png)
![2017-05-19_19 10 18](https://cloud.githubusercontent.com/assets/23000287/26272209/e6695ce8-3cc7-11e7-9c8f-dd98c6814497.png)
![2017-05-19_19 24 40](https://cloud.githubusercontent.com/assets/23000287/26272262/ed1621d8-3cc8-11e7-834a-8c98c66b1ee5.png)

**Comment by radfast** [comment]
Have you reported this to Metamorph developers?  Please provide a link.

**Comment by RurouniTim** [comment]
I haven't yet because it only occurs whe GC is installed, making me think it has to do with how the core mod renders the player model. I'll report it to them later today when I get home to my PC and post a link when I do.

**Comment by radfast** [comment]
It also only occurs when Metamorph is installed ...

**Comment by RurouniTim** [comment]
I've posted an issue to Metamorph's page as well...

https://github.com/mchorse/metamorph/issues/41

Also, an update to the rendering issue, after doing more testing, I also had a horse render through me while morphed.  Here's the screenshot of that.

![2017-05-20_19 17 48](https://cloud.githubusercontent.com/assets/23000287/26280692/6d2c36da-3d93-11e7-8ff8-ae980392d140.png)

**Comment by mchorse** [comment]
Sup, Metamorph's dev here. The inventory glitch is on my side, however I'm not sure about horses and bows stuck in the body.

**Comment by radfast** [comment]
Hey @mchorse  thanks for looking in
I'll take a look at the event listener you linked

We do a bit of stuff to the player model, adding more render layers, and hooking (well, replacing) the existing render layers for armor and held item so that they respect our model animations.

**Comment by mchorse** [comment]
I think there was some attributes in `@EventListener` that allowed prioritizing event calls, but I'm not sure. I'll have to look into Forge's source. 

Speaking of player renderers, I also [susbtitute player renderers](https://github.com/mchorse/metamorph/blob/master/src/main/java/mchorse/metamorph/ClientProxy.java#L91) to support easier first person arm rendering (RenderHandEvent was a nightmare) :joy: 

Do you provide dev and souce builds? I could look into it

**Comment by radfast** [comment]
Much appreciated.  Dev build [here](https://ci.micdoodle8.com/job/Galacticraft-1.10-dev/) if you need it.

I've changed the event priority for our listener so hopefully it can come after Metamorph, and if Metamorph cancels the event then our listener will never be called - I think Forge stops invoking later listeners if one cancels the event.

I'll make a new Galacticraft build 94 and maybe @RurouniTim can be kind enough to test it?

**Comment by radfast** [comment]
> Speaking of player renderers, I also susbtitute player renderers to support easier first person arm rendering (RenderHandEvent was a nightmare) 😂

Oh noes.  In that case you'll be substituting your player renderer for [our substitute](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/client/render/entities/RenderPlayerGC.java).  Your mod loads after ours, because M comes after G...   Probably means players won't be seeing any Galacticraft equipment if Metamorph is installed, and various minor effects  :(

[RenderPlayerAPI](https://minecraft.curseforge.com/projects/render-player-api/files) is the best solution to this type of conflict, though looks like that's not yet available for 1.11.2.

Otherwise we could actually very easily add your arm methods to our RenderPlayer - we have a way to add methods at runtime for compatibility, if needed.

**Comment by mchorse** [comment]
@radfast I can add an option to disable substitution on my side, but then the user would have to decide whether to see first person hand or GC equipment. Man, I wish RenderPlayerAPI was available for 1.11.2. That would be problematic for me, though (and for you, probably), because we'll have to depend on another mod. *sigh*

Although, it might be possible to make it optional. However, I haven't really dug into Forge's `@Optional` annotations. 

Also, @RurouniTim submitted similar issue after GC issue (or before) about Baubles equipment not rendering. Thanks for your input, now I know the problem's root for that issue also 👍

**Comment by radfast** [comment]
@mchorse   any chance you can create an API class with a **static** method like this - then we can call that static method from our code, and go with our substitute RenderPlayerGC.
>
   public static boolean renderMorphRightArm(AbstractClientPlayer clientPlayer)
    {
        IMorphing morph = Morphing.get(clientPlayer);

        if (morph != null && morph.isMorphed())
        {
            if (morph.getCurrentMorph().renderHand(clientPlayer, EnumHand.MAIN_HAND))
            {
                return true;
            }
        }

        return false;
    }

**Comment by radfast** [comment]
Also do you have a 1.8.9 version of your mod, or do we need to do this only in 1.10.2?

**Comment by radfast** [comment]
BTW is your current code in RenderPlayerSub going to be correct if the player has set the option to have MAIN_HAND as the left hand?

**Comment by RurouniTim** [comment]
I went ahead and did a test with just Galacticraft and Metamorph and it worked fine. I'm no longer having the weird horse head or bow show up. The upside down effect seems to have vanished as well. Whatever the issue was with the inventory also was fixed. As mentioned, it now renders the player hand instead of the morphed mob's hand, but that's something I'm okay with. I tested the Galacticraft gear (Oxygen mask, air tanks, etc) and they all render fine in player form. I'll keep an eye out in further testing in case I notice anything, but things seem to be working pretty well overall.

Thank you both for taking the time to look into this and for contributing to the development of mods that help keep Minecraft enjoyable.

**Comment by radfast** [comment]
Pleasure :)   Thank you for reporting the issue, it's excellent to fix compatibility issues while we're still in Beta.

@mchorse I sent you email, we can chat privately

**Comment by mchorse** [comment]
@radfast didn't get the mail, yet. I'm also about to go to sleep :stuck_out_tongue: 

Metamorph is 1.9.4, 1.10.2 and 1.11.2. Yeah, I can add such method, but how is it going to work? You going to substitute renderers at later stages and then will use this static method. Correct?

About the hand, I'm not sure 100%, I do remember testing it and it was working fine (at least rendering correctly at the left side). I'll ned to check that up with asymertic skin.

**Comment by mchorse** [comment]
@RurouniTim you're welcome! I'm really glad that you enjoying the mod, but also spent some time into submitting an issue, describing it in details and even providing potential source of the problem :+1:

**Comment by radfast** [comment]
@mchorse   ok great :)   we'll call the static method for left and right hand render just as you are in RenderSubPlayer.  once that's working, probably best if you can please auto-disable your substituion of RenderSubPlayer for RenderPlayer if Galacticraft is loaded - or test if the slim/default fields have the vanilla RenderPlayer and only substitute if they do?

It's not gonna help either our compatibility with other mods which substitute RenderPlayer, but it's a temporary fix that's better than nothing, while we head to RenderPlayerAPI support and while we wait for RenderPlayerAPI 1.11.2.
