### ISSUE TITLE
[1.11.2] Galacticraft Swords Render Incorrectly in two ways (Build 91)

### ISSUE THREAD

**Issue by booski2005** [micdoodle8/Galacticraft#2726]
When holding any of the Galacticraft swords in your left hand, in first person it renders as an item instead of a sword.
![2017-05-19_23 26 58](https://cloud.githubusercontent.com/assets/7104632/26273719/bafbf6a6-3cea-11e7-8a7d-d6bcfaef3106.png)
Also, when holding a Galacticraft sword in either the left or right hand in second or third person, it renders as an item instead of a sword. (Yes, I'm left handed, and this is kind of an OCD trigger. I could play with right hand, but that also becomes an OCD trigger.)
![2017-05-19_23 28 13](https://cloud.githubusercontent.com/assets/7104632/26273722/d859fcca-3cea-11e7-8dce-8df30bda43e4.png)
I'll also attach an image of this compared to a vanilla sword.
![2017-05-19_23 30 19](https://cloud.githubusercontent.com/assets/7104632/26273728/2457ec5e-3ceb-11e7-8824-3d0295f1fe4d.png)
![2017-05-19_23 30 37](https://cloud.githubusercontent.com/assets/7104632/26273729/2d04e82a-3ceb-11e7-9c49-755913e82868.png)
NOTE: I'm using OptiFine Ultra B9 & My Forge Version Is 2299. I'm not sure if this issue also occurs with 1.9 & 1.10.

**Comment by booski2005** [comment]
Why the rename? There was also a problem with the right hand...

**Comment by radfast** [comment]
Yes, sorry I missed the second part of the issue report when I renamed.
We will look at both, should be fixed soon.

**Comment by micdoodle8** [comment]
Thanks for the report, should be fixed as of the next build.
