### ISSUE TITLE
[1.11] galacticraft  vanilla armor slots shown at wrong series

### ISSUE THREAD

**Issue by tonimark** [micdoodle8/Galacticraft#2727]
when I open galacticraft inventory on minecraft 1.11 the vanilla armor slots shown wrong

**Comment by radfast** [comment]
please provide screenshot + log or list of other mods

**Comment by tonimark** [comment]
oh K

**Comment by tonimark** [comment]
wait

**Comment by tonimark** [comment]
here is the screenshot of the wrong armor slots 
![2017-05-20_17 01 22](https://cloud.githubusercontent.com/assets/17166550/26276333/15f6a43c-3d7e-11e7-9d5d-2013c8385871.png)

**Comment by radfast** [comment]
Thank you for reporting this.

Fixed in future build 92.
