### ISSUE TITLE
[1.11.2] getPickBlock gives Cheese Ore for Sapphire Ore

### ISSUE THREAD

**Issue by kenijey** [micdoodle8/Galacticraft#2728]
i just disabled cheese ore spawn in Moon, and this is what happens:
![123](https://cloud.githubusercontent.com/assets/24831406/26278132/414850a4-3d9c-11e7-8154-67d8d49ce8ea.PNG)
![2](https://cloud.githubusercontent.com/assets/24831406/26278140/614ca846-3d9c-11e7-9caa-2a0813c62336.PNG)
that's actually a cheese block. i tried middle click (vanilla feature) and breaking it

**Comment by kenijey** [comment]
forge 2299, GC b91

**Comment by kenijey** [comment]
btw, i'm having another bug in my modpack. there are no any mobs from galacticraft in planets, (like evolved creepers&zombies, etc) but there are alien villagers.
what could be causing this? how can i find what causes? thanks.
(i tested GC4 alone, i saw evolved mobs, but in my modpack.)

**Comment by radfast** [comment]
@kenijey  are you playing on a server?  (including a localhost server?)

"wrong mobs spawning" issues are normally caused by using different mod versions on client and server.  And not necessarily Galacticraft, it could be any mod (maybe even a config difference in some other mod, like a mob is enabled server-side but disabled client-side)

**Comment by radfast** [comment]
The Cheese Ore issue probably has the same cause, that's block IDs out of sync on client and server.

**Comment by kenijey** [comment]
no, i was in singleplayer (in my world)

**Comment by kenijey** [comment]
hey, i solved the no mob spawn problem. another mod is tweaking the dah-night cycle. 
and i'm saying again, it's not on the server, it's singleplayer. i make all tests in singleplayer.

**Comment by radfast** [comment]
I was able to reproduce this, looks like a PickBlock bug in 1.11.2.

**Comment by radfast** [comment]
Fixed in next build 95

**Comment by radfast** [comment]
Build 95 now available.

**Comment by kenijey** [comment]
Thank you.
