### ISSUE TITLE
[1.10.2] Crash after changing keyboard binding

### ISSUE THREAD

**Issue by 7eggert** [micdoodle8/Galacticraft#2729]
Minecraft does not start if I load Galacticraft. If I remember correctly, I removed a keybinding when the first crash occured.

at micdoodle8.mods.galacticraft.core.client.KeyHandler.keyTick(KeyHandler.java:65):

int keyCode = keyBinding.getKeyCode(); //← receives invalid keycode?
boolean state = inChat ? false : (keyCode < 0 ? Mouse.isButtonDown(keyCode + 100) : Keyboard.isKeyDown(keyCode)); //← barfs

I'd rewite this as:

boolean state = false;
try {
 boolean state = inChat ? false
   : (keyCode < 0 ? Mouse.isButtonDown(keyCode + 100)
    : Keyboard.isKeyDown(keyCode));
}
catch ... // java.lang.IndexOutOfBoundsException

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.10.2-4.0.0.91-BETA.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.65-beta.jar)
  BetterFoliageLoader (BetterFoliage-MC1.10.2-2.1.4.jar)
  RebornCoreASM (RebornCore-1.10.2-2.13.5.136-universal.jar)
  NWRTweak (Redstone-Paste-Mod-1.10.2.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.8.255-universal.jar)
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.1.156-universal.jar)
  CXLibraryCore (CXLibrary-1.10.2.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.8.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 5/20/17 5:46 PM
Description: Unexpected error

java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Buffer.java:540)
	at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:253)
	at org.lwjgl.input.Keyboard.isKeyDown(Keyboard.java:407)
	at micdoodle8.mods.galacticraft.core.client.KeyHandler.keyTick(KeyHandler.java:65)
	at micdoodle8.mods.galacticraft.core.client.KeyHandler.onTick(KeyHandler.java:47)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_384_KeyHandler_onTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:339)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1650)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (amd64) version 3.16.0-4-amd64
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1608665632 bytes (1534 MB) / 4085235712 bytes (3895 MB) up to 5341904896 bytes (5094 MB)
	JVM Flags: 5 total; -Xmx5G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 Optifine OptiFine_1.10.2_HD_U_D7 58 mods loaded, 58 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.8.255-universal.jar) 
	UCHIJA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJA	cei{1.3} [Chunk Edge Indicator] (1.10-chunkedgeindicator-1.3.jar) 
	UCHIJA	cxlibrary{1.2.3} [CXLibrary] (CXLibrary-1.10.2.jar) 
	UCHIJA	advInv{1.2.0} [Advanced Inventory] (Advanced-Inventory-Mod-1.10.2.jar) 
	UCHIJA	autopackager{1.6.3} [AutoPackager] (AutoPackager-Mod-1.10.2.jar) 
	UCHIJA	basemetals{2.4.0} [Base Metals] (BaseMetals_1.10.2-2.4.0.11.jar) 
	UCHIJA	bdlib{1.12.4.24} [BD Lib] (bdlib-1.12.4.24-mc1.10.2.jar) 
	UCHIJA	hud{1.3.8} [Better HUD] (Better HUD by NukeDuck [1.9.4][1.3.8].jar) 
	UCHIJA	betterfoliage{2.1.4} [Better Foliage] (BetterFoliage-MC1.10.2-2.1.4.jar) 
	UCHIJA	BiomesOPlenty{5.0.0.2162} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2162-universal.jar) 
	UCHIJA	Chameleon{1.10-2.2.2} [Chameleon] (Chameleon-1.10-2.2.2.jar) 
	UCHIJA	CodeChickenLib{2.5.8.255} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.8.255-universal.jar) 
	UCHIJA	CodeChickenCore{2.4.1.102} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.1.102-universal.jar) 
	UCHIJA	cofhcore{4.1.1} [CoFH Core] (CoFHCore-1.10.2-4.1.1.156-universal.jar) 
	UCHIJA	cyclopscore{0.10.2} [Cyclops Core] (CyclopsCore-1.9.4-0.10.2.jar) 
	UCHIJA	colossalchests{1.5.2} [Colossal Chests] (ColossalChests-1.10.2-1.5.2.jar) 
	UCHIJA	craftingcraft{4.1.9} [CraftingCraft] (CraftingCraft_1.10.2-4.1.9.jar) 
	UCHIJA	cyberware{beta-0.2.7} [Cyberware] (cyberware-1.9.4-1.10.2-beta-0.2.7.jar) 
	UCHIJA	lootablebodies{2.2.0} [DrCyano's Lootable Bodies] (DrCyanosLootableBodies_1.10.2-2.2.0.jar) 
	UCHIJA	endercompass{1.2.3.2} [Ender Compass] (Ender-Compass-Mod-1.10.2.jar) 
	UCHIJA	EnderBags{2.0.1} [EnderBags] (EnderBags-Mod-1.10.2.jar) 
	UCHIJA	endercore{1.10.2-0.4.1.65-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.65-beta.jar) 
	UCHIJA	JEI{3.14.7.417} [Just Enough Items] (jei_1.10.2-3.14.7.417.jar) 
	UCHIJA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJA	EnderIO{1.10.2-3.1.183} [Ender IO] (EnderIO-1.10.2-3.1.183.jar) 
	UCHIJA	EnderStorage{2.2.1.106} [EnderStorage] (EnderStorage-1.10.2-2.2.1.106-universal.jar) 
	UCHIJA	shetiphiancore{3.3.8} [ShetiPhian-Core] (shetiphiancore-1.10.0-3.3.8.jar) 
	UCHIJA	endertanks{1.4.12} [EnderTanks] (endertanks-1.10.0-1.4.12.jar) 
	UCHIJA	FlatBedrockx{1.2.1} [FlatBedrock Xplosion's Edition] (Flat-Bedrock-Mod-1.10.2.jar) 
	UCHIJA	fluxducts{1.0.4} [Flux Ducts] (fluxducts-mc1.9.4-1.0.4.jar) 
	UCHIJA	galacticraftcore{4.0.0} [Galacticraft Core] (GalacticraftCore-1.10.2-4.0.0.91-BETA.jar) 
	UCHIJA	galacticraftplanets{4.0.0} [Galacticraft Planets] (Galacticraft-Planets-1.10.2-4.0.0.91-BETA.jar) 
	UCHIJA	hopperducts{1.4.8} [Hopper Ducts] (hopperducts-mc1.9.4-1.4.8.jar) 
	UCHIJA	llor{1.1.1-mc[1.9-1.11]} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.1-mc[1.9-1.11].jar) 
	UCHIJA	mineralogy{3.2.0} [Mineralogy] (Mineralogy_1.10.2-3.2.0.jar) 
	UCHIJA	orespawn{1.1.0} [Ore Spawn] (OreSpawn_1.10.2-1.1.0.jar) 
	UCHIJA	poweradvantage{2.3.0} [Power Advantage] (PowerAdvantage_1.10.2-2.3.0.jar) 
	UCHIJA	pressure{1.3.1.20} [Pressure Pipes] (pressure-1.3.1.20-mc1.10.2.jar) 
	UCHIJA	progressiveautomation{1.7.4} [Progressive Automation] (ProgressiveAutomation-1.10.2-1.7.4.jar) 
	UCHIJA	quantumflux{2.0.7} [QuantumFlux] (QuantumFlux-Mod-1.10.2.jar) 
	UCHIJA	railcraft{10.1.1} [Railcraft] (Railcraft_1.10.2-10.1.1.jar) 
	UCHIJA	reborncore{2.13.5.136} [RebornCore] (RebornCore-1.10.2-2.13.5.136-universal.jar) 
	UCHIJA	reborncore-mcmultipart{2.13.5.136} [reborncore-MCMultiPart] (RebornCore-1.10.2-2.13.5.136-universal.jar) 
	UCHIJA	redstonepaste{1.7.4} [Redstone Paste] (Redstone-Paste-Mod-1.10.2.jar) 
	UCHIJA	rftools{6.00} [RFTools] (rftools-1.1x-6.00.jar) 
	UCHIJA	rftoolsdim{4.55} [RFTools Dimensions] (rftoolsdim-1.1x-4.55.jar) 
	UCHIJA	steamadvantage{2.2.0} [Steam Advantage] (SteamAdvantage_1.10.2-2.2.0.jar) 
	UCHIJA	thermalfoundation{2.0.5} [Thermal Foundation] (ThermalFoundation-1.10.2-2.0.5.81-universal.jar) 
	UCHIJA	thermalexpansion{5.0.4} [Thermal Expansion] (ThermalExpansion-1.10.2-5.0.4.90-universal.jar) 
	UCHIJA	chunkbase_villageinfo_ssp{2.1} [Village Info (SSP)] (VillageInfoSSP-1.9.4-2.1.jar) 
	UCHIJA	Waypoints{1.9.4-1.2.1} [Waypoints] (Waypoints-Mod-1.9.4.jar) 
	UCHIJA	worldedit{6.1.4} [WorldEdit] (worldedit-forge-mc1.10.2-6.1.4-dist.jar) 
	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.10.2-4.0.0.91-BETA.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.65-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
BetterFoliageLoader (BetterFoliage-MC1.10.2-2.1.4.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
RebornCoreASM (RebornCore-1.10.2-2.13.5.136-universal.jar)
  reborncore.mixin.transformer.MixinTransformer
NWRTweak (Redstone-Paste-Mod-1.10.2.jar)
  net.fybertech.nwr.NWRTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.8.255-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
CoFH Loading Plugin (CoFHCore-1.10.2-4.1.1.156-universal.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
CXLibraryCore (CXLibrary-1.10.2.jar)
  cubex2.cxlibrary.CoreModTransformer
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.8.jar)
  shetiphian.core.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '3.3.0 NVIDIA 340.102' Renderer: 'GeForce 9800 GT/PCIe/SSE2'
	List of loaded APIs: 
		* AdvInvAPI (1) from Advanced-Inventory-Mod-1.10.2.jar
		* CoFHAPI (1.8.9R1.2.0B1) from ProgressiveAutomation-1.10.2-1.7.4.jar
		* cofhapi (1.6.0) from CoFHCore-1.10.2-4.1.1.156-universal.jar
		* cofhapi|block (1.6.0) from CoFHCore-1.10.2-4.1.1.156-universal.jar
		* CoFHAPI|block (1.8.9R1.2.0B1) from fluxducts-mc1.9.4-1.0.4.jar
		* cofhapi|core (1.6.0) from CoFHCore-1.10.2-4.1.1.156-universal.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from Railcraft_1.10.2-10.1.1.jar
		* cofhapi|energy (1.5.0) from RebornCore-1.10.2-2.13.5.136-universal.jar
		* CoFHAPI|item (1.8.9R1.2.0B1) from mcjtylib-1.1x-2.3.11.jar
		* cofhapi|item (1.6.0) from CoFHCore-1.10.2-4.1.1.156-universal.jar
		* CoFHAPI|tileentity (1.8.9R1.2.0B1) from ProgressiveAutomation-1.10.2-1.7.4.jar
		* cofhapi|tileentity (1.6.0) from CoFHCore-1.10.2-4.1.1.156-universal.jar
		* cofhapi|util (1.6.0) from CoFHCore-1.10.2-4.1.1.156-universal.jar
		* cofhlib (1.6.0) from CoFHCore-1.10.2-4.1.1.156-universal.jar
		* cofhlib|audio (1.6.0) from CoFHCore-1.10.2-4.1.1.156-universal.jar
		* cofhlib|gui (1.6.0) from CoFHCore-1.10.2-4.1.1.156-universal.jar
		* cofhlib|gui|container (1.6.0) from CoFHCore-1.10.2-4.1.1.156-universal.jar
		* cofhlib|gui|element (1.6.0) from CoFHCore-1.10.2-4.1.1.156-universal.jar
		* cofhlib|gui|element|listbox (1.6.0) from CoFHCore-1.10.2-4.1.1.156-universal.jar
		* cofhlib|gui|slot (1.6.0) from CoFHCore-1.10.2-4.1.1.156-universal.jar
		* cofhlib|inventory (1.6.0) from CoFHCore-1.10.2-4.1.1.156-universal.jar
		* cofhlib|util (1.6.0) from CoFHCore-1.10.2-4.1.1.156-universal.jar
		* cofhlib|util|helpers (1.6.0) from CoFHCore-1.10.2-4.1.1.156-universal.jar
		* cofhlib|world (1.6.0) from CoFHCore-1.10.2-4.1.1.156-universal.jar
		* cofhlib|world|feature (1.6.0) from CoFHCore-1.10.2-4.1.1.156-universal.jar
		* compatlayer (0.2.5) from compatlayer-1.10-0.2.5.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.10.2-3.1.183.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.10.2-3.1.183.jar
		* EnderIOAPI|Teleport (0.0.2) from EnderIO-1.10.2-3.1.183.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.10.2-3.1.183.jar
		* Galacticraft API (1.1) from GalacticraftCore-1.10.2-4.0.0.91-BETA.jar
		* JustEnoughItemsAPI (4.10.1) from jei_1.10.2-3.14.7.417.jar
		* mcjtylib_ng (2.3.11) from mcjtylib-1.1x-2.3.11.jar
		* pressureAPI (1.3.1.20) from pressure-1.3.1.20-mc1.10.2.jar
		* railcraft:API|core (3.1.0) from Railcraft_1.10.2-10.1.1.jar
		* RailcraftAPI|bore (2.0.0) from Railcraft_1.10.2-10.1.1.jar
		* RailcraftAPI|carts (2.0.0) from Railcraft_1.10.2-10.1.1.jar
		* RailcraftAPI|charge (3.0.0) from Railcraft_1.10.2-10.1.1.jar
		* RailcraftAPI|crafting (2.0.0) from Railcraft_1.10.2-10.1.1.jar
		* RailcraftAPI|events (2.0.0) from Railcraft_1.10.2-10.1.1.jar
		* RailcraftAPI|fuel (2.0.0) from Railcraft_1.10.2-10.1.1.jar
		* RailcraftAPI|helpers (2.0.0) from Railcraft_1.10.2-10.1.1.jar
		* RailcraftAPI|items (2.1.0) from Railcraft_1.10.2-10.1.1.jar
		* RailcraftAPI|locomotive (2.0.0) from Railcraft_1.10.2-10.1.1.jar
		* RailcraftAPI|signals (4.0.0) from Railcraft_1.10.2-10.1.1.jar
		* RailcraftAPI|tracks (4.0.0) from Railcraft_1.10.2-10.1.1.jar
		* reborncoreAPI (2.13.5.136) from RebornCore-1.10.2-2.13.5.136-universal.jar
		* reborncoreAPI|Fuel (2.13.5.136) from RebornCore-1.10.2-2.13.5.136-universal.jar
		* reborncoreAPI|Power (2.13.5.136) from RebornCore-1.10.2-2.13.5.136-universal.jar
		* reborncoreAPI|Recipe (2.13.5.136) from RebornCore-1.10.2-2.13.5.136-universal.jar
		* reborncoreAPI|Tile (2.13.5.136) from RebornCore-1.10.2-2.13.5.136-universal.jar
		* WailaAPI (1.3) from Waila-1.7.0-B3_1.9.4.jar
	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                  * The RF API that is being used (1.6.0 from (guessing) null) differes from that that is reported as being loaded (1.8.9R1.2.0B1 from Railcraft_1.10.2-10.1.1.jar).
                    It is a supported version, but that difference may lead to problems.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/home/7eggert/.minecraft/!gamedirs/f1.10/mods/1.10.2/CoFHCore-1.10.2-4.1.1.156-universal.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/home/7eggert/.minecraft/!gamedirs/f1.10/mods/1.10.2/CoFHCore-1.10.2-4.1.1.156-universal.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/home/7eggert/.minecraft/!gamedirs/f1.10/mods/1.10.2/CoFHCore-1.10.2-4.1.1.156-universal.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/home/7eggert/.minecraft/!gamedirs/f1.10/mods/1.10.2/CoFHCore-1.10.2-4.1.1.156-universal.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/home/7eggert/.minecraft/!gamedirs/f1.10/mods/1.10.2/CoFHCore-1.10.2-4.1.1.156-universal.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/home/7eggert/.minecraft/!gamedirs/f1.10/mods/1.10.2/CoFHCore-1.10.2-4.1.1.156-universal.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/home/7eggert/.minecraft/!gamedirs/f1.10/mods/1.10.2/CoFHCore-1.10.2-4.1.1.156-universal.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/home/7eggert/.minecraft/!gamedirs/f1.10/mods/1.10.2/CoFHCore-1.10.2-4.1.1.156-universal.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/home/7eggert/.minecraft/!gamedirs/f1.10/mods/1.10.2/CoFHCore-1.10.2-4.1.1.156-universal.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash. Scroll up!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	EnderStorage Invalid Fingerprint Reports: 
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 2.13.5.136
		Mixin Status: 1
		Runtime Debofucsation 1
		RenderEngine: 1
	Launched Version: 1.10.2
	LWJGL: 2.9.4
	OpenGL: GeForce 9800 GT/PCIe/SSE2 GL version 3.3.0 NVIDIA 340.102, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Silence-Minecart-6dB.zip (incompatible), Mineralogy_high-res.zip (incompatible), Misa-1.9.zip (incompatible), Les Misa+ 11.2 patch.zip (incompatible), Misa Door 7eggert.zip (incompatible), SkinDeep_v2-1-1.zip (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x AMD Athlon(tm) II X2 250 Processor
	OptiFine Version: OptiFine_1.10.2_HD_U_D7
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.3.0 NVIDIA 340.102
	OpenGlRenderer: GeForce 9800 GT/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 2

**Comment by micdoodle8** [comment]
Should be fixed in the next build. Thanks.
