### ISSUE TITLE
Inaccurate treasure chest chat message

### ISSUE THREAD

**Issue by kenijey** [micdoodle8/Galacticraft#2731]
i just killed the tier 1 boss in moon, and opened the tier 1 chest with tier 1 key that i took from the boss, and it said this in chat:
![2017-05-20_23 48 24](https://cloud.githubusercontent.com/assets/24831406/26279242/f61a824e-3db6-11e7-8f18-48e0453c01e2.png)
used forge 2299, gc4 b91

**Comment by radfast** [comment]
@kenijey  it looks like there are other issues in your installation / set-up, see #2728 

Please fix those and then re-confirm that this key issue is an issue... ?

**Comment by kenijey** [comment]
hey ah, this picture/installation was in vanilla. only galacticraft + vanilla. and deleted all configs before launch. it was b91.

**Comment by kenijey** [comment]
btw i was in creative mode.

**Comment by radfast** [comment]
Thank you for reporting this.  I've now been able to reproduce the problem.  Should be fixed in next build 96.
