### ISSUE TITLE
[1.10.2] [Outdated GC version] Oxygen Compressor Crash

### ISSUE THREAD

**Issue by tommy1221** [micdoodle8/Galacticraft#2732]
when we hook up the oxygen compressor with the oxygen collector with a fluidd pipe then wrench it to change it to a gas pipe it crashes the server. you have to go into mcedit and delete the pipe to get the word back.

**Comment by tommy1221** [comment]
sorry if this was fixed. will update and let you know

**Comment by micdoodle8** [comment]
If it still crashes, can you provide us with the crash report using https://pastebin.com/

**Comment by radfast** [comment]
please try build 99 @tommy1221  and let us know?

(and don't worry if Forge reports 6 missing blocks / items in the world when you start your world after updating Galacticraft, there's nothing missing, those are unused items for air / empty blocks)

**Comment by radfast** [comment]
>   will update and let you know

?

**Comment by tommy1221** [comment]
I will try and check today. Been away on vacation sorry :)

**Comment by radfast** [comment]
no need to apologise, hope it was good :)

**Comment by radfast** [comment]
I'm going to assume that you're not seeing this crash in the latest Galacticraft version, so that we can close this.

If it happens again in the latest (currently that's build 109 at the time of posting) please do comment or re-open this, as obviously if there's a current issue we want to fix it.
