### ISSUE TITLE
Mod conflict: advanced rocketry

### ISSUE THREAD

**Issue by teamMK** [micdoodle8/Galacticraft#2733]
Hi,

i dont know wich mod cause this crash, so i will post it in both issue tracker.

Galacticraft and advanced rocketry cause an unexpected crash immediately at start up. I tested it only with libvulpes, advanced rocketry and galacticraft installed. I posted a link to the logfile below:

https://www.dropbox.com/s/e6ifctlsmuvzef0/latest.log?dl=0

**Comment by radfast** [comment]
Thanks for reporting.  Should be fixed in new [build 93](https://ci.micdoodle8.com/job/Galacticraft-1.11/93/).
