### ISSUE TITLE
[1.8.9] Create Space Station GUI position problem

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#2735]
Issue explained in title. Testing in dev environment.

**Comment by radfast** [comment]
InventoryTweaks present?  Or other mods?

**Comment by SteveKunG** [comment]
Here is my current mod lists.

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.139-dev.jar)
  Loader (thaifixes-3.0-1.8.9-pre-1.jar)
  MicdoodlePlugin (MicdoodleCore-1.8.9-4.0.0.94-BETA.jar)
  CCCDeobfPlugin (unknown)
  CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-dev.jar)
  NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-dev.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 22/5/2560, 1:38 น.
Description: Manually triggered debug crash

java.lang.Throwable
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1886)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1080)
	at net.minecraft.client.Minecraft.run(Minecraft.java:380)
	at net.minecraft.client.main.Main.main(Main.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:26)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:383)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['SteveKunG'/263, l='MpServer', x=-358.94, y=87.00, z=533.42]]
	Chunk stats: MultiplayerChunkCache: 580, 580
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: -357.00,64.00,529.00 - World: (-357,64,529), Chunk: (at 11,4,1 in -23,33; contains blocks -368,0,528 to -353,255,543), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Level time: 14073 game time, 14073 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 104 total; [EntityOcelot['Ocelot'/7429, l='MpServer', x=-395.50, y=76.00, z=523.50], EntityZombie['Zombie'/9998, l='MpServer', x=-348.50, y=23.00, z=588.50], EntityBat['Bat'/10001, l='MpServer', x=-415.44, y=24.13, z=558.63], GCEntityClientPlayerMP['SteveKunG'/263, l='MpServer', x=-358.94, y=87.00, z=533.42], EntitySkeleton['Skeleton'/9752, l='MpServer', x=-410.50, y=84.00, z=504.50], EntityZombie['Zombie'/10013, l='MpServer', x=-437.50, y=82.00, z=552.50], EntitySkeleton['Skeleton'/10529, l='MpServer', x=-424.50, y=41.00, z=515.84], EntityZombie['Zombie'/9507, l='MpServer', x=-406.88, y=54.00, z=553.19], EntitySquid['Squid'/9001, l='MpServer', x=-344.13, y=60.19, z=573.88], EntitySkeleton['Skeleton'/9263, l='MpServer', x=-421.50, y=62.00, z=527.50], EntityZombie['Zombie'/10545, l='MpServer', x=-380.50, y=25.00, z=603.50], EntityBat['Bat'/10805, l='MpServer', x=-388.22, y=23.74, z=546.36], EntityBat['Bat'/10557, l='MpServer', x=-410.25, y=19.10, z=576.69], EntityZombie['Zombie'/9790, l='MpServer', x=-367.53, y=28.00, z=581.94], EntitySkeleton['Skeleton'/10048, l='MpServer', x=-431.50, y=84.00, z=575.50], EntityZombie['Zombie'/10053, l='MpServer', x=-344.50, y=19.00, z=611.50], EntityZombie['Zombie'/9799, l='MpServer', x=-370.66, y=27.00, z=571.34], EntitySquid['Squid'/9288, l='MpServer', x=-356.50, y=60.72, z=471.50], EntitySkeleton['Skeleton'/9800, l='MpServer', x=-341.53, y=21.00, z=591.13], EntityBat['Bat'/10824, l='MpServer', x=-366.08, y=38.81, z=606.28], EntityZombie['Zombie'/10063, l='MpServer', x=-410.50, y=52.00, z=508.50], EntityPig['Pig'/80, l='MpServer', x=-433.50, y=66.00, z=490.50], EntityEnderman['Enderman'/10832, l='MpServer', x=-334.50, y=25.00, z=606.50], EntityPig['Pig'/82, l='MpServer', x=-432.53, y=67.00, z=481.94], EntityChicken['Chicken'/83, l='MpServer', x=-436.63, y=69.00, z=494.63], EntityBat['Bat'/10067, l='MpServer', x=-355.06, y=27.00, z=573.72], EntityChicken['Chicken'/84, l='MpServer', x=-437.50, y=67.00, z=493.78], EntityChicken['Chicken'/85, l='MpServer', x=-434.50, y=69.00, z=483.50], EntityPig['Pig'/88, l='MpServer', x=-436.34, y=69.00, z=479.13], EntityChicken['Chicken'/89, l='MpServer', x=-437.50, y=68.00, z=497.50], EntitySkeleton['Skeleton'/10589, l='MpServer', x=-421.50, y=29.00, z=598.50], EntityBat['Bat'/9828, l='MpServer', x=-365.91, y=28.10, z=587.66], EntityPig['Pig'/105, l='MpServer', x=-427.56, y=87.00, z=571.69], EntityPig['Pig'/106, l='MpServer', x=-421.47, y=89.00, z=579.28], EntityPig['Pig'/107, l='MpServer', x=-421.47, y=86.00, z=582.00], EntityPig['Pig'/108, l='MpServer', x=-422.50, y=86.00, z=577.50], EntityZombie['Zombie'/9836, l='MpServer', x=-371.50, y=27.00, z=573.50], EntityZombie['Zombie'/10348, l='MpServer', x=-404.50, y=26.00, z=596.50], EntitySheep['Sheep'/109, l='MpServer', x=-428.56, y=82.00, z=597.44], EntitySkeleton['Skeleton'/9837, l='MpServer', x=-298.50, y=33.00, z=493.50], EntitySheep['Sheep'/110, l='MpServer', x=-424.50, y=81.00, z=597.50], EntitySheep['Sheep'/111, l='MpServer', x=-427.47, y=81.00, z=597.44], EntityZombie['Zombie'/10607, l='MpServer', x=-390.06, y=11.00, z=550.50], EntitySheep['Sheep'/112, l='MpServer', x=-428.56, y=81.00, z=598.53], EntityPig['Pig'/113, l='MpServer', x=-400.50, y=81.00, z=485.50], EntitySkeleton['Skeleton'/9841, l='MpServer', x=-347.50, y=18.00, z=602.50], EntityPig['Pig'/114, l='MpServer', x=-400.50, y=81.00, z=485.50], EntityPig['Pig'/115, l='MpServer', x=-400.50, y=81.00, z=485.50], EntitySkeleton['Skeleton'/10356, l='MpServer', x=-429.50, y=65.00, z=535.50], EntityMinecartChest['container.minecart'/117, l='MpServer', x=-400.50, y=30.06, z=542.50], EntityBat['Bat'/9847, l='MpServer', x=-366.75, y=30.10, z=592.88], EntityZombie['Zombie'/10360, l='MpServer', x=-370.50, y=65.00, z=484.50], EntityMinecartChest['container.minecart'/121, l='MpServer', x=-408.50, y=20.06, z=583.50], EntityBat['Bat'/10623, l='MpServer', x=-391.75, y=22.00, z=551.46], EntitySquid['Squid'/9345, l='MpServer', x=-328.75, y=54.66, z=565.72], EntityPig['Pig'/130, l='MpServer', x=-397.50, y=81.00, z=481.50], EntityBat['Bat'/10627, l='MpServer', x=-350.56, y=22.10, z=611.75], EntityPig['Pig'/132, l='MpServer', x=-391.38, y=77.00, z=532.84], EntityMinecartChest['container.minecart'/133, l='MpServer', x=-396.50, y=25.06, z=558.50], EntitySquid['Squid'/9349, l='MpServer', x=-317.78, y=57.69, z=487.78], EntityCreeper['Creeper'/9605, l='MpServer', x=-385.41, y=85.00, z=556.97], EntityMinecartChest['container.minecart'/134, l='MpServer', x=-389.50, y=29.06, z=568.50], EntitySkeleton['Skeleton'/9862, l='MpServer', x=-373.59, y=79.00, z=511.91], EntitySquid['Squid'/9351, l='MpServer', x=-312.41, y=56.50, z=556.59], EntitySkeleton['Skeleton'/10632, l='MpServer', x=-379.91, y=20.00, z=595.78], EntityCreeper['Creeper'/9610, l='MpServer', x=-425.50, y=56.00, z=560.50], EntitySquid['Squid'/9358, l='MpServer', x=-317.63, y=59.97, z=528.06], EntityPig['Pig'/144, l='MpServer', x=-381.50, y=74.00, z=529.50], EntitySquid['Squid'/9104, l='MpServer', x=-339.13, y=59.75, z=573.25], EntitySkeleton['Skeleton'/9616, l='MpServer', x=-406.50, y=81.00, z=498.50], EntityPig['Pig'/145, l='MpServer', x=-381.50, y=75.00, z=528.50], EntityMinecartChest['container.minecart'/147, l='MpServer', x=-369.50, y=27.06, z=572.50], EntitySkeleton['Skeleton'/9881, l='MpServer', x=-386.50, y=22.00, z=610.50], EntityBat['Bat'/10393, l='MpServer', x=-426.88, y=53.25, z=553.47], EntityPig['Pig'/161, l='MpServer', x=-364.88, y=72.00, z=495.78], EntityPig['Pig'/162, l='MpServer', x=-365.50, y=81.00, z=574.50], EntityPig['Pig'/164, l='MpServer', x=-364.50, y=100.00, z=574.50], EntityPig['Pig'/165, l='MpServer', x=-358.13, y=112.00, z=572.72], EntitySkeleton['Skeleton'/10662, l='MpServer', x=-426.50, y=49.00, z=527.50], EntityCreeper['Creeper'/9639, l='MpServer', x=-433.50, y=53.00, z=507.50], EntityPig['Pig'/168, l='MpServer', x=-362.50, y=75.00, z=576.50], EntityCreeper['Creeper'/10410, l='MpServer', x=-366.50, y=27.00, z=582.50], EntityCreeper['Creeper'/9902, l='MpServer', x=-321.50, y=66.00, z=518.50], EntityPig['Pig'/180, l='MpServer', x=-347.57, y=71.91, z=550.47], EntityPig['Pig'/182, l='MpServer', x=-351.44, y=78.00, z=564.81], EntitySkeleton['Skeleton'/9910, l='MpServer', x=-292.50, y=24.00, z=494.50], EntityPig['Pig'/183, l='MpServer', x=-343.06, y=68.00, z=560.78], EntityPig['Pig'/184, l='MpServer', x=-348.72, y=69.00, z=562.53], EntitySkeleton['Skeleton'/9656, l='MpServer', x=-429.53, y=50.00, z=555.13], EntityBat['Bat'/10425, l='MpServer', x=-414.50, y=47.13, z=518.34], EntityCreeper['Creeper'/10431, l='MpServer', x=-415.47, y=53.00, z=550.53], EntityMinecartChest['container.minecart'/192, l='MpServer', x=-337.50, y=25.06, z=601.50], EntitySkeleton['Skeleton'/10435, l='MpServer', x=-318.19, y=69.00, z=513.72], EntityZombie['Zombie'/10691, l='MpServer', x=-430.69, y=47.00, z=530.81], EntitySquid['Squid'/9157, l='MpServer', x=-323.22, y=55.72, z=503.81], EntityZombie['Zombie'/10442, l='MpServer', x=-392.16, y=77.00, z=536.34], EntityCreeper['Creeper'/10449, l='MpServer', x=-342.50, y=16.00, z=611.50], EntityBat['Bat'/9943, l='MpServer', x=-387.64, y=32.11, z=589.39], EntityCreeper['Creeper'/10462, l='MpServer', x=-404.50, y=77.00, z=601.50], EntitySkeleton['Skeleton'/9447, l='MpServer', x=-417.72, y=54.00, z=541.53], EntityCreeper['Creeper'/9715, l='MpServer', x=-379.50, y=81.00, z=550.50], EntitySkeleton['Skeleton'/9716, l='MpServer', x=-419.50, y=76.00, z=533.50], EntityBat['Bat'/9718, l='MpServer', x=-374.27, y=28.06, z=573.26], EntitySlime['Slime'/10490, l='MpServer', x=-371.75, y=26.00, z=584.94]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:383)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2645)
	at net.minecraft.client.Minecraft.run(Minecraft.java:401)
	at net.minecraft.client.main.Main.main(Main.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:26)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1750954784 bytes (1669 MB) / 2632056832 bytes (2510 MB) up to 2632056832 bytes (2510 MB)
	JVM Flags: 3 total; -Xincgc -Xmx2560M -Xms2560M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.19 Powered by Forge 11.15.1.1902 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forgeSrc-1.8.9-11.15.1.1902-1.8.9-PROJECT(1.8.9).jar) 
	UCHIJAAAA	Forge{11.15.1.1902} [Minecraft Forge] (forgeSrc-1.8.9-11.15.1.1902-1.8.9-PROJECT(1.8.9).jar) 
	UCHIJAAAA	CodeChickenCore{${version}} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{${version}} [Not Enough Items] (NotEnoughItems-1.8-1.0.5.104-dev.jar) 
	UCHIJAAAA	GalacticraftCore{4.0.0} [Galacticraft Core] (bin) 
	UCHIJAAAA	nei{1.0} [nei] (bin) 
	UCHIJAAAA	GalacticraftPlanets{4.0.0} [Galacticraft Planets] (bin) 
	UCHIJAAAA	NBTEdit{1.8.9-2.0.0} [In-game NBTEdit] (NBTEdit-deobf-1.8.9-2.0.0.jar) 
	UCHIJAAAA	thaifixes{3.0-1.8.9} [ThaiFixes] (thaifixes-3.0-1.8.9-pre-1.jar) 
	Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.139-dev.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
Loader (thaifixes-3.0-1.8.9-pre-1.jar)
  com.lion328.thaifixes.coremod.Loader
MicdoodlePlugin (MicdoodleCore-1.8.9-4.0.0.94-BETA.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
CCCDeobfPlugin (unknown)
  
CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-dev.jar)
  codechicken.core.asm.InterfaceDependancyTransformer
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-dev.jar)
  codechicken.nei.asm.NEITransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 378.66' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'
	Launched Version: 1.8.9
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 750 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 378.66, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x AMD FX(tm)-6300 Six-Core Processor `

**Comment by radfast** [comment]
OK, I can reproduce this.

**How** did this happen?  I'm sure space station create was working a few days ago!

**Comment by radfast** [comment]
Font rendering has changed the button posiition.

Create button works if you click ~ 12 pixels higher than the drawn button.
