### ISSUE TITLE
Unable to seal a room on Mars

### ISSUE THREAD

**Issue by WDayneHS** [micdoodle8/Galacticraft#2737]
I'm trying to seal a fairly large room on Mars, but no matter the number of Sealers that I put in, the room will never seal. I'm sure that all of the blocks used are able to seal. I've attached my save file so someone who is better educated might take a look at it.

Any help is appreciated.

[Bunkers of the Planets.zip](https://github.com/micdoodle8/Galacticraft/files/1017904/Bunkers.of.the.Planets.zip)

**Comment by radfast** [comment]
Which Galacticraft version (please give the exact name of your GalacticraftCore file)?

**Comment by WDayneHS** [comment]
I used the Technic Launcher's Advanced Planetarian Warfare modpack (recommended version), with Worldedit 1.7.10 added. The only blocks used for the base are Galacticraft and Vanilla parts. 

I have a feeling that it is the hoed dirt that is preventing it from sealing.

I posted it here because I think that there may be an issue with one of the sealer's parameters, but if you think the forums will do better, I won't trouble you any longer.

**Comment by radfast** [comment]
Farmland (hoed dirt) will definitely prevent if from sealing - there's a gap at the top!!

I don't think there's an issue with the sealer's parameters in 1.7.10, but if your tests show there's an issue, please post screenshots.

Like I said, it's best to test a small room, like 2x2x2.  If that works OK then you can roll it out to something larger.

**Comment by WDayneHS** [comment]
Don't worry about it, I'm not getting anywhere with this. I will just find a more-updated modpack and play from it instead. Sorry to waste your time.
