### ISSUE TITLE
[1.10.2] Build 94- FPS Lag when hovering over Aluminum wires in JEI

### ISSUE THREAD

**Issue by Enemeez** [micdoodle8/Galacticraft#2738]
When hovering over any of the aluminum wires my frames drop from the average 145 all the way to 13.
![2017-05-22_16 58 48](https://cloud.githubusercontent.com/assets/28690420/26330091/f65ca3b8-3f0f-11e7-9455-a11901814417.png)

**Comment by radfast** [comment]
I can't reproduce this.  Which version of JEI?

The issue is most likely caused by whichever JEI plugin is writing that "**Colors: NetherBrick, LightBlue, IronGray**" info ...   what's that from?
