### ISSUE TITLE
[1.10.2]The Japanese version is garbled.

### ISSUE THREAD

**Issue by HatTricK2358** [micdoodle8/Galacticraft#2739]
Perhaps from around  1.10.2 build 94, most items and GUIs are garbled.
![bug1](https://cloud.githubusercontent.com/assets/27494598/26333444/be9e1766-3f98-11e7-9a69-2200c256a33f.png)
![bug2](https://cloud.githubusercontent.com/assets/27494598/26333445/bea3b11c-3f98-11e7-9d08-26b16d2c8d6f.png)
![bug0](https://cloud.githubusercontent.com/assets/27494598/26333480/f63a79f8-3f98-11e7-95e1-323010275015.png)

**Comment by radfast** [comment]
hmm, that's strange, the Japanese version hasn't changed for a long time.

Please can you help us by identifying which exact Galacticraft version breaks it.  You can get the older versions from [here](https://ci.micdoodle8.com/job/Galacticraft-1.10/) - build numbers on left hand side, click and it will give you the downloads.  For example, specifically, is **build 90** OK in Japanese?  (We changed some stuff to do with fonts between builds 88 and 90)

**Comment by radfast** [comment]
Apart from that I don't think we've changed anything language related since around builds 70-72...

**Comment by radfast** [comment]
This will be fixed in next build 100.  I think we're hoping for that to be our 'release' build - can you wait a couple of days for this?  If you were planning to contribute some Japanese localisations, I wouldn't want to delay you ...

Prior to build 100, Galacticraft builds 70 and earlier do not have this "garbling" issue.

**Comment by HatTricK2358** [comment]
Thank you for quick response! It is popular mod in Japan, so it will be helpful to respond. :)

**Comment by radfast** [comment]
We hope to release build 100 tomorrow (26.05.2017)

**Comment by radfast** [comment]
Build 100 now released.  This is our official stable release of the mod.
