### ISSUE TITLE
[1.7.10/Maybe 1.8+] Suggestion for Space Stations

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft#2741]
@radfast 
Would it be possible to add a config option to toggle the ability for a space station when created to be automatically added to the static loaded list in the config. But by default this config option (to enable automatically add space stations to the static loaded list) would be false because its only useful for servers using other mod telerports or/and kcauldron/thermos for other plugin teleporting.

I would love it if you could add it as it will allow servers owners/staff not have to stress about having the get players to do /gckeeploaded all the time and then the players complain when they cant do /home, etc there :P 

Im open to movement on ways to sort this issue/problem

**Comment by radfast** [comment]
?

You should only need to do /gckeeploaded once, surely

It also always used to be possible to set it up in Bukkit configs.  I don't know if kcauldron/thermos changed something, I'm not in the business of running a server these days...

**Comment by radfast** [comment]
oh I see, you want this for **every new space station**?  maybe there's a bukkit config for that, can you share relevant section of your .xml?

**Comment by MJRLegends** [comment]
@radfast Thats once per player though and that could be still 100+ times, and bukkits way doesnt seem to work only /gckeeploaded

**Comment by radfast** [comment]
Alternatively you could ask Essentials to fix it.  You'll see that they can **in fact** access the dimension, if you do a /back command.  Essentials just decided to put some unnecessary "is the dimension loaded currently" check when using /home.

**Comment by MJRLegends** [comment]
Essentials isnt updated so im unable to ask them for help :(

**Comment by radfast** [comment]
I see, so you simply want the game to auto-run /gckeeploaded at the same time as creating a space station?  That's all?

**Comment by radfast** [comment]
On my server I just patched Essentials when it did things I didn't like ... including the dumbass air block check when you use teleports.  It's not too hard to patch, it isn't obfuscated.

**Comment by MJRLegends** [comment]
Also its not with just /home its with mekanism teleport and that too,

And yeah. if you wanted to that ability could be behind a config option so its not an default GC ability, so people that need it can just set something to true to get that ability

**Comment by radfast** [comment]
ok, seems like shouldn't be too hard, I'll see what I can do

**Comment by MJRLegends** [comment]
@radfast Thanks :P

**Comment by MJRLegends** [comment]
Also i didnt know "dumbass air block check when you use teleports" was a issue. What does it doing that cause?

**Comment by radfast** [comment]
Well, in the past you couldn't use Essentials to teleport to a location which was sealed by an Oxygen Sealer.  It's possible they fixed that, otherwise I think you'd know what I mean here already!

**Comment by radfast** [comment]
@MJRLegends  this will be in next 1.7.10 build, and I'll probably roll this out to 1.8+ as well.

New 1.7.10 build in next 24 hours, I need to look at some other aspects.

**Comment by MJRLegends** [comment]
Nice thanks @radfast :D

**Comment by radfast** [comment]
New build 499 now available.
