### ISSUE TITLE
[1.8+] Weird Oxygen Tank API issue

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft#2742]
Ok so i have made some custom Oxygen Tanks

https://github.com/MJRLegends/ExtraPlanets/blob/dev_1.10.2/src/main/java/com/mjr/extraplanets/items/ItemOxygenTank.java

and 

https://github.com/MJRLegends/ExtraPlanets/blob/dev_1.10.2/src/main/java/com/mjr/extraplanets/items/ExtraPlanets_Items.java#L536

And when putting them in the inventory slots it doesnt work correctly, see tests below:

**Key: Left Oxygen Slot + Right Oxygen Slot**

GC Oxygen Heavy Tank + None - Ok
None + GC Oxygen Heavy Tank - Ok
GC Oxygen Heavy Tank + GC Oxygen Heavy Tank - Ok

Custom Oxygen Tank + None - Doesn't work
None + Custom Oxygen Tank - Doesn't work
Custom Oxygen Tank + Custom Oxygen Tank- Doesn't work

Custom Oxygen Tank + GC Oxygen Heavy Tank - Ok
GC Oxygen Heavy Tank + Custom Oxygen Tank - Ok

**Edit:** 

Ok = works as its taking oxygen from the tanks and not failing the oxygen setup check
Dont Work = Not taking oxygen from the tanks and failing the oxygen setup check

**Comment by radfast** [comment]
I don't understand what "Ok" and "doesn't work" refers to here ... !

Maybe show exactly what's wrong in the GC 1.10.2 sources or submit a PR?

**Comment by MJRLegends** [comment]
@radfast 

Ok = works as its taking oxygen from the tanks and not failing the oxygen setup check
Dont Work = Not taking oxygen from the tanks and failing the oxygen setup check

And im unable to find out why its doing it atm

**Comment by MJRLegends** [comment]
Could this be due to my Gear IDs for oxygen tanks 5000 and 5001?

**Comment by radfast** [comment]
Please place System.out.println debug messages into GCPlayerHandler.checkOxygen() in your IDE to figure out what's going on here, or use breakpoints.

I can't debug this without creating a Galacticraft add-on!

If you can show me what's wrong in Galacticraft's code, I'm sure we can fix it.

**Comment by MJRLegends** [comment]
@radfast ok will do

**Comment by MJRLegends** [comment]
@radfast Found the issue its because im not extending the ItemOxygenTank class with my oxygen tanks as the getDrainSpacing is checking for a item that has the instanceof of it

**Comment by MJRLegends** [comment]
@radfast Any chance we could have a api class like IOxygenTank or something so its easier to know what needs to be done?

**Comment by radfast** [comment]
I don't think that's necessary.  Just extend ItemOxygenTank.

**Comment by MJRLegends** [comment]
@radfast ok np
