### ISSUE TITLE
[1.11.2] Can't open world

### ISSUE THREAD

**Issue by marcus8448** [micdoodle8/Galacticraft#2746]
Whenever I try to run my world the game crashes with no warning I am using build 99 on 1.11.2.
Please help me!
[crash-2017-05-24_08.53.46-server.txt](https://github.com/micdoodle8/Galacticraft/files/1026199/crash-2017-05-24_08.53.46-server.txt)

**Comment by radfast** [comment]
Thanks, we'll take a look - should be able to fix this later today.

**Comment by marcus8448** [comment]
Thx!

**Comment by radfast** [comment]
The fix is in, might be an hour or two (or longer) before we have the next version of the mod available to download though, please be patient.

**Comment by radfast** [comment]
Build 100 now available, hope everything is now OK for you.  Any more issues, please post.
