### ISSUE TITLE
Cannot download galacticraft mods from website(Doesn't load) and cannot load forum either Please help

### ISSUE THREAD

**Issue by CutlassPlayz** [micdoodle8/Galacticraft#2747]
If you are some how either able to send me galacticraft 1.7.10 494-497<----(Any of these) for core, planets, and micdoodle core that would also be appreciated.

**Comment by Dream-Master** [comment]
https://ci.micdoodle8.com/job/Galacticraft-1.7/

**Comment by CutlassPlayz** [comment]
That website refuses to work for me on my phone and computer

**Comment by Dream-Master** [comment]
@CutlassPlayz I can download the mod there. So i guess its you internet connection/firewall/ping etc.

**Comment by CutlassPlayz** [comment]
is there anyway you could help me by putting core, planets, and micdoodle into a download place so I could get them? 494 or above for 1.7.10?

**Comment by CutlassPlayz** [comment]
@Dream-Master

**Comment by Dream-Master** [comment]
Try this
https://www.dropbox.com/s/7rslki40kh2lf2f/Galacticraft-1.7.10-3.0.12.497.zip?dl=0

**Comment by CutlassPlayz** [comment]
BLESS YOU @Dream-Master

**Comment by radfast** [comment]
Guys.  For the future please note: https://wiki.micdoodle8.com/wiki/DownloadTemp

**Comment by Dream-Master** [comment]
@radfast i get a NET::ERR_CERT_DATE_INVALID error when try to connect to jenkins.

**Comment by dj3520** [comment]
#2433

**Comment by EzerArch** [comment]
More precisely: https://github.com/micdoodle8/Galacticraft/issues/2433#issuecomment-304454925

**Comment by MJRLegends** [comment]
Btw its has now been fixed :D
