### ISSUE TITLE
Moon issue

### ISSUE THREAD

**Issue by 4ngelGu4rd** [micdoodle8/Galacticraft#2748]
every time i enter the moon in my single player world the internal server shuts down.I try to re enter it yet again it shuts down.

**Comment by radfast** [comment]
Please give more info so we can help fix this.

Which Galacticraft version?

Start the game, make this happen, then immediately post your logs, **latest.log** and **fml-client-latest.log**
Logs are in the .minecraft/logs folder.  You can copy+paste the whole log into a [Gist](https://gist.github.com/) or into [paste.ee](https://paste.ee/) or similar, then give us the links.

**Comment by Mike-T4** [comment]
This is a bit vague. What MC version and what other mods are you using?

**Comment by radfast** [comment]
Closing due to missing info, there's nothing we can do without the information requested.

If this happens again and you can give the info ^^^^^^ please re-open.
