### ISSUE TITLE
Custom mobs in Galacticraft worlds

### ISSUE THREAD

**Issue by SpikybumJolteon** [micdoodle8/Galacticraft#2749]
I wanted to ask for the ability for modders to add custom mob spawns to Galacticraft worlds without a hard dependency.

I saw the suggestion for this being something like this:
`PlanetRegistry.addMobSpawn(String planet, Class mobToSpawn, int randomChance)`

I really like this idea using a String for the planet identification like Forge does for items.

In my mod, one of my spawn register lines is like this:
`biome.getSpawnableList(EnumCreatureType.MONSTER).add(new SpawnListEntry(EntityRaptorZerglingNincada.class, 55, 3, 5));`

I figure I would show that in case any other values might be needed for that potential PlanetRegistry spawn method.

---------------

One other concern I have would be that my mobs can tell what the gravity value is of the world they are currently located in, if they are in one. That way I can adjust their AIs and Model animations accordingly for any world related to Galacticraft.

**Comment by radfast** [comment]
Hey, thanks for taking up the conversation here.

So I implemented this already.  From your mod all you have to do is call [this method](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/api/galaxies/Planet.java#L37)

You can either include our API - or selected classes from our API - as a soft dependency, or you can call that by Java reflection, it should be easy to call by reflection as it's a static method.

This will be included in our upcoming API and de-obf build 100 available through the [dev download site](https://www.micdoodle8.com/mods/galacticraft/downloads/dev), should be available tomorrow I think.

**Comment by radfast** [comment]
Closing this because the implementation is already in, but you're extremely welcome to continue the conversation here.

**Comment by radfast** [comment]
Build 100 now available with this incorporated, dev download link posted above.
