### ISSUE TITLE
WIKI SSL

### ISSUE THREAD

**Issue by metrotyranno** [micdoodle8/Galacticraft#2756]
Hi, 

Just wanted to let you know the SSL cert of the galacticraft wiki expired yesterday.

**Comment by EzerArch** [comment]
We know it: https://github.com/micdoodle8/Galacticraft/issues/2433#issuecomment-304454925

**Comment by radfast** [comment]
Thank you, very bad luck this happened on the same day as release.

**Comment by Dream-Master** [comment]
change the time on your computer and you can access the page :)

**Comment by MJRLegends** [comment]
Btw its has now been fixed :D
