### ISSUE TITLE
[1.10.2] GC armor rendering persistent 

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#2757]
World 1: Put thermal paddings and frequency module on.

![2017-05-28_01 54 59](https://cloud.githubusercontent.com/assets/6743303/26526200/af7cd05c-4348-11e7-8bdf-3a22b4baf66a.png)

![2017-05-28_01 54 49](https://cloud.githubusercontent.com/assets/6743303/26526205/d3711bb2-4348-11e7-856c-170b74aa6236.png)

Then close the world without closing the client. Create a new or open another world.

World 2:  No armor at all, but the same GC armor from previous world is being rendered.

![2017-05-28_01 58 13](https://cloud.githubusercontent.com/assets/6743303/26526214/266a3f9c-4349-11e7-8926-671ac2942153.png)

![2017-05-28_01 58 23](https://cloud.githubusercontent.com/assets/6743303/26526215/266d4aca-4349-11e7-92c9-e1ec6c88cdaa.png)

**Mods (forge 2297):**
- CodeChickenCore-1.10.2-2.4.1.102-universal
- CodeChickenLib-1.10.2-2.5.7.241-universal
- GalacticraftCore-1.10.2-4.0.0.100
- Galacticraft-Planets-1.10.2-4.0.0.100
- jei_1.10.2-3.14.7.416
- journeymap-1.10.2-5.4.6
- MCMultiPart-1.4.0-universal 
- MicdoodleCore-1.10.2-4.0.0.100
- NotEnoughItems-1.10.2-2.1.3.220-universal
- ShoulderSurfing-1.11.2-1.4
- worldedit-forge-mc1.10.2-6.1.4-dist

**Comment by radfast** [comment]
This probably explains #2708 also.  Good spot.
