### ISSUE TITLE
[1.10.2] Tier 3 Dungeon Key is huge

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#2759]
I know it's hard to see the key in the dungeon, but that's a bit too much. :3

![2017-05-28_02 53 42](https://cloud.githubusercontent.com/assets/6743303/26526416/e298ed4c-4350-11e7-989b-c8b682aa10f0.png)

**Comment by dj3520** [comment]
huge key for huge treasure perhaps?
