### ISSUE TITLE
[1.11.2] [100] Crash loading Space Station

### ISSUE THREAD

**Issue by TheSilentSong** [micdoodle8/Galacticraft#2763]
Forge: 13.20.0.2309
Galacticraft: 1.11.2 - 4.0.0.100

On loading a space station for the first time, I receive this crash: https://pastebin.com/B8YGuTZT

Loaded a creative T3 rocket and tried landing on all other planets just to make sure it was only the station, managed to load them all just fine.

**Comment by radfast** [comment]
Thanks for reporting, this is the new Dungeon Locator code messing up because there are no dungeons on space stations!  We should be able to fix this immediately.

**Comment by EzerArch** [comment]
Just to be sure. The `java.lang.ArithmeticException: / by zero` also happens in 1.10.2.

**Comment by radfast** [comment]
Should be fixed in latest versions for 1.8.9, 1.10.2 and 1.11.2 now available through the download site.

Any more similar problems, please comment or re-open.
