### ISSUE TITLE
[1.11.2] Industrial Craft 2 wont work with Galacticraft 4

### ISSUE THREAD

**Issue by vos3464** [micdoodle8/Galacticraft#2764]
Game crashes when loading these 2 mods and it won't tell me the crash.
For some reason, the crash log file won't get created.
Please test it yourself to find out what the problem is.

**Comment by radfast** [comment]
GC1.11.2 is tested with IC2 and works OK, actually I have IC2 permanently loaded in my workspace in 1.11.2 to make sure of this!

Gonna need more information from you to troubleshoot this:  **exact** versions of both mods, and logs or crash reports.

**Comment by vos3464** [comment]
![image](https://cloud.githubusercontent.com/assets/21976486/26529890/195c46d8-43c1-11e7-9a85-30d662af6cc4.png)
Heres the latest [log](https://pastebin.com/xcGg5hj5)

**Comment by vos3464** [comment]
I removed the Ic2 Config file to see if that is going to fix it.
[fml-client-latest](https://pastebin.com/XVE8TfdR)
EDIT: I removed the config and it got fixed!

**Comment by radfast** [comment]
ok that's good news - please can you show us the 2 different configs for IC2 (broken and new one) and we can see if there's any difference affecting Galacticraft.

Sounds like it could be an IC2 issue.

Anyhow you've fixed it, so I will close this now but if you can give us that config info still, we will look at it some more.

**Comment by radfast** [comment]
>    16:15:36] [Client thread/ERROR] [FML/ic2]: IndustrialCraft 2 Error
 
    The IC2 config file contains an invalid entry for balance/recyclerBlacklist.
 
    Invalid value at line 63 (recyclerBlacklist = minecraft:glass_pane, minecraft:stick, minecraft:snowball, minecraft:snow_layer, minecraft:snow, IC2:blockScaffold).
 
    There is no item matching IC2:blockScaffold.


Not a Galacticraft issue!
