### ISSUE TITLE
[1.7.10] Forge Essentials auth module not working

### ISSUE THREAD

**Issue by X-Coder** [micdoodle8/Galacticraft#2765]
Hi i want to use your mod with forge essentials admin mod. But for some reason, forge essentials auth module stops working when I use your mod.

With forge essentials setting B:canMoveWithoutLogin=false and B:forceEnable=true the player is still able to move around and use everything, when not logged in. Without your mod everything is working fine, the player can't move or use any GUI while not logged in.

I can't see any errors in the logs. The chatmessages, login and registration function do still work.

I tested it with these versions and some older ones:
MicdoodleCore-1.7-3.0.12.498 
GalacticraftCore-1.7-3.0.12.498.jar
Galacticraft-Planets-1.7-3.0.12.498.jar
[forgeessentials-1.7.10-1.4.6.1341-server.jar](https://minecraft.curseforge.com/projects/forge-essentials-74735/files/2410658)
forge-1.7.10-10.13.4.1614-1.7.10

**Comment by radfast** [comment]
Please explain more the function of auth module or provide a link to its documentation.  How can a player who is not logged in move around or use anything in Minecraft at all?

**Comment by X-Coder** [comment]
The authentication module adds a separate in game authentication process to a  server, it has nothing to do with launcher login.

If you connect to a server, you can't do anything on the server until you write /auth register myPassword and /auth login myPassword in chat. This is for vip slots or when the Minecraft Authorization Services goes offline.

You can find the description and docs on this page](https://github.com/ForgeEssentials/ForgeEssentials/wiki/Authentication-Module).

**Comment by radfast** [comment]
Thanks for the link to the sources.

The problem is in ForgeEssentials [this line](https://github.com/ForgeEssentials/ForgeEssentials/blob/1710/develop/src/main/java/com/forgeessentials/auth/AuthEventHandler.java#L65)  It would be better if they checked there for any instance of EntityPlayerMP. 

Best is to report this to ForgeEssentials and ask them to make that change.

You can alternatively try installing PlayerAPI in your server-side mod list, that should probably work.

**Comment by X-Coder** [comment]
Thank you very much for your help, The PlayerAPI fixed the issue for me.
I also reported it in this [ForgeEssential issue](https://github.com/ForgeEssentials/ForgeEssentials/issues/2268).
