### ISSUE TITLE
[1.11.2] Crash when making a Space Station

### ISSUE THREAD

**Issue by vos3464** [micdoodle8/Galacticraft#2768]
I got Galacticraft Latest Version with Industrial Craft 2
Crash Log: https://pastebin.com/h3tWsThm

**Comment by radfast** [comment]
That crash log is lacking information!

We are aware of a current issue with build 100 and Space Stations, you can try [build 101](https://ci.micdoodle8.com/job/Galacticraft-1.11/101/).

**Comment by radfast** [comment]
This issue should now be fixed in the latest build for all versions, available through the regular download site

Any more similar issues, please comment or re-open.
