### ISSUE TITLE
Shift-leftclick doesn't work for creative oxygen tank for the right oxygen tank slot

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#2771]
(Pretty minor issue, quite specific)

Shift-leftclicking a creative oxygen tank will not send it to the right oxygen tank slot in the GC inventory tab.

![2017-05-28_17 56 59](https://cloud.githubusercontent.com/assets/6743303/26532117/69a51c42-43cf-11e7-8034-3b603e8469fb.png)

Tested the other oxygen tank : no problem.

Using: GalacticraftCore-1.10.2-4.0.0.100

**Comment by radfast** [comment]
I think this is intended, as you can only wear the Creative tank alone, not with other tanks (including, not with other Creative tanks).

If you can have a Creative tank in left slot and an empty tank in right slot, that may be a bug...

The Creative tank is also not rendered in 3rd person view currently.

**Comment by SteveKunG** [comment]
This can be closed? I can't reproduce the shift-click bug.

**Comment by radfast** [comment]
I'm happy to close - thanks for your fix to the layer renderer :)
