### ISSUE TITLE
[1.10.2] Shift-Click on Moon-Lander

### ISSUE THREAD

**Issue by Timsuper** [micdoodle8/Galacticraft#2773]
We are playing on a server, and when we shift click or try to take items out of the Lander they disappear.

(Build 100)

**Comment by radfast** [comment]
Thanks we'll take a look.

You will need to update to build 102+ some time anyhow, 100 has a bug server-side with space stations.  But if you don't have space stations yet, don't worry about it today.

**Comment by Timsuper** [comment]
Ok. No we have no Stations yet. What I wanted to add: All items in the Lander disappear at once, once you try to take them.

**Comment by radfast** [comment]
OK, can you give me a modlist or server log please.  I can take a look later today.

**Comment by Timsuper** [comment]
Here you go.

![mods](https://cloud.githubusercontent.com/assets/18632345/26545010/5fa2de7e-4464-11e7-8bc7-872ed17945b1.JPG)
[2017-05-28-3.txt](https://github.com/micdoodle8/Galacticraft/files/1035456/2017-05-28-3.txt)

**Comment by radfast** [comment]
I can't reproduce this problem.

Can it be a manifestation of #2779?  So the player has not landed correctly on the Moon (it's like when you're in an unloaded chunk, you can move but you can't break blocks or pick up items), but a **re-log** puts you back in the lander and fixes it?

**Comment by Timsuper** [comment]
Couldn't reproduce in SP either. Testing in multiplayer...

**Comment by Timsuper** [comment]
Ok. Hmm. Everything seems fine.
