### ISSUE TITLE
Game crashes, when creating a space station

### ISSUE THREAD

**Issue by SamsungHyrican** [micdoodle8/Galacticraft#2774]
I only have these mods installed(and Forge 1.11.2 ofc):

Galaticcraft Core 1.11.2
Galaticcraft Planets 1.11.2
MicdoodleCore 1.11.2

The Space Station is created and i spawn in it for 1 second, but then the game crashes and the world gets unplayable. i cant start the world anymore. 

https://gist.github.com/SamsungHyrican/1220f575b39019a66140e6c3274067e4

**Comment by EzerArch** [comment]
You are using a _slightly_ outdated version (1.11.2-4.0.0.100.jar). Try updating: https://micdoodle8.com/mods/galacticraft/downloads

**Comment by SamsungHyrican** [comment]
it fixed the problem, thanks. it works now

**Comment by radfast** [comment]
Thanks Ez :)

**Comment by radfast** [comment]
Build 104 now available with this fix.
