### ISSUE TITLE
[1.10.2][Build 100] Atomic Battery doesn't have oreDict

### ISSUE THREAD

**Issue by bortooo** [micdoodle8/Galacticraft#2776]
![2017-05-29_21 50 52](https://cloud.githubusercontent.com/assets/28114042/26560813/aab93688-44b9-11e7-9a5b-5e80e9b6cb42.png)

**Comment by radfast** [comment]
thanks, we can add this for next build

**Comment by radfast** [comment]
Build 104 now available with this.
