### ISSUE TITLE
[1.10.2][Build 100] Rendering bug with Avaritia armor

### ISSUE THREAD

**Issue by bortooo** [micdoodle8/Galacticraft#2777]
![2017-05-29_22 03 40](https://cloud.githubusercontent.com/assets/28114042/26561120/06d34a7e-44bc-11e7-9d08-c7edb8d9768a.png)
![2017-05-29_22 03 45](https://cloud.githubusercontent.com/assets/28114042/26561121/07aba13a-44bc-11e7-8dcd-74e5a337e536.png)

Avaritia: 1.10.2-2.1.2.1
[Avaritia issue](https://github.com/Morpheus1101/Avaritia/issues/27)

**Comment by radfast** [comment]
This probably won't be fixable until we support RenderPlayerAPI in 1.10.2 and 1.11.2 (and Avaritia would need to support RenderPlayerAPI also).

Similar for other armors which are very different from vanilla, like ModularPowersuits.

**Comment by EzerArch** [comment]
This is prone to happen with any hi-poly armor, e.g., Mekanism diving set, Modular PowerSuits etc. Our solution prior 1.8 was integrating Smart Moving API on Galacticraft and expecting the other mod to do the same...

O wait, @radfast replied. Hello. 👋 :)

**Comment by radfast** [comment]
Hello :)

I've added the cantfix label for now.

We will look at adding RenderPlayerAPI support to Galacticraft in future, but I think right now that API is not yet even available for Minecraft 1.11.2.

**Comment by Morpheus1101** [comment]
Doable, probably something we'd look at for 1.11.2 at this stage for us anyway.

**Comment by radfast** [comment]
@Morpheus1101  if it's possible to implement your armor purely as a RenderLayer without changing the ModelBiped - so let us control the ModelBiped - there's a chance we can achieve inter-mod compatibility now ... we have just successfully achieved this with WearableBackpacks mod

Is there any chance of this?

**Comment by Morpheus1101** [comment]
i've spoken to covers1624 as he is my rendering guru for Avaritia an he has said to poke him on IRC to discuss this in more detail.

**Comment by radfast** [comment]
I'm actually not on IRC, as I don't like to chat while coding...  happy to talk to covers1624 by email or Skype.  I've sent him an email, please mention to him to look out for it.

**Comment by Morpheus1101** [comment]
He is on Discord & TeamSpeak, but not skype, but i will let him know to check for an email

**Comment by radfast** [comment]
I have found a way to fix this on our side, using the ASM transformer.

Fixed in Galacticraft 4 builds 152 and later.
