### ISSUE TITLE
[Sponge 2254 and later Sponge versions]  Multiplayer landing issue  [relog fixes]

### ISSUE THREAD

**Issue by sintaxcz** [micdoodle8/Galacticraft#2779]
I have issue on multiplayer server every time when some one launch rocket and select galacticraft planet he is teleported to galacticraft dimension and falling like player on planet and cant build etc. and after reconnect they spawn in landing module (baloons etc.) and sucesfully land still.
Build 104 dont fix it 
I starting from overworld 
Server use Sponge 1.10.2-2281-5.2.0-BETA-2353 
Using Player API 1.1 for 1.10.2 (nothing change with or without it)

in console i have only : 
> [06:24:43] [Server thread/INFO] [Galacticraft]: Found matching world (-28) for name: moon.moon 
> [06:24:43] [Server thread/INFO] [journeymap]: sintaxcz joining dimension -28 
> [06:24:43] [Server thread/INFO] [Galacticraft]: Server attempting to transfer player sintaxcz to dimension -28 
And nothing happened only falling down. Only reconect fix it and spawn landing module

**Comment by radfast** [comment]
It's strange, I'm testing build 104 on a Sponge server (spongeforge-1.10.2-2254-5.2.0-BETA-2272.jar) and the landing module is OK...

Any possibility you can test your setup with this older version of Sponge (you might need to roll back Forge to 2254 as well).   If that works, then we know it's a change Sponge made and I can try to find that change.

**Comment by sintaxcz** [comment]
Sorry cant rollback forge on live server with active players but i deleted sponge entirely and landing works with no problem thats mean its a sponge problem

**Comment by radfast** [comment]
ok thank you, very much appreciated

I have set up a test Sponge server, so now that I know it's Sponge, I'll try it with various Sponge versions between 2272 and 2353 and hopefully find a solution :)

**Comment by radfast** [comment]
I've found an issue with spawning entities in Sponge version 2254 and all later versions.

@sintaxcz  if possible please rollback your Sponge to ```spongeforge-1.10.2-2254-5.2.0-BETA-2250.jar```, I think that version of Sponge will not have this issue for you.

In my testing, a client with Forge 2281 can connect with no problems to a server with Forge 2254 - usually the differences between Forge versions are minimal and networking changes are uncommon.  Check for yourself to be sure.

I've also reported this as an issue at Sponge, linked, so let's hope a more long term solution can be found.

**Comment by sintaxcz** [comment]
Thanks i read that report and i realy thanks for your time (3 Hours of testing sponge related bug) I thinking to switching server from sponge to forge essentials becouse i think sponge Is related with some other bugs from some mods i use (advanced rocketry mining rockets stops landing mid air on z-255 when they return from asteroids but i must investigate this problem) only thing why i use sponge Is grief prevention,Spawn command,home and votifier.Forge Essentials have allmost all of that only thing i dont know is votifier And thats realy problem for me becouse no motivation = no votes

**Comment by sintaxcz** [comment]
Ha funny thing is i try to use spongeforge-1.10.2-2254-5.2.0-BETA-2250.jar on my Forge 2281 server with a no problem and teleporting to other dimensions not cause bugs (sometime on sponge 2353 even simple teleport to nether and back blocks commads like /spawn /home and relog fix it ) galacticraft landing modules works and advanced rocketry mining rockets landings now works !

**Comment by radfast** [comment]
Thanks, that confirms the issue report I made to Sponge is affecting several Forge mods, not only Galacticraft.

**Comment by ElSaam** [comment]
What about 1.11.2? I have same issue so what version should i use for 1.11.2?

**Comment by radfast** [comment]
Try [Sponge 2244](https://www.spongepowered.org/downloads/spongeforge/bleeding/1.11.2?until=2017-04-18T02%3A55%3A52Z) for 1.11.2.  That requires Forge 2227, though - like sintaxcz - you might find that the Sponge can actually work OK with other Forge 1.11.2 versions which are close to 2227

**Comment by ElSaam** [comment]
Got it working on 2275 with Forge 2228

**Comment by radfast** [comment]
@ElSaam  that's very interesting

Can I ask you a favour, it would really help.  Can you please also try out a few Sponge 1.11.2 versions after 2275 and let me know the **latest one which works**?

**Comment by ElSaam** [comment]
Actually 2244 was latest working. I tried it with Forge 2227 but says mod missing (Forge 2228) so i used that. That's good because Forge 2228 is recommended. I thought later versions were working because i flew from mars  to mars and looks like it only happens when you render new world.

**Comment by radfast** [comment]
Ok, so 2244 is the latest working and **Sponge 2275 is not working properly** - you're sure?

**Comment by ElSaam** [comment]
Im sure, you can try 2249 if you want to make sure.

**Comment by MJRLegends** [comment]
@radfast This could probably be closed as it doesnt seem to be a issue in the latest builds
