### ISSUE TITLE
Server-Log

### ISSUE THREAD

**Issue by Timsuper** [micdoodle8/Galacticraft#2781]
Found something in the Server-Log. Forge-Server version 12.18.3.2281.
[log.txt](https://github.com/micdoodle8/Galacticraft/files/1039532/log.txt)

**Comment by radfast** [comment]
thanks, investigating
and lol at the obfuscation, most people don't bother!

**Comment by radfast** [comment]
Will be fixed in next build 106.

Please don't talk to any Alien Villagers on your server until that fix :)

Interacting with Alien Villagers in SSP should be ok though

**Comment by radfast** [comment]
Build 106 now available.
