### ISSUE TITLE
Transferring Liquid

### ISSUE THREAD

**Issue by PlatinumFox** [micdoodle8/Galacticraft#2783]
https://wiki.micdoodle8.com/wiki/Galacticraft_4

the above link says to click on the fluid pipe to pull liquids out of a tank, but upon doing this it does not seem to work.
version 1.10.2
gc 4 105

**Comment by PlatinumFox** [comment]
@radfast 
my apologies this is not a bug. i never thought to click the pipes with a wrench (which worked). maybe update the link in the above post for people like me that went around clicking pipes with an empty hand lol. sorry for any troubles i have caused.

**Comment by radfast** [comment]
It's no problem :)

The wiki needs to be fully updated for Galacticraft 4, that will happen soon.
