### ISSUE TITLE
No music in 1.11.2 (maybe others too)

### ISSUE THREAD

**Issue by ElSaam** [micdoodle8/Galacticraft#2786]
Can't hear any Galacticraft music. I'm hearing only normal Minecraft music. This issue has been known since latest 1.7.10 build.

**Comment by radfast** [comment]
Thanks for the report and sorry for the time taken to get to this.  This is fixed in next build 153.

**Comment by ElSaam** [comment]
Many thanks!

**Comment by radfast** [comment]
Welcome, I'm pleased if you are still playing Galacticraft!
