### ISSUE TITLE
[1.8.9] JEI Compressor recipe show as crafting table

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#2787]
![2560-06-02_21 12 58](https://cloud.githubusercontent.com/assets/6128413/26729616/5b076462-47d8-11e7-9653-a44cb8bb4139.png)

**Comment by radfast** [comment]
hi @SteveKunG  I can't easily test JEI in 1.8.9 as my workspace has NEI (standalone NEI) in it.

Our JEI plugin code is basically the same in 1.8.9 and in 1.10.2, and the name "Compressor" is correctly shown in 1.10.2.

[Here](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/client/jei/ingotcompressor/IngotCompressorRecipeCategory.java#L30) is where the name is set in 1.8.9, and that name translates as "Compressor".

Is it possible this is a JEI bug?  1.8.9 JEI was early days for that mod.

**Comment by SteveKunG** [comment]
Testing outside dev environment, with my survival world I got the same result.

![2560-06-03_12 56 07](https://cloud.githubusercontent.com/assets/6128413/26751110/179975ce-485c-11e7-8506-b620b4684f75.png)
![2560-06-03_12 56 22](https://cloud.githubusercontent.com/assets/6128413/26751111/179b3648-485c-11e7-8516-af04768e3d3c.png)
