### ISSUE TITLE
[1.8.9] Space Station Arrival Block owner name is always named "bobby"

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#2790]
Checked by In-game NBTEdit.
Or /blockdata 0 64 0 {}

![2560-06-04_01 08 03](https://cloud.githubusercontent.com/assets/6128413/26755964/5a633078-48c2-11e7-86a7-926df78446ed.png)

**Comment by radfast** [comment]
does it matter?  that name isn't used for anything...  I'm sure you can find lots of unused data if you use NBT editors

**Comment by SteveKunG** [comment]
Oh, then I will make pull request to remove this.

**Comment by MJRLegends** [comment]
Haha 'bobby' great name :D
