### ISSUE TITLE
No oxygen on Air Lock

### ISSUE THREAD

**Issue by ElSaam** [micdoodle8/Galacticraft#2793]
This happened before and should be fixed but it's happening on 1.11.2 build 106 and 107, not sure if others.

**Comment by MJRLegends** [comment]
@ElSaam Please can you add details such as are you using Oxygen Sealer, if so how many? Are the oxygen sealers showing sealed without Air Lock being there and solid blocks instead?
Maybe some images of the setup/building also....

Im sure these will help the developers fix your issue

**Comment by ElSaam** [comment]
Too many oxygen sealers. Showing sealed with solid blocks.
[https://www.youtube.com/watch?v=2TnPl6d20vQ](url)

**Comment by micdoodle8** [comment]
Should be fixed in the next build, thanks!
