### ISSUE TITLE
1.11.2 Nitrogen Bottle crash Build 105

### ISSUE THREAD

**Issue by SebaSphere** [micdoodle8/Galacticraft#2794]
In my server, When someone right clicks a nitrogen canister, thier game crashes.

**Comment by MJRLegends** [comment]
@SebaSphere The developers are going to need the crash log your getting :D

**Comment by SebaSphere** [comment]
Ok. Im going to get it now

**Comment by SebaSphere** [comment]
https://pastebin.com/9gk91g36
14:06:00] [Server thread/INFO]: SebaSphere lost connection: Internal Exception: java.io.IOException: Error while read(...): Connection reset by peer
What it said in server when I crashed^

**Comment by radfast** [comment]
Thanks for reporting, this will be fixed in next build 108, probably to be released tomorrow.

Players should be OK if they have something targeted when they right-click the nitrogen canister, but maybe best not to experiment with this on a live server...
