### ISSUE TITLE
Build 105 Spider Boss Not dropping key

### ISSUE THREAD

**Issue by SebaSphere** [micdoodle8/Galacticraft#2795]
When One of my players Defeats the venus Spider Boss, It doesn't drop a key.

**Comment by MJRLegends** [comment]
Are you able to reproduce this yourself @SebaSphere ?

**Comment by SebaSphere** [comment]
Let me check right now. Haven't tested with a actual chest generated

**Comment by MJRLegends** [comment]
@SebaSphere Ok because im 99% sure this must be a rare or issue based on the setup used

**Comment by SebaSphere** [comment]
Wait. I thought this was the other github issue I posted. This was tested at actual dungeon with me seeing that player defeat boss.

**Comment by SebaSphere** [comment]
Did /invsee just to make sure He wasn't lying.

**Comment by MJRLegends** [comment]
@radfast i believe this issue was fixed in a pull request by me a long time back, probably best to close

**Comment by radfast** [comment]
thanks, yes that was #2930
