### ISSUE TITLE
Build 105 1.11.2 Treasure Chest

### ISSUE THREAD

**Issue by SebaSphere** [micdoodle8/Galacticraft#2800]
In Galacticraft 4, It is possible to get all the items out of the chest without defeating boss. What I did was put a hopper under the chest and got items from a c mode placed chest. Not sure about  boss chests

**Comment by MJRLegends** [comment]
The schematic is only put in the chest at death of boss so hoppering and cheatyness isnt a valid option to get the schematic

**Comment by SebaSphere** [comment]
Ok

**Comment by MJRLegends** [comment]
Im pretty sure the hopper and the Treasure Chest thing isnt going to work either as i believe that loot is also generated at boss death not at chest placement

**Comment by SebaSphere** [comment]
Yes, Its pregenerated

**Comment by MJRLegends** [comment]
This is defo a bug yeah :P @radfast
