### ISSUE TITLE
Airlock's no longer work if set on a horizontal plane

### ISSUE THREAD

**Issue by TheQuadShot** [micdoodle8/Galacticraft#2805]
Minecraft 1.10.2
MicdoodleCore-1.10.2-4.0.0.99-BETA
GalacticraftCore-1.10.2-4.0.0.99-BETA
Galacticraft-Planets-1.10.2-4.0.0.99-BETA

ModList:
https://pastebin.com/fXnVJLyR

LatestLog:
https://pastebin.com/9wYFXb2T

ScreenShot:
http://imgur.com/a/kenKc

iirc I could do this in 1.7.10

**Comment by radfast** [comment]
Thanks for reporting, this looks like a bug.

They were working correctly in a horizontal plane a few builds back, but it appears this function has been broken when fixing something else.  We'll get onto it...

I know you're a long time supporter of Galacticraft and I noticed from your Github profile you're an engineer, would you have time to help more pro-actively with the mod?

**Comment by TheQuadShot** [comment]
Sure, I'd love to help any way I can. I'm disabled now so I am limited in what I can do.

**Comment by micdoodle8** [comment]
_**Should**_ be fixed in the next build. I was able to recreate the issue once but not after that, I believe the commit above should fix the problem. Please re-open if it's present in the next build. Thanks for the report!
