### ISSUE TITLE
Rotating blocks w/wrench should not open UI

### ISSUE THREAD

**Issue by TheQuadShot** [micdoodle8/Galacticraft#2806]
Minecraft 1.10.2
MicdoodleCore-1.10.2-4.0.0.99-BETA
GalacticraftCore-1.10.2-4.0.0.99-BETA
Galacticraft-Planets-1.10.2-4.0.0.99-BETA

ModList:
https://pastebin.com/fXnVJLyR

LatestLog:
https://pastebin.com/9wYFXb2T

When I click or shift click a block (w/wrench) that has a UI it will open said UI...

**Comment by MJRLegends** [comment]
Try updating to the latest build of Galacticraft which i think is build 107 and test to see if its fixed then as i might of already been fixed

**Comment by TheQuadShot** [comment]
Yup, still happening.
