### ISSUE TITLE
micdoodle8.mods.galacticraft.core.util.WorldUtil.setNextMorning(WorldUtil.java:1822)

### ISSUE THREAD

**Issue by zzApotheosis** [micdoodle8/Galacticraft#2807]
## Versions
Minecraft 1.7.10
MCP v9.05
FML v7.10.99.99
Minecraft Forge 10.13.4.1614
Optifine OptiFine_1.7.10_HD_U_D8
MicdoodleCore-1.7-3.0.12.500
GalacticraftCore-1.7-3.0.12.500
Galacticraft-Planets-1.7-3.0.12.500

## Crashlog
https://drive.google.com/open?id=0B_wljXPJi507UWxGTTU5MURwd1k

## Information
It would appear that somehow, the "dayLength" variable in [this](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/util/WorldUtil.java#L1491) method is 0 in the Asteroid Belt, so when players try to sleep (Cryogenic) in the Asteroid Belt, they end up crashing with a divide-by-zero exception. I've gotten two crashes like this before I decided to report it. I haven't tried sleeping in the Asteroid Belt in a while now, so the bug may have been created sometime after GC version 463 (I think, can't recall exactly).

**Comment by radfast** [comment]
Thanks, it's a recent bug.  Fixed in 1.8.9+ by https://github.com/micdoodle8/Galacticraft/commit/fa7165c31ae1e7d53485e2bf217ebbc36815af86 but we should backport that to 1.7.10.  That will be in build 501.

**Comment by zzApotheosis** [comment]
Sounds great. Also, thank you and the other devs for maintaining 1.7.10. I'm still holding onto it while I can!

**Comment by radfast** [comment]
Pleasure.  We intend to continue to fix any major bugs or issues in 1.7.10, but new features from Galacticraft 4 will generally not be backported.
