### ISSUE TITLE
In my modpack, people can Tank the oxygen damage with high armour

### ISSUE THREAD

**Issue by Jacob345k** [micdoodle8/Galacticraft#2808]
Pretty much the title, any way around this? possibly upping the damage or making it void damage? I run 1.7.10 latest version of Galacticraft with other mods, I'm the "Android Guy" as well.

**Comment by radfast** [comment]
thanks, that's a good suggestion - we don't normally take suggestions here, but this one should be quick to solve and now I think about it, it's something which has also been bothering me

(players can also tank Moon Lander and rocket explosion / crash landing damage, which we might do something about ...)

**Comment by radfast** [comment]
hmm, our oxygen damage already bypasses armour ... but maybe your players have **Protection V** enchantments on their armour, or similar, that would still provide protection.

II'm making it so that oxygen and thermal damage will ignore protection enchantments, and rocket explosion damage will need Blast Protection for best mitigation.

**Comment by Jacob345k** [comment]
Do i need a specific version now, or what do i download? I didn't see the update go through on the 1.7.10 download site, it's still 3.0.12.500 http://imgur.com/bxUY2Ew which was the last one i got to fix the android one.

**Comment by radfast** [comment]
Sorry, we're having trouble with our build system making the next build 501 (the build server is low on disk space ...), so you might have to wait a day or two until our systems guy can get to it.  Nothing more I can do on that, I'm not even in the same time zone...

**Comment by Jacob345k** [comment]
No prob man, just got confuzzeled. I host my own server too, I understand.

**Comment by radfast** [comment]
I'll try to remember to post in this thread when build 501 becomes available, or you can just eheck the 1.7.10 downloads every day to see.

**Comment by Jacob345k** [comment]
I'll probably just check the downloads until it's ready, I have no life man. Thanks though!
