### ISSUE TITLE
Dungeon Glitch Build 105

### ISSUE THREAD

**Issue by SebaSphere** [micdoodle8/Galacticraft#2810]
![image](https://user-images.githubusercontent.com/27737877/26853376-af6127c8-4adf-11e7-8b95-2d91c8f89764.png)

If players explore a dungeon, A lot of times they would encounter a wall and have to dig

**Comment by SebaSphere** [comment]
If your confused on the pic, Its me in gm 3 looking at it

**Comment by radfast** [comment]
Please give a World Seed + block coordinates for that screenshot.  If you don't want to post them publicly, send me a PM at the Galacticraft forum.

**Comment by SebaSphere** [comment]
![image](https://user-images.githubusercontent.com/27737877/26853656-e1876c66-4ae0-11e7-904b-34d1f077a062.png)

**Comment by SebaSphere** [comment]
Getting seed now
Also Here's another dungeon
![image](https://user-images.githubusercontent.com/27737877/26853835-9866175c-4ae1-11e7-9fcf-5897ef86cc79.png)

**Comment by SebaSphere** [comment]
![image](https://user-images.githubusercontent.com/27737877/26853892-d2e7dd2a-4ae1-11e7-83bc-0d5416ce1d41.png)
Look in chat

**Comment by SebaSphere** [comment]
coords on top left for each of the dungeons

**Comment by radfast** [comment]
Thanks, we'll look at this.

**Comment by micdoodle8** [comment]
![2017-07-05_23 56 39](https://user-images.githubusercontent.com/1098060/27895015-9748729e-61dd-11e7-9655-99107973c172.png)

I don't seem to be getting the same issue on that seed, even with the same version.

What other mods were/are you using?

**Comment by QuantumStatement** [comment]
I have the similar issue

Minecraft 1.11.2
Forge 13.20.1.2386
Galacticraft 4.0.1.139
Game mode: Singleplayer
No other mods installed

String from latest.log

> [10:12:23] [Server thread/INFO]: [STDERR]: Could not find valid dungeon layout! This is a bug, please report it, including your world seed (/seed) and dungeon location (418, 50)

Seed: 5900424259505527135
Dimension: Moon

![2018-02-23_10 56 36](https://user-images.githubusercontent.com/35406698/36584131-89651f70-1889-11e8-8632-0337861d059d.png)
