### ISSUE TITLE
Missing texture for tile.slab_gc_double.moon_slab.name 

### ISSUE THREAD

**Issue by TheQuadShot** [micdoodle8/Galacticraft#2812]
Minecraft 1.10.2
MicdoodleCore-1.10.2-4.0.0.107-BETA
GalacticraftCore-1.10.2-4.0.0.107-BETA
Galacticraft-Planets-1.10.2-4.0.0.107-BETA

ModList:
https://pastebin.com/fXnVJLyR

LatestLog:
https://pastebin.com/9wYFXb2T

ScreenShot:
http://imgur.com/a/CozGl

I lost the texture to the block after I broke it. I was also expecting to get 2 slabs back when I broke the block.

**Comment by radfast** [comment]
It's currently intended that the double slab has no item texture, because it should be an unobtainable item (and it's not listed in JEI or creative tabs).

The real problem is that it didn't drop 2 slabs when the block was broken.

**Comment by radfast** [comment]
Fixed in next build 110.  Please delete any of the missing-textured blocks (they should not exist, and they can perhaps cause other issues if you keep them).
