### ISSUE TITLE
No experience awared for mining GC ores

### ISSUE THREAD

**Issue by TheQuadShot** [micdoodle8/Galacticraft#2813]
Minecraft 1.10.2
MicdoodleCore-1.10.2-4.0.0.107-BETA
GalacticraftCore-1.10.2-4.0.0.107-BETA
Galacticraft-Planets-1.10.2-4.0.0.107-BETA

ModList:
https://pastebin.com/fXnVJLyR

LatestLog:
https://pastebin.com/9wYFXb2T

Player should get some mining experience for the ores. Also, Tinker tools only get 1 exp for mining said ores which is the same for stone(Tinker Tool Leveling mod required).

**Comment by radfast** [comment]
Thanks for raising this, it's a good piece of polish to add.  Next build will have XP drops for silicon, cheese, desh and quartz ores, and Ilmenite, and Fallen Meteors.  I _think_ that's all the ores which drop items but please let us know if you identify others.

Tinker's Tool exp I don't know about ... I'm not sure if we can easily add their specific tool experience, unless perhaps they base that on the amount of XP orbs dropped?  But Tinker's Tool is a mod a like, and a popular mod, so I'd certainly like to support it if we can.

**Comment by TheQuadShot** [comment]
You also have Copper, Tin, Aluminium, and Galena. (JEI show's different textures for each DIM)

**Comment by radfast** [comment]
AFAIK vanilla does not drop experience orbs for **mining** iron ore, because the player will instead be given experience when he smelts the ore.

For the same reason, we should not drop XP orbs for copper, tin, aluminium and galena ores.

But we should award XP for the smelting, I'll re-open as that is an issue that needs to be fixed.

**Comment by radfast** [comment]
In test I am seeing XP correctly awarding when smelting all the different Galacticraft ores types which produce metal ingots.  XP is awarded both by vanilla furnaces and Galacticraft Electric Furnaces.

>: When I process these ores (in a vanilla furnace) I don't get exp as well. Vanilla ores do award exp when process in this manner. Hope that makes sense.

What types of ore, and are you sure about this?

**Comment by TheQuadShot** [comment]
Hmmm. I just tested this again and in my 1.11.2 it works just fine but my 1.10.2 I don't, One question though, is it a % chance to award or is it a flat number? I had the same issue with IE but discovered that it was a 30% chance to award xp so I have to smelt a stack or half stack to get any and I only use the vanilla furnace early game so I only smelt ingots (with tiny coal) on an as needed bases and my RNG just hates me. Later in the game I move to ore doubling and don't expect any xp as a trade off for double output.

**Comment by radfast** [comment]
Yes, for some ores it's a random chance, e.g. 50% for Galacticraft tin and copper, for others (e.g. gold in vanilla) you always get the XP.

I think the GC Electric Arc Furnace still awards XP even for the doubled output from ores, so actually you receive double XP as well.

Anyhow, seems like no issue remaining that needs to be fixed here, so I'll close this.
