### ISSUE TITLE
Grapple crash after teleport

### ISSUE THREAD

**Issue by SebaSphere** [micdoodle8/Galacticraft#2814]
https://pastebin.com/Yt9VnPtV
In survival Mode wearing a infinite oxygen thing, I tped to a player who wanted to show me his base. I decided to fly around a little and my game crashed.

**Comment by radfast** [comment]
It's the Grapple which is crashing, but in a way which should be impossible if the player is set up correctly.

Which tool are you using for the teleport?  Did this happen fairly soon after the teleport?

Please can you try to reproduce the same crash deliberately, by doing a teleport on your server then using the grapple right after?

**Comment by SebaSphere** [comment]
Player isn't online so I cant test for sure

**Comment by SebaSphere** [comment]
If you ever need to test something, I made you op.

**Comment by SebaSphere** [comment]
Doesnt seem like its with the tp plugin
I just had a player use a grapple in front of me
I crashed

**Comment by radfast** [comment]
Fixed next build, thanks for reporting.
