### ISSUE TITLE
[1.10.2] Build 106 Cargo Rocket Not Landing and Still Running/Items "Disappearing" Inside

### ISSUE THREAD

**Issue by SirKillz** [micdoodle8/Galacticraft#2815]
Version: 1.10.2-4.0.0.106
After the Cargo Rocket reaches its destination, it never fully docks but not like old issues it use to have.  This time the rocket still actually runs and sits in place while "docked" using fuel and making noise and particles.  The video can probably explain things a bit better.  
Video: https://youtu.be/Nj2AgZStCmw

**Comment by radfast** [comment]
Thanks for reporting, should be fixed in next build.
