### ISSUE TITLE
Specify FMLAT for access transformer in MANIFEST.MF, instead of using custom Access Transformer class (for better dev environment compatibility)

### ISSUE THREAD

**Issue by Barteks2x** [micdoodle8/Galacticraft#2817]
I tried to run galacticraft in dev environment, but I found that it crashes as soon as I run `/dimensiontp`, it was caused by a difference in used mappings. Galacticraft currently applies special deobf access transformer on it's own, which seems to be useless now. After I removed the deobf AT, moved the existing one manually to `META-INF` and specified `FMLAT` entry in `MANIFEST.MF` the mod ran just fine.

I can try to submit PR for that if needed.

**Comment by Barteks2x** [comment]
The issue should go to https://github.com/micdoodle8/MicdoodleCore/issues, I didn't notice it's separate repository

**Comment by EzerArch** [comment]
You can close this one here and reopen there. :)

**Comment by Barteks2x** [comment]
Ok
