### ISSUE TITLE
[Sponge] Rare crash with Terraformer on Venus

### ISSUE THREAD

**Issue by SebaSphere** [micdoodle8/Galacticraft#2822]
https://pastebin.com/CEkvHi4J
What happened

**Comment by SebaSphere** [comment]
I just got news that the only player online was using a terraformer on Venus when crash happened. Maybe it has to do with that. When he rejoins, the server crashes

**Comment by SebaSphere** [comment]
Not crashing anymore?

**Comment by radfast** [comment]
This crash should be fixed next commit.
