### ISSUE TITLE
[1.10.2] [PerfectSpawn mod] NoClassDefFoundError for WorldProviderSpace

### ISSUE THREAD

**Issue by fabledtruth** [micdoodle8/Galacticraft#2824]
https://pastebin.com/LYXsNeYC

**Comment by radfast** [comment]
I'm sorry, I have no clue what is causing this.  Galacticraft version 107 works correctly - with no crash on startup - for most people, either standalone or with most other popular mods, we've tested OK with FoamFix for example.

The **ClassNotFoundException** seen in the crash report usually means something is wrong with the installation, but I don't see anything wrong in your log.

Some things to try:

1.   re-download all three Galacticraft mod files, to make 100% sure you have complete downloads - and make sure to get them from our [official site](http://micdoodle8.com/mods/galacticraft/downloads)

2.   make sure you only have **one** version of Galacticraft in your ```/mods``` folder (also check the ```/mods/1.10.2``` subfolder)

3.   check that you can start Minecraft 1.10.2 with Galacticraft and no other mods present - you'll need to move everything else out of your ```/mods``` folder for this, so put your other mods in a safe place, and make sure to create a new world (it will damage an existing world if you change your modlist)

If you can start Galacticraft without your other mods, then it must be a mod conflict I guess, though it's really not obvious which other mod can be conflicting.  You can try to figure out which mod is conflicting using a "binary search" technique, so add back half of your mods to the ```/mods``` folder and see if the game crashes.  If there's no crash, add back half again.  Obviously think about which mods need to go with each other...

At a guess, mods I would be looking at for conflicts are:

1.  Galacticraft add-on mods which are still in beta

2.  any mod which is custom or has a very small number of users

3.  any mod which affects loading of other mods or which claims to make mod loading "easier" 

4.  any mod which is incorrectly distributing our API - if possible, do a file search inside all your .jar files for a folder named ```micdoodle8/mods/galacticraft/api/prefab/world/gen/```, any good zip file app should be able to do this - .jar files are actually .zip files renamed

If you find the cause please let us know here in case it helps someone else.

**Comment by fabledtruth** [comment]
I am removing mod by mod right now to see where it falls apart. Will update when and if i find anything out!

**Comment by fabledtruth** [comment]
after a few hours of going through over 300 mods haha i found the culprit! It is this mod [](https://minecraft.curseforge.com/projects/perfect-spawn) it does not play well with galacticraft it seems.

**Comment by radfast** [comment]
Great job for finding it

We can take a look at ```PerfectSpawn-MC1.10.2-1.4.jar``` and try to figure out why they are crashing us.

May take a while, so you might need to play without that mod for now...

**Comment by radfast** [comment]
I just noticed PerfectSpawn homepage says:

> This mod class transforms all WorldProviders it finds, if you get a crash that only happens while using PerfectSpawn come to me first!

So you should report it to them first ...
