### ISSUE TITLE
Galacticraft fluids in JEI

### ISSUE THREAD

**Issue by KrauzeBartek** [micdoodle8/Galacticraft#2825]
Galacticraft is not compatible with JEI please do samething with that.

**Comment by dj3520** [comment]
![image](https://user-images.githubusercontent.com/8284194/27009573-a771d926-4e5f-11e7-8fc8-e8ed7d1ded92.png)

GC 1.11.2 107 and JEI 1.11.2 4.3.5.277 working.

**Comment by KrauzeBartek** [comment]
But 1.10.2 is not working 100%

**Comment by dj3520** [comment]
What is missing?

**Comment by KrauzeBartek** [comment]
Fluids are missing

**Comment by MJRLegends** [comment]
@KrauzeBartek your statement _"Galacticraft is not compatible with JEI please do samething with that."_ isn't detailed like you gave a above, it does have JEI support just not all features are there yet. You'd be better of putting a suggestion in as this isnt a bug and its not a feature that is there.

**Comment by radfast** [comment]
Which fluids are missing?

**Comment by radfast** [comment]
All the canisters and buckets - which can be filled in machines - are included in JEI in 1.10.2

Here's an example:
![2017-06-18_16 08 41](https://user-images.githubusercontent.com/6842258/27261740-2f43d4e4-5441-11e7-81ac-307357ed2f1e.png)

JEI will not show otherfluid mechanics like click a bucket on a fluid block to pick up the fluid, but JEI is the same for vanilla water.  I don't see anything missing from our side.  If you need additional fluids help, you can find it on the official wiki.

Closing this now.  If there's a specific machine-made recipe missing from JEI, please let us know and we can re-open this.
