### ISSUE TITLE
Client crash when opening Ingot Compressor GUI

### ISSUE THREAD

**Issue by Partonetrain** [micdoodle8/Galacticraft#2830]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-1.7.6-1.11.2.jar)
  ChiselCorePlugin (Chisel-MC1.11.2-0.0.10.14.jar)
  MicdoodlePlugin (MicdoodleCore-1.11.2-4.0.0.107.jar)
  literalascension (literalascension-1.11.2-1.0.2.2.jar)
  LoadingPlugin (Quark-r1.2-92.jar)
  LoadingPlugin (Bloodmoon-MC1.11-1.5.1.jar)
  ForgelinPlugin (Forgelin-1.4.2.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 6/11/17 6:56 PM
Description: Rendering screen

java.lang.ArrayIndexOutOfBoundsException: 9
	at java.util.Arrays$ArrayList.get(Arrays.java:3841)
	at net.minecraft.util.NonNullList.get(SourceFile:40)
	at micdoodle8.mods.galacticraft.core.inventory.PersistantInventoryCrafting.func_70301_a(PersistantInventoryCrafting.java:41)
	at micdoodle8.mods.galacticraft.core.inventory.PersistantInventoryCrafting.func_70463_b(PersistantInventoryCrafting.java:64)
	at noppes.npcs.controllers.data.RecipeCarpentry.checkMatch(RecipeCarpentry.java:99)
	at noppes.npcs.controllers.data.RecipeCarpentry.func_77569_a(RecipeCarpentry.java:69)
	at assets.recipehandler.CraftingHandler.getCraftResult(CraftingHandler.java:156)
	at assets.recipehandler.CraftingHandler.getNumberOfCraft(CraftingHandler.java:203)
	at assets.recipehandler.GuiEventHandler$CreativeButton.func_146112_a(GuiEventHandler.java:108)
	at net.minecraft.client.gui.GuiScreen.func_73863_a(GuiScreen.java:72)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:81)
	at micdoodle8.mods.galacticraft.core.client.gui.container.GuiContainerGC.func_73863_a(GuiContainerGC.java:25)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1115)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.Arrays$ArrayList.get(Arrays.java:3841)
	at net.minecraft.util.NonNullList.get(SourceFile:40)
	at micdoodle8.mods.galacticraft.core.inventory.PersistantInventoryCrafting.func_70301_a(PersistantInventoryCrafting.java:41)
	at micdoodle8.mods.galacticraft.core.inventory.PersistantInventoryCrafting.func_70463_b(PersistantInventoryCrafting.java:64)
	at noppes.npcs.controllers.data.RecipeCarpentry.checkMatch(RecipeCarpentry.java:99)
	at noppes.npcs.controllers.data.RecipeCarpentry.func_77569_a(RecipeCarpentry.java:69)
	at assets.recipehandler.CraftingHandler.getCraftResult(CraftingHandler.java:156)
	at assets.recipehandler.CraftingHandler.getNumberOfCraft(CraftingHandler.java:203)
	at assets.recipehandler.GuiEventHandler$CreativeButton.func_146112_a(GuiEventHandler.java:108)
	at net.minecraft.client.gui.GuiScreen.func_73863_a(GuiScreen.java:72)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:81)
	at micdoodle8.mods.galacticraft.core.client.gui.container.GuiContainerGC.func_73863_a(GuiContainerGC.java:25)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)

-- Screen render details --
Details:
	Screen name: micdoodle8.mods.galacticraft.core.client.gui.container.GuiIngotCompressor
	Mouse location: Scaled: (240, 125). Absolute: (960, 500)
	Screen size: Scaled: (480, 251). Absolute: (1920, 1001). Scale factor of 4

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [GCEntityClientPlayerMP['Partonetrain'/1740925, l='MpServer', x=-445.90, y=69.00, z=202.52], GCEntityOtherPlayerMP['Wolsken'/1792744, l='MpServer', x=-472.70, y=29.09, z=230.49]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-470,67,232), Chunk: (at 10,4,8 in -30,14; contains blocks -480,0,224 to -465,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 2562535 game time, 2594271 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 123 total; [EntityCreeper['Creeper'/1829403, l='MpServer', x=-389.50, y=32.00, z=267.50], EntityCreeper['Creeper'/1829402, l='MpServer', x=-388.50, y=32.00, z=263.50], EntityHorse['Horse'/258, l='MpServer', x=-372.34, y=66.00, z=128.25], EntityHorse['Horse'/263, l='MpServer', x=-370.02, y=64.00, z=170.98], GCEntityOtherPlayerMP['Wolsken'/1667612, l='MpServer', x=-531.44, y=68.42, z=56.30], EntityBabySkeleton['entity.BabySkeleton.name'/1817105, l='MpServer', x=-412.43, y=68.00, z=192.55], EntityItem['item.tile.stonebrick'/1822742, l='MpServer', x=-466.58, y=26.00, z=232.89], GCEntityOtherPlayerMP['Wolsken'/1667612, l='MpServer', x=-452.20, y=69.13, z=197.49], EntityItem['item.tile.dirt.default'/1816590, l='MpServer', x=-468.14, y=26.00, z=231.79], EntityZombie['Zombie'/1828621, l='MpServer', x=-472.93, y=20.00, z=265.43], EntityZombie['Zombie'/1825027, l='MpServer', x=-500.50, y=14.00, z=215.50], EntityItem['item.item.arrow'/1828867, l='MpServer', x=-459.55, y=49.00, z=193.04], EntitySkeleton['Skeleton'/1828098, l='MpServer', x=-521.50, y=38.00, z=177.50], EntityItem['item.tile.flower1.dandelion'/1822471, l='MpServer', x=-469.24, y=25.00, z=231.13], EntityItem['item.tile.dirt.default'/1822470, l='MpServer', x=-465.68, y=32.00, z=233.57], EntityItem['item.item.bone'/1828868, l='MpServer', x=-459.32, y=48.00, z=194.58], EntityBat['Bat'/1829425, l='MpServer', x=-524.63, y=33.75, z=162.40], EntityZombie['Zombie'/1828651, l='MpServer', x=-514.50, y=17.00, z=160.50], EntityZombie['Zombie'/1828650, l='MpServer', x=-514.50, y=17.00, z=162.50], EntityCreeper['Creeper'/1828905, l='MpServer', x=-510.79, y=19.00, z=230.42], EntityZombie['Zombie'/1828904, l='MpServer', x=-403.50, y=47.00, z=188.50], EntitySpider['Spider'/1829416, l='MpServer', x=-406.26, y=39.00, z=221.36], EntityZombie['Zombie'/1828652, l='MpServer', x=-515.50, y=17.00, z=157.50], EntityItem['item.tile.dirt.default'/1822499, l='MpServer', x=-471.24, y=25.00, z=233.42], EntityCreeper['Creeper'/1828647, l='MpServer', x=-391.50, y=47.00, z=156.50], EntitySkeleton['Skeleton'/1829414, l='MpServer', x=-399.50, y=39.00, z=220.50], EntitySkeleton['Skeleton'/1829413, l='MpServer', x=-401.50, y=39.00, z=222.50], EntityRabbit['Rabbit'/1741146, l='MpServer', x=-350.88, y=104.00, z=-169.77], EntityBat['Bat'/1829722, l='MpServer', x=-402.52, y=20.07, z=178.28], GCEntityClientPlayerMP['Partonetrain'/1740925, l='MpServer', x=-445.90, y=69.00, z=202.52], EntityCow['Cow'/1199448, l='MpServer', x=-442.48, y=68.00, z=155.77], EntityCreeper['Creeper'/1823317, l='MpServer', x=-445.49, y=35.00, z=223.30], EntityCreeper['Creeper'/1828171, l='MpServer', x=-422.50, y=19.00, z=120.50], EntitySpark['Spark'/903518, l='MpServer', x=-433.50, y=73.50, z=187.50], EntitySkeleton['Skeleton'/1826883, l='MpServer', x=-503.50, y=57.00, z=259.50], EntitySkeleton['Skeleton'/1829190, l='MpServer', x=-424.33, y=30.00, z=263.49], EntityBat['Bat'/1829755, l='MpServer', x=-426.18, y=41.87, z=221.56], EntityEnderman['Enderman'/1828984, l='MpServer', x=-474.30, y=40.00, z=127.55], EntityBat['Bat'/1809779, l='MpServer', x=-473.92, y=41.10, z=221.20], EntitySquid['Squid'/1829235, l='MpServer', x=-474.72, y=60.45, z=192.24], EntitySquid['Squid'/1829234, l='MpServer', x=-467.52, y=61.35, z=201.15], EntityBat['Bat'/1822321, l='MpServer', x=-510.53, y=19.33, z=226.36], EntitySkeleton['Skeleton'/1817462, l='MpServer', x=-457.77, y=47.00, z=195.32], EntityItem['item.tile.stonebrick'/1822326, l='MpServer', x=-468.14, y=26.00, z=231.79], EntitySkeleton['Skeleton'/1828981, l='MpServer', x=-455.50, y=46.00, z=260.50], EntitySquid['Squid'/1829237, l='MpServer', x=-473.56, y=62.03, z=201.60], EntityZombie['Zombie'/1824629, l='MpServer', x=-364.50, y=32.00, z=158.50], EntityBat['Bat'/1809780, l='MpServer', x=-467.32, y=36.10, z=224.08], EntitySquid['Squid'/1829236, l='MpServer', x=-467.88, y=61.54, z=195.16], EntityChicken['Chicken'/112, l='MpServer', x=-516.14, y=68.00, z=141.37], GCEntityOtherPlayerMP['Wolsken'/1667612, l='MpServer', x=-450.70, y=69.00, z=192.74], EntityChicken['Chicken'/114, l='MpServer', x=-514.46, y=65.00, z=146.13], EntityItem['item.tile.stonebrick'/1822825, l='MpServer', x=-467.76, y=25.00, z=233.37], EntityBabySkeleton['entity.BabySkeleton.name'/1825129, l='MpServer', x=-410.67, y=68.00, z=205.29], EntityHorse['Horse'/115, l='MpServer', x=-520.89, y=68.00, z=143.97], EntityPig['Pig'/124, l='MpServer', x=-518.37, y=63.00, z=265.29], EntityBat['Bat'/1828710, l='MpServer', x=-485.75, y=52.10, z=132.25], EntityBat['Bat'/1828709, l='MpServer', x=-482.75, y=52.10, z=129.25], EntitySkeleton['Skeleton'/1828252, l='MpServer', x=-439.50, y=31.00, z=164.50], EntityEnderman['Enderman'/1829521, l='MpServer', x=-510.50, y=16.00, z=206.50], EntityHorse['Horse'/142, l='MpServer', x=-512.77, y=68.00, z=153.18], EntitySkeleton['Skeleton'/1810580, l='MpServer', x=-473.48, y=43.00, z=209.73], EntityZombie['Zombie'/1829513, l='MpServer', x=-448.50, y=36.00, z=164.50], EntitySpider['Spider'/1827720, l='MpServer', x=-394.50, y=39.00, z=210.50], EntitySkeleton['Skeleton'/1829000, l='MpServer', x=-520.50, y=14.00, z=174.50], EntityZombie['Zombie'/1829519, l='MpServer', x=-510.50, y=16.00, z=208.50], GCEntityOtherPlayerMP['Wolsken'/1792744, l='MpServer', x=-529.76, y=71.76, z=45.59], EntityHorse['Horse'/153, l='MpServer', x=-486.98, y=68.00, z=166.07], EntityItem['item.tile.stonebrick'/1822849, l='MpServer', x=-471.22, y=25.00, z=233.17], EntityHorse['Horse'/155, l='MpServer', x=-482.21, y=69.00, z=140.46], EntityZombie['Zombie'/1828487, l='MpServer', x=-446.50, y=26.00, z=134.50], EntitySkeleton['Skeleton'/1828999, l='MpServer', x=-519.50, y=14.00, z=176.50], EntityCreeper['Creeper'/1828486, l='MpServer', x=-450.50, y=26.00, z=139.50], EntitySquid['Squid'/1825978, l='MpServer', x=-470.75, y=61.00, z=187.40], EntitySpark['Spark'/903343, l='MpServer', x=-432.50, y=70.50, z=185.50], EntitySquid['Squid'/1825977, l='MpServer', x=-466.79, y=62.07, z=171.46], EntityZombie['Zombie'/1828797, l='MpServer', x=-373.50, y=19.00, z=267.19], EntityZombieVillager['Zombie Villager'/1828796, l='MpServer', x=-401.50, y=43.00, z=149.50], EntityHorse['Horse'/168, l='MpServer', x=-487.04, y=68.00, z=152.13], EntitySpark['Spark'/903333, l='MpServer', x=-432.50, y=70.50, z=186.50], EntityWorm['Worm'/170, l='MpServer', x=-477.50, y=62.50, z=191.50], EntitySpark['Spark'/903335, l='MpServer', x=-432.50, y=70.50, z=187.50], EntityWorm['Worm'/171, l='MpServer', x=-477.50, y=62.50, z=200.50], EntityWorm['Worm'/172, l='MpServer', x=-477.50, y=62.50, z=194.50], EntityWorm['Worm'/173, l='MpServer', x=-477.50, y=62.50, z=197.50], EntityBat['Bat'/1818804, l='MpServer', x=-502.75, y=14.52, z=215.25], GCEntityOtherPlayerMP['Wolsken'/1667612, l='MpServer', x=-532.12, y=70.64, z=55.37], EntityZombie['Zombie'/1826474, l='MpServer', x=-416.50, y=35.00, z=268.50], EntitySpark['Spark'/903614, l='MpServer', x=-429.50, y=70.50, z=186.50], EntityBat['Bat'/1828013, l='MpServer', x=-379.25, y=17.96, z=133.40], EntityZombie['Zombie'/1828524, l='MpServer', x=-397.50, y=23.00, z=245.50], EntityBat['Bat'/1829539, l='MpServer', x=-518.59, y=41.83, z=174.65], EntityWolf['Wolf'/285880, l='MpServer', x=-456.50, y=67.00, z=222.40], EntityCreeper['Creeper'/1824987, l='MpServer', x=-402.50, y=17.00, z=232.50], EntityHorse['Horse'/194, l='MpServer', x=-454.30, y=66.00, z=217.91], EntityZombie['Zombie'/1829087, l='MpServer', x=-451.20, y=36.00, z=166.52], EntitySkeleton['Skeleton'/1805277, l='MpServer', x=-457.50, y=49.00, z=190.79], EntitySkeleton['Skeleton'/1805276, l='MpServer', x=-460.46, y=49.00, z=205.27], EntityAncientGolem['Ancient Golem'/202, l='MpServer', x=-451.50, y=38.00, z=238.25], EntityCow['Cow'/203, l='MpServer', x=-403.27, y=68.00, z=121.50], EntityHorse['Horse'/205, l='MpServer', x=-450.11, y=64.00, z=153.07], EntityFireDragon['Fire Dragon'/206, l='MpServer', x=-416.89, y=9.00, z=160.11], EntityBat['Bat'/1827797, l='MpServer', x=-402.10, y=19.12, z=176.58], EntityZombie['Zombie'/1828565, l='MpServer', x=-398.58, y=43.00, z=154.18], EntitySkeleton['Skeleton'/1828564, l='MpServer', x=-400.50, y=43.00, z=149.50], GCEntityOtherPlayerMP['Wolsken'/1667612, l='MpServer', x=-450.70, y=69.00, z=192.74], EntityBat['Bat'/1829577, l='MpServer', x=-439.16, y=34.83, z=235.17], EntityCreeper['Creeper'/1828558, l='MpServer', x=-459.50, y=32.00, z=135.84], EntityCreeper['Creeper'/1828557, l='MpServer', x=-459.50, y=31.00, z=137.50], EntityZombie['Zombie'/1809345, l='MpServer', x=-444.10, y=28.00, z=232.38], EntityHorse['Horse'/221, l='MpServer', x=-443.00, y=66.00, z=248.93], GCEntityOtherPlayerMP['Wolsken'/1792744, l='MpServer', x=-472.70, y=29.09, z=230.49], EntityHorse['Horse'/232, l='MpServer', x=-391.72, y=70.00, z=128.87], EntityZombie['Zombie'/1828851, l='MpServer', x=-514.50, y=46.00, z=144.50], EntitySpark['Spark'/903396, l='MpServer', x=-434.50, y=73.50, z=186.50], EntityHorse['Horse'/234, l='MpServer', x=-390.02, y=70.00, z=137.01], EntityHorse['Horse'/235, l='MpServer', x=-387.00, y=70.00, z=133.98], EntityHorse['Horse'/237, l='MpServer', x=-430.29, y=66.00, z=247.11], EntitySkeleton['Skeleton'/1828854, l='MpServer', x=-483.50, y=52.00, z=123.50], EntityBat['Bat'/1814773, l='MpServer', x=-495.75, y=27.10, z=237.55], EntitySpider['Spider'/1827563, l='MpServer', x=-410.83, y=22.00, z=132.50], EntitySpider['Spider'/1827562, l='MpServer', x=-405.50, y=22.00, z=131.50], GCEntityOtherPlayerMP['Wolsken'/1792744, l='MpServer', x=-472.70, y=29.09, z=230.49]]
	Retry entities: 30 total; [EntityRabbit['Rabbit'/1741146, l='MpServer', x=-350.88, y=104.00, z=-169.77], EntityRabbit['Rabbit'/1741080, l='MpServer', x=-379.43, y=102.00, z=-175.52], EntityRabbit['Rabbit'/1741144, l='MpServer', x=-337.68, y=103.00, z=-158.23], EntityRabbit['Rabbit'/1741145, l='MpServer', x=-344.97, y=104.00, z=-168.28], EntityZombie['Zombie'/1741587, l='MpServer', x=-363.73, y=67.00, z=-131.50], EntityRabbit['Rabbit'/1741075, l='MpServer', x=-359.39, y=101.00, z=-92.98], EntityZombie['Zombie'/1796177, l='MpServer', x=-561.50, y=55.00, z=29.50], EntityHorse['Horse'/1760464, l='MpServer', x=-531.13, y=69.00, z=28.87], EntityCreeper['Creeper'/1800464, l='MpServer', x=-583.50, y=27.00, z=22.50], EntityRabbit['Rabbit'/1741078, l='MpServer', x=-361.80, y=103.00, z=-161.80], EntityItem['item.item.tconstruct.edible.slimeball_blue'/1741142, l='MpServer', x=-330.88, y=198.63, z=-83.13], EntityRabbit['Rabbit'/1741143, l='MpServer', x=-327.71, y=104.00, z=-159.79], EntityRabbit['Rabbit'/1741076, l='MpServer', x=-369.45, y=102.00, z=-80.57], EntityItem['item.item.tconstruct.edible.slimeball_blue'/1740936, l='MpServer', x=-335.76, y=101.00, z=-107.59], EntityChicken['Chicken'/1771336, l='MpServer', x=-458.11, y=68.00, z=26.25], EntityBat['Bat'/1741510, l='MpServer', x=-343.49, y=25.22, z=-58.30], EntityBat['Bat'/1741511, l='MpServer', x=-337.27, y=23.85, z=-58.09], EntityZombie['Zombie'/1742021, l='MpServer', x=-346.50, y=22.00, z=-133.50], EntityBabySkeleton['entity.BabySkeleton.name'/1741498, l='MpServer', x=-354.49, y=19.00, z=-144.50], EntityBlueSlime['entity.blueslime.name'/1742650, l='MpServer', x=-336.47, y=201.25, z=-90.12], EntityBabySkeleton['entity.BabySkeleton.name'/1741499, l='MpServer', x=-358.50, y=22.00, z=-145.50], EntityBlueSlime['entity.blueslime.name'/1742648, l='MpServer', x=-337.49, y=201.00, z=-92.32], EntityBabySkeleton['entity.BabySkeleton.name'/1741497, l='MpServer', x=-358.51, y=22.00, z=-149.66], EntityBlueSlime['entity.blueslime.name'/1742649, l='MpServer', x=-341.22, y=200.00, z=-90.57], EntityBat['Bat'/1741118, l='MpServer', x=-379.65, y=37.75, z=-103.52], EntityZombie['Zombie'/1741500, l='MpServer', x=-362.50, y=22.00, z=-152.50], EntityBlueSlime['entity.blueslime.name'/1742647, l='MpServer', x=-341.78, y=200.42, z=-93.64], EntityZombie['Zombie'/1741998, l='MpServer', x=-334.50, y=23.00, z=-154.50], EntityZombie['Zombie'/1741997, l='MpServer', x=-328.50, y=23.00, z=-157.50], EntityBat['Bat'/1794918, l='MpServer', x=-587.75, y=29.10, z=24.25]]
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:393)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version

**Comment by radfast** [comment]
Appears to be a conflict with Custom NPCs mod, can you give us exact version of that mod - actually give us a full modlist please or ```fml-client-latest.log```

At this stage it's not clear whether it is Galacticraft causing this problem or Custom NPCs, but we'll take a look.

**Comment by Partonetrain** [comment]
CustomNPCs jar is named `CustomNPCs_1.11.2(25may17).jar`.

Strangely, I can't find my `fml-client-latest.log`. Although if it's any consolation, the crash log references the carpentry bench which was actually removed from CustomNPCs and moved to Varied Commodities in 1.11.2, making me think it's a CustomNPCs problem.

**Comment by radfast** [comment]
I think we should be able to fix this from our side in build 108.  Please try it when it's available (should be later this weekend)
