### ISSUE TITLE
Build 107 display screens not working in Multiplayer

### ISSUE THREAD

**Issue by SebaSphere** [micdoodle8/Galacticraft#2831]
When I right click display screens on my server. They stay black

**Comment by radfast** [comment]
You still on build 105?

**Comment by SebaSphere** [comment]
Upgraded server to Build 107 awhile back

**Comment by SebaSphere** [comment]
This didn't work in build 105. I just completely forgot to report

**Comment by radfast** [comment]
Next time you play, please can you test this quickly in a single player world before you join your server.

I can't reproduce this, I'm wondering whether it is a problem specific to your server setup / Sponge.

**Comment by radfast** [comment]
Confirmed to be an issue in Multiplayer only.

**Comment by radfast** [comment]
Problem found and fixed in next build 109.
