### ISSUE TITLE
Some parts of WorldUtils.teleportEntity are done twice and/or wrong

### ISSUE THREAD

**Issue by Barteks2x** [micdoodle8/Galacticraft#2832]
Note: all that is said below is about the 1.11.2 branch, I don't know if it's still the case for older versions.

I noticed the problem when testing cubic chunks mod compatibility. Due to how it internally works, it's much more sensitive to incorrect usage of `PlayerChunkMap` class, and when teleporting between galacticraft dimensions it was crashing.

The issue:

 * First galacticraft is removing the player from PlayerChunkMap by calling `PlayerChunkMap#removePlayer`, cacthing any exceptions and ignring it. This one is not going to fail, but it shouldn't be there, because vanilla already does it later. But turns out it's "needed" (not really, explanation later)
 * Then Galacticraft calls `PlayyerList#preparePlayer` with `worldNew` as argument, which is also wrong.  Minecraft will try to remove player from the world it's going to, whicch does nothing. But it also adds the player to that world *after* trying to remove it, which succeeds
 * Then galacticraft calls the above method again, this time with `worldOld` as argument, which is correct here. Minecraft will try to remove player from the old world (again, which normally would do nothing), and add it to the new world **for the second time**. This causes huge debug log spam, but noone will really see it because debug logging is disabled by default. it also causes player to be added to the internal PlayerChunkMap list twice. This means that when setting render distance, which just happens to have no side effects aside of being slightly slower and spamming debug log. But adding the player twice also means that **the player needs to be removed twice**. This is why the first call to `PlayerChunkMap#removePlayer` is needed in the first place, because `PlayerList#preparePlayer` has been called twice.

So really, it's not surprising that it breaks with some other mods, it's surprising that it works at all in vanilla.

Then there is also the issue that galacticraft uses it's own weird way to remove the player from the old world that is completely redundant because it's done again later, this time correctly. So the `removeEntityFromWorld(worldOld, player, true);` line is completely redundant and may even cause issues (and very likely it did with cubic chunks, as this was the most likely reason the new world was receiving position updates in PlayerChunkMap before the player got added)

For completreness, this is fixed part of that method: https://pastebin.com/RKh2R5JH

**Comment by radfast** [comment]
Thank you, this is very helpful.  I'll take a detailed look at each of these.  It's likely most of these points are easily resolved now you have identified them, maybe even typos in the code.

**Comment by radfast** [comment]
Thanks again.  The issue boils down to:
1. unnecessary call to ```PlayerChunkMap#removePlayer``` as this will be done later by vanilla ```preparePlayer``` code
2. duplicated ```PlayyerList#preparePlayer``` line, which definitely should not have been there (and the worldNew was wrong!)

Both these things are now fixed.  The linked commit will propagate up to 1.11.2 when we merge branches later tonight.

-------

I don't see any problem with ```removeEntityFromWorld()``` line, why do you say this line is redundant?  This is doing the equivalent of ```worldserver.removePlayerEntityDangerously(playerIn)``` in vanilla dimension transfer code.

**Comment by Barteks2x** [comment]
I don't exactly remember now because it was too long ago, but iirc `worldserver.removePlayerEntityDangerously(playerIn)` is called directly some time later in other method.

**Comment by radfast** [comment]
OK, I see it, thank you!
