### ISSUE TITLE
[1.11.2] Fluid pipes not updating Embers containers

### ISSUE THREAD

**Issue by Eufranio** [micdoodle8/Galacticraft#2834]
When connecting a fluid pipe (with fluid ofc) to an Embers Fluid Vessel, the vessel will not fill in the client side, only in the server, so the client can't see the Vessel filling up with liquid. The Embers dev pointed me here.

Modpack: [MTN - Concept](https://www.technicpack.net/modpack/magibeta-111.1024667)
Embers 0.214
GalactiCraft 1.11.2-4.0.0.107

If you need any other info, just let me know.

**Comment by radfast** [comment]
This is something we won't be fixing, sorry!

Like most other "big" mods - for example Mekanism and [Thermal Dynamics](https://github.com/CoFH/ThermalDynamics/blob/1.12/src/main/java/cofh/thermaldynamics/util/TickHandler.java) - Galacticraft does all of its power and fluid pipe calculations and distribution on **server-side only**.  So **Embers** is going to have the same problem with all these mods.

Our machines, or tanks - and the tanks from most other mods I can think of, including Buildcraft, EnderIO, IC2, Mekanism - have their own methods for updating the client if fluid contents changes server-side.

Embers should really do the same.  It would be easy enough for them to add some client-updating code to the `fill()` method on their tanks.

I would discuss this directly with them except it looks like Embers is no longer on Github...
