### ISSUE TITLE
Abandoned Base issues (And an issue with the NASA workbench)

### ISSUE THREAD

**Issue by BrisingrAerowing** [micdoodle8/Galacticraft#2836]
Galacticraft 1.10.2 build 107

In the brewing room in abandoned bases, the potions in the brewing stands are defined incorrectly, using metadata instead of NBT. This causes them to display as a missing texture water bottle.

Also, the NASA workbench cannot be broken, in creative or survival, unless the block beneath it is broken, and even then it won't drop anything.

**Comment by radfast** [comment]
Thanks for reporting.  It's great to get the NASA workbench issue fixed, this will also improve the Cryogenic Chambers in Abandoned Bases.

All issues are fixed from build 4.0.0.112, should be available later tonight.
