### ISSUE TITLE
Flowing Oil textures glitched

### ISSUE THREAD

**Issue by TheDutchMC04** [micdoodle8/Galacticraft#2839]
The textures of the oil fluid are glitchy.
![2017-06-17_22 12 41](https://user-images.githubusercontent.com/28569170/27255998-211ab19a-53aa-11e7-8824-14e41e522cd7.png)
![2017-06-17_22 12 45](https://user-images.githubusercontent.com/28569170/27255999-211b4a10-53aa-11e7-8ed2-48a9188ede9f.png)
![2017-06-17_22 12 53](https://user-images.githubusercontent.com/28569170/27256000-211d800a-53aa-11e7-91f4-88217060f803.png) The last one is inside of a oil block

**Comment by EzerArch** [comment]
As usual, we'll need:
* Minecraft version.
* Galacticraft version.
* Installed mods.
* Has Optfine installed?

**Comment by zerisius** [comment]
i can confirm this.

for me it is minecraft 1.10.2
Galacticraft-Planets-1.10.2-4.0.0.109.jar
GalacticraftCore-1.10.2-4.0.0.109.jar
MicdoodleCore-1.10.2-4.0.0.109.jar

optifine is installed but i dont think that the mod causes this. when you walk into oil its just like air with a black texture on top from inside. there are no physical changes and there is no oxygen depletion etc.

**Comment by TheDutchMC04** [comment]
I use Minecraft 1.10.2, Java 8
Galacticraft-Core-1.10.2-4.0.0.107.jar
Galacticraft-planets-1.10.2-4.0.0.107.jar
MicdoodleCore-1.10.2-4.0.0.107.jar

ExtraPlanets-0.5.1-Beta-Build.jar

I don't use OptiFine or a resourcepack.
I have no changed GC or MicdoodleCore configs

Modlist:
JourneyMap (by techbrew)
EnderCore (by tterrag1098)
Ender IO (by CrazyPants_MC)
Inventory Tweaks (by Kobata)
Just Enough Items (JEI) (by mezz)
Mouse Tweaks (by YaLTeR97)
Chisels & Bits (by AlgorithmX2)
CodeChicken Lib 1.8.+ (by covers1624)
Brandon's Core (by brandon3055)
Waila (by ProfMobius)
MCMultiPart (by amadornes)
Refined Storage (by raoulvdberge)
OpenBlocks Elevator (by VsnGamer)
ValkyrieLib (by ValkyrieofNight)
Simple Generators (by ValkyrieofNight)
Mystical Agriculture (by BlakeBr0)
Cyclops Core (by kroeser)
Colossal Chests (by kroeser)
CompatLayer (by McJty)
McJtyLib (by McJty)
RFTools (by McJty)
ExtraPlanets (by MJRLegends)
Chisel (by tterrag1098)
VeinMiner (by Portablejim)
Wawla - What Are We Looking At (by darkh4x)
Mantle (by mDiyo)
Tinkers Construct (by mDiyo)
Tinkers' Tool Leveling (by bonusboni)
FTBLib (by FTB)
FTB Utilities (by FTB)
Extra Utilities (by RWTema)
Custom Main Menu (by lumien231)
Resource Loader (by lumien231)
Mob Grinding Utils (by Vadis365)
Draconic Evolution (by brandon3055)
Railcraft (by CovertJaguar)
Flat Colored Blocks (by AlgorithmX2)
FlatBedrock Xplosion's Edition (by big_Xplosion)
GraveStone Mod (by EuhDawson)
Galacticraft-core
Galacticraft-planets
MicdoodleCore

You can find the project here:[https://minecraft.curseforge.com/projects/galaxy-tales](url)

**Comment by SteveKunG** [comment]
This is Minecraft Forge issue, See also https://github.com/MinecraftForge/MinecraftForge/pull/3747

**Comment by radfast** [comment]
Thank you @SteveKunG  :)

Looks like Forge have fixed it in 1.11 but not backported to 1.10.

@TheDutchMC04  you can try going to Forge and ask them to backport the fix to Forge 1.10.2 - shouldn't be too hard to do, now that they know how to fix it in 1.11.

Anyhow, there's nothing we can do about it, if it's an issue in Forge.

**Comment by TheDutchMC04** [comment]
Thanks for the help!

**Comment by radfast** [comment]
actually looking at this further, we **may** be able to fix it our side by copying the Forge patch into our 1.10 code, though that will be for Galacticraft fluids only ... trying it, will see.

**Comment by SteveKunG** [comment]
By the way, Forge fluid fix code can be used in 1.8.9 and 1.10.2
https://github.com/SteveKunG/MorePlanets/blob/master/1.8.9/src/main/java/stevekung/mods/moreplanets/util/blocks/BlockFluidBaseMP.java#L181-L283

**Comment by radfast** [comment]
Yes, exactly.  https://github.com/micdoodle8/Galacticraft/commit/d562f1a6733e5b15f2b1590fa0e411a624ef577c Seems to work fine.

I saw your code has a note to remove in 1.11+, but actually in Galacticraft we will keep it in 1.11.  The reason is that this patch is not included in **all** Forge 1.11 versions (our minimum version requirement is 2228 which is before this patch).  And it does no harm to override Forge base code if the function is the same.
