### ISSUE TITLE
Could not get provider type for dimension -32, does not exist

### ISSUE THREAD

**Issue by MIGA2001** [micdoodle8/Galacticraft#2842]
Crashes on first minute of playing.
I changed dimention -30 to -32 due to id incompatibilities
That's all I know) Help please.
[crash-2017-06-19_19.20.49-client.txt](https://github.com/micdoodle8/Galacticraft/files/1085798/crash-2017-06-19_19.20.49-client.txt)

**Comment by MJRLegends** [comment]
Your crash is related to potions

`24 is asked by: potion.paralysis (biomesoplenty.common.potions.PotionParalysis), ic2.potion.radiation (ic2.core.IC2Potion)`

There for this has nothing to do with Galacticraft, it seems your config changes didnt effect this it just fixed you dimension conflicts

**Comment by MJRLegends** [comment]
AntiIdConflict and biomesoplenty and ic2 is your issue mod

**Comment by MIGA2001** [comment]
Thanks, that helped
