### ISSUE TITLE
java.lang.IllegalArgumentException: Failed to unregister dimension for id xx; No provider registered

### ISSUE THREAD

**Issue by DarioPro18** [micdoodle8/Galacticraft#2846]
https://pastebin.com/ecgbuq4U

I found this error when I exited and returned on my world created a few minutes ago.

One thing what I did was to change the dimension IDs for almost all the dimensions of the GalacticraftCore and ExtraPlanets mods because I found another error:

`java.lang.IllegalArgumentException: Could not get provider type for dimension xx, does not exist`

After changing the Dimension IDs, all works fine.

Someone who had the same problem?

**Thanks for help!**

**Comment by MJRLegends** [comment]
all you need to do is change some dimension ids in the configs of mods

**Comment by MJRLegends** [comment]
This isnt a bug as you can change them in the config, nothing can be done to sort this it will always happen with mods

**Comment by DarioPro18** [comment]
It Worked, thanks!
