### ISSUE TITLE
Galacticraft4 fluid pipes will not connect to Mekanism Oxygen

### ISSUE THREAD

**Issue by DrTwosie** [micdoodle8/Galacticraft#2847]
#### Issue description:
Galacticraft oxygen pipes used to connect to electrolytic separators and gas tanks of oxygen. Galacticraft 4 replaced oxygen pipes with fluid pipes. These do not connect.

I've raised it with Mekanism [here](https://github.com/aidancbrady/Mekanism/issues/4482) they suggest it is down to the connector api?

#### Steps to reproduce:
1. In a creative map, place a full tank of oxygen, an electrolytic separator, and a pressurized tube
2. Place fluid pipe next to each of these, or a sealed fluid pipe
3. They don't connect.

#### Version:
** Mekanism:9.3.2.309 for 1.11.2
** Galacticraft 4

**Comment by radfast** [comment]
Should be improved in next build 116.

No promise that Fluid Pipes do **everything** that Mekanism Pressurised Tubes can do.  But they can do the basics, for example you can now connect them to a Mekanism Electrolytic Separator and they will fill a Galacticraft tank or machine with oxygen / hydrogen.
