### ISSUE TITLE
Cannot pull wafers from Circuit Fabricator

### ISSUE THREAD

**Issue by TheQuadShot** [micdoodle8/Galacticraft#2849]
Galacticraft-Planets 1.10.2-4.0.0.107
GalacticraftCore 1.10.2.4.0.0.99
MiccdoodleCore 1.10.2-4.0.0.107

Galacticraft-Planets 1.11.2-4.0.0.106
GalacticraftCore 1.11.2-4.0.0.106
MiccdoodleCore 1.11.2-4.0.0.106

I can auto feed it the raw materials, but I can't pull wafers from it.

http://imgur.com/w3XwuuR
http://imgur.com/K5sojbR

**Comment by micdoodle8** [comment]
Thanks for the report. The wafers can be accessed from the bottom of the fabricator, and the top will now accept raw materials (along with the sides, as before).
