### ISSUE TITLE
Electric Arc Furnace Status doesn't change when redstone signal applied	(related to #2845)

### ISSUE THREAD

**Issue by TheQuadShot** [micdoodle8/Galacticraft#2850]
Galacticraft-Planets 1.10.2-4.0.0.107
GalacticraftCore 1.10.2.4.0.0.99
MiccdoodleCore 1.10.2-4.0.0.107

Galacticraft-Planets 1.11.2-4.0.0.106
GalacticraftCore 1.11.2-4.0.0.106
MiccdoodleCore 1.11.2-4.0.0.106

I have a stack of ore in the machine, I apply a redstone signal to it and it will stop processing ore, but it's status is "Running". It's status will only change if the input hopper empty at which point it changes to "Idle".

**Comment by radfast** [comment]
Thanks, fixed in 112 for both Electric Furnace and Electric Arc Furnace.

If you spot any more similar machine status issues, please post 'em up: they're quite easy to fix now that we have generalised rules for this.
