### ISSUE TITLE
Entering Cryogenic Chamber opens console.

### ISSUE THREAD

**Issue by TheQuadShot** [micdoodle8/Galacticraft#2851]
Galacticraft-Planets 1.10.2-4.0.0.107
GalacticraftCore 1.10.2.4.0.0.99
MiccdoodleCore 1.10.2-4.0.0.107

Galacticraft-Planets 1.11.2-4.0.0.106
GalacticraftCore 1.11.2-4.0.0.106
MiccdoodleCore 1.11.2-4.0.0.106

It's not really an issue unless I hit the Leave Bed button. If I sleep it's closed when I awaken.

**Comment by micdoodle8** [comment]
Hmm, this is an issue in vanilla as well, the console opens when you sleep in a bed. I think I'm going to have to leave this the way it is, to keep the behavior the same as vanilla. This is also very hard to fix because the sleep GUI is opened by vanilla code.
