### ISSUE TITLE
[1.11.2] Client desync: cannot break blocks in Space Station dimension

### ISSUE THREAD

**Issue by Eufranio** [micdoodle8/Galacticraft#2854]
When in a space station, the block hardness seems to be 0 for the client. So, we insta-break the blocks in the client, but as the hardness in the server is higher, it will only break in the client side, so we are unable to break the blocks in the space station.

I believe this is a client desync, since it also happened in the Moon dimension with me, but a re-log fixed the issue, but in the space stations relogging doesn't fix the issue... If you need any other info, just let me know.

**Comment by TheQuadShot** [comment]
Could you pastbin your mod list and latest.log file? Also what version are you running?

**Comment by Eufranio** [comment]
(Latest.log)[https://cdn.discordapp.com/attachments/185387567351332864/327934388442759170/latest.log]

**Comment by radfast** [comment]
Is it improved if your feet are on the ground, I mean landed on a block?

**Comment by Eufranio** [comment]
Sorry?

**Comment by TheQuadShot** [comment]
I've seen this before, I believe that the server needs to be restarted, it's worked for me on my server at least.

**Comment by Eufranio** [comment]
Restarting the server does NOT fixes this issue... After login again, the block hardness will still "seem" to be 0 for players in space station dimensions...

**Comment by radfast** [comment]
@Eufranio 

>   Is it improved if your feet are on the ground, I mean landed on a block?

I mean is the block hardness always seeming like 0 for the players in the space station dimension, or is it only like this when the player is floating in zero G (player feet not touching any block)?

**Comment by Eufranio** [comment]
The block hardness is **always** like 0, no matter if I'm floating or not.

**Comment by TheQuadShot** [comment]
I can't repro this. I went to https://www.technicpack.net/ and installed their launcher and mod pack, created a space station and didn't have a problem. I'm not sure what to do as far as testing but I'm open to suggestions.

**Comment by Eufranio** [comment]
This is happening on a [SpongeForge](https://github.com/SpongePowered/SpongeForge) server, with `spongeforge-1.11.2-2315-6.1.0-BETA-2381` and Forge `1.10.2-13.20.0.2298`, not in singleplayer. I can't test with pure forge, so idk if the issue also happens on it.

**Comment by radfast** [comment]
Please try the recommended version of Sponge.
https://wiki.micdoodle8.com/wiki/Sponge

There are multiple issues if you use a more recent version like 2381, the Sponge dev team are aware of this and it's not a Galacticraft issue.

**Comment by radfast** [comment]
I'm going to assume this issue is no longer happening, as it's been over a year since I posted ^^^^^^^^ and Sponge has had many updates since.

Please comment or re-open if it's seen again.
