### ISSUE TITLE
[1.10.2] EntityAstroMiner crash with Hwyla/Waila/Wawla

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft#2855]
Astro miner placed within the base crashes everyone in the area with the following crash log..

Crash Log: https://pastebin.com/AWGNxN8M

Hwyla: 1.8.17-B31
Wawla: 2.3.2.215
Galacticraft: Build 109
Forge: 12.18.3.2316

**Comment by radfast** [comment]
From our perspective this is a bug in WAILA / WAWLA.

I have already reported it [here](https://github.com/Darkhax-Minecraft/WAWLA/issues/75) with a simple solution (try / catch) but no progress seems to have been made on fixing it.

For now, I suggest you do not include WAILA etc in your modpack with Galacticraft.  And that's a good idea anyhow, I'd be literally **amazed** if there are no other mods where WAILA is causing crashes in a similar way.  Basically any modded entity of any kind is _at risk_ of crashing client-side if you look at it with WAILA / WAWLA installed.

**Comment by radfast** [comment]
https://wiki.micdoodle8.com/wiki/Compatibility

**Comment by Eufranio** [comment]
This problem also happens with Hwyla (developed by TehNut, that still active).

**Comment by MJRLegends** [comment]
@eurfannio thats what im using

**Comment by MJRLegends** [comment]
@radfast not including the mods isnt a option im afraid :(

**Comment by MJRLegends** [comment]
I can confirm removing Wawla fixes this issue

**Comment by radfast** [comment]
I've added a workaround for this from build 111.

Really the WAWLA guys should have fixed this, their approach is dangerous and unreliable.  WAWLA is giving nonsense results when you look at some other entities, rockets, for example - says everything is a Tier 1 Rocket.

**Comment by MJRLegends** [comment]
Nice thank you
