### ISSUE TITLE
Oxygen Sealer Algorithm Problem and Suggestion

### ISSUE THREAD

**Issue by ccbrown** [micdoodle8/Galacticraft#286]
In attempting to construct an epic space station, I've run into a few quirks of the sealer that are making my designs a bit.. challenging..

The biggest problem (and the part that would most likely classify as a bug) would be that two or more sealers sitting right next two each other aren't guaranteed to increase the maximum sealable volume.

Here's a small scale, 2-dimensional example of the problem with the current algorithm.  Say we had this area:

```
............................
.................|--------|.
................|         |.
...............|     |----|.
..............|     |.......
.............|     |........
............|     |.........
...........|     |..........
..........|   1 |...........
..........|2    |...........
..........|   3 |...........
...........|     |..........
............|     |.........
.............|     |........
..............|     |.......
...............|     |----|.
................|         |.
.................|--------|.
............................
```

The spaces and the dots represent empty blocks.  The numbers represent sealers.

Say the directions are `{NORTH, SOUTH, WEST, EAST}` (In-game they're `{DOWN, UP, NORTH, SOUTH, WEST, EAST}`).  Also say that instead of checking up to 1250 blocks, each sealer checks up to 50 (so this area, being 144 blocks including the walls should be sealable with this setup).

Walking through the current algorithm in [ThreadFindSeal.java](https://github.com/micdoodle8/Galacticraft/blob/f1fcc34fda6e5c35518db9bcc880b17d331a0e6d/common/micdoodle8/mods/galacticraft/core/oxygen/ThreadFindSeal.java), we "loopThrough" once, starting with sealer 1:  

```
............................
.................oq-------|.
................lnp       |.
...............ikmr  |----|.
..............ehjws |.......
.............fdgAvt|........
............XWcEzxu.........
...........| VbDBy..........
..........|  UaFC...........
..........|2 TSG|...........
..........|   RH|...........
...........|  QI |..........
............| PJ  |.........
.............|OK   |........
..............NL    |.......
...............M     |----|.
................|         |.
.................|--------|.
............................
```

Each letter represents a block that `loopThrough` is called for, assigned by the order that the call was made.  Once `loopThrough` was called for all of those blocks, and the stack unwinds, we end up with about 65 or so blocks checked, 1 additional sealer found (sealer 3), and no seal.

So next, because another sealer was found, we run through the loop again, with "checkCount" set to 100 instead of 50.

The recursion would do the same thing as before, but continue on to hit all of the blocks in the nose, including the third sealer, and would fill in parts of the wings:

```
............................
.................oq-------|.
................lnp       |.
...............ikmr  |----|.
..............ehjws |.......
.............fdgAvt|........
............XWcEzxu.........
...........1YVbDBy..........
..........2+ZUaFC...........
..........3_!TSG|...........
..........4)@&RH9...........
...........%#^QI80..........
............$*PJ7~:.........
.............(OK6`;'........
..............NL5=\<|.......
...............M -]> |----|.
................}"[       |.
.................{--------|.
............................
```

It would call loopThrough for a few more blocks but I ran out of characters (Also note that all of the sealers have been hit and I started using numbers for calls to loopThrough as well.).

The end result of this loop is that all three all sealers were found, but the seal was not made.  The third sealer (originally sealer number 2) did absolutely nothing, because it was added to sealer 1's thread, but only after the "checkCount" for sealer 1 was determined to be 100.

So hopefully that gives a decent overview of the problem.  

Of course, the theoretical stuff is interesting and all, but it doesn't really matter if no one can produce it in-game.  Well, unfortunately, I've been running into quirks caused by this on a lot of rooms with volumes of 2500+ blocks, namely this thing: 

http://imgur.com/Fkhkm1s

http://imgur.com/ktU8Tjz (The ring is divided in half so this is only intended to seal half of it.)

_Sometimes_ it works.  But then when I leave the zone and come back it stops.  But then after leaving and coming back a few more times, sometimes it starts working again (with no changes to anything).  Whether or not it works seems to be entirely dependent on which one of the sealers is processed first (based on debug log observations).

I can reproduce minimal test cases in creative if necessary.

I could suggest improvements or fixes like doing a breadth-first traversal through the blocks instead of depth-first, or not adding sealers to the thread if they're only found in that second loopThrough pass, but really I'd like to suggest a completely different algorithm because I'd really like to see a fundamental change in the sealers.

First off, they aren't really "sealers".  They're oxygen distributors.  That's what they do.  They can only work if everything has already been sealed.  

Next, the requirement that they be in close proximity to each other in order to increase range requires designs for large areas to just have a big clump of sealers hidden away in one place somewhere.  What I'd really like to see is something more realistic, where the oxygen distributors (or sealers, whatever you want to call them) have to be spread throughout the area that they're providing oxygen to.  So basically, each machine would provide oxygen to up to 1250 blocks within the sealed area, expanding from the machine in all directions IF and only if the entirety of the sealed area has oxygen provided to it.

Not only do I think this algorithm would be more enjoyable and have more predictable / intuitive behavior, but this algorithm could be made very efficient.  It would basically go like this:

Step 1:  For each active machine in existence, create a list of the blocks that it is capable of providing oxygen to.  These blocks would be found by a breadth-first search, radiating from the top of the machine, adding up to 1250 non-solid blocks within the sealed area. This is trivially cache-able and entirely independent of the presence of other nearby machines.  I'll call this list of blocks the machine's "service volume".

Step 2:  For each machine...

a.) If its service volume is entirely enclosed (which can be determined trivially in step 1), provide oxygen to the volume.
b.) Otherwise, if a block on the boundary of the service volume is neighboring a non-solid block that isn't part of another machine's service volume, provide no oxygen to the volume.
c.) Otherwise, a block on the boundary of the service volume is neighboring one or more blocks that are part of other machines' service volumes.  Mark the machine as having dependencies on the other ones.  After the next step, once dependencies are resolved, the machine will provide oxygen to its volume if and only if the other machines provide oxygen to theirs.

Step 3. Resolve dependencies.  Circular dependencies result in the involved machines providing oxygen to their volumes.

**Comment by CharZinta** [comment]
Seems like this might be back as two sealers next to each other only increase the space I can seal by about 100 blocks. So placing 6 sealers, thinking this would seal my 4chunk 4 rows deep, didn't work.  I could be wrong but here is my info. GC 1.7.10.12.372 Can anyone else duplicate this?

**Comment by dj3520** [comment]
@CharZinta Please update via the links at #2151 to the newest version of Galacticraft.
