### ISSUE TITLE
[Suggestion] Permission to create a space station

### ISSUE THREAD

**Issue by Eufranio** [micdoodle8/Galacticraft#2860]
Since Space Stations are a whole dimension, it would be nice for servers to have a permission for users to create a space statio, like `galacticraft.spacestation.create`, so we can restrict their creation.

**Comment by dj3520** [comment]
Check the core.conf config
`   # If set to true on a server, players will be completely unable to create space stations.`
`    B:"Disable Space Station creation"=false`

**Comment by Eufranio** [comment]
I have already seen this, and I dont want players COMPLETELY UNABLE to create space station, I want to RESTRICT their creation for specific players.

**Comment by TheQuadShot** [comment]
I don't understand the reason for this request, since each player can only create 1 space station. Is it for quest reward? or you just don't like some people? Or is it for premium player/subscribers only? I really am just trying to understand it.

**Comment by Eufranio** [comment]
I personally would only give this permission for "members": players who have played in the server for more than 1 month, so not everyone (guests) would be able to create space stations. Your points seems to be good reasons too, allowing space station creation as a reward for a quest is a nice idea.

**Comment by micdoodle8** [comment]
Are there other forge mods which add permissions like this? I wasn't aware this was possible.

**Comment by Eufranio** [comment]
Yes, CoFH mods (I think Thermal Expansion) adds a permission node for the `/cofh friends` command, and MineTweaker (now CraftTweaker) adds nodes for the `/mt` command, trough I don't think they use the default forge permissions API. For reference: https://github.com/MinecraftForge/MinecraftForge/pull/3155

**Comment by micdoodle8** [comment]
Thanks for the info, I've added a permission node as requested with 50befeda9692e482688ee851246418d9543a159b. Note this is only available in 1.10+, since there is no permission API before Forge 1.10.2-12.18.2.2121

**Comment by Eufranio** [comment]
Thanks!
