### ISSUE TITLE
I can't silk touch Venus Volcanic Rock

### ISSUE THREAD

**Issue by TheQuadShot** [micdoodle8/Galacticraft#2863]
Galacticraft-Planets 1.10.2-4.0.0.107
GalacticraftCore 1.10.2.4.0.0.99
MiccdoodleCore 1.10.2-4.0.0.107

Galacticraft-Planets 1.11.2-4.0.0.106
GalacticraftCore 1.11.2-4.0.0.106
MiccdoodleCore 1.11.2-4.0.0.106

Sorry if this is intended behavior. However it would be cool to carry a stack of portable lava :)

**Comment by micdoodle8** [comment]
Thanks :) Portable lava will be a feature in the next build!
