### ISSUE TITLE
Is there a way to create new recipes inside Gas Liquefier through Minetweaker/Modtweaker?  

### ISSUE THREAD

**Issue by lightning02** [micdoodle8/Galacticraft#2867]
I would like to add custom gasses into liquids, making hydrogen and nitrogen to fuse and create Ammonia.(The Ammonia is made from customitems mod). But I really was hoping for the process being made through Gas Liquefier machine :l

**Comment by radfast** [comment]
There is no way to do this currently.  To do it would need two things:
(a) on Galacticraft's side we would need to make an API method for adding recipes to the Gas Liquefier
(b) on Minetweaker/Modtweaker's side, they would then need to code for that API specifically

It's a good idea, but it's not worth us doing the API coding unless Minetweaker / Modtweaker will then be willing to add it as a feature - have you asked them?  Happy if you want to link to this issue.

Anyhow, I am closing this as it is not an "issue" with the Galacticraft mod as currently released, it is more of a question / suggestion.

Even though this is closed, you are welcome to carry on discussing it here, and if there is a solid case for an API change then that is something we can add to the list of suggestions which we plan to implement.

**Comment by Syndaryl** [comment]
I understand that CraftTweaker actually has an API for you to add your own items without them doing a mod update.

**Comment by lightning02** [comment]
@Syndaryl  I guess I could create an item like a tank called "Hydrogen-Nitrogen Gas Mix" and leave the pressure-fractionational process to the Gas Liquefier in order to obtain the liquid Ammonia.

**Comment by lightning02** [comment]
@radfast the owner of craft tweaker said that he could help / guide you eventually if you want to add support for it

**Comment by radfast** [comment]
Thanks @lightning02 that could be great, who is the owner of CraftTweaker?

**Comment by Syndaryl** [comment]
@jaredlll08 is the project lead/maintainer/whatever over at CraftTweaker. Active developer.

**Comment by jaredlll08** [comment]
o/ You could say I'm active  *most of the time*
anyway, I'm only really support 1.12 at the moment, baring 1 or 2 PR's for 1.11 final release, so if GC is 1.12, I'm happy to add support for it in Modtweaker, if not, maybe work on adding support in GC directly?

**Comment by radfast** [comment]
thanks @jaredlll08 

we are currently in bugfix phase for 1.10 and 1.11, so not yet in 1.12.

in principle I'm happy to support CraftTweaker for our various machines which have specific recipes.  Please can you link me to an example of another mod implementing the API?
