### ISSUE TITLE
Flexibility for Modpack Creators.

### ISSUE THREAD

**Issue by Axiom1999** [micdoodle8/Galacticraft#2873]
This is a simple feature request / idea that intends to give more flexibility to map architects and/or modpack creators.

Essentially, imagine providing a configuration file that allows per world/dimension modifications.
The main modification I'm looking for is the ability to change the atmospheric components of worlds. Looking at your source code, it seems you hard-code the components in and breathable air seems to be determined per dimension. Determining this through a config would be great! Creators could make the Overworld radioactive and take advantage of the Oxygen tanks etc.

An example could be:
```
"0": {
  "name": "Overworld",
  "pressure:" 1,
  "atmosphere: [
    "oxygen", 
    "water", 
    "nitrogen", 
    "argon"
  ],
  "radioactive": true
}
```

How cool would it be to remove Oxygen to simulate non-breathable atmosphere for radioactivity / possibly even add a radioactive effect as mentioned above!

**Comment by radfast** [comment]
This is a suggestion, and belongs on the forum.

If you want to create your own planet with the exact desired characteristics you want, it's not too hard to code a planet if you're not interested in having original worldgen or original features - there are lots of open source examples.

We do have a long term project of making atmosphere components and other planet details easier to code, but I do not have any current plans to open this up to JSON type configuration files.  It would be better for a custom modpack maker to code their own planet, or find a friendly coder to do it.
