### ISSUE TITLE
Day-night cycle doesn't match the /time command

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#2877]
The apparent day-night cycle, i.e., sun position in the sky and ambient brightness, doesn't match the values used in `/time [set|add]` command and it's quite inconsistent.

**Affects:** Minecraft 1.7.10 and 1.10.2, in the Space Station, Moon, Mars dims.

The bug was introduced in [the build 493](https://ci.micdoodle8.com/job/Galacticraft-1.7/493/changes).

### How to reproduce
For instance, Mars' day length is 24000t. The sunrise is supposed to happen _roughly_ at 0t plus N days × day length. Execute `/time set 0` and `/time set 24000`, the Sun sometimes will be at sunrise position, in others at the sunset, and sometimes the command doesn't work.

Try also `/time set 0` and then `/time add 24000` a few times, the sun will be at different positions as if the day length is ~12,320t. Actually it is 24000t if you leave the game running normally.

**Video:** https://youtu.be/dQ87V8TgMe4 (0:00 through 2:00 is enough)

### Additional info
I had noticed the sun in the Space Station dim wasn't obeying the /time command as usual, as if the day was shortened in half. I thought it was a new feature. But later on I found some solar panels on Mars were collecting energy at 10PM, it was when I found the /time issue and feared it was affecting the solar panels.

Nonetheless, I couldn't reproduce the solar panel part as you can see in the video, probably it was an isolated case. Breaking and replacing them seem to fix the issue. I'm also testing cryo-chambers to see if there is a correlation.

I'll add more details if I find something.

**Comment by EzerArch** [comment]
New info: This affects 1.10.2 version too.

**Comment by radfast** [comment]
This should be improved in build 165.
