### ISSUE TITLE
[1.10.2] (Optifine) Cape model bug with GC Player model when held rocket

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#2878]
![2560-07-04_12 15 11](https://user-images.githubusercontent.com/6128413/27815960-9778d49c-60b2-11e7-88f8-233816a395e4.png)

**Comment by EzerArch** [comment]
Only the cape? Try holding a rocket with thermal padding, oxygen gears, frequency module and control module. I suspect the GC Player model has a wrong vertical position when it holds rockets and other GC vehicles.

**Comment by marcus8448** [comment]
Is this fixed now? My issue (#2903) has been fixed.

**Comment by radfast** [comment]
I think this is now fixed in build 152.

Any more issue, please re-open with fresh screenshots ... maybe not at night :)
