### ISSUE TITLE
[1.10.2] TF Crude Oil Not Compatible

### ISSUE THREAD

**Issue by themechman** [micdoodle8/Galacticraft#2880]
Running 4.0.0.111 build with forge-1.10.2-12.18.3.2185-universal. ThermalFoundation-1.10.2-2.1.4.8-universal is running as well.

I was doing some testing and found that only the GC oil bucket is able to be refined in the Refinery. Sadly I dont know if this is an actual bug.

- Thermal Foundation adds an oil fluid as well since the oil from GC is compat with BC/PC oil/fuel. This shows as Forge Crude Oil.
- Pools of crude oil default to GC Oil bucket when you scoop them.
- Thermal Foundation will not process GC oil.
- Cannot place GC fluids into TF/TE/Mek tanks with bucket.

On the uptick, the end resultant "Fuel" is 100% compatible with each other. (The bucket item is NOT!)

**Comment by radfast** [comment]
The issue here is we are not currently accepting all oil types.  I mean the issue is not the buckets but the fluid inside the buckets. Happy to add the TF oil, I just need to check its internal name.

**Comment by radfast** [comment]
Should be compatible in next build 4.0.0.112, available tomorrow.

Please re-open this if these TF buckets are still not being accepted.

**Comment by themechman** [comment]
Thank you. I will let you know shortly.
