### ISSUE TITLE
No Meteors spawning on Mars

### ISSUE THREAD

**Issue by DragonwrathI** [micdoodle8/Galacticraft#2885]
Hi folks awesome Mod!

Only one real issue i see so far:
I have been active on Mars for 8-10 hours of play time so far and have not had a single meteor strike. 2 BC quarries side-by-side as well as a chickenchunks chunklloader for the power plant, all running for 3 hours+ and not a single meteor strike within the loaded chunks. I did not leave the area throughout this time.

While on the moon, I saw them constantly. At one point, I went AFK for a while in my base and found at least a dozen upon my return. Is there still a chance for metoers on Mars? The wiki's say so but they may be outdated...
Or perhaps it's a range thing? I have render distance set to 6 due to all the extra dimension/chunk loading going on. Was the same setting on the moon though where I had an abundance of meteors.

Mods:
GC v4.0.0.106
BC v7.99.6
Chickenchunks v2.1.3.68
Enderstorage v2.3.1.116

**Comment by radfast** [comment]
Thanks for reporting, we'll look into it.
I'm also not seeing any Slimeling eggs on Mars.

Which Minecraft version?

**Comment by DragonwrathI** [comment]
Same here, thanks for the reminder, haven't seen a single slimeling egg.
MC is 1.11.2

**Comment by radfast** [comment]
Meteor spawning should be improved in next build, see 516ba15

This also fixes an issue where 2 or 3 meteors sometimes landed at the exact same coordinates, building a tower of meteors.

------

The Slimeling eggs I'm still working on.  Looks like they are spawning in 1.11.2, only at the wrong heights - if you fly around in Creative mode you can sometimes find one in the air.

**Comment by radfast** [comment]
Slimeling eggs on Mars have been fixed for some time now :)
