### ISSUE TITLE
[1.11.2] Deconstructor eats everything!

### ISSUE THREAD

**Issue by marcus8448** [micdoodle8/Galacticraft#2888]
The Deconstructor will eat anything! It will take almost any non-GC item (ex. Cobblestone) and eat it up and give nothing back.
RANDOM ITEM:
![2017-07-10_12 17 16](https://user-images.githubusercontent.com/28928887/28035825-e07e0506-656a-11e7-8e88-0ce4e43cb741.png)
FML-Client-Latest.log here: https://gist.github.com/marcus8448/c197ea72d64859ed4d522900477ae9b9#file-gistfile1-txt

**Comment by marcus8448** [comment]
Note: Iron/Diamond etc blocks will still give items

**Comment by radfast** [comment]
Diamond should not give items...

This is intended behaviour.  If you don't want the Deconstructor to eat your item and see what you get from it, then don't put the item in the Deconstructor...

Basically it should be able to recover the metals from any item: it's not 100% recovery, but you probably don't have any other options...  Items which have no metallic elements will simply be eaten.  (The investigation of whether the item contains metal or not is, shall we say, 'destructive'.)
