### ISSUE TITLE
Moon block Turf with world edit //set command

### ISSUE THREAD

**Issue by TimeGumLord1** [micdoodle8/Galacticraft#2892]
Hi there i was wondering how to use world edit to make objects using planet blocks such as moon turf. I wanted to do //set then moon but it cannot refer it to anything?

**Comment by radfast** [comment]
In the F3 debug screen in Minecraft, if you look at a block, it will tell you on the right-hand column the internal name of the block and the metadata you need.

**Comment by TimeGumLord1** [comment]
ok thanks

**Comment by TimeGumLord1** [comment]
hi there  i tried doing that but it still cannot refer

**Comment by EzerArch** [comment]
I'm almost sure world edit doesn't like the "modname:blockname" thing.

Try this:
- Press F3+H
- In the inventory (Press E), hover your mouse on a Moon Turf block.
- Get the "numeric_ID:numeric_datatag" (it's in the tooltip) and use it.

**Comment by TimeGumLord1** [comment]
im sorry but dont get what you mean, i have done this but there is just this: 
![2017-07-14_14 31 18](https://user-images.githubusercontent.com/22731806/28214193-3525b25a-68a1-11e7-81aa-6404a3101dbc.png)

**Comment by dj3520** [comment]
use //set 4307:5

**Comment by TimeGumLord1** [comment]
does not match valid block type

**Comment by TimeGumLord1** [comment]
it says

**Comment by dj3520** [comment]
thermos/cauldron/kcauldron server?

**Comment by TimeGumLord1** [comment]
what? No i am just adding galacticcraft to my server. Its ok i will just leave it its fine

**Comment by EzerArch** [comment]
> use //set 4307:5

It does work in my 1.7.10 SP. Probably things have changed for 1.10+. :S

**Comment by dj3520** [comment]
@EzerArch well there's more stuff in GC4 so probably
@TimeGumLord1 Guessing you're using the forge version of worldedit then. The bukkit one usually doesn't work with modded stuff.

**Comment by TimeGumLord1** [comment]
oh ok thats probally why then
