### ISSUE TITLE
Compressor will not auto accept items.

### ISSUE THREAD

**Issue by BreeOge** [micdoodle8/Galacticraft#2894]
Minecraft 1.11.2
GalacticraftCore-1.11.2-4.0.0.114
Galacticraft-Planets-1.11.2-4.0.0.114
MicdoodleCore-1.11.2-4.0.0.114
forge-1.11.2-13.20.1.2393

I use Refined Storage for my crafting system, and I can not get it to input the items into the compressor at all.  I even tried to put them into a hopper, the items go into the hopper, but the compressor will not accept any items, I have tried all sides minus the bottom to feed items in by hopper, and it will not work no matter what.  I even tried ExtraUtils2 import and export pipes, no matter what I can not get the items to auto insert.

**Comment by TheQuadShot** [comment]
I can't repro the "vanilla" side of this(same versions as reported). Here's my setup
http://imgur.com/a/SHaiI

On the Refined storage part... I believe that it looks at NBT data and it's not matching so it won't insert.

**Comment by radfast** [comment]
Thanks @TheQuadShot  :)   Though your screenshot shows an Oxygen Compressor, but I think we're talking about an Ingot Compressor here, guess you made it in a hurry :p

OK I just tested this in 1.11.2 and looks like there's a bug with the Electric Compressor hopper inputs.  (Works OK in other Minecraft versions...)

**Comment by TheQuadShot** [comment]
I did both compressors (see second set of images) I didn't try the electric though.

**Comment by radfast** [comment]
I've found the bug, it was introduced in build 110.  We can fix this next build.

**Comment by BreeOge** [comment]
Am I missing a update? I am on 114 and been looking for the fixed one.  Haven't seen anything even on jenkins..

**Comment by radfast** [comment]
Hey @BreeOge 
Sorry the next update has been a while coming, both micdoodle8 and I have been busy IRL.
Build 115 should be released later tonight, maybe 1 hour from time of posting this.
