### ISSUE TITLE
Galacticraft breaks my modpack

### ISSUE THREAD

**Issue by xNifYT** [micdoodle8/Galacticraft#2896]
I created my own modpack i put Galacticraft Core and MicDoodle8 Core in it. When i launch the game it loads up in like 9/10 and it crashes. Without these mods everything works

Minecraft version: 1.10.2
Galacticraft version: 4.0.0.114
Forge version: 12.18.3.2316

All mods in modpack: 
![mods](https://user-images.githubusercontent.com/22347786/28241082-d1d3382e-698d-11e7-8f82-a6fdb6290847.png)

Crash report:
[https://pastebin.com/pPZSuGc7](url)

**Comment by SteveKunG** [comment]
Just increase your RAM to maximum. Example -Xmx6G or whatever you want.

**Comment by radfast** [comment]
Or add FoamFix to the pack.

**Comment by xNifYT** [comment]
Thx...
