### ISSUE TITLE
Fatally missing blocks and items error

### ISSUE THREAD

**Issue by MrcreativeBC** [micdoodle8/Galacticraft#2897]
SMP

Hello! 

Mod Galacticraft conflicts with BuildCraft mod.
When entering the server error appears: "Fatally missing blocks and items"
Client console: `[19:50:22] [Netty Client IO #1/ERROR] [FML/]: Failed to connect to server: there are 4 missing blocks and items
[19:50:22] [Netty Client IO #1/DEBUG] [FML/]: Missing list: [GalacticraftCore:tile.crudeOilStill, GalacticraftCore:tile.fuel, GalacticraftCore:tile.fuel, GalacticraftCore:tile.crudeOilStill]`
Game Version: 1.7.10
Version of the mod Galacticraft: 1.7-3.0.12.501
Version BuildCraft: 7.1.22
forge-1.7.10-10.13.4.1614-1.7.10-universal
Please quick solve this problem!

**Comment by dj3520** [comment]
Try setting these to true in config\Galacticraft\core.conf

    # Set to true to make Galacticraft oil register as oilgc, for backwards compatibility with previously generated worlds.
    B:"Use legacy oilgc fluid registration"=false

    # Set to true to make Galacticraft fuel register as fuelgc, for backwards compatibility with previously generated worlds.
    B:"Use legacy fuelgc fluid registration"=false
