### ISSUE TITLE
cascading worldgen lag when travelling to asteroids

### ISSUE THREAD

**Issue by DragonwrathI** [micdoodle8/Galacticraft#2899]
Minecraft version: 1.11.2
Galacticraft version: 4.0.0.114
Forge version: 13.20.1.2386

Single player

also running ExtraPlanets, Mekanism, Buildcraft and a bunch more

Hard crash when traveling to asteroids, and fml-client-latest shows:

Galacticraft Planets loaded a new chunk (80, 2  Dimension: -30) during chunk population, causing cascading worldgen lag.

Word no longer loadable, but I always back up my save before going interdimensional. Log and crash report attached

[fml-client-latest.txt](https://github.com/micdoodle8/Galacticraft/files/1153731/fml-client-latest.txt)
[crash-2017-07-17_15.10.58-server.txt](https://github.com/micdoodle8/Galacticraft/files/1153734/crash-2017-07-17_15.10.58-server.txt)

**Comment by DragonwrathI** [comment]
Reverted to 4.0.0.106 and the world loaded

**Comment by radfast** [comment]
The cascading worldgen issue is already fixed by https://github.com/micdoodle8/Galacticraft/commit/676e8a16b1b108866807fab4e733c57c9b209aa5 and will be seen in next build 115.

The concurrent modification crash is easily fixed, this will also be in the next build.

**Comment by DragonwrathI** [comment]
Awesome! Thanks for the work you do, this mod is tons of fun!
