### ISSUE TITLE
Crash when launching rocket

### ISSUE THREAD

**Issue by cilerba** [micdoodle8/Galacticraft#2904]
I'm currently, along with everyone else on the server, getting a crash whenever we reach the point during launching our rocket where the map opens.

Minecraft version: 1.11.2
Galacticraft version: 4.0.0.114
Forge version: 13.20.1.2393

Single player (SSP) or Multiplayer (SMP)?
SMP

Galacticraft add-ons and other mods installed?
Aether Legacy 1.0
Extra Utilities Mod
Gravestone
Inventory Tweaks
Just Enough Items
MicdoodleCore
On Further Tales
OptiFine
Pam's Harvestcraft
Roguelike Dungeons
Staffs of Fotia
Stupid Things
TreeCapitator
Wearable Backpacks

Please provide screenshots / crash report / log as needed.
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.11.2-4.0.0.114.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.62+beta.88.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 7/18/17 9:51 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at micdoodle8.mods.galacticraft.core.network.PacketSimple.handleClientSide(PacketSimple.java:303)
	at micdoodle8.mods.galacticraft.core.network.GalacticraftPacketHandler.tick(GalacticraftPacketHandler.java:65)
	at micdoodle8.mods.galacticraft.core.tick.TickHandlerClient.onClientTick(TickHandlerClient.java:639)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_177_TickHandlerClient_onClientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:348)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at micdoodle8.mods.galacticraft.core.network.PacketSimple.handleClientSide(PacketSimple.java:303)
	at micdoodle8.mods.galacticraft.core.network.GalacticraftPacketHandler.tick(GalacticraftPacketHandler.java:65)
	at micdoodle8.mods.galacticraft.core.tick.TickHandlerClient.onClientTick(TickHandlerClient.java:639)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_177_TickHandlerClient_onClientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:348)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['Cilerba'/585702, l='MpServer', x=722.94, y=1205.35, z=193.43]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (776,112,214), Chunk: (at 8,7,6 in 48,13; contains blocks 768,0,208 to 783,255,223), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Level time: 3771907 game time, 82189 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 53 total; [GCEntityClientPlayerMP['Cilerba'/585702, l='MpServer', x=722.94, y=1205.35, z=193.43], EntityBalloon['entity.balloon.name'/132, l='MpServer', x=784.35, y=72.00, z=248.35], EntityPainting['Painting'/57, l='MpServer', x=718.03, y=114.50, z=207.50], EntityCelestialFake['null'/586253, l='MpServer', x=722.94, y=1205.35, z=193.43], EntityPainting['Painting'/59, l='MpServer', x=729.50, y=70.50, z=169.03], EntityPainting['Painting'/61, l='MpServer', x=729.50, y=71.50, z=182.97], EntityPainting['Painting'/62, l='MpServer', x=720.97, y=114.50, z=207.50], EntityPainting['Painting'/527105, l='MpServer', x=762.97, y=107.50, z=225.50], EntityPainting['Painting'/527452, l='MpServer', x=745.03, y=108.00, z=231.50], EntityItemFrame['entity.ItemFrame.name'/66830, l='MpServer', x=762.97, y=107.50, z=227.50], EntityPainting['Painting'/150317, l='MpServer', x=750.03, y=107.50, z=228.00], EntityPainting['Painting'/527277, l='MpServer', x=748.03, y=101.50, z=228.50], EntityPainting['Painting'/505175, l='MpServer', x=762.97, y=107.50, z=233.50], EntityPainting['Painting'/527105, l='MpServer', x=762.97, y=107.50, z=225.50], EntityPainting['Painting'/527278, l='MpServer', x=753.00, y=102.00, z=225.03], EntityPainting['Painting'/527277, l='MpServer', x=748.03, y=101.50, z=228.50], EntityPainting['Painting'/527278, l='MpServer', x=753.00, y=102.00, z=225.03], EntityItemFrame['entity.ItemFrame.name'/68397, l='MpServer', x=757.50, y=107.50, z=219.97], EntityChicken['Chicken'/45, l='MpServer', x=667.84, y=75.00, z=113.80], EntityChicken['Chicken'/46, l='MpServer', x=668.87, y=76.00, z=115.50], EntityPainting['Painting'/150317, l='MpServer', x=750.03, y=107.50, z=228.00], EntityItemFrame['entity.ItemFrame.name'/68398, l='MpServer', x=755.50, y=107.50, z=219.97], EntityPig['Pig'/54, l='MpServer', x=669.43, y=71.00, z=147.26], EntityChicken['Chicken'/55, l='MpServer', x=702.00, y=66.00, z=122.74], EntityPainting['Painting'/57, l='MpServer', x=718.03, y=114.50, z=207.50], EntityPainting['Painting'/59, l='MpServer', x=729.50, y=70.50, z=169.03], EntityItemFrame['entity.ItemFrame.name'/60, l='MpServer', x=731.50, y=71.50, z=169.03], EntityPainting['Painting'/61, l='MpServer', x=729.50, y=71.50, z=182.97], EntityPainting['Painting'/62, l='MpServer', x=720.97, y=114.50, z=207.50], EntityCow['Cow'/63, l='MpServer', x=720.85, y=80.00, z=221.52], EntityTier1Rocket['Tier 1 Rocket'/64, l='MpServer', x=722.50, y=109.40, z=221.50], EntityCow['Cow'/65, l='MpServer', x=725.82, y=75.00, z=260.49], EntityItemFrame['entity.ItemFrame.name'/66624, l='MpServer', x=747.50, y=107.50, z=231.03], EntitySquid['Squid'/587465, l='MpServer', x=697.50, y=60.00, z=228.50], EntitySquid['Squid'/587466, l='MpServer', x=697.50, y=60.00, z=228.50], EntitySquid['Squid'/587467, l='MpServer', x=699.50, y=60.00, z=229.50], EntitySquid['Squid'/587468, l='MpServer', x=698.50, y=60.00, z=231.50], EntityBat['Bat'/587458, l='MpServer', x=670.50, y=29.10, z=144.50], EntityPainting['Painting'/505175, l='MpServer', x=762.97, y=107.50, z=233.50], EntityItemFrame['entity.ItemFrame.name'/66642, l='MpServer', x=745.03, y=107.50, z=233.50], EntityPainting['Painting'/527452, l='MpServer', x=745.03, y=108.00, z=231.50], EntityHorse['Horse'/86, l='MpServer', x=743.12, y=105.00, z=228.00], EntityItemFrame['entity.ItemFrame.name'/92, l='MpServer', x=776.50, y=114.50, z=215.97], EntityItemFrame['entity.ItemFrame.name'/93, l='MpServer', x=775.50, y=114.50, z=215.97], EntityItemFrame['entity.ItemFrame.name'/94, l='MpServer', x=777.50, y=114.50, z=215.97], EntityItemFrame['entity.ItemFrame.name'/95, l='MpServer', x=774.50, y=114.50, z=215.97], EntityItemFrame['entity.ItemFrame.name'/66535, l='MpServer', x=755.50, y=107.50, z=222.03], EntityItemFrame['entity.ItemFrame.name'/66801, l='MpServer', x=762.97, y=107.50, z=223.50], EntityArmorStand['Armor Stand'/521462, l='MpServer', x=754.50, y=100.00, z=227.50], EntityArmorStand['Armor Stand'/487925, l='MpServer', x=754.50, y=100.00, z=226.50], EntityItemFrame['entity.ItemFrame.name'/66559, l='MpServer', x=750.03, y=107.50, z=224.50], EntityCow['Cow'/126, l='MpServer', x=784.92, y=72.00, z=159.39], EntityItemFrame['entity.ItemFrame.name'/66558, l='MpServer', x=757.50, y=107.50, z=222.03]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:401)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 255125664 bytes (243 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.38 Powered by Forge 13.20.1.2393 Optifine OptiFine_1.11.2_HD_U_C3 21 mods loaded, 21 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.1.2393.jar) 
	UCHIJA	forge{13.20.1.2393} [Minecraft Forge] (forge-1.11.2-13.20.1.2393.jar) 
	UCHIJA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCHIJA	aether_legacy{v1.4.1} [Aether Legacy] (aether_legacy-1.11.2-1.0.jar) 
	UCHIJA	extrautils2{1.0} [extrautils2] (Extra-Utilities-Mod-1.11.2.jar) 
	UCHIJA	galacticraftcore{4.0.0} [Galacticraft Core] (GalacticraftCore-1.11.2-4.0.0.114.jar) 
	UCHIJA	galacticraftplanets{4.0.0} [Galacticraft Planets] (Galacticraft-Planets-1.11.2-4.0.0.114.jar) 
	UCHIJA	gravestone{1.7.3} [Gravestone Mod] (Gravestone-1.11.2.jar) 
	UCHIJA	inventorytweaks{1.62+beta.88.22444d0} [Inventory Tweaks] (InventoryTweaks-1.62+beta.88.jar) 
	UCHIJA	jei{4.5.0.287} [Just Enough Items] (jei_1.11.2-4.5.0.287.jar) 
	UCHIJA	onfurthertalesexplorefurther{2.9} [On Further Tales: Explore Further] (On-Further-Tales-1.11.2.jar) 
	UCHIJA	harvestcraft{1.11.2f} [Pam's HarvestCraft] (Pam's HarvestCraft 1.11.2f.jar) 
	UCHIJA	roguelike{1.6.6} [Roguelike Dungeons] (RoguelikeDungeons-1.11.2.jar) 
	UCHIJA	staffoffotiatontheo{1.0.0} [Staff of Fotia ton Theo] (Staffs_of_Fotia_ton_Theo-1.11.2.jar) 
	UCHIJA	stupidthings{1.1} [Stupid Things] (StupidThings-1.11.2.jar) 
	UCHIJA	bspkrscore{at_0.9} [bspkrsCore] (TreeCapitator-Mod-1.11.2.jar) 
	UCHIJA	treecapitator{at_0.9} [Treecapitator] (TreeCapitator-Mod-1.11.2.jar) 
	UCHIJA	wearablebackpacks{2.5.0} [Wearable Backpacks] (WearableBackpacks-1.11.2.jar) 
	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.11.2-4.0.0.114.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.62+beta.88.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.33' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	Launched Version: 1.11.2-forge1.11.2-13.20.1.2393
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.5.0 NVIDIA 382.33, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Default Improved 1.12.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
	OptiFine Version: OptiFine_1.11.2_HD_U_C3
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: BSL-Shaders-All-Versions-Standard.zip
	OpenGlVersion: 4.5.0 NVIDIA 382.33
	OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4`

**Comment by TheQuadShot** [comment]
It looks like you have a dimension conflict, your server admin will need to configure the server. Here's the link to the wiki:
https://wiki.micdoodle8.com/wiki/Galacticraft

**Comment by cilerba** [comment]
I tried removing all of the mods except for Galacticraft Core+Planets, and Micdoodle Core and it still resulted in the same crash. I removed the mods from both the client and the server as well as the config files for all of the removed mods.

**Comment by TheQuadShot** [comment]
iirc... Dimensions are created when the server started the first time. So the dimension conflict still exists, because disabling a mod won't delete the dimension (dim-*xx* folder) that is conflicting. I believe that GC uses (by default) dim-26 -> dim-29, so you need to change the one/s that are conflicting on the server GC config files. It's explained on the wiki.

**Comment by cilerba** [comment]
I probably should have mentioned that whenever I make a change (config changes, mod removals, etc), I delete the old world file and create a new one so there aren't any dim-xx folders whenever I test the mod. A newly generated world with no other mods still reproduces that error. Are the dimensions stored in another file that I'm overlooking? I can't seem to find information on that on the wiki.

**Comment by radfast** [comment]
Always appreciate TheQuadShot's help but I don't think this one is a dimension conflict.

The code that's crashing reads:
>
    FMLClientHandler.instance().getClient().player.getGameProfile().getName()

That's fairly fundamental Minecraft stuff, getting the player name.  I don't know why it's crashing on your game, seems likely to be another mod changed something or maybe a bug in this Forge version.

We'll do some testing and see if we can find an answer.

**Comment by TheQuadShot** [comment]
Sorry, I misread something somewhere. I thought it was a GCCoreUtil.getDimensionID(world) call on the client. I'll set up a proper environment so I don't derp reading code in browser windows again.

**Comment by radfast** [comment]
I'm having trouble reproducing this.  Like I said, it's an issue connected with getting the player name in Minecraft.  One of your other mods is stopping that working properly.

Please can the server owner try this.
1. Backing up the world
2. Start the game with a smaller modlist, and test a rocket launch, until the issue goes away
3. Then let us know which mod makes the difference.

Some of your mods (On Further Tales, Staffs of Fotia, Stupid Things etc) are ones I have not heard of.

**Comment by radfast** [comment]
I still don't know the cause of this :(

It's extremely strange, could be connected with another mod's "fake player" code or somehow a player who did not have a correct Mojang GameProfile.  (Can this happen with client-side hacks or unregistered Minecraft?)

Seems like it only happened one time.

Anyhow, I have updated our code so that if it happens again, it will not crash in this situation - instead there will be loss of functionality, for example the player may not be able to reach some planets in his rocket.
