### ISSUE TITLE
[1.10.2 SMP] Crash while on moon

### ISSUE THREAD

**Issue by ZimsShiz** [micdoodle8/Galacticraft#2907]
Minecraft version: 1.10.2
Galacticraft version: 4.0.0.114
Forge version: 12.18.3.2239

[Crash Report Here](https://gist.github.com/ZimsShiz/144b92c385d19df42b52b7eb24269af0)
This crash happens whenever someone spawns on the moon.

**Comment by dj3520** [comment]
Extracted info from crash log.

Error ticking entity on meteors on impact. 

Modlist, which includes `ExtraPlanets-0.5.6-Beta-Build.jar` and `More-Planets-1.10.2-2.0.7-GC112.jar`

CoFHCore-1.10.2-4.1.9.13-universal.jar
ActuallyAdditions-1.10.2-r105.jar
jei_1.10.2-3.14.7.420.jar
AppleCore-mc1.10.2-2.1.2.jar
AppleSkin-mc1.10.2-1.0.5.jar
appliedenergistics2-rv4-alpha-11.jar
ArchitectureCraft-1.7.1-mc1.10.2.jar
BetterAchievements-1.10.2-0.3.3.10.jar
BiblioCraft[v2.2.1][MC1.10.2].jar
CodeChickenLib-1.10.2-2.5.9.267-universal.jar
BrandonsCore-1.10.2-2.1.8.107-universal.jar
cfm-4.1.2-mc1.10.2.jar
Chisel-MC1.10.2-0.0.11.26.jar
CodeChickenCore-1.10.2-2.4.1.102-universal.jar
Draconic-Evolution-1.10.2-2.1.1.236-universal.jar
EnderCore-1.10.2-0.4.1.66-beta.jar
EnderIO-1.10.2-3.1.193.jar
EnderStorage-1.10.2-2.2.1.106-universal.jar
valkyrielib-1.10.2-0.10.6.jar
environmentaltech-1.10.2-0.10.6b.jar
industrialcraft-2-2.6.234-ex110.jar
GalacticraftCore-1.10.2-4.0.0.114.jar
Galacticraft-Planets-1.10.2-4.0.0.114.jar
ExtraPlanets-0.5.6-Beta-Build.jar
zerocore-1.10.2-0.1.0.6.jar
ExtremeReactors-1.10.2-0.4.5.30.jar
flatcoloredblocks-mc1.10-v4.4.jar
Mantle-1.10.2-1.1.5.jar
TConstruct-1.10.2-2.6.5.jar
theoneprobe-1.1x-1.4.7.jar
ImmersiveEngineering-0.10-61.jar
immersivepetroleum-1.10.2-1.0.7.jar
IronBackpacks-1.10.2-2.2.27.jar
ironchest-1.10.2-7.0.15.804.jar
malisiscore-1.10.2-4.4.0.jar
malisisdoors-1.10.2-5.2.0.jar
MCMultiPart-experimental-2.0.0_88-universal.jar
Mekanism-1.10.2-9.2.2.301.jar
MekanismGenerators-1.10.2-9.2.2.301.jar
MekanismTools-1.10.2-9.2.2.301.jar
MercuriusUpdater-1.10.2.jar
MobGrindingUtils-0.1.8.21.jar
ModularPowersuits-1.10.2-1.2.124.jar
More-Planets-1.10.2-2.0.7-GC112.jar
MorePlayerModels_1.10.2(11nov16).jar
Ore Core 1.10.2 (v.1.3.3).jar
ThermalFoundation-1.10.2-2.1.4.8-universal.jar
plustic-5.1.2.0.jar
ProjectE-1.10.2-PE1.3.1.jar
ThermalExpansion-1.10.2-5.1.8.16-universal.jar
ThermalDynamics-1.10.2-2.0.9.12-universal.jar
tinker_io-1.10.2-release 2.4.4.jar
TinkerToolLeveling-1.10.2-1.0.1.jar
topaddons-1.10.2-0.14.1.jar

**Comment by ZimsShiz** [comment]
Okay?
