### ISSUE TITLE
Cryogenic Chamber not changing time

### ISSUE THREAD

**Issue by CreeperDust** [micdoodle8/Galacticraft#2909]
Minecraft version: 1.8.9
Galacticraft version: 4.0.0.114
Forge version: 11.15.1.1902

World Type: SSP

Additional Mods: Voxelmap, Inventory Tweaks, Just Enough Items

I have noticed this only on Mars so far, as I have not tested the Cryogentic Chamber on my survival world on the Moon. When I used the cryo chamber at first, it changed the time to the next morning, but after about 3 uses, it stopped doing anything at all.

Edit: Just realized I have an outdated version of the mod (4.0.0.111). Updated it, and it still doesn't work.

**Comment by marcus8448** [comment]
I am quite sure that the Cryogentic Chamber is not supposed to change the time. I think it is just to restore health by a bit.

**Comment by dj3520** [comment]
@marcus8448 in 1.7.10 it does change time similar to a bed

**Comment by EzerArch** [comment]
> in 1.7.10 it does change time similar to a bed

In my 1.7.10 game, CryoChamber advances the time to the next 2nd sunrise. Too much? o.O'

**Comment by CreeperDust** [comment]
I have noticed that if i travel between dimensions and use the cryochamber, it works like once, then it stops working after that. Doesn't advance time at all.

**Comment by CreeperDust** [comment]
Now I'm using version 4.0.0.117 and the bug is still here. It also happens on multiplayer servers.

**Comment by radfast** [comment]
I think this issue is fixed from build 4.0.1.165.

If anyone thinks there's still a problem with the Cryogenic Chamber in build 165, please give details.

**Comment by TheQuadShot** [comment]
Ok, I just tested this on 1.12.2 with build .165, no matter what time I use the chamber the time advances to 0:00. I did only test on/in the overworld. Hope that helps

**Comment by radfast** [comment]
thank you for testing, guess this isn't fixed then :(

**Comment by radfast** [comment]
@TheQuadShot  I'm not seeing this, testing 165 on the Overworld.  Time advanced to dawn the next day.

(I'm able to use the chamber at any time of day.)

**Comment by TheQuadShot** [comment]
I thought it was working(till your post), maybe I just reported it incorrectly, sorry for that. I based my time on what Journey Map HUD displays, and I just assumed that 0:00 was dawn. btw  I did expect to be able to sleep at anytime, (just a test case I did)

**Comment by radfast** [comment]
There is a current issue, which is that (on the Overworld), it is advancing to next morning + 1, not next morning.

I'm looking at this right now, will probably make a build 166 soon.

**Comment by radfast** [comment]
OK all seems good in my testing in build 166.

**Comment by QuantumStatement** [comment]
Minecraft 1.11.2
Galacticraft 4.0.1.166
Singleplayer

Before using a Cryogenic Chamber
![2018-03-25_10 51 27](https://user-images.githubusercontent.com/35406698/37872998-119872bc-301c-11e8-97ca-faedc25f1b74.png)

After using a Cryogenic Chamber
![2018-03-25_10 51 39](https://user-images.githubusercontent.com/35406698/37873004-1a987542-301c-11e8-8bc2-46f96d96e805.png)

After returning to the Overworld
![2018-03-25_10 52 07](https://user-images.githubusercontent.com/35406698/37873008-23ed4d20-301c-11e8-860c-56d81a1ad4fc.png)

Also Cryogenic Chamber skip 2 days on Space Station

**Comment by radfast** [comment]
The behaviour in the screenshots is intended ... that is **exactly** how Cryogenic Chamber is supposed to work!!!   ("Dawn" on the Moon is the start of Day 8.  Time changes due to sleeping on the Moon are completely independent from time changes due to sleeping on the Overworld, so the Overworld is still on Day 0.)

In future this will also allow us to have planets whose day length is not a multiple of 24000 ticks.

**Note that using the `/time set xxxx` command will set the time on all dimensions, so dimensions will be back in sync after using a "time set" command.  `/time add xxxx` should not have this resyncing effect.**

The skip 2 days on a Space Station is a bug :(  thanks I'll take a look.
