### ISSUE TITLE
Crafting issue with Filled Canister of Liquid Oxygen disappear when used to refill heavy Oxygen tank

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft#2910]
I think its just best to include this link as theres enough information there to report the bug and for anyone to see whats going on

https://github.com/MJRLegends/Space-Astronomy-2-Feedback-/issues/54

MC: 1.10.2
Galacticraft: Build 114

I also tested in with just GC outside of my mod pack and same happens :D

**Comment by radfast** [comment]
will be fixed in 115, thanks for reporting

**Comment by MJRLegends** [comment]
@radfast No problem, thanks for fixing :D
