### ISSUE TITLE
Recipe Server Error with Open Computers

### ISSUE THREAD

**Issue by chezpaul** [micdoodle8/Galacticraft#2915]
Seems like Galacticraft and Open Computer use the same recipe for something? Not sure.
Minecraft version: 1.10.2 
Galacticraft version: 1.10.2-4.0.0.114
Forge version: 12.18.3.2316

Single player (SSP) or Multiplayer (SMP)? SMP

Galacticraft add-ons and other mods installed? No Add ons

Mods used: appliedenergistics2-core, ivtoolkit, Micdoodlecore, NotEnoughItems, OpenComputers|Core, <CoFH ASM>, ae2stuff, animania, appliedenergistics2, arsmagica2, AnimationAPI, Baubles, bdlib, bedbugs, BiblioCraft, biomebundle, BiomesOPlenty, bookshelf, Botania, bottledmilk, cfm, Chameleon, ChickenChunks, chisel, CodeChickenCore, CodeChickenLib, ccl-entityhook, cofhcore, PTRModelLib, props, eplus, endercore, EnderIO, EnderStorage, EnderZoo, energyconverters, extrautils2, FinderCompass, fluxnetworks, forestry, microblockcbe, forgemultipartcbe, minecraftmultipartcbe, galacticraftplanets, galacticraftcore, gendustry, geographicraft, GraveStone, hammercore, Waila, immersiveengineering, imc, IC2, ironbackpacks, ironchest, JEI, jeibees, malisiscore, malisisdoors, mantle, mcmultipart, Mekanism, MekanismGenerators, MekanismTools, mercurius_updater, testdummy, Morpheus, MrTJPCoreMod, mysticalagriculture, natura, neid, notenoughwands, OpenComputers, openterraingenerator, p455w0rdslib, getalltheseeds, harvestcraft, plustic, pressure, projectred-core, projectred-integration, projectred-transmission, projectred-illumination, projectred-expansion, projectred-transportation, railcraft, reccomplex, redstonearsenal, roguelike, simplecorn, solarfluxreborn, sonarcore, special_ai, StorageDrawers, tconstruct, thermaldynamics, thermalexpansion, thermalfoundation, Translocator, unidict, wailaplugins, wanionlib, weaponcaseloot, wct, worldcontrol, worldedit, wrcbe, xtones

Crash Report: https://pastebin.com/7bARXhgt

**Comment by dj3520** [comment]
OpenComputers is trying to use 'GalacticraftCore:item.sensorLens' in one of it's recipes. Not sure why since I don't get this error myself with 1.11.2

**Comment by xarses** [comment]
Sensor lens would be used on the world sensor http://ocdoc.cil.li/item:world_sensor_upgrade

**Comment by MJRLegends** [comment]
Put this in the "user.recipes" file in "/config/opencomputer/" https://pastebin.com/YwhS5xtY

**Comment by radfast** [comment]
Thanks @MJRLegends 

This is an error in the OC Integration module, I have notified them and made a [pull request](https://github.com/MightyPirates/OpenComputers/pull/2474) so they can easily fix it.

Any further issues please raise with the OC team.

**Comment by chezpaul** [comment]
FYI, this error still happens even after using the user.recipes fix offered above.
