### ISSUE TITLE
Crash Upon Entering Singleplayer World

### ISSUE THREAD

**Issue by LukaPix** [micdoodle8/Galacticraft#2916]
Game crashes upon entering a world
I have addons and Optifine installed but it says Galacticraft Core in the crash report.

Minecraft version: 1.11.2
Galacticraft version: 4.0.0.114
Forge version: 13.20.1.2421

Singleplayer

GC Addons:
-Space Advanced 2
-ExtraPlanets
Other Mods:
-ActuallyAdditions
-AetherLegacy
-AppliedLlamagistics
-AutoRegLib
-Avaritia
-BaseMetals
-BaseMinerals
-Baubles
-bdlib
-BigBattery
-BiomesOPlenty
-BlockDrops
-Botania
-BrandonsCore
-Chisel
-ChunkAnimator
-CodeChickenLib
-CoFHCore
-CommonCapabilities
-CompatLayer
-CraftTweaker
-CyclopsCore
-Decocraft 2
-DenseOres
-DraconicEvolution
-DynamicSurroundings
-ElecCore
-EndMetals
-ExtraUtils2
-ExtremeReactors
-FancyBlockParticles
-Forestry
-Futurepack
-Gendustry
-AdvancedGenerators
-GuideAPI
-HammerCore
-ImmersiveEngineering
-IndustrialForegoing
-IntegratedDynamics
-IntegratedTunnels
-InventoryX
-ItemZoom
-JEI
-JustEnoughResources
-LostThaumaturgy
-Mantle
-mcjtylib
-Mekanism
-MekanismGenerators
-MekanismTools
-MetallicCrops
-MinetweakerRecipeMaker
-ModernMetals
-morePlates
-NetherMetals
-NuclearCraft
-OpenComputers
-Optifine
-OreSpawn
-placementpreview
-ProjectE
-Psi
-RebornCore
-RedstoneArsenal
-RefinedStorage
-RFTools
-RFToolsControl
-RFToolsDimensions
-StevesCarts 2
-TConstruct
-TechReborn
-Tesla
-TheOneProbe
-ThermalDynamics
-ThermalExpansions
-ThermalFoundation
-Traverse
-XNet
-XTones
-ZeroCore

Full FML Log :[https://1drv.ms/t/s!An8Z2izmI8NLgpJc4udyrl5dUkSefA]( https://1drv.ms/t/s!An8Z2izmI8NLgpJc4udyrl5dUkSefA)

**Comment by dj3520** [comment]
check config for astralsorcery

**Comment by MJRLegends** [comment]
Reset your astralsorcery config (delete it and let it regenerate)

**Comment by radfast** [comment]
Looks like a coding error in AstralSorcery, they have used a Scala "Array" as the import when they meant to import the Java "Array".  Please report to them, not us.  This is not a Galacticraft issue, even though it happened during our dimension registration.

**Comment by radfast** [comment]
This is fixed in AstralSorcery in versions since May 3, 2017
