### ISSUE TITLE
I can go to high tier planets with low tier rockets

### ISSUE THREAD

**Issue by traso56** [micdoodle8/Galacticraft#2917]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version:1.7.10
Galacticraft version:1.7-3.0.12.501
Forge version:1614

Single player (SSP) or Multiplayer (SMP)?
SMP

i created my first rocket a tier I rocket and in the galaxy map i clicked launch to mercury just for fun but it actually launched me there and i was getting hurt of solar radiation

it was a friends lan server so i used creative to gather everyting and actually go to the moon
Galacticraft add-ons and other mods installed?

Please provide screenshots / crash report / log as needed.

**Comment by radfast** [comment]
Mercury is not in Galacticraft.  This is an issue with the add-on, maybe you are using Extra Planets or MorePlanets?

**Comment by traso56** [comment]
oh i was thinking mercury is the tier 3 planet but it's venus i will try with venus to see what happens and report it in galaxyspace
