### ISSUE TITLE
Minecraft closes/crashes when I go from a pad to an overworld one.

### ISSUE THREAD

**Issue by Ulisse54** [micdoodle8/Galacticraft#2918]
Hi. I'm not really sure it this would happen for any other pad in any other planet as I haven't had a chance to test. I have a space station where which has launch control frequency of 541. The overworld pad has a frequency of 540, when the landing process is about to be complete minecraft simply closes.  The problem is that if you try to log back in it'll first have a lot of FPS lag, but you'll see how you're out of the rocket. Rocket particles are still there though. ..then everything will disappear and the screen will turn light blue, pretty much the same color as the skybox, then it will close down, everytime you try to log in the same world.
latest,log file:
[latest.zip](https://github.com/micdoodle8/Galacticraft/files/1179329/latest.zip)

**Comment by radfast** [comment]
The log you have sent shows 2 errors, one in **Malisis Doors**, one in **Pam's HarvestCraft**/**Xaero Map**.  Looks like Malisis Doors is causing the crash, and the rest is just a consequence of the crash.

Galacticraft is not the cause of this.

Galacticraft is just moving you from one place to another place (the same way that a Nether Portal can do that), and when you arrive at the destination, the Minecraft game is loading blocks from Malisis Doors and from Pam's HarvestCraft, and somehow one of those mods is crashing - look at Malisis Doors first.

We can't help you any more with this, ask Malisis Doors developers for help.
