### ISSUE TITLE
Server crashes when creating worlds (Sponge/1.10.2)

### ISSUE THREAD

**Issue by DeltaVetal26** [micdoodle8/Galacticraft#2919]
Good day! I have
Sponge server on 1.10.2, I install GalacticCraft and when I run a clean server I get crash (the crashlog is attached below). Checked on different versions of forge and sponge - the problem is the same.
Versions, on which he checked:
========
- forge-1.10.2-12.18.3.2316-universal
- spongeforge-1.10.2-2281-5.2.0-BETA-2464
- GalacticraftCore-1.10.2-4.0.0.114
- Galacticraft-Planets-1.10.2-4.0.0.114
- MicdoodleCore-1.10.2-4.0.0.114
- More-Planets-1.10.2-2.0.8-GC114
========
- forge-1.10.2-12.18.3.2254-universal
- spongeforge-1.10.2-2254-5.2.0-BETA-2254
- GalacticraftCore-1.10.2-4.0.0.114
- Galacticraft-Planets-1.10.2-4.0.0.114
- MicdoodleCore-1.10.2-4.0.0.114
- More-Planets-1.10.2-2.0.8-GC114
========
Unfortunately, because of this the server is idle (the players are waiting for its prompt launch! Thank you in advance for your help!
[crash-2017-07-28_10.12.23-server.txt](https://github.com/micdoodle8/Galacticraft/files/1181960/crash-2017-07-28_10.12.23-server.txt)

**Comment by TheQuadShot** [comment]
Did you configure the server as per https://wiki.micdoodle8.com/wiki/Sponge ?
It mentions this issue specifically.

**Comment by radfast** [comment]
Thank you TheQuadShot :)

@DeltaVetal26 pls read the documentation
