### ISSUE TITLE
[1.7.10] Rednet Energy Crash

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft#2920]
**Minecraft version:** 1.7.10
**Galacticraft version:** Build 501
**Forge version:** 10.13.4.1614

**MinefactoryReloaded:** v2.8.1-174
**Cofh Core:** v3.1.4-329
**RedstoneArsenal:** v1.1.3-97

**Information:** 
So when placing a Rednet Energy Cable next to a oxygen collector at the energy input side of the machine it, see below for crash log

**Crash Log:** https://pastebin.com/kihetQGw

![](https://i.gyazo.com/4f9ffc055a4f420d134dc2ae53ac8b13.png)

**Comment by MJRLegends** [comment]
Update: Seems to crash on every Galacticraft machine with the rednet cable

**Comment by MJRLegends** [comment]
Config fix: 

1. Open "\config\powercrystals\minefactoryreloaded\common.cfg"
2. Go down to where it says "A list of block IDs to prevent RedNet cables from connecting to. (e.g., minecraft:torch)"
3. Replace the blacklist with the following https://pastebin.com/wiy7vuy5

Should look like this 
![](https://i.gyazo.com/5a934266d3a9f2a3e7f591f0074ca9d8.png)

**Comment by radfast** [comment]
Thanks

It's because RedNet is trying to extract energy from a machine that doesn't produce energy (and is marked as a receiver, not an energy provider).  Not sure why they want to do that, but we can work around this in build 502.

**Comment by MJRLegends** [comment]
Thanks for fixing this issue amazing work, any chance you could set Jenkins to build another build for 1.7.10 for this @radfast

**Comment by radfast** [comment]
Done.  Build 502 should be ready now.

**Comment by MJRLegends** [comment]
@radfast Thanks mate :D any chance you could update the mekanism api for 1.10.2 as just about to update my packs and im getting this issue due to the out of date mekanism api https://github.com/MJRLegends/Space-Astronomy-2-Feedback-/issues/63

Sorry to seem pushy just having a stressful time with crash bugs with many of mods and trying to push for fixes ASAP :D
