### ISSUE TITLE
Fluid Tank Bug (1.11.2) (SSP)

### ISSUE THREAD

**Issue by TheAmazingBC** [micdoodle8/Galacticraft#2923]
Minecraft version: 1.11.2
Galacticraft version: 1.11.2
Forge version: 1.11.2

Mods:
Buildcraft 1.11.2
JEI (Just Enough Items) 1.11.2
Computality 1.11.2
**_Fidget Spinner Mod_** 1.11.2 (What a Funny meme haHA)
Optifine 1.11.2
Treecapitator 1.11.2
TNT-mod 1.11.2
Xaeros Minimap 1.11.2

Sorry about my crappy computer

![ezgif com-gif-maker](https://user-images.githubusercontent.com/30563545/28750663-7dfe471a-74bf-11e7-92e2-dd03e0107285.gif)
![ba5](https://user-images.githubusercontent.com/30563545/28750665-8594d548-74bf-11e7-960b-7d6fdab1ffd4.png)

**Comment by dj3520** [comment]
Guessing you're clicking on the tank with an empty canister and it's disappearing. Does this happen with all tanks or just empty ones?

**Comment by TheAmazingBC** [comment]
I haven't tested this on the other cans yet but ill be back with new info

**Comment by 7M351** [comment]
Not just SSP problem. Tanks are also buggy with stacks of buckets and fluids without an associated canister item (like liquid argon).

**Comment by radfast** [comment]
Next build 135 fixes the following issues:

1.  Clicking on empty Fluid Tank with empty Canister "eats" the Canister

2.  Clicking on Fluid Tank filled with non-canister fluid (like liquid argon) "eats" the Canister

3.  Clicking on Fluid Tank with a stack of empty buckets eats the whole bucket stack and returns only one filled bucket

Thank you for reporting.  All these should now be correct in 1.11.2 and 1.12.2 (and these were not problems which existed in 1.10.2 and earlier).  

At the same time - for Galacticraft tanks at least - I've fixed a Forge bug which could insert filled buckets to your armor slots if all other inventory slots were full.  (That one also existed in 1.10.2.)
