### ISSUE TITLE
Can't craft (2) Batteries (Galacticraft Batteries) in AE2 Crafting

### ISSUE THREAD

**Issue by chezpaul** [micdoodle8/Galacticraft#2925]
Minecraft version: 1.10.2
Galacticraft version: 1.10.2-4.0.0.114
Forge version: 12.18.3.2316

Single player (SSP) or Multiplayer (SMP)? Multiplayer

Mods used: appliedenergistics2-core, ivtoolkit, Micdoodlecore, NotEnoughItems, OpenComputers|Core, , ae2stuff, animania, appliedenergistics2, arsmagica2, AnimationAPI, Baubles, bdlib, bedbugs, BiblioCraft, biomebundle, BiomesOPlenty, bookshelf, Botania, bottledmilk, cfm, Chameleon, ChickenChunks, chisel, CodeChickenCore, CodeChickenLib, ccl-entityhook, cofhcore, PTRModelLib, props, eplus, endercore, EnderIO, EnderStorage, EnderZoo, energyconverters, extrautils2, FinderCompass, fluxnetworks, forestry, microblockcbe, forgemultipartcbe, minecraftmultipartcbe, galacticraftplanets, galacticraftcore, gendustry, geographicraft, GraveStone, hammercore, Waila, immersiveengineering, imc, IC2, ironbackpacks, ironchest, JEI, jeibees, malisiscore, malisisdoors, mantle, mcmultipart, Mekanism, MekanismGenerators, MekanismTools, mercurius_updater, testdummy, Morpheus, MrTJPCoreMod, mysticalagriculture, natura, neid, notenoughwands, OpenComputers, openterraingenerator, p455w0rdslib, getalltheseeds, harvestcraft, plustic, pressure, projectred-core, projectred-integration, projectred-transmission, projectred-illumination, projectred-expansion, projectred-transportation, railcraft, reccomplex, redstonearsenal, roguelike, simplecorn, solarfluxreborn, sonarcore, special_ai, StorageDrawers, tconstruct, thermaldynamics, thermalexpansion, thermalfoundation, Translocator, unidict, wailaplugins, wanionlib, weaponcaseloot, wct, worldcontrol, worldedit, wrcbe, xtones

I can't pick up the (2) batteries when I select the recipe from JEI into my AE2 crafting terminal.
(Made from one coal, one red stone and 5 compressed Tin)
I do see the (2) batteries but I can't grab them.
I'm pretty much able to craft everything else I've tried so far which is a lot of Galacticraft stuff.

On a side note. The electric compressor will sometimes (50% of the time) crawl down my server to 1 fps. I take ingots out and it works fine, put them bac in, back to a crawl.

Thanks

**Comment by radfast** [comment]
1. can AE2 crafting make other recipes which have 2 ouputs, for example Tin Canister?

2. Electric Compressor issue: does it happen in a new world with a standalone Electric Compressor (maybe put an Infinite Battery in it to power it) or is it the other things you have built around it creating the 1fps lag?  Could also be the power systems, like it draws some power when it's working.  Please try a few things out and give us more info and maybe screenshots.

**Comment by chezpaul** [comment]
1. Yes I can craft (2) Tin Canister fine in AE2.
I dug in further and I can craft the (2) batteries in a regular crafting table. That works fine. So it's only in the AE2 crafting Terminal that it doesn't work. 
I can add the batteries in my inventory in AE2 once they are crafted. And take them out.
I tried to craft a storage module out of them but I was not able to as they charged while in my inventory (Ender wireless charging) and it seems like the recipe doesn't work for the storage module with charged batteries!! I didn't have time to check further.

2. I've just updated to v115 of Galacticraft and it seems like that might have fixed the issue. No more lag. Power system was with tons of power.

Thanks

**Comment by radfast** [comment]
ok, thanks for confirming on (2).  There weren't that many changes in v115 but we did fix one automation issue with the Electric Compressor so maybe that was causing the lag.

Storage module recipe needs uncharged batteries.  Can you disable your wireless charging?

I will investigate the AE2 problem but could be the issue is their side not our side.  Meanwhile you can maybe try using our **Magnetic Crafting Table**, it's like a regular Crafting Table except you can automate it using hoppers.

**Comment by radfast** [comment]
fixed next build 152, for anyone who is monitoring this
