### ISSUE TITLE
TileEntities, Redstone etc not updating on a Moon Base

### ISSUE THREAD

**Issue by Mooglemuffins** [micdoodle8/Galacticraft#2926]
Minecraft version: 1.11.2
Galacticraft version:  4.0.0
Forge version: 13.20.1.2386

Single player (SSP) or Multiplayer (SMP)? SMP

Galacticraft add-ons and other mods installed? Galacticraft Planets. Other mods installed include:

Open Terrain Generator
Biome Bundle
Blood Magic: Alchemical Wizardry
Embers
Just Enough Items/Too Many Items
Journeymap
Mantle
Soul Shards
Tinkers Construct
Thermal Foundation/Dynamics/Expansion
Treecapitator

Please provide screenshots / crash report / log as needed.

Few friends and I are running a custom modpack with the above listed mods. Things were going well until I got everything put together and launched off to go to the moon. Everything went normally with that until I landed on the moon and tried to start building a base. If I put anything redstone controlled down, like a pressure plate or a button it would get stuck in 'depressed' mode and not send any signal. Chests placed on the moon would not open. Multi-block structures like the launch pad would not combine into the launch pad when I place all 9 pieces down. Lastly any blocks I placed, would disappear if I logged off. (but my air would still be going down without any change). Basically I was stuck with no way to build anything or relaunch to get home since the launch pad would not function and the solar panel would not extend out to its structure if placed to even provide power. Anyone else run into this?

**Comment by radfast** [comment]
Please provide the **server log** from the game session when these problems happened.

(If you've been playing since it happened, could be like ```fml-server-3.log``` or something like that, check your logs folder and look at the times of the files there.)

Please keep an open mind: just because it happened "on the Moon", Galacticraft may not be the cause of this, could be something else you built in your Moon base made these issues start happening...

**Comment by Mooglemuffins** [comment]
> Please provide the server log from the game session when these problems happened.

I'll check with my friend who is running the server to try to get that for you!

> could be something else you built in your Moon base made these issues start happening...

There is literally nothing on the Moon yet, this was occurring from the moment I landed for the first time. The only thing on that planet that wasn't there to begin with is my lander. Everything else disappears.

Interestingly, the space station dimension works. It is just the planets that do not.

**Comment by radfast** [comment]
You can track the progress of the Sponge bug [here](https://github.com/SpongePowered/SpongeForge/issues/1552)

**Comment by Mooglemuffins** [comment]
Thanks for that info, here's the server log I was able to get from him in case you want to look. 
[serverlog.txt](https://github.com/micdoodle8/Galacticraft/files/1189263/serverlog.txt)

**Comment by radfast** [comment]
Thanks, and well done for spotting that it's the Terrain Control issue.  Your friend should update to the suggested version of Terrain Control.

(Your friend's server is not a Sponge server, sorry for that diversion!)

**Comment by Mooglemuffins** [comment]
Thanks! I'll let him know the good news.
