### ISSUE TITLE
[1.10.2] Galacticraft4 build 112 Standard Wrench doesn't rotate inputs and outputs of several machines

### ISSUE THREAD

**Issue by mcdodge34** [micdoodle8/Galacticraft#2928]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.10.2
Galacticraft version: GC4 b112
Forge version: 12.18.3.2316

Single player (SSP) or Multiplayer (SMP) : SMP on my own private server

Galacticraft add-ons and other mods installed : More planets version for GC4 b112, and for other mods, there's too many of them to list base pack is Foolcraft pack with FTB Beyond mods except for IC2 and TechReborn and I also added Advanced Rocketry.

Please provide screenshots / crash report / log as needed.

Don't think its relevant here, the wrench doesn't do its job and my OCD is killing me, I wanted to give this awesome mod a second chance, but the messy cables and input and outputs of the machines still drives me crazy.

**Comment by radfast** [comment]
Please read the documentation.  https://wiki.micdoodle8.com/wiki/Galacticraft_4

More configurable machines will be added over time, but there is currently no bug, and all the most common machines are covered.  I do not agree with you that Galacticraft inputs and outputs are "messy".

**Comment by mcdodge34** [comment]
The documentation about the wrench says we can, and for theses blocks (electric compressor and circuit fabircator, we can't, that or my sneak doesn't work with this wrench while it works for every other sneak functions of all the other mods, Could I suspect Better Sprinting to be affecting the sneak ability to work with this wrench maybe, I know it can cause some problems ???

**Comment by radfast** [comment]
Can you try making a /mods folder and world without Better Sprinting?

**Comment by mcdodge34** [comment]
Will do this. But I remember now there's something about a player api involved, that I never installed on this one I know it caused me some problems back in 1.6.4 if I remember my last adventures with Galacticraft, I had problems until I installed or uninstalled that player api thingy

**Comment by radfast** [comment]
Issues you had with 1.6.4 are not likely to arise with 1.10.2 version, there's been ~2 years of development since then.

Galacticraft recent versions can be used with PlayerAPI or without PlayerAPI, it's your choice.  PlayerAPI can help compatibility with a few other mods, we don't have a current list.

**Comment by mcdodge34** [comment]
After testing stuff with and without better sprinting, using Galacticraft 112 (cause I have More Planets 112), the only block I can reliably change the side of the power input is the electric arc furnace, all the others don't do anything at all like if something else wasn't right. Would love to switch the power input of most blocks under them, but its not possible even with the electric arc furnace we can only move it to either sides.

**Comment by TheQuadShot** [comment]
This may just be me and I'm not interpreting this incorrectly... You Rotate the block with the wrench, you aren't really "changing" which side is in/out. Try putting the machines with yellow warning tape on the bottom, onto a wired walkway, iirc it should power the machine from the bottom.

**Comment by mcdodge34** [comment]
I could do a small video if you wish this evening (GMT-5 time zone) I tried in my real world with better sprinting, and the only block I can rotate the inputs is the electrical arc furnace, the others just rotate the block itself and nothing else.

**Comment by radfast** [comment]
From the report it's difficult to understand whether it's a bug in Galacticraft, a mod conflict, a usage error or the mod is just not matching your expectation.

Please do the following tests, all with latest (116) Galacticraft build:

1.  New world, Galacticraft only (no other mods)

2.  New world, Galacticraft + Better Sprinting

3.  New world, full mod list

For each one please test the machines listed and let us know if the sides do **not** rotate with Sneak+Wrench.

The list of machines which should rotate sides currently - in build 116 - are:

Electric Furnace
Electric Arc Furnace
Energy Storage Module
Energy Storage Cluster
Electric Ingot Compressor
Circuit Fabricator
Oxygen Storage Module
Fuel Loader
Deconstructor

**Comment by mcdodge34** [comment]
Now, I understand, I'm going to assume now that everything works right as intended and there's no bug anymore. The electric compressor isn't in the list and all the blocks I tried in my survival modded world aren't in the list except the electric arc furnace. So that would explain why I couldn't rotate them.

**Comment by EzerArch** [comment]
Tested on MC1.10.2, Forge 2316, GC 116: I can *shift+wrench* both Electric Compressor and Circuit Fabricator to rotate their faces individually. 

![2017-08-07_16 49 34](https://user-images.githubusercontent.com/6743303/29043656-6da43f6c-7b92-11e7-9844-8e34f85b3d75.png)

I did the same test in 112: the machines cannot be shift-rotated properly. The all 4 sides rotate together. Probably [GC 113 (see 6)](https://ci.micdoodle8.com/job/Galacticraft-1.10/113/changes) fixed it.

_Side note:_ The [YouTube comment box](https://www.youtube.com/watch?v=4zaS3RlcHEM&lc=z12lhh5x5xngfxh5i04chxugmwm5ebvpaho) is not the best place to request help or report a bug. The primary place where the developers (and I) look at for bug report is this GitHub repo. I can't guarantee I'll reply every video comment on daily base.

**Comment by radfast** [comment]
Thanks @EzerArch  :)

Seems like the issue here is @mcdodge34 not using the latest version.  Guidelines say test in the **latest** version.

**Comment by mcdodge34** [comment]
Yup, I agree, still waiting for a new version of More Planets to get the latest GC 116 in my pack, I saw an update for GC 114, would I get any benefits moving from 112 to 114, or I'm better waiting for a version for 116 before upgrading, I'm always concerned that any extra addon need the exact version it was compiled for or I'm good with a version made for 114 and using latest version of GC with it ???
