### ISSUE TITLE
IC2 Cable and GC "Sealable Cable" blocks not connecting.

### ISSUE THREAD

**Issue by stoptt3** [micdoodle8/Galacticraft#2929]
Minecraft version:  1.10.2
Galacticraft version:  4.0.0.115
Forge version:  12.18.3.2185

Single player (SSP) or Multiplayer (SMP)?
SSP

Galacticraft add-ons and other mods installed?
GC Planets, IC2 version 2.6.252-ex110

Screenshot of compatibility error
![2017-07-31_18 30 09](https://user-images.githubusercontent.com/30608203/28802863-5e66a2c0-761e-11e7-9043-fde07d283694.png)
The Galacticraft "Sealable Cable" blocks will not connect to their intended IC2 counterpart cables.
From left to right:  Copper Cable, Gold Cable, HV Cable, Glass Fiber Cable, and Tin Cable

**Comment by radfast** [comment]
Which IC2 version?

**Comment by stoptt3** [comment]
IC2 version 2.6.252-ex110

**Comment by radfast** [comment]
Thanks, looks like IC2 changed how things work internally, again.

This is fixed from next GC build update.
