### ISSUE TITLE
Asteroids Abandoned Base worldgen crash - no asteroid data

### ISSUE THREAD

**Issue by border999** [micdoodle8/Galacticraft#2931]
Minecraft version: 1.10.2
Galacticraft version: 1.10.2-4.0.0.115
Galacticraft Planets version:1.10.2-4.0.0.115
Forge version: 1.10.2-forge1.10.2-12.18.3.2422

Single player (SSP) or Multiplayer (SMP)? Single Player

Galacticraft add-ons and other mods installed? Yes

Please provide screenshots / crash report / log as needed.
https://pastebin.com/0y7SFXfT

**Comment by border999** [comment]
Thank you for the more appropriate labeling.

**Comment by radfast** [comment]
YW!  It's actually to help us, so the devs know which issue is which ...

**Comment by border999** [comment]
Sorry that it's only a striped down log. There was almost 2MB's to sift through and the game wouldn't actually kick out a crash log for me.
Pastebin only let's me paste things up to a file size of 512kb.

**Comment by radfast** [comment]
Did anything strange in the history of this world, like an earlier crash, deletion of dimensions, or you added mods after starting the world?

Do you get the same crash:
1) if you create a new world and use ```/dimensiontp``` to go to the Asteroids?
2) if you copy/backup the existing world and try playing it with **only Galacticraft installed**?

For the problem world, please also check the ```/data``` folder in the world save folder for a file named ```GCAsteroidData.dat``` and post that file up for us to look at.

**Comment by radfast** [comment]
Note to other devs: the cause of the crash is ```WorldProviderAsteroids.getClosestAsteroidXZ()``` is returning null, that shouldn't be possible in a normally generated Asteroids dimension.

**Comment by border999** [comment]
Currently testing all recommended iterations.
Backup world with only the three galacticraft mods (Micdoodle, Core, and Planets) soft crash occurs when you attempt to enter the asteroids dimension.
Freshly started world with only those mods. Perfectly working.
Now testing with all the mods added back in.

**Comment by border999** [comment]
New world with all the mods in works. Slower than a snail, but it works.

**Comment by border999** [comment]
It seems that some kind of error's popped up in the dimensions folders. I'm wondering if it could be as simple just deleting those dimensions and forcing them to regenerate.

**Comment by radfast** [comment]
> It seems that some kind of error's popped up in the dimensions folders

Yes you can have issues if your saved data gets corrupted, there's nothing we can do to fix that - the only things which can fix it are regular backups, or a time machine...

**Comment by border999** [comment]
Just glad that I was able to report a valid issue and get something improved.
