### ISSUE TITLE
Problem with FinderCompass mod

### ISSUE THREAD

**Issue by chezpaul** [micdoodle8/Galacticraft#2932]
Minecraft version: 1.10.2
Galacticraft version: 1.10.2-4.0.0.115
Forge version: 12.18.3.2316

Single player (SSP) or Multiplayer (SMP)? Multiplayer

Mods used: appliedenergistics2-core, ivtoolkit, Micdoodlecore, NotEnoughItems, OpenComputers|Core, , ae2stuff, animania, appliedenergistics2, arsmagica2, AnimationAPI, Baubles, bdlib, bedbugs, BiblioCraft, biomebundle, BiomesOPlenty, bookshelf, Botania, bottledmilk, cfm, Chameleon, ChickenChunks, chisel, CodeChickenCore, CodeChickenLib, ccl-entityhook, cofhcore, PTRModelLib, props, eplus, endercore, EnderIO, EnderStorage, EnderZoo, energyconverters, extrautils2, FinderCompass, fluxnetworks, forestry, microblockcbe, forgemultipartcbe, minecraftmultipartcbe, galacticraftplanets, galacticraftcore, gendustry, geographicraft, GraveStone, hammercore, Waila, immersiveengineering, imc, IC2, ironbackpacks, ironchest, JEI, jeibees, malisiscore, malisisdoors, mantle, mcmultipart, Mekanism, MekanismGenerators, MekanismTools, mercurius_updater, testdummy, Morpheus, MrTJPCoreMod, mysticalagriculture, natura, neid, notenoughwands, OpenComputers, openterraingenerator, p455w0rdslib, getalltheseeds, harvestcraft, plustic, pressure, projectred-core, projectred-integration, projectred-transmission, projectred-illumination, projectred-expansion, projectred-transportation, railcraft, reccomplex, redstonearsenal, roguelike, simplecorn, solarfluxreborn, sonarcore, special_ai, StorageDrawers, tconstruct, thermaldynamics, thermalexpansion, thermalfoundation, Translocator, unidict, wailaplugins, wanionlib, weaponcaseloot, wct, worldcontrol, worldedit, wrcbe, xtones

I get an fatal in game crash, get logged out when I try to land on the moon.
This is my first trip in space. I went directly to the moon with a Tier 1 rocket fully loaded inventory (3 chests). I can take off, I see my take off. I can choose the moon as my destination, then I start landing and will slow down the lander but then crash.
If I log back in, I am in the same exact spot I crashed. I can slow down lander again and will crash within 5 seconds. This happens 4 times until I land with a big bang (too fast).
I will then be able to walk on moon for 5 seconds then same crash.

Here is my server log: [https://pastebin.com/u8wFuY2c](https://pastebin.com/u8wFuY2c)

Notice that server actually never crashes.

**Comment by radfast** [comment]
I don't see any Galacticraft issue in that log.

It could be any one of your 100 mods crashing.  I understand that this is on the Moon, but we just make the place ... would you report it to Mojang if it happened on the Overworld?

1.  Can you reproduce the issue in a new world (obviously backup or rename your server's ```world``` folder), using the Creative-mode command ```/dimensiontp``` to get to the Moon quickly?

2.  If you can reproduce it that way, then it's likely a mod conflict.  The only way to resolve this conflict is to try to figure out which exact one of your other mods is causing the issue.  To figure this out, start the game a few times with different sets of mods, using a [binary search method](https://wiki.micdoodle8.com/wiki/Common_Problems#Mod_conflicts:_Binary_Seach_method).

Do you have the same issue in SSP?  Might be easiest for you to do these tests in SSP.

**Comment by chezpaul** [comment]
Okay... will look into all this.
Thanks for pointing in a direction.

**Comment by chezpaul** [comment]
Seems like Finder Compass 1.10.2 was the culprit. At least in SSP, will try on server next...

**Comment by radfast** [comment]
ok great that you found it.  Can you reproduce the same issue with **only** GC and Finder Compass mods installed, in a new world?

Please give exact Finder Compass version, then we can test the issue ourselves.

You should also report the issue to the Finder Compass devs as it's a 50% chance the issue is on their side.

**Comment by chezpaul** [comment]
Finder Compass does not have a version. When you go to the [dev's site](http://atomicstryker.net/findercompass.php), he only gives you the choice to download Finder Compass 1.10.2 and that's it. He's not on Curse.

**Comment by BrisingrAerowing** [comment]
@chezpaul [Yes he is on Curse(forge)!](https://minecraft.curseforge.com/projects/finder-compass)

Atomic Striker does indeed have a very strange method of releasing things, so...

Also what does the Mod Info screen say about that mod (I don't have any of his mods installed)? It might have something related to a version.

**Comment by radfast** [comment]
> Can you reproduce the same issue with only GC and Finder Compass mods installed, in a new world?

**Comment by TheQuadShot** [comment]
Yes it does... It looks to me that compass is crashing when it tries to get stronghold info. Latest log isn't to helpful but the error in progress does give more info. It's from the game output window (which I can't for the life of me find as a file anywhere so I copy/paste from it). Hope this helps

error in progress 
https://pastebin.com/dvuTRT5T
latest log:
https://pastebin.com/A9VRu4dt

complete mod list:
FinderCompass-1.10.2.jar
Galacticraft-Planets-1.10.2-4.0.0.115.jar
GalacticraftCore-1.10.2-4.0.0.115.jar
InventoryTweaks-1.61-58.jar
jei_1.10.2-3.14.7.419.jar
MicdoodleCore-1.10.2-4.0.0.115.jar
modlist.txt
MouseTweaks-2.8-mc1.10.2.jar
Waila-1.7.0-B3_1.9.4.jar

**Comment by radfast** [comment]
There are no strongholds on the Moon!

How does FinderCompass deal with this in the Nether / The End?  (No strongholds there either...)

Please raise this with the FinderCompass developer, the issue is on his side.  Or uninstall that mod ...

**Comment by chezpaul** [comment]
Thanks guys. I just un installed the mod. I'll let him know.

**Comment by radfast** [comment]
Further investigation shows that there is a bug in Galacticraft linked to this, which is fixable.

A new Galacticraft build 140 will be released this weekend with the fix.
