### ISSUE TITLE
lang missing

### ISSUE THREAD

**Issue by ETStarLight** [micdoodle8/Galacticraft#2933]
@micdoodle8 @radfast I just checked en_US and zh_CN,found that there's missing localization entries for tin slabs.Could you please fix it?
P.S. The same to strange seeds.
P.P.S.I had @ you in the Pull request before to talk about it,but no one seen it.

**Comment by radfast** [comment]
Thanks, fixed. :)

I saw the @ notification but did not have time to make a fix yesterday.

**Comment by radfast** [comment]
Languages updated in build 116 now available.

Please let us know if you find any more localization issues.
