### ISSUE TITLE
corrupt world SpinManager.refresh(SpinManager.java:266)

### ISSUE THREAD

**Issue by Kepler68** [micdoodle8/Galacticraft#2937]
Minecraft version: 1.11.2
Galacticraft version: 4.0.0.115
Forge version: 1.11.2-13.20.0.2288

Multiplayer (SMP)

Galacticraft add-ons and other mods installed:
2 custom mods, only add blocks
crayfish furniture
mcdoodlecore
glacaticraft core
galacticraft planets
worldedit

crash report:
[crash-2017-08-03_18.29.12-server.txt](https://github.com/micdoodle8/Galacticraft/files/1197951/crash-2017-08-03_18.29.12-server.txt)

**Comment by MJRLegends** [comment]
This has already been reported and the problem has been fixed see https://github.com/micdoodle8/Galacticraft/issues/2924 for details on it

**Comment by Kepler68** [comment]
thanks

**Comment by radfast** [comment]
Should be improved in build 116 now available.
