### ISSUE TITLE
[1.11.2] Aluminum wires not connecting to OpenComputers power converter blocks

### ISSUE THREAD

**Issue by Spacebug300** [micdoodle8/Galacticraft#2938]
**Minecraft version:** 1.11.2
**Galacticraft version:** 1.11.2-4.0.0.115
**Forge version:** 13.20.1.2425

Multiplayer (Dedicated Server)

**Mods Installed:** 
- Galacticraft
- OpenComputers (v: 1.11.2-1.7.0.24)
- Just Enough Items (v: 1.11.2-4.5.0.294)

**Issue Description:**
On the OpenComputers wiki, it says that Galacticraft's aluminum/heavy aluminum wires may be used to provide power to the converter but they don't connect at all. I tried with some other blocks from the OpenComputers mod but the aluminum wires just refuse to connect.

**Screenshot:**
![screen shot 2017-08-05 at 15 34 23](https://user-images.githubusercontent.com/20500877/28995508-919b1814-79f3-11e7-9092-90e7a461573d.png)

**Comment by radfast** [comment]
Please raise the issue with OpenComputers devs, seems like they are not implementing our power API correctly (or maybe not at all).

Alternatively if you install one additional power mod, like IC2 or Thermal Foundation/Thermal Expansion, it will likely work.
