### ISSUE TITLE
[suggestion] Ability to color the sealed wires and sealed fluid blocks

### ISSUE THREAD

**Issue by mcdodge34** [micdoodle8/Galacticraft#2940]
This is just a suggestion here, I choose to use Environmental Tech Basalt to build both my Moon and Mars Base, and the white greyish colors of the sealed aluminum wire and sealed oxygen blocks doesn't fit that well with it. Since there's a new block (forgot the name of it) that allow us to paint the sides of the new vaccuum glass, maybe we should be able to paint anything with it, the same way the EnderIO Painting Machine works maybe.

**Comment by radfast** [comment]
That's a good idea, we might do that.  For the future, suggestions go on the suggestions area of the forum please.
