### ISSUE TITLE
Can't start server

### ISSUE THREAD

**Issue by Andrey228322** [micdoodle8/Galacticraft#2941]
Help pls.

Minecraft version: 1.7.10
Galacticraft version:501
Server can't start
https://pastebin.com/F4pmkf66

**Comment by TheQuadShot** [comment]
I don't see a fatal error in the log you posted(they're all warnings, which is normal). Please post a complete log file. Also there is a newer version available (.502) you may want to grab at https://micdoodle8.com/mods/galacticraft/downloads

**Comment by radfast** [comment]
Why are you reporting this to Galacticraft?  I don't see any Galacticraft error reported in that log.

As with any server, start simple and build it up.  Can you get to a simpler configuration which works?
