### ISSUE TITLE
GalacticCraft [Server thread/INFO]: TotalWeight 0, nothing to spawn???

### ISSUE THREAD

**Issue by RoboJsckPlsys** [micdoodle8/Galacticraft#2943]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.7.10
Galacticraft version: 1.7-3.0.12.501
Forge version: 10.13.4.1614

Single player (SSP) or Multiplayer (SMP)? SMP

Galacticraft add-ons and other mods installed?
- Galacticraft Planets
- About 60 other mods (Large modpack)

Please provide screenshots / crash report / log as needed.
https://pastebin.com/78PkQWK3

When a user goes to the galacticraft moon it starts to spam the console and logs with [Server thread/INFO]: TotalWeight 0, nothing to spawn??? and often kicks half if not all the players off the server. We have not yet found a fix for this and it is become frustrating as the server becomes a highly populated server.

**Comment by TheQuadShot** [comment]
GC doesn't do/have anything to do with weight, the log file also shows nothing. It's a mod conflict, to find it, it's  best to use the binary search method found here: https://wiki.micdoodle8.com/wiki/Common_Problems#Mod_conflicts:_Binary_Seach_method

**Comment by radfast** [comment]
Do you have **TechGuns** mod?  Seems to be a [known issue](https://github.com/pWn3d1337/Techguns/issues/76) in that mod.
