### ISSUE TITLE
Gas Liquefier ONLY outputs the liquified gas in the 2nd storage tank when via Buildcraft Liquld Pipe

### ISSUE THREAD

**Issue by kouwei32** [micdoodle8/Galacticraft#2947]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.7.10 Forge
Galacticraft version: 3.0.12
Forge version: 7.10.99.99

**Single player (SSP) or Multiplayer (SMP)?**
SSP.
**Galacticraft add-ons and other mods installed?**
BuildCraft, Ironchest, MrCrayfish's Furnitures, Journeymap, Walia(plus Harvastabality) ,NEI, CodeChickenCore, Optifine
**Please provide screenshots / crash report / log as needed.**
NOT CRASH ISSUE

When extracting the produced fuel (liquld methane) in a gas liquefier via buildcraft (wooden) liquld pipe, only the fuel in the first (internal) output tankis extracted. Since the gas liquefier always fills the second tank first, it will confuse some people who are testing their machines, because it will only start outputing when the second tank is full. Not sure if the issue is because of the BuildCraft pipe.

**Comment by TheQuadShot** [comment]
By design, If you use an Atmospheric Valve on the Input you could get 2 liquids out. So to pull from the center tank, pull from the Rear of the machine, to pull from the right tank, pull from the right. I've just confirmed this on 1.10.2 and 1.11.2 (GC version 4.0.0.115) and on 1.7.10 (GC version 3.0.12.502).

**Comment by radfast** [comment]
Thank you @TheQuadShot 

@kouwei32 if you still have an issue, please post screenshots of your setup showing which sides your pipes are connected.  Screenshots are easy to post, just drag and drop to here.
