### ISSUE TITLE
Default Oil gen seems too high

### ISSUE THREAD

**Issue by TheQuadShot** [micdoodle8/Galacticraft#2948]
Minecraft 1.10.2
Forge .2316
Galacticraft-Planets-1.10.2-4.0.0.115.jar
GalacticraftCore-1.10.2-4.0.0.115.jar
MicdoodleCore-1.10.2-4.0.0.115.jar
ModList: https://pastebin.com/9GGHG6u9
My typical mining layout: http://imgur.com/a/S1C43

I create a stairway going down. At lvl 50 I start branching out at 90° every 10 lvl's and create a long hall that I mine off of at 90°(see image). When I got to lvl 20 I started to the right and hit an oil pocket after 3 blocks, going left I hit one at 5 blocks, and going off of that hall I hit one at 8 blocks. So I hit 3 pockets within 6 chunks. While creating the main hall I hit one about every 3 or 4 chunks. I have no other mod that gens oil (immersive petroleum oil is below bedrock)

**Comment by radfast** [comment]
Should not be 3 pockets within 6 chunks, could be a quirk of the RNG?

Which biome are you in?  Oil pockets are more common in desert, ocean and swamp biomes.

You can probably see the oil pocket distribution in /gamemode 3.

**Comment by TheQuadShot** [comment]
I'm in a Plains biome. Here's a screenshot and to me, it seems like way too many pockets. I checked and the "bubbles"/pockets are all oil.
http://imgur.com/a/VQisu

**Comment by radfast** [comment]
I agree, that looks a bit too much!  Probably would be OK if the oilgen factor were 1.0.  I'll look back and see when that increased to 1.8 and why.

**Comment by radfast** [comment]
hmm, it's been set at 1.8 for over 3 years, since Galacticraft 2 era.

If we change the default factor to 1.0 that is not going to produce actual in-game changes for most people, because they will already have a Galacticraft config file in the ```config``` folder with the 1.8 value.  So instead I'll change how we process the value.

**Comment by EzerArch** [comment]
So, can I safely change the value to 1.0 in 1.7.10 for new worlds?

**Comment by radfast** [comment]
You can replicate it in 1.7.10 by changing the config value to 1.0, yes.

But note: config is the same for GC3 and GC4, so whatever value you set will affect both.
