### ISSUE TITLE
internal server error

### ISSUE THREAD

**Issue by Andrey228322** [micdoodle8/Galacticraft#2949]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.7.10
Galacticraft version: pre-last

MultiPlayer

Mod add GalaxySpace

If on the moon. Find a village. And go to her. Gives an error message. And you can not go to the server.!

Logs client: https://drive.google.com/open?id=0Bxwh_0sc7uJ1Y0o4bWdBXzh4RVU
LOG server: https://pastebin.com/YZeN6dqX
Help pls

**Comment by radfast** [comment]
It's a GalaxySpace error.  Seems like the GalaxySpace version is not compatible with latest Galacticraft version.  Look for a more recent GalaxySpace or report to GalaxySpace dev.
