### ISSUE TITLE
Moon / Mars Dungeon Gen causes server lag - and codefix (radfast #1)

### ISSUE THREAD

**Issue by radfast** [micdoodle8/Galacticraft#295]
Issue: Servers (especially large multiplayer public servers) lag when the Moon or Mars dimensions are loaded.  The lag increases as the server ages, due to more and more players travelling to those dimensions, walking around the map and so causing world generation.  Entity profiling might show the boss spawner entities as consuming a huge amount of CPU (more accurately, the problem is a very large quantity of those entities, see below).  The lag means that many public servers running modpacks incorporating Galacticraft have to disable access to the Moon and Mars dimensions in order for the rest of the server to stay playable ... which is kind of a shame!

Cause: There is a small bug in GCCoreMapGenDungeon.java (which was named GCMapGenDungeon.java in MC versions 1.5.2 and earlier).  That is code which is run multiple times by the Moon/Mar worldgen; it is run whenever a new underground dungeon has to be generated.  The bug is that the code maintains a private ArrayList "rooms" which persists between calls because only one instance of the dungeon generator is ever created (see the Moon / Mars chunkprovider code which defines a single persistent dungeonGenerator).  The ArrayList rooms is never cleared.  Therefore on each call to the MapGenDungeon code, it will have all the previously generated dungeon rooms still stored in that ArrayList, and the new generation of rooms just adds more to it.  Meaning, that generating a new dungeon, also re-generates all the rooms which were in previously generated Moon/Mars dungeons on the same server, wherever those rooms are located.  This problem causes multiple copies of tile entities such as the boss spawner to be generated (so there can be multiple copies of the same tile entity at the same coordinates).  This problem also results in re-filling of the chests in all dungeons, every time a new dungeon gets generated.

Solution:

In GCCoreMapGenDungeon.java, at lines 62-65:

```
public void generate(World world, Random rand, int x, int y, int z, int chunkX, int chunkZ, short[] blocks, byte[] metas, boolean useArrays)
{
    GCCoreMapGenDungeon.useArrays = useArrays;
    this.worldObj = world;
```

add this new line:

```
public void generate(World world, Random rand, int x, int y, int z, int chunkX, int chunkZ, short[] blocks, byte[] metas, boolean useArrays)
{
    GCCoreMapGenDungeon.useArrays = useArrays;
    this.worldObj = world;
    rooms.clear();
```

Result: no more lag.  (Tested by me on a big popular server and it works.  Note: a proper solution will require the server owner to delete, and fully re-generate, the Moon and Mars dimensions after updating to a version of the GalactiCraft code incorporating this fix.  If the dimensions are not re-generated then some lag will remain due to hangover of tile entities from the previous situation.)

**Comment by SrYthan** [comment]
thanks my bro, this saved my server, im not have the source code to do this fix, but i create a asm fix por this, if any else has the source code to send me, i appreciate this!

source code 1.5.2, im in 1.5.2-a0.1.36.410
