### ISSUE TITLE
[Suggestions] GC 4 API Features/Changes

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft#2956]
**Suggestion/ Sorta Bug:**
So the Deconstructor used  to break down rockets only works for GC tier 1 - 3 rocket, custom rockets just get taken and nothing is returned back to the player. This is because nothing is setup for returnable items for the custom rockets.

Any chance we could get a API hook to make this a thing for custom rockets too

Maybe a registry for the rocket input and then a array list of items you can get in return?
Or maybe make the Deconstructor detect items it was made with from recipe?

Its open to suggestions and ideas..

**Comment by MJRLegends** [comment]
Also so the Pre Launch Checklist book, please can we look at the design and make it less busy see below for details:

This is what it currently is
![](https://i.gyazo.com/23387bf6ed60b880ebc12e40a2c9e667.png)

Im thinking it would look better if it was like this
![](https://i.gyazo.com/0f1107dba043d0a1752ba382ea13628c.png)

This feature is also open to suggestions and ideas...

**Comment by radfast** [comment]
There is no specific API for the Deconstructor machine, but it has public fields and methods which you can use to add your mod's items and recipes.

See [this code section](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/tile/TileEntityDeconstructor.java#L61-L101)

So you can add more ```INasaWorkbenchRecipe``` to the ```knownRecipes``` list.  And if you have new types of metal plate or other materials which you want the machine to recover then you can call ```.addSalvage(itemStack)``` with those items - the machine will only recover itemstacks included in the list of known salvage items.

-------

I agree about the checklist looking busy, that is already on our (internal) todo list.

**Comment by MJRLegends** [comment]
Amazing thank you :D

**Comment by radfast** [comment]
I updated my comment with initial info on timing of when to do that.

**Comment by MJRLegends** [comment]
Thanks, yeah i totally missed the fact they were public methods haha

**Comment by MJRLegends** [comment]
@radfast Whats your thoughts of changing the pre launch checklist to be for easier to read/better layout, on the comment above about the pre launch checklist i've suggested what i think needs to change ( https://github.com/micdoodle8/Galacticraft/issues/2956#issuecomment-324033893 ) i just wondered whats your thoughts of it. as i get feedback all the time from players of my pack saying its confusing to see and they hate it and dont use it

**Comment by radfast** [comment]
I don't like the layout, very happy if someone wants to submit a PR which improves it.

Otherwise we might have to wait for micdoodle8 to be back, as the checklist is his sub-project.
