### ISSUE TITLE
(1.8+) Incorrect Naming on Tier 2 - 3 rockets and Custom rockets (Cause Found & Fix provided)

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft#2957]
**Issue:** Waila and other similar mods showing Tier 1 Rocket for Tier 2 - 3, etc

So i fixed this issue for my addon after spending time looking through the GC code to work out what the issue was..

I have two solutions for this issue:

**Solution one:**
See my changes i used to make it work for my addon, this could be applied to the Tier 2 - 3 rockets like i did for mine: 
https://github.com/MJRLegends/ExtraPlanets/commit/e59fab31df08efd597fb7477ef34ab0495b342ce#diff-26b432b8b93e6d7f87d458e04fa4a155

**Solution Two: This one is the better long term one**

Change this to false:
https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/api/prefab/entity/EntityAutoRocket.java#L1325

And remove this
https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/api/prefab/entity/EntityAutoRocket.java#L1311

This will make them use there registry names, e.g "entity.extraplanets.EntityTier10Rocket.name"

I understand that the hasCustomName method is overrided in the Rocket Entity classes but because getName is being used in EntityAutoRocket its because ignoring that

**Comment by MJRLegends** [comment]
If you would like me to make a pull request for this for you let me know @radfast @micdoodle8 :D

**Comment by MJRLegends** [comment]
Solution Two would be the one that is the best as it will make it so no addon has to override the getName method

**Comment by radfast** [comment]
ok we can do this, sorry I missed this in the build 117 update but we can do it for build 118.

**Comment by MJRLegends** [comment]
No problem its not a big issue :D Just thought since i found the issue and fixed for my custom rockets i thought i'd tell you where the problem is and how to fix it :)

**Comment by radfast** [comment]
Thanks, this also fixes an issue with rocket naming in the Display Screen when linked through a Telemetry Unit.  Implemented in next build 118.
