### ISSUE TITLE
(1.10.2 Maybe 1.8 and 1.11.2 too) Comparability with Ender IO Machines, Cables

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft#2958]
Minecraft version: 1.10.2
Galacticraft version: Build 117
Forge version: 12.18.3.2422
Ender IO Version: 1.10.2-3.1.193

Any chance of making these setup working or has it got to come from Ender IO?

## Testing within my mod pack
So the following setups do not transfer power
**Setup 1:** 
![2017-08-22_15 39 25](https://user-images.githubusercontent.com/8526321/29571236-98230bc8-8750-11e7-818c-d7ee867195b0.png)
![2017-08-22_15 39 28](https://user-images.githubusercontent.com/8526321/29571237-9827b25e-8750-11e7-83f8-d9070a178fe7.png)
![2017-08-22_15 39 21](https://user-images.githubusercontent.com/8526321/29571238-982ed494-8750-11e7-9193-ddce607a9d74.png)
**Setup 2:**
![2017-08-22_15 39 42](https://user-images.githubusercontent.com/8526321/29571248-a02d896a-8750-11e7-927e-d9ce49686859.png)
![2017-08-22_15 39 38](https://user-images.githubusercontent.com/8526321/29571246-a016b2c6-8750-11e7-80bb-cf3c36fb99f4.png)
![2017-08-22_15 39 40](https://user-images.githubusercontent.com/8526321/29571247-a01f9f44-8750-11e7-8e8f-822fd908185b.png)
**Setup 3:**
![2017-08-22_15 40 33](https://user-images.githubusercontent.com/8526321/29571264-a8ac97f2-8750-11e7-97c7-6ec66532d881.png)
![2017-08-22_15 40 34](https://user-images.githubusercontent.com/8526321/29571265-a925a98a-8750-11e7-8bf3-c69f9da5b34d.png)
![2017-08-22_15 40 37](https://user-images.githubusercontent.com/8526321/29571266-a99655d6-8750-11e7-858b-d4667e806139.png)
**Setup 4:**
![2017-08-22_15 42 46](https://user-images.githubusercontent.com/8526321/29571272-ac3143b4-8750-11e7-87a5-bfffcf1c7907.png)
![2017-08-22_15 42 48](https://user-images.githubusercontent.com/8526321/29571273-ac340784-8750-11e7-90ec-ce1be5e5c3ec.png)
![2017-08-22_15 42 51](https://user-images.githubusercontent.com/8526321/29571274-ac375aba-8750-11e7-8d9e-6d6aa65a09fe.png)

## Testing outside of my mod pack with just Ender IO and Galacticraft and JEI
**Setup 1**
![2017-08-22_15 52 19](https://user-images.githubusercontent.com/8526321/29571784-1649ad30-8752-11e7-811e-8a254a611233.png)
**Setup 2**
![2017-08-22_15 52 56](https://user-images.githubusercontent.com/8526321/29571785-1756ae4e-8752-11e7-85b6-de0bd7b1292a.png)
**Setup 3**
![2017-08-22_15 53 10](https://user-images.githubusercontent.com/8526321/29571791-1c7e62f4-8752-11e7-8eed-1829cd996194.png)

**Comment by dj3520** [comment]
In the last picture it looks like the capacitor is configured to not accept connections on that side.

**Comment by MJRLegends** [comment]
Yeah but it doesnt work which every setting i tried everything

**Comment by radfast** [comment]
I don't know if EnderIO is a standalone mod, it might need a CoFH mod to work as it uses the CofH power system (aka Redstone Flux).  Does it work with other (non-CoFH) mods on a standalone basis as you are testing here.

I'll be on vacation the next few days but when I get back, I'll test the EnderIO version you mentioned with Galacticraft.  Our mod is supposed to be fully RF compatible.

**Comment by TheQuadShot** [comment]
Adding just CoFH Core will make the EnderIO conduits work, but not the GC Wires. However adding just McJtyLib does solve the issue for the both.

**Comment by MJRLegends** [comment]
yeah with Galacticraft and Ender io and Cofh core still doesnt work @radfast :(

**Comment by MJRLegends** [comment]
and for me McJtyLib didnt solve it

**Comment by MJRLegends** [comment]
@radfast it seems Galacticraft is using the 1.8.9 Cofh api for 1.10.2 stillhttps://github.com/micdoodle8/Galacticraft/blob/MC1.10/dependencies/main/java/cofh/api/CoFHAPIProps.java

most other mods are using 1.5.0 or 1.6.0 of CoFHAPI

**Comment by TheQuadShot** [comment]
hmmmm, Here's my complete mod list I tested with (toggled Cofh and mcjtylib):
CoFHCore-1.10.2-4.1.11.16-universal.jar
EnderCore-1.10.2-0.4.1.66-beta.jar
EnderIO-1.10.2-3.1.193.jar
Galacticraft-Planets-1.10.2-4.0.0.117.jar
GalacticraftCore-1.10.2-4.0.0.117.jar
jei_1.10.2-3.14.7.419.jar
mcjtylib-1.1x-2.4.3.jar.disabled
MicdoodleCore-1.10.2-4.0.0.117.jar
MouseTweaks-2.8-mc1.10.2.jar
Waila-1.7.0-B3_1.9.4.jar

and my results:
With CoFH Core:
http://imgur.com/a/ZNcQF
With McJtyLib:
http://imgur.com/a/hcSnJ

**Comment by MJRLegends** [comment]
Yeah it connects but no power is being moved

**Comment by TheQuadShot** [comment]
In which case? That's true with CoFH Core, however with McJtyLib it does move power on both.

https://www.youtube.com/watch?v=UBmohws5bJI

**Comment by radfast** [comment]
I'll look at updating the API, but this will take a few days as I'll need to figure out what's changed - not much fun with other people's API code changes.

**Comment by MJRLegends** [comment]
No problem @radfast

**Comment by MJRLegends** [comment]
@radfast As of build 118 this is the latest on this issue

**These setups works ok**
![2017-10-03_19 19 47](https://user-images.githubusercontent.com/8526321/31141651-e35bb7d0-a86f-11e7-8aec-46994cd7638b.png)

![2017-10-03_19 21 37](https://user-images.githubusercontent.com/8526321/31141724-1af42434-a870-11e7-9afe-b33043e48dcd.png)

**These dont:**
![2017-10-03_19 23 19](https://user-images.githubusercontent.com/8526321/31141829-58d0b8da-a870-11e7-9529-625b67e46b81.png)
![2017-10-03_19 22 19](https://user-images.githubusercontent.com/8526321/31141758-327ad6c0-a870-11e7-843f-af02613d37f7.png)
![2017-10-03_19 22 20](https://user-images.githubusercontent.com/8526321/31141762-33ffb6e6-a870-11e7-9a4f-93289110e1ec.png)

**Comment by MJRLegends** [comment]
@radfast any chance you had time to look at this bug yet, dont worry if you haven't just a reminder it exists :D but see my last comment above as changes have been made to this bug since new commits

**Comment by radfast** [comment]
@MJRLegends  I've looked at it today.

It seems to be **working** in my testing with GC build 119 and EnderIO 1.10.2-3.1.193.

![2017-11-26_19 21 04](https://user-images.githubusercontent.com/6842258/33243492-2f7cb738-d2df-11e7-83d4-07844427d515.png)


If it's still not working for you, please give me more screenshots.  Bear in mind that a GC solar panel will not output if it's raining ...

**Comment by MJRLegends** [comment]
Still getting the issue but maybe something is causing it to happen, i will look in to this more later :D thanks for your reply

**Comment by MJRLegends** [comment]
Ive confirmed this not to be a Galacticraft issue @radfast
