### ISSUE TITLE
(1.10.2 Maybe 1.8.9/1.10.2?) JEI Support Issue for Compressor recipes

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft#2959]
**Minecraft version:** 1.10.2
**Galacticraft version:** Build 117
**Forge version:** 12.18.3.2422

**Single player (SSP) or Multiplayer (SMP)?** Any

Slots dont line up with background :P 

![](https://i.gyazo.com/c75c17da3a35eb2371427b1cf024e8e7.png)

**Comment by radfast** [comment]
Are you doing something to move the offset of the JEI panel from it's standard (screen centre) position?

**Comment by MJRLegends** [comment]
Nope im not touching the JEI support :(

**Comment by MJRLegends** [comment]
This seems to be a weird one off issue :D thanks for your time :D
