### ISSUE TITLE
[1.11.2][Bug]Astro Miner collects leaves with incorrect metadata

### ISSUE THREAD

**Issue by Mike-T4** [micdoodle8/Galacticraft#2960]
Minecraft version: 1.11.2
Galacticraft version: 1.11.2-4.0.0.117
Forge version: 2454

Single player.

Only Galacticraft, GalacticraftPlanets and Mcdoodlecore are installed.

When the Astro Miner mines Oak Lives, their metadata can be 4 or 12. Oak Leaves can normally not be obtained with these metadata values, and will as a result use the "Missing Texture" graphic when in the inventory.
The same seems to happen when collecting Sunflowers.

**Comment by radfast** [comment]
thank you for reporting this.  Simplest is probably to set the astrominer not to collect leaves - no real reason why a mining machine should be able to harvest leaves.

**Comment by radfast** [comment]
This should be implemented in next build 118.  Thanks again.
