### ISSUE TITLE
GalactiCraft Server crashing, SMP works

### ISSUE THREAD

**Issue by DarthRasputin** [micdoodle8/Galacticraft#2962]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.7.10
Galacticraft version: 1.7-3.0.12.495
Forge version: 1614 (1.7.10)

Single player (SSP) or Multiplayer (SMP)? SMP

Galacticraft add-ons and other mods installed? Screenshot

Please provide screenshots / crash report / log as needed.

All Mods work with GalacySpace, after adding another add-on the Server crashs
crash report https://pastebin.com/112GvNYj
SMP works fine with all of these
![screenshot_2](https://user-images.githubusercontent.com/31326738/29691794-ed464ab0-892c-11e7-9a9d-78cca5f3f45e.png)

**Comment by dj3520** [comment]
Not a galacticraft crash. Issues are with VacuumHorizon and SpaceAdvanced. Report there instead.

**Comment by radfast** [comment]
"after adding another add-on the Server crashs"

report to that add-on author please.

I don't see any GC issue here.
