### ISSUE TITLE
Fatal error during startup

### ISSUE THREAD

**Issue by Deanosaurio123** [micdoodle8/Galacticraft#2963]
when i try to start minecraft with the galacticraft mod it jus said it cant find galacticraft in the mods folder even though its in there. I am very confused please help me

**Comment by TheQuadShot** [comment]
There are 3 files that you need. Beyond that... You didn't bother to read how to post a bug, as it is you have provided no information that could help anyone help you. Please provide the requested information (the stuff you deleted to write your comment), and read the link that's provided. You may also want to look at the Wiki.

**Comment by radfast** [comment]
https://wiki.micdoodle8.com/wiki/Tutorials/Galacticraft_Installation_Guide

any more issues please provide the requested information like **TheQuadShot** said ^^^^^^^^^^^^^^
