### ISSUE TITLE
Cables Utils Crash

### ISSUE THREAD

**Issue by Senrabauqa** [micdoodle8/Galacticraft#2965]
Minecraft version: 1.11.2
Galacticraft version: 4.0.0.87
Forge version: 13.20.1.2454

Single player (SSP) or Multiplayer (SMP)? - SMP

Galacticraft add-ons and other mods installed?
Buildcraft-7.99.7
GalacticraftCore-1.11.2-4.0.0.87-BETA
Galacticraft-Planets-1.11.2-4.0.0.87-BETA
MicdoodleCore-1.11.2-4.0.0.87-BETA
twilightforest-1.11.2-2.4.0.144-universal
Mekanism-1.11.2-9.3.4-fix
MekanismGenerators-1.11.2-9.3.4-fix
MekanismTools-1.11.2-9.3.4-fix

Please provide screenshots / crash report / log as needed.
(client side)
[crash-2017-08-26_23.08.41-client.txt](https://github.com/micdoodle8/Galacticraft/files/1254003/crash-2017-08-26_23.08.41-client.txt)

(server side)
[crash-2017-08-26_23.09.02-server.txt](https://github.com/micdoodle8/Galacticraft/files/1253998/crash-2017-08-26_23.09.02-server.txt)

**Comment by MJRLegends** [comment]
Your using a very old Galacticraft, this is why your getting this crash, Update you Galacticraft and you will be good

**Comment by Senrabauqa** [comment]
Oh yeah sorry cant believe I didnt check that thanks very much :)

**Comment by radfast** [comment]
thanks @MJRLegends
