### ISSUE TITLE
[Low priority] GC version check failure

### ISSUE THREAD

**Issue by dj3520** [micdoodle8/Galacticraft#2968]
`[Thread-32/ERROR] [Galacticraft]: Galacticraft update check failed! Trying again in 15 seconds`

I'd imagine this is due to the http -> https that happened a while ago. Effects 1.7.10 and onward.

**Comment by radfast** [comment]
This is fixed in versions from 4.0.1.121 onwards.

Actually it will be automatically fixed for all GC versions as soon as the remote version gets updated to 4.0.1 - the failure is because the code thinks it has "failed" if the remote version ends with .0.
