### ISSUE TITLE
[Request] Space Station gamerule command/config option

### ISSUE THREAD

**Issue by hugeblank** [micdoodle8/Galacticraft#2970]
(None of this is really necessary, but...)

    Minecraft: 1.11.2
    SpongeForge: 1.11.2-2393-6.1.0-BETA-2592
    Minecraft Forge: 13.20.1.2454

Single player (SSP) or Multiplayer (SMP)?
Request is primarily for SMP

A player on a server that I am working on notified me that he had died on his space station and lost all his items. This was strange, because I had enabled keepInventory on all dimensions. Then I realized that even though I did do this, the player most likely made the station after I set the gamerule. I decided to skim the config of sponge to see if there was some sort of option that allowed me to set a default gamerule that persisted across dimensions the moment they generate, to no avail. Of course my next choice was to see if your mod has it, as it would make sense to have a feature like this for your mod, but alas, there isn't any. My request to you devs is that you add a config option that allows me to set default gamerules that persist across all space station dimensions, and get set immediately on newly generated space station dimensions. Thanks in advance, I hope this gets implemented!

**Comment by radfast** [comment]
We can't interact with Sponge gamerules in that way, sorry.  Maybe make the request to Sponge as a config option.  It's not specific to Galacticraft, it would be for the same for any mod which creates dimensions (e.g. Mystcraft).

**Comment by hugeblank** [comment]
Oh. I didn't realize that world persistence existed in vanilla.
