### ISSUE TITLE
[1.10.2] Texture size issues

### ISSUE THREAD

**Issue by BoxOfFlex** [micdoodle8/Galacticraft#2972]
Minecraft version: 1.10.2
Galacticraft version: 4.0.0.117
Forge version: 2422

Single player (SSP) or Multiplayer (SMP)? Both I guess

Galacticraft add-ons and other mods installed?
- More Planets
- Extra Planets
- Bunch of other mods

Please provide screenshots / crash report / log as needed.
`java.lang.RuntimeException: net.minecraft.client.renderer.StitcherException: Unable to fit: galacticraftcore:model/buggy_wheels, size: 1024x1024, atlas: 4096x4096, atlasMax: 4096x4096 - Maybe try a lower resolution resourcepack?`
[Full Log](https://hastebin.com/epiyalixur)

Just started doing this out of the blue after this pack I made has been working fine for 2 days without issues. Texture pack replacement didn't work at all. More RAM allocation didn't help anything. Optifine didn't help anything (didn't expect it to). I have no idea why it just stopped working out of the blue like this.

**Comment by BoxOfFlex** [comment]
Closing cause supposedly its not a mod issue (when it clearly is cause there should be no reason for this mod using such huge of textures) where its a GPU issue on low end systems, which mine is not lowend and is modern but whatever.

~~why is this game so stupid with hardware~~

**Comment by radfast** [comment]
The game puts together all textures from all mods into a giant texture called a "texture atlas".  It's just a coincidence that a Galacticraft texture was the one that took the size of that past the limit (OK not a complete coincidence, Galacticraft has a lot of textures).

The only things you can do to make this work are
1. enable your hardware to use a larger taxture atlas (see below)
2. use a smaller mod list

I don't know why your texture size on your graphics hardware is limited to 4096x4096, that's fairly small for modern graphics hardware on a PC - the normal is 16384x16384.  Actually the only time I've seen this issue before was when someone was trying to run modded Minecraft on an Android phone set to run Java ...

Maybe you can increase the max permitted texture size on your graphics hardware by updating the driver or changing some advanced OpenGL setting?  https://forum.openframeworks.cc/t/maximum-texture-size-on-your-graphics-card/23907/3

**Comment by radfast** [comment]
incidentally the reason the buggy wheel texture is 1024 x 1024 is because a part of it has to be circular, and a low resolution circle looks horrible

**Comment by BoxOfFlex** [comment]
It was something weird with caching issues, cause I launched a vanilla instance and then relaunched and it worked fine. Had this issue on an older MC version with a different mod which I don't remember how I even fixed it.
