### ISSUE TITLE
Can't craft Energy Storage Module

### ISSUE THREAD

**Issue by nialinius** [micdoodle8/Galacticraft#2974]
I followed the recipe on the wiki page and nothing happens

![galacticraft bug](https://user-images.githubusercontent.com/31781506/30232701-538df5c6-94e9-11e7-9b43-939980f8e336.png)

I notice the batteries look different compared to what I saw on the wiki so is there something I'm doing wrong?

Minecraft version: 1.11.2
Galacticraft version: 1.11.2
Forge version: 1.11.2

**Comment by marcus8448** [comment]
The reason is you are using fully charged batteries use empty ones and it will work.
![2017-09-08_15 57 28](https://user-images.githubusercontent.com/28928887/30234045-b04c8b46-94ae-11e7-9e86-2376a2eaba63.png)

**Comment by marcus8448** [comment]
I don't think the wiki is updated for GalactiCraft 4.

**Comment by dj3520** [comment]
The wiki needed this updated for GC3 actually. See #1998

**Comment by EzerArch** [comment]
If anyone's feeling like to, feel free to update the wiki. :)

**Comment by nialinius** [comment]
the empty battery worked, thanks!

**Comment by TheQuadShot** [comment]
I added a quick not to the wiki that the batteries must not have a charge. I'll fix the graphic to show the charge indicator empty soon.
