### ISSUE TITLE
Conflict with Aether

### ISSUE THREAD

**Issue by ZeBrasa** [micdoodle8/Galacticraft#2977]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.6.4 
Galacticraft version: 2.0.12.1026
Forge version: 1.0.0.250 
Multiplayer: Playing on local server with friends

Galacticraft add-ons and other mods installed?
Tekkit modpack(has galacticraft) + Aether II, fossils, Mo'creatures and ID Fix

Crash report:
[crash-2017-09-10_16.14.27-client.txt](https://github.com/micdoodle8/Galacticraft/files/1290631/crash-2017-09-10_16.14.27-client.txt)

Notes: So, I have been searching everywhere to fix this problem, and I found out that is a problem with Galacticraft. The problem is, when I enter a dimension of Aether, The game after a while crashes, with the error provided on the txt file. I noticed, when i can stay there a long time, the spawners from Galactic craft, like evolved spider and stuff, are there instead of the aether ones. And Evolved Skeleton boss also there. I think it's a problem on world gen. And I can't change the Spawner ID. I checked the Not enough Items, and the supposed name "mimic spawner" from an aether spawner is actually an evolved Spider or something. I Know that galacticraft and aether don't like to mix, but I would appreciate some help and tips on the matter. If you need anything extra content, fell free to ask.

**Comment by TheQuadShot** [comment]
You might try updating to GC version 1.6.4-2.0.13.1098, You can also check the install guide on the wiki
https://micdoodle8.com/mods/galacticraft/downloads
https://wiki.micdoodle8.com/wiki/Tutorials/Galacticraft_Installation_Guide

**Comment by ZeBrasa** [comment]
Ok, i will try that and check if this works. Thank you, will post as soon as I try it

**Comment by ZeBrasa** [comment]
Well, it worked! Thank you my friend! I can finally say that my modpack almost 100% functional! Thanks a lot!
