### ISSUE TITLE
[1.11.2] Texture of battery changes colour in Astro Miner Base

### ISSUE THREAD

**Issue by marcus8448** [micdoodle8/Galacticraft#2985]
When you put a infinite battery in a Astro miner the batterys texture will turn black.
Minecraft version: 1.11.2
Galacticraft version: 117
Forge version: 13.20.1.2476

Single player (SSP) or Multiplayer (SMP)? SSP

Galacticraft add-ons and other mods installed? Galacticraft planets, JEI

Please provide screenshots / crash report / log as needed.
![2017-09-18_20 06 37](https://user-images.githubusercontent.com/28928887/30574183-2e47f250-9cad-11e7-955e-d05dbac0a502.png)

**Comment by Romsik788** [comment]
Developers, please pay attention to this problem, as it also exists in the version of GC 4.0.1.120

**Comment by radfast** [comment]
Thanks to @SteveKunG for the fix.
