### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by PrincessEileen** [micdoodle8/Galacticraft#2987]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.11.2
Galacticraft version: 1.11.2
Forge version: 1.11.2

Single player (SSP) or Multiplayer (SMP)? singleplayer

Galacticraft add-ons and other mods installed? GalacticraftCore, Galacticraft-planets and micdoodleCore are all thats there nothing related to other mods

Please provide screenshots / crash report / log as needed.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.11.2-4.0.0.117.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 9/23/17 6:51 PM
Description: Ticking block entity

java.lang.NoSuchMethodError: net.minecraft.profiler.Profiler.startSection(Ljava/lang/Class;)V
	at net.minecraft.world.World.func_72939_s(World.java:1801)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1801)

-- Block entity being ticked --
Details:
	Name: minecraft:chest // net.minecraft.tileentity.TileEntityChest
	Block type: ID #54 (tile.chest // net.minecraft.block.BlockChest)
	Block data value: 3 / 0x3 / 0b0011
	Block location: World: (-327,45,404), Chunk: (at 9,2,4 in -21,25; contains blocks -336,0,400 to -321,255,415), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #54 (tile.chest // net.minecraft.block.BlockChest)
	Actual block data value: 3 / 0x3 / 0b0011
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1801)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)

-- Affected level --
Details:
	Level name: Galacticraft-
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 2617170230265776562
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-172,64,224), Chunk: (at 4,4,0 in -11,14; contains blocks -176,0,224 to -161,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1 game time, 1 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 100987 (now: false), thunder time: 74616 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 475663680 bytes (453 MB) / 1124700160 bytes (1072 MB) up to 4250140672 bytes (4053 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn428M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.38 Powered by Forge 13.20.1.2386 Optifine OptiFine_1.11.2_HD_U_B7 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.1.2386.jar) 
	UCHIJAAAA	forge{13.20.1.2386} [Minecraft Forge] (forge-1.11.2-13.20.1.2386.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCHIJAAAA	galacticraftcore{4.0.0} [Galacticraft Core] (GalacticraftCore-1.11.2-4.0.0.117.jar) 
	UCHIJAAAA	galacticraftplanets{4.0.0} [Galacticraft Planets] (Galacticraft-Planets-1.11.2-4.0.0.117.jar) 
	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.11.2-4.0.0.117.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.11.2_HD_U_B7
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.2.0 - Build 10.18.10.3910
	OpenGlRenderer: Intel(R) HD Graphics 4400
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by dj3520** [comment]
What were you doing when this crash happened and is it repeatable? Doesn't seem like GC caused it but I'm not an expert.

**Comment by PrincessEileen** [comment]
i was pretty much just creating a new world and then it crashes before it can load it also when i load up super flat it crashes when placing things like the rocket launch pad (i havent tested all galacticraft items) some things dont make me crash until maybe after a minute or so. also when being on the moon i crash in about a few minutes.  going into the space station instantly crashes my game as well as Jupiter and other planets

**Comment by MJRLegends** [comment]
@PrincessEileen From what i can see its crashing on MC Code and its crashing on ticking a minecraft chest
`Name: minecraft:chest // net.minecraft.tileentity.TileEntityChest`

It doesnt seem to be Galacticraft related

**Comment by radfast** [comment]
Please try it without Optifine.  That's the only thing I can think of, everything else looks normal.

**Comment by radfast** [comment]
I've looked at this some more.  I'm 99.9% sure this is caused by **Optifine**.

Maybe the Optifine version is not intended for the Minecraft/Forge version you are using?
