### ISSUE TITLE
Rockets launched by launch controllers won't land and constantly uses fuel [1.11.2]

### ISSUE THREAD

**Issue by CX-09** [micdoodle8/Galacticraft#2988]
/*Minecraft version: 1.11.2
Galacticraft version: 1.11.2-4.0.0.106
Forge version: 1.11.2-forge1.11.2-13.20.1.2386
Single player (SSP)
No other mods*/

//Not sure if this has been an issue for a long time, or if there's something I've done wrong. 
//As described in the title, cargo rockets would launch properly using the launch controller; however, it will not land on the destination launch pad. The rendering looks like the rocket has already landed, but the rocket is still using fuel at a constant rate and has a lot of steam particles around it. 
It is also the same for rockets carrying players.

I know it's best to provide a video, so sorry it's only screenshots ;)

**Experiment Setup: (the rocket used is a regular 18slot cargo rocket obtained in creative mode)**
![2017-09-23_13 30 29](https://user-images.githubusercontent.com/32228551/30776911-cb523dc4-a05b-11e7-9237-c0cde6f3d04f.png)

**Controller on the left:**
![2017-09-23_13 31 12](https://user-images.githubusercontent.com/32228551/30776915-d5ea6432-a05b-11e7-9d2d-076eaf08355c.png)
![2017-09-23_13 31 20](https://user-images.githubusercontent.com/32228551/30776921-ff03d100-a05b-11e7-942c-5d313ff2ba2d.png)

**Controller on the right:**
![2017-09-23_13 31 28](https://user-images.githubusercontent.com/32228551/30776922-00c7fcc8-a05c-11e7-9e00-9b38cd51bfec.png)
![2017-09-23_13 31 32](https://user-images.githubusercontent.com/32228551/30776929-0cb73544-a05c-11e7-9d45-170fd0e20931.png)

**Initial launch:**
![2017-09-23_13 31 46](https://user-images.githubusercontent.com/32228551/30776932-127c4578-a05c-11e7-87a6-7d78351c5ffb.png)
![2017-09-23_13 32 25](https://user-images.githubusercontent.com/32228551/30776933-1463c762-a05c-11e7-8715-7d123c8dd3fd.png)

**Landing bug (It stays like this forever)**
![2017-09-23_13 32 50](https://user-images.githubusercontent.com/32228551/30776935-18f8692c-a05c-11e7-9031-665ac90246bb.png)

**Continued combustion**
![2017-09-23_13 32 58](https://user-images.githubusercontent.com/32228551/30776937-2463edae-a05c-11e7-856a-bdb322d5246f.png)
![2017-09-23_13 33 05](https://user-images.githubusercontent.com/32228551/30776938-2700965c-a05c-11e7-9be0-75703d12962f.png)
![2017-09-23_13 33 11](https://user-images.githubusercontent.com/32228551/30776940-2ce0a012-a05c-11e7-8b18-54c1d66482c2.png)

BTW, GC is my favorite Minecraft mod! Keep up the good work micdoodle8! (๑•̀ㅂ•́)و✧

**Comment by TheQuadShot** [comment]
try updating to build 1.11.2-4.0.0.117

**Comment by CX-09** [comment]
Confirmed: It's a bug from 1.11.2-4.0.0.106 that was fixed in 1.11.2-4.0.0.117
Thanks TheQuadShot!

**Comment by radfast** [comment]
Thanks guys.

@CX-09 it's often best to try our latest build to see if a bug has been fixed :)
