### ISSUE TITLE
Missing mod screen breaks when galacticraft is installed

### ISSUE THREAD

**Issue by DeadSix27** [micdoodle8/Galacticraft#2989]
Minecraft version: 1.10.2
Galacticraft version: 1.10.2-4.0.0.117.jar
Forge version: forge-12.18.3.2488

This issue seems so obvious that I assumed it's already on here, but I couldn't find it in my search for "missing mods", "dependency", "required", "GuiModsMissing",  "NoClassDefFoundError: bxl".

Issue description:
If a mod requires another mod, forge usually shows an error like this (just an example):
![image](https://user-images.githubusercontent.com/1492505/30782216-db6a8c66-a12d-11e7-86bd-fcfd38e4c4b0.png)

However when Galacticraft and its addons are installed the game just crashes.
Here is the full log:
https://gist.github.com/DeadSix27/a08ead1c9fb80705a706b6c56cef8bf1

**Comment by TheQuadShot** [comment]
This isn't a GC problem, your still missing the ctm mod (ConnectedTextureMod). All of the files needed for GC are in the log, there are no other dependencies.

**Comment by DeadSix27** [comment]
Re-read my post. This is not about Chisel or CTM

**Comment by MJRLegends** [comment]
@DeadSix27 Your missing the CTM mod its a requirement for chisel its not optional.

**Comment by MJRLegends** [comment]
@DeadSix27 The crash is trying to rendering the screen telling you that you need this mod, the screen causing a crash isnt a GC issue. You just need to add the mod that has been explained above and you will be set

**Comment by MJRLegends** [comment]
![](https://i.gyazo.com/edf5be80a0a5b1bd6f92f945108cd6bc.png)
![](https://i.gyazo.com/6e5d9a7856e833ac49422c32eeb1b7bf.png)

**Comment by DeadSix27** [comment]
Why does everyone say that? I get that it does that because CTM is missing.. but that is not the problem.. the problem is that the forge mod missing screen does not work anymore with GC installed, instead of CRASHING out with NoClassDefFoundError: bxl it should show me a nice warning telling me im missing Mod XYZ... can you follow?

**Comment by MJRLegends** [comment]
@DeadSix27 Add CTM mod to your mods folder and then try

**Comment by DeadSix27** [comment]
@MJRLegends And then? What then then the game starts I do not even need to do that.

The issue isnt a missing mod: It is this screen not existing, see my above Edit: 
![image](https://user-images.githubusercontent.com/1492505/30812549-548d972c-a20b-11e7-923f-31e931200c68.png)

**Comment by MJRLegends** [comment]
@DeadSix27 I've saw this error about 1000 times and i make mod packs and mods trust me you need CTM mod or if not remove chisel

**Comment by DeadSix27** [comment]
@MJRLegends It is not about chisel.

**Comment by MJRLegends** [comment]
@DeadSix27 Ok right, The screen that is trying to render is the one where it says your missing the mod CTM. This screen not rendering is a Forge related thing, IF you add CTM mod to your mods folder then you will be missing no mods so this screen will never show. In which case your minecraft will run....

**Comment by MJRLegends** [comment]
Everyone who is a mod developer or mod pack developer will tell you the same thing. Im not trying to lie to you haha i know this crash i've seen it like 10000 times

**Comment by DeadSix27** [comment]
@MJRLegends Ok now you're getting closer... the issue also is not that the game can't run, its really just that that screen is bugged.. and why is that a forge issue when every single other mod works just fine with showing its missing dep except when galacticraft  is installed? Screams like an issue of GC to me

**Comment by MJRLegends** [comment]
Im out @radfast @micdoodle8 I tried :D

**Comment by DeadSix27** [comment]
@MJRLegends You were no help other than spamming more non related things.. really. 
Issue is not: Missing mods
Issue is: Rendering of the missing mods screen does not occur with GalactiCraft installed, but does fine without it.

**Comment by MJRLegends** [comment]
@DeadSix27 Add this https://minecraft.curseforge.com/projects/ctm/files/2465568 to your mods folder, as much as you think im lying to you this will fix your issue

**Comment by DeadSix27** [comment]
@MJRLegends Ok I will add it then I will add then I will add RFTools without mcjtylib, now what do you think will happen? Be real what should happen in that instance?

**Comment by MJRLegends** [comment]
@DeadSix27 Please Add the CTM mod and then you will see

**Comment by DeadSix27** [comment]
@MJRLegends I did add it and ofc it works but that was not the issue, now I added RFTools without mcjtylib .. please just tell me what should happen now when I start the game.

**Comment by MJRLegends** [comment]
Haha

**Comment by DeadSix27** [comment]
@MJRLegends No? Ok then I take it as an agreement that the missing mods screen does work fine (AS LONG AS GALACTICRAFT IS NOT IN THE MOD FOLDER)

**Comment by MJRLegends** [comment]
I sorry but i didnt say anything about the Missing Screen not being a bug. I was telling you how to get your game working so it doesnt crash

**Comment by MJRLegends** [comment]
You will see this missing mods crash with loads of mods including NEI and a few others

**Comment by MJRLegends** [comment]
Also ![](https://i.gyazo.com/358f84caa028ca7c848facfb23c9018c.png) seems to work without chisel installed

**Comment by DeadSix27** [comment]
@MJRLegends:

![image](https://user-images.githubusercontent.com/1492505/30814815-81b3bce4-a211-11e7-8490-cf47e8e12ce6.png)

**Comment by MJRLegends** [comment]
https://github.com/micdoodle8/MicdoodleCore/issues/10

**Comment by DeadSix27** [comment]
@MJRLegends Ah nice, exactly. Guess it got reported on micdoodlecore rather than GC itself. should have searched on there too (figured no one would report it there since micdoodlecore is really only used for GC the main mod and so people probably will end up reporting everything here)

**Comment by MJRLegends** [comment]
its a micdoodle core thing

**Comment by DeadSix27** [comment]
@MJRLegends and they do not know what causes it

**Comment by MJRLegends** [comment]
Probably best to close this issue up and move this to the other issue since its a issue with that mod

**Comment by DeadSix27** [comment]
Closed, See: https://github.com/micdoodle8/MicdoodleCore/issues/10

**Comment by radfast** [comment]
@DeadSix27 was correct to report this - except that it's already an open issue!   I mean, we know that it is an issue somehow caused when MicdoodleCore is present.

As stated in the open issue linked above ^^^^^^^^^^^^^^^^^ we have not been able to find or fix the actual cause of this yet, even though I've spent around 1 day on it.  Hoping eventually inspiration will strike or someone else will find a good solution.

**Comment by DeadSix27** [comment]
Would it be bad asking the forge team for advice here? Since your team seems to be out of ideas
