### ISSUE TITLE
Tiny Armor Rendering Inside Actual Armor (and minecraft:skull bug)

### ISSUE THREAD

**Issue by Doodled** [micdoodle8/Galacticraft#2990]
Minecraft version: 1.11.2
Galacticraft version: [full list of mods below]
Forge version: forge1.11.2-13.20.0.2296

SMP server.

Full Mods Folder List:
- Aether-2-Mod-1.11.2
- backpacks 1.11.2 - 3.3.0
- BiblioCraft[v2.3.3][MC1.11.2]
- buildcraft-7.99.6
- **GalacticraftCore-1.11.2-4.0.0.117**
- **Galacticraft-Planets-1.11.2-4.0.0.117**
- HarvestCraft-Mod-1.11.2
- Industrial-Craft-2-Mod-Experimental-1.11.2
- **MicdoodleCore-1.11.2-4.0.0.117**
- ProjectE-1.11.2-PE1.0.0B

This glitch does not occur when Galacticraft is not installed on the server.

![2017-09-24_04 41 01](https://user-images.githubusercontent.com/32237970/30781444-918d0162-a0e4-11e7-84ac-47ab763331f5.png)

You can see in the prior image someone with iron leg armor and boots, with a second pair of smaller armored legs sticking out from between them.

This does not happen when someone does not have armor on. It appears to only be the armor itself that is being re-rendered.

![2017-09-24_04 41 19](https://user-images.githubusercontent.com/32237970/30781445-918e0594-a0e4-11e7-883d-59dd471a738a.png)

It also appears this way in the inventory screen. This character is wearing glasses, and also appears to be wearing glasses on their lower torso, as a result of the glitch.

![2017-09-24_04 52 04](https://user-images.githubusercontent.com/32237970/30781447-9190d26a-a0e4-11e7-86cc-d1d2391f5bf5.png)

As a possibly-related glitch, when someone puts on a minecraft:skull object of someone's head, as shown in the image above, the head does not rotate with the actual player's head, but instead rotates with their body.

**Comment by radfast** [comment]
This glitch also does not occur when only Galacticraft is installed, so it must be an interaction with one of your other mods.  Please test which one it is and let us know.   When you can identify: Galacticraft + _other named mod_ creates this problem, we can start to look for a solution.

**Comment by marcus8448** [comment]
Skull bug happens with only Galacticraft installed.

**Comment by marcus8448** [comment]
(Build 118)

**Comment by Desektion** [comment]
Hate to bump this but I have the same problem. But on 1.10.2, 
GalactiCraft 4.0.0.119,
Forge Version: forge-1.10.2-12.18.3.2511-universal (latest)

The only mods I have that are similar to OP is IC2, and ProjectE.

So I removed both of them and tried again and I still have the same problem. 

![2017-11-23_01 33 19](https://user-images.githubusercontent.com/24522834/33160945-6f86f13e-cfee-11e7-831f-5315b4ce6a9e.png)

**Comment by Desektion** [comment]
Going down Galacticraft versions to the Promoted version Galacticraft 4.0.0.106 fixes the problem.

(IC2 and ProjectE are both installed still when I did this screenshot)
![2017-11-23_01 43 02](https://user-images.githubusercontent.com/24522834/33161187-c844f0c2-cfef-11e7-8f0a-2de2681f29fc.png)

**Comment by Doodled** [comment]
The bug still happened when only Galacticraft was installed.

_However,_ Desektion's solution with installing RenderPlayerAPI actually works! Thanks!

**Comment by roboderpy** [comment]
PlayerAPI resolve all conflicts/bugs related to galacticraft interaction between mods

**Comment by radfast** [comment]
Galacticraft has full support for **PlayerAPI** and **RenderPlayerAPI**, to resolve compatibility issues _with other mods which also support those API's_

**Comment by radfast** [comment]
The skull issue is now fixed, thanks for the report and sorry it took a while to get to this.

Seems that the armor issue can be fixed using RenderPlayerAPI.  It would still be good to know **which** of those 5 or so other mods is causing the armor conflict...

**Comment by radfast** [comment]
I've tested and discovered it's Aether II conflicting ... now to figure out why.

**Comment by radfast** [comment]
This is fixed in next version :)

**Comment by Celophy** [comment]
help, i have the same problem in 1.12, i can't fix it!!

**Comment by TheQKnight** [comment]
its been like a year and its not fixed...
