### ISSUE TITLE
[1.11.2] Rockets & Astro miners are not animated anymore

### ISSUE THREAD

**Issue by marcus8448** [micdoodle8/Galacticraft#2992]
Minecraft version: 1.11.2
Galacticraft version: Build 117
Forge version: 13.20.1.2476

Single player (SSP) or Multiplayer (SMP)? SSP

Galacticraft add-ons and other mods installed? Galacticraft Planets, JEI, Micdoodlecore

So in my inventory the Astro miner and the rockets (also the moon buggy if it is animated) are not spinning around in circles like they used to.

**Comment by marcus8448** [comment]
Also happens wo/ JEI

**Comment by radfast** [comment]
> like they used to

What changed when this stopped?  They still spin for me.

**Comment by EzerArch** [comment]
> So in my inventory the Astro miner and the rockets (also the moon buggy if it is animated) are not spinning around in circles like they used to

Wild guess: check your video settings. Go to Options > Video settings > Graphics: **Fancy**

If Optifine user, **also** go to: Options > Video settings > Animations > Items Animated: **On**

*(/me back to his cave.)*

**Comment by marcus8448** [comment]
Oh my bad. Works now thanks @EzerArch :)
