### ISSUE TITLE
[1.11.2] When i load it in Technic...

### ISSUE THREAD

**Issue by darraross** [micdoodle8/Galacticraft#2993]
Minecraft version: 1.11.2
Galacticraft version: 4.0.0.117 and 4.0.0.106
Forge version: I dont know

when i load galacticraft in technic launcher with JEI and optifine it pops up saying that "galacticraft core requires these mods(and it doesnt list any mod, then it goes on to say) add these mods or remove galacticraft core"

**Comment by marcus8448** [comment]
You three files GalacticraftCore MicdoodleCore and Galacticraft Planets

**Comment by marcus8448** [comment]
Not only one file

**Comment by radfast** [comment]
maybe @marcus8448 answered your question

If you still have problems:
1. read the [installation guide](https://wiki.micdoodle8.com/wiki/Tutorials/Galacticraft_Installation_Guide)
2. post a screenshot of your /mods folder or whichever folder the technic launcher is using for the modlist
