### ISSUE TITLE
Game crashes when i put the IC2 Pump machine to galacticraft crude oil.

### ISSUE THREAD

**Issue by spomacmega** [micdoodle8/Galacticraft#2996]
Minecraft version:1.11.2
Galacticraft version:4.0.0.117
Forge version:13.20.0.2315

Single player (SSP)

Galacticraft add-ons and other mods installed?
Industrial craft 2
Optifine

Please provide screenshots / crash report / log as needed.
Crash report won't showup. It just the game disappear when it crash (but the game still running in the processes tab in the Windows task Manager. So every time i exit the game i need to manually end process the javaw.exe)
Please help how can i remove the Pump machine i placed in the crude oil.

**Comment by radfast** [comment]
likely related to #2973 and #2980 

we'll work on fixing those and that will hopefully solve this as well - please keep an eye out for build 119 and let us know if that fixes it for you.
