### ISSUE TITLE
[1.7.10] spawn on moon bug

### ISSUE THREAD

**Issue by weitox** [micdoodle8/Galacticraft#2999]
Minecraft version:1.7.10
Galacticraft version:1.7-3.0.12.502 

Forge version:10.13.4.1614

Single player (SSP) 

Galacticraft add-ons and other mods installed?
Galacticraft Add-on -More Planetes (1.7.10-1.42-GC502.jar)
Galacticraft-Planets (1.7-3.0.12.502)

I have no crash reports bug after creating new world my minecraft crashs.
If I start it after that I spawn on Moon and (/tpx 0) doesn t work. I think that somehow
my minecraft puts moon on tpx id to 0 and delets Overworld id. Mystcraft linking books 
dont work too. I just spawn everytime on moon. 
It could not be compatible with the other mods.

![mods](https://user-images.githubusercontent.com/32393487/31020546-95ad21e8-a533-11e7-94e5-bc34d78cc567.PNG)

Thats the chat when I join again.

![chat](https://user-images.githubusercontent.com/32393487/31020682-f9217b98-a533-11e7-94b1-3c73a4012ea9.PNG)

**Comment by AugiteSoul** [comment]
More Planets has an option to make you spawn on a specific GC dimension. Go read its config.

**Comment by weitox** [comment]
I just disabled all mods except the galacticraft mods and creadet a world.After that I activadet all mods that worked pretty good. But thank you anyway.

**Comment by radfast** [comment]
Could have been a strange interaction between Mystcraft and Galacticraft, though normally both mods play OK together.

Anyhow, you fixed it so no action is needed.
