### ISSUE TITLE
[1.7.10] No Oxygen detected, with correct gear 

### ISSUE THREAD

**Issue by gooseapple5** [micdoodle8/Galacticraft#3001]
Minecraft version:1.7.10
Galacticraft version:502
Forge version:10.13.4.1614

Singeplayer

Galacticraft Core,Galacticraft Planets, Mcdoodlecore, and **Galaxy Space**

![2017-10-01_16 43 14](https://user-images.githubusercontent.com/32470858/31104323-fa0bd790-a7a1-11e7-878b-6b9c97625ab7.png)

Galacticraft doesn't recognize that I have an oxygen mask on, yet still drains the oxygen from the tank.

EDIT: Just figured out that the mod "Advanced Rocketry" was causing this, the two oxygen systems do not seem to work, if you know how to make it compatible that would be appreciated, thanks.

**Comment by MJRLegends** [comment]
Does it work without Galaxy Space? @gooseapple5

**Comment by gooseapple5** [comment]
No it doesnt, and ive reinstalled, got new versions too.

**Comment by gooseapple5** [comment]
None work

**Comment by radfast** [comment]
It's up to **Advanced Rocketry** to fix this, the "no oxygen detected" message is on their side.

We provide an oxygen API which they can use if they want to.  IIRC, Advanced Rocketry for 1.7.10 is dependent on Galacticraft so I'm not sure why they are not using it.  If there's a problem with the API, I'm sure the Advanced Rocketry devs will let us know.
