### ISSUE TITLE
[1.11.2] You can make a double Astro Miner Base

### ISSUE THREAD

**Issue by marcus8448** [micdoodle8/Galacticraft#3003]
I don't know if this is fixable or not but you can create a double Astro Miner Base.
```
Minecraft version: 1.11.2
Galacticraft version: Build 118
Forge version: 13.20.1.2386
```

Single player (SSP) or Multiplayer (SMP)?   SSP        (SMP is untested)

Galacticraft add-ons and other mods installed? Nope

Please provide screenshots / crash report / log as needed.
Double Astro Miner Base
![2017-10-07_21 08 49](https://user-images.githubusercontent.com/28928887/31313825-9319d82e-aba3-11e7-8445-cd1a2a7dd953.png)

How to reproduce:

1: Make this shape out of astro miner bases:

![2017-10-07_21 12 25](https://user-images.githubusercontent.com/28928887/31313841-0d4613e2-aba4-11e7-9413-3e445fcd8317.png)

2: Fill in the gap

**Comment by radfast** [comment]
Thank you, great screenshots.  Guess didn't think of the "fill in the gap" scenario ...

This should be fairly easily fixable in code.

**Comment by radfast** [comment]
Fixed from next build 161.  Thanks again for the careful report.
