### ISSUE TITLE
No te ahogas en los liquidos y debajo el agua puedes picar de forma normal

### ISSUE THREAD

**Issue by yerbuky** [micdoodle8/Galacticraft#3005]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.10.2
Galacticraft version: 118
Forge version: 2281

Single player (SSP) or Multiplayer (SMP)? SSP and SMP

Galacticraft add-ons and other mods installed? no

Please provide screenshots / crash report / log as needed.

No puedes ahogarte en los liquidos, como el oil, combustible o acidos, al igual que cuando estás dentro del liquido, se ve como si no hubiera liquido y puedes andar y picar sin problemas. en immersive ingeneering los efectos son correctos. 

foto:
![sin titulo-1](https://user-images.githubusercontent.com/10607719/31473645-2ffc5af4-aef6-11e7-9583-5161d9fb786c.jpg)

**Comment by SteveKunG** [comment]
English please....

**Comment by marcus8448** [comment]
"
You can not drown in liquids, like oil, fuel or acids, just like when you are inside the liquid, it looks like there is no liquid and you can walk and chop without problems. in immersive ingeneering the effects are correct ." According to Google Translate

**Comment by SteveKunG** [comment]
#1623

**Comment by radfast** [comment]
Fixed in build 133.

**Comment by radfast** [comment]
Build 133 is now available from the download site.

Also has a really nice new feature: **Hydraulic Platform** :)
