### ISSUE TITLE
[1.10.2] Electric Compressor ingredients disappear on automating complex recipes

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft#3006]
See https://github.com/MJRLegends/Space-Astronomy-2-Feedback-/issues/151 for details as there is quite a lot of information on it there

Minecraft version: 1.10.2
Galacticraft version: Build 117
Forge version: 12.18.3.2422

Single player (SSP) or Multiplayer (SMP)? Both

Galacticraft add-ons and other mods installed? Yep ExtraPlanets

**Comment by radfast** [comment]
It appears to be a Refined Storage issue.

This is not a valid Galacticraft recipe:
https://user-images.githubusercontent.com/10009510/31406938-6df4e3b0-ae03-11e7-8590-4896d526c040.png

I don't know why the Refined Storage uses up all its store of plates, but basically, if it does not give the Electric Compressor a valid recipe, then nothing is going to be made.

I don't know why it can't give a valid recipe, it looks like it was able to put two plates of Compressed Steel into different slots.

**Comment by MJRLegends** [comment]
Yeah thats what i thought was wrong, is there anything that can be done from galacticraft as the refined storage dev isnt updating anything but 1.12.2 version

**Comment by radfast** [comment]
No, nothing we can do.  We are returning a correct result for ```isItemValidForSlot()```, that's how vanilla Hoppers are able to work correctly with the Galacticraft machine.  Refined Storage accesses the machine the same way as a vanilla Hopper only more sophisticated - the Hopper tries all the slots randomly, the Refined Storage tries specific slots.

**Comment by MJRLegends** [comment]
Ok will just tell users to put in to in a hopper before the machine

**Comment by radfast** [comment]
Exactly.  Your players can just place a vanilla Hopper as an interface between the Refined Storage and the Electric Compressor.  Give the vanilla Hopper 2 x Compressed Steel, 2 x Compressed Aluminium, 2 x Compressed Bronze and then the correct plates should be made automatically.

**Comment by MJRLegends** [comment]
yeah
