### ISSUE TITLE
Crash related to weather cycle

### ISSUE THREAD

**Issue by chaNcharge** [micdoodle8/Galacticraft#3007]
Description: This is my best guess when looking at the crash report, but from what I can tell, the mod is trying to make it rain on the space station, but the gamerule doWeatherCycle is set to false. It's a little difficult to reproduce since it's kind of random.

[crash-2017-10-15_19.43.06-server.txt](https://github.com/micdoodle8/Galacticraft/files/1386104/crash-2017-10-15_19.43.06-server.txt)

Minecraft version: 1.11.2
Galacticraft version: 4.0.0.106
Forge version: 13.20.1.2513

Single player (SSP) or Multiplayer (SMP)? Single player

Galacticraft add-ons and other mods installed? None

Please provide screenshots / crash report / log as needed.

Crash report on pastebin (in case github one doesn't work): https://pastebin.com/WHzTRAXc

UPDATE: I am unable to return to the world, the game gives the same crash report
UPDATE 2: Was able to reenter the world by changing the rain time and thunder time in the NBT data. This issue is definitely related to the weather in game, not the gamerule.

**Comment by MJRLegends** [comment]
This jas already been fixed you just need to update your GC version as your on 106 and the latest is 118

**Comment by MJRLegends** [comment]
See #2924

**Comment by chaNcharge** [comment]
Oh ok, I just use the promoted builds as they're advertised as a stable build. Thank you.

**Comment by MJRLegends** [comment]
Yeah build 118 is stable enough for use
