### ISSUE TITLE
[1.7.10] All Moon treasure chests empty

### ISSUE THREAD

**Issue by TiranDirth** [micdoodle8/Galacticraft#3010]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.7.10
Galacticraft version: 3.0.12.502
Forge version: 10.13.4.1614

Single player (SSP) or Multiplayer (SMP)? Tested on both

Galacticraft add-ons and other mods installed? Tested with and without Galaxy Space 1.1.9

Please provide screenshots / crash report / log as needed.

I don't really have a log that appears to help here, I'm fairly technically competent and can happily dig through and try to find whatever might shed some light. This is what the log spits out over the time from just before I found the dungeon to when I spawned a key to check the loot.

[B#353]  [22:01:19] [Server thread/INFO] [FML]: Generating Moon Village at x848 z576
[B#353]  [22:01:52] [Server thread/INFO] [FML]: Generating Moon Village at x736 z656
[B#353]  [22:02:01] [Server thread/INFO] [FML]: Generating Moon Village at x752 z752
[B#353]  [22:03:41] [Server thread/INFO] [FML]: Generating Moon Village at x560 z1120
[B#353]  [22:04:18] [Client thread/INFO]: [CHAT] Boss despawned, don't leave the boss room while fighting! Re-enter room to respawn boss.
[B#353]  [22:04:19] [Client thread/INFO] [inventorytweaks]: net.minecraft.client.gui.inventory.GuiContainerCreative
[B#353]  [22:04:19] [Client thread/INFO] [inventorytweaks]: net.minecraft.client.gui.inventory.GuiContainerCreative$ContainerCreative
[B#353]  [22:04:25] [Client thread/INFO] [FML]: DRAGONAPI: No texture packs contain an image for Textures/TileEntity/altartex.png. Loading default.
[B#353]  [22:04:25] [Client thread/INFO] [FML]: DRAGONAPI: Pipelining texture from Reika.ChromatiCraft.ChromatiCraft to Textures/TileEntity/altartex.png
[B#353]  [22:04:25] [Client thread/INFO] [FML]: DRAGONAPI: No texture packs contain an image for Textures/aurapoint2-grid.png. Loading default.
[B#353]  [22:04:25] [Client thread/INFO] [FML]: DRAGONAPI: Pipelining texture from Reika.ChromatiCraft.ChromatiCraft to Textures/aurapoint2-grid.png
[B#353]  [22:04:25] [Client thread/INFO] [FML]: DRAGONAPI: No texture packs contain an image for Reika/ChromatiCraft/Textures/Items/items_color.png. Loading default.
[B#353]  [22:04:25] [Client thread/INFO] [FML]: DRAGONAPI: Pipelining texture from Reika.ChromatiCraft.ChromatiCraft to /Reika/ChromatiCraft/Textures/Items/items_color.png
[B#353]  [22:04:25] [Client thread/INFO] [FML]: DRAGONAPI: No texture packs contain an image for Reika/ChromatiCraft/Textures/Items/shardglow.png. Loading default.
[B#353]  [22:04:25] [Client thread/INFO] [FML]: DRAGONAPI: Pipelining texture from Reika.ChromatiCraft.ChromatiCraft to /Reika/ChromatiCraft/Textures/Items/shardglow.png
[B#353]  [22:04:25] [Client thread/INFO] [FML]: DRAGONAPI: No texture packs contain an image for Reika/ChromatiCraft/Textures/Items/items_colormod.png. Loading default.
[B#353]  [22:04:25] [Client thread/INFO] [FML]: DRAGONAPI: Pipelining texture from Reika.ChromatiCraft.ChromatiCraft to /Reika/ChromatiCraft/Textures/Items/items_colormod.png
[B#353]  [22:04:25] [Client thread/INFO] [FML]: DRAGONAPI: No texture packs contain an image for Reika/ChromatiCraft/Textures/Items/throwablegems.png. Loading default.
[B#353]  [22:04:25] [Client thread/INFO] [FML]: DRAGONAPI: Pipelining texture from Reika.ChromatiCraft.ChromatiCraft to /Reika/ChromatiCraft/Textures/Items/throwablegems.png
[B#353]  [22:04:29] [Server thread/INFO]: [CHARNAME: Given [Tier 1 Dungeon Key] * 1 to CHARNAME]
[B#353]  [22:04:29] [Client thread/INFO]: [CHAT] Given [Tier 1 Dungeon Key] * 1 to CHARNAME

Modlist:
Another One Bites the Dust
AE2
Baubles
Bibliocraft
Botania
Buildcraft
Carpenters Blocks
Chisel 2
Chromaticraft
CodeChickenCore
Damage Indicators
Dragon API
Ender IO
EnderCore
Extra Cells 2
Extra Utilities
ExtraTiC
Forestry
Forge Microblocks
Galacticraft Core
Galacticraft Planets
GalaxySpace
GeoStrata
Harcore Ender Expansion
Hats
iChunUtil
Iguana Tinker Tweaks
INpureCore
Inventory Tweaks
JourneyMap
Mantle
Mekanism
Mekanism Generators
Mekanism Tools
Metallurgy 4
Micdoodle8 Core
MineTweaker 3
MineTweakerRecipeMaker
Mod Tweaker 2
Morpheus
MrTJPCore
Natura
NEI
OpenBlocks
OpenMods
OpenModsCore
ProjectRed Core
Railcraft
The Twilight Forest
Thermal Dynamics
Thermal Expansion
Thermal Foundation
Tinkers' Construct
Waila
Waila Harvestability
Witchery

**Comment by MJRLegends** [comment]
Did you fight the boss?

**Comment by TiranDirth** [comment]
Aha, I'm a dumbass.

The first dungeon had spawned without a treasure room, so I ended up running past the boss in the second dungeon to just open the chest with the key from the first. After that I just spawned keys and kept checking with and without different mods.

It worked fine when the right boss was killed.

**Comment by EzerArch** [comment]
> **The chest loot is generated on boss death**, so it is impossible to get the loot without defeating the boss. The loot generation is random: you can generate the same world and defeat the same boss but the loot will likely be different. 
https://wiki.micdoodle8.com/wiki/Treasure_Chest#Contents
