### ISSUE TITLE
Desh Block not oredicted.

### ISSUE THREAD

**Issue by BrisingrAerowing** [micdoodle8/Galacticraft#3012]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Desh Blocks are not oredicted as blockDesh, causing PlusTiC to not register a block recipe for them using Molten Desh (from said mod).

See Landmaster/PlusTiC#121 for the issue there.

Minecraft version: 1.10.2
Galacticraft version: 4.0.0.118
Forge version: 12.18.3.2488

Single player (SSP) or Multiplayer (SMP)? SSP

Galacticraft add-ons and other mods installed? Extra Planets

Please provide screenshots / crash report / log as needed.

**Comment by radfast** [comment]
Fixed by #3016, thanks to @MJRLegends.

This fix will be included in next Galacticraft build 119.
