### ISSUE TITLE
High TPS during first world generation

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#3014]
Minecraft version: 1.10.2
Galacticraft version: Dev
Forge version: 1.10.2 Latest

Moon Overall TPS: 80+ (0.2-2 tps for a moment)
Asteroids Overall TPS: 60+ (1-3 tps for a moment)
Venus Overall TPS: 95+ (2-6 tps for a moment)

First time I teleport to the Mars and I got 80+ TPS on Mars and Overall TPS 100+
![2017-10-27_00 39 53](https://user-images.githubusercontent.com/6128413/32068456-991e0396-bab0-11e7-9a10-834fec1533cd.png)

Stay for awhile
![2017-10-27_00 41 23](https://user-images.githubusercontent.com/6128413/32068533-cfa9ed6c-bab0-11e7-9488-14b820d2a522.png)

/kill myself, TPS is the same as flat world
![2017-10-27_00 45 47](https://user-images.githubusercontent.com/6128413/32068565-da54a0f4-bab0-11e7-9fd9-f0abf3babeaf.png)

**Comment by MJRLegends** [comment]
You sure its not just the mapping thread getting thrown in to the tps time?
