### ISSUE TITLE
A question regarding a 1.12 update

### ISSUE THREAD

**Issue by Go-Wish** [micdoodle8/Galacticraft#3017]
Didn't know where was best to post this. But, I was wondering if y'all are planning on making a 1.12 version, and if so whether that has been started yet.

**Comment by TheQuadShot** [comment]
Please post these type of questions on the website and forums. They can be found here:
https://wiki.micdoodle8.com/

**Comment by Go-Wish** [comment]
Alright, thanks.

**Comment by radfast** [comment]
1.12.2 is now available to [download](https://www.micdoodle8.com/mods/galacticraft/downloads)
