### ISSUE TITLE
Drifting off into space while in creative mode on space station.

### ISSUE THREAD

**Issue by NoahJelen** [micdoodle8/Galacticraft#3018]
Minecraft version:1.11.2
Galacticraft version: 4.0 Build 118
Forge version: 
I don't know if this is intended or not, but I keep drifting away from my space station when I am trying to build on it in creative mode! Could someone please make it so creative mode players stay in the same spot without drifting into space? It's driving me crazy!
Here is a video 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/29718341/32084094-09aca8f4-ba7c-11e7-9a8c-73b363d715e2.gif)
of what I'm talking about:

**Comment by TheQuadShot** [comment]
I wouldn't call this a bug.... Your in zero G, and it's been this way for as long as I can remember. There is a forum for suggestions on the web site here:
https://wiki.micdoodle8.com

**Comment by NoahJelen** [comment]
I wasn’t drifting almost uncontrollably though. It used to be slow falling where I’d jump up and I would fall extremely slow.

**Comment by EzerArch** [comment]
Did you place [Spin Thrusters](https://wiki.micdoodle8.com/wiki/Spin_Thruster)? Remove them or  (depending on the version) switch them off via redstone.

**Comment by NoahJelen** [comment]
Thanks for the idea. I’ll place levers by them to switch them off while I’m building on my space station.

**Comment by EzerArch** [comment]
You might want to close this issue, if solved. ;)
