### ISSUE TITLE
Suggestion: teleportation to a player’s space station

### ISSUE THREAD

**Issue by NoahJelen** [micdoodle8/Galacticraft#3021]
This is not an issue but a suggestion. In the next build of galacticraft 4, can guys put in the ability for players to go to their own space station by going above a certain height in the overworld please?

**Comment by dj3520** [comment]
[Suggestions go on the forum not the issue tracker. Read the contributing guidelines.](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md#what-else-is-not-ok-on-the-issues-list)

**Comment by NoahJelen** [comment]
Sorry

**Comment by EzerArch** [comment]
Please close the issue.
