### ISSUE TITLE
[1.8+] Weird Shield Controller Behaviour with Addons

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft#3022]
Minecraft version: 1.8+ Currently working/testing on 1.10.2
Galacticraft version: Build 118
Forge version: 12.18.3.2511

Galacticraft add-ons and other mods installed? ExtraPlanets

Ok so,

When going to one of my custom planets in my addon and the shield controller is equipped it stops all damage to armour from damage such as explosions, mobs, etc. As soon as i take this shield controller off i start getting damage taken from my amour.

The planet im currently on is a non corrosive basics, but testing on one that is set to be corrosive like venus it still breaks the armour taking damage from other effects but the corrosive works on custom planets

**Comment by radfast** [comment]
Sounds like it is working as intended.

The Shield Controller when equipped stops **all** damage to your armour, similar to having an Unbreaking X enchantment.  Yes, it's intended to be an OP item.  And actually it won't stop certain forms of true damage, it only stops the normal effects where armour takes damage when the player takes damage.

**Comment by MJRLegends** [comment]
@radfast Can we at least have a api way to turn it off or make it not do it when corrosive is off

**Comment by radfast** [comment]
I don't understand why you want an API to turn it off.  The purpose of the Shield Controller item is to provide this protection **throughout the game**, so that players don't have to worry about durability when they have valuable armor.  Yes, it's OP, but the player has to reach Venus to get the item so it's very much an end-game item.

**Comment by MJRLegends** [comment]
@radfast Having to auto be hardcoded to do this for custom planets and moons means that no addon can have armour with durability systems, and i really wanted to have durability for my space suits.

Would be amazing if you can add a way to allow us to change this our custom content only :D
