### ISSUE TITLE
[1.7.10] Stuck in planet selection menu

### ISSUE THREAD

**Issue by lelodragneel** [micdoodle8/Galacticraft#3023]
I am stuck in the Planet Selection Menu, not able to exit. I have tried restarting the server and killing myself from console with no luck. What can I do?

Minecraft version: 1.7.10
Galacticraft version: GalacticraftCore-1.7-3.0.12.502 with Galacticraft-Planets-1.7-3.0.12.502
Forge version: forge-1.7.10-10.13.4.1614-1.7.10-universal

Single player (SSP) or Multiplayer (SMP)?
Multiplayer. It's a server.

Galacticraft add-ons and other mods installed?
GalaxySpace-1.1.9 STABLE.jar

**Comment by MJRLegends** [comment]
Please test without Galaxy Space as i know he has a custom planet screen and is probably why your getting the issue in which case its a issue for that addon mod dev

**Comment by lelodragneel** [comment]
I appreciate the fast reply, I will try that right now.

**Comment by lelodragneel** [comment]
Alright, I was able to select the overworld and launching to that planet as an OP after setting enableNewGalaxyMap to false under core.conf.

**Comment by MJRLegends** [comment]
yeah, this is a Galaxy Space issue please report it to the mod dev of that mod

**Comment by radfast** [comment]
thanks @MJRLegends
