### ISSUE TITLE
Rocket Without fuel just falls, still plays sound.

### ISSUE THREAD

**Issue by marcus8448** [micdoodle8/Galacticraft#3025]
Minecraft version: 1.11.2
Galacticraft version: 118 -120
Forge version: 1.11.2-13.20.1.2386

Single player (SSP) or Multiplayer (SMP)? SIngle player

Galacticraft add-ons and other mods installed? JEI (only)

Please provide screenshots / crash report / log as needed.
If you have a rocket that runs out of fuel on the way, the rocket falls down and nothing happens, but the sounds still play the rocket falls hits the ground and does nothing (and screen still shakes while in the rocket)
![2017-11-06_19 55 44](https://user-images.githubusercontent.com/28928887/32476500-9af53908-c32c-11e7-8fb5-e3c37bf5f5dd.png)
(If this is intended behavior then I think it should at least stop the sound)

**Comment by radfast** [comment]
This issue is fixed in new build 128 - thanks to @MJRLegends  :)
