### ISSUE TITLE
[1.7.10][Incompatibility/Bug With Ambience 1.0-3 Mod] Custom Music is overlapped by vanilla music in main menu due to GCcore

### ISSUE THREAD

**Issue by Sfven** [micdoodle8/Galacticraft#3026]
@radfast 
So it appears that the Ambience mod (by Vazkii) v1.0-3 (latest version of this mod for MC 1.7.10) and GalacticraftCore v1.7-3.0.12.502 (also latest version of GC for MC 1.7.10 last I checked) have compatibility issues.

I am working on a custom main menu (via the Custom Main Menu mod) for my modpack. In this main menu I wanted some custom ambience music, so I downloaded the latest version (for MC 1.7.10) of the Ambience mod, which seems to be the only mod that does this custom ambience stuff. 

The idea is that when you start the game, the music on the main menu will be a custom song. The Ambience mod does indeed start to play the custom song, however it is overlapped by vanilla music as well. I tested to see if it was Ambience's fault by removing _all_ other mods to see if the issue persisted. It did not, so I was forced to use the process of elimination on all 240ish mods to see which mod was causing this issue. As you have probably guessed by now, it was GalacticraftCore causing the vanilla music to overlap the custom music.

So I did a little research and found some potentially helpful stuff that might aid you in (hopefully) fixing this issue:

-[This](https://github.com/micdoodle8/Galacticraft/commit/f75afdb4d93e7d729982d7c76d7d7622124a565d) might be the change that caused Galacticraft to do this issue, not 100% sure though.

-Here is the [GitHub](https://github.com/Vazkii/Ambience/blob/master/ambience.properties.example) for the Ambience mod as well as its [download](https://minecraft.curseforge.com/projects/ambience-music-mod/files) page.

-I believe that Vazkii has attempted to fix an issue similar to this, and he did, however I believe GCcore is overriding his edit. Either way, [here](https://github.com/Vazkii/Ambience/commit/a15776cef0bf7013d176b8deff39361f61ab8d8e) is the edit he made to fix an overlapping issue.

-I have also opened an issue on Vazkii's GitHub [here](https://github.com/Vazkii/Ambience/issues/52) about this.

Good Luck ;)

Minecraft version: 1.7.10
Galacticraft version: 1.7-3.0.12.502
Forge version: 10.13.4.1614

Single player (SSP) or Multiplayer (SMP)?
-Main Menu, so neither
Galacticraft add-ons and other mods installed?
-Ambience v1.0-3
Please provide screenshots / crash report / log as needed.
-Forge log file can be found [here](https://drive.google.com/file/d/10nO8EutVWUdK0hE9yeFqaysX6uiqwui_/view?usp=sharing)

**Comment by Sfven** [comment]
To recreate the issue, grab Ambience v1.0-3, GCcore .502 and Forge 10.13.4.1614

Then simply configure Ambience mod to play a custom song in main menu (should only take like 60 seconds to configure).

And bam, you should then hear your custom song and vanilla music playing at the same time. Then remove GCcore, and this will stop happening and Ambience will function how it should. So maybe we can add compatibility for Ambience mod in a new 1.7.10 version?

**Comment by radfast** [comment]
I'm sorry, I don't have time to look at an issue like this.

- 1.7.10 is no longer in development apart from fixing game-breaking bugs
- this is not game-breaking, it's cosmetic only
- this affects only a very small percentage of players (people who want to do like you with a custom song in the main menu)
- it is not obvious how Galacticraft can be affecting this, the code you linked to has no possible relevance, and we are not watching any ```MusicEvent```.

If you or @Vazkii or any other coder can show exactly what in GalacticraftCore is causing this, and maybe post a PR, then we will happily incorporate it, but I don't have time to investigate myself.
