### ISSUE TITLE
[JourneyMap] Bug with custom teleport mods

### ISSUE THREAD

**Issue by BadLucKWyvern** [micdoodle8/Galacticraft#3029]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version:1.11.2
Galacticraft version:4.0.0.118
Forge version: 1.11.2-forge1.11.2-13.20.1.2510

Single player (SSP) or Multiplayer (SMP)? single

Galacticraft add-ons and other mods installed? extraplanets

Please provide screenshots / crash report / log as needed.

I reached the moon with the tier 1 rocket, but ive forgotten the oxygen, so i used a teleport point from Journeymap to come back at spawn and collecting oxygen on earth, but on earth, each time i take damages im jumping like if i didn't left the moon, and the StrongLeg upgrade armor from Blood magic is automaticaly farmed even without moving/jumping (jump upgrade that increase by jumping)
and i now have difficulties to mine some blocks...

**Comment by MJRLegends** [comment]
Please can you provide the fml-latest-client.log file

**Comment by BadLucKWyvern** [comment]
where can i find it ? :d

**Comment by BadLucKWyvern** [comment]
i came back on earth with the rocket and all is back to normal, im suspecting a teleport throught dimention make it bugged

**Comment by radfast** [comment]
Thanks for reporting.

Can you make this happen **again** using JourneyMap teleport again to move from Moon to your spawnpoint on Earth?

**Comment by BadLucKWyvern** [comment]
the gravity is different when i take damages on earth im forced to jumping
like if i didn't changed dimension :l
and the jumping buff on living armor from blood magic is farmed without
jumping


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-11-18 19:27 GMT+01:00 Galacticraft developer <notifications@github.com>
:

**Comment by radfast** [comment]
Note to self and other devs: this is likely related to [this](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/entities/player/GCPlayerHandler.java#L107)

**Comment by radfast** [comment]
Seems to be OK now in my testing of 141.

Any problems like this, please comment here or open a new issue.

**Comment by BadLucKWyvern** [comment]
Ill not be able to test now. Ive found a new job. So im not playing a lot
(maybe anymore) to minecraft now :s
I hope that will work when ill be back :3

**Comment by radfast** [comment]
@BadLucKWyvern good luck with your new job.  Don't worry about testing, this is something which I'm sure @MJRLegends and other people making modpacks will do!
