### ISSUE TITLE
[1.11.2] Moon day/night cycle thrown out of sync by sleeping

### ISSUE THREAD

**Issue by kyleedwardsny** [micdoodle8/Galacticraft#3030]
Minecraft version: 1.11.2
Galacticraft version: 4.0.0.118
Forge version: 13.20.1.2386

Single player (SSP)

Galacticraft and Galacticraft Planets, no other mods

I spent several (real-world) days getting everything I needed to go to the moon. I lifted off maybe 1 or 2 days after the full moon, which I assumed should have meant broad daylight when I got to the moon. But when I got there, it was the middle of the night! I ended up burying myself in a 1x1x2 hole waiting for the sun to rise because of how dangerous the moon is at night.

I have reproduced the issue in creative mode. Steps:

1. Make a Creative world.
2. Open the debug screen by pressing F3. You will see that it says "Day 0".
2. Place a bed.
3. `/set time night`
4. Sleep in the bed.
5. Open the debug screen. You will see that it now says "Day 1".
6. Use a Creative pre-fuelled rocket to get to the moon.
7. Open the debug screen. Instead of saying "Day 1", it says "Day 0".

**Comment by kyleedwardsny** [comment]
Never mind. I see that the time sync behavior was changed because of #2643. I wish I had known... is there a way to see the current time on the moon so I can plan this better next time?

**Comment by EzerArch** [comment]
> is there a way to see the current time on the moon so I can plan this better next time?

There is not. We as players have come up with the idea of using telescopes, dimensions locks (I'm unsure about this one) or the satellite dish to tell what's going on on another place, but someone needs to pick these up and code them.

**Comment by kyleedwardsny** [comment]
I'm writing a mod that uses the satellite dish and the display screen to show the time on other celestial bodies. The code is basically done; at this point I need to test it and port it to multiple versions. Link here: [https://github.com/kyleedwardsny/GalacticraftClock](https://github.com/kyleedwardsny/GalacticraftClock)

**Comment by EzerArch** [comment]
Interesting! :D

**Comment by EzerArch** [comment]
Oh fancy!

![](https://forum.micdoodle8.com/index.php?attachments/2017-11-16_13-34-33-png.1942)

https://forum.micdoodle8.com/index.php?threads/galacticraft-clock-mod.6829/

**Comment by EzerArch** [comment]
@radfast, just a question: According to this, "Each world (dimension) will now track its own time, and player use of beds or Cryogenic Chambers in those dimensions should change the time only in that dimension without touching other dimensions." ([link](https://github.com/micdoodle8/Galacticraft/issues/2643#issuecomment-300605153)), the Moon day-night cycle no longer follows the moon phases seen in the Overworld, right? Then I could consider [part of this wiki text](https://wiki.micdoodle8.com/wiki/Moon#Day-night_cycle) deprecated and make a proper edit.
