### ISSUE TITLE
Minecraft Crashing

### ISSUE THREAD

**Issue by igeorge16** [micdoodle8/Galacticraft#3031]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.11.2
Galacticraft version: 4.0.0.118
Forge version: 13.20.1.2530

Single player (SSP) or Multiplayer (SMP)?
SMP
Galacticraft add-ons and other mods installed?
Galacticraft Core, Galacticraft Planets, optifine, xray, MicDoodleCore, JustEnoughItems
Please provide screenshots / crash report / log as needed.
![tdeh](https://user-images.githubusercontent.com/33628667/32729366-1c6594c4-c88c-11e7-925d-68ff7c07adb5.png)

**Comment by MJRLegends** [comment]
Please can you provide the fml-latest-server.log file

**Comment by igeorge16** [comment]
You mean this ?
![fjhm cgfh](https://user-images.githubusercontent.com/33628667/32739070-86524628-c8a7-11e7-930a-e430f4631791.png)

**Comment by MJRLegends** [comment]
No its a file, screenshots of your console isnt helpful

**Comment by MJRLegends** [comment]
And your fml-latest-client.log file would be helpful too

**Comment by igeorge16** [comment]
the thing is i am using the aternos for the galacticraft server

**Comment by Sfven** [comment]
Go to **C:\Users\<your username>\AppData\Roaming\.minecraft\crash-reports**
Send us the most recent file there, should have a name with the date and time of the crash.

Next go to **C:\Users\<your username>\AppData\Roaming\.minecraft\logs**
There should be a lot of **log.gz** files in there, and at the bottom there should be:
**fml-client-1.log
fml-client-2.log
fml-client-3.log
fml-client-latest.log
fml-junk-earlystartup.log
latest.log**

Send us the **fml-client-latest.log**

Best of Luck,
~Sfven

**Comment by igeorge16** [comment]
https://pastebin.com/WRtvangv 
[fml-client-latest.log](https://github.com/micdoodle8/Galacticraft/files/1472079/fml-client-latest.log)
[fml-junk-earlystartup.log](https://github.com/micdoodle8/Galacticraft/files/1472080/fml-junk-earlystartup.log)
[latest.log](https://github.com/micdoodle8/Galacticraft/files/1472081/latest.log)
[fml-client-1.log](https://github.com/micdoodle8/Galacticraft/files/1472082/fml-client-1.log)
[fml-client-2.log](https://github.com/micdoodle8/Galacticraft/files/1472083/fml-client-2.log)
[fml-client-3.log](https://github.com/micdoodle8/Galacticraft/files/1472084/fml-client-3.log)

**Comment by igeorge16** [comment]
hello ?

**Comment by TheQuadShot** [comment]
I didn't see anything in any of the logs that point at GC being a problem, in the crash log on pastebin, it show's a bow with knockback enchantment crashed the game.

**Comment by radfast** [comment]
I don't see any Galacticraft issue.
It's crashing in something in vanilla Minecraft / Forge called ```detectOptifine```.
Maybe try without Optifine?  Or without the xray mod?

**Comment by igeorge16** [comment]
ok thank you
