### ISSUE TITLE
[1.11.2] Can't take contents of generated Cargo Loaders except using hoppers

### ISSUE THREAD

**Issue by AugiteSoul** [micdoodle8/Galacticraft#3035]
I cannot take the content of the Cargo Loaders full of loot generated in Asteroids dungeons, except using a hopper and a chest (but yeah, it's slow) Breaking the Loader destroys the loot.

**Comment by radfast** [comment]
It's intended behaviour, in the Asteroids dungeon.  It's supposed to be a small puzzle.  Actually I didn't intend that players can hopper the items out, it's intended that you should power up the Cargo Loader and load the items into a rocket!

So maybe I should fix that ...

**Comment by radfast** [comment]
hmm, in my testing I am not seeing a Hopper extracting items from a **Cargo Loader**.  That should be impossible already, both for standard Cargo Loaders and for the dungeon variety.

A Hopper can empty a Cargo Unloader but it cannot empty a Cargo Loader.

If you are using a Hopper to do this, please post a screenshot of your setup and also which exact Galacticraft and Forge version?

**Comment by radfast** [comment]
@AugiteSoul please show how you used the Hopper?  In my testing, it's not pulling items.

**Comment by AugiteSoul** [comment]
Nevermind. I just remembered that I did it in build 117, which isn't the latest build. Sorry :P

**Comment by radfast** [comment]
ok ... not sure that that changed much since build 117, but anyhow if you're not seeing the problem currently then I guess we don't need to worry any more :)
