### ISSUE TITLE
[1.7.10]When a modded server is booting is keeps saying that galacticraft failed to check for updates

### ISSUE THREAD

**Issue by AlexShepler** [micdoodle8/Galacticraft#3040]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version:
Galacticraft version:
Forge version:

Single player (SSP) or Multiplayer (SMP)?

Galacticraft add-ons and other mods installed?

Please provide screenshots / crash report / log as needed.

**Comment by MJRLegends** [comment]
Thanks for the report, but this has been reported already #2968.

The mod still will work correctly though
