### ISSUE TITLE
[1.11.2] Installing BuildCraft 8 Removes Galacticraft 4 Oil

### ISSUE THREAD

**Issue by ekultails** [micdoodle8/Galacticraft#3044]
Minecraft version: 1.11.2
Galacticraft version: 1.11.2-4.0.0.118
Forge version: 1.11.2-13.20.1.2386
BuildCraft: 7.99.8.1.
BuildCraft Compat: 7.99.0

When installing the (in-development for Minecraft 1.11.2) BuildCraft 8 on an existing multiplayer server that has been using Galacticraft 4, all of the existing oil disappears.

This issue seems to be related to a problem that occurred with older versions of Galacticraft and BuildCraft: https://wiki.micdoodle8.com/wiki/BuildCraft#Pre-version_3.0.9:_warning_if_installing_Buildcraft_on_existing_worlds. Since both projects have had major updates since then I think there might be another compatibility issue. After installing the BuildCraft mod, a seemingly normal warning appears that Galacticraft oil has been oil has been turned off for compatibility with BuildCraft. When logging into the server, though, all existing oil wells/lakes disappeared.

```
[07:53:03] [Server thread/INFO]: Preparing level "world"
[07:53:03] [Server thread/INFO] [FML]: Injecting existing block and item data into this server instance
[07:53:03] [Server thread/INFO] [FML]: Found a missing id from the world galacticraftcore:crude_oil_still
[07:53:03] [Server thread/INFO] [FML]: Found a missing id from the world galacticraftcore:crude_oil_still
[07:53:03] [Server thread/INFO] [FML]: Found a missing id from the world galacticraftcore:bucket_oil
[07:53:03] [Server thread/FATAL] [FML]: There are unidentified mappings in this world - we are going to attempt to process anyway
[07:53:03] [Server thread/FATAL] [FML]: Unidentified block: galacticraftcore:crude_oil_still, id 235
[07:53:03] [Server thread/FATAL] [FML]: Unidentified item: galacticraftcore:crude_oil_still, id 4097
[07:53:03] [Server thread/FATAL] [FML]: Unidentified item: galacticraftcore:bucket_oil, id 4098
[07:53:03] [Server thread/WARN] [FML]: Forge Mod Loader detected missing blocks/items.

There are 3 missing blocks and items in this save.
If you continue the missing blocks/items will get removed.
A world backup will be automatically created in your saves directory.

Missing Blocks/Items:
galacticraftcore:crude_oil_still
galacticraftcore:crude_oil_still
galacticraftcore:bucket_oil
```

The full log has been provided here: https://pastebin.com/BL89P0R3

BuildCraft was downloaded from here for testing:
https://www.mod-buildcraft.com/buildcraft-79912-alpha-buildcraft-79981-alpha-buildcraft-7123-stable-buildcraftcompat-717-stable-buildcraftcompat-7990-alpha.html

**Comment by MJRLegends** [comment]
Yeah this is intended, it will use buildcraft oil in replacement

**Comment by MJRLegends** [comment]
Config option of 
```
    # Set to true to make Galacticraft oil register as oilgc, for backwards compatibility with previously generated worlds.
    B:"Use legacy oilgc fluid registration"=false

```
could solve this so you have both for backwards compatibility

**Comment by ekultails** [comment]
Excellent, thank you so much for your assistance! I can confirm that it is working when setting that option to  true. If I have some spare time this weekend, I will look into updating the Wiki about the oil and fuel compatibility settings in these two locations:

* https://wiki.micdoodle8.com/wiki/Config
* https://wiki.micdoodle8.com/wiki/BuildCraft

Thanks again!

**Comment by radfast** [comment]
It's generally not a good idea to change mods (mods with worldgen) in a modpack after you already generated the world.

In a freshly generated world it's intended behaviour that Galacticraft does not generate oil, when Buildcraft is installed.

The legacy oil config option will preserve Galacticraft's oil (if you use the config before you install Buildcraft - if you use it after Buildcraft, it will be already too late!).  But using this config might prevent some other mods from recognising Galacticraft's oil as a type of "oil", so you might find some compatibility issues down the line.

Galacticraft will always accept it's own oil, of course.
