### ISSUE TITLE
[1.10.2] Server Crash when Client logs in.

### ISSUE THREAD

**Issue by chezpaul** [micdoodle8/Galacticraft#3046]
Minecraft version: 1.10.2
Galacticraft version: 119
Forge version: 2511
Playing on a server.
Mods used: [Here](https://pastebin.com/99HiTBJ6)

When I launch the server, it launches fine but when I login with client, I crash after about 5 seconds with [this error message](https://pastebin.com/4QmrRMT3).

If I take out Astral Sorcery, server works fine, put it back in and I get the same exact crash every time.
Astral Sorcery devs tell me it's a Galacticraft error, not an Astral one.

Thanks

**Comment by MJRLegends** [comment]
Yeah i had this issue see https://github.com/MJRLegends/Space-Astronomy-2-Feedback-/issues/44

**Comment by chezpaul** [comment]
Thanks man... so... it looks like they did not fix it right? Astral devs say it's a Galacticraft thing.
https://github.com/HellFirePvP/AstralSorcery/issues/378

Would my issue be fixed by just deleting all galacticraft display screens in my world?

**Comment by MJRLegends** [comment]
See the last comment on the link i posted it contains the fix

**Comment by MJRLegends** [comment]
But no its a Astral sorcery thing

**Comment by MJRLegends** [comment]
Which was confirmed here https://github.com/micdoodle8/Galacticraft/issues/2891

**Comment by chezpaul** [comment]
Got it
Thanks

**Comment by chezpaul** [comment]
Can I still go to Asteroid Belt? Or should I add it too to the list?

**Comment by MJRLegends** [comment]
No just adding 0 is all that is needed

**Comment by MJRLegends** [comment]
@chezpaul Please close :D
