### ISSUE TITLE
[1.10.2] Fluid Network Tps issue

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft#3047]
Minecraft version: 1.10.2
Galacticraft version: Build 118
Forge version: 12.18.3.2511
SpongeForge Version: spongeforge-1.10.2-2477-5.2.0-BETA-2731.jar

Ok, so server network that is hosting my mod pack is getting tps issues. I asked them to run this mod https://refinedstorage.raoulvdberge.com/wiki/profiling this makes a .nps profile file.

It seems there tps issues is coming from a GC handler see below for results of them profile files, they have two servers with my Space Astronomy 2 pack. and both have the issue but one is with Ender io and one is with Ender Tanks from Ender Storage mod

Server Network's Server 1:
![](https://i.gyazo.com/48f4372bcffcaa95dadd1d49632ab373.png)

Server Network's Server 2:
![](https://i.gyazo.com/f21ccd035a16153ac5922b71d4311355.png)

If you need anymore information or need me to get them try anything let me know.

**Comment by MJRLegends** [comment]
(Issue mainly for @radfast or @micdoodle8 )

**Comment by radfast** [comment]
Thanks, I'll take a look at this.

I enjoy fixing performance issues :)

This FluidNetwork code was borrowed from Mekanism, it's not code I wrote and so probably it's not optimised for high performance.

**Comment by MJRLegends** [comment]
Yeah thanks its really effecting their servers

**Comment by radfast** [comment]
Thank you for passing this on.
Please ask the server owner to test it, with that same profiler, in next build 120.
It should now run approximately 5-10x faster, I hope.

If no improvement is seen, please post new profiler screenshots, with ```micdoodle8.mods.galacticraft.core.fluid.FluidNetwork.onUpdate()``` fully expanded.

**Comment by MJRLegends** [comment]
@radfast No problem, i will get them to test ASAP. Will the Build 120 be out today?

**Comment by MJRLegends** [comment]
@radfast Ok, i up ported the fix you made to MC 1.10.2 and made a custom server side version for them to test and i can confirm that it works great and no more issues seen with the Fluid Network yet

**Comment by radfast** [comment]
oh wow, great job
ok thanks for confirming, I'm glad this one is fixed

**Comment by MJRLegends** [comment]
@radfast No problem, im helping them watch the tps for issues closely so i can easily see if it comes up again

**Comment by radfast** [comment]
yeah, any more tps issues in Galacticraft please let me know, like I say, that's one of the things I actually enjoy fixing, I think tps is important.  That's a good profiler so looks like your server guys know what they are doing here.

**Comment by MJRLegends** [comment]
Will do, yeah the profiler tool was suggested by me to them as they are the official servers for my packs so i help out with advanced support for the servers that the mod pack is on :D
