### ISSUE TITLE
I cant play galacticraft 1.11.2 on my modded client

### ISSUE THREAD

**Issue by BournUltimatum** [micdoodle8/Galacticraft#3053]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version:1.11.2 latest forge
Galacticraft version:1.11.2 latest
Forge version:1.11.2-forge1.11.2-13.20.1.2386

Single player

Galacticraft add-ons and other mods installed? 
No

It says which i cant play the mod because it requires java 8, i'm using java 7 because my computer or anything that i dont know, does not support java 8. Is there a way top run galacticraft 1.11.2 (beta) with java 7? If there isnt, i pray the devs to release a version for java 7, i wanted to play this mod on my aternos server, which only has the latest version of galacticraft. I would be happy too if someone of you may tell me how to do a free modded server without hamachi, and without any fake sites.

**Comment by TheQuadShot** [comment]
Getting a backward compatible version is very **very** unlikely. Dev's usually require a specific version for multiple reasons, the biggest is functionality (ie previous versions don't support _x_). As far a setting up a server there are lots of places (including youtube) that can guide you, or post your questions on the forums page.
https://forum.micdoodle8.com/index.php

**Comment by MJRLegends** [comment]
Yeah the developers will always use latest versions of resources like java, making it java 7 support will just hold the mod back from having latest java 8 improvements and features, being down performance in the long run, even more so that java 9 will be the main stream version soon

**Comment by radfast** [comment]
There is no way to run Galacticraft 1.11.2 in Java 7.

You have two choices.

1.  update your Java runtime to a Java 8 version (all PCs can run Java 8, and it's a free download)
2.  play the 1.7.10 version of the mod - that one works in Java 7.
