### ISSUE TITLE
1.8.9

### ISSUE THREAD

**Issue by EnderDragon1264** [micdoodle8/Galacticraft#3059]
I'm Having Problems Getting It To Work
(Info Below)
-------------------------------------------------------------------------------------------------------------------
Minecraft version: 1.8.9
Galacticraft version: 1.8.9
Forge version: 14.23.1.2561

Singleplayer

Only Galacticraft. No Other Mods Or Add-Ons

Screenshot: https://imgur.com/a/sJKor

**Comment by MJRLegends** [comment]
I believe its because you have a MC 1.12.2 forge version which is 14.23.1.2561 you need 11.15.1.2318 which is the latest 1.8.9 one see https://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.8.9.html to get this downloaded

**Comment by EnderDragon1264** [comment]
@MJRLegends I Was Using 1.8.9

https://imgur.com/gv8K7l7

**Comment by MJRLegends** [comment]
Your using a older version than it needs

**Comment by radfast** [comment]
Your first screen shot told you it needs at least ...1764.
Your second screen shot told you you have ...1722.

Just update Forge.

**Comment by EnderDragon1264** [comment]
@radfast Thanks! I’ll be right on that
