### ISSUE TITLE
Serious: When the rocket landed on the Y-axis 1200, the planet selection panel (GUI) failed to render and the game crashed. Restart the game, stuck in the middle of the galaxy space.

### ISSUE THREAD

**Issue by Twlilght-Dream-Of-Magic** [micdoodle8/Galacticraft#3064]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version:1.7.10
Galacticraft version:3.0.12.502
Forge version:10.13.4.1614

Single player (SSP) or Multiplayer (SMP)?  -> Use SSP

Galacticraft add-ons and other mods installed? -> Yes

Galacticraft add-ons installed List
----------
MorePlanets (Solar System) v1.4.3
ExtraPlanets v1.9.0
GalaxySpace v1.1.9 STABLE
----------

Please provide screenshots / crash report / log as needed.

## Twlilght_Dream:
**I am Chinese player, I use Chinese and English**

---- Minecraft Crash Report ----
// Sorry :(

Time: 17-12-22 上午1:55
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection.getCelestialBodyPosition(GuiCelestialSelection.java:1172)
	at micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection.getCelestialBodyPosition(GuiCelestialSelection.java:1185)
	at galaxyspace.SolarSystem.core.coremod.gui.screen.GSGuiCelestialSelection.drawCelestialBodies(Unknown Source)
	at galaxyspace.SolarSystem.core.coremod.gui.screen.GSGuiCelestialSelection.func_73863_a(Unknown Source)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1400)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection.getCelestialBodyPosition(GuiCelestialSelection.java:1172)
	at micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection.getCelestialBodyPosition(GuiCelestialSelection.java:1185)
	at galaxyspace.SolarSystem.core.coremod.gui.screen.GSGuiCelestialSelection.drawCelestialBodies(Unknown Source)
	at galaxyspace.SolarSystem.core.coremod.gui.screen.GSGuiCelestialSelection.func_73863_a(Unknown Source)

-- Screen render details --
Details:
	Screen name: galaxyspace.SolarSystem.core.coremod.gui.screen.GSGuiCelestialSelection
	Mouse location: Scaled: (213, 119). Absolute: (427, 240)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Twlilght_Yujiang'/378, l='MpServer', x=256.50, y=1208.87, z=229.50]]
	Chunk stats: MultiplayerChunkCache: 9, 9
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (64,64,232), Chunk: (at 0,4,8 in 4,14; contains blocks 64,0,224 to 79,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 846444 game time, 22984 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 2 total; [EntityCelestialFake['entity.CelestialScreen.name'/837, l='MpServer', x=256.50, y=1207.75, z=229.50], EntityClientPlayerMP['Twlilght_Yujiang'/378, l='MpServer', x=256.50, y=1208.87, z=229.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:425)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_152, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2805158344 bytes (2675 MB) / 3581935616 bytes (3416 MB) up to 4294967296 bytes (4096 MB)
	Mod Pack: Unknown / None
	LiteLoader Mods: 2 loaded mod(s)
          - VoxelMap version 1.5.20
          - VoxelLib version 2.3.1
	LaunchWrapper: 43 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: optifine.OptiFineClassTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: net.minecraftforge.classloading.FluidIdTransformer
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: codechicken.nei.asm.NEITransformer
          - Transformer: cn.lambdalib.pipeline.core.PipelineTransformer
          - Transformer: micdoodle8.mods.miccore.MicdoodleTransformer
          - Transformer: appeng.transformer.asm.ASMIntegration
          - Transformer: atomicstryker.dynamiclights.common.DLTransformer
          - Transformer: lain.mods.inputfix.InputFixTransformer
          - Transformer: invtweaks.forge.asm.ContainerTransformer
          - Transformer: com.creativemd.itemphysic.ItemTransformer
          - Transformer: api.player.forge.PlayerAPITransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: micdoodle8.mods.miccore.MicdoodleAccessTransformer
          - Transformer: appeng.transformer.asm.ASMTweaker
          - Transformer: cofh.asm.CoFHAccessTransformer
          - Transformer: invtweaks.forge.asm.ITAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: cofh.asm.CoFHClassTransformer
          - Transformer: com.gildedgames.util.threadedlighting.asm.TLTransformer
          - Transformer: shadersmodcore.transform.SMCClassTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.thevoxelbox.common.TimeUpdateTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.thevoxelbox.voxelmap.litemod.VoxelMapTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 8 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx4096m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 13, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D6 85 mods loaded, 85 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] ([NEI物品管理器] NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	LambdaLib|Core{1.2.3} [LambdaLib|Core] (minecraft.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJAAAA	InputFix{1.7.x-v4} [InputFix] (minecraft.jar) 
	UCHIJAAAA	itemphysic{0.8.3} [ItemPhysic] (minecraft.jar) 
	UCHIJAAAA	PlayerAPI{1.4} [Player API] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) 
	UCHIJAAAA	gilded-games-util{1.7.10-1.1} [Gilded Games Utility] (Gilded-games-util A.jar) 
	UCHIJAAAA	lucky{5.1.0} [Lucky Block] ([1.7.10] LuckyBlock v5.1.0 幸运方块.jar) 
	UCHIJAAAA	recipehandler{1.7.10} [NoMoreRecipeConflict] ([1.7.10][不再有合成冲突MOD].jar) 
	UCHIJAAAA	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCHIJAAAA	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal 砍树-2.0.4.jar) 
	UCHIJAAAA	NEIPlugins{1.1.0.11-unofficial} [NEI Plugins Unofficial] ([NEI扩展]NEI Plugins for 1.7.10 v1.1.0.11.jar) 
	UCHIJAAAA	NEIAddons{1.12.3.11} [NEI Addons] ([NEI扩展]NEIaddons for 1.7.10 v1.12.3.11.jar) 
	UCHIJAAAA	NEIAddons|Botany{1.12.3.11} [NEI Addons: Botany] ([NEI扩展]NEIaddons for 1.7.10 v1.12.3.11.jar) 
	UCHIJAAAA	NEIAddons|Forestry{1.12.3.11} [NEI Addons: Forestry] ([NEI扩展]NEIaddons for 1.7.10 v1.12.3.11.jar) 
	UCHIJAAAA	NEIAddons|CraftingTables{1.12.3.11} [NEI Addons: Crafting Tables] ([NEI扩展]NEIaddons for 1.7.10 v1.12.3.11.jar) 
	UCHIJAAAA	NEIAddons|ExNihilo{1.12.3.11} [NEI Addons: Ex Nihilo] ([NEI扩展]NEIaddons for 1.7.10 v1.12.3.11.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] ([NEI高亮显示]Waila-Mod-1.7.10.jar) 
	UCHIJAAAA	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] ([冒险者背包]Adventure_backpack-1.7.10-0.8c.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] ([匠魂手册]Mantle API for 1.7.10 v0.3.2.jar) 
	UCHIJAAAA	armourersWorkshop{1.7.10-0.38.1.98} [Armourer's Workshop] (ArmourersWorkShop 方块时装工坊1.7.10-0.38.1.98.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329 API.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.6} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.6-118 热力膨胀-基础.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.1.5} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.5-248 热力膨胀-核心.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] ([匠魂主体]TinkersConstruct for 1.7.10 v1.8.8 .jar) 
	UCHIJAAAA	TiCTooltips{1.2.3} [TiC Tooltips] ([匠魂工具]TiCTooltips-1.7.10-1.2.3.jar) 
	UCHIJAAAA	ChickenChunks{1.3.4.19} [ChickenChunks] ([区块加载器]ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
	UCHIJAAAA	LambdaLib{1.2.3} [LambdaLib] ([学园都市超能力] AcademyCraft 前置Lib] LambdaLib-1.2.3.jar) 
	UCHIJAAAA	academy-craft{1.0.4} [Academy Craft] ([学园都市超能力] AcademyCraft-1.0.4.jar) 
	UCHIJAAAA	cookingbook{1.0.134} [Cooking for Blockheads] ([懒人厨房]cookingbook-mc1.7.10-1.0.134.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.17} [BuildCraft] (Buildcraft-7.1.17 BC建筑.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.17} [BC Energy] (Buildcraft-7.1.17 BC建筑.jar) 
	UCHIJAAAA	IC2{2.2.822-experimental} [IndustrialCraft 2] (Industrialcraft2 v2.2.822 Experimental 工业2实验版.jar) 
	UCHIJAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] ([星系Mod] GalacticraftCore-1.7-3.0.12.502 核心API.jar) 
	UCHIJAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] ([星系Mod] Galacticraft-Planets-1.7-3.0.12.502 行星.jar) 
	UCHIJAAAA	MorePlanet{1.4.3} [More Planets] ([星系Mod扩展0] Galacticraft Addon MorePlanets (Solar System 太阳系空间) v1.4.3 for MC1.7.10+GC502.jar) 
	UCHIJAAAA	ExtraPlanets{1.9.0} [Extra Planets] ([星系Mod扩展1] Galacticraft Addon ExtraPlanets 额外行星 v1.9.0 for MC1.7.10+GC502.jar) 
	UCHIJAAAA	GalaxySpace{1.1.9} [GalaxySpace] ([星系Mod扩展2] Galacticraft Addon GalaxySpace v1.1.9 STABLE for MC1.7.10 (银河系空间).jar) 
	UCHIJAAAA	Backpack{2.0.1} [Backpack] ([更多背包]Backpack-2.0.1-1.7.x.jar) 
	UCHIJAAAA	harvestcraft{1.7.10i} [Pam's HarvestCraft] ([潘马斯农]Pam's HarvestCraft 1.7.10.jar) 
	UCHIJAAAA	aether{Alpha 1.7.10-1.4} [Aether II] (Aether B.jar) 
	UCHIJAAAA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (AppliedEnergistics2-rv2-stable-10 AE应用能源2 .jar) 
	UCHIJAAAA	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (ArchimedesShips v1.7.1 阿基米德船舶.jar) 
	UCHIJAAAA	plushieWrapper{0.0.0} [Plushie Wrapper] (ArmourersWorkShop 方块时装工坊1.7.10-0.38.1.98.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.17} [BC Silicon] (Buildcraft-7.1.17 BC建筑.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.17} [BC Transport] (Buildcraft-7.1.17 BC建筑.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.17} [BC Builders] (Buildcraft-7.1.17 BC建筑.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.17} [BC Robotics] (Buildcraft-7.1.17 BC建筑.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.17} [BC Factory] (Buildcraft-7.1.17 BC建筑.jar) 
	UCHIJAAAA	carsanddrives{1.0.9.1} [Cars and Drives] (Cars_and_Drives_Mod_v1.0.9.1 小汽车.jar) 
	UCHIJAAAA	ChestTransporter{2.0.3} [Chest Transporter] (ChestTransporter 搬箱器 2.0.3-MC1.7.10.jar) 
	UCHIJAAAA	DynamicLights{1.3.7} [Dynamic Lights] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_dropItems{1.0.7} [Dynamic Lights EntityItem Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_mobEquipment{1.0.7} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_floodLights{1.0.1} [Dynamic Lights Flood Light] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_otherPlayers{1.0.7} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	enchvil{1.0} [Enchvil Mod] (Enchvil-Mod-1.7.10＆2-CN.jar) 
	UCHIJAAAA	EnderStorage{1.4.7.37} [EnderStorage] (EnderStorage 1.4.7.37 末影存储 Universal for 1.7.10.jar) 
	UCHIJAAAA	enviromine{1.3.118} [EnviroMine] (EnviroMineCore-1.3.124 环境.jar) 
	UCHIJAAAA	FoodCraft{1.2.0} [FoodCraft(FoodCraft)] (FoodCraft-15.8.25-1.2.0-1.7.10.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-155-5dbbb14} [Inventory Tweaks] (InventoryTweaks-1.59-dev-155 R键整理物品.jar) 
	UCHIJAAAA	IronChest{6.0.60.741} [Iron Chest] (Ironchest for 1.7.10 v6.0.60.741 universal 更多箱子.jar) 
	UCHIJAAAA	LotsOfFood{1.7.10} [Lots of Food] (Lots of Food-1.7.10.jar) 
	UCHIJAAAA	miners{v3.1.1} [Miner's Heaven] (Miner's Heaven 矿工天堂 v3.1.1.jar) 
	UCHIJAAAA	cfm{3.4.7} [MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7 for 1.7.10 家具.jar) 
	UCHIJAAAA	MultiPageChest{1.3.4} [Multi Page Chest] (MultiPageChest 多页箱子 1.3.4 for MC1.7.10.jar) 
	UCHIJAAAA	Railcraft{9.12.2.0} [Railcraft] (Railcraft_1.7.10-9.12.2.0 铁路增强工艺.jar) 
	UCHIJAAAA	AS_Ruins{13.4} [Ruins Spawning System] (Ruins-1.7.10更多遗迹Ruins-1.7.10.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.2.1} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.2.1-172 热力膨胀-热力学(含管道).jar) 
	UCHIJAAAA	TooMuchTNT{2.9} [TooMuchTNT] (Too-Much-TNT-Mod-1.7.10.jar) 
	UCHIJAAAA	Torcherino{2.2s} [Torcherino] (Torcherino-1.7.10-2.2s 加速火把.jar) 
	UCHIJAAAA	TwilightForest{2.3.7} [The Twilight Forest] (TwilightForest-1.7.10-2.3.7 暮色森林.jar) 
	UCHIJAAAA	yarr_cutemobmodels{1.0.8} [Cute Mob Models] (YrrcuteMobModels-1.0.8-1.7.10 娘化怪物 [汉化].jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.13' Renderer: 'GeForce GTX 960/PCIe/SSE2'
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	CoFHCore: -[1.7.10]3.1.4-329
	ThermalFoundation: -[1.7.10]1.2.6-118
	ThermalExpansion: -[1.7.10]4.1.5-248
	TConstruct Environment: Environment healthy.
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	ThermalDynamics: -[1.7.10]1.2.1-172
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BC:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Launched Version: HMCL 2.5.3.88
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 960/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.13, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_D6
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	OpenGlVersion: 4.6.0 NVIDIA 388.13
	OpenGlRenderer: GeForce GTX 960/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by MJRLegends** [comment]
This is a galaxyspace issue, please report it to the galaxyspace developer

**Comment by Twlilght-Dream-Of-Magic** [comment]
OK, Now this report submit to Galaxyspace[Galacticraft Addon] the developer

**Comment by marcus8448** [comment]
Close?

**Comment by EzerArch** [comment]
@Twlilght-Dream-Of-Magic, please close the issue if this is not related to GC. :)

**Comment by radfast** [comment]
I think this can be either:

1.  A GalaxySpace issue

or 

2.  A problem when you have GalaxySpace, MorePlanets and ExtraPlanets all together.

**Comment by MJRLegends** [comment]
yeah from the crash log seems to be galaxy space
`at galaxyspace.SolarSystem.core.coremod.gui.screen.GSGuiCelestialSelection.drawCelestialBodies(Unknown Source)`
