### ISSUE TITLE
Oxygen Pipes and other various blocks missing

### ISSUE THREAD

**Issue by VariableSpy1719** [micdoodle8/Galacticraft#3066]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.11.2
Mods: GalacticraftCore-1.11.2-4.0.0.119.jar, Galacticraft-Planets-1.11.2-4.0.0.119.jar, MicdoodleCore-1.11.2-4.0.0.119, OptiFine_1.11.2_HD_U_C3.jar.
Forge version: 13.20.0.2311

Single player (SSP) or Multiplayer (SMP)? SinglePlayer

Galacticraft add-ons and other mods installed? Optifine

Please provide screenshots / crash report / log as needed.
![image](https://user-images.githubusercontent.com/34842082/34342581-b42e0b00-e971-11e7-95f6-75d8c5e2161f.png)

**Comment by marcus8448** [comment]
That is because in Galacticraft 4 oxygen pipes are now fluid pipes, fluid pipe walkways etc. Read about the changes here: https://wiki.micdoodle8.com/wiki/Galacticraft_4

**Comment by VariableSpy1719** [comment]
but the fluid pipes dont connect when i put them next to oxygen collector, or maybe its the wrong side. thx tho

**Comment by MJRLegends** [comment]
Correct for GC4 fluid pipes are your oxygen pipes too

**Comment by radfast** [comment]
If you are having problems using the Fluid Pipes please post a **screenshot** of your game.

If no more posts, I'll assume there is no more issue.
