### ISSUE TITLE
It's hard to press the ¨create a space station¨

### ISSUE THREAD

**Issue by IsakManiLegend** [micdoodle8/Galacticraft#3067]
Hi, im having trouble with the ¨create a space station¨ button or i think that's what its called i don't know because i cant see it i think its here but i cant tell.
I haven't found another place where it could be and i haven't found any videos showing the process of getting the space station in galacticraft 3
![galacticraft 3](https://user-images.githubusercontent.com/34522977/34388531-05d62760-eb2c-11e7-8e33-098d4a8d6362.PNG)
This is the minecraft version 1.7.10 by the way I also have the galaxyspace add-on but i don't know if it's because of it.

As you can see i have all the items required

![galacticraft 3 space station](https://user-images.githubusercontent.com/34522977/34388758-70190bdc-eb2d-11e7-8c48-879a9975fc04.PNG)

Can someone please help me!

**Comment by MJRLegends** [comment]
This a galaxy space issue please report it to the galaxy space developer

**Comment by IsakManiLegend** [comment]
ok thanks a ton!

**Comment by marcus8448** [comment]
@IsakManiLegend Please close :) It's not a GalactiCraft issue.

**Comment by radfast** [comment]
GalaxySpace changed that screen with things like "Atmospheric Parameters", so the button is covered up - please raise it with them.
