### ISSUE TITLE
[1.10.2] Server Crash error with 119

### ISSUE THREAD

**Issue by chezpaul** [micdoodle8/Galacticraft#3068]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.10.2
Galacticraft version:119
Forge version:2511

Server Crash

List of mods in server log below

Log [here](https://pastebin.com/MmhiHvPN)

**Comment by marcus8448** [comment]
Where in the log lists the mods? I can see in line 2238 but that's a LOT of mods... Next time try to do a separate pastebin of mods, and declare that you have addons (I think that you have Extra Planets). I think it will be easier for the devs that way. [Read the guidelines](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md)

**Comment by MJRLegends** [comment]
@marcus8448 its not needed, the error at the end shows its GC code crashing

**Comment by radfast** [comment]
Thanks @chezpaul for reporting, this should be fixed in build 120 coming in next few days (probably after 1 Jan 2018)

Hope your game is playable meanwhile without this - you might need to avoid the Abandoned Base region in the Asteroids dimension.

**Comment by chezpaul** [comment]
Thanks radfast.
Yes I'm good. Somehow I got it to work and I can't quite remember how to tell you the truth. Maybe I grabbed something from a backup? ;-)

**Comment by radfast** [comment]
Build 120 is available to download now.

**Comment by chezpaul** [comment]
Nice, thanks
