### ISSUE TITLE
Question Regarding 1.12.2

### ISSUE THREAD

**Issue by Darkosto** [micdoodle8/Galacticraft#3069]
Hello!

I had a chat with MJRLegends briefly and he mentioned there's some work being done a 1.12 port of Galacticraft. Is there any information on the progress so far? I'm working on a pretty large modpack and would absolutely love to include galacticraft and make it a big part of the project. I would also be willing to help out in any way with the progress of the port.

Thank you for your time and have a great rest of your day!
Darkosto

**Comment by MJRLegends** [comment]
@radfast @EzerArch @micdoodle8 If you push the current code i sent over to a branch, im happy to help out more with bugs/fixing errors

**Comment by ThomsonGaming** [comment]
would love to include this in my modpack also for 1.12.2

**Comment by MJRLegends** [comment]
For future reference this is the old issue on the 1.12 port #3037

**Comment by radfast** [comment]
@MJRLegends I am reviewing the current code with micdoodle8, please give us time, we both also have family commitments at this time of year.

everyone else: this is not a suitable issue report

**Comment by MJRLegends** [comment]
@radfast no problem, note i will take some responsibility to why this was posted here

**Comment by radfast** [comment]
1.12.2 is now available to [download](https://www.micdoodle8.com/mods/galacticraft/downloads)
