### ISSUE TITLE
Minecraft Crash Messaage when installing Galacticraft for Forge 1.7.10

### ISSUE THREAD

**Issue by pamicski** [micdoodle8/Galacticraft#3080]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.7.10
Galacticraft version:
Forge version: Forge 1.7.10

PLEASE HELP:

I get the message below after having installed the 3 required mods for this.  If I remove it loads.  Please tell me how to fix this as my son is desperate to play on this mod

**The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraftforge/registries/IForgeRegistryEntry**

**Comment by TheQuadShot** [comment]
Not enough information to tell you anything. Please read the Contribution guidelines and provide the required information.
https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md

**Comment by radfast** [comment]
Please check you are using the 1.7.10 version of Galacticraft ... !

Maybe post your full log.

**Comment by pamicski** [comment]
Resolved many thanks

Pam x
