### ISSUE TITLE
[1.12.x] Workspace Setup - Access Transformer Issue

### ISSUE THREAD

**Issue by CDAGaming** [micdoodle8/Galacticraft#3084]
**Sorry In Advance if this is in fact the wrong place to be posting this**

I'd Like to test out Galacticraft on 1.12 as you guys work on developing it, however, during setupDecompWorkspace it has the following error: [Build Error via Hastebin](https://hastebin.com/yefofixewi.lua)

If anyone can tell me what might be wrong, I'd Greatly appreciate it 
(Or if this is the wrong place to post this type of issue, to be redirected to where i can get support for this)

**Comment by radfast** [comment]
[RTFM :)](https://wiki.micdoodle8.com/wiki/GC3_API#Full_Galacticraft_Sources)

Second result in a Google search for **Galacticraft workspace access transformer** (and the first result is a post on Galacticraft forum with similar guidance).

**Comment by CDAGaming** [comment]
Ah, I completely forgot to look there lol

Thanks for the Help, really appreciated!

**Comment by CDAGaming** [comment]
Update: Mod works well on 1.12, except for the fact It flickers between the loading screen and Orbit Menu when returning to Earth 

Regardless, Kudos to @radfast and everyone else who brought this to 1.12.
You have my appreciation & respect :)
