### ISSUE TITLE
Space Station Landing Bug

### ISSUE THREAD

**Issue by Connj** [micdoodle8/Galacticraft#3093]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.10.2
Galacticraft version: 1.10.2-4.0.1.1.20
Forge version: 1.10.2-12.18.3.3216

Single player (SSP) or Multiplayer (SMP)?
SMP
Galacticraft add-ons and other mods installed?
Tough as Nails, Weather2, SecurityCraft
Please provide screenshots / crash report / log as needed.
![2018-01-11_01 08 23](https://user-images.githubusercontent.com/35390434/34903197-ac00a042-f7e9-11e7-89af-ec339790bac0.png)
![2018-01-11_01 09 27](https://user-images.githubusercontent.com/35390434/34903198-add5c488-f7e9-11e7-89c4-15089a00b951.png)
![2018-01-11_01 05 00](https://user-images.githubusercontent.com/35390434/34903199-af84a1be-f7e9-11e7-882d-98df208bacac.png)

When using a launch controller, going from anywhere to a space station causes some weird behavior. It seems like the player becomes disconnected from the rocket, but unable to exit. The only way I found to exit was to teleport, doing this causes the rocket to become dead wherever it may be.

**Comment by radfast** [comment]
likely related to #3063

**Comment by radfast** [comment]
should be fixed in build 148, please comment or re-open if any more similar problems.

**Comment by radfast** [comment]
Build 148 is now available - enjoy :)

**Comment by Connj** [comment]
Thanks, definitely makes the mod more realistic (SpaceX like.) The rocket
sounds still play after the rocket has landed, just thought I'd let you
know, if you didn't already know.

**Comment by radfast** [comment]
Thanks :)   I thought of SpaceX a lot when updating the landing code - our rockets are now navigating themselves to the destination pad with small ~~attitude~~ motion vector boosts if they get off course, it was hard to get it right!

I'll look at the sounds still playing, didn't know that - that's my bad, a lot of my testing of the game is with sound off because I listen to music while I code.
