### ISSUE TITLE
[1.11.2] Server crash with Telemetry Unit

### ISSUE THREAD

**Issue by QuantumStatement** [micdoodle8/Galacticraft#3095]
Minecraft version: 1.11.2
Galacticraft version: 4.0.1.120
Forge version: 13.20.1.2386

Single player (SSP) or Multiplayer (SMP)?
Multiplayer

Galacticraft add-ons and other mods installed?
Nope

Please provide screenshots / crash report / log as needed.
[Crash Report](https://gist.github.com/QuantumStatement/fb8f143dc05e910822c1ec5fa230cf4c)

Server crashes when you trying to link player and Telemetry Unit

**Comment by radfast** [comment]
Looks like this only occurs when you have an **single player game** with **extra players added** (LAN mode?)

Anyhow, thanks for reporting, this will be fixed in 121.
