### ISSUE TITLE
Request for CraftTweaker Support for Machine recipes

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft#3096]
Hello, 

Any chance we could find a way to add the ability to remove and add machine recipes for like a compressor and circuit fabricator.

Its something i want to add to my ExtraPlanets mod/addon, but would be great if Galacticraft has that feature too :D 

Let me know your thoughts

**Comment by radfast** [comment]
I'm not too keen on this:

-  it's a lot of development work for no real gameplay advantage for most people - I think people would rather see new features
-  there are already some config options to control those machine recipes, and the recipes are oredicted - if there is an incompatibility with another mod, I'm sure someone will tell me
-  it's hard to imagine what other recipe changes a modpack would want to make, except to change the balance and concepts in Galacticraft which is not something I want to encourage


Even in Minecraft 1.12.2 the recipes for these machines remain hard-coded for now (they are not in JSONs).

**Comment by MJRLegends** [comment]
:( ok, is there a way i can deregister compressor and circuit fabricator recipes, without messing stuff up

**Comment by MJRLegends** [comment]
The reason i ask is someone that i know is making a mod pack and they dont want to use diamonds for any recipes but the circuit fabricator has recipes using a diamond. Im trying to help them out with making sure things work to fit there pack so they can use the mod

**Comment by radfast** [comment]
See ```RecipeManagerGC.setConfigurableRecipes()``` for how to change Circuit Fabricator recipes in code.

**Comment by MJRLegends** [comment]
Ok will do
