### ISSUE TITLE
[Request] Register oredictionary in registerItems event

### ISSUE THREAD

**Issue by justinrusso** [micdoodle8/Galacticraft#3097]
Would it be possible to register the oredictionary of items at the end of the registerItems event? This would be ideal so that when crafttweaker is run, the items are already registered into their ore dictionaries.

**Comment by radfast** [comment]
that's a good idea - do you mean in 1.12.2 only, or which versions?

**Comment by justinrusso** [comment]
I personally just care for 1.12+

**Comment by radfast** [comment]
Now implemented

**Comment by radfast** [comment]
1.12.2 is now available to [download](https://www.micdoodle8.com/mods/galacticraft/downloads)
