### ISSUE TITLE
Some issues with Galacticraft in-game config

### ISSUE THREAD

**Issue by QuantumStatement** [micdoodle8/Galacticraft#3098]
Minecraft version: 1.11.2
Galacticraft version: 4.0.1.121
Forge version: 13.20.1.2386

Single player (SSP) or Multiplayer (SMP)?
SSP

Galacticraft add-ons and other mods installed?
None

Please provide screenshots / crash report / log as needed.
1. Galacticraft Core config don't fit in screen 
Large scale
![2018-01-15_17 26 26](https://user-images.githubusercontent.com/35406698/34947397-061038da-fa1b-11e7-8a00-fce9ee3040f1.png)
Normal scale
![2018-01-15_17 26 55](https://user-images.githubusercontent.com/35406698/34947462-3680ee2e-fa1b-11e7-9048-e9938ec91eee.png)

2. Also Galacticraft Core config resets after Minecraft reload

3. Galacticraft Planets settings are repeated 3 times
![2018-01-15_15 55 23](https://user-images.githubusercontent.com/35406698/34947512-5ce45588-fa1b-11e7-9ed1-a5f4e3cd80c5.png)

**Comment by MJRLegends** [comment]
Im sure one of the devs will find a way to fix this probably shorten the one config option that is causing the issue. But in the mean time you can always edit the config via the file in the configs folder :D

**Comment by radfast** [comment]
Thanks for raising this issue.

1 - is easy to fix, will be in next release. 

2 - I'm not sure what's normal, can someone tell me?  personally I don't use this config screen in any mod as I find it clunky

3 - seems like a bug, but we can check

**Comment by QuantumStatement** [comment]
To @radfast 
2. Settings changes made in Galacticraft config GUI aren't saves after Minecraft reload

**Comment by radfast** [comment]
1 2 and 3 are all now fixed next release.

2 was a stupid typo, which means this Galacticraft in-game config has **never worked properly**.  Therefore I'm pretty pleased this is now fixed - thanks for opening the issue.
