### ISSUE TITLE
Rocket Launch Pad dissapears when rocket starts from Space Station

### ISSUE THREAD

**Issue by QuantumStatement** [micdoodle8/Galacticraft#3099]
Minecraft version: 1.11.2
Galacticraft version: 4.0.1.121
Forge version: 13.20.1.2386

Single player (SSP) or Multiplayer (SMP)?
SSP

Galacticraft add-ons and other mods installed?
None

Rocket Launch Pad dissapears from parachests and landing vehicles if rocket (any tier) starts from Space Station

**Comment by radfast** [comment]
thanks for reporting

**Comment by radfast** [comment]
This is fixed in next build 139.
