### ISSUE TITLE
Crash when opening solar panel menu

### ISSUE THREAD

**Issue by 1CaptainAmerica** [micdoodle8/Galacticraft#3101]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.10.2
Galacticraft version: 1.10.2-4.0.0.106
Forge version: 1.10.2-12.18.3.2185-universal

Single player (SSP) or Multiplayer (SMP)?
Both

Galacticraft add-ons and other mods installed?
No Galacticraft add-ons, Other mods are as follows:
appliedenergistics2-rv4-stable-1
ClassicCombat-1.0.0-1.10.2-universal
CodeChickenCore-1.10.2-2.4.1.102-universal
CodeChickenLib-1.10.2-2.5.9.267-universal
CounterGuns-1.10.2-1.0.1
Guide-Book-Mod-1.10.2
industrialcraft-2-2.6.252-ex110
jei_1.10.2-3.14.7.420
NotEnoughItems-1.10.2-2.1.3.220-universal
SGCraft-1.13.2-mc1.10.2
Waila-1.7.0-B3_1.9.4

Please provide screenshots / crash report / log as needed.
---- Minecraft Crash Report ----

WARNING: coremods are present:
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.220-universal.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.267-universal.jar)
  AppEngLoadingPlugin (appliedenergistics2-rv4-stable-1.jar)
  MicdoodlePlugin (MicdoodleCore-1.10.2-4.0.0.106.jar)
  IC2core (industrialcraft-2-2.6.252-ex110.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 1/16/18 10:28 PM
Description: Unexpected error

java.lang.NoClassDefFoundError: cofh/api/energy/IEnergyContainerItem
	at micdoodle8.mods.galacticraft.core.inventory.SlotSpecific.<init>(SlotSpecific.java:46)
	at micdoodle8.mods.galacticraft.core.inventory.ContainerSolar.<init>(ContainerSolar.java:19)
	at micdoodle8.mods.galacticraft.core.client.gui.container.GuiSolar.<init>(GuiSolar.java:32)
	at micdoodle8.mods.galacticraft.core.client.gui.GuiHandler.getClientGuiElement(GuiHandler.java:240)
	at micdoodle8.mods.galacticraft.core.client.gui.GuiHandler.getClientGuiElement(GuiHandler.java:161)
	at net.minecraftforge.fml.common.network.NetworkRegistry.getLocalGuiContainer(NetworkRegistry.java:273)
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:110)
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2494)
	at micdoodle8.mods.galacticraft.core.blocks.BlockSolar.onMachineActivated(BlockSolar.java:177)
	at micdoodle8.mods.galacticraft.core.blocks.BlockAdvanced.func_180639_a(BlockAdvanced.java:52)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:410)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1518)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: cofh.api.energy.IEnergyContainerItem
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 24 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at micdoodle8.mods.galacticraft.core.inventory.SlotSpecific.<init>(SlotSpecific.java:46)
	at micdoodle8.mods.galacticraft.core.inventory.ContainerSolar.<init>(ContainerSolar.java:19)
	at micdoodle8.mods.galacticraft.core.client.gui.container.GuiSolar.<init>(GuiSolar.java:32)
	at micdoodle8.mods.galacticraft.core.client.gui.GuiHandler.getClientGuiElement(GuiHandler.java:240)
	at micdoodle8.mods.galacticraft.core.client.gui.GuiHandler.getClientGuiElement(GuiHandler.java:161)
	at net.minecraftforge.fml.common.network.NetworkRegistry.getLocalGuiContainer(NetworkRegistry.java:273)
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:110)
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2494)
	at micdoodle8.mods.galacticraft.core.blocks.BlockSolar.onMachineActivated(BlockSolar.java:177)
	at micdoodle8.mods.galacticraft.core.blocks.BlockAdvanced.func_180639_a(BlockAdvanced.java:52)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:410)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1518)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['_1CaptainAmerica'/303, l='MpServer', x=26.91, y=72.00, z=-198.77]]
	Chunk stats: MultiplayerChunkCache: 1060, 1060
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (7,64,-242), Chunk: (at 7,4,14 in 0,-16; contains blocks 0,0,-256 to 15,255,-241), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 11564 game time, 11564 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 74 total; [EntityCreeper['Creeper'/258, l='MpServer', x=91.43, y=34.00, z=-251.16], EntityWitch['Witch'/259, l='MpServer', x=93.50, y=33.00, z=-246.50], EntitySquid['Squid'/260, l='MpServer', x=75.07, y=54.25, z=-249.51], EntitySquid['Squid'/264, l='MpServer', x=83.40, y=59.82, z=-204.00], EntitySquid['Squid'/265, l='MpServer', x=88.40, y=56.11, z=-186.02], EntityCreeper['Creeper'/266, l='MpServer', x=95.77, y=23.00, z=-170.54], EntityZombie['Zombie'/142, l='MpServer', x=-11.55, y=44.00, z=-265.23], EntityCreeper['Creeper'/143, l='MpServer', x=-13.50, y=51.00, z=-251.50], EntityCreeper['Creeper'/144, l='MpServer', x=-14.50, y=29.00, z=-235.50], EntitySkeleton['Skeleton'/145, l='MpServer', x=-15.50, y=19.00, z=-200.50], EntityRabbit['Rabbit'/146, l='MpServer', x=-0.07, y=74.00, z=-179.34], EntityRabbit['Rabbit'/147, l='MpServer', x=-7.45, y=75.00, z=-175.06], EntityRabbit['Rabbit'/148, l='MpServer', x=-5.49, y=74.00, z=-173.59], EntityBat['Bat'/149, l='MpServer', x=-2.25, y=17.79, z=-142.25], EntityZombie['Zombie'/164, l='MpServer', x=1.50, y=31.00, z=-227.50], EntityRabbit['Rabbit'/165, l='MpServer', x=0.49, y=75.00, z=-218.71], EntitySkeleton['Skeleton'/166, l='MpServer', x=5.73, y=69.00, z=-205.54], EntityRabbit['Rabbit'/167, l='MpServer', x=4.56, y=73.00, z=-171.51], GCEntityClientPlayerMP['_1CaptainAmerica'/303, l='MpServer', x=26.91, y=72.00, z=-198.77], EntityZombie['Zombie'/168, l='MpServer', x=0.50, y=21.00, z=-131.50], EntityChicken['Chicken'/194, l='MpServer', x=31.51, y=67.00, z=-268.86], EntityChicken['Chicken'/196, l='MpServer', x=22.12, y=64.00, z=-266.51], EntityChicken['Chicken'/197, l='MpServer', x=23.13, y=68.00, z=-263.50], EntityZombie['Zombie'/198, l='MpServer', x=33.24, y=18.00, z=-188.32], EntitySkeleton['Skeleton'/199, l='MpServer', x=24.50, y=18.00, z=-177.50], EntitySkeleton['Skeleton'/200, l='MpServer', x=22.50, y=30.00, z=-180.50], EntitySkeleton['Skeleton'/201, l='MpServer', x=31.99, y=55.00, z=-189.47], EntityCreeper['Creeper'/202, l='MpServer', x=25.60, y=63.00, z=-192.16], EntitySpider['Spider'/203, l='MpServer', x=19.50, y=18.00, z=-168.50], EntitySkeleton['Skeleton'/204, l='MpServer', x=19.50, y=18.00, z=-168.50], EntityBat['Bat'/205, l='MpServer', x=35.52, y=46.50, z=-178.70], EntityRabbit['Rabbit'/206, l='MpServer', x=26.53, y=71.00, z=-160.35], EntityRabbit['Rabbit'/207, l='MpServer', x=24.25, y=72.00, z=-155.48], EntityRabbit['Rabbit'/208, l='MpServer', x=17.67, y=72.00, z=-140.95], EntityZombie['Zombie'/90, l='MpServer', x=-33.50, y=42.00, z=-271.50], EntityCreeper['Creeper'/91, l='MpServer', x=-39.50, y=43.00, z=-188.50], EntitySkeleton['Skeleton'/220, l='MpServer', x=37.45, y=29.00, z=-265.74], EntityCreeper['Creeper'/92, l='MpServer', x=-43.18, y=38.00, z=-146.53], EntityCreeper['Creeper'/221, l='MpServer', x=42.56, y=59.00, z=-213.18], EntityCreeper['Creeper'/93, l='MpServer', x=-27.79, y=39.00, z=-147.49], EntitySkeleton['Skeleton'/222, l='MpServer', x=42.27, y=48.00, z=-181.47], EntityZombie['Zombie'/94, l='MpServer', x=-32.41, y=36.00, z=-145.82], EntitySkeleton['Skeleton'/223, l='MpServer', x=38.50, y=48.00, z=-130.50], EntityCreeper['Creeper'/95, l='MpServer', x=-34.41, y=36.00, z=-144.17], EntityCreeper['Creeper'/96, l='MpServer', x=-34.33, y=36.00, z=-143.32], EntitySkeleton['Skeleton'/97, l='MpServer', x=-43.50, y=39.00, z=-142.50], EntitySkeleton['Skeleton'/98, l='MpServer', x=-35.39, y=36.00, z=-142.39], EntitySkeleton['Skeleton'/99, l='MpServer', x=-42.50, y=49.00, z=-137.50], EntityZombie['Zombie'/230, l='MpServer', x=62.50, y=18.00, z=-250.50], EntityRabbit['Rabbit'/231, l='MpServer', x=61.83, y=64.00, z=-247.07], EntityRabbit['Rabbit'/232, l='MpServer', x=53.69, y=64.00, z=-243.60], EntityEnderman['Enderman'/233, l='MpServer', x=62.63, y=62.00, z=-194.49], EntityRabbit['Rabbit'/234, l='MpServer', x=54.52, y=72.00, z=-195.77], EntityBat['Bat'/235, l='MpServer', x=56.75, y=19.10, z=-187.75], EntityRabbit['Rabbit'/236, l='MpServer', x=57.40, y=71.00, z=-176.60], EntityRabbit['Rabbit'/237, l='MpServer', x=57.09, y=71.00, z=-176.15], EntityZombie['Zombie'/238, l='MpServer', x=50.50, y=27.00, z=-151.50], EntityZombie['Zombie'/115, l='MpServer', x=-29.50, y=43.00, z=-276.50], EntitySkeleton['Skeleton'/244, l='MpServer', x=65.50, y=19.00, z=-257.50], EntityChicken['Chicken'/117, l='MpServer', x=-28.26, y=66.00, z=-276.90], EntitySquid['Squid'/245, l='MpServer', x=72.46, y=59.61, z=-262.10], EntityZombie['Zombie'/247, l='MpServer', x=64.50, y=18.00, z=-251.50], EntitySquid['Squid'/248, l='MpServer', x=74.76, y=52.86, z=-259.90], EntityRabbit['Rabbit'/120, l='MpServer', x=-31.34, y=83.00, z=-258.18], EntityZombie['Zombie'/249, l='MpServer', x=71.71, y=20.00, z=-187.03], EntityZombie['Zombie'/121, l='MpServer', x=-18.50, y=16.00, z=-251.50], EntityCreeper['Creeper'/250, l='MpServer', x=72.41, y=19.00, z=-187.70], EntityRabbit['Rabbit'/122, l='MpServer', x=-24.55, y=71.00, z=-248.31], EntityZombie['Zombie'/251, l='MpServer', x=66.54, y=21.00, z=-187.25], EntityBat['Bat'/123, l='MpServer', x=-17.04, y=30.10, z=-234.75], EntityBat['Bat'/124, l='MpServer', x=-28.25, y=23.10, z=-239.25], EntityBat['Bat'/252, l='MpServer', x=70.75, y=40.10, z=-146.25], EntityZombie['Zombie'/125, l='MpServer', x=-26.40, y=13.00, z=-148.68], EntityBat['Bat'/126, l='MpServer', x=-12.25, y=18.02, z=-136.52]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1053249992 bytes (1004 MB) / 3271557120 bytes (3120 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 20 mods loaded, 20 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv4-stable-1} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{2.1.3.220} [Not Enough Items] (NotEnoughItems-1.10.2-2.1.3.220-universal.jar) 
	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.9.267-universal.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJAAAA	appliedenergistics2{rv4-stable-1} [Applied Energistics 2] (appliedenergistics2-rv4-stable-1.jar) 
	UCHIJAAAA	classiccombat{1.0.0} [Classic Combat] (ClassicCombat-1.0.0-1.10.2-universal.jar) 
	UCHIJAAAA	CodeChickenLib{2.5.9.267} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.9.267-universal.jar) 
	UCHIJAAAA	CodeChickenCore{2.4.1.102} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.1.102-universal.jar) 
	UCHIJAAAA	counter_guns{1.0.1} [Counter Guns] (CounterGuns-1.10.2-1.0.1.jar) 
	UCHIJAAAA	IC2{2.6.252-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.252-ex110.jar) 
	UCHIJAAAA	galacticraftcore{4.0.0} [Galacticraft Core] (GalacticraftCore-1.10.2-4.0.0.106.jar) 
	UCHIJAAAA	galacticraftplanets{4.0.0} [Galacticraft Planets] (Galacticraft-Planets-1.10.2-4.0.0.106.jar) 
	UCHIJAAAA	guideBook{1.6.1} [Guide Book] (Guide-Book-Mod-1.10.2.jar) 
	UCHIJAAAA	JEI{3.14.7.420} [Just Enough Items] (jei_1.10.2-3.14.7.420.jar) 
	UCHIJAAAA	sgcraft{1.13.2} [SG Craft] (SGCraft-1.13.2-mc1.10.2.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	Loaded coremods (and transformers): 
NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.220-universal.jar)
  codechicken.nei.asm.NEITransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.267-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
AppEngLoadingPlugin (appliedenergistics2-rv4-stable-1.jar)
  appeng.coremod.transformer.IntegrationTransformer
MicdoodlePlugin (MicdoodleCore-1.10.2-4.0.0.106.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
IC2core (industrialcraft-2-2.6.252-ex110.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.59' Renderer: 'GeForce GTX 1080/PCIe/SSE2'
	AE2 Version: stable rv4-stable-1 for Forge 12.18.3.2185
	NotEnoughItems Invalid Fingerprint Reports: 
	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	AE2 Integration: IC2:ON, RF:OFF, RFItem:OFF, Waila:ON, JEI:ON, THE_ONE_PROBE:OFF
	Launched Version: 1.10.2-forge1.10.2-12.18.3.2185
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1080/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.59, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz

EDIT: Tried installing latest version of Galacticraft 1.10.2-4.0.1.121.jar as well, did not fix the issue.
Narrowed it down to SGCraft, seems to work fine without it but when I install SGCraft(Stargate Mod) it crashes when I open the menu for a basic or advanced solar panel. Still haven't figured out why but if I know when I install another mod it causes Galacticraft to crash is that still a relevant issue to solve or not?
EDIT2: Narrowed it down to which version of Galacticraft works with SGCraft and which don't. Currently running "stable" on version 1.10.2-4.0.0.87-BETA of Galacticraft. Any newer version causes the game to crash when opening the gui of a solar panel.

**Comment by radfast** [comment]
Thanks for the version info, this is helpful in finding a cause.

The cause here is actually that **SGCraft** is distributing an outdated version of the CofH API (aka Redstone flux).  I've looked at ```SGCraft-1.13.2-mc1.10.2.jar``` which dates from December 2016, it contains a version of that API which is even older than that.

Galacticraft since version 4.0.0.88 is using the correct current version of the CofH API.  That's why you get this crash.  You would get the same type of crash with any other 1.10.2 mod which references the current version of the CofH API.

The crash is caused by two problems on SGCraft's side:
1.  They are using an outdated version, please try a more recent version of SGCraft if available for 1.10.2
2.  They are **distributing** inside the SGCraft .jar file, an actual copy of the CofH API.  They should not do that, it's very bad practice and causes problems like this.

Can you find a more recent 1.10.2 version of SGCraft?

If not, there's a small chance you can fix the problem by adding to your mods folder anything with a more recent 1.10.2 version of the CofH API.  For example the best place to find it is in ```CoFHCore-1.10.2-4.1.9.13-universal.jar```.   Doing this will not cause any problem on Galacticraft's side.  It will either fix the problem completely here, or SGCraft will now crash in some other way connected with energy.

If that still doesn't fix it you will need to ask the SGCraft devs for help.  This is not a Galacticraft issue.

**Comment by radfast** [comment]
You can also go and criticise the CofH developers for changing their API method signatures mid-way through a Minecraft version (1.10.2).  The individual who decided to do that, is the root cause for this problem.

**Comment by 1CaptainAmerica** [comment]
Once I narrowed it down I kinda figured it wasn't a galacticraft issue, but thanks for the quick reply and help anyways. I'll try adding that and see what happens.

**Comment by radfast** [comment]
You're welcome, good luck!
