### ISSUE TITLE
[1.10.2] Coal Generator not accepting Coal from hopper

### ISSUE THREAD

**Issue by SmokePuddingEveryday** [micdoodle8/Galacticraft#3103]
Minecraft version: 1.10.2
Galacticraft version: Galacticraft-Planets-1.10.2-4.0.0.119
Forge version: Forge 1.10.2-12.18.3.2185

Single player (SSP) or Multiplayer (SMP)? **SMP**

Galacticraft add-ons and other mods installed? **Yes**

Coal generator will not accept coal from the hopper from any side. Coal blocks also do not work.

Screenshots:
![All Mods](https://user-images.githubusercontent.com/35554493/35082885-1f2ca4f4-fbea-11e7-92f2-c1fa541036f0.png)

![Hopper](https://user-images.githubusercontent.com/35554493/35082895-28058690-fbea-11e7-89a0-173d524a4a61.png)
![Coal Generator](https://user-images.githubusercontent.com/35554493/35082896-2818abbc-fbea-11e7-8e80-ba3b41db831b.png)

**Comment by radfast** [comment]
Fixed in next build 127, in all Galacticraft 4 versions.
