### ISSUE TITLE
Download Page Error

### ISSUE THREAD

**Issue by ETStarLight** [micdoodle8/Galacticraft#3106]
https://micdoodle8.com/mods/galacticraft/downloads
Now I can't download GC because error 500.Please fix it.
And……will achievements be back in 1.12.2?

**Comment by SteveKunG** [comment]
You still can download from here: https://ci.micdoodle8.com/

**Comment by ETStarLight** [comment]
Well it's about my introduce page on Chinese websites.The only download page most Chinese players could use directly and quickly is this page…

**Comment by chaNcharge** [comment]
The jenkins website is also down, 503 error.

**Comment by SteveKunG** [comment]
![image](https://user-images.githubusercontent.com/6128413/35186721-4fbd5326-fe4b-11e7-83a3-997cb40561a7.png)

**Comment by MJRLegends** [comment]
Yep jenkins all good over here

**Comment by chaNcharge** [comment]
Oh, now it works. The official download page is still down however.

**Comment by radfast** [comment]
It will be fixed soon, there is a server problem.  The server guys know about it.

**Comment by Daffehh** [comment]
by soon, what do you mean?

**Comment by MJRLegends** [comment]
You can download from https://ci.micdoodle8.com/ @Daffehh you dont need to wait for the sire to come back up to download

**Comment by Daffehh** [comment]
I know, but what about the 1.11 build?

**Comment by MJRLegends** [comment]
You can download the 1.11.2 build from that site too

**Comment by MJRLegends** [comment]
Well you could yesterday, think someone messed up and deleted it haha

**Comment by Daffehh** [comment]
yeah rip

**Comment by radfast** [comment]
**[Alternative download site]**(https://wiki.micdoodle8.com/wiki/DownloadTemp)

**Comment by ETStarLight** [comment]
It seems most Chinese could use Jenkins BUT not this：https://wiki.micdoodle8.com/wiki/DownloadTemp

**Comment by radfast** [comment]
If you want to make a Chinese language version of that page we can add it to the wiki - or you can copy the links to a Chinese wiki.  But if you copy, then a few times a year you would need to update the links manually.  I usually update ~ every 10 versions, or if there is a problem with the main download site like today.

(I'm looking to see if there is a way to have a permanent unchanging URL for each download link)

**Comment by chaNcharge** [comment]
Interesting how you guys chose to put it on a shady download site.

**Comment by radfast** [comment]
Filefactory?  We are not responsible for material other users of that site choose to place there, and I don't see it as better or worse than others like MegaUpload.   These links will only take you to our own absolutely non-shady files.  The advantage of Filefactory is it does not have a usage cap.  Most other sites have daily limits which we can quite easily hit with Galacticraft.  (85 downloads = 1GB, and we have way more than 85 downloads a day, especially when new releases become available.)

**Comment by chaNcharge** [comment]
I see, I just find the "throttling downloads unless you pay" type of sites a bit strange.

**Comment by radfast** [comment]
Throttling does not really matter, if it's only a 12MB download - will still be done in less than 1 minute.

I don't much like those types of sites either, but when our own download server is down we have to do something.

**Comment by chaNcharge** [comment]
Not really, since I haven't really experienced any throttling or any "forced payment". I get a lot of my mods off of there, so I trust CurseForge.

**Comment by MrEyeballs29** [comment]
@chaNcharge You may be correct. But recently curse is in maintenance right now (was on 1/22/2018).

**Comment by ETStarLight** [comment]
@redfast  Could you @ me every time you update en_US.lang?Then I could update zh_CN on next Sunday.

**Comment by BrisingrAerowing** [comment]
The downloads page seems to be back online.

**Comment by hunator** [comment]
@radfast If you wish, you might contact me and I might make backup download mirror for you.

There is just one limitation: You cannot make any money from such downloads. Server in question is in academic network, so there can't be any ads or any other monetisation present there. However it would be free of charge.

**Comment by radfast** [comment]
@hunator  thank you that's a kind offer.   I'll discuss with micdoodle8.
