### ISSUE TITLE
Incompatibility with Legendgear 2

### ISSUE THREAD

**Issue by Starisho** [micdoodle8/Galacticraft#3107]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.7.10
Galacticraft version: 3.0.12.502
Forge version: forge-1.7.10-10.13.4.1614-1.7.10-universal

Single player (SSP) or Multiplayer (SMP)?
SSP & SMP
Galacticraft add-ons and other mods installed?
none
Please provide screenshots / crash report / log as needed.

[New Text Document (4).txt](https://github.com/micdoodle8/Galacticraft/files/1649617/New.Text.Document.4.txt)

**Comment by Starisho** [comment]
It is worth noting I had not had this issue until updating galacticraft.
worked fine in Galacticraft 3.0.12.463
at the time I had wanted to update both this and Galaxyspace, with galaxy space taken out of the equation after the update, problem still persisted.
the problem is that upon clicking the respawn button on the death screen, the game crashes. both SMP and SSP. I believe in SMP you just get disconnected from the server in the client, but upon relogging you are still at the death screen. The only way to get back into the world alive to to delete your Player data.
Hope this helps!

**Comment by radfast** [comment]
The crash is in LegendGear:

        net.nmccoy.legendgear.PlayerEventHandler.handleStatTransfer(PlayerEventHandler.java:233)


Please report it to them, there's nothing we can do about this.

I don't see any clear reason why the change in GC versions from GC 3.0.12.463 to GC 3.0.12.502 would affect this, but it could be because we are doing something **rightI** in build 502 which was not working properly before.
