### ISSUE TITLE
[old build 1.7-3.0.12.375] Space Station Button Does Not Appear At All

### ISSUE THREAD

**Issue by GaygaySusu** [micdoodle8/Galacticraft#3108]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.7.10
Galacticraft version:1.7-3.0.12.375
Forge version: 1.7.10-1.2.0.345

Single player (SSP)

Galacticraft add-ons and other mods installed?
Galacticraft-Planets-1.7-3.0.12.375

Please provide screenshots / crash report / log as needed.

Hi! Whenever i go to space, I seem to not be able to create a space station. I do not know why. Please help.

I am using Baby's First Space Race from Technic Pack btw...
![skjermbilde](https://user-images.githubusercontent.com/35667314/35198294-b93669d6-feec-11e7-8e78-e44600ef1e21.PNG)

**Comment by GaygaySusu** [comment]
I am sorry if I am just retarded and did something wrong

**Comment by MJRLegends** [comment]
Are you traveling to space in a rocket or just pressing the key to display the Galaxy map?

**Comment by radfast** [comment]
Can you overwrite the mods in your pack?   Look in folder ```%appdata%\.technic\modpacks``` for the mods list.

Try this:
* backup the modpack folder for this space pack
* now in the modpack folder, delete the .375 versions of GalacticraftCore, Galacticraft-Planets and MicdoodleCore
* download Galacticraft 1.7.10 latest version from [this link](https://wiki.micdoodle8.com/wiki/DownloadTemp)
* from the zip file you downloaded, copy all 3 files into the modpack folder - these should be version .502

Try that, see how it goes.  I don't know if there will be crashes from other mods in the pack: **normally** when you update Galacticraft it keeps compatibility with older mods.

**Comment by radfast** [comment]
You're welcome to comment further and let us know how you get on.

But the **root cause** of this problem is that Baby's First Space Race pack is using a long-outdated Galacticraft version.  Fix that, and you should have a much better game.
