### ISSUE TITLE
Getting a working 1.12(.2) workspace ?

### ISSUE THREAD

**Issue by Fungie2134** [micdoodle8/Galacticraft#3109]
I am currently trying to get a working Galacticraft 1.12 workspace, for building, contributing and testing.
Using the 1.12.2 forge mdk, extracted, and added the content of both MicdoodleCore 1.12 + Galacticraft 1.12, it build, but running it do not load MicdoodleCore.

So, I tryed to build it separetly, and it fails to build... Following the 1.7.10 tutorial do not help at all, so how to get a working 1.12(.2) workspace ?

**Comment by radfast** [comment]
Instructions are on this project's home page.  If they don't work for you, you're probably not somebody who should be building the workspace.... ..... :)

**Comment by Fungie2134** [comment]
I finally fixed it, I had made a little error...

**Comment by radfast** [comment]
Great news 👍   We look forward to your contributions.

**Comment by radfast** [comment]
1.12.2 is now available to [download](https://www.micdoodle8.com/mods/galacticraft/downloads)
