### ISSUE TITLE
Minecraft launcher crashes 

### ISSUE THREAD

**Issue by BananaBoii** [micdoodle8/Galacticraft#3110]
Minecraft version:1.10.2
Galacticraft version:4.0.1.121
Forge version:12.18.3.2511
I am on Single player and when I launch the game it crashes.

I installed these mods: ExtraPlanets, MJRLegendsLib, Overlord, DragonMounter, MinecraftCapesForge and WorldEdit.

Crash Report: https://pastebin.com/PzUD45HQ

Please help me,
Thank you

**Comment by radfast** [comment]
Don't use the "dev" version of our mod - where did you even get it from????

You can download from [here](https://wiki.micdoodle8.com/wiki/DownloadTemp) today
