### ISSUE TITLE
[Request] Add Moon Turf to the Ore Dictionary

### ISSUE THREAD

**Issue by turbodiesel4598** [micdoodle8/Galacticraft#3112]
Hi there,

Dev of NuclearCraft here - someone just sent me a comment asking if there could be a way for GC moon turf to be harvested and processed in NC machines to produce small amounts of Helium-3. The easiest way for this to be possible would be to add moon turf to the ore dict, so then I can simply reference the entry in a new recipe on my side.

Would you be okay with this feature being added? Thanks in advance.

**Comment by radfast** [comment]
Hi :)   Yes no problem, that sounds like a great use for moon turf.  ```"turfMoon"``` good for you?

We can add this to our 1.12.2 version which should be released later this week (if all goes well...).
Do you want this in any other MC versions also?   We are currently actively maintaining 1.8.9, 1.10.2 and 1.11.2.

**Comment by turbodiesel4598** [comment]
Sounds great - just 1.12.2 should be good thanks, as I'm now only maintaining for that :)

**Comment by BrisingrAerowing** [comment]
> 1.12.2 version which should be released later this week (if all goes well...)

OT, but Awesome. Has all gone well? Galacticraft is one of my favorite mods.

Also, NuclearCraft looks VERY cool and would fit in quite well with a high-tech pack I am making (which will also include Galacticraft as part of the core progression).

**Comment by radfast** [comment]
All is well except that the download server is still down, the people who deal with that are working on it, but nothing more can happen until it's back online.

**Comment by MJRLegends** [comment]
Is the download server the only thing holding the 1.12.2 release back right now

**Comment by radfast** [comment]
Well, the fact there is no 1.12.2 branch on the Jenkins server (which is a related issue) is also a bit of a problem.  We want to do a proper release, not some semi-official build on a different download site.

**Comment by MJRLegends** [comment]
@radfast Im more confused to where the 1.11 branch on jenkins is vanished haha

**Comment by radfast** [comment]
@turbodiesel4598  this will be in Galacticraft (all recent versions) from build 4.0.1.126

**Comment by turbodiesel4598** [comment]
Cheers :)
