### ISSUE TITLE
Parachute bug in depth

### ISSUE THREAD

**Issue by ITheSloth** [micdoodle8/Galacticraft#3113]
SpaceAstronomy-1.7.5-1.7.10

Minecraft version: 1.7.10
Galacticraft version: 1.10.* (from memory, deleted SA1 in favour of SA2)
Forge version: Twitch

Single player (SSP) or Multiplayer (SMP)?
Singleplayer Space Astronomy

Galacticraft add-ons and other mods installed?
Anything from SA1, no additional plugins or mods.

Please provide screenshots / crash report / log as needed.
I believe this issue has happened to me in the past but the best description I can give in the most detail is this:

While wearing a white parachute (created by me in an ME system), I attempted to replace my white parachute in my character backpack with a black parachute (I got from the HQM mod) using shift click on the black parachute in my inventory. After the switch was made the parachute was stuck always on. Death and reload level don't do anything.

**Comment by MJRLegends** [comment]
Yeah this has happened for years but its a rare issue, and theres no known cause or how to reproduce it

**Comment by ITheSloth** [comment]
I'm willing to bet you a job I could not only find it, but fix it. I've already reproduced it in creative.

**Comment by MJRLegends** [comment]
How do you reproduce it?

**Comment by ITheSloth** [comment]
You have to swap the item in your character inventory with shift click from the tool bar.

**Comment by ITheSloth** [comment]
How can I contact you to show?

**Comment by ITheSloth** [comment]
@MJRLegends Sorry I was incorrect you just drop another parachute onto your character inventory and the bug happens. Video here.

https://www.dropbox.com/s/hof1ugra79wufb4/Parachutebug%20edited.mp4?dl=0

**Comment by MJRLegends** [comment]
@ITheSloth im sure this information will be helpful for the galacticraft devs to look at

**Comment by ITheSloth** [comment]
Feel free to pass it along if you are in touch with them. I made this account specifically to draw attention to this bug and I hope I can help in the future.

**Comment by radfast** [comment]
Thanks for the video - now that we can reproduce, we should be able to fix this fairly quickly, this weekend I hope - ITheSloth I'll @ notify you when the next build is available.

**Comment by radfast** [comment]
New build 503 with this fixed - now available on the normal download page.

**Comment by ITheSloth** [comment]
Glad to help. If I see any more I'll drop a thread and tag @radfast. Trying to make a name for myself in the scene and where better to start.

**Comment by radfast** [comment]
Grateful for your help.  Please don't tag me though, I see new threads without it.

**Comment by wdude999** [comment]
I am playing an old version of galactic craft in FTB space astronomy and the glitch happened to me. I fixed it by going into creative, going into a rocket, blasting off, and landing back on earth with no parachute equiped.

**Comment by dj3520** [comment]
@wdude999 As indicated above, the bug should no longer be present as it has been fixed in a newer version.
