### ISSUE TITLE
[Request] API Changes/Additions

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft#3120]
Hello, 

~~Any chance if possible please could add a method in GalacticraftRegistry to deregister/remove space station recipes?~~ **Has been added**

Would be amazing if you could :D 

MJRLegends

**Comment by MJRLegends** [comment]
Also,

The NasaWorkbench recipes currently have the ability to add more than one recipe through the api, and have lists for storing more recipes for each rocket, etc

But the slots are locked and hardcoded to only support one recipe https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/inventory/SlotBuggyBench.java#L43

Any chance if possible could we please tweak this to detect multiple recipes

**Comment by radfast** [comment]
Implemented in the linked commit.

Be careful when adding new recipes, if you move common ingredients (for example Heavy Plating) to different slots then this could mess up the ability to shift-click items into the workbench.
