### ISSUE TITLE
[1.12] Together Forever support for teams

### ISSUE THREAD

**Issue by justinrusso** [micdoodle8/Galacticraft#3122]
Hello,

It would be great if you could add support for [Together Forever](https://minecraft.curseforge.com/projects/together-forever), a team API mod - maybe making it not a dependency by keeping the system you have, but using the together forever team is if the mod exists?

I had requested this API to be made, as a way to get PURELY a team-based API mod for developers to utilize. Would be great if you could add support!

Thanks

**Comment by radfast** [comment]
It has 18 downloads total?!

How about Together Forever adds support for **our** SpaceRace teams.
If something is needed in our API to help compatibility, the developer can ask me.
