### ISSUE TITLE
Can't Use "/forge tps" command (error) (1.12.2)

### ISSUE THREAD

**Issue by kenijey** [micdoodle8/Galacticraft#3123]
Minecraft version:1.12.2
Galacticraft version:build 2
Forge version:2604

Single player (SSP) or Multiplayer (SMP)? singleplayer

Galacticraft add-ons and other mods installed? extra planets is, and yeah it's a modpack

Please provide screenshots / crash report / log as needed.
[latest.log](https://github.com/micdoodle8/Galacticraft/files/1663264/latest.log)

[fml-client-latest.log](https://github.com/micdoodle8/Galacticraft/files/1663222/fml-client-latest.log)
![sds](https://user-images.githubusercontent.com/24831406/35379241-8111f3c2-01c6-11e8-8564-c4709e857e46.PNG)

**_sorry if it's not about galacticraft, but it happened after installing galacticraft_**

**Comment by kenijey** [comment]
oops...it works fine if only galacticraft and extraplanets are installed on forge 2604... :/

**Comment by kenijey** [comment]
uhm.. i think i found the error in "latest.log". it says "**java.lang.IllegalArgumentException: Could not get provider type for dimension -36, does not exist**" but i see that in vanilla -36 is Triton, so if it errors in my modpack, another mod uses -36 as a dimension id so it conflicts?

**Comment by kenijey** [comment]
uhm, but if i run that command in my modpack without galacticraft, i can't see a -36 dim from any mod...

**Comment by MJRLegends** [comment]
"java.lang.IllegalArgumentException: Could not get provider type for dimension -36, does not exist" means dimension conflicts its no bug

**Comment by kenijey** [comment]
yeah but if i run that command without galacticraft and extra planets installed, i don't see a -36 dim from any mod on the dimensions list. could it be hidden or something?

**Comment by MJRLegends** [comment]
All good over here https://gyazo.com/40e5ec12d22adda750110238bb471f0c the mods are working as intended, you have dimension id conflicts you need to change the -36 id in the extraplanets

**Comment by kenijey** [comment]
okay. thanks!

**Comment by MJRLegends** [comment]
No problem
