### ISSUE TITLE
 (1.12.2) Game crash whit optifine and galacticraft installed

### ISSUE THREAD

**Issue by Taliom** [micdoodle8/Galacticraft#3126]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 127
Forge version: 1.12.2-14.23.1.2604
Optifine Verison 1.12.2 C8

Single player (SSP) or Multiplayer (SMP)? Single Player

----------------
Crash Report

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.127.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 1/26/18 4:18 PM
Description: Initializing game

java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/minecraft/client/renderer/EntityRenderer.func_78472_g(F)V @91: invokestatic
  Reason:
    Type 'net/minecraft/world/World' (current frame, stack[0]) is not assignable to 'net/minecraft/client/multiplayer/WorldClient'
  Current Frame:
    bci: @91
    flags: { }
    locals: { 'net/minecraft/client/renderer/EntityRenderer', float, 'net/minecraft/world/World' }
    stack: { 'net/minecraft/world/World' }
  Bytecode:
    0x0000000: 2ab4 049f 9904 152a b400 e2b4 0223 1304
    0x0000010: a2b6 022a 2ab4 00e2 b401 d54d 2cc6 03fc
    0x0000020: b804 a599 0037 2c2a b404 9d2a b401 0c2a
    0x0000030: b400 e2b4 01bf b204 a8b6 0434 23b8 04ae
    0x0000040: 9900 1a2a b400 fcb6 04b1 2a03 b504 9f2a
    0x0000050: b400 e2b4 0223 b602 beb1 2cb8 04b7 4625
    0x0000060: 1303 fd6a 1301 ac62 3804 0336 0515 0511
    0x0000070: 0100 a203 912c b404 bbb6 04c1 1505 1010
    0x0000080: 6c30 1704 6a38 062c b404 bbb6 04c1 1505
    0x0000090: 1010 7030 2ab4 049d 1301 e76a 1302 dc62
    0x00000a0: 6a38 072c b604 c49e 0012 2cb4 04bb b604
    0x00000b0: c115 0510 106c 3038 0617 0625 1304 c56a
    0x00000c0: 1304 c662 6a38 0817 0625 1304 c56a 1304
    0x00000d0: c662 6a38 0917 0717 0713 01a7 6a13 04c7
    0x00000e0: 6213 01a7 6a13 04c7 626a 380a 1707 1707
    0x00000f0: 1707 6a13 01a7 6a13 04c7 626a 380b 1708
    0x0000100: 1707 6238 0c17 0917 0a62 380d 1706 170b
    0x0000110: 6238 0e17 0c13 04c8 6a13 04c9 6238 0c17
    0x0000120: 0d13 04c8 6a13 04c9 6238 0d17 0e13 04c8
    0x0000130: 6a13 04c9 6238 0e2a b401 f30b 959e 004e
    0x0000140: 2ab4 01f5 2ab4 01f3 2ab4 01f5 6623 6a62
    0x0000150: 380f 170c 0c17 0f66 6a17 0c13 04ca 6a17
    0x0000160: 0f6a 6238 0c17 0d0c 170f 666a 170d 1301
    0x0000170: a76a 170f 6a62 380d 170e 0c17 0f66 6a17
    0x0000180: 0e13 01a7 6a17 0f6a 6238 0e2c b404 bbb6
    0x0000190: 04ce b604 d304 a000 2713 04d4 1707 1304
    0x00001a0: d56a 6238 0c13 04d6 170a 1304 d56a 6238
    0x00001b0: 0d13 04d7 170b 1304 d56a 6238 0eb2 04da
    0x00001c0: b601 5099 005b 06bc 0659 0317 0c51 5904
    0x00001d0: 170d 5159 0517 0e51 3a0f 2cb4 04bb b204
    0x00001e0: da08 bd00 0459 0323 b803 2153 5904 25b8
    0x00001f0: 0321 5359 0517 06b8 0321 5359 0617 07b8
    0x0000200: 0321 5359 0719 0f53 b804 dd57 190f 0330
    0x0000210: 380c 190f 0430 380d 190f 0530 380e 170c
    0x0000220: 0b0c b801 e638 0c17 0d0b 0cb8 01e6 380d
    0x0000230: 170e 0b0c b801 e638 0e2a b400 e2b4 01bf
    0x0000240: b204 a8b6 0434 9900 6d2a 2ab4 00e2 b401
    0x0000250: bf23 b604 e138 0f0c 170c 6e38 1017 100c
    0x0000260: 170d 6e95 9e00 090c 170d 6e38 1017 100c
    0x0000270: 170e 6e95 9e00 090c 170e 6e38 1017 0c0c
    0x0000280: 170f 666a 170c 1710 6a17 0f6a 6238 0c17
    0x0000290: 0d0c 170f 666a 170d 1710 6a17 0f6a 6238
    0x00002a0: 0d17 0e0c 170f 666a 170e 1710 6a17 0f6a
    0x00002b0: 6238 0e17 0c0c 959e 0006 0c38 0c17 0d0c
    0x00002c0: 959e 0006 0c38 0d17 0e0c 959e 0006 0c38
    0x00002d0: 0e2a b400 e2b4 019e b404 e438 0f0c 170c
    0x00002e0: 6638 100c 170d 6638 110c 170e 6638 120c
    0x00002f0: 1710 1710 6a17 106a 1710 6a66 3810 0c17
    0x0000300: 1117 116a 1711 6a17 116a 6638 110c 1712
    0x0000310: 1712 6a17 126a 1712 6a66 3812 170c 0c17
    0x0000320: 0f66 6a17 1017 0f6a 6238 0c17 0d0c 170f
    0x0000330: 666a 1711 170f 6a62 380d 170e 0c17 0f66
    0x0000340: 6a17 1217 0f6a 6238 0e17 0c13 04c8 6a13
    0x0000350: 04c9 6238 0c17 0d13 04c8 6a13 04c9 6238
    0x0000360: 0d17 0e13 04c8 6a13 04c9 6238 0e17 0c0c
    0x0000370: 959e 0006 0c38 0c17 0d0c 959e 0006 0c38
    0x0000380: 0d17 0e0c 959e 0006 0c38 0e17 0c0b 969c
    0x0000390: 0006 0b38 0c17 0d0b 969c 0006 0b38 0d17
    0x00003a0: 0e0b 969c 0006 0b38 0e17 0c2c b804 e86a
    0x00003b0: 380c 170d 2cb8 04eb 6a38 0d17 0e2c b804
    0x00003c0: ee6a 380e 1100 ff36 1317 0c13 04ef 6a8b
    0x00003d0: 3614 170d 1304 ef6a 8b36 1517 0e13 04ef
    0x00003e0: 6a8b 3616 2ab4 010c 1505 1304 f015 1410
    0x00003f0: 1078 8015 1510 0878 8015 1680 4f84 0501
    0x0000400: a7fc 6d2a b400 fcb6 04b1 2a03 b504 9f2a
    0x0000410: b400 e2b4 0223 b602 beb1               
  Stackmap Table:
    append_frame(@90,Object[#1203])
    append_frame(@109,Float,Float,Integer)
    append_frame(@185,Float,Float)
    full_frame(@395,{Object[#2],Float,Object[#1203],Float,Float,Integer,Float,Float,Float,Float,Float,Float,Float,Float,Float},{})
    same_frame(@445)
    same_frame_extended(@542)
    append_frame(@621,Float,Float)
    same_frame(@637)
    chop_frame(@691,2)
    same_frame(@701)
    same_frame(@711)
    same_frame(@721)
    full_frame(@887,{Object[#2],Float,Object[#1203],Float,Float,Integer,Float,Float,Float,Float,Float,Float,Float,Float,Float,Float,Float,Float,Float},{})
    same_frame(@897)
    same_frame(@907)
    same_frame(@917)
    same_frame(@927)
    same_frame(@937)
    full_frame(@1027,{Object[#2],Float,Object[#1203],Float,Float},{})
    chop_frame(@1049,3)

	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:522)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:522)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 112112632 bytes (106 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.1.2604 Optifine OptiFine_1.12.2_HD_U_C8 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version      | Source                                    | Signature                                |
	|:----- |:------------------- |:------------ |:----------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft           | 1.12.2       | minecraft.jar                             | None                                     |
	| UCH   | mcp                 | 9.42         | minecraft.jar                             | None                                     |
	| UCH   | FML                 | 8.0.99.99    | forge-1.12.2-14.23.1.2604.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge               | 14.23.1.2604 | forge-1.12.2-14.23.1.2604.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | micdoodlecore       |              | minecraft.jar                             | None                                     |
	| UCH   | mercurius_updater   | 1.0          | MercuriusUpdater-1.12.2.jar               | None                                     |
	| UCH   | galacticraftcore    | 4.0.1.127    | GalacticraftCore-1.12.2-4.0.1.127.jar     | None                                     |
	| UCH   | galacticraftplanets | 4.0.1.127    | Galacticraft-Planets-1.12.2-4.0.1.127.jar | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.127.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '3.3.11672 Compatibility Profile Context' Renderer: 'ATI Radeon HD 3450'
	Launched Version: 1.12.2-forge1.12.2-14.23.1.2604
	LWJGL: 2.9.4
	OpenGL: ATI Radeon HD 3450 GL version 3.3.11672 Compatibility Profile Context, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x AMD Phenom(tm) II X2 B55 Processor
	OptiFine Version: OptiFine_1.12.2_HD_U_C8
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.3.11672 Compatibility Profile Context
	OpenGlRenderer: ATI Radeon HD 3450
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 2

**Comment by MJRLegends** [comment]
Its probably due to the 512mb of ram you have assigned to a modded client

**Comment by Taliom** [comment]
So I have to assing more RAM to the game?

**Comment by MJRLegends** [comment]
Yeah, I dont even think vanilla mc would run on 512mb of ram

**Comment by Taliom** [comment]
I have assing more RAM to teh game but it don't works
The game only crashes when I put optifine in the mods folder but when there is only the 3 galacticraft mods it works fine

The launcher closes when forge starts saying "Loading Entity Render

**Comment by Taliom** [comment]
I try everything, I assing more RAM, reinstall the game and forge, I change versions of optifine and forge but nothing make it work... And it works fine in 1.11.2 but in 1.12.2 I dont know why crashes

Can someone help me please?? :(

**Comment by DarkMatterXCIX** [comment]
Error: java.lang.VerifyError: Bad type on operand stack

I have same issue and have 16gb of ram allocated to it, please fox

**Comment by radfast** [comment]
New release 127 with the fix will be available a bit later today.

**Comment by radfast** [comment]
new release 128 is now available
