### ISSUE TITLE
[Optifine C8] Error: java.lang.VerifyError: Bad type on operand stack

### ISSUE THREAD

**Issue by DarkMatterXCIX** [micdoodle8/Galacticraft#3129]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 127
Forge version: 1.12.2-14.23.1.2555

Single player (SSP) or Multiplayer (SMP)?
SSP but i would hope this works for SMP

Galacticraft add-ons and other mods installed?
No

Please provide screenshots / crash report / log as needed.
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  weaponlib (mw-1.11.6_mc1.12.2.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.2.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.3.2.jar)
  CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.5.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.127.jar)
  BCModPlugin (backpacks 1.12.2 - 3.4.3.jar)
  MalisisSwitchesPlugin (malisisswitches-1.12-5.0.0.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 1/27/18 1:38 AM
Description: Initializing game

**java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/minecraft/client/renderer/EntityRenderer.func_78472_g(F)V @91: invokestatic
  Reason:
    Type 'net/minecraft/world/World' (current frame, stack[0]) is not assignable to 'net/minecraft/client/multiplayer/WorldClient'
  Current Frame:
    bci: @91
    flags: { }
    locals: { 'net/minecraft/client/renderer/EntityRenderer', float, 'net/minecraft/world/World' }
    stack: { 'net/minecraft/world/World' }**
  Bytecode:
    0x0000000: 2ab4 04ae 9904 152a b400 e2b4 0223 1304
    0x0000010: b1b6 022a 2ab4 00e2 b401 d54d 2cc6 03fc
    0x0000020: b804 b499 0037 2c2a b404 ac2a b401 0c2a
    0x0000030: b400 e2b4 01bf b204 b7b6 0443 23b8 04bd
    0x0000040: 9900 1a2a b400 fcb6 04c0 2a03 b504 ae2a
    0x0000050: b400 e2b4 0223 b602 beb1 2cb8 04c6 4625
    0x0000060: 1304 066a 1301 ac62 3804 0336 0515 0511
    0x0000070: 0100 a203 912c b404 cab6 04d0 1505 1010
    0x0000080: 6c30 1704 6a38 062c b404 cab6 04d0 1505
    0x0000090: 1010 7030 2ab4 04ac 1301 e76a 1302 dc62
    0x00000a0: 6a38 072c b604 d39e 0012 2cb4 04ca b604
    0x00000b0: d015 0510 106c 3038 0617 0625 1304 d46a
    0x00000c0: 1304 d562 6a38 0817 0625 1304 d46a 1304
    0x00000d0: d562 6a38 0917 0717 0713 01a7 6a13 04d6
    0x00000e0: 6213 01a7 6a13 04d6 626a 380a 1707 1707
    0x00000f0: 1707 6a13 01a7 6a13 04d6 626a 380b 1708
    0x0000100: 1707 6238 0c17 0917 0a62 380d 1706 170b
    0x0000110: 6238 0e17 0c13 04d7 6a13 04d8 6238 0c17
    0x0000120: 0d13 04d7 6a13 04d8 6238 0d17 0e13 04d7
    0x0000130: 6a13 04d8 6238 0e2a b401 f30b 959e 004e
    0x0000140: 2ab4 01f5 2ab4 01f3 2ab4 01f5 6623 6a62
    0x0000150: 380f 170c 0c17 0f66 6a17 0c13 04d9 6a17
    0x0000160: 0f6a 6238 0c17 0d0c 170f 666a 170d 1301
    0x0000170: a76a 170f 6a62 380d 170e 0c17 0f66 6a17
    0x0000180: 0e13 01a7 6a17 0f6a 6238 0e2c b404 cab6
    0x0000190: 04dd b604 e204 a000 2713 04e3 1707 1304
    0x00001a0: e46a 6238 0c13 04e5 170a 1304 e46a 6238
    0x00001b0: 0d13 04e6 170b 1304 e46a 6238 0eb2 04e9
    0x00001c0: b601 5099 005b 06bc 0659 0317 0c51 5904
    0x00001d0: 170d 5159 0517 0e51 3a0f 2cb4 04ca b204
    0x00001e0: e908 bd00 0459 0323 b803 2153 5904 25b8
    0x00001f0: 0321 5359 0517 06b8 0321 5359 0617 07b8
    0x0000200: 0321 5359 0719 0f53 b804 ec57 190f 0330
    0x0000210: 380c 190f 0430 380d 190f 0530 380e 170c
    0x0000220: 0b0c b801 e638 0c17 0d0b 0cb8 01e6 380d
    0x0000230: 170e 0b0c b801 e638 0e2a b400 e2b4 01bf
    0x0000240: b204 b7b6 0443 9900 6d2a 2ab4 00e2 b401
    0x0000250: bf23 b604 f038 0f0c 170c 6e38 1017 100c
    0x0000260: 170d 6e95 9e00 090c 170d 6e38 1017 100c
    0x0000270: 170e 6e95 9e00 090c 170e 6e38 1017 0c0c
    0x0000280: 170f 666a 170c 1710 6a17 0f6a 6238 0c17
    0x0000290: 0d0c 170f 666a 170d 1710 6a17 0f6a 6238
    0x00002a0: 0d17 0e0c 170f 666a 170e 1710 6a17 0f6a
    0x00002b0: 6238 0e17 0c0c 959e 0006 0c38 0c17 0d0c
    0x00002c0: 959e 0006 0c38 0d17 0e0c 959e 0006 0c38
    0x00002d0: 0e2a b400 e2b4 019e b404 f338 0f0c 170c
    0x00002e0: 6638 100c 170d 6638 110c 170e 6638 120c
    0x00002f0: 1710 1710 6a17 106a 1710 6a66 3810 0c17
    0x0000300: 1117 116a 1711 6a17 116a 6638 110c 1712
    0x0000310: 1712 6a17 126a 1712 6a66 3812 170c 0c17
    0x0000320: 0f66 6a17 1017 0f6a 6238 0c17 0d0c 170f
    0x0000330: 666a 1711 170f 6a62 380d 170e 0c17 0f66
    0x0000340: 6a17 1217 0f6a 6238 0e17 0c13 04d7 6a13
    0x0000350: 04d8 6238 0c17 0d13 04d7 6a13 04d8 6238
    0x0000360: 0d17 0e13 04d7 6a13 04d8 6238 0e17 0c0c
    0x0000370: 959e 0006 0c38 0c17 0d0c 959e 0006 0c38
    0x0000380: 0d17 0e0c 959e 0006 0c38 0e17 0c0b 969c
    0x0000390: 0006 0b38 0c17 0d0b 969c 0006 0b38 0d17
    0x00003a0: 0e0b 969c 0006 0b38 0e17 0c2c b804 f76a
    0x00003b0: 380c 170d 2cb8 04fa 6a38 0d17 0e2c b804
    0x00003c0: fd6a 380e 1100 ff36 1317 0c13 04fe 6a8b
    0x00003d0: 3614 170d 1304 fe6a 8b36 1517 0e13 04fe
    0x00003e0: 6a8b 3616 2ab4 010c 1505 1304 ff15 1410
    0x00003f0: 1078 8015 1510 0878 8015 1680 4f84 0501
    0x0000400: a7fc 6d2a b400 fcb6 04c0 2a03 b504 ae2a
    0x0000410: b400 e2b4 0223 b602 beb1               
  Stackmap Table:
    append_frame(@90,Object[#1218])
    append_frame(@109,Float,Float,Integer)
    append_frame(@185,Float,Float)
    full_frame(@395,{Object[#2],Float,Object[#1218],Float,Float,Integer,Float,Float,Float,Float,Float,Float,Float,Float,Float},{})
    same_frame(@445)
    same_frame_extended(@542)
    append_frame(@621,Float,Float)
    same_frame(@637)
    chop_frame(@691,2)
    same_frame(@701)
    same_frame(@711)
    same_frame(@721)
    full_frame(@887,{Object[#2],Float,Object[#1218],Float,Float,Integer,Float,Float,Float,Float,Float,Float,Float,Float,Float,Float,Float,Float,Float},{})
    same_frame(@897)
    same_frame(@907)
    same_frame(@917)
    same_frame(@927)
    same_frame(@937)
    full_frame(@1027,{Object[#2],Float,Object[#1218],Float,Float},{})
    chop_frame(@1049,3)

	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:522)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:522)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1091677208 bytes (1041 MB) / 3925868544 bytes (3744 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.1.2555 Optifine OptiFine_1.12.2_HD_U_C8 89 mods loaded, 89 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                    | Version                      | Source                                              | Signature                                |
	|:----- |:--------------------- |:---------------------------- |:--------------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft             | 1.12.2                       | minecraft.jar                                       | None                                     |
	| UCH   | mcp                   | 9.42                         | minecraft.jar                                       | None                                     |
	| UCH   | FML                   | 8.0.99.99                    | forge-1.12.2-14.23.1.2555.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                 | 14.23.1.2555                 | forge-1.12.2-14.23.1.2555.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | micdoodlecore         |                              | minecraft.jar                                       | None                                     |
	| UCH   | mercurius_updater     | 1.0                          | MercuriusUpdater-1.12.2.jar                         | None                                     |
	| UCH   | securitycraft         | v1.8.3                       | [1.12.x] SecurityCraft v1.8.3.jar                   | None                                     |
	| UCH   | uncraftingtable       | 1.8-beta6                    | [1.12]UncraftingTable-1.8-beta6.jar                 | None                                     |
	| UCH   | csb_armorstand        | 1.0.4                        | ArmorStandGUI-1.12-1.0.4.jar                        | None                                     |
	| UCH   | backpacks16840        | 3.4.3                        | backpacks 1.12.2 - 3.4.3.jar                        | None                                     |
	| UCH   | battletowers          | 1.6.1                        | BattleTowers-1.12.2.jar                             | None                                     |
	| UCH   | bibliocraft           | 2.4.3                        | BiblioCraft[v2.4.3][MC1.12.0].jar                   | None                                     |
	| UCH   | bloodmoon             | 1.5.2                        | Bloodmoon-MC1.12.2-1.5.2.jar                        | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCH   | buildcraftlib         | 7.99.14                      | buildcraft-7.99.14.jar                              | None                                     |
	| UCH   | buildcraftcore        | 7.99.14                      | buildcraft-7.99.14.jar                              | None                                     |
	| UCH   | buildcraftbuilders    | 7.99.14                      | buildcraft-7.99.14.jar                              | None                                     |
	| UCH   | buildcraftenergy      | 7.99.14                      | buildcraft-7.99.14.jar                              | None                                     |
	| UCH   | buildcraftfactory     | 7.99.14                      | buildcraft-7.99.14.jar                              | None                                     |
	| UCH   | buildcraftrobotics    | 7.99.14                      | buildcraft-7.99.14.jar                              | None                                     |
	| UCH   | buildcraftsilicon     | 7.99.14                      | buildcraft-7.99.14.jar                              | None                                     |
	| UCH   | buildcrafttransport   | 7.99.14                      | buildcraft-7.99.14.jar                              | None                                     |
	| UCH   | chesttransporter      | 2.8.7                        | ChestTransporter-1.12-2.8.7.jar                     | None                                     |
	| UCH   | cjcm                  | 1.0                          | cjcm-1.0.jar                                        | None                                     |
	| UCH   | sanlib                | 1.3.1                        | SanLib-1.12-1.3.1.jar                               | None                                     |
	| UCH   | claysoldiers          | 3.0.0-alpha.4.1              | ClaySoldiersMod-1.12-3.0.0-alpha.4.1.jar            | None                                     |
	| UCH   | codechickenlib        | 3.1.5.331                    | CodeChickenLib-1.12.2-3.1.5.331-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | extendedrenderer      | v1.0                         | coroutil-1.12.1-1.1.24.jar                          | None                                     |
	| UCH   | coroutil              | 1.12.1-1.1.24                | coroutil-1.12.1-1.1.24.jar                          | None                                     |
	| UCH   | configmod             | v1.0                         | coroutil-1.12.1-1.1.24.jar                          | None                                     |
	| UCH   | cosmeticarmorreworked | 1.12.2-v1                    | CosmeticArmorReworked-1.12.2-v1.jar                 | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| UCH   | examplemod            | 1.0                          | craytunes-1.1.jar                                   | None                                     |
	| UCH   | cdm                   | 0.2.1                        | device-mod-0.2.1-1.12.2.jar                         | None                                     |
	| UCH   | craytunes             | 1.1                          | craytunes-1.1.jar                                   | None                                     |
	| UCH   | customspawner         | 3.11.3                       | CustomMobSpawner-3.11.3.jar                         | None                                     |
	| UCH   | cxlibrary             | 1.6.1                        | cxlibrary-1.12.1-1.6.1.jar                          | None                                     |
	| UCH   | ptrmodellib           | 1.0.0                        | Decocraft-2.5.2_1.12.2.jar                          | None                                     |
	| UCH   | props                 | 2.5.2                        | Decocraft-2.5.2_1.12.2.jar                          | None                                     |
	| UCH   | dldungeonsjdg         | 1.11.1                       | DoomlikeDungeons-1.11.1-MC1.12.2.jar                | None                                     |
	| UCH   | mocreatures           | 12.0.3                       | DrZharks MoCreatures Mod-12.0.3.jar                 | None                                     |
	| UCH   | durabilityshow        | 5.0.0                        | Durability Show-1.12-5.0.0.jar                      | None                                     |
	| UCH   | dynmap                | 2.6-beta-1-3                 | Dynmap-2.6-beta-1-forge-1.12.jar                    | None                                     |
	| UCH   | shadowmc              | 3.8.0                        | ShadowMC-1.12-3.8.0.jar                             | None                                     |
	| UCH   | extrarails            | 1.3.0                        | ExtraRails-1.12-1.3.0.jar                           | None                                     |
	| UCH   | cfm                   | 4.1.5                        | furniture-4.1.5-1.12.2.jar                          | None                                     |
	| UCH   | galacticraftcore      | 4.0.1.127                    | GalacticraftCore-1.12.2-4.0.1.127.jar               | None                                     |
	| UCH   | galacticraftplanets   | 4.0.1.127                    | Galacticraft-Planets-1.12.2-4.0.1.127.jar           | None                                     |
	| UCH   | giacomos_fishing_net  | 1.6.1                        | GiacomosFishingNet-1.12.2-1.6.1.jar                 | None                                     |
	| UCH   | grapplemod            | 1.12-v10                     | grapplemod-1.12-v10.jar                             | None                                     |
	| UCH   | furniture             | 2.0.3                        | How'BoutThatFurniture-2.0.3.jar                     | None                                     |
	| UCH   | ichunutil             | 7.1.4                        | iChunUtil-1.12.2-7.1.4.jar                          | None                                     |
	| UCH   | inventorytweaks       | 1.63+release.109.220f184     | InventoryTweaks-1.63.jar                            | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCH   | ironchest             | 1.12.2-7.0.34.820            | ironchest-1.12.2-7.0.34.820.jar                     | None                                     |
	| UCH   | jei                   | 4.8.5.144                    | jei_1.12.2-4.8.5.144.jar                            | None                                     |
	| UCH   | jrftl                 | 1.1                          | Just-Another-Rotten-Flesh-to-Leather-Mod-1.12.2.jar | None                                     |
	| UCH   | lostcities            | 1.0.2                        | lostcities-1.12-1.0.2.jar                           | None                                     |
	| UCH   | malisiscore           | 1.12.2-6.3.2                 | malisiscore-1.12.2-6.3.2.jar                        | None                                     |
	| UCH   | malisisdoors          | 1.12.2-7.2.4                 | malisisdoors-1.12.2-7.2.4.jar                       | None                                     |
	| UCH   | malisisswitches       | 1.12-5.0.0                   | malisisswitches-1.12-5.0.0.jar                      | None                                     |
	| UCH   | radixcore             | 1.12.x-2.2.1                 | RadixCore-1.12.x-2.2.1-universal.jar                | None                                     |
	| UCH   | mca                   | 1.12.2-5.3.1                 | MCA-1.12.x-5.3.1-universal.jar                      | None                                     |
	| UCH   | morefurnaces          | 1.10.4                       | MoreFurnaces-1.12.2-1.10.4.jar                      | None                                     |
	| UCH   | moreplayermodels      | 1.12.2                       | MorePlayerModels_1.12.2(18jan18).jar                | None                                     |
	| UCH   | shetiphiancore        | 3.5.5                        | shetiphiancore-1.12.0-3.5.5.jar                     | None                                     |
	| UCH   | multibeds             | 1.4.3                        | multibeds-1.12.0-1.4.3.jar                          | None                                     |
	| UCH   | multistorage          | 1.4.7                        | multistorage-1.12.0-1.4.7.jar                       | None                                     |
	| UCH   | mw                    | 1.11.6                       | mw-1.11.6_mc1.12.2.jar                              | None                                     |
	| UCH   | nei                   | 2.4.1                        | NotEnoughItems-1.12.2-2.4.1.233-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | harvestcraft          | 1.12.2h                      | Pam's HarvestCraft 1.12.2h.jar                      | None                                     |
	| UCH   | passthroughsigns      | 2.1.3                        | PassthroughSigns-1.12.2-2.1.3.jar                   | None                                     |
	| UCH   | personalcars          | 1.4                          | PersonalCars-1.4.jar                                | None                                     |
	| UCH   | portalgun             | 7.0.0                        | PortalGun-1.12.2-7.0.1.jar                          | None                                     |
	| UCH   | guilib                | 1.11 : updated by subaraki   | PSG Revamed-1.12-1.0.0.0.jar                        | None                                     |
	| UCH   | paintingselgui        | 1.11 v1: updated by Subaraki | PSG Revamed-1.12-1.0.0.0.jar                        | None                                     |
	| UCH   | redstonepaste         | 1.7.5                        | redstonepaste-mc1.12-1.7.5.jar                      | None                                     |
	| UCH   | reptilemod            | 3.8.4                        | reptilemod-1.12.2-3.8.4-79.jar                      | None                                     |
	| UCH   | roguelike             | 1.8.0                        | RoguelikeDungeons-1.12.2-1.8.0.jar                  | None                                     |
	| UCH   | sanplayermodel        | 1.0.3                        | SanLib-1.12-1.3.1.jar                               | None                                     |
	| UCH   | secretroomsmod        | 5.1.13                       | Secret-Rooms-Mod-1.12.2.jar                         | None                                     |
	| UCH   | silentlib             | 2.2.16                       | SilentLib-1.12-2.2.16-97.jar                        | None                                     |
	| UCH   | silentgems            | 2.6.7                        | SilentsGems-1.12-2.6.7-258.jar                      | None                                     |
	| UCH   | sgextraparts          | 1.4.1                        | SGExtraParts-1.12-1.4.1-34.jar                      | None                                     |
	| UCH   | spartanshields        | 1.4                          | SpartanShields-1.12.2-1.4.jar                       | None                                     |
	| UCH   | beneath               | 1.3.0                        | The+Beneath-1.12.2-1.3.0.jar                        | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| UCH   | torohealthmod         | 1.12.2-11                    | torohealth-1.12.2-11.jar                            | None                                     |
	| UCH   | bspkrscore            | at_0.9                       | Treecapitator-1.12-at_0.9a.jar                      | None                                     |
	| UCH   | treecapitator         | at_0.9                       | Treecapitator-1.12-at_0.9a.jar                      | None                                     |
	| UCH   | weather2              | 1.12.1-2.5.7                 | weather2-1.12.1-2.5.7.jar                           | None                                     |
	| UCH   | wolfarmor             | 1.12.2-2.1.0-RELEASE         | wolfarmor-1.12.2-2.1.0.24-RELEASE.jar               | None                                     |
	| UCH   | xaerominimap          | 1.14.5                       | Xaeros_Minimap_1.14.5_Forge_1.12.jar                | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
weaponlib (mw-1.11.6_mc1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.2.jar)
  lumien.bloodmoon.asm.ClassTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.3.2.jar)
  
CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  cubex2.cxlibrary.CoreModTransformer
ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.5.jar)
  shetiphian.asm.ClassTransformer
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.127.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
BCModPlugin (backpacks 1.12.2 - 3.4.3.jar)
  brad16840.core.ClassTransformer
MalisisSwitchesPlugin (malisisswitches-1.12-5.0.0.jar)
  net.malisis.switches.asm.MalisisSwitchesTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 390.65' Renderer: 'GeForce GTX 1070/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.1.2555
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 390.65, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 1600 Six-Core Processor 
	OptiFine Version: OptiFine_1.12.2_HD_U_C8
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 390.65
	OpenGlRenderer: GeForce GTX 1070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by radfast** [comment]
new build 128 now available
