### ISSUE TITLE
Weird rendering when Cubic Chunks is installed (possible conflict, not a Galacticraft bug)

### ISSUE THREAD

**Issue by NoahJelen** [micdoodle8/Galacticraft#3133]
Whenever I use Cubic Chunks and Galacticraft 4 on the same Minecraft version, blocks don't render properly over y=256. I was using Galacticraft in a single player world in creative mode.

Minecraft version:1.11.2
Galacticraft version:4.0.1.121
Forge version:13.20.1.2530

Other installed mods:
BetterFps-1.4.5
CubicChunks-1.11.2-0.0.711.0
Damage-Indicator-1.11.2
malisiscore-1.11.2-5.2.5
Xaeros_Minimap_1.13.1_Forge_1.11
XRay-48

Here are some screenshots and some log files:
[fml-client-1.log](https://github.com/micdoodle8/Galacticraft/files/1671541/fml-client-1.log)
[fml-client-2.log](https://github.com/micdoodle8/Galacticraft/files/1671542/fml-client-2.log)
[fml-client-3.log](https://github.com/micdoodle8/Galacticraft/files/1671543/fml-client-3.log)
[fml-client-latest.log](https://github.com/micdoodle8/Galacticraft/files/1671544/fml-client-latest.log)
[fml-junk-earlystartup.log](https://github.com/micdoodle8/Galacticraft/files/1671545/fml-junk-earlystartup.log)
[latest.log](https://github.com/micdoodle8/Galacticraft/files/1671546/latest.log)
![2018-01-27_23 08 12](https://user-images.githubusercontent.com/29718341/35486511-4193ae58-042c-11e8-9e21-a97c4e013aae.png)
![2018-01-27_23 08 28](https://user-images.githubusercontent.com/29718341/35486512-41acd888-042c-11e8-940e-bde88e3e3416.png)

Here is also some other potentially useful info about my system in which I play Minecraft on:
Operating System: Linux Mint 18.3 with Linux Kernel 4.10.0-40
CPU: Intel Pentium quad core with each core @ 2.16GhZ
RAM: 4GB (possibly DDR3)
Storage medium: 500GB Hard Drive

**Comment by radfast** [comment]
This is a known issue, listed on our [Compatibility wiki page](https://wiki.micdoodle8.com/wiki/Compatibility).  There's nothing much we can do about it, sorry.  We aim to be compatible with everything, but there's always going to be one or two things we cannot fix.

**Comment by Barteks2x** [comment]
I don't actually know what causes the issue here. What happens here shouldn't be possible.

**Comment by Barteks2x** [comment]
I debugged the issue, the issue is that GalactiCraft coremod is transforming RenderGlobal and limiting the player Y location the code sees to 256:
![image](https://user-images.githubusercontent.com/1349112/85631856-8ad78e00-b676-11ea-91fb-89d36c217cef.png)
