### ISSUE TITLE
Galacticraft Fuel not Default

### ISSUE THREAD

**Issue by Sunboyz21** [micdoodle8/Galacticraft#3134]
So whenever I boot up Minecraft the log says that 'Galacticraft Oil is not Default' and 'Galacticraft Fuel is not Default', I didn't mess around with the oil gen in Galacticraft or any other mod so I don't know why this is happening. Please Help

Minecraft version: 1.7.10
Galacticraft version: GalacticraftCore-1.7-3.0.12.502
Forge version: Latest 

Single player (SSP) or Multiplayer (SMP)? SSP

Galacticraft add-ons and other mods installed? No add-ons but I have the following mods installed:

https://imgur.com/a/pTeOu

Please provide screenshots / crash report / log as needed. 

https://imgur.com/a/HXJ78

I think that that's all that is needed to explain the issue, but I will post my Full Log just in case.

https://pastebin.com/u8nv5hXa

**Comment by radfast** [comment]
It's because you have Buildcraft.

Buildcraft's Oil and Fuel are used instead of Galacticraft's standard Oil and Fuel, when Buildcraft is present.

https://wiki.micdoodle8.com/wiki/BuildCraft
