### ISSUE TITLE
PlayerRevive invisible player model

### ISSUE THREAD

**Issue by CreativeMD** [micdoodle8/Galacticraft#3138]
Minecraft version: 1.12.2
Galacticraft version: 1.12.2-4.0.1.128
Forge version: 2604

Multiplayer

Galacticraft add-ons and other mods installed?
Yes

Somebody reported an issue about PlayerRevive (https://github.com/CreativeMD/PlayerRevive/issues/8). PlayerRevive will prevent a player from dying instantly but will make him lay down on the ground for a certain amount of time. Other players can revive him, if not he will bleed to death. As it turns out the player model becomes invisible as soon as a player is laying on the ground if Galacticraft is installed as well.

In order to make a player lay on the ground, it fakes sleeping (only affects rendering): https://github.com/CreativeMD/PlayerRevive/blob/1.11.2/src/main/java/com/creativemd/playerrevive/client/ReviveEventClient.java#L60

**Comment by radfast** [comment]
hey thanks for looking in.  I'll take a look and see what we can do.  Do you have a deobfuscated version of your mod I can use?

**Comment by CreativeMD** [comment]
I don't know if this one works: https://www.dropbox.com/s/da4dfi75628eefx/CreativeCore%20%2B%20PlayerRevive%20obfuscated.jar?dl=1

I never worked with deobfuscated versions :D

**Comment by kenijey** [comment]
i hope this issue gonna be solved soon =)

**Comment by micdoodle8** [comment]
Thanks @CreativeMD for the deobfuscated version, made debugging much easier! Should be fixed in the next build.

**Comment by CreativeMD** [comment]
Nice! Good to hear that, glad you could fix it.
