### ISSUE TITLE
Fluid pipe of length 1 does not transfer fluids

### ISSUE THREAD

**Issue by Mrkuff** [micdoodle8/Galacticraft#3139]
Minecraft version: 1.12.2
Galacticraft version: 1.12.2-4.0.1.128
Forge version: 1.12.2-14.23.1.2555 (recommended version)
Java : 1.8.0_161 (latest)
Single player (SSP)

Mods Installed :
GalacticraftCore-1.12.2-4.0.1.128
Galacticraft-Planets-1.12.2-4.0.1.128
MicdoodleCore-1.12.2-4.0.1.128

Bug encountered in survival with other mods installed and I've reproduce the bug in creative with only the Galacticraft mods in SSP.  When i'm using the wrench on input pipe, the oil move from the tank to the pipe but not to the Refinery machine.  And when used on the output pipe, fuel move from the Refinery to the pipe but not in the tank. (Utilizing 200mb for the pipe). 

For testing the "fuel output" i've used a bucket directly into the Refinery.  Oil never came  from the tank.

![2018-01-31_05 18 01](https://user-images.githubusercontent.com/15654765/35617481-534321bc-0646-11e8-964f-f52ffbb3211c.png)
![2018-01-31_05 18 26](https://user-images.githubusercontent.com/15654765/35617482-5360fae8-0646-11e8-81ab-b616b0145da2.png)
![2018-01-31_05 30 23](https://user-images.githubusercontent.com/15654765/35618087-e28e8a7c-0647-11e8-9623-d8d31a0dc8ed.png)

**Comment by radfast** [comment]
Thank you for reporting, we will prioritise this.

**Comment by MJRLegends** [comment]
I believe its because you need two cables at the start and end to configure them as the wrench will change both sides to input or output otherwise

**Comment by Mrkuff** [comment]
let me check

**Comment by Mrkuff** [comment]
You're right.  With 2 Fluid pipe, i had only to click one of them for the oil to move from the tank to the Refinery machine.

![2018-01-31_08 26 40](https://user-images.githubusercontent.com/15654765/35625527-a7406fd0-0660-11e8-8355-48be13fa8e6d.png)
![2018-01-31_08 26 46](https://user-images.githubusercontent.com/15654765/35625529-a76dac48-0660-11e8-98e2-b7aca2965435.png)

**Comment by MJRLegends** [comment]
Yep i believe (from micdoodle8 recent comment on it somewhere which i cant find atm) its intended this way due to theres mo many possible connections to make the wrench change between different connection types on each one cable so its just set up to change all connections to either nothing or input or output.

**Comment by Mrkuff** [comment]
I'm not finding the Wiki page for "Fluid Pipe", but may be nice to add this information to the future one.
I suppose this behavior is for all type of "cables" as well.  Thank for the input.

**Comment by radfast** [comment]
Thanks all - you are totally right, this is a known issue / mod design feature which has been raised before.

We need to make a Wiki page for this - @Mrkuff  can we use your screenshots for that please?

**Comment by Mrkuff** [comment]
sure, would be proud of it :D

**Comment by Mrkuff** [comment]
do you want one without the timestamp ?

**Comment by radfast** [comment]
oh yes, that would be nice - the first one (with pipes length 1) is already good, but if the second screenshot (with pipes length 2) can be taken from a similar angle that will look tidy on the Wiki

**Comment by Mrkuff** [comment]
There you go

![2018-02-01_02 14 41](https://user-images.githubusercontent.com/15654765/35665846-c3001578-06f5-11e8-9440-652bbd1b82e3.png)

**Comment by radfast** [comment]
beautiful, thank you - I'll aim to get that up this weekend
