### ISSUE TITLE
The setup is crashing

### ISSUE THREAD

**Issue by Ammolite** [micdoodle8/Galacticraft#3141]
I downloaded Galacticraft only, and then it told me to install the other 3, I installed them, and then the setup is crashing. It worked before, in fact, if it didn't it wouldn't tell me to install the other 3.
Please help me, I really want this mod

**Comment by radfast** [comment]
If you want help, you must give more information!

1. Post the crash report

2. Post a list or screenshot of your ```/mods``` folder

3. Make sure you followed the [instructions](https://wiki.micdoodle8.com/wiki/Tutorials/Galacticraft_Installation_Guide)


The most common noob type problems are:

- trying to use the mod in the wrong Minecraft version

- having multiple copies of the mod in your ```/mods``` folder

- trying to use the ```-dev``` version of the mod when you are not a software developer

**Comment by Ammolite** [comment]
Well, I checked I just downloaded the 3 things that site told me to - Plants, Core and Mcdoodiecore
![modds](https://user-images.githubusercontent.com/36047955/35694604-7ea7eef6-078a-11e8-9c56-fccda434acd9.png)
also, i am using 2555, and it doesn't work

**Comment by MJRLegends** [comment]
> I installed them, and then the setup is crashing

Please post the crash log your getting

**Comment by Ammolite** [comment]
That's the weird thing, I don't get any crash log, it just shows the icon, wait a few seconds, and then crash

**Comment by Romsik788** [comment]
Run minecraft with the console. When the game crashes, copy the contents of the console and paste it here.

**Comment by Ammolite** [comment]
what do you mean by content of console?

**Comment by wamc2017** [comment]
Hmm, if the game crashes at the start without producing a crash is mostly an issue if you use outdated mod versions. The AnyDimensionsModbeta3.1 is for 1.7.10 only (I haven't found any update through google), maybe that's the issue...

You could activate the output log (where you see the content of the console) by clicking Settings in the launcher and flipping the "Open output log when the game starts" switch ;)

![output log](https://user-images.githubusercontent.com/33242447/35704789-e2fb5904-07a0-11e8-9aac-e52a1f52bf7f.png)

**Comment by MJRLegends** [comment]
Running 1.7.10 mods with 1.12.2 would be the issue yeah, which means this isnt a galacticraft issue

**Comment by radfast** [comment]
seems like this can be closed

@Ammolite please post details if there's a reason to think this **is** a Galacticraft issue

**Comment by Ammolite** [comment]
Well, as I said before; before I even downloaded galacticraft, it worked perfectly.
Also,@wamc, I removed the mod, and it did nothing
BTW here's the log - 
![logg](https://user-images.githubusercontent.com/36047955/35725958-e5be04aa-080b-11e8-9fba-9d5ffd025a6a.png)

**Comment by MJRLegends** [comment]
Your problem isn't Galacticraft

**Comment by Ammolite** [comment]
Well ok, I'll try to see what it is

**Comment by Ammolite** [comment]
Also, thanks for the help! Appreciate it ^_^

**Comment by wamc2017** [comment]
Have you updated Galacticraft (and dependencies) to 132 which was released earlier? 129 got some problems with RFTools Dimensions: https://github.com/micdoodle8/Galacticraft/issues/3142

Also the first lines of the log aren't very helpful, but I think updating GC should solve your issue... :smile:

**Comment by radfast** [comment]
@Ammolite  yes this could be the RFTools Dimensions problem, that has been fixed in the latest Galacticraft.

It will be good to know this is working for you.

**Comment by Ammolite** [comment]
@radfast , yeah, it was the problem, had to remove it
I didnt even used that mod, but maybe you should fix it for people who do use it

**Comment by radfast** [comment]
>  that has been fixed in the latest Galacticraft.

:)
