### ISSUE TITLE
[1.12.2] [4.0.1.129] Crash at start, if other mods are present

### ISSUE THREAD

**Issue by wamc2017** [micdoodle8/Galacticraft#3142]
Minecraft version: 1.12.2
Galacticraft version: 1.12.2-4.0.1.129
Forge version: 14.23.1.2608

Single player (SSP) or Multiplayer (SMP)?
SSP & SMP (crash at the game start)

Galacticraft add-ons and other mods installed?
Happens only when other mods like RFTools Dimensions (and dependencies) or ExtraUtilities are installed.

Please provide screenshots / crash report / log as needed.
Crashlog with only Galacticraft and RFTools Dimensions (and dependencies) installed: https://pastebin.com/u2ZXpgfK
Crashlog with only Galacticraft and ExtraUtilities (and dependencies) installed: https://pastebin.com/c2wCtLqH

Doesn't happen with version 1.12.2-4.0.1.128. I will report to the other issue trackers, if this is not a galacticraft issue... :smiley: 
May be the same issue as https://github.com/micdoodle8/Galacticraft/issues/3141, but no crashlog is added there, so it could be an other problem... :smile:

**Comment by radfast** [comment]
Don't report to the other mods, this is caused by us.  Something in the update from 128 to 129.

**Comment by radfast** [comment]
Please try out new build 130, available to download now.  It should (hopefully...) fix this issue.

It would be great to have your confirmation that the issue is fixed.

**Comment by wamc2017** [comment]
Tried build 130, now the game crashes without other mods installed:
https://pastebin.com/uz9rnbet

**Comment by radfast** [comment]
Please see my updated message, please try 131

**Comment by wamc2017** [comment]
Extra Utilities is fine with 131, RFTools throws an error: https://pastebin.com/e024VntG

**Comment by radfast** [comment]
OK that's one improvement at least :)   Looking at RFTools now.   Thank you for your patience with this.

**Comment by wamc2017** [comment]
Thanks for looking into it, if I should test a new version, leave a comment... :smile:

**Comment by radfast** [comment]
Build 132 now ready for download.  This should cover the RFToolsDim crash too now.  There could still be something else in RFToolsDim but keeping fingers crossed ...

**Comment by wamc2017** [comment]
Thanks again, build 132 looks fine, have played for an hour and visited some RFTools and GC Dimensions, everything seems ok. :+1:
