### ISSUE TITLE
Crash between Custom Mob Spawner and Galacticraft

### ISSUE THREAD

**Issue by DarkMatterXCIX** [micdoodle8/Galacticraft#3143]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version:1.12.2
Galacticraft version:4.0.1.132
Forge version:14.23.1.2605

Single player (SSP) or Multiplayer (SMP)?
Multiplayer
Galacticraft add-ons and other mods installed?
Extra Planets, removed Extra Planets and it still happened, thanks much!
Please provide screenshots / crash report / log as needed.
Creash Report - https://pastebin.com/7vdJgigS
Log - https://pastebin.com/WAEY54K0
Log - https://pastebin.com/C4s7zuzd

did ask for help from multiple other devs as i didn't know the exact issue but they said its just a issue between Custom Mob Spawner and Galactic craft, they said report it to you as you would know how to fix it hopefully in a future update/bug fix. If you need anything else let me know I will reply! thanks so so much and incredible work!

**Comment by DarkMatterXCIX** [comment]
I got in touch with the Custom Mow Spawner dev and they said it's okay on their end, they said it's just a issue with your mod and theirs, sorry about reporting you probably got your hands full, but thanks much

**Comment by DarkMatterXCIX** [comment]
But if u need me to replicate the issue so u can get another log or anything let me know

**Comment by radfast** [comment]
It's an issue in CustomMobSpawner.  Not our mod.  Something to do with their filesystem access:

>   java.lang.Error
    at java.io.WinNTFileSystem.checkAccess(Native Method)
    at java.io.File.canRead(Unknown Source)
    at drzhark.customspawner.configuration.CMSConfiguration.load(CMSConfiguration.java:295)
    at drzhark.customspawner.environment.EnvironmentSettings.processEntityConfig(EnvironmentSettings.java:406)
    at drzhark.customspawner.environment.EnvironmentSettings.registerEntity(EnvironmentSettings.java:341)
    at drzhark.customspawner.environment.EnvironmentSettings.initializeEntities(EnvironmentSettings.java:212)
    at drzhark.customspawner.utils.CMSUtils.addWorldEnvironment(CMSUtils.java:143)

**Comment by radfast** [comment]
**Something to try - maybe this will workaround the crash in CustomMobSpawner**

Before starting the game, try manually creating empty folders for the needed folders for the Galacticraft dims in your world save folder.  For standard Galacticraft (without addons) that's:

DIM-28
DIM-29
DIM-30
DIM-31

(If you add ExtraPlanets or other addons you will need a lot more!)

**Comment by DarkMatterXCIX** [comment]
Bro that issue that person had with the devs is the exact same one I am having!!!! WTF!! They banned me a while ago and I made a new account as someone else cause I wanted to see wtf they r doing over there... they r garbage

**Comment by DarkMatterXCIX** [comment]
I will try out your ideas here in a sec and pray for the best

**Comment by radfast** [comment]
Yes that should work, **if** the problem here is that CMS doesn't understand about missing / empty dim folders.

**Comment by radfast** [comment]
Please let me know if it works, then we can add this tip to our wiki and help everybody.

**Comment by DarkMatterXCIX** [comment]
Wholy crap it's working as of rn..... genius!!! Thank you thank you thank you!!! So sick of dealing with him, he has his head so far in his ass thinking he owns minecraft and people have to pay him to play his mods its just trash

**Comment by DarkMatterXCIX** [comment]
So create a world without CMS, then add it on after it has made all folder for galacticraft and its add ons

**Comment by DarkMatterXCIX** [comment]
Never mind.... I went to another dimension... it worked for a bit. Went back home.. And got this crash log Pastebin

**Comment by DarkMatterXCIX** [comment]
https://pastebin.com/RsYq5NQi

**Comment by DarkMatterXCIX** [comment]
It crashes everyone the server does now. So.... cms is garbage and we will all leave it at that, thanks much guys
