### ISSUE TITLE
Game Difficulty changes not sticking after world saved in SSP

### ISSUE THREAD

**Issue by Zer0Lyfe** [micdoodle8/Galacticraft#3146]
Minecraft version:1.12.2
Galacticraft version: 1.12.2-4.0.1.132
Forge version:14.23.2.1611

Single player (SSP) or Multiplayer (SMP)?
Both
Galacticraft add-ons and other mods installed?
No other than dependencies.
Please provide screenshots / crash report / log as needed.

AS had it fixed on their end before my initial post about this but it is being caused by GC.
If you need anymore then this ill provide as long as i can.

Initial Post: https://github.com/micdoodle8/Galacticraft/issues/3131
https://github.com/HellFirePvP/AstralSorcery/issues/534 (he explains why it happens here)
https://www.youtube.com/watch?v=PUri31n102o (this shows how the bug works but if you need another video i can do it.) also the ignore the creation of the first world as it will happen even if you have one world

![image](https://user-images.githubusercontent.com/28994351/35767157-a43fc042-0921-11e8-8737-57bacf762a02.png)

This is the link to the github page of the 1.12.2 version in the image(as it has been updated more recently than the master branch):
https://github.com/micdoodle8/Galacticraft/blob/MC1.12/src/main/java/micdoodle8/mods/galacticraft/core/util/WorldUtil.java

**Comment by Zer0Lyfe** [comment]
sorry about having posting another issue but had just talked to HellFirePvP about this and he has identified the cause of the bug

**Comment by radfast** [comment]
@Zer0Lyfe  I don't understand the actual **issue** you are reporting.

Galacticraft **by design** registers its planets dimensions when the game starts, we call this static loading of dimensions.  (We also offer the ability to designate some space stations for static loading, by config or using an in-game command.)

This feature is necessary for several reasons:
* so that teleporters from some other mods can work, if the target location is on a different planet
* so that **/home** and similar commands in Bukkit/Sponge server plugins can work, if the target location is on a different planet
* so that other intra-dimension features like our Launch Controllers can work properly

In the days of Bukkit, there were server-side configs to give the server owner fine control over this.  I expect Sponge has the same, but I haven't looked into it.  Generally, properly managed servers **want** dimensions to be statically loaded for everything to work correctly.

It's not something I plan to change.

I have not understood why this is causing an issue for you, in game - or is it only "tidiness" you are concerned about?

A loaded dimension should not impose any server load, unless it has loaded chunks.  If another mod is causing server load, for a dimension with 0 loaded chunks, that's something the other mod needs to work on fixing.

Your video suggests it is something connected with two worlds in the same SSP game session?

**Comment by Zer0Lyfe** [comment]
The difficulty doesn't change when reloading the world after e.g closing the client, re-entering in the same session.

**Comment by Zer0Lyfe** [comment]
so it "resets" the difficulty to the default difficulty

**Comment by radfast** [comment]
OK, I see that's a bug.  But it's a bug in **vanilla/Forge** - you can reproduce it if you change the difficulty to Hard, lock it, click yes on the message, and then **immediately** quit the game like in your video.

If you play the game for a few seconds after changing the difficulty, then the difficulty change seems to stick OK, with Galacticraft present.

**Comment by Zer0Lyfe** [comment]
But it also happens when leaving the game 10 minutes after loading the world and is repeatable over and over with **your** mod and AS.

**Comment by Zer0Lyfe** [comment]
i was in a world for over 2 hours and it still did the same thing so it isn't about being instant.

**Comment by radfast** [comment]
OK, I hear you - even so, I'm going to need some convincing that it's a problem we are causing.  I will happily discuss some more with @HellfirePVP as requested https://github.com/HellFirePvP/AstralSorcery/issues/534#issuecomment-362816395 and see where get to.

**Comment by Zer0Lyfe** [comment]
sorry about this Radfast but this bug just doesn't want to disappear from the face of the earth. It gets fixed but then appears like 3 days after the fix so i'm sorry about being a bit aggressive.

**Comment by Zer0Lyfe** [comment]
It seen it happens with just GC and the deps so it isn't interaction and i did give it time to load in and waited 5 mins to exit and re-entered the world (**after like 2 minutes to let it all unload**) and it had reset the difficulty to normal(the default)

**Comment by radfast** [comment]
hmm ok, more tests show that this **can** happen with Galacticraft alone.

Looks like no connection with AstralSorcery mod, so I think we can stop troubling HellFirePVP (unless there's some other AstralSorcery interaction @Zer0Lyfe ?)

**Comment by Zer0Lyfe** [comment]
Nah no other buggy interactivity :)

**Comment by Josral** [comment]
I am having the same issue.  Galacticraft changes difficulty back to normal. This bug was present in the 1.11.2 version for me as well. Tested with Galacticraft as the only mod installed to verify that no other mod is responsible.

**Comment by radfast** [comment]
@Josral  thank you, yes this seems a problem in earlier versions as well.  Thinking about it, I've noticed it for months but assumed it was specific to my development environment (I normally play Minecraft inside a Java development environment).

This issue thread has "morphed" from being a comment about static dimension loading for planets (though I never understood there to be any **actual** issue), to an actual report of an unrelated issue about the Game Difficulty....

**Comment by TheQuadShot** [comment]
Just my two cents worth, Are you sure that this isn't related/caused by the addition of the ability to lock game settings in 1.8? I recall reading something about it in the forums (people not able to change difficulty "mid" game).

**Comment by radfast** [comment]
Your two cents always greatly valued :) 

What's happening is this:  (typical scenario for me testing things in-game) create a single player world with Normal difficulty, play a while, then switch to Peaceful when mobs become a bother.  It switches to Peaceful OK and the mobs disappear.  Save and Exit, then reload the world, and it will have switched back to Normal difficulty.   And this happens **even if you use the lock to lock your change to Peaceful** (and click Yes in the dialog asking if you are sure).

**Comment by TheQuadShot** [comment]
I really don't think this is a GC issue... I recall reading that people had this same problem and GC could not have been in every game with so many people reporting it. (not able to change difficulty/difficulty locked but doesn't show that it is locked/changed difficulty but after reload/relaunch setted reverted.)

**Comment by Zer0Lyfe** [comment]
I know it WAS an AS with mods like TF and Advanced Rocketry but that has been fixed in the 1.8.5v version of AS

**Comment by Josral** [comment]
Experimentation shows that GC is making the change during game load.

Test: Create a non-GC world. No GC mods.  Set difficulty to anything but normal.  Exit game and add GC mods.  Go back in. Load your non-GC world. The save held.  Create a new world with the GC mods present.  Funny thing is that the new world will have the difficulty setting of the first world as opposed to 'normal'.  Change your difficulty in the second world to something else.  Exit to menu.  Reload second world and the difficulty loads the same as the first world.  The save did not hold it seems.  Change the difficulty in second world again.  Exit the game without re-entering second world.  Remove GC mods.  Re-enter the game and load the second world.  The save holds.  Conclusion: GC is making it's changes during world load.

**Comment by radfast** [comment]
Thank you for that testing!  I'm sure I can fix this soon with that info.

**Comment by radfast** [comment]
This issue is fixed from next build 158.
