### ISSUE TITLE
crash on mac

### ISSUE THREAD

**Issue by metxo** [micdoodle8/Galacticraft#3149]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version:1.12.2
Forge version:1.12.2

Single player (SSP)

Galacticraft add-ons and other mods installed? jei

Please provide screenshots / crash report / log as needed.
The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: micdoodle8.mods.galacticraft.core.TransformerHooks.getWorldBrightness(Lnet/minecraft/client/multiplayer/WorldClient;)F

**Comment by radfast** [comment]
I think this was fixed already.  You didn't say which exact version you are running?

please check you have the latest version from our [download site](https://www.micdoodle8.com/mods/galacticraft/downloads)

if it's still a problem with that, please comment or re-open

**Comment by metxo** [comment]
thank you, it worjed :)
