### ISSUE TITLE
Gas Liquefier don't accept oxygen from pipes

### ISSUE THREAD

**Issue by QuantumStatement** [micdoodle8/Galacticraft#3150]
Minecraft version: 1.11.2
Galacticraft version: 4.0.1.132
Forge version: 13.20.1.2386

Single player (SSP) or Multiplayer (SMP)?
Singleplayer

Galacticraft add-ons and other mods installed?
None

Please provide screenshots / crash report / log as needed.

Gas Liquefier don't accept oxygen from pipes

**Comment by TheQuadShot** [comment]
Please clarify, Are you trying to get it from the atmosphere or a tank? Did you use the wrench on the pipe? If you trying to get it from the atmosphere then you need an atmospheric valve.

**Comment by QuantumStatement** [comment]
I am trying to get oxygen from tank, Oxygen Collector and Oxygen Storage module. Yes, I am used the wrench on the pipe when I try to get oxygen from tank.

**Comment by radfast** [comment]
>  Please provide screenshots / crash report / log as needed.

**Comment by QuantumStatement** [comment]
![2018-02-06_22 32 59](https://user-images.githubusercontent.com/35406698/35880168-3a7cd1f8-0b8e-11e8-8bd6-2aa50fca85f1.png)
![2018-02-06_22 33 11](https://user-images.githubusercontent.com/35406698/35880177-43dce60c-0b8e-11e8-9be4-8d5ff2760457.png)
![2018-02-06_22 33 29](https://user-images.githubusercontent.com/35406698/35880179-4588f374-0b8e-11e8-9cac-7aa6dc8b3bb0.png)

**Comment by radfast** [comment]
It's the wrong type of Oxygen.  The Oxygen Collector makes a breathable oxygen mixture for breathing - you can put it into wearable oxygen tanks.  But you can't put it into this machine - for this you need pure oxygen from a Water Electrolyser (or from another mod).

https://wiki.micdoodle8.com/wiki/Gases

**Comment by QuantumStatement** [comment]
Thanks for explanation
