### ISSUE TITLE
Gas Liquefier eats up Universal fluid cells from IC2

### ISSUE THREAD

**Issue by QuantumStatement** [micdoodle8/Galacticraft#3151]
Minecraft version: 1.11.2
Galacticraft version: 4.0.1.132
Forge version: 13.20.1.2386

Single player (SSP) or Multiplayer (SMP)?
Singleplayer

Galacticraft add-ons and other mods installed?
IndustrialCraft 2 version 2.7.86-ex111

Please provide screenshots / crash report / log as needed.
![2018-02-07_00 10 12](https://user-images.githubusercontent.com/35406698/35885310-7f777bfe-0b9e-11e8-8f36-249ab72d910b.png)
![2018-02-07_00 10 23](https://user-images.githubusercontent.com/35406698/35885316-8210a5e8-0b9e-11e8-8796-69b9d42f525e.png)

If you put an Universal fluid cell or Forge bucket with proper gas/liquid to input slot of Gas Liquefier, then they disappear

**Comment by radfast** [comment]
Thanks, we'll investigate.

**Comment by radfast** [comment]
Fixed in next build 134.
