### ISSUE TITLE
Crash About Ticking Entity (Can't fly anywhere)

### ISSUE THREAD

**Issue by mike40376** [micdoodle8/Galacticraft#3154]
This occurs whenever me or anybody in the server tries to leave Earth on a rocket.
Minecraft version: 1.7.10
Galacticraft version: 1.7-3.0.12.465
Forge version: 1.7.10-1.2.0.345-universal

Single player (SSP) or Multiplayer (SMP)?
SMP
Galacticraft add-ons and other mods installed?
Yes
Please provide screenshots / crash report / log as needed.
[crash-2018-02-07_00.05.05-server.txt](https://github.com/micdoodle8/Galacticraft/files/1701851/crash-2018-02-07_00.05.05-server.txt)

**Comment by radfast** [comment]
First please try updating Galacticraft to the latest.  3.0.12.465 is not the latest for 1.7.10.

If it still crashes with the latest, please post the new crash report - I need the line numbers in the up-to-date crash report.

**Comment by mike40376** [comment]
I have updated the mod and the error still persists when I try to enter orbit.
[crash-2018-02-07_13.20.35-server.txt](https://github.com/micdoodle8/Galacticraft/files/1704265/crash-2018-02-07_13.20.35-server.txt)

**Comment by MJRLegends** [comment]
Which Galacticraft addons do you have installed

**Comment by mike40376** [comment]
I have Planets, Core, and the Micdoodle Core

**Comment by MJRLegends** [comment]
Ok does it do it for every rocket or just a certain tier

**Comment by mike40376** [comment]
Every rocket

**Comment by radfast** [comment]
Looks like maybe you changed the Space Station dimension ID in Galacticraft's config file?   Or a dimension ID conflict, another mod is also using dimension provider IDs -26 and -27?

Please paste your Galacticraft ```core.conf``` config file.

**Comment by mike40376** [comment]
# Configuration file

achievements {
    # Base Achievement ID. All achievement IDs will start at this number.
    I:idAchievBase=1784
}


dimensions {
    # IDs of dimensions where rockets should not launch - this should always include the Nether.
    S:"Dimensions where rockets cannot launch" <
        1
        -1
     >

    # If true, rockets will be unable to reach the Overworld (only use this in special modpacks!)
    B:"Disable rockets from returning to Overworld"=false

    # Set this to true to have an automatic /gckeeploaded for any new Space Station created.
    B:"Set new Space Stations to be static loaded"=false

    # IDs to load at startup, and keep loaded until server stops. Can be added via /gckeeploaded
    I:"Static Loaded Dimensions" <
     >

    # Set this to 0 for no borders (default).  If set to e.g. 2000, players will land on the Moon inside the x,z range -2000 to 2000.)
    I:"World border for landing location on other planets (Moon, Mars, etc)"=0

    # Biome ID for Moon (Mars will be this + 1, Asteroids + 2 etc). Allowed range 40-250.
    I:biomeIDBase=102

    # Dimension ID for the Moon
    I:idDimensionMoon=-28

    # Dimension ID for the Overworld (as seen in the Celestial Map)
    I:idDimensionOverworld=0

    # WorldProvider ID for Overworld Space Stations (advanced: do not change unless you have conflicts)
    I:idDimensionOverworldOrbit=-27

    # WorldProvider ID for Static Space Stations (advanced: do not change unless you have conflicts)
    I:idDimensionOverworldOrbitStatic=-26
}


general {
    # If this is enabled, debug messages will appear in the console. This is useful for finding bugs in the mod.
    B:"Enable Debug Messages"=false

    # By default, you will respawn on galacticraft dimensions if you die. If you set this to true, you will respawn back on earth.
    B:"Force Overworld Spawn"=false

    # Setting this to false will revert night skies back to default minecraft star count
    B:"More Stars"=true

    # If you have FPS problems, setting this to true will help if rocket particles are in your sights
    B:"Disable Spaceship Particles"=false

    # If you're using this mod in virtual reality, or if you don't want the camera changes when entering a Galacticraft vehicle, set this to true.
    B:"Disable Vehicle Third-Person and Zoom"=false

    # If true, this will move the Oxygen Indicator to the left side. You can combine this with "Minimap Bottom"
    B:"Minimap Left"=false

    # If true, this will move the Oxygen Indicator to the bottom. You can combine this with "Minimap Left"
    B:"Minimap Bottom"=false

    # Increasing this will increase amount of oil that will generate in each chunk.
    D:"Oil Generation Factor"=1.8

    # List of non-galacticraft dimension IDs to generate oil in.
    I:"Oil gen in external dimensions" <
        0
     >

    # If this is enabled, GC oil will be added to existing Overworld maps where possible.
    B:"Retro Gen of GC Oil in existing map chunks"=false

    # If this is enabled, copper ore will generate on the overworld.
    B:"Enable Copper Ore Gen"=true

    # If this is enabled, tin ore will generate on the overworld.
    B:"Enable Tin Ore Gen"=true

    # If this is enabled, aluminum ore will generate on the overworld.
    B:"Enable Aluminum Ore Gen"=true

    # If this is enabled, silicon ore will generate on the overworld.
    B:"Enable Silicon Ore Gen"=true

    # Disable Cheese Ore Gen on Moon.
    B:"Disable Cheese Ore Gen on Moon"=false

    # Disable Tin Ore Gen on Moon.
    B:"Disable Tin Ore Gen on Moon"=false

    # Disable Copper Ore Gen on Moon.
    B:"Disable Copper Ore Gen on Moon"=false

    # If true, moon villages will not generate.
    B:"Disable Moon Village Gen"=false

    # If this is enabled, other mods' standard ores and all other features (eg. plants) can generate on the Moon and planets. Apart from looking wrong, this make cause 'Already Decorating!' type crashes.  NOT RECOMMENDED!  See Wiki.
    B:"Generate all other mods features on planets"=false

    # If generate other mods features is disabled as recommended, this setting can whitelist CoFHCore custom worldgen on planets.
    B:"Whitelist CoFHCore worldgen to generate its ores and lakes on planets"=false

    # If ThaumCraft is installed, ThaumCraft wild nodes can generate on the Moon and planets.
    B:"Generate ThaumCraft wild nodes on planetary surfaces"=true

    # Enter IDs of other mods' ores here for Galacticraft to generate them on the Moon and other planets. Format is BlockName or BlockName:metadata. Use optional parameters at end of each line: /RARE /UNCOMMON or /COMMON for rarity in a chunk; /DEEP /SHALLOW or /BOTH for height; /SINGLE /STANDARD or /LARGE for clump size; /XTRARANDOM for ores sometimes there sometimes not at all.  /ONLYMOON or /ONLYMARS if wanted on one planet only.  If nothing specified, defaults are /COMMON, /BOTH and /STANDARD.  Repeat lines to generate a huge quantity of ores.
    S:"Other mods ores for GC to generate on the Moon and planets" <
     >

    # Set to true to make Galacticraft oil register as oilgc, for backwards compatibility with previously generated worlds.
    B:"Use legacy oilgc fluid registration"=false

    # Set to true to make Galacticraft fuel register as fuelgc, for backwards compatibility with previously generated worlds.
    B:"Use legacy fuelgc fluid registration"=false

    # If this is true, the player will parachute onto the Moon instead - use only in debug situations.
    B:"Disable lander on Moon and other planets"=false

    # Spaceships will not explode on contact if set to true.
    B:"Disable Spaceship Explosion"=false

    # While true, space stations require you to invite other players using /ssinvite <playername>
    B:"Space Stations Require Permission"=true

    # If set to true on a server, players will be completely unable to create space stations.
    B:"Disable Space Station creation"=false

    # By default, Galacticraft will override capes with the mod's donor cape. Set to false to disable.
    B:"Override Capes"=true

    # Solar panels will work (default 2x) more effective on space stations.
    D:"Space Station Solar Energy Multiplier"=2.0

    # List non-opaque blocks from other mods (for example, special types of glass) that the Oxygen Sealer should recognize as solid seals. Format is BlockName or BlockName:metadata
    S:"External Sealable IDs" <
        minecraft:glass_pane:0
     >

    # List blocks from other mods that the Sensor Glasses should recognize as solid blocks. Format is BlockName or BlockName:metadata.
    S:"External Detectable IDs" <
        minecraft:coal_ore
        minecraft:diamond_ore
        minecraft:gold_ore
        minecraft:iron_ore
        minecraft:lapis_ore
        minecraft:redstone_ore
        minecraft:lit_redstone_ore
     >

    # Lower/Raise this value to change time between suffocation damage ticks
    I:"Suffocation Cooldown"=100

    # Change this value to modify the damage taken per suffocation tick
    I:"Suffocation Damage"=2

    # Change this if you wish to balance the mod (if you have more powerful weapon mods).
    D:"Dungeon Boss Health Modifier"=1.0

    # Set this to true for increased difficulty in modpacks (see forum for more info).
    B:"Harder Difficulty"=false

    # Set this to true for less metal use in Galacticraft recipes (makes the game easier).
    B:"Quick Game Mode"=false

    # Set this to true for a challenging adventure where the player starts the game stranded in the Asteroids dimension with low resources (only effective if Galacticraft Planets installed).
    B:"Adventure Game Mode"=false

    # Add together flags 8, 4, 2, 1 to enable the four elements of adventure game mode. Default 15.  1 = extended compressor recipes.  2 = mob drops and spawning.  4 = more trees in hollow asteroids.  8 = start stranded in Asteroids.
    I:"Adventure Game Mode Flags"=15

    # If this is enabled, areas sealed by Oxygen Sealers will run a seal check when the player breaks or places a block (or on block updates).  This should be enabled for a 100% accurate sealed status, but can be disabled on servers for performance reasons.
    B:"Enable Sealed edge checks"=true

    # Enable this if the standard canister recipe causes a conflict.
    B:"Alternate recipe for canisters"=false

    # This needs to match the OreDictionary name used in the other mod. Set a nonsense name to disable.
    S:"OreDict name of other mod's silicon usable in Galacticraft"=itemSilicon

    # Should normally be true. If you set this to false, in a modpack with other mods with the same metals, players may be able to craft advanced GC items without travelling to Moon, Mars, Asteroids etc.
    B:"Force the use of Galacticraft's own Meteoric Iron, Desh, Titanium etc in recipes (not their OreDict equivalents)"=true

    # Leave 'KEY_' value, adding the intended keyboard character to replace the letter. Values 0-9 and A-Z are accepted
    S:"Open Galaxy Map"=KEY_M

    # Leave 'KEY_' value, adding the intended keyboard character to replace the letter. Values 0-9 and A-Z are accepted
    S:"Open Fuel GUI"=KEY_F

    # Leave 'KEY_' value, adding the intended keyboard character to replace the letter. Values 0-9 and A-Z are accepted
    S:"Toggle Advanced Goggles"=KEY_K

    # The normal factor is 1.  Increase this to 2 - 5 if other mods with a lot of oil (e.g. BuildCraft) are installed to increase GC rocket fuel requirement.
    I:"Rocket fuel factor"=1

    # Increase to make the mouse drag scroll more sensitive, decrease to lower sensitivity.
    D:"Map Scroll Mouse Sensitivity"=1.0

    # Set to true to invert the mouse scroll feature on the galaxy map.
    B:"Map Scroll Mouse Invert"=false

    # Set to a value between 0.0 and 1.0 to decrease meteor spawn chance (all dimensions).
    D:"Meteor Spawn Modifier"=1.0

    # Set to false to stop meteors from breaking blocks on contact.
    B:"Meteor Block Damage Enabled"=true

    # Update check will not run if this is set to true.
    B:"Disable Update Check"=false

    # Biome Types will not be registered in the BiomeDictionary if this is set to true. Ignored (always true) for MC 1.7.2.
    B:"Disable Biome Type Registrations"=false

    # Space Race Manager will show on-screen after login, if enabled.
    B:"Enable Space Race Manager Popup"=false
}


schematic {
    # Schematic ID for "Add Schematic" Page, must be unique
    I:idSchematicAddSchematic=2147483647

    # Schematic ID for Moon Buggy, must be unique.
    I:idSchematicMoonBuggy=1

    # Schematic ID for Tier 1 Rocket, must be unique.
    I:idSchematicRocketT1=0
}

**Comment by radfast** [comment]
Config looks fine.

That means this issue is now pointing to an inter-mod conflict.  With your modlist of 50+ mods, it's impossible for me to say which one.  If you can help us by testing your modlist in smaller groups, until you figure out which is the 1 mod which is conflicting with Galacticraft in this way, then I can investigate the issue further and try to find a fix.

https://wiki.micdoodle8.com/wiki/Common_Problems#Mod_conflicts:_Binary_Seach_method

**Comment by mike40376** [comment]
I have an addon that runs ID conflict checks let me run that and post the ID files

**Comment by mike40376** [comment]
I'll switch around the Biome/Dimension IDs see if that helps

**Comment by mike40376** [comment]
I tried changing the biome and dimension IDs around but it crashed again. It seems the crash report is exactly the same
[crash-2018-02-07_20.01.10-server.txt](https://github.com/micdoodle8/Galacticraft/files/1705323/crash-2018-02-07_20.01.10-server.txt)

**Comment by radfast** [comment]
it's connected with the space stations somehow.  It's not biome/dimension IDs _per se_, your config looks OK.

Galacticraft dynamically creates a new actual dimension for each player's space station, these are normally DIM2, DIM3, DIM4, etc.

Maybe what's happening here is **one of those** is conflicting with another mod.  Normally Galacticraft will skip that used dimension if another mod already has it, for example we can skip from DIM2 to DIM4 for the next created space station. But if you change around your mod list **after** you already started the game map and made some space stations, then a conflict can still happen - for example you add a mod which wants DIM4 for itself.

Think about which mods you added after the map started, and which other mods add dimensions (for example, Twilight Forest)

Also maybe post a screenshot of your ```world``` folder showing all the DIMs

**Comment by mike40376** [comment]
![image](https://user-images.githubusercontent.com/25348892/35950207-6145cb68-0c43-11e8-9357-0fa2f27f889e.png)

**Comment by mike40376** [comment]
Looks like there is a DIM2 folder already in there. I'll try to find which mod is using it.

**Comment by mike40376** [comment]
Aroma1997 is using it for the Mining World dimension.

**Comment by mike40376** [comment]
I changed the Aroma Mining World dimension ID and deleted its DIM file but still crashes.

**Comment by radfast** [comment]
Can you make a backup copy of your world and mods folder, then try deleting all mods except for Galacticraft and Aroma1997 and see if it still crashes?

Also try:

- Galacticraft alone in this existing saved map (I'm trying to figure out if your map is damaged or if it's only a mod conflict)

- Galacticraft + Aroma in a newly created world:  go to Creative Mode and use the command ```/dimensiontp``` to create a space station immediately.

One more thing to look at: please can you post a screenshot of your ```world/data``` folder on the server.  I'm interested to see if there is a file ```spacestation_2.dat```.   If that's there, maybe exiting the game, deleting that file and re-starting will be enough to fix the problem.

-------

If we can solve the root cause of this following the above steps, that will be great because then we can make sure it can't happen in future for other players.  :)

If we cannot solve the root cause of this soon, then I can code Galacticraft so that it does not crash in this spot but instead silently fails.  That means you will not be able to access a space station on this server but everything else in the game will still work.

**Comment by mike40376** [comment]
I just fixed it.
I went to the /world/data folder and i saw 2 space station files. I deleted those and right after the mod worked perfectly, no crashing at all. The solution was that I had to change the Aroma1997 Mining World dimension ID from 2 to some number (in my instance 160). Since the world was already created I deleted the space staion files in the /world/data folder and I was able to use the mod without problems.

**Comment by radfast** [comment]
ok good job.

You might still need to watch the player permissions if creating those space stations again in future as the player data for specific players might show they already have a different station.  I've just looked at [our guidance](https://wiki.micdoodle8.com/wiki/Tutorials/Space_Station_for_Server_Admins#Guide_to_Galacticraft_dimensions_and_commands) (scroll down to **Deleting a space station** and it recommends to run the ```/ssnewowner``` command _before_ deleting the space station folders.
