### ISSUE TITLE
Crash in 1.12.2 when trying to open creative inventory with galacticraft version 4.0.1.132 

### ISSUE THREAD

**Issue by NoahJelen** [micdoodle8/Galacticraft#3161]
Forge version: 14.23.1.2555
Single Player Creative
Galacticraft add-ons and other mods installed? Nether Noah's Paradise Mod (My own mod) and Quark

More possibly useful info:
  Operating system: Linux Mint 18.3 with Linux kernel 4.10.0-40
  RAM: 8GB DDR4
  Storage: 1TB HDD
  Processor: Intel Core i3 2-core
[crash-2018-02-07_13.26.59-client.txt](https://github.com/micdoodle8/Galacticraft/files/1704654/crash-2018-02-07_13.26.59-client.txt)

**Comment by NoahJelen** [comment]
FYI: I was trying to use galacticraft in eclipse.

**Comment by radfast** [comment]
You need to use the access transformer.  Documentation [here](https://wiki.micdoodle8.com/wiki/GC3_API#Full_Galacticraft_Sources) - that link is also on the main page of this Github ;)
