### ISSUE TITLE
[1.12.2] Crash Upon World Creation

### ISSUE THREAD

**Issue by GiftedPuffer** [micdoodle8/Galacticraft#3168]
Minecraft version: 1.12.2
Galacticraft version: 4.0.1.132
Forge version: 14.23.2.2613

Single player

Galacticraft Add-on:
More Planets

Crash Report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.132.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 2/9/18 2:14 PM
Description: Exception ticking world

java.lang.ArrayIndexOutOfBoundsException: 0
	at micdoodle8.mods.galacticraft.api.prefab.world.gen.BiomeAdaptive.setBodyInstance(BiomeAdaptive.java:98)
	at micdoodle8.mods.galacticraft.api.prefab.world.gen.BiomeAdaptive.setBody(BiomeAdaptive.java:69)
	at micdoodle8.mods.galacticraft.api.prefab.world.gen.WorldProviderSpace.func_177499_m(WorldProviderSpace.java:427)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:186)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at micdoodle8.mods.galacticraft.api.prefab.world.gen.BiomeAdaptive.setBodyInstance(BiomeAdaptive.java:98)
	at micdoodle8.mods.galacticraft.api.prefab.world.gen.BiomeAdaptive.setBody(BiomeAdaptive.java:69)
	at micdoodle8.mods.galacticraft.api.prefab.world.gen.WorldProviderSpace.func_177499_m(WorldProviderSpace.java:427)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:186)

-- Affected level --
Details:
	Level name: New World
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 0 Drop: 0
	Level seed: -4267129713394836219
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 573240216 bytes (546 MB) / 1498034176 bytes (1428 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.2.2613 Optifine OptiFine_1.12.2_HD_U_C6 24 mods loaded, 24 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                  | Version      | Source                                        | Signature                                |
	|:--------- |:------------------- |:------------ |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft           | 1.12.2       | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | mcp                 | 9.42         | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | FML                 | 8.0.99.99    | forge-1.12.2-14.23.2.2613.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge               | 14.23.2.2613 | forge-1.12.2-14.23.2.2613.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | micdoodlecore       |              | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | mercurius_updater   | 1.0          | MercuriusUpdater-1.12.2.jar                   | None                                     |
	| UCHIJAAAA | clarity             | 1.1          | Clarity-Mod-1.12.2.jar                        | None                                     |
	| UCHIJAAAA | codechickenlib      | 3.1.5.331    | CodeChickenLib-1.12.2-3.1.5.331-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | galacticraftcore    | 4.0.1.132    | GalacticraftCore-1.12.2-4.0.1.132.jar         | None                                     |
	| UCHIJAAAA | galacticraftplanets | 4.0.1.132    | Galacticraft-Planets-1.12.2-4.0.1.132.jar     | None                                     |
	| UCHIJAAAA | gravestone          | 1.0.13       | GraveStone-1.12-Graves-1.0.13.jar             | None                                     |
	| UCHIJAAAA | gravestone-extended | 1.1.0        | Gravestone-Extended-Mod-1.12.2.jar            | None                                     |
	| UCHIJAAAA | ichunutil           | 7.1.4        | iChunUtil-1.12.2-7.1.4.jar                    | None                                     |
	| UCHIJAAAA | jei                 | 4.8.5.151    | jei_1.12.2-4.8.5.151.jar                      | None                                     |
	| UCHIJAAAA | lootbags            | 2.5.1        | LootBags-Mod-1.12.2.jar                       | None                                     |
	| UCHIJAAAA | lucky               | 7.5.0        | Lucky-Block-Mod-1.12.zip                      | None                                     |
	| UCHIJAAAA | moreplanets         | 2.0.11       | More-Planets-Mod-1.12.2.jar                   | None                                     |
	| UCHIJAAAA | morph               | 7.1.2        | Morphing-Mod-1.12.2.jar                       | None                                     |
	| UCHIJAAAA | nei                 | 2.4.1        | NotEnoughItems-1.12.2-2.4.1.233-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | placeableitems      | 3.1          | Placeable-Items-Mod-1.12.2.jar                | None                                     |
	| UCHIJAAAA | slimyboyos          | 1.0.0        | SlimyBoyos-Mod-1.12.2.jar                     | None                                     |
	| UCHIJAAAA | bspkrscore          | at_0.9       | TreeCapitator-Mod-1.12.jar                    | None                                     |
	| UCHIJAAAA | treecapitator       | at_0.9       | TreeCapitator-Mod-1.12.jar                    | None                                     |
	| UCHIJAAAA | uncraftingtable     | 1.8-beta6    | Uncrafting-Table-Mod-1.12.1.jar               | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.132.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_C6
	Render Distance Chunks: 2
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13456 Compatibility Profile Context 21.19.142.32768
	OpenGlRenderer: AMD Radeon(TM) R4 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by SteveKunG** [comment]
Oh, "More Planets 2.0.11"....
Please update to 2.0.12 it have been fixed 5 days ago.

**Comment by MJRLegends** [comment]
I have a feeling its due to the more planets your using also it doesn't look like a official one, please only download mods from authors sites and curseforge

**Comment by GiftedPuffer** [comment]
Alright, thanks for the help.

**Comment by radfast** [comment]
@GiftedPuffer  thanks for reporting, hope it's now working OK for you.

Please do report any more issues you have - especially watch what happens if you do Galacticraft things **after** using **Morph** mod to swap player locations, is everything in Galacticraft still working OK for you?  I didn't get round yet to testing Morph in 1.12.2 myself.

**Comment by GiftedPuffer** [comment]
I followed the comments above and everything worked out fine. I love galacticraft so much, hope you keep up the great work! ♥

**Comment by radfast** [comment]
Build 133 is now available from the download site.  Has a really nice new feature: **Hydraulic Platform**
