### ISSUE TITLE
Adventure Mode not working on Server

### ISSUE THREAD

**Issue by knoxhack** [micdoodle8/Galacticraft#3172]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 
1.12.2
Galacticraft version:
1.12.2-4.0.1.137.jar

Forge version: 
1.12.2 - 14.23.2.2617

Single player (SSP) or Multiplayer (SMP)?
SMP

Galacticraft add-ons and other mods installed?
Extra Planets,
More Planets

Please provide screenshots / crash report / log as needed.

Problem:
First player joins fine inside a pod in the asteroid dimension, but other new players starts getting spawned in the overworld dimension with no pod

**Comment by radfast** [comment]
Thanks for reporting.   Does the server have **Sponge**?  (If so which Sponge version)

**Comment by knoxhack** [comment]
Sponge is not installed

**Comment by radfast** [comment]
OK thanks.  This should be fixed in next build 138.  We'll likely release that some time on Saturday.

**Comment by knoxhack** [comment]
Thank you!

**Comment by radfast** [comment]
~~Saturday~~ -> Sunday
