### ISSUE TITLE
Missing OreDict names for some blocks

### ISSUE THREAD

**Issue by QuantumStatement** [micdoodle8/Galacticraft#3175]
Minecraft version: 1.11.2
Galacticraft version: 4.0.1.137
Forge version: 13.20.1.2386

Single player (SSP) or Multiplayer (SMP)?
SSP

Galacticraft add-ons and other mods installed?
IndustrialCraft 2 version 2.7.86-ex111
[JAOPCA](https://minecraft.curseforge.com/projects/jaopca) version 2.1.6.70

Silicon Block, Titanium Block, Lead Block ~~and Meteoric Iron Block~~ don't have OreDict names

**Comment by TheQuadShot** [comment]
How did you determine that they don't have OreDict entries and that they belong to GC? I know silicon is registered in src/main/java/micdoodle8/mods/galacticraft/core/GCBlocks.java. I don't think Titanium or Lead are GC Ore's since they aren't listed in/on the Wiki. Also technically Meteoric Iron isn't an Ore.

**Comment by radfast** [comment]
@QuantumStatement is correct that these are GC blocks without OreDict names.

But it's not clear why they **need** OreDict names.

Galacticraft uses a deliberate recipe system for blocks where to make the block you need 9 ingots, **at least one of which must be a GC ingot** even if they are all oredicted.   This means if you have for example Lead Ingot from 2 mods, you can control whether you craft a GC block or the other mod's block.  Now, the GC block obviously can be crafted back into 9 GC ingots.

Please provide an example of a situation where you actually need these blocks to be OreDicted?

**Comment by QuantumStatement** [comment]
1. GC Lead Block incompatible with IC2 Block Cutting Machine. Of course I may convert GC block to IC2 block, but it become difficult if I don't have any non-GC ingots

2. [JAOPCA](https://minecraft.curseforge.com/projects/jaopca) mod create duplicates of some GC blocks (normally this mod don't do this, because it create block only when don't find another block with the same OreDictionary name)
![2018-02-19_16 19 58](https://user-images.githubusercontent.com/35406698/36381466-b459c578-1596-11e8-9311-67c6069db79c.png)
I also find duplicate Silicon Block when played with Galacticraft and Advanced Rocketry, but for now this is not a problem for me

3. OreDictionary name for Meteoric Iron Block isn't really needed... because JAOPCA already adding it

**Comment by radfast** [comment]
ok those are good reasons, I wasn't aware of JAOPCA

**Comment by radfast** [comment]
implemented in next build 139.

(Not for Meteoric Iron Block because you said that is not needed ...)
