### ISSUE TITLE
[1.12.2] Items already Equipped on a Fresh, New World?

### ISSUE THREAD

**Issue by CDAGaming** [micdoodle8/Galacticraft#3180]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 4.0.1-138 (Present in earlier Versions)
Forge version: 14.23.2.2618 (Present in Earlier Versions)

Single player (SSP) or Multiplayer (SMP)?
Both

Galacticraft add-ons and other mods installed?
ExtraPlanets, MorePlanets

Details & Screenshots: 
When entering a New World, It shows my character with a shield controller as well as one oxygen tank equipped, even though as it is a new world, I didnt obtain either and they do not show in the GUI. 
![2018-02-19 14](https://user-images.githubusercontent.com/16328918/36405064-19b50df2-15b4-11e8-9ab1-ad8d13ec04ff.png)

**Comment by radfast** [comment]
This is likely an issue in **ExtraPlanets** or **MorePlanets** - seems similar to something reported before.

Please test _without_ those two mods in your ```/mods``` folder and see if the issue still occurs.  **(Obviously after removing mods from your /mods folder you must take care not to play any existing world or you can damage it.)**

**Comment by MJRLegends** [comment]
isn't this the bug where you leave one world that you was wearing them and they will render in another? in which case its been in GC for years and been reported loads

**Comment by radfast** [comment]
You're saying it's a GC core bug?  😊

**Comment by MJRLegends** [comment]
@radfast yeah im saying i've seen and had this since 1.7.10

**Comment by MJRLegends** [comment]
i believe something was tweaked with it https://github.com/micdoodle8/Galacticraft/commit/a0e0bbbf8694d27c88c0c0e0e958dd65fa90c408 i was watching a stream earlier and this same issue happened there for MC 1.12.2, i was going to try and take a look myself or report it if i couldnt fix it

**Comment by radfast** [comment]
ok thank you, that's very helpful - shouldn't be too hard to fix, once I figure out what Forge changed in 1.12.2.

**Comment by radfast** [comment]
OK, I **cannot reproduce this** in 1.12.2, tested with Forge 14.23.1.2600.

And the code looks OK - it should reset the client every time you pass through the Minecraft main menu or the Multiplayer servers list.

@CDAGaming please specify exact steps taken to leave World 1 and create a new World 2.  Especially if anything different from what I'm doing:

1. Play World 1 and equip a Shield Controller
2. hit ```Esc``` then **Save and Quit to Title**
3. in Minecraft main menu, click **Singleplayer**
4. click **Create New World**
5. Play World 2
6. hit ```F5``` to view my player in third person

Importantly if **Save and Quit to Title** is not taking you back to the Minecraft main menu then this isn't going to work properly, maybe you have a mod which changes that?

Or maybe something has replaced the Minecraft main menu in your setup?

**Comment by MJRLegends** [comment]
Could it be a conflict with CustomMainMenu mod? Not sure if they use there own screen or just override vanillas one

**Comment by radfast** [comment]
yes definitely it can be that ...

I'm looking to see if we have a way to do this which will be better altogether - this technique of looking at the menu is from Galacticraft 2....

**Comment by MJRLegends** [comment]
Yeah maybe target a client event that happens when exiting a world or multiplayer server if one is there for that

**Comment by CDAGaming** [comment]
Will check if this fixes it when I'm home but Thanks :D

**Comment by radfast** [comment]
It will fix it.  Note that right now the change is only in 1.8 branch, I will merge it up through the branches later tonight ready for build 139.
