### ISSUE TITLE
[1.11.2] Crash after open Gui Celestial Selection

### ISSUE THREAD

**Issue by BlesseNtumble** [micdoodle8/Galacticraft#3181]
Minecraft version: 1.11.2
Galacticraft version: GalacticraftCore-1.11.2-4.0.1.138
Forge version: Forge Mod Loader version 13.20.1.2588
Single player (SSP)

java.lang.IllegalAccessError: tried to access field net.minecraft.client.gui.GuiIngame.overlayMessage from class micdoodle8.mods.galacticraft.core.tick.TickHandlerClient
	at micdoodle8.mods.galacticraft.core.tick.TickHandlerClient.onPreGuiRender(TickHandlerClient.java:325)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_77_TickHandlerClient_onPreGuiRender_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:885)
	at net.minecraftforge.client.GuiIngameForge.renderGameOverlay(GuiIngameForge.java:117)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1146)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1140)
	at net.minecraft.client.Minecraft.run(Minecraft.java:407)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:26)

**Comment by TheQuadShot** [comment]
Maybe a silly question(not sure why the gradle references in  log), are you running the dev build? I can't repro this with GC and jei as only mods installed.

**Comment by BlesseNtumble** [comment]
yes, dev build.

**Comment by radfast** [comment]
@TheQuadShot   the dev build is specifically for running in an IDE.

Standard Minecraft is obfuscated - all class and method names are obfuscated, this prevents casual decompiling although the MCP and Forge are tacitly supported by Mojang and Microsoft (Minecraft "Java Edition" is now sold at a premium on the basis that it has lots of mods).  Example, ```EntitySkeleton.setDead()``` is obfuscated to something like ```bzg.c()```.  This also fractionally improves performance and reduces memory requirements because the strings are shorter.

Forge at runtime translates all obfuscated names to SRG (that's Searge!) names.  Example, ```EntitySkeleton.func_70106_y()``` instead of ```.setDead()```.

Therefore standard release versions of mods use SRG names for referencing all Minecraft code methods and fields.

The deobf version uses English (MCP) names for the same things, which only works when used with the decompiled Minecraft code inside a dev workspace.

**Comment by radfast** [comment]
@BlesseNtumble   you might need to look at your access transformers.   I don't know why ```net.minecraft.client.gui.GuiIngame.overlayMessage``` is not accessible in your workspace, in mine it is a ```public``` field.  I use Forge 1.11.2-13.20.0.2282.

You can edit your local copies of the [access transformers](https://github.com/micdoodle8/MicdoodleCore/tree/1.11/src/main/resources) and rebuild your workspace.

Or comment out these lines in ```TickHandlerClient``` in your local copy of Galacticraft's source code.

**Comment by MJRLegends** [comment]
Yeah i just comment it out

**Comment by radfast** [comment]
hmm actually maybe this can crash a release build too if this is not in the _at?  

Please confirm which version of Forge you're seeing ```net.minecraft.client.gui.GuiIngame.overlayMessage``` as a private field?

**Comment by MJRLegends** [comment]
Im using 1.11.2-13.20.1.2513 for my mods

**Comment by BlesseNtumble** [comment]
protected String overlayMessage = "";

**Comment by radfast** [comment]
OK I'll add this to the _at.

@MJRLegends @BlesseNtumble if you know of any more like this - should be easy to spot because your IDE will report "field / method not visible" errors in Galacticraft source code - please tell me.

**Comment by SteveKunG** [comment]
Wow, sounds weird. Why I'm not getting this crash?

**Comment by radfast** [comment]
@SteveKunG  different Forge versions?  Or you have added another _at from another mod?

**Comment by SteveKunG** [comment]
I use latest Forge for 1.11 workspace and 3 other mod *_at.cfg that don't have the `overlayMessage` field.

`overlayMessage` field is public.
![image](https://user-images.githubusercontent.com/6128413/36484052-958f2d26-174a-11e8-8291-9702417f9018.png)

Also everything is fine.
![2018-02-21_21 05 30](https://user-images.githubusercontent.com/6128413/36484197-0c1a6aa0-174b-11e8-93d2-a18e8ec139a8.png)

**Comment by radfast** [comment]
That's so strange!!!   @BlesseNtumble special Russian version?  ;p

**Comment by BlesseNtumble** [comment]
russian version? what?
i have forge 2588 and last GC4 dev build.
In forge 2588 field overlayMessage is protected

**Comment by BlesseNtumble** [comment]
fixed after add public net.minecraft.client.gui.GuiIngame field_73838_g # overlayMessage in _at.cfg

**Comment by radfast** [comment]
OK, I see the problem.

It was because the MCP name changed from `recordPlaying` to `overlayMessage` in 1.11.2 and we didn't update that.  `field_73838_g` works for all players in obfuscated version - and I guess for most devs also, as this wasn't affected @SteveKunG or me.  I'm not too sure of which situation the setup uses the `_at.deobf` instead of the `_at.cfg` 😕 

Fixed in https://github.com/micdoodle8/MicdoodleCore/commit/21f1768fde6633f794488ee377c496045b330377

Any more like this, please let me know!

**Comment by MJRLegends** [comment]
@radfast i found one more, getting the following error on MC 1.8.9
`java.lang.IllegalAccessError: tried to access field net.minecraft.world.chunk.Chunk.isChunkLoaded`

seems that its missing for MC 1.8.9

**Comment by MJRLegends** [comment]
@radfast i found one more, getting the following error on MC 1.8.9
`java.lang.IllegalAccessError: tried to access field net.minecraft.world.chunk.Chunk.isChunkLoaded`

**Comment by radfast** [comment]
thanks, fixed - https://github.com/micdoodle8/MicdoodleCore/commit/64309054d83989b8fcee3f131e6f60a0635c4422

**Comment by MJRLegends** [comment]
Thanks

**Comment by MJRLegends** [comment]
@radfast i found another one java.lang.IllegalAccessError: tried to access field net.minecraft.client.gui.inventory.GuiContainer.xSize i think this one might be on more than one mc version but i found it on 1.12.2

**Comment by radfast** [comment]
https://github.com/micdoodle8/MicdoodleCore/commit/82b553bc9a0032c51d338e08d3cc2a70f2d979e6

**Comment by MJRLegends** [comment]
@radfast new one java.lang.IllegalAccessError: tried to access field net.minecraft.client.audio.MusicTicker.mc from class micdoodle8.mods.galacticraft.core.client.sounds.MusicTickerGC

**Comment by radfast** [comment]
done, please update your _at

**Comment by MJRLegends** [comment]
@radfast thanks will do
