### ISSUE TITLE
No Confirmation Email on Forums

### ISSUE THREAD

**Issue by Ben12Net** [micdoodle8/Galacticraft#3187]
I haven't received a confirmation email for the Galacticraft Forums, and I can't think of any. way to solve this problem. I can't post on the forum support section, since you need to have a verified account.

**Comment by radfast** [comment]
What username on the forum?  Ben12Net - exactly like that?

**Comment by Ben12Net** [comment]
Got it I'll try it on monday.
My user name is the same as here, I'm sure I typed my email right, and nothing new is in my spam folder.
Nice to meet you, by the way!

**Comment by Ben12Net** [comment]
That's me!

**Comment by radfast** [comment]
Welcome to Galacticraft :)  If the forum isn't working on Monday please do re-post here.  Could be there's a more general problem which we need to fix.

**Comment by EzerArch** [comment]
> For posting on the forum, I think an account has to be at least 7 days old (@EzerArch do you know if that's right?), so please try again on Monday. This is to prevent spam posting on the forum by people trying to sell you guys soap, strange pills, or possibly even themselves...

Hahahahah.... uhmm... As far as I know, @micdoodle8's forum is not sending email verifications. We admins have to manually approve the accounts. :S

**Comment by radfast** [comment]
@EzerArch  I sent you PM on the forum

**Comment by EzerArch** [comment]
Answered.

**Comment by micdoodle8** [comment]
It appears things are working now - I'm getting forum emails, albeit in my spam folder
