### ISSUE TITLE
Shield overlay does not blend against translucent textures

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#3191]
GalacticraftCore-1.12.2-4.0.1.128
Galacticraft-Planets-1.12.2-4.0.1.128
MicdoodleCore-1.12.2-4.0.1.128
MC 1.12.2
Forge 14.23.2.2618
no addons

Player's shield overlay does not blend against water and possibly other translucent elements.

![untitled](https://user-images.githubusercontent.com/6743303/36629542-c374022e-1935-11e8-9355-2cc550936ffb.png)

Per: https://twitter.com/NicosaurusRex99/status/966129068302262272 (not headphone friendly ;) )

**Comment by NicosaurusRex99** [comment]
totally forgot i had music on when i filmed it... oops

**Comment by FrostQ** [comment]
Not only blend against water but entity shadow, entity (if you not to close) and Oxygen Distibutor's & Terraformer's Bubbles

**Comment by micdoodle8** [comment]
Thanks for the detailed report guys! Will be fixed in the next build.
