### ISSUE TITLE
Missing localized names for some ingame config settings

### ISSUE THREAD

**Issue by QuantumStatement** [micdoodle8/Galacticraft#3194]
Minecraft version: 1.11.2
Galacticraft version: 4.0.1.142

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP

Galacticraft add-ons and other mods installed?
None

Please provide screenshots / crash report / log as needed.

Some ingame config settings don't show localized names for languages other than English
Russian language, for example
![2018-02-25_19 42 38](https://user-images.githubusercontent.com/35406698/36644225-1f6fe560-1a68-11e8-9de3-37022e05321b.png)
Chinese language
![2018-02-25_19 44 07](https://user-images.githubusercontent.com/35406698/36644390-c47a6650-1a6a-11e8-8baa-abf363ced339.png)

Full list of unlocalized settings:

- Adventure Game Mode Flags
- Disable Space Race Manager Popup
- Disable Vehicle Third-Person and Zoom
- Use legacy oilgc fluid registration
- Use legacy fuelgc fluid registration
- Must use GC's own space metals in recipes
- Disable Sapphire Ore Gen on Moon
- Disable Biome Type Registrations
- Space Stations Require Permission
- IDSchematicRocketT1

**Comment by radfast** [comment]
Needs some kind person to edit the [Russian language file](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/resources/assets/galacticraftcore/lang/ru_RU.lang)

These are the required names in the lang file:
`gc.configgui.asteroids_flags`
`gc.configgui.enable_space_race_manager_popup`
`gc.configgui.disable_vehicle_camera_changes`
`gc.configgui.use_old_oil_fluid_i_d`
`gc.configgui.use_old_fuel_fluid_i_d`
`gc.configgui.disable_ore_dict_space_metals`
`gc.configgui.disable_sapphire_moon`
`gc.configgui.disable_biome_type_registrations`
`gc.configgui.space_stations_require_permission`
`gc.configgui.id_schematic_rocket_t1`

**Comment by QuantumStatement** [comment]
Last two strings (_gc.configgui.space_stations_require_permission_ and _gc.configgui.id_schematic_rocket_t1_) already have a translation

**Comment by radfast** [comment]
ok those two I have fixed, from next build 143

do you have time to add the other 8 as new ones?

**Comment by radfast** [comment]
Thank you :)

I've also added the strings in the `en_US` so these should migrate through to other languages.
