### ISSUE TITLE
Vapor Spout, Acid and Crash Probes not generate

### ISSUE THREAD

**Issue by FrostQ** [micdoodle8/Galacticraft#3195]
Minecraft version: 1.12.2
Galacticraft version: 4.0.1.142

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Both

Galacticraft add-ons and other mods installed?
Optifine
Buildcraft

Please provide screenshots / crash report / log as needed.
https://imgur.com/ZH8HcFVk

Surface: [128](https://imgur.com/kIfHSHX) | [132+](https://imgur.com/5T6wXlT)
Underground: [128](https://imgur.com/W9pxyXq) | [132+](https://imgur.com/dpmYG26)

**Comment by TheQuadShot** [comment]
By chance do you know about how big of an area you searched?

**Comment by EzerArch** [comment]
Well, this is going to be a two-fold question:

1. @radfast or any coder: does "Generate Structures:ON|OFF" in Create New World window affect galacticraft world gen?
2. Assuming 1 is true, @FrostQ : make sure that "Generate Structures" is on in 'Create New World > More World Options' and create a new world just to be sure.

**Comment by radfast** [comment]
Would be good to have confirmation from someone who  **is** seeing these in a Venus newly generated after build 142? 

- Vapour spout should be found in Venus Valley biomes, so look for the low-lying areas (dirt color changes) - they are small and hard to see but sometimes you can see the vapour rising
- Sulfuric Acid is found below the spout
- Crashed Probes are **rare**, like one every 1000 blocks, you really need to fly around a lot to find one.  

Spectator Mode (`/gamemode 3`) should help you to find Sulfuric Acid pockets easily.

**Comment by radfast** [comment]
@EzerArch:  structures in Galacticraft are the Dungeons and the Abandoned Base.   I think those must be affected by that flag.

Vapour Spout, Crashed Probe and other smaller terrain features are not affected by "Generate Structures".

**Comment by FrostQ** [comment]
Probably happening after build 132
Surface (build 128): https://imgur.com/kIfHSHX
Surface (build 132+): https://imgur.com/5T6wXlT
Underground (build 128): https://imgur.com/W9pxyXq
Underground (build 132+): https://imgur.com/dpmYG26

**Comment by radfast** [comment]
thank you that should help to narrow it down

**Comment by TheQuadShot** [comment]
Spouts/Acid are fine on 1.10.2 and 1.11.2, but they are broken on 1.12.2

**Comment by radfast** [comment]
thank you, I'll check 1.12.2 - thank you for saving me time

**Comment by radfast** [comment]
Guys thank you for these careful reports.  I've found the problem, fixed in next build 144.  72f414b]

Unfortunately, this will have affected - like @FrostQ says - all 1.12.2 versions from builds 132 to 143.  This is a big shame, because any player who has already generated Venus in those versions will be missing the features, until they go to new chunks.

Deleting DIM-31 is probably the only option, and let it regenerate in build 144.    (There is no easy way to retrogen chunks, at least not without risk of damaging player builds.)

I'm very sorry about this.  I didn't notice anything missing because my main 1.12.2 test games both already have a lot of the map on Venus generated.  And on a new game, there is nothing "obviously" wrong - the surface and landscape of Venus still looks OK.

**Comment by radfast** [comment]
I could make a chunk worldgen reset wand item for server owners to use in-game - have thought about that for dealing with a few other situations too - but it would take me a lot of time and I think my time is better spent on Galacticraft proper.  There must be other Minecraft server tools or plugins which can do this already?

(In the old ICBM mod there used to be the **Rejuvenation Explosive** although - like a lot in ICBM - that was badly coded and crash-prone on servers.)

**Comment by MJRLegends** [comment]
Personally i wouldnt worry about it to much it will slowly get better aa people start exploring or start new worlds or/and reset servers thankfully its not a fully needed world gen resource like dungeons.

It was the same with the eggs on mars not generating

**Comment by EzerArch** [comment]
> Deleting DIM-31 is probably the only option, and let it regenerate in build 144. (There is no easy way to retrogen chunks, at least not without risk of damaging player builds.)

There's a trick solution if someone wants to try: install MCEdit, open your world save, delete existing chunks (not those where you have built something on), save, reopen world save on Minecraft to regenerate chunks. As always, back up your precious world!
