### ISSUE TITLE
Galacticraft Planets ingame config doesn't show all settings

### ISSUE THREAD

**Issue by QuantumStatement** [micdoodle8/Galacticraft#3197]
Minecraft version: 1.11.2
Galacticraft version: 4.0.1.142

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP

Galacticraft add-ons and other mods installed?
None

I think Galacticraft Planets ingame config should have more settings. ~~Also it seems that string key for "Dimension ID: Venus" setting is broken~~

Ingame config
![2018-02-25_23 52 53](https://user-images.githubusercontent.com/35406698/36646475-cbec4480-1a88-11e8-8af1-70b5bda7488a.png)

planets.conf
![planetsconfig](https://user-images.githubusercontent.com/35406698/36646467-ba45a42e-1a88-11e8-8bff-0e02e91a002e.png)

**Comment by radfast** [comment]
Thanks.  This will be done right in build 151.
