### ISSUE TITLE
Stuck in bed, character stuck on spot forever if you leave the bed.

### ISSUE THREAD

**Issue by benten2000** [micdoodle8/Galacticraft#3198]
Minecraft version: 1.12.2
Galacticraft version: 4.0.1.142

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP

Galacticraft add-ons and other mods installed?
MicdoodleCore-1.12.2-4.0.1.142

With just these two mods installed when you go to sleep in a bed the screen starts to fade a normal and you can see the sky has become bright but your character is still stuck in the bed with the text box open with the leave bed button on screen.

If you choose to leave the bed your character is now stuck in that one place with any movement pulled back to the same spot, with the bed also stated it is still occupied.

Tried to teleport to a new location but still stuck on that new spot.
Also tried MCEdit to move character and the spawn point but the changes would not save.

**Comment by TheQuadShot** [comment]
I tested this on 1.10.2, 1.11.2, and 1.12.2 Works fine on 1.10.2 **ONLY**
The CryoChamber works fine on all 3 of the listed versions.
Hope that helps

**Comment by radfast** [comment]
Thanks for reporting, this will be fixed in build 143.

**Comment by radfast** [comment]
Build 143 is now available.
