### ISSUE TITLE
can't place moon's block

### ISSUE THREAD

**Issue by R-Josef** [micdoodle8/Galacticraft#3203]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version:1.10.2
Galacticraft version:GalacticraftCore-1.10.2-4.0.1.138

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? SMP

Galacticraft add-ons and other mods installed? Galacticraft-Planets-1.10.2-4.0.1.138 MicdoodleCore-1.10.2-4.0.1.138 sponge

Please provide screenshots / crash report / log as needed.

i found that when i break a moon's block like Moon Turt, and then this block will be add a nbt: 1 tag and i can't place the block anymore.

**Comment by R-Josef** [comment]
i have tested moon turf moon rock, moon dirt, and moon dungeon brick, they all have this problem, aren't dungeon brick unbreak?

**Comment by radfast** [comment]
dungeon bricks are breakable (but tough) in Galacticraft 3 and Galacticraft 4.   They were unbreakable in the old days, Minecraft 1.6.4 and Tekkit Lite and Voltz modpacks.

**Comment by R-Josef** [comment]
ok i know, but they might have some problem with place.

**Comment by TheQuadShot** [comment]
This must be sponge related since I can't repro this running the .142 builds (SSP). I was able to place them on the moon and on overworld.

**Comment by radfast** [comment]
I can't reproduce this running latest 144 builds, on a **Sponge server**.  spongeforge-1.10.2-2254-5.2.0-BETA-2272.jar

I tried regular pickaxe and Sticky Desh Pickaxe.  Both times the moon blocks mined correctly and were placeable.

**Comment by MJRLegends** [comment]
spongeforge 1.10.2-2477-5.2.0-BETA-2793 is the latest which means thats 500+ builds ahead of spongeforge-1.10.2-2254-5.2.0-BETA-2272

**Comment by radfast** [comment]
Please can somebody do me a favour and test with latest Sponge?  I don't have time today to set up a server on a different Forge version + a different Sponge version from the one I have already.

**Comment by MJRLegends** [comment]
I have a private server running latest sponge forge and galacticraft build 144 and i dont seem to get the issue either

**Comment by MJRLegends** [comment]
Could just be dimension spawn protection that spongeforge is adding and that is the cause of the issue

**Comment by radfast** [comment]
> I have a private server running latest sponge forge and galacticraft build 144 and i dont seem to get the issue either

Thank you :)

@R-Josef  see questions for you above ...

**Comment by R-Josef** [comment]
i'm sorry that after test we found it's LevelUp's error. 'LevelUp' add an nbt to block which make the block can't be place. thx for your patient and sorry to bother you.

**Comment by radfast** [comment]
no problem at all, thank you for confirming it is not our issue.

you're welcome to post anything else you find ...
