### ISSUE TITLE
Fluid Pipe don't work with some machine

### ISSUE THREAD

**Issue by R-Josef** [micdoodle8/Galacticraft#3209]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version:1.10.2
Galacticraft version: 1.10.2-4.0.1.138

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? SSP and SMP

Galacticraft add-ons and other mods installed?
Galacticraft-Planets and MicdoodleCore

Please provide screenshots / crash report / log as needed.
![default](https://user-images.githubusercontent.com/25573386/36778769-b606f24c-1ca8-11e8-8637-8a529965cf9a.png)
Fluid Pipe can't carry water from Fluid Tank to Water Electrolyzer. or carry the Methane Synthesizer's methane to Gas Liquefier. through its' lookings all has the entrance. i think this may be an error.

**Comment by QuantumStatement** [comment]
Try using a [Wrench](https://wiki.micdoodle8.com/wiki/Standard_Wrench) on [pipe](https://wiki.micdoodle8.com/wiki/Fluid_Pipe)

**Comment by radfast** [comment]
@ETStarLight do you know if there is a Chinese language version of our wiki page for https://wiki.micdoodle8.com/wiki/Fluid_Pipe?  I think you told me once there is a complete Chinese wiki for Galacticraft?

**Comment by R-Josef** [comment]
well, thank you

**Comment by ETStarLight** [comment]
@radfast   Well,there is a Chinese Wiki version,but it is for GalactiCraft3:[url]http://www.mcbbs.net/thread-506808-1-1.html[/url].
I don't have enough time to translate Wiki……In fact I have put off translation for The AetherII and MatterOverdrive again and again.So I won't translate any Wiki……at least in March.

**Comment by ETStarLight** [comment]
Well?!I have made a Chinese introduce page for GalactiCraft4 
 http://www.mcbbs.net/thread-727919-1-1.html,and I have translated  the Wiki for GC4.I don't know why he came here……

**Comment by R-Josef** [comment]
i'am sorry, i didn't read wiki before i asked, it's my fault.

**Comment by radfast** [comment]
@ETStarLight  it is possible for us to create a Chinese page to correspond to every page on the English-language wiki - like [this page](https://wiki.micdoodle8.com/wiki/%D0%9B%D1%83%D0%BD%D0%B0) in Russian.

The community could then - slowly - edit all the pages and translate to good Chinese language?

I will look to see whether it is possible to machine-translate all the pages initially - could be that will at least create a "template" which Chinese-speaking players can edit.

It's too much work for 1 person I agree!

How many players - approximately - do you think we have in China?

**Comment by ETStarLight** [comment]
@radfast  
It's impossible to get to know how many Chinese players we have……
NO MACHINE-TRANSLATION!All communities in China hate this!
I will update the little things I have translated……and it's time to make a Chinese Wiki page.
However——actually there is a community like FTBWiki in China called MCMOD.cn:http://www.mcmod.cn/class/194.html  This page is for GC.Many people work on it and I check all they made.It's NOT translation-----it's a players made wiki.
This issue is a special thing because most China players can't use English easily----most of them will close any English website

**Comment by ETStarLight** [comment]
I will work for official Wiki,and find some friends who translated other mods and play GalactiCraft.Don't worry about this.
I haven't edited any website like GalactiCraft before,so I need your help:-D

**Comment by radfast** [comment]
How do I write the name for Chinese language, in Chinese?   Is it 中文 ?

**Comment by radfast** [comment]
https://wiki.micdoodle8.com/wiki/Template:Otherlang

**Comment by radfast** [comment]
I made 1 change to help the situation posted by @R-Josef 

Now the Methane Synthesizer -> Gas Liquefier connection should work OK.
![methsynth](https://user-images.githubusercontent.com/6842258/37691111-5f757ad4-2ca7-11e8-810d-9e5a91fea2b7.png)
