### ISSUE TITLE
Mod compatibility w/JEI. Missing "Move Items" button on Magnetic Crafting Table

### ISSUE THREAD

**Issue by TheQuadShot** [micdoodle8/Galacticraft#3210]
Minecraft 1.10.2
Forge 12.18.2.2511

Galacticraft-Planets-1.10.2-4.0.1.142.jar
GalacticraftCore-1.10.2-4.0.1.142.jar
MicdoodleCore-1.10.2-4.0.1.142.jar

This is what I see on all other crafting tables (tinkers/vanilla)
https://imgur.com/a/g7QW8

**Comment by radfast** [comment]
thanks, this is a good idea.

**Comment by radfast** [comment]
implemented in 147
