### ISSUE TITLE
Crash With Actually Additions

### ISSUE THREAD

**Issue by kenijey** [micdoodle8/Galacticraft#3211]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 1.12.2-4.0.1.145

Galacticraft add-ons and other mods installed?
Actually Additions and Galacticraft (Core, MicDoodle, Planets)

[crash-2018-02-28_20.45.02-client.txt](https://github.com/micdoodle8/Galacticraft/files/1768212/crash-2018-02-28_20.45.02-client.txt)

**Comment by radfast** [comment]
Thanks @kenijey 

We added our use of Actually Additions API in this latest (build 145) version of Galacticraft.  I'll look at it and try to figure out why it is crashing.  Maybe something in 1.12.2 only.

**Comment by radfast** [comment]
Yes, looks like it is a problem in 1.12.2 only.  Fixed in our next build 146.

If you want to play today, please roll back your Galacticraft to build 144 - build 144 does not have this crash.

**Comment by radfast** [comment]
please try build 146, it will be good to have confirmation that's ok

**Comment by kenijey** [comment]
thank a lot for quick fix!
