### ISSUE TITLE
Landing on station

### ISSUE THREAD

**Issue by KrauzeBartek** [micdoodle8/Galacticraft#3212]
Minecraft version: 1.12.2
Galacticraft version:  144

Single player (SSP)

Galacticraft add-ons and other mods installed? YES

21:49:47 | net.minecraft.client.Minecraft | main | fatal | Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) 	at net.minecraft.util.Util.func_181617_a(SourceFile:47) 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086) 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) 	at net.minecraft.client.main.Main.main(SourceFile:123) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:483) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) Caused by: java.lang.NullPointerException 	at micdoodle8.mods.galacticraft.core.entities.player.GCEntityClientPlayerMP.func_70093_af(GCEntityClientPlayerMP.java:428) 	at micdoodle8.mods.galacticraft.core.entities.player.GCEntityClientPlayerMP.func_70047_e(GCEntityClientPlayerMP.java:463) 	at net.minecraft.entity.Entity.func_70055_a(Entity.java:1289) 	at org.blockartistry.lib.PlayerUtils.getPlayerBiome(PlayerUtils.java:67) 	at org.blockartistry.DynSurround.client.handlers.EnvironStateHandler$EnvironState.tick(EnvironStateHandler.java:164) 	at org.blockartistry.DynSurround.client.handlers.EnvironStateHandler$EnvironState.access$000(EnvironStateHandler.java:86) 	at org.blockartistry.DynSurround.client.handlers.EnvironStateHandler.onEntityJoin(EnvironStateHandler.java:416) 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_78_EnvironStateHandler_onEntityJoin_EntityJoinWorldEvent.invoke(.dynamic) 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) 	at net.minecraft.world.World.func_72838_d(World.java:1205) 	at net.minecraft.client.multiplayer.WorldClient.func_72838_d(WorldClient.java:259) 	at net.minecraft.client.Minecraft.func_71354_a(Minecraft.java:2568) 	at net.minecraft.client.network.NetHandlerPlayClient.func_147280_a(NetHandlerPlayClient.java:1060) 	at net.minecraft.network.play.server.SPacketRespawn.func_148833_a(SourceFile:31) 	at net.minecraft.network.play.server.SPacketRespawn.func_148833_a(SourceFile:12) 	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:20) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at net.minecraft.util.Util.func_181617_a(SourceFile:46) 	... 9 more
-- | -- | -- | -- | --
21:49:58 | net.minecraft.client.Minecraft | main | fatal | Unreported exception thrown! java.lang.NullPointerException 	at micdoodle8.mods.galacticraft.core.entities.player.GCEntityClientPlayerMP.func_70093_af(GCEntityClientPlayerMP.java:428) 	at micdoodle8.mods.galacticraft.core.entities.player.GCEntityClientPlayerMP.func_70047_e(GCEntityClientPlayerMP.java:463) 	at net.minecraft.client.audio.SoundManager.func_148615_a(SoundManager.java:523) 	at net.minecraft.client.audio.SoundHandler.func_147691_a(SoundHandler.java:268) 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1103) 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) 	at net.minecraft.client.main.Main.main(SourceFile:123) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:483) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by TheQuadShot** [comment]
Can you grab the .146 build and try again?

**Comment by radfast** [comment]
We can fix this in next build 147.  Please look for that later today.

**Comment by KrauzeBartek** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.147.jar)
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
FMLPlugin (elulib-0.1.12.jar)
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 3/1/18 7:58 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
at micdoodle8.mods.galacticraft.core.entities.player.GCEntityClientPlayerMP.func_70093_af(GCEntityClientPlayerMP.java:428)
at micdoodle8.mods.galacticraft.core.entities.player.GCEntityClientPlayerMP.func_70047_e(GCEntityClientPlayerMP.java:463)
at net.minecraft.client.audio.SoundManager.func_148615_a(SoundManager.java:523)
at net.minecraft.client.audio.SoundHandler.func_147691_a(SoundHandler.java:268)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1103)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
at net.minecraft.client.main.Main.main(SourceFile:123)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
-- Head --
Thread: Client thread
Stacktrace:
at micdoodle8.mods.galacticraft.core.entities.player.GCEntityClientPlayerMP.func_70093_af(GCEntityClientPlayerMP.java:428)
at micdoodle8.mods.galacticraft.core.entities.player.GCEntityClientPlayerMP.func_70047_e(GCEntityClientPlayerMP.java:463)
at net.minecraft.client.audio.SoundManager.func_148615_a(SoundManager.java:523)

-- Affected level --
Details:
Level name: MpServer
All players: 1 total; [GCEntityClientPlayerMP['Bartek'/13149, l='MpServer', x=8.50, y=65.00, z=8.50]]
Chunk stats: MultiplayerChunkCache: 0, 0
Level seed: 0
Level generator: ID 00 - default, ver 1. Features enabled: false
Level generator options:
Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Level time: 0 game time, 0 day time
Level dimension: 0
Level storage version: 0x00000 - Unknown?
Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
Forced entities: 0 total; []
Retry entities: 0 total; []
Server brand: fml,forge
Server type: Integrated singleplayer server
Stacktrace:
at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
at net.minecraft.client.main.Main.main(SourceFile:123)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
Minecraft Version: 1.12.2
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_25, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 1754447080 bytes (1673 MB) / 3841982464 bytes (3664 MB) up to 5726797824 bytes (5461 MB)
JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 10
FML: MCP 9.42 Powered by Forge 14.23.2.2623 Optifine OptiFine_1.12.2_HD_U_C9 59 mods loaded, 59 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

| State     | ID                  | Version                  | Source                                          | Signature                                |
|:--------- |:------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
| UCHIJAAAA | minecraft           | 1.12.2                   | minecraft.jar                                   | None                                     |
| UCHIJAAAA | mcp                 | 9.42                     | minecraft.jar                                   | None                                     |
| UCHIJAAAA | FML                 | 8.0.99.99                | forge-1.12.2-14.23.2.2623.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| UCHIJAAAA | forge               | 14.23.2.2623             | forge-1.12.2-14.23.2.2623.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| UCHIJAAAA | micdoodlecore       |                          | minecraft.jar                                   | None                                     |
| UCHIJAAAA | elucore             | 1.0                      | minecraft.jar                                   | None                                     |
| UCHIJAAAA | aether_legacy       | 1.12.2-v2.0              | aether_legacy-1.12.2-v2.0.jar                   | None                                     |
| UCHIJAAAA | blockcraftery       | 0.1.3                    | blockcraftery-0.1.3.jar                         | None                                     |
| UCHIJAAAA | codechickenlib      | 3.1.5.331                | CodeChickenLib-1.12.2-3.1.5.331-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
| UCHIJAAAA | chickenchunks       | 2.4.1.71                 | ChickenChunks-1.12.2-2.4.1.71-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
| UCHIJAAAA | ctm                 | MC1.12-0.2.3.12          | CTM-MC1.12-0.2.3.12.jar                         | None                                     |
| UCHIJAAAA | chisel              | MC1.12.2-0.2.0.31        | Chisel-MC1.12.2-0.2.0.31.jar                    | None                                     |
| UCHIJAAAA | redstoneflux        | 2.0.1                    | RedstoneFlux-1.12-2.0.1.2-universal.jar         | d4f1503fbacd9b9fb767720420c5395104239ec9 |
| UCHIJAAAA | cofhcore            | 4.3.10                   | CoFHCore-1.12.2-4.3.10.5-universal.jar          | None                                     |
| UCHIJAAAA | cofhworld           | 1.1.1                    | CoFHWorld-1.12.2-1.1.1.12-universal.jar         | None                                     |
| UCHIJAAAA | computercraft       | 1.80pr1                  | ComputerCraft1.80pr1.jar                        | None                                     |
| UCHIJAAAA | custommainmenu      | 2.0.8                    | CustomMainMenu-MC1.12.2-2.0.8.jar               | None                                     |
| UCHIJAAAA | durabilityshow      | 5.0.0                    | Durability+Show-1.12-5.0.0.jar                  | None                                     |
| UCHIJAAAA | mantle              | 1.12-1.3.1.21            | Mantle-1.12-1.3.1.21.jar                        | None                                     |
| UCHIJAAAA | jei                 | 4.8.5.147                | jei_1.12.2-4.8.5.147.jar                        | None                                     |
| UCHIJAAAA | tconstruct          | 1.12.2-2.9.1.65          | TConstruct-1.12.2-2.9.1.65.jar                  | None                                     |
| UCHIJAAAA | galacticraftcore    | 4.0.1.147                | GalacticraftCore-1.12.2-4.0.1.147.jar           | None                                     |
| UCHIJAAAA | dsurround           | 3.4.7.2                  | DynamicSurroundings-1.12.2-3.4.7.2.jar          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
| UCHIJAAAA | presets             | 3.4.7.2                  | DynamicSurroundings-1.12.2-3.4.7.2.jar          | None                                     |
| UCHIJAAAA | elementalcreepers   | $version                 | ElementalCreepers-v3.8.3-g68a0adb.jar           | None                                     |
| UCHIJAAAA | elevatorid          | 1.3.5                    | ElevatorMod-1.12.2-1.3.5.jar                    | None                                     |
| UCHIJAAAA | enderstorage        | 2.4.2.126                | EnderStorage-1.12.2-2.4.2.126-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
| UCHIJAAAA | erebus              | 1.0.21                   | Erebus-1.0.21.jar                               | None                                     |
| UCHIJAAAA | galacticraftplanets | 4.0.1.147                | Galacticraft-Planets-1.12.2-4.0.1.147.jar       | None                                     |
| UCHIJAAAA | mjrlegendslib       | 1.12.2-1.1.1             | MJRLegendsLib-1.12.2-1.1.1.jar                  | b02331787272ec3515ebe63ecdeea0d746653468 |
| UCHIJAAAA | extraplanets        | 1.12.2-0.2.6             | ExtraPlanets-1.12.2-0.2.6.jar                   | b02331787272ec3515ebe63ecdeea0d746653468 |
| UCHIJAAAA | zerocore            | 1.12-0.1.1.0             | zerocore-1.12-0.1.1.0.jar                       | None                                     |
| UCHIJAAAA | bigreactors         | 1.12.2-0.4.5.46          | ExtremeReactors-1.12.2-0.4.5.46.jar             | None                                     |
| UCHIJAAAA | cfm                 | 4.1.5                    | furniture-4.1.5-1.12.2.jar                      | None                                     |
| UCHIJAAAA | gravestone          | 1.10.1                   | gravestone-1.10.1.jar                           | None                                     |
| UCHIJAAAA | waila               | 1.8.23                   | Hwyla-1.8.23-B38_1.12.jar                       | None                                     |
| UCHIJAAAA | lunatriuscore       | 1.2.0.42                 | LunatriusCore-1.12.2-1.2.0.42-universal.jar     | None                                     |
| UCHIJAAAA | ingameinfoxml       | 2.8.2.94                 | InGameInfoXML-1.12.2-2.8.2.94-universal.jar     | None                                     |
| UCHIJAAAA | inventorytweaks     | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
| UCHIJAAAA | ironchest           | 1.12.2-7.0.40.824        | ironchest-1.12.2-7.0.40.824.jar                 | None                                     |
| UCHIJAAAA | journeymap          | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                     | None                                     |
| UCHIJAAAA | malisiscore         | 1.12.2-6.4.0             | malisiscore-1.12.2-6.4.0.jar                    | None                                     |
| UCHIJAAAA | malisisdoors        | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                   | None                                     |
| UCHIJAAAA | mekanism            | 1.12.2-9.4.3.330         | Mekanism-1.12.2-9.4.3.330.jar                   | None                                     |
| UCHIJAAAA | mekanismgenerators  | 9.4.3                    | MekanismGenerators-1.12.2-9.4.3.330.jar         | None                                     |
| UCHIJAAAA | mekanismtools       | 9.4.3                    | MekanismTools-1.12.2-9.4.3.330.jar              | None                                     |
| UCHIJAAAA | nei                 | 2.4.1                    | NotEnoughItems-1.12.2-2.4.1.233-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
| UCHIJAAAA | projecte            | 1.12-PE1.0.0             | ProjectE-1.12-PE1.2.0.jar                       | None                                     |
| UCHIJAAAA | redstonepaste       | 1.7.5                    | redstonepaste-mc1.12-1.7.5.jar                  | None                                     |
| UCHIJAAAA | refinedstorage      | 1.5.31                   | refinedstorage-1.5.31.jar                       | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
| UCHIJAAAA | resourceloader      | 1.5.3                    | ResourceLoader-MC1.12.1-1.5.3.jar               | d72e0dd57935b3e9476212aea0c0df352dd76291 |
| UCHIJAAAA | schematica          | 1.8.0.168                | Schematica-1.12.2-1.8.0.168-universal.jar       | None                                     |
| UCHIJAAAA | thermalfoundation   | 2.3.10                   | ThermalFoundation-1.12.2-2.3.10.6-universal.jar | None                                     |
| UCHIJAAAA | thermaldynamics     | 2.3.10                   | ThermalDynamics-1.12.2-2.3.10.4-universal.jar   | None                                     |
| UCHIJAAAA | thermalexpansion    | 5.3.10                   | ThermalExpansion-1.12.2-5.3.10.15-universal.jar | None                                     |
| UCHIJAAAA | treechopper         | 1.2.4                    | TreeChopper-1.12.2-1.2.4.jar                    | None                                     |
| UCHIJAAAA | twilightforest      | 3.6.345                  | twilightforest-1.12.2-3.6.345-universal.jar     | None                                     |
| UCHIJAAAA | wearablebackpacks   | 3.1.2                    | WearableBackpacks-1.12.2-3.1.2.jar              | None                                     |
| UCHIJAAAA | elulib              | 0.1.12                   | elulib-0.1.12.jar                               | None                                     |

Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
team.chisel.ctm.client.asm.CTMTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.147.jar)
micdoodle8.mods.miccore.MicdoodleTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)

Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
invtweaks.forge.asm.ContainerTransformer
FMLPlugin (elulib-0.1.12.jar)
elucent.elulib.asm.ASMTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
lumien.resourceloader.asm.ClassTransformer
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
net.fybertech.nwr.NWRTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2.jar)
org.blockartistry.DynSurround.asm.Transformer
GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4550' Renderer: 'Intel(R) HD Graphics 530'
Pulsar/tconstruct loaded Pulses:
- TinkerCommons (Enabled/Forced)
- TinkerWorld (Enabled/Not Forced)
- TinkerTools (Enabled/Not Forced)
- TinkerHarvestTools (Enabled/Forced)
- TinkerMeleeWeapons (Enabled/Forced)
- TinkerRangedWeapons (Enabled/Forced)
- TinkerModifiers (Enabled/Forced)
- TinkerSmeltery (Enabled/Not Forced)
- TinkerGadgets (Enabled/Not Forced)
- TinkerOredict (Enabled/Forced)
- TinkerIntegration (Enabled/Forced)
- TinkerFluids (Enabled/Forced)
- TinkerMaterials (Enabled/Forced)
- TinkerModelRegister (Enabled/Forced)
- chiselIntegration (Enabled/Not Forced)
- wailaIntegration (Enabled/Not Forced)

Launched Version: forge-14.23.2.2623
LWJGL: 2.9.4
OpenGL: Intel(R) HD Graphics 530 GL version 4.4.0 - Build 21.20.16.4550, Intel
GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

Using VBOs: No
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 8x Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
OptiFine Version: OptiFine_1.12.2_HD_U_C9
Render Distance Chunks: 8
Mipmaps: 0
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
Shaders: null
OpenGlVersion: 4.4.0 - Build 21.20.16.4550
OpenGlRenderer: Intel(R) HD Graphics 530
OpenGlVendor: Intel
CpuCount: 8

**Comment by radfast** [comment]
Thanks for your patience.  This will be fixed properly in 1.12.2 next version 148.

(Yestersday's fix covered it in 1.8.9, 1.10.2, 1.11.2 versions only - sorry about that!)

**Comment by radfast** [comment]
Build 148 is now available - enjoy :)

**Comment by KrauzeBartek** [comment]
Thanks !
