### ISSUE TITLE
[1.12 DEV] Json Recipe - Unrecognised condition data: quick_mode

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#3214]
https://pastebin.com/xSrGEfhE

**Comment by radfast** [comment]
It this a private build in your workspace - or is it the downloaded 1.12.2-dev?

I had this in my workspace, fixed it by deleting the `temporary` folder.  It's old assets which should not now be in GC 1.12 branch.

**Comment by SteveKunG** [comment]
Thank you, maybe it an old file in my worksp

**Comment by radfast** [comment]
https://github.com/micdoodle8/Galacticraft/commit/1c2badbd59541cc5b43f34c7b3f5c5773aff18ee#diff-1b0e00592580c9398d41ce27bd652baa

But I think Gradle caches assets - either in `temporary` folder or `build` folder.

When you build using our `build.gradle`, Gradle copies new assets from `src` folder into the cache, but it does **not** delete the old assets from the cache.  So if you build locally, it creates a `.jar` including these assets - which were supposed to be deleted.

On our Jenkins, the build script deletes the cache and temporary folder after each build.  This makes the build ~3 seconds longer, but it means no problems of this kind!
