### ISSUE TITLE
Issues with Evolved mobs' drops

### ISSUE THREAD

**Issue by QuantumStatement** [micdoodle8/Galacticraft#3216]
Minecraft version: 1.11.2
Galacticraft version: 4.0.1.147

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP

Galacticraft add-ons and other mods installed?
None

1. Evolved Creeper drop gunpowder instead of [redstone](https://wiki.micdoodle8.com/wiki/Evolved_Creeper#Data)
2. Evolved Creeper don't drop Blaze Rod if it is killed by a player while it is burning. I tested this in the sealed space and in the Overworld
3. I never see rare drops from evolved mobs (maybe this is not a bug because it's rare drops)
4. In Asteroids Adventure mode Evolved Zombies don't drop Copper ingot and Evolved Skeletons don't drop Lapis Lazuli

**Comment by radfast** [comment]
* The Copper Ingot drop from Evolved Zombie is **only** active in the Asteroids Adventure mode.
* For this drop you also need to check the Asteroids Adventure Mode flags - if the flags are 15 (or anything else with binary digit 2 set, like `0111` or `0010` in binary) then it is enabled.
* So, if you want this drop, but you don't want to start the game on Asteroids and you don't want the extra compressor recipes, set the flags to 2
* You can increase the chance for rare drops with a big Fortune enchantment - normal chance is 1 in 40 - with Looting IV the chance is 1 in 15.  _Maybe I should increase it?_

It looks like the Evolved Creeper is bugged though :(

**Comment by QuantumStatement** [comment]
* Drops from Evolved Creeper - OK
* Rare drops from Evolved mobs - OK
* Copper and Lapis Lazuli in Asteroids Challenge mode - OK

But instead standart drops (such as strings from Evolved Spiders or arrows from Evolved Skeletons) disappeared

**Comment by radfast** [comment]
Thanks for testing!   Standard drops will be restored in build 150.
