### ISSUE TITLE
Recipe for the new SEK (SpaceEmergencyKit) missing in JEI

### ISSUE THREAD

**Issue by TheQuadShot** [micdoodle8/Galacticraft#3220]
I got the recipe from the tweet via the WIKI, Not sure if they should stack currently it doesn't (dispenser idea you mentioned, not sure if they would need to be)

Minecraft 1.10.2
Forge 12.18.2.2511

Galacticraft-Planets-1.10.2-4.0.1.147.jar
GalacticraftCore-1.10.2-4.0.1.147.jar
MicdoodleCore-1.10.2-4.0.1.147.jar

**Comment by radfast** [comment]
I don't plan for it to stack, because the gear and tanks etc don't stack (and potions don't stack).

Not sure why the recipe is missing from JEI, I'll take a look.  Thanks for reporting!
