### ISSUE TITLE
Snow Layer and Torches on Solar Panels & others?

### ISSUE THREAD

**Issue by FrostQ** [micdoodle8/Galacticraft#3221]
Minecraft version: 1.12.2
Galacticraft version: 1.12.2-4.0.1.148

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Both

Galacticraft add-ons and other mods installed?
Yes

Screenshots:
![2018-03-03_10 50 38](https://user-images.githubusercontent.com/36822613/36933485-c4d7f022-1ed9-11e8-891b-66bf3e2fd103.png)
![2018-03-03_10 51 45](https://user-images.githubusercontent.com/36822613/36933486-cc27fa34-1ed9-11e8-9ddd-aa70be06553c.png)
![2018-03-03_11 39 41](https://user-images.githubusercontent.com/36822613/36933487-d1b3e864-1ed9-11e8-98a8-2c7492967ecf.png)
![2018-03-03_11 44 07](https://user-images.githubusercontent.com/36822613/36933492-dff47916-1ed9-11e8-8837-fad88b52c9a7.png)
![2018-03-03_12 07 42](https://user-images.githubusercontent.com/36822613/36933593-1bb7c488-1edc-11e8-9e39-e99173bcc239.png)
![2018-03-03_12 08 26](https://user-images.githubusercontent.com/36822613/36933594-20447438-1edc-11e8-8514-be0b8b3dce53.png)
![2018-03-03_12 10 51](https://user-images.githubusercontent.com/36822613/36933598-2c2ef476-1edc-11e8-9c39-1fba120cea99.png)
![2018-03-03_12 14 28](https://user-images.githubusercontent.com/36822613/36933626-99292b1e-1edc-11e8-9301-f78ebd66917c.png)
![2018-03-03_12 15 20](https://user-images.githubusercontent.com/36822613/36933627-9c75ff18-1edc-11e8-9438-c352c6d45fb9.png)

**Comment by radfast** [comment]
Thank you!

Seems like **some time** it could be fun to have a customised snow layer for Solar Panels (and they should not work with Snow on top!)

But the rest are definitely bugs - not sure how it can happen as these are certainly not solid blocks!

**Comment by radfast** [comment]
Thanks, should be good in build 150.
