### ISSUE TITLE
Glowing footprints

### ISSUE THREAD

**Issue by FrostQ** [micdoodle8/Galacticraft#3224]
Minecraft version: 1.12.2
Galacticraft version:

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Both

Galacticraft add-ons and other mods installed?
Yes (even without other mods)
![2018-03-04_14 13 41](https://user-images.githubusercontent.com/36822613/36946011-8882673c-1fb6-11e8-8590-7aec9d50d3a8.png)
Screenshots:
![2018-03-04_10 17 59](https://user-images.githubusercontent.com/36822613/36946007-7c2b3310-1fb6-11e8-9b50-6802c28e5f97.png)

**Comment by radfast** [comment]
thanks, nice image - I actually kind of like it, might not change

**Comment by MJRLegends** [comment]
Yeah it kinda is a cool unintended feature

**Comment by EzerArch** [comment]
> thanks, nice image - I actually kind of like it, might not change

There! I'd fix it, but also make it a feature for the [Sensor Glasses](https://wiki.micdoodle8.com/wiki/Sensor_Glasses).

**Comment by darthvader45** [comment]
Or just make em brighter with the Sensor Glasses on.  Still handy.

**Comment by micdoodle8** [comment]
Sensor glasses now make footprints brighter.

Removed the glow without glasses equipped.

**Comment by radfast** [comment]
Build 169 is now available to download.
