### ISSUE TITLE
Problems with work geothermal generator

### ISSUE THREAD

**Issue by Romsik788** [micdoodle8/Galacticraft#3228]
Minecraft version:1.12.2
Galacticraft version:4.0.1.150

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP, SSP not open to LAN
Galacticraft add-ons and other mods installed?
Ecology mod, JEI, voxelMap, scenter
Please provide screenshots / crash report / log as needed.
![2018-03-05_18 43 48](https://user-images.githubusercontent.com/33905242/36987785-dfb3c632-20a5-11e8-8141-34f569a02910.png)
The geothermal generator does not work for the installation of the geyser block (on the screen on the right). But on the generated geyser, on Venus, works (on the left on the screen).

**Comment by radfast** [comment]
BTW we have config settings to change the position of the oxygen display so that it does not over-write Voxel Map.

**Comment by Romsik788** [comment]
Interestingly came up. About the configuration I knew, I just forgot to change

**Comment by radfast** [comment]
I've marked it as Wiki problem to remind me to update the Wiki to explain this better.

Please can we use your screenshot on the Wiki?

**Comment by Romsik788** [comment]
Yes, use

**Comment by Saturn684** [comment]
you have to put a bucket of sulfuric acid under the vapor spout.
