### ISSUE TITLE
On Mars too bright night

### ISSUE THREAD

**Issue by Romsik788** [micdoodle8/Galacticraft#3231]
Minecraft version:1.12.2
Galacticraft version:4.0.1.150

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP, SSP not open to LAN
Galacticraft add-ons and other mods installed?
VoxelMap, scenter, JEI, ecology mod
Please provide screenshots / crash report / log as needed.
![2018-03-06_18 30 33](https://user-images.githubusercontent.com/33905242/37044960-8095ffa8-216d-11e8-9ce0-52b2305e260e.png)

Mars is too bright for the night. Please reduce the brightness of light at night on Mars.

**Comment by radfast** [comment]
This is intended by micdoodle8 - he chose the Mars night brightness and the look of the sky, and he and I both think it looks great.

It's not really too different from the Overworld.
