### ISSUE TITLE
Aluminum Wire Recipe

### ISSUE THREAD

**Issue by dr3amnightmare** [micdoodle8/Galacticraft#3234]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 4.0.1.148

Multiplayer (SMP)

Mod List:
Actually Additions
Aroma1997 Core
Aroma1997 Dimensional World
Bad Wither No Cookie - Reloaded
Blood Magic
Chisel
CoFH Core
CoFH World
ConnectedTexturesMod
ET Lunar
EnderIO
Enviromental Tech
Extra Utilities
ExtremeReactors
FTB Utilities
FTBLib
Flux Networks
Galacticraft
GraveStoneMod
In-Game Wiki Mod
Inventory Tweaks
Iron Backpacks
JourneyMap
Just Enough Resources (JER)
Light Level Overlay Reloaded
McMultiPart
Mob Grinding Utils
Mod Name Tooltip
Morpheus
NEI
NetherPortalFix
OMLib
OpenBlocks Elevators
OpenComputers
OpenGlasses
OpenModularTurrets
Quick Leaf Decay
RFTools
RFTools Control
Redstone Arsenal
Redstone Flux
Refined Storage
Reliquary
Simply Jetpacks?
Snad
Steves Carts Reborn
Storage Drawers
Storage Drawers Extras
The Camping Mod
The One Probe
Thermal Cultivation
Thermal Dynamics
Thermal Expansion
Thermal Foundation
Tinkers Construct
Tinkers Tools Leveling
TorchMaster
WOOT
YABBA

plus required dependencies

Aluminum Wire recipe does not accept all types of wool. Only white wool is accepted.

**Comment by TheQuadShot** [comment]
It's always been that way. There are color requirements for the Oxygen Tanks as well. Also if you could use other colors then they would show in JEI/NEI and they don't. So this would be a Request for Change and should go on the forums suggestions page here: https://forum.micdoodle8.com/index.php?forums/suggestions.7/

**Comment by QuantumStatement** [comment]
> It's always been that way

![2018-03-08_19 22 06](https://user-images.githubusercontent.com/35406698/37162446-4f8dd666-2306-11e8-9d55-07d4721f9908.png)

Galacticraft 4.0.1.150

**Comment by MJRLegends** [comment]
Yeah its set to white wool only from 1.7 to 1.12 @QuantumStatement yours is probably a mod/mod pack change being made

**Comment by dr3amnightmare** [comment]
Strange. I could have sworn it used to be all types of wool. I guess it has been a while. My bad. Hey @QuantumStatement , what mod does the change for you?

**Comment by QuantumStatement** [comment]
In Minecraft 1.11.2 you may use any color of wool even if only Galacticraft installed. In Minecraft 1.12.2 only white wool works

**Comment by radfast** [comment]
Thanks for reporting guys.  The intended recipe should accept any color of wool, so this is a bug in 1.12.2.

Minecraft's whole recipe system changed (internally) in 1.12.2 so there could be other bugs like this too - please report any you find.

(It does also mean that a resource pack can change recipes from 1.12.2 so players can change recipes for themselves if they really want to, without needing to use a mod like ModTweaker.)

**Comment by QuantumStatement** [comment]
> resource pack can change recipes from 1.12.2

Really? I thought this feature was delayed until Minecraft 1.13

**Comment by radfast** [comment]
I'm not sure - certainly from 1.12.2 our recipes are in principle replaceable assets, same way as textures.

**Comment by radfast** [comment]
Fixed next build, thanks for reporting @dr3amnightmare 

Also fixed Tier 2 Thermal Cloth which uses Wool.  I can't find anything else which is obviously wrong like this.
