### ISSUE TITLE
[1.12.2 only] "Whitelist CoFHCore World Gen" option don't work

### ISSUE THREAD

**Issue by QuantumStatement** [micdoodle8/Galacticraft#3236]
Minecraft version: 1.12.2
Galacticraft version: 4.0.1.150

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP

Galacticraft add-ons and other mods installed?
CoFH World 1.1.1.12

"Whitelist CoFHCore World Gen" option don't work in Minecraft 1.12.2. Possible reason - CoFHCore world generation was separate into different mod named [CoFH World](https://minecraft.curseforge.com/projects/cofh-world)

**Comment by radfast** [comment]
>  Possible reason - CoFHCore world generation was separate into different mod named CoFH World

Yes almost certainly that's the reason - thanks for reporting, I'll take a look.

**Comment by radfast** [comment]
Fixed next build.

**Comment by QuantumStatement** [comment]
It's working

**Comment by radfast** [comment]
thanks for confirming :)
