### ISSUE TITLE
[CoFH World/CoFH Core] "Enable Flat Bedrock" option generate dirt in Galacticraft dimensions

### ISSUE THREAD

**Issue by QuantumStatement** [micdoodle8/Galacticraft#3237]
Minecraft version: 1.12.2
Galacticraft version: 4.0.1.150

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP

Galacticraft add-ons and other mods installed?
CoFH World 1.1.1.12

Please provide screenshots / crash report / log as needed.
![2018-03-09_14 11 33](https://user-images.githubusercontent.com/35406698/37205633-8221c484-23a6-11e8-9497-1fc1debc059b.png)

CoFH developers [says](https://github.com/CoFH/Feedback/issues/970#issuecomment-371906833) that this problem lay on your side

**Comment by radfast** [comment]
Should be fixed next build.  I'm not sure how you generated that image if the CoFH Worldgen whitelisting option wasn't working?!

**Comment by QuantumStatement** [comment]
>how you generated that image if the CoFH Worldgen whitelisting option wasn't working?!

"Generate all other mods features on planets" option still work

**Comment by QuantumStatement** [comment]
Galacticraft 4.0.1.151
CoFH Core/World still generate dirt on Moon and Mars. On Venus it generate Venus Soft Rock
![2018-03-11_19 44 22](https://user-images.githubusercontent.com/35406698/37255973-71604ea2-2565-11e8-940c-e170aa639b74.png)
