### ISSUE TITLE
You discovered Earth

### ISSUE THREAD

**Issue by MarioSMB** [micdoodle8/Galacticraft#3240]
It's a somewhat amusing message to see on first start of a map, but it's a bit redundant and adds to the "mod spam" in chat.

**Comment by MarioSMB** [comment]
Just realised this is from an addon of Galacticraft, will open the issue there.

**Comment by TheQuadShot** [comment]
@MarioSMB lol, Today is Mar10 day! ;-)

**Comment by radfast** [comment]
anniversary of the discovery of the rings of Uranus
