### ISSUE TITLE
why galacticraft dont support buildcraft like in mc 1.6.4

### ISSUE THREAD

**Issue by xpatryk89** [micdoodle8/Galacticraft#3247]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version:1.11.2
Galacticraft version:4.0.0.177

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?

Galacticraft add-ons and other mods installed?

Please provide screenshots / crash report / log as needed.
In older minecraft versions eg 1.6.4 galacticraft supported buildcraft items, eg pipes, engines buildcraft fuel worked with galacticraft galacticraft fuel worked with buildcraft, buildcraft power from engines worked with galacticraft items eg electric furnance, with oxygen generator, i was able to use galacticraft power pipe with buildcraft and buildcraft piupe with buildcrqaft. please give me back it

**Comment by MJRLegends** [comment]
@xpatryk89 i believe support needs to be added/tweaked for it to work see #3246

**Comment by radfast** [comment]
lol two in one day?  did somebody release a Buildcraft + Galacticraft modpack?

**Comment by MJRLegends** [comment]
Possibly yeah

**Comment by QuantumStatement** [comment]
@xpatryk89 as temporary solution you may use [Energy Converters](https://minecraft.curseforge.com/projects/energy-converters) mod

**Comment by radfast** [comment]
Full Galacticraft / Buildcraft compatibility in our next build 159, should be available for download about 10 minutes from now.
