### ISSUE TITLE
Copyright issues

### ISSUE THREAD

**Issue by ccicnce113424** [micdoodle8/Galacticraft#3255]
Hello, can I forward your software on a third party Chinese website (www.mcmod.cn)? (translation from machine)

**Comment by radfast** [comment]
Hello!

Some concerns before you do this:

1.  It's possible @ETStarLight is **already** doing this on mcmod.cn - see discussion [here](https://github.com/micdoodle8/Galacticraft/pull/2870) - so I want his comments first.

2.  Can you do human translation - please?   It's **much better** for Chinese players.

3.  For mod download it's best to link to our [downloads site ](https://micdoodle8.com/mods/galacticraft/downloads) - this is the only way to have the **latest version** including the newest Chinese language translations.  You can see the translation is [updated frequently](https://github.com/micdoodle8/Galacticraft/commits/master/src/main/resources/assets/galacticraftcore/lang/zh_CN.lang)

4.  In 2015, another person made a Galacticraft forum thread in the Chinese language http://www.mcbbs.net/thread-435616-1-1.html - this shows the problems with doing this, I think it now needs some updating, looks like it is 1.7.10 only.  😭

**Comment by radfast** [comment]
I have closed this because it's not a "bug" or an "issue" in the mod that needs fixing.  You can still comment and discuss here :)

**Comment by ccicnce113424** [comment]
I don't mean that the program is Machine Translation. I mean that I publish the text by Machine Translation.

**Comment by ccicnce113424** [comment]
Mcmod.cn means that it has not been granted the permission of the author, and does not provide illegal downloads.

**Comment by radfast** [comment]
Yes, when you publish the text on mcmod.cn then it's like an advertisement / publicity for Galacticraft.

Our mod is high quality and so we want the advertisement / publicity to be **high quality**.

Therefore, the page on mcmod.cn needs text made by human translation.  Machine translation is not high quality...

**Comment by radfast** [comment]
We must wait for @ETStarLight comments.  He is our main contributor from China ... :)

**Comment by ETStarLight** [comment]
My Chinese ID in MCMOD is 星落辰，the editor for GalactiCraft page.
We don't and won't use any machine translation……
And I won't agree any republish of GalactiCraft in China!The official website is still work well,if possible I could provide a Chinese-translated website for the players,BUT 
(@radfast Please Pardon me use Chinese in discussing,and don't care about the issue any more.I will solve it with our leader of MCMOD, 重生是希望.)
您老人家光想着自己方便，人家自己的官网不要流量是咋的？这官网一没墙二没坏，学点英语有啥不好？要是真的发布我早八辈子上传了，你这是想干啥？

**Comment by ETStarLight** [comment]
别在这里打扰作者，有问题上官方群找人要我QQ，咱们面谈。

**Comment by radfast** [comment]
@ETStarLight   thank you, you are our star in China  :) 👍

**Comment by ETStarLight** [comment]
@radfast I have just back home from school⊙ω⊙
He meant that his sentences were written by Chinese and used Manchine to translate them to English.@ω@

**Comment by radfast** [comment]
>  He meant that his sentences were written by Chinese and used Manchine to translate them to English.@ω@

oh!   OK ... it was a machine translation problem, I didn't understand him!

**Comment by ETStarLight** [comment]
And is it possible for us to make a Chinese 
(download) page in our official website?I must think about children under 12 years old.

**Comment by radfast** [comment]
>  And is it possible for us to make a Chinese (download) page in our official website?

Yes, please do that if you want to.

You might need some scripting to have the latest builds automatically?  Our official (English) download page has scripts which pick up the builds and "promoted" builds.  It's best to talk to @micdoodle8 about this.

**Comment by ETStarLight** [comment]
Yeah I don't know much about website making^ω^
Download to 下载,Maybe Change this is enough@ω@
And version to 版本
