### ISSUE TITLE
Wooden Kinnesis Pipe?

### ISSUE THREAD

**Issue by FrostQ** [micdoodle8/Galacticraft#3258]
Minecraft version: 1.12.2
Galacticraft version: 4.0.1.160

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Both

Galacticraft add-ons and other mods installed?
- **buildcraft-7.99.15**
- and others

Please provide screenshots / crash report / log as needed.
![2018-03-18_20 25 15](https://user-images.githubusercontent.com/36822613/37570122-dee80286-2aeb-11e8-8b30-bd424c07c588.png)
but it still take energy from this solar panel

**Comment by radfast** [comment]
What's actually happening here is the **Solar Panel** is injecting energy into the BC wooden pipe.

You could also have a Gold Kinesis Pipe there, and it would still inject energy.

This is intended behaviour, and I think it's good for now.

Any further changes - including the graphical connection of the pipe to the Galacticraft solar panel - must wait until after Buildcraft is no longer in alpha.  I've been in contact with the Buildcraft devs and they have [told me](https://github.com/BuildCraft/BuildCraft/issues/4089#issuecomment-374023144) that Buildcraft API will be changing.

It's not worth my time to make it "perfect" now when it will be changing in future.

**Comment by radfast** [comment]
Sorry one more question: is there an intended way to use the API for a block which can connect **only** to a Wooden Kinesis Pipe, not to a Stone/Gold Kinesis Pipe?

If I return `IMjConnector.canConnect() == true` then every pipe connects.  But there's no way through the API to know which _type_ of pipe neighbour is asking the "canConnect()" question.

**Comment by radfast** [comment]
Build 161 is now available.
