### ISSUE TITLE
Slimeling eggs can't be picked up.

### ISSUE THREAD

**Issue by SpaceMinere** [micdoodle8/Galacticraft#3263]
Minecraft version: 1.10.2
Galacticraft version: 163

Single player (SSP)

No addons

When you break a slimeling egg, it hatches instead of dropping.

**Comment by radfast** [comment]
Fixed in next build 164.  Thank you for reporting!  (This bug probably also made it impossible to obtain the **Sticky Desh Pickaxe** item in versions 1.10.2 and later ... now fixed.)

**Comment by radfast** [comment]
Build 4.0.1.164 now available.
