### ISSUE TITLE
[1.12.2] Fuel Loader Dosen't Load Fuel.

### ISSUE THREAD

**Issue by tyabus** [micdoodle8/Galacticraft#3268]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 1.12.2-4.0.1.164

Multiplayer.

Galacticraft add-ons and other mods installed?
addon: Galacticraft-Planets 1.12.2-4.0.1.164
other mods:
Applied Energistics 2
BrandonsCore
CodeChickenLib
CoFHWorld
CoFHCore
Crafting Nether Star
Draconic Evolution
Extreme Reactors
mccray furniture
Redstone Flux
Thermal Foundation
Thermal Dynamics
Thermal Expansion
Toro Health
Twilight Forest
zerocore
logs:
dosen't need i guess.
screenshoots:
![image](https://user-images.githubusercontent.com/19637128/37822392-7f8a4222-2eb0-11e8-8953-e20fde4519cb.png)
![image](https://user-images.githubusercontent.com/19637128/37822411-8bdd3138-2eb0-11e8-99e0-8a14d4bdff07.png)
![image](https://user-images.githubusercontent.com/19637128/37822426-939ac8d6-2eb0-11e8-8bc5-bf7695d93a26.png)
![image](https://user-images.githubusercontent.com/19637128/37822465-b38b7aa0-2eb0-11e8-822c-86a8249f7e3a.png)

**Comment by TheQuadShot** [comment]
minecraft 1.12.2
forge 114.23.2.2619
Galacticraft-Planets-1.12.2-4.0.1.164
GalacticraftCore-1.12.2-4.0.1.164
MicdoodleCore-1.12.2-4.0.1.164

I can't reproduce this, nor can I tell what your screenshots are suppose to be telling _us_, Did you put fuel into the loader? Did you use a battery to power the unit (I don't see any power cables)? Can you show a screenshot of fuel and power in the loader, then show the fuel level in the rocket (enter the rocket and hit the "g" key).

**Comment by tyabus** [comment]
Sorry, my dumbness, but that "pipe" dosen't appear. It removed, or something. ( i played galacticraft on 3.X.X versions)

**Comment by TheQuadShot** [comment]
Oh, no, there are no pipe unless you are feeding the loader from a tank or from the refinery, and powering it up via cluster or solar panel , you can just use canisters of fuel and batteries(see attached imgs) to power up the loader (that's what I do when I get to a planet/moon/space station). There's lots of information on the wiki and you can ask for help in the forums here:
https://wiki.micdoodle8.com/wiki/Galacticraft

https://imgur.com/a/kdJ8q
https://imgur.com/a/EoB8M

**Comment by tyabus** [comment]
Thanks, closing issue.
