### ISSUE TITLE
Battery problems

### ISSUE THREAD

**Issue by Srsam2401** [micdoodle8/Galacticraft#3269]
Minecraft version: 11.2
Galacticraft version: 4.0.1.162

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP
Galacticraft add-ons and other mods installed? None

Please provide screenshots / crash report / log as needed.

I have just created another new world in 11.2 with the newest galacticraft version and there are two problems. For empty batteries, you can stack them, but if you put the stack into an advanced solar panel, it charges all four at the same time using the same amount of power it takes to charge one battery. And also, if I put a battery into my circuit fabricator, it can fully charge it on a 5gj charge. Could you fix this in an update for galacticraft?

**Comment by radfast** [comment]
Thanks for reporting the solar panel / stacked batteries charging issue.  We can fix that!

The circuit fabricator charging (and other machines) is already fixed, you will see this in next pending update 165.
