### ISSUE TITLE
Broken texture for 3 Mars machines when obtained by middle-clicking in creative

### ISSUE THREAD

**Issue by kouwei32** [micdoodle8/Galacticraft#3274]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version:4.0.1.163

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SMP on localhost Forge server.

Galacticraft add-ons and other mods installed?
BuildCraft,MrCrayfishFurniture,Optifine,EnderStorage,CodeChickenCore,ChickenChunks,JourneyMap,NEI,JEI

The textures in the inventory for the Water Electrolyzer, the Methane Synthesizer, and the Gas Liquefier are all full purple in the inventory (no texture) and the size is massive when dropped or held. The texture is normal when placed down and functions normally. No error messages present in log. While in the inventory, the machines lack a description when shift is pressed. Placing down the machine and then middle-clicking the machine again will (sometimes) repair the texture for the particular machine item.

P.S. This glitch was later unable to be reproduced in other machines, and so I will upload my world so you guys can check it out.

P.P.S. It might be caused by data values, because the value for the normal water electrolyzer is 8, while the broken one is 11. (`#4354/11` vs. `#4354/8`)

[World + Mods](https://1drv.ms/f/s!AuYOz32hHeG6jSk2rYkM2SNSBw7f)

(In the world, there is a fuel production system just outside the "ISS" space station. Middle-click the machines to see results.)

Please provide screenshots / crash report / log as needed.

![2018-03-24_19 34 29](https://user-images.githubusercontent.com/29967594/37871112-e4d016ee-2f9a-11e8-9139-31746cb14220.png)

(and no, the hydrogen is NOT turning into oxygen in the screenshot. Another pipe is in the background.)

**Comment by radfast** [comment]
Thank you, this is fixed in next buid 167.

For now, the purple textured item, you can place it and it should be the machine you want when placed.
