### ISSUE TITLE
Evolved Skeleton not holding bow correctly while attacking

### ISSUE THREAD

**Issue by FrostQ** [micdoodle8/Galacticraft#3275]
Minecraft version: 1.12.2
Galacticraft version: 4.0.1.166

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Both

Galacticraft add-ons and other mods installed?
Yes

Please provide screenshots / crash report / log as needed.
![2018-03-25_14 32 11](https://user-images.githubusercontent.com/36822613/37875046-1085c3a2-303a-11e8-8e03-42db7491d1f6.png)

**Comment by micdoodle8** [comment]
Thanks!

**Comment by radfast** [comment]
Build 169 is now available to download.
