### ISSUE TITLE
Fog on GC dimensions

### ISSUE THREAD

**Issue by FrostQ** [micdoodle8/Galacticraft#3276]
Minecraft version: 1.12.2
Galacticraft version: 4.0.1.166

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Both

Galacticraft add-ons and other mods installed?
- **Optifine** (with and without)
- and others (even without)

Please provide screenshots / crash report / log as needed.
Fog on GC dimensions appear only at Y is below 128 (or 255 if you have optifine)

Without optifine:
- Y <128
![2018-03-27_13 04 39](https://user-images.githubusercontent.com/36822613/37963870-e251f7e4-31bf-11e8-907a-e4c16a97d0b0.png)
- Y => 128
![2018-03-27_13 04 41](https://user-images.githubusercontent.com/36822613/37963879-e5810c20-31bf-11e8-9485-fbf628083dba.png)

With optifine
- Y < 255
![2018-03-25_14 40 04](https://user-images.githubusercontent.com/36822613/37875081-ae1d9c5c-303a-11e8-88d5-9a9b4455deb8.png)
- Y => 255
![2018-03-25_14 40 06](https://user-images.githubusercontent.com/36822613/37875082-b174b688-303a-11e8-92bd-b9fcc6f6cd15.png)

**Comment by micdoodle8** [comment]
Thanks, should be fixed in the next build. Not able to test with optifine in my development environment but I believe the fix should apply regardless.

**Comment by radfast** [comment]
Build 169 is now available to download.
