### ISSUE TITLE
Evolved Skeleton Boss's sounds

### ISSUE THREAD

**Issue by FrostQ** [micdoodle8/Galacticraft#3277]
Minecraft version: 1.12.2 (probably 1.8+)
Galacticraft version: 4.0.1.166

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Both

Galacticraft add-ons and other mods installed?
Yes

Please provide screenshots / crash report / log as needed.
None

Info:
Why his laught have pitch 1.1? On 1.7.10 had 0.5 .
"/playsound galacticraftcore:entity.bosslaugh hostile @a ~ ~ ~ 10 0.5 1"
His death sound pitch have highter too
Hurt sound is other than "1.7.10".
And why hold two bows?

**Comment by SteveKunG** [comment]
In 1.7 its hold two bows and (previously?) it shoot two arrows I think.

**Comment by radfast** [comment]
Fixed, thank you @SteveKunG.  Build 169 is now available to download.
