### ISSUE TITLE
[1.10.2] Slimeling eggs unobtainable in survival

### ISSUE THREAD

**Issue by SpaceMinere** [micdoodle8/Galacticraft#3278]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.10.2
Galacticraft version: 1.6.3

Single player (SSP)

Galacticraft add-ons and other mods installed?

Please provide screenshots / crash report / log as needed.

When breaking a slimeling egg with a tool such as a heavy duty pickaxe, it hatches instead of dropping itself like normal.

**Comment by radfast** [comment]
hey, thanks for reporting.  This issue is already fixed in a later build, please try 166.
