### ISSUE TITLE
Weird texture at the tip of Tier 3 Rocket

### ISSUE THREAD

**Issue by kouwei32** [micdoodle8/Galacticraft#3281]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 4.0.1.163

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Reproducible in all environments.

Galacticraft add-ons and other mods installed?
Unrelated to this issue.

Please provide screenshots / crash report / log as needed.

![2018-03-25_11 38 49](https://user-images.githubusercontent.com/29967594/37878661-4d44ba3c-3021-11e8-84dd-9181568d84ff.png)

**Comment by Romsik788** [comment]
I could fix it. I just can not find the texture of the rocket

**Comment by Romsik788** [comment]
I tried to paint the tip yellow, but only after that some parts of the rocket became yellow.

**Comment by micdoodle8** [comment]
Thanks for the report! The tip of the nose cone will no flash red/green as intended. Also, the grey part of the nose cone will match the 'team colour' - I'm not sure when this broke.

**Comment by Romsik788** [comment]
@micdoodle8 I hope you fix it.

**Comment by radfast** [comment]
Build 169 is now available to download.
