### ISSUE TITLE
Venus ore generation configs

### ISSUE THREAD

**Issue by eloquentJane** [micdoodle8/Galacticraft#3284]
Is it possible at some point to add config settings for the Venus ore generation? I am making a modpack and doing entirely custom ore generation, but if I can't disable Galacticraft ores on Venus that is likely to break things.

**Comment by TheQuadShot** [comment]
Gc ore's can be disabled in the /configs/planets.conf

**Comment by radfast** [comment]
hmm we don't have a disable for Venus.

> I am making a modpack and doing entirely custom ore generation, but if I can't disable Galacticraft ores on Venus that is likely to break things.

Please explain more?  Which ores do you plan to generate on Venus?  Which ores do you want to disable?

**Comment by eloquentJane** [comment]
I want to disable every default ore (from every mod I am using, including Galacticraft). I'm replacing them with ores generated using ContentTweaker and spawned in-world with COFH World. The ContentTweaker creation of ores and the COFH World worldgen are not difficult (and there's a config option to allow COFH World to generate ores in Galacticraft dimensions, so that is fine too), but there _will_ be issues if I can't disable the default ores of any mod because I am planning to do some major rebalancing of the entire game. I can remove recipes involving the default ores, but then players would accumulate useless ore blocks from mining on Venus, which would not be ideal as they would only serve to waste inventory space.

**Comment by radfast** [comment]
>   then players would accumulate useless ore blocks from mining on Venus

Lol, have you **been** to Venus?  It will take players probably 20 hours of game time at least before they can have a viable mining base on Venus.  So I don't think many players are actually going to be doing this.

I meant please can you list out here which actual ore blocks you want to disable.  For example, do you really want to disable our Silicon Ore?  Silicon is an essential ingredient in Galacticraft and players may not have another way to get it, unless you have another mod with silicon.

More generally, are you thinking about ore block **colors**?  Any ore blocks which are not our own Venus ores are going to look very strange in this worldgen.  If you're good enough with textures to overcome that problem, it would be nice for the community if you give your help to Galacticraft itself ...

**Comment by eloquentJane** [comment]
I am changing all relevant recipes with CraftTweaker; don't worry, I won't allow game-breaking issues like being unable to obtain key resources. Silicon will not be obtained from abstract "silicon ore", it'll be obtained by processing various realistic silicate minerals. And I am very familiar of how the mod is played by default (I've spent a long time testing every mod I plan on using, and I've also played with Galacticraft quite a bit over several game versions); that is why I feel confident with the ways I plan to rebalance it.

As for mining on Venus, yes, it will be a late-game thing, but it will be necessary to obtain various resources. I plan on making certain high-tier resources exclusively obtainable from custom ore blocks that I will spawn using custom worldgen files on Venus (certain rare-earth minerals, for example), and other resources (things like tungsten and zirconium, probably) more easily accessible from Venus than previous sources. I want to make mining in all new dimensions a requirement for progressing. The custom ores will be generated using ContentTweaker; and yes I have considered block appearances; although I am not exceptionally skilled at making textures, ContentTweaker allows me to set a block to use as the base texture for an ore, and then overlays the ore pixels onto the texture much like many mods' ores (or vanilla ores, for that matter) do to stone or netherrack.

Essentially, the reason I want to disable all Galacticraft ores is because I am creating new (and more complex in many cases) ways of progressing through all of the mods I am using for the modpack, for the purpose of extending gameplay, encouraging more complex automation, and adding interesting mod interactions. One of the things I am complicating is ore processing; I am largely going to be using realistic ores, so things like "copper ore" or "lead ore" like many mods add are not things I want to generate in the world at all. I can remove the recipes for refining Galacticraft's Venus ores, but that would (like I said previously) simply result in players accumulating large amounts of entirely-useless ore blocks while mining on Venus for whichever custom ores will be set to spawn _exclusively_ on Venus. And if I don't disable the recipes for refining Galacticraft ores, being unable to prevent the worldgen of those ores would majorly unbalance everything because processing them is just too simple (I want to remove the ability to simply smelt any ore directly to an ingot or two in a furnace or arc furnace). So the problem with being unable to disable the worldgen either results in unbalancing one of the main things I want to rebalance for my modpack, or results in inventory clutter while players try to mine _useful_ resources from Venus.

The specific blocks I want to disable are:
• Aluminum Ore
• Copper Ore
• Galena Ore
• Quartz Ore
• Silicon Ore
• Tin Ore
All the Venus versions of the above blocks. The rest of Galacticraft's ores can all currently have their worldgen disabled in the config file, but none of the Venus ones have such config settings at present.

**Comment by radfast** [comment]
OK, makes sense now.  We can do that for you next version.  Will probably be Thursday or Friday.

**Comment by eloquentJane** [comment]
Thanks, it's greatly appreciated.

**Comment by radfast** [comment]
This is included in next build 167.
