### ISSUE TITLE
Nether quartz ore in Arc Furnace only outputs one nether quartz item, despite being a ore

### ISSUE THREAD

**Issue by kouwei32** [micdoodle8/Galacticraft#3290]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version:4.0.1.163

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SMP on localhost Forge Server.

Galacticraft add-ons and other mods installed?
Yes, but I don't want to write this again. Check my other bug reports.

Please provide screenshots / crash report / log as needed.

**Comment by radfast** [comment]
The wiki says "doubled ingot production from smelting ores".

Nether Quartz is not an ingot ...

But ... seems reasonable to double this output as well.  The ore block will drop more than one quartz if mined with a Fortune enchantment.
