### ISSUE TITLE
Appears often in chat: The astro miner's route is blocked by: air

### ISSUE THREAD

**Issue by kouwei32** [micdoodle8/Galacticraft#3291]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version:4.0.1.163

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SMP.

Galacticraft add-ons and other mods installed?
Same as in #3290.

Please provide screenshots / crash report / log as needed.
![2018-03-27_20 58 38](https://user-images.githubusercontent.com/29967594/38008148-003f4e36-3202-11e8-944d-90e70041962a.png)
I have two astro miners in the asteroids area mining asteroids. This message often appear in chat despite my astro miners are working properly.

**Comment by kouwei32** [comment]
Apparently this also happens in other dimensions and is also likely to happen if the astro miner's base has a full inventory. Quite annoying.

**Comment by radfast** [comment]
@kouwei32  do you have Factions, WorldGuard, Grief Protection or other server plugins which could prevent the player mining some blocks?

The AstroMiner will also not mine those protected blocks.  Maybe this produces the "air" message you are seeing?

**Comment by radfast** [comment]
This should be improved in build 169.

(In English) there will now be a message "The Astro Miner's route is blocked by: Protected Area!" if it encounters one of these protected regions.

**Comment by kouwei32** [comment]
I do not have ANY area protection plugins. My mod server is private and running the normal forge server, and only me and my friends play on it. Seems like it is Galacticraft.

**Comment by radfast** [comment]
hmmm

I have made some other changes in build 169 that will interact with this.  It should now give you a correct message saying which is the problem block, instead of "air".

Let's see what it is and if it's still a problem we can re-open this.

**Comment by radfast** [comment]
Build 169 is now available to download.

**Comment by AlexaDTink** [comment]
Getting "blocked by: Protected Area!" with no protection plugins on a SSP/LAN game (I'm the host, sometimes opened to LAN to play with my nephew).

Should I add details here or start a new report?

**Comment by 7eggert** [comment]
I'm currently facing this problem on a fresh world, mercury from extra planets: "... blocked by: Protected Area!" ... but what position? Is it possible to find the nature of the block?

Sometimes randomly breaking blocks helps.
