### ISSUE TITLE
[1.12.2] Crash when making a double Astro Miner Base

### ISSUE THREAD

**Issue by marcus8448** [micdoodle8/Galacticraft#3293]
Minecraft version: 1.12.2
Galacticraft version: 166

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP
Galacticraft add-ons and other mods installed?
Planets

Please provide screenshots / crash report / log as needed.
[crash-2018-03-28_08.02.02-client.txt](https://github.com/micdoodle8/Galacticraft/files/1856529/crash-2018-03-28_08.02.02-client.txt)

Steps to reproduce:

![2018-03-28_08 05 33](https://user-images.githubusercontent.com/28928887/38037989-d37bf162-325e-11e8-99ef-60ad72627361.png)

Fill in the gap, you should get a light blue screen and then crash.

NOTE:
What's good is that it doesn't break the world :), it just makes one.

**Comment by radfast** [comment]
The crash report you posted is "impossible" if Galacticraft is downloaded correctly.

You appear to be using an unofficial mod file `GP.zip` instead of `GalacticraftPlanets`.  It's likely the cause of the error is linked to changes you made inside `GP.zip`.
