### ISSUE TITLE
Sun on display screen

### ISSUE THREAD

**Issue by Romsik788** [micdoodle8/Galacticraft#3295]
Minecraft version:1.12.2
Galacticraft version:4.0.1.164

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP not opened to LAN
Galacticraft add-ons and other mods installed?
Ecology mod, JEI/NEI, scenter, VoxelMap
Please provide screenshots / crash report / log as needed.
![2018-03-28_18 58 27](https://user-images.githubusercontent.com/33905242/38041685-b0361c56-32b2-11e8-8ab7-8bc62c6fe8fc.png)

**Comment by micdoodle8** [comment]
Thanks, should be rendering the full texture in the next build.
