### ISSUE TITLE
[1.12.2] Shield Controller not protecting armor from damage from other sources? It does protect it from corroding atmospheres however.

### ISSUE THREAD

**Issue by Z-Tunic** [micdoodle8/Galacticraft#3296]
Minecraft version: 1.12.2
Forge: 14.23.2.2629
Galacticraft version: 4.0.1.166

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Single-Player but most likely also other modes.

Galacticraft add-ons and other mods installed?
No other mods are installed.

Info:
The item "Shield Controller" has a description saying that it protects your armor from ALL kinds of damage. You will first notice this when you get it as a reward from Venus' Boss where the corrosive atmosphere on that planet normally degrades your armor by 1 per second while on the planet unless you wear this item.

However... despite the description saying that "Shield Controller protects armor from ALL forms of damage - even atmospheric corrosion!" Getting hit by mobs, shot by arrows and or getting burned by lava, etc. will still degrade your armor. Is this intended and the description is outdated? Or... is this a bug of some sorts? Maybe it's only certain types of damage? I am confused with this item.

Diamond Armor was used while having the Shield Controller equipped during the testing.

**Comment by Romsik788** [comment]
Shield controller protects only from atmospheric corrosion

**Comment by radfast** [comment]
> is this a bug of some sorts? Maybe it's only certain types of damage? I am confused with this item.

Sounds like a bug in 1.12.2.  The Shield Controller item is intended to protect your armor from atmospheric corrosion **and also all other types of armor damage** including arrows etc.

**Comment by TheQuadShot** [comment]
sorry if I'm off base here, Does it reduce damage from those "other" forms of attack damage?

I would think it would work something like a DR (Damage Resistance), not  a DT (Damage Threshold). Where DR removes _x_% of damage and DT would stop all damage under _x_

**Comment by radfast** [comment]
When all Minecraft "works" to reduce the player damage from an attack source, the armor itself takes some damage.  The amount of armor damage depends on the strength of the original attack and Unbreaking enchantments.  Also, the amount of damage armor can take, before breaking, depends on the armor type - diamond armor and other high tier armor can take many hits before breaking.  (Our Desh Armor, especially, takes a lot of punishment.)

For advanced players, with anvils and spells and plenty of resources, this armor damage is mostly just an annoyance - you might have very good enchanted armor, but it still takes some damage, and so eventually you need to repair the armor in an anvil.

The Shield Controller is intended to stop your armor from taking any damage at all.  Like having an Unbreaking infinity enchantment (or in practice Unbreaking X would be almost as good.)

This has no effect at all on the damage the **player** receives.  In recent Minecraft versions, attacks do a combination of physical damage (which is reduced by armor, according to armor tier and Protection enchantments) and true damage (unaffected by armor).  For example, Galacticraft's own suffocation damage from lack of oxygen is true damage, armor gives no protection against it.

The Shield Controller does not alter your armor value, armor protection tiers, Protection enchantments etc.

**Comment by marcus8448** [comment]
> Unbreaking infinity enchantment

There's actually a unbreaking NBT tag :)

**Comment by radfast** [comment]
On further testing, the armor is only getting **slightly** damaged with the Shield Controller in 1.12.2.

1.12.2 introduces a new mechanism "Armor Toughness" which affects how much damage the armor itself receives, and we didn't yet stop some of that damage getting through to the armor.

Fixed from next build 167.

**Comment by lolzhunter** [comment]
i have this issue as well, im using galacticraft 4 build 244 for both core, planets and the mcdoodle core, part of the modpack called Tekxit 3 for minecraft vers 1.12, i take armor damage from mobs too it seems with the shield controller equipped, im using full hexxit scale armor and it takes the same damage as if i didnt have the shield controller on at all, it does protect my armor from the venus atmosphere though so i know its not 'broken', any ideas on why this is? feel free to ask me for any more info that u need to help, ill be happy to provide
