### ISSUE TITLE
[1.7.10] CustomSteve render problem?

### ISSUE THREAD

**Issue by NSilviaS15** [micdoodle8/Galacticraft#3297]
So me and my weeb friend tried to launch 2 mikus into outer space and it didn't work. Cannot replicate with two Windows 7 devices so yea the problem might be weird and I am sorry if it was not a Galacticraft problem

Minecraft version:1.7.10
Galacticraft version:3.0.12

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SMP
Server on Win7
1 client on Win7
1 client on MacBook
Galacticraft add-ons and other mods installed?
CodeChickenCore{1.0.7.47}

customsteve{1.1.1-Beta} (Conflict?)

Micdoodlecore
NotEnoughItems{1.0.5.120}
CoFHCore{1.7.10R3.1.3}
exnihilo{1.38-53}
Mantle{1.7.10-0.3.2.jenkins191}
ThermalFoundation{1.7.10R1.2.5}
ThermalExpansion{1.7.10R4.1.4}
Waila{1.5.10}
TConstruct{1.7.10-1.8.8.build988}
exastris{MC1.7.10-1.16-36}
IC2{2.2.821-experimental}
GalacticraftCore{3.0.12}
GalacticraftMars{3.0.12} 
ExtraPlanets{1.7.10-1.9.5}
Forestry{4.2.14.62}
Roguelike{1.5.0} [Roguelike Dungeons]
ThermalDynamics{1.7.10R1.2.0}
VeinMiner{0.35.1_1.7.10-a8c76e8}

Please provide screenshots / crash report / log as needed.

Server Log
[2018-02-18-1.log](https://github.com/micdoodle8/Galacticraft/files/1862560/2018-02-18-1.log)

Client Log 1 (Win7)
1:[2018-02-18-1.log](https://github.com/micdoodle8/Galacticraft/files/1863655/2018-02-18-1.log)
2:[2018-02-18-2.log](https://github.com/micdoodle8/Galacticraft/files/1863658/2018-02-18-2.log)

Client Log 2 (Mac)
[2018-02-18-3.log](https://github.com/micdoodle8/Galacticraft/files/1863644/2018-02-18-3.log)

**Comment by TheQuadShot** [comment]
Why Guava only on the mac client? (I don't really know much about it other than what's on their github)

**Comment by radfast** [comment]
This is in your logs:

> java.io.FileNotFoundException: customsteve:texture/toon/toon00.png

That's not connected with Galacticraft!  Please take this up with CustomSteve mod.

**Comment by NSilviaS15** [comment]
Thanks for troubleshooting, and I am deeply sorry to have troubled you.
