### ISSUE TITLE
BC fluid break grating

### ISSUE THREAD

**Issue by FrostQ** [micdoodle8/Galacticraft#3300]
Minecraft version: 1.12.2
Galacticraft version: 4.0.1.168

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Both

Galacticraft add-ons and other mods installed?
- **Buildcraft**
- and others

Please provide screenshots / crash report / log as needed.
All bc fluids (except **Cool Oil**)
https://youtu.be/A_eTLubTvdE

**Comment by radfast** [comment]
Thanks for testing!

Looks like **all** fluids from other mods will destroy the grating, currently. :(  This is a side-effect of allowing fluids to flow into it.

The fix will be to register a grating variant for all Forge fluid blocks...  we can probably do this on Monday.

**Comment by radfast** [comment]
Fixed in build 169.

@SteveKunG @MJRLegends @BlesseNtumble  now it should be unnecessary for your mods to call `GalacticraftRegistry.registerGratingFluid()` - GalacticraftCore should automatically detect all your registered blocks which are `BlockFluidBase` subclasses.

**Comment by radfast** [comment]
Build 169 is now available to download.
