### ISSUE TITLE
Evolved Creeper drop Redstone instead Gunpowder

### ISSUE THREAD

**Issue by FrostQ** [micdoodle8/Galacticraft#3302]
Minecraft version: 1.12.2
Galacticraft version: 1.12.2-4.0.1.168

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Both

Galacticraft add-ons and other mods installed?
Yes

Please provide screenshots / crash report / log as needed.
Loot from evolved creepers:
![2018-03-31_15 59 01](https://user-images.githubusercontent.com/36822613/38163935-8ddd5baa-34fc-11e8-87ce-2a068311e99a.png)
- _Medium oxygen tank_ and others rare drop items is fine
- but redstone, sand and ice?

**Comment by QuantumStatement** [comment]
It's [intended behavior](https://wiki.micdoodle8.com/wiki/Evolved_Creeper#Data)

**Comment by radfast** [comment]
Thank you QuantumStatement

**Comment by radfast** [comment]
The ice and sand are used internally in the Creeper to regulate its explosiveness - it's how it stops the explosion after already primed.

**Comment by EzerArch** [comment]
> The ice and sand are used internally in the Creeper to regulate its explosiveness - it's how it stops the explosion after already primed.

Aaaand the wiki got an update. :) https://wiki.micdoodle8.com/wiki/Evolved_Creeper

**Comment by FrostQ** [comment]
Oh, i didn't know about this
