### ISSUE TITLE
No Such Method Error

### ISSUE THREAD

**Issue by Anubite51** [micdoodle8/Galacticraft#3304]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version:1.11.2
Galacticraft version:1.11.2

Multiplayer (SMP

Galacticraft add-ons and other mods installed? 
The only other mod was Aether 2 as I was testing Galacticraft since it crashed my launcher before in the same way.  The other galacticraft mods were the mcdoodlecore and Galacticraft planets

This is the inside of my .minecraft/mods folder.
![capture](https://user-images.githubusercontent.com/37968156/38169050-07509ada-352d-11e8-9aad-d2f56b19afc8.PNG)

Please provide screenshots / crash report / log as needed.  Here's the crash report
[crash-2018-03-30_21.54.52-client.txt](https://github.com/micdoodle8/Galacticraft/files/1866047/crash-2018-03-30_21.54.52-client.txt)

I had gone to forges forums asking about the error and was told that it was an issue with the code :/
Hopefully there is something I can do to fix this because I'd love to have this mod in my server! :)

**Comment by TheQuadShot** [comment]
have you tried disabling Aether and launching Galacticraft only session?

**Comment by radfast** [comment]
The reason for this error is you have mixed files from **different** Galactictraft versions, I can see both 121 and 128.

Delete all these files, delete micdoodlecore as well.

Now go to our [download site](https://micdoodle8.com/mods/galacticraft/downloads) and download the latest version, all three files.

**Comment by radfast** [comment]
Did you originally download our mod from an unofficial source?  Your mods folder looks wrong.  If you can show us the source, maybe we can do something about this, as it could be they are also giving other people a messed up version.

**Comment by radfast** [comment]
Also please link to the Forge forum thread where the "expert" said it was an issue with our code.

**Comment by Anubite51** [comment]
Here's the comment asking me to come here :)  Thank you for the help guys I will try starting it with just galacticraft and ill get it from your site!

http://www.minecraftforge.net/forum/topic/63781-no-such-method-error/?tab=comments#comment-300999

**Comment by wamc2017** [comment]
Let me guess, you downloaded Galacticraft-Planets-Mod-1.11.2.jar and MicdoodleCore-1.11.2.jar from .9minecraft and GalacticraftCore-1.11.2.jar from mc-mod? The files on their sites are exactly named as in your screenshot... (also looks like they got the same file size)

You should not download from these sites, they offer old mod versions which are hosted without the permission of their authors! (and may contain malware in some cases)

Check this list for future downloads, if the site is listed: https://github.com/VictiniX888/Illegal-Mod-Sites/blob/master/SITES.md

**Comment by MJRLegends** [comment]
#StopModReposts

**Comment by Anubite51** [comment]
I thought they had been all from 9minecraft.  Where is a good place to get all the mods from without having to memorize a bunch of different locations from each mod developer?

Ok i used the recommended links and the launcher still crashed with a different error :/  
[crash-2018-04-01_21.49.45-client.txt](https://github.com/micdoodle8/Galacticraft/files/1866876/crash-2018-04-01_21.49.45-client.txt)

 This one is a crashe while ticking screen.  Index out of bounds exception.  I dont know why this mod is so difficult to get working.  Says something about using an unsupported modified version of the game.  Is that with any mod though?

**Comment by TheQuadShot** [comment]
sounds weird, but lower your render distance and resolution and give it a try, if that fails try re-installing (or force update).

**Comment by radfast** [comment]
>  Where is a good place to get all the mods from without having to memorize a bunch of different locations from each mod developer?

[www.google.com](www.google.com)

>    Index out of bounds exception. I dont know why this mod is so difficult to get working. 

https://wiki.micdoodle8.com/wiki/Tutorials/Galacticraft_Installation_Guide#Minecraft%20crashes%20with:-%20java.lang.IndexOutOfBoundsException

**Comment by Anubite51** [comment]
So I'm trying to get this galacticraft to work with buildcraft and tinker's construct but it seems the versions of forge required make this impossible.  Anyone know any way to make these mods work together?

**Comment by radfast** [comment]
Galacticraft works with **almost any** version of Forge.  Please [RTFM](https://wiki.micdoodle8.com/wiki/Tutorials/Galacticraft_Installation_Guide).

If Buildcraft and TC have conflicting Forge requirements, you'll have to roll back to an earlier version of one of those mods.
