### ISSUE TITLE
Game Crashes Upon Opening

### ISSUE THREAD

**Issue by 104bytes** [micdoodle8/Galacticraft#3305]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2 Forge + 1.12.2 Liteloader
Galacticraft version: GalacticraftCore-1.12.2-4.0.1.168

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? SSP

Galacticraft add-ons and other mods installed? No addons, but other mods: 

- iChun Util

-  RadixCore

- Optifine

- MovingWorld

- MicdoodleCore

- Minecraft Comes Alive

- Just Enough Items

- Forestry

- DynamicSurroundings

- DoggyTalents

- Coral Reef Mod

- Damage Indicators

- CFM

- BiblioCraft

- BetterFoliage

- BackTools

- Aether Legacy

- BiomesOPlenty

- DavincisVessels

It is not other mods that don't work, as the game launchers when GalacticCraft is not in the mods folder.

Please provide screenshots / crash report / log as needed.
```

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Galacticraft Core (galacticraftcore)
```

**Comment by radfast** [comment]
Please provide the full crash report (from crash reports folder) or else the full log.

**Comment by radfast** [comment]
Closing due to lack of requested information.

We can't fix a problem if we don't know what it is.  (Also sometimes the lack of follow-up is a sign that the OP has fixed the issue themselves due to common derps such as incorrect downloads ...)

We will re-open if the requested information is provided.
