### ISSUE TITLE
Electric Furnace Randomly Stops Working

### ISSUE THREAD

**Issue by kouwei32** [micdoodle8/Galacticraft#3308]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 4.0.1.168

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SMP.

Galacticraft add-ons and other mods installed?
Same as in #3280.

Please provide screenshots / crash report / log as needed.

![2018-04-01_16 41 23](https://user-images.githubusercontent.com/29967594/38178684-b2b07e8c-35cc-11e8-9085-b8f6882b176e.png)

I broke it and places it again, and it's still not working.

**Comment by TheQuadShot** [comment]
Did you try to apply or remove a redstone signal to/from it?

**Comment by radfast** [comment]
If it's showing Status "OFF" this means there is a redstone signal disabling it.

Could be a weak redstone signal coming through nearby blocks.

Please break **all** blocks around the Electric Furnace and see if it is still not working.
