### ISSUE TITLE
Grapple's projectile is invisible

### ISSUE THREAD

**Issue by FrostQ** [micdoodle8/Galacticraft#3309]
Minecraft version: 1.12.2
Galacticraft version: 1.12.2-4.0.1.168

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Both

Galacticraft add-ons and other mods installed?
Yes

Please provide screenshots / crash report / log as needed.
- It is not about grapple's line/string
![2018-04-02_11 31 32](https://user-images.githubusercontent.com/36822613/38191535-75936cce-3669-11e8-9b21-1640d8727863.png)
https://youtu.be/b3LB6YU-kIE
And why small asteroid not spawning?

**Comment by micdoodle8** [comment]
Thanks! Both grapple and small asteroids will render properly in the next build.

**Comment by radfast** [comment]
Build 169 is now available to download.
