### ISSUE TITLE
Telepad work even if is disabled

### ISSUE THREAD

**Issue by FrostQ** [micdoodle8/Galacticraft#3313]
Minecraft version: 1.12.2
Galacticraft version: 4.0.1.168

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Both

Galacticraft add-ons and other mods installed?
Yes

Please provide screenshots / crash report / log as needed.
- https://youtu.be/ykups0TMjAw

**Comment by radfast** [comment]
Thank you for all your careful testing and bug reports!  I'm sure we can fix this one easily enough.

**Comment by radfast** [comment]
Build 169 is now available to download.
