### ISSUE TITLE
Bubbles sometimes not visible

### ISSUE THREAD

**Issue by FrostQ** [micdoodle8/Galacticraft#3315]
Minecraft version: 1.12.2
Galacticraft version: 4.0.1.168

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Both

Galacticraft add-ons and other mods installed?
Yes

Please provide screenshots / crash report / log as  needed.

Bubble disapear sometimes if you can't see looking Oxygen Distributor/Terraformer on screen
Screenshot with bugged footprints (full black and transparent rectangles), Bubble is on right screen.
![2018-04-03_16 57 12](https://user-images.githubusercontent.com/36822613/38257561-bd4694ae-3760-11e8-8cc1-97659b43cb3f.png)
Screenshot if you can see:
![2018-04-03_16 41 41](https://user-images.githubusercontent.com/36822613/38257642-e2cf5800-3760-11e8-986a-62776b2053d0.png)
![2018-04-03_16 57 14](https://user-images.githubusercontent.com/36822613/38257702-00149a1a-3761-11e8-89b4-a3b7b89d96a1.png)

Short Video:
https://youtu.be/gpBJYDiesiQ

**Comment by kouwei32** [comment]
Perhaps it's something like #3232, where the bubble rendering is outside of the frustum.

**Comment by micdoodle8** [comment]
Correct, the chunk with the bubble was being ignored because it's outside the frustum.

Bubbles (terraformer and distributor) are now rendered separately from the tile entity, so this should be fixed in the next build.

Thanks!

**Comment by radfast** [comment]
Build 169 is now available to download.
