### ISSUE TITLE
[1.12.2] Arm position issue with Aether Legacy.

### ISSUE THREAD

**Issue by Z-Tunic** [micdoodle8/Galacticraft#3318]
Minecraft version: 1.12.2
Forge: 14.23.2.2629
Galacticraft version: 4.0.1.168

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Single-Player but most likely also other modes.

Galacticraft add-ons and other mods installed?
aether_legacy-1.12.2-v2.0

Image:
![](https://cdn.discordapp.com/attachments/377171551155650560/430931911062454272/GCALModelissues.PNG)

Info:
Unsure if this goes here but... anyway...

The Shield of Repulsion's blue aura & Glove Models from Aether Legacy breaks slightly with Galacticraft being installed.

The Shield of Repulsion's blue aura & Gloves do detect certain movements like holding a flag or moving around but attacking or holding items it doesn't sync correctly and act as if standing still.

There are capes in Aether Legacy however I didn't notice anything wrong with them, as far as I know. The Model issues don't happen with Aether Legacy by itself.

**Comment by radfast** [comment]
See also #3259.  This will be linked with https://github.com/micdoodle8/Galacticraft/commit/1105d0d4ae9f315eb7300893ee2d4454b87e2b61#diff-9cbde4465a41981e648946596d71f05a  https://github.com/micdoodle8/Galacticraft/commit/2cdc06b1afdb25e664a7f8123c54b9f5ebdf0314#diff-9cbde4465a41981e648946596d71f05a  and  https://github.com/micdoodle8/Galacticraft/commit/46237b0b364aa8e7e6dbe31533038f3f81b573b7#diff-9cbde4465a41981e648946596d71f05a

**Comment by radfast** [comment]
See https://github.com/Modding-Legacy/Aether-Legacy/issues/45 for the same issues with Aether Legacy and More Player Models.   Aether Legacy developer does not want to fix this.

**Comment by Z-Tunic** [comment]
Huh, MorePlayerModels had the same issue and the dev didn't want to fix it? Interesting...

Granted it's been a year after that issue was posted so maybe he changed his mind? I don't know but only time will tell.

**Comment by radfast** [comment]
This is fixed in our next build 170.  All looks OK in my testing.
