### ISSUE TITLE
[1.12.2] No caves generating on Mars

### ISSUE THREAD

**Issue by AuroraPioneer** [micdoodle8/Galacticraft#3319]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 4.0.1.168

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Single player but surely affects all since it's a world gen problem

Galacticraft add-ons and other mods installed?
NEI/JEI are the only other mods I'm using

I had noticed that there were no cave entrances on Mars after flying around for awhile. I went into spectator mode to check where all the caves were and found none. There are some small open spaces scattered just below the surface but nothing more then that.

![2018-04-04_14 44 46](https://user-images.githubusercontent.com/8295683/38327714-e2de7068-3816-11e8-96ef-d0a45d4dd59c.png)

**Comment by FrostQ** [comment]
It was happened since 145 build
The small open spaces in your screenshot is **ice**
- Screenshot from 144 build
![2018-04-04_23 05 34](https://user-images.githubusercontent.com/36822613/38335274-19d421ac-385e-11e8-8b0c-7a1b2f1483b1.png)

**Comment by radfast** [comment]
Thanks both of you, I'm pleased we have caught this.

Fixed in next build 169.

Players will have to regenerate Mars chunks to have the caves and caverns.  This will also affect some addon planets @SteveKunG @MJRLegends which must have been missing caverns for similar reasons - sorry about that guys.

**Comment by MJRLegends** [comment]
@radfast I think all of mine as using a custom ChunkProvider anyways but appreciate the ping about the issue i will keep it in mine if i get any reports :D

**Comment by TheQuadShot** [comment]
Question, does/will GC follow the custom world gen that's in the newer versions (1.10+)? I create worlds that have no ravines/caves since I mine all of the planets with quarries.

**Comment by radfast** [comment]
No, Galacticraft planets worldgen makes no reference to the custom worldgen settings (e.g. the settings for "use caves", "use ravines").  I think vanilla Nether worldgen also ignores these.

**Comment by radfast** [comment]
Build 169 is now available to download.

**Comment by SteveKunG** [comment]
My planets use [ChunkProviderBaseMP](https://github.com/SteveKunG/MorePlanets/blob/1.12.2/src/main/java/stevekung/mods/moreplanets/util/world/gen/ChunkProviderBaseMP.java). So don't worry about that :)
