### ISSUE TITLE
Bugged Water

### ISSUE THREAD

**Issue by FrostQ** [micdoodle8/Galacticraft#3321]
Minecraft version: 1.12.2
Galacticraft version: 4.0.1.169

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Both

Galacticraft add-ons and other mods installed?
Yes (even without other mods)

Please provide screenshots / crash report / log as needed.
![2018-04-05_16 02 45](https://user-images.githubusercontent.com/36822613/38371027-c695a8ec-38eb-11e8-85c7-5b55c17f6d19.png)
![2018-04-05_16 08 42](https://user-images.githubusercontent.com/36822613/38371028-c6bf5106-38eb-11e8-96f2-1cd5027532f3.png)

**Comment by FrostQ** [comment]
In previous build i didn't have dark color water
I checked with only GC installed and previous build (168).
On 168 build was fine but on 169 is darker.
- Before 169 build (or no mods installed)
![2018-04-05_19 07 31](https://user-images.githubusercontent.com/36822613/38380728-ee02ae02-3904-11e8-8ee7-7d8fde3689d9.png)
- On 169 build
![2018-04-05_19 09 35](https://user-images.githubusercontent.com/36822613/38380729-ee27de66-3904-11e8-9789-46cffbaac2d4.png)

**Comment by MJRLegends** [comment]
I can confirm this issue too, i tested in MC 1.8.9

**Comment by SteveKunG** [comment]
Can confirmed with latest GC source code (1.12) installed.

![2018-04-06_01 08 45](https://user-images.githubusercontent.com/6128413/38383603-24a518c8-3937-11e8-92f8-5ece71300bb2.png)

**Comment by radfast** [comment]
The water issue is caused by the new [Bubble Renderer](https://github.com/micdoodle8/Galacticraft/commit/873008b28f03a64c4e5f60e2c1f63140b5a6aa4e).  Not connected with the Grating block.

I quite like the "bugged" water texture, it's worth remembering how we did this, maybe we can use it on a future planet...

**Comment by MJRLegends** [comment]
Yeah i thought the same about the bugged colour looks better tbh haha

**Comment by radfast** [comment]
@SteveKunG  the FPS drop is expected when you break and place blocks, the Minecraft client re-renders the whole chunk if 1 block changes.  You still have 267 FPS ...

I think your FPS will be similar if you:
* remove all the gratings but **keep** the water source block and flowing water in the same positions
* break and place some regular block like Wooden Plank at the same position

-----

The purple dot is a big mystery ... I can see it!  It is **not** connected with the fluids, it occurs even with the regular (no fluids) block.  We can also test it in 1.8.9 where there is no interaction between the Grating and fluids, I think it will be the same.

Seems to be related to the complex CUTOUT model for this block, dots are seen at the junction between
