### ISSUE TITLE
NBTTagCompound crash

### ISSUE THREAD

**Issue by xxlio109** [micdoodle8/Galacticraft#3323]
Minecraft version: 1.12.2
Galacticraft version: 1.12.2-4.0.1.170

Multiplayer (SMP),

https://github.com/SpongePowered/SpongeForge/issues/2083#issuecomment-379195007

**Comment by radfast** [comment]
hi @xxlio109 

I've responded in the SpongeForge issue thread.  What **phit** told you there is not correct.  This is not a Galacticraft issue, it probably is not connected with Galacticraft at all - meaning you would have exactly the same issue without Galacticraft installed.

On the Sponge thread (not here) it might help if you can give more details like
- does it occur **every time** you load this world and this player logs in - or was it a "one off" issue
- what action was the player doing at the time of the crash
- can you reproduce the crash with a smaller mod list
