### ISSUE TITLE
[Minor] Duplicating of Canned Food items in creative tab

### ISSUE THREAD

**Issue by QuantumStatement** [micdoodle8/Galacticraft#3324]
Minecraft version: 1.11.2
Galacticraft version: 4.0.1.170

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP

Galacticraft add-ons and other mods installed?
None

Please provide screenshots / crash report / log as needed.
![2018-04-06_01 49 56](https://user-images.githubusercontent.com/35406698/38431549-46804314-39cd-11e8-9bab-ad5be6215e26.png)

**Comment by radfast** [comment]
thanks, can be fixed easily enough.

The first set are the "old" canned food, which are `galacticraftcore:basic_item` with damage 15-18.  The second set are the "new" canned food which are `galacticraftcore:food` and compatible with other mods like Hunger Overhaul.

**Comment by FrostQ** [comment]
1.12.2 still have duplicate Canned Food on creative tab
