### ISSUE TITLE
Breaking a Grating placed on fluid source block also break fluid block

### ISSUE THREAD

**Issue by QuantumStatement** [micdoodle8/Galacticraft#3325]
Minecraft version: 1.11.2
Galacticraft version: 4.0.1.170

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP

Galacticraft add-ons and other mods installed?
IndustrialCraft 2 ver. 2.7.86
Buildcraft 7.99.8.2

Please provide screenshots / crash report / log as needed.
![2018-04-06_01 38 54](https://user-images.githubusercontent.com/35406698/38431907-7412701c-39ce-11e8-804e-19d5b57feb6e.png)
![2018-04-06_01 39 06](https://user-images.githubusercontent.com/35406698/38431908-744672ae-39ce-11e8-835a-4718fba5ad0b.png)
If you place Grating on fluid source block and break it, then fluid block disappears

Also fluid blocks under Grating aren't accessible for IC2 and Buildcraft pumps

**Comment by FrostQ** [comment]
Not fixed on 1.12.2
Lava in grating not emit light
![2018-04-07_10 30 38](https://user-images.githubusercontent.com/36822613/38453007-0d4456bc-3a4f-11e8-93eb-9c26c0a0a49e.png)

**Comment by radfast** [comment]
Thanks, good spot.  Fixed in next build 172, all versions.
