### ISSUE TITLE
Chromatic Applicator don't coloring Vacuum Glass

### ISSUE THREAD

**Issue by QuantumStatement** [micdoodle8/Galacticraft#3326]
Minecraft version: 1.11.2
Galacticraft version: 4.0.1.170

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP

Galacticraft add-ons and other mods installed?
None

Maybe I'm doing something wrong, but Chromatic Applicator don't coloring Vacuum Glass frame. I'm using all three types of Vacuum Glass with white frame

**Comment by radfast** [comment]
Thanks for reporting, I guess this has been not working in 1.10+ ever.  :(

Anyhow, fixed in next build 171.  :)

**Comment by FrostQ** [comment]
Not fixed in 1.12.2
![2018-04-07_10 23 38](https://user-images.githubusercontent.com/36822613/38452927-e02107f8-3a4d-11e8-9f49-2c857977ddef.png)
It still have white frame on this version

**Comment by radfast** [comment]
Fixed in 172.  (I was tired when I built last night, and forgot to upload the updated 1.12.2 code ...)
