### ISSUE TITLE
[1.12 Dev] Grating block rendering

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#3332]
My mod has added custom lava fluid (Crystallized Lava and Nuclear Waste) and travels 3 blocks like vanilla Lava. Fluid Model doesn't match to the original.

![2018-04-06_01 27 56](https://user-images.githubusercontent.com/6128413/38460502-38c61a46-3ae5-11e8-9250-61968192f939.png)
![2018-04-08_04 25 39](https://user-images.githubusercontent.com/6128413/38460503-38fc875c-3ae5-11e8-960c-288223c7159e.png)

Also z-fighting texture with Gases.
![2018-04-08_04 26 32](https://user-images.githubusercontent.com/6128413/38460515-8a200fa0-3ae5-11e8-80c1-bc10b7c03baf.png)
![2018-04-08_04 31 19](https://user-images.githubusercontent.com/6128413/38460522-b67a5b14-3ae5-11e8-8c28-dbcaf122bd86.png)

**Comment by radfast** [comment]
z fighting now fixed.  (Unfortunately we have to let the ForgeFluid be on top - I want to have the Grating on top but I can't find a way.)

The modded lava flow issue - please can you put breakpoints or `e.printStacktrace()` [here](https://github.com/micdoodle8/Galacticraft/blob/MC1.12/src/main/java/micdoodle8/mods/galacticraft/core/blocks/BlockGrating.java#L787-L789) and see if it is picking up the correct `quantaPerBlock` for your blocks - I think it should be 4?

**Comment by SteveKunG** [comment]
It seems fixed to me, I have update to latest sources. Thank you!

![2018-04-10_07 52 09](https://user-images.githubusercontent.com/6128413/38530382-5869354e-3c94-11e8-9a20-8c10387230f4.png)

**Comment by radfast** [comment]
that's good news 👍 

I'm not totally sure that I changed anything relevant to this.  But anyhow, if it's working, all is good!
