### ISSUE TITLE
Waila error's in build 173

### ISSUE THREAD

**Issue by TheQuadShot** [micdoodle8/Galacticraft#3334]
Minecraft 1.10.2
Forge 12.18.3.2511
Waila-1.7.0-B3_1.9.4
MicdoodleCore-1.10.2-4.0.1.173.jar
Galacticraft-Planets-1.10.2-4.0.1.173
GalacticraftCore-1.10.2-4.0.1.173

The tool tips are correct it's just waila. 

Launch controller - terraformer
Oxygen Storage Module - Electric Compressor
Deconstructor -  Electric Compressor
Circuit Fabricator - Electric Compressor
Oxygen Decompressor - Oxygen Compressor
Electric Furnace - Energy Storage Module
Energy Storage Cluster - Energy Storage Module - 
Electric Furnace - Energy Storage Module
Electric Arc Furnace - Energy Storage Module
Compressor - Coal Generator
All Walkways report as such (cant tell which is which after placed)
All Lighting Panels - Lighting Panels (square)
Emergency Post (with kit) - Emergency Post

**Comment by radfast** [comment]
Thanks, we probably need custom WAILA support :(

**Comment by radfast** [comment]
OK it's actually a WAILA bug:
https://bitbucket.org/ProfMobius/waila/issues/273/194-showing-incorrect-block-type-mekanism
https://github.com/aidancbrady/Mekanism/issues/3711

The fix which JaSpr provided as discussed on the Mekanism error report has never been included in WAILA.  Seems like WAILA is simply no longer updated at all, and everybody is using HWYLA or other alternatives.

**Comment by TheQuadShot** [comment]
I've re-checked with JEI (jei_1.10.2-3.14.7.420) the errors still exist with one additional

Cargo Unloader - Cargo Loader
