### ISSUE TITLE
Eating galacticraft foods when on an empty hunger bar crashes game ( sevTech3.0.6 )

### ISSUE THREAD

**Issue by daddy77gaming** [micdoodle8/Galacticraft#3336]
Mc 1.12.2
SevTech 3.0.6

Crashed on all type of canned foods & hamburgers, when on an empty hunger bar (after veinmining, but the hunger bar being empty is the cause combined with eating the food)
Only galacticraft foods cause this crash so far, tested various different mod foods for a couple of hours

https://github.com/Darkosto/SevTech-Ages/issues/1656

**Comment by micdoodle8** [comment]
Fixed in build 174, tested with SevTech :)
