### ISSUE TITLE
[Feature Request] Custom flags

### ISSUE THREAD

**Issue by efalder413** [micdoodle8/Galacticraft#334]
Would it be possible to add a folder where we can drop pngs of flags for countries other than USA? Or maybe a skin-style system on your website?

**Comment by Planetice** [comment]
is there a way to actually put png's into the game itself as i made a flag for my server but it will be too hard to make in game and was wondering if i could just insert it in a folder and use it?

**Comment by ROMVoid95** [comment]
Not in the current version but it could possible to add the ability
