### ISSUE TITLE
Request: Rocket Fuel Config

### ISSUE THREAD

**Issue by septemberWaves** [micdoodle8/Galacticraft#3351]
I'd like to request a setting in the configuration file that allows modpack developers to change the fluid that is used as rocket fuel. For example, it could be changed to require Ender IO rocket fuel, or some other complex fluid from another mod that's harder to make than regular fuel. If possible, being able to define multiple different rocket fuels with different fuel efficiencies (i.e. how effective they are as fuel) would be preferred; this way modpack developers such as myself can implement some progression with rocket fuels, with ones that are more challenging to make being ultimately better to use.

**Comment by TheQuadShot** [comment]
The dev team is always open to suggestions and requests for "enhancements", and in most cases they prefer them to be open to the community to get additional feedback on requests. However they also prefer them to be posted on the Forum so other users can see and comment. This is a bug tracking tool for them, so please file your request here: https://forum.micdoodle8.com/index.php and close this report. Thanks!

**Comment by septemberWaves** [comment]
Ah, I was unaware of the forum. I'll make any further requests there in future.

**Comment by radfast** [comment]
Having tiered/multiple fuels would need a lot of re-coding of rockets, fuel loaders, and all the landers.  (The landers give back the unused fuel.)  Would also need graphical changes.  That's a huge amount of coding for a feature which only one pack wants.

Maybe it's something we might do sometime, but there are a lot of other priorities - including new dimensions and making our existing dimensions a richer playing environment.

Meanwhile if you want to disable the standard Galacticraft Fuel, you could:
* set the Galacticraft config to disable oilgen in the world
* or set the Galacticraft config to make oil generate very _rarely_ in the world
* use a server plugin to ban the Refinery
* use CraftTweaker to change the Refinery recipe to make it extremely costly to make

Galacticraft's Fuel Loader will accept EnderIO Rocket Fuel already as an input.  So if you disable Galacticraft's own Fuel (or make it very rare / costly in one of the above ways) then players will have to use EnderIO Rocket Fuel.

More generally you can set Galacticraft into Hard Mode (and set Quick Mode off) if you want to make it very challenging.  If your modpack includes a mod with Steel (for example, Railcraft) then this will delay all rocket crafting until the player has achieved Steel.

You can also change the Rocket Fuel Factor to make the rockets burn more fuel when they fly, so one flight uses up a full tank of fuel.
