### ISSUE TITLE
[Vanilla bug] You slide on Hydraulic Platforms if they are built over ice or packed ice 

### ISSUE THREAD

**Issue by TheQuadShot** [micdoodle8/Galacticraft#3352]
Minecraft 1.10.2
Forge 12.18.3.2511

Galacticraft-Planets-1.10.2-4.0.1.173.jar
GalacticraftCore-1.10.2-4.0.1.173.jar
MicdoodleCore-1.10.2-4.0.1.173.jar

It's like standing on the ice. It only happens to the "bottom" platform. If you take it down then it doesn't happen, but it will if you step of it and return it will.

ADDED: I get a "Green Light" on an invalid platform (only one platform placed) I would expect that the light be red if their is no "landing platform" or destination for the platform.

**Comment by radfast** [comment]
I guess the reason is that when you stand on the platform you are < 1 block from the ice because the platform has a slight dip - the displacement is actually very close to that of Farmland, as you say.  This is probably what gives the "ice skating" behaviour whe you bound on ice.

How is vanilla behaviour with a half slab (bottom slab) over ice?  I imagine it will be the same.

I'll look at this movement issue at the same time as the green light issue, see if there's anything we can do from our side to fix it (I'm guessing there may not be).

**Comment by radfast** [comment]
>  ADDED: I get a "Green Light" on an invalid platform (only one platform placed) I would expect that the light be red if their is no "landing platform" or destination for the platform.

More info please to reproduce this.

If only one platform is placed, there should be no light at all.  It should have hazard lines all the way around the 1 block.  There isn't even a place for the light.
![2018-04-30_11 50 18](https://user-images.githubusercontent.com/6842258/39454082-28f20212-4cd1-11e8-98cf-9deb38231a4b.png)

**Comment by TheQuadShot** [comment]
Sorry, should have explained better. Stand on the platform, you get the green lights
https://imgur.com/a/lUERR7n
https://imgur.com/a/UkrQKKi
This give me the impression that it's operational, but if I don't have another platform above/below it, it's not. Hope that makes more sense now, if not let me know.

**Comment by radfast** [comment]
oh I see!  That's intended behaviour, currently.  The purpose of the green light is to show that you are standing in the correct position.  It's kinda assumed that the player knows whether he built another platform above/below it...

**Comment by TheQuadShot** [comment]
Sorry, I shared the map and the others(family) couldn't figure out how it worked, cause it turned green on them, turns out they were not standing on the one in the base(that's working) they were on the one outside over the ice where I was testing, they thought it lead to my mine shafts below the base. Any how I couldn't fault their logic and I agree with them. I'll file this over on the forum for discussion and maybe later stuff.

**Comment by radfast** [comment]
As with some other things, if we had 3-5 coders on the dev team then these kind of things could be polished more, maybe different colours even to tell you how far away the platforms above and below are.

As it is, I think it's working well enough and I need to switch my time to other things like the new Deep Space Station which is coming along nicely, but needs help and input from others now.  Any of your family members fancy themselves as builders?

**Comment by TheQuadShot** [comment]
I love building(personally I don't think I'm that good, but they insist)! And my family always elects me to do the building since they're always different and have lots of "secrets" for them to find (between the ages of 5 and 9, the older ones(16-24) just like that it's organized and has a sorting system so they can just dump and find things(LOL lazy bastards!),  I had/have a design in mind for a space station that isn't a torus, best described would be a spinning Jack https://imgur.com/a/rOgDgil I was going to put it in the mod pack I've been working on, but your more than welcome to it! I was going to put different processes in each sphere. My biggest problem is how to convert something I build into a json file, still haven't even started working on that part yet.

**Comment by radfast** [comment]
That's a nice shape for a station!

I've been researching the Stanford Torus, and [this very interesting paper](https://www.nasa.gov/sites/default/files/files/Longman_2013_PhI_Tensegrity.pdf) which is kind of a 21st century update on it, looking specifically at reducing the mass of the required materials while increasing the radiation protection.  It also has a design requirement for expandability, which seems crazy to me, must be many times the cost and more things to go wrong.

> My biggest problem is how to convert something I build into a json file.
I don't know a way, but there's bound to be a mod or plugin which can do this - you also need a way to convert the JSON file into a build of course...

**Comment by TheQuadShot** [comment]
Yep, the concept has been around for a while, material is the problem(and wanting "gravity") While I agree with a torus design is effective, an "ancient" or abandoned base needn't be "human" but able to be adapted to human use. My idea for the mod pack is loosely based on the Ember Wars, so very very ancient (few billion yrs) and lived/ing in black holes, human race saved by alien cloneing technology and eventually "procedurally generated humans(proce's)" (flash clones with fake memories) and no one can tell the difference. Except an alien race that gets it nourishment from "consuming" memories from sentient beings, that want this technology to open fast food chain stores (kidding), and pay an even higher price for original/true humans(for the gourmet) , and they aren't bibeds, so I needed/wanted bizarre designs. Then using "Proce's" repopulate a planet (void of sentient/hostile life)

**Comment by radfast** [comment]
Whoah, sounds an interesting and ambitious modpack.  I can think of a few mods that might help, but I don't know of any with a truly alien race.

In Galacticraft I am aiming to hint at the possibility of aliens, with the two "non-human" variants of the Abandoned Base in asteroids - internally in the code one variant is called Tunneler and one is called Avian.  There are also the Strange Seeds, which will do something eventually.  But we have not gone anywhere with these yet, nothing has been seen so far.

(I don't know if any of the Galacticraft add-ons have aliens?)
