### ISSUE TITLE
null pointer on ContainerCircuitFabricator.mergeEven

### ISSUE THREAD

**Issue by TheQuadShot** [micdoodle8/Galacticraft#3353]
Minecraft 1.10.2
Forge 12.18.3.2511

Galacticraft-Planets-1.10.2-4.0.1.173.jar
GalacticraftCore-1.10.2-4.0.1.173.jar
MicdoodleCore-1.10.2-4.0.1.173.jar

InventoryTweaks-1.62-dev-66.jar
MouseTweaks-2.8-mc1.10.2.jar
modlist
https://pastebin.com/gb9hJHPb

I was shift-clicking a stack of itemSilicon (EIOs) I've done this a *bunch of times since you added it with no problems.
*5 stacks of each output item type

Crashlog: https://pastebin.com/4QZVHKzQ

Edit: It's definitely happening when you drop(shift click) an odd number of itemSilicon

**Comment by radfast** [comment]
Thanks, will take a look...

**Comment by TheQuadShot** [comment]
Electric Compressor "chokes" on output at 64 in top and 63  in bottom and shows 2 ingots still in the compressor.
https://imgur.com/a/A5zY2G1
I think this is related to how the mergeEven is getting handled when it returns a null(?) but I could be totally wrong and will file this as a new bug if needed.

**Comment by radfast** [comment]
Thanks for the report!

Both things should be fixed next build 175.

(Also changed the message "Not enough power" in Circuit Fabricator GUI back to the intended shorter form "No Power" for reasons of space.)
