### ISSUE TITLE
[SereneSeasons] CoreMod conflict [1.12.2]

### ISSUE THREAD

**Issue by Dominance** [micdoodle8/Galacticraft#3355]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 1.7.4

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? 

Galacticraft add-ons and other mods installed? SereneSeasons

Please provide screenshots / crash report / log as needed.

https://pastebin.com/CAzfxzHY
https://pastebin.com/FqfjMSuN

also reported here https://github.com/Glitchfiend/SereneSeasons/issues/27

**Comment by TheQuadShot** [comment]
I'm not sure why this is filed here, Galacticraft isn't on the stack of either log files. 
One reports: Caught exception from Better With Mods (betterwithmods)
The other is: Caught exception from ContentTweaker (contenttweaker)

**Comment by radfast** [comment]
You seem to be using a **developer** version of Better With Mods.

You're welcome.

**Comment by Dominance** [comment]
Come now, I've never once reported a bad issue. Not using a Dev build of BWM but that doesn't even matter as it's clearly not a bwm issue. It's easy enough to test this out. You both are ASMing the same thing and the first mod in alphabetical order that uses what ever that is makes it crash.

**Comment by radfast** [comment]
OK you're totally right.  Sorry, was not clear from the initial post.

https://github.com/Glitchfiend/SereneSeasons/blob/master/src/main/java/sereneseasons/asm/transformer/EntityRendererTransformer.java

We are both transforming `EntityRenderer.addRainParticles()`.  Probably one of the transformers is crashing, but it's not shown in your crash reports **which** one is crashing.

**Comment by radfast** [comment]
@Dominance if you roll back Galacticraft to version 4.0.1.172 that should give you a temporary solution to this problem, as we only added rain particles to 4.0.1.173+.

A permanent solution is going to depend on co-operation from the SereneSeasons dev team.

**Comment by Dominance** [comment]
Ok thanks bro. Hope they get this in forge for you all.

**Comment by radfast** [comment]
The problem is fixed, testing SereneSeasons-1.12.2-1.1.5 with latest Galacticraft 4.0.1.176. :)
