### ISSUE TITLE
Galacticraft won't load, Help?

### ISSUE THREAD

**Issue by Showoff2500** [micdoodle8/Galacticraft#3359]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version:1.12.2
Galacticraft version:4

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? Singleplayer

Galacticraft add-ons and other mods installed? no

Please provide screenshots / c
![snip](https://user-images.githubusercontent.com/38637538/39101998-3037aa2e-465d-11e8-8cbb-47a0d20add5f.PNG)
crash report / log as needed.

**Comment by TheQuadShot** [comment]
install forge, you won't be able to load any mod (that I know of) without it

**Comment by MJRLegends** [comment]
Haha

**Comment by radfast** [comment]
You need to **run** the Forge installer - double click on it!!

https://wiki.micdoodle8.com/wiki/Tutorials/Galacticraft_Installation_Guide#Installing_Forge_on_Windows

See also higher up on that page: https://wiki.micdoodle8.com/wiki/Tutorials/Galacticraft_Installation_Guide#Installation_Guide

(the screenshot is a bit out of date but should still give you the right pointers ...)
