### ISSUE TITLE
Crash after placing Adv Solar Panel

### ISSUE THREAD

**Issue by kpoe112** [micdoodle8/Galacticraft#3363]
Minecraft version: 1.12.2
Galacticraft version: 4.0.1.121

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Just playing in the single player client. Not open to LAN.

Galacticraft add-ons and other mods installed?
Yes. Nothing other than Galacticraft/mcdoodle8 loaded.

I was playing Galacticraft just fine for a while. I went to place my first Advanced Solar Panel and Minecraft became unresponsive. Closed it and tried to open up my saved game. Crashed. Now every time I try to open the saved game, It crashes. Below is the crash report. Not sure what happened or why. I just want to continue my game. Hoping it can be saved. 

Crash Report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 4/25/18 3:53 PM
Description: Ticking block entity

java.lang.NoClassDefFoundError: micdoodle8/mods/galacticraft/planets/venus/dimension/WorldProviderVenus
	at micdoodle8.mods.galacticraft.core.tile.TileEntitySolar.func_73660_a(TileEntitySolar.java:190)
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: micdoodle8.mods.galacticraft.planets.venus.dimension.WorldProviderVenus
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at micdoodle8.mods.galacticraft.core.tile.TileEntitySolar.func_73660_a(TileEntitySolar.java:190)

-- Block entity being ticked --
Details:
	Name: minecraft:gc solar panel // micdoodle8.mods.galacticraft.core.tile.TileEntitySolar
	Block type: ID #289 (tile.solar // micdoodle8.mods.galacticraft.core.blocks.BlockSolar)
	Block data value: 4 / 0x4 / 0b0100
	Block location: World: (284,75,217), Chunk: (at 12,4,9 in 17,13; contains blocks 272,0,208 to 287,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #289 (tile.solar // micdoodle8.mods.galacticraft.core.blocks.BlockSolar)
	Actual block data value: 4 / 0x4 / 0b0100
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Time
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 3560141
	Level generator: ID 02 - largeBiomes, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (243,64,192), Chunk: (at 3,4,0 in 15,12; contains blocks 240,0,192 to 255,255,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 807075 game time, 918616 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 70580 (now: false), thunder time: 49835 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 560617824 bytes (534 MB) / 1124073472 bytes (1072 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 99
	FML: MCP 9.42 Powered by Forge 14.23.2.2641 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID               | Version      | Source                        | Signature                                |
	|:--------- |:---------------- |:------------ |:----------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft        | 1.12.2       | minecraft.jar                 | None                                     |
	| UCHIJAAAA | mcp              | 9.42         | minecraft.jar                 | None                                     |
	| UCHIJAAAA | FML              | 8.0.99.99    | forge-1.12.2-14.23.2.2641.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge            | 14.23.2.2641 | forge-1.12.2-14.23.2.2641.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | micdoodlecore    |              | minecraft.jar                 | None                                     |
	| UCHIJAAAA | galacticraftcore | 4.0.1.121    | Galacticraft-Mod-1.12.2.jar   | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by MJRLegends** [comment]
I'd strongly recommend adding jar signing as its a easy way to tell if they have compiled it themselves or downloaded a unofficial version. ExtraPlanets uses it for MC 1.8 to 1.12.2 versions @radfast

**Comment by kpoe112** [comment]
This is where I found it:
http://www.9minecraft.net/galacticraft-mod/

 Thanks. I'll get the legit one now.

**Comment by RockyWafflez** [comment]
@kpoe112 I had the exact same problem, Minecraft stopped responding when I tried to place the advanced solar panel from Galacticraft Core so I closed it and when I tried loading that world it kept crashing..... So I was wondering if downloading the legit one solved the problem or not?

**Comment by TheQuadShot** [comment]
@RockyWafflez 
Regardless, you should download Valid files from here: https://micdoodle8.com/mods/galacticraft/downloads
The answer is maybe?? If you need more help please post this in the support thread at the Forums Page here: https://forum.micdoodle8.com/index.php
Provide crash logs, and logs on pastebin/hastebin... and provide a link to them, as there  MAY be a way to fix your world, but no guarantees though. Thanks

**Comment by RockyWafflez** [comment]
@TheQuadShot Thankyou, I did it and it fixed the problem and my world is fine.. yay
