### ISSUE TITLE
Extra GT compat code that is not needed

### ISSUE THREAD

**Issue by SuperCoder7979** [micdoodle8/Galacticraft#3365]
Minecraft version: 1.12.2
Galacticraft version: latest

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? SSP

Galacticraft add-ons and other mods installed? GregTech Communithy Edition

the code here: https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/util/CompatibilityManager.java#L66-L82 is for old GregTech and should be removed. This causes a crash with the latest version of GregTech Community Edition for 1.12.2.

**Comment by MJRLegends** [comment]
Please post the crash log for the crash your having so the developers can fix the compact if its still needed

**Comment by SuperCoder7979** [comment]
https://gist.githubusercontent.com/Zer0Lyfe/4ad771ba09fd15f66d8cd0869261e0a6/raw/94b442ee97d4ce3e4e1d080bb590aaf9ca76fbf6/Latest.log this is the error log. https://github.com/GregTechCE/GregTech if you are interested

**Comment by radfast** [comment]
Thanks, I'll take a look.

Do you know **which exact** GT versions no longer need this - e.g. is it all recent GT, or only 1.12.2 versions, or only after a certain update?  Is there a way I can tell from mod name or classes present which version of GT is loaded?

**Comment by SuperCoder7979** [comment]
GT 1.12.2+ does not need this. to differenciate between versions, `gregtech.GregTechMod` is GT 1.12.2's mod class, while `gregtech.GT_Mod` is gregtech 1.7.10's mod class. if you need to find GT 6 for 1.7.10, `gregtech.GT_Proxy` exists for that version exclusively.

**Comment by radfast** [comment]
I'm really asking about **1.8.9**  **1.10.2** and **1.11.2**.   We use the same codebase for all these versions in Galacticraft, ideally I want all of these to be compatible with GregTech.

Please understand that while we want to support GregTech fully, I've never played the mod myself and I don't know the difference between all the different versions, so I am relying on your info here :)

**Comment by SuperCoder7979** [comment]
Ah, now I understand. GregTech doesn't exist for 1.8.9 or 1.11.2. 1.10.2 has an alpha but it is not supported because of brokenness, so it can be ruled out. So, effectively, GregTech only exists for 1.12.2 and 1.7.10, counting only supported versions ;)

**Comment by radfast** [comment]
OK that makes things easier :)

Fixed in our next build 175.  If any more GT compatibility issues emerge please do let me know - like I say, we want to give full support to GregTech because seems like scientific/engineering minded players might want to play both mods together.

**Comment by SuperCoder7979** [comment]
Alright, thank you! :D
