### ISSUE TITLE
crash: [1.10.2 /4.0.1.174)  java.lang.NullPointerException: Ticking entity while astrominer was mining in an Abandoned Base

### ISSUE THREAD

**Issue by 7eggert** [micdoodle8/Galacticraft#3366]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: Minecraft Version: 1.10.2
Galacticraft version: galacticraftplanets{4.0.1.174}
extraplanets{1.10.2-1.0.5}

Single player (SSP)

I did search for corresponding issues using the keywords "is:issue Ticking entity Miner" or "... astrominer"; also for  "is:issue NullPointerException".
[crash-2018-04-27_04.10.17-server.txt](https://github.com/micdoodle8/Galacticraft/files/1953641/crash-2018-04-27_04.10.17-server.txt)

**Comment by radfast** [comment]
Thank you, we'll investigate.

**Comment by radfast** [comment]
I don't know which block is causing this, could be a block from another mod.

Next version 175 will not crash here.  It will instead add a log line like this:

     AstroMiner was unable to mine anything from: tile.weirdblock.name

If you spot that in your logs after build 175, I'd be interested to know which block it is...
