### ISSUE TITLE
How to run dev verison of Galacticraft

### ISSUE THREAD

**Issue by jordanwilliams1** [micdoodle8/Galacticraft#3367]
Tried to run the latest dev build of Galacticraft with latest verison of forge but it crashes on load? What forge verison do i need? I've tried alot...

Here's my crash log.
https://pastebin.com/raw/8uPdxADH
The dev build i used: #174
https://ci.micdoodle8.com/job/Galacticraft-1.12-dev/

**Comment by MJRLegends** [comment]
The dev builds are for deof environments, please use the normal builds they contain the same changes

**Comment by radfast** [comment]
@jordanwilliams1  how did you come to https://ci.micdoodle8.com/job/Galacticraft-1.12-dev/ ?
