### ISSUE TITLE
Unable to exit Space Map launch screen

### ISSUE THREAD

**Issue by thelapisfox** [micdoodle8/Galacticraft#3368]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 4.0.1.170

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? SSP

Galacticraft add-ons and other mods installed? Playing Version 3.3.1.2 Modern Skyblock 3 mod pack.

Please provide screenshots / crash report / log as needed.
I am completely unable to continue my game. I will most likely have to restore a backup to get out of this issue. I launched in a tier 1 rocket from a space station in overworld orbit and was presented with the screen in the screenshot. I only have access to stars and I am unable to launch to any of them. I am also unable to exit this screen in any way, shape, or form. Restarting MC returns me to this same screen. Not sure what is going on here, but, I would like to know how to either a) avoid this from happening again, or b) exit it.

![gc issue](https://user-images.githubusercontent.com/899111/39398637-78e7a2bc-4ac5-11e8-9815-280ba2fa3391.jpg)

**Comment by TheQuadShot** [comment]
Just so I understand, your trying to "shoehorn" in GC on a skyblock map? In any case you should be able to hit the esc key. I'll try to repo this but I can't find this modpack on 1.12.2,  it's only on 1.10.2. Did  you download GC from: https://micdoodle8.com/mods/galacticraft/downloads

**Comment by thelapisfox** [comment]
Got the 1.12.2 mod pack off the Twitch/Curse downloader. Going to each planet in GC is part of the packs quests. It was fine going to the moon, but once I made a station and tried to lift off from it, the issue occurred,

**Comment by wamc2017** [comment]
Maybe that's the same issue: https://github.com/MJRLegends/Planet-Progression/issues/21

**Comment by thelapisfox** [comment]
Yup, that is the same issue. I guess I will add to that discussion so they know it is happening to others, or at least to me.

**Comment by MJRLegends** [comment]
@thelapisfox please close this as its not a GC issue
