### ISSUE TITLE
Galacticraft lamp crash while using Chisel as texture

### ISSUE THREAD

**Issue by mcdodge34** [micdoodle8/Galacticraft#3371]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 1.12.2.4.0.1.174

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? SMP didn't test in single player but I'm sure its the same

Galacticraft add-ons and other mods installed? Extra Planets, Planet Progression, I'M playing Modern Skyblock 3 latest version 3.3.1.4

Please provide screenshots / crash report / log as needed.

The game client crash when I try to mine your galacticraft lamps that imitate a chiseled block texture, here's the crash report, the server seems to be unaffected, its only when we try to mine them to place them somewhere else.

https://pastebin.com/WVmjj9dM

**Comment by radfast** [comment]
Thanks, this should be fixed in 175.

**Comment by mcdodge34** [comment]
Great news
