### ISSUE TITLE
ingotDesh missing from oredict (as seen from enderio)

### ISSUE THREAD

**Issue by 7eggert** [micdoodle8/Galacticraft#3373]
Minecraft / Galacticraft version:
Galacticraft-*-1.10.2-4.0.1.174.jar
ExtraPlanets-1.10.2-1.0.5.jar
EnderIO-1.10.2-3.1.183.jar

Single player (SSP)

When I export the oredict, it does not contain ingotDesh, nor when I import a recipe to generate oredict:ingotDesh (from dash armor or tools), that does not work. JEI does show ingotDesh as the oredict value though.

Example from an enderio recipe I try to import:

        <recipe name="auto sag Desh Boots" energyCost="2000"  bonusType="chance_only">
                <input>
                        <itemStack modID="galacticraftplanets" itemName="desh_boots" number="1" />
                </input>
                <output>
                        <itemStack oreDictionary="ingotDesh" number="3" chance="1" exp="0" />
                        <itemStack oreDictionary="ingotDesh" number="1" chance="0.5" exp="0" />
                </output>
        </recipe>

(I know that it's possible to use mod:name:damage)

**Comment by micdoodle8** [comment]
Should be fixed at this point, as I'm using "oreDesh" in the 1.12.2 recipes.
