### ISSUE TITLE
Coal to Diamonds

### ISSUE THREAD

**Issue by GhostFire90** [micdoodle8/Galacticraft#3376]
So as the title states I wish to turn coal into diamonds! The reason I put this here is that, a. This recipe was in a galacticraft compressor and b. I have no other leads! this was the recipe. x= coal U=fuel O= blank
xx0
xx0 = Diamond!
000
   U 
I cant find the mod that the person who was making the space race video so maybe one of you guys could?
it was IBalistic Squids! Much Apreciated

**Comment by radfast** [comment]
This is not a bug report.

You can try asking your question at the [forum](https://forum.micdoodle8.com/index.php?forums/general.12/)
