### ISSUE TITLE
Game crash with Extended Days mod on Space Station

### ISSUE THREAD

**Issue by QuantumStatement** [micdoodle8/Galacticraft#3379]
Minecraft version: 1.11.2
Galacticraft version: 4.0.1.174

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP

Galacticraft add-ons and other mods installed?
[Extended Days](https://minecraft.curseforge.com/projects/extended-days) 0.2.3-16

Please provide screenshots / crash report / log as needed.
[Crash Report](https://github.com/micdoodle8/Galacticraft/files/1960407/crash-2018-04-29_12.44.08-client.txt)

Game crashes when player arrived on Space Station

**Comment by radfast** [comment]
Can you config Extended Days mod to disable itself in some dimensions?

Did you report this to them as well?  It's not clear that this is our code crashing.

**Comment by QuantumStatement** [comment]
> Can you config Extended Days mod to disable itself in some dimensions?

No

**Comment by radfast** [comment]
Try this Extended Days config:

     Override Sky Rendering: false

Extended Days is changing the `SkyRenderer` in our dimension, where our own custom `WorldProvider` class specifies our `SkyRenderer`.  I don't think another mod should be doing that, so I'm going to flag this "Not a Galacticraft Issue", meaning its for Extended Days to fix it.  Meanwhile you can use that config to prevent the crash.
