### ISSUE TITLE
Sun moves backwards on Space Station after using the Cryogenic Chamber

### ISSUE THREAD

**Issue by QuantumStatement** [micdoodle8/Galacticraft#3380]
Minecraft version: 1.11.2
Galacticraft version: 4.0.1.174

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
LAN

Galacticraft add-ons and other mods installed?
IndustrialCraft 2 2.7.86-ex111
[Server.Properties for LAN](https://minecraft.curseforge.com/projects/server-properties-for-lan) 2.65

Sun start to move backwards (from west to east) on Space Station after player using the Cryogenic Chamber. After world restart Sun moves normally, but day count on Space Station resets to 0

**Comment by radfast** [comment]
oh noes!  I though we had all the Cryogenic Chamber problems properly fixed.

**Comment by TheQuadShot** [comment]
Well that should teach you to jump to the left followed by a step to the right...


Lets do the time warp again! Rocky Horror Picture Show

**Comment by radfast** [comment]
lol

**Comment by Pineatron** [comment]
I have this problem on Mars also. I went to sleep as the sun was setting and woke up during the morning. The sun was up in the air. And then monsters start spawning like it was the night. I check f3 and the light levels look right. So I wait until night. At night time nothing spawns. The whole night. And the sun was moving backward also during the daytime. I reloaded the world and then the monsters started despawning.

**Comment by randomei** [comment]
Same problem on Mars. Everything like Pineatron described.

**Comment by OriginalYshl** [comment]
Bump/same issue. It's not specific to any location, it makes the sun move the wrong way and mob spawning/light cycles seem to be disconnected on multiple worlds.

Of note, the sun doesn't just move the wrong way, it seems really ... chunky ... when it does. Instead of moving smoothly, the sun and stars go the wrong way like it's ticking like a clock.  Anyone have any ideas? What was the issue / fix in the past?

**Comment by tjaccardi** [comment]
Can confirm am also having chunky movement on Mars after the servers been up and people have used beds. It's kinda odd looking and makes it hard to admire the otherwise awesome looking skybox.
