### ISSUE TITLE
Moon villages sometimes generates without wells

### ISSUE THREAD

**Issue by QuantumStatement** [micdoodle8/Galacticraft#3382]
Minecraft version: 1.11.2
Galacticraft version: 4.0.1.175

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP

Galacticraft add-ons and other mods installed?
None

Please provide screenshots / crash report / log as needed.
![2018-04-30_18 08 36](https://user-images.githubusercontent.com/35406698/39437052-6a8df538-4ca8-11e8-8923-5ac0ce2509a7.png)

I don't know it's intended or not, but sometimes Moon villages generates without wells

**Comment by EzerArch** [comment]
Not intended if the spot is there, empty.
