### ISSUE TITLE
Water disappears when getting into Rowboat with Betweenlands installed

### ISSUE THREAD

**Issue by TheQKnight** [micdoodle8/Galacticraft#3385]
Minecraft version: 1.12.2
Galacticraft version: any - 175

Affects Single player and Multiplayer

Galacticraft and the Betweenlands mod installed

When you get inside a Rowboat from the Betweenlands mod, the water disappears. This only happens when Galacticraft is installed.

![2018-04-30_11 54 57](https://user-images.githubusercontent.com/17223871/39444833-dd720f2a-4c6d-11e8-9324-453fce35233e.png)
![2018-04-30_11 54 53](https://user-images.githubusercontent.com/17223871/39444846-e814a2b2-4c6d-11e8-8595-a0096e123225.png)

**Comment by TheQuadShot** [comment]
I'm not seeing this:
Minecraft 1.12.2
forge .2677
MicdoodleCore-1.12.2-4.0.1.175
Galacticraft-Planets-1.12.2-4.0.1.175
GalacticraftCore-1.12.2-4.0.1.175
TheBetweenLands 3.3.8 universal
https://imgur.com/a/8cEFXO8

What other mods are you running?

**Comment by radfast** [comment]
Thank you for testing @TheQuadShot  :)
I think it might be time for a new skin for you :p

**Comment by TheQuadShot** [comment]
lol, I never pay attention to my skin, I think it was one of my kids or grandkids joking around with me, and I just go with it, makes them happy grandpa doesn't know anything.

**Comment by TheQKnight** [comment]
No, it has to be the Betweenlands rowboat

**Comment by TheQKnight** [comment]
Don't be so quick to throw an issue away. I've been testing this since yesterday.

**Comment by radfast** [comment]
More specific information about your tests please @TheQKnight   Why are you saying this is Galacticraft?

Please list your other mods as requested.

Please explain the different setup for the two screenshots you posted in the first post.

**Comment by TheQKnight** [comment]
Like I said at the top, the Rowboat FROM Betweenlands only causes water to disappear when Galacticraft is installed.

**Comment by TheQKnight** [comment]
those 2 are the only mods

**Comment by radfast** [comment]
>  Please explain the different setup for the two screenshots you posted in the first post.

**Comment by radfast** [comment]
I am also not able to reproduce this, tested using the latest Galacticraft build 175.
![2018-05-01_00 56 51](https://user-images.githubusercontent.com/6842258/39455974-4b90e496-4cdb-11e8-87dd-4abde6c4752e.png)

Are you sure you have you tested it with **ONLY** Galacticraft and BetweenLands installed, no other mods at all?

**Comment by radfast** [comment]
OK I've tested this.
The problem exists in **The BetweenLands** version 3.3.8 but not in their version 3.3.0.

Therefore it is something they have changed between those two versions.  It's not a Galacticraft issue.  Please report it to The Betweenlands, you can reference this thread if you want to show them my comments.

It is possibly connected with them replacing the [player renderer](https://github.com/Angry-Pixel/The-Betweenlands/blob/1.12/src/main/java/thebetweenlands/client/render/entity/RenderPlayerRower.java) when the player is in a boat.   We also have a player renderer which is running all the time, but the game is happily switching between these two renderers in The Betweenlands version 3.3.0.

**Comment by TheQKnight** [comment]
1. Place a Betweenlands Weedwood boat in the water in the overworld.
2. Right click it.

**Comment by TheQKnight** [comment]
I contacted one of the authors before and they said it was Galacticraft's fault, so I came here. Now what am I to do?

**Comment by TheQKnight** [comment]
They told me it was some GC Player thing.

**Comment by radfast** [comment]
See also https://github.com/Angry-Pixel/The-Betweenlands/issues/568
They have this problem with another mod, **SevTech**, so it's not only with Galacticraft.

**You should have noticed this in their issues list, instead of wasting our time here.**

I think the rest is up to The Betweenlands dev team now.  They should be able to do something with my pointers that it's a problem introduced between their 3.3.0 and 3.3.1.

>  They told me it was some GC Player thing.

That suggest to me that they have not bothered checking properly.
