### ISSUE TITLE
[Sevtech] Planet UI is partially broken, and concerning error in console about conflicting dimension IDs

### ISSUE THREAD

**Issue by justinrusso** [micdoodle8/Galacticraft#3388]
I've generated with a fresh config for extra planets and it is still an issue. It seems to only be happening with Extra Planets planets as well, but Ive disabled both features that modify the map that MJR suggested I disable.

See https://github.com/MJRLegends/ExtraPlanets/issues/297

Minecraft version: 1.12.2
Galacticraft version: .175

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Singleplayer

Galacticraft add-ons and other mods installed?
Extra Planets 0.3.5

Please provide screenshots / crash report / log as needed.
https://gist.github.com/justinrusso/33614fd4c0bec8fcdadc49a67856dbb2 Please see the raw file. The error is at the very end.

**Comment by justinrusso** [comment]
I’ve regenerated the mods config and it still does not work... as ive stated.

**Comment by radfast** [comment]
@justinrusso  we have been thinking about adding a check for dimension conflicts at game start, with a more helpful error message to tell you which ones need fixing (or maybe just auto-disable them so you can still play).

If you make a copy of your currently erroring setup (copy all mods and configs), it could be great if you help us test the new conflict check - even if you get things working meanwhile.  New version might be ready for testing on Sunday, maybe.

**Comment by justinrusso** [comment]
Yeah this is indeed an issue of Extra Planets. I apologize for the invalid report.

**Comment by radfast** [comment]
@MJRLegends  if you can point me to the exact code that is going wrong, I'm happy to add more `try/catch` or arraylist size checking etc.

**Comment by MJRLegends** [comment]
@radfast thanks for your help but it seems its a contained issue in the sense its only happening for the sevtech mod pack dev team and im unable to reproduce the issue myself after doing many tests myself outside and inside of the dev workspace.

**Comment by radfast** [comment]
It's a shame that (most) modpack compilers don't come directly to the mods if they discover any issues ... never really understood why they don't.  You'd think the first thing a good modpack would want to do is resolve the issues or identify the issues which can't be resolved.

**Comment by justinrusso** [comment]
Excuse me?

**Comment by radfast** [comment]
@justinrusso  you are the maker of Sevtech?  You should have said, I did not know this.

**Comment by radfast** [comment]
So what are we doing here guys?  @MJRLegends saying he can't reproduce the issue.  I need some more pointers for that the issue is, or somebody needs to give me the broken configs for [Galacticraft + 1 other mod] which causes the problem.  I can't troubleshoot a full modpack, might need to load the other mod inside my development environment.

**Comment by justinrusso** [comment]
#### Description:
This is now fully reproducible in my opinion. I've guided another pack dev through this and he was able to do it now, but was unable to until I gave him steps. It fully appears to be a UI bug and minor overall - at least in comparison to what the error output states about dimension IDs changing.

---
#### Steps To Reproduce:
1. Open the map (M)
2. Click on Neptune
3. Click on a blank area
4. Click on Saturn
5. Click on blank area
6. Click on Neptune

This is how I did it, but I've been able to replicate it on other planets using a similar method of clicking on it, then to another planet, then back. This includes the Overworld in planets that bug out.

---
#### Versions:
**Forge:** 14.23.3.2678
**Galacticraft:** 4.0.1.175
**MJRLegendsLib:** 1.1.3

**Comment by justinrusso** [comment]
Yes, and I just verified again. It still errors

```
B:"Custom Galaxies on Celestaial Selection Screen"=false
B:"Use Custom Galaxy Map/Celestaial Selection Screen"=false
```

**Comment by radfast** [comment]
OK thanks both.  I'll try to replicate it here.  Might be 1-2 days before there's progress.

**Comment by MJRLegends** [comment]
Btw just to bring the details fro this up to date, still no reports for ExtraPlanets or my Space Astronomy 2 pack on anyone else getting this issue.

https://www.curseforge.com/minecraft/modpacks/modern-skyblock-3-departed is now using the latest ExtraPlanets with GC 176 and so far it seems they seem to be running issue free since May 6, 2018 when they updated the pack with these versions...

i also tested with SevTech v3.0.7 and latest ExtraPlanets with GC 176, and cant seem to reproduce anything myself there too

cc @justinrusso @radfast

**Comment by justinrusso** [comment]
Multiple devs have been able to replicate this.

**Comment by radfast** [comment]
@justinrusso any more info on how exactly to replicate it?   If it only happens with Extra Planets present and @MJRLegends, the developer of Extra Planets, is not able to replicate it then it's hard to see what I can do.

**Comment by Jandakast** [comment]
Started Brand new Instance, on Forge 2688. Configs default other than;
```
B:"Custom Galaxies on Celestaial Selection Screen"=false
B:"Use Custom Galaxy Map/Celestaial Selection Screen"=false
```

Only mods installed
```
ExtraPlanets-1.12.2-0.3.6.jar
Galacticraft-Planets-1.12.2-4.0.1.176.jar
GalacticraftCore-1.12.2-4.0.1.176.jar
MicdoodleCore-1.12.2-4.0.1.176.jar
MJRLegendsLib-1.12.2-1.1.3.jar
```

1. Open map with M
2. Click on Neptune
3. Click anywhere not a planet
4. Click Saturn
5. Click anywhere not a planet
6. Click Neptune
7. See broken GUI and Error in console

![image](https://user-images.githubusercontent.com/19498789/40124084-b9d86836-58f5-11e8-880d-aa94527ddda4.png)


```
10:36:27] [main/ERROR] [Galacticraft]: Problem identifying planet or dimension in an add on for Galacticraft!
[10:36:27] [main/ERROR] [Galacticraft]: (The problem is likely caused by a dimension ID conflict.  Check configs for dimension clashes.  You can also try disabling Mars space station in configs.)
```
Full log here https://pastebin.com/Nzdt7Wbr

**Comment by radfast** [comment]
thanks, those are super helpful instructions

**Comment by MJRLegends** [comment]
There is a chance https://github.com/micdoodle8/Galacticraft/commit/7aec872bd71c3f8269eff325c22b5de7b346d029 fixed this as it sounds like thats the issue

**Comment by MJRLegends** [comment]
Nope i tried with the instructions and still cant reproduce it

But 
[```
10:36:27] [main/ERROR] [Galacticraft]: Problem identifying planet or dimension in an add on for Galacticraft!
[10:36:27] [main/ERROR] [Galacticraft]: (The problem is likely caused by a dimension ID conflict.  Check configs for dimension clashes.  You can also try disabling Mars space station in configs.)
```
isn't the real error this error is just coming from a try catch and isn't the real error.  But https://github.com/micdoodle8/Galacticraft/commit/7aec872bd71c3f8269eff325c22b5de7b346d029 might fix it

**Comment by MJRLegends** [comment]
The real error is
`micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection:func_73863_a:1228]: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1`

But idk if its due to micdoodles changes as the problem they seem to have only happened when i updated ExtraPlanets and forced players to update to 174 which includes micdoodles changes

**Comment by radfast** [comment]
>   i cant even reproduce the issue to test this.

I also cannot reproduce it, following the steps 1-7, with Galacticraft build 176.  So something else is going on here maybe?  @justinrusso @Jandakast any step missing in your steps 1-7?  It's not really possible that the error always occurs for you and never for me + MJR following the same steps, software doesn't work like that!

**One other possibility: are you Sevtech guys using a different language from English?**  It could be a language issue, as the Gui obviously does make use of the player's language settings.

Apart from that, I'm not going to guess at the cause of an error which I cannot reproduce.  Though sure, it could be worth you guys trying out a slightly older Galacticraft build before the recent changes, try 4.0.1.169 and see if that makes any difference?

**Comment by justinrusso** [comment]
I was able to replicate it on SevTech 3.0.6 when initially testing this bug. That version uses:

GC: 4.0.1.170
EP: 0.3.2

We are both using English and are able to consistently replicate this in a fresh world containing just GC, EP, and JEI.

**Comment by justinrusso** [comment]
[![https://gyazo.com/ad4939d21bd512a584d350a882486c3a](https://i.gyazo.com/ad4939d21bd512a584d350a882486c3a.gif)](https://gyazo.com/ad4939d21bd512a584d350a882486c3a)

**Comment by radfast** [comment]
OK thanks again guys, I can now reproduce the issue.  It's happening when you click the **planet icons** but not when you click the planet names in the left hand column.

Trigger conditions:
1.   Click a planet with 2 moons or more.  (examples, Saturn, Uranus, Pluto)
2.   Click a planet with at least 1 moon but fewer than 2.  (examples, Neptune, Overworld)

Click on a planet in the left hand menu "resets" the GUI so it works again.

The issue can also be reproduced for larger numbers of moons.  e.g. Jupiter (4 moons) will cause Pluto (3 moons) to bug.  Pluto (3 moons) will cause Mars and Uranus (2 moons each) to bug.

**Comment by radfast** [comment]
Fixed in next release.

Sorry it took so long to fix.  Just shows, sometimes the only way to find the bug is if I can reproduce the error myself.

**Comment by radfast** [comment]
For @micdoodle8 :  I'm also seeing an additional issue, where you click on a planet icon (e.g. Overworld), message at the bottom reads click again to zoom.  Then you click on a different planet icon (e.g. Mars) and it immediately zooms in to Mars, even on your first click on Mars.  I think the GUI needs to reset the "click again to zoom" counter if the selected planet changes.

**Comment by MJRLegends** [comment]
@radfast Woooooooo, Would be amazing if you could make a build for GC in the next 24 hours so i can get my needed ExtraPlanets changes made to match and then we can get this bug over with and fix out to the players :D

**Comment by radfast** [comment]
build 177 now available for download
