### ISSUE TITLE
Aluminum Wire Transfer Rate

### ISSUE THREAD

**Issue by FaustyTheRager** [micdoodle8/Galacticraft#3392]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 4.0.1.170

Galacticraft add-ons and other mods installed?
Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Galactricraft Tweaker, ExtraPlanets, Galacticraft Planets

Could someone please tell me what the transfer rate is for the aluminum wire and heavy aluminum wire. I can't find any updated numbers and I can't figure out how to convert the old ones from the wiki.

**Comment by radfast** [comment]
Please ask your question on the forum.  This issue tracker is for bug reports only.
