### ISSUE TITLE
Double click in Planet Catalog don't work as intended

### ISSUE THREAD

**Issue by QuantumStatement** [micdoodle8/Galacticraft#3397]
Minecraft version: 1.11.2
Galacticraft version: 4.0.1.176

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP

Galacticraft add-ons and other mods installed?
None

In earlier versions of Galacticraft (I tested 4.0.1.169) double click on planet in Planet Selection Screen catalog showed the selected planet
![planetcatalog](https://user-images.githubusercontent.com/35406698/39946914-bb767f50-5578-11e8-8b77-762d6f9f3628.png)
But in resent versions this is don't work

**Comment by micdoodle8** [comment]
Thanks, should be fixed in the next build

**Comment by radfast** [comment]
build 177 now available for download
