### ISSUE TITLE
[1.12.2][176] Crash when opening the map with FTB Utilities

### ISSUE THREAD

**Issue by Alaberti** [micdoodle8/Galacticraft#3398]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 176
Edit: FTB Utilities: 5.0.2.11

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP 

Galacticraft add-ons and other mods installed?
Extra Planets 0.3.6

Please provide screenshots / crash report / log as needed.
https://paste.dimdev.org/facexobuca.txt

**Comment by MJRLegends** [comment]
Wrong issue tracker this isnt a GC issue see https://github.com/MJRLegends/ExtraPlanets/issues/300
