### ISSUE TITLE
Rocket launch particle lag on slow computers

### ISSUE THREAD

**Issue by kouwei32** [micdoodle8/Galacticraft#3400]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version:
Galacticraft version:
See my other posts, I forgot.

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Mostly SSP, but could be SMP as well.

Galacticraft add-ons and other mods installed?
See my other posts.

This glitch happens usually on laggy computers/servers. When a rocket takes off, the large amount of particle released will cause lag on slower computers, thus making the launch countdown much longer than 20 seconds. This will cause the rocket noise to gradually fade, then spring back up to full volume again, then repeat. Definition of slow computers would be like a 2017 MacBook Air or worse (e.g. non-gaming laptops).

Please provide screenshots / crash report / log as needed.

**Comment by TheQuadShot** [comment]
This looks like it's related to https://github.com/micdoodle8/Galacticraft/issues/3383
Please take note, telling the dev team "See my other posts" is imo is unacceptable. If a developer needs the additional information they now have to search for all of your post and hope they find what they are looking for. Also, this should have been added to the other bug. I know it says launch controller, it's still a sound issue on launch that is labeled as "Can't reproduce" and "follow up please", meaning that additional information is need to track down the issue. This would constitute additional information.

**Comment by radfast** [comment]
I am aware of the particle lag issue, was seeing it even on my dev systems.
I thought we had [fixed it](https://github.com/micdoodle8/Galacticraft/commit/35f21b0537b374fd3f0926fdb9a5871e60515931)
But by the sound of it we need to do more, or provide a config option to reduce particles.

BTW if you want to donate your 2017 Macbook Air to the Galacticraft dev team for "testing" purposes, feel free ...

**Comment by Romsik788** [comment]
on my fujitsu ah512 the same problem.

**Comment by Romsik788** [comment]
On my fujitsu ah512 the same problem.

**Comment by radfast** [comment]
build 177 has made some improvement to this, I now have a stable 60fps with all rocket launches - please try this build if you didn't try it already

**Comment by kouwei32** [comment]
This was actually an old bug that was around for a long time. I just forgot to report it. I havn’t used mods for a little while (playing servers) so it may be some time until I can retest this with the new build.

P.S. radfast unfotunately I cannot “donate” my macbook since it’s my main computer, but I could make a video.

**Comment by radfast** [comment]
>  it may be some time until I can retest this with the new build.

It it's still a problem in 177 let us know and we can re-open.
