### ISSUE TITLE
Accept slimeballs from other mods (AA and TiCon) in recipes?

### ISSUE THREAD

**Issue by TheQuadShot** [micdoodle8/Galacticraft#3401]
I can't use slimeball to craft either of the 2 recipes GC has that uses them(Slimeling Storage Bag, Fluid Manipulator). I'm not sure if this is a oredict issue or not.

slimeballGreen oredicts to slimeball
slimeballPurple(TiCon) oredicts to slimeball
slimeballBlue(TiCon) oredicts to slimeball
slimeballMagma(TiCon) oredicts to slimeball
slimeball(AA rice slimeball) oredicts to slimeball

Also the Wiki show's and says slimeball, and displays the vanilla slimeballGreen. If the green is required, then I want to change the wiki accordingly (I will take care of that if/when it's needed).

**Comment by radfast** [comment]
I don't play those other mods and I'm not familiar with their slimeballs.  Are they normally considered to be "on a par" with the vanilla slimeball, the green one?

I don't see there's any actual broken compatibility here.  You are able to craft the Galacticraft recipes using the vanilla slimeball, the one dropped by Slimes, even if you have these mods installed.

**Comment by YaibaToKen** [comment]
I think what @TheQuadShot is asking is, whether it would be possible to change the recipes to use the ore dictionary entry for the slimeball. Those other slimeball equivalents can be said to have the same "difficulty" of acquisition. For example, the tinker ones are dropped by purple and blue slimes from floating slime islands in the overworld and magma slimes from slime islands in the nether :)

**Comment by radfast** [comment]
>  Those other slimeball equivalents can be said to have the same "difficulty" of acquisition.

OK thank you @YaibaToKen  that is helpful, that's what I was asking.  We can probably oredict this easily enough in that case.

**Comment by radfast** [comment]
now included in build 177
