### ISSUE TITLE
Server crash on load chunk

### ISSUE THREAD

**Issue by prokopiy** [micdoodle8/Galacticraft#3403]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version:
Galacticraft version:

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
[crash-2018-05-16_19.03.18-server.txt](https://github.com/micdoodle8/Galacticraft/files/2009909/crash-2018-05-16_19.03.18-server.txt)

Galacticraft add-ons and other mods installed?

Please provide screenshots / crash report / log as needed.

**Comment by radfast** [comment]
Why are you reporting this on the **Galacticraft** issue tracker?
The crash appears to be in another mod.  ompd?
