### ISSUE TITLE
Solar Panel Array Module

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#3404]
> EzerArch - I think the new structure asks a different kind of solar panel that isn't a multi-block nor does it have moving parts but slabs capable of transmitting energy as they were interconnected wires.

> Radfast - Make me a model + textures for it and I'll add it :)

**1st mock-up:**

![2018-05-17_01 15 42](https://user-images.githubusercontent.com/6743303/40156475-0f72f5a2-5970-11e8-9a0c-1fcb967f8136.png)

Specs (proposal):
* Name: Solar Panel Array Module
* Dimensions: ~0.25 x 1.0 x 1.0, as thick as Heavy Wire;
* Collects sunlight on both sides;
* Accepts energy wires on 4 sides, hence the wire input marks. Not up or down;
* Recipe: one that requires stronger materials as it is a freestanding structure _(edit: and gold)_. We'll think about it later.

Yes, the texture is quite flat, I'll change it later after some feedback. And if everything is okay, I'll proceed to push request.

**More pics:**
Setup idea:
![2018-05-17_01 48 58](https://user-images.githubusercontent.com/6743303/40157382-156734b4-5975-11e8-8e4a-eed94cfab93e.png)
![2018-05-17_01 47 38](https://user-images.githubusercontent.com/6743303/40157380-12eab4cc-5975-11e8-9914-1325ab2d1815.png)
(The lattice structure is from [here](https://twitter.com/EzerArch/status/970122207753134081)) 

**Reference:**
![1](https://www.nasa.gov/sites/default/files/styles/full_width_feature/public/thumbnails/image/16938569907_90b5c8a831_o.jpg)

**Comment by radfast** [comment]
Don't worry about a .JSON file for the model, that is easy for me to make, it's a cuboid to match the thickness of Heavy Aluminum Wire.

But the textures for the sides will help me greatly ...

**Comment by EzerArch** [comment]
I see Heavy Aluminum Wire model is 4.8 pixels thick ([[1]](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/resources/assets/galacticraftcore/models/block/hvy_alu_wire_n.json#L10)), while I made the side texture 8 pixels wide (using 32x32 px tile set). You can UV map the side texture to fit in the model, can't you?

I got around to making some progress:
![2018-05-19_01 46 32](https://user-images.githubusercontent.com/6743303/40265074-913eaf20-5b07-11e8-8317-f757e2ee621a.png)
I retextured daylight sensors for the test. I think the rim is too much noisy and the golden surface needs to look more glossy.

**Comment by radfast** [comment]
When you're happy with the top surface texture, post it up and I can probably do the rest from alu wire model, I'll ask you if I can't...

I think the retextured daylight sensors look closer to your photo of an actual satellite.  Glossier sounds good.

I've realised I'll need to do actually quite a lot of coding work to make these work to generate in an array.  I mean each one has to function as both generator and wire at the same time.  Also for performance reasons we might not want to check all of them each tick.  (Currently a solar panel runs a block check, each tick, to see if there is any block obstructing its view of the sun.)  Let me think about this.  Don't worry about it, I **enjoy** coding electrical systems.

**Comment by EzerArch** [comment]
Now I'm happy:

![2018-05-20_20 18 58](https://user-images.githubusercontent.com/6743303/40284847-3c5ed18c-5c6b-11e8-831b-c85c0808c310.png)

Main:
![solar_panel_array](https://user-images.githubusercontent.com/6743303/40289255-abaed22c-5c8d-11e8-944e-1402e7c14936.png)
Sides:
![solar_panel_array_side](https://user-images.githubusercontent.com/6743303/40289256-ac3b2830-5c8d-11e8-8779-8bb82aec76cc.png)

I tried to mimic the ISS panels but also made a texture that is symmetrical in both axes so players wouldn't want to rotate it, and that looks good no matter the arrangement.

> I mean each one has to function as both generator and wire at the same time. Also for performance reasons we might not want to check all of them each tick.

I was thinking about a different method. Instead of making every block (module) in the array to collect and transmit energy:
* The modules only check if their view of the sun is obstructed.
* Each array should have an "Energy Collector" block to make a bridge between the array and an energy wire.
* The Energy Collector would count how many unobstructed modules are in the array, pretty much like the "Oxygen Collector" that counts how many leaf blocks are in a range and converts it to oxygen points.
* In result of the above, the array can be thinner, except only the Energy Collector needs to be as thick as the connecting wire.

**Comment by 7eggert** [comment]
Enderio does create a single solar panel by putting them next to each other. That seems to work quite well, I've got IIRC four stacks of them in a noon dimension, creating four panels.

**Comment by TheQuadShot** [comment]
Will it be a multiblock or just an array of a set size? I prefer the multilblock approach, so I would have "raw" panels and a collector module to attach/bridge/connect my wires to.

**Comment by micdoodle8** [comment]
Beautiful. Thank you @EzerArch ! I've implemented the solar arrays as of the latest build.

**Comment by EzerArch** [comment]
HOW DARE YOU WAKE ME UP FROM MY REST.... wait?! Oh look, you real MVP. :heart_eyes:

**Comment by Labiq** [comment]
I can't make solardust!

**Comment by dj3520** [comment]
@Labiq Your issue is not related to this topic or this mod.

**Comment by ayan311** [comment]
But i can neither see the recipe nor create the solar arrey module
