### ISSUE TITLE
Sealer stuck at "Check Starting"

### ISSUE THREAD

**Issue by Pwnsaucier** [micdoodle8/Galacticraft#341]
Version: 1.6.4-2.0.12.1010
Forge 965

Oxygen sealer gets stuck at "Check Starting"

What I see in game: http://i.imgur.com/RrsCYo7.jpg

And in the log:

 [B#439]  2014-04-17 13:02:21 [INFO] [STDERR] Exception in thread "GC Sealer Roomfinder Thread" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[B#439]  2014-04-17 13:02:21 [INFO] [STDERR]    at java.util.ArrayList.rangeCheck(Unknown Source)
[B#439]  2014-04-17 13:02:21 [INFO] [STDERR]    at java.util.ArrayList.get(Unknown Source)
[B#439]  2014-04-17 13:02:21 [INFO] [STDERR]    at micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.run(ThreadFindSeal.java:186)
[B#439]  2014-04-17 13:03:19 [INFO] [STDERR] Exception in thread "GC Sealer Roomfinder Thread" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[B#439]  2014-04-17 13:03:19 [INFO] [STDERR]    at java.util.ArrayList.rangeCheck(Unknown Source)
[B#439]  2014-04-17 13:03:19 [INFO] [STDERR]    at java.util.ArrayList.get(Unknown Source)
[B#439]  2014-04-17 13:03:19 [INFO] [STDERR]    at micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.run(ThreadFindSeal.java:186)
[B#439]  2014-04-17 13:03:19 [INFO] [STDERR] Exception in thread "GC Sealer Roomfinder Thread" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[B#439]  2014-04-17 13:03:19 [INFO] [STDERR]    at java.util.ArrayList.rangeCheck(Unknown Source)
[B#439]  2014-04-17 13:03:19 [INFO] [STDERR]    at java.util.ArrayList.get(Unknown Source)
[B#439]  2014-04-17 13:03:19 [INFO] [STDERR]    at micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.run(ThreadFindSeal.java:186)
[B#439]  2014-04-17 13:03:19 [INFO] [STDERR] Exception in thread "GC Sealer Roomfinder Thread" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[B#439]  2014-04-17 13:03:19 [INFO] [STDERR]    at java.util.ArrayList.rangeCheck(Unknown Source)
[B#439]  2014-04-17 13:03:19 [INFO] [STDERR]    at java.util.ArrayList.get(Unknown Source)
[B#439]  2014-04-17 13:03:19 [INFO] [STDERR]    at micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.run(ThreadFindSeal.java:186)
[B#439]  2014-04-17 13:03:19 [INFO] [STDERR] Exception in thread "GC Sealer Roomfinder Thread" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[B#439]  2014-04-17 13:03:19 [INFO] [STDERR]    at java.util.ArrayList.rangeCheck(Unknown Source)
[B#439]  2014-04-17 13:03:19 [INFO] [STDERR]    at java.util.ArrayList.get(Unknown Source)
[B#439]  2014-04-17 13:03:19 [INFO] [STDERR]    at micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.run(ThreadFindSeal.java:186)
[B#439]  2014-04-17 13:03:19 [INFO] [STDERR] Exception in thread "GC Sealer Roomfinder Thread" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[B#439]  2014-04-17 13:03:19 [INFO] [STDERR]    at java.util.ArrayList.rangeCheck(Unknown Source)
[B#439]  2014-04-17 13:03:19 [INFO] [STDERR]    at java.util.ArrayList.get(Unknown Source)
[B#439]  2014-04-17 13:03:19 [INFO] [STDERR]    at micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.run(ThreadFindSeal.java:186)

**Comment by Reputationgamer** [comment]
im having the same problem, my sealer worked fine until now, when its stuck on check starting
