### ISSUE TITLE
Website translating Discussion

### ISSUE THREAD

**Issue by ETStareak** [micdoodle8/Galacticraft#3411]
Sorry to begin this work too late,but the translation for AetherII is really a big deal.I think I will do the translation this evening.

**Comment by radfast** [comment]
Only @micdoodle8 can fix this.

For now, please try a different browser.  Just now I successfully downloaded Galacticraft 177 using **Firefox**.

**Comment by radfast** [comment]
Also:

*   try switching off any AdBlocker you have running

*  try waiting on that page for minimum 15 seconds, maybe you did not give it enough time

**Comment by Romsik788** [comment]
If you can not download it, then try downloading from here https://ci.micdoodle8.com/job/Galacticraft-1.12/
