### ISSUE TITLE
Constant crash on attempting to delete Galacticraft from mods

### ISSUE THREAD

**Issue by sfantah** [micdoodle8/Galacticraft#3412]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 4.0.1.174

Single player (SSP)

Galacticraft add-ons and other mods installed= yes

Please provide screenshots / crash report / log as needed.
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-81.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.20.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 5/20/18 7:30 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thermal Expansion (thermalexpansion)
Caused by: java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at net.minecraft.util.NonNullList.get(SourceFile:44)
	at net.minecraft.item.crafting.ShapedRecipes.func_77573_a(ShapedRecipes.java:109)
	at net.minecraft.item.crafting.ShapedRecipes.func_77569_a(ShapedRecipes.java:80)
	at net.minecraft.item.crafting.CraftingManager.func_82787_a(CraftingManager.java:199)
	at cofh.core.util.helpers.ItemHelper.getCraftingResult(ItemHelper.java:271)
	at cofh.thermalexpansion.util.managers.machine.SawmillManager.addAllLogs(SawmillManager.java:285)
	at cofh.thermalexpansion.util.managers.machine.SawmillManager.loadRecipes(SawmillManager.java:198)
	at cofh.thermalexpansion.util.managers.machine.SawmillManager.initialize(SawmillManager.java:193)
	at cofh.thermalexpansion.ThermalExpansion.managerInitialize(ThermalExpansion.java:143)
	at cofh.thermalexpansion.ThermalExpansion.handleIMC(ThermalExpansion.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:280)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:258)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:379)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:758)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:352)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1365382248 bytes (1302 MB) / 3992977408 bytes (3808 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.3.2678 Optifine OptiFine_1.12.2_HD_U_D2 97 mods loaded, 97 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                         | Version                      | Source                                            | Signature                                |
	|:----- |:-------------------------- |:---------------------------- |:------------------------------------------------- |:---------------------------------------- |
	| UCHIJ | minecraft                  | 1.12.2                       | minecraft.jar                                     | None                                     |
	| UCHIJ | mcp                        | 9.42                         | minecraft.jar                                     | None                                     |
	| UCHIJ | FML                        | 8.0.99.99                    | forge-1.12.2-14.23.3.2678.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ | forge                      | 14.23.3.2678                 | forge-1.12.2-14.23.3.2678.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ | ic2                        | 2.8.74-ex112                 | industrialcraft-2-2.8.74-ex112.jar                | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJ | advanced_solar_panels      | 4.2.0                        | Advanced+Solar+Panels-4.2.0.jar                   | None                                     |
	| UCHIJ | appliedenergistics2        | rv5-stable-11                | appliedenergistics2-rv5-stable-11.jar             | None                                     |
	| UCHIJ | bdlib                      | 1.14.3.12                    | bdlib-1.14.3.12-mc1.12.2.jar                      | None                                     |
	| UCHIJ | ae2stuff                   | 0.7.0.4                      | ae2stuff-0.7.0.4-mc1.12.2.jar                     | None                                     |
	| UCHIJ | applecore                  | 3.1.1                        | AppleCore-mc1.12.2-3.1.1.jar                      | None                                     |
	| UCHIJ | backpack                   | 3.0.1                        | Backpacks-Mod-1.12.2 (1).jar                      | None                                     |
	| UCHIJ | jei                        | 4.9.1.168                    | jei_1.12.2-4.9.1.168.jar                          | None                                     |
	| UCHIJ | base                       | 3.7.1                        | base-1.12.2-3.7.1.jar                             | None                                     |
	| UCHIJ | baubles                    | 1.5.2                        | Baubles-1.12-1.5.2.jar                            | None                                     |
	| UCHIJ | bookshelf                  | 2.3.544                      | Bookshelf-1.12.2-2.3.544.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJ | codechickenlib             | 3.1.6.339                    | CodeChickenLib-1.12.2-3.1.6.339-universal (1).jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJ | redstoneflux               | 2.0.1                        | RedstoneFlux-1.12-2.0.1.2-universal.jar           | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJ | brandonscore               | 2.4.0                        | BrandonsCore-1.12-2.4.0.152-universal.jar         | None                                     |
	| UCHIJ | buildcraftlib              | 7.99.16                      | buildcraft-7.99.16 (2).jar                        | None                                     |
	| UCHIJ | buildcraftcore             | 7.99.16                      | buildcraft-7.99.16 (2).jar                        | None                                     |
	| UCHIJ | buildcraftbuilders         | 7.99.16                      | buildcraft-7.99.16 (2).jar                        | None                                     |
	| UCHIJ | buildcraftenergy           | 7.99.16                      | buildcraft-7.99.16 (2).jar                        | None                                     |
	| UCHIJ | buildcraftfactory          | 7.99.16                      | buildcraft-7.99.16 (2).jar                        | None                                     |
	| UCHIJ | buildcraftrobotics         | 7.99.16                      | buildcraft-7.99.16 (2).jar                        | None                                     |
	| UCHIJ | buildcrafttransport        | 7.99.16                      | buildcraft-7.99.16 (2).jar                        | None                                     |
	| UCHIJ | buildcraftsilicon          | 7.99.16                      | buildcraft-7.99.16 (2).jar                        | None                                     |
	| UCHIJ | cofhcore                   | 4.3.11                       | CoFHCore-1.12.2-4.3.11.6-universal.jar            | None                                     |
	| UCHIE | mekanism                   | 9.4.1                        | Mekanism-1.12.1-9.4.1.326.jar                     | None                                     |
	| UCHIJ | sonarcore                  | 5.0.8                        | sonarcore-1.12.2-5.0.8.jar                        | None                                     |
	| UCHIJ | calculator                 | 5.0.4                        | calculator-1.12.2-5.0.4.jar                       | None                                     |
	| UCHIJ | chameleon                  | 1.12-4.1.3                   | Chameleon-1.12-4.1.3.jar                          | None                                     |
	| UCHIJ | clumps                     | 2.0.0                        | Clumps-3.0.0.jar                                  | None                                     |
	| UCHIJ | cofhworld                  | 1.1.1                        | CoFHWorld-1.12.2-1.1.1.12-universal.jar           | None                                     |
	| UCHIJ | compactsolars              | 1.12.2-5.0.17.340            | CompactSolars-1.12.2-5.0.17.340-universal.jar     | None                                     |
	| UCHIJ | cucumber                   | 1.1.0                        | cucumber-1.12-1.1.0.jar                           | None                                     |
	| UCHIJ | waila                      | 1.8.25                       | Hwyla-1.8.25-B40_1.12.jar                         | None                                     |
	| UCHIJ | darkutils                  | 1.8.208                      | DarkUtils-1.12.2-1.8.208.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJ | elevatorid                 | 1.3.6                        | ElevatorMod-1.12.2-1.3.6.jar                      | None                                     |
	| UCHIJ | endercore                  | 1.12.2-0.5.20                | EnderCore-1.12.2-0.5.20.jar                       | None                                     |
	| UCHIJ | thermalfoundation          | 2.3.11                       | ThermalFoundation-1.12.2-2.3.12.10-universal.jar  | None                                     |
	| UCHIJ | enderio                    | 5.0.22                       | EnderIO-1.12.2-5.0.22.jar                         | None                                     |
	| UCHIJ | enderiointegrationtic      | 5.0.22                       | EnderIO-1.12.2-5.0.22.jar                         | None                                     |
	| UCHIJ | enderiobase                | 5.0.22                       | EnderIO-1.12.2-5.0.22.jar                         | None                                     |
	| UCHIJ | enderioconduits            | 5.0.22                       | EnderIO-1.12.2-5.0.22.jar                         | None                                     |
	| UCHIJ | enderiointegrationforestry | 5.0.22                       | EnderIO-1.12.2-5.0.22.jar                         | None                                     |
	| UCHIJ | enderiointegrationticlate  | 5.0.22                       | EnderIO-1.12.2-5.0.22.jar                         | None                                     |
	| UCHIJ | enderiomachines            | 5.0.22                       | EnderIO-1.12.2-5.0.22.jar                         | None                                     |
	| UCHIJ | enderiopowertools          | 5.0.22                       | EnderIO-1.12.2-5.0.22.jar                         | None                                     |
	| UCHIJ | enderstorage               | 2.4.2.126                    | EnderStorage-1.12.2-2.4.2.126-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJ | energyconverters           | 1.0.1.2                      | energyconverters_1.12.1-1.0.1.2.jar               | None                                     |
	| UCHIJ | exnihilocreatio            | 1.12-0.2.2                   | exnihilocreatio-1.12-0.2.2.jar                    | None                                     |
	| UCHIJ | extracells                 | 2.5.11                       | ExtraCells-1.12.2-2.5.11a48.jar                   | None                                     |
	| UCHIJ | extrautils2                | 1.0                          | extrautils2-1.12-1.7.6.jar                        | None                                     |
	| UCHIJ | zerocore                   | 1.12-0.1.2.1                 | zerocore-1.12-0.1.2.1.jar                         | None                                     |
	| UCHIJ | bigreactors                | 1.12.2-0.4.5.48              | ExtremeReactors-1.12.2-0.4.5.48.jar               | None                                     |
	| UCHIJ | flansmod                   | 5.5.1                        | Flan's Mod-1.12.2-5.5.1.jar                       | None                                     |
	| UCHIJ | flansmodapocalypse         | 1.0                          | Flan's Mod-1.12.2-5.5.1.jar                       | None                                     |
	| UCHIJ | forgelin                   | 1.6.0                        | Forgelin-1.6.0.jar                                | None                                     |
	| UCHIJ | advgenerators              | 0.9.20.12                    | generators-0.9.20.12-mc1.12.2.jar                 | None                                     |
	| UCHIJ | guideapi                   | 1.12-2.1.5-60                | Guide-API-1.12-2.1.5-60.jar                       | None                                     |
	| UCHIJ | ichunutil                  | 7.1.4                        | iChunUtil-1.12.2-7.1.4.jar                        | None                                     |
	| UCHIJ | hats                       | 7.0.0                        | Hats-1.12.2-7.0.2.jar                             | None                                     |
	| UCHIJ | immersiveengineering       | 0.12-81                      | ImmersiveEngineering-0.12-81.jar                  | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHIJ | immersivecables            | 1.3.0                        | ImmersiveCables-1.12.2-1.3.0.jar                  | None                                     |
	| UCHIJ | teslacorelib               | 1.0.13                       | tesla-core-lib-1.12-1.0.13.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJ | industrialforegoing        | 1.12.2-1.12.2                | industrialforegoing-1.12.2-1.8.10-143.jar         | None                                     |
	| UCHIJ | inventorytweaks            | 1.64-dev+release.110.b4fac73 | InventoryTweaks-1.64-dev.jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJ | ironbackpacks              | 1.12.2-3.0.5-6               | IronBackpacks-1.12.2-3.0.5-6.jar                  | None                                     |
	| UCHIJ | ironchest                  | 1.12.2-7.0.42.827            | ironchest-1.12.2-7.0.42.827.jar                   | None                                     |
	| UCHIJ | journeymap                 | 1.12.2-5.5.2                 | journeymap-1.12.2-5.5.2.jar                       | None                                     |
	| UCHIJ | mantle                     | 1.12-1.3.2.24                | Mantle-1.12-1.3.2.24.jar                          | None                                     |
	| UCHIJ | mcjtylib_ng                | 2.6.7                        | mcjtylib-1.12-2.6.7.jar                           | None                                     |
	| UCHIJ | mtlib                      | 3.0.4                        | MTLib-3.0.4.jar                                   | None                                     |
	| UCHIJ | mysticalagriculture        | 1.6.9                        | mysticalagriculture-1.12-1.6.9.jar                | None                                     |
	| UCHIJ | mysticalagradditions       | 1.2.8                        | mysticalagradditions-1.12-1.2.8.jar               | None                                     |
	| UCHIJ | nei                        | 2.4.1                        | NotEnoughItems-1.12.2-2.4.1.233-universal (1).jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJ | notenoughwands             | 1.6.1                        | notenoughwands-1.12-1.6.1.jar                     | None                                     |
	| UCHIJ | projecte                   | 1.12-PE1.0.0                 | ProjectE-1.12-PE1.2.0.jar                         | None                                     |
	| UCHIJ | p455w0rdslib               | 2.0.29                       | p455w0rdslib-1.12-2.0.29.jar                      | None                                     |
	| UCHIJ | harvestcraft               | 1.12.2t                      | Pam's+HarvestCraft+1.12.2t.jar                    | None                                     |
	| UCHIJ | poweradapters              | 1.0.8                        | PowerAdapters-1.12.2-1.0.8.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJ | rafradek_tf2_weapons       | 1.3.6                        | rafradek_tf2_weapons-1.12.2-1.3.6.jar             | None                                     |
	| UCHIJ | reborncore                 | 3.8.0.264                    | RebornCore-1.12.2-3.8.0.264-universal.jar         | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UCHIE | thermalexpansion           | 5.3.11                       | ThermalExpansion-1.12.2-5.3.12.17-universal.jar   | None                                     |
	| UCHIE | simplyjetpacks             | 2.2.2.28                     | SimplyJetpacks2-1.12.2-2.2.2.28.jar               | None                                     |
	| UCHIJ | snad                       | 1.12.1-1.7.09.16a            | Snad-1.12.1-1.7.09.16a.jar                        | None                                     |
	| UCHIJ | stairway                   | v08                          | Stairway_1.12_v08.jar                             | None                                     |
	| UCHIJ | stevescarts                | 2.4.18.92                    | StevesCarts-1.12.2-2.4.18.92.jar                  | None                                     |
	| UCHIJ | storagedrawers             | 1.12-5.3.5                   | StorageDrawers-1.12.2-5.3.6.jar                   | None                                     |
	| UCHIJ | techreborn                 | 2.15.2.608                   | TechReborn-1.12.2-2.15.2.608-universal.jar        | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UCHIJ | thermaldynamics            | 2.3.11                       | ThermalDynamics-1.12.2-2.3.11.7-universal.jar     | None                                     |
	| UCHIJ | tp                         | 3.2.25                       | tinyprogressions-1.12.2-3.3.25-Release.jar        | None                                     |
	| UCHIJ | veinminer                  | 0.38.2                       | VeinMiner-1.12-0.38.2.647+b31535a.jar             | None                                     |
	| UCHIJ | veinminermodsupport        | 0.38.2                       | VeinMiner-1.12-0.38.2.647+b31535a.jar             | None                                     |
	| UCHIJ | wawla                      | 2.5.255                      | Wawla-1.12.2-2.5.255.jar                          | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJ | wct                        | 3.9.64                       | WirelessCraftingTerminal-1.12.2-3.9.64.jar        | None                                     |
	| UCHIJ | teslacorelib_registries    | 1.0.13                       | tesla-core-lib-1.12-1.0.13.jar                    | None                                     |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-81.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.20.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  invtweaks.forge.asm.ContainerTransformer
ForgelinPlugin (Forgelin-1.6.0.jar)
  
AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
  squeek.applecore.asm.TransformerModuleHandler
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.13' Renderer: 'GeForce GTX 1060 3GB/PCIe/SSE2'
	AE2 Version: stable rv5-stable-11 for Forge 14.23.1.2554
	List of loaded APIs: 
		* AppleCoreAPI (3.1.0) from AppleCore-mc1.12.2-3.1.1.jar
		* appliedenergistics2|API (rv5) from appliedenergistics2-rv5-stable-11.jar
		* Base|API (1.0.0) from base-1.12.2-3.7.1.jar
		* Baubles|API (1.4.0.2) from WirelessCraftingTerminal-1.12.2-3.9.64.jar
		* bigreactors|API (4.0.1) from ExtremeReactors-1.12.2-0.4.5.48.jar
		* BuildCraftAPI|blocks (1.0) from buildcraft-7.99.16 (2).jar
		* BuildCraftAPI|boards (2.0) from buildcraft-7.99.16 (2).jar
		* BuildCraftAPI|core (2.2) from buildcraft-7.99.16 (2).jar
		* BuildCraftAPI|crops (1.1) from buildcraft-7.99.16 (2).jar
		* BuildCraftAPI|enums (1.0) from buildcraft-7.99.16 (2).jar
		* BuildCraftAPI|events (2.0) from buildcraft-7.99.16 (2).jar
		* BuildCraftAPI|facades (1.1) from buildcraft-7.99.16 (2).jar
		* BuildCraftAPI|filler (5.0) from buildcraft-7.99.16 (2).jar
		* BuildCraftAPI|fuels (2.0) from buildcraft-7.99.16 (2).jar
		* BuildCraftAPI|gates (4.1) from buildcraft-7.99.16 (2).jar
		* BuildCraftAPI|items (1.1) from buildcraft-7.99.16 (2).jar
		* BuildCraftAPI|library (2.0) from buildcraft-7.99.16 (2).jar
		* BuildCraftAPI|lists (1.0) from buildcraft-7.99.16 (2).jar
		* BuildCraftAPI|power (1.3) from buildcraft-7.99.16 (2).jar
		* BuildCraftAPI|recipes (3.0) from buildcraft-7.99.16 (2).jar
		* BuildCraftAPI|robotics (3.0) from buildcraft-7.99.16 (2).jar
		* BuildCraftAPI|statements (1.1) from buildcraft-7.99.16 (2).jar
		* BuildCraftAPI|tiles (1.2) from buildcraft-7.99.16 (2).jar
		* BuildCraftAPI|tools (1.0) from buildcraft-7.99.16 (2).jar
		* BuildCraftAPI|transport (5.0) from buildcraft-7.99.16 (2).jar
		* calculatorapi (1.9.4 - 1.0) from calculator-1.12.2-5.0.4.jar
		* cofhapi (2.2.0) from CoFHCore-1.12.2-4.3.11.6-universal.jar
		* cofhapi|block (2.2.0) from CoFHCore-1.12.2-4.3.11.6-universal.jar
		* cofhapi|core (2.2.0) from CoFHCore-1.12.2-4.3.11.6-universal.jar
		* cofhapi|item (2.2.0) from CoFHCore-1.12.2-4.3.11.6-universal.jar
		* cofhapi|tileentity (2.2.0) from CoFHCore-1.12.2-4.3.11.6-universal.jar
		* cofhapi|util (2.2.0) from CoFHCore-1.12.2-4.3.11.6-universal.jar
		* enderioapi (4.0.0) from EnderIO-1.12.2-5.0.22.jar
		* enderioapi|addon (4.0.0) from EnderIO-1.12.2-5.0.22.jar
		* enderioapi|capacitor (4.0.0) from EnderIO-1.12.2-5.0.22.jar
		* enderioapi|conduits (4.0.0) from EnderIO-1.12.2-5.0.22.jar
		* enderioapi|farm (4.0.0) from EnderIO-1.12.2-5.0.22.jar
		* enderioapi|redstone (4.0.0) from EnderIO-1.12.2-5.0.22.jar
		* enderioapi|teleport (4.0.0) from EnderIO-1.12.2-5.0.22.jar
		* enderioapi|tools (4.0.0) from EnderIO-1.12.2-5.0.22.jar
		* enderioapi|upgrades (4.0.0) from EnderIO-1.12.2-5.0.22.jar
		* Guide-API|API (2.0.0) from Guide-API-1.12-2.1.5-60.jar
		* iChunUtil API (1.2.0) from iChunUtil-1.12.2-7.1.4.jar
		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.12-81.jar
		* ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.12-81.jar
		* industrialforegoingapi (4) from industrialforegoing-1.12.2-1.8.10-143.jar
		* journeymap|client-api (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-display (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-event (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-model (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-util (1.4) from journeymap-1.12.2-5.5.2.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.9.1.168.jar
		* MekanismAPI|core (9.0.0) from Mekanism-1.12.1-9.4.1.326.jar
		* MekanismAPI|energy (9.0.0) from Mekanism-1.12.1-9.4.1.326.jar
		* MekanismAPI|gas (9.0.0) from Mekanism-1.12.1-9.4.1.326.jar
		* MekanismAPI|infuse (9.0.0) from Mekanism-1.12.1-9.4.1.326.jar
		* MekanismAPI|laser (9.0.0) from Mekanism-1.12.1-9.4.1.326.jar
		* MekanismAPI|transmitter (9.0.0) from Mekanism-1.12.1-9.4.1.326.jar
		* MekanismAPI|util (9.0.0) from Mekanism-1.12.1-9.4.1.326.jar
		* projecteapi (1.11.2-1.0.0) from ProjectE-1.12-PE1.2.0.jar
		* ProjectEAPI (1.9.4-1.0.0) from p455w0rdslib-1.12-2.0.29.jar
		* reborncoreAPI (3.8.0.264) from RebornCore-1.12.2-3.8.0.264-universal.jar
		* reborncoreAPI|Power (3.8.0.264) from RebornCore-1.12.2-3.8.0.264-universal.jar
		* reborncoreAPI|Recipe (3.8.0.264) from RebornCore-1.12.2-3.8.0.264-universal.jar
		* reborncoreAPI|Tile (3.8.0.264) from RebornCore-1.12.2-3.8.0.264-universal.jar
		* sonarapi (1.0.1) from sonarcore-1.12.2-5.0.8.jar
		* stevescartsAPI (${version}) from StevesCarts-1.12.2-2.4.18.92.jar
		* stevescartsAPI|FARMS (${version}) from StevesCarts-1.12.2-2.4.18.92.jar
		* StorageDrawersAPI (2.1.0) from StorageDrawers-1.12.2-5.3.6.jar
		* StorageDrawersAPI|event (2.1.0) from StorageDrawers-1.12.2-5.3.6.jar
		* StorageDrawersAPI|registry (2.1.0) from StorageDrawers-1.12.2-5.3.6.jar
		* StorageDrawersAPI|render (2.1.0) from StorageDrawers-1.12.2-5.3.6.jar
		* StorageDrawersAPI|storage (2.1.0) from StorageDrawers-1.12.2-5.3.6.jar
		* StorageDrawersAPI|storage-attribute (2.1.0) from StorageDrawers-1.12.2-5.3.6.jar
		* techrebornAPI (2.15.2.608) from TechReborn-1.12.2-2.15.2.608-universal.jar
		* veinminerApi (0.3) from VeinMiner-1.12-0.38.2.647+b31535a.jar
		* WailaAPI (1.3) from Hwyla-1.8.25-B40_1.12.jar
		* wct|api (1.1) from WirelessCraftingTerminal-1.12.2-3.9.64.jar
		* zerocore|API|multiblock (1.10.2-0.0.2) from zerocore-1.12-0.1.2.1.jar
		* zerocore|API|multiblock|rectangular (1.10.2-0.0.2) from zerocore-1.12-0.1.2.1.jar
		* zerocore|API|multiblock|tier (1.10.2-0.0.2) from zerocore-1.12-0.1.2.1.jar
		* zerocore|API|multiblock|validation (1.10.2-0.0.2) from zerocore-1.12-0.1.2.1.jar
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.8.0.264
		Runtime Debofucsation 1
		RenderEngine: 1
	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:ON, JEI:ON, Mekanism:ON, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	OptiFine Version: OptiFine_1.12.2_HD_U_D2
	OptiFine Build: 20180430-132249
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 388.13
	OpenGlRenderer: GeForce GTX 1060 3GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by sfantah** [comment]
- Note - 

Attempted to delete almost every mod and still crashed

**Comment by radfast** [comment]
Nothing to do with Galacticraft.

We can't cause a crash from beyond the grave ...   None of our code is present in that crash report you posted.

Maybe Thermal Expansion added some item to the sawmill config which is no longer in the game now you changed mods.  Try deleting or resetting Thermal Expansion configs.

-----

Not sure why you would **want** to delete Galacticraft, was it causing some other problem in your pack?

**Comment by sfantah** [comment]
It would for whatever reason make the recipes screw up and slow the whole crafting process down (pretty much multiplayer lag in singleplayer) yet barely using any ram/cpu, other than that it is a great mod

**Comment by radfast** [comment]
>  It would for whatever reason make the recipes screw up and slow the whole crafting process down

It would help us out if you can give more details of that.  It's not an issue reported before, and maybe we can get it fixed for you?
* Are you talking about slowdown in JEI?
* Or slowdown when using a regular Crafting Table, like you're saying it takes a long time to show up the output item?  Or there's lag when moving items between slots in the crafting grid?
* Or something else?

Any other mods installed which "help" with crafting - or which change the regular crafting process?

**Comment by TheQuadShot** [comment]
The slow crafting and recipe "thing" isn't a GC issue, it was thought to be TiC but I'm not exactly sure since I can't repro it. https://github.com/SlimeKnights/TinkersConstruct/issues/3432

**Comment by TheQuadShot** [comment]
@radfast Sorry, my post was meant to be more of an fyi to some crafting issues going "around".
