### ISSUE TITLE
Immediate Crash At Launch, Help?

### ISSUE THREAD

**Issue by SharpForceTrauma** [micdoodle8/Galacticraft#3414]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version:1.12.2
Galacticraft version:4.0.1.169

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?  N/A

Galacticraft add-ons and other mods installed? Y, Galacticraft Planets, Extra Planets, JourneyMap, ToroCraft Damage Indicators.

Please provide screenshots / crash report / log as needed.
[latest.log](https://github.com/micdoodle8/Galacticraft/files/2032367/latest.log)
[crash-2018-05-23_13.10.23-client.txt](https://github.com/micdoodle8/Galacticraft/files/2032371/crash-2018-05-23_13.10.23-client.txt)

**Comment by Romsik788** [comment]
1. Update the galacticraft
2. Try to run without extra planets.
3. If nothing has helped then describe in more detail your problem.

**Comment by MJRLegends** [comment]
The issue is you haven't downloaded the mods from a official source so the versions you have are all broken. The place you downloaded them stole them.

**Comment by SharpForceTrauma** [comment]
@MJRLegends That may be it. I downloaded them from 9minecraft.net, which is my usual source for all of my mods. I'll try to redownload them from here. @Romsik788 I downloaded the official Galacticraft here, after the initial crash mentioned an exception error with the one I got from 9minecraft. I'm not sure about running it without addons, as I test loads in the state I wish to play them to ensure that everything works.

Thanks to both of you for helping!

**Comment by SharpForceTrauma** [comment]
@MJRLegends  May I ask for a the links to these addons, as well as yours and Micdoodle's corelibs?

**Comment by TheQuadShot** [comment]
Forums (add-ons)
https://forum.micdoodle8.com/index.php
Official core files at the Wiki
https://micdoodle8.com/mods/galacticraft/downloads
Any other add-ons not found at either should be on Curse or FTB

**Comment by SharpForceTrauma** [comment]
@MJRLegends I never knew this was such a huge problem before, thanks for showing me this. I got the plugin now. Learning this, this makes me wonder if this is the cause of the issues with some other mods I have. @TheQuadShot Thank you for linking!

**Comment by MJRLegends** [comment]
@radfast I'd recommenced adding Jar Signing (Signature) to GC & MicdoodleCore makes sure no one is using unofficial builds as the file names are not always a way to tell where they got the version.

**Comment by radfast** [comment]
how does that help if 9minecraft copies those builds?  They don't create builds from the source code, they copy our .jar files.

**Comment by marcus8448** [comment]
Hey @radfast I did some digging and they might actually build it themselves, unless the files just happen to be the same size... The hashes are different.
![screenshot 35](https://user-images.githubusercontent.com/28928887/41449670-4f2f4282-7017-11e8-9389-639f3ee06b0b.png)
