### ISSUE TITLE
[Feature Request] Add more tools for modpack makers

### ISSUE THREAD

**Issue by kriNon** [micdoodle8/Galacticraft#3415]
So I'm working on a modpack and there is some functionality that I am looking for.

I want my pack to start off on a space station / spaceship. I am thinking to achieve this properly I would either need to create a new dimension using a different mod, then adjust gravity, oxygen etc, and then somehow add the dimension to the earth as a Satellite (although support for adding or removing planets/moons/satellites from the map doesn't seem to exist currently.

The alternative would be to somehow modify the existing space station satellite that can be built for the world. For the purposes of the pack I would then need to be able to generate a shared space station (visible to everyone without requiring invite).

Thanks!

**Comment by TheQuadShot** [comment]
You should  check out the Pathfinder modpack (FTB). Also in the future please post feature requests or ideas on the forums page here: https://forum.micdoodle8.com/index.php
Thanks, and please close this report.
