### ISSUE TITLE
MAJOR Request

### ISSUE THREAD

**Issue by Moobien** [micdoodle8/Galacticraft#3419]
Guys can you make it so that EnderIO item conduits can connect to machines again, as well as switch to IItemHandler from IInventory

**Comment by radfast** [comment]
You'd better state:
* which Galacticraft version
* which EnderIO version
* screenshot of what is not working

**Comment by TheQuadShot** [comment]
I got the 1.12.2 info, Item Conduits don't work, Fluid and Power do.

Minecraft 1.12.2
Forge 14.23.3.2698
Galacticraft-Planets-1.12.2-4.0.1.177.jar
GalacticraftCore-1.12.2-4.0.1.177.jar
MicdoodleCore-1.12.2-4.0.1.177.jar

EnderIO-1.12.2-5.0.24.jar

Fluid and Power work
https://imgur.com/h8YM9CK

Item Conduits don't
https://imgur.com/DQj01In
