### ISSUE TITLE
Circuit Fabricator draining RF when idle

### ISSUE THREAD

**Issue by AstroxV** [micdoodle8/Galacticraft#3423]
Minecraft version: 1.12.2
Galacticraft version: 4.0.1.176

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP

Galacticraft add-ons and other mods installed?
SevTech modpack

Issue:
The Circuit Fabricator keeps draining RF when not in use. 

How to replicate:
Connect the fabricator to power to let it fill up with power. Then disconnect the power and slowly the fabricator starts to drain. This also happens when a redstone signal is applied.

**Comment by TheQuadShot** [comment]
Known issue https://github.com/micdoodle8/Galacticraft/issues/2845
Please close this bug.

**Comment by AstroxV** [comment]
Sorry, I searched but couldn't find that one, my bad.
