### ISSUE TITLE
Rocket Dupe (Rocket and Items)

### ISSUE THREAD

**Issue by artdude543** [micdoodle8/Galacticraft#3428]
Hello, I come to thee to post a dupe issue, which was posted on the SevTech: Ages tracker. I did see a similar issue posted last year on the tracker. But I thought to post a new one as the linked issue contains a decent amount of data and videos on the various dupe issues.

Minecraft version: 1.12.2
Galacticraft version: 4.0.1.176

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
- Looks like a server from the VOD.

Galacticraft add-ons and other mods installed?
- ExtraPlanets

All details and video can be found here: https://github.com/DarkPacks/SevTech-Ages/issues/2750

**Comment by TheQuadShot** [comment]
I can't make a 5x5 launch pad, it won't let me place the corners.
![2018-06-05_13 50 24](https://user-images.githubusercontent.com/11265900/41002027-6f6261bc-68c7-11e8-835e-38c692a3a100.png)

**Comment by artdude543** [comment]
Okay, I've thrown this up on ExtraPlanets Repo as I did not realize he was the one who had the larger launchpads. Never played with either mod so just assumed he would be extending some class in this mod but it's all custom from his code base. So re-reported over there.

But I wonder if the issue applies here with stack pads but 3x3 and on top by one as noted in the VOD?

**Comment by TheQuadShot** [comment]
No worries. I did try to dupe and was unable to. I'm running 1.12.2, GalacticraftCore-1.12.2-4.0.1.177

**Comment by radfast** [comment]
This is not an issue in Galacticraft.

For ExtraPlanets:  @MJRLegends see https://github.com/micdoodle8/Galacticraft/commit/51a662521f9047ba709e21513f6edc1ec517c76f and #3292
