### ISSUE TITLE
Galacticraft mod crashes when loading minecraft world

### ISSUE THREAD

**Issue by NazarBalous** [micdoodle8/Galacticraft#3430]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version:1.12.2
Galacticraft version:1.12.2-4.0.1.177

Singleplayer worlds old and new

Crashes even when it is the only mod, Minecraft doesn't crash when using only forge

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 6/6/18 10:18 AM
Description: Unexpected error

java.lang.NoSuchMethodError: micdoodle8.mods.galacticraft.core.TransformerHooks.getWorldBrightness(Lnet/minecraft/client/multiplayer/WorldClient;)F
	at net.minecraft.client.renderer.EntityRenderer.func_78472_g(EntityRenderer.java:838)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1234)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_78472_g(EntityRenderer.java:838)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1234)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['alisb'/103, l='MpServer', x=71.98, y=60.03, z=542.44]]
	Chunk stats: MultiplayerChunkCache: 49, 49
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (85,56,403), Chunk: (at 5,3,3 in 5,25; contains blocks 80,0,400 to 95,255,415), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3664050 game time, 86067 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 42 total; [EntitySkeleton['Skeleton'/64, l='MpServer', x=49.64, y=33.00, z=546.59], EntityCreeper['Creeper'/65, l='MpServer', x=52.52, y=42.00, z=546.15], EntitySkeleton['Skeleton'/66, l='MpServer', x=48.32, y=42.00, z=549.46], EntitySkeleton['Skeleton'/67, l='MpServer', x=48.28, y=42.00, z=547.70], EntityCreeper['Creeper'/70, l='MpServer', x=79.50, y=56.00, z=542.50], EntitySkeleton['Skeleton'/71, l='MpServer', x=77.50, y=56.00, z=568.50], EntityCreeper['Creeper'/73, l='MpServer', x=82.83, y=56.00, z=536.59], EntitySpider['Spider'/74, l='MpServer', x=89.97, y=56.00, z=538.70], EntitySkeleton['Skeleton'/75, l='MpServer', x=92.10, y=56.00, z=548.40], EntityWitch['Witch'/76, l='MpServer', x=91.52, y=56.00, z=547.27], EntitySpider['Spider'/77, l='MpServer', x=93.22, y=56.12, z=549.30], EntityCreeper['Creeper'/78, l='MpServer', x=82.19, y=56.00, z=545.28], EntitySpider['Spider'/83, l='MpServer', x=96.50, y=56.00, z=534.50], EntitySkeleton['Skeleton'/22, l='MpServer', x=44.10, y=42.00, z=524.71], EntityBat['Bat'/23, l='MpServer', x=47.83, y=39.10, z=524.35], EntityCreeper['Creeper'/24, l='MpServer', x=47.30, y=35.00, z=523.47], EntityBat['Bat'/27, l='MpServer', x=45.43, y=34.00, z=524.75], EntitySpider['Spider'/28, l='MpServer', x=47.50, y=56.00, z=524.50], EntityCreeper['Creeper'/34, l='MpServer', x=41.47, y=35.00, z=549.54], EntitySkeleton['Skeleton'/38, l='MpServer', x=42.53, y=44.00, z=550.29], EntityCreeper['Creeper'/40, l='MpServer', x=46.30, y=39.00, z=547.70], GCEntityClientPlayerMP['alisb'/103, l='MpServer', x=71.98, y=60.03, z=542.44], EntitySkeleton['Skeleton'/41, l='MpServer', x=47.19, y=42.00, z=547.30], EntitySkeleton['Skeleton'/43, l='MpServer', x=40.57, y=49.00, z=550.20], EntityCreeper['Creeper'/46, l='MpServer', x=49.50, y=44.00, z=522.50], EntityCreeper['Creeper'/47, l='MpServer', x=54.50, y=43.00, z=526.50], EntityBat['Bat'/48, l='MpServer', x=46.53, y=35.50, z=527.90], EntitySpider['Spider'/49, l='MpServer', x=52.83, y=56.00, z=524.44], EntityBat['Bat'/50, l='MpServer', x=49.75, y=31.10, z=537.44], EntityZombie['Zombie'/51, l='MpServer', x=52.20, y=30.00, z=542.49], EntityBat['Bat'/52, l='MpServer', x=52.25, y=40.10, z=540.58], EntityCreeper['Creeper'/53, l='MpServer', x=52.94, y=37.00, z=530.50], EntityBat['Bat'/54, l='MpServer', x=53.60, y=38.10, z=535.46], EntityBat['Bat'/55, l='MpServer', x=53.53, y=35.10, z=530.75], EntityEnderman['Enderman'/56, l='MpServer', x=53.30, y=32.00, z=542.70], EntityCreeper['Creeper'/57, l='MpServer', x=54.30, y=34.00, z=531.30], EntityCreeper['Creeper'/58, l='MpServer', x=52.30, y=37.00, z=530.48], EntityBat['Bat'/59, l='MpServer', x=52.75, y=34.10, z=531.59], EntitySkeleton['Skeleton'/60, l='MpServer', x=52.42, y=42.00, z=528.24], EntityWitch['Witch'/61, l='MpServer', x=48.30, y=32.00, z=548.30], EntityZombie['Zombie'/62, l='MpServer', x=53.30, y=37.00, z=545.70], EntityCreeper['Creeper'/63, l='MpServer', x=48.18, y=35.00, z=549.47]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 359074544 bytes (342 MB) / 817688576 bytes (779 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2641 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                  | Version      | Source                              | Signature                                |
	|:--------- |:------------------- |:------------ |:----------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft           | 1.12.2       | minecraft.jar                       | None                                     |
	| UCHIJAAAA | mcp                 | 9.42         | minecraft.jar                       | None                                     |
	| UCHIJAAAA | FML                 | 8.0.99.99    | forge-1.12.2-14.23.2.2641.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge               | 14.23.2.2641 | forge-1.12.2-14.23.2.2641.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | micdoodlecore       |              | minecraft.jar                       | None                                     |
	| UCHIJAAAA | galacticraftcore    | 4.0.1.128    | GalacticraftCore-1.12.2.jar         | None                                     |
	| UCHIJAAAA | galacticraftplanets | 4.0.1.121    | Galacticraft-Planets-Mod-1.12.2.jar | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4627' Renderer: 'Intel(R) HD Graphics 520'
	Launched Version: 1.12.2-forge1.12.2-14.23.2.2641
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 520 GL version 4.4.0 - Build 21.20.16.4627, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (United Kingdom)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz

I tried playing with render distance 3, but it still crashed.

Please help.
Thanks

**Comment by Romsik788** [comment]
Update galacticraft to latest version.

**Comment by radfast** [comment]
And next time, don't download our mod from an unofficial source like **9Minecraft**.  Get it from our official site.

**Comment by NazarBalous** [comment]
Thanks.
I appreciate that.

**Comment by EzerArch** [comment]
https://twitter.com/EzerArch/status/1004737613348130816

**Comment by MJRLegends** [comment]
Checkout http://stopmodreposts.org/ as people shouldnt be allowed to repost mods on scam sites its illegal posting, And please download the browser plugins found near the bottom of http://stopmodreposts.org/get-involved/ to make sure your not helping these people!! #StopModReposts
