### ISSUE TITLE
[1.12] Crash with latest OptiFine

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#3435]
More info at https://github.com/sp614x/optifine/issues/1419

**Comment by kenijey** [comment]
thank you SteveKunG... i was going to open this issue.

**Comment by radfast** [comment]
should be fixed in next build 178

**Comment by radfast** [comment]
grrrrrrrr

It appears that this was an issue in the optifine E1 preview only.  Not an issue in final release E1.

Now I've changed Galacticraft code to fix an issue which wasn't there, meaning Galacticraft now crashes with the release E1.

So unhelpful that Optifine is not open-source and not transparent about what changes it makes between versions.

**Comment by SteveKunG** [comment]
Can confirm it fixed, Thanks!
