### ISSUE TITLE
Unable to launch to the Moon 

### ISSUE THREAD

**Issue by Furytitaninzer** [micdoodle8/Galacticraft#3436]
Minecraft version:1.12.2
Galacticraft version:4.0.1.177

Single player (SSP)

Galacticraft add-ons and other mods installed?
SecurityCraft
Aether II
AppliedEnergistics 2
Baubles
Biomes O' Plenty
Bookshelf
BrandonsCore
BuildCraft
Carpenter's Blocks
Cdm (Crayfishes Device Mod)
Cfm (Crayfishes Furniture Mod)
CodeChickenLib
ComputerCraft
CustomMobSpawners
DarkUtils
Draconic Evolution
DrZharks Mo Creatures
Ender Core
EnderIO
ExtraPlanets
Galacticraft Planets
Infernal Mobs
Iron Chest
Jei
JourneyMap
Light Switch
MalisisCore
MalisisDoors
Mantle
MCA (Minecraft Comes Alive)
MicDoodleCore
MJRLegendsLib
Mobends
Optifine
OrbisAPI
Pam's HarvestCraft
PTRLib
RadixCore
RedstoneFlux
TConstruct
ThaumCraft
TheBetweenlandsCore
Thebetweenlands
TwilightForest
Worldedit

As the title says I am completely unable to launch to the moon no matter what tier rocket I use, whether in survival or creative. No matter what I do the button is red

**Comment by radfast** [comment]
Not clear why this would be.

1.  Can you try without ExtraPlanets and MJRLegendsLib, see if it works without those.

2.  Please confirm that you know how to launch to the moon in Galacticraft normally - for example if Galacticraft is the only mod installed, it works for you.  (I mean it's not your first time...)

3.  Please give exact steps taken to launch to the moon, and screenshots.  Can you reach any other destinations like Mars or Venus in a Tier 3 rocket?  In creative mode can you create a space station and launch to that?

**Comment by Furytitaninzer** [comment]
After trying without ExtraPlanets and MJRLegendsLib it started to work, thank you.

**Comment by radfast** [comment]
Could be you need a different version of ExtraPlanets - they are build to match specific versions of Galacticraft.

**Comment by maximus25** [comment]
What do you mean?

**Comment by MJRLegends** [comment]
DrZharks MoCreatures Mod uses -17 dimension id, Uranus from ExtraPlanets also does it seems it causes weird conflict issues probably due to DrZharks MoCreatures Mod side. ID Conflicts in the past have never caused a issue like this. So i dont claim this issue with ExtraPlanets being at fault.

Issue also caused by this MJRLegends/ExtraPlanets#531

Solution: Change Dimension ID in config
