### ISSUE TITLE
Keep spawning on the moon

### ISSUE THREAD

**Issue by Geistica** [micdoodle8/Galacticraft#3442]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version:1.7.10
Galacticraft version: 1.7-3.0.12.504

Single player (SSP)

Galacticraft add-ons and other mods installed?
Yes

Please provide screenshots / crash report / log as needed.
http://prntscr.com/jw8bsi < creating
http://prntscr.com/jw8ckq < spawning
http://prntscr.com/jw8ecn < Choosed overworld while in the menu screen ( I flew up with a rocket)

**Comment by Geistica** [comment]
Oh yeah and also this happend when I tried to get off the moon,relogged in and started the rocket again. https://pastebin.com/d8VwGbcA

**Comment by radfast** [comment]
That doesn't look like Galacticraft's moon, are you sure it's not the Advanced Rocketry moon?

You might also need to reduce the number of Galacticraft add-ons installed, you are trying to use **GalaxySpace**, **ExtraPlanets**, and **MorePlanets** all together.  That's probably not going to work, at least not without some advanced config editing and other wizardry (see forum posts about combining add-ons).

I recommend you pick just one of those, and run with that.

Could also be another mod which I don't know about.  What's **MoonOfMining**?

**Comment by MJRLegends** [comment]
Sounds like a another mod has changed or someones giving out messed up configs in a mod pack and its screwing people over, as i dont touch teleporting of the player... let alone which world they spawn in.

**Comment by Geistica** [comment]
Okay if it is the dimension conflict then where is the moon dimension id? Because I can't find it.

**Comment by Geistica** [comment]
Ok found out it was the dimension's id so yeah everything seems to be fine now

**Comment by Geistica** [comment]
Where do I change the dimension's id?
