### ISSUE TITLE
Unable to land on Earth's moon with Tier 1 rocket

### ISSUE THREAD

**Issue by maximus25** [micdoodle8/Galacticraft#3444]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version:1.12.2
Galacticraft version:1.12.2-4.0.1.77

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
single player
Galacticraft add-ons and other mods installed?
Yes
Please provide screenshots / crash report / log as needed.
![bug](https://user-images.githubusercontent.com/34800170/41626368-0a6f7d70-73ea-11e8-8235-abc185709d84.PNG)

**Comment by Romsik788** [comment]
Is not Galacticraft issues!

**Comment by radfast** [comment]
Duplicate of #3436.  The poster there said that removing ExtraPlanets fixed it.  @MJRLegends, author of ExtraPlanets mod, says it's not his mod at fault, maybe another cause. :/
