### ISSUE TITLE
Compressor Crash

### ISSUE THREAD

**Issue by NicosaurusRex99** [micdoodle8/Galacticraft#3447]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version:1.12.2
Galacticraft version:4.0.1.1777

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP
Galacticraft add-ons and other mods installed?
SpaceX
Please provide screenshots / crash report / log as needed.
Crash Report
https://pastebin.com/8EqyiP0K
Log
https://gist.github.com/NicosaurusRex99/f8fddda051895f054c07d9e609426d97

**Comment by marcus8448** [comment]
It might be another mod hence in the logs there are a TON of items / blocks etc. registered without a domain which then would default to minecraft.

**Comment by TheQuadShot** [comment]
I think it's a dupe/related to https://github.com/micdoodle8/Galacticraft/issues/3402, based on this line of the crashlog:
 at thaumcraft.api.crafting.ShapelessArcaneRecipe.func_77569_a(ShapelessArcaneRecipe.java:59)

**Comment by Eggonomicon** [comment]
Minecraft Version: 1.12.2
Galacticraft Version: 4.0.1.1777

SMP

Crash Report:
[https://pastebin.com/8jWqdktQ](url)

Mods: [https://minecraft.curseforge.com/projects/the-rise-of-technomancy-modpack](url)
Many, but seems to be an issue with Thaumcraft and Galacticraft together.

Crashes opening the compressor.

Have a great one!

**Comment by marcus8448** [comment]
It's actually a issue between Galacticraft, NoMoreRecipeConflict, and Thaumcraft. Not only GC and Thaumcraft.

**Comment by NicosaurusRex99** [comment]
Honestly i think @TheQuadShot was correct i will close this issue and move to #3402

**Comment by radfast** [comment]
Whoever makes **The Rise of Technomancy** modpack needs to update their pack.

Apparently Thaumcraft made an update which fixes this, about 24 days ago.

**Comment by Eggonomicon** [comment]
The Rise of Technomancy uses Thaumcraft-1.12.2-6.1.BETA16 is what the Modpack is using from 6-4-18, it's updated regularly. However I'll post this to their Github as it seems to be a conflict between the two mods and the way they do things.

Thank you, for your time and effort!
Eggonomicon

**Comment by radfast** [comment]
@Eggonomicon thank you for posting it to them.  Just to be clear once again, the conflict is between **NoMoreRecipeConflict** and **Thaumcraft**.  It is not a conflict with Galacticraft.  If you report it as a Galacticraft conflict it might look like a different issue.

[Here is the original true issue report](https://github.com/GotoLink/RecipeHandler/issues/17)

There is no conflict between Thaumcraft 1.12.2 and Galacticraft 1.12.2.
