### ISSUE TITLE
Invalid potion

### ISSUE THREAD

**Issue by masterbobli** [micdoodle8/Galacticraft#3449]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version:1.12.2
Galacticraft version:4.0.1.177

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Single player
Galacticraft add-ons and other mods installed?
no

![2018-06-21_12 02 08](https://user-images.githubusercontent.com/37212918/41697365-fb08ceba-754a-11e8-8519-a18c9c09029c.png)
I'm playing in asteroids challenge mode. When I checked the entry pod the potion inside are uncraftable potion instead of night vision potion as it was said in the wiki

**Comment by marcus8448** [comment]
It's a known bug. See #3425

**Comment by radfast** [comment]
Thanks for reporting.  If you have cheats enabled, please give yourself 4x Night Vision potion.  We will fix this either in next build or the one after.

**Comment by masterbobli** [comment]
Thank you

**Comment by masterbobli** [comment]
I just tested it in the latest build (181) again and the potion is still invalid. And drinking the potion doesn't give any effects.
