### ISSUE TITLE
Please make Galacticraft available on Twitch!!

### ISSUE THREAD

**Issue by Nightingale1776** [micdoodle8/Galacticraft#3450]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.10.2
Galacticraft version:

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?

Galacticraft add-ons and other mods installed?

Please provide screenshots / crash report / log as needed.

Galacticraft is one of my favorite mods ever and I want to add it to my modpack on Twitch. But I'm not sure how (noob) to unless it is available to install from twitch! Would love to play again, let me know what you think!

**Comment by TheQuadShot** [comment]
This has been covered on numerous occasions(see below). Please close this and post requests on the Forums here: https://forum.micdoodle8.com/index.php
https://github.com/micdoodle8/Galacticraft/issues/3207
https://forum.micdoodle8.com/index.php?threads/gc-on-curse.6787/#post-44267
