### ISSUE TITLE
[IMPORTANT]Need Your Permission For www.mcmod.cn

### ISSUE THREAD

**Issue by ETStareak** [micdoodle8/Galacticraft#3451]
@radfast  @micdoodle8  
Sadly,the worst thing has happened.
The Great Firewall of PRC updated and blocked nearly all GC websites——micdoodle8.com,our wiki,our forum,even our jenkins!Now Chinese players have no way to download GC normally…I can't do anything to break the wall,it's impossible;and the translation for micdoodle8.com and our wiki will be useless.

However,there is a way to make Chinese play GC normally,but need your permission.
[MCMOD](https://www.mcmod.cn) is a Chinese fan-made mod website,it can be thought as a Chinese FTBwiki with （permitted） mod release and download.
Can you give me the premission to upload all the .jars on it?Then Chinese players can get chance to download GC and play it.We just upload and allow download your jar just  from your website and won't change it.
Sincerely.

**Comment by radfast** [comment]
Yes, you have our permission for this.
Thank you for making Galacticraft available for Chinese players.

**Comment by ETStareak** [comment]
Thank you very much!
