### ISSUE TITLE
Strange lighting/transparency bug

### ISSUE THREAD

**Issue by Slayer5934** [micdoodle8/Galacticraft#3453]
Minecraft version: 1.12.2
Galacticraft version: 4.0.1.169

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP, SMP

Galacticraft add-ons and other mods installed?
RSWires
QuackLib

Please provide screenshots / crash report / log as needed.
https://github.com/therealfarfetchd/HCTM/issues/23

**Comment by radfast** [comment]
These lights are not from Galacticraft - please explain why reporting here as I'm a bit confused

Which mod has these lights?

**Comment by Slayer5934** [comment]
The issue only occurs with galacticraft installed, the connected thread explains what happens. For some reason its not correctly rendering a lamp from RSWires when turned on, but perfectly fine when turned off. The mod author has asked me to bring the issue here to see if anything can be learned of it. 

"I have no idea why anything should break the lights, they are standard models that work exactly like vanillas
Maybe it doesn't like that the model is bigger than 1 block? But I can't really help that since that's how the lights are supposed to look..."

"Light off works perfect, renders color and all. Only when lit it messes up."

"So it's only the outer part then. No idea why it happens, it's just an ordinary box with a transparent texture. Please report this to the Galacticraft Core issue tracker"

**Comment by radfast** [comment]
More info please
- can you figure out if it happens all the time or only sometimes
- does it depend on what else is being drawn on the screen
- if you start a new Flat world and place down only that glowing block, no other (non-vanilla) blocks, do you still have the same issue
- do you have the same issue underground (no sky)
- is it the same on a space station, the Moon and all planets?

Normally this type of issue happens only when another block with a special display is also shown on screen (even if only a small corner of that other block is visible) - so the problem switches on and off as you move your mouse around.

Please also try updating Galacticraft to latest version 181, that might have fixed it already.

**Comment by Slayer5934** [comment]
Ill give you this information soon, probably tomorrow.

**Comment by radfast** [comment]
thanks for confirming, good to know it's fixed
