### ISSUE TITLE
Stuck in infinite loop (at least that's what I think)

### ISSUE THREAD

**Issue by HoneyFun** [micdoodle8/Galacticraft#3455]
By the way, I do have More Planets, but the crash report had micdoodle8.mods.galacticraft.core.energy.grid.NetworkFinder.loopAll(NetworkFinder.java:_line_) on the second line of the stack trace (the first line was net.minecraft.world.World.func_175625_s[World.java:2396]), so I believe this is a pure Galacticraft issue (the only More Planets blocks I use are energy-generating blocks). Also, the first time it says "micdoodle8.mods.galacticraft.core.energy.grid.NetworkFinder.loopAll(NetworkFinder.java:_line_)" the line it says the method occurred from line 67 of NetworkFinder.java, but every other "micdoodle8.mods.galacticraft.core.energy.grid.NetworkFinder.loopAll(NetworkFinder.java:_line_)" says the method's line it was called from is 72. The exception is "java.lang.StackOverflowError: Exception ticking world entities". The crash report is extremely long so I'm not gonna just put it in the issue. I'm going to attach it.
[crash-2018-06-26_11.16.00-server.txt](https://github.com/micdoodle8/Galacticraft/files/2142091/crash-2018-06-26_11.16.00-server.txt)

**Comment by radfast** [comment]
Thanks for reporting.  Sorry this issue occurred.  This is a strange one because this code is not changed in the past 12 months.

It's the grid of Aluminum Wires causing this.  Any chance of a screenshot of your wire network?

Could be linked with the More Planets blocks, I didn't look at @SteveKunG's code in detail on this.  Does More Planets also add new types of wire or other conductor?

**Comment by HoneyFun** [comment]
More Planets does not add any more types of wire or other conductor.
I cannot get a screenshot of the wire network. The server that crashes crashes faster than I can get on the server.

**Comment by HoneyFun** [comment]
I somehow fixed it by removing MP, MD8 & GC and then running a bunch of fill commands in order to unlag-up the server. You can remove this issue.

**Comment by marcus8448** [comment]
@HoneyFun If this is not an issue anymore you can close this issue.

**Comment by marcus8448** [comment]
@HoneyFun If this is not an issue anymore you can close this issue.

**Comment by marcus8448** [comment]
@HoneyFun If this is not an issue anymore you can close this issue.
