### ISSUE TITLE
Slimeling Egg hit with Mekanism Atomic Disassembler -> Crash

### ISSUE THREAD

**Issue by Kr0goth** [micdoodle8/Galacticraft#3459]
Modern Skyblock 3, Multiplayer Server

Accidentally hit a green Slimeling Egg with a Mekanism Atomic Disassembler.

Game crashed with crash report: 
[crash-2018-07-01_09.13.43-client.txt](https://github.com/micdoodle8/Galacticraft/files/2152855/crash-2018-07-01_09.13.43-client.txt)

After logging in to server, following crash occurs:
[crash-2018-07-01_09.24.14-client.txt](https://github.com/micdoodle8/Galacticraft/files/2152852/crash-2018-07-01_09.24.14-client.txt)

**Comment by MJRLegends** [comment]
I think this is a conflict with Quarks PoisonPotatoUsage updating for entities

**Comment by ziz** [comment]
I'm also having this issue. Crash after hitting the slimeling egg with a (tinker's construct cobalt) silk touch pickaxe:

[crash-2018-07-09_21.20.47-client.txt](https://github.com/micdoodle8/Galacticraft/files/2178818/crash-2018-07-09_21.20.47-client.txt)

Crash after re-logging in:

[crash-2018-07-09_21.33.13-client.txt](https://github.com/micdoodle8/Galacticraft/files/2178819/crash-2018-07-09_21.33.13-client.txt)

As yet unclear if my world is easily recoverable.

**Comment by ziz** [comment]
I ended up having to delete the Mars dimension, and then things went back to not-crashing.

**Comment by radfast** [comment]
This is the same issue as #3461.

As [posted there](https://github.com/micdoodle8/Galacticraft/issues/3461#issuecomment-408686817), I think the most likely cause is different mod versions (of some other mod) between client and server.  Or else another mod which changes mod DataParameters (which are part of vanilla Minecraft internally) in an unexpected way.

Please carefully check all your mods and configs are exactly the same between client and server.

If they are the same, it would help us to know:
(a) if the same issue occurs in single player
(b) which other mods you changed recently.

**Comment by radfast** [comment]
For clarification, it's highly unlikely that this is linked with the Mekanism Atomic Disassembler.  You'd probably have had the same issue with a pickaxe.

It could be caused by another mod which adds an "Age" parameter to all mobs.
