### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by Xx-plzhelpme-xX** [micdoodle8/Galacticraft#3460]
Minecraft version: 1.12.2
Galacticraft version: 4.0.1.181

Galacticraft add-ons and other mods installed? Galacticraft planets, Player API, render Player API

"The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Galacticraft Core (galacticraftcore)"

[crash-2018-07-01_15.09.09-client.txt](https://github.com/micdoodle8/Galacticraft/files/2153267/crash-2018-07-01_15.09.09-client.txt)

plz help idk whats goin on

**Comment by MJRLegends** [comment]
You've downloaded Galacticraft Planets from a site which has stolen it. Download from the official galacticraft website and then from curseforge or mod devs sites for any future mod besides Galacticraft

Checkout http://stopmodreposts.org/ as people shouldnt be allowed to repost mods on scam sites its illegal posting, And please download the browser plugins found near the bottom of http://stopmodreposts.org/get-involved/ to make sure your not helping these people!! #StopModReposts

**Comment by Xx-plzhelpme-xX** [comment]
ah it was that i got mcdoodlecore from somewhere else. thank you for your kind assistance
