### ISSUE TITLE
Spongeforge compatibility issue, crash while creating space stations.

### ISSUE THREAD

**Issue by Slayer5934** [micdoodle8/Galacticraft#3462]
Minecraft version:1.12.2
Galacticraft version:181

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Multiplayer

Galacticraft add-ons and other mods installed?
No, spongeforge.

Please provide screenshots / crash report / log as needed.
[crash-2018-07-02_13.38.24-server.txt](https://github.com/micdoodle8/Galacticraft/files/2156223/crash-2018-07-02_13.38.24-server.txt)

When creating a space station with spongeforge installed a crash occurs, this does not happen when going to other planets. More information will be provided as requested, thank you.

**Comment by Slayer5934** [comment]
Likely related to issue #3458

**Comment by radfast** [comment]
Appears to be an issue introduced in a recent Sponge version, I don't know which one.

Can you try rolling back to an older Sponge - even _much_ older?

It would be extremely helpful if you can identify the particular Sponge version which started to have this issue, then we can work with the Sponge developers to find an actual code fix.  Needs your help in identifying the version please, it's hard enough to identify the code to be fixed even if we do know the version.

**Comment by Slayer5934** [comment]
Haven't been able to find out any info..

**Comment by Slayer5934** [comment]
It looks like the issue is fixed in the latest recommended spongeforge version, Ill let you know for sure the issue is gone when I update my modpack but so far so good.

**Comment by Slayer5934** [comment]
You can close this, its fixed.

**Comment by TheQuadShot** [comment]
@Slayer5934 You can close it, since you opened it you and a developer are the only ones that can.
