### ISSUE TITLE
Rocket disappeares when trying to exit overworld and can't create stations

### ISSUE THREAD

**Issue by Ghostcat1717** [micdoodle8/Galacticraft#3463]
**Hi everybody!**

Minecraft version: 1.12.2
Galacticraft version:4.0.1.181

SMP

Galacticraft add-ons and other mods installed?Other mods: applied energetics 2, buildcraft, ComputerCraft, spongeforge, Ultimatecore

Please provide screenshots / crash report / log as needed.
 So my problem is that when I try to enter a rocket in the overwolrd, it will startm, but i the moment when it is supposed to switch dimensions, I get this message:

/**************************************************************************************************************************/
/*                                         Exception occurred during a PhaseState                                         */
/**************************************************************************************************************************/
/* Sponge's tracking system makes a best effort to not throw exceptions randomly                                          */
/* but sometimes it is inevitable. In most cases, something else triggered this                                           */
/* exception and Sponge prevented a crash by catching it. The following stacktrace                                        */
/* can be used to help pinpoint the cause.                                                                                */
/**************************************************************************************************************************/
/* The PhaseState having an exception: EntityTickPhase                                                                    */
/* The PhaseContext:                                                                                                      */
/*     - Owner: GCEntityPlayerMP['Ghostcat'/5128, l='world', x=33.50, y=1206.15, z=188.50]                                */
/*     - Source: EntityTier3Rocket['Tier 3 Rocket'/5532, l='world', x=33.50, y=1200.15, z=188.50]                         */
/* org.spongepowered.asm.util.PrettyPrinter@32d8b26a                                                                      */
/**************************************************************************************************************************/
/* StackTrace:                                                                                                            */
/* java.lang.NullPointerException: null                                                                                   */
/*     micdoodle8.mods.galacticraft.core.util.WorldUtil.getPossibleDimensionsForSpaceshipTier(WorldUtil.java:220)         */
/*     micdoodle8.mods.galacticraft.core.util.WorldUtil.getArrayOfPossibleDimensions(WorldUtil.java:366)                  */
/*     micdoodle8.mods.galacticraft.core.util.WorldUtil.toCelestialSelection(WorldUtil.java:1390)                         */
/*     micdoodle8.mods.galacticraft.api.prefab.entity.EntityTieredRocket.onReachAtmosphere(EntityTieredRocket.java:401)   */
/*     micdoodle8.mods.galacticraft.api.prefab.entity.EntitySpaceshipBase.func_70071_h_(EntitySpaceshipBase.java:251)     */
/*     micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket.func_70071_h_(EntityAutoRocket.java:400)           */
/*     micdoodle8.mods.galacticraft.api.prefab.entity.EntityTieredRocket.func_70071_h_(EntityTieredRocket.java:177)       */
/*     micdoodle8.mods.galacticraft.planets.asteroids.entities.EntityTier3Rocket.func_70071_h_(EntityTier3Rocket.java:84) */
/*     org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:173)                             */
/*     net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zlk000(WorldServer.java:2881)                          */
/*     net.minecraft.world.World.func_72866_a(World.java:4154)                                                            */
/*     net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)                                                 */
/*     net.minecraft.world.World.func_72870_g(World.java:1952)                                                            */
/*     net.minecraft.world.World.func_72939_s(World.java:6586)                                                            */
/*     net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2222)                                                */
/*     net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)                                        */
/*     net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)                              */
/*     net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)                                        */
/*     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)                                                 */
/*     java.lang.Thread.run(Unknown Source)                                                                               */
/*  Phases Remaining:                                                                                                     */
/*                                                                                                                        */
/* Minecraft : 1.12.2                                                                                                     */
/* SpongeAPI : 7.1.0-SNAPSHOT-d453c3e                                                                                     */
/* SpongeForge : 1.12.2-2705-7.1.0-BETA-3206                                                                              */
/* Minecraft Forge : 14.23.4.2705                                                                                         */
/**************************************************************************************************************************/

The whole current server log is attached.
[log.txt](https://github.com/micdoodle8/Galacticraft/files/2156852/log.txt)

**Comment by TheQuadShot** [comment]
Just checking, did you configure your server according to the wiki?
https://wiki.micdoodle8.com/wiki/Sponge

**Comment by Ghostcat1717** [comment]
@TheQuadShot Yes, and the server is running the recommended spongeforge version, (spongeforge-1.12.2-2705-7.1.0-BETA-3136.jar)
I want to mention too, that galacticraft was working fine. It just refused to launch rockets between systems when players are in it from one minute to the other.

**Comment by Ghostcat1717** [comment]
@TheQuadShot  Here's a video that shows what is really going on:

https://youtu.be/6LAh1SWxA7s

**Comment by Ghostcat1717** [comment]
UPDATE: I've deleted all DIM files from world except DIM1. I've even delted galacticraft's overworldMap file, but for some reason, galacticraft now doesn't allow me to build a space station. ( The **A space station can be built here!** text is not showing up)

**Comment by Ghostcat1717** [comment]
I've checked the bug with another player. He could create space stations... and magically after multiple restarts it seems like galacticraft is working again. So if someone has the same issue (It looks like **these steps worked me**): 

* Make sure you have the latest recommended version of galacticraft
  * Optional: If the server has spongeforge, check its version too.
* If the rocket can not escape from Earth, delete all DIM files( dimensions), except 1(Overworld) then restart the server
  * If still noting, backup the world\galacticraft\overworldMap\Overworld1536.bin file, then delete the bin file in the server. Stop the server, and put the bin file back.
