### ISSUE TITLE
ParaChest trying to be cast as an EnergyStorageModule - Server Crash

### ISSUE THREAD

**Issue by ZenithAstralis** [micdoodle8/Galacticraft#3464]
- Minecraft version: 1.10.2
- Galacticraft version: GalacticraftCore v4.0.1.177 and Galacticraft-Planets v4.0.1.177
- Multiplayer (SMP)
- Galacticraft add-ons and other mods installed?
LOTS. Modpack is ["Space Astronomy 2" v1.5.2](https://minecraft.curseforge.com/projects/space-astronomy-2)

```
02.07 21:17:23 [Server] Server thread/ERROR [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$WorldTickEvent@293c3443:
02.07 21:17:23 [Server] INFO net.minecraft.util.ReportedException: Exception while updating neighbours
02.07 21:17:23 [Server] INFO at net.minecraft.world.World.func_180496_d(World.java:540) ~[aid.class:?]
02.07 21:17:23 [Server] INFO at ic2.core.energy.grid.EnergyNetLocal.onTickStart(EnergyNetLocal.java:163) ~[EnergyNetLocal.class:?]
02.07 21:17:23 [Server] INFO at ic2.core.energy.grid.EventHandler.onWorldTick(EventHandler.java:60) ~[EventHandler.class:?]
02.07 21:17:23 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_93_EventHandler_onWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?]
02.07 21:17:23 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
02.07 21:17:23 [Server] INFO at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
02.07 21:17:23 [Server] INFO at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:282) [FMLCommonHandler.class:?]
02.07 21:17:23 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:694) [MinecraftServer.class:?]
02.07 21:17:23 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
02.07 21:17:23 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
02.07 21:17:23 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
02.07 21:17:23 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
02.07 21:17:23 [Server] INFO Caused by: java.lang.ClassCastException: micdoodle8.mods.galacticraft.core.tile.TileEntityEnergyStorageModule cannot be cast to micdoodle8.mods.galacticraft.core.tile.TileEntityParaChest
02.07 21:17:23 [Server] INFO at micdoodle8.mods.galacticraft.core.blocks.BlockParaChest.func_189540_a(BlockParaChest.java:126) ~[BlockParaChest.class:?]
02.07 21:17:23 [Server] INFO at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:463) ~[art$a.class:?]
02.07 21:17:23 [Server] INFO at net.minecraft.world.World.func_180496_d(World.java:519) ~[aid.class:?]
02.07 21:17:23 [Server] INFO ... 11 more

```
Full crash log: [crash-reports%2Fcrash-2018-07-02_21.17.23-server.txt](https://github.com/micdoodle8/Galacticraft/files/2157332/crash-reports.2Fcrash-2018-07-02_21.17.23-server.txt)

I'm downloading the latest release for 1.10.2 right now and will work on slapping it onto the server to see if it fixes it, but this happens when any one of my players logs in at the main base area in the overworld. We're all within about 5 chunks of one another so it all gets loaded at once. We've been playing for a little while, so it's something that's developed recently, because I think we'd have noticed the server crashing sooner than this otherwise, lol.

**Comment by ZenithAstralis** [comment]
No such luck. Updated and rebooted, same bug: [crash-report](https://github.com/micdoodle8/Galacticraft/files/2157378/crash-reports.2Fcrash-2018-07-02_22.17.07-server.txt)
`02.07 22:17:07 [Server] INFO Caused by: java.lang.ClassCastException: micdoodle8.mods.galacticraft.core.tile.TileEntityEnergyStorageModule cannot be cast to micdoodle8.mods.galacticraft.core.tile.TileEntityParaChest`

**Comment by ZenithAstralis** [comment]
UPDATE: The server was 'fixed' by rolling it back to before the error occured; which lost us a few days of work, but okay w/e. It happened again though, and I'm still not sure why. Any word on this, devs?

**Comment by radfast** [comment]
The game's saved map has a Parachest block but an Energy Storage Module tileentity at the same location.

The cause of this is some sort of corruption in the map - like a block changed but the map was not fully saved after it changed (maybe due to another mod crashing the game during the save), or else Forge changed the internal block ID for the Parachest between game sessions (maybe because you updated a mod, which added a new block in an update, causing all other mod block IDs to change?  Forge can normally cope with that, but not always, especially if you are also using other tools like MCEdit)

It's not a Galacticraft bug _per se_.

Thanks for alerting us, we can change the Parachest code so that it doesn't actually crash here, but your Parachest in that position might not work.

Your best bet is probably to delete that actual block.  It probably won't happen again if you fully delete it.

If that doesn't fix it, let us know and we can look at making a code change, but that might be a few days before the next version is available.
