### ISSUE TITLE
required dependency GalacticraftCore has errored

### ISSUE THREAD

**Issue by MrProton657** [micdoodle8/Galacticraft#3467]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.7.10
Galacticraft version: 3.0.12.463

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? 
SSP

Galacticraft add-ons and other mods installed?
GalaxySpace, GalacticGreg
Please provide screenshots / crash report / log as needed.
If I try to load into a SSP world or generate one, in the log is the following text:

 [Server thread/ERROR] [galacticgreg]: Skipping event FMLServerStoppedEvent and marking errored mod galacticgreg since required dependency GalacticraftCore has errored

[05/7/2018 13:43:54 PM] [Server thread/ERROR] [GalaxySpace]: Skipping event FMLServerStoppedEvent and marking errored mod GalaxySpace since required dependency

The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
[05/7/2018 13:43:54 PM] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.
full log: https://pastebin.com/m4F8eBDb
I have seen this error here: #2939 but I actually haven't any idea why this so is. And in the thread wasn't any suggestion.
Please help me as soon you can!

I would be very grateful to you!

MrProton657

**Comment by MJRLegends** [comment]
Update to latest version theres no need for you to be using like 40 version back from the latest, You cant expect old versions to work...

**Comment by MrProton657** [comment]
(SOLVED) Thank you! You have saved my day! the use of the newest galacticraft Version has fixed many Bugs and problems with my minecraft!
