### ISSUE TITLE
Galacticraft- Empty dungeons after defeating the boss once.

### ISSUE THREAD

**Issue by skoales** [micdoodle8/Galacticraft#3470]
AFTER DEFEATING THE BOSS ONCE, ALL DUNGEONS ARE EMPTY AND SO ARE CHESTS. 

This is a big problem! Beceasu now I can't get a tier 2 rocket schematics. :(, Don't worry it was just a test run. This wouldn't be that much of a problem if I would keep the schematics after putting it in nasa workbench, but you don't get schematics back :(. If I would keep the schematics then I could trade with villagers, but I can't :( 

This is also a big problem, because I wanted to make a moded vanilla server ( galacticraft of course).

?!Is there a way of reseting a dungeon?!

Minecraft version:1.12.2
Galacticraft version: don't know, installed it month ago (the latest version)

I'm playing single player in survival/creative ( with cheats on , it was a test run)

I have extra planets add on installed, but I don't think that that's a problem.

If you need screenshots or anything just ask.

**Comment by TheQuadShot** [comment]
Not a bug/dupe, Please search the database before filing, make sure it's "is:issue" else you will only see open bugs. Also please close this report.
https://github.com/micdoodle8/Galacticraft/issues/3010

https://wiki.micdoodle8.com/wiki/Treasure_Chest#Contents 

If you have other questions about the mod, you can check the Forums(come and join we're nice people!) and/or the Wiki
Forums: https://forum.micdoodle8.com/index.php
Wiki: https://wiki.micdoodle8.com/wiki/Galacticraft

**Comment by skoales** [comment]
This is so embarrassing, I just found out that my world was set to peaceful. When I post this I meant that all dungeons don't spawn a boss, but as you can't see I didn't realize my world was set to peaceful, thanks anyway, I will close this now.
