### ISSUE TITLE
Rendering screen crash immediately after loading galaxy map

### ISSUE THREAD

**Issue by Calvin-13** [micdoodle8/Galacticraft#3472]
I am unable to open the world after this due to the same error

Minecraft version: 1.12.2
Galacticraft version: 181

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?: SSP

Galacticraft add-ons and other mods installed?:
Addons:
- ExtraPlanets
- More Planets
- Planet Progression

Other mods:
- Buildcraft
- CTM
- Chisel
- CLibrary (coremod for Matter Overdrive)
- CodeChickenLib
- CoFHCore
- CoFHWorld
- Computercraft
- CustomNPCs
- IC2 (no addons)
- JEI
- Matter Overdrive
- NEI
- Norzeteus Space Extended (Note: not related to GC)
- OMLib
- Open Modular Turrets
- Open Modular Passive Defense

Crash report: https://pastebin.com/0ByABa5r

**Comment by MJRLegends** [comment]
Update Planet Progression, always make sure you have updated mods

**Comment by Calvin-13** [comment]
It's always the simplest problem, isn't it?
