### ISSUE TITLE
MO charging station crashes with GC aluminum wire.

### ISSUE THREAD

**Issue by gonenoculer5** [micdoodle8/Galacticraft#3475]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 
GalacticraftCore-1.12.2-4.0.1.181
Galacticraft-Planets-1.12.2-4.0.1.181
MicdoodleCore-1.12.2-4.0.1.181

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SMP
Galacticraft add-ons and other mods installed?
ExtraPlanets-1.12.2-0.4.0
MJRLegendsLib-1.12.2-1.1.4
Please provide screenshots / crash report / log as needed.
https://paste.dimdev.org/desobejeho.mccrash

**Comment by gonenoculer5** [comment]
https://github.com/MatterOverdrive/MatterOverdrive/issues/158

**Comment by radfast** [comment]
Thanks @gonenoculer5 - as I posted just now on the MO issue, I think the cause is likely on MO's side but I'm happy to help where we can.
