### ISSUE TITLE
Client crash!

### ISSUE THREAD

**Issue by prokopiy** [micdoodle8/Galacticraft#3486]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 4.0.1.181

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SMP

crash-log:
https://paste.dimdev.org/iwisebobij.mccrash

**Comment by dj3520** [comment]
Does not appear to be a Galacticraft crash, though I'm not familiar with "GalacticraftTweaker" perhaps try without that mod. Also there's been a surge of reports that stem from downloading the mod from an unofficial source, so do make sure you've used https://micdoodle8.com/mods/galacticraft/downloads

**Comment by TheQuadShot** [comment]
Galacticraft Tweaker is made by MJRLegends
https://github.com/MJRLegends/GalacticraftTweaker/issues

**Comment by radfast** [comment]
@prokopiy  why have you reported this to us?

This presumably is your text added:

>    I blame micdoodle8, radfast, author of Micdoodle8 Core.

Why do you think this is a Galacticraft-caused crash and not any of your other 40+ mods?

**Comment by QuantumStatement** [comment]
>I blame micdoodle8, radfast, author of Micdoodle8 Core

It's [VanillaFix](https://minecraft.curseforge.com/projects/vanillafix) addition to crash report

**Comment by radfast** [comment]
oh!  well VanillaFix got it wrong this time.  Maybe chose us because we are the only core mod.
