### ISSUE TITLE
androids still suffocate on the moon

### ISSUE THREAD

**Issue by lag42** [micdoodle8/Galacticraft#3487]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version:1.12.2
Galacticraft version:1.12.2-4.0.1.181

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP

Galacticraft add-ons and other mods installed?
matter overdrive

Please provide screenshots / crash report / log as needed.
https://imgur.com/a/2ygmXVX

**Comment by TheQuadShot** [comment]
Sorry, I don't understand a few things. What do you mean "still"? I can't find a bug about an android suffocating on/in moon/space. Also what mod is creating or turning you into an android?

**Comment by lag42** [comment]
matter overdrive, and they mentioned they would add support in an [old issue](https://github.com/MatterOverdrive/MatterOverdrive/issues/158) on matter overdrive's git, it just seems to have never shown up

**Comment by TheQuadShot** [comment]
Ok, Thanks! And thanks for linking the issues!

**Comment by radfast** [comment]
This change is already [coded](https://github.com/micdoodle8/Galacticraft/commit/75156ef959b0f5ac6ccba36ccae1c7e94eff2c0d) in Galacticraft.  It will go live in next build 182 whenever that comes.
