### ISSUE TITLE
Overworld mobs on Moon

### ISSUE THREAD

**Issue by Michael11562** [micdoodle8/Galacticraft#3489]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 4.0.1.181

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?

Single Player

Galacticraft add-ons and other mods installed?

Galacticraft Core
Galacticraft Planets
Inventory Tweaks
Just Enough Items
Xaero's Minimap
Buildcraft
Backpack
Mcdoodle8 Core
Forge

Please provide screenshots / crash report / log as needed.

So I updated my minecraft world from 1.11.2 to 1.12.2 so I could use some more mods, and when I loaded up the map it said I was missing repositories. I just clicked okay and went on to use my map. Well, when I went back to the moon all the mobs were overworld mobs with no helmets on them. Is there anything I can do to fix this issue? I guess I might just have to delete the old moon world and have the world generator generate a new one? To do that do I just go into the file and rename the DIM file to .old and have it gen the new one? This definitely isn't a compatibility issue. Unless you call switching from 1.11.2 to 1.12.2 that.

![2018-07-29_21 34 32](https://user-images.githubusercontent.com/41881142/43373371-4778d4e4-9377-11e8-8494-b5c951282e9a.png)

![2018-07-29_21 34 27](https://user-images.githubusercontent.com/41881142/43373376-4da6f0c6-9377-11e8-9634-376d4f3ce4fe.png)

**Comment by marcus8448** [comment]
> I was missing repositories

As in missing mods or as in what? I have never gotten a missing repositories error before... 
Can you provide a log?

**Comment by Michael11562** [comment]
Everything is alright now. I took my own advice and deleted the old DIM file for the moon and had it regen. Thanks for the response. I'd never gotten a missing repository error before either :)
