### ISSUE TITLE
Air lock video on wiki isn't available

### ISSUE THREAD

**Issue by RarePlutonian** [micdoodle8/Galacticraft#3490]
So this isn't a problem with the *game*, but the tutorial video for the air lock on the wiki(https://wiki.micdoodle8.com/wiki/Air_Lock) isn't available; now I ain't no big gae, so this isn't a problem for me, but some scrubs might need it to understand how to oxygen good.

The link to the vid is here:
https://youtu.be/VZHy46kZZ_M

**Comment by marcus8448** [comment]
Updated the video, should work now.

**Comment by RarePlutonian** [comment]
Thanks <3

**Comment by radfast** [comment]
thanks @marcus8448

**Comment by RarePlutonian** [comment]
Hello there,

I just signed the petition "European Parliament: Stop the
censorship-machinery! Save the Internet!" and wanted to see if you could
help by adding your name.

Our goal is to reach 4,121,433 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/5rqNsd6pX2

Thanks!
Liam
