### ISSUE TITLE
Random enchantments

### ISSUE THREAD

**Issue by PhysicalNova** [micdoodle8/Galacticraft#3503]
The enchantments found in dungeon chests are great, strong, but they don't fit together. For example, Efficiency III, Punch I, Unbreaking III and Depth Strider II. Illogical am I right ?
Minecraft version: 1.12.2
Galacticraft version:1.12.2-4.0.1.181

Single player (SSP)

Galacticraft add-ons and other mods installed? No addons. No mods that would mess it up.

Please provide screenshots / crash report / log as needed.
![2018-08-09_23 56 56](https://user-images.githubusercontent.com/40638280/43928194-4ce3f19a-9c30-11e8-8f18-bfc54e4f484b.png)

**Comment by PhysicalNova** [comment]
Will delete the post. It seems to be related with the game itself, as I've found random enhanted books in a stronghold.

**Comment by PhysicalNova** [comment]
This seems to be related to the game itself. Fixes#3503

**Comment by marcus8448** [comment]
Uh, @PhysicalNova can you close this saying "fixes #3503" does not work unless you do so in a commit.

**Comment by PhysicalNova** [comment]
fixes #3503

**Comment by marcus8448** [comment]
You have to click the "close issue" button beside the comment button.

**Comment by PhysicalNova** [comment]
Omg I'm so stupid >_<... Sorry. Thanks for letting me know how to do !
