### ISSUE TITLE
Air launching

### ISSUE THREAD

**Issue by PhysicalNova** [micdoodle8/Galacticraft#3504]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)
If you press space while being in a rocket (already launched), It will relaunch in midair. If it was launched by a controller, then it will act as if it was launched manually. 

Minecraft version:1.12.2
Galacticraft version:1.12.2-4.0.1.181

Single player (SSP)

Galacticraft add-ons and other mods installed? No

Please provide screenshots / crash report / log as needed.
can't sorry :/

**Comment by EzerArch** [comment]
That's an old bug. If I press space, the rocket slows down and resumes its ascend.

**Comment by PhysicalNova** [comment]
Exactly.
