### ISSUE TITLE
Galacticraft NASA Workbench SpongeForge FATAL on requesting GUI

### ISSUE THREAD

**Issue by Foxgreat** [micdoodle8/Galacticraft#3510]
**I am currently running**
- SpongeForge-3403: 
- Forge-2705: 
- Java Version: 1.8.0_181, Oracle Corporation 
- Operating System: Linux (amd64) version 4.15.0-24-generic
- 113 Plugins/Mods:

Hello there, i want to stay this here too!
I have an issue on my server. While i trying to call for NASA Workbench GUI from Galacticraft it sends FATAL error and not opening workbench from SpongeForge. In singlePlayer works fine, without spongeforge on server works fine too. 

Here's my crash from Debugging GC's screen.
https://gist.github.com/Foxgreat/49d84a99f0788421ac4ce3152bfea8d7

And full Debug and Latest logs (sry for MySQL errors, my bad, working on it)
[debug.log](https://github.com/SpongePowered/SpongeForge/files/2296676/debug.log)
[latest.log](https://github.com/SpongePowered/SpongeForge/files/2296677/latest.log)

SpongeForge issue https://github.com/SpongePowered/SpongeForge/issues/2386

**Comment by Foxgreat** [comment]
Getted that after updates from later version to 181 NASA workbench broken on exacly map

**Comment by radfast** [comment]
as the OP reported on the SpongeForge issue, it's a broken worldmap after multiple updates to the modpack
