### ISSUE TITLE
Galacticraft cause JEI error

### ISSUE THREAD

**Issue by HydrogenC** [micdoodle8/Galacticraft#3513]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: latest

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? SSP

Galacticraft add-ons and other mods installed? ExtraPlanets

Please provide screenshots / crash report / log as needed.
[crash-2018-08-23_10.53.20-client.txt](https://github.com/micdoodle8/Galacticraft/files/2312772/crash-2018-08-23_10.53.20-client.txt)

It crashes while starting up. If I remove Galacticraft, it doesn't crash ant more.

**Comment by radfast** [comment]
You are reporting this here based on "java.lang.OutOfMemoryError: GC overhead limit exceeded"?

That "GC" there means Garbage Collector, not Galacticraft.  Garbage Collector is a part of Java runtime.  Please do a simple search on Google before reporting an issue here.
