### ISSUE TITLE
Stuck on loading screen and moon temperature error

### ISSUE THREAD

**Issue by Mugiwaxar** [micdoodle8/Galacticraft#3516]
Minecraft version: 1.12.2
Galacticraft version: 4.0.1.181

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Tested on single and multiplayer

Galacticraft add-ons and other mods installed?
- ExtraPlanets
- More-Planets
- Ftb Revelation ModPack

------------------------------------------------------------------------------------------------

Hello,
I'm here for 2 problems:

First, when I go to another planet, I have that screen that freeze forever until I restart the game:
![screenshot](https://user-images.githubusercontent.com/4124999/44990611-dac0fe80-af91-11e8-96a6-0c1d780ba832.png)

And seconde, when I go to the moon, I die because of extremly low temperature.
And yes, I wear the thermal protection...
This only appen since I've added the ExtraPlanets mod.
You gonne say: "Open a issue to ExtraPlanet GitHub"?
It's done!  Here: [#347](https://github.com/MJRLegends/ExtraPlanets/issues/347)  and Here: [#348](https://github.com/MJRLegends/ExtraPlanets/issues/348), but it was useless...

Please, I love so much Galacticraft and ExtraPlanets!
Can you do something for me?

Thanks for the help

**Comment by Mugiwaxar** [comment]
Hello, and thanks for your help
For the first problem, its Aroma1997 that make that
For the seconde problem, I removed all mods exept galacticraft and Extra Planet, same issue, then, it's not a conflit...

**Comment by TheQuadShot** [comment]
Can you provide a log when it happens in the GC and EP only game? To get a log file you can force a crash by using the "F3+C" hold for 10 seconds and release, this should then crash the game and produce a log file. Please post that log file to pastebin or equivalent and provide a link to it.

**Comment by micdoodle8** [comment]
I'm going to need a log as Quad has mentioned... I'll re-open if one is provided.
