### ISSUE TITLE
Hydraulic Lift is not letting go of the player

### ISSUE THREAD

**Issue by MuteTiefling** [micdoodle8/Galacticraft#3519]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 4.0.1.177

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? SSP

Galacticraft add-ons and other mods installed? Extra Planets

When I get on the lift, I can go up and down without issues. However, there are a couple of problems.
1) It doesn't stop at any of the other platforms. If I want off, I just have to kind of scoot off at the right time.
2) When I am off, the platform continues to move with me as I change elevation (like jumping or climbing up blocks). It stays within the bounds of the lift blocks but will move up through other blocks to match my relative height.
3) Breaking the blocks once this occurs appears to cause other issues... I could not, for example, interact with any inventories after this occurred. 

Once I logged out and back in, the platform returned to its normal position. Strangely, however, I was stuck in Spectator mode and had to enable cheats to return myself to Survival mode. 

If it makes any difference, I was doing all of this in my Overworld Space Station dimension.

**Comment by PhysicalNova** [comment]
make multiple levels of hydraulic plateform. If you get out before it has finished its animation / move, the game doesn't like it. Maybe the devs should disable movement when on the moving plateform ?

**Comment by TheQuadShot** [comment]
Please download from the official site, you version numbers are incorrect, and out of date.
https://micdoodle8.com/mods/galacticraft/downloads

**Comment by teagan75** [comment]
I have downloaded from official site
GalacticraftCore-1.12.2-4.0.1.181
Galacticraft-Planets-1.12.2-4.0.1.181
MicdoodleCore-1.12.2-4.0.1.181

I too have the same issues as the OP. Going into creative or logging off and on fix the issue. I can go down the elevator just fine. It's only when I try to go up the elevator platform keeps going up.

**Comment by teagan75** [comment]
![2018-11-17_12 37 04](https://user-images.githubusercontent.com/12485764/48664543-aa9fdc80-ea65-11e8-9fac-e5ed374d470e.png)

**Comment by PhysicalNova** [comment]
Ho. That's strange :/

**Comment by PhysicalNova** [comment]
Please try the hydraulics platforms with only galacticraft installed (micdoodle core, galacticraft core and galacticraft planets). Maybe the addon is causing the problem.

**Comment by radfast** [comment]
Thanks for reporting.  You are not supposed to "scoot off" hydraulic platforms before they have finished moving.  If the platform motion did not finish yet, there can be these types of visual issues, i.e. platform moving with the player or even the Spectator Mode problem.

I will look at adding some failsafes, for example we can maybe force the platform motion to be counted as "finished" after some time.

**Comment by teagan75** [comment]
This happens even if I don’t move. I am not trying to get off. It happens every time in survival but not creative.

**Comment by teagan75** [comment]
Sorry life has been busy, but i just checked this with only Galacticraft, GalacticraftCore- and GC Planets vs. 1.12.2-4.0.2.210
This is when I am in the space station dimension. Could it be affected by the new gravity mechanic?

**Comment by PhysicalNova** [comment]
I don't think the gravity mechanics disturbs the platforms's behavior. If you create a new world and test the hydraulic platforms in the same conditions, is it still not working ? Maybe there's something with the world itself... Furthermore, can you make a screenshot with the coordinates (x, y and z in the F3 menu), maybe something is wrong with the place in the world. 
If the problem persists, please download the lastest version on the official site, there was one uploaded recently. Have a nice day !

**Comment by PhysicalNova** [comment]
I tested the hydraulics platforms in a rotating space station, and I haven't encountered any problems. I play in the 211 version for 1.12.2, so try updating the mod.

**Comment by marq08** [comment]
Playing SevTech Ages 3.2.3 with the newest version installed. Just encountered this exact bug with no way to leave spectator mode as it is a server with no admins available for a while.  I built exactly two platforms. When jumping to get the platform to lift it failed to lift. When I left the platform I was unable to interact with entities so I relogged. Upon relogging I am stuck in spectator.

**Comment by ROMVoid95** [comment]
<h1 align="center">
<a>Repository Unarchived for Capes List Updates Only</a>
</h1>
<h3 align="center">
Use the<a href="https://github.com/TeamGalacticraft/Galacticraft-Legacy/issues"> Galacticraft-Legacy </a>repository for new Issues
</h3>
<p> 
<div align="center">
<tt>⚠
<strong>PLEASE NOTE THE FOLLOWING REGARDING THE GALACTICRAFT-LEGACY REPO AND 1.12.2 UPDATES</strong>
⚠</tt>
</div>
<h3>1.12.2 Issues/Bugs Only</h3>
<blockquote><em>
<a href="https://github.com/TeamGalacticraft/Galacticraft-Legacy">Galacticraft-Legacy</a> is only for 1.12.2 updates and issues only. Issues submitted using older versions will be closed
</em></blockquote>
<h3>Still Using Galacticraft v4.0.2.280 or Lower?</h3>
<blockquote><em>
Make sure you update to the <a href="https://github.com/TeamGalacticraft/Galacticraft-Legacy">latest version available</a></em></blockquote>
