### ISSUE TITLE
Cannot Travel To Planets

### ISSUE THREAD

**Issue by TeaPvP** [micdoodle8/Galacticraft#3522]
Minecraft version:
sponge 1.12.2-2705-7.1.0-Beta-3438
Galacticraft version:
4.0.1.181
Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Multiplayer server
Galacticraft add-ons and other mods installed?
https://gyazo.com/9d8f2efc52a1874848e00de9d7c76812
Please provide screenshots / crash report / log as needed.
The server does not crash but won't let me go to planets 
My point of view : 

https://gyazo.com/14def5b30cb014bb809a83c35d2923ab

**Comment by MJRLegends** [comment]
you have dimension id conflicts

**Comment by MJRLegends** [comment]
also your mod list you provided is missing mods that your My point of view  screenshot shows you have

**Comment by TeaPvP** [comment]
> you have dimension id conflicts

so do i just replace dimension ids in the config to fix this??

**Comment by MJRLegends** [comment]
yeah but since your mod list isnt correct i dont know what mods you actually have to give you a idea what config to change

**Comment by MJRLegends** [comment]
Any chance you could send me a copy of your fml latest and latest log files?

**Comment by TeaPvP** [comment]
Sorry for slow replies 

Latest log : 
https://pastebin.com/5LCdFqrK

Fml latest : 
https://pastebin.com/AhkTGMq7

**Comment by MJRLegends** [comment]
Your issue is ` Tried to register dimension for body: Triton hit conflict with ID -69` you will need to change on of then mods to use different ids

**Comment by MJRLegends** [comment]
And can you send me your client versions of the logs too

**Comment by TeaPvP** [comment]
having issues pasting in logs into pastebin also i changed all the ids and then when i typed /dimensiontp the worlds all started downloadig and the server crashed and went down

**Comment by TeaPvP** [comment]
https://pastebin.com/FDVbahxg

**Comment by MJRLegends** [comment]
Thanks FYI i asked for the logs so i can tweak thing on my ExtraPlanets side :D

**Comment by TeaPvP** [comment]
np thanks for helping me btw

**Comment by radfast** [comment]
thanks @MJRLegends, I will close this
