### ISSUE TITLE
1.12.2 Galacticraft CRASH

### ISSUE THREAD

**Issue by wiqg** [micdoodle8/Galacticraft#3525]
So , recently i've downloaded galacticraft and played it for a while until i got interested in some addons for it . I downloaded Extra planets and Galaxy Space , but they both crash . Not exactly crash but , everytime i start the game and i type /dimensiontp nothing happens , i cant type in chat , right click something or anything , just walk around . And if i try to do something else it crashes . Also the Galaxy Space mod doesnt even add new planets or anything ,as if it doesnt even exist, just the default planets, why ? Please help me fix it .

**Comment by TheQuadShot** [comment]
None of your issues have anything to do with GC. Please go to the respective pages. So please close this report.
https://github.com/BlesseNtumble/GalaxySpace
https://github.com/MJRLegends/ExtraPlanets/issues

**Comment by radfast** [comment]
Generally not a good idea to try to play two different addons together.  Some people have made it work, but it may need config changes.
