### ISSUE TITLE
about a new style of spaceships(not rocket )

### ISSUE THREAD

**Issue by 110TE** [micdoodle8/Galacticraft#3528]
I love the astro miner so much that I think if we could drive it in space and mine ourselves it can be enjoyable. a 3*3*4 spaceship, with oxygen and electricity provides. can also be add different block to makes it have more function.(such as solar power, lights, auto drive or cargo )

**Comment by TheQuadShot** [comment]
The developers are very active in the forums, and ask that suggestions be posted there in the Suggestion section. So please close this bug report and file your idea there, Thank!
https://forum.micdoodle8.com/index.php

**Comment by 110TE** [comment]
I know, but I can't sign up in the forums , so if anyone copy this idea to forums I will delete it immediately,thank you :D

**Comment by EzerArch** [comment]
> I know, but I can't sign up in the forums

Why? Did you create an account? I can recover it. Or even create one if you're having issues.
