### ISSUE TITLE
remove steel recipe enderio 1.12

### ISSUE THREAD

**Issue by Celophy** [micdoodle8/Galacticraft#3532]
i have this problem: for an 1.12 modpack i want to change the steel recipe from the simple alloy smelter to the normal alloy smelter or just remove it. 

![2018-10-12_20 05 54](https://user-images.githubusercontent.com/41362064/46886213-83e4f980-ce5a-11e8-8857-c7e0cd727bbd.png)

or if it isn't possible to remove the ingot, (from extreme reactors). 
i tried mietweaker but it didn't work...

**Comment by TheQuadShot** [comment]
Why is this filed here? GC has nothing to do with EIO... Please close this or show what it has to do with Galacticraft

**Comment by Celophy** [comment]
woops... sorry
