### ISSUE TITLE
Crash when mining Venus Vapor Spout with Volcanic Pickaxe

### ISSUE THREAD

**Issue by Fireztonez** [micdoodle8/Galacticraft#3535]
When I try to mine a Vapor Spout on Venus with a Volcanic Pickaxe, the game crash. I try with and WIthout Silk touch, and it does the samething. I also try with Vanilla Diamound PIckaxe and there have no issue.

Minecraft version: 1.12.2
MicdoodleCore version: 4.0.1.181
Galacticraft Core version: 4.0.1.181
Galacticraft Planets version: 4.0.1.181
Extra-Planets version: 0.4.3
Forge version: 14.23.5.2768
Java version: 8 update 181

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Tested on server and single player, each time, the client crash, but the server doesn't.

Please provide screenshots / crash report / log as needed.
https://gist.github.com/Fireztonez/6db029911f39d0fa9ea94c4bac5eddc0

**Comment by spylor** [comment]
I have the same problem when destroying meteors.

**Comment by radfast** [comment]
Thanks to both for reporting.  We should be able to fix this fairly easily.

**Comment by radfast** [comment]
Should be fixed in next build 482.
