### ISSUE TITLE
No tooltips on mouse-over in thge Energy Storage Module

### ISSUE THREAD

**Issue by Fireztonez** [micdoodle8/Galacticraft#3538]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 4.0.1.181

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Single Player

Galacticraft add-ons and other mods installed?
ExtraPlanets 0.4.3
and a long list of other mods, if needed I can provide the complete list

Please provide screenshots / crash report / log as needed.
![no_tooltips](https://user-images.githubusercontent.com/19277301/47037522-251acb00-d14d-11e8-97e1-ad9b987c49cc.png)

If you need more information please let me know and I will give you the informations myou need.

Thank's for your mod, I really enjoy!
Fireztonez

**Comment by TheQuadShot** [comment]
What should the "tooltip" say? The pretty much tells you everything, doesn't it?

**Comment by Robijnvogel** [comment]
I think that he's talking about the Tooltip that gets shown when hovering over an item in any inventory.

**Comment by TheQuadShot** [comment]
Ok, got it... All tooltips are suppressed when you open the UI on the following GC blocks(no matter if it's "in" the block or the players inventory.):

Energy Storage Unit
Energy Storage Cluster
Coal Generator
Magnetic Crafting Table

**Comment by Fireztonez** [comment]
Yes all tootips are deleted...
But, in this case, the tooltips should indicate (as it always indicates when you mouse over in your inventory) how much power the internal battery contains on how much capacity. 

PS: As of course you can not see it, this armor is actually the Space Suite Chestplate with JetPack, from Extra Planet)

**Comment by radfast** [comment]
Thanks for the precise report.  As @TheQuadShot says, it appears to be an issue for several GC blocks, not too surprising as they use a common code base.  We'll take a look.

**Comment by micdoodle8** [comment]
As a not if anyone is looking back at this, I was only able to recreate this in the two Energy Storage GUIs in 1.8.9, but all 4 machines @TheQuadShot mentioned above in 1.12.2.
