### ISSUE TITLE
Map zoom glitch (EXTRA PLANETS INSTALLED, BUT NOT LIKELY CAUSE)

### ISSUE THREAD

**Issue by gnomed-by-steve** [micdoodle8/Galacticraft#3541]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2 with 1.13 Item Ids
Galacticraft version: 4.0.1.181

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
100% SSP

Galacticraft add-ons and other mods installed?
Extra planets is installed, but likely not the issue.
Also valkrien warfare.
Please provide screenshots / crash report / log as needed.

While i cant provide any screenshots, I will describe the issue:

Map screen when choosing planets (not the plain map for some reason) starts zooming in and out at light speeds, making everything un-selectable, only showing the button for one planet almost completely faded out.

I will attempt to find the issue by isolating the mod with other mods, though i heard this might be because of Valkyrien warfare, which i also got barley working.

**Comment by radfast** [comment]
If you uninstall _ExtraPlanets_ does everything work OK?

**Comment by MJRLegends** [comment]
I haven't got any issue reports for this so i can't say its a known issue... Maybe something else outside of GC and ExtraPlanets

**Comment by radfast** [comment]
OK I will keep an open mind then - @gnomed-by-steve if you can let us know what happened when you tested with / without other mods (including Valkyrien Warfare) then we can look at this some more.

If you tell us that there's an issue in Galacticraft when you have Galacticraft + _x other mod_ installed, then I will look at that.  But I need your help to identify which one I need to test.

**Comment by gnomed-by-steve** [comment]
ok, sorry for the late reply. life stuff and all that. While isolating certain mods (valkrien warfare, etc.) I found out that this was a problem with my severely outdated drivers. Thanks for tuning in to the issue, but the issue itself wasn't with galacticraft, but my dinosaur of a computer.
