### ISSUE TITLE
[Piracy] Galacticraft core is missing mods it depends on?

### ISSUE THREAD

**Issue by DeadBait** [micdoodle8/Galacticraft#3542]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 1.12.2

Single player (SSP)
Galacticraft add-ons and other mods installed?
Backpacks mod ,  bloodmagic, chameleon, chococraft, corailtombstone, forge (version 1.12.2, 14.23.1.2555), forge (installer (same version) ), galacticraft, guide api, hwyla, ichunuil,
inventorypets, inventory tweaks, journeymap, mantle, micdoodlecore, minecolonies, mo creatures, oprifine, sync mod, tinkers construct mod, tinkers mechworks mod, tree capitator.
Please provide screenshots / crash report / log as needed.

![fml-client-latest - notepad 10_28_2018 6_38_04 pm](https://user-images.githubusercontent.com/44556809/47622968-d9b7d380-dae1-11e8-81a6-5befbc567463.png)
![fml-client-latest - notepad 10_28_2018 6_38_12 pm](https://user-images.githubusercontent.com/44556809/47622969-d9b7d380-dae1-11e8-83ef-ff7a7078cd20.png)
![fml-client-latest - notepad 10_28_2018 6_38_25 pm](https://user-images.githubusercontent.com/44556809/47622970-d9b7d380-dae1-11e8-90c5-587df891524d.png)
![fml-client-latest - notepad 10_28_2018 6_38_56 pm](https://user-images.githubusercontent.com/44556809/47622971-d9b7d380-dae1-11e8-8b20-f9ee5f5143dc.png)
![fml-client-latest - notepad 10_28_2018 6_39_03 pm](https://user-images.githubusercontent.com/44556809/47622972-d9b7d380-dae1-11e8-9fd5-28b4f34deeed.png)
![fml-client-latest - notepad 10_28_2018 6_39_09 pm](https://user-images.githubusercontent.com/44556809/47622973-d9b7d380-dae1-11e8-9eda-109fef652a58.png)
![fml-client-latest - notepad 10_28_2018 6_39_24 pm](https://user-images.githubusercontent.com/44556809/47622974-d9b7d380-dae1-11e8-81fc-a53e8e7f5a3e.png)
![fml-client-latest - notepad 10_28_2018 6_40_21 pm](https://user-images.githubusercontent.com/44556809/47622975-d9b7d380-dae1-11e8-8696-60030897dc4f.png)
![fml-client-latest - notepad 10_28_2018 6_40_37 pm](https://user-images.githubusercontent.com/44556809/47622976-da506a00-dae1-11e8-9b22-171dcdd83637.png)
![fml-client-latest - notepad 10_28_2018 6_40_48 pm](https://user-images.githubusercontent.com/44556809/47622977-da506a00-dae1-11e8-9b45-f95f9930bc45.png)
![fml-client-latest - notepad 10_28_2018 6_36_49 pm](https://user-images.githubusercontent.com/44556809/47622978-da506a00-dae1-11e8-80d9-0d6538f0dbe6.png)
![fml-client-latest - notepad 10_28_2018 6_37_09 pm](https://user-images.githubusercontent.com/44556809/47622979-da506a00-dae1-11e8-8964-554216c17005.png)
![fml-client-latest - notepad 10_28_2018 6_37_21 pm](https://user-images.githubusercontent.com/44556809/47622980-da506a00-dae1-11e8-8176-3a62502414b7.png)
![fml-client-latest - notepad 10_28_2018 6_37_32 pm](https://user-images.githubusercontent.com/44556809/47622981-da506a00-dae1-11e8-83bc-3ec2e39ed04d.png)
![fml-client-latest - notepad 10_28_2018 6_37_55 pm](https://user-images.githubusercontent.com/44556809/47622982-da506a00-dae1-11e8-9c50-dd762aa02f9f.png)
![fml-client-latest - notepad 10_28_2018 6_38_39 pm](https://user-images.githubusercontent.com/44556809/47622983-e50aff00-dae1-11e8-8146-8ff44f0e8ed8.png)
![fml-client-latest - notepad 10_28_2018 6_40_00 pm](https://user-images.githubusercontent.com/44556809/47622984-e50aff00-dae1-11e8-99df-0f67e9f5eae9.png)
![fml-client-latest - notepad 10_28_2018 6_37_45 pm](https://user-images.githubusercontent.com/44556809/47622985-e50aff00-dae1-11e8-9e60-2a9e5dc4d78f.png)

**Comment by DeadBait** [comment]
Please help me!

**Comment by TheQuadShot** [comment]
You need to download the files from an official site, the version numbers are incorrect for the Galacticraft files.
https://micdoodle8.com/mods/galacticraft/downloads

**Comment by DeadBait** [comment]
Thanks

**Comment by marcus8448** [comment]
Also, next time can you please send the log/crash using [gist](gist.github.com) or [pastebin](pastebin.com) 
 as otherwise it's hard to read. :)

**Comment by radfast** [comment]
thanks @TheQuadShot @marcus8448
