### ISSUE TITLE
1.12.2 Can`t find Cargo Rocket Schematic.

### ISSUE THREAD

**Issue by BaxAndrei** [micdoodle8/Galacticraft#3543]
Minecraft version: 1.12.2
Galacticraft version: `GalacticraftCore-1.12.2-4.0.1.181 Galacticraft-Planets-1.12.2-4.0.1.181 MicdoodleCore-1.12.2-4.0.1.181`

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?: SSP

Galacticraft add-ons and other mods installed?:  `107 mods : buildcraftlib@7.99.18,treechopper@1.2.4,buildcraftenergy@7.99.18,guilib@$version,doggytalents@1.14.2.379,cofhcore@4.6.1,projecte@1.12-PE1.3.1B,thermalinnovation@0.3.1,reborncore@3.10.2.337,hammercore@2.0.2.3,jeibees@0.9.0.5,ctm@MC1.12.2-0.3.2.20,controlling@3.0.6,microblockcbe@2.6.0.79,ironbackpacks@1.12.2-3.0.8-12,projectred-illumination@4.9.1.92,cofhworld@1.3.0,betterbuilderswands@0.11.1,ftblib@5.3.0.56,waila@1.8.26,props@2.6.2,galacticraftplanets@4.0.1.181,redstonearsenal@2.6.1,jeresources@0.8.5.27,durabilityshow@5.0.0,malisisdoors@1.12.2-7.3.0,refinedstorage@1.6.5,malisiscore@1.12.2-6.4.0,ptrmodellib@1.0.3,crafttweakerjei@2.0.2,redstoneflux@2.1.0,buildcraftsilicon@7.99.18,gendustry@1.6.5.8,energyconverters@1.0.2.2,solarflux@4.14r,projectred-core@4.9.1.92,ic2@2.8.999,buildcraftbuilders@7.99.18,additionalpipes@6.0.0.8,buildcraftfactory@7.99.18,projectred-fabrication@4.9.1.92,projectred-transmission@4.9.1.92,projectred-exploration@4.9.1.92,projectred-transportation@4.9.1.92,FML@8.0.99.99,nonvflash@1.2.0,thermalexpansion@5.5.2,projectred-integration@4.9.1.92,buildcraftcompat@7.99.15,oredictinit@1.12.2-2.2.1.71,forgemultipartcbe@2.6.0.79,ic2-classic-spmod@0.0.0.0,zettaindustries@1.3,worldcontrol@1.0.18,codechickenlib@3.2.2.353,buildcraftcore@7.99.18,wailaharvestability@1.1.12,aroma1997sdimension@2.0.0.2.b86,ctgui@1.0.0,xray@1.4.0,jei@4.12.1.217,buildcrafttransport@7.99.18,nei@2.4.2,thermalcultivation@0.3.1,bibliocraft@2.4.5,thermalfoundation@2.6.1,bdlib@1.14.3.12,wawla@2.5.264,mcp@9.42,journeymap@1.12.2-5.5.2,naturescompass@1.5.1,aroma1997core@2.0.0.0,inventorytweaks@1.63+release.109.220f184,mystcraft@0.13.6.00,bonsaitrees@1.1.1,micdoodlecore@,crafttweaker@4.1.11,enderstorage@2.4.5.135,projectred-compat@1.0,forge@14.23.5.2770,customports@1b,buildcraftrobotics@7.99.18,chesttransporter@2.8.8,ironchest@1.12.2-7.0.52.837,minecraft@1.12.2,mousetweaks@2.8,thermaldynamics@2.5.3,yabba@1.1.2.28,chickenchunks@2.4.1.73,projectred-relocation@4.9.1.92,stevescarts@2.4.24.118,jeiintegration@1.5.1.36,quark@r1.5-130,jaopca@1.12.2-2.2.8.95,autoreglib@1.3-20,galacticraftcore@4.0.1.181,gendustryjei@1.0.2,wrapup@1.12-1.1.3,mrtjpcore@2.1.3.35,projectred-expansion@4.9.1.92,appleskin@1.0.9,chisel@MC1.12.2-0.2.1.35,minecraftmultipartcbe@2.6.0.79,paintingselgui@$version,chiselsandbits@14.26,torohealthmod@1.12.2-11,forestry@5.8.2.354`

PROBLEM: I have finished more than 14 dungeons (tier 2) and I have not found any Cargo Rocket Schematic.

**Comment by TheQuadShot** [comment]
just to confirm,
You are on mars searching, and you are not in creative or peaceful mode, correct?

**Comment by baxandrei** [comment]
On mars.
Survival mode (never creative).
Normal mode and sometimes easy.

**Comment by baxandrei** [comment]
Another 5 dungeons finished, no 'cargo rocket schematic', just Tier 3 Rocket and Astro Miner. That's ridiculous, out of 20 chests no cargo schematic ...
