### ISSUE TITLE
Aternos servers

### ISSUE THREAD

**Issue by Puginator9000** [micdoodle8/Galacticraft#3544]
i used to play galactic craft with my friends on the free server hoster 'aternos' they made an update and you can now only add mods on the website 'curse forge' so i'm asking you can you please add the mods to curse forge so we can play galactic craft on our Aternos server what ever you decide i just want to say thank you

**Comment by TheQuadShot** [comment]
This issue has been discussed at length for a very long time. It is not a valid use of a bug report, please close this and bring this issue up at/on the forums here:
https://forum.micdoodle8.com/index.php

**Comment by marcus8448** [comment]
See #3207 #2031 and #3450.

**Comment by radfast** [comment]
or ... ask Aternos to allow Galacticraft to be added?  Seems like an easier solution than asking us to change the way our whole mod is provided and updated.
