### ISSUE TITLE
Crash at its planet menu thing but before that it spazzes out 

### ISSUE THREAD

**Issue by X-39** [micdoodle8/Galacticraft#3545]
Minecraft version: 1.12.2
Galacticraft version: 4.0.1.181

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Single player

Galacticraft add-ons and other mods installed?
![mod list](https://user-images.githubusercontent.com/41589258/47941510-5386fd00-dee6-11e8-9091-38d8ca9c13d2.png)

Please provide screenshots / crash report / log as needed.
[crash-2018-10-02_19.17.02-client.txt](https://github.com/micdoodle8/Galacticraft/files/2544177/crash-2018-10-02_19.17.02-client.txt)

**Comment by X-39** [comment]
Ive updated my Driver but still doesnt work

**Comment by X-39** [comment]
also Disabled the splash.properties but still crashes

**Comment by marcus8448** [comment]
What exactly does this have to do with Galacticraft? Maybe try the [Forge Support Forum](http://www.minecraftforge.net/forum) for this error. Or please post a different crash report that shows that Galacticraft is the one causing the problem.

**Comment by X-39** [comment]
It has because it Only crashes at the Planet GUI (Galacticraft)

**Comment by X-39** [comment]
![stuck after spazzing out](https://user-images.githubusercontent.com/41589258/47951145-9384c900-df54-11e8-8328-330bf0385e68.png)

this happens when going onto it then it crashes the game without a crash log

**Comment by marcus8448** [comment]
Can you send your **full log** (not the crash log) instead? Minecraft will always make a logfile.

**Comment by X-39** [comment]
[2018-11-03-4.log.gz](https://github.com/micdoodle8/Galacticraft/files/2545132/2018-11-03-4.log.gz)

**Comment by marcus8448** [comment]
Can you try playing Minecraft with ONLY Galacticraft as I cannot reproduce this issue.

**Comment by X-39** [comment]
its whenever i type /dimensiontp
or when i use a rocket

**Comment by radfast** [comment]
You have Galacticraft add-ons including Extra Planets, Blank Planet and Space-X installed.

It's likely any issue you are having is connected with one of those (or _maybe_ the combination, like they cannot be played together).

Like @marcus8448 already said, please try playing with only Galacticraft and other non-space mods - not any of the add-ons.  If that solves the issue then you need to figure out which add-on is causing it, and report it to that add-on author - not here.

**Comment by MJRLegends** [comment]
Seems from looking at this post https://support.feed-the-beast.com/t/failed-on-initialisation/39050 ram usage is the issue. As the crash log @X-39 provided matches the one in the post

**Comment by radfast** [comment]
thanks @MJRLegends  -  so @X-39 please give the game more RAM, or remove some mods, or try a RAM-saving mod like FoamFix.
