### ISSUE TITLE
Moon Rock and Moon Copper Ore share the same texture

### ISSUE THREAD

**Issue by RavenChan1023** [micdoodle8/Galacticraft#3546]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 4.0.1.181

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? Singleplayer Survival

Galacticraft add-ons and other mods installed? Galacticraft Planets, Galacticraft Core, Micdoodle Core, Uncrafting Table, Armor Chroma, Armor Plus, Backpacks, Baubles, BetterBedrockGen, Carbonado, Classic Combat, Dynamic Surroundings, Enhanced Armaments, Extended Days, Faster Ladder Climbing, Felling, Gravel Miner, Inventory Tweaks, Just Enough Items/Not Enough Items, Leather Works, MAGE, Traverse, PrimalCore, Real First-Person Render, Sound Filters, Spectrite, Stacksize, Vanilla Fix, Wither Skeleton Tweaks, World Tooltips and Xaero's Minimap are all the mods I have installed.

Please provide screenshots / crash report / log as needed.

As the title states, for whatever reason, the texture for Moon Rock and the moon's Copper Ore are the same. I'm providing a gif that shows me switching between the two items to show that the texture is the same.

![galacticraftrockandore](https://user-images.githubusercontent.com/37986598/47970021-8267b500-e045-11e8-9cdb-ec7608b30aff.gif)

**Comment by micdoodle8** [comment]
Should be fixed in the next build.
