### ISSUE TITLE
Crash whenever rocket below 0 or above 255 with cubic chunks installed (Including after rocket launch)

### ISSUE THREAD

**Issue by wingwisher** [micdoodle8/Galacticraft#3549]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2 forge version 14.23.5.2772
Galacticraft version: 1.12.2-4.0.1.181

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Single player

Galacticraft add-ons and other mods installed?
No Galacticraft add-ons, the only other mods are cubic chunks and playerapi

Logs of crashes for both above 255 and below 0 respectively:
https://paste.ubuntu.com/p/8mFCCMKbwj/
https://paste.ubuntu.com/p/3vCm76sS2z/

Log of crash for above 255 due to having been launched:
https://paste.ubuntu.com/p/q6fssCsdq4/

I did test and there are no issues with galacticraft bosses being outside of that range, haven't tested with any other vehicles (when trying to get unmanned rockets to launch to test it just maxes out my GPU usage without actually doing anything)

**Comment by micdoodle8** [comment]
Thanks for the detailed report, and sorry for the delay in fixing the issue. This should be solved in the next build.
