### ISSUE TITLE
[Sponge] Unable to launch to planet

### ISSUE THREAD

**Issue by Rcrafte22** [micdoodle8/Galacticraft#3554]
Minecraft version:1.12.2 Forge 14.23.5.2772
Galacticraft version:4.0.1.181
SMP（Use sponge server）

Galacticraft add-ons and other mods installed?
NO
-----------------------------------------------------------------------------------------------------------
Try to launch to another planet, in the planet map interface, you can't click the launch button.
The server version I am using: spongeforge-1.12.2-2768-7.1.4

**Comment by manticorex** [comment]
Minecraft Version: 1.12.2-forge1.12.2-14.23.5.2768
Galacticraft Version: 4.0.1.181
Sponge Version: spongeforge-1.12.2-2768-7.1.4

I can confirm this problem.
I have the exact same problem. First i fly with the rocket into the air. After that i choose a planet where to launch, try to hit the launch button and if i did, nothing happens. There are no error messages about this problem after i hit the launch button.

I tried this with other mods, and with no other mods and with a completly empty new server without any other mods, just with the three galacticraft JARs and the spongeforge JAR.

Always the same problem, hope you can fix this :)

**Comment by Rcrafte22** [comment]
@manticorex 
Thank you very much!
I don't know what chunk loader is.
Can you tell me what this is?

**Comment by TheQuadShot** [comment]
You can use a Launch Controller as one, or use a mod/util to keep the [chunks](https://minecraft.gamepedia.com/Chunk) loaded.

**Comment by Rcrafte22** [comment]
@radfast 
1.Try running on another server and it works fine.
2.Sorry,I don't have time to do that right now. I'll try later.
3.The old sponge version(1.12.2-2705-7.1.0-BETA-3361) works fine.The issue should occur on the sponge in Froge version 2768.

**Comment by radfast** [comment]
Thanks, that's very helpful - so it's between Sponge 7.1.0 and 7.1.4

**Comment by Rcrafte22** [comment]
@radfast 
I did further tests.
I narrowed down the range of versions that had problems.
Versions before Sponge1.12.2-2768-7.1.0-BETA-3483 were working normally.
I turned on the output debugging information in the configuration file, and there was no output when I clicked the Launch button.

**Comment by manticorex** [comment]
I tried also with some configuations.
Tried without Sponge and it worked fine.
But with Sponge without any other mods installed it didnt worked.

**@radfast:** So what does it mean right now? Do we have to report taht to Sponge or do you report that to Sponge?

**Comment by Rcrafte22** [comment]
@manticorex 

Oh, sorry, I forgot that.
I haven't reported it to the sponge yet.
May I trouble you to report it to the sponge?

**Comment by Rcrafte22** [comment]
@manticorex 
all right.
Later I'll report to the sponge.

**Comment by spylor** [comment]
I have the same reports atm. Also using that Sponge version.

**Comment by JoakimAlt2** [comment]
Have any solutions been found?

**Comment by ROMVoid95** [comment]
No longer an issue using the latest versions of forge/spongeforge. Closing
