### ISSUE TITLE
Ability to ignore oxygen and temperature by android player

### ISSUE THREAD

**Issue by Tortyash** [micdoodle8/Galacticraft#3559]
If it's possible I would like to don't worry about some organic stuff like oxygen and body heating when I play as android (maybe it's more in part of MO, but they didn't made that for 3 years)

**Comment by radfast** [comment]
Please state your **exact** Galacticraft and Matter Overdrive versions.

Galacticraft is already coded so that Androids ignore oxygen and temperature, in all recent versions.

**Comment by radfast** [comment]
My apologies - if you are using the latest Galacticraft 1.12.2 v181, it looks like [this fix](https://github.com/micdoodle8/Galacticraft/commit/75156ef959b0f5ac6ccba36ccae1c7e94eff2c0d) is not yet included.  This will be picked up in the next build 182, some time in the next few days.
