### ISSUE TITLE
Game crashes on null pointer exception in micdoodle8.mods.galacticraft.core.network.NetworkUtil.encodeData(NetworkUtil.java:156)

### ISSUE THREAD

**Issue by athompson92** [micdoodle8/Galacticraft#3560]
In game notes: Character is on moon in oxygen sealed room with sensor goggles on.  The game crashed as soon I a equipped the sensor goggles and now will not finish loading the save long enough for me to remove them.

Minecraft version:  Forge 1.12.2-14.23.5.2784
Galacticraft version: 1.12.2-4.0.1.181

Single player

Any Galacticraft add-ons installed? None, just vanilla galacticraft

Please provide screenshots / crash report / log / full modlist as needed

Mod list
ActuallyAdditions-1.12.2-r141
CodeChickenLib-1.12.2-3.2.2.353-universal
GalacticraftCore-1.12.2-4.0.1.181
Galacticraft-Planets-1.12.2-4.0.1.181
jei_1.12.2-4.12.1.217
JourneyMap-Mod-1.12.2-Unlimited
MicdoodleCore-1.12.2-4.0.1.181
NotEnoughItems-1.12.2-2.4.2.240-universal
Trapcraft-1.12-v2.4.3a-universal
VeinMiner-1.12-0.38.2.647+b31535a
xray-1.12.2-1.5.0
[crash-2018-12-01_11.03.14-server.txt](https://github.com/micdoodle8/Galacticraft/files/2636284/crash-2018-12-01_11.03.14-server.txt)
[crash-2018-12-01_11.44.37-server.txt](https://github.com/micdoodle8/Galacticraft/files/2636285/crash-2018-12-01_11.44.37-server.txt)
[crash-2018-12-01_10.56.18-server.txt](https://github.com/micdoodle8/Galacticraft/files/2636286/crash-2018-12-01_10.56.18-server.txt)

**Comment by athompson92** [comment]
Better spot for the crash report logs:
https://paste.ubuntu.com/p/x7SDCzH5WM/
https://paste.ubuntu.com/p/Vk5Kw73KGg/
https://paste.ubuntu.com/p/VB4NWJ3jvq/

**Comment by radfast** [comment]
thanks for reporting, we'll take a look.
