### ISSUE TITLE
o2 bubble not working after death

### ISSUE THREAD

**Issue by spaceboy01218** [micdoodle8/Galacticraft#3561]
Minecraft version:1.10.2
Galacticraft version: many, including 179 and 178
hi, I have been playing with galacticraft for a while and I have a base on the moon. not too far, but not just starting either. I have ic2, MFR, and extra planets along with some others. I can provide the full modlist if needed. anyway, I was playing on a LAN with my friend. we had a weird setup, in that one of us has to use an XBOX 360 controller to play and we use 2 copies of Minecraft at the same time, so it doesn't even need internet. but my friend was on "earth" and I was on the moon, with an o2 bubble sustained by a windmill. I had plenty of leaves around my oxygen collector, and the bubble deployed and worked fine. then when I die, the bubble doesn't work and I start taking damage. then it wont work until I reload, which means restarting Minecraft because it crashes on save and quit. otherwise, it seems to work. haven't tested the room pressurizing block though, hopefully that doesn't happen with that.

**Comment by micdoodle8** [comment]
Should be fixed in the next build. Thanks!
