### ISSUE TITLE
Volcanic Pickaxe causes GCEntityClientPlayerMP crash.

### ISSUE THREAD

**Issue by VasVadum** [micdoodle8/Galacticraft#3566]
Minecraft version: v1.12.2
Galacticraft version: 1.12.2-4.0.1.181

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Single Player.

Any Galacticraft add-ons installed?
Planets
More Planets

Please provide screenshots / crash report / log / full modlist:
https://pastebin.com/mmzHpUss
Modlist is inside crash log.

This appears to be the related line to the crash (according to a friend) ;
https://github.com/micdoodle8/Galacticraft/blob/MC1.12/src/main/java/micdoodle8/mods/galacticraft/planets/venus/items/ItemVolcanicPickaxe.java#L153

A special note:
I'm using Twitch to create a mod pack, unfortunately Galacticraft isn't a part of Twitch's options for installing as a mod and receiving automated updates, please look into this at some point so that I can obtain updates to your mod without manually looking each time.

**Comment by micdoodle8** [comment]
Thanks, should be fixed in the next build.
