### ISSUE TITLE
Weird server crash

### ISSUE THREAD

**Issue by TacticalUniverse** [micdoodle8/Galacticraft#3569]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version:  1.12.2-4.0.1.181

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? SMP

Any Galacticraft add-ons installed? please list all
Extra Plants
MJRLegneds Lib

Please provide screenshots / crash report / log / full modlist as needed
https://pastebin.com/abGiuZkT

**Comment by micdoodle8** [comment]
The link to the crash report you posted doesn't work anymore. Do you still have the log?

**Comment by TacticalUniverse** [comment]
No I don't have the crash report anymore as I normally expect my post to be answer with a day or two of posting and that's why the crash log disappeared off Pastebin
