### ISSUE TITLE
Planet select GUI issue when using multiverse

### ISSUE THREAD

**Issue by KevinMagers** [micdoodle8/Galacticraft#3571]
Minecraft version: 1.7.10
Galacticraft version: 3.0.12

Multiplayer
Galacticraft planets 3.0.12
search "The 1.7.10 pack" on technic to get modlist

I'm running the 1.7.10 pack from the technic launcher and I'm running the server with Thermos 1.7.10-1614. Once I install multiverse, galacticraft planet select GUI bugs out when selecting anything other than overworld or satellite. I've been able to manually go to some planets/moons via mv tp to get them to start generating/loading and it will work to fix the gui issue for the planet loaded, but this is only temporary fix. the issue starts all over once the server restarts. I know this has to do with how the planets are load/registered between different mods/ plugins but I'm unsure of the best way to keep them loaded so that the GUI does not omit the launch button
I've already tried /gckeeploaded, does not seem to change anything other than the config file
![guierror](https://user-images.githubusercontent.com/14279193/50126999-dd8bea80-0234-11e9-9e38-eb35923f0fc7.PNG)

**Comment by MJRLegends** [comment]
Dimension id conflict. Configure your configs. Putting mods in a folder and pressing launch isnt going to work.

**Comment by BlesseNtumble** [comment]
Extra Planets map, not GC3.

**Comment by MJRLegends** [comment]
@KevinMagers please can i have a copy of your server and client logs after getting this issue

**Comment by micdoodle8** [comment]
The client logs will be particularly useful here, it looks like a matrix stack over/underflow.

**Comment by micdoodle8** [comment]
I'll re-open this if the logs are uploaded. It also seems to be the same issue as #3596.
