### ISSUE TITLE
i need help in texture

### ISSUE THREAD

**Issue by yasscraft03** [micdoodle8/Galacticraft#3573]
hello guys i have a glich . i cant see the moon when i land on it and i cant see the space station too my minecraft version is 1.5.2 and the voltz is 2.0.4 . Plz help me

![2018-12-18_06 32 37](https://user-images.githubusercontent.com/45970606/50157765-23719e80-0287-11e9-84fd-c0305544cdab.png)
![2018-12-18_06 32 38](https://user-images.githubusercontent.com/45970606/50157767-23719e80-0287-11e9-921b-fd18998b6e1a.png)
![2018-12-18_06 32 38_2](https://user-images.githubusercontent.com/45970606/50157768-240a3500-0287-11e9-9d2e-8f938f662b62.png)
![2018-12-18_06 32 39](https://user-images.githubusercontent.com/45970606/50157770-240a3500-0287-11e9-91f1-d2d89b9629b9.png)
![2018-12-18_06 32 39_2](https://user-images.githubusercontent.com/45970606/50157771-240a3500-0287-11e9-89ff-7fae313bc94f.png)
![2018-12-18_06 32 39_3](https://user-images.githubusercontent.com/45970606/50157772-24a2cb80-0287-11e9-8a68-3602e08386cd.png)
![2018-12-18_06 32 39_4](https://user-images.githubusercontent.com/45970606/50157773-24a2cb80-0287-11e9-96fb-bda4c9a3fc7d.png)
![2018-12-17_05 04 37](https://user-images.githubusercontent.com/45970606/50157774-24a2cb80-0287-11e9-91b0-3d1935076c9f.png)
![2018-12-18_06 32 22](https://user-images.githubusercontent.com/45970606/50157775-253b6200-0287-11e9-86bd-47d73a9ce968.png)
![2018-12-18_06 32 24](https://user-images.githubusercontent.com/45970606/50157776-253b6200-0287-11e9-8bc0-cd3558b8dc12.png)
![2018-12-18_06 32 27](https://user-images.githubusercontent.com/45970606/50157777-253b6200-0287-11e9-9695-e6dd9865d661.png)
![2018-12-18_06 32 28](https://user-images.githubusercontent.com/45970606/50157780-25d3f880-0287-11e9-8665-65c6c93d267d.png)
![2018-12-18_06 32 31](https://user-images.githubusercontent.com/45970606/50157781-25d3f880-0287-11e9-9ef9-e55529b76be5.png)
![2018-12-18_06 32 35](https://user-images.githubusercontent.com/45970606/50157782-25d3f880-0287-11e9-81f3-4339c98a3cd3.png)

**Comment by HoeenCoder** [comment]
Are you trying to say you can't see the moon, while your _on_ the moon? (You can't see the moon in the sky while on it because its under your feet instead).
As far as I know (correct me if i'm wrong), space stations do not appear in the sky from any other planet/dimension.

**Comment by HoneyFun** [comment]
I think he's trying to say that he can't see the moon when he's on the moon. In the first screenshot, you see stars and then suddenly they stop. I think where they stop is where the moon should've been rendering itself.

**Comment by HoneyFun** [comment]
Plus, look at the map. The player is definitely on the moon.

**Comment by marcus8448** [comment]
Is Galacticraft for MC 1.5.2 still supported?

**Comment by micdoodle8** [comment]
Sorry, but it's been at least 4 years since this minecraft version was supported, and I'm not sure what the issue is anyway. You're not intended to see the moon nor your space station while you're on the moon.
