### ISSUE TITLE
Error in advancementloading (due to translation)

### ISSUE THREAD

**Issue by dierke9** [micdoodle8/Galacticraft#3581]
When trying to open a world the game chrashes when loading in the advancements this is because it cannot find the Moon dimension. This only happens when changing the language (When testing on English it worked the chrash happened wih tests on both Russian and German)

Minecraft version: 1.12
Galacticraft version: 4.0.1.184

Single player (SSP)

Any Galacticraft add-ons installed?
- extraplanets

Please provide screenshots / crash report / log / full modlist as needed
https://gist.github.com/dierke9/4ce1ee20cbbe0fb13b2c61c92dab20b2 <-- Gist containing the error (full log)
https://gist.github.com/dierke9/91988b3e2709c6092b722411ea0fcc63 <-- Gist containing chrashlog

**Comment by Voknehzyr** [comment]
@micdoodle8 So, when the new release will be ready? Or there's no info about that?
