### ISSUE TITLE
[1.12.2] Damage Sources: 'anvil' & 'fallingBlock' bypasses the Shield Controller for Helmets.

### ISSUE THREAD

**Issue by Z-Tunic** [micdoodle8/Galacticraft#3591]
Minecraft: 1.12.2
Forge: 14.23.5.2795

Mods: 3
GalacticraftCore-1.12.2-4.0.1.184
Galacticraft-Planets-1.12.2-4.0.1.184
MicdoodleCore-1.12.2-4.0.1.184

-----

While getting crushed by an anvil is normally unlikely & such, I was wondering where my helmet went after messing around with anvils. I also noticed it happening with anything that uses the 'fallingBlock' damage source.

![](https://cdn.discordapp.com/attachments/377171551155650560/530280920436047882/anvilfallingblockhelmetshieldcontroller.PNG)
On the left without the Shield Controller... both sources damages your armor. On the right with the Shield Controller... only your Helmet takes damage. Diamond Armor set was brand new during both tests.

For testing outside a survival world that I play on... I used the vanilla anvil block since that deals the 'anvil' damage source. Then I used a mod called 'Weather, Storm & Tornados' which when the weather gets bad it'll start to hail and if you get bashed in the head by the hail... it deals the 'fallingBlock' damage source. These are the only damage sources that bypasses the Shield Controller... as far as I'm aware.

**Comment by micdoodle8** [comment]
I'm impressed with your investigative work :)

Thanks, will be fixed in the next build. Make sure you update both GC and MicdoodleCore or you'll probably get a crash when you receive anvil/falling block damage.
