### ISSUE TITLE
Crash with MicdoodleCore

### ISSUE THREAD

**Issue by Dimalav567** [micdoodle8/Galacticraft#3595]
Singleplayer
Minecraft version:1.12.2.
GC version:4.0.1.184
GC Addons:More Planets, Galaxy Space
Hello,when world loaded minecraft crashed, i solved this when delete galacticcraft and MicdoodleCore. I think this reason.
[crash-2019-01-05_13.33.45-server.txt](https://github.com/micdoodle8/Galacticraft/files/2729422/crash-2019-01-05_13.33.45-server.txt)

**Comment by BlesseNtumble** [comment]
delete advancement folder in GalacticraftCore.jar/assets and GalacticraftPlanets.jar/assets

**Comment by Dimalav567** [comment]
> delete advancement folder in GalacticraftCore.jar/assets and GalacticraftPlanets.jar/assets

**Comment by Dimalav567** [comment]
> delete advancement folder in GalacticraftCore.jar/assets and GalacticraftPlanets.jar/assets

**Comment by Dimalav567** [comment]
Thank it's work
