### ISSUE TITLE
Adjacent Display Screens don't connect with each other or work

### ISSUE THREAD

**Issue by Lorsieab2** [micdoodle8/Galacticraft#3599]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: **1.12.2**
Galacticraft version: **1.12.2-4.0.1.185**
Forge Version: **14.23.5.2806**

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? **SSP**

Any Galacticraft add-ons installed? please list all: **None**

Please provide screenshots / crash report / log / full modlist as needed

**https://pastebin.com/sSSL3cci**

If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft) 

I was messing around with the display screens, and I found that I couldn't connect multiple screens together. I tried a 4x2, 6x5, 3x2 and 2x2 configuration, and none of the screens would connect or turn on when right clicking them. When exiting and reloading the world, some screens were on, but were on different channels. However, just one display screen works fine.
This happens both with a telemetry unit and without one.
The only mods I have are Galacticraft core, Micdoodle8 core and Galacticraft Planets downloaded from the official website.

**Comment by micdoodle8** [comment]
Thanks for the detailed report. This should be fixed in the next build.
