### ISSUE TITLE
[SUGGESTION] 1.13 Port

### ISSUE THREAD

**Issue by Romsik788** [micdoodle8/Galacticraft#3600]
I propose to create a branch for 1.13 and start porting GC and micdoodleCore. Forge 1.13-pre is already available (but only on github :D). https://github.com/MinecraftForge/MinecraftForge/tree/1.13-pre

**Comment by SteveKunG** [comment]
It not stable yet, since I've test with it. Still have a lots of bug and weird crash.

**Comment by micdoodle8** [comment]
Noted, but I'm going to wait a little while longer till it's stable. Could be a week, could be a month. I will try to find time for the port though.
