### ISSUE TITLE
Crash (ConcurrentModificationException)

### ISSUE THREAD

**Issue by Freebi85** [micdoodle8/Galacticraft#3602]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version:1.12.2
Galacticraft version:1.12.2-4.0.1.181

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?: SSP

Any Galacticraft add-ons installed? please list all: Extra Planets

Please provide screenshots / crash report / log / full modlist as needed
https://paste.dimdev.org/asifotowis.mccrash

**Comment by MJRLegends** [comment]
`at com.rwtema.extrautils2.items.ItemUnstableIngots.checkForExplosion(ItemUnstableIngots.java:192)`

Your crash has nothing to do with Galacticraft

**Comment by Freebi85** [comment]
ok im sorry.
