### ISSUE TITLE
Enhancement - Dynamic Surroundings integration

### ISSUE THREAD

**Issue by EngineerXL** [micdoodle8/Galacticraft#3603]
It would be nice to integrate this two mods. DynSur cfg can't solve all probllems - sword swing, tool changing e.t.c

**Comment by MJRLegends** [comment]
https://forum.micdoodle8.com/index.php?threads/dynamic-surroundings-config-files-for-galactic

**Comment by EngineerXL** [comment]
I'm already using it, but some sounds still active in vacuum

**Comment by TheQuadShot** [comment]
Are you wearing a Frequency Module? If you are, you Should "hear" things.
https://wiki.micdoodle8.com/wiki/Frequency_Module

**Comment by EngineerXL** [comment]
No, I'm not wearing it

**Comment by micdoodle8** [comment]
Sorry, we don't take suggestions in the issues list. There's a suggestions area on the forum that I look through when the mod is in a stable state.
