### ISSUE TITLE
/gchouston confirm requires OP

### ISSUE THREAD

**Issue by Blayyke** [micdoodle8/Galacticraft#3604]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version:

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?: SMP

Any Galacticraft add-ons installed? GalaxySpace

Please provide screenshots / crash report / log / full modlist as needed
https://i.imgur.com/VIbkZPA.jpg
The /gchouston confirm command acts as if the command is being performed on another player and denies it for people without operator as they cannot perform the command on other players.

If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft)

**Comment by Blayyke** [comment]
ah heck. thanks lol

**Comment by MJRLegends** [comment]
Lol
