### ISSUE TITLE
Issues from log file

### ISSUE THREAD

**Issue by TacticalUniverse** [micdoodle8/Galacticraft#3605]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version:  1.12.2-4.0.1.184

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Not sure if it's SSP or SMP
Any Galacticraft add-ons installed? please list all
Extra Planets
Please provide screenshots / crash report / log / full modlist as needed
https://gist.github.com/TacticalUniverse/51f2ca22f5d7cba188adff2ef8a3ff5a

If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft)

**Comment by micdoodle8** [comment]
This is not a Galacticraft problem. BetterBuildersWands is adding their items to our creative tab. Tell the author they should be checking `if (isInCreativeTab(tab))` in their getSubItems method.
