### ISSUE TITLE
Minecraft will crash if you put the Solar Array Controller on the ground.

### ISSUE THREAD

**Issue by Romsik788** [micdoodle8/Galacticraft#3607]
Minecraft version:1.12.2
Galacticraft version:4.0.2.188

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP not opened to LAN
Any Galacticraft add-ons installed? please list all
GalaxySpace
Please provide screenshots / crash report / log / full modlist as needed
[crash-2019-01-12_10.11.23-server.txt](https://github.com/micdoodle8/Galacticraft/files/2751839/crash-2019-01-12_10.11.23-server.txt)
Minecraft will crash if you put the Solar Array Controller on the ground.

**Comment by MJRLegends** [comment]
Its due to a error in the Arrays import. Stupid scala ones haha

**Comment by micdoodle8** [comment]
Thanks, fixed in build 189+
