### ISSUE TITLE
Issue with Compressor for Extra Planets

### ISSUE THREAD

**Issue by OceanSnipe17** [micdoodle8/Galacticraft#3619]
Minecraft version:1.12.2
Galacticraft version:1.12.2-4.0.1.181

Multiplayer (SMP)

Any Galacticraft add-ons installed? please list all
Galacticraft Planets 1.12.2-4.0.1.181
More Planets 1.12.2-2.0.17-GC181
Extra Planets 1.12.2-0.4.6
More Planet Extras 1.12.2-1.0

So my issue is that for the Extra Planet Heavy-Duty Plates, they do not import properly with a hopper. The items stack incorrectly and it results in having to manually fix this. I am trying to automate this with AE2 interfaces and its kind of a mute point if I have to go correct it all the time. 

I have already went to the Extra Planets discord and the mod author said:

"no idea then extraplanets does nothing with interaction with the ingot compressor, i just use the api for adding the recipe. so im unable to help you there"

Here is a video of what I am talking about.

https://drive.google.com/open?id=1gPu5r5x-PiKirCRFISGhwEGh-LFG2iN0

If there is something I can do differently please let me know.

**Comment by TheQuadShot** [comment]
Currently there is no support for AE or RS, there are plans to do so though.

**Comment by OceanSnipe17** [comment]
Whelp I guess I will just wait for that then.

**Comment by MJRLegends** [comment]
its not interacting with AE2 or RS @TheQuadShot even the hopper does it so it is supported for that

**Comment by TheQuadShot** [comment]
No, the hopper alone will not work the way it is, you would have to "prime" the machine first. That is to say, you place the plates manually then continue to "feed" it with a hopper. Not helpful unless your are processing more than a stack. This issue was discussed in the forums though.

**Comment by radfast** [comment]
This all appears to be intended behavior - see discussion on the [wiki](https://wiki.micdoodle8.com/wiki/Electric_Compressor#Automation)

The video shows the Electric Compressor filling from the Hopper in a smart way - it's **trying** to create a working plates recipe from the items provided, and at 0:33 in the video you can see it doing exactly this.  The player who made the video has been smart and provided the Heavy Duty Plate (the top left ingredient) to the Hopper first.

The only issue I can see is that the Compressed Palladium is not always being distributed evenly between the 5 slots it needs to fill.  The **Electric Compressor** is supposed - [see wiki](https://wiki.micdoodle8.com/wiki/Electric_Compressor#Automation) - to distribute evenly across all those slots, but we probably only tested it with standard Galacticraft recipes which are simpler, never having more than 2 slots with the same ingredient.  Looks like it is failing at 5 slots.

**Comment by MJRLegends** [comment]
Thanks for the fix

**Comment by radfast** [comment]
@MJRLegends  you are most welcome.  Please would you test the Heavy-Duty Plates recipe with a Hopper, as I don't have Extra Planets installed in my dev environment.

**Comment by MJRLegends** [comment]
Seems to work great @radfast

**Comment by OceanSnipe17** [comment]
Awesome. Glad to know it will work in the future.
