### ISSUE TITLE
Cannot enter my space station

### ISSUE THREAD

**Issue by HydrogenC** [micdoodle8/Galacticraft#3620]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 4.0.2.190

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? SSP

Any Galacticraft add-ons installed? please list all
ExtraPlanets

Please provide screenshots / crash report / log / full modlist as needed
[latest.log](https://github.com/micdoodle8/Galacticraft/files/2787062/latest.log)

It's kind of weird, it is stuck at the welcome screen to the space station. 
![2019-01-23_19 31 42](https://user-images.githubusercontent.com/33123710/51603851-f0858f00-1f45-11e9-995e-c0a622e0ee3a.png)
I've kept waiting for 50 minutes, and it is still stuck at this screen. 
The mouse is captured and the hud (from TimeHUD mod, as the picture shows) is displayed. And the background music is normally played.  If I check the log, I would find that tips (such as tips suggesting me to wear thermal suits) are already sent to the chat gui. But however the scene is covered by the welcome screen shown in the picture so that I am unable to operate. 
I guess that I entered the space station successful but the welcome screen appears by mistake so that I can't operate. Please fix this.

**Comment by HydrogenC** [comment]
When I force quit and re-enter the map, I would normally find myself in my space station and everything works well. 
Therefore, I think that the problem is that the welcome screen didn't close properly, like this: 
Normal: Display Welcome Screen -> Load Scene -> Close Welcome Screen -> Play
Bugged:  Load Scene -> Display Welcome Screen -> Stuck

**Comment by TheQuadShot** [comment]
I think the problem is Journey map, try running without that and see what happens.

**Comment by MJRLegends** [comment]
Probably your issue https://github.com/MJRLegends/ExtraPlanets/issues/392

**Comment by HydrogenC** [comment]
> Probably your issue [MJRLegends/ExtraPlanets#392](https://github.com/MJRLegends/ExtraPlanets/issues/392)

Differently, it only get stuck while entering space stations, all planets works properly.

**Comment by HydrogenC** [comment]
> Probably your issue [MJRLegends/ExtraPlanets#392](https://github.com/MJRLegends/ExtraPlanets/issues/392)

No, I changed all of the dimension id to a unused number and it still don't work. 
All space stations don't work and all planets works.

**Comment by HydrogenC** [comment]
> I think the problem is Journey map, try running without that and see what happens.

Deleting JourneyMap doesn't help.

**Comment by HydrogenC** [comment]
Due to the tests I made, it's caused by a mod call Universal Remote.
