### ISSUE TITLE
GC Machine Recipes Not Showing in NEI (1.7.10)

### ISSUE THREAD

**Issue by Jake1702** [micdoodle8/Galacticraft#3622]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.7.10
Galacticraft version: 3.0.12.504

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP

Any Galacticraft add-ons installed? please list all
GalaxySpace
Extra Planets
More Planets
GalacticOres
Pixel Galaxy
Amun-Ra
Vaccuum Horizon
Space Advanced

(I really hope I listed all)
Please provide screenshots / crash report / log / full modlist as needed
Here's my latest FML log (Warning very large): https://paste.ubuntu.com/p/WVXbnsd6vn/
Here's the part I noticed that I think is related: 

> Failed to Load micdoodle8.mods.galacticraft.core.nei.NEIGalacticraftConfig

**Comment by MJRLegends** [comment]
Please try without the following 
GalacticOres
Pixel Galaxy
Amun-Ra
Vaccuum Horizon

**Comment by Jake1702** [comment]
> Please try without the following
> GalacticOres
> Pixel Galaxy
> Amun-Ra
> Vaccuum Horizon

Yes, it does seem to work fine now. Interesting, is it a combination or does one of them cause it in particular?

**Comment by MJRLegends** [comment]
They are all old mods that havent been updated so wont work with latest version of mods

**Comment by MJRLegends** [comment]
Nope you would be able to fix it sorry

**Comment by Jake1702** [comment]
I just checked and Amun-Ra actually does work and doesn't break recipes. So I guess I can still use that one. Thanks for your help.
