### ISSUE TITLE
/dimensiontp or rockets in general wont work. | Sponge

### ISSUE THREAD

**Issue by SebaSphere** [micdoodle8/Galacticraft#3625]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)
https://github.com/SpongePowered/SpongeForge/issues/2587

Minecraft version: 1.12.2
Galacticraft version: 181

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Sponge / MP server

Any Galacticraft add-ons installed? please list all
https://minecraft.curseforge.com/projects/terras-starlight/relations/dependencies

Please provide screenshots / crash report / log / full modlist as needed
above

If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft)

**Comment by micdoodle8** [comment]
Closed, as SebaSphere has confirmed the issue has been resolved.
