### ISSUE TITLE
Enchantments applicable on Oxygen Tanks, batterie and fuel tank...

### ISSUE THREAD

**Issue by Fireztonez** [micdoodle8/Galacticraft#3626]
Batteries, Fuel Tanks and Oxygen tank can be enchant with Mending and probably other enchant into an anvil, so after it can refill by itself or with somes repair machine... This is clearly cheaty and this should probably not be the case...

Minecraft version: 1.12.2
Galacticraft version: 4.0.2.190

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Can be done in single player but probably same in LAN or server...

Any Galacticraft add-ons installed? please list all
Extra-Planet 0.4.7

Please provide screenshots / crash report / log / full modlist as needed
![oxygen_tank_mending](https://user-images.githubusercontent.com/19277301/52033021-6dd67400-24f1-11e9-89be-3e3ef22068c4.png)

Thank's

**Comment by Fireztonez** [comment]
Why do you close that issue?? Is it fixed?? Is it intended or you just don't care about that issue and you don't want to fix it??

Can you just let a note when you close issue, this is really not cool to see an issue without any information like that...

**Comment by TheQuadShot** [comment]
@MJRLegends This is a GC report, not an ExtraPlanets issue report...

**Comment by BlesseNtumble** [comment]
```
@Override
public boolean isBookEnchantable(ItemStack stack, ItemStack book) {
    return false
}
```
¯\_(ツ)_/¯

**Comment by Fireztonez** [comment]
Nice,
Thank's for having fix that for the next update!
