### ISSUE TITLE
Magnetic crafting table allows infinite item duplication

### ISSUE THREAD

**Issue by andylizi** [micdoodle8/Galacticraft#3628]
~~As this bug can be easily reproduced in multiplayer, I don't think it's a good idea to publicly disclose the details. Are there some ways to contact the maintainers directly? Or should I just post it here anyway?~~

---

### Environment

Minecraft version: 1.12.2
Galacticraft version: 4.0.2.190
Other mod installed: Buildcraft 7.99.21
Single player, Multiplayer, or SSP opened to LAN? All

### Description

![](https://user-images.githubusercontent.com/12008103/52173028-76130580-27b6-11e9-83a3-72be74b2e13b.png)

The duplicated diamonds can be used as any other "real" diamonds - i.e. they're not ghost items.

You can use a magnetic crafting table + Buildcraft input pipe to duplicate all crafting recipes that have more than one output, infinitely. You can duplicate diamonds (because "a diamond block to 9 diamonds") or tin cans (because "7 tin ingots to 2 tin cans"), but you can't, for example, duplicate diamond swords, as its recipe only have one output, or wafers, as it cannot be crafted at a crafting table.

![](https://user-images.githubusercontent.com/12008103/52173131-8c21c580-27b8-11e9-9df9-40eb312eb471.png)

Vanilla hoppers don't have this problem. Other logistics mods with something similar to Buildcraft pipes may also work, but I haven't tested it yet.

### Steps to reproduce

1. Open a client with the latest Galacticraft _(currently 4.0.2.190)_ and Buildcraft _(currently 7.99.21)_ installed.
2. Place a magnetic crafting table.
3. Connect a wooden pipe to the table and give it a power source (like pipe pulsers or redstone engines).
4. Open the magnetic crafting table, put in at least 2 diamond blocks _(technically it doesn't need two - see the step below)_
5. Click on the result stack to active auto-crafting for the current recipe. The table will consume one of the diamond blocks to give you 9 diamonds, but there're more blocks in the input slot.
6. Voila! Now you have diamonds pumping endlessly from the table, one at a time! Put down more redstone engines to increase the production speed!

### Cause

_(I don't actually understand how the [TileEntityCrafting](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/tile/TileEntityCrafting.java) or Buildcraft pipes works so below is all guess work)_

The wooden pipe **only extracts one item at a time** right? So when a recipe **has more than one output**, it'll only extract one of them, and GC doesn't count this as "consuming ingredients". Thus, infinite item duplication.

**Comment by TheQuadShot** [comment]
Yes, post it here and don't forget to include as much info as possible.

**Comment by radfast** [comment]
Fixed in f6a6d2b16.  Thank you very much for the detailed report.  Sorry it took 6 months to fix, I've been away from the mod.
