### ISSUE TITLE
Crash after joining a server

### ISSUE THREAD

**Issue by MTMiney** [micdoodle8/Galacticraft#3632]
Minecraft version: 1.7.10
Galacticraft version: 1.7-3.0.12.504

Multiplayer (SMP)

Any Galacticraft add-ons installed? please list all
Galacticraft Planets 
Extra Planets (2.0.7)

After I log into my friends server I get a 2-second delay then crash to desktop.
![modlist](https://user-images.githubusercontent.com/47390982/52349716-21110280-29f5-11e9-80e4-e72c33e6d56d.png)
[latest.log](https://github.com/micdoodle8/Galacticraft/files/2836791/latest.log)

**Comment by micdoodle8** [comment]
Although the entity is listed as a Galacticraft entity, this will happen with every crash. 

This has nothing to do with Galacticraft, it's a potion ID conflict.
