### ISSUE TITLE
Crash upon placing solar arrays

### ISSUE THREAD

**Issue by sigve10** [micdoodle8/Galacticraft#3641]
Minecraft version: 1.12.2
Galacticraft version: 1.12.2-4.0.2.190

Issue type: Crash

Single player

No add-ons installed

Crash Report (list of all installed mods at lines 52-144):
https://pastebin.com/tci7y77p

Notes:
Game crashed upon placing down a single solar array module.
Other solar array modules had recently been placed down with no notable issues.
Solar array controller was connected to a heavy aluminum wire, which was connected to nothing but an oxygen collector.
Issue occurred on a space station.
Upon rebooting the game, the issue did not reoccur. 

If you wish for further information, contact me.

**Comment by sigve10** [comment]
Same issue returned later whilst I was breaking a module
https://pastebin.com/iqQhK1TM

**Comment by sigve10** [comment]
These crashes happen constantly whenever I start breaking solar array modules, making it impossible to clear out a large quantity of them

**Comment by weirdwolf** [comment]
I just had this same problem occur on my private server. i decided to do a bit of testing, and the crash seems to happen when placing/removing array modules or power cables, while the solar array controller is enabled, i could place and remove array modules and power cables freely as long as the solar array controller was disabled, i.e. not generating power.

Crash-Report: 
[https://pastebin.com/mYVZ9MsY](url)

**Comment by micdoodle8** [comment]
Thanks, sorry for the delay. Should be fixed in the next build.
