### ISSUE TITLE
[CurseForge] Dodgy dev - request confimation

### ISSUE THREAD

**Issue by spannerman79** [micdoodle8/Galacticraft#3642]
Cureforge URL: https://minecraft.curseforge.com/projects/galacticraft-full

@radfast & @micdoodle8 : Did your stance on hosting over on curseforge change? (related: #2031 )

If not there is another dev that is ripping off your mod as their own if you look at the description.

Archived URL: https://web.archive.org/web/20190220040233/https://minecraft.curseforge.com/projects/galacticraft-full

**Comment by marcus8448** [comment]
Yeah, I'm _99.99%_ sure it's **fake**. Even if they were to put the mod on CurseForge it ~~probably~~ **definitely** wouldn't be posted by that guy - he reposted some "emerald mod" too.

**Comment by spannerman79** [comment]
Hence why I created this issue.

I cannot claim copyright so I cannot do a DMCA, hence why I tagged the two man devs of Galacticraft.

**Comment by marcus8448** [comment]
Well, the project has been taken down now.

**Comment by spannerman79** [comment]
> Well, the project has been taken down now

Yes it has been taken down - although its still available via the "CurseAPI" https://authors.curseforge.com/docs/api
