### ISSUE TITLE
Astrominer unloading chunks when further than 125 blocks from base

### ISSUE THREAD

**Issue by epicfail48** [micdoodle8/Galacticraft#3643]
Minecraft version: 12.2
Galacticraft version: Galacticraft 4, build 190

Multiplayer (SMP)

Installed mods are Galacticraft + planets, Biomes'o'plenty, Worldedit, JEI, and Inventory Tweaks on the server side, in a Forge server

Problem is as stated in the title, astrominers having the chunks they occupy unloaded when they get further than ~125 blocks from the base station. Once the player is close enough to load the chunk the miner resumes movement, but this does create an issue when mining the asteroid belt.

**Comment by marcus8448** [comment]
See #3307

**Comment by epicfail48** [comment]
> See #3307

Much appreciated, i actually knew about that ticket but given that its a year old, referencing a build of Galacticraft thats 34 builds old, and the most relevant bit of information was that there was an incompatibility with sponge, which my server isnt running, i felt it was worth bringing back up. Hopefully theres a fix somewhere

**Comment by radfast** [comment]
This should be fixed in next build 237.  Sorry for the time taken to get to this.
This will not fix the similar issue when Sponge is present (3307) - I'm still working on that one.
