### ISSUE TITLE
Broken models + textures on non-native dimensions caused by sensor glasses

### ISSUE THREAD

**Issue by TheRealDannyyy** [micdoodle8/Galacticraft#3645]
**Minecraft version:** 1.12.2
**Galacticraft version:** Build 181+
**Game type:** Multiplayer (SMP)

**Installed mods:**
- 3 Galacticraft jars (2x core, 1x planets)
- Extraplanets

**General log:**
https://pastebin.com/QtRDa6gQ

**Comment:**
In reference to this issue posted on the [Extraplanets Github](https://github.com/MJRLegends/ExtraPlanets/issues/408), there seems to be an issue with the sensor glasses on non-native planets. The linked issue has more context and further help for reproduction.

**Screenshot:**
![68747470733a2f2f692e6779617a6f2e636f6d2f39323831363339626134626466333231636136393564616234646230356236342e706e67](https://user-images.githubusercontent.com/15656049/54882423-2ec20080-4e5a-11e9-9b42-359b2a5c7e76.png) _(Arrows are broken.)_

![54057431-3eeba600-41f3-11e9-88fb-9faa7ede0205](https://user-images.githubusercontent.com/15656049/54882424-2ec20080-4e5a-11e9-9388-fd37feee0d68.jpg) _(Item in hand is broken and Extraplanets space suit has transparency problems.)_

**Comment by TheRealDannyyy** [comment]
Would really appreciate if someone could look into this. Since Extraplanets makes use of the visual features from the sensor glasses, it affects users of that mod the most.

**Comment by MJRLegends** [comment]
It was confirmed to be a Galacticraft issue and it been reported

**Comment by MJRLegends** [comment]
So no need to make another one..

**Comment by MJRLegends** [comment]
Ignore my messages i deleted im a idiot... haha

**Comment by micdoodle8** [comment]
Should be fixed in the next build, sorry for the delay.

Thanks for the detailed report!

**Comment by TheRealDannyyy** [comment]
@micdoodle8 Would appreciate the build number, if possible. The changelog seems to be outdated and doesn't contain all the recent changes from r191 to r210+.
