### ISSUE TITLE
Switchable wires glitch

### ISSUE THREAD

**Issue by FrostQ** [micdoodle8/Galacticraft#3648]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 4.0.2.190

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Both

Any Galacticraft add-ons installed? please list all
None
Please provide screenshots / crash report / log / full modlist as needed
- https://youtu.be/RxxRL64xqic

If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft)

**Comment by micdoodle8** [comment]
Thanks!
