### ISSUE TITLE
how tf do i go to uranus.

### ISSUE THREAD

**Issue by blarb21** [micdoodle8/Galacticraft#3650]
i can load a couple planets in my solar system but others are red, like Uranus even though i have a tier 10 rocket. help ples

**Comment by TheQuadShot** [comment]
GC doesn't have that planet... So you are most likely running Extra Planets, you might find some help that the GC Forums though.  Please close this report, and if you are unsuccessful at the forum, or its help section, then file it with Extra Planets. 
https://forum.micdoodle8.com/index.php?threads/extra-planets-tips-secrets.6837/
