### ISSUE TITLE
Galacticraft with camping 2 Invetory problem

### ISSUE THREAD

**Issue by Joosep127** [micdoodle8/Galacticraft#3657]
Soo I have thing problem where I can only equip the galacticraft items with right click and not unequip them because the galacticraft invetory wont appear from my invetory pls help (I have it installed I just don't have the galacticraft items in my invetory)

![Capture](https://user-images.githubusercontent.com/48839946/54845738-dc120880-4ce2-11e9-8428-d82880a3e85a.PNG)

**Comment by micdoodle8** [comment]
Please use the issue template
