### ISSUE TITLE
[Bug] When I build my rocket from advanced rocketry mod with GC solar panels on the ship, game just crashes and after restart my ship just destroying to half

### ISSUE THREAD

**Issue by Poxorosa** [micdoodle8/Galacticraft#3658]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)
When I build my rocket from advanced rocketry mod with GC solar panels on the ship, game just crashes and after restart my ship just destroying to half

Minecraft version: 1.12.2
Galacticraft version: Latest

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP
Any Galacticraft add-ons installed? please list all
No.

Please provide screenshots / crash report / log / full modlist as needed
https://pastebin.com/qeKSDW2J

If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft)

**Comment by micdoodle8** [comment]
Thanks, fixed in the next build
