### ISSUE TITLE
GC 3 Launching Issue with GLSL Shaders

### ISSUE THREAD

**Issue by austin4195** [micdoodle8/Galacticraft#366]
It appears that in the newest build of GC 3 (#38), It is no longer possible to even get off of the ground. The game also goes non-responsive when approaching Y=200. The earth texture does not get set like usual upon leaving the planet. The game must be force closed and as a result, a log isn't generated. 

The log I could get: http://paste.ee/p/wSygJ

**Comment by FelixBardner** [comment]
I had the exact same problem! Fortunately for me, I was running a mod pack on mine craft 1.6.4, so I had the option to disable the sky, stars, and the sun/moon, and seemed to fix that for me.
