### ISSUE TITLE
Entity being ticked, not sure who to blame

### ISSUE THREAD

**Issue by boosterdev** [micdoodle8/Galacticraft#3662]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 4.0.2.210

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SMP

Any Galacticraft add-ons installed? please list all
No

Please provide screenshots / crash report / log / full modlist as needed
https://paste.dimdev.org/oyabuvayev.mccrash

If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft) 
well yes I use the Jenkins Site

possible dupe of #3661

**Comment by TheQuadShot** [comment]
It looks like enderio to me:
`net.minecraft.item.ItemAir cannot be cast to crazypants.enderio.base.power.forge.item.IInternalPoweredItem`

**Comment by boosterdev** [comment]
> -- Entity being ticked --
  Entity Type: null (micdoodle8.mods.galacticraft.core.entities.player.GCEntityClientPlayerMP)

**Comment by TheQuadShot** [comment]
Yes, but:
https://wiki.micdoodle8.com/wiki/Common_Problems
"People sometimes report crashes involving GCEntityClientPlayerMP or GCPlayerBaseSP. In 99% of cases, these are not Galacticraft crashes, it's another mod crashing."

**Comment by HenryLoenwind** [comment]
-> https://github.com/Vazkii/Botania/issues/2878

**Comment by boosterdev** [comment]
Ty all for sorting it out :+1:
