### ISSUE TITLE
Crash when entering the Nether

### ISSUE THREAD

**Issue by NLBlacky** [micdoodle8/Galacticraft#3665]
Minecraft version: 1.12.2
Galacticraft version: GalacticraftCore-1.12.2-4.0.2.190.jar, Galacticraft-Planets-1.12.2-4.0.2.190.jar, GalacticraftTweaker-1.12.2-1.0.3.jar
Modpack: Project Ozone 3 v3.0.39

Whenever a player goes to the Nether, the server crashes with the error listed in the crashlog below. Crash happens on a multiplayer server running Project Ozone 3.

Crashlog: https://pastebin.com/c40svMHR

**Comment by radfast** [comment]
This is very likely the same issue as #3775.
We are hoping it is fixed in the next build of Galacticraft.
Sorry this has taken so long.

**Comment by radfast** [comment]
Please try build 1.12.2 - 4.0.2.234, this is fixed.
