### ISSUE TITLE
[Bug] - Another crash with advanced rocketry.

### ISSUE THREAD

**Issue by Poxorosa** [micdoodle8/Galacticraft#3667]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)
When I build my rocket from advanced rocketry with NASA workbench on a rocket, my game crashes.
Minecraft version: 1.12.2
Galacticraft version: latest

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP
Any Galacticraft add-ons installed? please list all
More planets, Galaxy Space.

Please provide screenshots / crash report / log / full modlist as needed
https://pastebin.com/rF7cGqrT

If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft)

**Comment by micdoodle8** [comment]
Fixed with f5bb40b3c6f07bead7e8c8e053e6772914730560

Thanks for the report :)
