### ISSUE TITLE
Sapphire Ore

### ISSUE THREAD

**Issue by chasejsutton49** [micdoodle8/Galacticraft#3668]
Sapphire Ore, while it can be obtained by mining it with Silk Touch, can't be smelted in any furnace into Lunar Sapphires. Also, according to JEI/NEI, it can't be smelted.

Minecraft version: 1.12.2
Galacticraft version: 4.0.2.210

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Single player (SSP)
Any Galacticraft add-ons installed? please list all
None
Please provide screenshots / crash report / log / full modlist as needed
![2019-04-13_11 41 39](https://user-images.githubusercontent.com/19761194/56082723-b65bb900-5de1-11e9-87bb-53983195d4dd.png)
__
If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft)

**Comment by micdoodle8** [comment]
Thanks. Will be fixed in the next build.
