### ISSUE TITLE
Galacticraft, stuck on Galaxy map

### ISSUE THREAD

**Issue by TitanGuard** [micdoodle8/Galacticraft#3669]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version:
Galacticraft version:

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?

Any Galacticraft add-ons installed? please list all

Please provide screenshots / crash report / log / full modlist as needed

If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft)

**Comment by TitanGuard** [comment]
I have a major problem, My minecraft had crashed during launching into space during the Galacticraft Map opening, now everytime i join the server the galaxy map is open and i can't see the solar system, and when i click on overworld to get to Earth i just flat out crash.
i'm using the current version of the Modpack Astroblock.

**Comment by MJRLegends** [comment]
One you haven't actually filed out the issue template provided you then talk about crashing but havent posted any crash logs. 

Unfortunately we are only programmers and we have not been to magic school so your going to have to provide the info we cant read your mind or access your crash logs

**Comment by TitanGuard** [comment]
sorry about that...
Minecraft Version: 1.12.2
Galacticraft Core Version: 1.12.2-4.0.2.210
Galacticraft add-on:, Galacticraft Planets version 1.12.2-4.0.2.210
GalacticraftTweaker-1.12.2-1.0.3
Crash log i think: [crash-2019-04-14_23.13.55-client.txt](https://github.com/micdoodle8/Galacticraft/files/3078670/crash-2019-04-14_23.13.55-client.txt)

Its a Multiplayer private server

Full modlist with versions (Astroblock Modpack on Twitch Luancher)
/dank/null	TheRealp455w0rd	DankNull-1.12-1.4.43.jar
Additional Resources	Portablejim	additionalresources-1.9.4-0.2.0.28+47cd0bd_signed.jar
AE2 Stuff	bdew	ae2stuff-0.7.0.4-mc1.12.2.jar
AE2 Wireless Terminal Library	TheRealp455w0rd	AE2WTLib-1.12.2-1.0.6.jar
Applied Energistics 2	AlgorithmX2	appliedenergistics2-rv6-stable-6.jar
AttributeFix	Darkhax	AttributeFix-1.12.2-1.0.7.jar
AutoRegLib	Vazkii	AutoRegLib-1.3-24.jar
Baubles	azanor	Baubles-1.12-1.5.2.jar
BdLib	bdew	bdlib-1.14.3.12-mc1.12.2.jar
Better Builder's Wands	Portablejim	BetterBuildersWands-1.12-0.12.0.251+d6c4d93.jar
Better Combat Rebirth	SanAndreasP	BetterCombat-1.12.2-1.5.6.jar
BetterFps	Guichaguri	BetterFps-1.4.8.jar
BlankPlanet	MJRLegends	BlankPlanet-1.12.2-0.3.jar
Block Drops (JEI Addon)	KidsDontPlay	blockdrops-1.12.2-1.4.0.jar
Blockcraftery	epicsquid319	blockcraftery-1.12.2-1.2.0.jar
Bonsai Trees	Davenonymous	bonsaitrees-1.1.2-b144.jar
Bookshelf	Darkhax	Bookshelf-1.12.2-2.3.576.jar
Building Gadgets	direwolf20	BuildingGadgets-2.6.6.jar
Chameleon	jaquadro	Chameleon-1.12-4.1.3.jar
Champions	theillusivec4	champions-1.12.2-1.0.5.jar
Chicken Chunks 1.8.+	covers1624	ChickenChunks-1.12.2-2.4.1.73-universal.jar
Chisel	tterrag1098	Chisel-MC1.12.2-0.2.1.35.jar
Clipboard	shadowfactsmc	Clipboard-1.12-1.3.0.jar
CodeChicken Lib 1.8.+	covers1624	CodeChickenLib-1.12.2-3.2.2.353-universal.jar
CoFH Core	TeamCoFH	CoFHCore-1.12.2-4.6.2.25-universal.jar
CoFH World	TeamCoFH	CoFHWorld-1.12.2-1.3.0.6-universal.jar
ConnectedTexturesMod	tterrag1098	CTM-MC1.12.2-0.3.3.22.jar
Controlling	jaredlll08	Controlling-3.0.6.jar
CoroUtil	Corosus	coroutil-1.12.1-1.2.15.jar
Crafting Tweaks	BlayTheNinth	CraftingTweaks_1.12.2-8.1.9.jar
CraftTweaker	jaredlll08	CraftTweaker2-1.12-4.1.13.jar
Cucumber Library	BlakeBr0	Cucumber-1.12.2-1.1.3.jar
Custom Main Menu	lumien231	CustomMainMenu-MC1.12.2-2.0.9.jar
Cyclops Core	kroeser	CyclopsCore-1.12.2-0.11.11.jar
Deep Mob Learning	IterationFunk	deepmoblearning-1.12.2-2.4.1-universal.jar
Default Options	BlayTheNinth	DefaultOptions_1.12.2-9.2.8.jar
Ding	iChun	Ding-1.12.1-1.0.1.jar
Discord	TeamDman	Discord-1.12.2-1.0.7.jar
Drones	Vadis365	Drones-0.3.1.jar
Emojiful	HRZNStudio	emojiful-1.0.3.jar
Enchanting Plus	Darkhax	EnchantingPlus-1.12.2-5.0.176.jar
Ender Storage 1.8.+	covers1624	EnderStorage-1.12.2-2.4.5.135-universal.jar
Environmental Tech	ValkyrieofNight	environmentaltech-1.12.2-2.0.19.1.jar
ET Lunar [Environmental Tech Addon]	ValkyrieofNight	etlunar-1.12.2-2.0.19.1.jar
Ex Compressum	BlayTheNinth	ExCompressum_1.12.2-3.0.26.jar
Ex Nihilo: Creatio	BloodWorkXGaming	exnihilocreatio-1.12.2-0.3.9.jar
Ex Sartagine	senpaisubaraki	exsartagine-1.12.2-0.2.0.0.jar
EXO-Craft	XxRexRaptorxX	ExoCraft-1.12.x-(v.1.1.0).jar
External Tweaker	Bartz24	externaltweaker-1.12-0.3.jar
ExtraPlanets	MJRLegends	ExtraPlanets-1.12.2-0.5.2.jar
Featured Servers	Jake_Evans	FeaturedServers-1.12-1.0.6.jar
Fluid Funnel	lemonszz	FluidFunnel-1.12.2-1.3.0.jar
Flux Networks	Ollie_Lansdell	fluxnetworks-1.12.2-3.0.19-21.jar
FoamFix for Minecraft	asiekierka	foamfix-0.10.3-1.12.2.jar
Forgiving Void	BlayTheNinth	ForgivingVoid_1.12.2-1.0.21.jar
FTB Library	FTB	FTBLib-5.4.1.91.jar
FTB Quests	LatvianModder	FTBQuests-1.5.1.136.jar
FTB Utilities	FTB	FTBUtilities-5.4.0.85.jar
Galacticraft Add-on - More Planets	SteveKunG	More-Planets-1.12.2-2.1.5-GC190.jar
Galacticraft Tweaker	MJRLegends	GalacticraftTweaker-1.12.2-1.0.3.jar
Global GameRules	Gory_Moon	GlobalGameRules-1.12.2-2.2.7.jar
Guide-API	TehNut	Guide-API-1.12-2.1.8-63.jar
HeartDrops	deflatedpickle	heartdrops-1.12.2-2.0.8.1.jar
Industrial Foregoing	Buuz135	industrialforegoing-1.12.2-1.12.4-228.jar
Integration Foregoing	Jacky1356400	IntegrationForegoing-1.12.2-1.8.2.jar
Inventory Generators	kjmaster2	inventorygenerators-1.2.2.jar
Inventory Pets	Purplicious_Cow	inventorypets-1.12-2.0.1.jar
Inventory Tweaks	Kobata	InventoryTweaks-1.64+dev.146.jar
Iron Backpacks	gr8pefish	IronBackpacks-1.12.2-3.0.8-12.jar
Iron Chests	progwml6	ironchest-1.12.2-7.0.55.839.jar
Iron Jetpacks	BlakeBr0	IronJetpacks-1.12-2-1.1.0.jar
Item Filters	LatvianModder	ItemFilters-1.0.1.8.jar
IvToolkit	Ivorforce	IvToolkit-1.3.3-1.12.jar
JourneyMap	techbrew	journeymap-1.12.2-5.5.4.jar
Just Enough Items (JEI)	mezz	jei_1.12.2-4.15.0.269.jar
Just Enough Resources (JER)	Way2muchnoise	JustEnoughResources-1.12.2-0.9.0.52.jar
KJLib	kjmaster2	kjlib-1.0.4.jar
Laser Creeper Robot Dino Riders From Space	Vadis365	LaserCreeperRobotDinoRidersFromSpace-2.0.0.jar
LetsEncryptCraft	CloudyPSP	letsencryptcraft-1.10.2-1.0.0.jar
Long Fall Boots	NanoHeart	longfallboots-1.2.1b.jar
LootTweaker	Daomephsta	LootTweaker-1.12.2-0.0.8.jar
Lost Souls	McJty	lostsouls-1.12-1.1.4.jar
LunatriusCore	Lunatrius	LunatriusCore-1.12.2-1.2.0.42-universal.jar
MalisisAdvert	Ordinastie	malisisadvert-1.12.2-6.1.0.jar
MalisisBlocks	Ordinastie	malisisblocks-1.12.2-6.1.0.jar
MalisisCore	Ordinastie	malisiscore-1.12.2-6.4.0.jar
MalisisDoors	Ordinastie	malisisdoors-1.12.2-7.3.0.jar
MalisisSwitches	Ordinastie	malisisswitches-1.12.2-5.1.0.jar
Mantle	mDiyo	Mantle-1.12-1.3.3.39.jar
Matter Overdrive: Legacy Edition	HRZNStudio	MatterOverdrive-1.12.2-0.6.2.207-universal.jar
McJtyLib	McJty	mcjtylib-1.12-3.1.1.jar
MCMultiPart	amadornes	MCMultiPart-2.5.3.jar
Mekanism	aidancbrady	Mekanism-1.12.2-9.6.8.366.jar
Mekanism Generators	aidancbrady	MekanismGenerators-1.12.2-9.6.8.366.jar
MekaTweaker	Lorexe	mekatweaker-1.12-1.1.2.jar
Minestrappolation 5	werty1125	Minestrappolation 5.6.5.jar
MJRLegends Lib	MJRLegends	MJRLegendsLib-1.12.2-1.1.8.jar
Mod Name Tooltip	mezz	modnametooltip_1.12.2-1.10.0.jar
ModTweaker	jaredlll08	modtweaker-4.0.15.jar
Modular Powersuits	MachineMuse	ModularPowersuits-1.12.2-0.7.0.035.jar
More Overlays	feldim2425	moreoverlays-1.14-mc1.12.2.jar
More Planets Extras	MJRLegends	MorePlanetsExtras-1.12.2-1.0.jar
Morpheus	Quetzi	Morpheus-1.12.2-3.5.106.jar
Mouse Tweaks	YaLTeR97	MouseTweaks-2.10-mc1.12.2.jar
MrTJPCore	Mr_TJP	MrTJPCore-1.12.2-2.1.3.35-universal.jar
MTLib	jaredlll08	MTLib-3.0.5.jar
MysticalLib	epicsquid319	mysticallib-1.12.2-1.1.1.jar
NasaTweaker	AmazigJj	nasatweaker-1.0.1.jar
Nature's Compass	ChaosTheDude	NaturesCompass-1.12.2-1.5.1.jar
No Nether Portals	Seneschal_Luwin	nonetherPortals_v1.0.0formc1.12.2.jar
No Recipe Book	Seneschal_Luwin	noRecipeBook_v1.2.2formc1.12.2.jar
OC Sensors	Davenonymous	ocsensors-1.0.4-b23.jar
OC XNet Driver	Davenonymous	ocxnetdriver-1.0.3-b17.jar
OldJavaWarning	Darkhax	OldJavaWarning-1.12.2-1.0.10.jar
OMLib	Keridos	omlib-1.12.2-3.0.1-162.jar
OpenBlocks Elevator	VsnGamer	ElevatorMod-1.12.2-1.3.8.jar
OpenComputers	SangarWasTaken	OpenComputers-MC1.12.2-1.7.4.153.jar
OpenGlasses2	marcin212	OpenGlasses-MC1.12.2-2.0.6.jar
OpenModularTurrets	Keridos	openmodularturrets-1.12.2-3.0.1-264.jar
Ore Excavation	Funwayguy	OreExcavation-1.4.133.jar
p455w0rd's Library	TheRealp455w0rd	p455w0rdslib-1.12.2-2.0.36.jar
Patchouli	Vazkii	Patchouli-1.0-16.jar
Placebo	Shadows_of_Fire	Placebo-1.12.2-1.5.1.jar
Planet Progression	MJRLegends	PlanetProgression-1.12.2-0.3.1.jar
Potion Icon Remover	Kashdeya	Potion Icon Remover-1.12-4.0.0.jar
Practical Logistics 2	Ollie_Lansdell	practicallogistics2-1.12.2-3.0.8-11.jar
RandomPatches	TheRandomLabs	randompatches-1.12.2-1.11.0.3.jar
Reap Mod	EuhDawson	reap-1.5.2.jar
ReAuth	TechnicianLP	reauth-3.6.0.jar
Recurrent Complex	Ivorforce	RecurrentComplex-1.4.7.jar
Redstone Arsenal	TeamCoFH	RedstoneArsenal-1.12.2-2.6.2.17-universal.jar
Redstone Flux	TeamCoFH	RedstoneFlux-1.12-2.1.0.6-universal.jar
Redstone Repository Revolved	epicsquid319	RedstoneRepository-1.12.2-1.4.0-dev-universal.jar
Resource Loader	lumien231	ResourceLoader-MC1.12.1-1.5.3.jar
RFTools	McJty	rftools-1.12-7.61.jar
RFTools Control	McJty	rftoolsctrl-1.12-1.9.3.jar
RPG-Hud	KurodaAkira	[1.12] RPG-HUD-3.6.6.2.jar
Satako library	Alexiy_Ov	Satako 1.12-2.21.jar
Scannable	SangarWasTaken	Scannable-MC1.12.2-1.6.3.24.jar
Shadowfacts' Forgelin	shadowfactsmc	Forgelin-1.8.2.jar
ShadowMC	shadowfactsmc	ShadowMC-1.12-3.8.0.jar
Simple Generators	ValkyrieofNight	simplegenerators-1.12.2-2.0.19.1.jar
Simple Storage Network	Lothrazar	SimpleStorageNetwork-1.12.2-1.5.7.jar
Slab Machines	mrbysco	Slab_Machines-1.0.4.jar
Sonar Core	Ollie_Lansdell	sonarcore-1.12.2-5.0.19-20.jar
SteveKunG's Lib	SteveKunG	SteveKunG's-Lib-1.12.2-1.0.5.jar
Storage Drawers	jaquadro	StorageDrawers-1.12.2-5.3.8.jar
SubLib	senpaisubaraki	subcommonlib-sublib-1.12.2-1.2.0.4.jar
Super Sound Muffler	Edgar_Allen	supersoundmuffler-1.12.1-1.0.2.9.jar
Tesla Core Lib	Face_of_Cat	tesla-core-lib-1.12.2-1.0.15.jar
The Lost Cities	McJty	lostcities-1.12-2.0.12.jar
The One Probe	McJty	theoneprobe-1.12-1.4.25.jar
Thermal Cultivation	TeamCoFH	ThermalCultivation-1.12.2-0.3.2.11-universal.jar
Thermal Dynamics	TeamCoFH	ThermalDynamics-1.12.2-2.5.4.18-universal.jar
Thermal Expansion	TeamCoFH	ThermalExpansion-1.12.2-5.5.3.41-universal.jar
Thermal Foundation	TeamCoFH	ThermalFoundation-1.12.2-2.6.2.26-universal.jar
Thermal Innovation	TeamCoFH	ThermalInnovation-1.12.2-0.3.2.11-universal.jar
ThermalLogistics	HeroWorkbrine	thermallogistics-0.2-17.jar
Toast Control	Shadows_of_Fire	Toast Control-1.12.2-1.8.0.jar
Totem Expansion	lemonszz	totemexpansion-1.2.2-1.12.2.jar
ToxicRain	CoolSquid	ToxicRain-1.12-1.0.1.jar
Twerk Sim 2K16	Funwayguy	TS2K16-1.2.9.jar
Ultimate Skyblock Resource Generator	rafacost3d	Ultimate SkyBlock Resource Generator-1.12.2-1.3.jar
Useful Nullifiers	Bartz24	usefulnullifiers-1.5.0.jar
ValkyrieLib	ValkyrieofNight	valkyrielib-1.12.2-2.0.19.1.jar
Void Island Control	Bartz24	voidislandcontrol-1.5.2.jar
Water Control Extreme	HRZNStudio	WaterControlExtreme-1.0.2.jar
Wawla - What Are We Looking At	Darkhax	Wawla-1.12.2-2.5.270.jar
Wearable Backpacks	InsomniaKitten	WearableBackpacks-1.12.2-3.1.3.jar
Whoosh	imba_knugel	Whoosh-1.12.2-0.1.12.1-universal.jar
Wireless Crafting Terminal	TheRealp455w0rd	WirelessCraftingTerminal-1.12.2-3.11.88.jar
XNet	McJty	xnet-1.12-1.7.6.jar
Xtones	TehNut	Xtones-1.12-1.0.8-11.jar
MicdoodleCore-1.12.2-4.0.2.210	Unknown Author	MicdoodleCore-1.12.2-4.0.2.210
Galacticraft-Planets-1.12.2-4.0.2.210	Unknown Author	Galacticraft-Planets-1.12.2-4.0.2.210
GalacticraftCore-1.12.2-4.0.2.210	Unknown Author	GalacticraftCore-1.12.2-4.0.2.210	
[crash-2019-04-14_23.13.55-client.txt](https://github.com/micdoodle8/Galacticraft/files/3078670/crash-2019-04-14_23.13.55-client.txt)
