### ISSUE TITLE
Unable to craft Titanium tools

### ISSUE THREAD

**Issue by ntggolfman** [micdoodle8/Galacticraft#3670]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

I can't craft titanium tools. I have tried the reccommended and latest versions.

Minecraft version: 1.12.2
Galacticraft version: 4.0.2.210

SSP opened to LAN (LAN)?

Any Galacticraft add-ons installed? please list all
Added Buildcraft mods

Please provide screenshots / crash report / log / full modlist as needed

**Comment by ntggolfman** [comment]
I'm sorry that I haven't provided any other info, but i'm not much of a programmer so I don't really know what to show whomever it may concern.

**Comment by marcus8448** [comment]
Seems fine to me... Are you using titanium plates? https://wiki.micdoodle8.com/wiki/Titanium_Axe

**Comment by ntggolfman** [comment]
Yes. Neither I nor my buddy who is hosting the world is able to craft them.

**Comment by RollWithRNGesus** [comment]
We are having the same issue on the dedicated server I run. Was there a solution to this? We are running the same versions as the OP.  Thanks!

**Comment by micdoodle8** [comment]
Well it appears the crafting recipe uses iron ingots instead of sticks now. I'm not sure if this changed or whether the wiki was always wrong.
