### ISSUE TITLE
Railcraft incompatibility?

### ISSUE THREAD

**Issue by Slayer5934** [micdoodle8/Galacticraft#3671]
Minecraft version: 1.12.2
Galacticraft version: 4.0.2.210

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
ANY

Any Galacticraft add-ons installed? please list all
NONE

Issue Description:
With Railcraft installed spawning an invalid block such as galacticraftcore:basic_block_core (without an ID) causes the game to crash.

Without Railcraft:
![image](https://user-images.githubusercontent.com/20819543/56136090-0bbdd480-5f60-11e9-95d8-955ef70b78b1.png)

With Railcraft:
https://paste.dimdev.org/uzubozavef.mccrash

Railcraft Issue:
https://github.com/Railcraft/Railcraft/issues/1816

**Comment by micdoodle8** [comment]
Thanks, will be fixed in the next build
