### ISSUE TITLE
World Ticking Crash

### ISSUE THREAD

**Issue by RodrigoTaipe93** [micdoodle8/Galacticraft#3674]
Hello,

There seems to be an issue with World Gen and Galacticraft...and Dynamic Trees:

- https://paste.dimdev.org/mideqaqeze.mccrash

- https://mega.nz/#!w9chmQYQ!6H6EsWyaAxa1vicfkeomIqEEKVKEylvb1dpCTtb9vEg

- https://mega.nz/#!E0EVjKhS!jaYXwKwO140VQzMG91e_obgvcGIFhd7edhSY7a6Ecbs

I'm sending this message to both mods authors

Background: At first, I thought it was Optifine or Mo Creatures. I was wrong. Hopefully, you guys can help me figure out an answer

The two links after the crash log link, are the latest log that help me suspect there is an issue with Dynamic Trees, World Gen and Galacticraft.

The problem is mainly with a World Ticking Crash.

**Comment by micdoodle8** [comment]
As far as I can tell this is just a dynamic trees issue. See the line `Error in another mod's worldgen.  This is *NOT* a Galacticraft bug, report it to the other mod please.`

Here's a hint for the dynamic trees devs: https://pastebin.com/XYuanhg7
