### ISSUE TITLE
Crash on opening galaxy map

### ISSUE THREAD

**Issue by krisjenner** [micdoodle8/Galacticraft#3678]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 4.0.1.1.8.1

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?

SSP opened to LAN

Any Galacticraft add-ons installed? please list all
Extra Planets

Please provide screenshots / crash report / log / full modlist as needed
https://paste.dimdev.org/gibifekeyu.mccrash

Crash report on opening galaxy map

If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft)

**Comment by TheQuadShot** [comment]
This is a crash in Extra Planets, and you already have a bug filed over there, so please close this report.
You might try the forums here(yes Extra Planets is covered there as well):
https://forum.micdoodle8.com/index.php
