### ISSUE TITLE
java.lang.ClassCastException: micdoodle8.mods.galacticraft.core.entities.player.GCEntityOtherPlayerMP cannot be cast to net.minecraft.entity.player.EntityPlayerMP

### ISSUE THREAD

**Issue by partridge420x** [micdoodle8/Galacticraft#3679]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 1.12.2-4.0.2.210

MultiPlayer
Any Galacticraft add-ons installed?: Galaxy Space

Please provide screenshots / crash report / log / full modlist as needed
https://gist.github.com/partridge420x/c6c5e8ee44a4de295830593a36cc5803
(All server info /nucleus info above^^^)
https://gist.github.com/partridge420x/4595f7df600b5f0325b721d848263359
(crash logs above^^^)

**Comment by radfast** [comment]
>   java.lang.ClassCastException: micdoodle8.mods.galacticraft.core.entities.player.GCEntityOtherPlayerMP cannot be cast to net.minecraft.entity.player.EntityPlayerMP
>	at DamageIndicatorsMod.core.DIEventBus.livingEvent(DIEventBus.java:229)

This is a bug in DamageIndicators mod.  Already reported on their issue tracker [here](https://www.curseforge.com/minecraft/mc-mods/damage-indicators-mod/issues/2) and said by them to be fixed.  So hopefully updating that mod should fix things, if this is still relevant to you?
