### ISSUE TITLE
crash after disabled AE2 dusts

### ISSUE THREAD

**Issue by sinopike** [micdoodle8/Galacticraft#3680]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version:1.12.2
Galacticraft version:4.0.2.210

single player only

no addons

game crashed when launching, after disabling dusts in AE2 (to solve somem problems with unidict). Seems to be causing error in compatibility model where galacticraft expects AE2 to have all resource enabled. no where to fix in config.

error happens when loading galacticraftcore 
[crash-2019-04-26_23.07.26-client.txt](https://github.com/micdoodle8/Galacticraft/files/3123157/crash-2019-04-26_23.07.26-client.txt)

**Comment by micdoodle8** [comment]
Should be fixed in the next build. Thanks!
