### ISSUE TITLE
Duplicate file names in Galacticraft

### ISSUE THREAD

**Issue by golololologol** [micdoodle8/Galacticraft#3681]
Minecraft version:1.12.2
Galacticraft version:4.0.2.210

Single player

Installed:Galacticraft,Millenaire,Galaxy space and buildhelper (all for 1.12.2) 

Galacticraft downloaded from good site: 
https://ru-m.org/mody-minecraft/1122/25013-skachat-galacticraft-dlya-minecraft-1122.html

Log:
[latest.log](https://github.com/micdoodle8/Galacticraft/files/3124322/latest.log)

In Mods all files have different names
Idk what happened
But minecraft writing:
![ScreenShot](https://user-images.githubusercontent.com/50058139/56854826-8239d980-6945-11e9-8781-6ebd84f08f5f.png)
(I tried to solve this problem, but with no sucсess)

**Comment by golololologol** [comment]
SOLVED!

**Comment by marcus8448** [comment]
ru-m.org is not a good website. Please checkout [Stop Mod Reposts](stopmodreposts.org) for more info about these sites. Please re-download Galacticraft from here: https://micdoodle8.com/mods/galacticraft/downloads.
