### ISSUE TITLE
Circuit Fabricator Uses Energy When Idle

### ISSUE THREAD

**Issue by KenyMylankca** [micdoodle8/Galacticraft#3683]
on 1.12.2, Forge 2836 with MicdoodleCore-1.12.2-4.0.2.210, GalacticraftCore-1.12.2-4.0.2.210, Galacticraft-Planets-1.12.2-4.0.2.210, it happens. Please don't make it use energy when it does nothing. Thanks...

**Comment by KenyMylankca** [comment]
and it's same with electric compressor. i think all GC machines have this problem. i really hope this be fixed

**Comment by TheQuadShot** [comment]
Did you apply a redstone signal to it? May be related to https://github.com/micdoodle8/Galacticraft/issues/2850

**Comment by KenyMylankca** [comment]
no i did not.

**Comment by marcus8448** [comment]
It's a intended 'feature' for realism. See https://github.com/micdoodle8/Galacticraft/issues/2845#issuecomment-309858208 - It might/could be changed in the future.

**Comment by KenyMylankca** [comment]
oh lol, i see. so how could we disable it from running? with a lever? or we have to break the energy cable connection?

**Comment by marcus8448** [comment]
You can use a lever, but it will still drain some energy (I think). If you want it to use no energy, I would recommend either breaking the circuit/wires or using switchable wires.

**Comment by KenyMylankca** [comment]
oh this is bad... there should be a config at least...

**Comment by radfast** [comment]
If the machine has energy in its internal battery, it will slowly lose it even when the machine is not used.  As explained on #2845, this is intended behaviour for game performance reasons and for realism.  In the real world, if you don't drive your car for 2 months, you might often find it has a flat battery and won't start (depends also on the weather, in a wet climate it's worse than a dry climate - we do not simulate this in Galacticraft!)

Wires or switches will not change this intended game behaviour.  Even disabling the machine will not change it, though @TheQuadShot has proposed we change that.

Currently, if you want to store energy for future use, use an **Energy Storage Module**, and use **Switchable Aluminum Wire**.  If you switch the wire to disconnect the energy store from all your machines, then the energy store will hold its energy forever until you need it.
