### ISSUE TITLE
Please add support for item transfer systems.

### ISSUE THREAD

**Issue by ryaniskira** [micdoodle8/Galacticraft#3684]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 1.12.2-4.0.2.210

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SMP

Any Galacticraft add-ons installed? ExtraPlanets

Currently, Galaticraft is currently the hardest mod to interact with item-wise, period. Mekanism's logistical transporters won't even connect to Galacicraft blocks, Pneumaticraft Repressurized's Omnidirectional hoppers are hit and miss, and Thermal Foundation's itemducts seem to be able to push items into Galacticraft blocks but unable to pull from them. Gasses and liquids I have no issues with whatsoever, it's just items.

This is a huge dealbreaker and with literally every other mod I've tried that has blocks with inventories, item transfer just works. I place down an item transfer block (for example Mekanism's logistical transporters and 90% of the time it just works, the other 10% of the time I just need to configure either the block or the pipe to be able to pull from the inventory containing block. The only consistent way to pull from Galaticraft blocks seems to be vanilla hoppers and those are nothing but lag generators.

- '[1.12.2]+SecurityCraft+v1.8.12.jar'
-  AbyssalCraft-1.12.2-1.9.7.jar
-  appliedenergistics2-rv6-stable-6.jar
-  AutoRegLib-1.3-26.jar
-  Baubles-1.12-1.5.2.jar
-  BetterFps-1.4.8.jar
-  BiomesOPlenty-1.12.2-7.0.1.2427-universal.jar
-  BrandonsCore-1.12.2-2.4.10.198-universal.jar
-  Cavern_1.12.2-v2.1.9.jar
-  ChickenChunks-1.12.2-2.4.1.73-universal.jar
-  Chisel-MC1.12.2-0.2.1.35.jar
-  Clumps-3.1.2.jar
-  CodeChickenLib-1.12.2-3.2.2.353-universal.jar
-  CoFHCore-1.12.2-4.6.2.25-universal.jar
-  CoFHWorld-1.12.2-1.3.0.6-universal.jar
-  ComputerCraft1.80pr1.jar
-  CTM-MC1.12.2-0.3.3.22.jar
-  Cucumber-1.12.2-1.1.3.jar
-  Decocraft-2.6.2_1.12.2.jar
-  Draconic-Evolution-1.12.2-2.3.21.342-universal.jar
-  DynamicSurroundings-1.12.2-3.5.4.3.jar
-  DynamicTrees-1.12.2-0.9.5.jar
-  DynamicTreesBOP-1.12.2-1.4.1e.jar
-  DynamicTreesPHC-1.12.2-1.4.2.jar
-  DynamicTreesTC-1.12.2-1.4.1e.jar
-  EnderStorage-1.12.2-2.4.5.135-universal.jar
-  enderutilities-1.12.2-0.7.12.jar
-  energyconverters_1.12.2-1.2.1.11.jar
-  ExtraCells-1.12.2-2.6.2a.jar
-  ExtraPlanets-1.12.2-0.5.2.jar
-  extrautils2-1.12-1.9.9.jar
-  ExtremeReactors-1.12.2-0.4.5.65.jar
-  FastLeafDecay-v14.jar
-  foamfix-0.10.5-1.12.2.jar
-  FTBLib-5.4.1.96.jar
-  FTBUtilities-5.4.0.94.jar
-  FTBUtilitiesBackups-1.0.0.3.jar
-  GalacticraftCore-1.12.2-4.0.2.210.jar
-  Galacticraft-Planets-1.12.2-4.0.2.210.jar
-  Hwyla-1.8.26-B41_1.12.2.jar
-  industrialcraft-2-2.8.125-ex112.jar
-  instantunify-1.12.2-1.1.2.jar
-  IronBackpacks-1.12.2-3.0.8-12.jar
-  ironchest-1.12.2-7.0.59.842.jar
-  jei_1.12.2-4.15.0.278.jar
-  journeymap-1.12.2-5.5.5b4.jar
-  LagGoggles-SPONGEFORGE-1.12.2-4.1.jar
-  malisiscore-1.12.2-6.5.1.jar
-  Mantle-1.12-1.3.3.49.jar
-  MatterOverdrive-1.12.2-0.7.1.0-universal.jar
-  mcjtylib-1.12-3.1.1.jar
-  Mekanism-1.12.2-9.7.2.373.jar
-  MekanismGenerators-1.12.2-9.7.2.373.jar
-  MekanismTools-1.12.2-9.7.2.373.jar
-  memory_repo
-  MicdoodleCore-1.12.2-4.0.2.210.jar
-  MJRLegendsLib-1.12.2-1.1.8.jar
-  MooFluids-1.12.2-1.8.12.02a.jar
-  MysticalAgriculture-1.12.2-1.7.3.jar
-  NetherPortalFix_1.12.1-5.3.17.jar
-  omlib-1.12.2-3.1.0-224.jar
-  OpenBlocks-1.12.2-1.8.1.jar
-  OpenComputers-MC1.12.2-1.7.4.153.jar
-  OpenModsLib-1.12.2-0.12.2.jar
-  openmodularturrets-1.12.2-3.1.0-326.jar
-  OreLib-1.12.2-3.5.2.2.jar
- "Pam's+HarvestCraft+1.12.2zc+The+7mm+Kidney+Stone+Update.jar"
-  plethora-1.12.2-1.1.13.jar
-  pneumaticcraft-repressurized-1.12.2-0.10.3-337.jar
-  ProgressiveAutomation-1.12.2-1.7.8.jar
-  PTRLib-1.0.4.jar
-  Quark-r1.5-146.jar
-  RedstoneFlux-1.12-2.1.0.6-universal.jar
-  rftools-1.12-7.61.jar
-  rftoolsctrl-1.12-1.9.3.jar
-  rftoolsdim-1.12-5.64.jar
-  SERVER-DiscordChat-1.12.2-2.3.0.jar
-  SERVER-Login_Shield-1.12.2-3-g7c6e7ac.jar
-  Stargate-Network-Mod-SGCraft-2.0.0-beta-5.jar
-  TConstruct-1.12.2-2.12.0.135.jar
-  techguns-1.12.2-2.0.1.2_1.jar
-  Thaumcraft-1.12.2-6.1.BETA26.jar
-  TheBetweenlands-3.4.6-server.jar
-  ThermalDynamics-1.12.2-2.5.4.18-universal.jar
-  ThermalExpansion-1.12.2-5.5.3.41-universal.jar
-  ThermalFoundation-1.12.2-2.6.2.26-universal.jar
-  TreeChopper-1.12.2-1.2.4.jar
-  twilightforest-1.12.2-3.9.888-universal.jar
-  zerocore-1.12.2-0.1.2.8.jar

**Comment by ryaniskira** [comment]
Update: just installed EnderIO and item conduits [present the same behavior as Mekanism's logistical transporters](https://imgur.com/a/mAClsi0).

**Comment by micdoodle8** [comment]
All item transfer systems should now work with Galacticraft. Thank you for the report.
