### ISSUE TITLE
Floating lava worldgen error on Venus

### ISSUE THREAD

**Issue by kouwei32** [micdoodle8/Galacticraft#3687]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 4.0.2.210

Floating lava generated on Venus. See screenshot.

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP
Any Galacticraft add-ons installed? please list all
None
Please provide screenshots / crash report / log / full modlist as needed
![image](https://user-images.githubusercontent.com/29967594/57422110-82e33300-71c3-11e9-8eee-18f980015ffe.png)

**Comment by micdoodle8** [comment]
Thanks, this should be fixed in the next build.
