### ISSUE TITLE
Stair blocks not sealable

### ISSUE THREAD

**Issue by elian1203** [micdoodle8/Galacticraft#3688]
Just as the title says. I tried sealing a room with stairs on the solid side facing indoors as the wiki says is possible, but it was not sealed. Covered all the stairs up, then the Oxygen Sealers worked.
MC Version 1.12.2
Galacticraft Version: 1.12.2-4.0.2.210

**Comment by MJRLegends** [comment]
just add them too this list in the core.conf Galacticraft config file

```
    # List non-opaque blocks from other mods (for example, special types of glass) that the Oxygen Sealer should recognize as solid seals. Format is BlockName or BlockName:metadata
    S:"External Sealable IDs" <
        
     >
```
