### ISSUE TITLE
Galactacraft Crash When 2 person Server Tried to fly to Mars.

### ISSUE THREAD

**Issue by Vnldwth** [micdoodle8/Galacticraft#3690]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 4.0.1.181
     planets: 4.0.1.128

SSP open to LAN with one person +host
Galactacraft Planets Added V: 4.0.1.128

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
  CXLibraryCore (CXLibrary-1.12.1.jar)
  weaponlib (Modern-Warfare-Mod-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 5/12/19 8:01 PM
Description: Exception generating new chunk

java.lang.NoSuchFieldError: field_185995_n
	at micdoodle8.mods.galacticraft.planets.mars.world.gen.ChunkProviderMars.onChunkProvide(ChunkProviderMars.java:111)
	at micdoodle8.mods.galacticraft.api.prefab.world.gen.ChunkProviderSpace.func_185932_a(ChunkProviderSpace.java:252)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143)
	at net.minecraft.world.World.func_72964_e(World.java:310)
	at net.minecraft.world.World.func_72838_d(World.java:1208)
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058)
	at net.minecraft.server.management.PlayerList.func_72377_c(PlayerList.java:377)
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:166)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at micdoodle8.mods.galacticraft.planets.mars.world.gen.ChunkProviderMars.onChunkProvide(ChunkProviderMars.java:111)
	at micdoodle8.mods.galacticraft.api.prefab.world.gen.ChunkProviderSpace.func_185932_a(ChunkProviderSpace.java:252)

-- Chunk to be generated --
Details:
	Location: -27,-31
	Position hash: -128849018907
	Generator: micdoodle8.mods.galacticraft.planets.mars.world.gen.ChunkProviderMars@407dc2c
Stacktrace:
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143)
	at net.minecraft.world.World.func_72964_e(World.java:310)
	at net.minecraft.world.World.func_72838_d(World.java:1208)
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058)
	at net.minecraft.server.management.PlayerList.func_72377_c(PlayerList.java:377)
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:166)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@663dae23
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1857737576 bytes (1771 MB) / 3154116608 bytes (3008 MB) up to 17179869184 bytes (16384 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx16G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 14, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 41 mods loaded, 41 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                    | Version           | Source                                      | Signature                                |
	|:--------- |:--------------------- |:----------------- |:------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft             | 1.12.2            | minecraft.jar                               | None                                     |
	| UCHIJAAAA | mcp                   | 9.42              | minecraft.jar                               | None                                     |
	| UCHIJAAAA | FML                   | 8.0.99.99         | forge-1.12.2-14.23.5.2768.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                 | 14.23.5.2768      | forge-1.12.2-14.23.5.2768.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | micdoodlecore         |                   | minecraft.jar                               | None                                     |
	| UCHIJAAAA | baubles               | 1.5.2             | Baubles-Mod-1.12.2.jar                      | None                                     |
	| UCHIJAAAA | artifacts             | 1.12.2-1.0.2      | Artifacts-Mod-1.12.2.jar                    | None                                     |
	| UCHIJAAAA | buildcraftlib         | 7.99.14           | BuildCraft-Mod-1.12.2.jar                   | None                                     |
	| UCHIJAAAA | buildcraftcore        | 7.99.14           | BuildCraft-Mod-1.12.2.jar                   | None                                     |
	| UCHIJAAAA | buildcraftbuilders    | 7.99.14           | BuildCraft-Mod-1.12.2.jar                   | None                                     |
	| UCHIJAAAA | buildcraftenergy      | 7.99.14           | BuildCraft-Mod-1.12.2.jar                   | None                                     |
	| UCHIJAAAA | buildcraftfactory     | 7.99.14           | BuildCraft-Mod-1.12.2.jar                   | None                                     |
	| UCHIJAAAA | buildcraftrobotics    | 7.99.14           | BuildCraft-Mod-1.12.2.jar                   | None                                     |
	| UCHIJAAAA | buildcraftsilicon     | 7.99.14           | BuildCraft-Mod-1.12.2.jar                   | None                                     |
	| UCHIJAAAA | buildcrafttransport   | 7.99.14           | BuildCraft-Mod-1.12.2.jar                   | None                                     |
	| UCHIJAAAA | extendedrenderer      | v1.0              | CoroUtil-1.12.2.jar                         | None                                     |
	| UCHIJAAAA | coroutil              | 1.12.1-1.2.19     | CoroUtil-1.12.2.jar                         | None                                     |
	| UCHIJAAAA | configmod             | v1.0              | CoroUtil-1.12.2.jar                         | None                                     |
	| UCHIJAAAA | cxlibrary             | 1.6.1             | CXLibrary-1.12.1.jar                        | None                                     |
	| UCHIJAAAA | dmonsters             | 1.6               | Deadly-Monsters-Mod-1.12.2.jar              | None                                     |
	| UCHIJAAAA | deconstruction        | 3.0.3             | Deconstruction-Table-Mod-1.12.2.jar         | None                                     |
	| UCHIJAAAA | dldungeonsjbg         | 1.12.3            | DoomlikeDungeons-1.12.2.jar                 | None                                     |
	| UCHIJAAAA | ic2                   | 2.8.107-ex112     | Industrialcraft-1.12.2.jar                  | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJAAAA | galacticraftcore      | 4.0.1.181         | Galacticraft-Mod-1.12.2.jar                 | None                                     |
	| UCHIJAAAA | galacticraftplanets   | 4.0.1.128         | Galacticraft-Planets-1.12.2.jar             | None                                     |
	| UCHIJAAAA | icbmclassic           | 1.12.2-3.3.0.63   | ICBM-classic-1.12.2-3.3.0b63.jar            | None                                     |
	| UCHIJAAAA | imsm                  | 1.12              | Instant-Massive-Structures-Mod-1.12.jar     | None                                     |
	| UCHIJAAAA | ironchest             | 1.12.2-7.0.59.842 | Iron-Chests-Mod-1.12.2.jar                  | None                                     |
	| UCHIJAAAA | jei                   | 4.15.0.269        | jei_1.12.2-4.15.0.269.jar                   | None                                     |
	| UCHIJAAAA | lucky                 | 7.5.0             | Lucky-Block-Mod-1.12.zip                    | None                                     |
	| UCHIJAAAA | mocreatures           | 12.0.5            | Mo-Creatures-Mod-1.12.2.jar                 | None                                     |
	| UCHIJAAAA | mw                    | 1.11.7.7          | Modern-Warfare-Mod-1.12.2.jar               | None                                     |
	| UCHIJAAAA | morefurnaces          | 1.10.1            | More-Furnaces-Mod-1.12.1.jar                | None                                     |
	| UCHIJAAAA | cfm                   | 6.2.0             | MrCrayfishs-Furniture-Mod-1.12.2.jar        | None                                     |
	| UCHIJAAAA | orecore               | 1.3.6             | Ore-Core-Mod-1.12.2.jar                     | None                                     |
	| UCHIJAAAA | progressiveautomation | 1.7.6             | Progressive-Automation-Mod-1.12.2.jar       | None                                     |
	| UCHIJAAAA | torohealthmod         | 1.12.2-11         | ToroCrafts-Damage-Indicators-Mod-1.12.2.jar | None                                     |
	| UCHIJAAAA | treechopper           | 1.2.4             | TreeChopper-1.12.2.jar                      | None                                     |
	| UCHIJAAAA | wearablebackpacks     | 3.1.3             | WearableBackpacks-1.12.jar                  | None                                     |
	| UCHIJAAAA | weather2              | 1.12.1-2.6.12     | Weather-Storms-Tornadoes-Mod-1.12.2.jar     | None                                     |
	| UCHIJAAAA | xaerominimap          | 1.16.3            | Xaeros-Minimap-Mod-1.12 (1).jar             | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
CXLibraryCore (CXLibrary-1.12.1.jar)
  cubex2.cxlibrary.CoreModTransformer
weaponlib (Modern-Warfare-Mod-1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [GCEntityPlayerMP['Texturalpie'/170, l='here we go...again...', x=-417.50, y=1207.30, z=-492.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'`

------------------------------------------------------------------------------

If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft)

Yes, Confirmed.

Host entered rocket, launched, game crashed, re opened, host selected mars and P2 launched rocket, game crashed (presumably from the launch), game now exits on hosts end when SSP world is selected.

[Crash Text.txt](https://github.com/micdoodle8/Galacticraft/files/3171008/Crash.Text.txt)

**Comment by marcus8448** [comment]
From the looks of your filenames, you seem to have downloaded the mod from a illegal/non-official webpage for example: 9minecraft. Also checkout [Stop Mod Reposts](stopmodreposts.org) for more info about these sites. Please re-download Galacticraft from here: https://micdoodle8.com/mods/galacticraft/downloads .
