### ISSUE TITLE
[1.12.2]Crashed with Arclamp

### ISSUE THREAD

**Issue by helhel1** [micdoodle8/Galacticraft#3692]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: GalacticraftCore-1.12.2-4.0.2.210

Multiplayer (SMP)

1 - Advanced Solar Panels
2 - AE2 Stuff
3 - Alternating Flux
4 - Applied Energistics 2
5 - Avaritia
6 - Baubles
7 - BiblioCraft
8 - Binnie’s Mods
9 - Biomes O' Plenty
10 - BlackThorne Empire Vehicles
11 - Blockcraftery
12 - BuildCraft
13 - Chisel
14 - Crafting EX
15 - Custom NPCs
16 - Ender IO
17 - Ender Storage
18 - Energy Converters
19 - Extra Cells 2
20 - Extra Planets
21 - Extra Utilities 2
22 - Extreme Reactors
23 - Fast Leaf Decay
24 - Forestry
25 - Galacticraft
26 - Gendustry
27 - Gravitation Suite
28 - Immersive Cables
29 - Immersive Engineering
30 - Immersive Petroleum
31 - Immersive Railroading
32 - Immersive Tech
33 - Immersive Vehicles
34 - Industrial Foregoing
35 - Industrial Wires
36 - Industrial Craft 2
37 - Inventory Tweaks
38 - Iron Chests
39 - Just Enough Items (JEI)
40 - MalisisDoors
41 - Matter Overdrive: Legacy Edition
42 - Mekanism
43 - Mekanism Generators
44 - MrCrayfish’s Furniture
45 - MTS Caterpillar-Pack
46 - MTS Heavy Industrial Pack by AdamRK
47 - Not Enough Items
48 - Online Picture Frame
49 - Open Modular Passive Defense
50 - Open Modular Turrets
51 - Open Blocks
52 - Practical Space Fireworks
53 - RailCraft
54 - Roguelike Dungeons
55 - Schematica
56 - Space Extended Mod
57 - The Official Vehicle Set for MTS
58 - Thermal Dynamics
59 - Thermal Expansion
60 - Thermal Foundation
61 - Tinkers’ Construct
62 - UNU Parts Pack
63 - Hwyla-Waila
64 - World Control

[crash-2019-05-12_23_03_04-server (1).txt](https://github.com/micdoodle8/Galacticraft/files/3186090/crash-2019-05-12_23_03_04-server.1.txt)

Crash occurs only if you put an arc lamp, crash does not occur instantly, but after a while.

**Comment by micdoodle8** [comment]
Can I get the full latest.log please, it's definitely caused by the arc lamp but it looks like that crash is only part of the problem.
