### ISSUE TITLE
Need to reset Mars, how?

### ISSUE THREAD

**Issue by silipopilli** [micdoodle8/Galacticraft#3694]
I am playing "The 1.7.10 Pack" with a few friends and the airlock somehow crashes the server every time I join, so I can't get away. Is there any way to reset the Mars or to delete it or to move me to another dimension? Greetings, Silas

**Comment by MJRLegends** [comment]
Delete DIM-29 folder or you can edit out the block using mc edit or delete the region file if you know how.

**Comment by MJRLegends** [comment]
Also for future reference the Galacticraft devs prefer questions like this to be on there forum and not here. They like to keep this bugs only
