### ISSUE TITLE
Unexpected error crash

### ISSUE THREAD

**Issue by WatermelonPL** [micdoodle8/Galacticraft#3697]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 4.0.2.210

Single player (SSP)

Any Galacticraft add-ons installed? No.

Please provide screenshots / crash report / log / full modlist as needed https://pastebin.com/zcXN5C6Z, modlist: Discord Rich Presence, Music Player (mod that allows for playing music from YT in MC), Optifine, RPG Hud, Thut Core, Thut Tech, U Team Core, WorldEdit

If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft): First downloaded from 9minecraft.net, then from official site

**Comment by TheQuadShot** [comment]
This is a crash in your Discord app. you can file a bug there:
https://github.com/paulhobbel/DiscordRP/issues

**Comment by TheQuadShot** [comment]
Evidently this is a known issue. There is a version of it for Galacticraft you can find it here:
https://minecraft.curseforge.com/projects/galacticraft-rpc

**Comment by marcus8448** [comment]
Update DiscordRP to 1.2.19 - See paulhobbel/DiscordRP#2
