### ISSUE TITLE
Galacticraft Causes Minecraft to no longer work.

### ISSUE THREAD

**Issue by Flatbox52** [micdoodle8/Galacticraft#3698]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: Unknown

Both (Single Player, Multiplayer, LAN) 

No addons were installed

No Screenshot, Log or anything available. 

Yes i have downloaded the mod from https://micdoodle8.com/mods/galacticraft/downloads

**Comment by TheQuadShot** [comment]
You have provided absolutely no information what so ever. This makes is absolutely impossible to help you. You could start with the list that the report asks you to provide, and at least confirm that you do have valid files (from the link provided), and uploading(to pastebin.com) and providing a link of the latest.log file.
