### ISSUE TITLE
Oil not entering the refinery 

### ISSUE THREAD

**Issue by SolSavvy** [micdoodle8/Galacticraft#3699]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 4.0.2.210

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?: Singleplayer

Any Galacticraft add-ons installed? please list all: Galacticraft Planets

Please provide screenshots / crash report / log / full modlist as needed

If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft)

![2019-06-04_18 07 25](https://user-images.githubusercontent.com/27328200/58917335-30c6fc00-86f4-11e9-9173-5d773fcd08cf.png)

![2019-06-04_18 07 37](https://user-images.githubusercontent.com/27328200/58917347-36244680-86f4-11e9-8821-824160877770.png)

**Comment by TheQuadShot** [comment]
Based on the image your pumping from both ends of the pipe. The black band should be against/abut the tank or machine you want to "pull" from. like this:
https://imgur.com/2BXwbj6
![2019-06-04_17 51 21](https://user-images.githubusercontent.com/11265900/58922918-0411e500-86f2-11e9-82d0-c85ede3454d8.png)
