### ISSUE TITLE
World once loaded with Galacticraft but not Aether now crashes after entering Aether

### ISSUE THREAD

**Issue by chasejsutton49** [micdoodle8/Galacticraft#3700]
Minecraft version: 1.12.2
Galacticraft version: 4.0.2.210

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Single player (SSP)
Any Galacticraft add-ons installed? please list all
No addons installed.

Issue:
Sorry for the mouthful of the issue name. A detailed breakdown, I started a world about over a year ago with Galacticraft but not Aether Legacy. About a few months later, I added Aether Legacy to the world, and nothing was wrong at first. I managed to enter the Aether Dimension without it crashing, only to have to game suddenly stop 2 to 5 minutes later. When I re-log, I'm right back to where I left off in the Aether, and I can play again only for a few minutes. I checked the crash report each and every time this happened, and all I can make from it is that Galacticraft is causing the problem because of "ticking". I checked the mods configs and the world files to see if anything was conflicting, but the dimension ID's are absolutely different (both in the config and the world) and the only adjustment *I* made to the configs was so you could not launch rockets in the Aether. So it's nothing to do with dimensions, and I really doubt the configs are causing it, all I know is that Galacticraft is causing this, just not sure what this "ticking" issue is or how to fix it. Here's the crash-report and the log. And yes, I'm using plenty of other mods but they don't seem to be causing this.

[crash-2019-06-08_12.05.14-server.txt](https://github.com/micdoodle8/Galacticraft/files/3268759/crash-2019-06-08_12.05.14-server.txt)
[latest.log](https://github.com/micdoodle8/Galacticraft/files/3268761/latest.log)

**Comment by micdoodle8** [comment]
Should be fixed in the next build. Thanks :)
