### ISSUE TITLE
Problems with Galacticraft, can't launch to the moon.

### ISSUE THREAD

**Issue by Bambi2001** [micdoodle8/Galacticraft#3701]
I can't go to the moon, the launch button and tier requirement is red, i can go to my space station on the overworld but that's it.
![Screen Shot 2019-06-09 at 12 52 35 PM](https://user-images.githubusercontent.com/51537119/59161972-72babe00-8ab7-11e9-981b-7188004f2626.png)
![Screen Shot 2019-06-09 at 12 32 37 PM](https://user-images.githubusercontent.com/51537119/59161974-751d1800-8ab7-11e9-8616-1555429ac699.png)

Minecraft version: 1.12.2
Galacticraft version: 4.0.2

SSP

Any Galacticraft add-ons installed? please list all
ExtraPlanets and MorePlanets

**Comment by Bambi2001** [comment]
I'd also like to know of a way to get rid of that details screen so i can actually see the planets and such

**Comment by marcus8448** [comment]
I'm pretty sure it's caused by a dimension ID conflict, try changing it in the galacticraft core config. If that still doesn't work, please send your log on [Gist](https://gist.github.com).

**Comment by Bambi2001** [comment]
> I'm pretty sure it's caused by a dimension ID conflict, try changing it in the galacticraft core config. If that still doesn't work, please send your log on [Gist](https://gist.github.com).

I tried changing its dimension in the core config but that didn't work, i sent my log

**Comment by micdoodle8** [comment]
You're still getting dimension ID conflicts

`[14:47:44] [main/ERROR] [Galacticraft]: Tried to register dimension for body: planet.Uranus hit conflict with ID -17`

**Comment by Bambi2001** [comment]
> You're still getting dimension ID conflicts
> 
> `[14:47:44] [main/ERROR] [Galacticraft]: Tried to register dimension for body: planet.Uranus hit conflict with ID -17`

how do i fix it?

**Comment by Bambi2001** [comment]
Alright nevermind guys, i figured it out and i can go to the moon now, thanks for the help
