### ISSUE TITLE
Broken item model for Hydraulic Platform

### ISSUE THREAD

**Issue by QuantumStatement** [micdoodle8/Galacticraft#3703]
Minecraft version: 1.12.2
Galacticraft version: 4.0.2.211

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP

Any Galacticraft add-ons installed? please list all
No

Please provide screenshots / crash report / log / full modlist as needed
![2019-06-14_00 38 19](https://user-images.githubusercontent.com/35406698/59536592-c3d61200-8efc-11e9-82a8-86d5d5d405b5.png)

**Comment by MJRLegends** [comment]
Looks good to me, whats wrong with it?

**Comment by TheQuadShot** [comment]
Just a guess, on the tool bar it's not a "3d block" and same for 3rd person as well as the size of the "block". I agree though, it's not a bug. The issue I have is in first person it just looks weird, but again it's not a bug imho.
