### ISSUE TITLE
Uhh micdoodle but he's on discord

### ISSUE THREAD

**Issue by SebaSphere** [micdoodle8/Galacticraft#3706]
@micdoodle8 Hey sorry for this being the improper place but don't know where else to contact you. Thanks for fixing the discord link on site the other day. Gonna guess Ezer'Arch relayed that to you. 

But Ill be away 

June 18 until July 2
July 6 until July 14

Best place to contact me is SebaSphereEmails@gmail.com during that time

I'd probably check the discord out and let people know you are alive lol

**Comment by SebaSphere** [comment]
Actually just found your email on profile.

**Comment by SebaSphere** [comment]
![image](https://user-images.githubusercontent.com/27737877/59643194-b35cac00-9135-11e9-8f97-1b887bdeefb2.png)
🤔

**Comment by SebaSphere** [comment]
I'll leave this open just in case you don't check email.

**Comment by EzerArch** [comment]
> Gonna guess Ezer'Arch relayed that to you.

S**t! forgot to check if mic replied. Yep, he did. 7 day ago. >_<'

Glad to hear the discord link got fixed.
