### ISSUE TITLE
Problems with the game on the network

### ISSUE THREAD

**Issue by Kane1395** [micdoodle8/Galacticraft#3707]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)
Sorry for language. Im from russia)
Minecraft version: 1.12.2
Galacticraft version: 4.0.1.181
Play on networks, have friend there is no planets except earth and Cosmo station (I host). The game is about the rest of the planet says that is unknown. And, too, most I have if my friend host. (Sorry for translator)
LAN

Any Galacticraft add-ons installed? More Planets.

Please provide screenshots / crash report / log / full modlist as needed
![p_BJF_-IRkQ](https://user-images.githubusercontent.com/51949028/59670979-e3f02480-91cd-11e9-82d5-afa3fc4b5207.jpg)
![NAB_yN3TXL4](https://user-images.githubusercontent.com/51949028/59671014-f8ccb800-91cd-11e9-875c-2d07f723adb5.jpg)
![LhhpJTb-cNk](https://user-images.githubusercontent.com/51949028/59671146-36c9dc00-91ce-11e9-96fa-5abd2722f33a.jpg)

**Comment by Kane1395** [comment]
First screenshot from my computer (I host). Second screenshot from my friend's computer.

**Comment by micdoodle8** [comment]
Can you try without more planets? That addon makes a lot of changes to the celestial map screen.

**Comment by MJRLegends** [comment]
That celestial map is from galaxy space addon.

**Comment by micdoodle8** [comment]
Ah you're right, my mistake
