### ISSUE TITLE
Chromatic Applicator sometimes applies across worlds

### ISSUE THREAD

**Issue by hypehuman** [micdoodle8/Galacticraft#3709]
Minecraft version: 1.12.2
Galacticraft versions: 1.12.2-4.0.1.181 (Promoted) and 1.12.2-4.0.2.211 (Latest)
Forge version: 1.12.2-14.23.5.2768 (Recommended)
Game modes tested: SSP and LAN
No addons/mods besides the three Galacticraft mods.

When you open a world with a color applied, and then open a world that has never seen a Chromatic Applicator, the second world "remembers" the first world's colors. Restarting the program seems to temporarily fix the issue.

Steps to reproduce:
1. Create a new singleplayer world (let's call it World One)
2. Use a Chromatic Applicator to apply a bright color to a piece of vacuum glass
3. Exit the world, but don't exit Minecraft
4. Create a new singleplayer world (let's call it World Two)
5. Place a piece of vacuum glass (make sure it's the same type as in Step 2).
6. Observe the color of the frame. **Expected Behavior**: The glass is the default grayish color. **Actual Behavior**: The glass is dyed the same color as in Step 2.
7. Exit the Minecraft application
8. Open Minecraft again enter World Two
9. Observe the appropriately colorless glass
10. Enter World One.
11. Exit World One.
12. Enter World Two.
13. Observe the color of the frame. **Expected Behavior**: The glass is the default grayish color. **Actual Behavior**: The glass is dyed the same color as in Step 2.

**Comment by radfast** [comment]
Thank you @hypehuman for this extremely clear issue report.  This fix should be included from next build 236.
