### ISSUE TITLE
PacketSimple causing server to crash

### ISSUE THREAD

**Issue by rzhong9963** [micdoodle8/Galacticraft#3710]
Minecraft version: 1.12.2
Galacticraft version: Build 211

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? Multiplayer

Any Galacticraft add-ons installed? None

Please provide screenshots / crash report / log / full modlist as needed
[crash-2019-06-29_18.05.51-server.txt](https://github.com/micdoodle8/Galacticraft/files/3342197/crash-2019-06-29_18.05.51-server.txt)
Mods used listed in debug portion of crash report.

The server crashes once every few hours in multiplayer. I have tried an earlier version but that did not help. I haven't gotten any crashes of similar nature to this with any of the other mods.

**Comment by micdoodle8** [comment]
I believe this should be fixed. If the crash continues in build 222 or after, feel free to re-post the issue (with new server log, as I've added a bit of debug info).
