### ISSUE TITLE
Meteor block doesn't appear when meteor strikes a vertical wall

### ISSUE THREAD

**Issue by hypehuman** [micdoodle8/Galacticraft#3713]
Minecraft version: 1.12.2
Galacticraft versions: 1.12.2-4.0.1.181 (Promoted) and 1.12.2-4.0.2.211 (Latest)
Forge version: 1.12.2-14.23.5.2768 (Recommended)
Game modes tested: SSP and LAN
No addons/mods besides the three Galacticraft mods.

When a meteor strikes a vertical wall (specifically, when it the side of a block that has another block on top of it), it explodes, but no meteor block is generated. I would have expected either for the meteor block to be generated on the side of the struck block and then fall down, or for the meteor to go through the exploded block(s) and then strike there.

I looked at the code, and the problem is that it assumes that the meteor struck the top face of the block: https://github.com/micdoodle8/Galacticraft/blob/33af6a3803b6ccc7c5030da13bcfda6c1cec4750/src/main/java/micdoodle8/mods/galacticraft/core/entities/EntityMeteor.java#L153-L157

**I think if we use the provided `RayTraceResult` object, we could get the `RayTraceResult.sideHit` to get which face of the block was struck and generate the meteor there instead of always assuming that it struck the top face.**

Alternatively (and this feels more like a feature suggestion than a bug fix), we could first cause the explosion, then run the RayTrace once more, and place the meteor inside the explosion hole. I think then we could get rid of the meteor being gravity-effected, which seems like it's there just to make the meteor fall into its own explosion hole.

**Comment by micdoodle8** [comment]
Thanks for the detailed report! I ended up getting good results just by doing the explosion first without re-running the ray trace:

![2019-08-12_16 42 08](https://user-images.githubusercontent.com/1098060/62897044-5ee24100-bd20-11e9-8d27-e7655f606f8b.png)

Next build (231+) has proper meteor behavior.
