### ISSUE TITLE
Packet Simple causing crash on log in

### ISSUE THREAD

**Issue by Deltatacoman** [micdoodle8/Galacticraft#3715]
Minecraft version: 1.12.2
Galacticraft version: 4.0.1.181

Multiplayer Sponge Server

More Planets for GC 4.0.1.181
[server log.txt](https://github.com/micdoodle8/Galacticraft/files/3356849/server.log.txt) - server log

https://pastebin.com/jde2Vnpr - Crash Report

If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft)

The crash happens when certain players join the server, the entire server goes down and restarts, sometimes when the server restarts and the same players join the server doesn't immediately crash, but after about 10 minutes the server goes down again.

**Comment by micdoodle8** [comment]
This is a very strange crash - I'm not sure if it's an attack. If you don't mind me asking, do you know the players personally or is this a public server? And do you notice a pattern of certain players causing the crash?

**Comment by micdoodle8** [comment]
I believe this should be fixed. If the crash continues in build 222 or after, feel free to re-post the issue (with new server log, as I've added a bit of debug info).
