### ISSUE TITLE
terraformer and other blocks are not appearing

### ISSUE THREAD

**Issue by edgelord1** [micdoodle8/Galacticraft#3718]
buildcraft is installed

**Comment by edgelord1** [comment]
pipe walkways have disappeared too

**Comment by MJRLegends** [comment]
Congratulations on making the most unhelpful issue report ever

**Comment by edgelord1** [comment]
...

**Comment by edgelord1** [comment]
so basically, I booted up the game and played withe galacticraft a bit. I noticed some things were missing like the terraformer:https://www.google.com/imgres?imgurl=https%3A%2F%2Fwiki.micdoodle8.com%2Fimages%2F4%2F41%2FTerraformer.png&imgrefurl=https%3A%2F%2Fwiki.micdoodle8.com%2Fwiki%2FTerraformer&docid=G8BHS_qeHc262M&tbnid=7RCVoLWpDM7A1M%3A&vet=10ahUKEwikvty0_p7jAhWTFXwKHcrLB4YQMwhCKAEwAQ..i&w=150&h=150&bih=902&biw=1280&q=galacticraft%20terraformer&ved=0ahUKEwikvty0_p7jAhWTFXwKHcrLB4YQMwhCKAEwAQ&iact=mrc&uact=8 and some other blocks and items, like the Astro miner:https://www.google.com/imgres?imgurl=https%3A%2F%2Fwiki.micdoodle8.com%2Fimages%2Fthumb%2F4%2F40%2FAstro_Miner.png%2F150px-Astro_Miner.png&imgrefurl=https%3A%2F%2Fwiki.micdoodle8.com%2Fwiki%2FAstro_Miner&docid=5YJJUrI11nDJlM&tbnid=PPoCptNQqAJEDM%3A&vet=10ahUKEwj30p7I_p7jAhVmj1QKHWSLAZsQMwhIKAQwBA..i&w=150&h=126&bih=902&biw=1280&q=galacticraft%20miner&ved=0ahUKEwj30p7I_p7jAhVmj1QKHWSLAZsQMwhIKAQwBA&iact=mrc&uact=8

**Comment by TheQuadShot** [comment]
@edgelord1 There are some questions on the form when you file a bug, non of which you answered. So we have no idea what version your running, or if it's even an official release. So there is absolutely no way anyone can even try to help you. And since you are the only one reporting this, it's more than likely that the problem/issue is on your end, but we can't tell anything from this report.  So we are still looking for something from you...

**Comment by marcus8448** [comment]
^
Please provide your minecraft version, full modlist, galacticraft version number (**NOT 'LATEST' or 'RECOMMENDED'**), your log, and where you downloaded galacticraft from

**Comment by edgelord1** [comment]
my minecraft version is 1.12.2
mods installed:
buildcraft
thermal dynamics
thermal expansion
thermal foundation
redstone flux
Cofh core
Cofh world
better animals+
crayfish mods
optifine 
claysoldiers mod
and of course galacticraft
my version is 4
I downloaded galacticraft straight from micdoodle8.com

**Comment by marcus8448** [comment]
I don't see anything out of the ordinary... Could you upload your logfile via [gist](https://gist.github.com/)?

**Comment by edgelord1** [comment]
[latest.log](https://github.com/micdoodle8/Galacticraft/files/3366193/latest.log)

**Comment by edgelord1** [comment]
here is the latest log

**Comment by marcus8448** [comment]
Try without optifine

**Comment by edgelord1** [comment]
i did but it still does not work

**Comment by micdoodle8** [comment]
Can I see a screenshot of your blocks tab in creative? This is what I see:

![2019-07-21_12 39 51](https://user-images.githubusercontent.com/1098060/61594014-df47d300-abb4-11e9-9c27-75cd0d6083d4.png)
