### ISSUE TITLE
GC Mobs Spawing In The Overworld

### ISSUE THREAD

**Issue by MokahTGS** [micdoodle8/Galacticraft#3723]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 
Galacticraft-Planets-1.12.2-4.0.2.211
GalacticraftCore-1.12.2-4.0.2.211
MicdoodleCore-1.12.2-4.0.2.211

Full Mod List: https://pastebin.com/A4Lx9dt4

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? SSP

Any Galacticraft add-ons installed? please list all
PlanetProgression-1.12.2-0.3.6
More-Planets-1.12.2-2.0.19-GC211

Please provide screenshots / crash report / log / full modlist as needed

https://www.dropbox.com/s/d2a6odo00nq0twe/2019-07-14_17.11.25.png?dl=0

https://www.dropbox.com/s/0rtcymvjk1r6vrh/2019-07-14_17.11.32.png?dl=0

**Comment by TheQuadShot** [comment]
You have a biome conflict, biome ID's for GC are 102-105 here's a wiki page that might help. Please close this issue report. Thanks

https://wiki.micdoodle8.com/wiki/Compatibility

**Comment by MokahTGS** [comment]
Thanks for the help.  Can I change the GC biome numbers in a config if I needed too?

**Comment by TheQuadShot** [comment]
No, change it in the biome mod you added, I don't remember which one you used, but you should change it there.

**Comment by MokahTGS** [comment]
Yeah normally I use Biomes A Plenty and this modpack I'm building uses Biome Bundle...I'm not totally versed where it handles that stuff...I'll dig around and figure it out.  I also see in the wiki that Erebus has biome conflicts which I use as well...I'll change that config too.
