### ISSUE TITLE
Ticking Entity Crash With Mob Death Messages

### ISSUE THREAD

**Issue by Spongebobfan907** [micdoodle8/Galacticraft#3726]
Minecraft version: 1.12.2
Galacticraft version: 4.0.2.211

Any Galacticraft add-ons installed? please list all
Galacticraft Planets
Extra Planets
BlankPlanet
Planet Progression

single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? SSP

Please provide screenshots / crash report / log / full modlist as needed
https://paste.dimdev.org/zujejeqevo.mccrash

https://github.com/multiplemonomials/Mob-Death-Messages/issues/1

**Comment by MJRLegends** [comment]
Not sure how this would be Galacticraft, please stick with your multiple monomials issue report for now.

**Comment by Spongebobfan907** [comment]
> Not sure how this would be Galacticraft, please stick with your multiple monomials issue report for now.

I Had VanillaFix Installed and when it crashed I suspected that it was caused by Galacticraft core and MobDeathMesages. Did you look at the crash report?
