### ISSUE TITLE
Errors on placing and destroying coal generator

### ISSUE THREAD

**Issue by 2nt0** [micdoodle8/Galacticraft#3727]
Minecraft version: 1.12.2
Galacticraft version: 4.0.2.212
Forge Version: 14.23.5.2838

No GC add-ons or other mods installed, GC downloaded from the official site.
Single Player and Multiplayer both affected, relevant portion of [log file](https://github.com/micdoodle8/Galacticraft/files/3413689/lastest.log) from multiplayer server.

Errors are thrown when coal generator is placed, as well as broken. Block visually breaks but player cannot move through it. Item is not dropped, even when using pickaxe. Relogging SP or restarting the MP server replaces the block. Using a wrench on the block (before breaking or on the ghost block afterwards) also replaces the block.

When the block that is now present, after either relogging/restarting or using a wrench, is broken it drops two copies of itself, essentially duplicating the item. Having tested on other GC machines, it only appears to affect the coal generator.

**Comment by micdoodle8** [comment]
Thanks! I believe all the machines should be fixed as of the next build.
