### ISSUE TITLE
Server Crash with Extra Utilities 2 Quantum Quarry

### ISSUE THREAD

**Issue by Aiidoneus** [micdoodle8/Galacticraft#3729]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2 
Galacticraft version: GalacticraftCore-1.12.2-4.0.2.190

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? SMP-Sponge Server if that helps 

Any Galacticraft add-ons installed? please list all
MicdoodleCore-1.12.2-4.0.2.190 (will include this just incase)
Galacticraft-Planets-1.12.2-4.0.2.190
GalacticraftTweaker-1.12.2-1.0.3

Please provide screenshots / crash report / log / full modlist as needed
https://gist.github.com/Aiidoneus/a969f2a3eb4c6455b6b009f631418411

I am not sure what mod is at fault here. I think it points to Galaticraft? If you could point me into the right direction or need anymore information, I am more than happy to provide it. Thanks for a great mod!
-Aidoneus

**Comment by micdoodle8** [comment]
Hey! Can I see your Galacticraft config?

**Comment by Aiidoneus** [comment]
Which config? The core.conf? 
Sorry about the late reply I could have sworn I replied to this.

**Comment by micdoodle8** [comment]
All good :)

Yes, actually the core.conf and planets.conf please

**Comment by radfast** [comment]
I'm not sure that this is the same issue as #3775 and others, though it could depend on the config.  It would also be good to know which **dimension number** the Quantum Quarry "Workhouse Dimenstion" should be?  @Aiidoneus ?

**Comment by radfast** [comment]
@Aiidoneus it's definitely worth trying the [latest Galacticraft build](https://micdoodle8.com/mods/galacticraft/downloads) - that's build 236 or later.  There's a reasonable chance that will fix it for you.
