### ISSUE TITLE
Energy Storage Module Crashes Game

### ISSUE THREAD

**Issue by ow-lawd-he-comin** [micdoodle8/Galacticraft#3732]
The Energy Storage Module and the Energy Storage Cluster both crash the game once I place it, interact, or connect a wire to it. If the wire is connected, it crashes once I load up the world. This is in singleplayer, with no other mods. I am using Forge version 1.12.2

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.213.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 7/22/19 11:54 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at micdoodle8.mods.galacticraft.core.tile.TileEntityEnergyStorageModule.func_73660_a(TileEntityEnergyStorageModule.java:112)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at micdoodle8.mods.galacticraft.core.tile.TileEntityEnergyStorageModule.func_73660_a(TileEntityEnergyStorageModule.java:112)

-- Block entity being ticked --
Details:
	Name: minecraft:gc energy storage module // micdoodle8.mods.galacticraft.core.tile.TileEntityEnergyStorageModule
	Block type: ID #294 (tile.machine_tiered // micdoodle8.mods.galacticraft.core.blocks.BlockMachineTiered // galacticraftcore:machine_tiered)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (121,64,259), Chunk: (at 9,4,3 in 7,16; contains blocks 112,0,256 to 127,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #294 (tile.machine_tiered // micdoodle8.mods.galacticraft.core.blocks.BlockMachineTiered // galacticraftcore:machine_tiered)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: New Worlde
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 8964966482079810688
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (120,64,256), Chunk: (at 8,4,0 in 7,16; contains blocks 112,0,256 to 127,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3729 game time, 3729 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 147580 (now: false), thunder time: 66275 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 334406552 bytes (318 MB) / 939524096 bytes (896 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version      | Source                                    | Signature                                |
	|:------ |:------------------- |:------------ |:----------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2       | minecraft.jar                             | None                                     |
	| LCHIJA | mcp                 | 9.42         | minecraft.jar                             | None                                     |
	| LCHIJA | FML                 | 8.0.99.99    | forge-1.12.2-14.23.5.2838.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2838 | forge-1.12.2-14.23.5.2838.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | micdoodlecore       |              | minecraft.jar                             | None                                     |
	| LCHIJA | galacticraftcore    | 4.0.2.211    | GalacticraftCore-1.12.2-4.0.2.213.jar     | None                                     |
	| LCHIJA | galacticraftplanets | 4.0.2.211    | Galacticraft-Planets-1.12.2-4.0.2.213.jar | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.213.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by TheQuadShot** [comment]
I don't understand why it shows version 4.0.2.211 from GalacticraftCore-1.12.2-4.0.2.213.jar, these should match up. ie it should be Version: 4.0.2.211 Source: GalacticraftCore-1.12.2-4.0.2.211.jar etc.

Are you sure you downloaded them from https://micdoodle8.com/mods/galacticraft/downloads

**Comment by ow-lawd-he-comin** [comment]
@TheQuadShot Thank you! I fixed the problem you stated and it works like a charm!
