### ISSUE TITLE
Jenkins version number not matches the file name

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#3733]
It seems the Version Number is not updated since build 211.

![Capture](https://user-images.githubusercontent.com/6128413/61730693-192afc00-ada4-11e9-9ca7-49c3b0d7831f.PNG)

**Comment by MJRLegends** [comment]
Yea can confirm i noticed the same thing

**Comment by micdoodle8** [comment]
Good eye! Fixed, thank you.

**Comment by SteveKunG** [comment]
Its happened again with GC Build 224.
![image](https://user-images.githubusercontent.com/6128413/62281867-b65af400-b478-11e9-9319-156189f65baf.png)

**Comment by micdoodle8** [comment]
Fixed again as of build 226
