### ISSUE TITLE
Telepads have range of 65536 instead of 256

### ISSUE THREAD

**Issue by ShadowKiller1902** [micdoodle8/Galacticraft#3734]
Minecraft version: 1.12.2
Galacticraft version: 4.0.2.210

Line 495 of `galacticraft.planets.asteroids.tile.TileEntityShortRangeTelepad` checks for a distance of `TELEPORTER_RANGE * TELEPORTER_RANGE` rather than just `TELEPORTER_RANGE`, resulting in the max range of the short range telepads being `256 * 256 == 65536` instead of `256`.

**Comment by micdoodle8** [comment]
Thank you, good eye
