### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by Azure08** [micdoodle8/Galacticraft#3735]
Minecraft version: 1.12.2
Galacticraft version: 4.0.2.2.1.7

Add-ons: Extra Planets, More Planets

Crash log: https://paste.dimdev.org/ifoqikacaj.mccrash

I downloaded the mods from the official site.

**Comment by MJRLegends** [comment]
Thats just because you have reached the block limit in minecraft, remove mods to get under the limit

**Comment by Azure08** [comment]
Do you think that installing JustEnoughIDs will fix it?

**Comment by MJRLegends** [comment]
Yed
