### ISSUE TITLE
Galacticraft Capes not rendering properly on latest build

### ISSUE THREAD

**Issue by SebaSphere** [micdoodle8/Galacticraft#3739]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: Build 218

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP and SMP

Any Galacticraft add-ons installed? please list all
No

Please provide screenshots / crash report / log / full modlist as needed
![image](https://user-images.githubusercontent.com/27737877/61922705-6091c380-af2f-11e9-96e9-793aa0afc8bc.png)

If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft)

Capes don't render properly in the latest build 10/10 I love the new cape design

**Comment by SebaSphere** [comment]
Was just testing the new build and that's the first thing I notice lol.

**Comment by micdoodle8** [comment]
Is this still happening? Could be either a connection issue or github went down for a little while. Nothing has changed in the cape code for a long time.

**Comment by SebaSphere** [comment]
I'd need to check as I'm not home right now but it works fine on the promoted build (181). Need to check what build it happens as I'm using a slightly later build on my modpack and it works fine. Don't know the build number off the top of my head.

**Comment by SebaSphere** [comment]
Whoops forgot to mention I'm using forge-14.23.5.2838 @micdoodle8

**Comment by SebaSphere** [comment]
Same forge version on 181 
![image](https://user-images.githubusercontent.com/27737877/61977304-1a367600-afbc-11e9-8fae-c8f52b854e04.png)

**Comment by micdoodle8** [comment]
Fixed in the next build, thank ya

**Comment by SebaSphere** [comment]
No problem
