### ISSUE TITLE
BlockSlabGC queries BlockState from World instead of using the one passed in

### ISSUE THREAD

**Issue by MajorTuvok** [micdoodle8/Galacticraft#3741]
Minecraft version: 1.12.2 - 14.23.5.2815
Galacticraft version: 4.0.2.210

Please provide screenshots / [crash report / log](https://gist.github.com/MuteTiefling/75e41c48f2a7cd9ee523cb321c02eaa4) / full modlist as needed

A user reported to us  (see Direwolf20-MC/BuildingGadgets#330) that we were crashing when attempting to use GC slabs. Investigating the crash log, I found out that BlockSlabGC is [requerying the world for the IBlockState](https://github.com/micdoodle8/Galacticraft/blob/2d98a62f3130b1bbadda1ed9f90cb282a5f36ba7/src/main/java/micdoodle8/mods/galacticraft/core/blocks/BlockSlabGC.java#L100) in order to retrieve the pick drop. We need the pickDrop to determine  build costs. But because the block isn't build yet and MC requires a whole World instead of `IBlockAccess` to be passed into that method the Block isn't actually present in the world. Using the correct `IBlockState` which was passed in would fix that.

**Comment by micdoodle8** [comment]
Thanks, will be fixed in build 219.

I noticed the same thing is being done in tier two mars machines (Gas Liquefier, Methane Synthesizer, Electrolyzer) so it's also been fixed there.

**Comment by MajorTuvok** [comment]
Ok, thanks for the quick fix
