### ISSUE TITLE
Arc Furnace crash the server

### ISSUE THREAD

**Issue by phiphila** [micdoodle8/Galacticraft#3742]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 1.12.2-4.0.2.218

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
I play on a distant personal server

Any Galacticraft add-ons installed? please list all

Please provide screenshots / crash report / log / full modlist as needed:

---- Minecraft Crash Report ----
WARNING: coremods are present:
  CreativePatchingLoader (CreativeCore_v1.9.32_mc1.12.2.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.8-core.jar)
  MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  CharmLoadingPlugin (Charm-1.12.2-1.2.2.jar)
  LibLoader (# LibLoader.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  ForgelinPlugin (Forgelin-1.8.3.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.0.381.jar)
  CoreMod (TickProfiler-1.12-0.0.7.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.217.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 7/26/19 4:12 PM
Description: Ticking player

java.lang.ArrayIndexOutOfBoundsException: 3
	at java.util.Arrays$ArrayList.get(Arrays.java:3841)
	at net.minecraft.util.NonNullList.get(SourceFile:44)
	at micdoodle8.mods.galacticraft.core.tile.TileEntityInventory.func_70301_a(TileEntityInventory.java:92)
	at net.minecraft.inventory.Slot.func_75211_c(Slot.java:60)
	at net.minecraft.inventory.Container.func_75142_b(Container.java:79)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:324)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:642)
	at net.minecraft.world.World.func_72939_s(World.java:1734)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.Arrays$ArrayList.get(Arrays.java:3841)
	at net.minecraft.util.NonNullList.get(SourceFile:44)
	at micdoodle8.mods.galacticraft.core.tile.TileEntityInventory.func_70301_a(TileEntityInventory.java:92)
	at net.minecraft.inventory.Slot.func_75211_c(Slot.java:60)
	at net.minecraft.inventory.Container.func_75142_b(Container.java:79)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:324)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Player being ticked --
Details:
	Entity Type: null (micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP)
	Entity ID: 2221
	Entity Name: Phiphila
	Entity's Exact location: 35.12, 76.06, 306.91
	Entity's Block location: World: (35,76,306), Chunk: (at 3,4,2 in 2,19; contains blocks 32,0,304 to 47,255,319), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:642)
	at net.minecraft.world.World.func_72939_s(World.java:1734)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [GCEntityPlayerMP['Phiphila'/2221, l='world', x=35.12, y=76.06, z=306.91]]
	Chunk stats: ServerChunkCache: 678 Drop: 0
	Level seed: 2644005319599211621
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (56,88,87), Chunk: (at 8,5,7 in 3,5; contains blocks 48,0,80 to 63,255,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 643252645 game time, 541945775 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 99149 (now: false), thunder time: 22854 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.14.101-mtxserv-version1
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 500715416 bytes (477 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 22 total; -Xms2048M -Xmx4096M -XX:MaxMetaspaceSize=512M -XX:+UseFastAccessorMethods -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1HeapRegionSize=4M -XX:MaxGCPauseMillis=100 -XX:+ParallelRefProcEnabled -XX:ParallelGCThreads=4 -XX:ConcGCThreads=1 -XX:+DisableExplicitGC -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:InitiatingHeapOccupancyPercent=30 -XX:G1MixedGCLiveThresholdPercent=50 -XX:G1HeapWastePercent=2 -XX:G1ReservePercent=2 -XX:UseSSE=4 -XX:+UseNUMA
	IntCache: cache: 0, tcache: 1, allocated: 5, tallocated: 104
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 128 mods loaded, 128 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                    | Version                  | Source                                                   | Signature                                |
	|:------ |:--------------------- |:------------------------ |:-------------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft             | 1.12.2                   | minecraft.jar                                            | None                                     |
	| LCHIJA | mcp                   | 9.42                     | minecraft.jar                                            | None                                     |
	| LCHIJA | FML                   | 8.0.99.99                | minecraft_server.jar                                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                 | 14.23.5.2838             | minecraft_server.jar                                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | creativecoredummy     | 1.0.0                    | minecraft.jar                                            | None                                     |
	| LCHIJA | micdoodlecore         |                          | minecraft.jar                                            | None                                     |
	| LCHIJA | opencomputers|core    | 1.7.4.153                | minecraft.jar                                            | None                                     |
	| LCHIJA | activatedcarbon       | 1.2                      | ActivatedCarbon-1.12.2-1.2.jar                           | None                                     |
	| LCHIJA | animalnet             | 1.11                     | animalnet-1.11.jar                                       | None                                     |
	| LCHIJA | baubles               | 1.5.2                    | Baubles-1.12-1.5.2.jar                                   | None                                     |
	| LCHIJA | atum                  | 2.0.11                   | Atum-1.12.2-2.0.11.jar                                   | None                                     |
	| LCHIJA | backpack              | 3.0.2                    | backpack-3.0.2-1.12.2.jar                                | None                                     |
	| LCHIJA | baubleofundying       | 1.0.1                    | BaubleOfUndying-1.12-1.0.1.jar                           | None                                     |
	| LCHIJA | miscrails             | 1.0.0                    | Better-Railroads-1.0.0.jar                               | None                                     |
	| LCHIJA | betterunderground     | 1.1.2                    | Better-Underground-Mod-1.12.2.jar                        | None                                     |
	| LCHIJA | bibliocraft           | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar                        | None                                     |
	| LCHIJA | biomesoplenty         | 7.0.1.2439               | BiomesOPlenty-1.12.2-7.0.1.2439-universal.jar            | None                                     |
	| LCHIJA | birdsnests            | 2.0.0                    | BirdsNests1.12.2-2.0.0.jar                               | None                                     |
	| LCHIJA | bookshelf             | 2.3.569                  | Bookshelf-1.12.2-2.3.569.jar                             | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | buildcraftlib         | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                             | None                                     |
	| LCHIJA | buildcraftcore        | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                             | None                                     |
	| LCHIJA | buildcraftbuilders    | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                             | None                                     |
	| LCHIJA | buildcrafttransport   | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                             | None                                     |
	| LCHIJA | buildcraftsilicon     | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                             | None                                     |
	| LCHIJA | crafttweaker          | 4.1.14                   | CraftTweaker2-1.12-4.1.14.jar                            | None                                     |
	| LCHIJA | buildcraftcompat      | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                             | None                                     |
	| LCHIJA | buildcraftenergy      | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                             | None                                     |
	| LCHIJA | buildcraftfactory     | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                             | None                                     |
	| LCHIJA | buildcraftrobotics    | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                             | None                                     |
	| LCHIJA | carbonado             | 1.5.1                    | carbonado-1.5.1-mc1.12.x.jar                             | None                                     |
	| LCHIJA | cavern                | 2.2.0                    | Cavern_1.12.2-v2.2.0.jar                                 | b78e30ad27c82f3e348f76edf497058678207299 |
	| LCHIJA | caverntweaks          | 2.0                      | caverntweaks-1.12.2-2.0.jar                              | None                                     |
	| LCHIJA | champions             | 1.12.2-1.0.9             | champions-1.12.2-1.0.9.jar                               | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | jei                   | 4.15.0.281               | jei_1.12.2-4.15.0.281.jar                                | None                                     |
	| LCHIJA | charm                 | 1.12.2-1.2.2             | Charm-1.12.2-1.2.2.jar                                   | None                                     |
	| LCHIJA | codechickenlib        | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar            | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | coherentvillages      | v0.0.5.10                | coherent_villages-pre-release_v0.0.5.10.jar              | None                                     |
	| LCHIJA | crafttweakerjei       | 2.0.2                    | CraftTweaker2-1.12-4.1.14.jar                            | None                                     |
	| LCHIJA | creativecore          | 1.9.9                    | CreativeCore_v1.9.32_mc1.12.2.jar                        | None                                     |
	| LCHIJA | dailies               | 1.12.2-6                 | dailies-1.12.2-6.jar                                     | None                                     |
	| LCHIJA | disenchanter          | 1.6                      | disenchanter-[1.12]1.6.jar                               | None                                     |
	| LCHIJA | gottschcore           | 1.7.0                    | GottschCore-mc1.12.2-f14.23.5.2768-v1.7.0.jar            | None                                     |
	| LCHIJA | dungeons2             | 1.6.1                    | Dungeons2-mc1.12.2-f14.23.5.2768-v1.6.1.jar              | None                                     |
	| LCHIJA | endreborn             | 0.3.0                    | EndReborn+II+[0.3.0].jar                                 | None                                     |
	| LCHIJA | thaumcraft            | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                         | None                                     |
	| LCHIJA | twilightforest        | 3.8.689                  | twilightforest-1.12.2-3.8.689-universal.jar              | None                                     |
	| LCHIJA | immersiveengineering  | 0.12-89                  | ImmersiveEngineering-0.12-89.jar                         | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCHIJA | engineeredgolems      | 1.2                      | Engineered+Golems-1.2a.jar                               | None                                     |
	| LCHIJA | erebus                | 1.0.30                   | Erebus-1.0.30.jar                                        | None                                     |
	| LCHIJA | exoticbirds           | 1.0                      | Exotic+Birds+1.12.2-2.2.1.jar                            | None                                     |
	| LCHIJA | et                    | 1.2.0                    | ExpTranslation-1.12.2-1.2.0.jar                          | None                                     |
	| LCHIJA | extraalchemy          | 0.3.8.6.1-release        | extraalchemy-0.3.8.6.1-release.jar                       | None                                     |
	| LCHIJA | ic2                   | 2.8.168-ex112            | industrialcraft-2-2.8.168-ex112.jar                      | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | mantle                | 1.12-1.3.3.49            | Mantle-1.12-1.3.3.49.jar                                 | None                                     |
	| LCHIJA | galacticraftcore      | 4.0.2.217                | GalacticraftCore-1.12.2-4.0.2.217.jar                    | None                                     |
	| LCHIJA | galacticraftplanets   | 4.0.2.217                | Galacticraft-Planets-1.12.2-4.0.2.217.jar                | None                                     |
	| LCHIJA | mjrlegendslib         | 1.12.2-1.1.8             | MJRLegendsLib-1.12.2-1.1.8.jar                           | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHIJA | extraplanets          | 1.12.2-0.5.4             | ExtraPlanets-1.12.2-0.5.4.jar                            | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHIJA | familiarfauna         | 1.0.10                   | FamiliarFauna-1.12.2-1.0.10.jar                          | None                                     |
	| LCHIJA | faufil                | 1.0.2                    | Faucets+and+Filters-1.0.2.jar                            | None                                     |
	| LCHIJA | forgelin              | 1.8.3                    | Forgelin-1.8.3.jar                                       | None                                     |
	| LCHIJA | forgemultipartcbe     | 2.5.0.71                 | ForgeMultipart-1.12.2-2.5.0.71-universal.jar             | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | microblockcbe         | 2.5.0.71                 | ForgeMultipart-1.12.2-2.5.0.71-universal.jar             | None                                     |
	| LCHIJA | minecraftmultipartcbe | 2.5.0.71                 | ForgeMultipart-1.12.2-2.5.0.71-universal.jar             | None                                     |
	| LCHIJA | friendshipbracelet    | 1.1.2                    | FriendshipBracelet-1.1.2.jar                             | None                                     |
	| LCHIJA | giacomosfoundry       | 1.3.13                   | GiacomosFoundry-1.12.2-1.3.13.jar                        | None                                     |
	| LCHIJA | hearthstonemod        | 0.4.7                    | HearthstoneMod-1.12.2-0.4.7.jar                          | None                                     |
	| LCHIJA | waila                 | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                              | None                                     |
	| LCHIJA | llibrary              | 1.7.19                   | llibrary-1.7.19-1.12.2.jar                               | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | iceandfire            | 1.7.1                    | iceandfire-1.7.1-1.12.2.jar                              | None                                     |
	| LCHIJA | immersivepetroleum    | 1.1.9                    | immersivepetroleum-1.12.2-1.1.9.jar                      | None                                     |
	| LCHIJA | infraredstone         | 1.2.1                    | InfraRedstone-1.2.1.jar                                  | None                                     |
	| LCHIJA | inspirations          | 1.12.2-0.2.4             | Inspirations-1.12.2-0.2.4.jar                            | None                                     |
	| LCHIJA | instantunify          | 1.1.2                    | instantunify-1.12.2-1.1.2.jar                            | None                                     |
	| LCHIJA | inventorytweaks       | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                                 | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | ironchest             | 1.12.2-7.0.64.843        | ironchest-1.12.2-7.0.64.843.jar                          | None                                     |
	| LCHIJA | jaopca                | 1.12.2-2.2.8.103         | JAOPCA-1.12.2-2.2.8.103.jar                              | None                                     |
	| LCHIJA | oredictinit           | 1.12.2-2.2.1.71          | JAOPCA-1.12.2-2.2.8.103.jar                              | None                                     |
	| LCHIJA | shadowmc              | 3.8.0                    | ShadowMC-1.12-3.8.0.jar                                  | None                                     |
	| LCHIJA | leveluphp             | 1.12.2-1.3.0             | level-up-hp-1.12.2-1.3.0.jar                             | None                                     |
	| LCHIJA | lex                   | 1.0.8                    | LibEx-1.12.2-1.0.8.jar                                   | None                                     |
	| LCHIJA | magicclover           | 1.12-0.7.8               | magicclover-1.12-0.7.8.jar                               | None                                     |
	| LCHIJA | malisiscore           | 1.12.2-6.4.0             | malisiscore-1.12.2-6.4.0.jar                             | None                                     |
	| LCHIJA | malisisdoors          | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                            | None                                     |
	| LCHIJA | malisisswitches       | 1.12.2-5.1.0             | malisisswitches-1.12.2-5.1.0.jar                         | None                                     |
	| LCHIJA | megaloot              | 0.2.30                   | megaloot-1.12.2-0.2.30.jar                               | None                                     |
	| LCHIJA | mekanism              | 1.12.2-9.8.0.381         | Mekanism-1.12.2-9.8.0.381.jar                            | None                                     |
	| LCHIJA | mekanismgenerators    | 1.12.2-9.8.0.381         | MekanismGenerators-1.12.2-9.8.0.381.jar                  | None                                     |
	| LCHIJA | guilib                | $version                 | morepaintings-paintings-1.12.2-5.0.0.2.r2 2019.02.06.jar | None                                     |
	| LCHIJA | paintingselgui        | $version                 | morepaintings-paintings-1.12.2-5.0.0.2.r2 2019.02.06.jar | None                                     |
	| LCHIJA | morepaintings         | $version                 | morepaintings-paintings-1.12.2-5.0.0.2.r2 2019.02.06.jar | None                                     |
	| LCHIJA | morpheus              | 1.12.2-3.5.106           | Morpheus-1.12.2-3.5.106.jar                              | None                                     |
	| LCHIJA | mtlib                 | 3.0.6                    | MTLib-3.0.6.jar                                          | None                                     |
	| LCHIJA | mysticalwildlife      | 1.3.0                    | mysticalwildlife-1.12.2-1.3.0.jar                        | None                                     |
	| LCHIJA | nex                   | 2.0.8                    | NetherEx-1.12.2-2.0.8.jar                                | None                                     |
	| LCHIJA | opencomputers         | 1.7.4.153                | OpenComputers-MC1.12.2-1.7.4.153.jar                     | None                                     |
	| LCHIJA | patchouli             | 1.0-19                   | Patchouli-1.0-19.jar                                     | None                                     |
	| LCHIJA | jmilpol               | 1.6                      | PendantOfLife-1.6.jar                                    | None                                     |
	| LCHIJA | playerrevive          | 1.0                      | PlayerRevive_v1.2.22_mc1.12.2.jar                        | None                                     |
	| LCHIJA | potioncore            | 1.6_for_1.12.2           | PotionCore-1.6_for_1.12.2.jar                            | None                                     |
	| LCHIJA | qualitytools          | 1.0.6_for_1.12.2         | QualityTools-1.0.6_for_1.12.2.jar                        | None                                     |
	| LCHIJA | reactor_stuff         | 1.9                      | ReactorStuff-[1.12.2]-1.9.jar                            | None                                     |
	| LCHIJA | additionalstructures  | 2.2.2                    | Rex's-Additional-Structures-1.12.x-(v.2.2.2).jar         | None                                     |
	| LCHIJA | roguelike             | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar                       | None                                     |
	| LCHIJA | ruins                 | 17.2                     | Ruins-1.12.2_jun7.jar                                    | None                                     |
	| LCHIJA | shutters              | 1.12.2-1.0-pre           | shutters-1.12.2-1.0.jar                                  | None                                     |
	| LCHIJA | simplefluidtanks      | 1.12.2-1.7.1.1           | simplefluidtanks-1.12.2-1.7.1.1.jar                      | None                                     |
	| LCHIJA | spartanshields        | 1.5.4                    | SpartanShields-1.12.2-1.5.4.jar                          | None                                     |
	| LCHIJA | tickprofiler          | 1.12-0.0.7               | TickProfiler-1.12-0.0.7.jar                              | None                                     |
	| LCHIJA | toolbelt              | 1.7.1                    | ToolBelt-1.12.0-1.7.1.jar                                | None                                     |
	| LCHIJA | toroquest             | 1.12.2-5.3               | toroquest-1.12.2-5.3.jar                                 | None                                     |
	| LCHIJA | totemdefender         | 2.9                      | TotemDefender-1.12.2-2.9.jar                             | None                                     |
	| LCHIJA | treasure2             | 1.3.7                    | Treasure2-mc1.12.2-f14.23.5.2768-v1.3.7.jar              | None                                     |
	| LCHIJA | treechopper           | 1.2.4                    | TreeChopper-1.12.2-1.2.4.jar                             | None                                     |
	| LCHIJA | tropicraft            | 7.1.9.115                | tropicraft-MC1.12.2-7.1.9.115.jar                        | None                                     |
	| LCHIJA | tumbleweed            | 1.11-0.4.5               | tumbleweed-1.11-0.4.5.jar                                | None                                     |
	| LCHIJA | uppers                | 0.0.6                    | Uppers-0.0.6.jar                                         | None                                     |
	| LCHIJA | of                    | 0.13                     | Useful+Interior+-+0.13+[1.12.2].jar                      | None                                     |
	| LCHIJA | vc                    | 5.9.13                   | ViesCraft-1.12.2-5.9.13.jar                              | None                                     |
	| LCHIJA | wanionlib             | 1.12.2-2.0               | WanionLib-1.12.2-2.0.jar                                 | None                                     |
	| LCHIJA | wawla                 | 2.5.246                  | Wawla-1.12.2-2.5.246.jar                                 | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | waystones             | 4.0.67                   | Waystones_1.12.2-4.0.67.jar                              | None                                     |
	| LCHIJA | worldcontrol          | 1.0.31                   | WorldControl-1.0.31.jar                                  | None                                     |
	| LCHIJA | worleycaves           | 1.4.1                    | worleycaves-1.4.1.jar                                    | None                                     |
	| LCHIJA | wrcbe                 | 2.3.1                    | WR-CBE-1.12.2-2.3.1.30-universal.jar                     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | thebetweenlands       | 3.4.8                    | TheBetweenlands-3.4.8-server.jar                         | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| LCHIJA | unidict               | 1.12.2-2.9.2             | UniDict-1.12.2-2.9.2.jar                                 | None                                     |
	| LCHIJA | wrapup                | 1.12-1.1.3               | WrapUp-1.12-1.1.3.jar                                    | None                                     |

	Loaded coremods (and transformers): 
CreativePatchingLoader (CreativeCore_v1.9.32_mc1.12.2.jar)
  
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.8-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  
CharmLoadingPlugin (Charm-1.12.2-1.2.2.jar)
  svenhjol.charm.base.CharmClassTransformer
LibLoader (# LibLoader.jar)
  
TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
  li.cil.oc.common.asm.ClassTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
ForgelinPlugin (Forgelin-1.8.3.jar)
  
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
MekanismCoremod (Mekanism-1.12.2-9.8.0.381.jar)
  mekanism.coremod.KeybindingMigrationHelper
CoreMod (TickProfiler-1.12-0.0.7.jar)
  
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.217.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	Pulsar/inspirations loaded Pulses: 
		- InspirationsShared (Enabled/Forced)
		- InspirationsBuilding (Enabled/Not Forced)
		- InspirationsUtility (Enabled/Not Forced)
		- InspirationsTools (Enabled/Not Forced)
		- InspirationsRecipes (Enabled/Not Forced)
		- InspirationsTweaks (Enabled/Not Forced)
		- InspirationsShared (Enabled/Forced)
		- WailaPlugin (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [GCEntityPlayerMP['Phiphila'/2221, l='world', x=35.12, y=76.06, z=306.91]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft)

hi,
Je ne peux pas ouvrir le four à arc sans faire planter le serveur, je passe donc en mode 1 et le supprime, je m'en donne un nouveau depuis l'inventaire et je veux alors le mettre dans le jeu, je clique et... : depuis ce moment le serveur crache. J'ai besoin de recharger une sauvegarde

I can not open the arc oven without crashing the server, so I switch to mode 1 and delete it, I give it a new one from the inventory and then I want to put it in the game, I click and. ..: since then the server spits. I need to reload a backup

have a good day

**Comment by micdoodle8** [comment]
Hi, this is fixed in build 218 (you're using 217), please re-download the latest build from the site
