### ISSUE TITLE
Crash in BuildCraft Lib after 4.0.2.210

### ISSUE THREAD

**Issue by PromanSEW** [micdoodle8/Galacticraft#3743]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 4.0.2.218 (219 also crashes)

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP

Any Galacticraft add-ons installed? please list all
GalaxySpace 1.12.2-2.0.8

Please provide screenshots / crash report / log / full modlist as needed
https://gist.github.com/PromanSEW/2d1ed4e41e5c8f5b15275f78abedbb8d

If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft)
Yes

Issue at BuildCraft repo with discussion:
https://github.com/BuildCraft/BuildCraft/issues/4446

**Comment by micdoodle8** [comment]
This looks to me like a GalaxySpace issue, but I'll look closer as soon as I'm able

**Comment by PromanSEW** [comment]
@micdoodle8 I have updated only GC, not GalaxySpace. Game was not crashing on build 210

**Comment by Romsik788** [comment]
@PromanSEW GS no supported version GC 212 and up. Please use GC version 211

**Comment by micdoodle8** [comment]
Appears to be fixed in the upcoming build of GS 👍
