### ISSUE TITLE
prefab worldgen error 

### ISSUE THREAD

**Issue by AsimRamay** [micdoodle8/Galacticraft#3753]
Minecraft version: 1.12.2
Galacticraft version: 4.0.2.218

SMP

Add Ons:
Extra Planets 0.5.4
Galacticraft Planets 4.0.2.218

so im having this weird error , the server loads up fine , the world generates and then retogens some , after a while this error below happens, however if  delete data and region folder , world generates exactly the same but without all the modifications i made to the world (ovb) , also generates perfectly if i start a new world , however i don't really wanna lose all my progress
and i even tried using NBT to remove all galacticraft references in those data folders , and taking galacticraft mod out and it worked , but then adding it back in still gives this error, kinda confused as to why

the other thing is i could play just fine until this error outputs (found no way to turn it off), because server would works fine before this starts spamming it every ms and causing it to run slow as hell 

```
8:22:58 PM CONSOLE: [INFO] java.lang.Exception: Stack trace
8:22:58 PM CONSOLE: [INFO] at java.lang.Thread.dumpStack(Unknown Source)
8:22:58 PM CONSOLE: [INFO] at micdoodle8.mods.galacticraft.api.prefab.world.gen.BiomeAdaptive.func_180622_a(BiomeAdaptive.java:231)
8:22:58 PM CONSOLE: [INFO] at com.xcompwiz.mystcraft.world.ChunkProviderMyst.replaceBlocksForBiome(ChunkProviderMyst.java:69)
8:22:58 PM CONSOLE: [INFO] at com.xcompwiz.mystcraft.world.ChunkProviderMyst.func_185932_a(ChunkProviderMyst.java:92)
8:22:58 PM CONSOLE: [INFO] at net.minecraft.world.gen.ChunkProviderServer.redirect$generateChunk$zzh000(ChunkProviderServer.java:523)
8:22:58 PM CONSOLE: [INFO] at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143)
8:22:58 PM CONSOLE: [INFO] at com.xcompwiz.mystcraft.world.profiling.WorldProviderMystDummy.generateNextChunk(WorldProviderMystDummy.java:305)
8:22:58 PM CONSOLE: [INFO] at com.xcompwiz.mystcraft.world.profiling.InstabilityDataCalculator.stepChunkGeneration(InstabilityDataCalculator.java:376)
8:22:58 PM CONSOLE: [INFO] at com.xcompwiz.mystcraft.world.profiling.InstabilityDataCalculator.onServerTick(InstabilityDataCalculator.java:198)
8:22:58 PM CONSOLE: [INFO] at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2558_InstabilityDataCalculator_onServerTick_ServerTickEvent.invoke(.dynamic)
8:22:58 PM CONSOLE: [INFO] at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
8:22:58 PM CONSOLE: [INFO] at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
8:22:59 PM CONSOLE: [INFO] at micdoodle8.mods.galacticraft.api.prefab.world.gen.BiomeAdaptive.func_180624_a(BiomeAdaptive.java:217)
8:22:59 PM CONSOLE: [INFO] at com.xcompwiz.mystcraft.world.ChunkProviderMyst.func_185931_b(ChunkProviderMyst.java:145)
8:22:59 PM CONSOLE: [INFO] at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
8:22:59 PM CONSOLE: [INFO] at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999)
8:22:59 PM CONSOLE: [INFO] at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
8:22:59 PM CONSOLE: [INFO] at com.xcompwiz.mystcraft.world.profiling.WorldProviderMystDummy.generateNextChunk(WorldProviderMystDummy.java:305)
8:22:59 PM CONSOLE: [INFO] at com.xcompwiz.mystcraft.world.profiling.InstabilityDataCalculator.stepChunkGeneration(InstabilityDataCalculator.java:376)
8:22:59 PM CONSOLE: [INFO] at com.xcompwiz.mystcraft.world.profiling.InstabilityDataCalculator.onServerTick(InstabilityDataCalculator.java:198)
8:22:59 PM CONSOLE: [INFO] at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2558_InstabilityDataCalculator_onServerTick_ServerTickEvent.invoke(.dynamic)
8:22:59 PM CONSOLE: [INFO] at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
8:22:59 PM CONSOLE: [INFO] at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
8:22:59 PM CONSOLE: [INFO] at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
8:22:59 PM CONSOLE: [INFO] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
8:22:59 PM CONSOLE: [INFO] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)

```

**Comment by TheQuadShot** [comment]
What happens if you disable Myst? Can you try it? Thanks

**Comment by AsimRamay** [comment]
removing either Mystcraft or Galacticraft works , this doesnt make much sense to me tho , since i added multiple mods while both Mystcraft & Glacticraft were present throughout including biome mods yet this only occurred recently - maybe some type of incompatibility which is unfortunate , but i guess i can live without one of em , ill see if deleting mystcraft data and regs fixes this

**Comment by MJRLegends** [comment]
Could be biome id conflicts or some related thats the issue

**Comment by AsimRamay** [comment]
the only thing i find weird about it being a biome id conflict is that while exactly the same mods are present , same world seed , if i juts delete region data (which are chunks ive modified e.g. to make my base) the world will load in fine , everything will look similar including the village just my base will be gone 
and this error does not occur at all then, from my understanding changing region data does not change the biomes or how their ids are assigned

**Comment by micdoodle8** [comment]
Is it generating the overworld when this is happening?

**Comment by AsimRamay** [comment]
Overworld , dimensions seem to be fine, also deleting dimension data does nothing , but deleting region data + over world data folder items fixes the problem

**Comment by radfast** [comment]
`BiomeAdaptive` can be generated only on Galacticraft worlds, not vanilla dimensions and not other mods' worlds like Mystcraft.   Unless there is a biome ID conflict.

The whole purpose of BiomeAdaptive is to reduce the number of Biome IDs which Galacticraft needs to a small number, normally less than 5, to reduce the chance of biome ID conflicts.

In this case this is **deliberate stacktrace logging** in [our code](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/api/prefab/world/gen/BiomeAdaptive.java#L231) to show there is a biome ID conflict.  It is **not** a crash as such - it only looks like a crash because of the deliberate stacktrace logging.

We can easily change the code to produce this stacktrace only once and then stop spamming it, to fix the spam / slowness problem.  But this will not fix the underlying problem, i.e. the biome ID conflict.

The server owner can maybe fix the biome ID conflict by looking at biome IDs in Mystcraft and the config `biomeIDBase` in Galacticraft.

**Comment by radfast** [comment]
In next build we have improved logging of this - it should tell you which ID and which other Biome is conflicting, and no more spam.

Thanks again for reporting.
