### ISSUE TITLE
no such method error

### ISSUE THREAD

**Issue by forhillcat** [micdoodle8/Galacticraft#3755]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 1.12.2

Single player (SSP)

Any Galacticraft add-ons installed? galaxy space, galacticraft tweaker
[crash-2019-08-06_15.09.16-client.txt](https://github.com/micdoodle8/Galacticraft/files/3471088/crash-2019-08-06_15.09.16-client.txt)

Please provide screenshots / crash report / log / full modlist as needed

If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft)

**Comment by micdoodle8** [comment]
Update GC, GalaxySpace is crashing because you're using an older version of GC.
