### ISSUE TITLE
Crash on Joining Local World(LAN)

### ISSUE THREAD

**Issue by KenyMylankca** [micdoodle8/Galacticraft#3756]
https://paste.dimdev.org/madotadegi.mccrash -> with GC builds .226
https://paste.dimdev.org/zazagogiyo.mccrash -> with GC builds .224

Minecraft version: 1.12.2

Any Galacticraft add-ons installed? only galaxy space (+asmodeus core)

**Comment by MJRLegends** [comment]
How have you come to the conclusion its Galacticraft causing the crashing?

**Comment by KenyMylankca** [comment]
cus it says entity being ticked `Entity Type: null (micdoodle8.mods.galacticraft.core.entities.player.GCEntityOtherPlayerMP)`

**Comment by micdoodle8** [comment]
The vanilla entity is replaced by GC's entity. That doesn't mean it's GC's fault, it just means the player is a Galacticraft player.

I need a stack trace (it's in the full log). It looks like this: 
![Stack Trace Example](https://blogs.jetbrains.com/idea/wp-content/uploads/2010/03/screen-shot-2010-03-17-at-100031-am.png)

**Comment by KenyMylankca** [comment]
uhm i will provide more crash reports about this if i have any more today (i will test again)
and please also see **[this](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap/issues/65)**, maybe it's about the same issue. just trying to help, i don't know...

**Comment by micdoodle8** [comment]
That's what I'm looking for. 

I do appreciate the help, just dealing with a lot of github issues at once. Thank you for the report.

**Comment by KenyMylankca** [comment]
hey uhm, i did so many (i think enough) tests yesterday, and it didn't crash anytime again. i think u can close this issue. the only bug in the modpack was tile entity blocks' dealing damage is instantly fast and i don't think it's about Galacticraft xD (for example, when u touch the campfire from Tough As Nails(it doesn't matter what mod!) it should harm u 1 damage about per second, but it deals that 1 damage in every tick.) so i'm gonna inspect what causes it...
thanks for the help-back tho!

**Comment by KenyMylankca** [comment]
and yes, Mitchell; the bug i talked about is not about Galacticraft. Thanks again! and good luck on development on your great mods.
