### ISSUE TITLE
World gen not working

### ISSUE THREAD

**Issue by SpGilbert** [micdoodle8/Galacticraft#3759]
Minecraft version:1.12.2
Galacticraft version: 226
Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
single player
Please provide screenshots / crash report / log / full modlist as needed
https://paste.dimdev.org/hebekadoso.mccrash this crash report does not have the problem only the mod names.
problem: 
Prevents all world gen with project vibrant journeys no crash reports only.log file.
.log file:
https://paste.ubuntu.com/p/cHtygpF4Qz/
It used to work but it does not work anymore.

**Comment by TheQuadShot** [comment]
From the log file:
`[20:48:39] [Server thread/ERROR] [Galacticraft]: Error in another mod's worldgen.  This is *NOT* a Galacticraft bug, report it to the other mod please.`

**Comment by micdoodle8** [comment]
Looks to be a Vibrant Journeys world gen issue based on the stack trace.
