### ISSUE TITLE
Can't launch to the moon from space station even with tier 1 rocket?

### ISSUE THREAD

**Issue by Willbound** [micdoodle8/Galacticraft#3760]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version:4.0.2.226

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? SMP

Any Galacticraft add-ons installed? please list all
Baubles-1.12-1.5.2
BuildCraft-Mod-1.12.2
CodeChickenLib-1.12.2
GalacticraftCore-1.12.2-4.0.2.226
Galacticraft-Planets-1.12.2-4.0.2.226
jei_1.12.2-4.15.0.268
MicdoodleCore-1.12.2-4.0.2.226
OreExcavation-1.4.140
ProjectE-1.12.2-PE1.4.1
RedstoneFlux-1.12.2
spongeforge-1.12.2-2705-7.1.0-BETA-3136

Please provide screenshots / crash report / log / full modlist as needed
https://ibb.co/bsLpT4N

If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft)

**Comment by TheQuadShot** [comment]
Do you have these items in your player inventory when you try?
16 Aluminum Ingots
32 Tin Ingots
24 Iron Ingots
1 Advanced Wafer.
https://wiki.micdoodle8.com/wiki/Overworld_Space_Station

**Comment by Willbound** [comment]
> Do you have these items in your player inventory when you try?
> 16 Aluminum Ingots
> 32 Tin Ingots
> 24 Iron Ingots
> 1 Advanced Wafer.
> https://wiki.micdoodle8.com/wiki/Overworld_Space_Station

Yes, I've already built the station, but whenever I take off again I can't go to the moon

**Comment by TheQuadShot** [comment]
Oh, sorry I completely misread that, Can you launch from the overworld to the moon?

**Comment by Willbound** [comment]
no that didn't work either

**Comment by TheQuadShot** [comment]
Could you please post a link to your "latest.log" file? You can post on pastebin.com or similar? Preferably from an attempt to launch there, Thanks

**Comment by Willbound** [comment]
https://pastebin.com/GSfqrJ0A

**Comment by micdoodle8** [comment]
So when you click on the moon, the launch button is green, but clicking does nothing? Or is the button red? Or are you getting a loading screen that doesn't complete?

**Comment by Willbound** [comment]
I was able to fix it by installing simple dimensions which somehow caused the boot up console log to include the assigning of dimension IDs to the planets/moon, (idk why it wasn't assigning them IDs in the first place), I still couldn't launch to the moon but after teleporting myself there (w/ simple dimensions) I was able to finally hit the launch button,  same story with Mars as well

**Comment by Willbound** [comment]
Also I'm having another problem where the treasure chests are not spawning after defeating a boss

**Comment by micdoodle8** [comment]
Okay, I'm going to close this. If anyone's having the same issue please comment here or create a new issue.

Please create a new issue with the dungeon gen information (screenshots, logs, etc)

**Comment by bluelightning32** [comment]
I created a new bug for the general spongeforge+space stations problem:
https://github.com/micdoodle8/Galacticraft/issues/3775
