### ISSUE TITLE
Wrong version

### ISSUE THREAD

**Issue by BlesseNtumble** [micdoodle8/Galacticraft#3762]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: ``1.12.2``
Galacticraft version: ``227 build``

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
``SSP``
Any Galacticraft add-ons installed? please list all

Please provide screenshots / crash report / log / full modlist as needed

![image](https://user-images.githubusercontent.com/8407547/62820228-21ed4180-bb9c-11e9-9a5c-dc13981ce3c4.png)

**Comment by micdoodle8** [comment]
Should be fixed as of 229, having issues with a script in the jenkins workspace

**Comment by BlesseNtumble** [comment]
![image](https://user-images.githubusercontent.com/8407547/62856397-c653bd00-bd2f-11e9-8aa3-e8fe22a92609.png)
229 DEV build

**Comment by micdoodle8** [comment]
Should be fixed in 230 dev, thanks again
