### ISSUE TITLE
[DEV] Broken NASA recipes.

### ISSUE THREAD

**Issue by BlesseNtumble** [micdoodle8/Galacticraft#3763]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: ``1.12.2``
Galacticraft version: ``229 DEV build``

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? 
``SSP``

Any Galacticraft add-ons installed? please list all

Please provide screenshots / crash report / log / full modlist as needed
After installing the GC build, the recipes at the NASA workbench broke.
![image](https://user-images.githubusercontent.com/8407547/62861462-8d6f1480-bd3e-11e9-81ec-cb2815ce849f.png)

Recipes are successfully registered.
![image](https://user-images.githubusercontent.com/8407547/62861601-fce50400-bd3e-11e9-8809-3510446da7be.png)
registerRecipes() called in RegistryEvent.Register<IRecipe> event.

IInventoy:
![image](https://user-images.githubusercontent.com/8407547/62861687-39186480-bd3f-11e9-889b-c512f225f818.png)

In container
```
 @Override
    public void onCraftMatrixChanged(IInventory par1IInventory)
    {       
    	this.craftResult.setInventorySlotContents(0, GSUtils.findMatchingNASARecipe(GSRecipeUtil.getFinsRecipes(), this.craftMatrix));
    }
```
```
public static ItemStack findMatchingNASARecipe(List<INasaWorkbenchRecipe> recipes, IInventory craftMatrix)
    {
        for (INasaWorkbenchRecipe recipe : recipes)
        {
            if (recipe.matches(craftMatrix))
            {
                return recipe.getRecipeOutput();
            }
        }

        return ItemStack.EMPTY;
    }
```

**Comment by BlesseNtumble** [comment]
For fix need add Container#onCraftMatrixChanged(this);
![image](https://user-images.githubusercontent.com/8407547/62867426-31ac8780-bd4e-11e9-9247-a19da646185d.png)

And please, replace ``private final Container eventHandler`` on `` protecter final Container eventHandler``

**Comment by micdoodle8** [comment]
Thanks for the detailed report :)
