### ISSUE TITLE
Compat Issue with Cubic Chunks - BiomeAdaptive

### ISSUE THREAD

**Issue by border999** [micdoodle8/Galacticraft#3764]
Minecraft version: 1.12.2
Galacticraft version: 1.12.2-4.0.2.231
Single player (SSP)
Any Galacticraft add-ons installed? 
ZollernGalaxy-1.12.2-v2.0.1
[crash-2019-08-14_15.49.21-client.txt](https://github.com/micdoodle8/Galacticraft/files/3504042/crash-2019-08-14_15.49.21-client.txt)
https://gist.github.com/border999/17ba0d43d7f72df45bec511829f4d179

**Comment by radfast** [comment]
Galacticraft is not intended to be compatible with CubicChunks.

Galacticraft depends fundamentally on the player height, for example above height y=256 is a height only rockets can reach, and above height y=1500 (approximately) the rocket will leave the atmosphere and enter orbit.

There is no way to make those systems compatible with Cubic Chunks, and therefore we have not attempted to code other more minor parts of the mod for Cubic Chunks compatibility.

Is it possible for you to play without Cubic Chunks?

**Comment by border999** [comment]
yes, I was simply curious if you could reconcile the issue.

**Comment by Barteks2x** [comment]
This honestly looks like some issue with mixin or related that makes the AccessTransformer not apply correctly. It has nothing to do with cubic chunks itself. Galscricraft is known to run and more or less work with cubic chunks already. It's just not very stable, and there are some known issues.

**Comment by Barteks2x** [comment]
I found the issue.
Starting with recent versions, I have the following mixin:
```java
@Mixin(Biome.class)
public abstract class MixinBiomeTemperatureConfig {

    @Shadow @Final protected static NoiseGeneratorPerlin TEMPERATURE_NOISE;

    @Shadow public abstract float getDefaultTemperature();

    /**
     * @author Barteks2x
     * @reason Configure how it changes with height
     */
    @Overwrite
    public final float getTemperature(BlockPos pos) {
        if (pos.getY() > CubicChunksConfig.biomeTemperatureCenterY) {
            float noise = (float) (TEMPERATURE_NOISE.getValue((double) ((float) pos.getX() / 8.0F), (double) ((float) pos.getZ() / 8.0F)) * 4.0D);
            int y = Math.min(pos.getY(), CubicChunksConfig.biomeTemperatureScaleMaxY);
            return this.getDefaultTemperature() +
                (noise + y - CubicChunksConfig.biomeTemperatureCenterY) * CubicChunksConfig.biomeTemperatureHeightFactor;
        } else {
            return this.getDefaultTemperature();
        }
    }
}
```

MicdoodleCore has access transformer that makes this method non-final, but mixin completely overwrites it, **including access modifiers**. And mixins are applied afte rAccessTransformers, so the access modifier ends up being final.

**Comment by border999** [comment]
@Barteks2x I still choose CC

**Comment by radfast** [comment]
> I found the issue.
> Starting with recent versions, I have the following mixin:
> 
> ```java
> @Mixin(Biome.class)
> public abstract class MixinBiomeTemperatureConfig {
> 
>     @Shadow @Final protected static NoiseGeneratorPerlin TEMPERATURE_NOISE;
> 
>     @Shadow public abstract float getDefaultTemperature();
> 
>     /**
>      * @author Barteks2x
>      * @reason Configure how it changes with height
>      */
>     @Overwrite
>     public final float getTemperature(BlockPos pos) {
>         if (pos.getY() > CubicChunksConfig.biomeTemperatureCenterY) {
>             float noise = (float) (TEMPERATURE_NOISE.getValue((double) ((float) pos.getX() / 8.0F), (double) ((float) pos.getZ() / 8.0F)) * 4.0D);
>             int y = Math.min(pos.getY(), CubicChunksConfig.biomeTemperatureScaleMaxY);
>             return this.getDefaultTemperature() +
>                 (noise + y - CubicChunksConfig.biomeTemperatureCenterY) * CubicChunksConfig.biomeTemperatureHeightFactor;
>         } else {
>             return this.getDefaultTemperature();
>         }
>     }
> }
> ```
> 
> MicdoodleCore has access transformer that makes this method non-final, but mixin completely overwrites it, **including access modifiers**. And mixins are applied afte rAccessTransformers, so the access modifier ends up being final.

@Barteks2x thank you for looking in, and thank you for identifying this - awesome.  I will reopen and we will see what we can do here.

**Comment by radfast** [comment]
I don't see any easy fix to this from our side, without re-coding the whole of MicdoodleCore to use mixins throughout instead of access transformers.

@Barteks2x a quick and dirty solution could be for you not to set that method as `final` in your mixin?  Presumably you don't need it to be final, and no other mod is going to have an issue if this method is **not** final.

**Comment by SupremeMarshal** [comment]
I will need a large number of biomes to create the preset for generating the interior of every planets.

**Comment by Barteks2x** [comment]
I am already doing that so this shouldn't be an issue anymore. Galacticraft always did something that cubic chunks broke in some way as far as I can remember but I haven't tested it in a long time.

**Comment by border999** [comment]
as always. I can test if you wish. @Barteks2x knows my discord, anytime the addon or beta edition of CC is available, I'll test.

**Comment by Barteks2x** [comment]
It's been fixed for a few months now. Even latest version on curse should have it fixed.

**Comment by catflight679** [comment]
Makes sense as to why my world didn't work at y=2118 (with peaks that come slightly higher). A bit higher than the default height limit.
