### ISSUE TITLE
Charging village cause Crash

### ISSUE THREAD

**Issue by nortak264** [micdoodle8/Galacticraft#3769]
Minecraft version: 1.12.2
Galacticraft version: 4.0.2.231

Single player (SSP)

I started a world with differents mods. 

During exploration, i got a crash when I charged new chunks.

There is the report crash on attach file :

[crash-2019-08-23_00.33.28-server.txt](https://github.com/micdoodle8/Galacticraft/files/3532193/crash-2019-08-23_00.33.28-server.txt)

Pls someone help me. I don't want to lose my world.

**Comment by TheQuadShot** [comment]
This crash is caused by extrautils2 not GC.
`java.lang.NoSuchFieldError: field_185198_a
at com.rwtema.extrautils2.villagers.EmeraldForPotions.getCraftLevels(EmeraldForPotions.java:70)`

**Comment by nortak264** [comment]
Oh...

Thx for the response.
