### ISSUE TITLE
Exception spamming with Valkyrienwarfare

### ISSUE THREAD

**Issue by Eldewrath** [micdoodle8/Galacticraft#3770]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

With valkyrienwarefare there is an exception spamming, which affects the fps  significantly.

Minecraft version: 1.12.2
Galacticraft version: GalacticraftCore-1.12.2-4.0.2.211

Occurs in Mulitplayer

Any Galacticraft add-ons installed? please list all
- GalacticraftCore-1.12.2-4.0.2.211
- Galacticraft-Planets-1.12.2-4.0.2.211
- MicdoodleCore-1.12.2-4.0.2.211

Valkyrienwarfare: 
- ValkyrienWarfare+0.9_final-universal

[Exception.txt](https://github.com/micdoodle8/Galacticraft/files/3536193/Exception.txt)

**Comment by Eldewrath** [comment]
I think its an bug in valkyrien warfare, since it does not occur in older versions

**Comment by micdoodle8** [comment]
This actually is a GC issue, are you using a plain Minecraft Forge server, or something like Kettle?

**Comment by Eldewrath** [comment]
Using plain Forge server: forge-1.12.2-14.23.5.2768-universal.jar
