### ISSUE TITLE
Creating a space station with SpongeForge breaks other dimensions

### ISSUE THREAD

**Issue by bluelightning32** [micdoodle8/Galacticraft#3775]
Minecraft version: 1.12.2
Galacticraft version: 1.12.2-4.0.2.233
Forge version: forge-1.12.2-14.23.5.2838-universal.jar
SpongeForge version: spongeforge-1.12.2-2838-7.1.7-RC3903.jar

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
* SMP

Any Galacticraft add-ons installed? please list all
```
> /sponge plugins 
[12:32:42] [Server thread/INFO] [minecraft/DedicatedServer]: Plugins (4): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge
> /sponge mods
[12:32:44] [Server thread/INFO] [minecraft/DedicatedServer]: Mods (10): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, Galacticraft Core, Galacticraft Planets, Micdoodle8 Core, SpongeForge
```

There have numerous bug reports about the space station breaking things. I run a DD&SS server, and every couple of months it breaks when someone builds a space station. The first sign of things getting broken is when some other dimension gets labelled as a space station:
```
> /forge tps
[12:35:41] [Server thread/INFO] [minecraft/DedicatedServer]: Dim  0 (Space Station) : Mean tick time: 2.208 ms. Mean TPS: 20.000
[12:35:41] [Server thread/INFO] [minecraft/DedicatedServer]: Dim -1 (the_nether) : Mean tick time: 0.086 ms. Mean TPS: 20.000
[12:35:41] [Server thread/INFO] [minecraft/DedicatedServer]: Dim  1 (the_end) : Mean tick time: 0.057 ms. Mean TPS: 20.000
[12:35:41] [Server thread/INFO] [minecraft/DedicatedServer]: Dim  2 (Space Station) : Mean tick time: 1.323 ms. Mean TPS: 20.000
[12:35:41] [Server thread/INFO] [minecraft/DedicatedServer]: Overall : Mean tick time: 4.151 ms. Mean TPS: 20.000
```

Other mods have been blamed (especially extra planets). So I decided to make the simplest possible reproduction of the issue.
1. Install forge.
2. Add spongeforge to the mods folder.
3. Add galacticraft.
4. Start the server.
5. Connect to the server with your client.
6. Op yourself.
7. Go into creative mode.
8. Run `/dimensiontp` to bring up the planet screen.
9. Click on the overworld.
10. Click on create space station.
11. Disconnect.
12. Restart the server.
13. Run forge tps and see that the overworld now has the space station type:
```
> /forge tps
[12:38:14] [Server thread/INFO] [minecraft/DedicatedServer]: Dim  0 (Space Station) : Mean tick time: 0.218 ms. Mean TPS: 20.000
[12:38:14] [Server thread/INFO] [minecraft/DedicatedServer]: Dim -1 (the_nether) : Mean tick time: 0.016 ms. Mean TPS: 20.000
[12:38:14] [Server thread/INFO] [minecraft/DedicatedServer]: Dim  1 (the_end) : Mean tick time: 0.012 ms. Mean TPS: 20.000
[12:38:14] [Server thread/INFO] [minecraft/DedicatedServer]: Dim  2 (Space Station) : Mean tick time: 0.386 ms. Mean TPS: 20.000
[12:38:14] [Server thread/INFO] [minecraft/DedicatedServer]: Overall : Mean tick time: 0.862 ms. Mean TPS: 20.000
```

If you have other mods installed that add more dimensions, galacticraft will pick other dimensions to corrupt. Sometimes it will corrupt the nether or end instead. Most things on the corrupt dimension still work, but eventually you'll find problems like rockets won't work any more, or entering the dimension crashes the server.

**Comment by bluelightning32** [comment]
Debug log for the server after restart (when it shows the wrong dimension type):
https://gist.github.com/bluelightning32/4dc6c1087dedfe9dc3765c954a9893f1

**Comment by MJRLegends** [comment]
Yea this is very known and seems to be a spongeforge issue. Despite reporting and talking to them about it no progress was made with fixing it

**Comment by bluelightning32** [comment]
All the existing bug reports I found on this were messy. Which one do you think best captures the conversation with the Sponge developers?

**Comment by TheAgentRAINBOW** [comment]
Thank you for bringing this bug attention again, my ticket on it never ended in a fix being found.

**Comment by MJRLegends** [comment]
https://github.com/SpongePowered/SpongeForge/issues/1429

**Comment by bluelightning32** [comment]
To me it looks like the action items from SpongeForge#1429 weren't executed on the Galacticraft side.

The second to last comment in SpongeForge#1429 was this from phit,
> It's already way too long for anyone to remotely grasp what is still relevant, make a clean new issue with all the relevant info to reproduce this. It will make everyones job way easier when it comes to getting into fixing this. Feel free to reference this issue in there.

MJRLegends replied with:
> @phit No problem i will do, i wasn't clear over
> >make a new issue, that log is completely different from what was reported here

> but now you have explained it in details i totally agree thank you for your messages

The SpongeForge people also asked for a repro in 1.12.

**Comment by bluelightning32** [comment]
I've tracked it down a line where Galacticraft is using Java reflection to incorrectly edit the dimension id map inside of SpongeForge.

I built Galacticraft with this diff applied:
```
diff --git a/src/main/java/micdoodle8/mods/galacticraft/core/util/WorldUtil.java b/src/main/java/micdoodle8/mods/galacticraft/core/util/WorldUtil.java
index f18e0e7f8..8de6150a1 100644
--- a/src/main/java/micdoodle8/mods/galacticraft/core/util/WorldUtil.java
+++ b/src/main/java/micdoodle8/mods/galacticraft/core/util/WorldUtil.java
@@ -503,6 +503,7 @@ public class WorldUtil
                                     Int2ObjectMap<DimensionType> result = (Int2ObjectMap<DimensionType>) dtDI.get(null);
                                     if (result != null)
                                     {
+                                        GCLog.info("Overriding dimensionid " + id + " to " + providerID);
                                         result.put(id, WorldUtil.getDimensionTypeById(providerID));
                                         GCLog.info("Re-registered dimension type " + providerID);
                                     }
```

And I got this log output:
```
[14:58:58] [Server thread/INFO] [Galacticraft]: Overriding dimensionid 0 to -26
[14:58:58] [Server thread/INFO] [Galacticraft]: Re-registered dimension type -26
```

**Comment by micdoodle8** [comment]
I'm thoroughly confused, I followed your steps to recreate the problem exactly and I'm not getting the issue.

Upon restart:
`[19:34:23] [Server thread/INFO] [minecraft/DedicatedServer]: Dim  0 (overworld) : Mean tick time: 3.065 ms. Mean TPS: 20.000
[19:34:23] [Server thread/INFO] [minecraft/DedicatedServer]: Dim -1 (the_nether) : Mean tick time: 0.063 ms. Mean TPS: 20.000
[19:34:23] [Server thread/INFO] [minecraft/DedicatedServer]: Dim  1 (the_end) : Mean tick time: 0.038 ms. Mean TPS: 20.000
[19:34:23] [Server thread/INFO] [minecraft/DedicatedServer]: Dim  2 (Space Station) : Mean tick time: 0.119 ms. Mean TPS: 20.000
[19:34:23] [Server thread/INFO] [minecraft/DedicatedServer]: Overall : Mean tick time: 3.446 ms. Mean TPS: 20.000`

`> sponge plugins
[19:37:32] [Server thread/INFO] [minecraft/DedicatedServer]: Plugins (4): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge
> sponge mods
[19:37:38] [Server thread/INFO] [minecraft/DedicatedServer]: Mods (10): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, Galacticraft Core, Galacticraft Planets, Micdoodle8 Core, SpongeForge`

Are you using an edited config file?

**Comment by bluelightning32** [comment]
I'm using the default config files.

I did notice that if the space station is created first, then SpongeForge is added, it takes 2 restarts for the problem to start.

The default sponge config on my computer is not telling the space station to load on startup:
```
[minecraft@mihoshi server]$ cat config/sponge/worlds/galacticraftcore/space_station/DIM_SPACESTATION2/world.conf
# 1.0
# 
# # If you need help with the configuration or have any questions related to Sponge,
# # join us at the IRC or drop by our forums and leave a post.
# 
# # IRC: #sponge @ irc.esper.net ( https://webchat.esper.net/?channel=sponge )
# # Forums: https://forums.spongepowered.org/
# 


```

**Comment by bluelightning32** [comment]
Here's a tarball of my server after the reproduction:
https://drive.google.com/file/d/15ujYqODlC3d2ym9UFe8PrxYS_ZXQM8rp/view?usp=sharing

**Comment by micdoodle8** [comment]
Ah okay, restarting the server again did get the overworld overridden

**Comment by radfast** [comment]
> I've tracked it down to a line where Galacticraft is using Java reflection to incorrectly edit the dimension id map inside of SpongeForge.
> 
> I built Galacticraft with this diff applied:
> 
> ```
> diff --git a/src/main/java/micdoodle8/mods/galacticraft/core/util/WorldUtil.java b/src/main/java/micdoodle8/mods/galacticraft/core/util/WorldUtil.java
> index f18e0e7f8..8de6150a1 100644
> --- a/src/main/java/micdoodle8/mods/galacticraft/core/util/WorldUtil.java
> +++ b/src/main/java/micdoodle8/mods/galacticraft/core/util/WorldUtil.java
> @@ -503,6 +503,7 @@ public class WorldUtil
>                                      Class sponge = Class.forName("org.spongepowered.common.world.WorldManager");
>                                      Field dtDI = sponge.getDeclaredField("dimensionTypeByDimensionId");
>                                      dtDI.setAccessible(true);
>                                      Int2ObjectMap<DimensionType> result = (Int2ObjectMap<DimensionType>) dtDI.get(null);
>                                      if (result != null)
>                                      {
> +                                        GCLog.info("Overriding dimensionid " + id + " to " + providerID);
>                                          result.put(id, WorldUtil.getDimensionTypeById(providerID));
>                                          GCLog.info("Re-registered dimension type " + providerID);
>                                      }
> ```
> 
> And I got this log output:
> 
> ```
> [14:58:58] [Server thread/INFO] [Galacticraft]: Overriding dimensionid 0 to -26
> [14:58:58] [Server thread/INFO] [Galacticraft]: Re-registered dimension type -26
> ```

The issue here appears to be that the `id` is 0.  That should be a space station dimension id like +3, 
 I'm looking at this now.

**Comment by MJRLegends** [comment]
Wonder if this will fix not just space stations but the planets turning in to the nether too. Looking at the code it looks like it would

**Comment by radfast** [comment]
Yes, I think it **may** fix all those issues which we couldn't find a solution for before.  @MJRLegends if you're able to test this your side before we make a general release, that could be awesome?

Sorry about the long length of time the dimensions have been an issue with Sponge.  Sometimes taking a break and looking at it with fresh eyes helps :)

**Comment by radfast** [comment]
@bluelightning32 this **may** be fixed by my code commit, though this is not yet in a release build.  I think @micdoodle8 will want to test this first, and if it looks OK then we can release it.
