### ISSUE TITLE
[1.12.2] [Astroblock] {Venus} the bounds of the randomizer are negative

### ISSUE THREAD

**Issue by Enderdraak** [micdoodle8/Galacticraft#3777]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 4.0.2.210
Astroblock version: 1.1.31

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SMP.

Any Galacticraft add-ons installed? please list all
The only mod I can think of in the astroblock modpack is "Extra Planets".

Please provide screenshots / crash report / log / full modlist as needed
Crash log 1: https://pastebin.com/LrJUMVkc
Crash log 2: https://pastebin.com/H1sFaiyr
Crash log 3: https://pastebin.com/ihvA3cZQ
Crash log 4: https://pastebin.com/6VDaQEA9

If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft)
Not of use

Something seems to go wrong at the randomizer, but on the second line galacty craft is mentiond. As far as I can tell this only happends on venus and it happends about every 2 min. I only have reached Tier 3 Rockets so I would not know if it happends on any other planet, moons or somewhere in space.

**Comment by radfast** [comment]
Thank you for reporting, and thank you for a very clear report.  This is now fixed in the next Galacticraft build 4.0.2.236.

Please ask the Astroblock modpack creator to update Galacticraft to 236.  That's a good idea anyhow, there are other important recent bugfixes, and a new block: the **Laser Turret**.

**Comment by knoxhack** [comment]
I'll hopefully get an update out this coming weekend :) thanks for the fix
