### ISSUE TITLE
Server Crashed after enter the teleport pad

### ISSUE THREAD

**Issue by StuffyfunRyan** [micdoodle8/Galacticraft#3778]
Server Crashed after enter the teleport pad

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  wings (wings-1.1.5-1.12.2.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2 (1).jar)
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  TickrateChanger (TickrateChanger-Mod-1.12.2.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 8/30/19 12:58 PM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at net.minecraft.inventory.ItemStackHelper.func_191281_a(SourceFile:34)
	at net.minecraft.inventory.ItemStackHelper.func_191282_a(SourceFile:29)
	at micdoodle8.mods.galacticraft.core.tile.TileEntityInventory.func_189515_b(TileEntityInventory.java:77)
	at micdoodle8.mods.galacticraft.core.energy.tile.EnergyStorageTile.func_189515_b(EnergyStorageTile.java:41)
	at micdoodle8.mods.galacticraft.core.energy.tile.TileBaseUniversalElectrical.func_189515_b(TileBaseUniversalElectrical.java:184)
	at micdoodle8.mods.galacticraft.core.energy.tile.TileBaseElectricBlock.func_189515_b(TileBaseElectricBlock.java:153)
	at micdoodle8.mods.galacticraft.planets.asteroids.tile.TileEntityTelepadFake.func_189515_b(TileEntityTelepadFake.java:138)
	at micdoodle8.mods.galacticraft.core.energy.tile.TileBaseElectricBlock.func_189517_E_(TileBaseElectricBlock.java:162)
	at net.minecraft.network.play.server.SPacketChunkData.<init>(SourceFile:52)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187272_b(PlayerChunkMapEntry.java:157)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:165)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.inventory.ItemStackHelper.func_191281_a(SourceFile:34)
	at net.minecraft.inventory.ItemStackHelper.func_191282_a(SourceFile:29)
	at micdoodle8.mods.galacticraft.core.tile.TileEntityInventory.func_189515_b(TileEntityInventory.java:77)
	at micdoodle8.mods.galacticraft.core.energy.tile.EnergyStorageTile.func_189515_b(EnergyStorageTile.java:41)
	at micdoodle8.mods.galacticraft.core.energy.tile.TileBaseUniversalElectrical.func_189515_b(TileBaseUniversalElectrical.java:184)
	at micdoodle8.mods.galacticraft.core.energy.tile.TileBaseElectricBlock.func_189515_b(TileBaseElectricBlock.java:153)
	at micdoodle8.mods.galacticraft.planets.asteroids.tile.TileEntityTelepadFake.func_189515_b(TileEntityTelepadFake.java:138)
	at micdoodle8.mods.galacticraft.core.energy.tile.TileBaseElectricBlock.func_189517_E_(TileBaseElectricBlock.java:162)
	at net.minecraft.network.play.server.SPacketChunkData.<init>(SourceFile:52)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187272_b(PlayerChunkMapEntry.java:157)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:165)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)

-- Affected level --
Details:
	Level name: Creative
	All players: 1 total; [GCEntityPlayerMP['Stffyfun_Ryan'/0, l='Creative', x=-334.50, y=5.41, z=-839.50]]
	Chunk stats: ServerChunkCache: 857 Drop: 0
	Level seed: -4162882503556595820
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-139,255,-905), Chunk: (at 5,15,7 in -9,-57; contains blocks -144,0,-912 to -129,255,-897), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
	Level time: 5783137 game time, 60318 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 3.10.0-957.21.2.el7.x86_64
	Java Version: 1.8.0_212, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1606274032 bytes (1531 MB) / 2130051072 bytes (2031 MB) up to 2130051072 bytes (2031 MB)
	JVM Flags: 10 total; -Xmx2048M -Xms2048M -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalMode -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=2 -XX:+AggressiveOpts -XX:+CMSClassUnloadingEnabled -XX:MaxMetaspaceSize=512M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 38 mods loaded, 37 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version           | Source                                            | Signature                                |
	|:------ |:------------------- |:----------------- |:------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2            | minecraft.jar                                     | None                                     |
	| LCHIJA | mcp                 | 9.42              | minecraft.jar                                     | None                                     |
	| LCHIJA | FML                 | 8.0.99.99         | forge-1.12.2-14.23.5.2838-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2838      | forge-1.12.2-14.23.5.2838-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | micdoodlecore       |                   | minecraft.jar                                     | None                                     |
	| LCHIJA | obfuscate           | 0.2.6             | minecraft.jar                                     | None                                     |
	| LCHIJA | baubles             | 1.5.2             | Baubles-1.12-1.5.2.jar                            | None                                     |
	| LCHIJA | buildcraftlib       | 7.99.24.2         | buildcraft-all-7.99.24.2.jar                      | None                                     |
	| LCHIJA | buildcraftcore      | 7.99.24.2         | buildcraft-all-7.99.24.2.jar                      | None                                     |
	| LCHIJA | buildcraftbuilders  | 7.99.24.2         | buildcraft-all-7.99.24.2.jar                      | None                                     |
	| LCHIJA | buildcrafttransport | 7.99.24.2         | buildcraft-all-7.99.24.2.jar                      | None                                     |
	| LCHIJA | buildcraftsilicon   | 7.99.24.2         | buildcraft-all-7.99.24.2.jar                      | None                                     |
	| LCHIJA | buildcraftcompat    | 7.99.24.2         | buildcraft-all-7.99.24.2.jar                      | None                                     |
	| LCHIJA | buildcraftenergy    | 7.99.24.2         | buildcraft-all-7.99.24.2.jar                      | None                                     |
	| LCHIJA | buildcraftfactory   | 7.99.24.2         | buildcraft-all-7.99.24.2.jar                      | None                                     |
	| LCHIJA | buildcraftrobotics  | 7.99.24.2         | buildcraft-all-7.99.24.2.jar                      | None                                     |
	| LCHIJA | cdm                 | 0.4.1             | cdm-0.4.1-mc1.12.2.jar                            | None                                     |
	| LCHIJA | cfm                 | 6.3.0             | cfm-6.3.0-mc1.12.2.jar                            | None                                     |
	| LCHIJA | cgm                 | 0.12.1            | cgm-0.12.1-mc1.12.2.jar                           | None                                     |
	| LCHIJA | golems              | 7.1.5             | ExtraGolems-1.12-7.1.5.jar                        | None                                     |
	| LCHIJA | galacticraftcore    | 4.0.2.220         | Galacticraft-Mod-1.12.2.jar                       | None                                     |
	| LCHIJA | galacticraftplanets | 4.0.2.220         | Galacticraft-Planets-Mod-1.12.2.jar               | None                                     |
	| LCHIJA | ironbackpacks       | 1.12.2-3.0.8-12   | IronBackpacks-1.12.2-3.0.8-12.jar                 | None                                     |
	| LCHIJA | ironchest           | 1.12.2-7.0.67.844 | ironchest-1.12.2-7.0.72.847.jar                   | None                                     |
	| LCHIJA | lsc                 | 0.6.2.2-alpha     | Loot+Slash+Conquer-1.12.2-0.6.2.2-alpha.jar       | None                                     |
	| LCHIJA | mycommands          | 1.12.2-01         | MyCommands-Mod-1.12.2.jar                         | None                                     |
	| LCHIJA | railcraft           | 12.0.0            | railcraft-12.0.0.jar                              | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LCHIJA | reborncore          | 3.16.0.469        | RebornCore-1.12.2-3.16.0.469-universal.jar        | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCHIJA | stevescarts         | 2.4.31.135        | StevesCarts-1.12.2-2.4.31.135.jar                 | None                                     |
	| LCHIJA | tickratechanger     | 1.0.14            | TickrateChanger-Mod-1.12.2.jar                    | None                                     |
	| LCHIJA | torcherino          | 7.6               | torcherino-7.6.jar                                | None                                     |
	| LCHIJA | twilightforest      | 3.9.984           | twilightforest-1.12.2-3.9.984-universal.jar       | None                                     |
	| LCHIJA | vehicle             | 0.41.0            | vehicle-0.41.0-mc1.12.2.jar                       | None                                     |
	| LCHIJA | llibrary            | 1.7.19            | llibrary-1.7.19-1.12.2.jar                        | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | wings               | 1.1.5             | wings-1.1.5-1.12.2.jar                            | None                                     |
	| LCHIJA | bauble_wings        | 1.0.0             | wings-1.1.5-1.12.2.jar                            | None                                     |
	| LCHIJA | worldedit           | 6.1.10-SNAPSHOT   | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |
	| UD     | mobends_wings       | 1.0.0             | wings-1.1.5-1.12.2.jar                            | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
wings (wings-1.1.5-1.12.2.jar)
  me.paulf.wings.server.asm.WingsRuntimePatcher
  me.paulf.wings.server.asm.mobends.WingsMoBendsRuntimePatcher
MicdoodlePlugin (MicdoodleCore-1.12.2 (1).jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
TickrateChanger (TickrateChanger-Mod-1.12.2.jar)
  me.guichaguri.tickratechanger.TickrateTransformer
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.16.0.469
		Runtime Debofucsation 1
	Profiler Position: N/A (disabled)
	Player Count: 1 / 35; [GCEntityPlayerMP['Stffyfun_Ryan'/0, l='Creative', x=-334.50, y=5.41, z=-839.50]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by radfast** [comment]
Please update your Galacticraft to the latest version.  This has already been fixed by fe94b85
