### ISSUE TITLE
Laser Turret Beta - Polygon Model Rescaling Bug

### ISSUE THREAD

**Issue by ARandomDeadGuy2** [micdoodle8/Galacticraft#3779]
Minecraft version: 1.12.2
Galacticraft version: 4.0.2.233

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? 
>SSP

Any Galacticraft add-ons installed? please list all 
>ExtraPlanets, More Planets

Please provide screenshots / crash report / log / full modlist as needed
Modlist:
-Baubles 1.12 v1.5.2
-Biomes O' Plenty 1.12.2 v7.0.1.2419 universal
-Bookshelf 1.12.2 v2.3.585
-ExtraPlanets 1.12.2 v0.5.6
-GalacticraftCore 1.12.2 v4.0.2.233
-Galacticraft Planets 1.12.2 v4.0.2.233
-Gravitation Suite v3.1.1
-IC2 v2.8.170-ex112
-Lost Cities 1.12 v2.0.15
-Lucky Blocks 1.12.2 v7.6.0
-MCA 1.12.2 v6.0.0 universal
-MicdoodleCore 1.12.2 v4.0.2.233
-MJRLegendsLib 1.12.2 v1.1.8
-Modular Powersuits 1.12.2 v1.0.46
-More Planets 1.12.2 v2.0.21-GC224
-More Swords Legacy 1.12.2 v1.0.4
-Numina 1.12.2 v1.0.38
-RadixCore 1.12.X v2.2.1 universal
-Rex's Additional Structures 1.12.X v2.2.2
-The Betweenlands v3.4.4 universal

Screenshots:
![2019-08-30_01 39 53](https://user-images.githubusercontent.com/54706281/64010384-841bd100-cace-11e9-852e-1a935b12a5f3.png)
![2019-08-30_02 41 47](https://user-images.githubusercontent.com/54706281/64011071-d27d9f80-cacf-11e9-8e75-dd871e3ee2af.png)
![2019-08-30_02 44 17](https://user-images.githubusercontent.com/54706281/64011231-2092a300-cad0-11e9-90c5-d1b7a00468ba.png)
![2019-08-30_02 45 57](https://user-images.githubusercontent.com/54706281/64011354-60598a80-cad0-11e9-805d-2ce5431222b0.png)

If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft)

**Comment by ARandomDeadGuy2** [comment]
The only striking issue I have noticed thus far in terms of bugs related to the laser turrets is that the polygonal model for the idle laser upscales significantly with distance. A screenshot of this effect has been attached, showing the apparent size of the beam polygons relative to a spherical base that is 31 blocks in diameter. When the player approaches the turrets, the polygon models scale back down to their proper size. The exact cause for this bug is not known, but given the turrets are still in the Beta phase, I figured the input would be useful for the development team.

**Comment by ARandomDeadGuy2** [comment]
As an update to the observed behavior of the polygon models, they gradually increase in size after the player reaches a certain distance away, and continue to expand until the player approaches them.

**Comment by micdoodle8** [comment]
Thanks, it was such a gradual increase I didn't notice :)

**Comment by ARandomDeadGuy2** [comment]
No problem! I'll be sure to report any other issues I run across as well.
