### ISSUE TITLE
no cargo rockets, or even launch controllers.

### ISSUE THREAD

**Issue by manssimba** [micdoodle8/Galacticraft#3783]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 4

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
server with forge

Any Galacticraft add-ons installed? please list all
none

Please provide screenshots / crash report / log / full modlist as needed

i don't get any cargo stuff.

**Comment by TheQuadShot** [comment]
Please provide more information, here's what we need to be able to help:

Version numbers for the following:
Minecraft
Forge
GalacticraftCore
Galacticraft-Planets
MicdoodleCore

Be sure to provide the full version number. (ie GalacticraftCore - 1.12.4.0.1.181)
A complete list of installed mods, this can be done by opening a Command Prompt in the /mods directory and typing: dir/b >modlist.txt
This will create a list of your mods(in the same directory) to a .txt file called modlist.txt, then upload this file to pastebin(it's free) or equivalent and provide a link to the file.
It might also be helpful to post your latest.log file as well. It can be found in your /logs directory.

**Comment by manssimba** [comment]
okay...
minecraft: 1.12.2
forge: 14.23.5.2844
galacticraft - dont know, downloaded recommended like yesterday
galacticraft planets- dont have
micdoodlecore - same as galacticraft core.

**Comment by manssimba** [comment]
and forge server side is 14.23.5.276

**Comment by manssimba** [comment]
oh and client side optifine

**Comment by radfast** [comment]
>    galacticraft planets- dont have

Cargo Rockets and Launch Controllers are features in **Galacticraft Planets**.  You should download this too, it's a part of the mod.  [Official download link](https://micdoodle8.com/mods/galacticraft/downloads)
