### ISSUE TITLE
Industrialcraft 2 and Galacticraft crash at launch.

### ISSUE THREAD

**Issue by GoldenTensar** [micdoodle8/Galacticraft#3784]
Minecraft version: 1.12.2
Galacticraft version: GalacticraftCore-1.12.2-4.0.2.236
Industrial craft version: industrialcraft-2-2.8.170-ex112  (but it's not working with other versions I tested too)

Single player

None

https://paste.dimdev.org/cupedupuvi.mccrash

Downloaded galacticraft on his official website, and industrialcraft on CurseForge

**Comment by radfast** [comment]
>   java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.

It's not a conflict.  The game has run out of block IDs.  The problem here is simply that you have **too many mods**.   Remove the mods you are not using.   Or use the mod **NotEnoughIDs**
