### ISSUE TITLE
Quick Question: is the oxygen mask supposed to make you Taller?

### ISSUE THREAD

**Issue by BrisingrAerowing** [micdoodle8/Galacticraft#3785]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)
[From this Reddit post](https://www.reddit.com/r/feedthebeast/comments/cydpan/til_gc_oxygen_mask_makes_you_taller/)
Minecraft version: Asked for on post above
Galacticraft version:

Also, the Discord link on the main site doesn’t work on mobile.

**Comment by micdoodle8** [comment]
Yes, it's very subtle. 1.9375m instead of 1.8m
