### ISSUE TITLE
Server crash while using Fluxbore on the moon

### ISSUE THREAD

**Issue by shroomdog27** [micdoodle8/Galacticraft#3787]
Minecraft version: 1.12.2
Galacticraft version: GalacticraftCore-1.12.2-4.0.2.236, Galacticraft-Planets-1.12.2-4.0.2.236, MicdoodleCore-1.12.2-4.0.2.236

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? SMP crashes, SSP does not crash, but still prints errors

Any Galacticraft add-ons installed? None

Please provide screenshots / crash report / log / full modlist as needed: 

Modlist: CodeChickenLib, CoFHCore, CoFHWorld, RedstoneFlux, ThermalCultiviation, ThermalDynamics, ThermalExpansion, ThermalFoundation, ThermalInnovation
Server Crash Report: https://pastebin.com/xurvQZXv
Singleplayer log: https://pastebin.com/de57H7AZ

#### Issue description:
When in survival mode, if a player tries to use a Fluxbore added by ThermalInnovation to drill on the moon, the server crashes while on SMP, and prints an error in the log on SSP. In SSP, the server does not crash, but the item pops out normally.

#### Steps to reproduce:
1. Install CodeChickenLib, CoFHCore, CoFHWorld, RedstoneFlux, ThermalCultiviation, ThermalDynamics, ThermalExpansion, ThermalFoundation, ThermalInnovation, GalacticraftCore, Galacticraft-Planets, MicdoodleCore
2. Travel to the moon.
3. Equip oxygen equipment for survival mode and obtain a Fluxbore (any should reproduce the issue. I used the creative mode bore.)
4. Drill past the surface of the moon using a multiblock mode (I used 5x5) 
5. Experience server crash

**Comment by radfast** [comment]
Thanks very much for reporting.  This is fixable, but it will be a couple of days or more before we can get to this and make the next build.

**Comment by radfast** [comment]
I have looked at this.  The issue is in the Fluxbore, not in Galacticraft - their code will potentially cause crashes with many / most blocks.

This is the problem code:
https://github.com/CoFH/ThermalInnovation/blob/1.12/src/main/java/cofh/thermalinnovation/item/ItemDrill.java#L187-L202

Their interaction with vanilla Minecraft is bad, they should not break the actual block the player is using the item on, inside the `onBlockStartBreak()` method call.  This is because vanilla Minecraft code assumes that the blockstate the item is being used on remains unchanged.

See vanilla code:

            IBlockState iblockstate = this.world.getBlockState(pos);  //iblockstate is set
            TileEntity tileentity = this.world.getTileEntity(pos);
            Block block = iblockstate.getBlock();

            if ((block instanceof BlockCommandBlock || block instanceof BlockStructure) && !this.player.canUseCommandBlock())
            {
                this.world.notifyBlockUpdate(pos, iblockstate, iblockstate, 3);
                return false;
            }
            else
            {
                ItemStack stack = player.getHeldItemMainhand();
                if (!stack.isEmpty() && stack.getItem().onBlockStartBreak(stack, pos, player)) return false;   //ThermalInnovations Fluxbore (drill) can change blockstates in the world here

                this.world.playEvent(this.player, 2001, pos, Block.getStateId(iblockstate));
                boolean flag1 = false;

                if (this.isCreative())
                {
                    flag1 = this.removeBlock(pos);
                    this.player.connection.sendPacket(new SPacketBlockChange(this.world, pos));
                }
                else
                {
                    ItemStack itemstack1 = this.player.getHeldItemMainhand();
                    ItemStack itemstack2 = itemstack1.isEmpty() ? ItemStack.EMPTY : itemstack1.copy();
                    boolean flag = iblockstate.getBlock().canHarvestBlock(world, pos, player);   //Here the vanilla code assumes iblockstate still represents the block at pos

**Comment by radfast** [comment]
OK looks like we can fix this on our side anyhow without too much problem, please wait for next build 237.

**Comment by shroomdog27** [comment]
That seems very narcissistic that the CoFH team automatically assumes all issues are due to people not using their mods correctly rather than implementing their code poorly. Well, thanks for fixing this from your side regardless.
