### ISSUE TITLE
Incorrect dungeons generation

### ISSUE THREAD

**Issue by electron93** [micdoodle8/Galacticraft#3789]
- Minecraft version: **1.12.2**
 - Forge version: **14.23.5.2838** (or **14.23.5.2846** on the test server)
 - Galacticraft version: **1.12.2-4.0.2.237** (also with earlier builds)
 - **SpongeForge** version: **1.12.2-2838-7.1.7-RC3908**
 - Java version: **1.8.0_222/64-bit**

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? **Multiplayer**

All other mods are disabled. The entrance room is not generated at all. Corridors are generated blocked quite often.

<details><summary>Screenshots: Dungeon</summary><p>

![2019-09-10_12 33 08](https://user-images.githubusercontent.com/1076914/64603873-b7613880-d3c9-11e9-86e7-059b69e8a1dd.png)

![2019-09-10_12 33 15](https://user-images.githubusercontent.com/1076914/64603885-bcbe8300-d3c9-11e9-84ab-fc3cce301d13.png)

![2019-09-10_12 33 59](https://user-images.githubusercontent.com/1076914/64603893-bfb97380-d3c9-11e9-9885-c2385d3b22e9.png)

![2019-09-10_12 34 28](https://user-images.githubusercontent.com/1076914/64603898-c2b46400-d3c9-11e9-8503-9644530245cd.png)

![2019-09-10_12 34 40](https://user-images.githubusercontent.com/1076914/64603903-c647eb00-d3c9-11e9-8a39-5e4b3a0b0057.png)

![2019-09-10_12 34 56](https://user-images.githubusercontent.com/1076914/64603910-ca740880-d3c9-11e9-8406-61ec5c4c65f3.png)

![2019-09-10_12 35 00](https://user-images.githubusercontent.com/1076914/64603915-cea02600-d3c9-11e9-9fff-8a41949996a3.png)
</p></details>

<details><summary>Screenshots: Another dungeon. Corridor blocked in several places.</summary><p>

![2019-09-10_12 59 56](https://user-images.githubusercontent.com/1076914/64604608-1d9a8b00-d3cb-11e9-94e5-8ae848778db8.png)

![2019-09-10_13 00 04](https://user-images.githubusercontent.com/1076914/64604624-24290280-d3cb-11e9-8c07-5aacaed62d51.png)

![2019-09-10_13 00 11](https://user-images.githubusercontent.com/1076914/64604631-27bc8980-d3cb-11e9-9977-376704b2a027.png)

![2019-09-10_13 00 25](https://user-images.githubusercontent.com/1076914/64604645-2be8a700-d3cb-11e9-9f1c-9a06534df293.png)
</p></details>

_It could also be caused by some kind of bug in Sponge..._

**Comment by MJRLegends** [comment]
Please post your seed and coords of this dungeon

**Comment by electron93** [comment]
@MJRLegends That world has already been deleted.

New seed and coordinates of the dungeons:
 - moonmoon Seed: `-6617320935096621212`, dungeons: [`-366 274`, `434 562`]

**Comment by Siiriiks** [comment]
I am having the exact same problem. We haven't been able to find any dungeons on the Moon at all on my server. But we can find them easily on Singleplayer. The Server and Modpack have the same config files and Galacticraft Version (4.0.2.231).

**Comment by radfast** [comment]
@Siiriiks  is your server also a Sponge server?

**Comment by Siiriiks** [comment]
> @Siiriiks is your server also a Sponge server?

Yes, my server is running spongeforge-1.12.2-2838-7.1.7-RC3910.

**Comment by DaveDevil** [comment]
same problem here, also with sponge.

spongeforge-1.12.2-2825-7.1.7-RC3774

**Comment by laundmo** [comment]
problem still persists with `spongeforge-1.12.2-2838-7.1.9.jar`

**Comment by cestofmir** [comment]
Problem still persits

spongeforge-1.12.2-2838-7.2.1-RC4011

Galacticraft 1.12.2-4.0.3.244

**Comment by QuantumStatement** [comment]
#2810?

**Comment by KraKcze** [comment]
Hello, same problem here. Also with sponge.
Do you know any reasonable fix?
Thank you for reply.

**Comment by Romz24** [comment]
I encountered the same problem on version 1.12.2

GC version: 4.0.2.280
Sponge: 2838-7.2.2
Forge: 14.23.5.2854

<details>
  <summary>Screenshot</summary>

![biEfuF7kiRk](https://user-images.githubusercontent.com/2458113/85953200-4f3f0b80-b977-11ea-9697-7a3a08cf24a3.jpg)
![UEuuZN8HU_o](https://user-images.githubusercontent.com/2458113/85953202-4fd7a200-b977-11ea-9c44-7b96691707d0.jpg)
</details>
