### ISSUE TITLE
Visual incompatibility with Wings mod when BlockBuster mod present

### ISSUE THREAD

**Issue by Herbertofury** [micdoodle8/Galacticraft#3791]
EDITED
HELP VERY MUCH APPRECIATED
With only the main galacticraft core mods and
wings from wings mod, wings do not render at all
tails work somehow though
![df](https://user-images.githubusercontent.com/18050735/64728068-720b3c80-d497-11e9-86cb-56dacf8186ad.png)

wings- 1.15
forge version: 14.23.5.2846
minecraft version 1.12.2
metamorph version 1.18
mclib version 1.0.3
wings version 1.15
Galacticraft version: 
GalacticraftCore-1.12.2-4.0.2.237
Galacticraft-Planets-1.12.2-4.0.2.237
MicdoodleCore-1.12.2-4.0.2.237

Incompatibility is super weird as it involves meta morph and blockbuster mods not working with wings only when galacticraft is installed. Solved issue by removing both of those mods and only keeping emoticons

**Comment by radfast** [comment]
Please provide a link of where you reported this to the Wings developers?

**Comment by radfast** [comment]
OK in my tests, Galacticraft and Wings are working fine together - with **no other mods installed**.

![2019-09-14_18 33 06](https://user-images.githubusercontent.com/6842258/64911802-59f91e80-d71e-11e9-8f5c-ac6231a7820e.png)

Looks like MetaMorph may be the problem ... needs further investigation.

**Comment by radfast** [comment]
Even with MetaMorph 1.18 installed, everything **still** looks OK in my tests, the wings are displayed.

Do I have to do something else to stop showing the wings, like use MetaMorph to switch to a mob and switch back to a player?

**Comment by radfast** [comment]
OK I can reproduce it by adding BlockBuster mod as well as Metamorph.  That's strange.

The issue is connected with Metamorph's RenderSubPlayer and [this issue](https://github.com/mchorse/metamorph/issues/82)

**Comment by radfast** [comment]
I've managed to fix this by adding code which detects Metamorph's non-standard way of doing things.
Please wait for next GC build 238.

**Comment by snowfox1600** [comment]
wait so if I download galaticraft then will the metamorphosis problem persist or will it be ok

**Comment by ROMVoid95** [comment]
As long as no changes to the metamorph mod was made between then and now, it should be fine.
