### ISSUE TITLE
EnderLiquidConduit at BlockPos{x=18193, y=50, z=-19132}: Inserted fluid volume (8mB) is less than when we asked the target how much to insert (16mB). This means that one of the blocks connected to this conduit line has a bug.

### ISSUE THREAD

**Issue by clienthax** [micdoodle8/Galacticraft#3794]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: GalacticraftCore-1.12.2-4.0.2.224

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SMP

Any Galacticraft add-ons installed? please list all
Galacticraft-Planets

Please provide screenshots / crash report / log / full modlist as needed
Technic launcher: Tekxit 3.

![image](https://user-images.githubusercontent.com/1056270/64893896-34154080-d670-11e9-99aa-88d1233e9b99.png)

![image](https://user-images.githubusercontent.com/1056270/64893882-2b246f00-d670-11e9-9654-38c0c22500f9.png)

The setup in question is 4x Galacticraft oxygen collectors in a row, feeding into a Enderio Fluid tank + galacticraft blocks (oxygen bubble distributor, Oxygen compressor),

It seems that the Oxygen bubble distributor is the faulty block here, causing logspam from enderio, removing this block from the network prevents any warnings.

```
> [21:43:58] [Server thread/WARN] [enderio]: EnderLiquidConduit at BlockPos{x=18193, y=50, z=-19132}: Inserted fluid volume (8mB) is less than when we asked the target how much to insert (16mB). This means that one of the blocks connected to this conduit line has a bug.
> [21:43:58] [Server thread/WARN] [enderio]: EnderLiquidConduit at BlockPos{x=18193, y=50, z=-19132}: In addition, putting back 8mB into the source tank failed, leading to 8mB being voided.
> [21:43:58] [Server thread/WARN] [enderio]: EnderLiquidConduit at BlockPos{x=18193, y=50, z=-19132}: Inserted fluid volume (8mB) is less than when we asked the target how much to insert (16mB). This means that one of the blocks connected to this conduit line has a bug.
> [21:43:58] [Server thread/WARN] [enderio]: EnderLiquidConduit at BlockPos{x=18193, y=50, z=-19132}: In addition, putting back 8mB into the source tank failed, leading to 8mB being voided.
> [21:43:58] [Server thread/WARN] [enderio]: EnderLiquidConduit at BlockPos{x=18193, y=50, z=-19132}: Inserted fluid volume (8mB) is less than when we asked the target how much to insert (16mB). This means that one of the blocks connected to this conduit line has a bug.
> [21:43:58] [Server thread/WARN] [enderio]: EnderLiquidConduit at BlockPos{x=18193, y=50, z=-19132}: In addition, putting back 8mB into the source tank failed, leading to 8mB being voided.
> [21:43:58] [Server thread/WARN] [enderio]: EnderLiquidConduit at BlockPos{x=18193, y=50, z=-19132}: Inserted fluid volume (8mB) is less than when we asked the target how much to insert (16mB). This means that one of the blocks connected to this conduit line has a bug.
> [21:43:58] [Server thread/WARN] [enderio]: EnderLiquidConduit at BlockPos{x=18193, y=50, z=-19132}: In addition, putting back 8mB into the source tank failed, leading to 8mB being voided.
> [21:43:58] [Server thread/WARN] [enderio]: EnderLiquidConduit at BlockPos{x=18193, y=50, z=-19132}: Inserted fluid volume (8mB) is less than when we asked the target how much to insert (16mB). This means that one of the blocks connected to this conduit line has a bug.
> [21:43:58] [Server thread/WARN] [enderio]: EnderLiquidConduit at BlockPos{x=18193, y=50, z=-19132}: In addition, putting back 8mB into the source tank failed, leading to 8mB being voided.
```

**Comment by radfast** [comment]
Thanks and hello @clienthax old friend :)

**Comment by clienthax** [comment]
Cheers @radfast , good to see you are still around :)
Discord clienthax#1337 if you want to catch up

**Comment by radfast** [comment]
This is fixed in next build 238 when it comes.
There's no bug, by design the GC oxygen machines always ask for twice as much oxygen as they use, this ensures the internal oxygen tank will fill up even while the machine is working.
I've capped this behaviour when the machine is full, so there's shouldn't be any more warnings in future.

I'm still _partly_ around, don't have as much time for coding as before but I'm aiming to keep adding to Galacticraft when I can.

**Comment by clienthax** [comment]
@radfast Do you have any idea what commit hash  GalacticraftCore-1.12.2-4.0.2.224 was?
Alternatively, were there any packet changes between latest and that version as if not i should just be ok changing out the version number serverside for now ;)

**Comment by radfast** [comment]
I don't know exactly, but it was 28 July so around [this one](https://github.com/micdoodle8/Galacticraft/commit/004dab2ee85480326a4cdc99801edf5ef433469b)

There can be server/client incompatibility if you update server-side only, because Galacticraft recently added a new block and tile, the [Laser Turret](https://github.com/micdoodle8/Galacticraft/commit/b066c99c7c307689496a73b397dab4b21e8dcb0e).  I guess there's a chance you could be OK if no players actually build those - and how would they know to if they don't have the recipe client-side?  But I can't promise it won't lead to Forge messing up the block IDs somehow...   Try it and see?

**Comment by clienthax** [comment]
@radfast This doesn't seem to of fixed the issue :(
Would a world copy of the troublesome place be usefull?

**Comment by HenryLoenwind** [comment]
Just one thing: Please make sure the conduit network only has a single connection to the block it's complaining about. Otherwise it may trigger a known issue on our side.

**Comment by clienthax** [comment]
@HenryLoenwind Will have a look soon, Do you have a link to the issue in question?
