### ISSUE TITLE
crash when placing laser turret

### ISSUE THREAD

**Issue by NITDroid1995** [micdoodle8/Galacticraft#3795]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 4.0.2.236

Multiplayer (SMP)

Any Galacticraft add-ons installed? please list all
ExtraPlanets-1.12.2-0.5.6

Please provide screenshots / crash report / log / full modlist as needed
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.57-core.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.236.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  SpongeCoremod (spongeforge-1.12.2-2838-7.1.7-RC3924.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.17-universal.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  EmoticonsCore (emoticons-0.2.1-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 20.09.19 14:21
Description: Exception ticking world

java.lang.NoSuchFieldError: timeSinceShot
	at micdoodle8.mods.galacticraft.planets.venus.tile.TileEntityLaserTurret.<init>(TileEntityLaserTurret.java:98)
	at micdoodle8.mods.galacticraft.planets.venus.blocks.BlockLaserTurret.func_149915_a(BlockLaserTurret.java:105)
	at net.minecraft.block.Block.createTileEntity(Block.java:1274)
	at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:782)
	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:800)
	at net.minecraft.world.World.redirect$impl$getTileOrNullIfMarkedForRemoval$zlm000(World.java:8901)
	at net.minecraft.world.WorldServer.redirect$impl$getTileOrNullIfMarkedForRemoval$zlm000(WorldServer.java:4698)
	at net.minecraft.world.World.func_175625_s(World.java:2399)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java:250)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:115)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at micdoodle8.mods.galacticraft.planets.venus.tile.TileEntityLaserTurret.<init>(TileEntityLaserTurret.java:98)
	at micdoodle8.mods.galacticraft.planets.venus.blocks.BlockLaserTurret.func_149915_a(BlockLaserTurret.java:105)
	at net.minecraft.block.Block.createTileEntity(Block.java:1274)
	at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:782)
	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:800)
	at net.minecraft.world.World.redirect$impl$getTileOrNullIfMarkedForRemoval$zlm000(World.java:8901)
	at net.minecraft.world.WorldServer.redirect$impl$getTileOrNullIfMarkedForRemoval$zlm000(WorldServer.java:4698)
	at net.minecraft.world.World.func_175625_s(World.java:2399)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java:250)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:115)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)

-- Affected level --
Details:
	Level name: world
	All players: 2 total; [GCEntityPlayerMP['Frisk'/224, l='world', x=-689,93, y=70,00, z=-186,46], GCEntityPlayerMP['NITDroid'/3182, l='world', x=-691,62, y=70,00, z=-184,65]]
	Chunk stats: ServerChunkCache: 925 Drop: 0
	Level seed: 1465593826094700044
	Level generator: ID 10 - RTG, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-256,64,-148), Chunk: (at 0,4,12 in -16,-10; contains blocks -256,0,-160 to -241,255,-145), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 762629 game time, 864480 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 142321 (now: false), thunder time: 139738 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false

-- Sponge PhaseTracker --
Details:
	Phase Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zji000(MinecraftServer.java:4721)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:889)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:371)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:554)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 7119393544 bytes (6789 MB) / 8163164160 bytes (7785 MB) up to 8163164160 bytes (7785 MB)
	JVM Flags: 2 total; -Xmx8G -Xms4G
	IntCache: cache: 0, tcache: 0, allocated: 16, tallocated: 121
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 60 mods loaded, 59 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	Mods:

	| State  | ID                                | Version                  | Source                                        | Signature                                |
	|:------ |:--------------------------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                         | 1.12.2                   | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                               | 9.42                     | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                               | 8.0.99.99                | forge.jar                                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                             | 14.23.5.2838             | forge.jar                                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | ivtoolkit                         | 1.3.3-1.12               | minecraft.jar                                 | None                                     |
	| LCHIJA | micdoodlecore                     |                          | minecraft.jar                                 | None                                     |
	| LCHIJA | spongeapi                         | 7.1.0-13da4949c          | spongeforge-1.12.2-2838-7.1.7-RC3924.jar      | None                                     |
	| LCHIJA | sponge                            | 1.12.2-7.1.7-SNAPSHOT    | spongeforge-1.12.2-2838-7.1.7-RC3924.jar      | None                                     |
	| LCHIJA | spongeforge                       | 1.12.2-2838-7.1.7-RC3924 | spongeforge-1.12.2-2838-7.1.7-RC3924.jar      | None                                     |
	| LCHIJA | dsurroundcore                     | 3.5.4.3                  | minecraft.jar                                 | None                                     |
	| LCHIJA | bookshelf                         | 2.3.581                  | Bookshelf-1.12.2-2.3.581.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | carryon                           | 1.12.1                   | CarryOn+MC1.12.2+v1.12.1.jar                  | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
	| LCHIJA | codechickenlib                    | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | containerfix                      | 1.0                      | ContainerFix+MC1.12.2+v1.0.jar                | None                                     |
	| LCHIJA | crafttweaker                      | 4.1.18                   | CraftTweaker2-1.12-4.1.18.jar                 | None                                     |
	| LCHIJA | mtlib                             | 3.0.6                    | MTLib-3.0.6.jar                               | None                                     |
	| LCHIJA | modtweaker                        | 4.0.17                   | modtweaker-4.0.17.jar                         | None                                     |
	| LCHIJA | jei                               | 4.15.0.280               | jei_1.12.2-4.15.0.280.jar                     | None                                     |
	| LCHIJA | crafttweakerjei                   | 2.0.3                    | CraftTweaker2-1.12-4.1.18.jar                 | None                                     |
	| LCHIJA | emoticons                         | 0.2.1                    | emoticons-0.2.1-1.12.2.jar                    | None                                     |
	| LCHIJA | endercore                         | 1.12.2-0.5.57            | EnderCore-1.12.2-0.5.57.jar                   | None                                     |
	| LCHIJA | enderio                           | 5.0.44                   | EnderIO-1.12.2-5.0.44.jar                     | None                                     |
	| LCHIJA | enderiointegrationtic             | 5.0.44                   | EnderIO-1.12.2-5.0.44.jar                     | None                                     |
	| LCHIJA | enderiobase                       | 5.0.44                   | EnderIO-1.12.2-5.0.44.jar                     | None                                     |
	| LCHIJA | enderioconduits                   | 5.0.44                   | EnderIO-1.12.2-5.0.44.jar                     | None                                     |
	| LCHIJA | enderioconduitsappliedenergistics | 5.0.44                   | EnderIO-1.12.2-5.0.44.jar                     | None                                     |
	| LCHIJA | enderioconduitsopencomputers      | 5.0.44                   | EnderIO-1.12.2-5.0.44.jar                     | None                                     |
	| LCHIJA | enderioconduitsrefinedstorage     | 5.0.44                   | EnderIO-1.12.2-5.0.44.jar                     | None                                     |
	| LCHIJA | forestry                          | 5.8.2.387                | forestry_1.12.2-5.8.2.387.jar                 | None                                     |
	| LCHIJA | enderiointegrationforestry        | 5.0.44                   | EnderIO-1.12.2-5.0.44.jar                     | None                                     |
	| LCHIJA | mantle                            | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                      | None                                     |
	| LCHIJA | tconstruct                        | 1.12.2-2.12.0.135        | TConstruct-1.12.2-2.12.0.135.jar              | None                                     |
	| LCHIJA | enderiointegrationticlate         | 5.0.44                   | EnderIO-1.12.2-5.0.44.jar                     | None                                     |
	| LCHIJA | enderiomachines                   | 5.0.44                   | EnderIO-1.12.2-5.0.44.jar                     | None                                     |
	| LCHIJA | enderiopowertools                 | 5.0.44                   | EnderIO-1.12.2-5.0.44.jar                     | None                                     |
	| LCHIJA | epicsiegemod                      | 13.164                   | EpicSiegeMod-13.164.jar                       | None                                     |
	| LCHIJA | galacticraftcore                  | 4.0.2.236                | GalacticraftCore-1.12.2-4.0.2.236.jar         | None                                     |
	| LCHIJA | galacticraftplanets               | 4.0.2.236                | Galacticraft-Planets-1.12.2-4.0.2.236.jar     | None                                     |
	| LCHIJA | mjrlegendslib                     | 1.12.2-1.1.8             | MJRLegendsLib-1.12.2-1.1.8.jar                | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHIJA | extraplanets                      | 1.12.2-0.5.6             | ExtraPlanets-1.12.2-0.5.6.jar                 | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHIJA | railcraft                         | 12.0.0                   | railcraft-12.0.0.jar                          | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LCHIJA | immersiveengineering              | 0.12-89                  | ImmersiveEngineering-0.12-89.jar              | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCHIJA | immersivepetroleum                | 1.1.9                    | immersivepetroleum-1.12.2-1.1.9.jar           | None                                     |
	| LCHIJA | immersivetech                     | 1.3.10                   | immersivetech-1.12-1.3.10.jar                 | None                                     |
	| LCHIJA | industrialrenewal                 | 0.9                      | IndustrialRenewal_1.12.2-0.9.jar              | None                                     |
	| LCHIJA | malisiscore                       | 1.12.2-6.5.1-SNAPSHOT    | malisiscore-1.12.2-6.5.1.jar                  | None                                     |
	| LCHIJA | malisisdoors                      | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                 | None                                     |
	| LCHIJA | recipehandler                     | 0.13                     | NoMoreRecipeConflict-0.13(1.12.2).jar         | None                                     |
	| LCHIJA | nei                               | 2.4.2                    | NotEnoughItems-1.12.2-2.4.2.240-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | planetprogression                 | 1.12.2-0.3.8             | PlanetProgression-1.12.2-0.3.8.jar            | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHIJA | sereneseasons                     | 1.2.17                   | SereneSeasons-1.12.2-1.2.17-universal.jar     | None                                     |
	| LCHIJA | wawla                             | 2.5.273                  | Wawla-1.12.2-2.5.273.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | orelib                            | 3.5.2.2                  | OreLib-1.12.2-3.5.2.2.jar                     | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dsurround                         | 3.5.4.3                  | DynamicSurroundings-orelib.jar                | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | rtg                               | 6.1.0.0-snapshot.1       | RTG-1.12.2-6.1.0.0-snapshot.1.jar             | None                                     |
	| UD     | emoticons_core                    | 0.2.1                    | minecraft.jar                                 | None                                     |

	Plugins:

	| State  | ID                 | Version     | Source                                      | Signature |
	|:------ |:------------------ |:----------- |:------------------------------------------- |:--------- |
	| LCHIJA | nucleus-heisenberg | 0.9.1       | [PL]Heisenberg-addNucleus.jar               | None      |
	| LCHIJA | luckperms          | 4.4.26      | [PL]LuckPerms-Sponge-4.4.26.jar             | None      |
	| LCHIJA | nucleus            | 1.11.0-S7.1 | [PL]Nucleus-1.11.0-S7.1-MC1.12.2-plugin.jar | None      |
	| LCHIJA | magibridge         | 2.6.2       | [PL]MagiBridge-API7-2.6.2.jar               | None      |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.57-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.236.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
SpongeCoremod (spongeforge-1.12.2-2838-7.1.7-RC3924.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.17-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  org.orecruncher.dsurround.asm.Transformer
EmoticonsCore (emoticons-0.2.1-1.12.2.jar)
  mchorse.emoticons.core.EmoCoreClassTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                 An unsupported base software is installed: 'sponge'. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	Profiler Position: N/A (disabled)
	Player Count: 2 / 100; [GCEntityPlayerMP['Frisk'/224, l='world', x=-689,93, y=70,00, z=-186,46], GCEntityPlayerMP['NITDroid'/3182, l='world', x=-691,62, y=70,00, z=-184,65]]
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)
[crash-2019-09-20_14.21.46-server.txt](https://github.com/micdoodle8/Galacticraft/files/3635461/crash-2019-09-20_14.21.46-server.txt)

If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft)

**Comment by radfast** [comment]
Thank you for reporting, this will be fixed in next Galacticraft build 238.
