### ISSUE TITLE
Galacticraft Moon Villages get corruped by Muon

### ISSUE THREAD

**Issue by Velocihater** [micdoodle8/Galacticraft#3798]
REVIEW THE GUIDELINES - see [Contributing](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) link on right side.

Minecraft version: 1.12.2
Galacticraft version: 4.0.2.237

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
-SS.

Any Galacticraft add-ons installed? please list all
Extra Planets, More Planets, More Planets Extra

Please provide screenshots / crash report / log / full modlist as needed
![2019-09-21_12 31 11](https://user-images.githubusercontent.com/40730042/65391529-d21f9f80-dd2f-11e9-81fc-956ad3388fd3.png)

If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft)

**Comment by radfast** [comment]
Please explain more what is wrong, or post extra pictures.  I don't see anything wrong in that picture, except that the distant chunks are not fully loaded.

In the title of this issue, what do you mean "Muon"?

**Comment by Velocihater** [comment]
Muon is a village terrain generation mod, which I assume also affects Galacticraft villages. As for the corruption, i don't think moon villages are supposed to have wooden planks and crops

**Comment by radfast** [comment]
I see the problem.  I feel like this issue is most likely to be on Muon's side, did you report it to them?  They ought to test whether the dimension is a vanilla dimension, before running their terrain changing code - for example they could look at the WorldProvider type.
