### ISSUE TITLE
Tile entity crash with Telepads

### ISSUE THREAD

**Issue by clienthax** [micdoodle8/Galacticraft#3799]
REVIEW THE GUIDELINES - see [Contributing](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) link on right side.

Minecraft version: 1.12.2
Galacticraft version: GalacticraftCore-1.12.2-4.0.2.224

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Sponge - SMP

Any Galacticraft add-ons installed? please list all
Galacticraft-Planets

Please provide screenshots / crash report / log / full modlist as needed
https://gist.github.com/clienthax/9f2065cddf48d22e766fbc79f5bc8430

From player who had this in their inventory
```
 I looked in my inventory and the telepads I placed were still sitting there.
I did nothing so much as look at my inventory for 5 seconds, and then the server went down.
It seems not only are Galacticraft Short Range Telepads bugged, but they corrupted my (as well as 4 other's) base.
Apparently my player might be messed up as well. I am no longer just concerned about my or my team's items, but if another player loads that chunk and is stuck until being jailed
 I did not anticipate or want to cause any issues, simply just connect facilities with telepads.
```

**Comment by MJRLegends** [comment]
You just got to update your Galacticraft to latest.....
