### ISSUE TITLE
Crash on loading world, Invalid dimension planet.venus

### ISSUE THREAD

**Issue by Lgk2** [micdoodle8/Galacticraft#3806]
REVIEW THE GUIDELINES - see [Contributing](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) link on right side.

Minecraft version: 1.12.2
GalacticraftCore 1.12.2-4.0.2.237
Galacticraft-Planets 1.12.2-4.0.2.237

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
- If SMP server, please mention if it has **Sponge**, AtomMC, BukkitForge, BungeeCord etc.
SSP

Any Galacticraft add-ons installed? please list all
ExtraPlanets

Please provide screenshots / crash report / log / full modlist as needed
https://pastebin.com/rTJsjDNc

**Comment by radfast** [comment]
I don't see any obvious reason for this.  Can you try removing ExtraPlanets from your modlist and restart - please make sure to use a new test world for this type of testing (to avoid block and item loss).

Also please paste up a full log, the error you are reporting is when loading Achievements, could be there was some earlier Venus-related error in the startup.

**Comment by Lgk2** [comment]
It works without extraplanets and that's why i reported it to them first but the developer there said that he doesn't do anything with advancements so it must be related to galacticraft. https://github.com/MJRLegends/ExtraPlanets/issues/484#event-2688931036

**Comment by Lgk2** [comment]
Where do i find the full log?

**Comment by EzerArch** [comment]
> Where do i find the full log?

It's in the Minecraft folder: `\.minecraft\logs\fml-client-latest.log`

**Comment by MJRLegends** [comment]
Seems to me like an dimension id conflict or something and then gc advancements failing

**Comment by Lgk2** [comment]
[latest.log](https://github.com/micdoodle8/Galacticraft/files/3721864/latest.log)
Here's the full log where it happens

**Comment by radfast** [comment]
As I suspected, this is in your logs.   Fix this and you should be OK:

>   [16:31:57] [Client thread/ERROR]: Tried to register dimension for body: planet.asteroids hit conflict with ID -30
[16:31:57] [Client thread/ERROR]: Tried to register dimension for body: planet.mars hit conflict with ID -29
[16:31:57] [Client thread/ERROR]: Tried to register dimension for body: planet.venus hit conflict with ID -31

**Comment by EzerArch** [comment]
> It is so well established in the modding community that Galacticraft uses dimensions -25 to -31.

@radfast, don't you feel important by the fact that we are a well respected part of modding community to the point we have reserved dim ids? I do now. :3

> that I'd be surprised if another mod would take these by default

How dare they?! >:(

**Comment by radfast** [comment]
I don't know about "well respected", seems like a lot of people are angry we are not on CurseForge, and other people are upset we have our own power system instead of using RF power (we actually provide full RF compatibility).  Some devs don't like that we hack the bytecode in MicdoodleCore instead of using Mixins, and a tiny group of other modders really hate that we provide the Galacticraft inventory tab and a continuation of the TConstruct inventory tabs system.

But ... surely every developer knows that we use dimensions -25 to -31, we've been doing that for over 5 years.
