### ISSUE TITLE
Parachest Landing Caused the Server Crash

### ISSUE THREAD

**Issue by Accepted42** [micdoodle8/Galacticraft#3808]
REVIEW THE GUIDELINES - see [Contributing](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) link on right side.

Minecraft version:1.12.2
Galacticraft version:4.0.2.237

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
- If SMP server, please mention if it has **Sponge**, AtomMC, BukkitForge, BungeeCord etc.
SMP, Sponge RC3928

Any Galacticraft add-ons installed? please list all

Please provide screenshots / crash report / log / full modlist as needed
[crash-2019-10-10_01.02.44-server.txt](https://github.com/micdoodle8/Galacticraft/files/3708711/crash-2019-10-10_01.02.44-server.txt)

If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft)

**Comment by radfast** [comment]
Very strange.

    java.lang.NoSuchFieldError: stacks
	at micdoodle8.mods.galacticraft.core.entities.EntityParachest.placeChest(EntityParachest.java:141)
	at micdoodle8.mods.galacticraft.core.entities.EntityParachest.func_70071_h_(EntityParachest.java:98)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:167)
	at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zlh000(WorldServer.java:4740)

The line numbers reported in EntityParachest.java do not match our lines, so something is messing with our code.  The `EntityParachest.placeChest()` method does not make use of any field `stacks`.

**Comment by Accepted42** [comment]
Thanks, the reason has been found. It seems that I loaded a unofficial fix mod which should mess with the parachest code and cause the server crash. Sorry for the bothering.

**Comment by radfast** [comment]
>   I loaded a unofficial fix mod which should mess with the parachest code 

Please give feedback to the author of that "unofficial fix mod", ask them to remove their changes to the parachest?    If there's a bug with the parachest, it will be best to report it to us here, then we can fix it for everybody.

Is that mod "anothercommonbugfix"?

**Comment by Accepted42** [comment]
Yes, it is the mod.
I have made the comment on their mod page. 
And by he way, thanks a lot for your great mod!

**Comment by marcus8448** [comment]
The bug that mod is trying to fix is the bug that PR #3695 solves.

**Comment by radfast** [comment]
Thanks @marcus8448, we should take a look.  Do you know whether the bug is 1.7.10 specific or seen in later GC versions as well?
