### ISSUE TITLE
No way to turn off mobs spawning on other planets

### ISSUE THREAD

**Issue by ShatteredAscent** [micdoodle8/Galacticraft#381]
I just felt that in order to make this mod as realistic as possible that there should be a way to turn off the creepers, spiders, zombies, and skeletons on other planets. i mean i spend days gathering materials to get to the moon just to find out that the mobs beat me there first? they even have oxygen gear. they spawn by the hundreds and theres no way to produce nearly enough light due to reduced oxygen to keep them out of your base. This isn't an immediate issue but i would like to see it in a future update.

**Comment by chezpaul** [comment]
You could try to use Just Another Spawner and config it for specific spawns on the planets.
That's what I'm trying to do. Just haven't figured it out yet. But it can be done.
