### ISSUE TITLE
Cannot mine vapour spout

### ISSUE THREAD

**Issue by ToserBan** [micdoodle8/Galacticraft#3822]
Minecraft version: 1.12.2
Galacticraft version: GalacticraftCore-1.12.2-4.0.2.231.jar
Galacticraft-Planets-1.12.2-4.0.2.231.jar

Single Player

Any Galacticraft add-ons installed? 
ExtraPlanets-1.12.2-0.5.6.jar

When i trie to mine a vapour spout on venus, it doesnt drop, Instead, a venus soft rock block drops. This happens even with silk touch.

**Comment by MJRLegends** [comment]
Update Galacticraft and ExtraPlanets both are out of date

**Comment by radfast** [comment]
Did updating fix it for you?   If it's still happening in the latest version that's a bug we'll need to look at, but for the moment I'm going to mark this "Fixed".  You can still comment and I'll re-open this if we need to.
