### ISSUE TITLE
AE2 p2p to GC Energy cluster crash

### ISSUE THREAD

**Issue by falnen** [micdoodle8/Galacticraft#3830]
After crashing my friend's server i tested this in single player, it is reproducible.

When placing a energy cluster next to an applied energistics FE p2p tunnel on the wrong side (SO placing the output side of the cluster to the output side of the p2p tunnel) The game crashes and the cluster needs to be edited out before restarting the game.

so i guess this would be a comparability thing with AE? i dint notice this when using conduits/cables from other mods.

Minecraft version:1.12.2
Galacticraft version:4.0.2.238

Single player and multiplayer.
Galacticraft planets is installed.

Crash report
 >https://pastebin.com/JYPXrfMu

**Comment by falnen** [comment]
After further testing, i noticed that not all energy sources crash with this setup. using a mekanism energy cube or thermal expansion energy cell (Even a creative one) Will not crash the game but instead instantly drain the energy cube.
Using thermal expansion ducts does still cause a crash. 
> https://pastebin.com/uieAhYMP

**Comment by marcus8448** [comment]
It seems like AE2 expects the energy storage cluster to have the Forge Energy Capability (see [here](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/df2a7c18588aa5d322910dc1a93ca1be3fea372a/src/main/java/appeng/parts/p2p/PartP2PFEPower.java#L78)). But, as the cluster doesn't seem to have the capability, it returns null/`NullEnergyStorage`. Which then crashes the game [here](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/df2a7c18588aa5d322910dc1a93ca1be3fea372a/src/main/java/appeng/parts/p2p/PartP2PFEPower.java#L138)

**Comment by falnen** [comment]
The same think happens with thermal expansion ducts As well. And the crash here is only happening with inputting power from p2p to  the output side of the energy cluster.

**Comment by radfast** [comment]
Thanks for reporting.  We have an open issue relating to the Forge Energy Capability, so I'll be looking at both together and with any luck find a fix for both.

**Comment by falnen** [comment]
I've got applied energistics2 rv6 stable 7.
Not sure if it matters but we have aestuff and extra cells installed As well.

Might be important but we just recently updated our mod list and updated galacticraft from 4.0.2.237 to 4.0.2.238 and didn't notice this issue in till after the update, that's not to say it wasn't there just that I didn't run into it.

**Comment by radfast** [comment]
Thanks @falnen and @marcus8448.  This should be working properly in next build .239.

**Comment by radfast** [comment]
It may take us a few days to make build .239 available for download, due to reasons outside my control.  I'll aim to post in this thread again once .239 is available.
