### ISSUE TITLE
Various warnings in log on startup

### ISSUE THREAD

**Issue by Antoniopf25** [micdoodle8/Galacticraft#3839]
Minecraft version: 1.12.2
Galacticraft version: Galacticraft-Planets-1.12.2-4.0.2.238.jar

Its a multiplayer server, with BungeeCord 1297
The mods are 
![image](https://user-images.githubusercontent.com/58468303/70045097-cec45200-15c3-11ea-9fb4-afe76f785ecc.png) and 
![image](https://user-images.githubusercontent.com/58468303/70045116-d97ee700-15c3-11ea-9cd8-e951c1b0539a.png)

No add-ons of galacticraft intalled

And i have the following problems, sorry for the text

03.12 10:51:30 [Server] Server thread/WARN [FML]: Potentially Dangerous alternative prefix `minecraft` for name `gc beam reflector`, expected `galacticraftplanets`. This could be a intended override, but in most cases indicates a broken mod.
03.12 10:51:30 [Server] Server thread/WARN [FML]: Potentially Dangerous alternative prefix `minecraft` for name `gc beam receiver`, expected `galacticraftplanets`. This could be a intended override, but in most cases indicates a broken mod.
03.12 10:51:30 [Server] Server thread/WARN [FML]: Potentially Dangerous alternative prefix `minecraft` for name `gc short range telepad`, expected `galacticraftplanets`. This could be a intended override, but in most cases indicates a broken mod.
03.12 10:51:30 [Server] Server thread/WARN [FML]: Potentially Dangerous alternative prefix `minecraft` for name `gc fake short range telepad`, expected `galacticraftplanets`. This could be a intended override, but in most cases indicates a broken mod.
03.12 10:51:30 [Server] Server thread/WARN [FML]: Potentially Dangerous alternative prefix `minecraft` for name `gc astro miner base builder`, expected `galacticraftplanets`. This could be a intended override, but in most cases indicates a broken mod.
03.12 10:51:30 [Server] Server thread/WARN [FML]: Potentially Dangerous alternative prefix `minecraft` for name `gc astro miner base`, expected `galacticraftplanets`. This could be a intended override, but in most cases indicates a broken mod.
03.12 10:51:30 [Server] Server thread/WARN [FML]: Potentially Dangerous alternative prefix `minecraft` for name `gc venus spout`, expected `galacticraftplanets`. This could be a intended override, but in most cases indicates a broken mod.
03.12 10:51:30 [Server] Server thread/WARN [FML]: Potentially Dangerous alternative prefix `minecraft` for name `gc venus dungeon spawner`, expected `galacticraftplanets`. This could be a intended override, but in most cases indicates a broken mod.
03.12 10:51:30 [Server] Server thread/WARN [FML]: Potentially Dangerous alternative prefix `minecraft` for name `gc tier 3 treasure chest`, expected `galacticraftplanets`. This could be a intended override, but in most cases indicates a broken mod.
03.12 10:51:30 [Server] Server thread/WARN [FML]: Potentially Dangerous alternative prefix `minecraft` for name `gc geothermal generator`, expected `galacticraftplanets`. This could be a intended override, but in most cases indicates a broken mod.
03.12 10:51:30 [Server] Server thread/WARN [FML]: Potentially Dangerous alternative prefix `minecraft` for name `gc crashed probe`, expected `galacticraftplanets`. This could be a intended override, but in most cases indicates a broken mod.
03.12 10:51:30 [Server] Server thread/WARN [FML]: Potentially Dangerous alternative prefix `minecraft` for name `gc solar array module`, expected `galacticraftplanets`. This could be a intended override, but in most cases indicates a broken mod.
03.12 10:51:30 [Server] Server thread/WARN [FML]: Potentially Dangerous alternative prefix `minecraft` for name `gc solar array controller`, expected `galacticraftplanets`. This could be a intended override, but in most cases indicates a broken mod.
03.12 10:51:30 [Server] Server thread/WARN [FML]: Potentially Dangerous alternative prefix `minecraft` for name `gc laser turret`, expected `galacticraftplanets`. This could be a intended override, but in most cases indicates a broken mod.

A few lines down i have this

03.12 10:51:32 [Server] Server thread/INFO [FML]: Registry SoundEvent: Found a missing id from the world galacticraftcore:laser.shoot
03.12 10:51:32 [Server] Server thread/INFO [FML]: Registry SoundEvent: Found a missing id from the world galacticraftcore:ambience.singledrip
03.12 10:51:32 [Server] Server thread/INFO [FML]: Registry SoundEvent: Found a missing id from the world galacticraftcore:laser.charge
03.12 10:51:32 [Server] Server thread/INFO [FML]: Registry SoundEvent: Found a missing id from the world galacticraftcore:player.openairlock
03.12 10:51:32 [Server] Server thread/INFO [FML]: Registry SoundEvent: Found a missing id from the world galacticraftcore:player.parachute
03.12 10:51:32 [Server] Server thread/INFO [FML]: Registry SoundEvent: Found a missing id from the world galacticraftcore:shuttle.shuttle
03.12 10:51:32 [Server] Server thread/INFO [FML]: Registry SoundEvent: Found a missing id from the world galacticraftcore:player.closeairlock
03.12 10:51:32 [Server] Server thread/INFO [FML]: Registry SoundEvent: Found a missing id from the world galacticraftcore:entity.bosslaugh
03.12 10:51:32 [Server] Server thread/INFO [FML]: Registry SoundEvent: Found a missing id from the world galacticraftcore:ambience.scaryscape
03.12 10:51:32 [Server] Server thread/INFO [FML]: Registry SoundEvent: Found a missing id from the world galacticraftcore:galacticraft.music_space
03.12 10:51:32 [Server] Server thread/INFO [FML]: Registry SoundEvent: Found a missing id from the world galacticraftcore:entity.bossdeath
03.12 10:51:32 [Server] Server thread/INFO [FML]: Registry SoundEvent: Found a missing id from the world galacticraftcore:entity.slime_death
03.12 10:51:32 [Server] Server thread/INFO [FML]: Registry SoundEvent: Found a missing id from the world galacticraftcore:entity.ooh
03.12 10:51:32 [Server] Server thread/INFO [FML]: Registry SoundEvent: Found a missing id from the world galacticraftcore:entity.astrominer
03.12 10:51:32 [Server] Server thread/INFO [FML]: Registry SoundEvent: Found a missing id from the world galacticraftcore:entity.ouch
03.12 10:51:32 [Server] Server thread/INFO [FML]: Registry SoundEvent: Found a missing id from the world galacticraftcore:block.deconstructor
03.12 10:51:32 [Server] Server thread/ERROR [FML]: Unidentified mapping from registry minecraft:soundevents
03.12 10:51:32 [Server] Server thread/ERROR [FML]:     galacticraftcore:player.parachute: 745
03.12 10:51:32 [Server] Server thread/ERROR [FML]:     galacticraftcore:entity.bossdeath: 738
03.12 10:51:32 [Server] Server thread/ERROR [FML]:     galacticraftcore:entity.bosslaugh: 739

Hope you can help me

**Comment by ROMVoid95** [comment]
"Potentially Dangerous alternative prefix" is one of the most common and normal things to see in any console or log. 

any type of "Found a missing id from the world" indicates the current world that is loading has "stuff" from mods that either: 

- existed in a previous versions of the mod but is not in the current version
- still exists but changed the name

or you simply do not have the mod installed.

**Comment by MJRLegends** [comment]
RomVoid95 thats not what this error means

**Comment by ROMVoid95** [comment]
k

**Comment by radfast** [comment]
@Antoniopf25 are you able to play the game?  I mean, are you **only** reporting errors in logs?  Some errors in logs are normal - or at least don't cause any major problems.

**Comment by MJRLegends** [comment]
Yea he should be able to play perfectly fine with them errors reporting to the log
