### ISSUE TITLE
[issue] Where is the Galacticraft v220?

### ISSUE THREAD

**Issue by Eliicopter** [micdoodle8/Galacticraft#3843]
![Micdoodle8 - Galacticraft Download - Mozilla Firefox 07 12 2019 22_07_21 (2)_LI](https://user-images.githubusercontent.com/58640656/70380598-281edf00-193e-11ea-8d81-e5fed99e4c63.jpg)

so 210 is there but i cant see any 220 pls help!!
![Micdoodle8 - Galacticraft Download - Mozilla Firefox 07 12 2019 22_07_21 (2)_LI](https://user-images.githubusercontent.com/58640656/70380610-48e73480-193e-11ea-9956-6958cb785edf.jpg)

**Comment by MJRLegends** [comment]
Probably a failed build meaning build 221 so probably same as 220

**Comment by dj3520** [comment]
Checked the jenkins and 220 failed to compile. So it doesn't exist. But there were apparently no changes between 220 and 221, so what Legends said is likely the case.

**Comment by radfast** [comment]
The more interesting question is why are you trying to get Galacticraft version 220?   You should use the current version.
