### ISSUE TITLE
Couldn't load advancement galacticraftcore:xxx

### ISSUE THREAD

**Issue by zerisius** [micdoodle8/Galacticraft#3844]
Minecraft version: 1.12.2
Galacticraft version: 1.12.2-4.0.2.238
Multiplayer (SMP): spongeforge-1.12.2-2838-7.1.8-RC3962
Galacticraft add-ons installed: ExtraPlanets-1.12.2-0.5.9

so this happens whenever i start my local server:
https://gist.github.com/zerisius/3327514ad9be7dc74b9cf472158ae012

**Comment by marcus8448** [comment]
#3828 + #3844
