### ISSUE TITLE
Galacticraft Core causes Minecraft to fail to start (crash)

### ISSUE THREAD

**Issue by SpencerMeow** [micdoodle8/Galacticraft#3846]
Minecraft version: 1.12.2
Galacticraft version: 4.02.238

Using galacticraft planets, extra planets, more planets.

Know a fix?
https://paste.dimdev.org/uhefekidoh.mccrash

**Comment by marcus8448** [comment]
You have so many mods, Minecraft has run out of id's. Please either remove some mods or add [JustEnoughIds](https://www.curseforge.com/minecraft/mc-mods/jeid).

**Comment by radfast** [comment]
Thank you @marcus8448  :)
