### ISSUE TITLE
Game crashes when parachest loads

### ISSUE THREAD

**Issue by WatanabeAndy** [micdoodle8/Galacticraft#3847]
Minecraft version:1.12.2
Galacticraft version:4.0.2.238
forge:1.12.2-14.23.5.2847

It happened at SMP and SSP.

Here are the crash reprot:

---- Minecraft Crash Report ----
// Don't do that.

Time: 2019-12-11 23:32:42 CST
Description: Ticking entity

java.lang.NoSuchFieldError: stacks
    at micdoodle8.mods.galacticraft.core.entities.EntityParachest.placeChest(EntityParachest.java:141)
    at micdoodle8.mods.galacticraft.core.entities.EntityParachest.onUpdate(EntityParachest.java:98)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1993)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1955)
    at net.minecraft.world.World.redirect$updateEntity$zzj000(World.java:4117)
    at net.minecraft.world.World.updateEntities(World.java:1759)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
  Entity Type: galacticraftcore:para_chest (micdoodle8.mods.galacticraft.core.entities.EntityParachest)
  Entity ID: 1550680
  Entity Name: Parachest
  Entity's Exact location: -1672.73, 96.00, 3932.10
  Entity's Block location: World: (-1673,96,3932), Chunk: (at 7,6,12 in -105,245; contains blocks -1680,0,3920 to -1665,255,3935), Region: (-4,7; contains chunks -128,224 to -97,255, blocks -2048,0,3584 to -1537,255,4095)
  Entity's Momentum: 0.00, 0.00, 0.00
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {Motion:[0.0d,0.0d,0.0d],placedChest:0b,color:15,UUIDLeast:-5260131370523616159L,CargoLength:2,Invulnerable:0b,Air:300s,OnGround:1b,Dimension:0,PortalCooldown:0,Rotation:[0.0f,0.0f],UpdateBlocked:0b,FallDistance:0.0f,FuelLevel:606,UUIDMost:1853206046515150928L,Pos:[-1672.7343162659215d,96.0d,3932.100611816554d],Fire:-1s,Items:[{Slot:0b,id:"galacticraftcore:landing_pad",Count:9b,Damage:0s},{Slot:1b,id:"galacticraftcore:rocket_t1",Count:1b,Damage:0s}]}

-- Affected level --
  Level name: world
  All players: 2 total; [GCEntityPlayerMP['Electro_Master'/1519249, l='world', x=-1668.27, y=96.00, z=3935.55], GCEntityPlayerMP['Watanabe_Andy'/1409149, l='world', x=-1605.84, y=95.00, z=3958.08]]
  Chunk stats: ServerChunkCache: 1066 Drop: 0
  Level seed: 8876791207956294561
  Level generator: ID 00 - default, ver 1. Features enabled: true
  Level generator options: 
  Level spawn location: World: (166,65,353), Chunk: (at 6,4,1 in 10,22; contains blocks 160,0,352 to 175,255,367), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 4793691 game time, 4793691 day time
  Level dimension: 0
  Level storage version: 0x04ABD - Anvil
  Level weather: Rain time: 99924 (now: false), thunder time: 61218 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Linux (amd64) version 2.6.32-754.el6.x86_64
  Java Version: 1.8.0_202, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 4280693400 bytes (4082 MB) / 6222249984 bytes (5934 MB) up to 6222249984 bytes (5934 MB)
  JVM Flags: 2 total; -Xmx6000M -Xms6000M
  IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
  FML: MCP 9.42 Powered by Forge 14.23.5.2808 35 mods loaded, 35 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                            | Version              | Source                                            | Signature                                |
       |:------ |:----------------------------- |:-------------------- |:------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                     | 1.12.2               | minecraft.jar                                     | None                                     |
       | LCHIJA | mcp                           | 9.42                 | minecraft.jar                                     | None                                     |
       | LCHIJA | FML                           | 8.0.99.99            | iserver.jar                                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                         | 14.23.5.2808         | iserver.jar                                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | anothercommonbugfix           | 1.0.7                | minecraft.jar                                     | None                                     |
       | LCHIJA | micdoodlecore                 |                      | minecraft.jar                                     | None                                     |
       | LCHIJA | foamfixcore                   | 7.7.4                | minecraft.jar                                     | None                                     |
       | LCHIJA | foamfix                       | 0.10.9-1.12.2        | -优化foamfix-0.10.9-1.12.2.jar                      | None                                     |
       | LCHIJA | journeymap                    | 1.12.2-5.5.2         | -地图journeymap-1.12.2-5.5.2.jar                    | None                                     |
       | LCHIJA | inventorytweaks               | 1.64+dev.146.2180b27 | -整理InventoryTweaks-1.64+dev.146.jar               | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCHIJA | ic2                           | 2.8.109-ex112        | industrialcraft-2-2.8.109-ex112.jar               | de041f9f6187debbc77034a344134053277aa3b0 |
       | LCHIJA | advanced_solar_panels         | 4.3.0                | Advanced+Solar+Panels-4.3.0.jar                   | None                                     |
       | LCHIJA | galacticraftcore              | 4.0.2.238            | GalacticraftCore-1.12.2-4.0.2.238.jar             | None                                     |
       | LCHIJA | armourers_workshop            | 1.12.2-0.49.1        | Armourers-Workshop-1.12.2-0.49.1.jar              | None                                     |
       | LCHIJA | forgelin                      | 1.8.4                | 刻前Forgelin-1.8.4.jar                              | None                                     |
       | LCHIJA | betterrecords                 | 1.12.2-1.6.1         | BetterRecords-1.12.2-1.6.1.jar                    | None                                     |
       | LCHIJA | chinjufumod                   | 3.2.2                | ChinjufuMod[1.12.2]3.2.2.jar                      | None                                     |
       | LCHIJA | crafttweaker                  | 4.1.20               | CraftTweaker2-1.12-4.1.20.jar                     | None                                     |
       | LCHIJA | jei                           | 4.13.1.220           | jei_1.12.2-4.13.1.220.jar                         | None                                     |
       | LCHIJA | crafttweakerjei               | 2.0.3                | CraftTweaker2-1.12-4.1.20.jar                     | None                                     |
       | LCHIJA | cucumber                      | 1.1.3                | Cucumber-1.12.2-1.1.3.jar                         | None                                     |
       | LCHIJA | galacticraftplanets           | 4.0.2.238            | Galacticraft-Planets-1.12.2-4.0.2.238.jar         | None                                     |
       | LCHIJA | mjrlegendslib                 | 1.12.2-1.1.9         | MJRLegendsLib-1.12.2-1.1.9.jar                    | b02331787272ec3515ebe63ecdeea0d746653468 |
       | LCHIJA | extraplanets                  | 1.12.2-0.6.0         | ExtraPlanets-1.12.2-0.6.0.jar                     | b02331787272ec3515ebe63ecdeea0d746653468 |
       | LCHIJA | galacticrafttweaker           | 1.12.2-1.0.3         | GalacticraftTweaker-1.12.2-1.0.3.jar              | b02331787272ec3515ebe63ecdeea0d746653468 |
       | LCHIJA | mysticalagriculture           | 1.7.5                | MysticalAgriculture-1.12.2-1.7.5.jar              | None                                     |
       | LCHIJA | mysticalagradditions          | 1.3.2                | MysticalAgradditions-1.12.2-1.3.2.jar             | None                                     |
       | LCHIJA | oreexcavation                 | 1.4.143              | OreExcavation-1.4.143.jar                         | None                                     |
       | LCHIJA | planetprogression             | 1.12.2-0.3.8         | PlanetProgression-1.12.2-0.3.8.jar                | b02331787272ec3515ebe63ecdeea0d746653468 |
       | LCHIJA | spedosketeleportationcommands | 0.7                  | TeleportationCommands-0.7.jar                     | None                                     |
       | LCHIJA | treechopper                   | 1.2.4                | TreeChopper-1.12.2-1.2.4.jar                      | None                                     |
       | LCHIJA | vanillafix                    | 1.0.10-SNAPSHOT      | VanillaFix-1.0.10-99.jar                          | None                                     |
       | LCHIJA | cfm                           | 6.3.1                | 家具furniture-6.3.1-1.12.2.jar                      | None                                     |
       | LCHIJA | compactsolars                 | 1.12.2-5.0.18.341    | 工业高太CompactSolars-1.12.2-5.0.18.341-universal.jar | None                                     |
       | LCHIJA | gokistats                     | @version@            | 技能gokiStats-1.2.5.1.jar                           | None                                     |
  Loaded coremods (and transformers): ForgelinPlugin (刻前Forgelin-1.8.4.jar)
                                        
                                      CustomSkinLoader (CustomSkinLoader_Forge-14.10a.jar)
                                        customskinloader.forge.loader.LaunchWrapper
                                      Inventory Tweaks Coremod (-整理InventoryTweaks-1.64+dev.146.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (-优化foamfix-0.10.9-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      AnotherCommonBugFix (AnotherCommonBugFix-1.0.7-1.12.2.jar)
                                        com.anotherera.core.ACBFClassTransformer
                                      MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.238.jar)
                                        micdoodle8.mods.miccore.MicdoodleTransformer
  Suspected Mods: Galacticraft Core (galacticraftcore)
  Profiler Position: N/A (disabled)
  Player Count: 2 / 40; [GCEntityPlayerMP['Watanabe_Andy'/1409149, l='world', x=-1605.84, y=95.00, z=3958.08], GCEntityPlayerMP['Electro_Master'/1519249, l='world', x=-1668.27, y=96.00, z=3935.55]]
  Is Modded: Definitely; Server brand changed to 'fml,forge'
  Type: Dedicated Server (map_server.txt)

**Comment by marcus8448** [comment]
Bug in the mod anothercommonbugfix. See #3808

**Comment by WatanabeAndy** [comment]
> 在mod anothercommonbugfix中的错误。参见[＃3808](https://github.com/micdoodle8/Galacticraft/issues/3808)

Thank you so much,  it works after I delete the mod. The outdated mod fixing bug made the bug. Maybe we should tell the mod auther about this bug. Thank you for your help.
