### ISSUE TITLE
Crash from turret

### ISSUE THREAD

**Issue by caribhunt** [micdoodle8/Galacticraft#3849]
Minecraft version: 1.12.2
Galacticraft version: 237

SMP, Tablecloth

Addons: GalaxySpace only

Placed a turret, then the server crashed. After, if you look on it or just close to it, server also crashes. My hoster reboots the vds after that particular event. WorldEdit, Minecraft commands and block breakers from mods can't remove it. Successfully deleted only by an explosion.

https://pastebin.com/CysCzqD5

**Comment by marcus8448** [comment]
Already fixed - See #3807 & #3795 
Update Galacticraft to `.238+`
