### ISSUE TITLE
Immediate disconnect from server when going to planets 

### ISSUE THREAD

**Issue by ShadowRocks2** [micdoodle8/Galacticraft#3851]
Minecraft version: 1.12.2
Galacticraft version: 4.0.2.215

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SMP
No plugins
No addons

> [17:07:23] [Server thread/INFO] [FML]: Loading dimension -30 (FTB) (net.minecraft.server.dedicated.DedicatedServer@29a1ef32)
> [17:07:23] [Server thread/INFO] [FML]: Loading dimension -29 (FTB) (net.minecraft.server.dedicated.DedicatedServer@29a1ef32)
> [17:07:23] [Server thread/INFO] [FML]: Loading dimension -31 (FTB) (net.minecraft.server.dedicated.DedicatedServer@29a1ef32)
> [17:07:35] [Server thread/INFO] [Galacticraft]: Found matching world (-28) for name: moon.moon
> [17:07:35] [Server thread/INFO] [Galacticraft]: Server attempting to transfer player ShadowRocks2 to dimension -28
> [17:07:35] [Server thread/INFO] [minecraft/DedicatedServer]: ShadowRocks2 has reached the goal [Galacticraft]
> [17:07:38] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 2875ms behind, skipping 57 tick(s)
> [17:07:51] [Server thread/INFO] [minecraft/NetHandlerPlayServer]: ShadowRocks2 lost connection: Timed out
> [17:07:51] [Server thread/INFO] [minecraft/DedicatedServer]: ShadowRocks2 left the game
> [17:07:51] [Server thread/WARN] [minecraft/NetworkManager]: handleDisconnection() called twice

EDIT: when it does this im stuck on taking one small step loading screen and have to restart game

**Comment by radfast** [comment]
The most likely cause of this is different Galacticraft versions installed on the player (client) and the server.

On both the server and the client, please update Galacticraft to the latest version .239 or later, from the [official download site](https://micdoodle8.com/mods/galacticraft/downloads).

If the issue still occurs with both the server and the client on version .239, please re-open this.
