### ISSUE TITLE
PO3 - crashes when loading a new planet with extraplanets

### ISSUE THREAD

**Issue by dokodCZ** [micdoodle8/Galacticraft#3853]
Minecraft version: 1.12.2
Galacticraft version: 4.0.2.237

OPENED TO LAN

Any Galacticraft add-ons installed? please list all
ExtraPlanets 0.5.6
Galacticraft planets
Galacticraft tweaker

When going to a new planet , server stops and the screen is stucked on "Taking one small step" - I have to restart client. 
 
log: 
[2019-12-30-1.log](https://github.com/micdoodle8/Galacticraft/files/4009829/2019-12-30-1.log)

log from VanillaFix : https://paste.dimdev.org/kaqamejufi.mccrash

**Comment by MJRLegends** [comment]
Update ExtraPlanets and MJRLegendsLib and Galacticraft and your issue will be fixed

While your there do it for all your other mods too so others don't get issue reports for older versions

**Comment by MJRLegends** [comment]
You probably are just using a old mod pack version
