### ISSUE TITLE
Random crashes in client with TileEntityScreen

### ISSUE THREAD

**Issue by Kissune** [micdoodle8/Galacticraft#3854]
REVIEW THE GUIDELINES - see [Contributing](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) link on right side.
Even though this isn't the latest version, I looked at the changelog for the build above this one, and it doesn't really look like it would fix whatever was causing this. This crash occurs just... Randomly. Whenever I'm doing anything. Mining, walking around, whatever. Haven't tried on other planets, this is just an overworld problem. Sometimes it takes 30 seconds to crash, sometimes 15 minutes. But these crash logs are all from 4 sequential crashes.

Minecraft version: 1.12.2
Galacticraft version: 4.0.2.238

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
- If SMP server, please mention if it has **Sponge**, AtomMC, BukkitForge, BungeeCord etc.
SMP, no extra addons like sponge.

Any Galacticraft add-ons installed? please list all
ExtraPlanets

Please provide screenshots / crash report / log / full modlist as needed

[crash-2019-12-31_19.46.11-client.txt](https://github.com/micdoodle8/Galacticraft/files/4013800/crash-2019-12-31_19.46.11-client.txt)
[crash-2019-12-31_20.13.35-client.txt](https://github.com/micdoodle8/Galacticraft/files/4013801/crash-2019-12-31_20.13.35-client.txt)
[crash-2019-12-31_20.24.14-client.txt](https://github.com/micdoodle8/Galacticraft/files/4013802/crash-2019-12-31_20.24.14-client.txt)
[crash-2019-12-31_21.21.24-client.txt](https://github.com/micdoodle8/Galacticraft/files/4013803/crash-2019-12-31_21.21.24-client.txt)

**Comment by radfast** [comment]
Thanks for reporting.  This seems to be caused by the world state changing (maybe due to another mod or multithreaded code for performance, I'm not sure) while a Galacticraft Display Screen tile is in the middle of an update tick.

I have updated the Display Screens next build (.242) so that this should hopefully be fixed.  You will need to test it though in your setup, as the issue seems to be unique to you ...

**Comment by radfast** [comment]
You can get build .242 [here](https://ci.micdoodle8.com/job/Galacticraft-1.12/242/)
