### ISSUE TITLE
GC mobs are not displayed correctly

### ISSUE THREAD

**Issue by Romsik788** [micdoodle8/Galacticraft#3857]
REVIEW THE GUIDELINES - see [Contributing](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) link on right side.

Minecraft version:1.12.2
Galacticraft version:4.0.2.239

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
- If SMP server, please mention if it has **Sponge**, AtomMC, BukkitForge, BungeeCord etc.
SSP, SSP not opened to LAN
Any Galacticraft add-ons installed? please list all
![Безымянный](https://user-images.githubusercontent.com/33905242/71768214-d48fb900-2f1c-11ea-9db9-752e9cc6868b.png)

Please provide screenshots / crash report / log / full modlist as needed
![2020-01-03_20 51 39](https://user-images.githubusercontent.com/33905242/71768226-eec99700-2f1c-11ea-84fa-3c356e5f9ff8.png)
![2020-01-03_20 52 54](https://user-images.githubusercontent.com/33905242/71768228-ef622d80-2f1c-11ea-9f72-fb704e1b60c0.png)
![2020-01-04_11 46 05](https://user-images.githubusercontent.com/33905242/71768229-ef622d80-2f1c-11ea-931f-20d3e5b67faf.png)
![2020-01-04_15 45 08](https://user-images.githubusercontent.com/33905242/71768230-effac400-2f1c-11ea-9402-bd758d868c0e.png)
GC mobs are not displayed correctly. Maybe because of OptiFine?
If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft)

**Comment by radfast** [comment]
In case someone else finds this thread, this is intended behaviour if you wear the [Sensor Glasses](https://wiki.micdoodle8.com/wiki/Sensor_Glasses)

**Comment by QuantumStatement** [comment]
![ff](https://user-images.githubusercontent.com/33905242/71768226-eec99700-2f1c-11ea-84fa-3c356e5f9ff8.png)
I don't think such mob backlight is intended
