### ISSUE TITLE
... blocked by: Protected Area!

### ISSUE THREAD

**Issue by MikeDB-wtf** [micdoodle8/Galacticraft#3859]
Minecraft version: 1.12.2
Galacticraft version: 4.0.2.239
SSP/LAN. Sometimes opened to LAN but happens either way.
No add-ons. Was unaware of those and will now need to go look at them.
Also installed: The Betweenlands, JourneyMap, TreeCapitator, Bounding Box Reloaded. Nothing that should affect this.

Went to a clean, untouched area and set up four astro miner bases and put a miner and a creative infinite battery in each. Once the miners "woke up" and tried to move, chat was spammed with that message while the miners moved back and forth (looked like a row of pistons). Eventually, they all decided there was nothing left to mine.
![2020-01-05_09 23 50](https://user-images.githubusercontent.com/57364403/71782422-44df1e80-2f9f-11ea-97f5-77c07cf7a71a.png)

I then experimented a bit and removed the four blocks in front of each that the miner could technically fit through, replaced all the miners and they started working just fine. After they got a ways out, one returned with no apparent issues while the other three:

![2020-01-05_09 43 57](https://user-images.githubusercontent.com/57364403/71782508-43fabc80-2fa0-11ea-8f47-968ad9261d70.png)
![2020-01-05_09 44 29](https://user-images.githubusercontent.com/57364403/71782509-43fabc80-2fa0-11ea-8ec6-62ddc1ad9bb2.png)

They're just stuck and can't seem to go anywhere. Meanwhile, number 4:

![2020-01-05_09 48 41](https://user-images.githubusercontent.com/57364403/71782534-b370ac00-2fa0-11ea-9ee7-7643b787c6c6.png)

Was going to the end of the straightaway in front of its base and heading down. Now it reaches that end and turns around and goes right back.

I also very often get something like this:

![2020-01-05_10 06 16](https://user-images.githubusercontent.com/57364403/71782739-1f541400-2fa3-11ea-95cd-59a6f79a871b.png)

Whereby the miner dug down but left a couple of blocks unmined (gap is a rectangle, not a cross) and it then can't return (either Protected Area! or return route blocked).

Occasionally, it's nothing more than gravel that dropped into it's path.

In all cases, breaking a couple of the blocks in front of the miner allows it to continue even though it sometimes continues in a completely different direction.

I suspect this is a different issue even though it appears to be related in that they only appear together. If some miners are incorrectly claiming "Protected Area!", then all the bases' inventories look like this:

![2020-01-05_09 47 44](https://user-images.githubusercontent.com/57364403/71782569-2e39c700-2fa1-11ea-8737-e3eda6b0bf27.png)

**Comment by radfast** [comment]
Thanks for reporting.  We can do something about the spam messages.

The cause of the "Protected Area" message is that Forge is preventing block breaking - so it thinks the player who owns the Astro Miner would be unable to break that particular block.  The usual reason for this is that the server is using some kind of anti-griefing plugin or factions plugin.

You didn't say if you are using Sponge or other server tools, or any plugins.  If you are not using server plugins, then the most likely explanation is one of your other mods has this type of functionality.  Maybe you know which one?

----

The add-ons for Galacticraft are pretty interesting, the most played in 1.12.2 are Extra Planets by @MJRLegends and More Planets by @SteveKunG.   For a fuller list, see the [forum](https://forum.micdoodle8.com/index.php?forums/addons-and-resource-packs.11/).    There's also a nice texture pack by @EzerArch and he made some [compatibility configs](https://forum.micdoodle8.com/index.php?threads/dynamic-surroundings-config-files-for-galacticraft.6639/) for the audio mod Dynamic Surroundings and other customisations.  There is also an awesome [SpaceX add-on](https://www.curseforge.com/minecraft/mc-mods/spacecraftx), though I haven't recently checked whether it is fully updated for the latest Galacticraft - hopefully it should be OK, we try not to make changes which breaks add-ons.

**Comment by MikeDB-wtf** [comment]
Very sorry about the long delay, I completely missed the email saying there was a response!

Doesn't SSP indicate Sponge and family aren't involved? (I honestly don't know) I am using the "normal" client/server software (MinecraftLauncher.exe and minecraft.jar). All mods (except that I missed Optifine) are listed in the OP; none have any such blocking ability.

I discovered similar behaviour if/when it encounters multi-blocks but I assume that's intended (either by Forge or GC).

I will attempt to recheck after removing extraneous mods tomorrow.

Regarding AM base inventory: I wasn't clear. The inventories don't match, I was referring to the way the UI is layed out. I did, however, figure out that one was caused by being in spectator. If it's a bug to show up like that, it's not related to this one.

SpacecraftX has not been updated since July 2018. I have no earthly idea yet if it still works, though. I will have to look into at least some of those addons when I get time.

**Comment by MikeDB-wtf** [comment]
Alright. Started a brand new map and switched to creative. Found an area relatively void of caves, lava, water, etc. Grabbed enough material to set up six astro miner bases. Within two minutes I got a short burst of "protected area" and "route blocked" messages and went looking for the culprit. I found this:

![2020-02-10_06 28 32](https://user-images.githubusercontent.com/57364403/74150385-6d29f080-4bcf-11ea-94dc-2b25ac7aafd7.png)

I then shut down and stripped the mods folder:

![Empty Mods Folder](https://user-images.githubusercontent.com/57364403/74150576-cf82f100-4bcf-11ea-950f-039b95686897.jpg)

Luckily for seeing what's going on, MC has no reason to update the brightness values in it's config yet since Gammabright boosted them.

Shortly after reloading, I received this, presumably related to the above pictured miner:

![2020-02-10_06 41 40](https://user-images.githubusercontent.com/57364403/74150993-ca727180-4bd0-11ea-804c-3f98dd35421d.png)

I then received a burst of just "protected area" messages and found these three:

![2020-02-10_06 42 20](https://user-images.githubusercontent.com/57364403/74151135-17564800-4bd1-11ea-8c18-027eaae73e0d.png)

( I don't know how easy it is to see, but there are no special blocks there)

Next, I shut down, deleted and created a new world and tried again:

![2020-02-10_06 55 18](https://user-images.githubusercontent.com/57364403/74151704-5fc23580-4bd2-11ea-8967-91207ef62f59.png)

The top two are attempting to return, the bottom two are not. All four are hung up.

**Comment by MikeDB-wtf** [comment]
Probably unrelated but just in case:

In this picture, you can see the final two miners. Both have decided the area is empty and there's nothing left to do. The one on the left has clearly not even made it's runout (the straight stretch before the miner starts changing direction). The one on the right might have finished it's runout, I'm not sure how long it is, but never switched directions; only out and back.

![2020-02-10_07 13 06](https://user-images.githubusercontent.com/57364403/74153002-2808bd00-4bd5-11ea-9646-f143cd94529e.png)

After typing this and before posting, I went and looked at the game again.  The two returning and one stuck one all "suddenly" broke through whatever the problem was and continued. I then went down to the one remaining and stood there waiting. Sure enough, on it's next attempt, it also broke through and continued.

I have a theory. Astrominer code does not like the only player being in spectator. I shouldn't think this would be an issue since tests in the asteroid belt show them willing to go up to 32 chunks away, which is four times my render in the belt and far outside the area loaded around the player.

**Comment by dj3520** [comment]
Small heads up, SSP means survival single player (or some equivalent.) Indicates nothing about Sponge usage. At least to my knowledge.

**Comment by TheQuadShot** [comment]
correct, Survival Single Player and Survival Multi-Player as per the Minecraft Wiki

**Comment by MikeDB-wtf** [comment]
Yes, Survival Single Player. Isn't Sponge a multiplayer server?

**Comment by dj3520** [comment]
Ah, I hadn't thought of that.

**Comment by radfast** [comment]
Thanks for the further detailed reports and screenshots.  I will test this in my game when I have time, and try to figure out what's going on here....

(The reason I asked about Sponge etc is because you said you sometimes opened up your SSP game to LAN.  LAN is multiplayer, so I guess you could have Sponge installed for that, to have a few server-side plugins.  The AstroMiner would certainly report "Protected Area" if a server plugin - Factions, for example - would prevent the player from breaking blocks.)

Hmm, one thought, it could be a protected spawn area?   Do you have the x,y,z co-ordinates of where the miner is?

**Comment by radfast** [comment]
>   I have a theory. Astrominer code does not like the only player being in spectator.

I don't know, I didn't test this.  The AstroMiner should move if its owning player is online, and otherwise it should be inert, and unmovable and unbreakable.

**Comment by MikeDB-wtf** [comment]
Curious, can one use the vanilla launcher and jar for SSP and have it switch to Sponge, et al, for SMP? Not relevant here, just an odd thought.

No spawn protection relevant here as most of my tests have had me put them down without me moving away from the initial spawn and they could be blocked immediately (before they can get out) or, in a couple of cases, hundreds of blocks away.

New theory: Astrominer shares player's "permissions" and a player in spectator cannot break blocks. After all, in spectator, I cannot open chests that haven't already been opened and cannot even manipulate my own inventory. It stands to reason that I wouldn't be able to break blocks so the Astrominer can't either.

It might be less of an "intended behaviour" and more of a "side effect of how Minecraft works so there's nothing to be done". The end result would be that it might not be fixable but you could detect the player's gamemode and adjust the warning accordingly; Perhaps even make them just shut down similarly to when the player goes offline.

**Comment by sebastiaoLa** [comment]
I know this is an old issue but I just spent the last hour searching for this

For anyone that finds this thread, double check that you are not in spectator mode, at least for me that was the issue
