### ISSUE TITLE
Can't create space station or go to an already created one.

### ISSUE THREAD

**Issue by xBitey** [micdoodle8/Galacticraft#3861]
I am not able to create a new space station after flying to the Planet Selection Screen even though I previously could. I already had a space station and one day it decided to disappear. While looking at my files I discovered that the only way I can go to this station is by doing the command, /tpx xBitey 99. This means the station is in dimension 99. Any hints on how to fix these issues. By the way I play on Mac.
![Screen Shot 2020-01-06 at 3 38 05 pm](https://user-images.githubusercontent.com/59551218/71797575-8c96a080-309a-11ea-9a15-533f6eda7ee4.jpg)

Minecraft version: 1.12.2
Galacticraft version: 4.0.2.239

SSP opened to LAN (LAN)

**Comment by xBitey** [comment]
I think it might be because of the mod Advanced Rocketry.

**Comment by dj3520** [comment]
If you remove Advanced Rocketry does the issue persist? (Ensure to back up
your world before testing.)

**Comment by xBitey** [comment]
Actually I did a test on a test world with the same mods, did /dimensiontp and I was able to create a Space Station. Therefore, the mods aren't the problem the world I normally play is the problem.

**Comment by xBitey** [comment]
You wouldn't believe how I fixed it but it turns out that the solution was to simply invite myself to my own space station. This is done by doing /ssinvite [Player]

**Comment by radfast** [comment]
@xBitey glad you fixed it.  The game should not normally require you to invite yourself.  To put it another way, when you create a space station the game automatically gives you an invitation to your own space station - of course!

I guess something could have changed in a rare situation.  Possible causes:
- corruption in a .dat data file - any file can be corrupted if the game crashes while writing a file, or if your PC runs out of battery at that exact moment, or similar
- or it could be that one time in a billion when a memory chip or hard drive flips a bit.  (Maybe more likely if your PC is running too hot?  Gaming can make PCs too hot.  I recommend every gamer should constantly monitor hard drive temperatures using a tool like [OpenHardwareMonitor](https://openhardwaremonitor.org/).
- or another mod changed something in a Galacticraft data file - unlikely, but perhaps possible if another mod has a file with the exact same name (I don't know of any)
