### ISSUE TITLE
Pre-Launch Checklist order is wrong

### ISSUE THREAD

**Issue by xJon** [micdoodle8/Galacticraft#3863]
It doesn't start with the moon and goes in order?

Minecraft version: `1.12.2`
Galacticraft version: `4.0.2.243`

Single player (SSP)

Any Galacticraft add-ons installed? `ExtraPlanets, PlanetProgression`

Please provide screenshots / crash report / log / full modlist as needed
![bug](https://user-images.githubusercontent.com/8945347/72907020-ddb1c000-3d3b-11ea-866a-0872b701fc82.gif)

**Comment by MJRLegends** [comment]
Yea the Pre-Launch Checklist is badly laid out

**Comment by xJon** [comment]
@MJRLegends I want to redirect players to an in-game information source so they know to use a space suit along with other space equipment
![Screenshot_4](https://user-images.githubusercontent.com/8945347/72907949-709f2a00-3d3d-11ea-9766-3e1f98a10655.png)
I just wish the checklist was better

**Comment by TheQuadShot** [comment]
Sorry, just my 2 cents worth... How can a "Check list" be out of order? Especially since they can be equipped in any order; at that point (imho) it's purely subjective.

**Comment by MJRLegends** [comment]
Its out if any logical order. Hes correct with saying that

**Comment by xJon** [comment]
Yeah, one can only go to Mars after going to the Moon, so the checklist should be in order of gameplay tiers.

**Comment by TheQuadShot** [comment]
@xJon Ah! That I understand, I wasn't addressing the "lay out" or the order of the planets. Sorry I wasn't clear with my comment.

**Comment by xJon** [comment]
@TheQuadShot Yeah, my only complaint is the order of the planets.

**Comment by MJRLegends** [comment]
I might have a pull request later with a ordering sort fix
