### ISSUE TITLE
I can't go into space (Or i can't go back or the universe is very bugged)

### ISSUE THREAD

**Issue by bartcreator** [micdoodle8/Galacticraft#3868]
Minecraft version: 1.12.2
Galacticraft version: 1.12.2-4.0.2.243 plus ExtraPlanets 1.12.2-0.6.2

Single player (SSP), Multiplayer (SMP)

Forge 14.23.5.2847

Issue: I've got alot problems with Galacticraft and addon ExtraPlanets.
I've got problems i with rocket start up, if i start i go infinity thru the sky.
If it will finnaly open the map of the universe, i can choose planet and everything looks normal, but if i want to go back on Earth, i can only see an infinity loading screen.
If i shut the game, there is sometimes a crush screen or nothing, just a launcher.
PS: Im using TLauncher

Mods:
[1.12]bspkrsCore-universal-7.6.0.1
[1.12]TreeCapitator-client-1.43.0
BetterFoliage-MC1.12-2.3.1
betternether-0.1.8.6
BiomesOPlenty-1.12.2-7.0.1.2444-universal
ChocolateQuestRepoured-1.12.2-1.5.2A
CodeChickenLib-1.12.2-3.2.3.358-universal
CoralReef-2.5-1.12.2
CustomMobSpawner-3.11.5
DrZharks MoCreatures Mod-12.0.5
DynamicLights-1.12.2
ExtraPlanets-1.12.2-0.6.2
Forgelin-1.8.4
furniture-6.3.1-1.12.2
GalacticraftCore-1.12.2-4.0.2.243
Galacticraft-Planets-1.12.2-4.0.2.243
gravestone-1.10.3
guns-0.15.3-1.12.2
inventorypets-1.12-2.0.3
InventoryTweaks-1.64%2Bdev.150
jei_1.12.2-4.15.0.293
journeymap-1.12.2-5.5.6
MicdoodleCore-1.12.2-4.0.2.243
MJRLegendsLib-1.12.2-1.1.9
NotEnoughItems-1.12.2-2.4.3.245-universal
obfuscate-0.2.6-1.12.2
OptiFine_1.12.2_HD_U_F5
Pam's HarvestCraft 1.12.2z
Reforged-0.7.5-1.12+
RoguelikeDungeons-1.12.2-1.8.0
tlskincape1.12.2-1.4
TravellersBackpack-1.12.2-1.0.20.20
twilightforest-1.12.2-3.10.1013-universal

**Comment by MJRLegends** [comment]
Probably best to post your log files

**Comment by bartcreator** [comment]
How can i do it?
When i open them with Notepad there are weird signs and words

**Comment by bartcreator** [comment]
[latest.log](https://github.com/micdoodle8/Galacticraft/files/4118732/latest.log)

Is it good?

**Comment by bartcreator** [comment]
Update 

I repaired it by my self. All i had to was removing deactivated mods.
