### ISSUE TITLE
Server dimensions crash ID -30

### ISSUE THREAD

**Issue by knorst** [micdoodle8/Galacticraft#3874]
The server works and now is giving this problem of dimension ID.

I look on internet and appears to be an invalid ID, checking the core.conf this ID is not present...

The crash report: https://pastebin.com/WYuirxyN

The LOG is this: https://pastebin.com/6hYVx6G6

Any idea?

**Comment by ROMVoid95** [comment]
-30 is the dimension ID for the Asteroids dimension in `planets.conf`

**Comment by radfast** [comment]
One of your other mods must be creating a non-standard dimensions set-up.  It's hard for us to tell which without seeing all your mods and all their configs.

Most likely JustEnoughDimensions - try removing that?

> I look on internet 

lol?   If that's coming from a forum, maybe post that their answers are wrong?

**Comment by knorst** [comment]
Thanks for the reply.

The one is crashing is the "appliedenergistics2". I don't found in the cfg file a way to change the dimensions.

JustEnoughDimensions was an atempt to solve this crash lol

**Comment by radfast** [comment]
Galacticraft should be compatible with AppliedEnergistics2, I have tested it myself.

If you paste up your "appliedenergistics2" crash report I can take a look.

Best is to test with **only these two mods installed** (Galacticraft and AE2) and see if you still have the same crash.
