### ISSUE TITLE
The stupid fatal error

### ISSUE THREAD

**Issue by ZgameZ129** [micdoodle8/Galacticraft#3877]
Ok, this fatal error is making me mad. I have a screenshot. This is a multiplayer fatal error. I'm not even in singleplayer!

![2020-02-08 (4)](https://user-images.githubusercontent.com/52746484/74081626-2f5b8980-4a62-11ea-8e4f-882a11afd179.png)

This happens when i join one of my worlds.

**Comment by radfast** [comment]
There's nothing here to show this is even a Galacticraft issue!

Please complete the issue report in full.  There's a template for a reason.

In this case, before anyone can help you, you will need to provide server and client logs covering the time when this happened.  Again, the game makes logs for a reason....  If you don't know how to find those logs, maybe ask for basic help on one of the many Minecraft forums?

I am closing this for now, we can re-open if you provide the necessary information.
