### ISSUE TITLE
GC 2-3 incompatibility with Animated Player mod

### ISSUE THREAD

**Issue by SpwnX** [micdoodle8/Galacticraft#388]
Animated player is a mod which adds realistic movement to the player : http://www.minecraftforum.net/topic/1768057-172aesthetic-animated-player-rounded-curves-v141/
After adding GC to the modpack, it simply stops working and we get vanilla animations.

Example (when the animated player mod is working [without GC]):
![2014-05-16_19 49 00](https://cloud.githubusercontent.com/assets/2791175/3003541/e771ec1a-dd55-11e3-95f8-2f8b2ae78c47.png)
![2014-05-16_19 49 31](https://cloud.githubusercontent.com/assets/2791175/3003542/e78b0ee8-dd55-11e3-9e76-704147d1a0ad.png)
Now when it doesnt work :
![2014-05-16_20 03 33](https://cloud.githubusercontent.com/assets/2791175/3003555/cdbe3700-dd56-11e3-8392-6ed6d2ee5c7a.png)
![2014-05-12_22 30 31](https://cloud.githubusercontent.com/assets/2791175/3003546/2049d6ba-dd56-11e3-8d1c-50c65437196a.png)

This happens on both 1.6.4 and 1.7.2 versions of both mods.

Could it be the bytecode injections galacticraft does on basefiles :D ?

**Comment by Miguel1042** [comment]
I have the same problem with a similar mod, mo´bends mod. Can you change the mod to stop editing the player movements but you can also jump up in other planets?????

**Comment by Miguel1042** [comment]
what do i have to do?

**Comment by Miguel1042** [comment]
what will happen if we edit galacticraft and meke it stop editing minecraft mevements?
Sorry if my english is not perfect but i am spanish

**Comment by radfast** [comment]
> what will happen if we edit galacticraft 

Do you know Java?

2 ways to fix this:

1)  Try Mo 'Bends with __Player API 1.4__ and __Render Player API 1.2__ - like RellezSource said.

2)  If that doesn't fix it, ask the Mo 'Bends author to make his mod compatible with Player API and Render Player API.

**Comment by Miguel1042** [comment]
how can I install  Player API 1.4 and Render Player API 1.2?? I want it for a server and in a server there isn´t any bin folder

**Comment by Miguel1042** [comment]
Thank you!

**Comment by Miguel1042** [comment]
Now I have an other problem, it is not with galacticraft, but I think maybe you can help me. I installded render player API and now mobends works with galacticraft, but render player API bugged an other mod, named armourers workshop, its a great mod. You can create your own armor and sword textures and put it in your swords/armor. But when I heve installed render player API in doesnt work with the armor :(
I will be very thankful if you help me again
