### ISSUE TITLE
Mod(s) not working for my modpack

### ISSUE THREAD

**Issue by Scaldac** [micdoodle8/Galacticraft#3881]
I have twitch and i create a custom modpack (or profile they call it) and when i copy and paste the micdoodle core, galacticraft core and more planets mods into the mods folder and start the game from the launcher it crashes when i click play for "unexpected reasons" it doesn't even get to the minecraft forge loading screen. Don't confuse this post with a request for putting it on twitch i don't care about that i just want to play this mod on my custom modpack. I am using the 1.12.2 latest version for all three and using forge 14.23.5.2847

**Comment by dj3520** [comment]
Please include what version of Galacticraft, if any Galacticraft add-ons are present, and see if there's any crash logs (or logs in general.) I doubt it but if the launcher isn't even starting the game, then it's probably a problem with the launcher itself.

**Comment by Scaldac** [comment]
Sorted turns out i needed to reinstall my minecraft native launcher

**Comment by radfast** [comment]
Thanks @dj3520   :)
