### ISSUE TITLE
a little bug - torch placement with off hand

### ISSUE THREAD

**Issue by Ashoon114** [micdoodle8/Galacticraft#3882]
soo basically ive been playing around and out of the blue i noticed that if you hold your regular good old minecraft torch in your left arm it allows you to place it on the moon ( didn't check for other planets ) it glows normally, when on the other hand if you place it with your right arm the torch emits only a small source of light, figured i would report this.

**Comment by dj3520** [comment]
Normal minecraft torches are not supposed to work on the moon unless they're in oxygen. When going to the moon they're actually replaced with a similar kind of torch that looks just like a regular torch but has this modified behavior to it. You can tell if you have the Item IDs displayed. It sounds like the swap isn't happening for the offhand slot.

**Comment by radfast** [comment]
Thanks for reporting @Ashoon114  - good spot.

It shouldn't be too hard to fix.  Sorry if it breaks your immersion!
