### ISSUE TITLE
Parachest dump bug on 1.12.2

### ISSUE THREAD

**Issue by GuanCangHai6** [micdoodle8/Galacticraft#3886]
SSP/SMP
Minecraft Version:1.12.2
Forge Version:14.23.5.2838
Galacticraft Version:4.0.2.238 & 4.0.2.244

I know this issue https://github.com/micdoodle8/Galacticraft/issues/3551
But in 1.12.2 this bug reappear again.I think this bug exist in all versions.

Basically,in Overworld Space Station, where the parachest appears, there are some blocks in both y=63~255(not air), all the items in parachest will rain down.

My English is poor, I'm sorry if you don't understand what I mean

**Comment by radfast** [comment]
Your English is OK.  I understand :)

We can investigate.
