### ISSUE TITLE
NASA Workbench to accept chestWood OreDict chests

### ISSUE THREAD

**Issue by xJon** [micdoodle8/Galacticraft#3891]
Minecraft version: `1.12.2`
Galacticraft version: `.244`

Any Galacticraft add-ons installed? please list all
`ExtraPlanets`
`PlanetProgression`

Please provide screenshots / crash report / log / full modlist as needed
![Screenshot_4](https://user-images.githubusercontent.com/8945347/75181480-fa7c5180-5746-11ea-848f-b1c4c7e7f359.png)

It'd be very useful for compatibility with other mods (in this case Quark) if by default the NASA Workbench would accept any chest that is ore dict'd as `chestWood`, because currently it only supports the vanilla chest.

**Comment by micdoodle8** [comment]
Works in build 249, although for the time being you can't mix and match chestWood types in the same recipe, you have to choose one chest type or another. Thanks!
