### ISSUE TITLE
Emerging Technology compat

### ISSUE THREAD

**Issue by PlatinumFox** [micdoodle8/Galacticraft#3892]
Emerging technology adds an item called synthetic silk. this item is basically string. it works exactly like string and can be used in every recipe but it does not work as "fuel" for the grappling hook.
not sure if this is a bug report or a feature request.
also left not on emerging technology github in case this is their issue.

latests GC version
1.12.2
galaxy space installed
Single player

**Comment by MoonManModding** [comment]
Specifically in regards to the above, would it be possible to check for the "string" Ore Dictionary tag [when using the grappling hook](https://github.com/micdoodle8/Galacticraft/blob/f85e1dd5ff52ca71e3491c609fb524f270bd77fe/src/main/java/micdoodle8/mods/galacticraft/planets/asteroids/items/ItemGrappleHook.java#L71)?

Thank you ❤
