### ISSUE TITLE
Cannot use standard wrench to change spin thruster direction

### ISSUE THREAD

**Issue by Jacky10X** [micdoodle8/Galacticraft#3900]
Minecraft version: 1.12.2
Galacticraft version: Galacticraft-1.12.2-4.0.2.244

SMP: CatServer

Have no error, just cannot change the spin thruster direction by a right-click it using standard wrench but the standard wrench is decreasing the durability.
Another machine can rotate the direction.
Do I do the method wrong? or the way has changed to rotate the spin thruster?

**Comment by radfast** [comment]
Thanks for reporting, we will check.  There is not **intended** to be any change in the way to do this...

**Comment by radfast** [comment]
This is fixed, the fix will be in next build.  Thanks again for reporting, it's been something missing in 1.12 for a long time.
