### ISSUE TITLE
In 1.12.2 I can't craft Solar Dust

### ISSUE THREAD

**Issue by TeksuneStudio** [micdoodle8/Galacticraft#3904]
I can't craft Solar Dust. 

Have I not progressed far enough yet to get to it? Is it something just found later on in the game? Is there a crafting recipe that's not in JEI? 

Version 1.12.2
Addons:
GalacticraftTweaker-1.12.2-1.0.3.jar
More-Planets-1.12.2-2.1.10-GC238.jar
Galacticraft-Planets-1.12.2-4.0.2.244.jar
GalacticraftCore-1.12.2-4.0.2.244.jar

**Comment by BlesseNtumble** [comment]
It's ore on venus.

**Comment by dj3520** [comment]
If this is resolved please close the issue.

**Comment by TeksuneStudio** [comment]
Sorry about that! Closing issue.

**Comment by radfast** [comment]
I've updated the Wiki to add a page for [Solar Dust](https://wiki.micdoodle8.com/wiki/Solar_Dust).
