### ISSUE TITLE
Invalid oxygen setup in airlock when passing between 2 sealed rooms

### ISSUE THREAD

**Issue by veesusmikelheir** [micdoodle8/Galacticraft#3909]
Minecraft version: 1.12.2
Galacticraft version: 4.0.2.244

SSP

No Addons

Galacticraft Only

When using an airlock to pass between two sealed rooms with valid oxygen setups, the area in the airlock itself will count as a vacuum and cause anyone passing through it without a valid oxygen setup to take damage until the sealers recheck the seal, even though the rooms on both sides are completely sealed. 

It's the same bug outlined in this forum post: https://forum.micdoodle8.com/index.php?threads/invalid-oxygen-setup.6899/

It is still not fixed as of 244

**Comment by TheAgentRAINBOW** [comment]
Can reproduce, having the same issue. Very annoying when trying to build a space station :(

**Comment by radfast** [comment]
Thanks both.  Sorry, I can see I commented on the forum thread 2 years ago, but we forgot to open an issue here for it and so it was never fixed.  Should be an easy enough fix.

**Comment by TheAgentRAINBOW** [comment]
Just curious, you said in the forum thing the same thing would happen with torches etc.
I can see it would be simple enough to fix for airlocks but is it possible to fix for other blocks? It would probably require a seal check every time a block is broken but that might be laggy?
I had a thought. What if by default when a block is broken it becomes breathable air for a second then when the next seal check happens it can be turned into non-breathable air if it's invalid. Sorry, just spitting out ideas from my head 🙃

**Comment by radfast** [comment]
That's actually a great idea - codewise it can probably be implemented through `onNeighborChange` on the sealed air blocks.  I'll look into this.

**Comment by radfast** [comment]
Fixed in next build 251.

The fix is for airlocks only.   A fix for other "breathable" blocks like torches would need to be done separately.

**Comment by radfast** [comment]
OK other "breathable" blocks like torches are also now fixed.  Thank you @TheAgentRAINBOW for the suggestion.

Both fixes will be in build .251.
