### ISSUE TITLE
Hopper issue with Magnetic Crafting Table

### ISSUE THREAD

**Issue by StarchierOrb** [micdoodle8/Galacticraft#3915]
REVIEW THE GUIDELINES - see [Contributing](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) link on right side.

Minecraft version: 1.12.2
Galacticraft version: 4.0.2.244

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
- SMP  using BukkitForge(CatServer)

Any Galacticraft add-ons installed? please list all
ExtraPlanets

Please provide screenshots / crash report / log / full modlist as needed
Log:     https://paste.ubuntu.com/p/ffH4wHN6R3/
When player using hoppers to input and output item to the galacticraft machines, sometimes the hopper will not work at all . It will cause seriously lag and console will spam the error.

galacticraft machine with hopper will cause lag
spark report:https://sparkprofiler.github.io/#oBVEmmoaMF

Modlist
ImmersiveEngineering
zombieawareness
zombie_players
worldedit-forge
VariedCommodities
ToughAsNails
SpiceOfLife
SereneSeasons
pamscookables
Pam's HarvestCraft
MCA
instantunify
hostileworlds_invasions
cfm-furniture
foamfix
ExtraPlanets
MJRLegendsLib
Galacticraft-Planets
GalacticraftCore
industrialcraft
coroutil
CookingForBlockheads
BiomesOPlenty
BiblioCraft
AppleCore
aether_legacy
micdoodlecore

**Comment by radfast** [comment]
Thank you for reporting.  This appears to be an issue using a vanilla Hopper to extract items from a Magnetic Crafting Table. 

Do you have any idea what items were being crafted in the Magnetic Crafting Table when this happened?  It might help our testing.

**Comment by StarchierOrb** [comment]
Possibly caused by the oredict transform. When player try to craft Industrialcraft resources (ic2:resource) and the essential resources of immersiveengineering, their hopper somestimes not work and cause lag (TPS 20->10-)

**Comment by radfast** [comment]
I can see an IC2 Upgrade Module in that.   I'll do some testing with IC2 items and hoppers.

>   When player try to craft Industrialcraft resources (ic2:resource) and the essential resources of immersiveengineering, their hopper somestimes not work and cause lag (TPS 20->10-)

We can't do anything to help with slow code in other mods.  More than half of Minecraft mod developers, in my opinion, do not understand how to do efficient low-latency coding (or they, wrongly, don't think it's important).  Mojang is also somewhat guilty of this, since Minecraft version 1.10.  Feels like the original smart developers like Notch left the company and they hired a bunch of people fresh out of universities.

**Comment by radfast** [comment]
This seems to be lag-free and error-free in the latest Galacticraft build 250 (now available to [download](https://micdoodle8.com/mods/galacticraft/downloads)).

Using vanilla Hoppers and chests to feed items in and out of the Magnetic Crafting Table, I have auto-crafted a huge number of IC2 Upgrade Modules and all went OK :)
