### ISSUE TITLE
¿An incompability?

### ISSUE THREAD

**Issue by MoonwalkDelta27** [micdoodle8/Galacticraft#3917]
REVIEW THE GUIDELINES - see [Contributing](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) link on right side.

Minecraft version:1.12.2
Galacticraft version:Lastest

Single player (SSP)

Crash Report
https://paste.dimdev.org/yirixesaqe.mccrash

I download it from micdoodle8.com

P.S I downloaded other mods and VanillaFix says that is Galacticraft

**Comment by Gandalf360one** [comment]
The obfuscate mod cause the problem

**Comment by radfast** [comment]
Why are you reporting to us?   The crash report you posted shows a problem in Mr Crayfish / Obfuscate mod.
