### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ygabrielxd** [micdoodle8/Galacticraft#3918]
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 19/01/20 02:26
Description: Exception in server tick loop

java.lang.RuntimeException: Already decorating
	at ary.a(SourceFile:25)
	at arm.a(SourceFile:389)
	at bgv.a(SourceFile:472)
	at qs.a(SourceFile:174)
	at bfh.a(SourceFile:870)
	at qs.c(SourceFile:104)
	at net.minecraft.server.MinecraftServer.k(SourceFile:315)
	at cyk.a(IntegratedServer.java:181)
	at cyk.i(IntegratedServer.java:204)
	at net.minecraft.server.MinecraftServer.run(SourceFile:417)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 6757032 bytes (6 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 22, allocated: 13, tallocated: 95
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Very likely; Jar signature invalidated

**Comment by MJRLegends** [comment]
Most unhelpful bug report of the year congratulations

**Comment by radfast** [comment]
I don't see any connection with Galacticraft.   Also, this is in Minecraft **1.8** ?  We don't have a 1.8 version.

Closing now, we can re-open if there is any evidence this might be connected with Galacticraft.

**Comment by dj3520** [comment]
It's as if [the guidelines](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) don't even exist sometimes.
