### ISSUE TITLE
A problem for laser turret

### ISSUE THREAD

**Issue by GuanCangHai6** [micdoodle8/Galacticraft#3921]
Minecraft version:1.12.2
Galacticraft version:4.0.2.244
SSP

My tamed Slimeling was killed by the Laser Turret I placed.
I am not sure if this is intentional or just a bug.
![2020-04-04_23 56 50](https://user-images.githubusercontent.com/61133254/78455359-6c45a480-76d0-11ea-99f6-9ebad8278caf.png)

**Comment by EzerArch** [comment]
You need to add Slimeling in the whitelist.

Please follow these steps: https://wiki.micdoodle8.com/wiki/Laser_Turret#Usage

**Comment by radfast** [comment]
Thanks for reporting, this fix will be in next Galacticraft build 245 when that comes (next few days I hope).

Big thanks to @marcus8448 for the coded solution.
