### ISSUE TITLE
Turret button UI

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#3935]
Just a small UI thing: no matter if the turret is on whitelist mode or blacklist mode, the button that adds a new item always reads "Blacklist". 

![2020-04-13_19 48 44](https://user-images.githubusercontent.com/6743303/79168292-e6a4b180-7dbf-11ea-8815-1f99159c7fde.png)

For sake of simplicity, I'd change that to "Add", which fits both modes.

**Comment by micdoodle8** [comment]
Thanks Ezer!
