### ISSUE TITLE
Issue with Topography preset and Galacticraft transfer to Overworld

### ISSUE THREAD

**Issue by SebaSphere** [micdoodle8/Galacticraft#3936]
REVIEW THE GUIDELINES - see [Contributing](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) link on right side.

Minecraft version: 1.12.2
Galacticraft version: 244

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
- If SMP server, please mention if it has **Sponge**, AtomMC, BukkitForge, BungeeCord etc.
Singleplayer world
**SSP**

Any Galacticraft add-ons installed? please list all
GalaxySpace | MorePlanets

Please provide screenshots / crash report / log / full modlist as needed
![image](https://user-images.githubusercontent.com/27737877/79359084-1fec3700-7f10-11ea-82bc-7856b959287d.png)

If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft)

Whenever I try to /dimensiontp back to Earth in a topography preset, I get this crash and GC refuses to let me go to the overworld. Screen kind of freezes and I need to manually restart the game to get back to the dimension selector.

**Comment by SebaSphere** [comment]
https://bitbucket.org/bloodnbonesgaming/topography/issues/19/crash-when-trying-to-go-back-to-the

**Comment by SebaSphere** [comment]
Thanks for the quick fix (=

**Comment by micdoodle8** [comment]
Thanks Seba!
