### ISSUE TITLE
Game crash when user interacts with creative inventory.

### ISSUE THREAD

**Issue by CapturedCherry** [micdoodle8/Galacticraft#3938]
Minecraft version: 1.12.2
Galacticraft version 1.12.2-4.0.2.249

The minecraft client will crash when user interacts with the creative inventory arrows used to scroll though mods installed. 

Crash Report https://pastebin.com/dTfAs2B0

Notes:
I have tested with different versions of forge with no hope.
This crash dose not happen with Galacticraft version 1.12.2-4.0.2.244
No OptiFine, texture packs or sheaders installed

**Comment by radfast** [comment]
Fixed in build .250, now available.

Thanks for reporting - it was good to catch this one so fast.  (The cause was that we changed something which would require ExtraPlanets to update as well.)
