### ISSUE TITLE
Potential mod conflict with Adv. Rocketry relating to the oxygen system

### ISSUE THREAD

**Issue by djthekiller321** [micdoodle8/Galacticraft#3939]
REVIEW THE GUIDELINES - see [Contributing](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) link on right side.

Minecraft version:
Galacticraft version: 1.12.2  4.0.2.244

Single player

Any Galacticraft add-ons installed? Please list all of them: Galaxy Space, More Planets

Please provide screenshots / videos / full modlist as needed

Please state the site that you downloaded Galacticraft from: Micdoogle8.com
![1](https://user-images.githubusercontent.com/25395537/79622270-7356b480-80cb-11ea-9e24-138dbd3d6d01.png)
![2](https://user-images.githubusercontent.com/25395537/79622285-7e114980-80cb-11ea-9299-6e64ae24a473.png)

**Comment by djthekiller321** [comment]
with adv rocketry, on galacticraft planets, you do not need oxygen gear

**Comment by radfast** [comment]
How do you expect us to fix this?   If Advanced Rocketry changed the way our planets work, that's down to them.

I understand that players want to have lots and lots of planets to visit and things to do in space, but I don't think it's reasonable to expect the two mods to work together - there will be too many overlaps and exactly this type of issue.

**Comment by radfast** [comment]
See also #3818
