### ISSUE TITLE
Server crash on start after update

### ISSUE THREAD

**Issue by sergifs** [micdoodle8/Galacticraft#3948]
REVIEW THE GUIDELINES - see [Contributing](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) link on right side.

Minecraft version: 1.12.2
Galacticraft version: 1.12.2-4.0.2.272
Forge Version: 1.12.2-14.23.5.2847

Single player (SP), Multiplayer (MP), or SP opened to LAN (LAN)? MP

Please upload crash report / full log to [Github Gist](https://gist.github.com/) or any other paste site: https://gist.github.com/sergifs/54b72e431a98e2e4a7786edb8f064f35

Please provide screenshots / videos / full modlist as needed:
micdoodlecore
deconstruction
buildcraftlib
buildcraftcore
buildcraftfactory   
buildcrafttransport 
buildcraftsilicon   
additionalpipes     
bookshelf           
buildcraftbuilders  
buildcraftcompat    
buildcraftenergy    
buildcraftrobotics  
chameleon           
chineseworkshop     
compactmachines3    
mantle              
tconstruct          
conarm              
craftableglowstone  
deuf                
ebwizardry          
eplus               
equaldragons        
worldedit           
forgeessentials     
galacticraftcore    
galacticraftplanets 
globalxp            
jaff                
kineticclearlag     
lm                  
lunatriuscore       
mychunkloader       
valkyrielib         
simplegenerators    
stackie             
storagedrawers      
treechopper         
uteamcore           
usefulbackpacks     
universalmodifiers  
veinminer           
veinminermodsupport 
llibrary            
shetiphiancore      

Please state the site that you downloaded Galacticraft from:
https://micdoodle8.com/mods/galacticraft/downloads

I've been using the version 1.12.2-4.0.2.247 without any issues, after updating to version 1.12.2-4.0.2.272, the server crashed after finishing loading. Downgraded to the old version and started correctly.

**Comment by micdoodle8** [comment]
Should be fixed in the next build, thanks!
