### ISSUE TITLE
Download Server Down

### ISSUE THREAD

**Issue by micdoodle8** [micdoodle8/Galacticraft#3950]
This is a known issue.

For the time being download 1.12 build 272 from here:
[GalacticraftCore](https://www.dropbox.com/s/m1u2qso2zlud4o9/GalacticraftCore-1.12.2-4.0.2.272.jar?dl=0)
[GalacticraftPlanets](https://www.dropbox.com/s/xcmf3gnlbc70xvj/Galacticraft-Planets-1.12.2-4.0.2.272.jar?dl=0)
[MicdoodleCore](https://www.dropbox.com/s/4tj4vdnhdzx1j0c/MicdoodleCore-1.12.2-4.0.2.272.jar?dl=0)

**Comment by ahmedjacop68** [comment]
hi micdoodle8
