### ISSUE TITLE
[Website] Wiki is not able to be updated/edited for verified users

### ISSUE THREAD

**Issue by ROMVoid95** [micdoodle8/Galacticraft#3957]
I know this may not be the place for this, but other than the forums this is my only contact point.

EzerArch and as well as myself have been trying to get the wiki updated with more current info.
However the wiki is not able to be edited by anyone. I did notice that the forums theme changed so not sure if this is a backend issue. 

 - logged in the edit page buttons simply do not appear. 
 - the main page now has a __NOTITLE__ at the top
 - the settings drop down and profile drop down constantly appear
 - ChromeDev console shows 
```
2VM389:2 Uncaught SyntaxError: Unexpected token '<'
    at t.activateScript (rocket-loader.min.js:1)
    at rocket-loader.min.js:1
    at t.run (rocket-loader.min.js:1)
    at rocket-loader.min.js:1
    at rocket-loader.min.js:1
```

if you want to see how it looks ive attached screenshots for brevity.
![000908-05-01-20 09_52_31](https://user-images.githubusercontent.com/42848897/80814613-d0556e80-8b91-11ea-931d-e13af18cd45d.jpg)
![000909-05-01-20 09_52_43](https://user-images.githubusercontent.com/42848897/80814620-d0ee0500-8b91-11ea-99e6-753b8d113aa7.jpg)

**Comment by radfast** [comment]
Thanks @ROMVoid95  - the wiki could certainly use some updates, also images of the recently added items.

As you probably saw from the download issues people had this week, over the last few days @micdoodle8 has been updating the servers which support Galacticraft's downloads page and wiki, so I guess this could be connected with that.   I'm sure this will be fixed soon.

**Comment by micdoodle8** [comment]
Yes I updated mediawiki, still ironing out some issues. Temporary fix: If you see that blue button poking out from the edge of the dropdowns, you might be able to click on it. If you can't, you can press F12 in chrome and delete the dropdown.

**Comment by ROMVoid95** [comment]
i figured so just wanted to make sure nothing slipped past.

**Comment by micdoodle8** [comment]
Should be good now! Leave a message if there's any further issues with the wiki.
