### ISSUE TITLE
IC2 Items Don't Drop in Oxygen Sealed Rooms

### ISSUE THREAD

**Issue by 2Crispy** [micdoodle8/Galacticraft#3959]
Minecraft version: 1.12.2
Galacticraft version: 272

Multiplayer

No Galacticraft addons

Server log: https://pastebin.com/FS1U5HAm

Modlist:
alib, Baubles, BetterFps, BiblioCraft, BiomesOPlenty, Bloodmoon, Chisel, chiselsandbits, Clumps, conarm, CookingForBlockheads, coroutil, CraftStudioAPI, CraftTweaker2, CreativeCore, FastWorkbench, foamfix, Forgelin, GalacticraftCore, GalacticraftPlanets, grapplemod, gravestone, HardcoreDarkness, ImmersiveEngineering, industrialcraft-2, InventoryTweaks, IronBackpacks, ironchest, jei, jepb, Mantle, Matchlock+Guns+Mod, MicdoodleCore, MJRLegendsLib, NaturesCompass, NetherPortalFix, NoMoreRecipeConflict, OnlinePicFrame, OptiFine, Pam's+HarvestCraft, Patchouli, PlayerRevive, powerchisels, Reliquary, rustic, SpartanShields, TConstruct, Thaumcraft, tinkersjei, TreeChopper, twilightforest, UnlimitedChiselWorks, VanillaFix, VeinMiner, zombieawareness

Please state the site that you downloaded Galacticraft from: https://micdoodle8.com/mods/galacticraft/downloads

IC2 machines and cables have stopped dropping when I break them in a room with an activated oxygen sealer. Whenever this happens, the exception found in the logs happens in the server console.  Galacticraft and vanilla blocks seem mostly unaffected, although I lost a cryogenic chamber once, but every machine or cable I have tried from IC2 consistently does not drop when broken. Disabling the oxygen sealer or breaking them outside of the sealed room fixes this. The IC2 version is 2.8.170-ex112

**Comment by micdoodle8** [comment]
I'm making build 280 now, which contains an attempted fix. Can you test it out and report back? I can't seem to recreate the issue myself.
