### ISSUE TITLE
Evolved Spider Jockey spawns with vanilla Skeleton

### ISSUE THREAD

**Issue by QuantumStatement** [micdoodle8/Galacticraft#3963]
Minecraft version: 1.12.2
Galacticraft version ("latest" is not a valid option): 4.0.2.272

**Single player (SP)**, Multiplayer (MP), or SP opened to LAN (LAN)?
- If MP server, please mention if it has Sponge, AtomMC, BukkitForge, BungeeCord etc.

Any Galacticraft add-ons installed? Please list all of them:
No addons

Please upload crash report / full log to [Github Gist](https://gist.github.com/) or any other paste site:
N/A

Please provide screenshots / videos / full modlist as needed
![2020-05-07_14 47 21](https://user-images.githubusercontent.com/35406698/81328028-e89f1f00-90a4-11ea-8c18-3eded1f9d032.png)

Please state the site that you downloaded Galacticraft from:
micdoodle8.com

**Comment by micdoodle8** [comment]
Thanks! Funnily enough, both vanilla skeletons and evolved skeletons could spawn on the spiders, so there was a 1 in 10,000 chance that both would spawn on the same spider. Wonder if anyone has ever seen that happen :)
