### ISSUE TITLE
Game crashing when interacting with power machines

### ISSUE THREAD

**Issue by xanderc2** [micdoodle8/Galacticraft#3968]
Minecraft version: 1.12.2

Galacticraft: 273

All, SP,MP 

Any Galacticraft add-ons installed? Please list all of them: 
ExtraPlanets | MJRLegends | ExtraPlanets-1.12.2-0.6.4.jar

Please upload crash report / full log to [Github Gist](https://gist.github.com/) or any other paste site:

Please state the site that you downloaded Galacticraft from: official site

The game crashes and the world get corrupted whn i put a conduit next to a power INPUT of any galacticraft machine even with only EU as accepted energy by config

[crash-2020-05-12_07.58.54-server.txt](https://github.com/micdoodle8/Galacticraft/files/4613724/crash-2020-05-12_07.58.54-server.txt)

**Comment by micdoodle8** [comment]
Thanks for the report, should be fixed in the next build

**Comment by xanderc2** [comment]
thanks, will be good for my pack, love it
