### ISSUE TITLE
Retrieving block state from the world seems unnecessary in getPickBlock

### ISSUE THREAD

**Issue by sam-kirby** [micdoodle8/Galacticraft#3970]
REVIEW THE GUIDELINES - see [Contributing](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) link on right side.

Minecraft version: 1.12.2
Galacticraft version: 4.0.2.277

Single player (SP), Multiplayer (MP), or SP opened to LAN (LAN)? Any

Any Galacticraft add-ons installed? Please list all of them: No

Please upload crash report / full log to [Github Gist](https://gist.github.com/) or any other paste site: Not relevant

In [BlockBasic](../blob/master/src/main/java/micdoodle8/mods/galacticraft/core/blocks/BlockBasic.java)#getPickBlock, this mod retrieves the block state from the world despite being passed it as an argument. This is innocuous enough in most cases, but breaks compatibility with the Scannables mod, which passes only BlockPos.ORIGIN. [Ref](https://github.com/MightyPirates/Scannable/blob/master-MC1.12/src/main/java/li/cil/scannable/util/BlockUtils.java#L23). While I don't argue this is necessarily correct, I don't see the reason for not using the passed state here.

Please state the site that you downloaded Galacticraft from: Github

**Comment by micdoodle8** [comment]
Good catch, must've been there since the 1.8 update. Thanks
