### ISSUE TITLE
Silk Touch doesn't drop an galacticraft ores 

### ISSUE THREAD

**Issue by ncpfluke** [micdoodle8/Galacticraft#3973]
Minecraft Version 1.12.2

All Gamemodes (single player and server)

I also have buildcraft and optifine mods installed

Cant obtain any galacticraft ores with an iron silk touch pickaxe. Vanilla blocks are obtainable just fine, but desh ore and cheese ore and tin ore does not drop anything when mined with an iron silk touch pickaxe. Makes it a little difficult to build an orion belt for an astro miner :p

**Comment by micdoodle8** [comment]
Desh and ilmenite require diamond pickaxes. I've updated the wiki to reflect this.
