### ISSUE TITLE
Server crashes as i leave planet before map screen loads.

### ISSUE THREAD

**Issue by Itscmd** [micdoodle8/Galacticraft#3991]
REVIEW THE GUIDELINES - see [Contributing](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) link on right side.

Minecraft version: 1.7.10
Galacticraft version: 1.7-3.0.12.504

MP server hosted on Serverminer, no plugins.

GalacticraftOres
Galaxy space
Moon of mining

crash report: https://gist.github.com/Itscmd/480df54086a4b6ba54b642e094f9c692

modlist: https://gist.github.com/Itscmd/f423f98687bd9de1526e6d6b68f07d74

Please state the site that you downloaded Galacticraft from: https://micdoodle8.com/mods/galacticraft/downloads

All of the items load just fine, no issues were encountered until I liftoff to the point it's supposed to load the galaxy map. Then suddenly, "Server Closed"

**Comment by MJRLegends** [comment]
Two of your dimensions have dimension id conflicts. Check your full log to find out which

**Comment by Itscmd** [comment]
Sorry, I'm rather new to all this and need help on how to figure that out. What do I look for in here to find that? And what log am I looking at exactly? I have been using the minecraft game output option and the server crash report any time I open the game to get a clue but I'm not 100% certain of what I'm looking at or looking for.
