### ISSUE TITLE
 inventory

### ISSUE THREAD

**Issue by Jly4** [micdoodle8/Galacticraft#3997]
Minecraft version: 1.12.2
Galacticraft version : 1.12.2-4.0.2.280

Multiplayer (MP)
- magma(https://github.com/magmafoundation/Magma)

Any Galacticraft add-ons installed? Please list all of them:  galacticraft planets

Please provide screenshots / videos / full modlist as needed
https://imgur.com/a/qbPyt5b

items in inventory are visible on top of the search bar in jei and inventory.
this is not, if you delete galacticraft, this is also not in the single-player game.
how to fix it? 

Please state the site that you downloaded Galacticraft from:
https://ru-minecraft.ru/download/index.php?file=GalacticraftCore-1.12.2-4.0.2.280.jar

**Comment by marcus8448** [comment]
You seem to have downloaded Galacticraft from a illegal/non-official webpage. Please checkout Stop Mod Reposts<https://stopmodreposts.org/> for more info about these bad sites.
Please re-download Galacticraft from here: https://micdoodle8.com/mods/galacticraft/downloads.

**Comment by Jly4** [comment]
This is a good and proven site. I'm downloading all the mods from him

**Comment by MJRLegends** [comment]
Its still a illegal site dude even if you used it for ages.
