### ISSUE TITLE
I downloaded Extra planets and Every time I go into the world and get to the part where I get to choose which planet to go to it kicks me out and says my connection has been terminated and puts me in the MP section even though its singer player

### ISSUE THREAD

**Issue by BeepBoopie** [micdoodle8/Galacticraft#4003]
REVIEW THE GUIDELINES - see [Contributing](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) link on right side.

Minecraft version:
Galacticraft version ("latest" is not a valid option):
1.12.2
Single player (SP), Multiplayer (MP), or SP opened to LAN (LAN)?
- If MP server, please mention if it has **Sponge**, AtomMC, BukkitForge, BungeeCord etc.
Single player

Any Galacticraft add-ons installed? Please list all of them:
MicdoodleCore 1.12.2
MJRLengensLib 1.12.2
Extraplanets 1.12.2-0.6.4
Galacticraft-Planets 1.12.2-4.0.2.280
GalacticraftCore-1.12.2-4.0.2.280

Please upload crash report / full log to [Github Gist](https://gist.github.com/) or any other paste site:
![image](https://user-images.githubusercontent.com/67057176/84900502-117ce180-b05f-11ea-838a-5c92a2123cde.png)

Another issue is it doesnt give me a crash report it just kicks me out

Please provide screenshots / videos / full modlist as needed
![image](https://user-images.githubusercontent.com/67057176/84899544-a5e64480-b05d-11ea-8ca9-952913bc92a2.png)

Please state the site that you downloaded Galacticraft from: https://micdoodle8.com/mods/galacticraft/downloads
and for Extra planets 
https://www.curseforge.com/minecraft/mc-mods/extraplanets

**Comment by BeepBoopie** [comment]
And yes I did download the newest versions

**Comment by dj3520** [comment]
Your issue should exist here instead: https://github.com/MJRLegends/ExtraPlanets/issues
Include a server log when making the issue.

**Comment by MJRLegends** [comment]
Looks to me like hes been downloading mods on 9minecraft site and thats why.

Micdoodle core and malisis doors

**Comment by MJRLegends** [comment]
Please dont report it on the ExtraPlanets issue tracker with them illegal downloaded jar files i will just close the issue. Please replace them with legit copies and if the issue still happens report it then

**Comment by BeepBoopie** [comment]
Where do I find the real copy of Extra planets?

**Comment by MJRLegends** [comment]
You already have that. Its the other two i said that is not legit copies

**Comment by BeepBoopie** [comment]
but they are I got them from the McDoodle site

**Comment by MJRLegends** [comment]
Micdoodle you have isnt the file name isnt something you get from that site. The file name you have is from a site like 9minecraft

**Comment by MJRLegends** [comment]
Also you have Asmodeuscore core mod but no mods that require it at this current time. Probably best to remove it in till you add more mods or if you want the galaxy map screen that asmodeuscore then you'd defo want to keep it

**Comment by BeepBoopie** [comment]
can you give me the link to the real site?
also the site I used was https://micdoodle8.com/mods/galacticraft/downloads
so make sure to tell McDoodle that someone has made a site with his name

**Comment by MJRLegends** [comment]
As already said MicdoodleCore-Mod.jar is not a offical jar file name you get that file name when you download from illegal sites..

Redownload MicdoodleCore

**Comment by MJRLegends** [comment]
https://micdoodle8.com/new-builds/GC-1.12/280/MicdoodleCore-1.12.2-4.0.2.280.jar

**Comment by L1v3p** [comment]
O mesmo erro que tá acontecendo com migo
