### ISSUE TITLE
Lower space station tp Y level.

### ISSUE THREAD

**Issue by josh-65** [micdoodle8/Galacticraft#4007]
Can the tp point on space stations be lowered to Y level 0 So we can fully use 256 blocks maybe even lower like -5 so we can fly under it.

**Comment by TheQuadShot** [comment]
This should be posted on the web site, not a bug report. You can post it there and open it up for discussion with the community here:
https://forum.micdoodle8.com/index.php
Please close this report, and post it over there, Thanks
