### ISSUE TITLE
Crawler (space evolution) doesn't drop sugarcane

### ISSUE THREAD

**Issue by mcqwy** [micdoodle8/Galacticraft#4021]
In asteroid challenge mode, crawler (space evolution) will not drop sugarcane.
And slimy monsters don't drop slime balls when they don't die.
This will make it impossible for me to make water electrolysis machines and methane synthesis machines.
Eventually, rocket fuel cannot be obtained without returning to earth.

**Comment by mcqwy** [comment]
Also, I saw on the official WiFi that spiders (space evolution) would drop cheese curd.
After actual measurement, I killed a lot of spiders. It won't fall off cheese curd

**Comment by dj3520** [comment]
This is an issue with the modpack you're using, not a specific mod.

**Comment by mcqwy** [comment]
Sorry, I didn't catch you
