### ISSUE TITLE
Keep crashing with Pams harvestcraft 

### ISSUE THREAD

**Issue by JOLO827** [micdoodle8/Galacticraft#4022]
When I put Pams harvestcraft in my mod pack it crashes
I have vanilla fix so it shows what mod is Causing it

![4A92EBC1-55A6-46E3-B7B9-F18541BC9942](https://user-images.githubusercontent.com/68410673/87804392-d0284f00-c821-11ea-9d5c-0fda7b599811.png)

I’m playing in 1.12.2 the version of galaticraft is .280. I’m playing on single player. The addons I have for galaticraft is. galacticraft add-on-more planets and extra planets. And I downloaded galticraft from the official website 

Here’s the crash report

---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 2020-07-17 11:27:54 EDT
Description: Initializing game

java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.
    at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:295)
    at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
    at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
    at micdoodle8.mods.galacticraft.core.blocks.BlockGrating.createForgeFluidVersion(BlockGrating.java:136)
    at micdoodle8.mods.galacticraft.core.blocks.BlockGrating.createForgeFluidVersions(BlockGrating.java:148)
    at micdoodle8.mods.galacticraft.core.GalacticraftCore$RegistrationHandler.registerItems(GalacticraftCore.java:719)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_450_RegistrationHandler_registerItems_Register.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:850)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Mac OS X (x86_64) version 10.13.6
  Java Version: 1.8.0_74, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1062584344 bytes (1013 MB) / 2013265920 bytes (1920 MB) up to 2147483648 bytes (2048 MB)
  JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F5 61 mods loaded, 61 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                   | Version             | Source                                        | Signature                                |
       |:----- |:-------------------- |:------------------- |:--------------------------------------------- |:---------------------------------------- |
       | LCH   | minecraft            | 1.12.2              | minecraft.jar                                 | None                                     |
       | LCH   | mcp                  | 9.42                | minecraft.jar                                 | None                                     |
       | LCH   | FML                  | 8.0.99.99           | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | forge                | 14.23.5.2854        | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | ivtoolkit            | 1.3.3-1.12          | minecraft.jar                                 | None                                     |
       | LCH   | micdoodlecore        |                     | minecraft.jar                                 | None                                     |
       | LCH   | otgcore              | 1.12.2 - v8.3       | minecraft.jar                                 | None                                     |
       | LCH   | foamfixcore          | 7.7.4               | minecraft.jar                                 | None                                     |
       | LCH   | damageindicatorsmod  | 1.0                 | [1.12.2]DamageIndicatorsMod-3.5.1.jar         | None                                     |
       | LCH   | aether_legacy        | 1.4.4               | aether_legacy-1.12.2-v1.4.4.jar               | None                                     |
       | LCH   | aoa3                 | 3.3.1               | AoA3-3.3.1.jar                                | 8bddeac148843f40e0b9f69201be2f4b3071700d |
       | LCH   | autoreglib           | 1.3-32              | AutoRegLib-1.3-32.jar                         | None                                     |
       | LCH   | battletowers         | 1.6.5               | BattleTowers-1.12.2.jar                       | None                                     |
       | LCH   | baubles              | 1.5.2               | Baubles-1.12-1.5.2.jar                        | None                                     |
       | LCH   | betternether         | 0.1.8.6             | betternether-0.1.8.6.jar                      | None                                     |
       | LCH   | openterraingenerator | v8.3                | OpenTerrainGenerator-1.12.2 - v8.3.jar        | None                                     |
       | LCH   | biomebundle          | 5.1                 | Biome_Bundle-1.12.2-v6.1.jar                  | None                                     |
       | LCH   | biomesoplenty        | 7.0.1.2441          | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar | None                                     |
       | LCH   | guideapi             | 1.12-2.1.8-63       | Guide-API-1.12-2.1.8-63.jar                   | None                                     |
       | LCH   | bloodmagic           | 1.12.2-2.4.3-105    | BloodMagic-1.12.2-2.4.3-105.jar               | None                                     |
       | LCH   | chococraft           | 0.9.1.52            | chococraft_1.12.1-0.9.1.52.jar                | None                                     |
       | LCH   | craftstudioapi       | 1.0.0               | CraftStudio-1.0.0.93-mc1.12-alpha.jar         | None                                     |
       | LCH   | dldungeonsjbg        | 1.13.2              | DoomlikeDungeons-1.13.2-MC1.12.2.jar          | None                                     |
       | LCH   | ebwizardry           | 4.2.11              | ElectroblobsWizardry-4.2.11-MC1.12.2.jar      | None                                     |
       | LCH   | mantle               | 1.12-1.3.3.55       | Mantle-1.12-1.3.3.55.jar                      | None                                     |
       | LCH   | jei                  | 4.15.0.291          | jei_1.12.2-4.15.0.291.jar                     | None                                     |
       | LCH   | thaumcraft           | 6.1.BETA26          | Thaumcraft-1.12.2-6.1.BETA26.jar              | None                                     |
       | LCH   | twilightforest       | 3.10.1013           | twilightforest-1.12.2-3.10.1013-universal.jar | None                                     |
       | LCH   | tconstruct           | 1.12.2-2.13.0.183   | TConstruct-1.12.2-2.13.0.183.jar              | None                                     |
       | LCH   | galacticraftcore     | 4.0.2.280           | GalacticraftCore-1.12.2-4.0.2.280.jar         | None                                     |
       | LCH   | galacticraftplanets  | 4.0.2.280           | Galacticraft-Planets-1.12.2-4.0.2.280.jar     | None                                     |
       | LCH   | mjrlegendslib        | 1.12.2-1.1.9        | MJRLegendsLib-1.12.2-1.1.9.jar                | b02331787272ec3515ebe63ecdeea0d746653468 |
       | LCH   | extraplanets         | 1.12.2-0.6.4        | ExtraPlanets-1.12.2-0.6.4.jar                 | b02331787272ec3515ebe63ecdeea0d746653468 |
       | LCH   | foamfix              | 0.10.9-1.12.2       | foamfix-0.10.9-1.12.2.jar                     | None                                     |
       | LCH   | fpsreducer           | mc1.12.2-1.12.4     | FpsReducer-mc1.12.2-1.12.4.jar                | None                                     |
       | LCH   | gravestone           | 1.10.2              | gravestone-1.10.2.jar                         | None                                     |
       | LCH   | waila                | 1.8.26              | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     |
       | LCH   | ichunutil            | 7.2.2               | iChunUtil-1.12.2-7.2.2.jar                    | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCH   | journeymap           | 1.12.2-5.7.1        | journeymap-1.12.2-5.7.1.jar                   | None                                     |
       | LCH   | libraryex            | 1.1.3               | LibraryEx-1.12.2-1.1.3.jar                    | None                                     |
       | LCH   | lootbags             | 2.5.8.5             | LootBags-1.12.2-2.5.8.5.jar                   | None                                     |
       | LCH   | lycanitesmobs        | 2.0.7.2 - MC 1.12.2 | lycanitesmobs-1.12.2-2.0.7.2.jar              | None                                     |
       | LCH   | radixcore            | 1.12.x-2.2.1        | RadixCore-1.12.x-2.2.1-universal.jar          | None                                     |
       | LCH   | mca                  | 1.12.2-5.3.1        | MCA-1.12.x-5.3.1-universal.jar                | None                                     |
       | LCH   | moreplanets          | 2.0.24              | More-Planets-1.12.2-2.0.24-GC251.jar          | b3468b224a74e296555ad7efeb35f482e6f445de |
       | LCH   | morph                | 7.2.0               | Morph-1.12.2-7.2.0.jar                        | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCH   | netherex             | 2.1.7               | NetherEx-1.12.2-2.1.7.jar                     | None                                     |
       | LCH   | harvestcraft         | 1.12.2zb            | Pam's HarvestCraft 1.12.2zg.jar               | None                                     |
       | LCH   | patchouli            | 1.0-19              | Patchouli-1.0-19.jar                          | None                                     |
       | LCH   | reccomplex           | 1.4.8.2             | RecurrentComplex-1.4.8.2.jar                  | None                                     |
       | LCH   | roguelike            | 1.8.0               | RoguelikeDungeons-1.12.2-1.8.0.jar            | None                                     |
       | LCH   | ruins                | 17.2                | Ruins-1.12.2.jar                              | None                                     |
       | LCH   | surge                | 2.0.79              | Surge-1.12.2-2.0.79.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | texfix               | 4.0                 | TexFix V-1.12-4.0.jar                         | None                                     |
       | LCH   | tfspellpack          | 1.0.1               | TFSpellPack-1.0.1-MC1.12.2.jar                | None                                     |
       | LCH   | toughasnails         | 3.1.0.139           | ToughAsNails-1.12.2-3.1.0.139-universal.jar   | None                                     |
       | LCH   | tropicraft           | 7.1.9.115           | tropicraft-MC1.12.2-7.1.9.115.jar             | None                                     |
       | LCH   | vanillafix           | 1.0.10-150          | VanillaFix-1.0.10-150.jar                     | None                                     |
       | LCH   | llibrary             | 1.7.19              | llibrary-1.7.19-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCH   | thebetweenlands      | 3.6.1               | TheBetweenlands-3.6.1-universal.jar           | 38067d6878811efb38b6a045521cfd80b9b60b38 |
       | LCH   | midnight             | 0.3.5               | themidnight-0.3.5.jar                         | None                                     |
  Loaded coremods (and transformers): llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.9-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      midnight (themidnight-0.3.5.jar)
                                        com.mushroom.midnight.core.transformer.MidnightClassTransformer
                                      OTGCorePlugin (OTG-Core.jar)
                                        com.pg85.otg.forge.asm.excluded.OTGClassTransformer
                                      MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
                                        micdoodle8.mods.miccore.MicdoodleTransformer
                                      IvToolkit (IvToolkit-1.3.3-1.12.jar)
                                        
                                      TheBetweenlandsLoadingPlugin (TheBetweenlands-3.6.1-core.jar)
                                        thebetweenlands.core.TheBetweenlandsClassTransformer
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.79.jar)
  GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-10.36.32' Renderer: 'Intel Iris Pro OpenGL Engine'
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - wailaIntegration (Enabled/Not Forced)
  Suspected Mods: Galacticraft Core (galacticraftcore)
  Launched Version: 1.12.2-forge-14.23.5.2854
  LWJGL: 2.9.2
  OpenGL: Intel Iris Pro OpenGL Engine GL version 2.1 INTEL-10.36.32, Intel Inc.
  GL Caps: VboRegions not supported, missing: OpenGL 1.3, ARB_copy_buffer
           Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: vanilla
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 4x Intel(R) Core(TM) i5-4570R CPU @ 2.70GHz

**Comment by ROMVoid95** [comment]
use https://www.curseforge.com/minecraft/mc-mods/jeid

**Comment by JOLO827** [comment]
Thanks it works now
