### ISSUE TITLE
Website is down, How do I download Galacticraft?

### ISSUE THREAD

**Issue by JohnB17** [micdoodle8/Galacticraft#4025]
I can't get through to the website "micdoodle8.com" I think it is down. I found other issues on this repository saying the same thing but they were posted in 2016, 4 years ago. How am I supposed download this?

**Comment by MJRLegends** [comment]
http://micdoodle8.com/mods/galacticraft/downloads works fine, it seems to be the forums down

**Comment by JohnB17** [comment]
I still can't get through. I'll clear my browser cache but I don't know

**Comment by Bop01** [comment]
That didn't work for me either. Is there any other place to find the download?

**Comment by EzerArch** [comment]
@JohnB17 @Bop01:
@micdoodle8 is aware of the problem. Site will be back soon.

**Comment by JohnB17** [comment]
Thanks, the only place I could find with the files precompiled was 9minecraft.net (I hate 9minecraft.net but I couldn't compile it my self)
