### ISSUE TITLE
Cannot craft Fuel Loader with correct items, cant check forum due to it being down

### ISSUE THREAD

**Issue by Joshbts** [micdoodle8/Galacticraft#4026]
it seems i cant craft a fuel loader using 5 Compressed steel, 2 compressed aluminium, basic wafer and a tin canister but cant check the correct forum either due to it being down, please help

**Comment by EzerArch** [comment]
Forum is back up.

I recommend installing JEI to check the recipes in game: https://www.curseforge.com/minecraft/mc-mods/jei

**Comment by Joshbts** [comment]
The forum isnt back up, atleast not the WIKI, already installed JEI after trying to sort the problem myself, worked well

**Comment by EzerArch** [comment]
Both the wiki and the forum are on my side. Probably there was some DNS changes and it takes some while to spread.

> 5 Compressed steel, 2 compressed aluminium, basic wafer and a tin canister

That's an old recipe from GC2 and GC3.
