### ISSUE TITLE
Flag won´t show my skin face on original mc

### ISSUE THREAD

**Issue by KexoTV** [micdoodle8/Galacticraft#4027]
Bug: **Flag won´t show my skin face on original mc (even friends flag won´t show)**

Minecraft version: **1.12.2**
Galacticraft version ("latest" is not a valid option): **4.0.2.280**

SP openned to LAN

![2020-07-21_15 09 00](https://user-images.githubusercontent.com/55331891/88077449-946feb00-cb7b-11ea-82a5-e47191e7329a.png)

Any Galacticraft add-ons installed? Please list all of them: **None**

Please state the site that you downloaded Galacticraft from: **Curseforge**

**Comment by marcus8448** [comment]
Flags no longer have the player's face automatically pasted on. You can now draw your own flag in-game [like this one](https://wiki.micdoodle8.com/wiki/File:Wikiflag.png) in the 'space race manager' screen
