### ISSUE TITLE
Skript Times u hit an armorstand

### ISSUE THREAD

**Issue by Wountie** [micdoodle8/Galacticraft#4028]
So i want to create a skript but i have 1 issue i want to add 1 to a variable.
![Skripttttttttttttttttttttttt](https://user-images.githubusercontent.com/67549185/88195297-2b05e000-cc40-11ea-90c2-0a2f5d63b1d5.png)

**Comment by Wountie** [comment]
So i want to create a skript but i have 1 issue i want to add 1 to a variable.
![Skripttttttttttttttttttttttt](https://user-images.githubusercontent.com/67549185/88194912-aa46e400-cc3f-11ea-9da6-d97d314fb3c6.png)

**Comment by dj3520** [comment]
This is not related to Galacticraft. Please close this issue.

**Comment by Wountie** [comment]
> This is not related to Galacticraft. Please close this issue.

idk how to change the things that relate to
