### ISSUE TITLE
Turret target selection error - report

### ISSUE THREAD

**Issue by Yoga34** [micdoodle8/Galacticraft#4031]
REVIEW THE GUIDELINES - see [Contributing](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) link on right side.

Minecraft version: 1.12.2
Galacticraft version ("latest" is not a valid option): 4.0.2.244

Single player (SP), Multiplayer (MP), or SP opened to LAN (LAN)?
- If MP server, please mention if it has **Sponge**, AtomMC, BukkitForge, BungeeCord etc.

SP

Any Galacticraft add-ons installed? Please list all of them: Galacticraft Planets

Please upload crash report / full log to [Github Gist](https://gist.github.com/) or any other paste site:

Please provide screenshots / videos / full modlist as needed

Video:
https://youtu.be/GgkeAMJoppM - Watch from the middle

Modlist:
Chicken Chunks
Code Chicken Lib
Custom NPC
VoxelMap
Galacticraft Core
Galacticraft Planets
Micdoodle Core
Genetics Reborn
Gravestone
Gravity Gun
I Chun Util
Industrial Craft 2
Just Enough Items
Lag Googles
Deconstruction Table
Not Enough Items
Techguns
Tick Central

Please state the site that you downloaded Galacticraft from: minecraft-inside.ru

**Comment by TheMCSpacePro** [comment]
Try downloading Galacticraft from here: https://micdoodle8.com/mods/galacticraft/downloads

Also, please use the latest version.

**Comment by Yoga34** [comment]
Are you kidding? There is a bug with a turret, it shoots a turret from the Techguns mod by mistake, considering it a hostile mob, even if this turret was placed by the player.

**Comment by TheMCSpacePro** [comment]
This may have been fixed in the latest version. Also, you downloaded the mod from an illegal reposting site, hence why I'm saying to redownload the **_latest_** version of the mod from the offical site.

**Comment by Yoga34** [comment]
Okay. I'll upload. But the latest version doesn't mean stable. There may be new bugs.

**Comment by Yoga34** [comment]
Anyway, take note of this error. If the latest update doesn't change anything I will say so.

**Comment by Yoga34** [comment]
The update didn't fix the bug.

**Comment by dj3520** [comment]
If this is not fixed please keep the issue open.
