### ISSUE TITLE
POTENTIAL BIOME ID CONFLICT for id 255 conflicting with Galacticraft

### ISSUE THREAD

**Issue by Trackhe** [micdoodle8/Galacticraft#4033]
Minecraft version:1.12.2
Galacticraft version : 1.12.2-4.0.2.280

Multiplayer (MP
MP Server mohist. https://github.com/Mohist-Community/Mohist

Any Galacticraft add-ons installed?
Galacticraft-Planets-1.12.2-4.0.2.280.jar
GalaxySpace-1.12.2-2.0.14.jar
ExtraPlanets-1.12.2-0.6.5.jar
ZollernGalaxy-1.12.2-v2.0.14.jar
More-Planets-1.12.2-2.1.12-GC251.jar
And i had Interstellar-Exoplanets-0.0.9.32 but the Dev from this mod is a rude guy.

crash report [hier](https://gist.github.com/Trackhe/b47ce921f0a57532b565f24457b26948)

Please state the site that you downloaded Galacticraft from: 
https://micdoodle8.com/mods/galacticraft

I guess the Problem is that Minecraft limit the Biom number to 255 but the mod [JustEnoughIDs](https://www.curseforge.com/minecraft/mc-mods/jeid) give minecraft 1.12.2 the limit of 65k 
and Galacticraft not use it

**Comment by MJRLegends** [comment]
Try update Galacticraft as its very out of date also your crash log is the java script of the website that you posted it on so its impossible to see it

**Comment by dj3520** [comment]
Corrected crash report URL: https://gist.github.com/Trackhe/b47ce921f0a57532b565f24457b26948

**Comment by Trackhe** [comment]
@micdoodle8 is it possible to add the support of JustEnoughID`s in the next weeks? I dont know enough to add it with a pull request or a fork. (sadly ^^' )

**Comment by ROMVoid95** [comment]
What exactly made me a rude guy lol??
