### ISSUE TITLE
I can see through planets

### ISSUE THREAD

**Issue by Danchu67** [micdoodle8/Galacticraft#4042]
REVIEW THE GUIDELINES - see [Contributing](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) link on right side.

Minecraft version: 1.12.2
Galacticraft version ("latest" is not a valid option):4.0.2.280

Single player (SP), Multiplayer (MP), or SP opened to LAN (LAN)?
SP
Any Galacticraft add-ons installed? Please list all of them: MorePlanets, GalaxySpace

Please provide screenshots / videos / full modlist as needed
![Bug](https://user-images.githubusercontent.com/69430318/89737226-6e808c80-da3d-11ea-8a07-df43403636e3.png)

Please state the site that you downloaded Galacticraft from:
https://micdoodle8.com/mods/galacticraft

Whenever I visit a planet it looks like this

**Comment by dj3520** [comment]
Please include full modlist.
