### ISSUE TITLE
Galacticraft Version

### ISSUE THREAD

**Issue by berkanelit** [micdoodle8/Galacticraft#4044]
Please my friend 1.15-1.16

**Comment by MJRLegends** [comment]
Lol

**Comment by ekultails** [comment]
Work has already started on Galacticraft for Minecraft [1.14](https://github.com/micdoodle8/Galacticraft/tree/MC1.14) and [1.15](https://github.com/micdoodle8/Galacticraft/tree/MC1.15).

**Comment by tj5382** [comment]
> Work has already started on Galacticraft for Minecraft [1.14](https://github.com/micdoodle8/Galacticraft/tree/MC1.14) and [1.15](https://github.com/micdoodle8/Galacticraft/tree/MC1.15).

Is there an estimated completion date? Or too early to tell?

**Comment by ROMVoid95** [comment]
nope
