### ISSUE TITLE
Sponge Galacticraft Space Station TPS issues

### ISSUE THREAD

**Issue by Enterprise12nx01** [micdoodle8/Galacticraft#4045]
I was having issues where a space station with nothing on it yet was causing a massive tps loss (upto 14) on a public server
i found this: https://wiki.micdoodle8.com/wiki/Tutorials/Space_Station_for_Server_Admins

It use to be fixed with these settings on MCPC+
world-environment-settings:
normal:
keep-world-loaded: true
nether:
keep-world-loaded: true
the_end:
keep-world-loaded: false
gccorespacestation:
keep-world-loaded: false
gcmoon:
keep-world-loaded: false
enabled: true
gcmars:
keep-world-loaded: false
enabled: true

Sponge does not have this option however, does anybody have any ideas of how to fix this issue?

Minecraft version: 1.12.2
Galacticraft version ("latest" is not a valid option): 1.12.2-4.0.2.280

Single player (SP), Multiplayer (MP), or SP opened to LAN (LAN)?
- If MP server, please mention if it has **Sponge**, AtomMC, BukkitForge, BungeeCord etc.
Sponge MP

Any Galacticraft add-ons installed? Please list all of them: No

Please upload crash report / full log to [Github Gist](https://gist.github.com/) or any other paste site:
NA

Please provide screenshots / videos / full modlist as needed
NA

Please state the site that you downloaded Galacticraft from:
http://www.micdoodle8.com/

**Comment by Irgendwer01** [comment]
Sponge is known to cause issues with TPS, its recommend to do a pregen to reduce lag https://www.curseforge.com/minecraft/mc-mods/chunkpregenerator
