### ISSUE TITLE
Hanging while switching dimensions

### ISSUE THREAD

**Issue by mc-oofert** [micdoodle8/Galacticraft#4051]
Minecraft version: 1.12.2
Galacticraft version ("latest" is not a valid option):
4.0.2.280
Single player (SP), Multiplayer (MP), or SP opened to LAN (LAN)?
- If MP server, please mention if it has **Sponge**, AtomMC, BukkitForge, BungeeCord etc.
SP
Any Galacticraft add-ons installed? Please list all of them:
Galacticraft Planets
Please upload crash report / full log to [Github Gist](https://gist.github.com/) or any other paste site:
[log.txt](https://github.com/micdoodle8/Galacticraft/files/5141847/log.txt)

Please provide screenshots / videos / full modlist as needed
[modlist.txt](https://github.com/micdoodle8/Galacticraft/files/5141855/modlist.txt)
Please state the site that you downloaded Galacticraft from:
https://micdoodle8.com/mods/galacticraft/downloads

whenever i travel to the moon or to the overworld using a rocket for example it hangs at the loading

**Comment by TheMCSpacePro** [comment]
Better Portals is causing this issue. There is a fix in the works by ROMVoid.

**Comment by mc-oofert** [comment]
@TheMCSpacePro thanks that seemed to fix it
