### ISSUE TITLE
(1.12.2)(SP)Galacticraft stuck on loading screen when entering a dimension

### ISSUE THREAD

**Issue by InvitedRhino683** [micdoodle8/Galacticraft#4052]
Minecraft version: 1.12.2
Galacticraft version: 4.0.2.280

Log: [latest.log](https://github.com/micdoodle8/Galacticraft/files/5144658/latest.log)

Video: https://youtu.be/nvDZfW8TPaY

Config Folder: [config.zip](https://github.com/micdoodle8/Galacticraft/files/5144665/config.zip)

Downloaded Site: https://micdoodle8.com/mods/galacticraft/downloads

I'd like to note that this was on Creative Mode.

**Comment by TheMCSpacePro** [comment]
Better Portals issue, ROM has created a prototype for a fix.

**Comment by InvitedRhino683** [comment]
Can you send me the link?

**Comment by InvitedRhino683** [comment]
or maybe the file?

**Comment by TheMCSpacePro** [comment]
Sorry, 1) That would be **against the Galacticraft license** and 2) ROM is still working on it.

**Comment by InvitedRhino683** [comment]
Wait, who is ROM again?

**Comment by TheMCSpacePro** [comment]
A GC Addon Dev.

**Comment by InvitedRhino683** [comment]
Got it. How do i know when it is Finished?
