### ISSUE TITLE
 Not Loading

### ISSUE THREAD

**Issue by Team708X** [micdoodle8/Galacticraft#4054]
REVIEW THE GUIDELINES - see [Contributing](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) link on right side.

Minecraft version:
Galacticraft version (core, planets, and micdoodle) 1.12.2-4.0.2.280

Single player (SP), Multiplayer (MP), or SP opened to LAN (LAN)?
-Planned SP (No lan)
Any Galacticraft add-ons installed? Please list all of them:
None? GC Planets?
Please upload crash report / full log to [Github Gist](https://gist.github.com/) or any other paste site:
None, It will not load, But here are my logs: https://gist.github.com/Team708X/53a99cbef0b91b361f99c67bfa2864e9
Please provide screenshots / videos / full modlist as needed
Can't, I have ~430 mods
Please state the site that you downloaded Galacticraft from:
Micdoodle8.com

All I know is that I said yes to downloading micdoodle as I didn't have it (all my mods got deleted) and then it softlocked

**Comment by dj3520** [comment]
You only posted a partial log. There's not enough information there to tell what's going on.

**Comment by Team708X** [comment]
Fixed, If MC launcher opens, but not MC itself, start a nonmodded client (I use latest release). close it out, and then start MC again
