### ISSUE TITLE
so I'm making a mod pack and im getting this error code...

### ISSUE THREAD

**Issue by gaminggeek773** [micdoodle8/Galacticraft#4058]
The game crashed whilst initializing game
Error: java.lang.NoSuchMethodError: micdoodle8.mods.galacticraft.core.energy.tile.TileBaseElectricBlockWithInventory: method <init>()V not found
Exit Code: -1

here is the crash report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  GSHooksLoader (GalaxySpace-1.12.2-2.0.14.jar)
  WolfArmorCore (wolfarmor-1.12.2-3.4.1.1-UNIVERSAL-signed.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 9/12/20 6:30 PM
Description: Initializing game

java.lang.NoSuchMethodError: micdoodle8.mods.galacticraft.core.energy.tile.TileBaseElectricBlockWithInventory: method <init>()V not found
	at com.mjr.extraplanets.tileEntities.machines.TileEntityAdvancedRefinery.<init>(TileEntityAdvancedRefinery.java:46)
	at com.mjr.extraplanets.blocks.machines.AdvancedRefinery.createTileEntity(AdvancedRefinery.java:94)
	at micdoodle8.mods.galacticraft.core.items.ItemBlockDesc.func_77624_a(ItemBlockDesc.java:84)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:707)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:576)
	at net.minecraft.client.Minecraft$$Lambda$1486/1644203058.apply(Unknown Source)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at net.minecraft.client.Minecraft$$Lambda$1504/162892964.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:590)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:529)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.mjr.extraplanets.tileEntities.machines.TileEntityAdvancedRefinery.<init>(TileEntityAdvancedRefinery.java:46)
	at com.mjr.extraplanets.blocks.machines.AdvancedRefinery.createTileEntity(AdvancedRefinery.java:94)
	at micdoodle8.mods.galacticraft.core.items.ItemBlockDesc.func_77624_a(ItemBlockDesc.java:84)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:707)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:576)
	at net.minecraft.client.Minecraft$$Lambda$1486/1644203058.apply(Unknown Source)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at net.minecraft.client.Minecraft$$Lambda$1504/162892964.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:590)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:529)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2065697736 bytes (1970 MB) / 4051697664 bytes (3864 MB) up to 11453595648 bytes (10923 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12288m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 52 mods loaded, 52 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version           | Source                                        | Signature                                |
	|:----- |:------------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft           | 1.12.2            | minecraft.jar                                 | None                                     |
	| LCH   | mcp                 | 9.42              | minecraft.jar                                 | None                                     |
	| LCH   | FML                 | 8.0.99.99         | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge               | 14.23.5.2854      | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | micdoodlecore       |                   | minecraft.jar                                 | None                                     |
	| LCH   | actuallyadditions   | 1.12.2-r151       | ActuallyAdditions-1.12.2-r151-2.jar           | None                                     |
	| LCH   | ageofweapons        | 0.13.5            | Age+of+Weapons+1.12.2++(v.0.13.5) (1).jar     | None                                     |
	| LCH   | appliedenergistics2 | rv6-stable-7      | appliedenergistics2-rv6-stable-7.jar          | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCH   | carrots             | 1.0.0b1           | carrotslib-mc1.12.2-1.0.0b1.jar               | None                                     |
	| LCH   | armorunder          | 1.0.0             | armorunder-mc1.12.2-1.0.0.jar                 | None                                     |
	| LCH   | asmodeuscore        | 0.0.17            | AsmodeusCore-1.12.2-0.0.17.jar                | None                                     |
	| LCH   | baubles             | 1.5.2             | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCH   | bountifulbaubles    | 0.0.1             | Bountiful Baubles-1.12.2-0.1.5.jar            | None                                     |
	| LCH   | buildcraftlib       | 7.99.24.6         | buildcraft-all-7.99.24.6.jar                  | None                                     |
	| LCH   | buildcraftcore      | 7.99.24.6         | buildcraft-all-7.99.24.6.jar                  | None                                     |
	| LCH   | buildcraftbuilders  | 7.99.24.6         | buildcraft-all-7.99.24.6.jar                  | None                                     |
	| LCH   | buildcrafttransport | 7.99.24.6         | buildcraft-all-7.99.24.6.jar                  | None                                     |
	| LCH   | buildcraftsilicon   | 7.99.24.6         | buildcraft-all-7.99.24.6.jar                  | None                                     |
	| LCH   | buildcraftcompat    | 7.99.24.6         | buildcraft-all-7.99.24.6.jar                  | None                                     |
	| LCH   | buildcraftenergy    | 7.99.24.6         | buildcraft-all-7.99.24.6.jar                  | None                                     |
	| LCH   | buildcraftfactory   | 7.99.24.6         | buildcraft-all-7.99.24.6.jar                  | None                                     |
	| LCH   | buildcraftrobotics  | 7.99.24.6         | buildcraft-all-7.99.24.6.jar                  | None                                     |
	| LCH   | mantle              | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                      | None                                     |
	| LCH   | jei                 | 4.16.1.301        | jei_1.12.2-4.16.1.301.jar                     | None                                     |
	| LCH   | tconstruct          | 1.12.2-2.13.0.183 | TConstruct-1.12.2-2.13.0.183.jar              | None                                     |
	| LCH   | conarm              | 1.2.5.9           | conarm-1.12.2-1.2.5.9.jar                     | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCH   | galacticraftcore    | 4.0.2.280         | GalacticraftCore-1.12.2-4.0.2.280.jar         | None                                     |
	| LCH   | galacticraftplanets | 4.0.2.280         | Galacticraft-Planets-1.12.2-4.0.2.280.jar     | None                                     |
	| LCH   | mjrlegendslib       | 1.12.2-1.1.8      | MJRLegendsLib-1.12.2-1.1.8.jar                | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCH   | extraplanets        | 1.12.2-0.5.3      | ExtraPlanets-1.12.2-0.5.3.jar                 | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCH   | galaxyspace         | 2.0.14            | GalaxySpace-1.12.2-2.0.14.jar                 | None                                     |
	| LCH   | llibrary            | 1.7.19            | llibrary-1.7.19-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | iceandfire          | 1.7.1             | iceandfire-1.7.1-1.12.2.jar                   | None                                     |
	| LCH   | ironchest           | 1.12.2-7.0.67.844 | ironchest-1.12.2-7.0.72.847.jar               | None                                     |
	| LCH   | iseedragons         | 0.12              | ISeeDragons-0.12.jar                          | None                                     |
	| LCH   | potioncore          | 1.9_for_1.12.2    | PotionCore-1.9_for_1.12.2.jar                 | None                                     |
	| LCH   | qualitytools        | 1.0.7_for_1.12.2  | QualityTools-1.0.7_for_1.12.2.jar             | None                                     |
	| LCH   | railcraft           | 12.0.0            | railcraft-12.0.0.jar                          | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LCH   | realistictorches    | 2.1.1             | RealisticTorches-1.12.2-2.1.1.jar             | None                                     |
	| LCH   | reborncore          | 3.19.4.529        | RebornCore-1.12.2-3.19.4.529-universal.jar    | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCH   | somanyenchantments  | 0.4.4             | So Many Enchantments V0.4.4.jar               | None                                     |
	| LCH   | spartanshields      | 1.5.4             | SpartanShields-1.12.2-1.5.4.jar               | None                                     |
	| LCH   | spartanweaponry     | beta 1.3.8        | SpartanWeaponry-1.12.2-beta-1.3.8.jar         | None                                     |
	| LCH   | stevescarts         | 2.4.32.137        | StevesCarts-1.12.2-2.4.32.137.jar             | None                                     |
	| LCH   | switchbow           | 1.5.7             | switchbow-1.5.7.jar                           | None                                     |
	| LCH   | tcomplement         | 1.12.2-0.4.3      | TinkersComplement-1.12.2-0.4.3.jar            | None                                     |
	| LCH   | toolbelt            | 1.9.12            | ToolBelt-1.12.2-1.9.12.jar                    | None                                     |
	| LCH   | toughasnails        | 3.1.0.139         | ToughAsNails-1.12.2-3.1.0.139-universal.jar   | None                                     |
	| LCH   | vc                  | 5.9.16            | ViesCraft-1.12.2-5.9.16.jar                   | None                                     |
	| LCH   | waystones           | 4.1.0             | Waystones_1.12.2-4.1.0.jar                    | None                                     |
	| LCH   | wearablebackpacks   | 3.1.4             | WearableBackpacks-1.12.2-3.1.4.jar            | None                                     |
	| LCH   | wolfarmor           | 3.4.1.1           | wolfarmor-1.12.2-3.4.1.1-UNIVERSAL-signed.jar | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
GSHooksLoader (GalaxySpace-1.12.2-2.0.14.jar)
  galaxyspace.core.hooklib.minecraft.PrimaryClassTransformer
WolfArmorCore (wolfarmor-1.12.2-3.4.1.1-UNIVERSAL-signed.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 432.00' Renderer: 'GeForce GT 710/PCIe/SSE2'
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Pulsar/tcomplement loaded Pulses: 
		- ModuleCommons (Enabled/Forced)
		- ModuleMelter (Enabled/Not Forced)
		- ModuleArmor (Enabled/Not Forced)
		- ModuleSteelworks (Enabled/Not Forced)
		- Oredict (Enabled/Forced)

	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.19.4.529
		Runtime Debofucsation 1
		RenderEngine: 0
	Launched Version: forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: GeForce GT 710/PCIe/SSE2 GL version 4.6.0 NVIDIA 432.00, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz

and I need some help fixing it I've tried different versions and removing them and putting them back in

**Comment by MJRLegends** [comment]
Update ExtraPlanets its very old version
