### ISSUE TITLE
Stuck on loading screen of Minecraft

### ISSUE THREAD

**Issue by Throwaway1321** [micdoodle8/Galacticraft#4060]
Minecraft version:
Galacticraft version is 1.12.2-4.0.0.2.280

Single player

Any Galacticraft add-ons installed? Please list all of them: 
i have Zollern galaxy, Extra planets, more planets, and galaxy space
https://user-images.githubusercontent.com/71412273/93399046-bd92bc00-f84a-11ea-8da7-031d27036446.PNG is a list of all mods i have

Please state the site that you downloaded Galacticraft from: i use the Official micdoodle site to download galacticraft the addons are from curseforge

**Comment by MJRLegends** [comment]
Please post full debug and latest log files

**Comment by Throwaway1321** [comment]
nvm i found out it was caused by betterportals

**Comment by Throwaway1321** [comment]
nvm it was because of betterportals
