### ISSUE TITLE
Galacticraft Fabric

### ISSUE THREAD

**Issue by berkanelit** [micdoodle8/Galacticraft#4062]
Can it be compatible with the fabric version?
As the fabric is better than fps and speed boredom, it would be great if this trendy fabric came.

**Comment by dj3520** [comment]
This would require re-writing the nearly all of the mod.

**Comment by berkanelit** [comment]
yes correct, but now all mods write compatible with the fabric version.

**Comment by Gandalf360one** [comment]
The Horizon Team is working on a rewrite for Fabric. It is called Galacticraft reroven

**Comment by marcus8448** [comment]
To elaborate on that, Galacticraft: Rewoven is a total rewrite of Galacticraft for FabricMC. It is **not** Galacticraft 5 or meant as a replacement for Galacticraft 4. The github repository for the project can be found here: [StellarHorizons/Galacticraft-Rewoven](https://github.com/StellarHorizons/Galacticraft-Rewoven)

**Comment by berkanelit** [comment]
ok, It will be beautiful, it will be better than forge
