### ISSUE TITLE
Visual issue with Buildcraft engines in Asteroids

### ISSUE THREAD

**Issue by CapnAce** [micdoodle8/Galacticraft#4063]
Minecraft version: 1.12.2
Galacticraft version: 4.0.2.280

Single player 

Any Galacticraft add-ons installed:
More Planets
GalaxySpace

Please state the site that you downloaded Galacticraft from:
micdoodle8.com

Resources:

[Minecraft 1.12.2 2020-09-30 13-25-00_Trim.zip](https://github.com/micdoodle8/Galacticraft/files/5308139/Minecraft.1.12.2.2020-09-30.13-25-00_Trim.zip)

When I turn around the screen turns black and jagged because there is a redstone engine outside the structure, so it happens even if it is not visible, then I turn back around and place then break a second redstone engine. This issue occurs with all buildcraft engines, but not buildcraft pipes. Unknown if it occurs on other planets, haven't tested

Mods Installed:
Optifine
Galacticraft
   GalaxySpace
   More Planets
Hwyla
Just Enough Items
Buildcraft
Dynamic Surroundings
Serene Seasons
Sound Filter

**Comment by dj3520** [comment]
Does this persist without Optifine?

**Comment by CapnAce** [comment]
> Does this persist without Optifine?

It does not. I did some more testing and discovered it is an issue between galaxyspace and optifine. no other combination of mods produced the same effect

**Comment by CapnAce** [comment]
I took the issue to the GalaxySpace page, I think this is more their problem then y’all’s
