### ISSUE TITLE
Dungeon locater compass.

### ISSUE THREAD

**Issue by NathanVH8** [micdoodle8/Galacticraft#4065]
REVIEW THE GUIDELINES - see [Contributing](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) link on right side.

Minecraft version: 1.12.2
Galacticraft version ("latest" is not a valid option): 4.0.2.280 for core, planets, and micdoodle core

Single player (SP), Multiplayer (MP), or SP opened to LAN (LAN)? SP
- If MP server, please mention if it has **Sponge**, AtomMC, BukkitForge, BungeeCord etc.

Any Galacticraft add-ons installed? Please list all of them: Galaxy space

Please upload crash report / full log to [Github Gist](https://gist.github.com/) or any other paste site:

Please provide screenshots / videos / full modlist as needed

Please state the site that you downloaded Galacticraft from: The offical Galacticraft website.

The dungeon locater compass is not working.
And yes this is my first time writing a bug report.

**Comment by MJRLegends** [comment]
Which planet or moon?

**Comment by MJRLegends** [comment]
Also what doesnt work with it

**Comment by NathanVH8** [comment]
It's so far not working on the moon around earth, and the thing not working about it is that it's aways pointing behind you no matter which way you are facing.

**Comment by NathanVH8** [comment]
As far as I can tell it's only not working on the moon (Earth's moon) every where else I have tried, it worked.
