### ISSUE TITLE
Crash Report 1.7.10

### ISSUE THREAD

**Issue by Retro922** [micdoodle8/Galacticraft#4066]
Minecraft version: 1.7.10

Single player

Any Galacticraft add-ons installed? Please list all of them: ExtraPlanets, more planets, galaxy space, moon of mining. (all were disabled when getting crash)

https://paste.ubuntu.com/p/Sn6yDjWbjw/

Please state the site that you downloaded Galacticraft from: micdoodle8.com, ver 3.0

**Comment by MJRLegends** [comment]
Youve download Galacticraft Planets from an illegal source

**Comment by Retro922** [comment]
Fixed that. Now I receive this problem. https://paste.ubuntu.com/p/9R5FYHD5wW/    I tried to disable certain mods that I thought would cause it but with no luck.
