### ISSUE TITLE
Galacticraft or Micdoodle core crashing on server startup 

### ISSUE THREAD

**Issue by Kwesty4658** [micdoodle8/Galacticraft#4074]
As it said in the title, either galacticraft or micdoodle core are crashing on startup, I installed PlayerAPI and that fixed it for a few hours but It went back to crashing.

https://gist.github.com/Kwesty4658/b6f57c43aa62d5198bff31ad59890fd9

Galacticraft planets, Galacticraft tweaker

Modlist: https://gist.github.com/Kwesty4658/82815550963b936a6829eceb1abff059

I downloaded it from the micdoodle website

**Comment by dj3520** [comment]
Please include additional information as requested in the [issue template found here.](https://github.com/micdoodle8/Galacticraft/blob/master/ISSUE_TEMPLATE)

**Comment by marcus8448** [comment]
#4020
