### ISSUE TITLE
Server crashes on startup

### ISSUE THREAD

**Issue by lewmilburn** [micdoodle8/Galacticraft#4076]
REVIEW THE GUIDELINES - see [Contributing](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) link on right side.

Minecraft version: 1.12.2
Galacticraft version ("latest" is not a valid option): 1.12.1-4.0.2.280

Single player (SP), Multiplayer (MP), or SP opened to LAN (LAN)?
MP

Any Galacticraft add-ons installed? Please list all of them:
Planets

Please upload crash report / full log to [Github Gist](https://gist.github.com/) or any other paste site: https://pastebin.com/DZ7BR7Bd

Please provide screenshots / videos / full modlist as needed
Modlist: AE2, Advanced Solar Panels, BuildCraft, Baubles, BetterFps, BiblioCraft, BiomesOPlenty, Botania, CC: Tweaked, Chisels and Bits, Chest Transporter, CodeChickenLib, CoFHCore, CoFHWorld, Energy Converters, Forge Multipart, FTBLib, FTBUtilities, Galacticraft Core & Planets, Hwyla, IC2, IronChest, JEI, Mantle, MCMultiPart, MicdoodleCore, MrTJPCore, ProjectE, ProjectRed Base & Compat & Fabrication & Integration & Lighting & Mechanical & World, Refined Storage, RedstoneFlux, Tinkers Construct, Thaumcraft, ThermalDynamics & Expansion & Foundation, Unifier, Wawla, WR-CBE,

Please state the site that you downloaded Galacticraft from:
micdoodle8.com

**Comment by dj3520** [comment]
The server doesn't start because of this? Or it just shows in the log file?

**Comment by MJRLegends** [comment]
This error wouldnt stop the server starting its a warning type error

**Comment by lewmilburn** [comment]
sorry my control panel said it wouldn't start when infact it would.
Sorry!
