### ISSUE TITLE
Minecraft Crash 1.7.10 

### ISSUE THREAD

**Issue by DenKynai** [micdoodle8/Galacticraft#4078]
Minecraft version:
1.7.10
If i join my minecraft world it freezed en crashed instant, this happents eveerytime when i want to join my single player world. I launch my game from the FTB App, i' m playing FTB Inifnity Evolved 1.7.10. Can some one help me to fix this bug
[crash-2021-11-30_22.00.40-server.txt](https://github.com/micdoodle8/Galacticraft/files/7628929/crash-2021-11-30_22.00.40-server.txt)
?

**Comment by MJRLegends** [comment]
Please post crash log for this crash, we are only developers and sadly not magicians so we dont know how to help without a crash log.

Thank you :)

**Comment by DenKynai** [comment]
[crash-2021-11-30_22.00.40-server.txt](https://github.com/micdoodle8/Galacticraft/files/7628821/crash-2021-11-30_22.00.40-server.txt)

**Comment by MJRLegends** [comment]
Your world has corrupt chunks.....

**Comment by ROMVoid95** [comment]
closing since this is not an issue with Galacticraft

**Comment by DenKynai** [comment]
Can i fix that?
