### ISSUE TITLE
crash when trying to go to another planet Galacticraft

### ISSUE THREAD

**Issue by gamerYToff** [micdoodle8/Galacticraft#4085]
[tl console.log](https://github.com/micdoodle8/Galacticraft/files/7830399/tl.console.log)

when I try to go to another planet the game gets stuck on the screen for a small step and when I leave the world and come back it continues in the menu that shows the planets and I can neither leave the menu nor go to some planet

I'm sorry for the errors in the post it's my 1 post on github and I don't speak well
plus they told me to upload the log instead of copying the text here and as my minecraft gets stuck in the small step screen I finish it with the task manager

my mods
[1.12.2]+SecurityCraft+v1.8.23.2.jar
[1.12.2]DamageIndicatorsMod-3.5.1.jar
[æ°ªé??è??è??]LoliPickaxe-1.2.16f-1.12.2.jar
[MC1.12.2]DeconTable-3.0.4.jar
ActuallyAdditions-1.12.2-r152.jar
advancedsolarpanels-4.3.0.jar
AdvSolarPatch-1.2.1.jar
aether_ii-1.12.2-0.3.0+build411-universal.jar
aiotbotania-0.7.1.jar
appliedenergistics2-rv6-stable-7.jar
AsmodeusCore-1.12.2-0.0.28.jar
AttributeFix-1.12.2-1.0.10.jar
Avaritia-1.12.2-3.3.0.37-universal.jar
avaritiarecipemaker-1.0.0.jar
BackTools-1.12.2-7.0.1.jar
Baubles-1.12-1.5.2.jar
BetterBuildersWands-1.12.2-0.13.2.271+5997513.jar
BetterFps-1.4.8.jar
Botania+r1.10-364.4.jar
BotanicAdditions-1.12.2-12.2.6.jar
branders-enhanced-mob-spawners-v1.12.2-1.4.4.jar.jar
BrandonsCore-1.12.2-2.4.20.162-universal.jar
carryon-1.12.2-1.12.6.20.jar
Chameleon-1.12-4.1.3.jar
ChickenChunks-1.12.2-2.4.2.74-universal.jar
chickens-6.1.0.jar
CLib-1.0.2.31-universal.jar
Clumps-3.1.2.jar
CodeChickenLib-1.12.2-3.2.3.358-universal.jar
CoFHCore-1.12.2-4.6.6.1-universal.jar
CoFHWorld-1.12.2-1.4.0.1-universal.jar
collective-1.12.2-3.0.jar
Controlling-3.0.10.jar
corpse-1.12.2-1.0.8.jar
CosmeticArmorReworked-1.12.2-v5a.jar
CraftTweaker2-1.12-4.1.20.670.jar
Cucumber-1.12.2-1.1.3.jar
Cyclic-1.12.2-1.20.11.jar
Draconic-Additions-1.12.2-1.17.0.45-universal.jar
Draconic-Evolution-1.12.2-2.3.28.354-universal.jar
ElevatorMod-1.12.2-1.3.14.jar
EnchantmentDescriptions-1.12.2-1.1.20.jar
EnderCore-1.12.2-0.5.76.jar
EnderIO-1.12.2-5.3.70.jar
ExpandedEquivalence-1.12.2-12.3.17.jar
ExpOre-1.12.2-1.0.jar
ExtraGolems-1.12-7.1.9.jar
extrautils2-1.12-1.9.9.jar
ExtremeReactors-1.12.2-0.4.5.68.jar
FantasticLib-1.12.2.047.jar
FluxNetworks-1.12.2-4.1.1.34.jar
foamfix-0.10.14-1.12.2.jar
Forgelin-1.8.4.jar
FpsReducer-mc1.12.2-1.20.jar
GalacticraftCore-1.12.2-4.0.2.280.jar
Galacticraft-Planets-1.12.2-4.0.2.280.jar
GalaxySpace-1.12.2-2.0.17.jar
Gaunlets_1.0.0.jar
gravestone-1.10.3.jar
HammerLib-1.12.2-2.0.6.31.jar
Hwyla-1.8.26-B41_1.12.2.jar
iChunUtil-1.12.2-7.2.2.jar
ImmersiveEngineering-0.12-98.jar
industrialcraft-2-2.8.221-ex112.jar
industrialforegoing-1.12.2-1.12.13-237.jar
infinitetrading_1.12.2-1.4.jar
Infinity-0.14.2.jar
instgroups.json
ironchest_1.12.2_7.0.72.847.jar
jei_1.12.2-4.16.1.302.jar
journeymap-1.12.2-5.7.1.jar
Mantle-1.12-1.3.3.55.jar
Mekanism-1.12.2-9.8.3.390.jar
MekanismGenerators-1.12.2-9.8.3.390.jar
MekanismTools-1.12.2-9.8.3.390.jar
MicdoodleCore-1.12.2-4.0.2.280.jar
Minecraft-Comes-Alive-Mod-1.12.2.jar
mixinbooter-3.0.jar
MobBattleMod-1.12.2-2.3.4.jar
morechickens-1.12.2-3.2.0.jar
More-Planets-1.12.2-2.2.2-GC280.jar
MysticalAgradditions-1.12.2-1.3.2.jar
MysticalAgriculture-1.12.2-1.7.5.jar
mysticallib-1.12.2-1.13.0.jar
NaturesCompass-1.12.2-1.8.5.jar
NBTManipulator-1.12.2.006.jar
Neat 1.4-17.jar
NotEnoughItems-1.12.2-2.4.3.245-universal.jar
OpenBlocks-1.12.2-1.8.1.jar
OpenModsLib-1.12.2-0.12.2.jar
overloadedarmorbar-1.0.4g.jar
Patchouli-1.0-23.6.jar
ProjectE-1.12.2-PE1.4.1.jar
ProjectE-Integration-1.12.2-3.0.1.jar
ProjectEX-1.2.0.40.jar
ProjectIntelligence-1.12.2-1.0.9.28-universal.jar
PTRLib-1.0.5.jar
RadixCore-1.12.x-2.2.1-universal.jar
RedstoneFlux-1.12-2.1.1.1-universal.jar
roost-1.12.2-2.0.10.jar
ScalingHealth-1.12.2-1.3.42+147.jar
searchablechests-1.12-1.5.3-3.jar
SilentLib-1.12.2-3.0.14+168.jar
SolarFluxReborn-1.12.2-12.4.11.jar
spectrite-1.7.1.jar
SteveKunG's-Lib-1.12.2-1.1.11.jar
StorageDrawers-1.12.2-5.4.2.jar
TConstruct-1.12.2-2.13.0.183.jar
tesla-core-lib-1.12.2-1.0.18.jar
Thaumcraft_1.12.2_6.1.BETA26.jar
ThermalDynamics-1.12.2-2.5.6.1-universal.jar
ThermalExpansion-1.12.2-5.5.7.1-universal.jar
ThermalFoundation-1.12.2-2.6.7.1-universal.jar
tlskincape1.12.2-1.4.jar
twilightforest-1.12.2-3.11.1021-universal.jar
VanillaFix-1.0.10-150.jar
villagespawnpoint_1.12.2-1.8.jar
WailaHarvestability-mc1.12-1.1.12.jar
worldedit-forge-mc1.12.2-6.1.10-dist.jar
xray-1.12.2-1.6.0.jar
zerocore-1.12.2-0.1.2.9.jar

**Comment by ROMVoid95** [comment]
TLauncher is not supported
