### ISSUE TITLE
All planets got add with name of 2.0

### ISSUE THREAD

**Issue by Gokalpwave** [micdoodle8/Galacticraft#4100]
Hello guys i just update my galacticraft files to the newest with all mods and finished the compatibility settings new but when i got in the game and press M to see the galaxy map there was new galaxies cool but there is copy of all planets at my solar system named as Jupiter 2.0 Saturn 2.0 etc etc how do i fix that there is like 2x planets at my sol system rn

**Comment by ROMVoid95** [comment]
@Gokalpwave extraplanets adds the 2.0 to its planets to differ them from the same planet names that galaxyspace adds, so this is as intended.

**Comment by Gokalpwave** [comment]
> @Gokalpwave extraplanets adds the 2.0 to its planets to differ them from the same planet names that galaxyspace adds, so this is as intended.
sir i understand it but let me show you what chaos looks like 
![image](https://user-images.githubusercontent.com/104260687/164942672-5bc73b17-1804-4f77-87a6-ba4fe5ba1fe1.png)

**Comment by Gokalpwave** [comment]
is there any way to fix this thing

**Comment by MJRLegends** [comment]
Hey let me explain a bit more hopefuly it will help

Its like this to make Galaxyspace and ExtraPlanets work together, its the only way to get them working. The only other way would not not allowing these mods to be used together

Hope that helps.

**Comment by Gokalpwave** [comment]
> Hey let me explain a bit more hopefuly it will help
> 
> Its like this to make Galaxyspace and ExtraPlanets work together, its the only way to get them working and keep all features from both more working and able to be accessed.
> 
> The only other way would be not allowing these mods to be used together
> 
> Hope that helps.

Well i would like to thank to you for replying to me i see and i have no problem with that i just wondered the reason and i have my answer. I love what you guys create and want to thank again sir have a nice day
