### ISSUE TITLE
Galacticraft cannot launch

### ISSUE THREAD

**Issue by Gokalpwave** [micdoodle8/Galacticraft#4136]
I dont know why but i cant even launch minecraft rn with the mods i have. I tried to make them compatible with eachother but here is my crash log anyway:

******

*****
[crashlog.txt](https://github.com/micdoodle8/Galacticraft/files/13536832/crashlog.txt)

**Comment by ROMVoid95** [comment]
@Gokalpwave just giving a heads up that almost no mods will provide support when using a cracked Minecraft client/launcher
