### ISSUE TITLE
r1084 and earlier: Stars are drawn in front of the Sun and the Moon graphics

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#470]
This is an old visual glitch, the stars are drawn in front of the Sun and the Moon graphics. This is more noticeable when the sun is not full bright.

![2014-06-28_08 26 30](https://cloud.githubusercontent.com/assets/6743303/3420654/54cf4bd6-feb7-11e3-9ba5-cd25d043b64a.png)
![2014-06-28_08 28 06](https://cloud.githubusercontent.com/assets/6743303/3420655/54d10bb0-feb7-11e3-94da-b820e8b623b5.png)

**Comment by radfast** [comment]
This will (finally!) be fixed in the latest 3.0.9.

**Comment by EzerArch** [comment]
> This will (finally!) be fixed in the latest 3.0.9.

??? I thought it was a problem with vanilla code. Thank you very much!
