### ISSUE TITLE
Build 1085: Schematics disapearing in Nasa Workbench

### ISSUE THREAD

**Issue by JasonMcRay** [micdoodle8/Galacticraft#478]
From time to time added schematics to NASA Workbench disapear. Sometimes all added, sometimes only Moon Buggy, sometimes T2 rockets...

**Comment by Cronosus** [comment]
today this bug happened to one of my player.. all schematics from his workbench disappeared...

**Comment by ensirius** [comment]
Can confirm that we had today this issue with last GC build

**Comment by TheQuadShot** [comment]
@ensirius  @Cronosus Please provide more information. What version of Minecraft? Is it Forge or Sponge? What other mods are installed? Can you provide the logs?
