### ISSUE TITLE
Gravity Issue With Star Miner

### ISSUE THREAD

**Issue by JakXLT** [micdoodle8/Galacticraft#533]
I created a planet in a space station dimension using the Star Miner mod and found that the gravity seems to conflict with the mod a bit. There's no crashes or anything but I found that the star miner mod gravity only works on the sides and bottom of the planet, and when you try to go to the top of the planet it switches back to Galacticraft gravity.

I don't actually expect a fix for this since the mod is for 1.6.4 and is also from Japan so having a discussion with the mod dev might be difficult, and the mod also has it's own low earth orbit space dimension, however if there is a way to fix it PLEASE do so because, as far as making awesome GC space stations goes, this is it. This is THE mod to have... if the gravity didn't conflict.

**Comment by EzerArch** [comment]
Is this still relevant/an issue? BTW, 1.6 is 99% dead, in my opinion.

**Comment by SteveKunG** [comment]
+1 @EzerArch The mod doesn't update for a long time.

**Comment by kouwei32** [comment]
+1

**Comment by kouwei32** [comment]
This should be closed, it's been almost 4 years XD @radfast

**Comment by radfast** [comment]
hmm I guess we can, as we're never going to be able to fix this... :)

**Comment by EzerArch** [comment]
:fireworks: :fireworks: :fireworks:
