### ISSUE TITLE
Cargo Rocket Offset Landing Bug

### ISSUE THREAD

**Issue by AJ-Ferguson** [micdoodle8/Galacticraft#563]
When launching a Cargo Rocket with its destination set in the same dimension, the cargo rocket will "land" above the pad without actually touching it.

Video: http://www.youtube.com/watch?v=6iUwcNu1Uls

Setup:
Client + Server
Only mod installed is Galacticraft

**Comment by dj3520** [comment]
I'm just so happening to have this same issue with GC3.0.8.261.
![2015-02-12_03 00 08](https://cloud.githubusercontent.com/assets/8284194/6182538/de90d27a-b313-11e4-85ac-5710a7662ad2.png)

**Comment by EzerArch** [comment]
See  #1252.

**Comment by radfast** [comment]
Thanks for the screenshot, sorry it's taking us a while to get to this one.  I can reproduce this, though it's a little random.  Problem is that so far I have totally failed to find a reason for it.
