### ISSUE TITLE
Warp Drive Mod & Galacticraft Machinery

### ISSUE THREAD

**Issue by JakXLT** [micdoodle8/Galacticraft#586]
I've been playing with this mod and building a (rather extensive) star ship. I have found that after warping any distance, galacticraft machines seem to stop communicating with power and oxygen cables/pipes.

**Comment by radfast** [comment]
I will close this issue now, as we will not be updating 1.6.4 unless major bugs are found.

If similar "wiring stops working after moving my base" issues happen in 1.7.10, please can someone re-open or just make a new issue.  By "moving my base" I mean mods or plugins which can move a whole load of blocks together.

**Comment by radfast** [comment]
See also #3116 which looks like the same "moving my base" issue.
