### ISSUE TITLE
Launch to Space Station

### ISSUE THREAD

**Issue by Archervenom** [micdoodle8/Galacticraft#609]
When I go into space I would create a space station and click launch on it and nothing would happen. I have the 3.0.0.122. build

**Comment by XeMo97** [comment]
I can not create a space station, it does not show me the option to do so.
I'm using build 3.0.12.440 on a multiplayer server I'm hosting.

Any solutions?

**Comment by dj3520** [comment]
Screenshot? Also does this happen with the newest build, version 446?

**Comment by radfast** [comment]
Please provide:
* server log
* ```core.conf```

Please test your setup using latest GC build without any Galacticraft add-ons.  (Make a test world for this, changing mods or configs may damage any existing server world.)
