### ISSUE TITLE
Block go black when using Night vision potion in the asteroids dimension

### ISSUE THREAD

**Issue by JusticeOF666** [micdoodle8/Galacticraft#752]
![2014-08-01_15 49 28](https://cloud.githubusercontent.com/assets/7925899/3779491/b603f970-1982-11e4-919e-5f9b05427e95.png)
The complete black areas are block normally
![2014-08-01_15 50 48](https://cloud.githubusercontent.com/assets/7925899/3779501/dfdd9d82-1982-11e4-8e8e-f7989ae185ae.png)

**Comment by EzerArch** [comment]
Tested in r302 with minimal setup (no MCPatcher or mods), on NVIDIA GeForce GT 440. It's fixed, at least on my end.

![2015-03-28_17 17 41](https://cloud.githubusercontent.com/assets/6743303/6882729/6f2f9e70-d56e-11e4-8917-b6fdae10b7d1.png)

**Comment by SteveKunG** [comment]
![2559-01-20_01 03 04](https://cloud.githubusercontent.com/assets/6128413/12443201/cd1e20a6-bf88-11e5-8b0b-9029fd6c8438.png)

I can't reproduce in my eclipse development. (GeForce 9500 GT/PCIe/SSE2)

**Comment by radfast** [comment]
Working OK for me too, both with Optifine and without Optifine.

**Comment by C1ffisme** [comment]
I can confirm this. I use a night vision helmet from RotaryCraft, and it makes everything in the asteroids look black.

**Comment by radfast** [comment]
Thank you @C1ffisme

Which Galacticraft version, which Forge version, and are you using Optifine?

**Comment by radfast** [comment]
I think this should be fixed by build 428, [shortcut here](http://ci.micdoodle8.com/job/Galacticraft-1.7/428/).
