### ISSUE TITLE
GC3 r145: Player gets stuck on the floor on chunk load

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#784]
In dimensions G>1, the player gets stuck ~0.1 m in the floor, keeps bouncing up and down and can't move until he breaks the blocks beneath. It happens on chunk load by world load or death. As parallel effect, the player model loses the brightness and recovers it when gets unstuck.

This bug doesn't occur all the time and is barely noticeable on G=1 dimensions. This is an old bug that still persists.

How to reproduce:
1. Stand on a solid block;
2. Reload the world or die;
3. Once respawning, hit F5;
4. If the player model is dark, you managed to catch the bug;
5. Try to move.
5.a. On the Overworld, you will be able to move, walk 2 blocks, the player will be held for 1 tick and recover brightness.
5.a. On low gravity dimensions, you won't be able to move immediately most of times, you need to break the blocks to set you free.

Reproducible with and without mods. 

**Video:** http://www.twitch.tv/ezerarch/b/554600676 (I removed the bspkrsCore mod afterwards, still Reproducible)

**Comment by radfast** [comment]
Seems like this is still happening, on the Overworld at any rate.

I'm not sure whether this is an issue **caused** by Galacticraft but we can probably fix it.

**Comment by EzerArch** [comment]
As of today, I don't get this issue any more.

Safe to close?

**Comment by SteveKunG** [comment]
Testing with GC Build 467. This issue not longer happened.

**Comment by radfast** [comment]
Thanks guys, I'm happy to close this.
