### ISSUE TITLE
-------> OFFICIAL: KNOWN ISSUES IN LATEST BUILD <-------- *** Read first ! **

### ISSUE THREAD

**Issue by radfast** [micdoodle8/Galacticraft#791]
This is a list of known issues in the latest build of Galacticraft 3.  The latest build as of now is 3.0.8.259 which has full RF compatibility.  Get it here: http://micdoodle8.com/mods/galacticraft/downloads (the 'Latest' build in red)

_Posting new issues - guidelines:_
1.  When posting, always tell us your exact Galacticraft version.
2.  Please test it in the latest GC version, before posting your issue.
3.  Please do not re-post known issues.  It would be a good idea to do a _Search_ on Github (Issues not Code) to check your issue is not already posted in either Open or Closed issues.
4.  If reporting a crash, please _always_ post your full crash report, use Pastebin or similar to post it
5.  If reporting a mod conflict, we might ask you to do some testing to isolate which exact other mod is conflicting with GC.

Suggestions and Feature Requests belong on the official forum http://forum.micdoodle8.com/index.php?forums/suggestions.7/ - not on the Github.  (Exception: if you're a translator and it's a localization suggestion, then you can post your suggestion here.)

You can post comments and replies here but be warned they may become irrelevant as the known issues get fixed.  Irrelevant and off-topic comments _will be deleted_.

Compatibility
------------------
See also http://wiki.micdoodle8.com/wiki/Compatibility

*  GC energy Beam Receivers cannot pull power _out_ of other mods machines
*  Sealed IC2 cables are not working properly
*  Sealed Applied Energistics cables are not working properly

Old Buildcraft issues
----------------------------
There were a few issues with pre-current versions of Buildcraft, including EnderIO 2.0 and many other mods which include the Buildcraft API.  Latest versions of those other mods may fix it, also of course you should update Galacticraft to the latest.  More info: http://wiki.micdoodle8.com/wiki/Buildcraft and http://wiki.micdoodle8.com/wiki/Compatibility#Buildcraft_API

Space Stations
------------------
*  You cannot walk "up" stairs on a space station, you become stuck
*  You cannot go "down" ladders on a space station
*  Rotating Space Stations - blocks not connected to the space station will rotate as well
*  Mekanism Jetpack does not work in space
*  IC2 quantum chest-plate does not work in space
*  Sideways motion using 'A' and 'D' keys makes only a temporary change to your movement

Graphical and Rendering issues
-------------
* Footprints on the Moon sometimes hang off the edge of the block they are on
* Footprints on the Moon appear to 'jump' position around 1/2 second after first appearing
* Space dimension skies: Stars are visible 'behind' the sun and the moon #470

Sounds
-----------
*  Galacticraft music is not working

**Comment by radfast** [comment]
@skyboy 
>  That change to the API doesn't break old implementations

I can't 100% agree with that.  In practice now third party mods may be either using and distributing IEnergyHandler or using and distributing only IEnergyReceiver and/or IEnergyProvider, or distributing all three.  This is a pain for a network like us to implement.

This is what I have had to code to overcome this:
https://github.com/micdoodle8/Galacticraft/commit/7d8331bc47aee29c119685f59674e1e10585905b

(OK, an alternative solution could have been to distribute a full set of the RF API files ourselves but we do not like to distribute APIs - our mod is implementing compatibility with the RF API if present, but our mod is not itself dependent on the RF API.)

**Comment by skyboy** [comment]
@radfast Supporting both versions of the API is indeed painful, however that's not something that's intended either: The RF API was designed as an all-or-nothing system, where it's supported or not supported, rather than supported sometimes.

**Comment by radfast** [comment]
As a major mod and a network provider, we _have_ to support both versions, as we have no way to know which version the other mods installed alongside ours will use.

**Comment by Nick-77ab2** [comment]
The "jenkins" early build website is giving a 404 not found, is there a new one or something?

**Comment by radfast** [comment]
No, it's some kind of server issue.

There's this for emergencies, it's a couple weeks behind the latest version but better than nothing:
http://wiki.micdoodle8.com/wiki/DownloadTemp

**Comment by dj3520** [comment]
Confirmed 404 - http://ci.micdoodle8.com/
Apache 2 Test Page

**Comment by radfast** [comment]
Still down :(   I've emailed the relevant person, there's really nothing else we can do except wait.

**Comment by Nick-77ab2** [comment]
darn ok well think snow, just cus, you know ive only had one snow day all my school year, and it was in November :(

**Comment by dj3520** [comment]
The site is technically "working" by displaying the 404, but the files it serves are misplaced/non-existant. Essentially the server's been reset.

**Comment by Kodos-Atoz** [comment]
radfast, any way to build and use the repo's releases section to put out a version now and then in the mean time? I'm sure lots of folks would appreciate having builds with recent fixes and changes.

**Comment by radfast** [comment]
@dj3520  @Nick-77ab2 @Kodos-Atoz   The actual Downloads page http://micdoodle8.com/mods/galacticraft/downloads is still working, I test downloaded version 3.0.8.261 just now.

People who have a good reason for needing an earlier version (I can't imagine what that reason would be) will just have to be patient until the Jenkins is back up.  I can't make public builds myself either until the Jenkins is back up.  (That's not really a problem right now, because actually I'm working on a new feature which is still a few days from being ready for release.  You guys will like it when you see it :) )

**Comment by Kodos-Atoz** [comment]
Oh that's mean, now I'm excited lol.  Will have to keep an eye on commits and such for info =)

Unrelated; How come you're never in the IRC, radfast?  Really surprised you're not there more often. Kind of miss having micdoodle there, too.

**Comment by dj3520** [comment]
In the mean time you should clear up some space on the Jenkins machine. I've seen a few builds fail due to lack of disk space.

**Comment by radfast** [comment]
@Kodos-Atoz  I have limited time each day for coding Galacticraft and looking at issues.  If I spent some of that time on IRC then I would have even less time for coding.

@dj3520  the Jenkins machine is entirely outside my control, it's not even in micdoodle8's control.  I'm sure the people running it are aware of the diskspace issues.  Please don't complain about it, making the Galacticraft downloads available consumes a serious amount of bandwith (I estimate over 40TB since Galacticraft was first released back in 2013) and there's not many people would be willing to provide that to us at all.

**Comment by radfast** [comment]
Thanks to @EzerArch for pointing out to me that this link is still working fine: http://2.iongaming.org:8080/job/Galacticraft-1.7/

**Comment by Nick-77ab2** [comment]
its actually working now

**Comment by Nick-77ab2** [comment]
so yea just notifying ,or however you spell it, you

**Comment by dj3520** [comment]
@radfast I'm not nessasarily complaining about the lack of space. I just found it humorous it was the reason why some builds would fail. Perhaps a set about of space should be checked avalible before the build proceeds. If it isn't there, the oldest build should be deleted to make room. Surely I doubt all 1000+ builds of GC2 are still there...right? At least, if they are, they're compressed...right?

**Comment by dpsman917** [comment]
ops and players are getting  flying is not enabled when using space station flight.

the server.properties says flying true

does not happen if i am wearing an angel ring or have bat flight

i have checked google and changelogs and found nothing. is there somthing simple i am missing?
did not see it as a known issue
