### ISSUE TITLE
CustomNPCS incompatiblity

### ISSUE THREAD

**Issue by ghost** [micdoodle8/Galacticraft#831]
When CustomNPCS is installed, the "Factions" and "Quests" tabs sit on top of the Galacticraft tab for where you put in your space suit stuff.

Not sure who I need to talk to but theres no real support for customnpcs... so I hope you can help !!!

**Comment by EzerArch** [comment]
Noppes replied:

> I've tried looking for documentation about their api before. Found nothing so I passed. Also not really a bug more like a conflict.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1278956-custom-npcs?comment=19422

**Comment by radfast** [comment]
Thanks for raising the issue over there, @EzerArch, I have commented on Noppes' thread with coding details so that he can implement the Tinker's Construct system if he wants to.

**Comment by EzerArch** [comment]
You're welcome. BTW, he replied your post.
