### ISSUE TITLE
Hoppers and extractions with Arc furnace and Gas liquefier [GC3]

### ISSUE THREAD

**Issue by dj3520** [micdoodle8/Galacticraft#868]
- Electric Arc Furnace won't accept items piped/hoppered from sides. Top works fine.
- I don't know if this is intended, but Gas Liquefier cannot have items extracted via BC extraction pipes.
- Small bug, extended tooltip for buggy fuel pad is same as rocket pad.
  ![buggy-pad-tooltip-bug](https://cloud.githubusercontent.com/assets/8284194/3945723/45f5db4c-264f-11e4-9bcb-8c63e8075a9c.png)

**Comment by chezpaul** [comment]
I know this is closed. I found this thread through google.
But there is no fuel fluid output on the Gas Liquefier.
How can I output Fuel with a Buildcraft fluid pipe?

**Comment by dj3520** [comment]
Opposite the input side is the first tank's output. I can't remember off
the top of my head but either the front or back of the machine acts as the
second tank's output, whichever the pipe connects to. Usual wood or emerald
fluid extraction pipe powered by redstone engine, autoauric (spelled that
one wrong) gate, or possibly the power adapter.
