### ISSUE TITLE
Render Sleeping

### ISSUE THREAD

**Issue by BlesseNtumble** [micdoodle8/Galacticraft#897]
GC build 175
Server Cauldron 
Client 1.7.10

Screenshot:
http://firepic.org/images/2014-08/23/xlku6eigsm8l.png

**Comment by TheJulianJES** [comment]
New info?

**Comment by TheJulianJES** [comment]
@radfast It only happens if your FOV is higher than 100.

**Comment by radfast** [comment]
Thank you for that extra info, maybe it will help me to find a solution now!
