### ISSUE TITLE
[Optifine]  Player face icon missing from rocket HUD

### ISSUE THREAD

**Issue by BlesseNtumble** [micdoodle8/Galacticraft#979]
Missing texture Player in all 3 Rockets
Screen: http://6.firepic.org/6/images/2014-09/11/c5tpfemvwght.png

Build 185
Client 1.7.10

**Comment by radfast** [comment]
I am not seeing this issue in any of my recent testing with Optifine, seems like either GC or Optifine has fixed it as a consequence of fixing something else - it was most likely connected with an OpenGL state issue.

I'll close this in around 1 day unless anyone can confirm this is still an issue in latest GC builds (428 and later).

**Comment by EzerArch** [comment]
My reply to another issue kind of confirms this as closed: https://github.com/micdoodle8/Galacticraft/issues/1565#issuecomment-172390145 (see Results/With Optifine)

**Comment by EzerArch** [comment]
You might want to close this issue. Confirmed: https://github.com/micdoodle8/Galacticraft/issues/1565#issuecomment-177413036 and https://github.com/micdoodle8/Galacticraft/issues/1565#issuecomment-177559855.

**Comment by radfast** [comment]
Thank you @EzerArch .  Your word is my command :p
